### PR TITLE
Fix fairsharing reclamation bug

### LINKED ISSUE #6577: Fairsharing bug that prevents CQs from reclaiming guarantees
**What happened**: 
We noticed an increase in guarantee violations when fairsharing is turned on where CQs are unable to reclaim their guarantees when preemption is required despite having guarantees.

There were a lot of logs that said...
- `Workload requires preemption, but there are no candidate workloads allowed for preemption` 
- `couldn't assign flavors to pod set foo: insufficient unused quota for nvidia.com/gpu in flavor bar, 5 more needed`. 
  - This cluster also only has 1 flavor.

**What you expected to happen**:
Cqs need to be able to reclaim guarantees. 

**How to reproduce it (as minimally and precisely as possible)**:
We detect this in production and don't know how to repro. But it occurs multiple times in production. 

**Anything else we need to know?**:
Here is a theory:

We do hit these logs: `logV.Info("Simulating fair preemption", "candidates", workload.References(candidates), "resourcesRequiringPreemption", preemptionCtx.frsNeedPreemption.UnsortedList(), "preemptingWorkload", klog.KObj(preemptionCtx.preemptor.Obj))`

* `candidates` is heavily populated within our logs (meaning at some point it had a lot of preemption candidates)

Tracing the code, here is our theory:
1. `fairPreemptions(...)`
2. `logV.Info("Simulating fair preemption", "candidates", workload.References(candidates), ...)`
    1. we do see a lot of candidates here in the logs but later down return no preemption candidates
3. This means `fits` within `fits, targets, retryCandidates := runFirstFsStrategy(preemptionCtx, candidates, strategies[0])` is probably false. Why?

It could be this...
1. `workloadFits()` checks...
```
if v > preemptionCtx.preemptorCQ.Available(fr) {
    return false
} 
// v is resources preemptor workload needs for flavor
// "Available returns the current capacity available, before preempting any workloads"
```
2. `Available` → `available` → `LocalAvailable`
3. `LocalAvailable` returns `guaranteedQuota() - Usage[fr]`

The issue is probably here:
```
func (r resourceNode) guaranteedQuota(fr resources.FlavorResource) int64 {
    if lendingLimit := r.Quotas[fr].LendingLimit; lendingLimit != nil {
        return max(0, r.SubtreeQuota[fr]-*lendingLimit)
    }
    return 0
}
```
1. `guaranteedQuota` isn’t actually returning you guaranteed quota. Its basing the calculation off lendingLimit... which... we do not set. 
2. `LendingLimit == nil` → `return 0`

SO. Back to this:
1. 
```
if v > preemptionCtx.preemptorCQ.Available(fr) {
        return false
}
 ```
2. v > 0 → return false
3. ❌ fails fit check

---
⭐️ Other supporting evidence: This could explain this! https://github.com/kubernetes-sigs/kueue/issues/6219
`Reclamation disappeared as a preemption reason after turning on fairshare`

**Environment**:
- Kueue version (use `git describe --tags --dirty --always`): 0.12.2

### PR DESCRIPTION
**Pull request by pajakd**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When there are large values of quotas and (especially) fair weights, the rounding in DRS calculation causes the returned value to sometimes be 0 for borrowing CQs.  

With this PR I would like to make sure that any borrowing CQ gets DRS of at least 1. As expressed in the comment https://github.com/kubernetes-sigs/kueue/blob/6c61dda233c15975247f6338c5c745c976716541/pkg/cache/fair_sharing.go#L41-L48 `If zero, it means that the usage of the ClusterQueue is below the nominal` -- this PR is enforcing this rule. It was previously violated as all of the testcases added to this PR are failing without the fix.

This PR in my opinion should fix #6577 

#### Which issue(s) this PR fixes:

Part of #6577

#### Does this PR introduce a user-facing change?

```release-note
FS: Fixing a bug where a preemptor ClusterQueue was unable to reclaim its nominal quota when the preemptee ClusterQueue can borrow a large number of resources from the parent ClusterQueue / Cohort
```

### CODE REVIEW

File: pkg/cache/fair_sharing.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func dominantResourceShare(node dominantResourceShareNode, wlReq resources.Flavo
 	}
 
 	dws := drs * 1000 / node.fairWeight().MilliValue()
-	return int(dws), dRes
```
Comment (amy) [inline pkg/cache/fair_sharing.go:85]: I need to check with the team. But... I think we could depend on these very small differences in fractional values. Is there a reason DWS and DRS need to be int and not float64?

Comment (pajakd) [reply pkg/cache/fair_sharing.go:85]: With this PR I only want to fix the most basic thing: "CQ can always reclaim its nominal quota".

Large values of fairWeights are also causing another issue: "integer DWS cannot capture the small differences in fractional values". A fix for that one would be more involved (changing the type or some smart normalization) and I'd like to discuss that with @gabesaba 

But this PR should not break anything as currently the value is int and this PR is only changing from 0 to 1 sometimes.

Comment (PBundyra) [reply pkg/cache/fair_sharing.go:85]: Please note that the value is also used in FairSharing API `.WeightedShare` field. If we decided to change the type it would either mean we need to change the API, or the field doesn't accurately represent CQ/Cohort's state

Comment (rajatphull) [reply pkg/cache/fair_sharing.go:85]: As per the function header, If the returned value is zero, it indicates that the ClusterQueue’s usage is below its nominal quota. However, since the change never returns 0 then how does this align with the stated constraint?

Comment (amy) [reply pkg/cache/fair_sharing.go:85]: A few additional things to consider:
1. The rounding issue is both drs and dws (ie not just dws)
2. Yeah let's discuss float64. If there's a tournament where everything is close and ends up with 1, the tiebreaker is something that's not quota
3. +1 to what @rajatphull said. Would this incorrectly set the real reclaiming CQ to 1 instead of 0? 

The rounding down error is twofold:
Scenario 1: lets say we have a world where no CQ weights are set, if something is borrowing a small amount of quota proportional to the cohort size. 
Scenario 2: Where CQ weights are set, if something has a large weight + borrowing a small amount proportional to the weight and cohort size.

Comment (amy) [reply pkg/cache/fair_sharing.go:85]: @pajakd @PBundyra Would like to understand:
1. If there's context to why the field was set as int? (no worries if there is none. Just want to make sure I'm not missing anything.)
2. Could I get a link to the large fs weight issue?

File: pkg/cache/fair_sharing.go [hunk 2]
```diff
@@ -82,7 +82,7 @@ func dominantResourceShare(node dominantResourceShareNode, wlReq resources.Flavo
...
+	return max(1, int(dws)), dRes
```
Comment (tenzen-y) [inline pkg/cache/fair_sharing.go:85]: @pajakd @PBundyra This change looks like a slightly aggressive change. IIUC, we no longer prune workloads from preemption targets after this change. So, I think that we should not apply this change by default.

Ideally, we should dynamically change the current scale (1000) in `ratio := b * 1000 / lr` considering the lendable and resource units. The reason for considering the resource Unit is that it 1 has a different importance between cpu and devices (e.g., nvidia.com/gpu, mellanox.com/connectx_8).

But, if @rajatphull or @amy want to ship immidiatelly this aggressive starategy for the short-term approach, I'm ok with that.
In that case, we should introduce the deprecated FG, then it should be disabled by default.

Comment (amy) [reply pkg/cache/fair_sharing.go:85]: The fix also is a maybe a bug? See: `#3` https://github.com/kubernetes-sigs/kueue/pull/6617#discussion_r2285927234

File: pkg/cache/fair_sharing.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/cache/fair_sharing.go:85]: @amy 

> If there's context to why the field was set as int? (no worries if there is none. Just want to make sure I'm not missing anything.)

I think that the reason is avoiding friction for preemption. The current rounding strategy (integer) could represent almost the same DWS, which could help to reduce high-frequency preemptions. But, the float64 no longer represents almost the same DWS, which will introduce the preemption storm in some clusters 😓 

So, I would like to select the normarization and keeping integer rather than float64.

> Could I get a link to the large fs weight issue?

This one: https://github.com/kubernetes-sigs/kueue/issues/4247. We are planning to mention the notifications in documents and add some validations.

File: pkg/cache/fair_sharing.go (hunk 2 above)
Comment (amy) [reply pkg/cache/fair_sharing.go:85]: This could also introduce a new bug. See: `#3` https://github.com/kubernetes-sigs/kueue/pull/6617#discussion_r2285927234

Comment (tenzen-y) [reply pkg/cache/fair_sharing.go:85]: > This could also introduce a new bug. See: `#3` [#6617 (comment)](https://github.com/kubernetes-sigs/kueue/pull/6617#discussion_r2285927234)

Yes. So, I called this as a slightly aggressive approach and guard this behind deprecated FG for short-term solution. After we implement the golden strategy, we will remove the deprecated FG.

Comment (tenzen-y) [reply pkg/cache/fair_sharing.go:85]: So, if you feel that additional problems caused by this new strategy are not acceptable, we do not need to introduce this new strategy.

File: pkg/cache/fair_sharing.go (hunk 1 above)
Comment (amy) [reply pkg/cache/fair_sharing.go:85]: @tenzen-y Not quite following this: `the float64 no longer represents almost the same DWS, which will introduce the preemption storm in some clusters`

Let's specifically talk about the tournament in the case where the entire tournament tree is borrowing. What happens with float64 vs. int? This is my guess:
- with float64: the tournament winner and remaining CQs that are not pruned would frequently change. Whereas if its int, if the shares are close, there's something more deterministic like timestamps or priority as tiebreaker, which would cause less preemption churn?

File: pkg/cache/fair_sharing.go (hunk 2 above)
Comment (amy) [reply pkg/cache/fair_sharing.go:85]: With `max(1, int(dws))`, everything is effectively fairshare. And there are no guarantee reclamations. This is because pruning prunes CQs with 0 value. So now everything is fair game to be considered as a preemption candidate. 

So yeah, lets think through a longer term fix or a different short term fix. We have mitigation strategies today we can continue using.

File: pkg/cache/fair_sharing.go (hunk 1 above)
Comment (PBundyra) [reply pkg/cache/fair_sharing.go:85]: > As per the function header, If the returned value is zero, it indicates that the ClusterQueue’s usage is below its nominal quota. However, since the change never returns 0 then how does this align with the stated constraint?

The code responsible for returning 0 when the usage is below nominal quota is still here: https://github.com/kubernetes-sigs/kueue/pull/6617/files#diff-e822642151fb9037f5ada06309828ea5c2ecb4a3cb9619ae445ce138622511a4R62

File: pkg/cache/fair_sharing.go (hunk 2 above)
Comment (PBundyra) [reply pkg/cache/fair_sharing.go:85]: As mentioned here: https://github.com/kubernetes-sigs/kueue/pull/6617#discussion_r2286155669
We would still have an if branch that returns 0 if the usage is below nominal quota so we would keep pruning

File: pkg/cache/fair_sharing.go (hunk 1 above)
Comment (amy) [reply pkg/cache/fair_sharing.go:85]: @PBundyra missed that 🤦🏻‍♀️, thanks! 

Okay. In that case, here's the remaining items in this thread:
1. Make sure `drs` also doesn't round down (not just dws) here: `ratio := b * 1000 / lr`.
2. Help me understand the preemption storm for float64: https://github.com/kubernetes-sigs/kueue/pull/6617#discussion_r2286101829

Comment (tenzen-y) [reply pkg/cache/fair_sharing.go:85]: > 1. Make sure drs also doesn't round down (not just dws) here: ratio := b * 1000 / lr.

We compute the final share with `MAX(1, dws)`. So, `0` is no longer an effective value for returning a value.
Even if lendableResources or fairWeight is a large number, then drs will be 0, the final share must be `1`

> 2. Help me understand the preemption storm for float64

In the `LessThanInitialShare` mode, we compute the fairness with `preemptorNewShare < targetOldShare`. So, if we distinguish between 1.1 and 1.2 (for example), additional Preemptions could happen in some cases.
The current computation with integer share value will not occur preemption (e.g., `1(.1) == 1(.2)`).

So, I still urge to introduce the normalization and keep integer typed.

File: pkg/cache/fair_sharing.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/cache/fair_sharing.go:85]: @PBundyra Good point, I was missing the line. Thank you for calling that.
In that case, this change works well.

As a side effect, even when the HRN has a large borrowable resource (= parentHRN has a large lendable resource), fair sharing will be enforced after this PR. But I think that is expected behavior.

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
FS: Fixing a bug where a preemptor ClusterQueue was unable to reclaim its nominal quota when the preemptee ClusterQueue can borrow a large number of resources from the parent ClusterQueue / Cohort
```

**Review by tenzen-y — COMMENTED** [review]
@pajakd @PBundyra Thank you!
/lgtm
/approve

**Comment by amy** [comment]
/hold cancel

Sorry, just wanted to trace the code before we merged. (was worried about new bugs, but I agree that's not the case) To confirm, I see this at the top:
```
	if len(borrowing) == 0 {
		return 0, ""
	}
```
So...
✅ if not borrowing, we're still able to reclaim guarantees
✅ if borrowing, all fractional values are rounded to 1

Thanks for bearing with me as I understand this code! 

/approve
/lgtm

File: pkg/cache/fair_sharing.go (hunk 1 above)
Comment (amy) [reply pkg/cache/fair_sharing.go:85]: Thanks for the explanation!

**Comment by amy** [comment]
@tenzen-y please tag me when the patch including this is cut. 🙏

**Comment by tenzen-y** [comment]
> @tenzen-y please tag me when the patch including this is cut. 🙏

Sure.
