### PR TITLE
Fix transitions of Requeued condition

### LINKED ISSUE #2038: Fix transitions of Requeued condition
The `Requeued` condition should transition to `False` in the following scenarios:

- When workload.spec.active=false. It should return to True when it's reactivated.
- When evicted due to WaitForPodsReady, the workload will temporarily be in backoff. During this time, Requeued should be false.

As per [comment](https://github.com/kubernetes-sigs/kueue/pull/1977#discussion_r1574949456).

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
- fixed Requeued condition transition on activate/deactivate workload
- fixed Requeued condition transition on WaitForPodsReady

#### Which issue(s) this PR fixes:
Fixes #2038 

#### Does this PR introduce a user-facing change?
```release-note
Fix transitions of Requeued condition.
```

### CODE REVIEW

File: pkg/controller/core/workload_controller.go [hunk 1]
```diff
@@ -165,10 +165,37 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
+
+		// If a deactivated workload is re-activated we need to reset the RequeueState.
+		if workload.IsEvictedByDeactivation(&wl) && wl.Status.RequeueState != nil {
+			wl.Status.RequeueState = nil
+			updated = true
+		}
+
+		// If a deactivated workload is re-activated we need to set the WorkloadRequeued condition to true if already unset.
+		if workload.IsUnsetRequeuedByDeactivation(&wl) {
+			workload.SetRequeuedCondition(&wl, "ReactivateWorkload", "The workload is reactivated")
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go]: Added

**Comment by alculquicondor** [comment]
cc @mimowo

File: pkg/workload/workload.go [hunk 2]
```diff
@@ -572,6 +586,15 @@ func IsEvictedByPodsReadyTimeout(w *kueue.Workload) (*metav1.Condition, bool) {
 	return cond, true
 }
 
+// IsUnsetRequeuedByPodsReadyTimeout returns true if the workload is unset requeued by pods ready timeout.
+func IsUnsetRequeuedByPodsReadyTimeout(w *kueue.Workload) (*metav1.Condition, bool) {
+	cond := apimeta.FindStatusCondition(w.Status.Conditions, kueue.WorkloadRequeued)
+	if cond == nil || cond.Status != metav1.ConditionFalse || cond.Reason != kueue.WorkloadEvictedByPodsReadyTimeout {
+		return nil, false
+	}
+	return cond, true
```
Comment (mimowo) [inline pkg/workload/workload.go:595]:
```suggestion
	return cond != nil && cond.Status == metav1.ConditionFalse && cond.Reason == kueue.WorkloadEvictedByPodsReadyTimeout
```
as above, much easier to read

File: pkg/controller/core/workload_controller.go [hunk 3]
```diff
@@ -165,10 +165,37 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
+		if workload.IsUnsetRequeuedByDeactivation(&wl) {
+			workload.SetRequeuedCondition(&wl, kueue.WorkloadRequeuedByReactivation, "The workload is reactivated")
+			updated = true
+		}
+
+		// Wait for requeueAt and set the WorkloadRequeued condition to true.
+		if condition, isUnset := workload.IsUnsetRequeuedByPodsReadyTimeout(&wl); condition != nil && isUnset {
+			var requeueAfter time.Duration
+			if wl.Status.RequeueState != nil && wl.Status.RequeueState.RequeueAt != nil {
+				requeueAfter = time.Until(wl.Status.RequeueState.RequeueAt.Time)
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:187]: Compute the time using the r.clock. should be available on the main branch. It allows us to use fakeClock for testing.

File: pkg/controller/jobs/job/job_controller_test.go [hunk 4]
```diff
@@ -668,6 +668,326 @@ func TestReconciler(t *testing.T) {
...
+			wantEvents: []utiltesting.EventRecord{
+				{
+					Key:       types.NamespacedName{Name: "job", Namespace: "ns"},
+					EventType: "Normal",
+					Reason:    "Stopped",
+					Message:   "At least one admission check is false",
+				},
+			},
+		},
+		"when workload is evicted due to cluster queue stopped, job gets suspended": {
```
Comment (mimowo) [inline pkg/controller/jobs/job/job_controller_test.go:831]: Thanks for adding this scenario for completeness. I'm wondering if this is not a scenario that we missed, and we should also say Requeued=false here. Then, set Requeued=true when the CQ is no longer stopped. WDYT @alculquicondor ?

File: apis/kueue/v1beta1/workload_types.go [hunk 5]
```diff
@@ -329,6 +329,12 @@ const (
 	WorkloadEvictedByDeactivation = "InactiveWorkload"
 )
 
+const (
+	// WorkloadRequeuedByReactivation indicates that the workload was requeued
+	// because spec.active is set to true.
+	WorkloadRequeuedByReactivation = "ReactivateWorkload"
```
Comment (mimowo) [inline apis/kueue/v1beta1/workload_types.go:335]:
```suggestion
	WorkloadReactivated = "WorkloadReactivated"
```
It is a `reason`. It will be clear that it is `Requeued` from the condition type.

File: apis/kueue/v1beta1/workload_types.go [hunk 6]
```diff
@@ -329,6 +329,12 @@ const (
 	WorkloadEvictedByDeactivation = "InactiveWorkload"
 )
 
+const (
```
Comment (mimowo) [inline apis/kueue/v1beta1/workload_types.go:332]: nit: put together with other workload reasons

**Review by mimowo — COMMENTED** [review]
LGTM overall, I'm yet wondering if we handle properly QueueStopped scenario.

File: pkg/workload/workload.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/workload/workload.go]: Done

File: pkg/controller/core/workload_controller.go (hunk 3 above)
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go]: Done

File: apis/kueue/v1beta1/workload_types.go (hunk 5 above)
Comment (mbobrovskyi) [reply apis/kueue/v1beta1/workload_types.go]: Done

File: apis/kueue/v1beta1/workload_types.go (hunk 6 above)
Comment (mbobrovskyi) [reply apis/kueue/v1beta1/workload_types.go]: Done

File: apis/kueue/v1beta1/workload_types.go [hunk 7]
```diff
@@ -327,6 +327,10 @@ const (
 	// WorkloadEvictedByDeactivation indicates that the workload was evicted
 	// because spec.active is set to false.
 	WorkloadEvictedByDeactivation = "InactiveWorkload"
+
+	// WorkloadReactivated indicates that the workload was requeued because
+	// spec.active is set to true after deactivation.
+	WorkloadReactivated = "WorkloadReactivated"
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply apis/kueue/v1beta1/workload_types.go]: Fixed

File: pkg/controller/core/workload_controller.go [hunk 8]
```diff
@@ -152,10 +152,37 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 	ctx = ctrl.LoggerInto(ctx, log)
 	log.V(2).Info("Reconciling Workload")
 
-	// If a deactivated workload is re-activated, we need to reset the RequeueState.
-	if wl.Status.RequeueState != nil && ptr.Deref(wl.Spec.Active, true) && workload.IsEvictedByDeactivation(&wl) {
-		wl.Status.RequeueState = nil
-		return ctrl.Result{}, workload.ApplyAdmissionStatus(ctx, r.client, &wl, true)
+	if ptr.Deref(wl.Spec.Active, true) {
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:155]: I'm thinking we should move this block below L188 (handling of deletion), and maybe even L192 (handling of workload finished). The reason being, that now we handle here PodsReadyTimeout, and this may result in waiting potentially arbitrarily long for requeue, the waiting times grow exponentially like 10s, 20s, 40s... . 

However, it is possible a user deletes the workload in the meanwhile, and we are not able to remove finalizer, and we unnecessarily wait for the requeue. Similarly, a user may mark the workload as finished. 

Could you check if this is the case, then please fix (not highest priority, so could be follow up), plus add a test?

File: pkg/controller/jobs/job/job_controller_test.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/controller/jobs/job/job_controller_test.go:831]: Yes, it should be similar to setting Active=false on the workload.

File: pkg/controller/core/workload_controller.go (hunk 8 above)
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go:163]: Yes, you right. Moved it and added tests.

File: pkg/controller/jobs/job/job_controller_test.go (hunk 4 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/job/job_controller_test.go:831]: Added this logic.

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 9]
```diff
@@ -1775,6 +1775,38 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler", ginkgo.Orde
 			wll.Spec.Active = ptr.To(false)
 			gomega.Expect(k8sClient.Update(ctx, wll)).Should(gomega.Succeed())
 
+			gomega.Eventually(func(g gomega.Gomega) {
```
Comment (alculquicondor) [inline test/integration/controller/jobs/job/job_controller_test.go:1778]: Also add similar validations for existing integration tests for PodsReadyTimeout.

I'm interested to see the whole transition from Admitted, to Evicted (Requeued=false), and then Requeue=True.

IIRC, it should be feasible to control the time passing from the test (without using time.Sleep)

File: pkg/controller/core/workload_controller_test.go [hunk 10]
```diff
@@ -549,7 +549,7 @@ func TestReconcile(t *testing.T) {
 				RequeueState(ptr.To[int32](4), ptr.To(metav1.NewTime(testStartTime.Add(80*time.Second).Truncate(time.Second)))).
 				Obj(),
 		},
-		"deactivated workload": {
+		"deactivate workload by reached re-queue backoffLimitCount": {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller_test.go:552]: For this case no. Because deactivation handling on ReconcileGenericJob and unit test don't cover it.

File: pkg/controller/core/workload_controller_test.go [hunk 11]
```diff
@@ -590,6 +590,92 @@ func TestReconcile(t *testing.T) {
...
+				Active(true).
+				Condition(metav1.Condition{
+					Type:    kueue.WorkloadRequeued,
+					Status:  metav1.ConditionTrue,
+					Reason:  kueue.WorkloadReactivated,
+					Message: "The workload is reactivated",
+				}).
+				Obj(),
+		},
+		"should check the WorkloadRequeued condition on pods ready timeout": {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller_test.go:613]: Yes, correct.

File: pkg/controller/core/workload_controller_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/core/workload_controller_test.go:552]: Then we should cover this in integration. There should be a test for it, we just need to add the checks for the conditions.

File: apis/kueue/v1beta1/workload_types.go [hunk 12]
```diff
@@ -327,6 +327,18 @@ const (
...
+	// spec.active is set to true after deactivation.
+	WorkloadReactivated = "Reactivated"
+
+	// WorkloadBackoffFinished indicates that the workload was requeued because
+	// backoff finished.
+	WorkloadBackoffFinished = "BackoffFinished"
+
+	// WorkloadClusterQueueStarted indicates that the workload was requeued because
+	// cluster queue started.
+	WorkloadClusterQueueStarted = "ClusterQueueStarted"
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply apis/kueue/v1beta1/workload_types.go]: Done

File: pkg/controller/core/workload_controller.go [hunk 13]
```diff
@@ -166,9 +160,52 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
+		var updated bool
+
+		// If a deactivated workload is re-activated we need to reset the RequeueState.
+		if workload.IsEvictedByDeactivation(&wl) && wl.Status.RequeueState != nil {
+			wl.Status.RequeueState = nil
+			updated = true
+		}
+
+		// If a deactivated workload is re-activated we need to set the WorkloadRequeued condition to true.
+		if workload.IsUnsetRequeuedByDeactivation(&wl) {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go]: Done

File: pkg/controller/core/workload_controller_test.go [hunk 14]
```diff
@@ -590,6 +590,92 @@ func TestReconcile(t *testing.T) {
...
+				Condition(metav1.Condition{
+					Type:    kueue.WorkloadRequeued,
+					Status:  metav1.ConditionFalse,
+					Reason:  kueue.WorkloadEvictedByPodsReadyTimeout,
+					Message: "Exceeded the PodsReady timeout ns",
+				}).
+				RequeueState(ptr.To[int32](1), ptr.To(metav1.NewTime(testStartTime.Add(60*time.Second).Truncate(time.Second)))).
+				Obj(),
+		},
+		"should set the WorkloadRequeued condition to true on pods ready timeout": {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller_test.go]: Done

File: pkg/workload/workload.go [hunk 15]
```diff
@@ -577,6 +585,24 @@ func IsEvictedByPodsReadyTimeout(w *kueue.Workload) (*metav1.Condition, bool) {
 	return cond, true
 }
 
+// IsUnsetRequeuedByDeactivation returns true if the workload is unset requeued by deactivation.
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/workload/workload.go]: Done

File: pkg/controller/jobs/job/job_controller_test.go [hunk 16]
```diff
@@ -668,6 +668,326 @@ func TestReconciler(t *testing.T) {
...
+						State: kueue.CheckStateReady,
+						PodSetUpdates: []kueue.PodSetUpdate{
+							{
+								Name: "main",
+								Labels: map[string]string{
+									"ac-key": "ac-value",
+								},
+							},
+						},
+					}).
```
Comment (tenzen-y) [inline pkg/controller/jobs/job/job_controller_test.go:698]: I guess that this admission check is irrelevant in this case, right?
If so, could you eliminate this admissionCheck?

File: pkg/controller/jobs/raycluster/raycluster_controller_test.go [hunk 17]
```diff
@@ -328,7 +328,6 @@ func TestReconciler(t *testing.T) {
 					Condition(metav1.Condition{
 						Type:               kueue.WorkloadRequeued,
 						Status:             metav1.ConditionTrue,
-						Reason:             "Pending",
```
Comment (tenzen-y) [inline pkg/controller/jobs/raycluster/raycluster_controller_test.go:331]: Why is this reason empty?

File: pkg/workload/workload.go [hunk 18]
```diff
@@ -394,6 +390,18 @@ func SetRequeuedCondition(wl *kueue.Workload, reason string, message string) {
...
+func UnsetRequeuedCondition(wl *kueue.Workload, reason string, message string) {
+	condition := metav1.Condition{
+		Type:               kueue.WorkloadRequeued,
+		Status:             metav1.ConditionFalse,
+		Reason:             reason,
+		Message:            api.TruncateConditionMessage(message),
+		ObservedGeneration: wl.Generation,
+	}
+	apimeta.SetStatusCondition(&wl.Status.Conditions, condition)
+}
```
Comment (tenzen-y) [inline pkg/workload/workload.go:403]: Could you commonize the `SetRequeuedCondition` and the `UnSetRequeuedCondition` functions?
Also, could you re-title the `UnSetRequeuedCondition` to something like the `DisabledRequeuedCondition` since the `UnsetRequeuedCondition` never unset the `Requeued` condition?
@alculquicondor WDYT about the function name, `DisabledRequeuedCondition`? Any recommended name?

```golang
func SetRequeuedCondition(wl *kueue.Workload, reason, message string) {
	updateRequeuedCondition(wl, reason, message, metav1.ConditionTrue)
}

func DisableRequeuedCondition(wl *Workload, reason, message string) {
	updateRequeuedCondition(wl, reason, message, metav1.ConditionFalse)
}

func updateRequeuedCondition(wl *Workload, reason, message string, status metav1.ConditionStatus) {
	condition := metav1.Condition{
		Type:               kueue.WorkloadRequeued,
		Status:             status,
		Reason:             reason,
		Message:            api.TruncateConditionMessage(message),
		ObservedGeneration: wl.Generation,
	}
	apimeta.SetStatusCondition(&wl.Status.Conditions, condition)
}
```

File: pkg/workload/workload.go [hunk 19]
```diff
@@ -577,6 +585,12 @@ func IsEvictedByPodsReadyTimeout(w *kueue.Workload) (*metav1.Condition, bool) {
 	return cond, true
 }
 
+// IsUnsetRequeuedByClusterQueueStopped returns true if the workload is unset requeued by cluster queue stopped.
+func IsUnsetRequeuedByClusterQueueStopped(w *kueue.Workload) bool {
```
Comment (tenzen-y) [inline pkg/workload/workload.go:589]:
```suggestion
func IsDisabledRequeuedByClusterQueueStopped(w *kueue.Workload) bool {
```

I mentioned above, could we re-title this function name to smoothing like `disable`?

File: pkg/controller/core/workload_controller.go [hunk 20]
```diff
@@ -166,9 +160,52 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
+
+		// Wait for requeueAt and set the WorkloadRequeued condition to true.
+		if workload.IsUnsetRequeuedByPodsReadyTimeout(&wl) {
+			var requeueAfter time.Duration
+			if wl.Status.RequeueState != nil && wl.Status.RequeueState.RequeueAt != nil {
+				requeueAfter = wl.Status.RequeueState.RequeueAt.Time.Sub(r.clock.Now())
+			}
+			if requeueAfter > 0 {
+				return reconcile.Result{RequeueAfter: requeueAfter}, nil
+			}
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go]: Should we reset the `RequeueState` on this case?

File: pkg/controller/jobs/raycluster/raycluster_controller_test.go (hunk 17 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/raycluster/raycluster_controller_test.go:331]: On the request we are using abstract (without Reason and Message) evicted condition. So thats why on result we get it empty. I will set `WorkloadEvictedByDeactivation`.

File: pkg/controller/core/workload_controller_test.go [hunk 21]
```diff
@@ -590,6 +590,92 @@ func TestReconcile(t *testing.T) {
...
+			workload: utiltesting.MakeWorkload("wl", "ns").
+				Active(true).
+				Condition(metav1.Condition{
+					Type:    kueue.WorkloadRequeued,
+					Status:  metav1.ConditionFalse,
+					Reason:  kueue.WorkloadEvictedByPodsReadyTimeout,
+					Message: "Exceeded the PodsReady timeout ns",
+				}).
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller_test.go:643]: Done

File: test/integration/controller/core/workload_controller_test.go [hunk 22]
```diff
@@ -452,4 +448,144 @@ var _ = ginkgo.Describe("Workload controller", ginkgo.Ordered, ginkgo.ContinueOn
...
+
+			ginkgo.By("deleting the workload", func() {
+				gomega.Expect(k8sClient.Delete(ctx, &createdWl)).To(gomega.Succeed())
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, wlKey, &createdWl)).ToNot(gomega.Succeed())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+		})
+
+		ginkgo.It("should handle the workload finished", func() {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply test/integration/controller/core/workload_controller_test.go]: Moved to unit tests.

File: test/integration/controller/core/workload_controller_test.go [hunk 23]
```diff
@@ -452,4 +448,144 @@ var _ = ginkgo.Describe("Workload controller", ginkgo.Ordered, ginkgo.ContinueOn
...
+			gomega.Expect(k8sClient.Create(ctx, localQueue)).To(gomega.Succeed())
+		})
+
+		ginkgo.AfterEach(func() {
+			gomega.Expect(util.DeleteNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
+			util.ExpectClusterQueueToBeDeleted(ctx, k8sClient, clusterQueue, true)
+			util.ExpectResourceFlavorToBeDeleted(ctx, k8sClient, flavor, true)
+		})
+
+		ginkgo.It("should handle the workload deletion", func() {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply test/integration/controller/core/workload_controller_test.go]: Removed this test. Already tested on unit tests.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 9 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go:1777]: Added

File: pkg/controller/jobs/job/job_controller_test.go (hunk 16 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/job/job_controller_test.go]: You right. Removed it.

File: pkg/controller/jobs/raycluster/raycluster_controller_test.go (hunk 17 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/raycluster/raycluster_controller_test.go:331]: Done

File: pkg/workload/workload.go (hunk 19 above)
Comment (mbobrovskyi) [reply pkg/workload/workload.go]: Renamed

File: pkg/workload/workload.go [hunk 24]
```diff
@@ -383,10 +379,19 @@ func UnsetQuotaReservationWithCondition(wl *kueue.Workload, reason, message stri
 }
 
 // SetRequeuedCondition sets the WorkloadRequeued condition to true
-func SetRequeuedCondition(wl *kueue.Workload, reason string, message string) {
+func SetRequeuedCondition(wl *kueue.Workload, reason, message string) {
```
Comment (alculquicondor) [inline pkg/workload/workload.go:382]:
```suggestion
func RequeuedCondition(wl *kueue.Workload, reason, message string, status bool) {
```

File: pkg/workload/workload.go (hunk 18 above)
Comment (mbobrovskyi) [reply pkg/workload/workload.go]: Done

File: pkg/workload/workload.go (hunk 24 above)
Comment (mbobrovskyi) [reply pkg/workload/workload.go]: Done

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 25]
```diff
@@ -1832,6 +1895,150 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler", ginkgo.Orde
...
+						Message: "The workload has no reservation",
+					}, util.IgnoreConditionTimestampsAndObservedGeneration),
+					gomega.BeComparableTo(metav1.Condition{
+						Type:    kueue.WorkloadRequeued,
+						Status:  metav1.ConditionFalse,
+						Reason:  kueue.WorkloadEvictedByPodsReadyTimeout,
+						Message: fmt.Sprintf("Exceeded the PodsReady timeout %s", wlKey.String()),
+					}, util.IgnoreConditionTimestampsAndObservedGeneration),
+				))
+			}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
```
Comment (alculquicondor) [inline test/integration/controller/jobs/job/job_controller_test.go:1993]:
```suggestion
			}, util.Timeout, util.Interval).Should(gomega.Succeed())
```

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 26]
```diff
@@ -1832,6 +1895,150 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler", ginkgo.Orde
...
+			CRDPath: crdPath,
+		}
+		cfg = fwk.Init()
+		waitForPodsReady := &configapi.WaitForPodsReady{
+			Enable:         true,
+			BlockAdmission: ptr.To(true),
+			Timeout:        &metav1.Duration{Duration: util.Timeout},
+			RequeuingStrategy: &configapi.RequeuingStrategy{
+				Timestamp:          ptr.To(configapi.EvictionTimestamp),
+				BackoffBaseSeconds: ptr.To[int32](configapi.DefaultRequeuingBackoffBaseSeconds),
```
Comment (alculquicondor) [inline test/integration/controller/jobs/job/job_controller_test.go:1917]:
```suggestion
				BackoffBaseSeconds: ptr.To[int32](1),
```

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 27]
```diff
@@ -1832,6 +1895,150 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler", ginkgo.Orde
...
+						Message: "The workload is admitted",
+					}, util.IgnoreConditionTimestampsAndObservedGeneration),
+					gomega.BeComparableTo(metav1.Condition{
+						Type:    kueue.WorkloadRequeued,
+						Status:  metav1.ConditionTrue,
+						Reason:  kueue.WorkloadBackoffFinished,
+						Message: "The workload backoff was finished",
+					}, util.IgnoreConditionTimestampsAndObservedGeneration),
+				))
+			}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
```
Comment (alculquicondor) [inline test/integration/controller/jobs/job/job_controller_test.go:2037]:
```suggestion
			}, util.Timeout, util.Interval).Should(gomega.Succeed())
```

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 28]
```diff
@@ -1832,6 +1895,150 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler", ginkgo.Orde
 	})
 })
 
+var _ = ginkgo.Describe("Job controller interacting with scheduler when waitForPodsReady enabled", ginkgo.Ordered, ginkgo.ContinueOnFailure, func() {
```
Comment (alculquicondor) [inline test/integration/controller/jobs/job/job_controller_test.go:1898]: I fear that there is high potential for flakiness here.

The ideal solution is to manipulate the passing of time in the test, if you can pass a fake time to every controller.

OTOH, we are not too concerned with what the scheduler is doing, so we could potentially remove it from the equation. What we are concerned mostly is the interaction between the job controller and the workload reconciler.

@mimowo do you have any suggestions on how to improve this test?

File: test/integration/controller/core/workload_controller_test.go [hunk 29]
```diff
@@ -405,12 +405,6 @@ var _ = ginkgo.Describe("Workload controller", ginkgo.Ordered, ginkgo.ContinueOn
 							Reason:  "Pending",
 							Message: "By test",
 						}, util.IgnoreConditionTimestampsAndObservedGeneration),
-						gomega.BeComparableTo(metav1.Condition{
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply test/integration/controller/core/workload_controller_test.go:408]: Because this test doesn't execute jobframework reconciler. jobframework reconciler should handle AdmissionCheck eviction and set Requeued condition to true. 

I can add something like this. But I'm not sure that it will give us something.

```go
workload.SetRequeuedCondition(&createdWl, "AdmissionCheck", "At least one admission check is false", true)
gomega.Expect(k8sClient.Status().Update(ctx, &createdWl)).Should(gomega.Succeed())
```

[the remark this answers is not in the document]
Comment (alculquicondor) [reply test/integration/controller/core/workload_controller_test.go:408]: No, that's ok.
Thanks for explaining.

File: pkg/controller/core/workload_controller_test.go [hunk 30]
```diff
@@ -590,6 +590,92 @@ func TestReconcile(t *testing.T) {
 				Message:   "Deactivated Workload \"ns/wl\" by reached re-queue backoffLimitCount",
 			}},
 		},
+		"should set the WorkloadRequeued condition to true on re-activated": {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller_test.go:593]: Yes, still working on it :(. The problem is that this status doesn't update by Patch/Apply. The workload.ApplyAdmissionStatus skipping all nil values.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/core/workload_controller_test.go:593]: uhm..... I think that might be a limitation of the fake client. Maybe you can leave it, as it is already tested on integration https://github.com/kubernetes-sigs/kueue/pull/1838/files#diff-f4fac662d1029511a4b1ca216fa88a0396663289dda8c022e8fcda59a02deabc

File: pkg/controller/core/workload_controller.go [hunk 31]
```diff
@@ -166,9 +160,51 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
 	cqName, cqOk := r.queues.ClusterQueueForWorkload(&wl)
 	if cqOk {
-		if updated, err := r.reconcileSyncAdmissionChecks(ctx, &wl, cqName); updated || err != nil {
+		// because we need to react to API cluster cq events, the list of checks from a cache can lead to race conditions
+		cq := kueue.ClusterQueue{}
+		if err := r.client.Get(ctx, types.NamespacedName{Name: cqName}, &cq); err != nil {
+			return ctrl.Result{}, err
+		}
+		// If stopped cluster queue is started we need to set the WorkloadRequeued condition to true.
+		if workload.IsDisabledRequeuedByClusterQueueStopped(&wl) && ptr.Deref(cq.Spec.StopPolicy, kueue.None) == kueue.None {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go:203]: The eviction setting on workload_controller here:

```go
if workload.IsAdmitted(wl) {
    if queueStopPolicy != kueue.HoldAndDrain {
        return false, nil
    }
    log.V(3).Info("Workload is evicted because the ClusterQueue is stopped", "clusterQueue", klog.KRef("", cqName))
    workload.SetEvictedCondition(wl, kueue.WorkloadEvictedByClusterQueueStopped, "The ClusterQueue is stopped")
    err := workload.ApplyAdmissionStatus(ctx, r.client, wl, true)
    return true, client.IgnoreNotFound(err)
}
```

After that on jobframework reconciler this event handling and setting Requeued=true.

```go
// 6. handle eviction
if evCond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadEvicted); evCond != nil && evCond.Status == metav1.ConditionTrue {
    if err := r.stopJob(ctx, job, wl, StopReasonWorkloadEvicted, evCond.Message); err != nil {
        return ctrl.Result{}, err
    }
    if workload.HasQuotaReservation(wl) {
        if !job.IsActive() {
            log.V(6).Info("The job is no longer active, clear the workloads admission")
            if evCond.Reason == kueue.WorkloadEvictedByDeactivation ||
                evCond.Reason == kueue.WorkloadEvictedByPodsReadyTimeout ||
                evCond.Reason == kueue.WorkloadEvictedByClusterQueueStopped {
                workload.SetRequeuedCondition(wl, evCond.Reason, evCond.Message, false)
            } else {
                workload.SetRequeuedCondition(wl, evCond.Reason, evCond.Message, true)
            }
            _ = workload.UnsetQuotaReservationWithCondition(wl, "Pending", evCond.Message)
            err := workload.ApplyAdmissionStatus(ctx, r.client, wl, true)
            if err != nil {
                return ctrl.Result{}, fmt.Errorf("clearing admission: %w", err)
            }
        }
    }
    return ctrl.Result{}, nil
}
```

File: pkg/controller/core/workload_controller_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller_test.go]: Done

File: pkg/controller/core/workload_controller_test.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller_test.go:593]: Added comment to do not confuse in future.

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 32]
```diff
@@ -1832,6 +1895,150 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler", ginkgo.Orde
...
+
+	ginkgo.BeforeAll(func() {
+		fwk = &framework.Framework{
+			CRDPath: crdPath,
+		}
+		cfg = fwk.Init()
+		waitForPodsReady := &configapi.WaitForPodsReady{
+			Enable:         true,
+			BlockAdmission: ptr.To(true),
+			Timeout:        &metav1.Duration{Duration: util.Timeout},
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go]: Done

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 25 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go]: Done

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 26 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go]: Done

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 27 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go]: Done

File: pkg/controller/core/workload_controller.go (hunk 31 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/core/workload_controller.go]: Got it, thanks!

**Comment by alculquicondor** [comment]
Integration passed 1/5

/test pull-kueue-test-integration-main

**Comment by mbobrovskyi** [comment]
Integration passed 2/5

/test pull-kueue-test-integration-main

**Comment by mbobrovskyi** [comment]
Integration passed 3/5

/test pull-kueue-test-integration-main

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 28 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go:1899]: With current solution I think we can't manipulate the passing of time in the test. Inside worload_controller we are using another incapsulated waitForPodsReadyConfig.

**Comment by mbobrovskyi** [comment]
Integration passed 4/5

/test pull-kueue-test-integration-main

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 28 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go:1899]: With scheduler I think it's more realistic case.

**Comment by mbobrovskyi** [comment]
Integration passed 5/5

/test pull-kueue-test-integration-main

**Comment by alculquicondor** [comment]
/lgtm
/approve

If @mimowo has any suggestions, we can apply them in a follow up.

File: pkg/controller/core/workload_controller.go [hunk 33]
```diff
@@ -166,9 +160,51 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
+				updated = true
+			case kueue.WorkloadEvictedByPodsReadyTimeout:
+				var requeueAfter time.Duration
+				if wl.Status.RequeueState != nil && wl.Status.RequeueState.RequeueAt != nil {
+					requeueAfter = wl.Status.RequeueState.RequeueAt.Time.Sub(r.clock.Now())
+				}
+				if requeueAfter > 0 {
+					return reconcile.Result{RequeueAfter: requeueAfter}, nil
+				}
+				workload.SetRequeuedCondition(&wl, kueue.WorkloadBackoffFinished, "The workload backoff was finished", true)
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:185]: It looks inconsistent: that we don't clear`wl.Status.RequeueState` for PodsReady timeout, but we clear it on L168 in case of Reactivation. In particular, I'm wondering if this could lead to incrementing the `RequeueState.Count` [here](https://github.com/kubernetes-sigs/kueue/blob/f108fef22eb4532f3918754e5a08226ac366343c/pkg/controller/core/workload_controller.go#L420) on the second requeue. Please verify and fix if this is the case.

File: pkg/controller/core/workload_controller.go [hunk 34]
```diff
@@ -166,9 +160,51 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
 	cqName, cqOk := r.queues.ClusterQueueForWorkload(&wl)
 	if cqOk {
-		if updated, err := r.reconcileSyncAdmissionChecks(ctx, &wl, cqName); updated || err != nil {
+		// because we need to react to API cluster cq events, the list of checks from a cache can lead to race conditions
+		cq := kueue.ClusterQueue{}
+		if err := r.client.Get(ctx, types.NamespacedName{Name: cqName}, &cq); err != nil {
+			return ctrl.Result{}, err
+		}
+		// If stopped cluster queue is started we need to set the WorkloadRequeued condition to true.
+		if isDisabledRequeuedByClusterQueueStopped(&wl) && ptr.Deref(cq.Spec.StopPolicy, kueue.None) == kueue.None {
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:203]: I would suspect it does not matter what was the `StopPolicy` that lead to the setting `Requeued: false` for ClusterQueueStopped. In particular, if the `stopPolicy: HoldAndDrain`, then I believe we would set the `Requeued: false` [here](https://github.com/kubernetes-sigs/kueue/blob/f108fef22eb4532f3918754e5a08226ac366343c/pkg/controller/core/workload_controller.go#L331-L334). However, the extra check `ptr.Deref(cq.Spec.StopPolicy, kueue.None) == kueue.None` would prevent us to set `Requeued: true`.

**Comment by mimowo** [comment]
> If @mimowo has any suggestions, we can apply them in a follow up.

@mbobrovskyi please verify and address (if needed) in a follow up the following comments: 
- https://github.com/kubernetes-sigs/kueue/pull/2063#discussion_r1590751039
- https://github.com/kubernetes-sigs/kueue/pull/2063#discussion_r1590754789

File: pkg/controller/core/workload_controller.go (hunk 33 above)
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go:185]: I'm not sure that we need to clear `wl.Status.RequeueState` in this case, because we need to know how much attempts we have, to deactivate workload if we exceeded the limit [here](https://github.com/kubernetes-sigs/kueue/blob/f108fef22eb4532f3918754e5a08226ac366343c/pkg/controller/core/workload_controller.go#L421).

```go
func (r *WorkloadReconciler) triggerDeactivationOrBackoffRequeue(ctx context.Context, wl *kueue.Workload) (bool, error) {
...
        // If requeuingBackoffLimitCount equals to null, the workloads is repeatedly and endless re-queued.
	requeuingCount := ptr.Deref(wl.Status.RequeueState.Count, 0) + 1
	if r.waitForPodsReady.requeuingBackoffLimitCount != nil && requeuingCount > *r.waitForPodsReady.requeuingBackoffLimitCount {
		wl.Spec.Active = ptr.To(false)
		if err := r.client.Update(ctx, wl); err != nil {
			return false, err
		}
		r.recorder.Eventf(wl, corev1.EventTypeNormal, kueue.WorkloadEvictedByDeactivation,
			"Deactivated Workload %q by reached re-queue backoffLimitCount", klog.KObj(wl))
		return true, nil
	}
...
}
```

Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go:185]: Or you mean to clear just RequeueAt field?

Comment (mimowo) [reply pkg/controller/core/workload_controller.go:185]: > I'm not sure that we need to clear wl.Status.RequeueState in this case, because we need to know how much attempts we have

Ah, got it, we need to preserve the `count` so that we can increment it if the PodsReady timeout is exceeded for the next time.

> Or you mean to clear just RequeueAt field?

I guess the field is harmless, but might be confusing, since the workload is already requeued, so indeed, I would suggest to clear it.

File: pkg/controller/core/workload_controller.go (hunk 34 above)
Comment (mimowo) [reply pkg/controller/core/workload_controller.go:203]: Oh, I think the implementation is correct (as discussed offline), we only set `Requeue: true` if `stopPolicy: None`.

**Comment by mimowo** [comment]
@mbobrovskyi thanks for handling the comments, so the only follow up would be to clear `RequeueAt` when we set `Requeued: true`.

**Comment by mbobrovskyi** [comment]
#2143.

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
NONE
```

Because this fixes an unreleased feature.
