### PR TITLE
WaitForPodsReady: Reset the requeueState while reconciling

### LINKED ISSUE #1821: RequeueState isn't always reset
**What happened**:

If you introduce `g.Expect(workload.Status.RequeueState).NotTo(gomega.BeNil())` right after this line:

https://github.com/kubernetes-sigs/kueue/blob/0c5740d977f8fa73ac0c04d3007a0bf167784b9e/test/integration/webhook/workload_test.go#L109

You will see that the object already lost the RequeueState.
This is because the workload reconciler sometimes sees the old object and produces an SSA update that still has the original object with no requeueState.

I think the webhook defaulter only applies on Create and not on Update.

We should probably reset the requeueState in the reconciler itself, but I'm not sure at which point. Unless the webhook can be configured to be called during Update?

**What you expected to happen**:

RequeueState to be reset

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I discovered this in https://github.com/kubernetes-sigs/kueue/pull/1820, when I tried to make the reconciler only do updates when the Admission condition changes.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
As @alculquicondor mentioned https://github.com/kubernetes-sigs/kueue/issues/1821#issuecomment-1994761605, mutating webhooks seems not to be possible to update `spec` and `status` in a single webhook call.

So, we must reset requeueState while reconciling instead of webhooks.

#### Which issue(s) this PR fixes:

Fixes #1821

#### Does this PR introduce a user-facing change?

```release-note
WaitForPodsReady: Fix a bug that the requeueState isn't reset.
```

### CODE REVIEW

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 1]
```diff
@@ -248,7 +248,7 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
 			// To avoid flakiness, we don't verify if the workload has a QuotaReserved=false with pending reason here.
 		})
 
-		ginkgo.It("Should re-admit a timed out workload and deactivate a workload exceeded the re-queue count limit", func() {
+		ginkgo.It("Should re-admit a timed out workload and deactivate a workload exceeded the re-queue count limit. After that re-activating a workload", func() {
```
Comment (gabesaba) [inline test/integration/scheduler/podsready/scheduler_test.go:251]: nit: s/activating/activate

may we consider a separate test for this, assuming that setting up the state isn't too difficult?

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 2]
```diff
@@ -276,6 +276,27 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
...
+				g.Expect(k8sClient.Status().Update(ctx, prodWl)).Should(gomega.Succeed())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed(), "Job reconciler should add an Evicted condition with InactiveWorkload to the Workload")
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(prodWl), prodWl)).Should(gomega.Succeed())
+				prodWl.Spec.Active = ptr.To(true)
+				g.Expect(k8sClient.Update(ctx, prodWl)).Should(gomega.Succeed())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed(), "Reactivate inactive Workload")
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(prodWl), prodWl)).Should(gomega.Succeed())
+				g.Expect(prodWl.Status.RequeueState).Should(gomega.BeNil())
```
Comment (gabesaba) [inline test/integration/scheduler/podsready/scheduler_test.go:298]: should we verify at the start of this sequence that the Requeue state is in a certain configuration (non-nil, or something more specific), in case the previous part of test changes?

Not relevant if this test is split out and this state is set explicitly.

Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:298]: We already verify that here: https://github.com/kubernetes-sigs/kueue/blob/975b5f238ee08c27c5988ec46a52ce1f29e38285/test/integration/scheduler/podsready/scheduler_test.go#L273

Does it make sense?

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 1 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:251]: It is possible to divide this test into two tests, but we need to start another manager to configure the `backoffLimitCount=1 or 0` like this: https://github.com/kubernetes-sigs/kueue/blob/975b5f238ee08c27c5988ec46a52ce1f29e38285/test/integration/scheduler/podsready/scheduler_test.go#L201

It could increase integration test time. So, to avoid reducing time, I implement this test like the current one.

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 3]
```diff
@@ -276,6 +276,27 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
...
+			ginkgo.By("verify the re-activated inactive 'prod' workload re-queue state is reset")
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(prodWl), prodWl)).Should(gomega.Succeed())
+				apimeta.SetStatusCondition(&prodWl.Status.Conditions, metav1.Condition{
+					Type:    kueue.WorkloadEvicted,
+					Status:  metav1.ConditionTrue,
+					Reason:  kueue.WorkloadEvictedByDeactivation,
+					Message: "evicted by Test",
+				})
+				g.Expect(k8sClient.Status().Update(ctx, prodWl)).Should(gomega.Succeed())
```
Comment (alculquicondor) [inline test/integration/scheduler/podsready/scheduler_test.go:289]: wouldn't the controller add this already?

Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:289]: Although the jobs controller adds this condition here: https://github.com/kubernetes-sigs/kueue/blob/a96927de470d985f17b03a328c33bb8547eae9a4/pkg/controller/jobframework/reconciler.go#L423, we don't register the jobs controller to the manager. 

https://github.com/kubernetes-sigs/kueue/blob/975b5f238ee08c27c5988ec46a52ce1f29e38285/test/integration/scheduler/podsready/suite_test.go#L68-L104

Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:289]: We just register the indexers: https://github.com/kubernetes-sigs/kueue/blob/975b5f238ee08c27c5988ec46a52ce1f29e38285/test/integration/scheduler/podsready/suite_test.go#L96-L97

Comment (alculquicondor) [reply test/integration/scheduler/podsready/scheduler_test.go:289]: Interesting...
We should probably move that piece of code to the Workload controller in a follow up. It doesn't belong in the job reconciler, as it is completely independent from the job. Otherwise, if anyone wants to write a custom integration, they would need to implement this.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 3 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:289]: It makes sense, but I need to remember why we put this here.
Let me open an issue for this.

Comment (alculquicondor) [reply test/integration/scheduler/podsready/scheduler_test.go:289]: Can you add a TODO to remove this status update and link to https://github.com/kubernetes-sigs/kueue/issues/1841?

Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:289]: Sure

**Comment by tenzen-y** [comment]
@alculquicondor Could you give `lgtm` again?

**Comment by tenzen-y** [comment]
/test pull-kueue-test-integration-main
due to https://github.com/kubernetes-sigs/kueue/issues/1829

**Comment by tenzen-y** [comment]
I'm preparing the cherry-pick PR.
