### PR TITLE
Remove duplicate env variables in podSet template.

### LINKED ISSUE #3540: Add option to disable strict pod spec validation
**What would you like to be added**:

We would need to influence strictness level of Pod spec validation.

**Why is this needed**:

It turned out Kueue validates Pod spec differently compared to plain K8s.
In our case workloads have been blocked due to env vars being duplicated in Pod spec.
Because there are many components involved regarding pod spec creation and manipulation
we cannot guarantee env var keys to be unique.

Plain K8s wouldn't complain about duplicated env vars. This is why we think it would be helpful
to offer more control on Kueue's validation mechanism.

This could also be relevant to resource types other than Pods.

Log of kueue controller `v0.8.1`:
``` json
 {
    "level": "error",
    "ts": "2024-11-14T17:56:56.563529963Z",
    "caller": "controller/controller.go:329",
    "msg": "Reconcilererror",
    "controller": "v1_pod",
    "namespace": "",
    "name": "",
    "reconcileID": "",
    "error": "Workload.kueue.x-k8s.io\"pod-reproduce-env-bug-o5ymx1-n0-0-24899\"isinvalid:spec.podSets[0].template.spec.containers[0].env[2]:Duplicatevalue:map[string]interface{},{\"name\":\"DUPLICATE_ENV\"},",
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"
  }
```

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

<sub>Lucas Zanella [lucas.zanella@mercedes-benz.com](mailto:lucas.zanella@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #3540

#### Does this PR introduce a user-facing change?

```release-note
Fixed the bug that prevented managing workloads with duplicated environment variable names in containers. This issue manifested when creating the Workload via the API.
```

### CODE REVIEW

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 1]
```diff
@@ -964,6 +964,47 @@ var _ = ginkgo.Describe("Job controller", ginkgo.Ordered, ginkgo.ContinueOnFailu
 			})
 		})
 	})
+
+	ginkgo.It("should deduplicate env variables", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Extend the scenario or add a new test to demonstrate what happens on eviction

File: pkg/controller/jobframework/utils.go [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+			}
+			container.Env = slices.Collect(maps.Values(envVars))
+		}
+	}
+}
+
+// DeduplicateEnvVariablesFromPodSet removes duplicate environment variables from all containers
+// in the given pod set. Duplicates are identified by environment variable name;
+// only the last occurrence of each name is preserved.
+func DeduplicateEnvVariablesFromPodSet(podSet *kueue.PodSet) {
```
Comment (mimowo) [inline pkg/controller/jobframework/utils.go]: This is too specific. We may need more tweaks also for ports for example. I would suggest a name like SanitizePodSets, it should also check the new feature gate inside

**Comment by mimowo** [comment]
I would also suggest to make the release note a bit more generic like Fix the bug which prevented managing workloads with duplicated env. names in containers. This issue would manifest on creating the Workload API.

File: pkg/controller/jobframework/utils.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/controller/jobframework/utils.go]: Done

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Done

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 3]
```diff
@@ -2452,6 +2289,82 @@ var _ = ginkgo.Describe("Interacting with scheduler", ginkgo.Ordered, ginkgo.Con
...
+		highWlLookupKey := types.NamespacedName{Name: workloadjob.GetWorkloadNameForJob(lowJob.Name, lowJob.UID), Namespace: ns.Name}
+
+		ginkgo.By("Checking that the high priority workload is created and admitted", func() {
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, highWlLookupKey, highCreatedWorkload)).Should(gomega.Succeed())
+				g.Expect(workload.IsAdmitted(highCreatedWorkload)).Should(gomega.BeTrue())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+		})
+
+		ginkgo.By("Checking that the low priority workload is successfully preempted", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: I would like to also add a ginkgo assert on the low priority Job - does it still have the envs as originally, or sanitized.  That could be a separate ginkgo.By

Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Do we need to sanitize Job?

File: pkg/controller/jobframework/utils.go [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+// SanitizePodSet sanitizes a single PodSet by removing duplicate environment
+// variables from all containers in its pod template, but only if the
+// WorkloadEnvDeduplication feature gate is enabled.
+func SanitizePodSet(podSet *kueue.PodSet) {
+	if features.Enabled(features.WorkloadEnvDeduplication) {
+		for containerIndex := range podSet.Template.Spec.Containers {
+			container := &podSet.Template.Spec.Containers[containerIndex]
+			envVars := make(map[string]corev1.EnvVar)
+			for _, envVar := range container.Env {
+				envVars[envVar.Name] = envVar
```
Comment (mimowo) [inline pkg/controller/jobframework/utils.go]: I think when containers execture then 
PATH="var1"
PATH="var1$PATH" 
expands the TEST variable rather than override. This is actually common feature to use in .bashrc on linux to append a new path. It is less common on k8s, but maybe some programs ported from OS to k8s could use it, so I'm thinking that ideally we should resolve it. 

Please check how much complication that would be, maybe there are some library resolvers

File: pkg/features/kube_features.go [hunk 5]
```diff
@@ -198,6 +198,14 @@ const (
...
 	// Enable all updates to Workload objects to use Patch Merge instead of Patch Apply.
 	WorkloadRequestUseMergePatch featuregate.Feature = "WorkloadRequestUseMergePatch"
+
+	// owner: @mbobrovskyi
+	//
+	// WorkloadEnvDeduplication enables automatic deduplication of environment variables
+	// in PodSet templates within Workload objects. When enabled, duplicate env var entries
+	// are resolved by keeping only the last occurrence, allowing workload creation to succeed
+	// even when duplicates are present in the spec.
+	WorkloadEnvDeduplication featuregate.Feature = "WorkloadEnvDeduplication"
```
Comment (mimowo) [inline pkg/features/kube_features.go]:
```suggestion
	// owner: @mbobrovskyi
	//
	// SanitizePodSets enables automatic sanitization of PodSets when creating the Workload object.
	// The main use case it deduplication of environment variables
	// in PodSet templates within Workload objects. When enabled, duplicate env var entries
	// are resolved by keeping only the last occurrence, allowing workload creation to succeed
	// even when duplicates are present in the spec.
	SanitizePodSets featuregate.Feature = "SanitizePodSets"
```

Comment (mbobrovskyi) [reply pkg/features/kube_features.go]: Done

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 3 above)
Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Added.

Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: > Do we need to sanitize Job?

No, it is actually better to keep job as is, nice that it didn't require any additiional code changes 👍

Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: OK. Than it is done.

File: pkg/controller/jobframework/utils.go (hunk 4 above)
Comment (mbobrovskyi) [reply pkg/controller/jobframework/utils.go]: I tired to run this on k8s:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 3
  completions: 3
  completionMode: Indexed
  suspend: false
  template:
    spec:
      containers:
        - name: dummy-job
          image: busybox
          command:
            - printenv
          env:
            - name: TEST
              value: "/some-path"
            - name: TEST
              value: "/another-path:$TEST"
          resources:
            requests:
              cpu: "1"
              memory: "1Mi"
      restartPolicy: Never
```

And as a result I catch:

```
kubectl logs sample-job-0-zkkbr                                                               
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=sample-job-0
TEST=/another-path:$TEST
JOB_COMPLETION_INDEX=0
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
HOME=/root
```

So I don’t think we need to support this.

Comment (mimowo) [reply pkg/controller/jobframework/utils.go]: Awesome, thank you for the test, it makes our job easier

**Comment by mimowo** [comment]
@mbobrovskyi have you had a chance to also test e2e on a running cluster? I'm wondering if there is no issue that we would constantly try to update the Workload because EquivalentToWorkload responds to false. To verify that check the lists of events for the workload.

File: pkg/features/kube_features.go [hunk 6]
```diff
@@ -312,6 +321,9 @@ var defaultVersionedFeatureGates = map[featuregate.Feature]featuregate.Versioned
 	WorkloadRequestUseMergePatch: {
 		{Version: version.MustParse("0.14"), Default: false, PreRelease: featuregate.Alpha},
 	},
+	SanitizePodSets: {
+		{Version: version.MustParse("0.15"), Default: false, PreRelease: featuregate.Alpha},
```
Comment (mimowo) [inline pkg/features/kube_features.go]:
```suggestion
		{Version: version.MustParse("0.15"), Default: true, PreRelease: featuregate.Beta},
```
I think this is a bugfix, we may introduce the FG just as a bailout option if something goes wrong, but I think this should be default behavior.

Comment (mbobrovskyi) [reply pkg/features/kube_features.go]: Done

File: pkg/controller/jobframework/utils.go [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+// variables from all containers in its pod template, but only if the
+// SanitizePodSets feature gate is enabled.
+func SanitizePodSet(podSet *kueue.PodSet) {
+	if features.Enabled(features.SanitizePodSets) {
+		for containerIndex := range podSet.Template.Spec.Containers {
+			container := &podSet.Template.Spec.Containers[containerIndex]
+			envVars := make(map[string]corev1.EnvVar)
+			for _, envVar := range container.Env {
+				envVars[envVar.Name] = envVar
+			}
```
Comment (mimowo) [inline pkg/controller/jobframework/utils.go]: Actually, this code may not be keeping the env variables in the same order. I think it is better to make sure they are in the same order as before.

Comment (mimowo) [reply pkg/controller/jobframework/utils.go]: I think we could reuse this structure in `pkg/util/orderedgroups/ordered_groups.go` which is esstinatilly what we need

Comment (mbobrovskyi) [reply pkg/controller/jobframework/utils.go]: Done

**Comment by mbobrovskyi** [comment]
@mimowo PTAL

**Comment by mimowo** [comment]
@mbobrovskyi please prepare the cherrypicks
