### PR TITLE
Flaky test: Pod groups when Single CQ should admit group that fits.

### LINKED ISSUE #2225: Faky test: Pod groups when Single CQ should admit group that fits
/kind flake

**What happened**:
Failed `End To End Suite: kindest/node:v1.28.0: [It] Pod groups when Single CQ should admit group that fits`

```shell
{Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:133 with:
NotFoundError expects an error failed [FAILED] Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:133 with:
NotFoundError expects an error
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:134 @ 05/17/24 17:17:58.033
}
```

**What you expected to happen**:
No errors.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2221/pull-kueue-test-e2e-main-1-28/1791517344896389120

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Flaky test: Pod groups when Single CQ should admit group that fits.

#### Which issue(s) this PR fixes:

Fixes #2225

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by trasc — COMMENTED** [review]
/lgtm

File: test/e2e/singlecluster/pod_test.go [hunk 1]
```diff
@@ -522,6 +520,20 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+func expectWorkloadFinalized(ctx context.Context, k8sClient client.Client, wlKey client.ObjectKey) {
+	gomega.EventuallyWithOffset(1, func(g gomega.Gomega) error {
+		var wl kueue.Workload
+		err := k8sClient.Get(ctx, wlKey, &wl)
+		if client.IgnoreNotFound(err) != nil {
+			return client.IgnoreNotFound(err)
+		}
+		if err != nil || len(wl.Finalizers) == 0 {
+			return nil
+		}
```
Comment (tenzen-y) [inline test/e2e/singlecluster/pod_test.go:532]: By these verifications, this test succeeded even if the workload was not deleted, right?
Is this expected behavior?

File: test/e2e/singlecluster/pod_test.go [hunk 2]
```diff
@@ -522,6 +520,20 @@ var _ = ginkgo.Describe("Pod groups", func() {
 	})
 })
 
+func expectWorkloadFinalized(ctx context.Context, k8sClient client.Client, wlKey client.ObjectKey) {
+	gomega.EventuallyWithOffset(1, func(g gomega.Gomega) error {
+		var wl kueue.Workload
+		err := k8sClient.Get(ctx, wlKey, &wl)
+		if client.IgnoreNotFound(err) != nil {
+			return client.IgnoreNotFound(err)
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply test/e2e/singlecluster/pod_test.go]: Thanks

File: test/e2e/singlecluster/pod_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/e2e/singlecluster/pod_test.go:532]: Yes, we just need to check that removed Finalizers on workload. Workload automatically removing by garbage collector after all pods deleted.

File: test/e2e/singlecluster/pod_test.go [hunk 3]
```diff
@@ -522,6 +520,20 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+	gomega.EventuallyWithOffset(1, func(g gomega.Gomega) error {
+		var wl kueue.Workload
+		err := k8sClient.Get(ctx, wlKey, &wl)
+		if client.IgnoreNotFound(err) != nil {
+			return err
+		}
+		if err != nil || len(wl.Finalizers) == 0 {
+			return nil
+		}
+		return fmt.Errorf("finalizers not yet removed")
```
Comment (mimowo) [inline test/e2e/singlecluster/pod_test.go:533]:
```suggestion
		return fmt.Errorf("Workload %s is not finalized yet", wlKey)
```
nit: I suppose it could be useful for debugging to grep and match different log artifacts

**Review by mimowo — COMMENTED** [review]
LGTM

File: test/e2e/singlecluster/pod_test.go (hunk 3 above)
Comment (mbobrovskyi) [reply test/e2e/singlecluster/pod_test.go]: Thanks. Fixed.

File: test/e2e/singlecluster/pod_test.go (hunk 1 above)
Comment (tenzen-y) [reply test/e2e/singlecluster/pod_test.go:532]: Ah, I see. Removed finalizer indicates issued the deletion of Workload.

File: test/e2e/singlecluster/pod_test.go [hunk 4]
```diff
@@ -522,6 +520,20 @@ var _ = ginkgo.Describe("Pod groups", func() {
 	})
 })
 
+func expectWorkloadFinalized(ctx context.Context, k8sClient client.Client, wlKey client.ObjectKey) {
+	gomega.EventuallyWithOffset(1, func(g gomega.Gomega) error {
```
Comment (tenzen-y) [inline test/e2e/singlecluster/pod_test.go:524]:
```suggestion
	gomega.EventuallyWithOffset(1, func() error {
```

I guess that this gomega variable is not needed.

**Review by tenzen-y — COMMENTED** [review]
Basically lgtm

File: test/e2e/singlecluster/pod_test.go (hunk 4 above)
Comment (mbobrovskyi) [reply test/e2e/singlecluster/pod_test.go]: Fixed

File: test/e2e/singlecluster/pod_test.go (hunk 1 above)
Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go:532]: It means that the deletion, when issued, will be able to complete. The delete itself is issued by the gc-controller, with the period of 20s (see [here](https://github.com/kubernetes/kubernetes/blob/a70089ab991d2d78fef14033424e8dc2dd05f13f/pkg/controller/podgc/gc_controller.go#L50)). Since removing the finalizer is the last responsibility of Kueue, then testing just that seems like a viable approach.

**Comment by tenzen-y** [comment]
/test pull-kueue-test-integration-main

Due to https://github.com/kubernetes-sigs/kueue/issues/2243

**Comment by tenzen-y** [comment]
/retest
Due to #2245 and #2247

**Comment by mbobrovskyi** [comment]
@tenzen-y I propose to make another issue it. WDYT?

**Comment by tenzen-y** [comment]
> @tenzen-y I propose to make another issue for it. WDYT?

I already created the issue.

**Comment by mbobrovskyi** [comment]
Thanks

**Comment by tenzen-y** [comment]
> @tenzen-y: #2236 failed to apply on top of branch "release-0.6":
> 
> ```
> Applying: Fixed "Pod groups when Single CQ should admit group that fits" test.
> Using index info to reconstruct a base tree...
> M	test/e2e/singlecluster/pod_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging test/e2e/singlecluster/pod_test.go
> CONFLICT (content): Merge conflict in test/e2e/singlecluster/pod_test.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Fixed "Pod groups when Single CQ should admit group that fits" test.
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

@mbobrovskyi Could you manually create cherry-pick PR?
