### PR TITLE
Fix genref templates to include Configuration root type in config docs

### LINKED ISSUE #10278: Kueue Configuration v1beta2 reference docs require refresh
**What would you like to be documented or improved**: In the current docs several fields are missing: 
- namespace
- manageJobsWithoutQueueName
- managedJobsNamespaceSelector
- featureGates

**Location**: https://kueue.sigs.k8s.io/docs/reference/kueue-config.v1beta2/

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

The generated reference docs for `config.kueue.x-k8s.io/v1beta1` and `config.kueue.x-k8s.io/v1beta2` were missing the root `Configuration` type and all its direct fields (`namespace`, `manageJobsWithoutQueueName`, `managedJobsNamespaceSelector`, `featureGates`, etc.).

The root cause was that `Configuration` lacked the `+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object` marker comment, which the genref tooling uses to identify top-level resource types. This PR adds that marker to both `v1beta1` and `v1beta2` `Configuration` types and regenerates the reference docs.

Changes:
- Add `+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object` marker to `apis/config/v1beta1/configuration_types.go` and `apis/config/v1beta2/configuration_types.go`
- Regenerate `kueue-config.v1beta1.md` and `kueue-config.v1beta2.md` which now include the `Configuration` type with all its fields and proper "Appears in" cross-references

#### Which issue(s) this PR fixes:

Fixes #10278

#### Special notes for your reviewer:

The marker `+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object` is already present on other root types (e.g. in the core API types). Adding it here is consistent with the existing pattern and is what the genref tool uses to identify types that should appear in the "Resource Types" section with `apiVersion`/`kind` rows.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

---
> **AI Assistance Disclosure**: This pull request was created with the assistance of AI (Claude Code by Anthropic).

### CODE REVIEW

File: apis/config/v1beta1/configuration_types.go [hunk 1]
```diff
@@ -25,6 +25,7 @@ import (
 )
```
Comment (tenzen-y) [inline apis/config/v1beta1/configuration_types.go:26]:
```suggestion
// The deepcopy-gen marker is required to generate API reference documentation by genref.

```

File: apis/config/v1beta2/configuration_types.go [hunk 2]
```diff
@@ -26,6 +26,7 @@ import (
 )
```
Comment (tenzen-y) [inline apis/config/v1beta2/configuration_types.go:27]:
```suggestion
// The deepcopy-gen marker is required to generate API reference documentation by genref.

```

File: apis/config/v1beta1/configuration_types.go (hunk 1 above)
Comment (kannon92) [reply apis/config/v1beta1/configuration_types.go:26]: done.

File: apis/config/v1beta2/configuration_types.go (hunk 2 above)
Comment (kannon92) [reply apis/config/v1beta2/configuration_types.go:27]: done.
