### PR TITLE
Fix "Short PodsReady timeout Should requeue a workload which exceeded…

### LINKED ISSUE #3366: Flaky Test: SchedulerWithWaitForPodsReady Short PodsReady timeout Should requeue a workload which exceeded the timeout to reach PodsReady=True [slow]
**What happened**:

Failed `Scheduler with WaitForPodsReady Suite: [It] SchedulerWithWaitForPodsReady Short PodsReady timeout Should requeue a workload which exceeded the timeout to reach PodsReady=True [slow]`.

```shell
{Timed out after 5.001s.
the workload should be evicted after the timeout expires
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/scheduler/podsready/scheduler_test.go:237 with:
Expected
    <[]v1.Condition | len:3, cap:4>: [
        {
            Type: "QuotaReserved",
            Status: "True",
            ObservedGeneration: 1,
            LastTransitionTime: {
                Time: 2024-10-29T18:18:27Z,
            },
            Reason: "QuotaReserved",
            Message: "Quota reserved in ClusterQueue prod-cq",
        },
        {
            Type: "Evicted",
            Status: "True",
            ObservedGeneration: 1,
            LastTransitionTime: {
                Time: 2024-10-29T18:18:28Z,
            },
            Reason: "PodsReadyTimeout",
            Message: "Exceeded the PodsReady timeout podsready-v4pth/prod1",
        },
        {
            Type: "Admitted",
            Status: "True",
            ObservedGeneration: 1,
            LastTransitionTime: {
                Time: 2024-10-29T18:18:27Z,
            },
            Reason: "Admitted",
            Message: "The workload is admitted",
        },
    ]
not to have condition Evicted and status True failed [FAILED] Timed out after 5.001s.
the workload should be evicted after the timeout expires
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/scheduler/podsready/scheduler_test.go:237 with:
Expected
    <[]v1.Condition | len:3, cap:4>: [
        {
            Type: "QuotaReserved",
            Status: "True",
            ObservedGeneration: 1,
            LastTransitionTime: {
                Time: 2024-10-29T18:18:27Z,
            },
            Reason: "QuotaReserved",
            Message: "Quota reserved in ClusterQueue prod-cq",
        },
        {
            Type: "Evicted",
            Status: "True",
            ObservedGeneration: 1,
            LastTransitionTime: {
                Time: 2024-10-29T18:18:28Z,
            },
            Reason: "PodsReadyTimeout",
            Message: "Exceeded the PodsReady timeout podsready-v4pth/prod1",
        },
        {
            Type: "Admitted",
            Status: "True",
            ObservedGeneration: 1,
            LastTransitionTime: {
                Time: 2024-10-29T18:18:27Z,
            },
            Reason: "Admitted",
            Message: "The workload is admitted",
        },
    ]
not to have condition Evicted and status True
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/scheduler/podsready/scheduler_test.go:243 @ 10/29/24 18:18:32.963
}
```

**What you expected to happen**:

No errors happened

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-main/1851324069593485312

Screenshot 2024-10-30 at 13 46 19

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
… the timeout to reach PodsReady=True" test.

#### What type of PR is this?
/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:
Fix "Short PodsReady timeout Should requeue a workload which exceeded the timeout to reach PodsReady=True" flaky test.

#### Which issue(s) this PR fixes:

Fixes #3366

#### Special notes for your reviewer:
It was introduced on https://github.com/kubernetes-sigs/kueue/pull/3348/files#diff-f4fac662d1029511a4b1ca216fa88a0396663289dda8c022e8fcda59a02deabcR235-R237 by mistake.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/retest

Due to https://github.com/kubernetes-sigs/kueue/issues/3368.

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 1]
```diff
@@ -232,9 +232,9 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
 			gomega.Eventually(func(g gomega.Gomega) {
 				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(prodWl1), prodWl1)).Should(gomega.Succeed())
 				if time.Since(admittedAt) < podsReadyTimeout {
-					g.Expect(prodWl1.Status.Conditions).Should(testing.HaveConditionStatusTrue(kueue.WorkloadEvicted), "the workload should not be evicted until the timeout expires")
+					g.Expect(prodWl1.Status.Conditions).ShouldNot(testing.HaveConditionStatusTrue(kueue.WorkloadEvicted), "the workload should not be evicted until the timeout expires")
```
Comment (mimowo) [inline test/integration/scheduler/podsready/scheduler_test.go:235]: Actually, does it make sense to even check `time.Since(admittedAt) < podsReadyTimeout` this way? If the g.Expect fails it will be retried by `gomega.Eventually`. 

So, IIUC we can just sleep(podsReadyTimeout) and wrap the gomega.Eventually around Expect for WorkloadEvicted. Note that if we do `sleep(podsReadyTimeout)` the Eventually the test will be sligtly faster on average as without the sleep the Eventually will backoff with exponential delay so it is unlikely to be checked after 2s (it will be checked after 2s + the accumulated backoff).

Then, verify `g.Expect(ptr.Deref(prodWl1.Status.RequeueState,` outside of the Eventually.

Comment (mbobrovskyi) [reply test/integration/scheduler/podsready/scheduler_test.go]: Done
