### PR TITLE
Prevent admitting inactive workloads

### LINKED ISSUE #6711: Inactive workloads are occasionally admitted
**What happened**:

We've observed that inactive workloads (`.spec.active=false`) occasionally get admitted and are then immediately evicted.

After investigation, we found this is triggered by runtime class reconciliation, which pushes all pending workloads back onto the internal heap, regardless of their active status. This causes the scheduler to consider them, even though they're inactive.

The main [workload controller correctly checks](https://github.com/kubernetes-sigs/kueue/blob/v0.13.3/pkg/controller/core/workload_controller.go#L633-L634) .spec.active before adding workloads to the heap. However, this check is missing in [other situations](https://github.com/kubernetes-sigs/kueue/blob/v0.13.3/pkg/controller/core/workload_controller.go#L928).

**What you expected to happen**:

We’d expect Kueue to consistently avoid scheduling inactive workloads, regardless of the trigger.

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply the test setup below.
2. Annotate the RuntimeClass:
   ```
   kubectl annotate runtimeclass test-kueue-class foo=bar
   ```

This will trigger the code mentioned above, and you’ll see the following events in the workload:

```
  Type    Reason                   Age   From                       Message
  ----    ------                   ----  ----                       -------
  Normal  QuotaReserved            2s    kueue-admission            Quota reserved in ClusterQueue test-cluster-queue, wait time since queued was 14s
  Normal  Admitted                 2s    kueue-admission            Admitted by ClusterQueue test-cluster-queue, wait time since reservation was 0s
  Normal  EvictedDueToDeactivated  2s    kueue-workload-controller  The workload is deactivated
```

Example spec:

```
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: test-kueue-class
handler: myconfiguration
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: test-rf
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: test-cluster-queue
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
    - coveredResources: ["cpu", "memory"]
      flavors:
        - name: "test-rf"
          resources:
            - name: "cpu"
              nominalQuota: 10
            - name: "memory"
              nominalQuota: 2Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: test-local-queue
spec:
  clusterQueue: test-cluster-queue
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: Workload
metadata:
  name: test-wl-1
spec:
  active: false
  podSets:
    - count: 1
      name: main
      template:
        spec:
          runtimeClassName: test-kueue-class
          containers:
            - name: demo
              resources:
                limits:
                  cpu: "1"
                  memory: 128Mi
                requests:
                  cpu: "1"
                  memory: 128Mi
  queueName: test-local-queue
```

**Environment**:

- Kubernetes version (use `kubectl version`): v1.31.6
- Kueue version (use `git describe --tags --dirty --always`): 0.13.0

### PR DESCRIPTION
**Pull request by olekzabl**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

It fixes #6711 - analogously as in the discontinued #6737 - but adding 2 more bits:

- an integration test which passes now and fails without the fix
- assertions deeper down the stack to ensure no future degradation of this kind

#### Which issue(s) this PR fixes:

Fixes #6711

#### Special notes for your reviewer:

Please see the discussion in #6711, starting from [this comment](https://github.com/kubernetes-sigs/kueue/issues/6711#issuecomment-3576166232).

#### Does this PR introduce a user-facing change?

```release-note
Fix issue #6711 where an inactive workload could transiently get admitted into a queue.
```

### CODE REVIEW

File: pkg/util/testing/core.go [hunk 1]
```diff
@@ -60,16 +60,23 @@ func CheckEventRecordedFor(ctx context.Context, k8sClient client.Client,
 		len(events.Items), eventReason, eventType, eventMessage, ref.Namespace)
 }
 
-// HasEventAppeared returns if an event has been emitted
-func HasEventAppeared(ctx context.Context, k8sClient client.Client, event corev1.Event) (bool, error) {
+// HasAnyEventAppeared returns if an event has been emitted
+func HasAnyEventAppeared(ctx context.Context, k8sClient client.Client, matcher func(*corev1.Event) bool) (bool, error) {
```
Comment (kshalot) [inline pkg/util/testing/core.go]: I feel like this could be renamed to:
```suggestion
func HasMatchingEventAppeared(ctx context.Context, k8sClient client.Client, matcher func(*corev1.Event) bool) (bool, error) {
```

It immediately suggests that there is some matcher involved, while "any" can literally be read as "any event".

File: pkg/controller/core/workload_controller.go [hunk 2]
```diff
@@ -1108,8 +1108,10 @@ func (h *resourceUpdatesHandler) queueReconcileForPending(ctx context.Context, q
 			continue
 		}
 
-		if err = h.r.queues.AddOrUpdateWorkload(wlCopy); err != nil {
-			log.V(2).Info("ignored an error for now", "error", err)
+		if workload.IsActive(wlCopy) && !workload.HasQuotaReservation(wlCopy) {
+			if err = h.r.queues.AddOrUpdateWorkload(wlCopy); err != nil {
```
Comment (kshalot) [inline pkg/controller/core/workload_controller.go:1112]: From what I see [`AddOrUpdateWorkload` calls `AddOrUpdateWorkloadWithoutLock`](https://github.com/kubernetes-sigs/kueue/blob/81e20a34b1e975edacd3ff6a39b5980f86f99db0/pkg/cache/queue/manager.go#L436-L442) under the hood and you added the checks to that function as well.

Is it purely "just in case"?

File: pkg/util/testing/core.go (hunk 1 above)
Comment (olekzabl) [reply pkg/util/testing/core.go]: Done.

File: pkg/controller/core/workload_controller.go (hunk 2 above)
Comment (olekzabl) [reply pkg/controller/core/workload_controller.go:1112]: What you highlighted is the actual check.

What I added deeper in `AddOrUpdateWorkloadWithoutLock` is an assertion.

The story is that there are 6 paths to reach `AddOrUpdateWorkloadWithoutLock` altogether, and the other 5 were already covered with this check. (BTW not easily migratable down the call stack). So I added the 6-th check on the same level, to be "little invasive" into the code structure.

However, I also chose to add an assertion deeper down, so that tests can catch any change which adds a 7-th path but forgets to pre-check.

(Discussed in more detail in the issue, #6711).

**Comment by mimowo** [comment]
Thanks  👍 
/lgtm
/approve
/cherrypick release-0.14
/cherrypick release-0.13
