### PR TITLE
MultiKueue skip garbage collection for disconnected clients.

### LINKED ISSUE #2365: [MultiKueue] integration tests fail occasionally
/kind flake

**What happened**:

Failure on the unrelated branch: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2362/pull-kueue-test-integration-main/1798319515201703936

**What you expected to happen**:

No failure

**How to reproduce it (as minimally and precisely as possible)**:

Probably repeat the build multiple times.

**Anything else we need to know?**:

The report from the build log:
```
  In [ReportAfterSuite] at: autogenerated by Ginkgo @ 06/05/24 11:50:42.911
------------------------------
Ginkgo timed out waiting for all parallel procs to report back
Test suite: multikueue (./test/integration/multikueue)
This occurs if a parallel process exits before it reports its results to the
Ginkgo CLI.  The CLI will now print out all the stdout/stderr output it's
collected from the running processes.  However you may not see anything useful
in these logs because the individual test processes usually intercept output to
stdout/stderr in order to capture it in the spec reports.
You may want to try rerunning your test suite with
--output-interceptor-mode=none to see additional output here and debug your
suite.
  
Output from proc 1:
  --- FAIL: TestMultiKueue (31.90s)
  FAIL
Output from proc 2:
Output from proc 3:
  PASS
Output from proc 4:
  PASS
** End **Could not open /logs/artifacts/test_integration_multikueue_junit.xml:
open /logs/artifacts/test_integration_multikueue_junit.xml: no such file or directory
Ginkgo ran 20 suites in 6m39.250168558s
There were failures detected in the following suites:
  multikueue ./test/integration/multikueue
Test Suite Failed
make: *** [Makefile-test.mk:68: test-integration] Error 1
```

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:
MultiKueue skip garbage collection for disconnected clients, which otherwise can cause a panic if the GC runes between the time a `remoteClient` is connected and it's initial connection to the worker cluster.

#### Which issue(s) this PR fixes:

Fixes #2365 

#### Does this PR introduce a user-facing change?

```release-note
[MultiKueue] Skip garbage collection for disconnected clients which could occasionally result in panic.
```

### CODE REVIEW

File: pkg/controller/admissionchecks/multikueue/multikueuecluster.go [hunk 1]
```diff
@@ -98,6 +98,7 @@ func newRemoteClient(localClient client.Client, wlUpdateCh, watchEndedCh chan<-
 		localClient:  localClient,
 		origin:       origin,
 	}
+	rc.connecting.Store(true)
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/multikueuecluster.go:101]: Is this needed for the skip itself or it fixes another scenario?

**Review by mimowo — COMMENTED** [review]
LGTM overall, one question.

Also, it seems that this issue can affect users. If so, please add a relevant release note and we could cherry-pick.

File: pkg/controller/admissionchecks/multikueue/multikueuecluster.go (hunk 1 above)
Comment (trasc) [reply pkg/controller/admissionchecks/multikueue/multikueuecluster.go:101]: It is needed, it's one of the two key parts of the fix.

**Comment by trasc** [comment]
> LGTM overall, one question.
> 
> Also, it seems that this issue can affect users. If so, please add a relevant release note and we could cherry-pick.

done

File: pkg/controller/admissionchecks/multikueue/multikueuecluster.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/admissionchecks/multikueue/multikueuecluster.go:101]: ack

**Comment by mimowo** [comment]
/release-note-edit
```release-note
[MultiKueue] Skip garbage collection for disconnected clients which could occasionally result in panic.
```
To make it more relatable by users.

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
MultiKueue: Skip garbage collection for disconnected clients which could occasionally result in panic.
```
