### PR TITLE
TAS: Update cache on delete Topology.

### LINKED ISSUE #3614: TAS: Updates or deletion of Topology is not reflected in TAS cache resulting in wrong admission
**What happened**:

The updates to the TAS topology object are not tracked by the resource_flavor controller.
As a consequence:
- after deletion of the topology workloads continue to be admitted
- after mutating the topology workloads are admitted using the old topology

**What you expected to happen**:

Updates or deletion to the Topology object are observed and reflected by changing the cache status

Fixing both scenarios can be separate PRs (probably preferred). I think we can cover the scenarios at the integration test level (since we don't need to create pods as in e2e).

**How to reproduce it (as minimally and precisely as possible)**:

Scenario 1 (for deletion): 
create the TAS structure 

```
apiVersion: kueue.x-k8s.io/v1alpha1
kind: Topology
metadata:
  name: "gke-default"
spec:
  levels:
  - nodeLabel: "kubernetes.io/hostname"
---
kind: ResourceFlavor
apiVersion: kueue.x-k8s.io/v1beta1
metadata:
  name: "tas-flavor"
spec:
  nodeLabels:
    kubernetes.io/os: "linux"
    #    cloud.google.com/gke-nodepool: "tas-node-pool"
  topologyName: "gke-default"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "tas-cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "tas-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 200 
      - name: "memory"
        nominalQuota: 200Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "tas-user-queue"
spec:
  clusterQueue: "tas-cluster-queue"
```
2. delete the topology
3. create a workload like this 

```
apiVersion: batch/v1
kind: Job 
metadata:
  generateName: tas-sample-small-required-host-
  labels:
    kueue.x-k8s.io/queue-name: tas-user-queue
spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  template:
    metadata:
      annotations:
        kueue.x-k8s.io/podset-required-topology: "kubernetes.io/hostname"
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["1800s"]
        resources:
          requests:
            cpu: "1" 
            memory: "200Mi"
      restartPolicy: Never
```
issue: the workload gets admitted

**Scenario 2:** 

2. instead of deleting the topology in (2.) change the level label to some non-existing
3. create the same workload - workload gets admitted

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixed bug that doesn't allow to update cache on delete Topology.

#### Which issue(s) this PR fixes:

Fixes #3614

#### Does this PR introduce a user-facing change?

```release-note
TAS: Fixed bug that doesn't allow to update cache on delete Topology.
```

### CODE REVIEW

File: pkg/controller/tas/resource_flavor.go [hunk 1]
```diff
@@ -146,15 +186,13 @@ func (r *rfReconciler) Reconcile(ctx context.Context, req reconcile.Request) (re
...
-			levels := utiltas.Levels(&topology)
-			tasInfo := r.tasCache.NewTASFlavorCache(kueue.TopologyReference(topology.Name), levels, flv.Spec.NodeLabels)
-			r.tasCache.Set(kueue.ResourceFlavorReference(flv.Name), tasInfo)
+		topology := kueuealpha.Topology{}
+		if err := r.client.Get(ctx, types.NamespacedName{Name: string(*flv.Spec.TopologyName)}, &topology); err != nil {
+			return reconcile.Result{}, err
 		}
+		levels := utiltas.Levels(&topology)
+		tasInfo := r.tasCache.NewTASFlavorCache(kueue.TopologyReference(topology.Name), levels, flv.Spec.NodeLabels)
+		r.tasCache.Set(kueue.ResourceFlavorReference(flv.Name), tasInfo)
```
Comment (mimowo) [inline pkg/controller/tas/resource_flavor.go:195]: Only set new if the nodeLabels, or levels are changed, to avoid throwing away the workload usage otherwise.

Comment (mbobrovskyi) [reply pkg/controller/tas/resource_flavor.go]: Done

**Comment by mimowo** [comment]
@mbobrovskyi please split this PR into two: for delete and update. I think for delete we are almost good to go, for update I need to rethink if we need this complication. And I'm not sure about race conditions for the workload usage, so maybe we just block updating.

File: test/integration/tas/tas_test.go [hunk 2]
```diff
@@ -514,6 +514,48 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
 				})
 			})
+
+			ginkgo.It("should not admit the workload after the topology is deleted but should admit it after the topology is created", func() {
+				ginkgo.By("delete topology", func() {
+					util.ExpectObjectToBeDeleted(ctx, k8sClient, topology, true)
+				})
+
+				var wl *kueue.Workload
+				ginkgo.By("creating a workload which requires block and can fit", func() {
```
Comment (mimowo) [inline test/integration/tas/tas_test.go:524]: I think this test could be racy - the workload might get admitted if it is scheduled before the topology is removed from cache. I'm wondering if we could trigger deactivation of the ClusterQueue due to TopologyNotFound, by analogy to [here](https://github.com/kubernetes-sigs/kueue/blob/f0d1ecdd60df7e0105b4eb1319ff43f67222460f/pkg/cache/clusterqueue.go#L268). Then, in the test we could simply wait until the queue becomes inactive.

Comment (mimowo) [reply test/integration/tas/tas_test.go:524]: Yeah, but I think we should deactivate as we deactivate when there is no ResourceFlavor

Comment (mbobrovskyi) [reply test/integration/tas/tas_test.go:524]: On this case I think we should think how to reconcile ClusterQueue.

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-integration-main 

1/5

File: test/integration/tas/tas_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/tas/tas_test.go:524]: I'm concerned this may flake, if the workload is created before the topology delete event is propagated. 

To test if this is possible I suggest to:
1. temporarily inject time.Sleep(2*time.Second) before `tasCache.Delete`, [here](https://github.com/kubernetes-sigs/kueue/pull/3615/files#diff-7f688e0706bb6b6775d35b320ee0d496f92ed367d87cb845979731898ea9d1eaR182)
2. if we confirm the test fails, adjust the test to create the workloads in a loop using gomega.Eventually
3. once the test is stable, remove the temporarily injected sleep

**Comment by mimowo** [comment]
/test pull-kueue-test-integration-main

2/5

**Comment by mimowo** [comment]
/test pull-kueue-test-integration-main

3/5

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-integration-main

4/5

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-integration-main

5/5

File: test/integration/tas/tas_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/integration/tas/tas_test.go:532]: Done

Comment (mbobrovskyi) [reply test/integration/tas/tas_test.go:532]: I also tested it using a stress test.

```
KUBEBUILDER_ASSETS=/Users/mykhailo_bobrovskyi/Library/Application\ Support/io.kubebuilder.envtest/k8s/1.31.0-darwin-arm64 stress ./tas.test -test.run TestAPIs
10m55s: 301 runs so far, 0 failures
```

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve

**Comment by mimowo** [comment]
@mbobrovskyi can you check what are the conflicts and prepare manual cherry-pick if nothing serious?

**Comment by mbobrovskyi** [comment]
> @mbobrovskyi can you check what are the conflicts and prepare manual cherry-pick if nothing serious?

We should cherry-pick https://github.com/kubernetes-sigs/kueue/pull/3509 first.
