### PR TITLE
TAS: Respect `requiredDuringSchedulingIgnoredDuringExecution` affinity

### LINKED ISSUE #7728: TAS: nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution is ignored
**What happened**:

When we create a Workload the nodeAffinity. is not respected by TAS.

Here we could follow the implementation for nodeSelectors, as here: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/scheduler/tas_flavor_snapshot.go#L719-L728

Supporting `preferredDuringSchedulingIgnoredDuringExecution` is more subtle, and is not part of the issue.

**What you expected to happen**:

nodeAffnity.requiredDuringSchedulingIgnoredDuringExecution. to be respected by TAS,

**How to reproduce it (as minimally and precisely as possible)**:

Schedule a workload using the construction below, example:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: instance-type
          operator: In
          values:
          - high-mem-xlarge
          - high-mem-2xlarge
```

### PR DESCRIPTION
**Pull request by kshalot**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR adds support for the `requiredDuringSchedulingIgnoredDuringExecution` affinity setting to TAS. This field is currently being ignored during scheduling.

#### Which issue(s) this PR fixes:
Fixes #7728

#### Special notes for your reviewer:
I marked this PR with `kind/bug` because the affinity being ignored seems like a bug/missing part of how scheduling is supposed to work rather than a standalone feature.

#### Does this PR introduce a user-facing change?
```release-note
TAS: Fix the `requiredDuringSchedulingIgnoredDuringExecution` node affinity setting being ignored in topology-aware scheduling.
```

### CODE REVIEW

File: pkg/cache/scheduler/tas_flavor_snapshot.go [hunk 1]
```diff
@@ -105,6 +106,8 @@ type leafDomain struct {
 	// nodeLabels contains the list of labels on the node, only applies for
 	// lowest level of topology, if the lowest level is node
 	nodeLabels map[string]string
+
+	node *corev1.Node
```
Comment (mimowo) [inline pkg/cache/scheduler/tas_flavor_snapshot.go:103]: Oh, I see we need to keep the entire workload to match fields, but funnily `metadata.name` seems the only supported field: https://github.com/kubernetes/kubernetes/blob/dd4d9fad24828f54ad48b5c6c413a6d073b19e90/staging/src/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go#L156-L162

So the options I see:
1. Keep the `nodeLabels`, `nodeTaints,  and the `nodeFields` separately in the leafDomain struct
2. replace `nodeTaints`, and `nodeLabels` with  `node *corev1.Node` 
3. replace `nodeTaints`, and `nodeLabels` with  `node *corev1.Node` , but drop node status from the cache as unused

My preference is for (2.) for this PR for simplicity. We may consider follow up with (3.), but I'm not sure about it.

File: pkg/cache/scheduler/tas_flavor_snapshot.go [hunk 2]
```diff
@@ -726,6 +734,16 @@ func (s *TASFlavorSnapshot) findTopologyAssignment(
...
 	}
+
+	var affinitySelector *nodeaffinity.NodeSelector
+	var err error
+	if requiredAffinityNodeSelector != nil {
+		affinitySelector, err = nodeaffinity.NewNodeSelector(requiredAffinityNodeSelector)
+		if err != nil {
+			return nil, fmt.Sprintf("invalid affinity node selectors: %s, reason: %s", requiredAffinityNodeSelector, err)
+		}
+	}
```
Comment (Singularity23x0) [inline pkg/cache/scheduler/tas_flavor_snapshot.go:734]: Why not execute this logic together with retrieving "requiredAffinityNodeSelector"?
There would be no need for the "requiredAffinityNodeSelector != nil" check and var then.

File: pkg/cache/scheduler/tas_flavor_snapshot.go (hunk 1 above)
Comment (kshalot) [reply pkg/cache/scheduler/tas_flavor_snapshot.go:103]: I did not remove the `nodeLabels` and `nodeTaints` initially simply to avoid cluttering the diff in the preliminary review.

My first thought of how to do this properly was option (2.) to avoid redundancy, I did not think as deep as option (3.). Nevertheless, I agree with the sentiment that it is something to consider as a follow-up rather than in this PR.

(2.) is implemented in https://github.com/kubernetes-sigs/kueue/pull/7899/commits/b27ddf05bb2cfbf251c6c5a913313d6bedda2ac6.

File: pkg/cache/scheduler/tas_flavor_snapshot.go [hunk 3]
```diff
@@ -1317,32 +1328,43 @@ func (s *TASFlavorSnapshot) fillInCounts(
 		domain.leaderState = 0
 	}
 	for _, leaf := range s.leaves {
-		// 1. Check Tolerations against Node Taints
-		taint, untolerated := corev1helpers.FindMatchingUntoleratedTaint(leaf.nodeTaints, tolerations, func(t *corev1.Taint) bool {
-			return t.Effect == corev1.TaintEffectNoSchedule || t.Effect == corev1.TaintEffectNoExecute
-		})
```
Comment (kshalot) [inline pkg/cache/scheduler/tas_flavor_snapshot.go:1323]: This check was originally executed regardless of `isLowestLevelNode` and `leaf.nodeTaints` is only set when the last level is a leaf, so IIUC we can skip this if `!s.isLowestLevelNode()`, like the `selector` check.

I re-ordered the guard clauses because then this can be checked once + the original comments were invalid (comments said that `"2. Check Node Labels against Compiled Selector"` but it was actually done **third**, and `belongsToRequiredDomain` was second.

File: pkg/cache/scheduler/tas_flavor_snapshot.go (hunk 2 above)
Comment (kshalot) [reply pkg/cache/scheduler/tas_flavor_snapshot.go:734]: The variable being a bit higher is a leftover from previous implementation, but this logic won't be simplified anyway (at least from what I see).

It's either two `nil` checks or two `if`s. I went for two `if`s now for readability

Comment (Singularity23x0) [reply pkg/cache/scheduler/tas_flavor_snapshot.go:734]: Fair enough, leaving the final shape to you.

**Review by mimowo — COMMENTED** [review]
I would love to also have some unit tests for that for the ease of debugging, probably scheduler_tas_test.go has all the bits ready

File: pkg/cache/scheduler/tas_flavor_snapshot.go (hunk 1 above)
Comment (mimowo) [reply pkg/cache/scheduler/tas_flavor_snapshot.go:103]: sgtm, I'm ok with (2.)  for now. (3.) is nice to chop of some memory, but we can leave it for later if needed.

Comment (olekzabl) [reply pkg/cache/scheduler/tas_flavor_snapshot.go:103]: When chopping memory, I'd also watch out for annotations, as they're quite unbounded in size.

(And, in practice, I recall seeing Pods etc. where annotations took most of their bytesize. Not sure how often that happens for Nodes).

File: pkg/scheduler/scheduler_tas_test.go [hunk 4]
```diff
@@ -2373,6 +2373,100 @@ func TestScheduleForTAS(t *testing.T) {
...
+					Queue("tas-main").
+					PodSets(
+						*utiltestingapi.MakePodSet("one", 1).
+							PreferredTopologyRequest(corev1.LabelHostname).
+							RequiredDuringSchedulingIgnoredDuringExecution(
+								[]corev1.NodeSelectorTerm{
+									{
+										MatchExpressions: []corev1.NodeSelectorRequirement{
+											{
+												Key:      "key",
```
Comment (olekzabl) [inline pkg/scheduler/scheduler_tas_test.go]: As it is now, I'd need to go high up to the definition of `singleNode` to check if it indeed has no `key: value` label.
And it's so generic that someone could add it there one day.
How about using some very distinctive label name here?

File: test/integration/singlecluster/tas/tas_test.go [hunk 5]
```diff
@@ -2050,6 +2050,84 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+									},
+								},
+							}).
+							Request(corev1.ResourceCPU, "1").
+							Obj()).
+						Obj()
+					util.MustCreate(ctx, k8sClient, wl1)
+				})
+
+				ginkgo.By("verify the workload is inadmissible due to missing label", func() {
```
Comment (olekzabl) [inline test/integration/singlecluster/tas/tas_test.go]: To be strict, you only verify that it is inadmissible. You don't verify the reason.

Loose thought: maybe if you put "due to missing label" in parentheses, it'll be less confusing?

File: test/integration/singlecluster/tas/tas_test.go [hunk 6]
```diff
@@ -2050,6 +2050,84 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+					util.ExpectWorkloadsToBePending(ctx, k8sClient, wl1)
+					util.ExpectPendingWorkloadsMetric(clusterQueue, 0, 1)
```
Comment (olekzabl) [inline test/integration/singlecluster/tas/tas_test.go:2102]: [nit] I wonder if checking metrics here is valuable.
We've already checked that `wl1` specifically is pending; then checking metrics looks like testing just the metrics (not actual behavior under test), which I suppose has been done elsewhere already.

File: pkg/cache/scheduler/tas_flavor_snapshot.go (hunk 1 above)
Comment (kshalot) [reply pkg/cache/scheduler/tas_flavor_snapshot.go:103]: Good point, since a single annotation can be as large as 256kb. Nevertheless, I feel that maybe it's still for `>=0.15.1`?

File: test/integration/singlecluster/tas/tas_test.go (hunk 6 above)
Comment (kshalot) [reply test/integration/singlecluster/tas/tas_test.go:2102]: I'm happy to change it, but I just wanted to say that this test is based on existing tests in this file that contain this check.

Example: https://github.com/kubernetes-sigs/kueue/blob/ced66bd2e9d770253e931ca4004462bd258bda5b/test/integration/singlecluster/tas/tas_test.go#L2092

File: pkg/cache/scheduler/tas_flavor_snapshot.go (hunk 1 above)
Comment (mimowo) [reply pkg/cache/scheduler/tas_flavor_snapshot.go:103]: Yes, it could be backported as a performance optimization in the future. Feel free to submit a small PR

File: test/integration/singlecluster/tas/tas_test.go (hunk 5 above)
Comment (kshalot) [reply test/integration/singlecluster/tas/tas_test.go]: I want to keep the "missing label" and "wrong label value" information in the case name because it will be helpful when examining test failures, but you are right that the wording "due to" is not necessarily correct. I reworded it to focus on state rather than cause: https://github.com/kubernetes-sigs/kueue/pull/7899/commits/03a62bc1578b7ac8a672de439fc3453c6e334b39

**Comment by mimowo** [comment]
Thanks 👍 I can see some discussion is ongoing, but it does not look like blockers, so let me merge as we are releasing tomorrow. We can address the smaller things later.
/lgtm
/approve

I think this is worth backporting, so please prepare the cherrypicks in case the robot fails on conflicts.
/cherrypick release-0.14
/cherrypick release-0.13

**Comment by mimowo** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7899/pull-kueue-test-e2e-customconfigs-main/1993718563780694016


looks like unrelated flake

EDIT: Opened: https://github.com/kubernetes-sigs/kueue/issues/7919
