### PR TITLE
[workload] Drop Quota Reservation on cluster queue deletion.

### LINKED ISSUE #1253: A cluster queue may be stuck in "Terminating" if it has Reserving workloads pending on an inactive check.
**What happened**:
A cluster queue may be stuck in "Terminating" if it has Reserving workloads pending on an inactive check.

**What you expected to happen**:
A deleted cluster queue should eventually release its  finalizer and be fully deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Drop the workloads quota reservation if it's not Admitted and the target ClusterQueue is deleted.

#### Which issue(s) this PR fixes:

Fixes #1253 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/core/workload_controller.go [hunk 1]
```diff
@@ -216,6 +221,25 @@ func (r *WorkloadReconciler) reconcileSyncAdmissionChecks(ctx context.Context, w
 	return false, nil
 }
 
+func (r *WorkloadReconciler) reconcileReservationOnQueueDeletion(ctx context.Context, wl *kueue.Workload, cqName string) (bool, error) {
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller.go:224]:
```suggestion
func (r *WorkloadReconciler) reconcileReservationOnClusterQueueDeletion(ctx context.Context, wl *kueue.Workload, cqName string) (bool, error) {
```

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 2]
```diff
@@ -708,28 +709,44 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Ordered, ginkgo.Contin
...
 
+		ginkgo.AfterEach(func() {
+			util.ExpectAdmissionCheckToBeDeleted(ctx, k8sClient, check, true)
+		})
+
 		ginkgo.It("Should delete clusterQueues successfully when no admitted workloads are running", func() {
 			util.ExpectClusterQueueToBeDeleted(ctx, k8sClient, cq, true)
 		})
 
 		ginkgo.It("Should be stuck in termination until admitted workloads finished running", func() {
```
Comment (tenzen-y) [inline test/integration/controller/core/clusterqueue_controller_test.go:735]: IMO, we should leave this case without admissionCheck.
So, can you create another case with admissionChecks?

**Review by tenzen-y — COMMENTED** [review]
How does the workload-controller find that the cq is terminating?
IIUC, the cq-controller doesn't send a generic event to the workload-controller.

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 2 above)
Comment (trasc) [reply test/integration/controller/core/clusterqueue_controller_test.go:735]: In my opinion , the  test is about how the queue is deleted while there are admitted workloads, the way the workloads become admitted is not relevant.

Comment (tenzen-y) [reply test/integration/controller/core/clusterqueue_controller_test.go:735]: It makes sense. `QuotaReserved` is added to workloads even if we don't use two-phase admission.

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 3]
```diff
@@ -708,28 +709,44 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Ordered, ginkgo.Contin
...
 			wl := testing.MakeWorkload("workload", ns.Name).Queue(lq.Name).Obj()
 			gomega.Expect(k8sClient.Create(ctx, wl)).To(gomega.Succeed())
 			gomega.Expect(util.SetQuotaReservation(ctx, k8sClient, wl, testing.MakeAdmission(cq.Name).Obj())).To(gomega.Succeed())
+			util.SetWorkloadsAdmissionCkeck(ctx, k8sClient, wl, check.Name, kueue.CheckStateReady, true)
+			gomega.Eventually(func(g gomega.Gomega) {
+				key := client.ObjectKeyFromObject(wl)
+				updatedWl := &kueue.Workload{}
+				g.Expect(k8sClient.Get(ctx, key, updatedWl)).To(gomega.Succeed())
+				g.Expect(apimeta.IsStatusConditionTrue(updatedWl.Status.Conditions, kueue.WorkloadAdmitted)).To(gomega.BeTrue())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
```
Comment (tenzen-y) [inline test/integration/controller/core/clusterqueue_controller_test.go:749]:
```suggestion
			gomega.Eventually(func() bool {
				key := client.ObjectKeyFromObject(wl)
				updatedWl := &kueue.Workload{}
				if errr := k8sClient.Get(ctx, key, updatedWl); err != nil {
					return false
				}
				return apimeta.IsStatusConditionTrue(updatedWl.Status.Conditions, kueue.WorkloadAdmitted)
			}, util.Timeout, util.Interval).Should(gomega.BeTrue())
```

Comment (trasc) [reply test/integration/controller/core/clusterqueue_controller_test.go:749]: `func(g gomega.Gomega)` version gives better assertion reports on failure wjile the both of them are doing the same thing

Comment (tenzen-y) [reply test/integration/controller/core/clusterqueue_controller_test.go:749]: I'm ok with using `func(g gomega.Gomega)`. However, I don't find this way only here.
So, if you believe that this way is much better, I would suggest replacing `func() bool` with this way in all places as a follow up.

This means that I think we should use `func() bool` in this PR.

**Comment by tenzen-y** [comment]
> How does the workload-controller find that the cq is terminating?
IIUC, the cq-controller doesn't send a generic event to the workload-controller.

@trasc How about this?

File: pkg/controller/core/workload_controller.go [hunk 4]
```diff
@@ -159,6 +159,11 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 		if evictionTriggered, err := r.reconcileCheckBasedEviction(ctx, &wl); evictionTriggered || err != nil {
 			return ctrl.Result{}, err
 		}
+
+		if reservationRemoved, err := r.reconcileReservationOnQueueDeletion(ctx, &wl, cqName); reservationRemoved || err != nil {
+			return ctrl.Result{}, err
+		}
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller.go:165]: Uhm, I'm wondering if we should do this confirmation in L135. Because if the `reservationRemoved` is `true`, any other processes aren't needed.

WDYT?

**Comment by trasc** [comment]
> > How does the workload-controller find that the cq is terminating?
> > IIUC, the cq-controller doesn't send a generic event to the workload-controller.
> 
> @trasc How about this?

The workload controller is whacking the clusterQueues to keep the admission checks in sync.

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (trasc) [reply pkg/controller/core/workload_controller.go:165]: It was added here to have the "has reservations" cases grouped.

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 3 above)
Comment (trasc) [reply test/integration/controller/core/clusterqueue_controller_test.go:749]: we are using `func(g gomega.Gomega)` in other places already

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/controller/core/workload_controller.go:165]: why not before `reconcileCheckBasedEviction`?

File: pkg/controller/core/workload_controller.go [hunk 5]
```diff
@@ -216,6 +221,25 @@ func (r *WorkloadReconciler) reconcileSyncAdmissionChecks(ctx context.Context, w
 	return false, nil
 }
 
+func (r *WorkloadReconciler) reconcileReservationOnQueueDeletion(ctx context.Context, wl *kueue.Workload, cqName string) (bool, error) {
+	if workload.IsAdmitted(wl) {
+		return false, nil
+	}
+
+	queue := kueue.ClusterQueue{}
+	if err := r.client.Get(ctx, types.NamespacedName{Name: cqName}, &queue); err != nil {
```
Comment (alculquicondor) [inline pkg/controller/core/workload_controller.go:230]: just in case, also remove the reservation if this returns a NotFound error

File: pkg/controller/core/workload_controller.go [hunk 6]
```diff
@@ -571,7 +595,7 @@ func (w *workloadCqHandler) Update(ctx context.Context, ev event.UpdateEvent, wq
 	log.V(5).Info("Workload cluster queue update event")
 	oldCq, oldIsQueue := ev.ObjectOld.(*kueue.ClusterQueue)
 	newCq, newIsQueue := ev.ObjectNew.(*kueue.ClusterQueue)
-	if oldIsQueue && newIsQueue && !slices.CmpNoOrder(oldCq.Spec.AdmissionChecks, newCq.Spec.AdmissionChecks) {
+	if oldIsQueue && newIsQueue && (!slices.CmpNoOrder(oldCq.Spec.AdmissionChecks, newCq.Spec.AdmissionChecks) || !newCq.DeletionTimestamp.IsZero()) {
```
Comment (alculquicondor) [inline pkg/controller/core/workload_controller.go:598]: for readability, it's useful to have something like: `if !oldIsQueue || !newIsQueue { return }`.

It makes it clear that we are exiting because basic checks are not satisified.

But since it's just one line after the check, this is acceptable.

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 3 above)
Comment (alculquicondor) [reply test/integration/controller/core/clusterqueue_controller_test.go:749]: I prefer `func(g gomega.Gomega)`. It will give better error reporting than returning `bool`. I just didn't know this was possible before.

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 2 above)
Comment (alculquicondor) [reply test/integration/controller/core/clusterqueue_controller_test.go:735]: For the purpose of not enlarging the suite indefinitely, I think this is fine.

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 7]
```diff
@@ -708,28 +709,44 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Ordered, ginkgo.Contin
...
 
 		ginkgo.It("Should be stuck in termination until admitted workloads finished running", func() {
+			util.SetAdmissionCheckActive(ctx, k8sClient, check, metav1.ConditionTrue)
 			util.ExpectClusterQueueStatusMetric(cq, metrics.CQStatusActive)
 
 			ginkgo.By("Admit workload")
 			wl := testing.MakeWorkload("workload", ns.Name).Queue(lq.Name).Obj()
 			gomega.Expect(k8sClient.Create(ctx, wl)).To(gomega.Succeed())
 			gomega.Expect(util.SetQuotaReservation(ctx, k8sClient, wl, testing.MakeAdmission(cq.Name).Obj())).To(gomega.Succeed())
+			util.SetWorkloadsAdmissionCkeck(ctx, k8sClient, wl, check.Name, kueue.CheckStateReady, true)
```
Comment (alculquicondor) [inline test/integration/controller/core/clusterqueue_controller_test.go:743]:
```suggestion
			util.SetWorkloadsAdmissionCheck(ctx, k8sClient, wl, check.Name, kueue.CheckStateReady, true)
```

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 8]
```diff
@@ -708,28 +709,44 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Ordered, ginkgo.Contin
...
+			gomega.Eventually(func(g gomega.Gomega) {
```
Comment (alculquicondor) [inline test/integration/controller/core/clusterqueue_controller_test.go:744]: We didn't get the method for WaitForWorkloadToBeAdmitted back? If not, we can leave it for a follow up.

**Review by alculquicondor — COMMENTED** [review]
Almost ready

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 3 above)
Comment (tenzen-y) [reply test/integration/controller/core/clusterqueue_controller_test.go:749]: > we are using func(g gomega.Gomega) in other places already

I didn't find that this way has already been used. If so, I'm ok.

**Comment by tenzen-y** [comment]
> > > How does the workload-controller find that the cq is terminating?
> > > IIUC, the cq-controller doesn't send a generic event to the workload-controller.
> > 
> > 
> > @trasc How about this?
> 
> The workload controller is whacking the clusterQueues to keep the admission checks in sync.

Ah, sorry. The workload controller watches ClusterQueues.

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:165]: > It was added here to have the "has reservations" cases grouped.

This sounds fine.

This is just a comment, we need to wait for the next reconciliation triggered by workload's `conditions` updating if `SyncAdmittedCondition` returns true.

File: pkg/controller/core/workload_controller.go (hunk 1 above)
Comment (trasc) [reply pkg/controller/core/workload_controller.go]: done

File: pkg/controller/core/workload_controller.go (hunk 5 above)
Comment (trasc) [reply pkg/controller/core/workload_controller.go]: done

File: pkg/controller/core/workload_controller.go (hunk 6 above)
Comment (trasc) [reply pkg/controller/core/workload_controller.go]: done

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 7 above)
Comment (trasc) [reply test/integration/controller/core/clusterqueue_controller_test.go]: done

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 8 above)
Comment (trasc) [reply test/integration/controller/core/clusterqueue_controller_test.go:744]: it's in #1241

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 3 above)
Comment (trasc) [reply test/integration/controller/core/clusterqueue_controller_test.go:749]: https://github.com/kubernetes-sigs/kueue/blob/25b6dbfe30d04d970e38c0d203003f0acf72d7ed/test/util/util.go#L465-L481

Comment (tenzen-y) [reply test/integration/controller/core/clusterqueue_controller_test.go:749]: Thanks for pointing this out.
