### PR TITLE
Validate prebuilt workload for Pod groups.

### LINKED ISSUE #4113: [Flaky test] Pod controller when manageJobsWithoutQueueName is disabled when Using pod group Should ungate pods with prebuild workload
/kind flake

**What happened**:

The test failed on periodic build of main branch: https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-integration-main

Image

**What you expected to happen**:

No failures

**How to reproduce it (as minimally and precisely as possible)**:

Run CI

**Anything else we need to know?**:

This is a new test introduced in https://github.com/kubernetes-sigs/kueue/pull/4023

```
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:767 with:
Expected
    <[]v1.PodSchedulingGate | len:1, cap:1>: [
        {
            Name: "kueue.x-k8s.io/admission",
        },
    ]
not to contain element matching
    <v1.PodSchedulingGate>: {
        Name: "kueue.x-k8s.io/admission",
    } failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:767 with:
Expected
    <[]v1.PodSchedulingGate | len:1, cap:1>: [
        {
            Name: "kueue.x-k8s.io/admission",
        },
    ]
not to contain element matching
    <v1.PodSchedulingGate>: {
        Name: "kueue.x-k8s.io/admission",
    }
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go:1655 @ 01/30/25 18:22:28.131
}
```

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:
- Fix "Should ungate pods with prebuild workload" integration test.
- Add validation for prebuilt workloads in Pod groups to ensure that the prebuilt workload name cannot be different from the workload name.

#### Which issue(s) this PR fixes:

Fixes #4113

#### Special notes for your reviewer:

When updating the Workload, we should catch an event to trigger the PodReconciler.

We send this event here 

https://github.com/kubernetes-sigs/kueue/blob/c74db07260c20ff8a4e3a611b9ac20f5b1f48582/pkg/controller/jobs/pod/event_handlers.go#L150-L153 

But the problem is that we send the group name instead of the prebuilt Workload name.

And here

https://github.com/kubernetes-sigs/kueue/blob/c74db07260c20ff8a4e3a611b9ac20f5b1f48582/pkg/controller/jobs/pod/pod_controller.go#L614-L618

we will not find it due to workload name different.

To fix this, I propose restricting users from setting different names for the Pod group and the prebuilt workload.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
/hold
 I'm suspecting there might be some issue with the way the test is written, not the production code, because the issue does not surface on the LWS e2e tests which are using the same mechanism. I would like to first understand the problem why the test flakes. 
 
 I don't think a release note is needed since LWS is not released yet.

**Comment by mbobrovskyi** [comment]
> Can we please document/add a comment that if a users wants to use PodGroup with PrebuiltWorkload than the those should be the same? Other than that LGTM

Done

**Comment by mimowo** [comment]
/hold
for the verify fixes

**Review by mimowo — COMMENTED** [review]
/lgtm 
Thanks!

File: pkg/controller/jobs/pod/pod_webhook.go [hunk 1]
```diff
@@ -361,3 +363,13 @@ func validateUpdateForRetriableInGroupAnnotation(oldPod, newPod *Pod) field.Erro
 
 	return field.ErrorList{}
 }
+
+func validatePrebuiltWorkloadName(pod *Pod) field.ErrorList {
+	allErrs := field.ErrorList{}
```
Comment (tenzen-y) [inline pkg/controller/jobs/pod/pod_webhook.go:368]: This is a nit comment.

The `field.ErrorList` is a sllice. 
So it would be better not to initialize it with an empty slice.

Comment (tenzen-y) [reply pkg/controller/jobs/pod/pod_webhook.go:368]: I opened a fixing PR: https://github.com/kubernetes-sigs/kueue/pull/4526
