### PR TITLE
[cmd/kueue] Use a single rate limiter across all API types.

### LINKED ISSUE #2423: ClientConnection.QPS applies to individual API types
**What happened**:
When setting [ClientConnection.QPS](https://github.com/kubernetes-sigs/kueue/blob/e8e0810115f3bef7518b4c07eb4c2e2579660060/apis/config/v1beta1/configuration_types.go#L301), the limit applies to each type (e.g. pod, workload, status, clusterqueue, etc)

**What you expected to happen**:
This should be a global limit. Otherwise, it is hard for administrators to know exactly how many queries per second Kueue will be making to the API Server.

**How to reproduce it (as minimally and precisely as possible)**:
Set to a very low limit (e.g. 1), with burst set to same as the limit. Observe that Kueue is making more than 1 call per second to the API Server.

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Use a single rate limiter across all API types.

#### Which issue(s) this PR fixes:

Fixes #2423

#### Does this PR introduce a user-facing change?

```release-note
Use a single rate limiter for all API types clients.

ACTION REQUIRED: Consider adjusting `clientConnection.qps` and `clientConnection.burst` if you observe any performance degradation.
```

### CODE REVIEW

File: cmd/kueue/main.go [hunk 1]
```diff
@@ -135,9 +136,11 @@ func main() {
...
 		kubeConfig.UserAgent = useragent.Default()
 	}
-	kubeConfig.QPS = *cfg.ClientConnection.QPS
-	kubeConfig.Burst = int(*cfg.ClientConnection.Burst)
-	setupLog.V(2).Info("K8S Client", "qps", kubeConfig.QPS, "burst", kubeConfig.Burst)
+
+	// Set the RateLimiter here, otherwise the controller-runtime's typedClient will use a different RateLimiter
+	// for each API type.
+	kubeConfig.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(*cfg.ClientConnection.QPS, int(*cfg.ClientConnection.Burst))
+	setupLog.V(2).Info("K8S Client", "qps", *cfg.ClientConnection.QPS, "burst", *cfg.ClientConnection.Burst)
```
Comment (trasc) [inline cmd/kueue/main.go:143]: @alculquicondor @tenzen-y Do you think it can help us to create a config for the scope of the rate limiting settings (global vs per API type)?

Comment (alculquicondor) [reply cmd/kueue/main.go:143]: I would like to avoid adding configuration overhead.

This LGTM. I would just add an `ACTION REQUIRED` in the release note to adjust the qps.

**Comment by alculquicondor** [comment]
/lgtm
/approve
/hold
in case @tenzen-y disagrees

File: cmd/kueue/main.go (hunk 1 above)
Comment (tenzen-y) [reply cmd/kueue/main.go:143]: LGTM
One thing is documentation. Actually, we don't have docs on how to tune kueue-controller-managers client configurations, iiuc.

but, that is out of scope of this PR.

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve
/hold cancel
