### PR TITLE
Fix the flaky test for resources

### LINKED ISSUE #7935: [flaky test] SchedulerWithExcludeResourcePrefixes should use exact prefix matching
**What happened**:

failure: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7933/pull-kueue-test-integration-baseline-main/1993948535971647488

**What you expected to happen**:

no flake

**How to reproduce it (as minimally and precisely as possible)**:

ci
**Anything else we need to know?**:
```
Scheduler with Exclude Resource Prefixes Suite: [It] SchedulerWithExcludeResourcePrefixes should use exact prefix matching expand_less	1s
{failed to run manager
Unexpected error:
    <*net.OpError | 0xc0006c1ea0>: 
    listen tcp 127.0.0.1:33465: bind: address already in use
    {
        Op: "listen",
        Net: "tcp",
        Source: nil,
        Addr: <*net.TCPAddr | 0xc0014127e0>{
            IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1],
            Port: 33465,
            Zone: "",
        },
        Err: <*os.SyscallError | 0xc0013288a0>{
            Syscall: "bind",
            Err: <syscall.Errno>0x62,
        },
    }
occurred failed [FAILED] failed to run manager
Unexpected error:
    <*net.OpError | 0xc0006c1ea0>: 
    listen tcp 127.0.0.1:33465: bind: address already in use
    {
        Op: "listen",
        Net: "tcp",
        Source: nil,
        Addr: <*net.TCPAddr | 0xc0014127e0>{
            IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1],
            Port: 33465,
            Zone: "",
        },
        Err: <*os.SyscallError | 0xc0013288a0>{
            Syscall: "bind",
            Err: <syscall.Errno>0x62,
        },
    }
occurred
In [It] at: /usr/local/go/src/runtime/asm_amd64.s:1693 @ 11/27/25 08:00:00.616
}
```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind failing-test
/kind flake

#### Which issue(s) this PR fixes:

Fixes #7935

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/scheduler/excluderesources/scheduler_test.go [hunk 1]
```diff
@@ -77,6 +77,7 @@ var _ = ginkgo.Describe("SchedulerWithExcludeResourcePrefixes", func() {
 		gomega.Expect(util.DeleteNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
 		util.ExpectObjectToBeDeleted(ctx, k8sClient, cq, true)
 		util.ExpectObjectToBeDeleted(ctx, k8sClient, defaultFlavor, true)
+		fwk.StopManager(ctx)
```
Comment (mbobrovskyi) [inline test/integration/singlecluster/scheduler/excluderesources/scheduler_test.go:80]: For follow-up I think we can move it to BeforeAll and AfterAll.

Comment (mimowo) [reply test/integration/singlecluster/scheduler/excluderesources/scheduler_test.go:80]: yes, good idea
