### PR TITLE
Reset all Ready and Ready AdmissionChecks on Eviction as Pending

### LINKED ISSUE #3322: Workload is stuck after one of the AdmissionCheck is in `Retry` state
**What happened**:
After one of the AdmissionCheck was set to `Retry` state, Workload get evicted and never requeued again.

**What you expected to happen**:
Requeue immediately or after some backoff time - depending on the `.status.requeueState.requeuAt`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Currently, when AdmissionCheck is in `Retry` state, the Workloads gets evicted and there's no actual retry. The changes improves that flow, changing all AdmissionChecks to `Pending` if one of them is in `Retry` state (unless there's a `Rejected` AdmissionCheck).

#### Which issue(s) this PR fixes:

Fixes #3322 

#### Does this PR introduce a user-facing change?

```release-note
Workload is requeued with all AdmissionChecks set to Pending if there was an AdmissionCheck in Retry state.
```

### CODE REVIEW

File: pkg/controller/core/workload_controller.go [hunk 1]
```diff
@@ -164,7 +164,7 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 			case kueue.WorkloadEvictedByDeactivation:
 				workload.SetRequeuedCondition(&wl, kueue.WorkloadReactivated, "The workload was reactivated", true)
 				updated = true
-			case kueue.WorkloadEvictedByPodsReadyTimeout:
+			case kueue.WorkloadEvictedByPodsReadyTimeout, kueue.WorkloadEvictedByAdmissionCheck:
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:167]: I'm wondering if this change belong conceptually to the same fix.
IIUC the intention of this change (and the one below 
```
// The requeued condition status set to true only on EvictedByPreemption
setRequeued := evCond.Reason == kueue.WorkloadEvictedByPreemption
```
IIUC they are aiming to "respect backoff delay when requeuing due to failed admission checks", and could be a separate bugfix. Let me know if I'm missing something.

Comment (PBundyra) [reply pkg/controller/core/workload_controller.go]: That's right, fixed

File: pkg/workload/workload.go [hunk 2]
```diff
@@ -649,6 +649,11 @@ func ApplyAdmissionStatusPatch(ctx context.Context, c client.Client, patch *kueu
 	return c.Status().Patch(ctx, patch, client.Apply, client.FieldOwner(constants.AdmissionName))
 }
 
+// ApplyStatusPatch applies the patch of status fields of a workload with SSA.
+func ApplyStatusPatch(ctx context.Context, c client.Client, patch *kueue.Workload) error {
+	return c.Status().Patch(ctx, patch, client.Apply, client.FieldOwner(constants.WorkloadControllerName))
```
Comment (mimowo) [inline pkg/workload/workload.go:654]: I'm wondering if we need another entity to make the patch. What is the entity managing status Workload fields like `status.requeueState`, or changing the readiness of checks when transitioning from Pending -> Ready or Rejected?

Comment (PBundyra) [reply pkg/workload/workload.go:654]: Regarding `status.requeueState` the entity is `kueue-admission`, and for transitions e.g. Pending -> Ready it's `kueue.x-k8s.io/provisioning-request`. Hence, I decided to go with `kueue-workload-controller` since this is the controller that calls this function. We can come up with some more consitent semantics for the field owners, but I believe this is out of the scope of this PR. WDYT?

File: pkg/controller/core/workload_controller.go [hunk 3]
```diff
@@ -346,6 +346,9 @@ func (r *WorkloadReconciler) reconcileCheckBasedEviction(ctx context.Context, wl
 	if err := workload.ApplyAdmissionStatus(ctx, r.client, wl, true); err != nil {
 		return false, client.IgnoreNotFound(err)
 	}
+	if err := workload.SetAllChecksToPending(ctx, r.client, wl); err != nil {
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:349]: Actually, I think it is better to update the state for the checks just after `workload.SetEvictedCondition(wl, kueue.WorkloadEvictedByAdmissionCheck, message)`, and submit in the `ApplyAdmissionStatus`, because now it requires to Patches, and both update the status.

File: pkg/workload/workload.go (hunk 2 above)
Comment (mimowo) [reply pkg/workload/workload.go:654]: I see, this is fine from that perspective, but maybe we don't need to think about it if we update the checks along with setting Evicted=true, as in the other comment: https://github.com/kubernetes-sigs/kueue/pull/3323/files#r1818884218?

File: pkg/controller/core/workload_controller.go (hunk 3 above)
Comment (PBundyra) [reply pkg/controller/core/workload_controller.go]: Agree, fixed

File: pkg/workload/workload.go (hunk 2 above)
Comment (PBundyra) [reply pkg/workload/workload.go]: Done

File: pkg/controller/core/workload_controller.go [hunk 4]
```diff
@@ -380,6 +380,7 @@ func (r *WorkloadReconciler) reconcileCheckBasedEviction(ctx context.Context, wl
 	// at this point we know a Workload has at least one Retry AdmissionCheck
 	message := "At least one admission check is false"
 	workload.SetEvictedCondition(wl, kueue.WorkloadEvictedByAdmissionCheck, message)
+	workload.SetAllChecksToPending(wl, "AdmissionCheck pending after retry")
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:383]: It is not necessarily "after retry" as ready checks can also be flipped. I would move the message construction under the function as it potentially could differ.

File: pkg/workload/admissionchecks.go [hunk 5]
```diff
@@ -86,6 +86,19 @@ func FindAdmissionCheck(checks []kueue.AdmissionCheckState, checkName string) *k
...
 
+// SetAllChecksToPending sets all AdmissionChecks to Pending
+func SetAllChecksToPending(w *kueue.Workload, message string) {
+	checks := w.Status.AdmissionChecks
+	for i := range checks {
+		checks[i] = kueue.AdmissionCheckState{
+			Name:               checks[i].Name,
+			State:              kueue.CheckStatePending,
+			LastTransitionTime: metav1.NewTime(time.Now()),
+			Message:            message,
```
Comment (mimowo) [inline pkg/workload/admissionchecks.go:97]: Maybe just say "Reset to Pending due to eviction. Previously: <reason>"

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (PBundyra) [reply pkg/controller/core/workload_controller.go:383]: Done

File: pkg/workload/admissionchecks.go (hunk 5 above)
Comment (PBundyra) [reply pkg/workload/admissionchecks.go:97]: Done

File: pkg/controller/core/workload_controller.go [hunk 6]
```diff
@@ -380,7 +380,7 @@ func (r *WorkloadReconciler) reconcileCheckBasedEviction(ctx context.Context, wl
 	// at this point we know a Workload has at least one Retry AdmissionCheck
 	message := "At least one admission check is false"
 	workload.SetEvictedCondition(wl, kueue.WorkloadEvictedByAdmissionCheck, message)
-	workload.SetAllChecksToPending(wl, "AdmissionCheck pending after retry")
+	workload.SetAllChecksToPending(wl, "Reset to Pending after eviction. Previously: ")
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:383]:
```suggestion
	workload.ResetChecksOnEviction(wl)
```
nit, I think constructing the message prefix makes it a bit weird to follow

Comment (PBundyra) [reply pkg/controller/core/workload_controller.go]: Done

**Comment by mimowo** [comment]
/lgtm
/approve
Thanks!

**Comment by mimowo** [comment]
/retitle Reset all Ready and Ready AdmissionChecks on Eviction as Pending

**Comment by mimowo** [comment]
I think we actually need to reset the checks regardless of the reason of eviction. For example, if the checks passed, but the workload is evicted due to WaitForPodsReady?

**Comment by mimowo** [comment]
When deactivating (evicting with deactivation reason) a workload we reset the `requeueState` so that it is "clean" or re-activation: https://github.com/kubernetes-sigs/kueue/blob/42c7b476ac13dbf2d494227ca831b91f262fa07e/pkg/controller/core/workload_controller.go#L203-L206

I think for consistency we should do the same with checks, but we can re-visit this as a follow up.

/lgtm
/approve
/hold cancel

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 7]
```diff
@@ -447,6 +447,7 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
 
 				gomega.Eventually(func(g gomega.Gomega) {
 					g.Expect(k8sClient.Get(ctx, wlKey, &updatedWl)).To(gomega.Succeed())
+					fmt.Printf("Workload %+v\n", updatedWl)
```
Comment (tenzen-y) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:450]: @PBundyra Could you remove this debug log?

**Comment by tenzen-y** [comment]
It seems that this is obviously bug.
/cherry-pick release-0.8

**Comment by mimowo** [comment]
> /cherry-pick release-0.8

I guess we could cherry-pick but then we also need to cherry-pick the forced-ownership PR which might be more that we want.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 7 above)
Comment (PBundyra) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:450]: Sure, will do in a follow-up

Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:450]: This is needed for cheery picking to 0.8.2

Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:450]: taken that: https://github.com/kubernetes-sigs/kueue/pull/3389
