### PR TITLE
Fix flaky workload retention test after manager restart

### LINKED ISSUE #9358: Flaky Test: Workload controller with resource retention when manager is setup with long retention period should not delete the workload before retention period elapses [slow]
**Which test is flaking?**:
Flaky Test: Workload controller with resource retention when manager is setup with long retention period should not delete the workload before retention period elapses [slow]

**Link to failed CI job or steps to reproduce locally**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9321/pull-kueue-test-integration-extended-main/2023776846776111104

**Failure message or logs**:
```
Core Controllers Suite: [It] Workload controller with resource retention when manager is setup with long retention period should not delete the workload before retention period elapses [slow] expand_less	15s
{Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/metrics.go:293 with:
Expected
    <float64>: 1
to equal
    <float64>: 0 failed [FAILED] Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/metrics.go:293 with:
Expected
    <float64>: 1
to equal
    <float64>: 0
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/core/workload_controller_test.go:1043 @ 02/17/26 15:17:39.147
}
```

### PR DESCRIPTION
**Pull request by sohankunkerkar**
Adds a controller-readiness barrier after restartManager() to ensure controllers are processing events before deleting the workload. Without this, gauge metric assertions passed from stale prometheus state, allowing the delete to race ahead of controller startup.

#### What type of PR is this?
/kind flake

#### Which issue(s) this PR fixes:

Fixes #9358

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/controller/core/workload_controller_test.go [hunk 1]
```diff
@@ -1027,6 +1027,21 @@ var _ = ginkgo.Describe("Workload controller with resource retention", ginkgo.Or
 				restartManager()
 			})
 
+			ginkgo.By("waiting for workload controller to be active after restart", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/controller/core/workload_controller_test.go:1030]: Interesting, is my understanding correct this flake happens when we get event about Workloads after events for the LocalQueue, and in this case the metric update for LQ does not yet see all the Workloads.

If this is the case, then I agree this is a low priority issue, because any LQ update will fix the inaccurate metric, and I'm ok with the pragmatic fix for the tests. 

However, I would like to request:
1. verify on some experiment PR it works if looped 200 times
2. open a follow up issue to "ensure the LQ metrics are accurate after Kueue restart"

Also, have you got a chance to investigate what it would entail to fix properly?

Comment (sohankunkerkar) [reply test/integration/singlecluster/controller/core/workload_controller_test.go:1030]: >Interesting, is my understanding correct this flake happens when we get event about Workloads after events for the LocalQueue, and in this case the metric update for LQ  does not yet see all the Workloads.
  
Close but not quite. The event ordering is handled correctly by AddLocalQueue/AddClusterQueue which cross-reference each other. The root cause is that after an in-process restart, prometheus gauges retain stale values from the old manager, so Eventually(gauge == 1) passes instantly without waiting for controllers to start. The delete then races ahead of `m.finishedWorkloads` being populated.

>If this is the case, then I agree this is a low priority issue, because any LQ update will fix the inaccurate metric, and I'm ok with the pragmatic fix for the tests.

Agreed. There's no long-term consistency issue. The gauges converge after both event handlers complete. There's a possible transient startup window where the gauge may be briefly inaccurate, but no corruption or permanent drift.

> verify on some experiment PR it works if looped 200 times

I usually put a up PR after this testing. I will add a short note next time when I create a similar PR.

> open a follow up issue to "ensure the LQ metrics are accurate after Kueue restart"

IIUC, in production, process restart zeroes prometheus, so this race can't happen. The transient startup inconsistency resolves within milliseconds as controllers initialize. I don't think a follow-up is needed.

> Also, have you got a chance to investigate what it would entail to fix properly?

Yes, I didn't dig deeper but it would mean either resetting finished workload gauges in NewManager or re-reporting them after all sources sync. Both are narrow but touch metric lifecycle for a transient window with no real-world impact. IMO, the test-side fix with the probe workload barrier is the right scope for this issue.

**Comment by mimowo** [comment]
Thank you ! 
/lgtm
/approve
/cherrypick release-0.16
/cherrypick release-0.15
