### PR TITLE
Wait for ClusterQueue and LocalQueue for StatefulSet tests

### LINKED ISSUE #5041: Flaky E2E Test: StatefulSet integration when StatefulSet created should allow to change queue name if ReadyReplicas=0
**What happened**:

End To End Suite: kindest/node:v1.30.10: [It] StatefulSet integration when StatefulSet created should allow to change queue name if ReadyReplicas=0

```
{Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/statefulset_test.go:375 with:
Expected
    <int32>: 0
to equal
    <int32>: 3 failed [FAILED] Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/statefulset_test.go:375 with:
Expected
    <int32>: 0
to equal
    <int32>: 3
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/statefulset_test.go:376 @ 04/18/25 07:24:31.271
}
```

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5030/pull-kueue-test-e2e-main-1-30/1913127191198044160

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
We find this test to be very flaky in our downstream testing. We had to disable it.

I was seeing that increasing the timeout for this seems to have helped.
#### Which issue(s) this PR fixes:

Fixes #5041 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/singlecluster/statefulset_test.go [hunk 1]
```diff
@@ -69,8 +69,10 @@ var _ = ginkgo.Describe("StatefulSet integration", func() {
 			}).
 			Obj()
 		util.MustCreate(ctx, k8sClient, cq)
+		util.ExpectClusterQueuesToBeActive(ctx, k8sClient, cq)
 
 		lq = testing.MakeLocalQueue(localQueueName, ns.Name).ClusterQueue(cq.Name).Obj()
+		util.ExpectLocalQueuesToBeActive(ctx, k8sClient, lq)
```
Comment (mimowo) [inline test/e2e/singlecluster/statefulset_test.go]: This should be after create

Comment (kannon92) [reply test/e2e/singlecluster/statefulset_test.go]: doh!

fixed.

**Comment by mbobrovskyi** [comment]
/lgtm
Thank you!

**Comment by kannon92** [comment]
@mimowo 

Thank you for carrying those changes.

I opened up https://github.com/kubernetes-sigs/kueue/pull/6190.
