### PR TITLE
Fix fungibility: Try next flavor if can't preempt on first

### LINKED ISSUE #1344: ClusterQueue not considering next ResourceFlavor when whenCanPreempt: Preempt is set
**What happened**:

Setting `whenCanPreempt: Preempt` in a ClusterQueue with 2 resource flavors appears to stop the ClusterQueue from considering the 2nd resource flavor.

**How to reproduce it (as minimally and precisely as possible)**:

* Created a cluster queue with 2 resource flavors
* Each resource flavor has quota for 2 cpus
* Submitting 3 jobs that require 1 cpu each (via Job or plain Pod API) will result in 2 being admitted and 1 not

NOTE: ClusterQueue is configured as follows:

```yaml
  preemption:
    reclaimWithinCohort: Any
    withinClusterQueue: LowerOrNewerEqualPriority
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: Preempt
```

**What you expected to happen**:

All 3 jobs should be admitted (quota from resource flavor 2 should be used).

**Anything else we need to know?**:

Condition of non-admitted Workload:

```
status:
  conditions:
  - lastTransitionTime: "2023-11-17T22:37:24Z"
    message: 'couldn''t assign flavors to pod set main: borrowing limit for cpu in
      flavor flav-1 exceeded'
    reason: Pending
    status: "False"
    type: QuotaReserved
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3-gke.100", GitCommit:"6466b51b762a5c49ae3fb6c2c7233ffe1c96e48c", GitTreeState:"clean", BuildDate:"2023-06-23T09:27:28Z", GoVersion:"go1.20.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
- Kueue version (use `git describe --tags --dirty --always`): Built from main (commit `4405e35b51bb153611e0a01f48884aa2c131055c` - deployed with manifests from `0.5.0`)
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR fixes 3 problems:
- The AllocatableResourceGeneration for a ClusterQueue was changing for unrelated status updates (Thanks to @KunWuLuan for this fix)
- Needed to requeue immediately if there are pending flavors to try.
- The indexes for the lastattempt were accumulating across scheduling attempts.

#### Which issue(s) this PR fixes:

Fixes #1344

#### Special notes for your reviewer:

This supersedes #1356.

I want to add more tests before merging.

#### Does this PR introduce a user-facing change?

```release-note
Fix fungibility policy `Preempt` where it was not able to utilize the next flavor if preemption was not possible.
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/hold
I want to add a few unit tests.

File: pkg/scheduler/flavorassigner/flavorassigner.go [hunk 1]
```diff
@@ -256,18 +269,14 @@ func assignFlavors(log logr.Logger, requests []workload.PodSetResources, podSets
 		TotalBorrow: make(cache.FlavorResourceQuantities),
 		PodSets:     make([]PodSetAssignment, 0, len(requests)),
 		Usage:       make(cache.FlavorResourceQuantities),
-	}
-	if lastAssignment != nil {
-		assignment.LastState = *lastAssignment
-	} else {
-		assignment.LastState = workload.AssigmentClusterQueueState{
+		LastState: workload.AssigmentClusterQueueState{
```
Comment (tenzen-y) [inline pkg/scheduler/flavorassigner/flavorassigner.go:272]: Why don't we set the `lastAssignment` to the `assignment.LastState` when the `lastAssignment` isn't nil?
IIUC, we can use the `lastAssignment` since the `lastAssignment` is the latest, not outdated here.

File: pkg/queue/cluster_queue_impl.go [hunk 2]
```diff
@@ -142,7 +142,7 @@ func (c *clusterQueueBase) requeueIfNotPresent(wInfo *workload.Info, immediate b
 	c.rwm.Lock()
 	defer c.rwm.Unlock()
 	key := workload.Key(wInfo.Obj)
-	if immediate || c.queueInadmissibleCycle >= c.popCycle {
+	if immediate || c.queueInadmissibleCycle >= c.popCycle || wInfo.LastAssignment.PendingFlavors() {
```
Comment (tenzen-y) [inline pkg/queue/cluster_queue_impl.go:145]: Oh, this fix is great to see. I couldn't find this hidden bug.

File: pkg/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -1284,14 +1309,98 @@ func TestEntryOrdering(t *testing.T) {
...
+		cq                           *kueue.ClusterQueue
+		newcq                        *kueue.ClusterQueue
+		wantLastAssignmentGeneration int64
+	}{
+		{
+			name:                         "RGs not change",
+			cq:                           &clusterQueue,
+			newcq:                        clusterQueue.DeepCopy(),
+			wantLastAssignmentGeneration: 1,
+		},
```
Comment (tenzen-y) [inline pkg/scheduler/scheduler_test.go:1358]: It's a great test case.

**Review by tenzen-y — COMMENTED** [review]
/lgtm

I left just a question.

**Comment by alculquicondor** [comment]
/hold
I want to add more tests before merging. Just to make sure there aren't more surprises.
