### PR TITLE
Trigger cq reconciliation on snapshot change

### LINKED ISSUE #1122: Flaky: Should update of the pending workloads when a new workload is scheduled
**What happened**:

```shell
Core Controllers Suite: [It] ClusterQueue controller when Reconciling clusterQueue pending workload status Should update of the pending workloads when a new workload is scheduled 
{Timed out after 30.000s.
  &v1beta1.ClusterQueuePendingWorkloadsStatus{
  	Head: []v1beta1.ClusterQueuePendingWorkload{
+ 		{Name: "three", Namespace: "core-clusterqueue-thrgz"},
+ 		{Name: "four", Namespace: "core-clusterqueue-thrgz"},
  	},
  	... // 1 ignored field
  }
 failed [FAILED] Timed out after 30.000s.
  &v1beta1.ClusterQueuePendingWorkloadsStatus{
  	Head: []v1beta1.ClusterQueuePendingWorkload{
+ 		{Name: "three", Namespace: "core-clusterqueue-thrgz"},
+ 		{Name: "four", Namespace: "core-clusterqueue-thrgz"},
  	},
  	... // 1 ignored field
  }
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/controller/core/clusterqueue_controller_test.go:810 @ 09/14/23 05:03:31.307
}
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1118/pull-kueue-test-integration-main/1702185468826750976

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind flake

#### Which issue(s) this PR fixes:

Fixes #1122

#### Special notes for your reviewer:

When the snapshot is updated it triggers reconciliation, when the next status update is expected.

Tested by running in a loop and no flakes after 100 repeats

I have disabled the check for time https://github.com/kubernetes-sigs/kueue/blob/ee5b6ba29a1bbed1574262e362182573c5f6fa5e/pkg/controller/core/clusterqueue_controller.go#L603. With this check the test flakes, as there is a possibility, that the last reconciliation is triggered by snapshot updated, and `< UpdateInterval`, so it would not result in queue change. Further, the next snapshot check would not trigger another reconciliation as the snapshot is not changed. I think we can improve the behavior by marking a snapshot by snapshot revisions (1, 2, 3...). Then, we could skip comparing the contents of the snapshot and queue if the current snapshot used by cluster queue has revision >= the revision of the snapshot in manager. Ticketed: https://github.com/kubernetes-sigs/kueue/issues/1138.

Bumped the update interval to 2s to make the test fail almost every time on master, while currently it passes almost every time.

#### Does this PR introduce a user-facing change?

```release-note
Ensure the Cluster queue status with pending workloads is changed
```

### CODE REVIEW

File: pkg/queue/manager.go [hunk 1]
```diff
@@ -569,25 +570,32 @@ func (m *Manager) getClusterQueue(cqName string) ClusterQueue {
 	return m.clusterQueues[cqName]
 }
 
-func (m *Manager) UpdateSnapshot(cqName string, maxCount int32) {
+// UpdateSnapshot computes the new snapshot and replaces if it differs from the
+// pevious version. It returns true if the snapshot was actually updated.
```
Comment (alculquicondor) [inline pkg/queue/manager.go:574]:
```suggestion
// previous version. It returns true if the snapshot was actually updated.
```

File: test/integration/controller/core/suite_test.go [hunk 2]
```diff
@@ -75,7 +75,7 @@ func managerSetup(mgr manager.Manager, ctx context.Context) {
 	controllersCfg := &config.Configuration{}
 	controllersCfg.Metrics.EnableClusterQueueResources = true
 	controllersCfg.QueueVisibility = &config.QueueVisibility{
-		UpdateIntervalSeconds: 1,
+		UpdateIntervalSeconds: 2,
```
Comment (alculquicondor) [inline test/integration/controller/core/suite_test.go:78]: why change this?

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 3]
```diff
@@ -798,11 +801,11 @@ var _ = ginkgo.Describe("ClusterQueue controller", func() {
 				},
 			}, ignoreLastChangeTime))
 
-			ginkgo.By("Finishing workload", func() {
```
Comment (alculquicondor) [inline test/integration/controller/core/clusterqueue_controller_test.go:801]: I guess we are not being very consistent, but the idea of putting things inside a function seems visually useful. I would just revert.

File: test/integration/controller/core/suite_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/controller/core/suite_test.go:78]: Bumped the update interval to 2s to make the test fail almost every time on master, while currently it passes almost every time. Added a note in the PR description.

File: pkg/controller/core/clusterqueue_controller.go [hunk 4]
```diff
@@ -63,6 +63,7 @@ type ClusterQueueReconciler struct {
 	wlUpdateCh                           chan event.GenericEvent
 	rfUpdateCh                           chan event.GenericEvent
 	acUpdateCh                           chan event.GenericEvent
+	shUpdateCh                           chan event.GenericEvent
```
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/core/clusterqueue_controller.go:66]: yes, sgtm

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 3 above)
Comment (mimowo) [reply test/integration/controller/core/clusterqueue_controller_test.go]: I see, I did it for consistency, but have no issue to revert, so that the diff is cleaner.

**Comment by mimowo** [comment]
@alculquicondor I have addressed the comments. PTAL.

File: pkg/controller/core/clusterqueue_controller.go [hunk 5]
```diff
@@ -529,6 +535,33 @@ func (h *cqAdmissionCheckHandler) Generic(_ context.Context, e event.GenericEven
...
+	if !isCq {
+		return
+	}
+	remainingTime := constants.UpdatesBatchPeriod
+	if cq.Status.PendingWorkloadsStatus != nil {
+		remainingTime = h.queueVisibilityUpdateInterval - time.Since(cq.Status.PendingWorkloadsStatus.LastChangeTime.Time)
+		if remainingTime <= constants.UpdatesBatchPeriod {
+			remainingTime = constants.UpdatesBatchPeriod
+		}
+	}
```
Comment (tenzen-y) [inline pkg/controller/core/clusterqueue_controller.go:558]: This looks like a great calculation for batch processing :)

File: pkg/controller/core/clusterqueue_controller.go [hunk 6]
```diff
@@ -544,12 +577,16 @@ func (r *ClusterQueueReconciler) SetupWithManager(mgr ctrl.Manager) error {
 	acHandler := cqAdmissionCheckHandler{
 		cache: r.cache,
 	}
+	shHandler := cqSnapshotHandler{
```
Comment (tenzen-y) [inline pkg/controller/core/clusterqueue_controller.go:580]:
```suggestion
	snapHandler := cqSnapshotHandler{
```

nit.

File: pkg/controller/core/clusterqueue_controller.go [hunk 7]
```diff
@@ -544,12 +577,16 @@ func (r *ClusterQueueReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
+		queueVisibilityUpdateInterval: r.queueVisibilityUpdateInterval,
+	}
 	return ctrl.NewControllerManagedBy(mgr).
 		For(&kueue.ClusterQueue{}).
 		Watches(&corev1.Namespace{}, &nsHandler).
 		WatchesRawSource(&source.Channel{Source: r.wlUpdateCh}, &wHandler).
 		WatchesRawSource(&source.Channel{Source: r.rfUpdateCh}, &rfHandler).
 		WatchesRawSource(&source.Channel{Source: r.acUpdateCh}, &acHandler).
+		WatchesRawSource(&source.Channel{Source: r.snapUpdateCh}, &shHandler).
```
Comment (tenzen-y) [inline pkg/controller/core/clusterqueue_controller.go:589]:
```suggestion
		WatchesRawSource(&source.Channel{Source: r.snapUpdateCh}, &snapHandler).
```

ditto.

**Review by tenzen-y — COMMENTED** [review]
LGTM
just a nit.

File: pkg/controller/core/clusterqueue_controller.go (hunk 7 above)
Comment (mimowo) [reply pkg/controller/core/clusterqueue_controller.go]: done

**Comment by mimowo** [comment]
@tenzen-y thanks for reviewing, addressed the nit :)

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve
