### PR TITLE
Retry to reset start time and restore info after error on stop job.

### LINKED ISSUE #2566: JobReconciler does not retry to reset start time and restore info after error on stop job.
**What happened**:
`JobReconciler` does not retry to reset start time and restore info after error on stop job. This happening if the job was successfully suspended but on reset start time https://github.com/kubernetes-sigs/kueue/blob/dc73a33849ce6b76093eca1aade29cfe390d63a5/pkg/controller/jobs/job/job_controller.go#L179 or restore info https://github.com/kubernetes-sigs/kueue/blob/dc73a33849ce6b76093eca1aade29cfe390d63a5/pkg/controller/jobs/job/job_controller.go#L187 an error occurs. 

On this case re-try will not be attempted because `JobReconciler` skipping all not suspended jobs https://github.com/kubernetes-sigs/kueue/blob/dc73a33849ce6b76093eca1aade29cfe390d63a5/pkg/controller/jobframework/reconciler.go#L600.

**What you expected to happen**:
Retry to reset start time and restore info after error on stop job

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
To fix an issue that didn't allow to retry reset start time and restore info after error on stop job.

#### Which issue(s) this PR fixes:

Fixes #2566

#### Does this PR introduce a user-facing change?

```release-note
Fixed issue that prevented restoring the startTime and pod template when evicting a batch/v1 Job, if any API errors happened in the process
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
/retest
due to insufficient computing.

File: pkg/controller/jobframework/reconciler.go [hunk 1]
```diff
@@ -596,8 +596,8 @@ func (r *JobReconciler) ensureOneWorkload(ctx context.Context, job GenericJob, o
 		toDelete = toDelete[1:]
 	}
 
-	// If there is no matching workload and the job is running, suspend it.
-	if match == nil && !job.IsSuspended() {
+	// If there is no matching workload suspend job.
+	if match == nil {
```
Comment (tenzen-y) [inline pkg/controller/jobframework/reconciler.go:600]: What happens in the case where there is a suspended Job without restored nodeSelector which means the reconciler failed to restore nodeSelector in the previous reconciliation.

I'm suspecting that the Worlload is accidentally removed, right?
Could you add a unit test in the batch/job controller for the assumed situations?

Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:600]: You mean this case?

https://github.com/kubernetes-sigs/kueue/blob/dfa182907281dea39fd227aea58abf1374727bef/pkg/controller/jobs/job/job_controller_test.go#L2552-L2601

Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:600]: Looks like removing workloads happening after stop, so it's nothing change. 

https://github.com/kubernetes-sigs/kueue/blob/dfa182907281dea39fd227aea58abf1374727bef/pkg/controller/jobframework/reconciler.go#L600-L641

Comment (trasc) [inline pkg/controller/jobframework/reconciler.go:600]: The main problem is that a "half stopped" will have the "running"  pod set info making it not equivalent to its workload , therefore the problematic part of this condition if  is `match==nil` not `!job.IsSuspended()`.

File: pkg/controller/jobs/job/job_controller_test.go [hunk 2]
```diff
@@ -2558,7 +2558,7 @@ func TestReconciler(t *testing.T) {
 				Suspend(true).
 				Obj(),
 			wantJob: *baseJobWrapper.Clone().Toleration(corev1.Toleration{
-				Key:      "tolerationkey2",
+				Key:      "tolerationkey1",
```
Comment (trasc) [inline pkg/controller/jobs/job/job_controller_test.go:2561]: why?

Comment (mbobrovskyi) [reply pkg/controller/jobs/job/job_controller_test.go:2561]: Because now the job stops and pod set info restores.

https://github.com/kubernetes-sigs/kueue/blob/dfa182907281dea39fd227aea58abf1374727bef/pkg/controller/jobs/job/job_controller.go#L183-L189

File: pkg/controller/jobframework/reconciler.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:600]: Looks like this solution will not work on another cases. 

For example here:

https://github.com/kubernetes-sigs/kueue/blob/dfa182907281dea39fd227aea58abf1374727bef/pkg/controller/jobframework/reconciler.go#L484-L492

Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go:600]: > Looks like this solution will not work on another cases.

How does the code change affect the code you reference here?

Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:600]: Maybe it's a good idea to create something like transactions using labels. We can add some label when we start suspending job and delete this label on the last update.

```go
func (j *Job) Stop(ctx context.Context, c client.Client, podSetsInfo []podset.PodSetInfo, _ jobframework.StopReason, eventMsg string) (bool, error) {
	stoppedNow := false
	if !j.IsSuspended() {
		j.Suspend()
		j.ObjectMeta.Labels[StoppingLabel] = "true"
		if err := c.Update(ctx, j.Object()); err != nil {
			return false, fmt.Errorf("suspend: %w", err)
		}
		stoppedNow = true
	}

	// Reset start time if necessary, so we can update the scheduling directives.
	if j.Status.StartTime != nil {
		j.Status.StartTime = nil
		if err := c.Status().Update(ctx, j.Object()); err != nil {
			return stoppedNow, fmt.Errorf("reset status: %w", err)
		}
	}

	j.RestorePodSetsInfo(podSetsInfo)
	delete(j.ObjectMeta.Labels, StoppingLabel)
	if err := c.Update(ctx, j.Object()); err != nil {
		return false, fmt.Errorf("restore info: %w", err)
	}
	return stoppedNow, nil
}

...

func (j *Job) IsSuspended() bool {
    return j.Spec.Suspend != nil && *j.Spec.Suspend && j.Labels[StoppingLabel] != "true"
}

```
 
WDYT @alculquicondor @mimowo

Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go:600]: Using labels seems awkward, if anything we could use conditions for this purpose, but I'm not clear if this is needed.

Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:600]: > > Looks like this solution will not work on another cases.
> 
> How does the code change affect the code you reference here? Still, I think we should really test this e2e.

I mean that it will not "re-stop" job because we have:

https://github.com/kubernetes-sigs/kueue/blob/dfa182907281dea39fd227aea58abf1374727bef/pkg/controller/jobframework/reconciler.go#L445-L446

Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:600]: > Using labels seems awkward, if anything we could use conditions for this purpose, but I'm not clear if this is needed.

Agree, but on this case we will know for sure that it stopped.

Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go:600]: I see. In that case it seems trickier than initially thought.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Fixed issue that prevented restoring the startTime and pod template when evicting a batch/v1 Job, if any API errors happened in the process
```

**Comment by mbobrovskyi** [comment]
/retest
due to insufficient computing.

**Comment by mbobrovskyi** [comment]
/retest
due to insufficient computing.

**Comment by mbobrovskyi** [comment]
/retest
due to insufficient computing.

**Comment by mbobrovskyi** [comment]
/retest
due to insufficient computing.
