### PR TITLE
[AFS] Get rid of creating redundant LQs in integration tests

### LINKED ISSUE #6416: LocalQueue controller logs ClusterQueues
**What happened**:
In the logs of LocalQueue controller there are not only LocalQueues but also ClusterQueues 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
E.g. see the AFS tests:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6400/pull-kueue-test-integration-baseline-main/1952288809257275392

```2025-08-04T08:55:16.610360678Z	LEVEL(-2)	core/localqueue_controller.go:152	Reconcile LocalQueue	{"controller": "localqueue_controller", "namespace": "core-q5vjw", "name": "cq1", "reconcileID": "7e5c06f6-7e33-4669-90e4-e34e0f822672"}```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When creating CQ in tests we also created LQ with the same name. This PR deletes those redundant LQs, as they were not used and created noise in the logs 

#### Which issue(s) this PR fixes:

Fixes #6416 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go [hunk 1]
```diff
@@ -610,16 +612,6 @@ var _ = ginkgo.Describe("Scheduler", ginkgo.Ordered, ginkgo.ContinueOnFailure, f
 		wls     []*kueue.Workload
 	)
 
-	var createQueue = func(cq *kueue.ClusterQueue) *kueue.ClusterQueue {
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:613]: Nice win, it is actually a good example that too smart functions in tests can sometimes bite :)

Comment (PBundyra) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:613]: Yeah :)

**Comment by mimowo** [comment]
/test pull-kueue-test-integration-baseline-main
checking if flake

**Comment by PBundyra** [comment]
It wasn't a flake. One of the workloads in the test used the LQ that I've deleted. Fixed: https://github.com/kubernetes-sigs/kueue/compare/0a1c67591d23394ececb9f608e82daefcee89803..1911cf91616401b0cee00cc5293c8be6c9df4948

**Comment by mimowo** [comment]
/lgtm
/approve
/cherrypick release-0.13
/cherrypick release-0.12

Thank you 👍
