### PR TITLE
Serialization support for FlavorResource, FlavorResourceSet and FlavorResourceQuantities

### LINKED ISSUE #4137: Problem serializing some Kueue types for logging
**What happened**:
Observing error messages like the following in logs:

```
"nominatedAssignmentError": "json: unsupported type: resources.FlavorResourceQuantities"
"resourcesError": "json: unsupported type: resources.FlavorResourceQuantities"
"resourcesRequiringPreemptionError": "json: unsupported type: sets.Set[[sigs.k8s.io/kueue/pkg/resources.FlavorResource](http://sigs.k8s.io/kueue/pkg/resources.FlavorResource)]"
"usageError": "json: unsupported type: resources.FlavorResourceQuantities"
```

here are the lines, corresponding to v0.10.0
```
cache/snapshot.go:64
cache/snapshot.go:73
preemption/preemption.go:346
scheduler/logging.go:43
```

**What you expected to happen**:
These types should be serialized properly

**How to reproduce it (as minimally and precisely as possible)**:
Run integration tests with higher log verbosity, grep for json: unsupported type

**Anything else we need to know?**:
The scope of this bug includes identifying other types we fail to serialize - the list above is not necessarily exhaustive - and fixing those too

**Environment**:
- Kueue version (use `git describe --tags --dirty --always`): v0.10.0

### PR DESCRIPTION
**Pull request by nasedil**
#### What this PR does / why we need it:
Properly serializes FlavorResource, FlavorResourceSet and FlavorResourceQuantities types which are logged in integration tests.
#### Which issue(s) this PR fixes:

Fixes #4137 

#### Special notes for your reviewer:
As discussed in #4137 part of this issue depends on making serializable `k8s.io/apimachinery/pkg/util/sets.Set` in upstream repo.  In the second commit I created `FlavorResourceSet` type to make it work without changing upstream code.   Possible options are to keep it temporarily until upstream is fixed, keep it permanently, or just discart and keep only the first commit and wait till upstream issue is fixed.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/preemption/preemption.go [hunk 1]
```diff
@@ -63,14 +64,35 @@ type Preemptor struct {
...
+
 type preemptionCtx struct {
 	log               logr.Logger
 	preemptor         workload.Info
 	preemptorCQ       *cache.ClusterQueueSnapshot
 	snapshot          *cache.Snapshot
 	requests          resources.FlavorResourceQuantities
 	tasRequests       cache.WorkloadTASRequests
-	frsNeedPreemption sets.Set[resources.FlavorResource]
+	frsNeedPreemption FlavorResourceSet
```
Comment (tenzen-y) [inline pkg/scheduler/preemption/preemption.go:95]: I do not think we should do for logging. Instead of that, why we can not just use slice?

```go
frsNeedPreemption.UnsortedList()
```

@mimowo Did you indicate JsonMarshal proposed in this PR? If yes, what is the reason not to use slice?

File: pkg/resources/resource.go [hunk 2]
```diff
@@ -27,4 +29,20 @@ type FlavorResource struct {
 	Resource corev1.ResourceName
 }
 
+func (fr FlavorResource) MarshalJSON() ([]byte, error) {
```
Comment (mimowo) [inline pkg/resources/resource.go:32]: I think implementing String should be enough, and much simpler. Then, you can convert sets to slices with built-in: `sets.List(set)`

File: pkg/scheduler/preemption/preemption.go [hunk 3]
```diff
@@ -63,14 +64,35 @@ type Preemptor struct {
 	applyPreemption func(ctx context.Context, w *kueue.Workload, reason, message string) error
 }
 
+type FlavorResourceSet struct {
```
Comment (mimowo) [inline pkg/scheduler/preemption/preemption.go:67]: why not just `type FlavorResourceSet sets.Set[resources.FlavorResource]`

File: pkg/scheduler/preemption/preemption.go (hunk 1 above)
Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go:95]: Actually, my suggestion was to use slice rather than Json, for sure. I was just thinking about exposing this via String function, but `frsNeedPreemption.UnsortedList()` is also neat. I'm ok either way.

File: pkg/scheduler/preemption/preemption.go (hunk 3 above)
Comment (nasedil) [reply pkg/scheduler/preemption/preemption.go:67]: I tried this at first, but then it's not possible to call methods of `sets.Set` directly from `FlavorResourceSet`

File: pkg/scheduler/preemption/preemption.go (hunk 1 above)
Comment (nasedil) [reply pkg/scheduler/preemption/preemption.go:95]: Actually yes, it looks like logger manages to marshal `frsNeedPreemption.UnsortedList()` just fine, and using `String()` for `FlavorResourceSet` I still need to do marshalling somehow.  So I can substitute `frsNeedPreemption` with `frsNeedPreemption.UnsortedList()` in klog calls just fine.  Moreover, it works even when `FlavorResource` and `FlavorResourceQuantities` do not implements `String()`.

However the line https://github.com/kubernetes-sigs/kueue/blob/398c74d105743af8a3ad0d660323e5fdbfaf6e30/pkg/scheduler/logging.go#L43 still leads to the `"json: unsupported type: resources.FlavorResourceQuantities"` error (even when `FlavorResource` and `FlavorResourceQuantities` implement `String()`).  And even if I implement JsonMarshal for them it would not output as nicely as it works .  Looks like there is some functionality in klog that nicely formats to json that should be used, not sure why it doesn't pick up in this case.

I also see `klog.KObj(preemptionCtx.preemptor.Obj)` in klog calls, maybe this could be relevant?

Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go:95]: > still leads to the "json: unsupported type: resources.FlavorResourceQuantities" error (even when FlavorResource and FlavorResourceQuantities implement String())

Yeah, I would assume adding String() for `resources.FlavorResourceQuantities` would be enough, as the logger should check the input type implementes the Stringer interface and call String(), we had a similar case here: https://github.com/kubernetes/kubernetes/issues/121392#issuecomment-1772982267

Comment (nasedil) [reply pkg/scheduler/preemption/preemption.go]: I can trace that `e.assignment` is passed to the logger here: https://github.com/kubernetes-sigs/kueue/blob/398c74d105743af8a3ad0d660323e5fdbfaf6e30/pkg/scheduler/logging.go#L40
where `e` is of type `entry`.

The type `entry` is defined here:  https://github.com/kubernetes-sigs/kueue/blob/398c74d105743af8a3ad0d660323e5fdbfaf6e30/pkg/scheduler/scheduler.go#L320-L331

And `e.assignment` is of type `Assignment` from here:  https://github.com/kubernetes-sigs/kueue/blob/398c74d105743af8a3ad0d660323e5fdbfaf6e30/pkg/scheduler/flavorassigner/flavorassigner.go#L43-L54
which uses `FlavorResourceQuantities` which are `type FlavorResourceQuantities map[FlavorResource]int64`. And `FlavorResource` is serialized fine in `frsNeedPreemption.UnsortedList()`.

Maybe logger supports structs like:
```
type FlavorResource struct {
	Flavor   kueue.ResourceFlavorReference
	Resource corev1.ResourceName
}
```
But not `map[FlavorResource]int64` out of the box?  That's just one guess.

Comment (nasedil) [reply pkg/scheduler/preemption/preemption.go]: Update:  changed log from
```
_, log := utiltesting.ContextWithLog(t)
```
to
```
log := util.NewTestingLogger(ginkgo.GinkgoWriter, -2)
```
And now it's reprodusible:
```
  2025-03-03T14:01:44.979677194Z	LEVEL(-2)	scheduler/scheduler_test.go:94	test-just-resource	{"flavor-resource1": {"Flavor":"testFlavour1","Resource":"testResource1"}}
  2025-03-03T14:01:44.9799564Z	LEVEL(-2)	scheduler/scheduler_test.go:95	test-resource-quantity	{"flavor-resource-quantitiesError": "json: unsupported type: resources.FlavorResourceQuantities"}
  2025-03-03T14:01:44.980021379Z	LEVEL(-2)	scheduler/scheduler_test.go:96	test-resource-set	{"flavor-resource-setError": "json: unsupported type: sets.Set[sigs.k8s.io/kueue/pkg/resources.FlavorResource]"}
  2025-03-03T14:01:44.980076418Z	LEVEL(-2)	scheduler/scheduler_test.go:97	test-resource-set	{"flavor-resource-set-unsortedList": [{"Flavor":"testFlavour2","Resource":"testResource2"},{"Flavor":"testFlavour1","Resource":"testResource1"}]}
```

**Comment by nasedil** [comment]
I used `String()` for serialization.  It results in outputs like this.
```
test-just-resource	{"flavor-resource1": "{\"Flavor\":\"testFlavour1\",\"Resource\":\"testResource1\"}"}
test-resource-quantity	{"flavor-resource-quantities": "{{\"Flavor\":\"testFlavour2\",\"Resource\":\"testResource2\"}:5,{\"Flavor\":\"testFlavour1\",\"Resource\":\"testResource1\"}:3}"}
 ```
Not sure how if there's a straightforward way to avoid escape slashes in the output.

I also debugged how `FlavorResource` and `FlavorResourceQuantities` are outputted, they both lead to reflect encoder here [vendor/go.uber.org/zap/zapcore/json_encoder.go](https://github.com/uber-go/zap/blob/6d482535bdd97f4d97b2f9573ac308f1cf9b574e/zapcore/json_encoder.go#L179) which uses go builtins for encoding.  And it automatically encodes `FlavorResource` but not `map[FlavorResource]int64`.  I don't see a straightforward way to generalize encoding for maps, and seems like `String()` is a good enough approach here.

@mimowo @tenzen-y  what do you think?

**Comment by mimowo** [comment]
Thanks for the investigation. I will check that tomorrow. Im generally ok with either slashes or the json approach. Mostly wanted to see pros and cons of both. Any opinion from @tenzen-y or @PBundyra will be valuable in the meanwhile.

**Comment by nasedil** [comment]
I'm sorry, while `String()` approach worked for that testcase I've made, it did not work with actual integration tests.  So I reverted back to `MarshalJSON()`.

File: pkg/resources/resource.go [hunk 4]
```diff
@@ -27,4 +30,16 @@ type FlavorResource struct {
...
 }
 
+func (fr FlavorResource) String() string {
+	return fmt.Sprintf(`{"Flavor":"%s","Resource":"%s"}`, string(fr.Flavor), string(fr.Resource))
+}
+
 type FlavorResourceQuantities map[FlavorResource]int64
+
+func (q FlavorResourceQuantities) MarshalJSON() ([]byte, error) {
+	temp := make(map[string]int64)
```
Comment (mimowo) [inline pkg/resources/resource.go:40]:
```suggestion
	temp := make(map[string]int64, len(q))
```
nit, just to avoid unnecessary resizes

**Review by mimowo — COMMENTED** [review]
/approve

File: pkg/resources/resource.go (hunk 4 above)
Comment (nasedil) [reply pkg/resources/resource.go]: done, thanks

**Comment by mimowo** [comment]
/lgtm
Thanks!

**Comment by tenzen-y** [comment]
> I'm sorry, while `String()` approach worked for that testcase I've made, it did not work with actual integration tests. So I used a combination of `MarshalJSON()` and `String()`.
> 
> Regarding escaping, I've realized that escaping is actually needed because in JSON keys have to be strings while in `map[FlavorResource]int64` the keys are structs.

Interesting behavior; thank you for sharing that! For sure, LGTM!
