### PR TITLE
Revert "Workload controller refactor - predicates cleanup - Delete event (#8655)"

### LINKED ISSUE #10495: Follower can keep stale workload cache after leader failover, causing preemption target overlap and "workload not found" errors
**What happened**:

In the HA setup, we observed that pods remained `SchedulingGated` and workloads were pending after a leader failover. The pod had warning events indicating `Workload has overlapping preemption targets with another workload`. Also, kueue logs show a lot `workloads.kueue.x-k8s.io "<name>" not found` errors.

As additional context, we also observed that the gap between leader and follower metrics became much larger after the upgrade to `v0.17.0`, which might suggest cache divergence across replicas.

**What you expected to happen**:

After a leader failover, the new leader works properly.

**How to reproduce it (as minimally and precisely as possible)**:

We do not yet have a minimal standalone reproducer, but the problem appears to require all of the following:

1. Run Kueue v0.17.0 in HA mode with at least 2 controller-manager replicas.
3. Let the follower observe workload updates while it is not the active leader.
4. Delete workloads that may still exist in the follower-side scheduler / queue caches.
5. Force a leader failover (in our case, the leader was OOM-killed).
6. Let the former follower become leader and start scheduling.

After failover, the new leader may keep stale preemption targets for deleted workloads and start emitting:

- `workloads.kueue.x-k8s.io "<name>" not found`
- `Workload has overlapping preemption targets with another workload`

**Anything else we need to know?**:

We believe this may be a regression related to the workload delete handling refactor, specifically because:

- workload cache cleanup on delete appears to have moved to the `Reconcile` path on `Get(...)=NotFound`
- however, on follower replicas, `leaderAwareReconciler` returns early on `NotFound` and does not delegate to the underlying reconciler
- this seems to leave stale queue/scheduler cache state on followers
- when such a follower later becomes leader, it schedules using stale workload state

**Environment**:
- Kubernetes version (use `kubectl version`): 1.35
- Kueue version (use `git describe --tags --dirty --always`): 0.17.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Ladicle**
#### What type of PR is this?

/bug
/kind regression

#### What this PR does / why we need it:

This PR reverts #8655 as a quick workaround to resolve #10495. (https://github.com/kubernetes-sigs/kueue/pull/10496#discussion_r3087674111)

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/kueue/issues/10495

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug in HA mode that caused follower replicas to retain stale workload caches after deletion.
```

### CODE REVIEW

File: pkg/controller/core/workload_controller.go [hunk 1]
```diff
@@ -1098,13 +1047,31 @@ func (r *WorkloadReconciler) Create(e event.TypedCreateEvent[*kueue.Workload]) b
...
 	status := "unknown"
 	if !e.DeleteStateUnknown {
 		status = workload.Status(e.Object)
 	}
-	r.logger().V(2).Info("Workload delete event", "workload", klog.KObj(e.Object), "queue", e.Object.Spec.QueueName, "status", status)
-	r.preemptionExpectations.ObservedUID(r.logger(),
+	log := r.logger().WithValues("workload", klog.KObj(e.Object), "queue", e.Object.Spec.QueueName, "status", status)
+	log.V(2).Info("Workload delete event")
+	r.preemptionExpectations.ObservedUID(log,
 		client.ObjectKeyFromObject(e.Object), e.Object.UID)
```
Comment (Ladicle) [inline pkg/controller/core/workload_controller.go:1058]: Most of the conflicts were in the tests originally added in #8655, so I've simply removed them. Aside from the tests, this was the only conflict in the logic.

**Comment by mimowo** [comment]
Can you already also prepare the CP for 0.17 using `./hack/cherry_pick_pull.sh release-0.17 10518` ?

File: pkg/controller/core/workload_controller.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/core/workload_controller.go:1058]: Thank you for the report and the PR 👍

**Review by tenzen-y — COMMENTED** [review]
I carefully checked this PR, then confirmed that the conflicts are mostly only TestWorkloadDeletion and TestGetWorkloadFromCache.

Thank you!
/lgtm
/approve

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
Fix a bug in HA mode that caused follower replicas to retain stale workload caches after deletion.
```
