### PR TITLE
Fix LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy test.

### LINKED ISSUE #4374: [Flaky test] LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy
/kind flake 

**What happened**:

The test failed on unrelated PR: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/4368/pull-kueue-test-e2e-main-1-32/1893968484795158528

**What you expected to happen**:

No random failures

**How to reproduce it (as minimally and precisely as possible)**:

Run on CI

**Anything else we need to know?**:

```
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:103 with:
Error matcher expects an error.  Got:
    <nil>: nil failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:103 with:
Error matcher expects an error.  Got:
    <nil>: nil
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/leaderworkerset_test.go:425 @ 02/24/25 10:28:43.548
}
```
This is e2e test `pull-kueue-test-e2e-main-1-32` so maybe the timeout of 10s is not enough, I would suggest to try incrementing it.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:
Fix LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy test.

#### Which issue(s) this PR fixes:

Fixes #4374

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/singlecluster/leaderworkerset_test.go [hunk 1]
```diff
@@ -422,7 +422,7 @@ var _ = ginkgo.Describe("LeaderWorkerSet integration", func() {
 				})
 
 				ginkgo.By("Check workload for group 2 is deleted", func() {
-					util.ExpectObjectToBeDeleted(ctx, k8sClient, createdWorkload2, false)
+					util.ExpectObjectToBeDeletedWithTimeout(ctx, k8sClient, createdWorkload2, false, util.LongTimeout)
```
Comment (tenzen-y) [inline test/e2e/singlecluster/leaderworkerset_test.go:425]: Just checking.
Does the root cause is taking more time to delete Workloads?

Comment (tenzen-y) [reply test/e2e/singlecluster/leaderworkerset_test.go:425]: Thank you for clarifying that. In that case, do you have any reason why we do not verify if group 2 worker StatefulSet is removed before this checking?

Comment (mbobrovskyi) [reply test/e2e/singlecluster/leaderworkerset_test.go:425]: I'm not sure if it's useful. The Pod group combines Pods from both leader and worker StatefulSets. Additionally, we don’t need to test the LWS staff; we need to confirm that the Pods are deleted and the Workload is removed.

Comment (mimowo) [reply test/e2e/singlecluster/leaderworkerset_test.go:425]: > In that case, do you have any reason why we do not verify if group 2 worker StatefulSet is removed before this checking?

I would rather not do it, because StatefulSet is rather a technical detail of LWS. Especially, the e2e should show how users and Kueue interact with LWS, they don't need to know about the internal use of STS.

**Comment by mimowo** [comment]
/lgtm
/approve
/hold
leaving final unhold to @tenzen-y
