### PR TITLE
Commonize workload eviction and fix accounting for related metrics

### LINKED ISSUE #6296: Commonize the code for workload eviction
**What would you like to be cleaned**:

Commonize workload eviction by using the common workload.EvictWorkload function (or just workload.Evict).

**Why is this needed**:

Currently many different places handles workload eviction in slightly different ways, we should commonize to make bugs less likely.

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #6296

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @mszadkow who might be intereseted in the changes in the context of migrating SSA to patch. I hope with these changes it will be easier to update (fewer places)

File: pkg/controller/core/workload_controller.go [hunk 1]
```diff
@@ -251,25 +250,20 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
 			updated = true
 		}
-
-		// exception due to complicated logic, not using PrepareForEviction (temporarily)
-		workload.ResetClusterNomination(&wl)
-		updated = workload.ResetChecksOnEviction(&wl, r.clock.Now()) || updated
-		reportWorkloadEvictedOnce := workload.WorkloadEvictionStateInc(&wl, kueue.WorkloadDeactivated, "")
-		if updated {
-			if err := workload.ApplyAdmissionStatus(ctx, r.client, &wl, true, r.clock); err != nil {
+		if evicted {
```
Comment (mszadkow) [inline pkg/controller/core/workload_controller.go]: The problem with this whole condition branch that starts on the line 233 is that there are many tests that expect some outcome from here - I would call it side effects.
E.g. if the `kueue.WorkloadEvicted` is already present, we need to call ResetChecksOnEviction.
Question remains if tests correctly document the behaviour?
Ahh I see you already adjusted some of the tests.

Comment (mimowo) [reply pkg/controller/core/workload_controller.go]: Yes, eviction as done currently is a mess, trying to untangle a little bit :)

For this particular case I think we should use DeactivatedDueTo and align with the long existing metric.

I'm yet considering if this is a separete PR or part of this.

**Comment by mimowo** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6297/pull-kueue-test-integration-baseline-main/1950867693955452928 is known flake

**Comment by mimowo** [comment]
cc @mszadkow @tenzen-y I think this is ready for review. I would like to cherrypick the PR. Let me know if this is ok, or for extra safety you would prefer to split it potentially.

**Comment by mimowo** [comment]
/hold
to avoid premature merging

**Comment by mimowo** [comment]
Making sure there are no new flakes introduced
/test pull-kueue-test-e2e-main-1-31
/test pull-kueue-test-e2e-main-1-32
/test pull-kueue-test-e2e-main-1-33
/test pull-kueue-test-e2e-multikueue-main
/test pull-kueue-test-e2e-tas-main
/test pull-kueue-test-integration-baseline-main
/test pull-kueue-test-integration-extended-main
/test pull-kueue-test-integration-multikueue-main

**Comment by mimowo** [comment]
/test pull-kueue-test-e2e-multikueue-main
mk known flake

**Comment by tenzen-y** [comment]
> WIP because still testing

Is this still WIP?

As I can check the issue, it says just cleanup, but this PR says bug fix. Which one?

**Comment by mimowo** [comment]
> As I can check the issue, it says just cleanup, but this PR says bug fix. Which one?

It is mostly cleanup, but it also fixes some corner cases, so I added bugfix.

**Comment by mimowo** [comment]
Only rebased to get some recent flake fixes for Multikueue tests

**Comment by mimowo** [comment]
@tenzen-y so while the PR is motivated by commonizing code, in the process I realized some bugs are fixed for `evicted_workloads_once_total`. 

I could try to decouple the bugfix first, wdyt?

**Comment by tenzen-y** [comment]
> @tenzen-y so while the PR is motivated by commonizing code, in the process I realized some bugs are fixed for `evicted_workloads_once_total`.
> 
> I could try to decouple the bugfix first, wdyt?

Yeah, I would like to decouple those. I think we can cherry-pick those to release branches, but I want to have a separate one.

**Comment by mimowo** [comment]
Seems like the smallest PR just with the fixes for the metric: https://github.com/kubernetes-sigs/kueue/pull/6332.

I will rebase this one and update release note once the other is merged.

File: pkg/controller/core/workload_controller.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/core/workload_controller.go]: This is now solved in https://github.com/kubernetes-sigs/kueue/pull/6332

**Comment by mimowo** [comment]
/unhold
after rebase after https://github.com/kubernetes-sigs/kueue/pull/6332 is merged

**Comment by mimowo** [comment]
@tenzen-y this is rebased already, ptal

File: pkg/workload/workload.go [hunk 2]
```diff
@@ -1080,23 +1081,31 @@ func AdmissionChecksForWorkload(log logr.Logger, wl *kueue.Workload, admissionCh
...
 	if err := ApplyAdmissionStatus(ctx, c, wl, true, clock); err != nil {
 		return err
 	}
-	reportWorkloadEvictedOnce := WorkloadEvictionStateInc(wl, reason, "")
+	if wl.Status.Admission == nil {
+		// This is an extra safeguard for access to `wl.Status.Admission`.
+		// This function is expected to be called only for workload which have
+		// Admission.
+		log := log.FromContext(ctx)
+		log.V(2).Info("WARNING: unexpected eviction of workload without status.Admission", "workload", klog.KObj(wl))
```
Comment (tenzen-y) [inline pkg/workload/workload.go]:
```suggestion
		log.V(3).Info("WARNING: unexpected eviction of workload without status.Admission", "workload", klog.KObj(wl))
```

It looks like this is a debug log. So, it would be better level to 3.

File: pkg/workload/workload.go
Comment (tenzen-y) [inline pkg/workload/workload.go:1]: The returned value from `ResetChecksOnEviction` has never been used, anywhere.
So, could you change the following function with `func ResetChecksOnEviction(w *kueue.Workload, now time.Time) { `?

https://github.com/kubernetes-sigs/kueue/blob/db2ccd903ca226be83e4da31879ce55b2a727bd0/pkg/workload/admissionchecks.go#L96

File: pkg/workload/workload.go [hunk 3]
```diff
@@ -1114,8 +1123,7 @@ func ReportEvictedWorkload(recorder record.EventRecorder, wl *kueue.Workload, cq
 }
 
 func ReportPreemption(preemptingCqName kueue.ClusterQueueReference, preemptingReason string, targetCqName kueue.ClusterQueueReference, wl *kueue.Workload) {
-	durationToPreemption := workloadsWithPodsReadyToEvictedTime(wl)
```
Comment (tenzen-y) [inline pkg/workload/workload.go]: Why we can drop the preemption duration?

File: pkg/metrics/metrics_test.go [hunk 4]
```diff
@@ -160,15 +160,12 @@ func TestReportAndCleanupClusterQueueEvictedNumber(t *testing.T) {
...
-	ReportPreemption("cluster_queue1", "InCohortReclamation", "cluster_queue1", &duration)
-	ReportPreemption("cluster_queue1", "InCohortFairSharing", "cluster_queue1", &duration)
-	ReportPreemption("cluster_queue1", "InCohortReclaimWhileBorrowing", "cluster_queue1", &duration)
+	ReportPreemption("cluster_queue1", "InClusterQueue", "cluster_queue1")
+	ReportPreemption("cluster_queue1", "InCohortReclamation", "cluster_queue1")
+	ReportPreemption("cluster_queue1", "InCohortFairSharing", "cluster_queue1")
+	ReportPreemption("cluster_queue1", "InCohortReclaimWhileBorrowing", "cluster_queue1")
 
 	expectFilteredMetricsCount(t, PreemptedWorkloadsTotal, 4, "preempting_cluster_queue", "cluster_queue1")
-	expectFilteredMetricsCount(t, EvictedWorkloadsTotal, 1, "cluster_queue", "cluster_queue1")
```
Comment (tenzen-y) [inline pkg/metrics/metrics_test.go]: Does this mean that we don't record Eviction count when preemption happened?

File: pkg/workload/workload.go (hunk 3 above)
Comment (mimowo) [reply pkg/workload/workload.go]: Because `PodsReadyToEvictedTime` is already accounted via workload.ReportEvictedWorkload.

However, this function was not called during preemption, now I call it from applyPreemptionWithSSA.

See https://github.com/kubernetes-sigs/kueue/pull/6420 for the ease of reviewing I extracted the change

File: pkg/metrics/metrics_test.go (hunk 4 above)
Comment (mimowo) [reply pkg/metrics/metrics_test.go]: The metric is no longer reported via `ReportPreemption`, but by the more generic `workload.ReportEvictedWorkload`.

This allows to commonize the code, see https://github.com/kubernetes-sigs/kueue/pull/6420 for the ease of reviewing.

Comment (tenzen-y) [reply pkg/metrics/metrics_test.go]: Thank you for describing that. SGTM

File: pkg/workload/workload.go (hunk 3 above)
Comment (tenzen-y) [reply pkg/workload/workload.go]: Thanks, SGTM

File: pkg/workload/workload.go
Comment (tenzen-y) [reply pkg/workload/workload.go:1]: @mimowo What about this?

**Review by tenzen-y — COMMENTED** [review]
Otherwise LGTM

File: pkg/workload/workload.go
Comment (mimowo) [reply pkg/workload/workload.go:1]: It is no longer used after the refactor, but was used in the past. Let me rebase and I check how to handle that.

Comment (mimowo) [reply pkg/workload/workload.go:1]: Ok I rebased, so indeed the rebased value is no longer used currently. What I could do is to keep it returned (just to minimize the diff) and remove in follow up, but I'm not sure it is worth it. wdyt?

Comment (tenzen-y) [reply pkg/workload/workload.go:1]: After this PR, ResetChecksOnEviction returning value is no longer used. So, I think removing the returning process in ResetChecksOnEviction would be better in this PR.

**Comment by tenzen-y** [comment]
The remaining one is only https://github.com/kubernetes-sigs/kueue/pull/6297/files#r2251765801
Otherwise LGTM

File: pkg/workload/workload.go
Comment (mimowo) [reply pkg/workload/workload.go:1]: Ack, done

**Comment by mimowo** [comment]
> The remaining one is only https://github.com/kubernetes-sigs/kueue/pull/6297/files#r2251765801

Sure, I just pushed the change.
