### PR TITLE
[kueuectl] Fix "Should print cluster queues list with paging" test.

### LINKED ISSUE #2353: Flaky integration test: Should print workloads list with paging
/kind flake

**What happened**:

Integration test failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2314/pull-kueue-test-integration-main/1798039851593895936

**What you expected to happen**:

No flake

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the build.

**Anything else we need to know?**:

```
  [FAILED] Expected
      <string>: "...     1s
      "
  to equal               |
      <string>: "...     0s
      "
  In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/kueuectl/list_test.go:206 @ 06/04/24 17:19:10.001
```

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Fix "Should print cluster queues list with paging" test.

#### Which issue(s) this PR fixes:

Fixes #2353

#### Special notes for your reviewer:
Fixes for https://github.com/kubernetes-sigs/kueue/issues/2353#issuecomment-2159897688.

`Active` status calculated by `meta.IsStatusConditionTrue(cq.Status.Conditions, v1beta1.ClusterQueueActive)`. Sometime we don't have time to set this condition to `True` between creation clusterqueues (an `JustBeforeEach`) and print list of clusterqueues. That's why we have `active = false`. So we need to wait time to be sure that status set to `true`.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/kueuectl/list_test.go [hunk 1]
```diff
@@ -134,44 +132,48 @@ very-long-local-queue-name   cq1                            0
 		})
 
 		// Simple client set that are using on unit tests not allow to filter by field selector.
-		ginkgo.It("Should print local queues list filtered by field selector", func() {
-			streams, _, output, errOutput := genericiooptions.NewTestIOStreams()
-			configFlags := CreateConfigFlagsWithRestConfig(cfg, streams)
-			executeTime := time.Now()
-			kueuectl := app.NewKueuectlCmd(app.KueuectlOptions{ConfigFlags: configFlags, IOStreams: streams, Clock: testingclock.NewFakeClock(executeTime)})
+		ginkgo.It("Should print cluster queues list filtered by field selector", func() {
```
Comment (mimowo) [inline test/integration/kueuectl/list_test.go:135]: This is this test changed since the title says "print cluster queues list with paging"? Is it also failing for the same reason?

File: test/integration/kueuectl/list_test.go [hunk 2]
```diff
@@ -134,44 +132,48 @@ very-long-local-queue-name   cq1                            0
...
 
-			gomega.Expect(err).NotTo(gomega.HaveOccurred(), "%s: %s", err, output)
-			gomega.Expect(errOutput.String()).Should(gomega.BeEmpty())
-			gomega.Expect(output.String()).Should(gomega.Equal(fmt.Sprintf(`NAME                           COHORT   PENDING WORKLOADS   ADMITTED WORKLOADS   ACTIVE   AGE
+				g.Expect(err).NotTo(gomega.HaveOccurred(), "%s: %s", err, output)
+				g.Expect(errOutput.String()).Should(gomega.BeEmpty())
+				g.Expect(output.String()).Should(gomega.Equal(fmt.Sprintf(`NAME                           COHORT   PENDING WORKLOADS   ADMITTED WORKLOADS   ACTIVE   AGE
 cq1                                     0                   0                    true     %s
-very-long-cluster-queue-name            0                   0                    false    %s
+very-long-cluster-queue-name            0                   0                    true     %s
```
Comment (mimowo) [inline test/integration/kueuectl/list_test.go:171]: Can we reduce the scope of eventually just to the table?

File: test/integration/kueuectl/list_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/integration/kueuectl/list_test.go:135]: I can't see the problem with this test. But to be sure I added eventually here too.

File: test/integration/kueuectl/list_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/integration/kueuectl/list_test.go:171]: Sorry. Which scope do you mean?

File: test/integration/kueuectl/list_test.go (hunk 1 above)
Comment (mimowo) [reply test/integration/kueuectl/list_test.go:135]: I suggest not add it proactively, unless we have some good reason to believe it is flaky.

File: test/integration/kueuectl/list_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/kueuectl/list_test.go:171]: The eventually essentially does "retry the entire test until it passes". It seems quite aggressive, so I was thinking we could wrap less.

Let me take a step back - what is the reason the test flakes? Please update the PR description. When we understand what is the problem maybe we see a better solution.

Comment (mbobrovskyi) [reply test/integration/kueuectl/list_test.go:171]: Active status calculated by `meta.IsStatusConditionTrue(cq.Status.Conditions, v1beta1.ClusterQueueActive)`. Sometime we don't have time to set this condition to `True` between creation clusterqueues (an `JustBeforeEach`) and print list of clusterqueues. So that's why we have active status = false. So we need to wait time to be sure that status set to true.

Comment (mimowo) [reply test/integration/kueuectl/list_test.go:171]: Ah I see, in that case can we await in the `JustBeforeEach` for the CQ to be active? Or just at the beginning of affected tests (`Its`).

Comment (mbobrovskyi) [reply test/integration/kueuectl/list_test.go:180]: Good point. Thanks. Fixed

**Comment by mimowo** [comment]
Thanks! Now looks clear.
/lgtm
/approve
