### PR TITLE
Fix evicting workloads due to AdmissionCheck retry

### LINKED ISSUE #5129: GKE; The workload backoff was finished; The workload has failed admission checks; Max nodepool size reached
**Possibly the same issue**
https://github.com/kubernetes-sigs/kueue/issues/3258

**What happened**:

On a GKE cluster workloads fail admission check for jobs that had to be queue due to max nodepool size reached. I'm also using [Dynamic Workload Scheduler](https://cloud.google.com/blog/products/compute/introducing-dynamic-workload-scheduler)

We have seen this happened the most on flavors that require more than 1 GPU. The example below comes from a run with a flavor that needs x4 A100.

```
Status:
  Admission Checks:
    Last Transition Time:  2025-04-25T16:06:34Z
    Message:               Retrying after failure: Max nodepool size reached, affected nodepools: dws-a100-40gb-4x-node-pool
    Name:                  dws-prov
    State:                 Retry
  Conditions:
    Last Transition Time:  2025-04-25T16:09:23Z
    Message:               The workload has failed admission checks
    Observed Generation:   1
    Reason:                Pending
    Status:                False
    Type:                  QuotaReserved
    Last Transition Time:  2025-04-25T16:09:23Z
    Message:               At least one admission check is false
    Observed Generation:   1
    Reason:                AdmissionCheck
    Status:                True
    Type:                  Evicted
    Last Transition Time:  2025-04-25T16:10:23Z
    Message:               The workload backoff was finished
    Observed Generation:   1
    Reason:                BackoffFinished
    Status:                True
    Type:                  Requeued
  Requeue State:
    Count:       1
    Requeue At:  2025-04-25T16:10:23Z
  Resource Requests:
    Name:  main
    Resources:
      Cpu:             1250m
      Memory:          8Gi
      nvidia.com/gpu:  4
Events:
  Type     Reason   Age                   From             Message
  ----     ------   ----                  ----             -------
  Warning  Pending  14m (x89 over 3h32m)  kueue-admission  The workload has failed admission checks
```

**What you expected to happen**:
I was expecting the backoff strategy to retry admission checks for 7 days.
```yaml
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ProvisioningRequestConfig
metadata:
  name: dws-config
spec:
  provisioningClassName: queued-provisioning.gke.io
  managedResources:
  - nvidia.com/gpu
  retryStrategy:
    backoffLimitCount: 15
    backoffBaseSeconds: 60
    backoffMaxSeconds: 604800  # 7 days in seconds
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a GKE cluster with one nodepool of size 1 of a given flavor 
2. Create two jobs that need that flavor
3. When the first job finishes, the second will already be in a BackoffFinished state and will not attempt to run another admission check.

**Anything else we need to know?**:
This can be completely wrong and the cause of this problem but I'm assuming that I need to allow the nodepool to scale to a value one more than my quota. 

e.g.
`If I have a quota of [1] A100 I should set my autoscaling on my nodepool to 2`

`If I have a quota of [4] A100 and my favor needs four GPUs per box I need to set autoscaling on my nodepool to 8`

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.32.3-gke.1717000
```
- Kueue version (use `git describe --tags --dirty --always`):
```
v0.11.4 (but we saw this on v0.11.3 as well. Probably also the previous ones)
```
- Cloud provider or hardware configuration:
```
Google Cloud; A100 40GB
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=b09cce333d9e64d1404b4b56037dd2492722fa1e
GOOGLE_CRASH_ID=Lakitu
VERSION=117
VERSION_ID=117
BUILD_ID=18613.164.98
```
- Kernel (e.g. `uname -a`):
```
Linux gke-prod-n-r-training-kueue-node-pool-6334a200-6nv5 6.6.72+ #1 SMP PREEMPT_DYNAMIC Sun Mar 30 09:02:56 UTC 2025 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
```
- Install tools:
- Others:

I was also seeing errors like this one for the jobs that were failing
```json
{
  "insertId": "qftjasvb2zeu3dc9",
  "jsonPayload": {
    "error": "clearing admission: Operation cannot be fulfilled on workloads.kueue.x-k8s.io \"job-0d1fff4c41864c69b8f9fca17b7d4f73-35ffd\": the object has been modified; please apply your changes to the latest version and try again",
    "controllerKind": "Job",
    "reconcileID": "8ddad845-2f9e-49f2-ab0d-7295bd183b0d",
    "level": "error",
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224",
    "controllerGroup": "batch",
    "controller": "job",
    "namespace": "default",
    "msg": "Reconciler error",
    "Job": {
      "namespace": "default",
      "name": "0d1fff4c41864c69b8f9fca17b7d4f73"
    },
    "name": "0d1fff4c41864c69b8f9fca17b7d4f73",
    "ts": "2025-04-25T16:09:23.164778584Z",
    "caller": "controller/controller.go:316"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "n-r-training",
      "cluster_name": "prod-n-r-training-cluster-us-e1",
      "pod_name": "kueue-controller-manager-5975cbd886-56vc9",
      "namespace_name": "kueue-system",
      "container_name": "manager",
      "location": "us-east1"
    }
  },
  "timestamp": "2025-04-25T16:09:23.165111880Z",
  "severity": "ERROR",
  "labels": {
    "compute.googleapis.com/resource_name": "gke-prod-n-r-training-kueue-node-pool-6334a200-6nv5",
    "k8s-pod/app_kubernetes_io/component": "controller",
    "logging.gke.io/top_level_controller_type": "Deployment",
    "k8s-pod/control-plane": "controller-manager",
    "logging.gke.io/top_level_controller_name": "kueue-controller-manager",
    "k8s-pod/pod-template-hash": "5975cbd886",
    "k8s-pod/app_kubernetes_io/name": "kueue"
  },
  "logName": "projects/n-r-training/logs/stderr",
  "receiveTimestamp": "2025-04-25T16:09:25.369575252Z"
}
```

### LINKED ISSUE #5480: [flaky test] Provisioning when Workload uses a provision admission check with BackoffLimitCount=1 Should retry if a ProvisioningRequest fails, then succeed if the second Provisioning request succeeds
**What happened**:

failure on unrelated branch: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5479/pull-kueue-test-integration-baseline-release-0-12/1929919449490526208

**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:

```
{Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:959 with:
Expected
    <v1beta1.CheckState>: Retry
to equal
    <v1beta1.CheckState>: Pending failed [FAILED] Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:959 with:
Expected
    <v1beta1.CheckState>: Retry
to equal
    <v1beta1.CheckState>: Pending
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:963 @ 06/03/25 15:19:32.596
}
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #5573: [flaky test]  Provisioning when Workload uses a provision admission check with BackoffLimitCount=1 Should retry if a ProvisioningRequest fails, then reject AdmissionCheck if the second ProvisioningRequest fails
/kind flake

**What happened**:

[failure ](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5572/pull-kueue-test-integration-baseline-release-0-11/1932040894110765056)

**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:
```
Provisioning admission check suite: [It] Provisioning when Workload uses a provision admission check with BackoffLimitCount=1 Should retry if a ProvisioningRequest fails, then reject AdmissionCheck if the second ProvisioningRequest fails expand_less	15s
{Timed out after 10.007s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1735 with:
Expected
    <v1beta1.CheckState>: Retry
to equal
    <v1beta1.CheckState>: Pending failed [FAILED] Timed out after 10.007s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1735 with:
Expected
    <v1beta1.CheckState>: Retry
to equal
    <v1beta1.CheckState>: Pending
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1739 @ 06/09/25 11:49:00.349
}
[open stderropen_in_new](https://prow.k8s.io/spyglass/lens/junit/iframe?req=%7B%22artifacts%22%3A%5B%22artifacts%2Fjunit.xml%22%5D%2C%22index%22%3A2%2C%22src%22%3A%22gs%2Fkubernetes-ci-logs%2Fpr-logs%2Fpull%2Fkubernetes-sigs_kueue%2F5572%2Fpull-kueue-test-integration-baseline-release-0-11%2F1932040894110765056%22%7D&topURL=https%3A//prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5572/pull-kueue-test-integration-baseline-release-0-11/1932040894110765056&lensIndex=2#)
```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #5129
Fixes #5573
Fixes #5480

#### Special notes for your reviewer:

Since the issue has a racy nature I opened also experiment PRs:
- https://github.com/kubernetes-sigs/kueue/pull/6285 - aims to show the repro using 300 repeats on existing code
- https://github.com/kubernetes-sigs/kueue/pull/6284 - aims to show on CI the fix works

To minimize the scope of the fix I only use the strict mode for requests which operate on the status.admissionChecks.state. For other requests I leave non-strict (but we may revist that later).

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug which could occasionally cause workloads evicted by the built-in AdmissionChecks
(ProvisioningRequest and MultiKueue) to get stuck in the evicted state which didn't allow re-scheduling.
This could happen when the AdmissionCheck controller would trigger eviction by setting the
Admission check state to "Retry".
```

### CODE REVIEW

**Comment by mimowo** [comment]
/hold 
to avoid premature merging (we may prefer to wait for the experiment PRs).

File: test/e2e/singlecluster/e2e_test.go [hunk 1]
```diff
@@ -654,7 +654,7 @@ var _ = ginkgo.Describe("Kueue", func() {
 			ginkgo.By("setting the check as successful", func() {
 				gomega.Eventually(func(g gomega.Gomega) {
 					g.Expect(k8sClient.Get(ctx, wlLookupKey, createdWorkload)).Should(gomega.Succeed())
-					patch := workload.BaseSSAWorkload(createdWorkload)
+					patch := workload.BaseSSAWorkload(createdWorkload, true)
```
Comment (tenzen-y) [inline test/e2e/singlecluster/e2e_test.go]: I think that it would be better to create a testing function, `BaseSSAWorkload`, to enforce strict mode in E2E tests.
If we allow them to disable strict mode, we will make the regressions.

However, the `BaseSSAWorkload` testing function could block the misconfigurations in E2E tests.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 2]
```diff
@@ -917,6 +917,52 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+
+			ginkgo.By("Checking the Workload is Evicted", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, wlKey, &updatedWl)).To(gomega.Succeed())
+					_, evicted := workload.IsEvictedByAdmissionCheck(&updatedWl)
+					g.Expect(evicted).To(gomega.BeTrue())
+				}, util.Timeout, time.Millisecond).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Checking the AdmissionChecks are reset to Pending and remain this way", func() {
```
Comment (tenzen-y) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:953]: Just checking, is this the core verification for the observed bugs?

File: pkg/controller/admissionchecks/provisioning/controller.go
Comment (tenzen-y) [inline pkg/controller/admissionchecks/provisioning/controller.go:1]: IIUC, these changes are key to preventing rolling back to the outdated Admission.

File: pkg/controller/admissionchecks/multikueue/workload.go
Comment (tenzen-y) [inline pkg/controller/admissionchecks/multikueue/workload.go:1]: Just checking, this is not reported from your customers. But, MultiKueue Admission could technically occur the same problem as ProvReq since both relies on the AdmissionCheck mechanism, right?

If yes, that makes sense to contain this fix in this PR.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:953]: Yes, exactly. To me more precise the first assert is enough:

```
check := workload.FindAdmissionCheck(updatedWl.Status.AdmissionChecks, kueue.AdmissionCheckReference(ac.Name))
g.Expect(check).NotTo(gomega.BeNil())
g.Expect(check.State).To(gomega.Equal(kueue.CheckStatePending), fmt.Sprintf("workload status: %v, conditions: %v", updatedWl.Status, updatedWl.Status.Conditions))
```
Let me just cleanup the message

File: pkg/controller/admissionchecks/provisioning/controller.go
Comment (mimowo) [reply pkg/controller/admissionchecks/provisioning/controller.go:1]: Yes, these are the main changes for the fix (to use strict in provisioning controller).

File: pkg/controller/admissionchecks/multikueue/workload.go
Comment (mimowo) [reply pkg/controller/admissionchecks/multikueue/workload.go:1]: Yes, I think exactly the same issue could occur in MultiKueue in case of retry admission Check.

However, the conditions required to repro require to trigger retry, similar to "The connection to a worker cluster is unreliable", and then await for re-admission. IIRC we don't have such test currently, but it would be tricky to add, and even then it would probably only fail 1/100 (similar as for ProvReq).

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:953]: cleaned up, ptal

File: test/e2e/singlecluster/e2e_test.go (hunk 1 above)
Comment (mimowo) [reply test/e2e/singlecluster/e2e_test.go]: Yes, I think this is better to use `BaseSSAWorkload(w, true)` in tests consistently. 

I was thinking to introduce function like `testing/util -> BaseSSAWorkloadForTests(w)`, wdyt?

Comment (tenzen-y) [reply test/e2e/singlecluster/e2e_test.go]: SGTM, thank you.

Comment (mimowo) [reply test/e2e/singlecluster/e2e_test.go]: Updated tentatively per suggestion - naming the function as util.BaseSSAWorkload, ptal

File: pkg/controller/admissionchecks/multikueue/workload.go
Comment (tenzen-y) [reply pkg/controller/admissionchecks/multikueue/workload.go:1]: I don't request to add such a tricky test for now.
SGTM

**Comment by tenzen-y** [comment]
@mimowo Could we make release-note as more generic? In other workds, could we say that AdmissionCheck mechanism occurs the rollback problem in case of Eviction, and the effective ranges are MultiKueue and ProvisioningRequest and custom AdmissionCheck controller?

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 2 above)
Comment (tenzen-y) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:953]: SGTM, thank you.

File: test/e2e/singlecluster/e2e_test.go (hunk 1 above)
Comment (tenzen-y) [reply test/e2e/singlecluster/e2e_test.go]: Both sounds good to me.

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

Let us try performing tests 5 times.

/hold

**Comment by mimowo** [comment]
Sure, but this change does not affect implementations of the custom AC controllers directly.

**Comment by tenzen-y** [comment]
> Sure, but this change does not affect implementations of the custom AC controllers directly.

Ah, right. If they use BaseSSAWorkload function, they could technically face the same problem.
But, we don't want to care all custom cases.

So, as you said, we can focus on ProvReq and MultiKueue, but we want to mention about AdmissionCheck problem so that the external AdmissionCheck controller devel could check their code whether their controller has the same problem.

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Fix the bug which could occasionally cause workloads evicted, by the built-in AdmissionChecks
(ProvisioningRequest and MultiKueue), to get stuck in the evicted state which didn't allow re-scheduling.
This could happen when the AdmissionCheck controller would trigger eviction by setting the
Admission check state to "Retry".
```
wdyt?

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Fix the bug which could occasionally cause workloads evicted by the built-in AdmissionChecks
(ProvisioningRequest and MultiKueue) to get stuck in the evicted state which didn't allow re-scheduling.
This could happen when the AdmissionCheck controller would trigger eviction by setting the
Admission check state to "Retry".
```

**Comment by tenzen-y** [comment]
> /release-note-edit
> 
> ```
> Fix the bug which could occasionally cause workloads evicted, by the built-in AdmissionChecks
> (ProvisioningRequest and MultiKueue), to get stuck in the evicted state which didn't allow re-scheduling.
> This could happen when the AdmissionCheck controller would trigger eviction by setting the
> Admission check state to "Retry".
> ```
> 
> wdyt?

SGTM, thanks.

**Comment by tenzen-y** [comment]
Just trying

/cherry-pick release-0.12
/cherry-pick release-0.13

**Comment by mimowo** [comment]
/test pull-kueue-test-integration-baseline-main
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6283/pull-kueue-test-integration-baseline-main/1950559248463171584
this is a known new flake https://github.com/kubernetes-sigs/kueue/issues/6227. Hopefully we can address in the coming days.

**Comment by mimowo** [comment]
> Just trying
> 
> /cherry-pick release-0.12 /cherry-pick release-0.13

I tested locally and it merges without conflicts to the branches

**Comment by tenzen-y** [comment]
> > Just trying
> > /cherry-pick release-0.12 /cherry-pick release-0.13
> 
> I tested locally and it merges without conflicts to the branches

great to hear that

**Comment by mimowo** [comment]
Unfortunately running the test on CI despite nearly 1000 runs didn't bring failures (the experiment PRs), so I think we need to rely on the presence / absence of the rare flakes + manual testing locally, but reproducing the failure is tricky.

**Comment by mimowo** [comment]
> Let us try performing tests 5 times.
> /hold

Done for integration and e2e tests, no flakes other than already known ones.
/unhold
