### PR TITLE
[AFS] Implement cache for AFS consumed resources

### LINKED ISSUE #6710: [AFS] Introduce cache that stores `.admissionFairSharingStatus.ConsumedResources` values
**What would you like to be added**:
Currently, `admissionFairSharingStatus.ConsumedResources` is only stored in controller runtime informer. I'd like to add a field that represents it in cache.

**Why is this needed**:
With the present implementation it's hard to synchronize usage of this fields across different controllers.
E.g. Let's assume we have a thread that rebuilds the heap and it uses the `.consumedResources` field. It may rebuild a half of the heap but in the meantime some other thread updates the field. This can result in inconsistent sorting a thus, a wrong Workload is picked to be scheduled

Besides the race condition, the change will also make sorting/scheduling process faster

### LINKED ISSUE #7688: [flaky test] Scheduler when Using AdmissionFairSharing at ClusterQueue level admits one workload from each LocalQueue when quota is limited
/kind flake 

**What happened**:
failure https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-main/1990131289172217856
**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:

```
Scheduler Fair Sharing Suite: [It] Scheduler when Using AdmissionFairSharing at ClusterQueue level admits one workload from each LocalQueue when quota is limited expand_less	18s
{Timed out after 10.006s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:365 with:
Not enough workloads are admitted
Expected
    <int>: 0
to equal
    <int>: 1 failed [FAILED] Timed out after 10.006s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:365 with:
Not enough workloads are admitted
Expected
    <int>: 0
to equal
    <int>: 1
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:1057 @ 11/16/25 19:16:39.271
}
```

### LINKED ISSUE #7693: AFS: entry penalties decay/are lost much faster than the config suggests
**What happened**:

I have investigated logs of the flaky test https://github.com/kubernetes-sigs/kueue/issues/7688, and it seems the entry penalty for LQ was lost just after 62ms.

**What you expected to happen**:

Entry penalties to decay the same pace as regular usage.

**How to reproduce it (as minimally and precisely as possible)**:

The test flakes due to this.

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?
Implements cache-based storage for AFS consumed resources, fixing race condition where consumed resources aren't visible to scheduler when entry penalties are deleted.

/kind bug

#### Which issue(s) this PR fixes:

Fixes #6710
Fixes #7688
Fixes #7693

#### Does this PR introduce a user-facing change?

```release-note
AdmissionFairSharing: Fix the bug that occasionally a workload may get admitted from a busy LocalQueue,
bypassing the entry penalties.
```

### CODE REVIEW

**Review by IrvingMg — COMMENTED** [review]
I’ve added a new subpackage for Admission Fair Sharing under the queue package, with the intention of also moving the AfsEntryPenalties struct there. 

I think this will help tidy up the code and avoid the circular dependency in CalcLocalQueueFSUsage between the queue and workload packages when using AFS structs. This can be a follow-up.

File: pkg/cache/queue/afs/consumed_resources.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
+/*
```
Comment (IrvingMg) [inline pkg/cache/queue/afs/consumed_resources.go:1]: I’ve added a new subpackage for Admission Fair Sharing under the queue package, with the intention of also moving the AfsEntryPenalties struct there. 

I think this will help tidy up the code and avoid the circular dependency in CalcLocalQueueFSUsage between the queue and workload packages when using AFS structs. This can be a follow-up

File: pkg/controller/core/localqueue_controller.go [hunk 2]
```diff
@@ -273,43 +274,49 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
 
-		// update status
-		return r.updateAdmissionFsStatus(ctx, lq, sum)
-	})
-	return err
-}
+	r.queues.SetAfsConsumedResources(lqKey, sum, r.clock.Now())
+	r.log.V(3).Info("Updated AFS consumed resources cache", "namespace", lq.Namespace, "name", lq.Name, "consumedResources", sum)
 
-func (r *LocalQueueReconciler) updateAdmissionFsStatus(ctx context.Context, lq *kueue.LocalQueue, consumedResources corev1.ResourceList) error {
```
Comment (IrvingMg) [inline pkg/controller/core/localqueue_controller.go:308]: Since we’ve added the cache, do we still need to update consumedResources in the LQ status? If we’re not updating the status anymore, then we might need to update the API to remove that field, right?

**Comment by IrvingMg** [comment]
I’ve opened  draft PR for early review. 

@PBundyra  PTAL.

File: pkg/cache/queue/afs/consumed_resources.go [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+
+// ConsumedResourcesEntry stores the consumed resources for a LocalQueue with timestamp
+type ConsumedResourcesEntry struct {
+	Resources  corev1.ResourceList
+	LastUpdate time.Time
+}
+
+// AfsConsumedResources manages the fair sharing consumed resources cache
+type AfsConsumedResources struct {
+	sync.RWMutex
```
Comment (tenzen-y) [inline pkg/cache/queue/afs/consumed_resources.go]: Why do we need this mutex?
The `resources` typed is syncMap.

Comment (IrvingMg) [reply pkg/cache/queue/afs/consumed_resources.go]: Right, I’ve removed it. Thanks!

File: pkg/controller/core/localqueue_controller.go (hunk 2 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go:308]: I've reverted this change and kept the status update. I think for observability it's still useful to have it. However, I decreased its impact by making it non-blocking for the reconciliation, so if status update fails, we just log the error.

File: pkg/workload/workload.go [hunk 4]
```diff
@@ -320,27 +321,25 @@ func dropExcludedResources(input corev1.ResourceList, excludedPrefixes []string)
...
-	}
-	for resName, resVal := range lq.Status.FairSharing.AdmissionFairSharingStatus.ConsumedResources {
-		weight, found := resWeights[resName]
-		if !found {
-			weight = 1
+	lqKey := utilqueue.KeyFromWorkload(i.Obj)
+
+	if afsConsumedResources != nil {
+		if entry, found := afsConsumedResources.Get(lqKey); found {
+			for resName, resVal := range entry.Resources {
```
Comment (PBundyra) [inline pkg/workload/workload.go]: Can we avoid nesting if's and instead, check if afsConsumedResources == nil and then return 0 if that's the case. Same for if the values is not found in the map

File: pkg/workload/workload.go [hunk 5]
```diff
@@ -350,6 +349,11 @@ func (i *Info) CalcLocalQueueFSUsage(ctx context.Context, c client.Client, resWe
 		usage += weight * penaltyVal.AsApproximateFloat64()
 	}
```
Comment (PBundyra) [inline pkg/workload/workload.go]: Can we consolidate with the consumedResource above to avoid duplicating?

File: pkg/controller/core/localqueue_controller.go [hunk 6]
```diff
@@ -274,41 +281,63 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
 	halfLifeTime := r.admissionFSConfig.UsageHalfLifeTime.Seconds()
 	// reset usage to 0 if halfLife is 0
 	if halfLifeTime == 0 {
-		return r.updateAdmissionFsStatus(ctx, lq, corev1.ResourceList{})
+		now := r.clock.Now()
+		r.queues.SetAfsConsumedResources(lqKey, corev1.ResourceList{}, now)
+		r.log.V(3).Info("Reset AFS consumed resources cache", "namespace", lq.Namespace, "name", lq.Name)
+		if err := r.updateAdmissionFsStatus(ctx, lq, corev1.ResourceList{}, now); err != nil {
+			r.log.V(3).Info("Failed to reset LocalQueue status", "namespace", lq.Namespace, "name", lq.Name, "error", err)
+		}
```
Comment (mimowo) [inline pkg/controller/core/localqueue_controller.go]: This looks suspicious to update the cache before the request succeeds. I guess we could just revert the order, but ideally I think we should follow the analogy to regular usage. Then we consolidate assumed usage it cached usage in workload_controller reconciler handlers.

Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Could you clarify what “consolidate assumed usage and cached usage in workload_controller reconciler handlers” means? Does it mean that we should track assumed vs. actual AFS values? 

If so, I’m wondering whether the decay calculation would then need to happen twice, once during assumption and once in the LQ reconciler, to ensure that we use fresher data.

Comment (mimowo) [reply pkg/controller/core/localqueue_controller.go]: I mean to we have workload assumed usage is consiolidated into "usage", here: https://github.com/kubernetes-sigs/kueue/blob/3b7aee0eb10ccdd9c23ed8fe7e2318047dbc7939/pkg/controller/core/workload_controller.go#L898-L902

I consider this should be analogy to consolidating the cached afsPenalties into the cached consumedResources. I think it could happen also inside the workload_controller.

Let me know if I'm unclear, maybe I'm missing something here which is an important detail. My main point is to basically follow the same flow pattern as for usage, so the analogy I have in mind:
- afsPenalties <-> usage for assumedWorkload
- ConsumedResources <-> usage for admittedWorkload

Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: So the workflow would be:

1. Scheduler: Push the entry penalty on admission (current behavior).
2. workload_controller update when the workload gets admitted: Calculate the new consumed value (with decay + penalty), update the cache, and clear the penalty.
3. LQ reconciler: Recalculate the consumed value (with decay to ensure fresh data), update the cache, and update the status from the cache.

Is this correct?

Comment (mimowo) [reply pkg/controller/core/localqueue_controller.go]: > Scheduler: Push the entry penalty on admission (current behavior).

sgtm

> workload_controller update when the workload gets admitted: Calculate the new consumed value (with decay + penalty), update the cache, and clear the penalty.

Yes, with a small caveat that it would not always mean "clear the penalty", because if we have another workload contributing to the penalty then we should just subtract from the penalty - then last workload will clear( yes). Instead of subtracting it would also work if you stamp each penalty with the workload name/namespace.

> LQ reconciler: Recalculate the consumed value (with decay to ensure fresh data), update the cache, and update the status from the cache.

sgtm

Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: I've applied the changes. PTAL.

**Comment by IrvingMg** [comment]
/test pull-kueue-test-e2e-multikueue-main
/test pull-kueue-test-e2e-main-1-33

Look like network issue:

```
shasum: standard input: no properly formatted SHA checksum lines found
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: plugin install hook for "unittest" exited with error
make: *** [Makefile-deps.mk:110: helm] Error 1
```

See: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7780/pull-kueue-test-e2e-multikueue-main/1992955152935424000

File: pkg/controller/core/localqueue_controller.go (hunk 6 above)
Comment (PBundyra) [reply pkg/controller/core/localqueue_controller.go]: Please do not update the cache until the update to status was successful

File: pkg/controller/core/localqueue_controller.go [hunk 7]
```diff
@@ -274,41 +281,44 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
 }
 
 func (r *LocalQueueReconciler) reconcileConsumedUsage(ctx context.Context, lq *kueue.LocalQueue) error {
+	lqKey := utilqueue.Key(lq)
 	halfLifeTime := r.admissionFSConfig.UsageHalfLifeTime.Seconds()
 	// reset usage to 0 if halfLife is 0
 	if halfLifeTime == 0 {
-		return r.updateAdmissionFsStatus(ctx, lq, corev1.ResourceList{})
+		now := r.clock.Now()
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: Move it to the top to avoid duplication, and keep consistency between cache and status

File: pkg/controller/core/localqueue_controller.go [hunk 8]
```diff
@@ -274,41 +281,44 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
+		r.queues.SetAfsConsumedResources(lqKey, corev1.ResourceList{}, now)
+		r.log.V(3).Info("Reset AFS consumed resources cache", "namespace", lq.Namespace, "name", lq.Name)
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: Please set verbosity to 2

File: pkg/controller/core/localqueue_controller.go [hunk 9]
```diff
@@ -274,41 +281,44 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
+		if err := r.updateAdmissionFsStatus(ctx, lq, corev1.ResourceList{}, now); err != nil {
+			r.log.V(3).Info("Failed to reset LocalQueue status", "namespace", lq.Namespace, "name", lq.Name, "error", err)
+		}
+		return nil
+	}
+
+	now := r.clock.Now()
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: ditto

File: pkg/controller/core/localqueue_controller.go [hunk 10]
```diff
@@ -274,41 +281,44 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
-	sum := resource.MergeResourceListKeepSum(scaledOldUsage, scaledNewUsage)
-	// Add penalty to the final usage
-	lqKey := utilqueue.Key(lq)
-	err = r.queues.UpdateWithPenalty(lqKey, func(penalty corev1.ResourceList) error {
-		sum = resource.MergeResourceListKeepSum(sum, penalty)
+	elapsed := now.Sub(entry.LastUpdate).Seconds()
+	newConsumed := afs.CalculateDecayedConsumed(oldUsage, newUsage, elapsed, halfLifeTime)
+
+	r.queues.SetAfsConsumedResources(lqKey, newConsumed, now)
+	r.log.V(3).Info("Updated AFS consumed resources cache", "namespace", lq.Namespace, "name", lq.Name, "consumedResources", newConsumed)
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: Set verbosity to 2 please

File: pkg/controller/core/localqueue_controller.go [hunk 11]
```diff
@@ -274,41 +281,44 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
 
-		// update status
-		return r.updateAdmissionFsStatus(ctx, lq, sum)
-	})
-	return err
+	return r.updateAdmissionFsStatus(ctx, lq, newConsumed, now)
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: Revert order so it first updates the status and then if there's no error updates the cache

File: pkg/cache/queue/manager.go [hunk 12]
```diff
@@ -810,6 +812,22 @@ func (m *Manager) GetAfsEntryPenalties() *utilmaps.SyncMap[queue.LocalQueueRefer
...
+}
+
+func (m *Manager) DeleteAfsConsumedResources(lqKey queue.LocalQueueReference) {
+	m.afsConsumedResources.Delete(lqKey)
+}
+
+func (m *Manager) GetAfsConsumedResources() *queueafs.AfsConsumedResources {
+	return m.afsConsumedResources
+}
+
```
Comment (PBundyra) [inline pkg/cache/queue/manager.go]: Since there's no logic, I consider it redundant. I'd rather make this field in manager public to avoid such boilerplate

File: pkg/controller/core/localqueue_controller.go [hunk 13]
```diff
@@ -174,8 +175,14 @@ func (r *LocalQueueReconciler) Reconcile(ctx context.Context, req ctrl.Request)
 
 	if afs.Enabled(r.admissionFSConfig) {
 		updated := r.initializeAdmissionFsStatus(&queueObj)
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: I think we should modify it here, and initialize. This would reduce the code added below

File: pkg/controller/core/localqueue_controller.go [hunk 14]
```diff
@@ -274,41 +281,44 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
+			r.log.V(3).Info("Failed to reset LocalQueue status", "namespace", lq.Namespace, "name", lq.Name, "error", err)
+		}
+		return nil
+	}
+
+	now := r.clock.Now()
+	entry, found := r.queues.GetAfsConsumedResourcesFor(lqKey)
+	if !found {
+		entry.LastUpdate = now
 	}
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: IIUC this should never happen because of the code here https://github.com/kubernetes-sigs/kueue/pull/7780/files#diff-9177ca87118e92b78007b8e08ffc92f1a18afa6fd6b4168b464e497e09ec53ecR183-R184

File: pkg/controller/core/workload_controller.go [hunk 15]
```diff
@@ -967,6 +980,43 @@ func (r *WorkloadReconciler) Generic(e event.TypedGenericEvent[*kueue.Workload])
...
+	oldUsage := oldEntry.Resources
+	newUsage := cacheLq.GetAdmittedUsage()
+	elapsed := now.Sub(oldEntry.LastUpdate).Seconds()
+	newConsumed := afs.CalculateDecayedConsumed(oldUsage, newUsage, elapsed, r.admissionFSConfig.UsageHalfLifeTime.Seconds())
+	newConsumed = resource.MergeResourceListKeepSum(newConsumed, penalty)
+
+	r.queues.SetAfsConsumedResources(lqKey, newConsumed, now)
+	r.queues.SubEntryPenalty(lqKey, penalty)
+
+	log.V(3).Info("Updated AFS consumed usage", "localQueue", klog.KRef(wl.Namespace, string(wl.Spec.QueueName)), "consumed", newConsumed)
```
Comment (PBundyra) [inline pkg/controller/core/workload_controller.go]: Please set verbosity to 2

File: pkg/controller/core/workload_controller.go [hunk 16]
```diff
@@ -967,6 +980,43 @@ func (r *WorkloadReconciler) Generic(e event.TypedGenericEvent[*kueue.Workload])
...
+
+	lq := &kueue.LocalQueue{
+		ObjectMeta: metav1.ObjectMeta{
+			Namespace: wl.Namespace,
+			Name:      string(wl.Spec.QueueName),
+		},
+		Spec: kueue.LocalQueueSpec{
+			ClusterQueue: wl.Status.Admission.ClusterQueue,
+		},
+	}
```
Comment (PBundyra) [inline pkg/controller/core/workload_controller.go]: Please refactor GetCacheLocalQueue function to use lqkey and reduce this

File: pkg/workload/workload.go (hunk 4 above)
Comment (IrvingMg) [reply pkg/workload/workload.go]: Done

File: pkg/workload/workload.go (hunk 5 above)
Comment (IrvingMg) [reply pkg/workload/workload.go]: Done

File: pkg/controller/core/localqueue_controller.go (hunk 7 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Done.

File: pkg/controller/core/localqueue_controller.go (hunk 8 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Done.

File: pkg/controller/core/localqueue_controller.go (hunk 10 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Done.

File: pkg/controller/core/localqueue_controller.go (hunk 11 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Done.

File: pkg/cache/queue/manager.go (hunk 12 above)
Comment (IrvingMg) [reply pkg/cache/queue/manager.go]: Done.

File: pkg/controller/core/workload_controller.go (hunk 15 above)
Comment (IrvingMg) [reply pkg/controller/core/workload_controller.go]: Done.

File: pkg/controller/core/workload_controller.go (hunk 16 above)
Comment (IrvingMg) [reply pkg/controller/core/workload_controller.go]: Done.

File: pkg/controller/core/localqueue_controller.go (hunk 13 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Do you mean we should also initialize the consumed cache inside initializeAdmissionFsStatus?

File: pkg/controller/core/localqueue_controller.go (hunk 14 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Lines 183-184 check for the cache entry but don't create it. We still need the `!found` check to handle cases where the cache is missing.

File: pkg/controller/core/localqueue_controller.go (hunk 13 above)
Comment (PBundyra) [reply pkg/controller/core/localqueue_controller.go]: I would rename it into `initializeIfNeeded` and cover both cache and status there

File: pkg/controller/core/localqueue_controller.go [hunk 17]
```diff
@@ -274,41 +281,47 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
-	err = r.queues.UpdateWithPenalty(lqKey, func(penalty corev1.ResourceList) error {
-		sum = resource.MergeResourceListKeepSum(sum, penalty)
+	elapsed := now.Sub(entry.LastUpdate).Seconds()
+	newConsumed := afs.CalculateDecayedConsumed(oldUsage, newUsage, elapsed, halfLifeTime)
 
-		// update status
-		return r.updateAdmissionFsStatus(ctx, lq, sum)
-	})
-	return err
+	r.log.V(2).Info("Updated AFS consumed resources cache", "namespace", lq.Namespace, "name", lq.Name, "consumedResources", newConsumed)
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: This log should be after the request (or even maybe cache to be more future-proof) success

File: pkg/controller/core/localqueue_controller.go [hunk 18]
```diff
@@ -274,41 +281,47 @@ func (r *LocalQueueReconciler) initializeAdmissionFsStatus(lq *kueue.LocalQueue)
...
 
 func (r *LocalQueueReconciler) reconcileConsumedUsage(ctx context.Context, lq *kueue.LocalQueue) error {
+	lqKey := utilqueue.Key(lq)
 	halfLifeTime := r.admissionFSConfig.UsageHalfLifeTime.Seconds()
-	// reset usage to 0 if halfLife is 0
+	now := r.clock.Now()
+
 	if halfLifeTime == 0 {
-		return r.updateAdmissionFsStatus(ctx, lq, corev1.ResourceList{})
+		r.log.V(2).Info("Reset AFS consumed resources cache", "namespace", lq.Namespace, "name", lq.Name)
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: This log should be after the request (or even maybe cache to be more future-proof) success

File: pkg/controller/core/workload_controller.go [hunk 19]
```diff
@@ -900,6 +910,9 @@ func (r *WorkloadReconciler) Update(e event.TypedUpdateEvent[*kueue.Workload]) b
 		if !r.cache.AddOrUpdateWorkload(log, wlCopy) {
 			log.V(2).Info("ClusterQueue for workload didn't exist; ignored for now")
 		}
+		if afs.Enabled(r.admissionFSConfig) && status == workload.StatusAdmitted {
```
Comment (PBundyra) [inline pkg/controller/core/workload_controller.go]: This should also be guarded somehow by ClusterQueue's AdmissionMode

File: pkg/controller/core/localqueue_controller_test.go
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller_test.go:1]: Can we add a test for the scenario where the cache hadn't been initialized earlier

File: pkg/controller/core/localqueue_controller.go (hunk 14 above)
Comment (PBundyra) [reply pkg/controller/core/localqueue_controller.go]: Please see my latest comment there

File: pkg/scheduler/scheduler_afs_test.go
Comment (PBundyra) [inline pkg/scheduler/scheduler_afs_test.go:1]: Same here, do we have a test that covers scenario if the LQ usage cache is not initailized

File: pkg/cache/queue/afs_entry_penalties.go [hunk 20]
```diff
@@ -60,20 +60,6 @@ func (m *AfsEntryPenalties) peek(lqKey utilqueue.LocalQueueReference) corev1.Res
 	return penalty
 }
 
-func (m *AfsEntryPenalties) updateWithPenalty(lqKey utilqueue.LocalQueueReference, fn func(penalty corev1.ResourceList) error) error {
```
Comment (PBundyra) [inline pkg/cache/queue/afs_entry_penalties.go:63]: After we deleted this function it seems the mutex is now redundant. This can be addressed in the follow up PR, but please create a GH issue and follow up on that after merge of this PR

**Comment by PBundyra** [comment]
I like how this PR converges into an LGTM, great job!
After you address my latest comments please run O(200) runs of integration tests that happened to be flaky in the past to ensure it addresses the issue. Please paste the results here

File: pkg/cache/queue/afs_entry_penalties.go (hunk 20 above)
Comment (IrvingMg) [reply pkg/cache/queue/afs_entry_penalties.go:63]: I've opened https://github.com/kubernetes-sigs/kueue/issues/7888

File: pkg/controller/core/localqueue_controller.go (hunk 17 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Done.

File: pkg/controller/core/localqueue_controller.go (hunk 18 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Done.

File: pkg/controller/core/workload_controller.go (hunk 19 above)
Comment (IrvingMg) [reply pkg/controller/core/workload_controller.go]: Done.

File: pkg/controller/core/localqueue_controller_test.go
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller_test.go:1]: Done.

File: pkg/scheduler/scheduler_afs_test.go
Comment (IrvingMg) [reply pkg/scheduler/scheduler_afs_test.go:1]: Done.

File: pkg/controller/core/localqueue_controller.go (hunk 13 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Done.

**Comment by mimowo** [comment]
This is actually user facing (just unlikely), proposal release note, ptal @PBundyra 
/release-note-edit
```release-note
AdmissionFairSharing: Fix the bug that occasionally a workload may get admitted from a busy LocalQueue,
bypassing the entry penalties.
```

**Comment by IrvingMg** [comment]
> After you address my latest comments please run O(200) runs of integration tests that happened to be flaky in the past to ensure it addresses the issue. Please paste the results here

I’m currently running repetitions of the test “admits one workload from each LocalQueue when quota is limited”. So far, over 100 have completed successfully. I’ll share the logs once all 200 are done.

UPDATE: 200 repetitions were completed successfully. Here are the logs, gzip-compressed due to GitHub’s file size constraints.

[out.log.gz](https://github.com/user-attachments/files/23751049/out.log.gz)

File: pkg/controller/core/localqueue_controller_test.go [hunk 21]
```diff
@@ -222,17 +225,14 @@ func TestLocalQueueReconcile(t *testing.T) {
...
-						AdmissionFairSharingStatus: &kueue.LocalQueueAdmissionFairSharingStatus{
-							LastUpdate: metav1.NewTime(clock.Now().Add(-5 * time.Minute)),
-							ConsumedResources: map[corev1.ResourceName]resource.Quantity{
-								corev1.ResourceCPU: resource.MustParse("8"),
-								"GPU":              resource.MustParse("16"),
-							},
-						},
-					}).
 				Obj(),
+			initialConsumedResources: queueafs.ConsumedResourcesEntry{
```
Comment (mimowo) [inline pkg/controller/core/localqueue_controller_test.go:229]: Hm, actually here I have a doubt about restarts. Because I think when Kueue restarts we must populate the cache based on the status of the LQ. So seeing the status removed makes me wonder if we handle restarts properly. Dropping the afsPenalties is ok - the consequence is limited. However, we must double check if the consumedResources already accounted in the status are taken into account. 

So:  please test on a running cluster what happens when Kueue is restarted, say kubectl delete --all pods -nkueue-system. We could also automate that test in the integration tests using StopManager / StartManager helpers.

Comment (mimowo) [reply pkg/controller/core/localqueue_controller_test.go:229]: cc @PBundyra

Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller_test.go:229]: Restart scenario should be handled by  `initializeAfsIfNeeded` function:
https://github.com/kubernetes-sigs/kueue/blob/1c312e28b8dae582bf2617a0b4f9afffb475b648/pkg/controller/core/localqueue_controller.go#L290-L293

where `getCurrentUsageForLocalQueue` is:
https://github.com/kubernetes-sigs/kueue/blob/1c312e28b8dae582bf2617a0b4f9afffb475b648/pkg/controller/core/localqueue_controller.go#L298-L304

A unit test for this scenario was added here:
https://github.com/kubernetes-sigs/kueue/blob/1c312e28b8dae582bf2617a0b4f9afffb475b648/pkg/controller/core/localqueue_controller_test.go#L529-L571

Comment (mimowo) [reply pkg/controller/core/localqueue_controller_test.go:229]: > Restart scenario should be handled by initializeAfsIfNeeded function:

Thank you for the pointers, I will read. In the meanwhile - have you had a chance to check on a live cluster?

Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller_test.go:229]: I’ve removed the status from the tests to reduce verbosity, since it wasn’t required for most of them because the calculations use the cache.

File: pkg/cache/queue/cluster_queue_test.go [hunk 22]
```diff
@@ -158,7 +160,7 @@ func Test_PushOrUpdate(t *testing.T) {
 	for name, tc := range cases {
 		t.Run(name, func(t *testing.T) {
 			ctx, _ := utiltesting.ContextWithLog(t)
-			cq := newClusterQueueImpl(ctx, nil, defaultOrdering, fakeClock, nil, false, nil)
+			cq := newClusterQueueImpl(ctx, nil, defaultOrdering, fakeClock, nil, false, nil, nil)
```
Comment (mimowo) [inline pkg/cache/queue/cluster_queue_test.go:163]: seeing so many params, and many "nil" passed I think it will be better to use the options pattern. However, this is for a technical follow up, don't mix it here.

File: pkg/controller/core/workload_controller.go [hunk 23]
```diff
@@ -967,6 +980,34 @@ func (r *WorkloadReconciler) Generic(e event.TypedGenericEvent[*kueue.Workload])
...
+
+	oldEntry, found := r.queues.AfsConsumedResources.Get(lqKey)
+	if !found {
+		oldEntry.LastUpdate = now
+	}
+
+	cacheLq, err := r.cache.GetCacheLocalQueue(wl.Status.Admission.ClusterQueue, lqKey)
+	if err != nil {
+		log.V(2).Info("Failed to get cache LocalQueue", "error", err)
+		return
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:996]: Longer term this error should not be silenced, but the operation would be retried in Reconciler, however this requires a bigger refactoring to move the logic from Update to Reconcile: https://github.com/kubernetes-sigs/kueue/issues/5310

cc @Singularity23x0

File: pkg/controller/core/localqueue_controller_test.go (hunk 21 above)
Comment (mimowo) [reply pkg/controller/core/localqueue_controller_test.go:229]: Yeah, I read it and

```golang
 if !hasCache { 
 	currentUsage := r.getCurrentUsageForLocalQueue(lq.Spec.ClusterQueue, lqKey) 
 	r.queues.AfsConsumedResources.Set(lqKey, currentUsage, now) 
 } 
 ```
 makes sense to me covering this case

Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller_test.go:229]: > In the meanwhile - have you had a chance to check on a live cluster?

Not yet. I’ll try it on a Kind cluster and share the results.

Comment (mimowo) [reply pkg/controller/core/localqueue_controller_test.go:229]: sgtm, I think it is enough to submit workloads to populate the consumedResources in status, then restart Kueue and make sure the status is not wiped out. Also, that it gets decaying properly.

**Comment by mimowo** [comment]
Looks much more solid now 👍 
/lgtm
/approve
Hold for:
1. manual test on a live cluster for Kueue restart: https://github.com/kubernetes-sigs/kueue/pull/7780#discussion_r2563832983
2. in case @PBundyra has some remaining comments
/hold

**Comment by IrvingMg** [comment]
> 1. manual test on a live cluster for Kueue restart

Here are the logs with the steps I followed for the manual restart test on a Kind cluster: 
[afs-restart-results.log](https://github.com/user-attachments/files/23768105/afs-restart-results.log)

**Comment by mimowo** [comment]
Thank you, the raport lgtm

File: pkg/cache/queue/afs/consumed_resources.go [hunk 24]
```diff
@@ -0,0 +1,62 @@
...
+
+// Get retrieves the consumed resources for a LocalQueue
+func (a *AfsConsumedResources) Get(lqKey utilqueue.LocalQueueReference) (ConsumedResourcesEntry, bool) {
+	return a.resources.Get(lqKey)
+}
+
+// Delete removes the consumed resources entry for a LocalQueue
+func (a *AfsConsumedResources) Delete(lqKey utilqueue.LocalQueueReference) {
+	a.resources.Delete(lqKey)
+}
```
Comment (PBundyra) [inline pkg/cache/queue/afs/consumed_resources.go:62]: IIUC this is unused, please remove

File: pkg/controller/core/localqueue_controller.go [hunk 25]
```diff
@@ -173,10 +174,16 @@ func (r *LocalQueueReconciler) Reconcile(ctx context.Context, req ctrl.Request)
...
+		initNeeded := r.initializeAfsIfNeeded(&queueObj)
 		lqKey := utilqueue.Key(&queueObj)
-		if interval := r.admissionFSConfig.UsageSamplingInterval.Duration; !updated && sinceLastUpdate < interval && !r.queues.HasPendingPenaltyFor(lqKey) {
+		var sinceLastUpdate time.Duration
+		if entry, found := r.queues.AfsConsumedResources.Get(lqKey); found {
+			sinceLastUpdate = r.clock.Now().Sub(entry.LastUpdate)
+		} else {
+			// No cache entry, force reconciliation by setting time >= interval
+			sinceLastUpdate = r.admissionFSConfig.UsageSamplingInterval.Duration
+		}
```
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go]: Isn't this redundant now, given we always initialize if there was no entry before? We never delete from the cache so I think it should always be there

**Comment by PBundyra** [comment]
Just some nits, other than that lgtm! Thanks @IrvingMg great job!

**Comment by PBundyra** [comment]
Leaving unholding to @mimowo

File: pkg/controller/core/localqueue_controller.go (hunk 25 above)
Comment (mimowo) [reply pkg/controller/core/localqueue_controller.go]: Hm, but the call to initializeAfsIfNeeded (L177) and L180 are not under a lock, so what guarantees there is not concurrent modifcation which would remove the key in-between (for example by WorkloadController)?

File: pkg/controller/core/localqueue_controller.go
Comment (PBundyra) [inline pkg/controller/core/localqueue_controller.go:230]: I think we should also delete from afsConsumedResources here

File: pkg/cache/queue/afs/consumed_resources.go (hunk 24 above)
Comment (mimowo) [reply pkg/cache/queue/afs/consumed_resources.go:62]: I'm not sure we want to remove the fuction. I think we might be missing invoking the function from the LQ even handler for Delete. If we never call Delete I think we may have a memory leak that the entry stay in the map outliving the deleted LQ by user.

File: pkg/controller/core/localqueue_controller.go (hunk 25 above)
Comment (mimowo) [reply pkg/controller/core/localqueue_controller.go]: Even if we only call Delete from event handler for LQ, then I think it is possible:
1. Update triggers Reconcile
2. Reconcile starts
3. User deletes object
Now "Delete" event handler may be running concurrently with the ongoing Reconcile from point (2.), and thus call AfsConsumedResources.Delete, after initializeAfsIfNeeded, but before AfsConsumedResources.Get.

So, I agree this is super unlikely, but we need to be careful about the potential crash here. 

As long as we handle such unlikely scenario gracefully (no panic) I'm good.No need for anything sophisticated like: L183-L184.

**Comment by mimowo** [comment]
> Leaving unholding to @mimowo

sg, I think the remaining aspects of the PR: 
1. ensure the Delete is called when the LQ is deleted to make sure no memory leak.
2. potentially simplify handling of the corner case discussed in https://github.com/kubernetes-sigs/kueue/pull/7780#discussion_r2564722590 (to be checked)

File: pkg/cache/queue/afs/consumed_resources.go (hunk 24 above)
Comment (IrvingMg) [reply pkg/cache/queue/afs/consumed_resources.go:62]: Right, I was missing this. Added, thanks!

File: pkg/controller/core/localqueue_controller.go (hunk 25 above)
Comment (IrvingMg) [reply pkg/controller/core/localqueue_controller.go]: Done. I’ve added a check after init to ensure the entry is still there. If not, the reconciliation is skipped.

https://github.com/kubernetes-sigs/kueue/blob/19b4c9198a57c66e7dc79ff40f05b169f7710440/pkg/controller/core/localqueue_controller.go#L176-L183

File: pkg/cache/queue/cluster_queue_test.go (hunk 22 above)
Comment (IrvingMg) [reply pkg/cache/queue/cluster_queue_test.go:163]: I've created https://github.com/kubernetes-sigs/kueue/issues/7912

File: pkg/controller/core/localqueue_controller.go
Comment (mimowo) [reply pkg/controller/core/localqueue_controller.go:230]: I can see it done here: https://github.com/kubernetes-sigs/kueue/compare/1c312e28b8dae582bf2617a0b4f9afffb475b648..19b4c9198a57c66e7dc79ff40f05b169f7710440#diff-9177ca87118e92b78007b8e08ffc92f1a18afa6fd6b4168b464e497e09ec53ecR225-R227

**Comment by mimowo** [comment]
Thank you 👍 
/unhold
/lgtm

**Comment by mimowo** [comment]
@IrvingMg please check if we can cherrypick. Since AFS is alpha on 0.13 and 0.14 this is not "must", but if we can, then it would be great. It would be great to try to backport to 0.14 at least.
