### PR TITLE
Protect GuaranteedQuota When FairSharing Weight=0

### LINKED ISSUE #4961: [Fair Sharing] Preempting Nominal Quota when FairSharing Weight is 0
**What happened**:
When FairSharing weight=0, we even preempt even workloads using nominal quota

**What you expected to happen**:
Nominal quota workloads should be protected. Only borrowing should be immediately reclaimed/preempted

**How to reproduce it (as minimally and precisely as possible)**:
Create Queues/Cohorts of the following structure, with ReclaimWithinCohort=Any

- Root-Cohort
  - Best-Effort-Cohort(weight 0, nominal 1)
    - Best-Effort-Queue
  - High-Priority-Queue(weight 1, nominal 0)

Submit a workload to Best-Effort-Queue of size 1, then to High-Priority-Queue. Remark that high-priority-queue can preempt from best-effort, even when it is not borrowing. I'm not sure if this is also a problem in the flat case; this should also be tested:

- Root-Cohort
  - Best-Effort-Queue(weight 0, nominal 1)
  - High-Priority-Queue(weight 1, nominal 0)

- Kueue version: 0.11.3

### PR DESCRIPTION
**Pull request by gabesaba**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We protect workloads running under nominal quota from being preempted, even when Cohort has FairWeight of 0. We do this by only returning math.MaxInt score when the Cohort is borrowing. When a Cohort is not borrowing, it gets a FairShare score of 0.

#### Which issue(s) this PR fixes:
Fixes #4961

#### Does this PR introduce a user-facing change?
```release-note
Fix bug where Cohorts with FairWeight set to 0 could have workloads running within Nominal Quota preempted
```

### CODE REVIEW

File: pkg/cache/fair_sharing.go [hunk 1]
```diff
@@ -38,19 +38,18 @@ type dominantResourceShareNode interface {
...
+// or Cohort is borrowing, we return math.MaxInt.
 func dominantResourceShare(node dominantResourceShareNode, wlReq resources.FlavorResourceQuantities) (int, corev1.ResourceName) {
 	if !node.HasParent() {
 		return 0, ""
 	}
-	if node.fairWeight().IsZero() {
-		return math.MaxInt, ""
-	}
 
 	borrowing := make(map[corev1.ResourceName]int64, len(node.getResourceNode().SubtreeQuota))
```
Comment (tenzen-y) [inline pkg/cache/fair_sharing.go:54]: what if the number of`borrowing` is 0?
Are there still the same problems?

I meant I guess lines 61-62 still have problems.

```
	if len(borrowing) == 0 {
		return 0, ""
	}
```

**Comment by PBundyra** [comment]
/lgtm
Thanks

File: pkg/cache/fair_sharing.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/cache/fair_sharing.go:54]: Ah, I missunderstand something. Line 61-62 indicates there is not borrowing. So, we do not need to case the weight value.

/approve

Comment (tenzen-y) [reply pkg/cache/fair_sharing.go:54]: /cherry-pick release-0.11
