### PR TITLE
Fix: fix cohortName field for `v1beta2.ClusterQueue`

### LINKED ISSUE #9281: kubectl always lists an empty cohort for `v1beta2.ClusterQueue`
**What happened**:
When you create a `ClusterQueue` belonging to a `Cohort`, the cohort's name is not displayed when running `kubectl get cq`.

**What you expected to happen**:
I'd expect the cohort's name to be displayed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `ClusterQueue` with `.spec.cohortName`.
2. Run `kubectl get cq`.

**Anything else we need to know?**:
The name of `.spec.cohort` was changed to `.spec.cohortName` in `v1beta2`, but `.spec.cohort` is still referenced in `genclient`:
https://github.com/kubernetes-sigs/kueue/blob/a4692d942d656caee4bce019abc563da76ab3bb4/apis/kueue/v1beta2/clusterqueue_types.go#L540

Since `v1beta2` started being used for storage in [`v0.16.0`](https://github.com/kubernetes-sigs/kueue/releases/tag/v0.16.0), it's likely not an issue in versions `<0.16.0`.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): v0.16.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by polinasand**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

For v1beta2:
When running `kubectl get clusterqueue` command, the expected output is:
```
NAME                                        COHORT   PENDING WORKLOADS
clusterqueue.kueue.x-k8s.io/cluster-queue   cohort-1         0
```
But the actual output has cohort name missing:
```
NAME                                        COHORT   PENDING WORKLOADS
clusterqueue.kueue.x-k8s.io/cluster-queue            0
```
This PR fixes this bug.

Manual testing:
Before:
Screenshot 2026-02-23 at 11 02 55

After:
Screenshot 2026-02-23 at 10 53 45

#### Which issue(s) this PR fixes:

Fixes #9281

#### Does this PR introduce a user-facing change?
```release-note
Fixed invalid field name in the `ClusterQueue` printer columns. The "Cohort" column will now correctly display the assigned cohort in kubectl, k9s, and other UI tools instead of being blank.
```

### CODE REVIEW

**Comment by mimowo** [comment]
Thank you @polinasand for working on that 👍

**Comment by Singularity23x0** [comment]
Could you provide the results of a manual test for this command? A screenshot of the command being executed and returning the correct output should be more than enough.

File: apis/kueue/v1beta2/clusterqueue_types.go [hunk 1]
```diff
@@ -537,7 +537,7 @@ type BorrowWithinCohort struct {
 // +kubebuilder:storageversion
 // +kubebuilder:resource:scope=Cluster,shortName={cq}
 // +kubebuilder:subresource:status
-// +kubebuilder:printcolumn:name="Cohort",JSONPath=".spec.cohort",type=string,description="Cohort that this ClusterQueue belongs to"
+// +kubebuilder:printcolumn:name="Cohort",JSONPath=".spec.cohortName",type=string,description="Cohort that this ClusterQueue belongs to"
```
Comment (kshalot) [inline apis/kueue/v1beta2/clusterqueue_types.go:540]: You could make a drive-by change of the references to `.spec.cohort` in the docstrings in this file, like [here](https://github.com/kubernetes-sigs/kueue/blob/d0566be060242295d73394ce930b08f5205e38ba/apis/kueue/v1beta2/clusterqueue_types.go#L260). Seems like it falls under the same bucket.

**Comment by kshalot** [comment]
> @polinasand: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kueue-verify-main	[0386597](https://github.com/kubernetes-sigs/kueue/commit/03865971a015484d4d8cbb2bae5f33f14d3b2f88)	[link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9394/pull-kueue-verify-main/2025893613367463936)	true	`/test pull-kueue-verify-main`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=kueue&pr=9394). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Apolinasand). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/kueue/issues?q=is:issue+is:open) when you hit one in your PR.
> 
> Details

FYI this should generate all that's missing;
```sh
$ make generate update-helm
```

**Comment by mimowo** [comment]
/approve
Leaving lgtm to @kshalot 
Let's cherrypick because the versions are affected as they use v1beta2:
/cherrypick release-0.16
/cherrypick release-0.15

**Comment by kshalot** [comment]
@polinasand The cherry pick to `release-0.15` failed as there are merge conflicts in that branch.

You'll have to manually create one, PTAL at `hack/cherry_pick_pull.sh`.

**Comment by mimowo** [comment]
/release-note-edit
```release-note
CLI: Fix the bug that cohort name wasn't actually displayed in the output when running `kubectl get clusterqueue` command.
```

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Fixed invalid field name in the `ClusterQueue` printer columns. The "Cohort" column will now correctly display the assigned cohort in kubectl, k9s, and other UI tools instead of being blank.
```
