### PR TITLE
Wait for quota reservation before admission in Should readmit preempted Job with priorityClass in alternative flavor with admission check  test

### LINKED ISSUE #7714: [Flaky] Interacting with scheduler when the cluster queue has admission check and workload priority class Should readmit preempted Job with priorityClass in alternative flavor with admission check
/kind flake

**What happened**:

Job Controller Suite: [It] Interacting with scheduler when the cluster queue has admission check and workload priority class Should readmit preempted Job with priorityClass in alternative flavor with admission check 

```
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:615 with:
Expected
    <int>: 0
to equal
    <int>: 1 failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:615 with:
Expected
    <int>: 0
to equal
    <int>: 1
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2454 @ 11/17/25 15:58:38.058
}
```

**What you expected to happen**:

No errors

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7711/pull-kueue-test-integration-baseline-main/1990446599133728768

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Wait for quota reservation before admission.

#### Which issue(s) this PR fixes:

Fixes #7714

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/util/util.go [hunk 1]
```diff
@@ -293,18 +293,27 @@ func FinishWorkloads(ctx context.Context, k8sClient client.Client, workloads ...
 		}, Timeout, Interval).Should(gomega.Succeed())
 	}
 }
-
```
Comment (mimowo) [inline test/util/util.go:296]: nit revert

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 2]
```diff
@@ -2433,10 +2433,8 @@ var _ = ginkgo.Describe("Interacting with scheduler", ginkgo.Ordered, ginkgo.Con
 				Name:      workloadjob.GetWorkloadNameForJob(highJob.Name, highJob.UID),
 				Namespace: ns.Name,
 			}
-			ginkgo.By("Fetching the created high priority workload", func() {
-				gomega.Eventually(func(g gomega.Gomega) {
-					g.Expect(k8sClient.Get(ctx, highWlLookupKey, createdHighWorkload)).Should(gomega.Succeed())
-				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			ginkgo.By("Verifying the created high priority workload is quota reserved", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2434]: Do the same for the low priority workload above. I think it could also flake there for the same reason

Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2434]: Good point! Thank you!

File: test/util/util.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/util/util.go:296]: Thanks!

**Review by mimowo — COMMENTED** [review]
Thank you for stabilizing the build!
/lgtm
/approve
/cherrypick release-0.14
/cherrypick release-0.13
