### PR TITLE
Fix node scheduling properties change detection logic

### LINKED ISSUE #8400: TAS resource flavor controller regularly reconciled by irrelevant node updates
**What happened**:

`tas_resource_flavor_controller` already filters out some irrelevant node updates, but still some unnecessary status updates trigger the reconciliation. For example, `.status.runtimeHandler` randomly changes its order, `.status.images` changes whenever new images are loaded onto the node. Even when testing this with kind, the node's event updates occur only every few seconds. 

**What you expected to happen**:

Inadmissible workloads are re-evaluated only when the related events happen.

**How to reproduce it (as minimally and precisely as possible)**:

Add a log line after `checkNodeSchedulingPropertiesChanged(oldNode, newNode)` and check the object diffs.

**Anything else we need to know?**:

In our production env, we apply the following patches:

- Instead of filtering out unnecessary events, only extract the required events. e.g.
```
func nodeSchedulingPropertiesChange(newNode *v1.Node, oldNode *v1.Node) eventType {
	nodeChangeExtracters := []nodeChangeExtractor{
		extractNodeSpecUnschedulableChange,
		extractNodeAllocatableChange,
		extractNodeLabelsChange,
		extractNodeTaintsChange,
		extractNodeConditionsChange,
		extractNodeAnnotationsChange,
	}
	var at eventType
	for _, fn := range nodeChangeExtracters {
		at |= fn(newNode, oldNode)
	}
	return at
}
...
```

- Make the queueing interval customizable to ease requeue frequency. This prevents requeueing when a node's taint is continuously updated over a short period (e.g., due to hardware failure). This workaround might be unnecessary once https://github.com/kubernetes-sigs/kueue/issues/8339 is resolved.
:

```
func (h *nodeHandler) queueReconcileForNode(node *corev1.Node, q workqueue.TypedRateLimitingInterface[reconcile.Request]) {
	if node == nil {
		return
	}
	// trigger reconcile for TAS flavors affected by the node being created or updated
	for name, cache := range h.cache.CloneTASCache() {
		if nodeBelongsToFlavor(node, cache.NodeLabels(), cache.TopologyLevels()) {
			q.AddAfter(reconcile.Request{NamespacedName: types.NamespacedName{
				Name: string(name),
			}}, h.tasFlavorRequeuPeriod) // originally: `constants.UpdatesBatchPeriod` (1s)
		}
	}
}
```

**Environment**:

- Kubernetes version (use `kubectl version`): v1.34.2
- Kueue version (use `git describe --tags --dirty --always`): v1.15.2
- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Ladicle**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In this PR, instead of filtering out unnecessary events, only extract the required events.
`tas_resource_flavor_controller` already filters out some irrelevant node updates, but some unnecessary status updates still trigger reconciliation. 

#### Which issue(s) this PR fixes:

Fixes #8400

#### Special notes for your reviewer:

I've included a node annotation change extractor to align with the unit test, though I'm not entirely sure if it's the right trigger to retry for inadmissible workloads.

#### Does this PR introduce a user-facing change?

```release-note
TAS: fix TAS resource flavor controller to extract only scheduling-relevant node updates to prevent unnecessary reconciliation.
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @PBundyra

File: pkg/controller/tas/resource_flavor.go [hunk 1]
```diff
@@ -250,7 +216,83 @@ func nodeBelongsToFlavor(node *corev1.Node, nodeLabels map[string]string, levels
...
-	return !nodeSemantic.DeepEqual(oldNode, newNode)
+type eventType int64
+
+const (
+	UpdateNodeAllocatable eventType = 1 << iota
+	UpdateNodeLabel
+	UpdateNodeTaint
+	UpdateNodeCondition
+	UpdateNodeAnnotation
+	UpdateNodeSpecUnschedulable
```
Comment (mimowo) [inline pkg/controller/tas/resource_flavor.go]: no need to export those

File: pkg/controller/tas/resource_flavor_test.go [hunk 2]
```diff
@@ -91,17 +91,36 @@ func TestNodeHandler_Update(t *testing.T) {
 						LastTransitionTime: now,
 					},
 				).Obj(),
-			wantChanged: false,
+			wantChanged: None,
+		},
+		"RuntimeHandler order changed": {
```
Comment (mimowo) [inline pkg/controller/tas/resource_flavor_test.go:96]: Please add an analogous unit test for images

File: pkg/controller/tas/resource_flavor.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/tas/resource_flavor.go]: also, since they all refer to nodes, maybe it is better to name them just as:
```
	nodeLabelsChanged
    nodeTaintsChanged
	nodeNormalizedConditionsChanged
	nodeAnnotationsChanged
	nodeSpecUnschedulableChanged
```

File: pkg/controller/tas/resource_flavor_test.go
Comment (tenzen-y) [inline pkg/controller/tas/resource_flavor_test.go:1]: I'd propose introducing `RuntimeHandlers` and `Images` chain functions for NodeWrapper instead of anonymous functions.

But, we can do it in a follow-up PR.

Comment (tenzen-y) [reply pkg/controller/tas/resource_flavor_test.go:1]: cc @mimowo

Comment (tenzen-y) [reply pkg/controller/tas/resource_flavor_test.go:1]: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/util/testingjobs/node/wrappers.go

Comment (mimowo) [reply pkg/controller/tas/resource_flavor_test.go:1]: sgtm, thanks for opening the issue https://github.com/kubernetes-sigs/kueue/issues/8457
