### PR TITLE
TAS: fixed performance issue due to unncessary (empty) request by TopologyUngater

### LINKED ISSUE #8277: TAS: performance issue due to unncessary (empty) request by TopologyUngater
**What happened**:

There are many unncessary request sent by TopologyUngater for TAS workloads  (at least for workloads with >50 pods). 

We see that TopologyUngater sends empty requests are it unconditionally returns "true" from the Patch update function, here: https://github.com/kubernetes-sigs/kueue/blob/441fe203453014175d04dba136e4e3de8d96e9b4/pkg/controller/tas/topology_ungater.go#L246-L252

**What you expected to happen**:

TopologyUngater skips sending the request if already ungated.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix performance issue due to unncessary (empty) request by TopologyUngater

#### Which issue(s) this PR fixes:

Fixes #8277

#### Does this PR introduce a user-facing change?

```release-note
TAS: fixed performance issue due to unnecessary (empty) request by TopologyUngater
```

### CODE REVIEW

File: pkg/controller/tas/topology_ungater.go [hunk 1]
```diff
@@ -243,13 +244,18 @@ func (r *topologyUngater) Reconcile(ctx context.Context, req reconcile.Request)
 		podWithUngateInfo := &allToUngate[i]
 		var ungated bool
 		e := utilclient.Patch(ctx, r.client, podWithUngateInfo.pod, func() (bool, error) {
-			log.V(3).Info("ungating pod", "pod", klog.KObj(podWithUngateInfo.pod), "nodeLabels", podWithUngateInfo.nodeLabels)
 			ungated = utilpod.Ungate(podWithUngateInfo.pod, kueue.TopologySchedulingGate)
-			if podWithUngateInfo.pod.Spec.NodeSelector == nil {
-				podWithUngateInfo.pod.Spec.NodeSelector = make(map[string]string)
+			if !equality.Semantic.DeepEqual(podWithUngateInfo.pod.Spec.NodeSelector, podWithUngateInfo.nodeLabels) {
```
Comment (mimowo) [inline pkg/controller/tas/topology_ungater.go]: Please add test cases:
1. NodeSelector is specified already, so `equality.Semantic.DeepEqual(podWithUngateInfo.pod.Spec.NodeSelector, podWithUngateInfo.nodeLabels)` is true, to verify that we still would ungate in this case
2. to demonstrate the client does not send the request. I think this could be done in unit test for topology_ungater_test.go by interceptor which always errors.

File: pkg/controller/tas/topology_ungater.go [hunk 2]
```diff
@@ -243,13 +242,21 @@ func (r *topologyUngater) Reconcile(ctx context.Context, req reconcile.Request)
...
 			}
-			maps.Copy(podWithUngateInfo.pod.Spec.NodeSelector, podWithUngateInfo.nodeLabels)
-			return true, nil
+			for k, v := range podWithUngateInfo.nodeLabels {
+				if current, exists := podWithUngateInfo.pod.Spec.NodeSelector[k]; !exists || current != v {
+					podWithUngateInfo.pod.Spec.NodeSelector[k] = v
+					changed = true
+				}
+			}
+			return changed, nil
```
Comment (PBundyra) [inline pkg/controller/tas/topology_ungater.go]: This wouldn't catch the case where there would be something present in `podWithUngateInfo.pod.Spec.NodeSelector` and not in `podWithUngateInfo.nodeLabels`. I suggest using `maps.Equal`

File: pkg/controller/tas/topology_ungater.go [hunk 3]
```diff
@@ -243,13 +242,21 @@ func (r *topologyUngater) Reconcile(ctx context.Context, req reconcile.Request)
 		podWithUngateInfo := &allToUngate[i]
 		var ungated bool
 		e := utilclient.Patch(ctx, r.client, podWithUngateInfo.pod, func() (bool, error) {
-			log.V(3).Info("ungating pod", "pod", klog.KObj(podWithUngateInfo.pod), "nodeLabels", podWithUngateInfo.nodeLabels)
 			ungated = utilpod.Ungate(podWithUngateInfo.pod, kueue.TopologySchedulingGate)
+			if ungated {
+				log.V(3).Info("ungating pod", "pod", klog.KObj(podWithUngateInfo.pod), "nodeLabels", podWithUngateInfo.nodeLabels)
```
Comment (PBundyra) [inline pkg/controller/tas/topology_ungater.go:248]: If we want to log this after ensuring we indeed send the Patch then we should log it right before returning, depending on `changed` value

File: pkg/controller/tas/topology_ungater.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/controller/tas/topology_ungater.go]: This is not working because the number of keys can be different.

Comment (mbobrovskyi) [reply pkg/controller/tas/topology_ungater.go]: I tried this solution and unit tests failed.

Comment (mimowo) [reply pkg/controller/tas/topology_ungater.go]: ~why the number of keys would be different? We can create the Pod with the nodeSelector already as the TAS would add~

Comment (PBundyra) [reply pkg/controller/tas/topology_ungater.go]: After second consideration this looks good to me, thanks

Comment (mimowo) [reply pkg/controller/tas/topology_ungater.go]: I think if the Pod is already ungated we can skip the node selectors update. 

I think such a request would not even succeed because Kubernetes has validation against mutating a pod template for ungated pods.

This would also simplify the code allowing to return to simple Copy

Comment (mimowo) [reply pkg/controller/tas/topology_ungater.go]: So here is the validation code https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L5788-L5794 in the code k8s which only accepts node selector updates if the pod is gated. In TAS we update the node selectors atomically in the same request which ungates the Pod. So, if the pod is already ungated, there is no need to change selectors.

Comment (mimowo) [reply pkg/controller/tas/topology_ungater.go]: So I want to propose:

```golang
ungated = utilpod.Ungate(podWithUngateInfo.pod, kueue.TopologySchedulingGate)
if ungated {
	log.V(3).Info("ungating pod", "pod", klog.KObj(podWithUngateInfo.pod), "nodeLabels", podWithUngateInfo.nodeLabels)
	if podWithUngateInfo.pod.Spec.NodeSelector == nil {
		podWithUngateInfo.pod.Spec.NodeSelector = make(map[string]string)
  	}
    maps.Copy(podWithUngateInfo.pod.Spec.NodeSelector, podWithUngateInfo.nodeLabels)
}
return ungated, nil
```

Comment (mbobrovskyi) [reply pkg/controller/tas/topology_ungater.go]: Done

**Comment by mimowo** [comment]
/release-note-edit
```release-note
TAS: fixed performance issue due to unnecessary (empty) request by TopologyUngater
```
