### PR TITLE
Fix second-pass queue cleanup when workload no longer needs retry

### LINKED ISSUE #8357: TAS NodeHotSwap: make sure QueueSecondPassIfNeeded removes workload from second-queue pass if no longer needed
**What would you like to be cleaned**:

Make sure workload controller calling QueueSecondPassIfNeeded would remove the workload from second pass queue if no longer needed there.

The scenario:
1. node failure controller adds the unhealthyNodes to the workload
2. workload controller adds the workload to QueueSecondPassIfNeeded
3. node failure controller removes the node from unhealtyNodes becuase the node is now healthy
Issue: workload controller does not remove the workload from QueueSecondPassIfNeeded

**Why is this needed**:

To avoid potential race condition bugs, and make the interaction between controllers easier.

### PR DESCRIPTION
**Pull request by skools-here**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes cleanup of the second-pass scheduling queue by ensuring workloads are removed once they no longer require a retry, while preserving the initial backoff behavior.

#### Which issue(s) this PR fixes:
Fixes #8357

#### Special notes for your reviewer:
Cleanup is gated on retry iteration to avoid prematurely canceling the initial backoff window.

#### Does this PR introduce a user-facing change?

```release-note
TAS: Fixed an issue where workloads could remain in the second-pass scheduling queue (used for integration
or TAS with ProvisioningRequests, and for TAS Node Hot Swap) even if they no longer require to be in the queue.
```

### CODE REVIEW

File: pkg/cache/queue/manager.go [hunk 1]
```diff
@@ -815,17 +815,21 @@ func (m *Manager) DeleteSecondPassWithoutLock(wl *kueue.Workload) {
...
 		delay := m.secondPassQueue.nextDelay(iteration)
-		log := ctrl.LoggerFrom(ctx)
 		log.V(3).Info("Workload pre-queued for second pass (with backoff)", "workload", workload.Key(w), "delay", delay)
 		m.secondPassQueue.prequeue(w)
 		m.clock.AfterFunc(delay, func() {
 			m.queueSecondPass(ctx, w, iteration)
 		})
 		return true
 	}
+	if !workload.NeedsSecondPass(w) && iteration > 0 {
```
Comment (gabesaba) [inline pkg/cache/queue/manager.go]: nit: else-if, and add a short comment to document this branch?
```suggestion
	else if iteration > 0 {
	  // some comment, including link to #8357
```

**Review by gabesaba — COMMENTED** [review]
Thanks for the fix! I just have a small nitpick comment

/approve

**Comment by gabesaba** [comment]
And please update the release-note

**Comment by skools-here** [comment]
Hey @gabesaba I fixed the changes and added release notes also kindly review!

File: pkg/cache/queue/manager.go [hunk 2]
```diff
@@ -815,16 +815,22 @@ func (m *Manager) DeleteSecondPassWithoutLock(wl *kueue.Workload) {
 // QueueSecondPassIfNeeded queues for the second pass of scheduling with exponential
 // delay.
 func (m *Manager) QueueSecondPassIfNeeded(ctx context.Context, w *kueue.Workload, iteration int) bool {
+	log := ctrl.LoggerFrom(ctx)
```
Comment (mimowo) [inline pkg/cache/queue/manager.go:818]: Could you please add some unit test for that changes in, probably in TestQueueSecondPassIfNeeded?

Comment (skools-here) [reply pkg/cache/queue/manager.go:818]: Thanks! I’ll add unit coverage for this case and update the PR.

**Comment by gabesaba** [comment]
> Hey @gabesaba I fixed the changes and added release notes also kindly review!

thank you! will wait for @mimowo's comment to be addressed.

File: pkg/cache/queue/manager.go (hunk 2 above)
Comment (skools-here) [reply pkg/cache/queue/manager.go]: Added the unit coverage in TestQueueSecondPassIfNeeded for the cleanup path when a workload no longer requires a retry after the first iteration. Thanks!

**Comment by skools-here** [comment]
> > Hey @gabesaba I fixed the changes and added release notes also kindly review!
> 
> thank you! will wait for @mimowo's comment to be addressed.

I have completed what @mimowo said kindly take a look !

**Comment by skools-here** [comment]
The e2e job `pull-kueue-test-e2e-main-1-35 `failed twice without a test assertion failure. Unit tests and lint are passing locally. This seems like an infra flake.

**Comment by gabesaba** [comment]
> This seems like an infra flake.

I think so too

```
Error response from daemon: Head "https://registry.k8s.io/v2/jobset/jobset/manifests/v0.10.1": dial tcp 34.96.108.209:443: i/o timeout
```

/retest

File: pkg/cache/queue/manager_test.go [hunk 3]
```diff
@@ -1449,6 +1456,13 @@ func TestQueueSecondPassIfNeeded(t *testing.T) {
 			for _, wl := range tc.workloads {
 				manager.QueueSecondPassIfNeeded(ctx, wl, 0)
 			}
+			if name == "workload no longer needs second pass after first iteration" {
+				manager.QueueSecondPassIfNeeded(
+					ctx,
+					baseWorkloadNotNeedingSecondPass.DeepCopy(),
+					1,
+				)
+			}
```
Comment (gabesaba) [inline pkg/cache/queue/manager_test.go]: This is an anti-pattern - having a special case in the shared test logic for one of the test cases.

Additionally, are we testing in this case that the new logic works? I don't see anything which changes whether the 2nd pass is needed, nor checks if it is removed from the queue.

We might need another test fixture to test this. Let me know if you need help (though I'm OOO monday)

Comment (mimowo) [reply pkg/cache/queue/manager_test.go]: I can see this code adjusted to use `DeleteWorkload`, but I'm not clear this captures what we want to test. Using DeleteWorkload does not correspond to the original issue https://github.com/kubernetes-sigs/kueue/issues/8357.

IIUC the intention is to show that `QueueSecondPassIfNeeded` would delete the workload if it was already added, but the update is no longer needed. 

To better capture the intention, I would propose to add a new test case parameter like `update: func(wl *kueue.Workload)`. If specified it allows to update the workload, and if updated we call `QueueSecondPassIfNeeded` once again. This will make sure non of the pre-existing tests are affected, but we can test the new scenarios. wdyt?

Comment (skools-here) [reply pkg/cache/queue/manager_test.go]: Thanks for the feedback! I’ll refactor the tests to use a dedicated fixture that updates the workload from “needs second pass” to “no longer needs second pass” and re invokes QueueSecondPassIfNeeded. I’ll push an update shortly.

**Comment by mimowo** [comment]
@skools-here please let us know if you have cycles to work on completing that. I would be great to include in the next patch.

**Comment by skools-here** [comment]
> @skools-here please let us know if you have cycles to work on completing that. I would be great to include in the next patch.

Thanks for asking! Yes, I do have cycles to work on this. I’m currently refactoring the test to cover the update transition as discussed, and I’ll push an updated patch shortly.

**Comment by skools-here** [comment]
I have pushed the changes in test can you please take a look.

File: pkg/cache/queue/manager.go [hunk 4]
```diff
@@ -833,6 +839,12 @@ func (m *Manager) queueSecondPass(ctx context.Context, w *kueue.Workload, iterat
 	m.Lock()
 	defer m.Unlock()
 
+	key := workload.Key(w)
+
+	if !m.secondPassQueue.prequeued.Has(key) {
```
Comment (mimowo) [inline pkg/cache/queue/manager.go]: This does not seem necessary since we already check for the "prequeued" state inside secondpassqueue. So, this is generally better place as under locking.

What we might be missing it to clear `wInfo.SecondPassIteration` if we don't queue. Do we have a test case for this scenario?

File: pkg/cache/queue/manager.go [hunk 5]
```diff
@@ -833,6 +839,13 @@ func (m *Manager) queueSecondPass(ctx context.Context, w *kueue.Workload, iterat
...
+		m.secondPassQueue.deleteByKey(key)
+		return
+	}
```
Comment (mimowo) [inline pkg/cache/queue/manager.go]: Could you explain why this is for, and which testcase shows it is useful? Also, I think we should update `wInfo.SecondPassIteration = 0` in that case so that we start fresh if it hits second pass again.

Comment (mimowo) [reply pkg/cache/queue/manager.go]: Oh sorry for misleading you maybe, I think this new code:

```
		wInfo := workload.NewInfo(w, m.workloadInfoOptions...)
		wInfo.SecondPassIteration = 0
```
does not seem relevant, because the wInfo would be GCed quickly.


Maybe to clarify I was thinking this entire block can be removed, because `prequeued` is arealdy checked inside `if m.secondPassQueue.queue(wInfo) {`

Comment (skools-here) [reply pkg/cache/queue/manager.go]: Thanks for the clarification! That makes sense  since `queue()` already checks `prequeued`, the extra guard here is redundant. I’ll simplify `queueSecondPass` accordingly and rely on the queue logic, keeping the tests to validate the cleanup behavior.

**Comment by mimowo** [comment]
/release-note-edit
```release-note
TAS: Fixed an issue where workloads could remain in the second-pass scheduling queue (used for integration
or TAS with ProvisioningRequests, and for TAS Node Hot Swap) even if they no longer require to be in the queue.
```

**Comment by mimowo** [comment]
Thank you 👍 
/lgtm
/approve
/cherrypick release-0.15
/cherrypick release-0.14

**Comment by mimowo** [comment]
@skools-here could you please prepare cherrypicks manually? Usually the ./hack/cherry_pick_pull.sh script is handy, but you can also do it completely manually

**Comment by mimowo** [comment]
Since we are approaching the release let me try to take care of the CPs here.

File: pkg/cache/queue/manager_test.go [hunk 6]
```diff
@@ -1395,22 +1396,26 @@ func TestQueueSecondPassIfNeeded(t *testing.T) {
...
 			Name:  "prov-check",
 			State: kueue.CheckStateReady,
 		})
+
 	baseWorkloadNotNeedingSecondPass := baseWorkloadBuilder.Clone()
 
 	cases := map[string]struct {
 		workloads []*kueue.Workload
-		deleted   sets.Set[workload.Reference]
+		update    func(*kueue.Workload)
```
Comment (tenzen-y) [inline pkg/cache/queue/manager_test.go:1411]:
```suggestion
		updateWorkload    *kueue.Workload
```

Such dynamic modification while UT should be avoided as much as possible.
Those anonymous functions bring us surprises, maintenance PoV in the long-running future.

File: pkg/cache/queue/manager_test.go [hunk 7]
```diff
@@ -1420,43 +1425,57 @@ func TestQueueSecondPassIfNeeded(t *testing.T) {
...
 				manager.QueueSecondPassIfNeeded(ctx, wl, 0)
 			}
-			for _, wl := range tc.deleted.UnsortedList() {
-				manager.secondPassQueue.deleteByKey(wl)
+
+			if tc.update != nil {
+				wl := tc.workloads[0]
+				tc.update(wl)
+				manager.QueueSecondPassIfNeeded(ctx, wl, 1)
 			}
```
Comment (tenzen-y) [inline pkg/cache/queue/manager_test.go:1470]:
```suggestion
			if tc.updateWorkload != nil {
				manager.QueueSecondPassIfNeeded(ctx, tc.updateWorkload, 1)
			}
```

File: pkg/cache/queue/manager.go (hunk 2 above)
Comment (tenzen-y) [inline pkg/cache/queue/manager.go:818]:
```suggestion
	log := ctrl.LoggerFrom(ctx)
	wlKey := workload.Key(w)
```

`wlKey` is the same during this function.

File: pkg/cache/queue/manager.go [hunk 8]
```diff
@@ -815,16 +815,22 @@ func (m *Manager) DeleteSecondPassWithoutLock(wl *kueue.Workload) {
 // QueueSecondPassIfNeeded queues for the second pass of scheduling with exponential
 // delay.
 func (m *Manager) QueueSecondPassIfNeeded(ctx context.Context, w *kueue.Workload, iteration int) bool {
+	log := ctrl.LoggerFrom(ctx)
 	if workload.NeedsSecondPass(w) {
 		iteration++
 		delay := m.secondPassQueue.nextDelay(iteration)
-		log := ctrl.LoggerFrom(ctx)
 		log.V(3).Info("Workload pre-queued for second pass (with backoff)", "workload", workload.Key(w), "delay", delay)
```
Comment (tenzen-y) [inline pkg/cache/queue/manager.go:822]:
```suggestion
		log.V(3).Info("Workload pre-queued for second pass (with backoff)", "workload", wlKey, "delay", delay)
```

File: pkg/cache/queue/manager.go [hunk 9]
```diff
@@ -815,16 +815,22 @@ func (m *Manager) DeleteSecondPassWithoutLock(wl *kueue.Workload) {
...
 		m.secondPassQueue.prequeue(w)
 		m.clock.AfterFunc(delay, func() {
 			m.queueSecondPass(ctx, w, iteration)
 		})
 		return true
+	} else if iteration > 0 {
+		// Remove the workload from the second-pass queue only after at least one
+		// retry iteration, to avoid canceling the initial backoff window.
+		// See #8357.
+		log.V(3).Info("Workload removed from second pass queue", "workload", workload.Key(w))
```
Comment (tenzen-y) [inline pkg/cache/queue/manager.go:832]:
```suggestion
		log.V(3).Info("Workload removed from second pass queue", "workload", wlKey)
```

File: pkg/cache/queue/manager.go [hunk 10]
```diff
@@ -815,16 +815,22 @@ func (m *Manager) DeleteSecondPassWithoutLock(wl *kueue.Workload) {
...
 		log.V(3).Info("Workload pre-queued for second pass (with backoff)", "workload", workload.Key(w), "delay", delay)
 		m.secondPassQueue.prequeue(w)
 		m.clock.AfterFunc(delay, func() {
 			m.queueSecondPass(ctx, w, iteration)
 		})
 		return true
+	} else if iteration > 0 {
+		// Remove the workload from the second-pass queue only after at least one
+		// retry iteration, to avoid canceling the initial backoff window.
+		// See #8357.
```
Comment (tenzen-y) [inline pkg/cache/queue/manager.go:831]:
```suggestion
		// See https://github.com/kubernetes-sigs/kueue/issues/8357.
```

Could you use a link for visibility?

**Comment by skools-here** [comment]
@tenzen-y thanks for the review I am working on your suggestions.

**Comment by mimowo** [comment]
Thank you @skools-here for taking those 👍

File: pkg/cache/queue/manager_test.go (hunk 6 above)
Comment (mimowo) [reply pkg/cache/queue/manager_test.go:1411]: +1, current implementation sets status.admission=nil to make the workload not needing the second pass, but I'm not sure we have a helper for that. We can alternatively Evict the workload for example (eg. using EvictedAt), which would also be more realistic case, because workload is first evicted, and only then the admission is removed.

Comment (mimowo) [reply pkg/cache/queue/manager_test.go:1411]: I opened the potentially related issue https://github.com/kubernetes-sigs/kueue/issues/8633

**Comment by mimowo** [comment]
Ok, I opened https://github.com/kubernetes-sigs/kueue/issues/8682 to keep track of that
