### PR TITLE
[MultiKueue] Introduce Admission Check Validation feature gate

### LINKED ISSUE #3094: [MultiKueue] AdmissionCheck conditions are confusing
**What happened**:

I got feedback from a user running into an issue with MultiKueue, and getting distracted by confusing AdmissionCheck conditions, and wasting time during investigations.

```yaml
  - lastTransitionTime: "2024-09-07T10:27:28Z"
      message: only one multikueue managed admission check can be used in one ClusterQueue
      observedGeneration: 1
      reason: MultiKueue
      status: "True"
      type: SingleInstanceInClusterQueue
    - lastTransitionTime: "2024-09-07T10:27:28Z"
      message: admission check cannot be applied at ResourceFlavor level
      observedGeneration: 1
      reason: MultiKueue
      status: "True"
      type: FlavorIndependent
```

**What you expected to happen**:

No user-facing conditions used by MultiKueue for its inner-workings.

**How to reproduce it (as minimally and precisely as possible)**:

Setup MultiKueue according to https://kueue.sigs.k8s.io/docs/tasks/manage/setup_multikueue/. 

**Anything else we need to know?**:

The mechanism was introduced as part of [Single instance admission check.](https://github.com/kubernetes-sigs/kueue/pull/1635#top)(https://github.com/kubernetes-sigs/kueue/pull/1635), but the solution based on status conditions was contested and deferred to be revisted on future releases https://github.com/kubernetes-sigs/kueue/pull/1635#discussion_r1466659290. 

I propose to:
- drop the conditions, and hard-code dependencies between built-in Admission checks, as suggested in the [comment](https://github.com/kubernetes-sigs/kueue/pull/1635#discussion_r1466659290). This approach will also let us easily implement https://github.com/kubernetes-sigs/kueue/issues/2021
- move the user-facing configuration as part of the support for external Admission Checks (I can open a follow up issue for this)

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
`SingleInstanceInClusterQueue` and `FlavorIndependent` are confusing to the multi-cluster users.
We need to wrap them with feature gate, but preserve the logic for MultiKueue Admission Checks constraints without those status conditions.

#### Which issue(s) this PR fixes:

Fixes #3094 

#### Does this PR introduce a user-facing change?

```release-note
Deprecated SingleInstanceInClusterQueue and FlavorIndependent status conditions.

ACTION REQUIRED: the Admission check status conditions “FlavorIndependent” and “SingleInstanceInClusterQueue” are no longer supported by default.
If you were using any of these conditions for your external AdmissionCheck you need to enable the `AdmissionCheckValidationRules` feature gate. 
For the future releases you will need to provide validation by an external controller.
```

### CODE REVIEW

File: pkg/features/kube_features.go [hunk 1]
```diff
@@ -109,6 +109,13 @@ const (
 	// Enable Topology Aware Scheduling allowing to optimize placement of Pods
 	// to put them on closely located nodes (e.g. within the same rack or block).
 	TopologyAwareScheduling featuregate.Feature = "TopologyAwareScheduling"
+
+	// owner: @mszadkow
+	// alpha: v0.9
+	// Deprecated: v0.10
```
Comment (mimowo) [inline pkg/features/kube_features.go:115]:
```suggestion
	// alpha: v0.9
	// deprecated: v0.9
```

File: pkg/cache/cache.go [hunk 2]
```diff
@@ -240,11 +241,19 @@ func (c *Cache) DeleteResourceFlavor(rf *kueue.ResourceFlavor) sets.Set[string]
 func (c *Cache) AddOrUpdateAdmissionCheck(ac *kueue.AdmissionCheck) sets.Set[string] {
 	c.Lock()
 	defer c.Unlock()
+
+	// TBD: This might not be needed, but we could keep it for readability
+	// because SingleInstanceInClusterQueue and FlavorIndependent will be false if AdmissionCheckValidationRules is off
+	singleInstanceInClusterQueue, flavorIndependent := false, false
+	if features.Enabled(features.AdmissionCheckValidationRules) {
```
Comment (mimowo) [inline pkg/cache/cache.go:248]: Gating this code makes sense, but I think for reasability we can do:
```
newAC :=  AdmissionCheck{
  Active
  Controller 
  // by default SingleInstanceInClusterQueue and FlavorIndependent to false
}
if features.Enabled(features.AdmissionCheckValidationRules) {
  newAC. SingleInstanceInClusterQueue =apimeta.IsStatusConditionTrue(ac.Status.Conditions, kueue.AdmissionChecksSingleInstanceInClusterQueue)
  newAC.FlavorIndependent = apimeta.IsStatusConditionTrue(ac.Status.Conditions, kueue.FlavorIndependentAdmissionCheck)
}
c.admissionChecks[ac.Name] = newAC
```

File: pkg/cache/clusterqueue.go [hunk 3]
```diff
@@ -265,16 +266,28 @@ func (c *clusterQueue) inactiveReason() (string, string) {
 			reasons = append(reasons, kueue.ClusterQueueActiveReasonAdmissionCheckInactive)
 			messages = append(messages, fmt.Sprintf("references inactive AdmissionCheck(s): %v", c.inactiveAdmissionChecks))
 		}
-		if len(c.multipleSingleInstanceControllersChecks) > 0 {
-			reasons = append(reasons, kueue.ClusterQueueActiveReasonMultipleSingleInstanceControllerAdmissionChecks)
-			for _, controller := range utilmaps.SortedKeys(c.multipleSingleInstanceControllersChecks) {
-				messages = append(messages, fmt.Sprintf("only one AdmissionCheck of %v can be referenced for controller %q", c.multipleSingleInstanceControllersChecks[controller], controller))
+		if features.Enabled(features.AdmissionCheckValidationRules) {
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:269]: IIUC we don't need any diff here if we used a dedicated cache field.
Then we can also easier drop the code in 0.10. For the hard-coded validation we can use 
`multipleMultiKueueChecks` and `perFlavorMultiKueueChecks`

File: pkg/cache/clusterqueue.go [hunk 4]
```diff
@@ -333,11 +346,22 @@ func (c *clusterQueue) updateWithAdmissionChecks(checks map[string]AdmissionChec
 				inactive = append(inactive, acName)
 			}
 			checksPerController[ac.Controller] = append(checksPerController[ac.Controller], acName)
-			if ac.SingleInstanceInClusterQueue {
+
+			if features.Enabled(features.AdmissionCheckValidationRules) {
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:350]: Similarly here, avoid the diff by using dedicated cache fields for the new checks

File: pkg/cache/clusterqueue_test.go [hunk 5]
```diff
@@ -771,10 +775,52 @@ func TestClusterQueueUpdateWithAdmissionCheck(t *testing.T) {
...
+				},
+				"check3": {
+					Active:                       true,
+					Controller:                   "controller2",
+					SingleInstanceInClusterQueue: true,
+				},
+			},
+			wantStatus:  pending,
+			wantReason:  "MultipleSingleInstanceControllerAdmissionChecks",
+			wantMessage: "Can't admit new workloads: Cannot use multiple MultiKueue AdmissionChecks on the same ClusterQueue.",
```
Comment (mimowo) [inline pkg/cache/clusterqueue_test.go:800]: When the feature is disabled set reason as MultipleMultiKueueAdmissionChecks

File: pkg/cache/clusterqueue_test.go [hunk 6]
```diff
@@ -771,10 +775,52 @@ func TestClusterQueueUpdateWithAdmissionCheck(t *testing.T) {
...
+			admissionChecks: map[string]AdmissionCheck{
+				"check1": {
+					Active:            true,
+					Controller:        "controller1",
+					FlavorIndependent: true,
+				},
+			},
+			wantStatus:  pending,
+			wantReason:  "FlavorIndependentAdmissionCheckAppliedPerFlavor",
+			wantMessage: "Can't admit new workloads: MultiKueue AdmissionCheck cannot be specified per flavor.",
```
Comment (mimowo) [inline pkg/cache/clusterqueue_test.go:815]: When the gate is disabled use reason `MutliKueueAdmissionCheckAppliedPerFlavor`

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 7]
```diff
@@ -758,6 +758,91 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Ordered, ginkgo.Contin
...
+
+			gomega.Eventually(func() []metav1.Condition {
+				var updatedCq kueue.ClusterQueue
+				gomega.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(cq), &updatedCq)).To(gomega.Succeed())
+				return updatedCq.Status.Conditions
+			}, util.Timeout, util.Interval).Should(gomega.BeComparableTo([]metav1.Condition{
+				{
+					Type:    kueue.ClusterQueueActive,
+					Status:  metav1.ConditionFalse,
+					Reason:  "MultipleSingleInstanceControllerAdmissionChecks",
```
Comment (mimowo) [inline test/integration/controller/core/clusterqueue_controller_test.go:787]: Make this specific as in the other comment.

**Review by mimowo — COMMENTED** [review]
Overall this looks good.

I'm leaning to use dedicated fields in the cache for the checks so that there is a clear separation of the new and old mechanism. It will make it easier to drop the old mechanism in 0.10. Maybe it would also give us more control over the reasons, it will be better to have dedicated reasons.

File: test/integration/multikueue/multikueue_test.go [hunk 8]
```diff
@@ -187,6 +187,10 @@ var _ = ginkgo.Describe("Multikueue", ginkgo.Ordered, ginkgo.ContinueOnFailure,
 		gomega.Expect(worker2TestCluster.client.Create(worker2TestCluster.ctx, worker2Cq)).Should(gomega.Succeed())
 		worker2Lq = utiltesting.MakeLocalQueue(worker2Cq.Name, worker2Ns.Name).ClusterQueue(worker2Cq.Name).Obj()
 		gomega.Expect(worker2TestCluster.client.Create(worker2TestCluster.ctx, worker2Lq)).Should(gomega.Succeed())
+
+		ginkgo.By("Disabling AdmissionCheckValidationRules feature", func() {
+			gomega.Expect(features.SetEnable(features.AdmissionCheckValidationRules, false)).To(gomega.Succeed())
+		})
```
Comment (mbobrovskyi) [inline test/integration/multikueue/multikueue_test.go:193]: I think it should be disabled by default?

File: test/integration/multikueue/multikueue_test.go [hunk 9]
```diff
@@ -348,6 +340,9 @@ var _ = ginkgo.Describe("Multikueue", ginkgo.Ordered, ginkgo.ContinueOnFailure,
 	})
 
 	ginkgo.It("Should properly manage the active condition of AdmissionChecks and MultiKueueClusters, kubeconfig provided by file", func() {
+		ginkgo.By("Enabling AdmissionCheckValidationRules feature", func() {
+			gomega.Expect(features.SetEnable(features.AdmissionCheckValidationRules, true)).To(gomega.Succeed())
+		})
```
Comment (mbobrovskyi) [inline test/integration/multikueue/multikueue_test.go:345]:
```suggestion
		ginkgo.By("Enabling AdmissionCheckValidationRules feature", func() {
			features.SetFeatureGateDuringTest(ginkgo.GinkgoTB(), features.ConfigurableResourceTransformations, true)
		})
```

File: site/content/en/docs/installation/_index.md [hunk 10]
```diff
@@ -255,6 +255,7 @@ The currently supported features are:
 | `TopologyAwareScheduling`             | `false` | Alpha      | 0.9   |       |
 | `ConfigurableResourceTransformations` | `false` | Alpha      | 0.9   |       |
 | `WorkloadResourceRequestsSummary`     | `false` | Alpha      | 0.9   |       |
+| `AdmissionCheckValidationRules`       | `false` | Alpha      | 0.9   | 0.9   |
```
Comment (mbobrovskyi) [inline site/content/en/docs/installation/_index.md:258]:
```suggestion
| `AdmissionCheckValidationRules`       | `false` | Deprecated | 0.9   | 0.9   |
```

File: test/integration/multikueue/multikueue_test.go (hunk 8 above)
Comment (mszadkow) [reply test/integration/multikueue/multikueue_test.go:193]: True, but I think it persists between tests, so I would rather keep it disabled before each test

Comment (mbobrovskyi) [reply test/integration/multikueue/multikueue_test.go:193]: Use `features.SetFeatureGateDuringTest` it should revert after test.

File: pkg/cache/clusterqueue.go [hunk 11]
```diff
@@ -77,9 +77,12 @@ type clusterQueue struct {
 	inactiveAdmissionChecks                         []string
 	multipleSingleInstanceControllersChecks         map[string][]string // key = controllerName
 	flavorIndependentAdmissionCheckAppliedPerFlavor []string
-	admittedWorkloadsCount                          int
-	isStopped                                       bool
-	workloadInfoOptions                             []workload.InfoOption
+	// TBD: Are we interested in knowing those AC names?
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:80]: If it does not add too much complexity, then it is better to know them

File: pkg/cache/clusterqueue.go [hunk 12]
```diff
@@ -230,7 +233,9 @@ func (c *clusterQueue) updateQueueStatus() {
 		len(c.missingAdmissionChecks) > 0 ||
 		len(c.inactiveAdmissionChecks) > 0 ||
 		len(c.multipleSingleInstanceControllersChecks) > 0 ||
-		len(c.flavorIndependentAdmissionCheckAppliedPerFlavor) > 0 {
+		len(c.flavorIndependentAdmissionCheckAppliedPerFlavor) > 0 ||
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:236]: was this check for `flavorIndependentAdmissionCheckAppliedPerFlavor` missing before?

File: pkg/cache/clusterqueue.go [hunk 13]
```diff
@@ -265,18 +270,30 @@ func (c *clusterQueue) inactiveReason() (string, string) {
 			reasons = append(reasons, kueue.ClusterQueueActiveReasonAdmissionCheckInactive)
 			messages = append(messages, fmt.Sprintf("references inactive AdmissionCheck(s): %v", c.inactiveAdmissionChecks))
 		}
+
+		// TBD: This shouldn't be feature gated, as the messages and reasons are valid
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:274]: I guess we don't need to feature gate it, because if the gate is disabled thee value `multipleSingleInstanceControllersChecks` would be empty anyway. Right? If this is the case, maybe just comment: "This doesn't need to be gated behind <gate name>, because it is empty when the gate is disabled"

File: pkg/cache/clusterqueue.go [hunk 14]
```diff
@@ -265,18 +270,30 @@ func (c *clusterQueue) inactiveReason() (string, string) {
...
 		if len(c.multipleSingleInstanceControllersChecks) > 0 {
 			reasons = append(reasons, kueue.ClusterQueueActiveReasonMultipleSingleInstanceControllerAdmissionChecks)
 			for _, controller := range utilmaps.SortedKeys(c.multipleSingleInstanceControllersChecks) {
 				messages = append(messages, fmt.Sprintf("only one AdmissionCheck of %v can be referenced for controller %q", c.multipleSingleInstanceControllersChecks[controller], controller))
 			}
 		}
-
+		// TBD: This shouldn't be feature gated, as the messages and reasons are valid
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:281]: as above

File: pkg/cache/clusterqueue.go [hunk 15]
```diff
@@ -333,19 +352,33 @@ func (c *clusterQueue) updateWithAdmissionChecks(checks map[string]AdmissionChec
 				inactive = append(inactive, acName)
 			}
 			checksPerController[ac.Controller] = append(checksPerController[ac.Controller], acName)
+
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:355]: nit, revert formatting changes

File: pkg/cache/clusterqueue_test.go [hunk 16]
```diff
@@ -771,10 +797,69 @@ func TestClusterQueueUpdateWithAdmissionCheck(t *testing.T) {
...
+			cqStatus: pending,
+			admissionChecks: map[string]AdmissionCheck{
+				"check1": {
+					Active:            true,
+					Controller:        kueue.MultiKueueControllerName,
+					FlavorIndependent: true,
+				},
+			},
+			wantStatus:  pending,
+			wantReason:  "FlavorIndependentAdmissionCheckAppliedPerFlavor",
```
Comment (mimowo) [inline pkg/cache/clusterqueue_test.go:851]: IIUC this reason should be also specific for MultiKueue as the feature gate is disbaled

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 17]
```diff
@@ -758,6 +761,100 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Ordered, ginkgo.Contin
 				},
 			}, util.IgnoreConditionTimestampsAndObservedGeneration))
 		})
+
+		ginkgo.It("Should prevent workload admission due to multikueue contraints", func() {
```
Comment (mimowo) [inline test/integration/controller/core/clusterqueue_controller_test.go:765]: We want to have also an integration test when the feature gate is not enabled, and we see the reasons are specific for MultiKueue.

File: pkg/cache/clusterqueue.go (hunk 12 above)
Comment (mszadkow) [reply pkg/cache/clusterqueue.go:236]: no, it was there what changed is just `||`

Comment (mimowo) [reply pkg/cache/clusterqueue.go:236]: ah, I missed that

File: pkg/cache/clusterqueue_test.go [hunk 18]
```diff
@@ -771,10 +797,69 @@ func TestClusterQueueUpdateWithAdmissionCheck(t *testing.T) {
...
+		},
 	}
 
 	for _, tc := range testcases {
 		t.Run(tc.name, func(t *testing.T) {
+			if tc.acValidationRulesEnabled {
+				features.SetFeatureGateDuringTest(t, features.AdmissionCheckValidationRules, true)
+			} else {
+				features.SetFeatureGateDuringTest(t, features.AdmissionCheckValidationRules, false)
+			}
```
Comment (mbobrovskyi) [inline pkg/cache/clusterqueue_test.go:862]:
```suggestion
			}
```

File: pkg/cache/clusterqueue_test.go [hunk 19]
```diff
@@ -672,12 +674,35 @@ func TestClusterQueueUpdateWithAdmissionCheck(t *testing.T) {
 					SingleInstanceInClusterQueue: true,
 				},
 			},
+			wantStatus:               pending,
+			wantReason:               "MultipleSingleInstanceControllerAdmissionChecks",
+			wantMessage:              `Can't admit new workloads: only one AdmissionCheck of [check2 check3] can be referenced for controller "controller2".`,
+			acValidationRulesEnabled: true,
+		},
+		{
+			name:     "Active clusterQueue with an MultiKueue AC strategy updated with duplicate single instance AC Controller - MultiKueue AdmissionCheckValidationRules enabled",
```
Comment (mbobrovskyi) [inline pkg/cache/clusterqueue_test.go:683]:
```suggestion
			name:     "Active clusterQueue with an MultiKueue AC strategy updated with duplicate single instance AC Controller - MultiKueue AdmissionCheckValidationRules disabled",
```

File: pkg/cache/clusterqueue.go [hunk 20]
```diff
@@ -333,19 +352,33 @@ func (c *clusterQueue) updateWithAdmissionChecks(checks map[string]AdmissionChec
...
 		}
 	}
 
 	// sort the lists since c.AdmissionChecks is a map
 	slices.Sort(missing)
 	slices.Sort(inactive)
 	slices.Sort(flavorIndependentCheckOnFlavors)
+	slices.Sort(perFlavorMultiKueueChecks)
+	multipleMultiKueueControllersList := multipleMultiKueueControllers.UnsortedList()
+	slices.Sort(multipleMultiKueueControllersList)
```
Comment (mbobrovskyi) [inline pkg/cache/clusterqueue.go:381]:
```suggestion
	multipleMultiKueueControllersList := sets.List(multipleMultiKueueControllers)
```

File: pkg/cache/clusterqueue_test.go (hunk 16 above)
Comment (mszadkow) [reply pkg/cache/clusterqueue_test.go:851]: problematic, bc who this stuff is designed, first reason to appear is actually returned
```go
		return reasons[0], api.TruncateConditionMessage(strings.Join([]string{"Can't admit new workloads: ", strings.Join(messages, ", "), "."}, ""))
```

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 17 above)
Comment (mszadkow) [reply test/integration/controller/core/clusterqueue_controller_test.go:765]: this is actually the test without the feature gate,
we don't check status there just messages

File: pkg/cache/clusterqueue_test.go (hunk 16 above)
Comment (mimowo) [reply pkg/cache/clusterqueue_test.go:851]: I would think we don't need to generate this reason then, only the dedicated one

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 17 above)
Comment (mimowo) [reply test/integration/controller/core/clusterqueue_controller_test.go:765]: I would say the reason is more important than the message.

File: pkg/cache/clusterqueue_test.go (hunk 16 above)
Comment (mszadkow) [reply pkg/cache/clusterqueue_test.go:851]: I will put the new multikueue reason before those old
but if we want to change the overall approach it should be another PR

File: pkg/cache/clusterqueue.go [hunk 21]
```diff
@@ -265,13 +271,25 @@ func (c *clusterQueue) inactiveReason() (string, string) {
 			reasons = append(reasons, kueue.ClusterQueueActiveReasonAdmissionCheckInactive)
 			messages = append(messages, fmt.Sprintf("references inactive AdmissionCheck(s): %v", c.inactiveAdmissionChecks))
 		}
+
+		if len(c.multipleMultiKueueAdmissionChecks) > 1 {
+			reasons = append(reasons, kueue.ClusterQueueActiveReasonMultipleMultiKueueAdmissionChecks)
+			messages = append(messages, "Cannot use multiple MultiKueue AdmissionChecks on the same ClusterQueue")
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:277]:
```suggestion
			messages = append(messages, "Cannot use multiple MultiKueue AdmissionChecks on the same ClusterQueue, found: %v", strings.Join(multipleMultiKueueAdmissionChecks, ","))
```

File: pkg/cache/clusterqueue.go [hunk 22]
```diff
@@ -265,13 +271,25 @@ func (c *clusterQueue) inactiveReason() (string, string) {
...
+		}
+
+		if len(c.perFlavorMultiKueueAdmissionChecks) > 0 {
+			reasons = append(reasons, kueue.ClusterQueueActiveReasonMutliKueueAdmissionCheckAppliedPerFlavor)
+			messages = append(messages, "MultiKueue AdmissionCheck cannot be specified per flavor")
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:282]:
```suggestion
			messages = append(messages, "Cannot specify MultiKueue AdmissionCheck per flavor, found: %s", strings.Join(perFlavorMultiKueueAdmissionChecks, ",") )
```
or along the lines

File: pkg/cache/clusterqueue.go [hunk 23]
```diff
@@ -339,13 +359,25 @@ func (c *clusterQueue) updateWithAdmissionChecks(checks map[string]AdmissionChec
 			if ac.FlavorIndependent && flavors.Len() != 0 {
 				flavorIndependentCheckOnFlavors = append(flavorIndependentCheckOnFlavors, acName)
 			}
+
+			if ac.Controller == kueue.MultiKueueControllerName {
+				// MultiKueue Admission Checks have extra constraints
+				// disallow to use multiple MultiKueue AdmissionChecks on the same ClusterQueue
+				// MultiKueue AdmissionCheck cannot be specified per flavor
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:366]:
```suggestion
				// MultiKueue Admission Checks has extra constraints:
				// - cannot use multiple MultiKueue AdmissionChecks on the same ClusterQueue
				// - cannot use specify MultiKueue AdmissionCheck per flavor
```
nit

**Review by mimowo — COMMENTED** [review]
LGTM overall, left some minor remarks
cc @mbobrovskyi as another pair of eyes

File: pkg/features/kube_features.go [hunk 24]
```diff
@@ -159,6 +166,7 @@ var defaultFeatureGates = map[featuregate.Feature]featuregate.FeatureSpec{
 	ConfigurableResourceTransformations: {Default: false, PreRelease: featuregate.Alpha},
 	WorkloadResourceRequestsSummary:     {Default: false, PreRelease: featuregate.Alpha},
 	ExposeFlavorsInLocalQueue:           {Default: true, PreRelease: featuregate.Beta},
+	AdmissionCheckValidationRules:       {Default: false, PreRelease: featuregate.Alpha},
```
Comment (mbobrovskyi) [inline pkg/features/kube_features.go:169]:
```suggestion
	AdmissionCheckValidationRules:       {Default: false, PreRelease: featuregate.Deprecated},
```

File: pkg/controller/admissionchecks/multikueue/admissioncheck_test.go [hunk 25]
```diff
@@ -66,6 +68,7 @@ func TestReconcile(t *testing.T) {
 					}).
 					Obj(),
 			},
+			acValidationRulesEnabled: true,
```
[the remark this answers is not in the document]
Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/admissioncheck_test.go:71]: we can reverse this sure

File: pkg/cache/clusterqueue_test.go [hunk 26]
```diff
@@ -672,12 +697,35 @@ func TestClusterQueueUpdateWithAdmissionCheck(t *testing.T) {
...
+			},
 			wantStatus:  pending,
-			wantReason:  "MultipleSingleInstanceControllerAdmissionChecks",
-			wantMessage: `Can't admit new workloads: only one AdmissionCheck of [check2 check3] can be referenced for controller "controller2".`,
+			wantReason:  kueue.ClusterQueueActiveReasonMultipleMultiKueueAdmissionChecks,
+			wantMessage: `Can't admit new workloads: Cannot use multiple MultiKueue AdmissionChecks on the same ClusterQueue, found: check1,check3.`,
 		},
 		{
-			name:     "Active clusterQueue with a FlavorIndependent AC applied per ResourceFlavor",
+			name:     "Active clusterQueue with a FlavorIndependent AC applied per ResourceFlavor - AdmissionCheckValidationRules enabled",
```
Comment (mbobrovskyi) [inline pkg/cache/clusterqueue_test.go:728]: Shouldn't it be disabled?

Comment (mbobrovskyi) [inline pkg/cache/clusterqueue_test.go:728]: The same question.

**Review by mbobrovskyi — COMMENTED** [review]
/lgtm

Thanks!

**Review by mimowo — COMMENTED** [review]
/approve
Thanks!
