### PR TITLE
Fix provisioning request test

### LINKED ISSUE #1484: Flaky: Provisioning when A workload is using a provision admission check Should let a running workload to continue after the provisioning request deleted
**What happened**:

Failed "[It] Provisioning when A workload is using a provision admission check Should let a running workload to continue after the provisioning request deleted"

**What you expected to happen**:

No error wouldn't happen.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1468/pull-kueue-test-integration-main/1736772290600767488

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by B1F030**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix integration test for [test/integration/controller/admissionchecks/provisioning/provisioning_test.go](https://github.com/kubernetes-sigs/kueue/blob/main/test/integration/controller/admissionchecks/provisioning/provisioning_test.go)
#### Which issue(s) this PR fixes:

Fixes #1484

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by B1F030** [comment]
cc @kerthcet

**Comment by B1F030** [comment]
cc @tenzen-y 
It should work now.

**Comment by tenzen-y** [comment]
@B1F030 Please squash all commits into one.

**Comment by B1F030** [comment]
> @B1F030 Please squash all commits into one.

@tenzen-y  Done.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 1]
```diff
@@ -592,15 +597,32 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
 			})
 
 			ginkgo.By("Checking the admission check is ready", func() {
+				updatedWl := &kueue.Workload{}
```
Comment (mimowo) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:600]: Should we add additional step "Check the workload is admitted"? If the workload isn't admitted, we will invoke 
`syncOwnedProvisionRequest` which may recreate the PR, and thus evict the workload. See https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/admissionchecks/provisioning/controller.go#L138-L151

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 2]
```diff
@@ -568,20 +569,24 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
 			})
 
 			ginkgo.By("Setting the provision request as Provisioned", func() {
+				createdRequest := &autoscaling.ProvisioningRequest{}
 				gomega.Eventually(func() error {
+					err := k8sClient.Get(ctx, provReqKey, createdRequest)
+					if err != nil {
+						return err
+					}
```
Comment (tenzen-y) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:589]: Can you use `gomega.Eventually(func(g gomega.Gomega) {`?

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 3]
```diff
@@ -592,15 +597,32 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+								provisioning.ConsumesAnnotationKey: provReqKey.Name,
+							},
+						},
+					}))
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
 			})
 
 			ginkgo.By("Deleting the provision request", func() {
+				createdRequest := &autoscaling.ProvisioningRequest{}
+				createdRequest.Name, createdRequest.Namespace = provReqKey.Name, provReqKey.Namespace
```
Comment (tenzen-y) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:625]: Instead of generating an object, should we get a PR object?

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 4]
```diff
@@ -614,10 +636,11 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
 				gomega.Eventually(func() error {
 					request := &autoscaling.ProvisioningRequest{}
 					return k8sClient.Get(ctx, provReqKey, request)
-				}, util.Timeout, util.Interval).Should(testing.BeNotFoundError())
+				}, util.Timeout, util.Interval).Should(gomega.BeNil())
```
Comment (tenzen-y) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:639]: Why do we need to use `BeNil()` instead of `BeNotFoundError`?

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 1 above)
Comment (tenzen-y) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:600]: SGTM

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 3 above)
Comment (alculquicondor) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:625]: This is better, as it avoids an API call. However, prefer using this style:
```
object := &Type{
  field: value
}
```

Comment (tenzen-y) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:625]: I'm ok with @alculquicondor recommendation way.

Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go]: Done.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 1 above)
Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:598]: Done.

**Comment by B1F030** [comment]
@tenzen-y @mimowo  Done. Thanks for review!

**Comment by tenzen-y** [comment]
If you face a flaky test, please open a tracking issue.

Opened: #1501

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 5]
```diff
@@ -568,39 +569,74 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
 			ginkgo.By("Setting the provision request as Provisioned", func() {
-				gomega.Eventually(func() error {
+				createdRequest := &autoscaling.ProvisioningRequest{}
+				gomega.Eventually(func(g gomega.Gomega) error {
+					g.Expect(k8sClient.Get(ctx, provReqKey, createdRequest)).To(gomega.Succeed())
 					apimeta.SetStatusCondition(&createdRequest.Status.Conditions, metav1.Condition{
 						Type:   autoscaling.Provisioned,
 						Status: metav1.ConditionTrue,
 						Reason: autoscaling.Provisioned,
 					})
```
Comment (tenzen-y) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:591]:
```suggestion
				gomega.Eventually(func(g gomega.Gomega) {
					g.Expect(k8sClient.Get(ctx, provReqKey, createdRequest)).To(gomega.Succeed())
					apimeta.SetStatusCondition(&createdRequest.Status.Conditions, metav1.Condition{
						Type:   autoscaling.Provisioned,
						Status: metav1.ConditionTrue,
						Reason: autoscaling.Provisioned,
					})
					g.Expect(k8sClient.Status().Update(ctx, createdRequest)).To(gomega.Succeed())
				}, util.Timeout, util.Interval).Should(gomega.Succeed())					
```

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 6]
```diff
@@ -568,39 +569,74 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+			ginkgo.By("Check the workload is admitted", func() {
+				updatedWl := &kueue.Workload{}
+				gomega.Eventually(func() error {
+					err := k8sClient.Get(ctx, wlKey, updatedWl)
+					if err != nil {
+						return err
+					}
+					util.ExpectWorkloadsToHaveQuotaReservation(ctx, k8sClient, string(updatedWl.Status.Admission.ClusterQueue), updatedWl)
+					return nil
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
```
Comment (tenzen-y) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:630]:
```suggestion
				gomega.Eventually(func(g gomega.Gomega) {
					g.Expect(k8sClient.Get(ctx, wlKey, updatedWl)).To(gomega.Succeed())
					util.ExpectWorkloadsToHaveQuotaReservation(ctx, k8sClient, string(updatedWl.Status.Admission.ClusterQueue), updatedWl)
				}, util.Timeout, util.Interval).Should(gomega.Succeed())
```

**Comment by B1F030** [comment]
> If you face a flaky test, please open a tracking issue.

OK, I thought that was because of github CI. Tests sometimes just fail, after retest, they turn out to be correct.
I will record it as an issue next time I meet this kind of situation.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 7]
```diff
@@ -568,39 +569,69 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+						},
+					}))
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Check the workload is admitted", func() {
+				updatedWl := &kueue.Workload{}
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, wlKey, updatedWl)).To(gomega.Succeed())
+					util.ExpectWorkloadsToHaveQuotaReservation(ctx, k8sClient, string(updatedWl.Status.Admission.ClusterQueue), updatedWl)
```
Comment (tenzen-y) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:624]: Should we use `ExpectWorkloadsToBeAdmitted` instead of `ExpectWorkloadsToHaveQuotaReservation`?

https://github.com/kubernetes-sigs/kueue/blob/395137afeaad94179db68043e5c74ab193f6beb1/test/util/util.go#L268

Since the provisioning controller verifies `Admission` status:

https://github.com/kubernetes-sigs/kueue/blob/395137afeaad94179db68043e5c74ab193f6beb1/pkg/controller/admissionchecks/provisioning/controller.go#L138-L142

https://github.com/kubernetes-sigs/kueue/blob/395137afeaad94179db68043e5c74ab193f6beb1/pkg/workload/workload.go#L433-L436

**Review by tenzen-y — COMMENTED** [review]
Otherwise lgtm.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 7 above)
Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:624]: Sounds resonable to me.

**Review by tenzen-y — COMMENTED** [review]
Thanks
/lgtm
/approve

**Comment by B1F030** [comment]
Flaky: Provisioning when A workload is using a provision admission check
similar to #1501

**Comment by tenzen-y** [comment]
There seems to be another flakiness.

/lgtm cancel

**Comment by B1F030** [comment]
```
  Not enough workloads are admitted
  Expected
      <int>: 0
  to equal
      <int>: 1
```

**Comment by B1F030** [comment]
Maybe we should still use `ExpectWorkloadsToHaveQuotaReservation` instead of `ExpectWorkloadsToBeAdmitted`?

**Comment by B1F030** [comment]
Cause we just set admission check and then set quota reservation to the workload, so `"Check the workload is admitted"` maybe confusing, it actually means `"Check the workload has quota reservation"`.

**Comment by mimowo** [comment]
I think the intention of the test is to simulate that the workload is `admitted`, not just `quota reserved`. This is important for the `workload.IsAdmitted(wl)` check as pointed out here: https://github.com/kubernetes-sigs/kueue/pull/1493#discussion_r1433590685. 

I see this is failing `Check the workload is admitted`. 

Now, I think the test is failing because there is no scheduler to transition the workload from `QuotaReservation` to `Admission`. So, we need to do this from test code, I think this is the function you are looking for: https://github.com/kubernetes-sigs/kueue/blob/395137afeaad94179db68043e5c74ab193f6beb1/test/util/util.go#L478-L489 - call it before `Check the workload is admitted`.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 7 above)
Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:624]: yes, I think we should use `ExpectWorkloadsToBeAdmitted` to meet the `IsAdmitted` check. 

As discussed https://github.com/kubernetes-sigs/kueue/pull/1493#issuecomment-1865853179, I suspect this is problematic because there is no scheduler in the integration test setup. Please consider calling `SyncAdmittedConditionForWorkloads`.

**Comment by tenzen-y** [comment]
> SyncAdmittedConditionForWorkloads

@mimowo Yes, that's right. Thank you for the clarifications.
@B1F030 The following job-controller test would be helpful:

https://github.com/kubernetes-sigs/kueue/blob/395137afeaad94179db68043e5c74ab193f6beb1/test/integration/controller/jobs/job/job_controller_test.go#L241-L253

**Comment by B1F030** [comment]
In that case, `"Checking the workload remains admitted"` need to be replaced by `ExpectWorkloadsToBeAdmitted`, right?

**Comment by mimowo** [comment]
> In that case, `"Checking the workload remains admitted"` need to be replaced by `ExpectWorkloadsToBeAdmitted`, right?

Correct.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 8]
```diff
@@ -597,10 +598,38 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+			ginkgo.By("Check the workload is admitted", func() {
+				util.SyncAdmittedConditionForWorkloads(ctx, k8sClient, updatedWl)
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, wlKey, updatedWl)).To(gomega.Succeed())
+					util.ExpectWorkloadsToBeAdmitted(ctx, k8sClient, updatedWl)
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
 			})
 
 			ginkgo.By("Deleting the provision request", func() {
+				createdRequest := &autoscaling.ProvisioningRequest{
```
Comment (mimowo) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:627]: Can we revert this change to minimize the diff - does not seem related?

Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:627]: Still we need to delete the provisioning request, if not set ObjectMeta, there will be an Error like:
```
      resource name may not be empty
      {
          s: "resource name may not be empty",
      }
```

Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:627]: Yes, we delete the provisioning request, I was just thinking about the place where we declare the variable.

Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:627]: This Error happens both on `k8sClient.Delete(ctx, createdRequest)` and `util.SyncAdmittedConditionForWorkloads(ctx, k8sClient, updatedWl)`.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 9]
```diff
@@ -618,13 +647,10 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
 
 			ginkgo.By("Checking the workload remains admitted", func() {
-				gomega.Eventually(func() error {
-					err := k8sClient.Get(ctx, wlKey, updatedWl)
-					if err != nil {
-						return err
-					}
-					util.ExpectWorkloadsToHaveQuotaReservation(ctx, k8sClient, string(updatedWl.Status.Admission.ClusterQueue), updatedWl)
-					return nil
+				util.SyncAdmittedConditionForWorkloads(ctx, k8sClient, updatedWl)
```
Comment (mimowo) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:650]: No need to call `SyncAdmittedConditionForWorkloads` here. This function is used to transition from `QuotaReservation` to `Admitted` by scheduler (which is not present in the setup). 
However, here we don't expect this to be needed. One thing which could happen is that the workload_controller evicts the workload, but scheduler should not be involved.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 8 above)
Comment (tenzen-y) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:627]: I'm ok with either way.

Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:627]: Don't you get the `createdRequest` populated at `k8sClient.Get(ctx, provReqKey, createdRequest)`?

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 9 above)
Comment (tenzen-y) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:650]: Correct.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 8 above)
Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:627]: I mean, this used to work in the test, right? You were deleting the provisioning request before this PR. I'm just thinking the way it was setup does not need to change,

Comment (tenzen-y) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:627]: @mimowo We have discussed about `k8sClient.Get(ctx, provReqKey, createdRequest)` in https://github.com/kubernetes-sigs/kueue/pull/1493#discussion_r1431289995, and then we decided not to call api-server .

Comment (tenzen-y) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go]: Oops. I misunderstood what you wanted to say.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 10]
```diff
@@ -568,26 +568,31 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
 			})
 
-			createdRequest := &autoscaling.ProvisioningRequest{}
 			provReqKey := types.NamespacedName{
 				Namespace: wlKey.Namespace,
 				Name:      provisioning.GetProvisioningRequestName(wlKey.Name, ac.Name, 1),
 			}
-
+			createdRequest := &autoscaling.ProvisioningRequest{
+				ObjectMeta: metav1.ObjectMeta{
```
Comment (mimowo) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:576]: Do we need to provide the `ObjectMeta` here? I think it will be populated on the `Get`?

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 8 above)
Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go]: I think the old method had the same number of requests actually, we still call the `Get` at the same places.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 11]
```diff
@@ -573,21 +573,21 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
 				Namespace: wlKey.Namespace,
 				Name:      provisioning.GetProvisioningRequestName(wlKey.Name, ac.Name, 1),
 			}
-
```
Comment (mimowo) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:576]: nit: revert

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 10 above)
Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go]: Sorry I'm still greenhand on this. Really appreciate for your patience.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 12]
```diff
@@ -597,6 +597,28 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+							Name: "ps2",
+							Annotations: map[string]string{
+								provisioning.ConsumesAnnotationKey: provReqKey.Name,
+							},
+						},
+					}))
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Check the workload is admitted", func() {
```
Comment (mimowo) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:618]: I think this is the actual fix, to make sure that the workload is admitted, so that we don't go beyond this check: https://github.com/kubernetes-sigs/kueue/blob/395137afeaad94179db68043e5c74ab193f6beb1/pkg/controller/admissionchecks/provisioning/controller.go#L138. 

Previously the test would be flaky, because going beyond the condition still required some extra work to evict the workload. Whereas the check in "Checking the workload remains admitted" would be fast. 

Could you please verify this by using `Consistently` instead of `Eventually` here on the main branch? I expect you would get the failure consistently. If you confirm the case, then please use `Consistently` on the fix and confirm that it is stable now. If we can confirm this, I'm ok with either `Eventually` or `Consistently` to be actually merged. The drawback of `Consistently` is that by default it takes 3s, but maybe we can use 1s.

**Review by mimowo — COMMENTED** [review]
LGTM, I would yet like to have confirm the understanding of why this was flaky with the experiment as in https://github.com/kubernetes-sigs/kueue/pull/1493#discussion_r1433796407

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go (hunk 12 above)
Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:618]: `Eventually` passed the test successfully. I will test `Consistently` next.

Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:618]: You can also run the tests locally. I would usually do 
1. mark the test I want to run in isolation with `ginkgo.FIt` instead of `ginkgo.It` (F for focus)
2. run integration tests selectively for the package: `INTEGRATION_TARGET=./test/integration/controller/admissionchecks/provisioning make test-integration`

Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:618]: Ok. let's use `Eventually`.

File: test/integration/controller/admissionchecks/provisioning/provisioning_test.go [hunk 13]
```diff
@@ -607,24 +630,15 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
-					Name:      provisioning.GetProvisioningRequestName(wlKey.Name, ac.Name, 1),
-				}
 				gomega.Eventually(func() error {
-					request := &autoscaling.ProvisioningRequest{}
-					return k8sClient.Get(ctx, provReqKey, request)
+					return k8sClient.Get(ctx, provReqKey, createdRequest)
 				}, util.Timeout, util.Interval).Should(testing.BeNotFoundError())
 			})
 
 			ginkgo.By("Checking the workload remains admitted", func() {
```
Comment (mimowo) [inline test/integration/controller/admissionchecks/provisioning/provisioning_test.go:638]: I just realized this suite does not run the workload controller. In that case we would really not expect eviction. So, I think what we should test here is:
1. that the admission check remains in the Ready state
2. the Provisioning request is not recreated

Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:638]: Should I remove `"Checking the workload remains admitted"`?

Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:638]: Good question. I think it is ok to drop it. Maybe just add a comment next to the new one: "Checking the workload admission check remains Ready" saying "We use this as a proxy check to verify that the workload remains admitted, because the test suite does not run the workload controller".

Comment (B1F030) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:638]: OK, Thank you!

Comment (mimowo) [reply test/integration/controller/admissionchecks/provisioning/provisioning_test.go:638]: Alternatively we could consider enabling the workload controller in a new dedicated suite, but this feels overkill for this PR.

**Comment by mimowo** [comment]
/lgtm 
Please squash the commits :)
/assign @tenzen-y

**Comment by B1F030** [comment]
Just to confirm in case:
```
ginkgo.By("Checking the admission check is ready", func() {
        gomega.Eventually(func(g gomega.Gomega) {
	        g.Expect(k8sClient.Get(ctx, wlKey, updatedWl)).To(gomega.Succeed())
	        state := workload.FindAdmissionCheck(updatedWl.Status.AdmissionChecks, ac.Name)
	        g.Expect(state).NotTo(gomega.BeNil())
	        g.Expect(state.State).To(gomega.Equal(kueue.CheckStateReady))
	        g.Expect(state.PodSetUpdates).To(gomega.BeComparableTo([]kueue.PodSetUpdate{
		        {
			        Name: "ps1",
			        Annotations: map[string]string{
				        provisioning.ConsumesAnnotationKey: provReqKey.Name,
			        },
		        },
		        {
			        Name: "ps2",
			        Annotations: map[string]string{
				        provisioning.ConsumesAnnotationKey: provReqKey.Name,
			        },
		        },
	        }))
        }, util.Timeout, util.Interval).Should(gomega.Succeed())
})

...

ginkgo.By("Checking the admission check remains ready", func() {
        gomega.Eventually(func(g gomega.Gomega) {
	        g.Expect(k8sClient.Get(ctx, wlKey, updatedWl)).To(gomega.Succeed())
	        state := workload.FindAdmissionCheck(updatedWl.Status.AdmissionChecks, ac.Name)
	        g.Expect(state).NotTo(gomega.BeNil())
	        g.Expect(state.State).To(gomega.Equal(kueue.CheckStateReady))
        }, util.Timeout, util.Interval).Should(gomega.Succeed())
})
```
Is it ok?

**Comment by mimowo** [comment]
> Is it ok?

lgtm

**Comment by B1F030** [comment]
> lgtm

OK, thanks!

**Review by tenzen-y — COMMENTED** [review]
Thanks! /approve
