### PR TITLE
Ensure admission configuration is set in the workloadReconciler and entry penalties are correctly updated

### LINKED ISSUE #10271: EntryPenalty and consumedResources are not being updated upon workload admission
**What happened**:
Admission fair sharing configuration is not being set on the WorkloadReconciler making the `updateAfsConsumedUsage` to be skipped, consequently the EntryPenalty and consumedResources are not being updated upon workload admission.

**What you expected to happen**:
EntryPenalty and consumedResources are updated upon workload admission.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by MaysaMacedo**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

- If the admission config is not set, the [updateAfsConsumedUsage](https://github.com/kubernetes-sigs/kueue/blob/91cbbe65fca0d99a13ffc3647b785e141e3d3add/pkg/controller/core/workload_controller.go#L1111) wouldn't have a chance to run in the WorkloadReconciler.
- Also, If the resources listed on the localqueue entry penalties have value as zero, the entry penalty can be cleaned up. This helps with ensuring no pending items are listed for the localqueue penalties and local queue reconciler do not think anymore that there are entry penalties to handle.

#### Which issue(s) this PR fixes:

Fixes #10271

#### Special notes for your reviewer:
Assisted with Claude

#### Does this PR introduce a user-facing change?

```release-note
AdmissionFairSharing: Fixed a bug in entry penalties by reducing them when workload is admitted and also clearing them up if all the resources on the admission entry penalty have value zero.
```

### CODE REVIEW

File: pkg/controller/core/workload_controller.go [hunk 1]
```diff
@@ -133,6 +133,13 @@ func WithPreemptionExpectations(value *expectations.Store) Option {
 	}
 }
 
+// WithAdmissionFairSharing sets the admission fair sharing configuration.
+func WithAdmissionFairSharing(value *config.AdmissionFairSharing) Option {
```
Comment (sohankunkerkar) [inline pkg/controller/core/workload_controller.go:137]: nit: `WithAdmissionFairSharingConfig` to be consistent with the localqueue_controller

File: pkg/controller/core/workload_controller.go [hunk 2]
```diff
@@ -1190,6 +1197,7 @@ func (r *WorkloadReconciler) updateAfsConsumedUsage(log logr.Logger, wl *kueue.W
 
 	r.queues.AfsConsumedResources.Set(lqKey, newConsumed, now)
 	r.queues.AfsEntryPenalties.Sub(lqKey, penalty)
+	log.V(3).Info("Entry penalty subtracted from localQueue", "localQueue", klog.KRef(wl.Namespace, string(wl.Spec.QueueName)), "penalty", penalty)
```
Comment (sohankunkerkar) [inline pkg/controller/core/workload_controller.go]:
```suggestion
log.V(3).Info("Entry penalty subtracted from localQueue", "localQueue", klog.KRef(wl.Namespace, string(wl.Spec.QueueName)), "penalty", penalty, "remaining", r.queues.AfsEntryPenalties.Peek(lqKey))                                                                                                                                                                                                        
```

File: test/integration/singlecluster/scheduler/fairsharing/suite_test.go [hunk 3]
```diff
@@ -73,7 +73,7 @@ var _ = ginkgo.ReportAfterSuite("Generate JUnit Report", func(report ginkgo.Repo
 	gomega.Expect(err).NotTo(gomega.HaveOccurred())
 })
 
-func managerAndSchedulerSetup(admissionFairSharing *config.AdmissionFairSharing) framework.ManagerSetup {
+func managerAndSchedulerSetup(admissionFairSharing *config.AdmissionFairSharing, queuesOut ...**qcache.Manager) framework.ManagerSetup {
```
Comment (sohankunkerkar) [inline test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: There's a simpler pattern already in the codebase for TAS that uses a package-level `qManager` var that gets set directly inside the setup closure (qManager = queues). It also avoids the double-pointer variadic and would be more consistent with existing tests.

File: pkg/controller/core/workload_controller.go (hunk 1 above)
Comment (MaysaMacedo) [reply pkg/controller/core/workload_controller.go:137]: I tried to do that before, but I got and issue saying WithAdmissionFairSharingConfig was being redeclared given it was declared in the localqueue_controller. Probably this happens because they are under the same package.

Comment (sohankunkerkar) [reply pkg/controller/core/workload_controller.go:137]: ah, that makes sense!

**Comment by sohankunkerkar** [comment]
cc @mimowo

**Comment by kannon92** [comment]
cc @mimowo @gabesaba

**Comment by mimowo** [comment]
cc @PBundyra, could you give it a pass?

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go [hunk 4]
```diff
@@ -1393,6 +1394,83 @@ var _ = ginkgo.Describe("Scheduler", ginkgo.Label("feature:fairsharing", "featur
 			util.ExpectWorkloadsToBePreempted(ctx, k8sClient, wlHighA)
 		})
 	})
+
+	ginkgo.When("Using AdmissionFairSharing", ginkgo.Label("feature:admissionfairsharing"), func() {
```
Comment (PBundyra) [inline test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: Can we merge it with the existing When `Using AdmissionFairSharing at ClusterQueue level`? The setup looks very similar

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go [hunk 5]
```diff
@@ -1393,6 +1394,83 @@ var _ = ginkgo.Describe("Scheduler", ginkgo.Label("feature:fairsharing", "featur
...
+			util.ExpectWorkloadsToBeAdmitted(ctx, k8sClient, wlB)
+
+			ginkgo.By("Verifying no entry penalty exists after workload admission")
+			gomega.Eventually(func(g gomega.Gomega) {
+				penalty := qManager.AfsEntryPenalties.HasPendingFor(lqBKey)
+				g.Expect(penalty).To(gomega.BeFalse(), "entry penalty should be absent for lq-b")
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+			ginkgo.By("Verifying lq-b now has non-zero consumed resources")
+			util.ExpectLocalQueueFairSharingUsageToBe(ctx, k8sClient, client.ObjectKeyFromObject(lqB), ">", 0)
```
Comment (PBundyra) [inline test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: While the first part of the case looks great, I believe this is redundant as we already have cases that test exactly this

**Comment by PBundyra** [comment]
LGTM when it comes to logic, just some comments to tests

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go (hunk 5 above)
Comment (MaysaMacedo) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: I'm assuming this is the code block you're talking about, so I'm removing it. Let me know in case it's not.
```
			ginkgo.By("Creating competing pending workloads from both queues")
			_ = createWorkload("lq-a", "4")
			wlB := createWorkload("lq-b", "4")

			ginkgo.By("Releasing quota so one pending workload can be admitted")
			util.FinishWorkloads(ctx, k8sClient, wlA1)

			ginkgo.By("Verifying lq-b workload is admitted first due to lower consumed usage")
			util.ExpectWorkloadsToBeAdmitted(ctx, k8sClient, wlB)

			ginkgo.By("Verifying no entry penalty exists after workload admission")
			gomega.Eventually(func(g gomega.Gomega) {
				penalty := qManager.AfsEntryPenalties.HasPendingFor(lqBKey)
				g.Expect(penalty).To(gomega.BeFalse(), "entry penalty should be absent for lq-b")
			}, util.Timeout, util.Interval).Should(gomega.Succeed())

			ginkgo.By("Verifying lq-b now has non-zero consumed resources")
			util.ExpectLocalQueueFairSharingUsageToBe(ctx, k8sClient, client.ObjectKeyFromObject(lqB), ">", 0)
```

**Comment by PBundyra** [comment]
/lgtm
Thank you!

**Comment by mimowo** [comment]
Thank you 👍 
/approve
/cherrypick release-0.17
/cherrypick release-0.16

**Comment by mimowo** [comment]
@MaysaMacedo please prepare the CP for 0.16 manually

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
AdmissionFairSharing: Fixed a bug in entry penalties by reducing them when workload is admitted and also clearing them up if all the resources on the admission entry penalty have value zero.
```
