### PR TITLE
Fix: remove workload finalizer if workload is finished

### LINKED ISSUE #1450: High churn cluster with pod only causing stuck queue and overcommitment
**What happened**:

Workloads are not deleted even though the pods are deleted, keeping a dangling finalizer and thus the queue gets stuck

**What you expected to happen**:

Work is processed correctly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The queue shows > 1000 admitted workloads, even though only about 110 are allowed:

Bildschirmfoto 2023-12-13 um 19 44 45

The following shows that there are stucked workloads on the ClusterQueue "background" stuck since a few hours.
Bildschirmfoto 2023-12-13 um 19 59 04

workloads have a deletion timestamp and finalizer, which is hours old (pod does not exist anymore)
Bildschirmfoto 2023-12-13 um 20 18 36

looks like that is not finialized, even though the "JobFinished" condition is true on the workflow (example from a different stuck workload): 

Bildschirmfoto 2023-12-14 um 08 08 31

Deleting the finalizer, causes the admitted "workload" resources to get cleaned up. Restarting the controller didn't resolve the error.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.28.3-eks
- Kueue version (use `git describe --tags --dirty --always`): v0.5.1
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by achernevskii**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Workload will be finalized if it has a Finished condition and no OwnerReferences.

#### Which issue(s) this PR fixes:

Fixes #1450

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/jobs/pod/pod_controller_test.go [hunk 1]
```diff
@@ -990,8 +990,21 @@ func TestReconciler(t *testing.T) {
...
+					PodSets(*utiltesting.MakePodSet("b990493b", 2).Request(corev1.ResourceCPU, "1").Obj()).
+					Queue("test-queue").
+					ReserveQuota(
+						utiltesting.MakeAdmission("cq").
+							Assignment(corev1.ResourceCPU, "unit-test-flavor", "2").
+							AssignmentPodCount(2).
+							Obj(),
+					).
+					Admitted(true).
+					Delete().
```
Comment (tenzen-y) [inline pkg/controller/jobs/pod/pod_controller_test.go:1004]: Should we verify in https://github.com/kubernetes-sigs/kueue/blob/6242c0ff8ab90887424805321d2275ff14a6765d/pkg/controller/jobs/pod/pod_controller_test.go#L2153 if the workload has `deletionTimestamp` instead of adding such a deletionTimestamp?

File: pkg/util/workload/workload.go [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+import (
+	"context"
+
+	"sigs.k8s.io/controller-runtime/pkg/client"
+	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
+
+	kueue "sigs.k8s.io/kueue/apis/kueue/v1beta1"
+)
+
+func RemoveWorkloadFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) error {
```
Comment (tenzen-y) [inline pkg/util/workload/workload.go:12]: Should we move this function to the `workload` (pkg/workload) package?

**Comment by tenzen-y** [comment]
@achernevskii Also, can you fix the CI error?

File: pkg/controller/core/workload_controller.go [hunk 3]
```diff
@@ -133,8 +134,8 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 	ctx = ctrl.LoggerInto(ctx, log)
 	log.V(2).Info("Reconciling Workload")
 
-	if apimeta.IsStatusConditionTrue(wl.Status.Conditions, kueue.WorkloadFinished) {
-		return ctrl.Result{}, nil
+	if apimeta.IsStatusConditionTrue(wl.Status.Conditions, kueue.WorkloadFinished) && len(wl.ObjectMeta.OwnerReferences) == 0 {
```
[the remark this answers is not in the document]
Comment (achernevskii) [reply pkg/controller/core/workload_controller.go:137]: If workload has an owner reference, there's a possibility that the owner job should be stopped:
https://github.com/kubernetes-sigs/kueue/blob/bb69906b810c13c4c49d1386d4c2341f713738e3/pkg/controller/jobframework/reconciler.go#L257
We will introduce a race condition between the workload and job controller if we don't check for the owner references here.

And the workload is finalized here for the uncommon scenario, when the workload has no owner references, so the reconcile for respective job could not be queued.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/core/workload_controller.go:137]: I think it should look more like this:

```
if len(owners) == 0 && deletionTimestamp != nil {
  finalize()
}
if finished {
  return
}
```

Note that workloads might not have owners in two cases:
- When using prebuilt workload #1358
- When using orphan cascade deletion https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#set-orphan-deletion-policy

[the remark this answers is not in the document]
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:137]: @achernevskii Thank you for the clarifications!
As @alculquicondor mentioned, there are some positive situations when the workload doesn't have 
ownerReference. So, I think that we should apply the Aldo's suggestion.

File: pkg/util/workload/workload.go (hunk 2 above)
Comment (achernevskii) [reply pkg/util/workload/workload.go]: Done in f0690dcf

File: pkg/controller/core/workload_controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (achernevskii) [reply pkg/controller/core/workload_controller.go]: Changed the behavior in f0690dcf

File: pkg/controller/core/workload_controller_test.go [hunk 4]
```diff
@@ -329,6 +355,42 @@ func TestReconcile(t *testing.T) {
...
+				OwnerReference(batchv1.SchemeGroupVersion.String(), "Job", "job", "test-uid", true, true).
+				Delete().
+				Obj(),
+			wantWorkload: utiltesting.MakeWorkload("unit-test", "ns").Finalizers(kueue.ResourceInUseFinalizerName).
+				Condition(metav1.Condition{
+					Type:   "Finished",
+					Status: "True",
+				}).
+				OwnerReference(batchv1.SchemeGroupVersion.String(), "Job", "job", "test-uid", true, true).
+				Delete().
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller_test.go:392]: Comparing the `deletionTimestamp` would cause a flaky test?
So, can we verify if the workload has the `deletionTImestamp` in Line 427 instead of comparison?

File: pkg/util/testing/wrappers.go [hunk 5]
```diff
@@ -226,6 +226,13 @@ func (w *WorkloadWrapper) OwnerReference(apiVersion, kind, name, uid string, con
 	return w
 }
 
+// Delete sets a deletion timestamp for the pod object
+func (w *WorkloadWrapper) Delete() *WorkloadWrapper {
```
Comment (tenzen-y) [inline pkg/util/testing/wrappers.go:230]:
```suggestion
// DeletionTimestamp sets a deletion timestamp for the pod object
func (w *WorkloadWrapper) DeletionTimestamp() *WorkloadWrapper {
```

File: pkg/util/testing/wrappers.go [hunk 6]
```diff
@@ -226,6 +226,13 @@ func (w *WorkloadWrapper) OwnerReference(apiVersion, kind, name, uid string, con
...
+	t := metav1.NewTime(time.Now()).Rfc3339Copy()
+	w.Workload.DeletionTimestamp = &t
```
Comment (tenzen-y) [inline pkg/util/testing/wrappers.go:232]:
```suggestion
	w.Workload.DeletionTimestamp := ptr.To(metav1.NewTime(time.Now()).Rfc3339Copy())
```

**Review by tenzen-y — COMMENTED** [review]
Overall lgtm

File: pkg/util/testing/wrappers.go (hunk 6 above)
Comment (achernevskii) [reply pkg/util/testing/wrappers.go:232]: > What is this `Rfc3339Copy` doing? truncating to second?

Correct, had to add it because of https://github.com/kubernetes/kubernetes/issues/81026

File: pkg/controller/core/workload_controller_test.go (hunk 4 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller_test.go:392]: We can probably use `EquateApproxTime`.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
Please squash, so that cherry-picking is less cumbersome.

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

> Please squash, so that cherry-picking is less cumbersome.


@alculquicondor Isn't the default merge method squash?

https://github.com/kubernetes/test-infra/blob/c96b01283ef705e2a3c1f0b836b8ffeef0223c13/config/prow/config.yaml#L783

**Comment by alculquicondor** [comment]
It is, but the cherry-pick bot still goes by the original commits. Not sure if the individual commits could run into conflicts where the squashed commit wouldn't

**Comment by tenzen-y** [comment]
> It is, but the cherry-pick bot still goes by the original commits. Not sure if the individual commits could run into conflicts where the squashed commit wouldn't

I see. I'm fine with manually squash.

**Comment by trasc** [comment]
squashed, but somehow it detected code changes due to rebase. Needs LGTM.

/unhold

**Comment by alculquicondor** [comment]
@tenzen-y do you think it's that important to cherry-pick this?

It's a bit of an edge case.

**Comment by tenzen-y** [comment]
> @tenzen-y do you think it's that important to cherry-pick this?
> 
> It's a bit of an edge case.

@alculquicondor I think that cherry-picking might be better since we have a chance to release a patch version (v0.5.2).
If we don't have any plan to release a patch version, I'm ok with either way.

Are you concerned about manyconflicts?

**Comment by alculquicondor** [comment]
@trasc can you try to get a manual cherry-pick?

**Comment by trasc** [comment]
> @trasc can you try to get a manual cherry-pick?

done #1583

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix a bug in the pod integration that the pod's finalizer won't be removed even though the pod is finished
```
