### PR TITLE
LeaderWorkerSet: Fix bug that doesn't allow to delete Pod after LeaderWorkerSet delete

### LINKED ISSUE #8733: [Flaky E2E] LeaderWorkerSet integration when LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy
/kind flake

**What happened**:

End To End Suite: kindest/node:v1.33.7: [It] LeaderWorkerSet integration when LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy [area:singlecluster, feature:leaderworkerset]

```
{Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/leaderworkerset_test.go:401 with:
Expected
    <[]v1.Pod | len:1, cap:1>: [
        {
            TypeMeta: {Kind: "", APIVersion: ""},
            ObjectMeta: {
                Name: "lws-1",
                GenerateName: "lws-",
                Namespace: "lws-e2e-kxs58",
                SelfLink: "",
                UID: "2e00ca28-c0a8-4163-b2eb-401eb3e28ada",
                ResourceVersion: "7408",
                Generation: 3,
                CreationTimestamp: {
                    Time: 2026-01-22T04:44:12Z,
                },
                DeletionTimestamp: {
                    Time: 2026-01-22T04:44:16Z,
                },
                DeletionGracePeriodSeconds: 0,
                Labels: {
                    "kueue.x-k8s.io/podset": "main",
                    "kueue.x-k8s.io/queue-name": "lws-lq-lws-e2e-kxs58",
                    "leaderworkerset.sigs.k8s.io/group-index": "1",
                    "leaderworkerset.sigs.k8s.io/worker-index": "0",
                    "statefulset.kubernetes.io/pod-name": "lws-1",
                    "kueue.x-k8s.io/managed": "true",
                    "kueue.x-k8s.io/prebuilt-workload-name": "leaderworkerset-lws-1-617bf",
                    "leaderworkerset.sigs.k8s.io/group-key": "ab78cb5390af86053cda5b5fbad00c73773216e3",
                    "leaderworkerset.sigs.k8s.io/name": "lws",
                    "leaderworkerset.sigs.k8s.io/template-revision-hash": "855d744646",
                    "apps.kubernetes.io/pod-index": "1",
                    "controller-revision-hash": "lws-99c4ff976",
                    "kueue.x-k8s.io/pod-group-name": "leaderworkerset-lws-1-617bf",
                },
                Annotations: {
                    "kueue.x-k8s.io/pod-group-total-count": "3",
                    "kueue.x-k8s.io/pod-suspending-parent": "leaderworkerset.x-k8s.io/leaderworkerset",
                    "kueue.x-k8s.io/role-hash": "main",
                    "kueue.x-k8s.io/workload": "leaderworkerset-lws-1-617bf",
                    "leaderworkerset.sigs.k8s.io/size": "3",
                    "kueue.x-k8s.io/pod-group-serving": "true",
                },
                OwnerReferences: [
                    {
                        APIVersion: "apps/v1",
                        Kind: "StatefulSet",
                        Name: "lws",
                        UID: "fa42f1dd-d424-4851-941b-ff313b6985ec",
                        Controller: true,
                        BlockOwnerDeletion: true,
                    },
                ],
                Finalizers: ["foregroundDeletion"],
                ManagedFields: [
                    {
                        Manager: "kueue",
                        Operation: "Apply",
                        APIVersion: "v1",
                        Time: {
                            Time: 2026-01-22T04:44:14Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:status\":{\"f:conditions\":{\"k:{\\\"type\\\":\\\"TerminationTarget\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}}}}",
                        },
                        Subresource: "status",
                    },
                    {
                        Manager: "kube-controller-manager",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2026-01-22T04:44:12Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kueue.x-k8s.io/pod-group-serving\":{},\"f:kueue.x-k8s.io/pod-suspending-parent\":{},\"f:leaderworkerset.sigs.k8s.io/size\":{}},\"f:generateName\":{},\"f:labels\":{\".\":{},\"f:apps.kubernetes.io/pod-index\":{},\"f:controller-revision-hash\":{},\"f:leaderworkerset.sigs.k8s.io/name\":{},\"f:leaderworkerset.sigs.k8s.io/template-revision-hash\":{},\"f:leaderworkerset.sigs.k8s.io/worker-index\":{},\"f:statefulset.kubernetes.io/pod-name\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"fa42f1dd-d424-4851-941b-ff313b6985ec\\\"}\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"c\\\"}\":{\".\":{},\"f:args\":{},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:name\":{},\"f:resources\":{\".\":{},\"f:limits\":{\".\":{},\"f:cpu\":{}},\"f:requests\":{\".\":{},\"f:cpu\":{}}},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{}}},\"f:dnsPolicy\":{},\"f:enableServiceLinks\":{},\"f:hostname\":{},\"f:restartPolicy\":{},\"f:schedulerName\":{},\"f:securityContext\":{},\"f:subdomain\":{},\"f:terminationGracePeriodSeconds\":{}}}",
                        },
                        Subresource: "",
                    },
                    {
                        Manager: "kueue",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2026-01-22T04:44:12Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:metadata\":{\"f:annotations\":{\"f:kueue.x-k8s.io/pod-group-total-count\":{},\"f:kueue.x-k8s.io/role-hash\":{},\"f:kueue.x-k8s.io/workload\":{}},\"f:labels\":{\"f:kueue.x-k8s.io/managed\":{},\"f:kueue.x-k8s.io/pod-group-name\":{},\"f:kueue.x-k8s.io/podset\":{},\"f:kueue.x-k8s.io/prebuilt-workload-name\":{},\"f:kueue.x-k8s.io/queue-name\":{}}},\"f:spec\":{\"f:nodeSelector\":{}}}",
                        },
                        Subresource: "",
                    },
                    {
                        Manager: "kubelet",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2026-01-22T04:44:15Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:status\":{\"f:conditions\":{\"k:{\\\"type\\\":\\\"ContainersReady\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Initialized\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"PodReadyToStartContainers\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Ready\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}},\"f:containerStatuses\":{},\"f:hostIP\":{},\"f:hostIPs\":{},\"f:phase\":{},\"f:podIP\":{},\"f:podIPs\":{\".\":{},\"k:{\\\"ip\\\":\\\"10.244.2.80\\\"}\":{\".\":{},\"f:ip\":{}}},\"f:startTime\":{}}}",
                        },
                        Subresource: "status",
                    },
                ],
            },
            Spec: {
                Volumes: [
                    {
                        Name: "kube-api-access-wb522",
                        VolumeSource: {
                            HostPath: nil,
                            EmptyDir: nil,
                            GCEPersistentDisk: nil,
                            AWSElasticBlockStore: nil,
                            GitRepo: nil,
                            Secret: nil,
                            NFS: nil,
                            ISCSI: nil,
                            Glusterfs: nil,
                            PersistentVolumeClaim: nil,
                            RBD: nil,
                            FlexVolume: nil,
                            Cinder: nil,
                            CephFS: nil,
                            Flocker: nil,
                            DownwardAPI: nil,
                            FC: nil,
                            AzureFile: nil,
                            ConfigMap: nil,
                            VsphereVolume: nil,
                            Quobyte: nil,
                            AzureDisk: nil,
                            PhotonPersistentDisk: nil,
                            Projected: {
                                Sources: [
                                    {
                                        Secret: nil,
                                        DownwardAPI: nil,
                                        ConfigMap: nil,
                                        ServiceAccountToken: {
                                            Audience: ...,
                                            ExpirationSeconds: ...,
                                            Path: ...,
                                        },
                                        ClusterTrustBundle: nil,
                                        PodCertificate: nil,
                                    },
                                    {
                                        Secret: nil,
                                        DownwardAPI: nil,
                                        ConfigMap: {
                                            LocalObjectReference: ...,
                                            Items: ...,
                                            Optional: ...,
                                        },
                                        ServiceAccountToken: nil,
                                        ClusterTrustBundle: nil,
                                        PodCertificate: nil,
                                    },
                                    {
                                        Secret: nil,
                                        DownwardAPI: {Items: ...},
                                        ConfigMap: nil,
                                        ServiceAccountToken: nil,
                                        ClusterTrustBundle: nil,
                                        PodCertificate: nil,
                                    },
                                ],
                                DefaultMode: 420,
                            },
                            PortworxVolume: nil,
                            ScaleIO: nil,
                            StorageOS: nil,
                            CSI: nil,
                            Ephemeral: nil,
                            Image: nil,
                        },
                    },
                ],
                InitContainers: nil,
                Containers: [
                    {
                        Name: "c",
                        Image: "registry.k8s.io/e2e-test-images/agnhost:2.60",
                        Command: nil,
                        Args: ["netexec"],
                        WorkingDir: "",
                        Ports: nil,
                        EnvFrom: nil,
                        Env: [
                            {
                                Name: "LWS_LEADER_ADDRESS",
                                Value: "lws-1.lws.lws-e2e-kxs58",
                                ValueFrom: nil,
                            },
                            {
                                Name: "LWS_GROUP_SIZE",
                                Value: "3",
                                ValueFrom: nil,
                            },
                            {
                                Name: "LWS_WORKER_INDEX",
                                Value: "0",
                                ValueFrom: nil,
                            },
                        ],
                        Resources: {
                            Limits: {
                                "cpu": {
                                    i: {value: 200, scale: -3},
                                    d: {Dec: nil},
                                    s: "200m",
                                    Format: "DecimalSI",
                                },
                            },
                            Requests: {
                                "cpu": {
                                    i: {value: 200, scale: -3},
                                    d: {Dec: nil},
                                    s: "200m",
                                    Format: "DecimalSI",
                                },
                            },
                            Claims: nil,
                        },
                        ResizePolicy: nil,
                        RestartPolicy: nil,
                        RestartPolicyRules: nil,
                        VolumeMounts: [
                            {
                                Name: "kube-api-access-wb522",
                                ReadOnly: true,
                                RecursiveReadOnly: nil,
                                MountPath: "/var/run/secrets/kubernetes.io/serviceaccount",
                                SubPath: "",
                                MountPropagation: nil,
                                SubPathExpr: "",
                            },
                        ],
                        VolumeDevices: nil,
                        LivenessProbe: nil,
                        ReadinessProbe: nil,
                        StartupProbe: nil,
                        Lifecycle: nil,
                        TerminationMessagePath: "/dev/termination-log",
                        TerminationMessagePolicy: "File",
                        ImagePullPolicy: "IfNotPresent",
                        SecurityContext: nil,
                        Stdin: false,
                        StdinOnce: false,
                        TTY: false,
                    },
                ],
                EphemeralContainers: nil,
                RestartPolicy: "Always",
                TerminationGracePeriodSeconds: 1,
                ActiveDeadlineSeconds: nil,
                DNSPolicy: "ClusterFirst",
                NodeSelector: {
                    "instance-type": "on-demand",
                },
                ServiceAccountName: "default",
                DeprecatedServiceAccount: "default",
                AutomountServiceAccountToken: nil,
                NodeName: "kind-worker",
                HostNetwork: false,
                HostPID: false,
                HostIPC: false,
                ShareProcessNamespace: nil,
                SecurityContext: {
                    SELinuxOptions: nil,
                    WindowsOptions: nil,
                    RunAsUser: nil,
                    RunAsGroup: nil,
                    RunAsNonRoot: nil,
                    SupplementalGroups: nil,
                    SupplementalGroupsPolicy: nil,
                    FSGroup: nil,
                    Sysctls: nil,
                    FSGroupChangePolicy: nil,
                    SeccompProfile: nil,
                    AppArmorProfile: nil,
                    SELinuxChangePolicy: nil,
                },
                ImagePullSecrets: nil,
                Hostname: "lws-1",
                Subdomain: "lws",
                Affinity: nil,
                SchedulerName: "default-scheduler",
                Tolerations: [
                    {
                        Key: "node.kubernetes.io/not-ready",
                        Operator: "Exists",
                        Value: "",
                        Effect: "NoExecute",
                        TolerationSeconds: 300,
                    },
                    {
                        Key: "node.kubernetes.io/unreachable",
                        Operator: "Exists",
                        Value: "",
                        Effect: "NoExecute",
                        TolerationSeconds: 300,
                    },
                ],
                HostAliases: nil,
                PriorityClassName: "",
                Priority: 0,
                DNSConfig: nil,
                ReadinessGates: nil,
                RuntimeClassName: nil,
                EnableServiceLinks: true,
                PreemptionPolicy: "PreemptLowerPriority",
                Overhead: nil,
                TopologySpreadConstraints: nil,
                SetHostnameAsFQDN: nil,
                OS: nil,
                HostUsers: nil,
                SchedulingGates: nil,
                ResourceClaims: nil,
                Resources: nil,
                HostnameOverride: nil,
                WorkloadRef: nil,
            },
            Status: {
                ObservedGeneration: 0,
                Phase: "Succeeded",
                Conditions: [
                    {
                        Type: "TerminationTarget",
                        ObservedGeneration: 0,
                        Status: "True",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:14Z,
                        },
                        Reason: "NoMatchingWorkload",
                        Message: "missing workload",
                    },
                    {
                        Type: "PodReadyToStartContainers",
                        ObservedGeneration: 0,
                        Status: "False",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:15Z,
                        },
                        Reason: "",
                        Message: "",
                    },
                    {
                        Type: "Initialized",
                        ObservedGeneration: 0,
                        Status: "True",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:12Z,
                        },
                        Reason: "PodCompleted",
                        Message: "",
                    },
                    {
                        Type: "Ready",
                        ObservedGeneration: 0,
                        Status: "False",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:15Z,
                        },
                        Reason: "PodCompleted",
                        Message: "",
                    },
                    {
                        Type: "ContainersReady",
                        ObservedGeneration: 0,
                        Status: "False",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:15Z,
                        },
                        Reason: "PodCompleted",
                        Message: "",
                    },
                    {
                        Type: "PodScheduled",
                        ObservedGeneration: 0,
                        Status: "True",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:12Z,
                        },
                        Reason: "",
                        Message: "",
                    },
                ],
                Message: "",
                Reason: "",
                NominatedNodeName: "",
                HostIP: "172.18.0.3",
                HostIPs: [{IP: "172.18.0.3"}],
                PodIP: "10.244.2.80",
                PodIPs: [{IP: "10.244.2.80"}],
                StartTime: {
                    Time: 2026-01-22T04:44:12Z,
                },
                InitContainerStatuses: nil,
                ContainerStatuses: [
                    {
                        Name: "c",
                        State: {
                            Waiting: nil,
                            Running: nil,
                            Terminated: {
                                ExitCode: 0,
                                Signal: 0,
                                Reason: "Completed",
                                Message: "",
                                StartedAt: {
                                    Time: 2026-01-22T04:44:13Z,
                                },
                                FinishedAt: {
                                    Time: 2026-01-22T04:44:15Z,
                                },
                                ContainerID: "containerd://2f779c4800f5e708da239f009065e03a992b9c6baa4027684d0a2124514bb8d2",
                            },
                        },
                        LastTerminationState: {Waiting: nil, Running: nil, Terminated: nil},
                        Ready: false,
                        RestartCount: 0,
                        Image: "registry.k8s.io/e2e-test-images/agnhost:2.60",
                        ImageID: "sha256:d9b1f93401bfcf4303c130dca0890f18667239f8daf633d211f718a230604147",
                        ContainerID: "containerd://2f779c4800f5e708da239f009065e03a992b9c6baa4027684d0a2124514bb8d2",
                        Started: false,
                        AllocatedResources: {
                            "cpu": {
                                i: {value: 200, scale: -3},
                                d: {Dec: nil},
                                s: "200m",
                                Format: "DecimalSI",
                            },
                        },
                        Resources: {
                            Limits: {
                                "cpu": {
                                    i: {value: 200, scale: -3},
                                    d: {Dec: nil},
                                    s: "200m",
                                    Format: "DecimalSI",
                                },
                            },
                            Requests: {
                                "cpu": {
                                    i: {value: 200, scale: -3},
                                    d: {Dec: nil},
                                    s: "200m",
                                    Format: "DecimalSI",
                                },
                            },
                            Claims: nil,
                        },
                        VolumeMounts: [
                            {
                                Name: "kube-api-access-wb522",
                                MountPath: "/var/run/secrets/kubernetes.io/serviceaccount",
                                ReadOnly: true,
                                RecursiveReadOnly: "Disabled",
                            },
                        ],
                        User: {
                            Linux: {
                                UID: 0,
                                GID: 0,
                                SupplementalGroups: [0, 1, 2, 3, 4, 6, 10, 11, 20, 26, 27],
                            },
                        },
                        AllocatedResourcesStatus: nil,
                        StopSignal: nil,
                    },
                ],
                QOSClass: "Burstable",
                EphemeralContainerStatuses: nil,
                Resize: "",
                ResourceClaimStatuses: nil,
                ExtendedResourceClaimStatus: nil,
                AllocatedResources: nil,
                Resources: nil,
            },
        },
    ]
to be empty failed [FAILED] Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/leaderworkerset_test.go:401 with:
Expected
    <[]v1.Pod | len:1, cap:1>: [
        {
            TypeMeta: {Kind: "", APIVersion: ""},
            ObjectMeta: {
                Name: "lws-1",
                GenerateName: "lws-",
                Namespace: "lws-e2e-kxs58",
                SelfLink: "",
                UID: "2e00ca28-c0a8-4163-b2eb-401eb3e28ada",
                ResourceVersion: "7408",
                Generation: 3,
                CreationTimestamp: {
                    Time: 2026-01-22T04:44:12Z,
                },
                DeletionTimestamp: {
                    Time: 2026-01-22T04:44:16Z,
                },
                DeletionGracePeriodSeconds: 0,
                Labels: {
                    "kueue.x-k8s.io/podset": "main",
                    "kueue.x-k8s.io/queue-name": "lws-lq-lws-e2e-kxs58",
                    "leaderworkerset.sigs.k8s.io/group-index": "1",
                    "leaderworkerset.sigs.k8s.io/worker-index": "0",
                    "statefulset.kubernetes.io/pod-name": "lws-1",
                    "kueue.x-k8s.io/managed": "true",
                    "kueue.x-k8s.io/prebuilt-workload-name": "leaderworkerset-lws-1-617bf",
                    "leaderworkerset.sigs.k8s.io/group-key": "ab78cb5390af86053cda5b5fbad00c73773216e3",
                    "leaderworkerset.sigs.k8s.io/name": "lws",
                    "leaderworkerset.sigs.k8s.io/template-revision-hash": "855d744646",
                    "apps.kubernetes.io/pod-index": "1",
                    "controller-revision-hash": "lws-99c4ff976",
                    "kueue.x-k8s.io/pod-group-name": "leaderworkerset-lws-1-617bf",
                },
                Annotations: {
                    "kueue.x-k8s.io/pod-group-total-count": "3",
                    "kueue.x-k8s.io/pod-suspending-parent": "leaderworkerset.x-k8s.io/leaderworkerset",
                    "kueue.x-k8s.io/role-hash": "main",
                    "kueue.x-k8s.io/workload": "leaderworkerset-lws-1-617bf",
                    "leaderworkerset.sigs.k8s.io/size": "3",
                    "kueue.x-k8s.io/pod-group-serving": "true",
                },
                OwnerReferences: [
                    {
                        APIVersion: "apps/v1",
                        Kind: "StatefulSet",
                        Name: "lws",
                        UID: "fa42f1dd-d424-4851-941b-ff313b6985ec",
                        Controller: true,
                        BlockOwnerDeletion: true,
                    },
                ],
                Finalizers: ["foregroundDeletion"],
                ManagedFields: [
                    {
                        Manager: "kueue",
                        Operation: "Apply",
                        APIVersion: "v1",
                        Time: {
                            Time: 2026-01-22T04:44:14Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:status\":{\"f:conditions\":{\"k:{\\\"type\\\":\\\"TerminationTarget\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}}}}",
                        },
                        Subresource: "status",
                    },
                    {
                        Manager: "kube-controller-manager",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2026-01-22T04:44:12Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kueue.x-k8s.io/pod-group-serving\":{},\"f:kueue.x-k8s.io/pod-suspending-parent\":{},\"f:leaderworkerset.sigs.k8s.io/size\":{}},\"f:generateName\":{},\"f:labels\":{\".\":{},\"f:apps.kubernetes.io/pod-index\":{},\"f:controller-revision-hash\":{},\"f:leaderworkerset.sigs.k8s.io/name\":{},\"f:leaderworkerset.sigs.k8s.io/template-revision-hash\":{},\"f:leaderworkerset.sigs.k8s.io/worker-index\":{},\"f:statefulset.kubernetes.io/pod-name\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"fa42f1dd-d424-4851-941b-ff313b6985ec\\\"}\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"c\\\"}\":{\".\":{},\"f:args\":{},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:name\":{},\"f:resources\":{\".\":{},\"f:limits\":{\".\":{},\"f:cpu\":{}},\"f:requests\":{\".\":{},\"f:cpu\":{}}},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{}}},\"f:dnsPolicy\":{},\"f:enableServiceLinks\":{},\"f:hostname\":{},\"f:restartPolicy\":{},\"f:schedulerName\":{},\"f:securityContext\":{},\"f:subdomain\":{},\"f:terminationGracePeriodSeconds\":{}}}",
                        },
                        Subresource: "",
                    },
                    {
                        Manager: "kueue",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2026-01-22T04:44:12Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:metadata\":{\"f:annotations\":{\"f:kueue.x-k8s.io/pod-group-total-count\":{},\"f:kueue.x-k8s.io/role-hash\":{},\"f:kueue.x-k8s.io/workload\":{}},\"f:labels\":{\"f:kueue.x-k8s.io/managed\":{},\"f:kueue.x-k8s.io/pod-group-name\":{},\"f:kueue.x-k8s.io/podset\":{},\"f:kueue.x-k8s.io/prebuilt-workload-name\":{},\"f:kueue.x-k8s.io/queue-name\":{}}},\"f:spec\":{\"f:nodeSelector\":{}}}",
                        },
                        Subresource: "",
                    },
                    {
                        Manager: "kubelet",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2026-01-22T04:44:15Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:status\":{\"f:conditions\":{\"k:{\\\"type\\\":\\\"ContainersReady\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Initialized\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"PodReadyToStartContainers\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Ready\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}},\"f:containerStatuses\":{},\"f:hostIP\":{},\"f:hostIPs\":{},\"f:phase\":{},\"f:podIP\":{},\"f:podIPs\":{\".\":{},\"k:{\\\"ip\\\":\\\"10.244.2.80\\\"}\":{\".\":{},\"f:ip\":{}}},\"f:startTime\":{}}}",
                        },
                        Subresource: "status",
                    },
                ],
            },
            Spec: {
                Volumes: [
                    {
                        Name: "kube-api-access-wb522",
                        VolumeSource: {
                            HostPath: nil,
                            EmptyDir: nil,
                            GCEPersistentDisk: nil,
                            AWSElasticBlockStore: nil,
                            GitRepo: nil,
                            Secret: nil,
                            NFS: nil,
                            ISCSI: nil,
                            Glusterfs: nil,
                            PersistentVolumeClaim: nil,
                            RBD: nil,
                            FlexVolume: nil,
                            Cinder: nil,
                            CephFS: nil,
                            Flocker: nil,
                            DownwardAPI: nil,
                            FC: nil,
                            AzureFile: nil,
                            ConfigMap: nil,
                            VsphereVolume: nil,
                            Quobyte: nil,
                            AzureDisk: nil,
                            PhotonPersistentDisk: nil,
                            Projected: {
                                Sources: [
                                    {
                                        Secret: nil,
                                        DownwardAPI: nil,
                                        ConfigMap: nil,
                                        ServiceAccountToken: {
                                            Audience: ...,
                                            ExpirationSeconds: ...,
                                            Path: ...,
                                        },
                                        ClusterTrustBundle: nil,
                                        PodCertificate: nil,
                                    },
                                    {
                                        Secret: nil,
                                        DownwardAPI: nil,
                                        ConfigMap: {
                                            LocalObjectReference: ...,
                                            Items: ...,
                                            Optional: ...,
                                        },
                                        ServiceAccountToken: nil,
                                        ClusterTrustBundle: nil,
                                        PodCertificate: nil,
                                    },
                                    {
                                        Secret: nil,
                                        DownwardAPI: {Items: ...},
                                        ConfigMap: nil,
                                        ServiceAccountToken: nil,
                                        ClusterTrustBundle: nil,
                                        PodCertificate: nil,
                                    },
                                ],
                                DefaultMode: 420,
                            },
                            PortworxVolume: nil,
                            ScaleIO: nil,
                            StorageOS: nil,
                            CSI: nil,
                            Ephemeral: nil,
                            Image: nil,
                        },
                    },
                ],
                InitContainers: nil,
                Containers: [
                    {
                        Name: "c",
                        Image: "registry.k8s.io/e2e-test-images/agnhost:2.60",
                        Command: nil,
                        Args: ["netexec"],
                        WorkingDir: "",
                        Ports: nil,
                        EnvFrom: nil,
                        Env: [
                            {
                                Name: "LWS_LEADER_ADDRESS",
                                Value: "lws-1.lws.lws-e2e-kxs58",
                                ValueFrom: nil,
                            },
                            {
                                Name: "LWS_GROUP_SIZE",
                                Value: "3",
                                ValueFrom: nil,
                            },
                            {
                                Name: "LWS_WORKER_INDEX",
                                Value: "0",
                                ValueFrom: nil,
                            },
                        ],
                        Resources: {
                            Limits: {
                                "cpu": {
                                    i: {value: 200, scale: -3},
                                    d: {Dec: nil},
                                    s: "200m",
                                    Format: "DecimalSI",
                                },
                            },
                            Requests: {
                                "cpu": {
                                    i: {value: 200, scale: -3},
                                    d: {Dec: nil},
                                    s: "200m",
                                    Format: "DecimalSI",
                                },
                            },
                            Claims: nil,
                        },
                        ResizePolicy: nil,
                        RestartPolicy: nil,
                        RestartPolicyRules: nil,
                        VolumeMounts: [
                            {
                                Name: "kube-api-access-wb522",
                                ReadOnly: true,
                                RecursiveReadOnly: nil,
                                MountPath: "/var/run/secrets/kubernetes.io/serviceaccount",
                                SubPath: "",
                                MountPropagation: nil,
                                SubPathExpr: "",
                            },
                        ],
                        VolumeDevices: nil,
                        LivenessProbe: nil,
                        ReadinessProbe: nil,
                        StartupProbe: nil,
                        Lifecycle: nil,
                        TerminationMessagePath: "/dev/termination-log",
                        TerminationMessagePolicy: "File",
                        ImagePullPolicy: "IfNotPresent",
                        SecurityContext: nil,
                        Stdin: false,
                        StdinOnce: false,
                        TTY: false,
                    },
                ],
                EphemeralContainers: nil,
                RestartPolicy: "Always",
                TerminationGracePeriodSeconds: 1,
                ActiveDeadlineSeconds: nil,
                DNSPolicy: "ClusterFirst",
                NodeSelector: {
                    "instance-type": "on-demand",
                },
                ServiceAccountName: "default",
                DeprecatedServiceAccount: "default",
                AutomountServiceAccountToken: nil,
                NodeName: "kind-worker",
                HostNetwork: false,
                HostPID: false,
                HostIPC: false,
                ShareProcessNamespace: nil,
                SecurityContext: {
                    SELinuxOptions: nil,
                    WindowsOptions: nil,
                    RunAsUser: nil,
                    RunAsGroup: nil,
                    RunAsNonRoot: nil,
                    SupplementalGroups: nil,
                    SupplementalGroupsPolicy: nil,
                    FSGroup: nil,
                    Sysctls: nil,
                    FSGroupChangePolicy: nil,
                    SeccompProfile: nil,
                    AppArmorProfile: nil,
                    SELinuxChangePolicy: nil,
                },
                ImagePullSecrets: nil,
                Hostname: "lws-1",
                Subdomain: "lws",
                Affinity: nil,
                SchedulerName: "default-scheduler",
                Tolerations: [
                    {
                        Key: "node.kubernetes.io/not-ready",
                        Operator: "Exists",
                        Value: "",
                        Effect: "NoExecute",
                        TolerationSeconds: 300,
                    },
                    {
                        Key: "node.kubernetes.io/unreachable",
                        Operator: "Exists",
                        Value: "",
                        Effect: "NoExecute",
                        TolerationSeconds: 300,
                    },
                ],
                HostAliases: nil,
                PriorityClassName: "",
                Priority: 0,
                DNSConfig: nil,
                ReadinessGates: nil,
                RuntimeClassName: nil,
                EnableServiceLinks: true,
                PreemptionPolicy: "PreemptLowerPriority",
                Overhead: nil,
                TopologySpreadConstraints: nil,
                SetHostnameAsFQDN: nil,
                OS: nil,
                HostUsers: nil,
                SchedulingGates: nil,
                ResourceClaims: nil,
                Resources: nil,
                HostnameOverride: nil,
                WorkloadRef: nil,
            },
            Status: {
                ObservedGeneration: 0,
                Phase: "Succeeded",
                Conditions: [
                    {
                        Type: "TerminationTarget",
                        ObservedGeneration: 0,
                        Status: "True",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:14Z,
                        },
                        Reason: "NoMatchingWorkload",
                        Message: "missing workload",
                    },
                    {
                        Type: "PodReadyToStartContainers",
                        ObservedGeneration: 0,
                        Status: "False",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:15Z,
                        },
                        Reason: "",
                        Message: "",
                    },
                    {
                        Type: "Initialized",
                        ObservedGeneration: 0,
                        Status: "True",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:12Z,
                        },
                        Reason: "PodCompleted",
                        Message: "",
                    },
                    {
                        Type: "Ready",
                        ObservedGeneration: 0,
                        Status: "False",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:15Z,
                        },
                        Reason: "PodCompleted",
                        Message: "",
                    },
                    {
                        Type: "ContainersReady",
                        ObservedGeneration: 0,
                        Status: "False",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:15Z,
                        },
                        Reason: "PodCompleted",
                        Message: "",
                    },
                    {
                        Type: "PodScheduled",
                        ObservedGeneration: 0,
                        Status: "True",
                        LastProbeTime: {
                            Time: 0001-01-01T00:00:00Z,
                        },
                        LastTransitionTime: {
                            Time: 2026-01-22T04:44:12Z,
                        },
                        Reason: "",
                        Message: "",
                    },
                ],
                Message: "",
                Reason: "",
                NominatedNodeName: "",
                HostIP: "172.18.0.3",
                HostIPs: [{IP: "172.18.0.3"}],
                PodIP: "10.244.2.80",
                PodIPs: [{IP: "10.244.2.80"}],
                StartTime: {
                    Time: 2026-01-22T04:44:12Z,
                },
                InitContainerStatuses: nil,
                ContainerStatuses: [
                    {
                        Name: "c",
                        State: {
                            Waiting: nil,
                            Running: nil,
                            Terminated: {
                                ExitCode: 0,
                                Signal: 0,
                                Reason: "Completed",
                                Message: "",
                                StartedAt: {
                                    Time: 2026-01-22T04:44:13Z,
                                },
                                FinishedAt: {
                                    Time: 2026-01-22T04:44:15Z,
                                },
                                ContainerID: "containerd://2f779c4800f5e708da239f009065e03a992b9c6baa4027684d0a2124514bb8d2",
                            },
                        },
                        LastTerminationState: {Waiting: nil, Running: nil, Terminated: nil},
                        Ready: false,
                        RestartCount: 0,
                        Image: "registry.k8s.io/e2e-test-images/agnhost:2.60",
                        ImageID: "sha256:d9b1f93401bfcf4303c130dca0890f18667239f8daf633d211f718a230604147",
                        ContainerID: "containerd://2f779c4800f5e708da239f009065e03a992b9c6baa4027684d0a2124514bb8d2",
                        Started: false,
                        AllocatedResources: {
                            "cpu": {
                                i: {value: 200, scale: -3},
                                d: {Dec: nil},
                                s: "200m",
                                Format: "DecimalSI",
                            },
                        },
                        Resources: {
                            Limits: {
                                "cpu": {
                                    i: {value: 200, scale: -3},
                                    d: {Dec: nil},
                                    s: "200m",
                                    Format: "DecimalSI",
                                },
                            },
                            Requests: {
                                "cpu": {
                                    i: {value: 200, scale: -3},
                                    d: {Dec: nil},
                                    s: "200m",
                                    Format: "DecimalSI",
                                },
                            },
                            Claims: nil,
                        },
                        VolumeMounts: [
                            {
                                Name: "kube-api-access-wb522",
                                MountPath: "/var/run/secrets/kubernetes.io/serviceaccount",
                                ReadOnly: true,
                                RecursiveReadOnly: "Disabled",
                            },
                        ],
                        User: {
                            Linux: {
                                UID: 0,
                                GID: 0,
                                SupplementalGroups: [0, 1, 2, 3, 4, 6, 10, 11, 20, 26, 27],
                            },
                        },
                        AllocatedResourcesStatus: nil,
                        StopSignal: nil,
                    },
                ],
                QOSClass: "Burstable",
                EphemeralContainerStatuses: nil,
                Resize: "",
                ResourceClaimStatuses: nil,
                ExtendedResourceClaimStatus: nil,
                AllocatedResources: nil,
                Resources: nil,
            },
        },
    ]
to be empty
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/leaderworkerset_test.go:402 @ 01/22/26 04:45:00.661
}
```

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/8732/pull-kueue-test-e2e-main-1-33/2014193502698606592

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #8752: [Flaky E2E] LeaderWorkerSet integration when LeaderWorkerSet created should allow to scale up, scale down fast LeaderReadyStartupPolicy
/kind flake

**What happened**:

End To End Suite: kindest/node:v1.35.0: [It] LeaderWorkerSet integration when LeaderWorkerSet created should allow to scale up, scale down fast LeaderReadyStartupPolicy 

```
{Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:120 with:
Error matcher expects an error.  Got:
    <nil>: nil failed [FAILED] Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:120 with:
Error matcher expects an error.  Got:
    <nil>: nil
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/leaderworkerset_test.go:481 @ 01/23/26 04:53:54.402
}
```

**What you expected to happen**:

No issue

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-release-0-15-1-35/2014557337439703040

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
LeaderWorkerSet: Fix bug that doesn't allow to delete Pod after LeaderWorkerSet delete

#### Which issue(s) this PR fixes:

Fixes #8733
Fixes #8752

#### Does this PR introduce a user-facing change?

```release-note
LeaderWorkerSet: Fixed bug that doesn't allow to delete Pod after LeaderWorkerSet delete
```

### CODE REVIEW

File: test/e2e/singlecluster/leaderworkerset_test.go
Comment (mbobrovskyi) [inline test/e2e/singlecluster/leaderworkerset_test.go:1]: /hold Revert this changes

**Comment by mimowo** [comment]
Please explain tge solution approach, because it looks much more complex than the alternative solution i proposed in another PR, so I would like to understand why all this code is needed.

Also please open alternative PR looping the test 300 tines to confirm tge flake is eliminated

**Comment by mbobrovskyi** [comment]
> Also please open alternative PR looping the test 300 tines to confirm tge flake is eliminated

I added this on this PR. I will revert commit if we take a decision to merge it.

File: pkg/controller/jobs/statefulset/statefulset_controller.go [hunk 1]
```diff
@@ -66,3 +67,10 @@ func (d *StatefulSet) GVK() schema.GroupVersionKind {
 func SetupIndexes(context.Context, client.FieldIndexer) error {
 	return nil
 }
+
+func suspendedByParent(sts *appsv1.StatefulSet) bool {
+	if parent, ok := sts.Spec.Template.Annotations[podconstants.SuspendedByParentAnnotation]; ok {
```
Comment (mykysha) [inline pkg/controller/jobs/statefulset/statefulset_controller.go]: Can we simplify it to be
```
parent, ok := sts.Spec.Template.Annotations[podconstants.SuspendedByParentAnnotation]
return ok && return parent != FrameworkName
```
?

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 2]
```diff
@@ -243,6 +244,11 @@ func (r *Reconciler) handle(obj client.Object) bool {
 	log := r.logger().WithValues("statefulset", klog.KObj(sts))
 	ctrl.LoggerInto(ctx, log)
 
+	if suspendedByParent(sts) {
+		log.V(3).Info(fmt.Sprintf("Skipping reconciliation because %s is set", podcontroller.SuspendedByParentAnnotation))
```
Comment (mykysha) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go]: I believe it might be helpful to include the foreign parent name to the logs, WDYT?

File: pkg/controller/jobs/statefulset/statefulset_controller.go (hunk 1 above)
Comment (mykysha) [reply pkg/controller/jobs/statefulset/statefulset_controller.go]: And I believe that `managedByAnotherFramework` would better fit the name here

File: pkg/controller/jobs/statefulset/statefulset_webhook.go [hunk 3]
```diff
@@ -68,8 +68,19 @@ func SetupWebhook(mgr ctrl.Manager, opts ...jobframework.Option) error {
 var _ webhook.CustomDefaulter = &Webhook{}
 
 func (wh *Webhook) Default(ctx context.Context, obj runtime.Object) error {
+	stsObj, ok := obj.(*appsv1.StatefulSet)
+	if !ok {
+		return nil
+	}
+
 	ss := fromObject(obj)
```
Comment (mykysha) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go]: Nit: I believe the `fromObject` conversion is unnecessary before the ParentAnnotation check, so it could be moved after

Comment (mbobrovskyi) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go]: Done

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Done

File: pkg/controller/jobs/statefulset/statefulset_controller.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/statefulset/statefulset_controller.go]: Done

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 4]
```diff
@@ -243,6 +244,14 @@ func (r *Reconciler) handle(obj client.Object) bool {
 	log := r.logger().WithValues("statefulset", klog.KObj(sts))
 	ctrl.LoggerInto(ctx, log)
 
+	if frameworkName, managed := managedByAnotherFramework(sts); managed {
+		log.V(3).Info(
+			fmt.Sprintf("Skipping reconciliation because %s is set", podcontroller.SuspendedByParentAnnotation),
```
Comment (mykysha) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Also I believe that this log is misleading. We do not skip because podcontroller.SuspendedByParentAnnotation is set but rather because the statefulset is managed by another framework.
Would
```
log.V(3).Info("Skipping reconciliation because the object is managed by another framework", "framework", frameworkName)
```
work?

**Comment by mbobrovskyi** [comment]
Moved the experimental test to another PR: https://github.com/kubernetes-sigs/kueue/pull/8870

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go (hunk 4 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Done

**Comment by mykysha** [comment]
/lgtm
Thank you!

File: pkg/controller/jobs/statefulset/statefulset_webhook.go
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go:189]: I think we should also check the new function `managedByAnotherFramework` here, because otherwise if the k8s GC tries to remove the `foregroundDeletion` finalizer the patch may fail here, because the `WorkloadShouldBeSuspended` function will fail here, wdyt?

Comment (mbobrovskyi) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go:189]: Done

File: pkg/controller/jobs/statefulset/statefulset_webhook.go [hunk 5]
```diff
@@ -68,8 +68,20 @@ func SetupWebhook(mgr ctrl.Manager, opts ...jobframework.Option) error {
 var _ webhook.CustomDefaulter = &Webhook{}
 
 func (wh *Webhook) Default(ctx context.Context, obj runtime.Object) error {
-	ss := fromObject(obj)
+	stsObj, ok := obj.(*appsv1.StatefulSet)
```
Comment (mykysha) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go:71]: I am wondering whether we can create a separate function to convert the `runtime.Object` and check the `*appsv1.StatefulSet` annotations to reduce the duplications

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 6]
```diff
@@ -243,6 +243,11 @@ func (r *Reconciler) handle(obj client.Object) bool {
 	log := r.logger().WithValues("statefulset", klog.KObj(sts))
 	ctrl.LoggerInto(ctx, log)
 
+	if frameworkName, managed := managedByAnotherFramework(sts); managed {
```
Comment (mykysha) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go:246]: Could you please also add a unit test for the reconciler skip?

Comment (mbobrovskyi) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go:246]: Done

File: pkg/controller/jobs/statefulset/statefulset_webhook.go (hunk 5 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go:71]: But we need to skip Default at all if it is not a sts.

**Comment by mbobrovskyi** [comment]
Looks like this solution works. The experiment runs without any related issues: https://github.com/kubernetes-sigs/kueue/pull/8870

**Comment by mimowo** [comment]
/hold
Keeping in case  @sohankunkerkar has some extra comments

/approve
/lgtm
/cherrypick release-0.17
/cherrypick release-0.16

**Comment by mbobrovskyi** [comment]
> One optional suggestion: consider squashing the 5 commits before merge for cleaner git history.

It should be squashed automatically when merging.
