### PR TITLE
Do not cleanup excess pods when awaiting to observe previous clean ups

### LINKED ISSUE #1593: Flaky E2E test for Pod replacement
**What happened**:

Sometimes the Workload is never declared as Finished.

```
End To End Suite: kindest/node:v1.29.0: [It] Pod groups when Single CQ Failed Pod can be replaced in group expand_less	50s
{Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:300 with:
it's finished failed [FAILED] Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:300 with:
it's finished
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:224 @ 01/16/24 20:19:48.709
}
```

Looking at the kube-scheduler logs, the Pod called `excess` got scheduled, which shouldn't have happened. This either means that some other Pod failed or was identified as an excess by Kueue.

**What you expected to happen**:

The workload to finish successfully

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1592/pull-kueue-test-e2e-main-1-29/1747351345448357888

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

- After cleaning up pods, await to observe them in the event handlers before cleaning up more pods.
- When sorting pods for clean up, prefer the ones that are still gated or have lost their finalizer.

This prevents unnecessary cleanups in two scenarios:
- The user creates an excess pod when the group just was started. Previously, the reconciler might not have observed the pods that it ungated, deleting one of these pods.
- The user creates two replacement pods to fill up a Failed Pod. Previously, the reconciler might delete one the Pods in the first reconcile, and the other one in the second reconcile.

#### Which issue(s) this PR fixes:

Fixes #1593

#### Special notes for your reviewer:

Adding parallelism simplified handling of expectations when there are failures. But I extracted the changes specific to parallelism into a separate PR #1632

#### Does this PR introduce a user-facing change?

Unreleased feature

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Passed 3/5

/test pull-kueue-test-e2e-main-1-27
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-29

**Comment by alculquicondor** [comment]
Passed 4/5

/test pull-kueue-test-e2e-main-1-27
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-29

**Comment by mimowo** [comment]
> /assign mimowo

ack

**Comment by alculquicondor** [comment]
Passed 5/5

Bonus run:

/test pull-kueue-test-e2e-main-1-27
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-29

File: pkg/controller/jobs/pod/expectations.go [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+)
+
+type uids = sets.Set[types.UID]
+
+// expectationsStore contains UIDs for which we are waiting to observe some change through event handlers.
+type expectationsStore struct {
+	sync.Mutex
+	name string
+
+	store map[types.NamespacedName]uids
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobs/pod/expectations.go:34]: I considered it, but it doesn't add much value, and it rather adds unnecessary castings.

**Comment by alculquicondor** [comment]
Rebased

File: pkg/controller/jobs/pod/expectations.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/pod/expectations.go:34]: sgtm, it could be helpful if we were to use more functions from it, but the code is quite simple indeed

File: pkg/controller/jobs/pod/pod_controller.go [hunk 2]
```diff
@@ -705,14 +717,34 @@ func (p *Pod) cleanupExcessPods(ctx context.Context, c client.Client, totalCount
...
+	}
 
 	// Sort active pods by creation timestamp
 	sort.Slice(activePods, func(i, j int) bool {
-		return activePods[i].ObjectMeta.CreationTimestamp.Before(&activePods[j].ObjectMeta.CreationTimestamp)
+		pi := &activePods[i]
+		pj := &activePods[j]
+		iFin := slices.Contains(pi.Finalizers, PodFinalizer)
+		jFin := slices.Contains(pj.Finalizers, PodFinalizer)
+		// Keep pods that have a finalizer
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_controller.go:731]: Does it really mean `keep` or, just prioritize removal of pods without finalizer?

File: pkg/controller/jobs/pod/pod_controller.go [hunk 3]
```diff
@@ -705,14 +717,34 @@ func (p *Pod) cleanupExcessPods(ctx context.Context, c client.Client, totalCount
...
+		if iFin != jFin {
+			return iFin
+		}
+		iGated := gateIndex(pi) != gateNotFound
+		jGated := gateIndex(pj) != gateNotFound
+		// keep pods that aren't gated.
+		if iGated != jGated {
+			return !iGated
+		}
+		return pi.ObjectMeta.CreationTimestamp.Before(&pj.ObjectMeta.CreationTimestamp)
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_controller.go:741]: This would not break the tie if we have 2 excess pods, created in the same second. All pods have a finalizer, and all aren't gated. Can you confirm this is not an issue, and explain why?

File: pkg/controller/jobs/pod/pod_controller_test.go [hunk 4]
```diff
@@ -2091,6 +2092,180 @@ func TestReconciler(t *testing.T) {
...
+					Admitted(true).
+					Obj(),
+			},
+			workloadCmpOpts: defaultWorkloadCmpOpts,
+			excessPodsExpectations: []keyUIDs{{
+				key:  types.NamespacedName{Name: "test-group", Namespace: "ns"},
+				uids: []types.UID{"pod2"},
+			}},
+		},
+		"delete excess pod that is gated": {
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_controller_test.go:2193]: Could we ever delete an excess pod if it is not gated? Possibly not related to the PR directly, just prior work, but would like to know.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller.go]: updated comment

File: pkg/controller/jobs/pod/pod_controller.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller.go:741]: In the first iteration, any of the 2 pods will be picked. In the second iteration, if we haven't observed the finalizer removal or the pod disappearing, then will return before deleting more pods.

File: pkg/controller/jobs/pod/pod_controller_test.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller_test.go:2193]: yes, it can be deleted too.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller.go]: sgtm

File: pkg/controller/jobs/pod/pod_controller.go (hunk 3 above)
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller.go:741]: I see, sounds good

File: pkg/controller/jobs/pod/pod_controller_test.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller_test.go:2193]: I see, makes sense. So, from correctness point of view we could delete any of them, but it is preferable to delete the one that is gated, because it hasn't started computations yet. The aim of this test case is to demonstrate that out of the candidates we pick the one that is gated. sgtm.

File: pkg/controller/jobs/pod/event_handlers.go [hunk 5]
```diff
@@ -54,11 +57,25 @@ func (h *podEventHandler) Update(ctx context.Context, e event.UpdateEvent, q wor
...
+	if !ok {
+		return
+	}
+
+	log := ctrl.LoggerFrom(ctx).WithValues("pod", klog.KObj(p))
+
+	if g, isGroup := p.Labels[GroupNameLabel]; isGroup {
+		// If the watch was temporarily unavailable, it is possible that the object reported in the event still
+		// has a finalizer, but we can consider this Pod cleaned up, as it is being deleted.
+		h.cleanedUpPodsExpectations.ObservedUID(log, types.NamespacedName{Namespace: p.Namespace, Name: g}, p.UID)
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/event_handlers.go:70]: I decided to not check the finalizer in Delete, just in case.

File: pkg/controller/jobs/pod/pod_controller_test.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller_test.go:2193]: Exactly.

Imagine the following scenario:
1. 1 replacement pod is created. The reconciler ungates it.
2. The user creates another replacement pod by mistake (so it's excess). This has the same timestamp as the previous pod.
3. Kueue should delete the gated pod.

Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller_test.go:2193]: Also, this is covered by the existing E2E test, as we create replacement pods without waiting.

File: pkg/controller/jobs/pod/event_handlers.go [hunk 6]
```diff
@@ -54,11 +57,25 @@ func (h *podEventHandler) Update(ctx context.Context, e event.UpdateEvent, q wor
...
+	}
+
+	log.V(5).Info("Queueing reconcile for pod")
+
+	q.Add(reconcileRequestForPod(p))
 }
 
 func (h *podEventHandler) Generic(ctx context.Context, e event.GenericEvent, q workqueue.RateLimitingInterface) {
-	h.queueReconcileForPod(ctx, e.Object, q)
```
Comment (mimowo) [inline pkg/controller/jobs/pod/event_handlers.go:61]: Any reason to delete this?

Comment (alculquicondor) [reply pkg/controller/jobs/pod/event_handlers.go:61]: It's just useless

File: pkg/controller/jobs/pod/pod_controller.go [hunk 7]
```diff
@@ -721,12 +753,18 @@ func (p *Pod) cleanupExcessPods(ctx context.Context, c client.Client, totalCount
...
+				// We won't observe this cleanup in the event handler.
+				p.excessPodExpectations.ObservedUID(log, p.key, pod.UID)
 				return err
 			}
 		}
 		if pod.ObjectMeta.DeletionTimestamp.IsZero() {
 			log.V(3).Info("Deleting excess pod in group", "excessPod", klog.KObj(&pod))
-			return c.Delete(ctx, &pod)
+			if err := c.Delete(ctx, &pod); err != nil {
+				// We won't observe this cleanup in the event handler.
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller.go:764]: If we call Delete, we should expect to observe it. If the Delete call fails, then we won't observe it. The next reconcile will try to delete again.

File: pkg/controller/jobs/pod/event_handlers.go (hunk 6 above)
Comment (mimowo) [reply pkg/controller/jobs/pod/event_handlers.go:61]: sgtm

File: pkg/controller/jobs/pod/pod_controller_test.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller_test.go:2193]: sgtm

**Comment by alculquicondor** [comment]
/retest
Failure during building of the image, due to a temporary network problem.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller.go:764]: ah, ok this a little bit tricky and does not seem covered by unit tests currently. I think it would be nice to cover, possibly in a follow up. WDYT?

[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller.go:764]: I mean the scenario when the Delete fails, so we wait for expectations, then when we re-attempt deleting the same pod.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller.go:764]: If the Delete fails, we won't be waiting for expectations. This is a call to `ObservedUID`, not `ExpectUIDs`.

But yes, we can follow up with unit tests.

[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller.go:764]: Right, my mistake. sgtm

**Comment by mimowo** [comment]
I suggested a follow up to demonstrate the calls to `ObservedUID` are necessary and correct when there is an error for the Update or Delete operations: https://github.com/kubernetes-sigs/kueue/pull/1623#discussion_r1463639856
/lgtm
