### PR TITLE
Fix second pass entries outliving the workload delete

### LINKED ISSUE #5511: Deleted workload entry outlives cq in scheduler cache
As we see in this [log](https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5461/pull-kueue-test-integration-baseline-main/1930264942032719872/build-log.txt) and many examples in the #5395.

Workload `wl1` entry from test `Nodes are created before test with the hostname being the lowest level  should evict workload when multiple assigned nodes fail` outlives the test in the scheduler's cache.
That's because it was re-queued for second pass.
Thus it is still visible in test `Preemption is enabled within ClusterQueue  should preempt the low and mid priority workloads to fit the high-priority workload` in result it is considered as possible preemption for `wl2` causing preemption failure
```
  2025-06-04T14:11:53.966698632Z	ERROR	scheduler	scheduler/scheduler.go:271	Failed to preempt workloads	{"schedulingCycle": 167, "workload": {"name":"wl2","namespace":"tas-rjx27"}, "clusterQueue": {"name":"cluster-queue"}, "error": "workloads.kueue.x-k8s.io \"wl1\" not found"}
```
and blocking `wl2` from being admitted.

**What you expected to happen**:
Delete workloads don't get scheduled for second pass, if they do scheduler do not nominates them for preemption.

**How to reproduce it (as minimally and precisely as possible)**:
Here is the reproduction [PR](https://github.com/kubernetes-sigs/kueue/pull/5513)

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind flake 

#### Which issue(s) this PR fixes:

Fixes #5511

#### Special notes for your reviewer:

The issue is that the forgetWorkload called on the secondPassQueue would hit the void while the workload awaits for 1s [here](https://github.com/kubernetes-sigs/kueue/blob/d2f9f2efcd066f007930e9f04fe7629ed8983a0a/pkg/queue/manager.go#L793). Now we prequeue such a workload, and if forgetWorkload is called in the meanwhile, then "enqueue" is forgotten either.

Adding a reliably reproducing integration test is tricky. Running the test https://github.com/kubernetes-sigs/kueue/pull/5513 in a loop reproduces in consistently, but requires multiple many repeats.

To prove the fix works:
- I ran the CI build, with commit https://github.com/kubernetes-sigs/kueue/pull/5587/commits/418b65e2b5fe12fed7c5125cccad3be629d9cb3a, and it passed [here]( https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5587/pull-kueue-test-integration-baseline-main/1932086255051345920)
- I ran it locally looped >100 times and it passed consistently
- I revert the mitigation: https://github.com/kubernetes-sigs/kueue/pull/5461. Before the mitigation it was failing pretty often.
- I add unit tests

#### Does this PR introduce a user-facing change?

```release-note
TAS: fix the scenario when deleted workload still lives in the cache.
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @PBundyra

**Comment by mimowo** [comment]
/assign @PBundyra 
cc @tenzen-y 
/cherry-pick release-0.12

File: test/integration/singlecluster/tas/tas_test.go
Comment (PBundyra) [inline test/integration/singlecluster/tas/tas_test.go:1]: Can we be consistent with the name changes and stick with either `cq` or `cluster-queue`

**Comment by PBundyra** [comment]
/lgtm
/hold
Feel free to unhold if you address the nit

File: test/integration/singlecluster/tas/tas_test.go
Comment (mimowo) [reply test/integration/singlecluster/tas/tas_test.go:1]: Well, in this commit I just blindly reverted the mitigation PR. I'm not clear what is the benefit of consistent naming. Detecting flakes is maybe a benefit, otoh tracing the logs becomes harder. From the perspective of being able to trace the logs I would even say using "GenerateName" is better.

In any case we are not consistent at all in a bigger picture, so I would keep it out of scope, and recommend opening issue if you feel it is the right direction:

image

File: pkg/queue/manager_test.go [hunk 1]
```diff
@@ -1285,3 +1287,102 @@ func TestGetPendingWorkloadsInfo(t *testing.T) {
...
 	}
 }
+
+func TestQueueSecondPassIfNeeded(t *testing.T) {
+	now := time.Now()
+
+	scheme := runtime.NewScheme()
+	if err := kueue.AddToScheme(scheme); err != nil {
+		t.Fatalf("Failed adding kueue scheme: %s", err)
+	}
```
Comment (tenzen-y) [inline pkg/queue/manager_test.go]: Why do we need this? Doesn't `utiltesting.NewFakeClient()` perform the same thing?

File: pkg/queue/manager_test.go [hunk 2]
```diff
@@ -1285,3 +1287,102 @@ func TestGetPendingWorkloadsInfo(t *testing.T) {
...
+			passTime: time.Second,
+		},
+		"two queued workloads, one deleted in the meanwhile": {
+			workloads: []*kueue.Workload{
+				baseWorkloadNeedingSecondPass.DeepCopy(),
+				func() *kueue.Workload {
+					wl := baseWorkloadNeedingSecondPass.DeepCopy()
+					wl.Name = "second"
+					return wl
+				}(),
```
Comment (tenzen-y) [inline pkg/queue/manager_test.go]: Let's use `Clone` instead of anonymous func.

File: pkg/queue/manager_test.go (hunk 1 above)
Comment (mimowo) [reply pkg/queue/manager_test.go]: I just copy-pasted from another test, let me try if I can drop.

Comment (mimowo) [reply pkg/queue/manager_test.go]: Done, dropped and it works, maybe we could also clean it in other places as a follow up

File: pkg/queue/manager_test.go (hunk 2 above)
Comment (mimowo) [reply pkg/queue/manager_test.go]: Done

File: pkg/queue/manager_test.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/queue/manager_test.go]: SGTM, feel free to open it.

**Review by tenzen-y — COMMENTED** [review]
Thank you
/lgtm
/approve

If you believe that you already got agreement with @PBundyra, feel free to merge this one.

**Comment by mimowo** [comment]
/unhold
I synced with @PBundyra that we don't need to align the CQ names in the PR

File: pkg/queue/manager_test.go (hunk 1 above)
Comment (mimowo) [reply pkg/queue/manager_test.go]: https://github.com/kubernetes-sigs/kueue/issues/5601
