### PR TITLE
[release-0.6] WaitForPodsReady: Reset .status.requeueState once the workload is deactivated

### LINKED ISSUE #2174: WaitForPodsReady: After a Workload is deactivated by exceeded the backoffLimit, the reactivated Workload could be immediately re-deactivated
**What happened**:

After the Workload is deactivated with `.spec.active=false` by exceeded re-queueing backoffLimit, if we manually reactivate it with `.spec.active=true`, it is immediately re-deactivated.

The root cause is the race condition between the workload-controller and kueue-scheduler by not resetting the `.status.requeueState.count` in the Workload while deactivating the Workload here: https://github.com/kubernetes-sigs/kueue/blob/0f0a315fe11704ee85bdc72fdc7f46d76d935a8e/pkg/controller/core/workload_controller.go#L196-L206.

So, the kueue-scheduler could pop the reactivated Workload from the queue before the `.status.requeueState.count` in the Workload here: https://github.com/kubernetes-sigs/kueue/blob/0f0a315fe11704ee85bdc72fdc7f46d76d935a8e/pkg/controller/core/workload_controller.go#L166-L170

Not resetting the `status.requeueState.count` is the intended behavior to notify users how many times the Job was requeued.
But, to avoid this race condition, we need to reset the `count` while deactivating the Workload.

**What you expected to happen**:
The reactivated Workload should be tried to re-queue until backoffLimit.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
If the Workload is deactivated, the workload resets the requeueState to avoid a race condition between the kueue-scheduler and the workload controller in the case of the deactivated workload.

When the workload is deactivated by exceeding the backoffLimitCount, the workload is added `The workload is deactivated due to exceeding the maximum number of re-queuing retries`. I will introduce a dedicated reason in another PR to focus on fixing the bug.

#### Which issue(s) this PR fixes:

Fixes #2174

#### Special notes for your reviewer:
This PR is cherry-pick of #2219

The primary difference from #2219 is the criteria to deduce that the Workload is deactivated due to exceeding the backoffLimitCount.

In the v0.7 implementation, the deactivated workload doesn't have the `.status.requeuesState.requeueAt` since the `requeueAt` should be reset when the workload was requeued (`Requeued=true` condition).

```go
// The deactivation reason could be deduced as the maximum number of re-queuing retries if the workload met all criteria below:
//  1. The waitForPodsReady feature is enabled, which means that it has "PodsReady" condition.
//  2. The workload has already exceeded the PodsReadyTimeout.
//  3. The workload already has been re-queued previously, which means it doesn't have the requeueAt field.
//  4. The number of re-queued has already reached the waitForPodsReady.requeuingBackoffLimitCount.
```

But, in the v0.6 implementation, an empty `requeueAt` is dropped from the criteria since we never reset the `requeueAt` and `Requeued` condition, a new feature for the v0.7.

```go
// The deactivation reason could be deduced as the maximum number of re-queuing retries if the workload met all criteria below:
//  1. The waitForPodsReady feature is enabled, which means that it has "PodsReady" condition.
//  2. The workload has already exceeded the PodsReadyTimeout.
//  3. The number of re-queued has already reached the waitForPodsReady.requeuingBackoffLimitCount.
```

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug that causes the reactivated Workload to be immediately deactivated even though it doesn't exceed the backoffLimit.
```

### CODE REVIEW

File: pkg/controller/core/workload_controller_test.go [hunk 1]
```diff
@@ -527,6 +527,17 @@ func TestReconcile(t *testing.T) {
...
+		// but we already verified this case in the integration test.
+		//"deactivated workload": {
+		//	workload: utiltesting.MakeWorkload("wl", "ns").
+		//		Active(false).
+		//		RequeueState(ptr.To[int32](1), ptr.To(metav1.NewTime(testStartTime.Add(1*time.Second).Truncate(time.Second)))).
+		//		Obj(),
+		//	wantWorkload: utiltesting.MakeWorkload("wl", "ns").
+		//		Active(false).
+		//		Obj(),
+		//},
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller_test.go:540]: This test didn't work well for the same reason: https://github.com/kubernetes-sigs/kueue/pull/2063/files#r1589119722.

**Comment by alculquicondor** [comment]
still WIP?

**Comment by tenzen-y** [comment]
> still WIP?

@alculquicondor This PR is ready for review right now. 
PTAL.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
