### PR TITLE
test(tas): wait for TrainingRuntime visibility before creating TrainJob

### LINKED ISSUE #9504: Flaky E2E test: TopologyAwareScheduling for TrainJob when Creating a TrainJob Should place pods in podset slices with two-level scheduling based on the ranks-ordering
**Which test is flaking?**:

End To End TAS Suite: kindest/node:v1.35.0: [It] TopologyAwareScheduling for TrainJob when Creating a TrainJob Should place pods in podset slices with two-level scheduling based on the ranks-ordering 

**Link to failed CI job or steps to reproduce locally**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9501/pull-kueue-test-e2e-tas-release-0-16/2026834045899378688

**Failure message or logs**:

```shell
{Expected success, but got an error:
    <*errors.StatusError | 0xc00029ae60>: 
    admission webhook "vtrainjob.kb.io" denied the request: runtime 'test-trainingruntime' not found
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "admission webhook \"vtrainjob.kb.io\" denied the request: runtime 'test-trainingruntime' not found",
            Reason: "Forbidden",
            Details: nil,
            Code: 403,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc00029ae60>: 
    admission webhook "vtrainjob.kb.io" denied the request: runtime 'test-trainingruntime' not found
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "admission webhook \"vtrainjob.kb.io\" denied the request: runtime 'test-trainingruntime' not found",
            Reason: "Forbidden",
            Details: nil,
            Code: 403,
        },
    }
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/tas/trainjob_test.go:190 @ 02/26/26 01:57:04.824
}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by Sebastianhayashi**
Fixes #9504.

## Summary
This addresses a flake in the TrainJob TAS e2e flow where `TrainJob` creation can be rejected with:

- `admission webhook "vtrainjob.kb.io" denied the request: runtime 'test-trainingruntime' not found`

The test creates `TrainingRuntime` and immediately creates `TrainJob`. On slower CI, the webhook cache may not observe the runtime yet.

## Change
- Add an `Eventually` check after creating `TrainingRuntime` and before creating `TrainJob`, waiting until `Get` can read the runtime from cache.
- Applied consistently across the relevant TrainJob TAS scenarios in `test/e2e/tas/trainjob_test.go`.

## Why this is safe
- Test-only change.
- Does not weaken the test objective; it enforces expected object visibility before dependent creation.

## Evidence
- Failing signal: intermittent `runtime not found` admission rejection in focused TAS test.
- Focused passing verification captured in the evidence bundle.

## Notes
I cannot run full Go e2e in this shell due environment constraints; CI should validate behavior.

```release-note
NONE
```

### CODE REVIEW

**Comment by Sebastianhayashi** [comment]
> Thank you for the PR! Just quick FYI: don't drop the release-note section with NONE from the PR descirption, because it is read by the robot (I added it back here manually)

Gotcha!

File: test/e2e/tas/trainjob_test.go [hunk 1]
```diff
@@ -115,6 +115,12 @@ var _ = ginkgo.Describe("TopologyAwareScheduling for TrainJob", func() {
 				Obj()
 
 			util.MustCreate(ctx, k8sClient, trainingRuntime)
+			ginkgo.By("waiting for trainingRuntime to be available in cache", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					got := &kftrainer.TrainingRuntime{}
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(trainingRuntime), got)).To(gomega.Succeed())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
```
Comment (mimowo) [inline test/e2e/tas/trainjob_test.go]: This will not always help - it only checks the TrainingRuntime is inside the cache of the test's client. However, it may still not be in the cache of the TrainJob's informer / client.

So, I think the better approach will be to wrap the `util.MustCreate(ctx, k8sClient, trainjob)` in Eventually, and explain in a comment that sometimes the request is rejected by the webhook's if the TrainingRunitime is not yet seen by the webhook client's cache.

Comment (mimowo) [reply test/e2e/tas/trainjob_test.go]: Same in other palces. Consider introducing a helper function for that like `createTrainJobWithRetry ` used locally only

Comment (Sebastianhayashi) [reply test/e2e/tas/trainjob_test.go]: I see

I updated the PR to retry TrainJob creation itself via a local `createTrainJobWithRetry` helper and applied it across the relevant places.

File: test/e2e/tas/trainjob_test.go [hunk 2]
```diff
@@ -312,3 +313,11 @@ func readRankAssignmentsFromTrainJobPods(pods []corev1.Pod) map[string]string {
 	}
 	return assignment
 }
+
+func createTrainJobWithRetry(ctx context.Context, c client.Client, trainJob *kftrainer.TrainJob) {
```
Comment (mimowo) [inline test/e2e/tas/trainjob_test.go:317]: We may generalize this in a follow up to fix the analogous issue: https://github.com/kubernetes-sigs/kueue/issues/9609

Maybe just `util.MustCreateWithRetry` cc @falconlee236
