### PR TITLE
Asynchronous Inadmissible Workload Requeueing

### LINKED ISSUE #8095: Reduce amount of apiserver writes on workloads that didn't admit.
**What happened**:

Too many api server writes cause slow admission processing on best effort queues with heterogenous CQ (for example containig workloads both requiring and not requiing gpus and corresponding RF with and without GPUs)

**What you expected to happen**:

Fast processing and admission.

**How to reproduce it (as minimally and precisely as possible)**:

Create large number of CPU and GPU workloads queuing in CQ with 2 RF - one with GPU, one without. Stucked GPU workloads slow down CPU workloads processing.

cc: @mimowo

### PR DESCRIPTION
**Pull request by gabesaba**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We decouple requesting inadmissible workloads to be reprocessed,
from the processing of these requests where we move the workloads.

This has a few main advantages
1) Allows batching requeues, avoiding the starvation noted [here](https://github.com/kubernetes-sigs/kueue/issues/8095#issuecomment-3860607333)
2) Reduces lock contention
3) Avoid spamming requeues 20+ times per second.

We accomplish this by defining the `inadmissibleWorkloadRequeuer`,
which implements the `requeueInadmissibleListener` interface.

Any requests to requeue inadmisisble workloads must go through this interface.
Then, the requeuer will process these requests in batches. The requeuer
deduplicates requests to the same ClusterQueue/Root Cohort, further reducing
duplicate reprocessing.

#### Which issue(s) this PR fixes:
Fixes #8095

#### Special notes for your reviewer:
* one preparatory PR merges this diff will be smaller #9224,
* see note in 9224 about exporting these test factories #9224
* see comment about eventCh buffering - need some feedback here

#### Does this PR introduce a user-facing change?
```release-note
Scheduling: Fix the bug where inadmissible workloads would be re-queued too frequently at scale.
This resulted in excessive processing, lock contention, and starvation of workloads deeper in the queue.
The fix is to throttle the process with a batch period of 1s per CQ or Cohort.
```

### CODE REVIEW

**Comment by gabesaba** [comment]
@sohankunkerkar, can you drive this review please?

File: pkg/cache/queue/inadmissible_workloads.go [hunk 1]
```diff
@@ -152,38 +171,103 @@ func queueInadmissibleWorkloads(ctx context.Context, c *ClusterQueue, client cli
...
+func (r *inadmissibleWorkloadRequeuer) Delete(context.Context, event.TypedDeleteEvent[requeueRequest], workqueue.TypedRateLimitingInterface[requeueRequest]) {
+}
+func (r *inadmissibleWorkloadRequeuer) Generic(_ context.Context, e event.TypedGenericEvent[requeueRequest], q workqueue.TypedRateLimitingInterface[requeueRequest]) {
+	q.AddAfter(e.Object, r.batchPeriod)
+}
+
+func (r *inadmissibleWorkloadRequeuer) setupWithManager(mgr ctrl.Manager) error {
+	return builder.TypedControllerManagedBy[requeueRequest](mgr).
+		Named("inadmissible_workload_requeue_controller").
+		WatchesRawSource(source.TypedChannel(r.eventCh, &inadmissibleWorkloadRequeuer{})).
```
Comment (sohankunkerkar) [inline pkg/cache/queue/inadmissible_workloads.go]: `inadmissibleWorkloadRequeuer{}` is a zero-value instance and  its batchPeriod is 0. The Generic handler calls `q.AddAfter(e.Object, r.batchPeriod)`, and client-go's `AddAfter`  with duration <= 0 falls through to q.Add(item) immediately with no delay.
This means the 1s batch period defined [here](https://github.com/kubernetes-sigs/kueue/pull/9232/changes#diff-cf86fb9d0de4435aa26109145f6918dbf7830bb0e2cdc035729039e208d32a03R42) is never applied. Should this be r instead?

File: pkg/cache/queue/inadmissible_workloads.go [hunk 2]
```diff
@@ -152,38 +171,103 @@ func queueInadmissibleWorkloads(ctx context.Context, c *ClusterQueue, client cli
...
+}
+
+func newInadmissibleWorkloadReconciler(qManager *Manager) *inadmissibleWorkloadRequeuer {
+	return &inadmissibleWorkloadRequeuer{
+		qManager: qManager,
+		// note to reviewers: should this be a buffered channel? I imagine that
+		// q.AddAfter will process this so fast that it is not necessary.
+		// LLM review suggested this to derisk deadlock (during startup?), but I don't
+		// see this risk.
+		eventCh:     make(chan event.TypedGenericEvent[requeueRequest]),
```
Comment (sohankunkerkar) [inline pkg/cache/queue/inadmissible_workloads.go]: I looked at controller-runtime's `source.TypedChannel` internals  where syncLoop starts a goroutine that continuously reads from the user channel and writes to an internal 1024-buffered dst channel. Since all callers (`NotifyRetryInadmissible`, `notifyRetryInadmissibleWithoutLock`, `AddOrUpdateCohort`) are reconciler goroutines that only run after mgr.Start() has started the source. 

Even though unbuffered channel looks safe with current TypedChannel startup ordering. Still, for future DRA/WAS/TAS growth, should we prefer a small bounded buffer here as the default resilience pattern for internal event fan-in? We still keep dedup semantics in AddAfter with keyed requeueRequest.

File: pkg/cache/queue/inadmissible_workloads.go [hunk 3]
```diff
@@ -152,38 +171,103 @@ func queueInadmissibleWorkloads(ctx context.Context, c *ClusterQueue, client cli
...
+	notifyCohort(cohortName kueue.CohortReference)
+}
+
+type requeueRequest struct {
+	ClusterQueue kueue.ClusterQueueReference
+	Cohort       kueue.CohortReference
+}
+
+// inadmissibleWorkloadRequeuer is responsible for receiving notifications,
+// and requeuering workloads as a result of these notifications.
```
Comment (sohankunkerkar) [inline pkg/cache/queue/inadmissible_workloads.go]: `s/requeuering/requeuing/g`

File: pkg/cache/queue/manager.go [hunk 4]
```diff
@@ -298,20 +313,10 @@ func (m *Manager) AddClusterQueue(ctx context.Context, cq *kueue.ClusterQueue) e
...
-			if qImpl != nil {
-				m.reportLQPendingWorkloads(qImpl)
-			}
-		}
-	}
+	notifyRetryInadmissibleWithoutLock(m, sets.New(cqImpl.name))
+	reportMetrics(m, cqImpl.name)
 
-	if queued || addedWorkloads {
+	if addedWorkloads {
```
Comment (sohankunkerkar) [inline pkg/cache/queue/manager.go:301]: I assume this is the intentional tradeoff for batching?
This is fine if intentional, but worth explicitly documenting as throughput-over-latency tradeoff.

File: pkg/cache/queue/inadmissible_workloads.go [hunk 5]
```diff
@@ -73,50 +84,57 @@ func (iw *inadmissibleWorkloads) replaceAll(newMap inadmissibleWorkloads) {
...
-// moved, it returns false.
+// requeueWorkloadsCohort moves all inadmissible
+// workloads in the Cohort tree. It expects to be
+// passed a root Cohort.
 //
-// WARNING: must hold a read-lock on the manager when calling,
-// or otherwise risk encountering an infinite loop if a Cohort
-// cycle is introduced.
-func requeueWorkloadsCohort(ctx context.Context, m *Manager, cohort *cohort) bool {
+// RequeueCohort moves all inadmissibleWorkloads in
```
Comment (sohankunkerkar) [inline pkg/cache/queue/inadmissible_workloads.go]: It looks like we can remove this information.

File: pkg/cache/queue/inadmissible_workloads.go [hunk 6]
```diff
@@ -152,38 +171,103 @@ func queueInadmissibleWorkloads(ctx context.Context, c *ClusterQueue, client cli
...
+
+// inadmissibleWorkloadRequeuer is responsible for receiving notifications,
+// and requeuering workloads as a result of these notifications.
+type inadmissibleWorkloadRequeuer struct {
+	qManager    *Manager
+	eventCh     chan event.TypedGenericEvent[requeueRequest]
+	batchPeriod time.Duration
+}
+
+func newInadmissibleWorkloadReconciler(qManager *Manager) *inadmissibleWorkloadRequeuer {
```
Comment (sohankunkerkar) [inline pkg/cache/queue/inadmissible_workloads.go]: The constructor says "Reconciler", type says "Requeuer". Pick one. Since the type is `inadmissibleWorkloadRequeuer`, the constructor should be `newInadmissibleWorkloadRequeuer`.

File: pkg/cache/queue/test_util.go [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+
+// NewManagerForUnitTests creates a new Manager for testing purposes.
+func NewManagerForUnitTests(client client.Client, checker StatusChecker, options ...Option) *Manager {
+	manager, _ := NewManagerForUnitTestsWithRequeuer(client, checker, options...)
+	return manager
+}
+
+// NewManagerForIntegrationTests is a factory for Integration Tests, setting the
+// batch period to a much lower value (requeueBatchPeriodIntegrationTests).
+func NewManagerForIntegrationTests(client client.Client, checker StatusChecker, options ...Option) *Manager {
```
Comment (mimowo) [inline pkg/cache/queue/test_util.go]: Do we really need the functions? I would argue against introducing such functions for testing. 

It is a cleaner pattern  to parametrize the value by passing the Options. Here you could expose a param like `BatchInterval`.

For example this is how controller-runtime exposes configuration for manager's RetryPeriod and other options.

File: pkg/cache/queue/test_util.go [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+	}
+	for cohortName := range w.cohorts {
+		requeueWorkloadsCohort(ctx, w.manager, cohortName)
+	}
+	w.cqs.Clear()
+	w.cohorts.Clear()
+}
+
+// NewManagerForUnitTestsWithRequeuer creates a new Manager for testing purposes, pre-configured with a testInadmissibleWorkloadRequeuer.
+func NewManagerForUnitTestsWithRequeuer(client client.Client, checker StatusChecker, options ...Option) (*Manager, *testInadmissibleWorkloadRequeuer) {
```
Comment (mimowo) [inline pkg/cache/queue/test_util.go]: For unit tests it is slightly more acceptable, but also I would argue against it. If we need to have a dedicated parametrization in unit tests we can use Options to the standard NewManager.

File: pkg/cache/queue/manager_test.go [hunk 9]
```diff
@@ -63,7 +63,7 @@ func TestAddLocalQueueOrphans(t *testing.T) {
 		utiltestingapi.MakeWorkload("f", "earth").Queue("foo").Finished().Obj(),
 		utiltestingapi.MakeWorkload("a", "moon").Queue("foo").Obj(),
 	)
-	manager := NewManager(kClient, nil)
+	manager := NewManagerForUnitTests(kClient, nil)
```
Comment (mimowo) [inline pkg/cache/queue/manager_test.go:66]: I don't like how the diff is bloated by this change. Rather than impacting all tests, can we introduce the new batch period behind a dedicated feature gate, and only add a set of dedicated tests?

File: pkg/cache/queue/inadmissible_workloads.go [hunk 10]
```diff
@@ -152,38 +171,103 @@ func queueInadmissibleWorkloads(ctx context.Context, c *ClusterQueue, client cli
...
 		if cq == nil {
 			continue
 		}
-		if cq.HasParent() && !hierarchy.HasCycle(cq.Parent()) {
-			rootName := cq.Parent().getRootUnsafe().GetName()
-			if processedRoots.Has(rootName) {
-				continue
-			}
-			processedRoots.Insert(rootName)
-		}
```
Comment (mimowo) [inline pkg/cache/queue/inadmissible_workloads.go:180]: Is it a drive-by cleanup, or something necessary for the PR?

File: pkg/cache/queue/inadmissible_workloads.go [hunk 11]
```diff
@@ -73,50 +84,57 @@ func (iw *inadmissibleWorkloads) replaceAll(newMap inadmissibleWorkloads) {
...
-	return requeueWorkloadsCohortSubtree(ctx, m, root)
 }
 
+// WARNING: must only be called (indirectly) by InadmissibleWorkloadRequeuer.
 func requeueWorkloadsCohortSubtree(ctx context.Context, m *Manager, cohort *cohort) bool {
 	queued := false
 	for _, clusterQueue := range cohort.ChildCQs() {
-		queued = queueInadmissibleWorkloads(ctx, clusterQueue, m.client) || queued
+		if queueInadmissibleWorkloads(ctx, clusterQueue, m.client) {
+			reportMetrics(m, clusterQueue.name)
```
Comment (mimowo) [inline pkg/cache/queue/inadmissible_workloads.go]: It doesn't seem if we called `reportMetrics` here before, and so the change looks unrelated. Was it a bug before, or this is some non-obvious drive-by cleanup or something really needed here now?

File: pkg/cache/queue/manager.go [hunk 12]
```diff
@@ -298,20 +313,10 @@ func (m *Manager) AddClusterQueue(ctx context.Context, cq *kueue.ClusterQueue) e
...
-	if features.Enabled(features.LocalQueueMetrics) {
-		for _, q := range queues.Items {
-			qImpl := m.localQueues[queue.Key(&q)]
-			if qImpl != nil {
-				m.reportLQPendingWorkloads(qImpl)
-			}
-		}
-	}
+	notifyRetryInadmissibleWithoutLock(m, sets.New(cqImpl.name))
+	reportMetrics(m, cqImpl.name)
```
Comment (mimowo) [inline pkg/cache/queue/manager.go]: same here, I'm not clear why the code about metrics reporting is changing now.

**Comment by mimowo** [comment]
Let me propose to rephrase with the clear prefix, and clearly clarification what is the batch period, feel free to adjust, but I wanted to emphasize the direction in communicating to end user.
/release-note-edit
```release-note
Scheduling: Fix the bug where inadmissible workloads would be re-queued too frequently at scale.
This resulted in excessive processing, lock contention, and starvation of workloads deeper in the queue.
The fix is to throttle the process with a batch period of 1s per CQ or Cohort.
```

File: pkg/cache/queue/test_util.go (hunk 8 above)
Comment (mimowo) [reply pkg/cache/queue/test_util.go]: For example, I'm wondering if we could pass clock when constructing the manager (might be optional parameter, real clock by default), and just move the clock by one second in unit tests. This aligns more with the current approach to time-based testing.

**Comment by mimowo** [comment]
LGTM overall, the main comments from me:
1. it would be better to see if we can eliminate the custom functions for Unit and Integration tests. I imagine in unit tests we could use a custom clock to trigger the Reconcile.
2. I'm wondering about a feature gate, but for 1s batching I'm leaning to think this is not needed. For larger delays like 5s. or 30s I would find this necessary, but we can consider it in the future.
3. The PR is already large and we are going to cherrypick, so offloaing the diff by prep PRs, like drive-by cleanups is preferred

File: pkg/cache/queue/inadmissible_workloads.go (hunk 11 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: Previously we were calling requeue, and then reporting metrics if anything was moved. Now that we decouple notifying requeue from the actual requeueing, we need to update metrics in the latter step.

File: pkg/cache/queue/inadmissible_workloads.go (hunk 10 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go:180]: Drive-by-cleanup. I (think) I can revert this, but later on this simplification makes sense, as we collapse keys in the requeuer and adds are cheap

File: pkg/cache/queue/inadmissible_workloads.go (hunk 2 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: Thanks for the analysis, and this sgtm. How does 128 sound to you?

File: pkg/cache/queue/inadmissible_workloads.go (hunk 1 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: Good catch, should definitely be r. I'll add an integration test to, to make sure we have this code under test.

File: pkg/cache/queue/manager_test.go (hunk 9 above)
Comment (gabesaba) [reply pkg/cache/queue/manager_test.go:66]: I created a prep PR, to reduce the diff: https://github.com/kubernetes-sigs/kueue/pull/9224

In the feature flag case, are you suggesting maintaining both branches - before and after decoupling request requeueing from processing requeueing?

File: pkg/cache/queue/test_util.go (hunk 8 above)
Comment (gabesaba) [reply pkg/cache/queue/test_util.go]: For the new controller to work, it needs to be wired with `ctrl.Manager`, and these requeues will be processed in a different go-routine. I don't think this is the right choice for unit tests.

File: pkg/cache/queue/manager.go (hunk 12 above)
Comment (gabesaba) [reply pkg/cache/queue/manager.go]: Same as https://github.com/kubernetes-sigs/kueue/pull/9232#discussion_r2812368472

File: pkg/cache/queue/test_util.go (hunk 7 above)
Comment (gabesaba) [reply pkg/cache/queue/test_util.go]: How about the options for NewManager, and then some factory that resides in the integration tests, that sets up integration tests with certain options (such as a smaller batching period)?

File: pkg/cache/queue/manager.go (hunk 4 above)
Comment (gabesaba) [reply pkg/cache/queue/manager.go:301]: Related to https://github.com/kubernetes-sigs/kueue/pull/9232#discussion_r2812368472. Broadcast wlil be a no-op until the workloads are moved. I add a broadcast call in `requeueWorkloadsCQ` and `requeueWorkloadsCohort`

File: pkg/cache/queue/inadmissible_workloads.go (hunk 5 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: Updated the comment, combining information from both parts

File: pkg/cache/queue/test_util.go (hunk 7 above)
Comment (mimowo) [reply pkg/cache/queue/test_util.go]: +1, yes generic NewManager in the production code, and NewManagerForIntegrationTests for the test packages sgtm

File: pkg/cache/queue/test_util.go (hunk 8 above)
Comment (mimowo) [reply pkg/cache/queue/test_util.go]: > For the new controller to work, it needs to be wired with ctrl.Manager, and these requeues will be processed in a different go-routine. I don't think this is the right choice for unit tests.

Hm, let me double check why you consider this is not the right choice? Actually, for unit tests it is great to be able to control the passage of time. Otherwise we risk flakes, this is why we tend to use fake clocks for most of our unit testing.

I remember this is what we do in the core k8s when using workqueues, just pass time and this triggers a goroutine inside the workqueue mechanics triggers the reconcile. So, I think what is needed is to call `NewControllerManagedBy` and customize the clock. 

Let me know if there are some issues why this is not valid approach. It is not a blocker for me, just feels like more natural, safer (to avoid flakes), and consistent with the rest of codebase.

File: pkg/cache/queue/inadmissible_workloads.go (hunk 10 above)
Comment (mimowo) [reply pkg/cache/queue/inadmissible_workloads.go:180]: Let's decouple to a PR.

File: pkg/cache/queue/inadmissible_workloads.go (hunk 11 above)
Comment (mimowo) [reply pkg/cache/queue/inadmissible_workloads.go]: sgtm, don't you mind just introducing `reportMetrics` in a prep?

File: pkg/cache/queue/manager.go (hunk 12 above)
Comment (mimowo) [reply pkg/cache/queue/manager.go]: sgtm, let's resolve this one.

File: pkg/cache/queue/manager_test.go (hunk 9 above)
Comment (mimowo) [reply pkg/cache/queue/manager_test.go:66]: > In the feature flag case, are you suggesting maintaining both branches - before and after decoupling request requeueing from processing requeueing?

Yeah, good question. I think the amount of changes looks scary for the PR to be safe without a FG. If we can bring it down to reviewable state by prep PRs, maybe we can drop the FG.

If we go with the FG approach I imagine it goes to Beta directly (enabled by default), and we only have a small portion of tests testing the FG disabled. Then we graduate the FG after 2 releases. Basically, we keep FG=false just as a bailout output when something goes wrong.

File: pkg/cache/queue/inadmissible_workloads.go (hunk 10 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go:180]: Ack. I will submit as a follow-up PR

File: pkg/cache/queue/inadmissible_workloads.go (hunk 11 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: https://github.com/kubernetes-sigs/kueue/pull/9295

Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: Renamed as `reportPendingWorkloads` in that PR

File: pkg/cache/queue/inadmissible_workloads.go (hunk 2 above)
Comment (sohankunkerkar) [reply pkg/cache/queue/inadmissible_workloads.go]: Yeah, that sounds good!

File: pkg/controller/core/resourceflavor_controller.go [hunk 13]
```diff
@@ -143,7 +143,7 @@ func (r *ResourceFlavorReconciler) Create(e event.TypedCreateEvent[*kueue.Resour
 	// As long as one clusterQueue becomes active,
 	// we should inform clusterQueue controller to broadcast the event.
 	if cqNames := r.cache.AddOrUpdateResourceFlavor(log, e.Object.DeepCopy()); len(cqNames) > 0 {
-		qcache.QueueInadmissibleWorkloads(context.Background(), r.qManager, cqNames)
+		qcache.NotifyRetryInadmissible(r.qManager, cqNames)
```
Comment (mimowo) [inline pkg/controller/core/resourceflavor_controller.go:146]: Nice to see these uses of Background context eliminated 👍

File: pkg/cache/queue/test_util.go (hunk 8 above)
Comment (gabesaba) [reply pkg/cache/queue/test_util.go]: This still requires setting up a controller-runtime `ctrl.Manager` in the unit tests, to call `NewControllerManagedBy` (or `TypedControllerManagedBy`). This seems to me deep in the territory of integration tests, especially since existing unit tests don't have a `ctrl.Manager`. Even if this were not required, we're relying on processing in go-routines and will require some syncronization to ensure the tests are not flaky. 

I think that this lightweight test object makes more sense for unit tests, and covering the behavior of the async controller should be handled in integration tests (to be expanded as per https://github.com/kubernetes-sigs/kueue/pull/9232#discussion_r2812433555)

Comment (mimowo) [reply pkg/cache/queue/test_util.go]: I can see this is a matter of taste. Indeed, spawning a goroutine is what we do in unit tests for in the k8s contorllers, for example [here](https://github.com/kubernetes/kubernetes/blob/7ed7104d27eab560edef041097970d97f3d85e6b/pkg/controller/job/job_controller_test.go#L6709). However, there it is a bit more lightweight as the basic workqueue is used, rather than the entire controller-runtime's manager.

> I think that this lightweight test object makes more sense for unit tests, and covering the behavior of the async controller should be handled in integration tests (to be expanded as per https://github.com/kubernetes-sigs/kueue/pull/9232#discussion_r2812433555)

Yes, but the drawback is leaking test-only functions into prod code (at least in the initial implementation), maybe this is solvable by other means.

In any case, I'm ok with the pattern as is, it is not a blocker, just something I wanted to explore as we go into the territory of using controller-runtime reconcilers for internal code.

I think taking a pause of how to do it well is time worth spent. I'm still a bit hesitant - even if you wire this all up now, there will be a learning curve for how to wire the stuff in the future. I think it might be introducing a complexity barrier for new developers in the community.  I basically though that reusing the controller-runtime existing machinery will make the unit tests easier to write, but I'm not stubborn here. 

Let me know if you indeed considered the consequences and think this is better decision I'm ok with that.

File: pkg/cache/queue/inadmissible_workloads.go (hunk 11 above)
Comment (mimowo) [reply pkg/cache/queue/inadmissible_workloads.go]: Can be resolved now.

File: pkg/cache/queue/test_util.go (hunk 8 above)
Comment (gabesaba) [reply pkg/cache/queue/test_util.go]: https://github.com/kubernetes-sigs/kueue/pull/9321

**Comment by mimowo** [comment]
https://github.com/kubernetes-sigs/kueue/pull/9346 inspred me to ask - lets run all integration tests using batching of 100ms or so. Maybe this can uncover more changes like that

**Comment by mimowo** [comment]
LGTM overall, Leaving the reminder of the review to @sohankunkerkar

**Comment by sohankunkerkar** [comment]
@gabesaba could you rebase on top of the main branch? I will do one final review after that. Also, resolve the comments which are already addressed. It would be really helpful to see some performance numbers with this change. Thanks!

**Comment by gabesaba** [comment]
> @gabesaba could you rebase on top of the main branch? I will do one final review after that. Also, resolve the comments which are already addressed. It would be really helpful to see some performance numbers with this change. Thanks!

Sounds good, I'll ping when it's ready. I'm still fighting with some flaky integration tests. Thanks for your patience!

**Comment by mimowo** [comment]
> Sounds good, I'll ping when it's ready. I'm still fighting with some flaky integration tests. Thanks for your patience!

Is that addressed now?

File: pkg/cache/queue/inadmissible_workloads.go [hunk 14]
```diff
@@ -73,50 +84,57 @@ func (iw *inadmissibleWorkloads) replaceAll(newMap inadmissibleWorkloads) {
...
 }
 
+// WARNING: must only be called (indirectly) by InadmissibleWorkloadRequeuer.
 func requeueWorkloadsCohortSubtree(ctx context.Context, m *Manager, cohort *cohort) bool {
 	queued := false
 	for _, clusterQueue := range cohort.ChildCQs() {
-		queued = queueInadmissibleWorkloads(ctx, clusterQueue, m.client) || queued
+		if queueInadmissibleWorkloads(ctx, clusterQueue, m.client) {
+			reportPendingWorkloads(m, clusterQueue.name)
+			queued = true
```
Comment (mimowo) [inline pkg/cache/queue/inadmissible_workloads.go]: I would like to extend the information to surface the number of workloads re-queued. This will help to understand how much backlog builds in the 1s period, to get some feeling how much is too much, because I expect it might be not the last time we are thinking about this problem. 

It might be a small follow up PR to de-couple the added complexity. wdyt @sohankunkerkar @gabesaba ?

File: pkg/cache/queue/inadmissible_workloads.go (hunk 1 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: Added new integration tests `Requeueing Inadmissible Workloads`, and validated that this test fails with the 0ms value, and before this change.

File: pkg/cache/queue/inadmissible_workloads.go (hunk 14 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: Yes, I will add this as a follow-up after this merges.

**Comment by gabesaba** [comment]
> Sounds good, I'll ping when it's ready. I'm still fighting with some flaky integration tests. Thanks for your patience!


Ready for review @sohankunkerkar.

> It would be really helpful to see some performance numbers with this change. Thanks!

I don't have cycles to do a proper performance test of this feature, but I will provide some numbers about the number of requeue log lines printed before/after the change for the integ/e2e suites, as a proxy to see how the collapsing is happening

File: pkg/cache/queue/inadmissible_workloads.go [hunk 15]
```diff
@@ -152,38 +171,120 @@ func queueInadmissibleWorkloads(ctx context.Context, c *ClusterQueue, client cli
...
+	setManager(manager *Manager)
+}
+
+type requeueRequest struct {
+	ClusterQueue kueue.ClusterQueueReference
+	Cohort       kueue.CohortReference
+}
+
+// controllerRequeuer satisfies the inadmissibleRequeuer
+// interface, implemented via a controller-runtime
```
Comment (sohankunkerkar) [inline pkg/cache/queue/inadmissible_workloads.go]: Thinking a bit deeper about this, have you considered using a raw `workqueue.TypedDelayingQueue` instead of wrapping it in a controller-runtime controller? The only functionality needed here is deduplication and AddAfter, both of which are provided directly by the delaying queue. AddAfter is goroutine-safe as well, so callers can invoke it while holding locks without risking blocking.

IMO, the controller-runtime layer actually adds extra indirection: a channel, event-handler boilerplate (with empty methods), a source.TypedChannel bridge, and a type assertion in SetupControllers, just to enqueue items. 

Since there’s no Kubernetes API object being reconciled and this is a purely internal debounced operation, a Runnable registered via mgr.Add() would provide the same lifecycle management without the additional complexity.

File: pkg/cache/queue/inadmissible_workloads.go [hunk 16]
```diff
@@ -152,38 +171,120 @@ func queueInadmissibleWorkloads(ctx context.Context, c *ClusterQueue, client cli
...
 	// Track processed cohort roots to avoid requeuing the same hierarchy
 	// multiple times when multiple CQs in cqNames share a root.
 	processedRoots := sets.New[kueue.CohortReference]()
-	var queued bool
 	for name := range cqNames {
 		cq := m.hm.ClusterQueue(name)
 		if cq == nil {
 			continue
 		}
+		if !cq.HasParent() {
```
Comment (sohankunkerkar) [inline pkg/cache/queue/inadmissible_workloads.go:192]: Nit: These conditions are mutually exclusive. A CQ either has a parent or it doesn't. `if/else if` makes that obvious and drops the redundant `HasParent()` check. Also, when `HasParent()` is true but there is a cycle, neither branch fires and workloads silently stay inadmissible. That matches the old behavior, but a comment would help future readers understand the skip is intentional.
```go
 if !cq.HasParent() {                                                                                                                            
      m.requeuer.notifyClusterQueue(cq.name)                                                                                                      
  } else if !hierarchy.HasCycle(cq.Parent()) {                                                                                                    
      rootName := cq.Parent().getRootUnsafe().GetName()                                                                                           
      if processedRoots.Has(rootName) {                                                                                                           
          continue                                                                                                                                
      }
      m.requeuer.notifyCohort(rootName)
      processedRoots.Insert(rootName)
  }
```

File: pkg/cache/queue/manager.go [hunk 17]
```diff
@@ -316,7 +340,10 @@ func (m *Manager) UpdateClusterQueue(ctx context.Context, cq *kueue.ClusterQueue
 
 	// TODO(#8): Selectively move workloads based on the exact event.
 	// If any workload becomes admissible or the queue becomes active.
-	if (specUpdated && requeueWorkloadsCQ(ctx, m, cqImpl)) || (!oldActive && cqImpl.Active()) {
+	if specUpdated {
```
Comment (sohankunkerkar) [inline pkg/cache/queue/manager.go:326]: `Broadcast()` on the spec-update path is now deferred to the async reconcile. Worth a short comment here so it doesn't look like an accidental omission.

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go [hunk 18]
```diff
@@ -868,7 +869,15 @@ var _ = ginkgo.Describe("Scheduler", ginkgo.Label("feature:fairsharing"), func()
...
 			ginkgo.By("Create admissible workload in queue1")
-			createWorkloadWithPriority("cq1", "3", 99)
+			highPriorityWl := createWorkloadWithPriority("cq1", "3", 99)
+
+			ginkgo.By("Wait until scheduler attempts to schedule priority=99 wl")
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(highPriorityWl), highPriorityWl)).To(gomega.Succeed())
+				cond := meta.FindStatusCondition(highPriorityWl.Status.Conditions, kueue.WorkloadQuotaReserved)
+				g.Expect(cond).NotTo(gomega.BeNil())
+				g.Expect(cond.Message).To(gomega.ContainSubstring("insufficient unused quota"))
```
Comment (sohankunkerkar) [inline test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:879]: This line checks for "insufficient unused quota". [Line 904](https://github.com/kubernetes-sigs/kueue/pull/9232/changes#diff-03b8fcadabe2fe0e35d1e1d7d9a56d259b3673a457d895f94e2418525c2a1081R904) checks for "insufficient quota". The second is a substring of the first. I suspect if the condition message hasn't changed between the two waits, the second Eventually succeeds immediately on the stale condition without actually waiting for the scheduler to re-evaluate after the cohort update. If the intent is to observe a new evaluation, check for a more specific message or verify that `LastTransitionTime` has changed

File: pkg/cache/queue/inadmissible_workloads.go (hunk 16 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go:192]: Thanks, and updated! I had previously considered the else if, but I was on the fence whether it was easier to read that, vs explicitly see the condition spelled out (HasParent && !HasCycle).

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go (hunk 18 above)
Comment (gabesaba) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:879]: The 2nd is a subsequence, rather than substring, so it works :). I was considering pulling this out to a test library, so it is more readable/understandable, but it seems premature right now with just one usage

These map to these two statuses:
1) NoFit https://github.com/kubernetes-sigs/kueue/blob/9285880dcacdb378d23f863ff10e5c43e9f12522/pkg/scheduler/flavorassigner/flavorassigner.go#L1006
2) Preempt https://github.com/kubernetes-sigs/kueue/blob/9285880dcacdb378d23f863ff10e5c43e9f12522/pkg/scheduler/flavorassigner/flavorassigner.go#L1018

File: pkg/cache/queue/inadmissible_workloads.go (hunk 15 above)
Comment (gabesaba) [reply pkg/cache/queue/inadmissible_workloads.go]: Done. And thank you, I think this version is much better :)

**Comment by gabesaba** [comment]
> I don't have cycles to do a proper performance test of this feature, but I will provide some numbers about the number of requeue log lines printed before/after the change for the integ/e2e suites, as a proxy to see how the collapsing is happening

https://github.com/kubernetes-sigs/kueue/blob/5d4002e99fbe7135ea7c85d82a927bad1a4b89f9/pkg/cache/queue/inadmissible_workloads.go#L137 Which is called for each ClusterQueue that is requeued

## Integ
**Before**

```
grep "Resetting the head of the ClusterQueue" integ_before.txt | wc -l
236
```
**After**

```
grep "Resetting the head of the ClusterQueue" integ_after.txt | wc -l
192
```

## E2E
**Before**

```
find ./bin/run-test-e2e-singlecluster-1.35.0/kind-worker/containers/ -name "*kueue*log" | xargs grep "Resetting the head" | wc -l
16
```
**After**

```
find ./bin/run-test-e2e-singlecluster-1.35.0/kind-worker/containers/ -name "*kueue*log" | xargs grep "Resetting the head" | wc -l
2
```

**Comment by mimowo** [comment]
@gabesaba one more sanity question: this 1s delay only affects workloads which need to "requeue" , ie. workloads which are freshly created will get admitted immediately without any delay (if quota allows), right?

Context: for some users even 1s delay for new workloads might be a bit problematic: https://kubernetes.slack.com/archives/C032ZE66A2X/p1772006708515269?thread_ts=1771747325.514489&cid=C032ZE66A2X

**Comment by mimowo** [comment]
These failures are likely relevant (I haven't seen them before flaking):
- https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9232/pull-kueue-test-integration-extended-main/2026341167074906112 
- https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9232/pull-kueue-test-e2e-main-1-32/2026341167251066880

I would assume some of the tests make assumptions which are no longer true with the asynchronous workload requeuing.

So please investigate / fix / adjust tests.

**Comment by gabesaba** [comment]
> @gabesaba one more sanity question: this 1s delay only affects workloads which need to "requeue" , ie. workloads which are freshly created will get admitted immediately without any delay (if quota allows), right?
> 
> Context: for some users even 1s delay for new workloads might be a bit problematic: https://kubernetes.slack.com/archives/C032ZE66A2X/p1772006708515269?thread_ts=1771747325.514489&cid=C032ZE66A2X

Correct.

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go (hunk 18 above)
Comment (sohankunkerkar) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:879]: ack, thanks!

**Comment by mimowo** [comment]
Yes the tests flaked on issues uncovered by this PR. Some of them are already merged so likely the retest will help

**Comment by mimowo** [comment]
looks neat to me as well. I consider it a serious performance bug at scale, lets cherrypick
/cherrypick release-0.16
/cherrypick release-0.15

**Comment by mimowo** [comment]
@sohankunkerkar leaving the lgtm to you, feel free to proceed when ready. 

Most likely the PR will ha e small conflicts so feel free tk contribute cherrypick PRs ( we are planning to release tomorrow so such a contribution will help us to meet the plan but dont worry about it if you are busy or unsure)

**Comment by gabesaba** [comment]
I accidently pushed the wip change implementing https://github.com/kubernetes-sigs/kueue/pull/9232#discussion_r2840448540, which wiped the lgtm @sohankunkerkar. My apologies. I rebased and pushed again
