### PR TITLE
Fix preemption expectations

### LINKED ISSUE #10181: Preemptions can get stuck on preemption expectations
**What happened**:

Preemptions can occassionally get stuck due to unsatisfied preemption expectations, see https://github.com/kubernetes-sigs/kueue/pull/10179

**What you expected to happen**:

* preemptions never get stuck on preemptionExpectations

**How to reproduce it (as minimally and precisely as possible)**:

test: https://github.com/kubernetes-sigs/kueue/pull/10179

**Anything else we need to know?**:

The root cause is that the workload_controller removes the expctations before the scheduler sees the Evicted=true condition. As a result scheduler may repeat the request, and repeat adding the preemptionExpectation. The repeated expectation is never removed because the victim workload has already transitioned to Evicted.

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?
/kind bug
/kind regression

#### Which issue(s) this PR fixes:

Fixes #10181

#### Does this PR introduce a user-facing change?

```release-note
Scheduling: fix the bug that scheduler could get stuck trying to preempt a workload due to the corruption of the
in-memory state tracking the pending preemptions (called preemptionExpectations).
```

### CODE REVIEW

File: cmd/kueue/main.go [hunk 1]
```diff
@@ -326,6 +326,8 @@ func main() {
 		os.Exit(1)
 	}
 
+	preemptionExpectations := preemptexpectations.New()
+	// queueOptions = append(queueOptions, qcache.WithPreemptionExpectations(preemptionExpectations))
```
Comment (mwielgus) [inline cmd/kueue/main.go]: Why this is commented out? Uncomment or remove.

File: pkg/cache/queue/manager.go [hunk 2]
```diff
@@ -564,6 +573,7 @@ func (m *Manager) AddOrUpdateWorkloadWithoutLock(log logr.Logger, w *kueue.Workl
 		return ErrClusterQueueDoesNotExist
 	}
 	cq.PushOrUpdate(wInfo)
+	m.preemptionExpectations.ObservedUID(log, client.ObjectKeyFromObject(w), w.UID)
```
Comment (mwielgus) [inline pkg/cache/queue/manager.go:579]: is it guaranteed that m.preemptionExpectations is not nil?

File: pkg/cache/queue/manager.go [hunk 3]
```diff
@@ -156,6 +163,8 @@ type Manager struct {
 	lqMetrics    *metrics.LocalQueueMetricsConfig
 
 	requeuer inadmissibleRequeuer
+
+	preemptionExpectations *expectations.Store
```
Comment (mwielgus) [inline pkg/cache/queue/manager.go:171]: Please add some documentation what is the intended use of this field.

File: pkg/controller/core/workload_controller.go [hunk 4]
```diff
@@ -1068,11 +1066,6 @@ func (r *WorkloadReconciler) Update(e event.TypedUpdateEvent[*kueue.Workload]) b
 	}
 	log.V(2).Info("Workload update event")
 
-	if workload.IsEvicted(e.ObjectNew) && !workload.IsEvicted(e.ObjectOld) {
```
Comment (mwielgus) [inline pkg/controller/core/workload_controller.go:1071]: Where is the tracking done now?

File: test/integration/singlecluster/scheduler/preemption_test.go [hunk 5]
```diff
@@ -237,6 +239,97 @@ var _ = ginkgo.Describe("Preemption", func() {
 			util.ExpectWorkloadsToBePending(ctx, k8sClient, wl4)
 		})
 
+		for i := range 20 {
```
Comment (mwielgus) [inline test/integration/singlecluster/scheduler/preemption_test.go]: Why 20?

Comment (mimowo) [reply test/integration/singlecluster/scheduler/preemption_test.go]: The test would only fail 1/2 of the time at the main branch. So repeating makes it more likely to catch the issue. I will remove the looping when ready to merge

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/core/workload_controller.go:1071]: Here: https://github.com/kubernetes-sigs/kueue/pull/10185/changes#diff-c7ed976ece2ea8cfd72847c76a214be5920b16aa7770e4d3cef7d8c974a36028R575
whenever we add it to the queue.

File: cmd/kueue/main.go (hunk 1 above)
Comment (mimowo) [reply cmd/kueue/main.go]: uncommented, this is important

File: pkg/cache/queue/manager.go (hunk 2 above)
Comment (mimowo) [reply pkg/cache/queue/manager.go:579]: In the production code it is non-nil because it is wired in main.go when creating the single instance of the queue manager, via [NewManager](https://github.com/kubernetes-sigs/kueue/blob/2a9f6f00cae15104197f2c4a5e592f755c188799/pkg/cache/queue/manager.go#L164).  After that the  queue manager is not changed.

However, it might be nil for the unit and integration tests which don't use it. Those tests which use the field started to fail so I had to plumb many of them.

File: test/integration/singlecluster/scheduler/preemption_test.go (hunk 5 above)
Comment (mimowo) [reply test/integration/singlecluster/scheduler/preemption_test.go]: Removed now

File: pkg/cache/queue/manager.go (hunk 3 above)
Comment (mimowo) [reply pkg/cache/queue/manager.go:171]: added a comment, ptal

File: cmd/experimental/kueue-populator/go.mod [hunk 6]
```diff
@@ -94,14 +95,16 @@ require (
...
-	sigs.k8s.io/lws v0.7.0 // indirect
+	sigs.k8s.io/lws v0.8.0 // indirect
 	sigs.k8s.io/randfill v1.0.0 // indirect
-	sigs.k8s.io/structured-merge-diff/v6 v6.3.1 // indirect
-	volcano.sh/apis v1.13.1-0.20251028070205-46d20c0699e7 // indirect
+	sigs.k8s.io/structured-merge-diff/v6 v6.3.2 // indirect
+	volcano.sh/apis v1.14.0 // indirect
 )
+
+replace sigs.k8s.io/kueue => ../../../
```
Comment (mimowo) [inline cmd/experimental/kueue-populator/go.mod:110]: This and the related changes are needed so that populator is compiled using the "local" version of Kueue. This is needed, because we change the code to setup the controllers, and the populator is setting up the controllers for integration tests. 

cc @PBundyra @sohankunkerkar

File: test/integration/singlecluster/controller/jobs/job/suite_test.go [hunk 7]
```diff
@@ -112,12 +112,14 @@ func managerAndControllersSetup(
 		lqMetrics := metrics.NewLocalQueueMetricsConfig(configuration.Metrics.LocalQueueMetrics)
 
 		cCache := schdcache.New(mgr.GetClient(), schdcache.WithLocalQueueMetrics(lqMetrics))
-		queues := util.NewManagerForIntegrationTests(ctx, mgr.GetClient(), cCache, qcache.WithLocalQueueMetrics(lqMetrics))
+		preemptionExpectations := preemptexpectations.New()
```
Comment (sohankunkerkar) [inline test/integration/singlecluster/controller/jobs/job/suite_test.go:115]: Since we dropped `qcache.WithLocalQueueMetrics(lqMetrics)` from the queue manager, does this break LQ metric reporting in DeleteLocalQueue and Requeue code paths?

File: test/integration/singlecluster/webhook/core/suite_test.go [hunk 8]
```diff
@@ -72,12 +73,14 @@ func managerSetup(ctx context.Context, mgr manager.Manager) {
 	gomega.Expect(err).NotTo(gomega.HaveOccurred())
 
 	cCache := schdcache.New(mgr.GetClient())
-	queues := util.NewManagerForIntegrationTests(ctx, mgr.GetClient(), cCache)
+	preemptexpectations := preemptexpectations.New()
```
Comment (sohankunkerkar) [inline test/integration/singlecluster/webhook/core/suite_test.go]: The variable `preemptexpectations` shadows the package alias `preemptexpectations`.

Comment (mimowo) [reply test/integration/singlecluster/webhook/core/suite_test.go]: fixed

File: test/integration/singlecluster/controller/jobs/job/suite_test.go (hunk 7 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/suite_test.go:115]: fixed

File: test/integration/singlecluster/scheduler/inadmissible/suite_test.go [hunk 9]
```diff
@@ -81,12 +82,14 @@ func managerAndSchedulerSetup(ctx context.Context, mgr manager.Manager) {
 	// Use a longer batch period so that
 	// requeue notifications are reliably collapsed in the test.
 	batchPeriod := 2 * time.Second
-	queues := util.NewManagerForIntegrationTestsWithBatchPeriod(ctx, mgr.GetClient(), cCache, batchPeriod)
+	preemptionExpectations := preemptexpectations.New()
```
Comment (sohankunkerkar) [inline test/integration/singlecluster/scheduler/inadmissible/suite_test.go:85]: Is this suite_test using the shared-store wiring as other setups?
The queue manager gets `qcache.WithPreemptionExpectations(preemptionExpectations)`, and controllers get the same `preemptionExpectations`, but the scheduler here is still created without scheduler.WithPreemptionExpectations(preemptionExpectations)

Comment (mimowo) [reply test/integration/singlecluster/scheduler/inadmissible/suite_test.go:85]: Indeed, I think this `preemptionExpectations` is nil for scheduler in this test suite, but it also was nil before so no regression here. Ideally we wire scheduler too, but we can do that when some tests in test/integration/singlecluster/scheduler/inadmissible/requeueing_test.go 
 start to require it.
