### PR TITLE
[Fix] Re-do mk admission after eviction in worker cluster

### LINKED ISSUE #8302: MultiKueue should redo the admission process once the workload looses Admission in the worker cluster
**What happened**:

Currently only the cluster that previously run the workload tries to readmit the workload.

**What you expected to happen**:

If a MK workload looses admission (due to preemption, node failure, etc), it should get back to the MK admission process and be attempted on multiple clusters.

**How to reproduce it (as minimally and precisely as possible)**:

Preempt MK workload at the worker cluster level.

**Anything else we need to know?**:

It is a generalization of #8089

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #8302

#### Does this PR introduce a user-facing change?

```release-note
MultiKueue: trigger workload eviction on the management cluster when the corresponding workload is evicted
on the remote worker cluster. In particular this is fixing the issue with workloads using ProvisioningRequests, 
which could get stuck in a worker cluster which does not have enough capacity to ever admit the workloads.
```

### CODE REVIEW

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 1]
```diff
@@ -349,22 +349,53 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+			if err := group.jobAdapter.SyncJob(ctx, w.client, remoteCl, group.controllerKey, group.local.Name, w.origin); err != nil {
+				log.Error(err, "Syncing remote controller object")
+				// We'll retry this in the next reconciling.
+				return reconcile.Result{}, err
+			}
+			return reconcile.Result{}, nil
+		}
+
+		// workload eviction on worker cluster
+		log.V(5).Info("Workload gets evicted in the remote cluster", "cluster", evictedRemote)
```
Comment (olekzabl) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Nit: this present tense feels slightly confusing; IIUC the workload already got evicted.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 2]
```diff
@@ -349,22 +349,53 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+		needsACUpdate := acs.State == kueue.CheckStateReady
+		if err := workload.PatchAdmissionStatus(ctx, w.client, group.local, w.clock, func(wl *kueue.Workload) (bool, error) {
+			if needsACUpdate {
+				acs.State = kueue.CheckStatePending
+				acs.Message = fmt.Sprintf("Workload evicted on worker cluster: %q, resetting for re-admission", *group.local.Status.ClusterName)
+				acs.LastTransitionTime = metav1.NewTime(w.clock.Now())
+				workload.SetAdmissionCheckState(&wl.Status.AdmissionChecks, *acs, w.clock)
+				wl.Status.ClusterName = nil
+				wl.Status.NominatedClusterNames = nil
```
Comment (olekzabl) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Out of curiosity - can this have an effect, given [this rule](https://github.com/kubernetes-sigs/kueue/blob/d872725a0e398e29c2ad5a0030a29afdd9ea9237/apis/kueue/v1beta2/workload_types.go#L567)?
(or is this intended to replace an empty list with `nil` in some edge cases?)

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 3]
```diff
@@ -349,22 +349,53 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
 			return reconcile.Result{}, err
 		}
 
-		// Wait for QuotaReserved=false in the local job.
+		if needsACUpdate {
+			w.recorder.Eventf(group.local, corev1.EventTypeNormal, "MultiKueue", acs.Message)
+		}
+
+		for cluster := range group.remotes {
+			if err := client.IgnoreNotFound(group.RemoveRemoteObjects(ctx, cluster)); err != nil {
```
Comment (olekzabl) [inline pkg/controller/admissionchecks/multikueue/workload.go]: In most cases, other calls to `RemoveRemoteObjects` in this file are followed by `group.remotes[cluster] = nil`.
Should it be done also here?

File: test/e2e/multikueue/e2e_test.go [hunk 4]
```diff
@@ -603,6 +604,93 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+			ginkgo.By("Checking that the workload is created and admitted in the manager cluster", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sManagerClient.Get(ctx, wlKey, managerWl)).To(gomega.Succeed())
+					g.Expect(workload.IsAdmitted(managerWl)).To(gomega.BeTrue())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			createdAtWorker := ""
+
+			ginkgo.By("Checking that the workload is created in one of the workers", func() {
```
Comment (olekzabl) [inline test/e2e/multikueue/e2e_test.go]: Below, you'll modify worker's CQ limits to manipulate what it can fit.
If so, how about using that trick once more, to get control over where the wl lands initially?

AFAICS the [initial CPU quotas](https://github.com/kubernetes-sigs/kueue/blob/c249417d0f385de9148eb45fea63ec4f51102212/test/e2e/multikueue/e2e_test.go#L152-L168) are: 2 at worker1 and 1 at worker2.
So if you set 1.5 for your workload, it'll certainly land on worker 1.
Then, you could swap the quotas (say, first set 2 at w2, then set 1 at w1) and verify if the workload moved to w2.

Compared to what you have now, +1 CQ update but -4 `if` blocks. (If I'm not mistaken).

File: test/e2e/multikueue/e2e_test.go [hunk 5]
```diff
@@ -603,6 +604,93 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+						g.Expect(k8sWorker2Client.Get(ctx, wlKey, workerWorkload)).To(gomega.Succeed())
+						g.Expect(workload.SetConditionAndUpdate(ctx, k8sWorker2Client, workerWorkload, kueue.WorkloadEvicted, metav1.ConditionTrue, kueue.WorkloadEvictedByPreemption, "By test", "evict", util.RealClock)).To(gomega.Succeed())
+					}, util.Timeout, util.Interval).Should(gomega.Succeed())
+				}
+			})
+
+			ginkgo.By("Checking that the workload is re-admitted in the other worker cluster", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sManagerClient.Get(ctx, wlKey, managerWl)).To(gomega.Succeed())
+					g.Expect(managerWl.Status.ClusterName).NotTo(gomega.HaveValue(gomega.Equal(createdAtWorker)))
```
Comment (olekzabl) [inline test/e2e/multikueue/e2e_test.go]: You could also check that it's not empty.

File: test/integration/multikueue/jobs_test.go [hunk 6]
```diff
@@ -1885,6 +1886,91 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
 			}, gomega.Equal(completedJobCondition))))
 		})
 	})
+	ginkgo.It("Should redo the admission process once the workload looses Admission in the worker cluster", func() {
```
Comment (olekzabl) [inline test/integration/multikueue/jobs_test.go]:
```suggestion
	ginkgo.It("Should redo the admission process once the workload loses Admission in the worker cluster", func() {
```

File: test/integration/multikueue/jobs_test.go [hunk 7]
```diff
@@ -1885,6 +1886,91 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
...
+				createdWorkload := &kueue.Workload{}
+				g.Expect(worker1TestCluster.client.Get(worker1TestCluster.ctx, wlLookupKey, createdWorkload)).To(gomega.Succeed())
+				g.Expect(workload.SetConditionAndUpdate(worker1TestCluster.ctx, worker1TestCluster.client, createdWorkload, kueue.WorkloadEvicted, metav1.ConditionTrue, kueue.WorkloadEvictedByPreemption, "By test", "evict", util.RealClock)).To(gomega.Succeed())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+		})
+
+		ginkgo.By("check manager's workload ClusterName reset", func() {
+			gomega.Eventually(func(g gomega.Gomega) {
+				managerWl := &kueue.Workload{}
+				g.Expect(managerTestCluster.client.Get(worker1TestCluster.ctx, wlLookupKey, managerWl)).To(gomega.Succeed())
```
Comment (olekzabl) [inline test/integration/multikueue/jobs_test.go]:
```suggestion
				g.Expect(managerTestCluster.client.Get(managerTestCluster.ctx, wlLookupKey, managerWl)).To(gomega.Succeed())
```

(or are there reasons to use the other context here?)

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 8]
```diff
@@ -349,22 +349,53 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+				// We'll retry this in the next reconciling.
+				return reconcile.Result{}, err
+			}
+			return reconcile.Result{}, nil
+		}
+
+		// workload eviction on worker cluster
+		log.V(5).Info("Workload gets evicted in the remote cluster", "cluster", evictedRemote)
+		needsACUpdate := acs.State == kueue.CheckStateReady
+		if err := workload.PatchAdmissionStatus(ctx, w.client, group.local, w.clock, func(wl *kueue.Workload) (bool, error) {
```
Comment (olekzabl) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Why would we do it when `needsACUpdate` is false?
(Currently, the update func does nothing in this case, but it still returns `true` - looks like we'd send an empty patch request to the apiserver?)

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 2 above)
Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/workload.go]: That's basically what we do when we evict using `resetClusterNomination`, but if that was empty already no need to do that.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 3 above)
Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/workload.go]: I see we are not that consistent with it, but sure let's add it

File: test/e2e/multikueue/e2e_test.go (hunk 4 above)
Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: Yes, that's sounds great, I will definitively go for that.
I was out of ideas how to get rid of this "if madness", somehow forgot about using CQ once more.
thank you!

File: test/integration/multikueue/jobs_test.go (hunk 7 above)
Comment (mszadkow) [reply test/integration/multikueue/jobs_test.go]: Copy-Paste syndrome ;)

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 8 above)
Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Yes, I see what you mean.
Actually moving needsACUpdate as update return val makes more sense

File: test/e2e/multikueue/e2e_test.go (hunk 5 above)
Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: Yes, but I want to check if it's given value, not any value

Comment (olekzabl) [reply test/e2e/multikueue/e2e_test.go]: Oh, I meant: check that it's distinct from `createdAtWorker` (as currently), _and_ that it's not empty.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 8 above)
Comment (olekzabl) [reply pkg/controller/admissionchecks/multikueue/workload.go]: I think it'd be still a bit clearer like this:
```go
needsACUpdate := ...
if needsACUpdate {
  if err := workload.PatchAdmissionStatus(..., func(wl *kueue.Workload) (bool, error) {
    ...
    return true, nil
  }); err != nil {
    ...
  }
}
```

Because in the current version, when `needsACUpdate` is false, we still enter the function, make some changes to `wl`, possibly non-trivial ones (e.g. I imagine we might be changing its status message), and then suddenly "give up" with `return needsACUpdate, nil`. The effect is as intended (no-op), but the way to it is a bit confusing.

WDYT?

Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Right, it might be little bit too complicated, sure.
Let's clarify this a bit.

File: test/e2e/multikueue/e2e_test.go (hunk 5 above)
Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: `createdAtWorker` was useful in previous version, I have removed it

Comment (olekzabl) [reply test/e2e/multikueue/e2e_test.go]: Oh, ok.

File: test/e2e/multikueue/e2e_test.go [hunk 9]
```diff
@@ -603,6 +604,75 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sWorker1Client.Get(ctx, wlKey, workerWorkload)).To(gomega.Succeed())
+					g.Expect(workload.SetConditionAndUpdate(ctx, k8sWorker1Client, workerWorkload, kueue.WorkloadEvicted, metav1.ConditionTrue, kueue.WorkloadEvictedByPreemption, "By test", "evict", util.RealClock)).To(gomega.Succeed())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Checking that the workload is re-admitted in worker2", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sManagerClient.Get(ctx, wlKey, managerWl)).To(gomega.Succeed())
+					g.Expect(managerWl.Status.ClusterName).NotTo(gomega.HaveValue(gomega.Equal("worker2")))
```
Comment (olekzabl) [inline test/e2e/multikueue/e2e_test.go]:
```suggestion
					g.Expect(managerWl.Status.ClusterName).To(gomega.HaveValue(gomega.Equal("worker2")))
```

(We want it to equal `worker2`, right? And I guess the test currently passes because the current expectation is satisfied _before_ the re-admission happens).

**Comment by mimowo** [comment]
I think this PR will also address https://github.com/kubernetes-sigs/kueue/issues/8089, right? if so then mark that in the issue description
cc @yaroslava-serdiuk

**Comment by mimowo** [comment]
LGTM overall 👍

**Comment by mimowo** [comment]
TBH, I would prefer to categorize this as a bug, because from user perspective the issues https://github.com/kubernetes-sigs/kueue/issues/8302 are https://github.com/kubernetes-sigs/kueue/issues/8089 are already problematic for using MK with ProvReq. If we cherrypick we could fix this user story in 0.15.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 3 above)
Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Added.

**Comment by mszadkow** [comment]
> I think this PR will also address #8089, right? if so then mark that in the issue description cc @yaroslava-serdiuk

I am not 100% sure it's addressing that, we check for evicted workloads, depending what is the symptoms of failing ProvisioningRequest.
I can check that with manual tests in GKE

**Comment by mimowo** [comment]
Thanks, this should work fine according to my understanding, but yes, please check.

We may also add a test for ProvReq specifically in a follow up.

**Comment by mimowo** [comment]
@mszadkow let me know about the results of your testing, but I think this should be actually fixing the ProvReq issue.
/release-note-edit
```release-note
MultiKueue: trigger workload eviction on the management cluster when the corresponding workload is evicted
on the worker remote cluster. In particular this is fixing the issue with workloads using ProvisioningRequests, 
which could get stuck in a worker clusters which does not have enough capacity to ever admit the workloads.
```

**Comment by mimowo** [comment]
/release-note-edit
```release-note
MultiKueue: trigger workload eviction on the management cluster when the corresponding workload is evicted
on the worker remote cluster. In particular this is fixing the issue with workloads using ProvisioningRequests, 
which could get stuck in a worker cluster which does not have enough capacity to ever admit the workloads.
```

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 10]
```diff
@@ -349,22 +349,53 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+				log.Error(err, "Syncing remote controller object")
+				// We'll retry this in the next reconciling.
+				return reconcile.Result{}, err
+			}
+			return reconcile.Result{}, nil
 		}
 
-		// Wait for QuotaReserved=false in the local job.
+		// workload evicted on worker cluster
+		log.V(5).Info("Workload was evicted in the remote cluster", "cluster", evictedRemote)
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/workload.go]:
```suggestion
		log.V(3).Info("Workload was evicted in the remote cluster", "cluster", evictedRemote)
```
This is quite a significant event, let's increase verbosity

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 11]
```diff
@@ -349,22 +349,53 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+		needsACUpdate := acs.State == kueue.CheckStateReady
+		if needsACUpdate {
+			if err := workload.PatchAdmissionStatus(ctx, w.client, group.local, w.clock, func(wl *kueue.Workload) (bool, error) {
+				acs.State = kueue.CheckStatePending
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Shouldn't we set retry here, and let the regular logic handle cleaning of the ClusterName and NominatedClusterNames? Maybe there are also other ACs which are already Ready. I think it is safer to go through full retry.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 12]
```diff
@@ -349,22 +349,53 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+				return true, nil
+			}); err != nil {
+				log.Error(err, "Failed to patch workload status")
+				return reconcile.Result{}, err
+			}
+
+			w.recorder.Eventf(group.local, corev1.EventTypeNormal, "MultiKueue", acs.Message)
+		}
+
+		for cluster := range group.remotes {
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Wouldn't this be handled by pre-existing code if we set the AC state as "Retry"?

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 11 above)
Comment (mimowo) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Then also the check above `needsACUpdate := acs.State == kueue.CheckStateReady` seems unnecessary

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 13]
```diff
@@ -349,22 +349,53 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+			}
+			return reconcile.Result{}, nil
 		}
 
-		// Wait for QuotaReserved=false in the local job.
+		// workload evicted on worker cluster
+		log.V(5).Info("Workload was evicted in the remote cluster", "cluster", evictedRemote)
+		needsACUpdate := acs.State == kueue.CheckStateReady
+		if needsACUpdate {
+			if err := workload.PatchAdmissionStatus(ctx, w.client, group.local, w.clock, func(wl *kueue.Workload) (bool, error) {
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/workload.go:375]: I think this is legitimate bugfix, especially for the ProvReq scenario, but it changes the pre-existing logic, which was underspecified in the KEP. I think it will be safer to have a feature gate like "MultiKueueRedoAdmissionOnEvictionInWorker". This will give us a bailout option in case someone is affected. If noone complains we just graduate in 0.18.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 12 above)
Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/workload.go]: It has the same effect, so let's stick to Retry

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 11 above)
Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Yes, Retry works even better, less code

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 12 above)
Comment (mimowo) [reply pkg/controller/admissionchecks/multikueue/workload.go]: maybe not exactly the same, because this way we will retry other AC too which I think is desired

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 14]
```diff
@@ -349,22 +349,47 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+				return reconcile.Result{}, err
+			}
+			return reconcile.Result{}, nil
+		}
+
+		// workload evicted on worker cluster
+		log.V(3).Info("Workload was evicted in the remote cluster", "cluster", evictedRemote)
+		if err := workload.PatchAdmissionStatus(ctx, w.client, group.local, w.clock, func(wl *kueue.Workload) (bool, error) {
+			acs.State = kueue.CheckStateRetry
+			acs.Message = fmt.Sprintf("Workload evicted on worker cluster: %q, resetting for re-admission", *group.local.Status.ClusterName)
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Please include in the message the previous state. Maybe add something like "...resetting for re-admission. Previously: Ready".

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 12 above)
Comment (mszadkow) [reply pkg/controller/admissionchecks/multikueue/workload.go]: I meant it has the same effect on remote clients, but yes we should reset it all AC too

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 15]
```diff
@@ -349,22 +349,39 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+		}
+
+		// workload evicted on worker cluster
+		log.V(3).Info("Workload was evicted in the remote cluster", "cluster", evictedRemote)
+		if err := workload.PatchAdmissionStatus(ctx, w.client, group.local, w.clock, func(wl *kueue.Workload) (bool, error) {
+			acs.Message = fmt.Sprintf("Workload evicted on worker cluster: %q, resetting for re-admission. Previously: %q", *group.local.Status.ClusterName, acs.State)
+			acs.State = kueue.CheckStateRetry
+			acs.LastTransitionTime = metav1.NewTime(w.clock.Now())
+			workload.SetAdmissionCheckState(&wl.Status.AdmissionChecks, *acs, w.clock)
+			return true, nil
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go]:
```suggestion
			return workload.SetAdmissionCheckState(&wl.Status.AdmissionChecks, *acs, w.clock), nil
```

File: pkg/features/kube_features.go [hunk 16]
```diff
@@ -341,7 +347,10 @@ var defaultVersionedFeatureGates = map[featuregate.Feature]featuregate.Versioned
 		{Version: version.MustParse("0.15"), Default: false, PreRelease: featuregate.Alpha},
 	},
 	SkipFinalizersForPodsSuspendedByParent: {
-		{Version: version.MustParse("0.16"), Default: true, PreRelease: featuregate.Beta}, // GA in 0.18
+		{Version: version.MustParse("0.16"), Default: true, PreRelease: featuregate.Beta},
+	},
+	MultiKueueRedoAdmissionOnEvictionInWorker: {
```
Comment (mbobrovskyi) [inline pkg/features/kube_features.go:362]: Please add to this table:

https://kueue.sigs.k8s.io/docs/installation/#feature-gates-for-alpha-and-beta-features

File: pkg/features/kube_features.go [hunk 17]
```diff
@@ -341,7 +347,10 @@ var defaultVersionedFeatureGates = map[featuregate.Feature]featuregate.Versioned
...
+		{Version: version.MustParse("0.16"), Default: false, PreRelease: featuregate.Alpha},
```
Comment (mbobrovskyi) [inline pkg/features/kube_features.go]:
```suggestion
		{Version: version.MustParse("0.16"), Default: true, PreRelease: featuregate.Beta}, // GA in 0.18
```

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 18]
```diff
@@ -349,23 +350,43 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+				// We'll retry this in the next reconciling.
+				return reconcile.Result{}, err
+			}
+			return reconcile.Result{}, nil
 		}
 
-		// Wait for QuotaReserved=false in the local job.
-		return reconcile.Result{}, nil
+		if features.Enabled(features.MultiKueueRedoAdmissionOnEvictionInWorker) {
+			if acs.State == kueue.CheckStateReady {
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/workload.go]: nit, but we can inline the checks `features.Enabled(features.MultiKueueRedoAdmissionOnEvictionInWorker)  && acs.State == kueue.CheckStateReady` to save one level of indentention

**Comment by mimowo** [comment]
/lgtm
/approve
Thank you 👍 I think we can keep this without cherrypicking for now.

File: test/e2e/multikueue/e2e_test.go [hunk 19]
```diff
@@ -626,6 +627,84 @@ var _ = ginkgo.Describe("MultiKueue", func() {
 			})
 		})
 
+		ginkgo.It("Should re-do admission process when workload gets evicted in the worker", func() {
+			defaultManagerKueueCfg := util.GetKueueConfiguration(ctx, k8sManagerClient)
+			util.UpdateKueueConfiguration(ctx, k8sManagerClient, defaultManagerKueueCfg, managerClusterName, func(cfg *kueueconfig.Configuration) {
+				cfg.FeatureGates[string(features.MultiKueueRedoAdmissionOnEvictionInWorker)] = true
+			})
```
Comment (mbobrovskyi) [inline test/e2e/multikueue/e2e_test.go:634]: I think this changes no need. We already have enabled true. Could you please prepare follow-up PR to remove this?

File: test/e2e/multikueue/e2e_test.go [hunk 20]
```diff
@@ -626,6 +627,84 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+
+			ginkgo.DeferCleanup(func() {
+				util.UpdateKueueConfiguration(ctx, k8sManagerClient, defaultManagerKueueCfg, managerClusterName, func(cfg *kueueconfig.Configuration) {})
```
Comment (mbobrovskyi) [inline test/e2e/multikueue/e2e_test.go:637]: Also this.

File: test/integration/multikueue/jobs_test.go [hunk 21]
```diff
@@ -1873,6 +1874,103 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
 			}, gomega.Equal(completedJobCondition))))
 		})
 	})
+	ginkgo.It("Should redo the admission process once the workload loses Admission in the worker cluster", func() {
+		features.SetFeatureGateDuringTest(ginkgo.GinkgoTB(), features.MultiKueueRedoAdmissionOnEvictionInWorker, true)
```
Comment (mbobrovskyi) [inline test/integration/multikueue/jobs_test.go:1878]: Also here.

**Comment by mimowo** [comment]
/release-note-edit
```release-note
MultiKueue: trigger workload eviction on the management cluster when the corresponding workload is evicted
on the remote worker cluster. In particular this is fixing the issue with workloads using ProvisioningRequests, 
which could get stuck in a worker cluster which does not have enough capacity to ever admit the workloads.
```
