### PR TITLE
Fix Kueue startup by waiting for webhooks server using probes

### LINKED ISSUE #1658: Flaky Multikueue E2E tests
**What happened**:

It looks like the Kueue managers start properly, but somehow they crash later.
As a result, we observe:

```
Internal error occurred: failed calling webhook "mclusterqueue.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-clusterqueue?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
```

In `End To End MultiKueue Suite: kindest/node:v1.28.0: [It] MultiKueue when Creating a multikueue admission check Should run a job on worker if admitted`

**What you expected to happen**:

Kueue managers to continue to run properly

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1607/pull-kueue-test-e2e-main-1-28/1750942764473782272

Note that this PR only changes documentation, so the flakiness is definitely on the multikueue code.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

To fix the flaky test.
To also let users wait for Kueue webhooks ready without the need for creating / deleting objects as in `KueueReadyForTesting`

#### Which issue(s) this PR fixes:

Fixes #1658

#### Special notes for your reviewer:

Tested locally, trying to see what will happen on GH CI.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
All green, retrying to get more signal:
/test pull-kueue-test-e2e-main-1-26
/test pull-kueue-test-e2e-main-1-27
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-29

File: cmd/kueue/main.go [hunk 1]
```diff
@@ -274,11 +274,15 @@ func setupControllers(mgr ctrl.Manager, cCache *cache.Cache, queues *queue.Manag
...
+	readyz := func(req *http.Request) error {
+		return mgr.GetWebhookServer().StartedChecker()(req)
+	}
+
+	if err := mgr.AddHealthzCheck("healthz", readyz); err != nil {
 		setupLog.Error(err, "unable to set up health check")
 		os.Exit(1)
 	}
-	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
+	if err := mgr.AddReadyzCheck("readyz", readyz); err != nil {
```
Comment (trasc) [inline cmd/kueue/main.go:285]:
```suggestion
	if err := mgr.AddReadyzCheck("readyz",  mgr.GetWebhookServer().StartedChecker()); err != nil {
```

File: cmd/kueue/main.go [hunk 2]
```diff
@@ -274,11 +274,15 @@ func setupControllers(mgr ctrl.Manager, cCache *cache.Cache, queues *queue.Manag
 func setupProbeEndpoints(mgr ctrl.Manager) {
 	defer setupLog.Info("Probe endpoints are configured on healthz and readyz")
 
-	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
+	readyz := func(req *http.Request) error {
+		return mgr.GetWebhookServer().StartedChecker()(req)
+	}
+
```
Comment (trasc) [inline cmd/kueue/main.go:280]:
```suggestion
```

File: cmd/kueue/main.go [hunk 3]
```diff
@@ -274,11 +274,15 @@ func setupControllers(mgr ctrl.Manager, cCache *cache.Cache, queues *queue.Manag
...
+	if err := mgr.AddHealthzCheck("healthz", readyz); err != nil {
```
Comment (trasc) [inline cmd/kueue/main.go:281]: why change the `healthz`?

File: hack/e2e-common.sh [hunk 4]
```diff
@@ -55,5 +55,6 @@ function cluster_kueue_deploy {
     else
         kubectl apply --server-side -k test/e2e/config
     fi
+    kubectl wait --for=condition=available --timeout=3m deployment/kueue-controller-manager -n kueue-system
```
Comment (trasc) [inline hack/e2e-common.sh:58]: Can we do this somewhere else ?  

It could help if in case of multikue , we deploy in manager, and instead of waiting to be ready now, we also deploy in the workers , and check the availability later on for all of them.

Comment (mimowo) [reply hack/e2e-common.sh:58]: I see, this is a simple way of waiting for Kueue ready. I imagine users would like to use in their setup scripts. Typically it takes a couple of seconds.

One alternative is to revert the removal of  `KueueReadyForTesting`, but I don't like it, because it recreates objects, this takes time and could cover some issues (as it is actually currently in case of single cluster). Actually, in this PR I wanted to remove it to test that it is not necessary.

Other alternatives I see modify `KueueReadyForTesting` to check the deployment status as this line, or run the entire setup of different clusters for MK in parallel at the script level.

File: cmd/kueue/main.go (hunk 3 above)
Comment (mimowo) [reply cmd/kueue/main.go:281]: I'm not sure the change to healthz is required. I will test if this can be simplified. Do you know what healthz is used for?

Comment (trasc) [reply cmd/kueue/main.go:281]: it should indicate if the container is running, https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#types-of-probe

Comment (mimowo) [reply cmd/kueue/main.go]: Good call, reverted setting it, going to test.

File: cmd/kueue/main.go (hunk 2 above)
Comment (mimowo) [reply cmd/kueue/main.go]: done

File: cmd/kueue/main.go (hunk 1 above)
Comment (mimowo) [reply cmd/kueue/main.go]: done

File: cmd/kueue/main.go [hunk 5]
```diff
@@ -278,7 +279,9 @@ func setupProbeEndpoints(mgr ctrl.Manager) {
 		setupLog.Error(err, "unable to set up health check")
 		os.Exit(1)
 	}
-	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
+	if err := mgr.AddReadyzCheck("readyz", func(req *http.Request) error {
+		return mgr.GetWebhookServer().StartedChecker()(req)
+	}); err != nil {
```
Comment (trasc) [inline cmd/kueue/main.go:284]:
```suggestion
	if err := mgr.AddReadyzCheck("readyz",mgr.GetWebhookServer().StartedChecker()); err != nil {
```

Comment (trasc) [reply cmd/kueue/main.go:284]: or could the `GetWebhookServer()` return different servers on different calls?

Comment (mimowo) [reply cmd/kueue/main.go:284]: I cannot do this, then the replicas never get ready. The function needs to get the webhook server once ready. I think the webhook server is set asynchronously in controller-runtime.

**Comment by mimowo** [comment]
All green, retrying to get more signal:
/test pull-kueue-test-e2e-main-1-26
/test pull-kueue-test-e2e-main-1-27
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-29

File: cmd/kueue/main.go (hunk 5 above)
Comment (trasc) [reply cmd/kueue/main.go:284]: .... very strange, maybe the cert manager is is doing it ... 
maybe add a comment about this if confirmed.

all other references in sigs are using it directly. 
https://github.com/search?q=org%3Akubernetes-sigs%20StartedChecker&type=code

Comment (trasc) [reply cmd/kueue/main.go:284]: > , I guess we could do the same so that we don't get the transient errors logged.

What kind of errors? 

`GetWebhookServer().StartedChecker` should be the way to go since it actually attempts to connect the server.

Comment (tenzen-y) [reply cmd/kueue/main.go:284]: > I guess we could do the same so that we don't get the transient errors logged. WDYT?

I agree with you. We probably could use this:

https://github.com/kubernetes-sigs/kueue/blob/0b0961db512b5ee91047eaba6ff88694e46ff8c3/pkg/util/cert/cert.go#L70

> GetWebhookServer().StartedChecker should be the way to go since it actually attempts to connect the server.

IIUC, The `GetWebhookServer().StartedChecker` returns 200 only if the checker gets a positive response with tls from the webhook servers. So, we need to wait to be ready for webhook servers, which means we need to wait to be ready for certs.

In the case of `healthz.Ping` (our current checker), it always returns `true` since it doesn't check whether or not the webhook servers can actually work fine.

- `StartedChecker` : https://github.com/kubernetes-sigs/controller-runtime/blob/8475c55f3e00e5611de0880eccd785efa85e8e38/pkg/webhook/server.go#L271-L273
- `healthz.Ping()`: https://github.com/kubernetes-sigs/controller-runtime/blob/8475c55f3e00e5611de0880eccd785efa85e8e38/pkg/healthz/healthz.go#L186-L187

Comment (mimowo) [reply cmd/kueue/main.go:284]: I was thinking about the transient errors before the webhooks is ready, but they are very nice anyway:
```
2024-01-31T13:09:29.832263236Z stderr F 2024-01-31T13:09:29.832081013Z	DEBUG	controller-runtime.healthz	healthz/healthz.go:60	healthz check failed	{"checker": "readyz", "error": "webhook server has not been started yet"}
```
Maybe it doesn't actually make sense though to wait in the checker for ready certs, because it does not attempt to connect if the started=false: https://github.com/kubernetes-sigs/controller-runtime/blob/8475c55f3e00e5611de0880eccd785efa85e8e38/pkg/webhook/server.go#L281C9-L281C16

And it changes started=true only after getting the certs: https://github.com/kubernetes-sigs/controller-runtime/blob/8475c55f3e00e5611de0880eccd785efa85e8e38/pkg/webhook/server.go#L261 (just before listening)

Comment (alculquicondor) [reply cmd/kueue/main.go:284]: GetWebhookServer probably doesn't return a meaningful server until the first webhooks is registered, which only happens after the certs are ready.

Just leave a comment for it.

File: hack/e2e-common.sh (hunk 4 above)
Comment (alculquicondor) [reply hack/e2e-common.sh:58]: +1 on changing `KueueReadyForTesting` with an availability check for the deployment.

File: cmd/kueue/main.go (hunk 5 above)
Comment (tenzen-y) [reply cmd/kueue/main.go:284]: > Maybe it doesn't actually make sense to wait in the checker for ready certs, because it does not attempt to connect if the started=false

I think that waiting for certs to get ready makes sense since the  `StartedChecker` returns a meaningful server only after the certs are ready:  https://github.com/kubernetes-sigs/controller-runtime/blob/8475c55f3e00e5611de0880eccd785efa85e8e38/pkg/webhook/server.go#L237-L240

Comment (trasc) [reply cmd/kueue/main.go:284]: `GetWebhookServer().StartedChecker` is what we need to determine the readiness.

I'm only not sure why we need a closure for calling it , since from what I can see the field  holding the webhook is private  and only stable whit an option when crating the manager,  however it's not a huge problem.

and

>>, I guess we could do the same so that we don't get the transient errors logged.

>What kind of errors?

Comment (mimowo) [reply cmd/kueue/main.go:284]: > `GetWebhookServer().StartedChecker` is what we need to determine the readiness.
> 
> I'm only not sure why we need a closure for calling it , since from what I can see the field holding the webhook is private and only stable whit an option when crating the manager, however it's not a huge problem.
> 

TBH, I'm not sure why either. What I verified experimentally is that if I just call `GetWebhookServer before `WaitForCertsReady` then the webhook is not initialized, and it stays that way. 

I get the following logs then even if keeping the readyz probe like currently, but just invoking `GetWebookServer()` before registering the probe:

```
2024-01-31T19:49:50.466048439Z	INFO	setup	kueue/main.go:291	readyz	{"ws": {"Options":{"Host":"","Port":9443,"CertDir":"/tmp/k8s-webhook-server/serving-certs","CertName":"tls.crt","KeyName":"tls.key","ClientCAName":"","TLSOpts":null,"WebhookMux":{}}}, "err": "webhook server has not been started yet"}
```

I suspect this has something to do with the one-time memorization of the not initialized webhook as runnable here: https://github.com/kubernetes-sigs/controller-runtime/blob/73519a939e27c8465c6c49694356cbd66daf1677/pkg/manager/internal.go#L258.

However, I'm not sure of the details. I would need to further investigate probably with debugger. Let me know if you have some ideas how to get to the bottom of it.

Let me put in the comment what I know so far.

> and
> 
> > > , I guess we could do the same so that we don't get the transient errors logged.
> 
> > What kind of errors?

I meant transient errors before the webhook server is listening, but I didn't how the look like in practice before writing. I was thinking maybe we have many errors about certs not ready. For what I can see we get these errors: 
```
2024-01-31T13:09:29.832263236Z stderr F 2024-01-31T13:09:29.832081013Z	DEBUG	controller-runtime.healthz	healthz/healthz.go:60	healthz check failed	{"checker": "readyz", "error": "webhook server has not been started yet"}
```
before the checker checks the `started` field before attempting the connection. So, there is only a small window where we can get transient errors, between setting `started: true`, and actually listening: https://github.com/kubernetes-sigs/controller-runtime/blob/8475c55f3e00e5611de0880eccd785efa85e8e38/pkg/webhook/server.go#L261-L263. However, I have never seen this errors so far.

Comment (trasc) [reply cmd/kueue/main.go:292]: > I have never seen this errors so far.

I'ts normal behavior when the pod is not yet ready, (previously we ware "ready" from the start). 

Maybe something like: 
```suggestion
	if err := mgr.AddReadyzCheck("readyz", func(req *http.Request) error {
		select{
		case <-certsReady:
			return mgr.GetWebhookServer().StartedChecker()(req)
		case <-req.Context().Done():
			return errors.New("request canceled")
		}
	}); err != nil {
```
Could decrease the umber of messages.

But i find it a bit odd to block the http handler.

Comment (mimowo) [reply cmd/kueue/main.go:292]: I was thinking about waiting explicitly for `certsReady` (it is done in the `hierarchical-namespaces` project as pointed out above). 

However, I think it doesn't improve messages., because we already wait for certs ready as `mgr.GetWebhookServer().StartedChecker()` first checks if `started=true`. then, `started=true` means that certs are ready. If certs aren't ready we get the nice message: `{"checker": "readyz", "error": "webhook server has not been started yet"}`. I think this is enough, and no reason to complicate the code.

Comment (mimowo) [reply cmd/kueue/main.go:292]: Ok, I think I have some new insights into :

> I'm only not sure why we need a closure for calling it , since from what I can see the field holding the webhook is private and only stable whit an option when crating the manager, however it's not a huge problem.

if we call `GetWebhookServer`, then the not fully initialized webhook server runnable is registered here: https://github.com/kubernetes-sigs/controller-runtime/blob/73519a939e27c8465c6c49694356cbd66daf1677/pkg/manager/internal.go#L257. 

When manager starts it starts all runnables, including the webhook server, but it fails, in this case I see in logs early on:
```
2024-02-01T12:44:13.308211223Z	INFO	controller-runtime.webhook	webhook/server.go:191	Starting webhook server
2024-02-01T12:44:13.40926745Z	INFO	controller/controller.go:178	Starting EventSource	{"controller": "cert-rotator", "source": "kind source: *v1.Secret"}
2024-02-01T12:44:13.40932954Z	INFO	controller/controller.go:178	Starting EventSource	{"controller": "cert-rotator", "source": "kind source: *unstructured.Unstructured"}
2024-02-01T12:44:13.40933832Z	INFO	manager/internal.go:516	Stopping and waiting for non leader election runnables
```

Note the presence of "Stopping and waiting for non leader election runnables" just after the start.

OTOH (as in this PR) If we delay calling `GetWebhookServer` then the runnables are added after the certs are ready, and only then the webhook server is started, then it starts successfully. We the log `Starting webhook server` is much later (after certs ready).

Comment (mimowo) [reply cmd/kueue/main.go:292]: slightly polished the comment

File: hack/e2e-common.sh (hunk 4 above)
Comment (alculquicondor) [reply hack/e2e-common.sh:58]: Let's leave this for a follow up.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve
/hold
for a couple more re-runs just in case.

File: hack/e2e-common.sh (hunk 4 above)
Comment (mimowo) [reply hack/e2e-common.sh:58]: Sure, but I'm not sure what is the preferred option as a follow up. Is it returning to the `KueueReadyForTesting`, but waiting for deployment available, as in the command line?

**Comment by mimowo** [comment]
@alculquicondor @tenzen-y 
I have added a release note, because this is actually a user-facing change IMO. Previously it was really hard to tell when Kueue can accept requests, especially in the HA mode. Should we consider cherry-picking?

**Comment by tenzen-y** [comment]
> @alculquicondor @tenzen-y I have added a release note, because this is actually a user-facing change IMO. Previously it was really hard to tell when Kueue can accept early requests, especially in the HA mode. Should we consider cherry-picking?

I'm fine with cherry-picking.
This patch would be helpful for both HA and non-HA users. Without this patch, we need to manually check if the manager has started since the readinessprove server starts in spite of not being ready.

**Comment by alculquicondor** [comment]
+1 on cherry pick
