### PR TITLE
Incorrect admission due to wrong borrowable resource when a cluster queue in cohort is deleted

### LINKED ISSUE #5937: Incorrect admission due to wrong borrowable resource when a cluster queue in cohort is deleted
**What happened**:
ClusterQueue can admit a workload incorrectly through borrowing even when a ClusterQueue in the same cohort is deleted and no borrowable resource is present.

**What you expected to happen**:
When ClusterQueue is deleted, borrowable resources of ClusterQueues in the same cohort should be updated automatically to keep the borrowable resources up-to-date.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two ClusterQueues in the same cohort and LocalQueues for respective CQs:
  ```yaml
  apiVersion: kueue.x-k8s.io/v1beta1
  kind: ResourceFlavor
  metadata:
    name: default-flavor
  spec: {}
  ---
  # Create two cluster queues in the same cohort
  # 8 CPU nominal quota and 0 CPU nominal quota respectively.
  # cluster queue with 0 CPU nominal quota will have to borrow from the other to admit workloads.
  apiVersion: kueue.x-k8s.io/v1beta1
  kind: ClusterQueue
  metadata:
    name: cluster-queue-1
  spec:
    cohort: bug-test
    namespaceSelector: {}
    resourceGroups:
    - coveredResources: ["cpu"]
      flavors:
      - name: "default-flavor"
        resources:
          - name: cpu
            nominalQuota: "8"
  ---
  apiVersion: kueue.x-k8s.io/v1beta1
  kind: ClusterQueue
  metadata:
    name: cluster-queue-2
  spec:
    cohort: bug-test
    namespaceSelector: {}
    resourceGroups:
    - coveredResources: ["cpu"]
      flavors:
      - name: "default-flavor"
        resources:
          - name: cpu
            nominalQuota: "0"
  ---
  # Create local queues for the corresponding cluster queues.
  apiVersion: kueue.x-k8s.io/v1beta1
  kind: LocalQueue
  metadata:
    name: local-queue-1
    namespace: test
  spec:
    clusterQueue: cluster-queue-1
  ---
  apiVersion: kueue.x-k8s.io/v1beta1
  kind: LocalQueue
  metadata:
    name: local-queue-2
    namespace: test
  spec:
    clusterQueue: cluster-queue-2
  
  ```
2. Delete **cluster-queue-1** which has 8 CPU nominal quota. This will result in 0 borrowable CPU and 0 nominal CPU quota for **cluster-queue-2**
3. Create a pod which requests 8 CPU to **cluster-queue-2**. This is supposed to be scheduling gated but you'll see it pending, passing the admission.
```yaml
# A pod requesting 8 CPUs
apiVersion: v1
kind: Pod
metadata:
  name: pod-8-cpu
  namespace: test
  labels:
    kueue.x-k8s.io/queue-name: local-queue-2
spec:
  containers:
  - name: sleep
    command: ["sleep", "infinity"]
    image: busybox:stable
    resources:
      requests:
        cpu: "8"
```

**Anything else we need to know?**:

We can remediate this situation by:
* Restarting the Kueue controller manager.
* Submitting another workload in cluster-queue-2 (which seems to trigger sync).

However since there could be an incorrect admission until we take this remediation, it'd be best if controller could remediate by itself.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.29.4
- Kueue version (use `git describe --tags --dirty --always`): v0.12.4 (latest) and v0.11.6

### PR DESCRIPTION
**Pull request by amy**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Fixes https://github.com/kubernetes-sigs/kueue/issues/5937
updates cohort tree resources in cache on clusterQueue deletion event

#### Which issue(s) this PR fixes:

Fixes #5937

#### Does this PR introduce a user-facing change?

```release-note
Fix incorrect workload admission after CQ is deleted in a cohort reducing the amount of available quota. The culprit of the issue was that the cached amount of quota was not updated on CQ deletion.
```

### CODE REVIEW

**Comment by amy** [comment]
/hold 

(need to add integration tests, want to make sure this approach makes sense. See https://github.com/kubernetes-sigs/kueue/issues/5937 for context)

**Comment by mimowo** [comment]
@amy please add an integration test for the issue scenario

File: pkg/controller/core/clusterqueue_controller.go [hunk 1]
```diff
@@ -341,7 +341,9 @@ func (r *ClusterQueueReconciler) Delete(e event.TypedDeleteEvent[*kueue.ClusterQ
 	defer r.notifyWatchers(e.Object, nil)
 
 	r.log.V(2).Info("ClusterQueue delete event", "clusterQueue", klog.KObj(e.Object))
-	r.cache.DeleteClusterQueue(e.Object)
+	if err := r.cache.DeleteClusterQueue(e.Object); err != nil {
+		r.log.Error(err, "Error deleting ClusterQueue from cache", "clusterQueue", klog.KObj(e.Object))
+	}
```
Comment (amy) [inline pkg/controller/core/clusterqueue_controller.go]: @mimowo probably could use your input here about error handling / logging convention. The message could maybe be improved. 

Otherwise, this PR is ready for review!

File: test/e2e/singlecluster/pod_test.go [hunk 2]
```diff
@@ -552,4 +553,110 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+						var updatedPod corev1.Pod
+						g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(pod), &updatedPod)).To(gomega.Succeed())
+						g.Expect(updatedPod.Spec.SchedulingGates).To(gomega.ContainElement(corev1.PodSchedulingGate{
+							Name: podconstants.SchedulingGateName,
+						}))
+					}, util.ConsistentDuration, util.ShortInterval).Should(gomega.Succeed())
+				})
+			})
+		})
+	})
```
Comment (amy) [inline test/e2e/singlecluster/pod_test.go]: Note for future me: You'll notice that this integration test does not include a check on whether the workload reservation was removed. 

See: https://github.com/kubernetes-sigs/kueue/issues/5937#issuecomment-3077597464

> Even though the quota for cohort is reduced, the Workload still has the QuotaReserved condition. Kueue does not have a mechanism to preempt due to reduced quota (either by lowering the numbers or deleting a CQ contributing to the cohort's quota). So, as a result CQs and cohorts may run over-committed for a while.

File: pkg/cache/cache.go [hunk 3]
```diff
@@ -459,14 +459,17 @@ func (c *Cache) UpdateClusterQueue(log logr.Logger, cq *kueue.ClusterQueue) erro
...
 	c.Lock()
 	defer c.Unlock()
 	cqName := kueue.ClusterQueueReference(cq.Name)
 	curCq := c.hm.ClusterQueue(cqName)
 	if curCq == nil {
-		return
+		return nil
 	}
+
+	parent := curCq.Parent()
```
Comment (mimowo) [inline pkg/cache/cache.go]: Question (I'm not sure): Can this be moved lower down when used?

File: test/e2e/singlecluster/pod_test.go [hunk 4]
```diff
@@ -552,4 +553,110 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+									},
+								},
+							},
+						},
+					},
+				}
+				util.MustCreate(ctx, k8sClient, pod)
+
+				ginkgo.By("Verify the pod should remain scheduling gated (not admitted)", func() {
+					gomega.Consistently(func(g gomega.Gomega) {
```
Comment (mimowo) [inline test/e2e/singlecluster/pod_test.go]: Using consistently is time consuming for integration tests.

I think the same effect can be achieved by checking metrics for Pending with "Inadmissible" status: `util.ExpectPendingWorkloadsMetric(clusterQueue, 0, 1)`

 This metric is only bumped after scheduler considered the workload, so we know it was considered and put as inadmissible. wdyt?

File: pkg/controller/core/clusterqueue_controller.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/core/clusterqueue_controller.go]: Handling errors in event handlers is tricky, because event handles are not retried, so ideally if the function `r.cache.DeleteClusterQueue` wouldn't be returning errors.

Now, I see it starts to return as you call updateCohortTreeResources. Also, I see that the only possible error, at least currently is when it is a cycle.  I see this function is called from many places and some of them silence the error saying that ignored as this is "cycle error" - however, I think this is anti pattern, because as code evolves the comments and silencing may get wrong.

Instead of updating the interface for `r.cache.DeleteClusterQueue`  I propose:
- introduce a new function: `updateCohortTreeResourcesIfNoCycle` and use it from the new code
```golang
func updateCohortTreeResourcesIfNoCycle(cohort *cohort) {
	if !hierarchy.HasCycle(cohort) {
        	updateCohortResourceNode(cohort.getRootUnsafe())
	}
}
```
- follow up to use the new funciton from all other places which currently silence the error.

This will also make the diff smaller making it safer to cherrypick the fix.

cc @gabesaba

**Comment by mimowo** [comment]
Proposing the release note
/release-note-edit
```release-note
Fix incorrect workload admission after CQ is deleted in a cohort reducing the amount of available quota. The culprit of the issue was that the cached amount of quota was not updated on CQ deletion.
```
Feel free to rephrase.

File: pkg/cache/cache.go (hunk 3 above)
Comment (gabesaba) [reply pkg/cache/cache.go]: it can probably be moved to immediately above `c.hm.DeleteClusterQueue`

File: pkg/cache/cache.go [hunk 5]
```diff
@@ -478,6 +481,13 @@ func (c *Cache) DeleteClusterQueue(cq *kueue.ClusterQueue) {
 	}
 	c.hm.DeleteClusterQueue(cqName)
 	metrics.ClearCacheMetrics(cq.Name)
+
+	// Update cohort resources after deletion
+	if parent != nil {
+		return updateCohortTreeResources(parent)
```
Comment (gabesaba) [inline pkg/cache/cache.go]: We can safely ignore this error. We were still able to successfully delete the ClusterQueue, despite the Cohort having a cycle. Since there is a cycle in this Cohort, none of its ClusterQueues will be able to schedule until the cycle is removed (at which point, this `updateCohortTreeResources` function will have been called successfully)
```suggestion
		updateCohortTreeResources(parent)
```

File: pkg/controller/core/clusterqueue_controller.go (hunk 1 above)
Comment (gabesaba) [reply pkg/controller/core/clusterqueue_controller.go]: This suggestion works, or just ignoring the error. I'm fine with either.

**Review by gabesaba — COMMENTED** [review]
Thanks for the fix :)

File: test/e2e/singlecluster/pod_test.go (hunk 4 above)
Comment (amy) [reply test/e2e/singlecluster/pod_test.go]: Hm... interestingly...`PendingWorkloads` is not emitted even though I saw a scheduling gate in the test you see above. Code path I'm looking at:
1. `pkg/controller/core/clusterqueue_controller.go`
```
// Code Review Notes: metrics for deleted CQ cleared in both functions
r.cache.DeleteClusterQueue(e.Object)
r.qManager.DeleteClusterQueue(e.Object)
```
2. since `r.qManager.DeleteClusterQueue(e.Object)` happens last, I tried adding this there:
```
        // Get cohort before deletion to requeue workloads in remaining queues
	var cohortToRequeue *cohort
	if cqImpl.HasParent() {
		cohortToRequeue = cqImpl.Parent()
	}

	m.hm.DeleteClusterQueue(kueue.ClusterQueueReference(cq.Name))
	metrics.ClearClusterQueueMetrics(cq.Name)

	// Requeue workloads in the cohort after deletion
	// This ensures that workloads in remaining ClusterQueues are re-evaluated
	// for admissibility after a lending ClusterQueue is deleted
	if cohortToRequeue != nil {
		ctx := context.Background()
		if m.requeueWorkloadsCohort(ctx, cohortToRequeue) {
			m.Broadcast()
		}
	}
```

However... the metric is still not emitted when I use `util.ExpectPendingWorkloadsMetric(clusterQueue, 0, 1)` locally. @gabesaba @mimowo any suggestions? Will continue debugging. 🤔

Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go]: Cool, I don't know what might be the issue from the top of my head, for now I will just recommend our test debugging guide: https://kueue.sigs.k8s.io/docs/contribution_guidelines/testing/#debug-tests-in-vscode

Hint: I often bump timeouts locally, so that I have time to interpret what I'm seeing in the debugger.

Let me know if you feel stuck, I will try to help or look for an alternative.

File: test/e2e/singlecluster/pod_test.go [hunk 6]
```diff
@@ -552,4 +553,110 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+								Command: []string{"sleep", "infinity"},
+								Resources: corev1.ResourceRequirements{
+									Requests: corev1.ResourceList{
+										corev1.ResourceCPU: resource.MustParse("8"),
+									},
+								},
+							},
+						},
+					},
+				}
```
Comment (mimowo) [inline test/e2e/singlecluster/pod_test.go]: I would suggest to use the PodWrapper, probably something like
```golang
pod := podtesting.MakePod("pod-8-cpu", ns.Name).
	Image(util.GetAgnHostImage(), util.BehaviorWaitForDeletionFailOnExit).
	TerminationGracePeriod(1).
	Queue(lq.Name).
	RequestAndLimit(corev1.ResourceCPU, "8").
```
In particular don't use `"busybox:stable"` because it will need to pull another image.

File: test/e2e/singlecluster/pod_test.go (hunk 4 above)
Comment (amy) [reply test/e2e/singlecluster/pod_test.go]: More findings:
I updated `QueueInadmissibleWorkloads` to report pending workloads as part of the `m.requeueWorkloadsCohort` path:
```
func (c *ClusterQueue) QueueInadmissibleWorkloads(ctx context.Context, client client.Client) bool {
	fmt.Println("-- QueueInadmissibleWorkloads -- ")
         ...
	if len(c.inadmissibleWorkloads) == 0 {
		fmt.Println("-- c.inadmissibleWorkloads is 0 --")
		return false
	}
        ...
        # new code here
	fmt.Println("-- QueueInadmissibleWorkloads, reportPendingWorkloads --")
	reportPendingWorkloads(c.GetName(), c)
	return moved
}
```
Interestingly, it never hits `fmt.Println("-- QueueInadmissibleWorkloads, reportPendingWorkloads --")`

Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go]: Actually, only now I realized this is e2e test, I think we don't need that to repro the issue / prove the fix. 

An integration test will be faster and easier to debug. The proper place I think is in https://github.com/kubernetes-sigs/kueue/blob/main/test/integration/singlecluster/scheduler/scheduler_test.go

File: test/e2e/singlecluster/pod_test.go (hunk 6 above)
Comment (amy) [reply test/e2e/singlecluster/pod_test.go]: resolving this due to your note about integration test being sufficient

**Comment by amy** [comment]
@mimowo @gabesaba ready for another pass 🫡

**Comment by amy** [comment]
/retest

Note: Trying to gauge if this test is flaky: `[pull-kueue-test-integration-baseline-main](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5985/pull-kueue-test-integration-baseline-main/1945990870717173760)`. Current error: 
```
Scheduler Suite: [It] Workload controller with scheduler when Workload with RuntimeClass defined Should accumulate RuntimeClass's overhead expand_less | 11s
-- | --
{Timed out after 10.001s. The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:115 with: Error matcher expects an error.  Got:     <nil>: nil failed [FAILED] Timed out after 10.001s. The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:115 with: Error matcher expects an error.  Got:     <nil>: nil In [AfterEach] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/scheduler/workload_controller_test.go:204 @ 07/17/25 23:48:06.027 }
```

Looks like it failed resource cleanup in the AfterEach. 

Locally `make test-integration` passes.

**Comment by amy** [comment]
cc/ @mimowo @gabesaba 

Looks like this test is failing in this PR. But the integration tests passes locally. Do y'all think its a timeout issue? 
https://github.com/kubernetes-sigs/kueue/pull/5985#issuecomment-3086336938

```
make test-integration

# local output
Ginkgo ran 23 suites in 10m34.970075167s
Test Suite Passed
/Users/amychen/Gopath/src/github.com/kubernetes-sigs/kueue/bin/ginkgo-top -i /Users/amychen/Gopath/src/github.com/kubernetes-sigs/kueue/bin/integration.json > /Users/amychen/Gopath/src/github.com/kubernetes-sigs/kueue/bin/integration-top.yaml
```

**Comment by mimowo** [comment]
Let me retry, maybe [this failure](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5985/pull-kueue-test-integration-baseline-main/1946021850337251328) is just an unrelated flake (unfortunately we have some). If confirmed i will open an issue.

**Comment by mimowo** [comment]
Oh, it failed again, I think this is not a flake actually. The issue is that the new test references the on-demand RF (that is fine), but does not clear its CQs after itself. Ideally, each test should clean after itself in the AfterEach, Otherwise it is hard to run the tests in a loop. 

I see there is another test which does not clean after itself, but is using another dedicated RF - I will open a cleanup issue for that. Opened: https://github.com/kubernetes-sigs/kueue/issues/6017

File: test/integration/singlecluster/scheduler/scheduler_test.go [hunk 7]
```diff
@@ -2683,4 +2698,58 @@ var _ = ginkgo.Describe("Scheduler", func() {
...
+			lq1 *kueue.LocalQueue
+			lq2 *kueue.LocalQueue
+		)
+
+		ginkgo.AfterEach(func() {
+			gomega.Expect(util.DeleteNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
+			util.ExpectObjectToBeDeleted(ctx, k8sClient, cq1, true)
+			util.ExpectObjectToBeDeleted(ctx, k8sClient, cq2, true)
+			util.ExpectObjectToBeDeleted(ctx, k8sClient, lq1, true)
+			util.ExpectObjectToBeDeleted(ctx, k8sClient, lq2, true)
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/scheduler_test.go]: IIUC `util.DeleteNamespac` cleans all namespace-scoped resources, so LQs, in particular.

File: test/integration/singlecluster/scheduler/scheduler_test.go [hunk 8]
```diff
@@ -2639,6 +2639,21 @@ var _ = ginkgo.Describe("Scheduler", func() {
 
 			ns = util.CreateNamespaceFromPrefixWithLog(ctx, k8sClient, "core-")
 		})
+
+		ginkgo.AfterEach(func() {
```
Comment (amy) [inline test/integration/singlecluster/scheduler/scheduler_test.go]: Will remove the changes here once this issue is resolved: https://github.com/kubernetes-sigs/kueue/issues/6017

Wrote this chunk because I want the tests to pass on my PR.

**Comment by amy** [comment]
/hold 

dependent on https://github.com/kubernetes-sigs/kueue/issues/6017

File: test/integration/singlecluster/scheduler/scheduler_test.go (hunk 7 above)
Comment (mimowo) [reply test/integration/singlecluster/scheduler/scheduler_test.go]: I expect this is enough:

```golang
gomega.Expect(util.DeleteNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
util.ExpectObjectToBeDeleted(ctx, k8sClient, cq1, true)
util.ExpectObjectToBeDeleted(ctx, k8sClient, cq2, true)
util.ExpectObjectToBeDeleted(ctx, k8sClient, onDemandFlavor, true)		
```

**Comment by mimowo** [comment]
> /hold dependent on https://github.com/kubernetes-sigs/kueue/issues/6017

Is it really depending on that, I see the other test creates CQs and RFs named differently, so while I like to fix the issue, I don't expect dependency here.

File: test/integration/singlecluster/scheduler/scheduler_test.go (hunk 8 above)
Comment (mimowo) [reply test/integration/singlecluster/scheduler/scheduler_test.go]: Sure. However, I expect this is not really blocking you PR, because the Flavors are named differently. Your PR probably interacted with yet another test which has the issue. If that works, I prefer to merge without it so that we can cherrypick without conflicts (probably, unless in other places), because the test was added in 0.12.

As for the cleanup logic namespace-scoped resources (LQs, Workloads, etc) are cleaned with `gomega.Expect(util.DeleteNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())`, and so the iterations `for _, lq := range lqs {` and `for _, wl := range wls {` are not needed.

**Comment by amy** [comment]
> > /hold dependent on #6017
> 
> Is it really depending on that, I see the other test creates CQs and RFs named differently, so while I like to fix the issue, I don't expect dependency here.

oh! I think I misunderstood your previous comment then. Let me... try removing that unrelated chunk and see if the tests still pass.

File: test/integration/singlecluster/scheduler/scheduler_test.go (hunk 8 above)
Comment (amy) [reply test/integration/singlecluster/scheduler/scheduler_test.go]: https://github.com/kubernetes-sigs/kueue/pull/5985#issuecomment-3089649887

**Comment by mimowo** [comment]
Thank you 👍 

/lgtm
/approve
/cherrypick release-0.12
/cherrypick release-0.11

**Comment by mimowo** [comment]
@amy would you mind to try preparing the cherrypick? You can try the ./hack/cherry_pick_pull.sh script (or as such)

If there are too many conflicts, then don't bother, 0.11 will be end of life once we release 0.13 (coming soon).
