### PR TITLE
[jobframework] Use the jobs uid in workload's name hash.

### LINKED ISSUE #1726: Job gets admitted, but is never un-suspended.
**What happened**:

Job submitted, workload got created and admitted that job. Job was never un-suspended. I tried to patch Job to `suspend: false`, but it immediately got suspended again.

There are multiple identical errors from kueue:

```json
{
  "level": "error",
  "ts": "2024-02-12T08:30:42.026624587Z",
  "caller": "jobframework/reconciler.go:335",
  "msg": "Handling job with no workload",
  "controller": "job",
  "controllerGroup": "batch",
  "controllerKind": "Job",
  "Job": {
    "name": "ml-job-annotator-gt-webface-gpu",
    "namespace": "pgrunt"
  },
  "namespace": "pgrunt",
  "name": "ml-job-annotator-gt-webface-gpu",
  "reconcileID": "edba044d-1ece-4364-8c6a-c0dc66907553",
  "job": "pgrunt/ml-job-annotator-gt-webface-gpu",
  "gvk": "batch/v1, Kind=Job",
  "error": "workloads.kueue.x-k8s.io \"job-ml-job-annotator-gt-webface-gpu-ff6d8\" already exists",
  "stacktrace": "sigs.k8s.io/kueue/pkg/controller/jobframework.(*JobReconciler).ReconcileGenericJob\n\t/workspace/pkg/controller/jobframework/reconciler.go:335\nsigs.k8s.io/kueue/pkg/controller/jobframework.(*genericReconciler).Reconcile\n\t/workspace/pkg/controller/jobframework/reconciler.go:1007\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"
}
```

Cluster, local queue

```yaml
NapiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kueue.x-k8s.io/v1beta1","kind":"ClusterQueue","metadata":{"annotations":{},"name":"cq-all-resources"},"spec":{"flavorFungibility":{"whenCanBorrow":"Borrow","whenCanPreempt":"TryNextFlavor"},"namespaceSelector":{},"preemption":{"reclaimWithinCohort":"Never","withinClusterQueue":"Never"},"queueingStrategy":"StrictFIFO","resourceGroups":[{"coveredResources":["nvidia.com/gpu"],"flavors":[{"name":"gpu-a40","resources":[{"name":"nvidia.com/gpu","nominalQuota":8}]},{"name":"gpu-a100","resources":[{"name":"nvidia.com/gpu","nominalQuota":4}]}]},{"coveredResources":["cpu","memory","ephemeral-storage","github.com/fuse","pods"],"flavors":[{"name":"default-flavor","resources":[{"name":"cpu","nominalQuota":256},{"name":"memory","nominalQuota":"2Ti"},{"name":"ephemeral-storage","nominalQuota":"2Ti"},{"name":"github.com/fuse","nominalQuota":"10k"},{"name":"pods","nominalQuota":220}]}]}]}}
  creationTimestamp: "2024-02-07T14:30:12Z"
  finalizers:
  - kueue.x-k8s.io/resource-in-use
  generation: 4
  name: cq-all-resources
  resourceVersion: "336378666"
  uid: cb3e70ae-714d-4aa4-8edc-0b76041d24b9
spec:
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Never
    withinClusterQueue: Never
  queueingStrategy: StrictFIFO
  resourceGroups:
  - coveredResources:
    - nvidia.com/gpu
    flavors:
    - name: gpu-a40
      resources:
      - name: nvidia.com/gpu
        nominalQuota: 8
    - name: gpu-a100
      resources:
      - name: nvidia.com/gpu
        nominalQuota: 4
  - coveredResources:
    - cpu
    - memory
    - ephemeral-storage
    - github.com/fuse
    - pods
    flavors:
    - name: default-flavor
      resources:
      - name: cpu
        nominalQuota: 256
      - name: memory
        nominalQuota: 2Ti
      - name: ephemeral-storage
        nominalQuota: 2Ti
      - name: github.com/fuse
        nominalQuota: 10k
      - name: pods
        nominalQuota: 220
  stopPolicy: None
status:
  admittedWorkloads: 1
  conditions:
  - lastTransitionTime: "2024-02-07T14:31:07Z"
    message: Can admit new workloads
    reason: Ready
    status: "True"
    type: Active
  flavorsReservation:
  - name: gpu-a40
    resources:
    - borrowed: "0"
      name: nvidia.com/gpu
      total: "2"
  - name: gpu-a100
    resources:
    - borrowed: "0"
      name: nvidia.com/gpu
      total: "0"
  - name: default-flavor
    resources:
    - borrowed: "0"
      name: cpu
      total: "10"
    - borrowed: "0"
      name: ephemeral-storage
      total: 12Gi
    - borrowed: "0"
      name: github.com/fuse
      total: "0"
    - borrowed: "0"
      name: memory
      total: 45Gi
    - borrowed: "0"
      name: pods
      total: "1"
  flavorsUsage:
  - name: gpu-a40
    resources:
    - borrowed: "0"
      name: nvidia.com/gpu
      total: "2"
  - name: gpu-a100
    resources:
    - borrowed: "0"
      name: nvidia.com/gpu
      total: "0"
  - name: default-flavor
    resources:
    - borrowed: "0"
      name: cpu
      total: "10"
    - borrowed: "0"
      name: ephemeral-storage
      total: 12Gi
    - borrowed: "0"
      name: github.com/fuse
      total: "0"
    - borrowed: "0"
      name: memory
      total: 45Gi
    - borrowed: "0"
      name: pods
      total: "1"
  pendingWorkloads: 0
  reservingWorkloads: 1
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  creationTimestamp: "2024-02-07T14:33:08Z"
  generation: 1
  name: lq-all-resources
  namespace: pgrunt
  resourceVersion: "336378665"
  uid: 7f52812a-6752-4363-8eee-4789bb2d6358
spec:
  clusterQueue: cq-all-resources
status:
  admittedWorkloads: 1
  conditions:
  - lastTransitionTime: "2024-02-07T14:33:08Z"
    message: Can submit new workloads to clusterQueue
    reason: Ready
    status: "True"
    type: Active
  flavorUsage:
  - name: gpu-a40
    resources:
    - name: nvidia.com/gpu
      total: "2"
  - name: gpu-a100
    resources:
    - name: nvidia.com/gpu
      total: "0"
  - name: default-flavor
    resources:
    - name: cpu
      total: "10"
    - name: ephemeral-storage
      total: 12Gi
    - name: github.com/fuse
      total: "0"
    - name: memory
      total: 45Gi
    - name: pods
      total: "1"
  flavorsReservation:
  - name: gpu-a40
    resources:
    - name: nvidia.com/gpu
      total: "2"
  - name: gpu-a100
    resources:
    - name: nvidia.com/gpu
      total: "0"
  - name: default-flavor
    resources:
    - name: cpu
      total: "10"
    - name: ephemeral-storage
      total: 12Gi
    - name: github.com/fuse
      total: "0"
    - name: memory
      total: 45Gi
    - name: pods
      total: "1"
  pendingWorkloads: 0
  reservingWorkloads: 1
```

Job.yaml

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: ml-job
    kueue.x-k8s.io/queue-name: lq-all-resources
    kueue.x-k8s.io/priority-class: ml-low
  name: ml-job-webface-mapping-this_is_placeholder
spec:
  backoffLimit: 0
  suspend: true
  template:
    metadata:
      name: ml-job
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - hawking
      containers:
      - command:
        - bash
        - -c
        - |
          export PATH="/opt/venv/bin/:${PATH}" &&
          cd /data/workspace/facekit &&
          pip install -e . &&
          facekit face_annotator multiface ${WORKLOAD_ARGS} --processes 30
        env:
        - name: GIT_REPO
          value: "redacted"
        - name: GIT_CHECKOUT_BRANCH
          value: "redacted"
        - name: WORKLOAD_ARGS
          value: ""
        - name: OMP_NUM_THREADS
          value: "1"
        - name: NUMEXPR_NUM_THREADS
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: user-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: user-credentials
        - name: CLEARML_API_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: CLEARML_API_ACCESS_KEY
              name: user-credentials
        - name: CLEARML_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: CLEARML_API_SECRET_KEY
              name: user-credentials
        image: "redacted"
        imagePullPolicy: Always
        name: ml-main
        resources:
          limits:
            cpu: 100
            ephemeral-storage: 120Gi
            memory: 80Gi
            nvidia.com/gpu: "2"
          requests:
            cpu: 30
            ephemeral-storage: 120Gi
            memory: 45Gi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data/user
          name: user-configuration
        - mountPath: /data/workspace
          name: workspace
        - mountPath: /srv/dvc_cache/
          name: dvc-cache
        - mountPath: /mnt/nas.brno/
          name: nas-brno
        - mountPath: /etc/redacted/
          name: iengine-lic
        - mountPath: /dev/shm
          name: dev-shm
        - mountPath: /mnt/data/downloader
          name: downloader
        - mountPath: /encrypted/INC-12499
          name: wiki-hdd
        - mountPath: /root
          name: user-home-dev-pod-0
        workingDir: /data/workspace
      imagePullSecrets:
      - name: registry-credentials
      initContainers:
      - command:
        - bash
        - -c
        - |
          if [[ ! -d "/root/.ssh" ]]; then
            mkdir ~/.ssh &&
            mkdir ~/.kube &&
            cp /data/user/id_* ~/.ssh &&
            cp /data/user/.git* ~/ &&
            cp /data/user/kubeconfig ~/.kube/config &&
            ssh-keyscan -p 7999 -t rsa redacted > ~/.ssh/known_hosts &&
            cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys &&
            chmod 600 ~/.ssh/id_rsa &&
            git clone $GIT_REPO &&
            cd "$(basename "$GIT_REPO" .git)" &&
            git checkout $GIT_CHECKOUT_BRANCH
          fi
        env:
        - name: GIT_REPO
          value: "redacted"
        - name: GIT_CHECKOUT_BRANCH
          value: "redacted"
        image: bitnami/git:latest
        name: init-git-repo
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /data/user
          name: user-configuration
        - mountPath: /data/workspace
          name: workspace
        workingDir: /data/workspace
      priorityClassName: ml-low
      restartPolicy: Never
      runtimeClassName: nvidia
      volumes:
      - name: user-configuration
        projected:
          sources:
          - secret:
              items:
              - key: id_rsa
                path: id_rsa
              - key: id_rsa.pub
                path: id_rsa.pub
              - key: .git-credentials
                path: .git-credentials
              - key: kubeconfig
                path: kubeconfig
              name: user-credentials
          - configMap:
              items:
              - key: .gitconfig
                path: .gitconfig
              name: gitconfig
          - configMap:
              items:
              - key: clearml.conf
                path: clearml.conf
              name: clearml.conf
      - hostPath:
          path: /srv/dvc_cache/
        name: dvc-cache
      - emptyDir: {}
        name: workspace
      - hostPath:
          path: /mnt/nas.brno
        name: nas-brno
      - configMap:
          name: iengine.lic
        name: iengine-lic
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: dev-shm
      - hostPath:
          path: /mnt/data/downloader
        name: downloader
      - hostPath:
          path: /encrypted/INC-12499
        name: wiki-hdd
      - name: user-home-dev-pod-0
        persistentVolumeClaim:
          claimName: user-home-dev-pod-0
  ttlSecondsAfterFinished: 1200

```

The Worklaod object has status:

```yaml
Conditions:
Last Transition Time: 2024-02-11T10:42:40Z
Message: Quota reserved in ClusterQueue cq-all-resources
Reason: QuotaReserved
Status: True
Type: QuotaReserved
Last Transition Time: 2024-02-11T10:42:40Z
Message: The workload is admitted
Reason: Admitted Status: True
Type: Admitted
```

**What you expected to happen**:

Job gets un-suspended, Pod is created and running.

**How to reproduce it (as minimally and precisely as possible)**:

Create cluster+local queue and try submitting job mentioned above.

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cq-all-resources
spec:
  preemption:
    reclaimWithinCohort: Never
    withinClusterQueue: Never
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  queueingStrategy: StrictFIFO
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: gpu-a40
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 8
        - name: gpu-a100
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 4
    - coveredResources: ["cpu", "memory", "ephemeral-storage", "github.com/fuse", "pods"]
      flavors:
      - name: "default-flavor"
        resources:
        - name: "cpu"
          nominalQuota: 256
        - name: "memory"
          nominalQuota: 2Ti
        - name: "ephemeral-storage"
          nominalQuota: 2Ti
        - name: "github.com/fuse"
          nominalQuota: 10k
        - name: "pods"
          nominalQuota: 220
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: pgrunt
  name: lq-all-resources
spec:
  clusterQueue: cq-all-resources
```

**Anything else we need to know?**:

I guess that's all, let me know if you need some more information and I will happily provide.

**Environment**:

- Kubernetes version (use `kubectl version`): Server Version: v1.26.10+rke2r2
- Kueue version (use `git describe --tags --dirty --always`): 0.5.2 installed via 0.1.0 Helm chart
- Cloud provider or hardware configuration: on-prem, 8x NVIDIA-A40, AMD EPYC 7502, 1TB RAM
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`): 5.15.0-79-generic
- Install tools: Helm v3.11.2, Kustomize v5.0.4-0.20230601165947-6ce0bf390ce3

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
[jobframework] Use the jobs uuid in workload's name hash. With this we can avoid name collisions for workloads create for jobs having the same name and type created at different pints in time.
#### Which issue(s) this PR fixes:

Fixes #1726

#### Does this PR introduce a user-facing change?

```release-note
The hash suffix of the workload's name are now influenced by the job's object UID. Recreated jobs with the same name and kind will use different workload names.
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
Actually, I think it would be good to get to the bottom of [1726](https://github.com/kubernetes-sigs/kueue/issues/1726) before adding UID to the hash. At least I still don't fully understand it, so maybe just explaining would be enough if you already know. I'm worried that with this change with risk covering some issues, and complications on upgrade. 

Concrete questions:
1. in case there is a conflict in a scenario when a job is recreated with different pod spec, so that the workload is not longer equivalent, should we not trigger recreation the workload?
2. what is the impact during upgrade, what will happen to user workloads which are pending, and admitted ones?

**Comment by alculquicondor** [comment]
I'm ok with this change, but before we merge it, I think we should make sure we are not depending on the predictability of the workload name.

**Comment by tenzen-y** [comment]
What happens if admins do cluster migration? 
We often migrate the existing cluster to a new cluster to update the k8s version with backup and restore etcd.

I guess that workloads are just recreated with a new name since Job UID is changed by migration, right?
So, there is no impact, right?

**Comment by mimowo** [comment]
I still have concerns about this approach, summarized here: https://github.com/kubernetes-sigs/kueue/issues/1726#issuecomment-1945514791.

**Comment by trasc** [comment]
@alculquicondor 
Passed the workload creation the workload name is irrelevant for Kueue, job reconciliation is done based on ownership (with the exception of prebuilt workloads when there is no relationship between the wl and job name).

From a human user perspective the wl names will continue to look similar `<job-prefix>-<job-name>-<hash-segment>`,  where `hash-segment` is an opaque string.

@tenzen-y 
For etcd backup/restore I'd expect the workloads to be part of that process as well, if not, indeed the should just be recreated. (are the UIDs  changed in migration?)

**Comment by tenzen-y** [comment]
> For etcd backup/restore I'd expect the workloads to be part of that process as well, if not, indeed the should just be recreated. (are the UIDs changed in migration?)

If we directly backup and restore etcd, UID wouldn't be changed, but if we use cluster backup tools like the [`velero`](https://velero.io/), UID will be changed. I'm ok with only recreating the workloads.

**Comment by alculquicondor** [comment]
My worry is this line:

https://github.com/kubernetes-sigs/kueue/blob/e10df68a066f23ee1f6787de6e5cd24be86772df/pkg/controller/jobs/job/job_webhook.go#L80

**Comment by trasc** [comment]
> GetWorkloadNameForOwnerRef

Yes , this could be problematic in case of  kueue upgrades, it could keep the child job Suspended if the workload for the parent was created before the upgrade.

A similar problem we have with prebuilt workloads, but only for jobsets at this point, and we do this https://github.com/kubernetes-sigs/kueue/blob/01bd53214c8bc92b9a1164b224104a2f73397b4a/pkg/controller/jobs/jobset/jobset_webhook.go#L60-L69

to overcome it.

Maybe we could droop the usage of the parentWlAnotation and cover the prebuilt scenario as well.

**Comment by alculquicondor** [comment]
> Maybe we could drop the usage of the parentWlAnotation and cover the prebuilt scenario as well.

Can you expand on this?

**Comment by trasc** [comment]
> > Maybe we could drop the usage of the parentWlAnotation and cover the prebuilt scenario as well.
> 
> Can you expand on this?

We can use an ownership based approach, the child job and the worker have the same parent . https://github.com/kubernetes-sigs/kueue/pull/1732/commits/4dc9ba07b3b255e0ea4c582cc5af36d2b08404d1

**Comment by alculquicondor** [comment]
I like that. Let's start with a PR just for that.

**Comment by trasc** [comment]
> I like that. Let's start with a PR just for that.

Moved in #1747

**Review by mimowo — COMMENTED** [review]
Code LGTM, just some nits. Also, a suggestion for potential follow up.

I'm on a fence regarding the release note saying "to avoid potential name collisions". They are rare at rate 1/16mln they are still sort of possible to observe. Maybe we can rephrase a little not to be definitive.

File: pkg/controller/jobs/pod/pod_controller_test.go [hunk 1]
```diff
@@ -3171,8 +3171,8 @@ func TestIsPodOwnerManagedByQueue(t *testing.T) {
 }
 
 func TestGetWorkloadNameForPod(t *testing.T) {
-	wantWlName := "pod-unit-test-7bb47"
-	wlName := GetWorkloadNameForPod("unit-test")
+	wantWlName := "pod-unit-test-65369"
```
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller_test.go:3174]: I see, but this is actually all that `GetWorkloadNameForPod` does - the rest is happening underneath. So we may unit test it just by checking it passes the parameters properly IMO. I think if we want to check the hashing, then the unit test for `GetWorkloadNameForOwnerWithGVK` is more appropriate, so that the intention is clear.

**Comment by mimowo** [comment]
Should we update the PR description to note  that it fixes https://github.com/kubernetes-sigs/kueue/issues/1726? Or we believe there is more to do to close it, like the GC? In that case we may just mention "Part of #1726".

File: pkg/controller/jobs/pod/pod_controller_test.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller_test.go:3174]: I genuinely don't know that the intentions of this test are.

[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller_test.go:3174]: +1 I feel maintaining tests with concrete value of the hash is bad.

For `GetWorkloadNameForPod` I would be fine to drop it entirely (or just test delegation as mentioned above).

For `GetWorkloadNameForOwnerWithGVK` I guess we would like to demonstrate that the hash is stable given the job UID and name. However, this would be tested at integration test level, so also I don't see much of a need. Feel free not to add them.

**Comment by trasc** [comment]
> Should we update the PR description to note that it fixes #1726? Or we believe there is more to do to close it, like the GC? In that case we may just mention "Part of #1726".

Lt's go with Fix, since the issue cannot be reproduce after adding this.

File: pkg/controller/jobs/pod/pod_controller_test.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller_test.go:3174]: The test should focus on the behavior we want to have:
- The prefix matches the job kind and name
- (new) two jobs with the same name but different UID get different workload names.

[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller_test.go]: done

**Comment by mimowo** [comment]
/lgtm
IIUC the remaining issue is that when a running Job is deleted with `--cascade orphan`, then the workload remains admitted and continues to consume quota, which we want to tackle by GC (either removal or marking as finished). If this is correct, could you please open a follow up issue?

**Comment by mimowo** [comment]
For the release note, maybe something more user-oriented:
"The workload name is no longer the same for recreated jobs (with the same namespace and name),
because  Job UID is used to determine the hash-like suffix in the workload name."

WDYT @tenzen-y

**Comment by tenzen-y** [comment]
> For the release note, maybe something more user-oriented: "The workload name is no longer the same for recreated jobs (with the same namespace and name), because Job UID is used to determine the hash-like suffix in the workload name."
> 
> WDYT @tenzen-y

@mimowo Generally, sgtm, but it is better to emphasize that the creating workloads names lose consistency or obtain completely random names. WDYT?

**Comment by trasc** [comment]
> "The workload names are virtually random now."

Cannot be added since they are not random.

**Comment by mimowo** [comment]
> > "The workload names are virtually random now."
> 
> Cannot be added since they are not random.

Well, I think saying "virtually" random, or "random from user's perspective" is fine, but I don't have a strong opinion. Still, I think we should make set the release note to something understandable to users. WDYT @tenzen-y ?

**Comment by trasc** [comment]
Release note updated

File: pkg/controller/jobs/job/job_controller_test.go [hunk 2]
```diff
@@ -2164,7 +2164,7 @@ func TestReconciler(t *testing.T) {
 				Effect:   corev1.TaintEffectNoSchedule,
 			}).Obj(),
 			workloads: []kueue.Workload{
-				*utiltesting.MakeWorkload(GetWorkloadNameForJob(baseJobWrapper.Name), "ns").
+				*utiltesting.MakeWorkload(GetWorkloadNameForJob(baseJobWrapper.Name, baseJobWrapper.GetUID()), "ns").
```
Comment (alculquicondor) [inline pkg/controller/jobs/job/job_controller_test.go:2167]: Can we have another unit test where we put a completely different name, but the reconciler still recognizes it as the workload for the job?

Comment (trasc) [reply pkg/controller/jobs/job/job_controller_test.go:2167]: It will be a bit of a stretch and has nothing to do with the current PR.

Comment (alculquicondor) [reply pkg/controller/jobs/job/job_controller_test.go:2167]: It does have to do. It's one minimal safety guard to ensure that existing jobs (before upgrading to the latest version) continue to run.

Comment (trasc) [reply pkg/controller/jobs/job/job_controller_test.go:2167]: Why not add this when owner based workload section was added?

Comment (alculquicondor) [reply pkg/controller/jobs/job/job_controller_test.go:2167]: because of bad foresight, but it wasn't that important then.

Comment (trasc) [reply pkg/controller/jobs/job/job_controller_test.go:2167]: for the vast majority of tests the workload has name `a` hot the name that is usually generated.

Comment (alculquicondor) [reply pkg/controller/jobs/job/job_controller_test.go:2167]: ok, thanks for checking. That should be enough.

**Comment by tenzen-y** [comment]
> > > "The workload names are virtually random now."
> > 
> > 
> > Cannot be added since they are not random.
> 
> Well, I think saying "virtually" random, or "random from user's perspective" is fine (after saying that it is a hash-like in the previous sentence), but I don't have a strong opinion. Still, I think we should make set the release note to something understandable to users. WDYT @tenzen-y ?

Sorry for the late. It sounds good to me.
