### PR TITLE
[test/int/kueuectl] Delete the used CQ at the end of stop/resume tests.

### LINKED ISSUE #2245: [kueuectl] Flaky test "Should stop a ClusterQueue Stop a ClusterQueue and drain workloads"
**What happened**:

The test failed on unrelated branch https://github.com/kubernetes-sigs/kueue/pull/2239

**What you expected to happen**:

No failure

**How to reproduce it (as minimally and precisely as possible)**:

Probably just repeat the build

**Anything else we need to know?**:

```
Kueuectl Suite: [It] Kueuectl Stop when Stopping a ClusterQueue Should stop a ClusterQueue Stop a ClusterQueue and drain workloads expand_less	0s
{Expected success, but got an error:
    <*errors.StatusError | 0xc0005141e0>: 
    clusterqueues.kueue.x-k8s.io "cq-1" already exists
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "clusterqueues.kueue.x-k8s.io \"cq-1\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "cq-1",
                Group: "kueue.x-k8s.io",
                Kind: "clusterqueues",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc0005141e0>: 
    clusterqueues.kueue.x-k8s.io "cq-1" already exists
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "clusterqueues.kueue.x-k8s.io \"cq-1\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "cq-1",
                Group: "kueue.x-k8s.io",
                Kind: "clusterqueues",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/kueuectl/stop_test.go:87 @ 05/21/24 07:10:01.133
}
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:
Delete the used CQ at the end of stop/resume integration tests.

#### Which issue(s) this PR fixes:

Fixes #2245

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: test/integration/kueuectl/resume_test.go [hunk 1]
```diff
@@ -111,6 +111,13 @@ var _ = ginkgo.Describe("Kueuectl Resume", ginkgo.Ordered, ginkgo.ContinueOnFail
 						g.Expect(ptr.Deref(createdClusterQueue.Spec.StopPolicy, v1beta1.None)).Should(gomega.Equal(v1beta1.None))
 					}, util.Timeout, util.Interval).Should(gomega.Succeed())
 				})
+
+				ginkgo.By("Delete the ClusterQueue", func() {
```
Comment (mimowo) [inline test/integration/kueuectl/resume_test.go:115]: I would suggest to use `util.ExpectClusterQueueToBeDeleted` to don't repeat the code, and wrap inside `ginkgo.DeferCleanup` so that we clean up in case the test itself fails.

Comment (trasc) [reply test/integration/kueuectl/resume_test.go]: done

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
thanks!

**Comment by mimowo** [comment]
/test pull-kueue-test-integration-main
https://github.com/kubernetes-sigs/kueue/issues/2243
