### PR TITLE
Validating admissionchecks

### LINKED ISSUE #1187: Validate workload PodSetUpdates
**What happened**:

It is possible to set workload PodSetUpdates with invalid values, resulting in errors during workload admission.

**What you expected to happen**:

Fail fast on modifications to `workload.PodSetUpdates` which are performed by external controllers.

Validated things:
- `PodSetUpdates.name` should be a valid pod set name
- `PodSetUpdates.tolerations` should a valid list of tolerations, see https://github.com/kubernetes/kubernetes/blob/57d3cc66050545d7fefb0841e750a0a41df14144/pkg/apis/core/validation/validation.go#L3749
- validate annotations and labels, see: https://github.com/kubernetes/kubernetes/blob/57d3cc66050545d7fefb0841e750a0a41df14144/pkg/apis/core/validation/validation.go#L126

Proposed solution: workload webhook.

Part of  #1145

### PR DESCRIPTION
**Pull request by stuton**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Validate PodSetUpdates field to avoid errors during workload admission

#### Which issue(s) this PR fixes:

Fixes #1187

#### Does this PR introduce a user-facing change?

```release-note
validate PodSetUpdates field of workload
```

### CODE REVIEW

**Comment by trasc** [comment]
@stuton , @mimowo  should we also make sure that the `PodSetUpdates` of a admission check  is not change  

`oldAC.State == newAC.State == Ready`

**Comment by mimowo** [comment]
> @stuton , @mimowo should we also make sure that the PodSetUpdates of a admission check is not changed when
oldAC.State == newAC.State == Ready

I think so, it's easier to relax if needed, than make validation strong later.

File: pkg/webhooks/workload_webhook.go [hunk 1]
```diff
@@ -182,6 +184,87 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
...
+		ac := &obj.Status.AdmissionChecks[i]
+		allErrs = append(allErrs, validatePodSetUpdates(ac, obj, admissionChecksPath.Child("podSetUpdates"))...)
+	}
+	return allErrs
+}
+
+func validatePodSetUpdates(acs *kueue.AdmissionCheckState, obj *kueue.Workload, basePath *field.Path) field.ErrorList {
+	var allErrs field.ErrorList
+
+	knowPodSets := make(map[string]struct{}, len(obj.Spec.PodSets))
```
Comment (mimowo) [inline pkg/webhooks/workload_webhook.go:200]: Use `sets.Set[string]`  to represent the pod set names

File: pkg/webhooks/workload_webhook.go [hunk 2]
```diff
@@ -182,6 +184,87 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
...
+	knowPodSetNames := make([]string, len(obj.Spec.PodSets))
```
Comment (mimowo) [inline pkg/webhooks/workload_webhook.go:201]: No need for this. If you use sets, you can convert them to list with `sets.List`.

File: pkg/webhooks/workload_webhook.go [hunk 3]
```diff
@@ -182,6 +184,87 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
...
+		}
+		allErrs = append(allErrs, validateTolerations(psu.Tolerations, psuPath.Child("tolerations"))...)
+		allErrs = append(allErrs, apivalidation.ValidateAnnotations(psu.Annotations, psuPath.Child("annotations"))...)
+		allErrs = append(allErrs, metav1validation.ValidateLabels(psu.Labels, psuPath.Child("labels"))...)
+	}
+	return allErrs
+}
+
+// validateTolerations is extracted from git.k8s.io/kubernetes/pkg/apis/core/validation/validation.go
+func validateTolerations(tolerations []corev1.Toleration, fldPath *field.Path) field.ErrorList {
```
Comment (mimowo) [inline pkg/webhooks/workload_webhook.go:224]: Oh, I don't really like this but found we have also other copy-paste places like this. https://github.com/kubernetes-sigs/kueue/blob/525098b838eb28ee241cf1aaee5e53f161d30a0c/pkg/webhooks/resourceflavor_webhook.go#L134. Is there no way to depend on the `git.k8s.io/kubernetes/pkg/apis/core/validation/` package?

File: pkg/webhooks/workload_webhook_test.go [hunk 4]
```diff
@@ -232,6 +234,35 @@ func TestValidateWorkload(t *testing.T) {
 				field.Invalid(firstPodSetSpecPath.Child("containers").Index(0).Child("resources", "requests").Key(string(corev1.ResourcePods)), nil, ""),
 			},
 		},
+		"should have a valid podSetUpdate name": {
```
Comment (mimowo) [inline pkg/webhooks/workload_webhook_test.go:237]: Please also add tests which verify the set of names in `podSetUpdates` to be not matching these in `podSets`

File: pkg/webhooks/workload_webhook.go [hunk 5]
```diff
@@ -182,6 +184,87 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
...
+		knowPodSets[name] = struct{}{}
+		knowPodSetNames = append(knowPodSetNames, name)
+	}
+	for i := range acs.PodSetUpdates {
+		psu := &acs.PodSetUpdates[i]
+		psuPath := basePath.Index(i)
+		for _, msg := range validation.IsDNS1123Label(psu.Name) {
+			allErrs = append(allErrs, field.Invalid(psuPath.Child("name"), psu.Name, msg))
+		}
+		if _, found := knowPodSets[psu.Name]; !found {
```
Comment (mimowo) [inline pkg/webhooks/workload_webhook.go:213]: I think currently the implementation only works then the set in podSets equals the set in podSetUpdates. Not sure this is expected. @stuton please confirm.

File: pkg/webhooks/workload_webhook.go (hunk 3 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook.go:224]: As I know, libraries are published as standalone modules and can be referenced directly. I've never meet validation library as standalone module. We can consider depending on k8s.io/kubernetes directly but it's not recommended: https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505627280

Comment (mimowo) [reply pkg/webhooks/workload_webhook.go:224]: Ok, I would suggest adding the link to the comment so that we have a pointer.

File: pkg/webhooks/workload_webhook.go (hunk 5 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook.go:213]: when the names of podSetUpdates don't equal the names of podSets we will provide "notsupported" error

File: pkg/webhooks/workload_webhook.go (hunk 3 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook.go:224]: added comment https://github.com/kubernetes-sigs/kueue/pull/1220/commits/dd3dde19094c7988fcd3440d59aaf40d1dafee6b

File: pkg/webhooks/workload_webhook.go (hunk 2 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook.go]: done https://github.com/kubernetes-sigs/kueue/pull/1220/commits/dd3dde19094c7988fcd3440d59aaf40d1dafee6b

File: pkg/webhooks/workload_webhook.go (hunk 5 above)
Comment (mimowo) [reply pkg/webhooks/workload_webhook.go]: IIUC currently in code you only check that every name in podSetUpdates is in known set. So you are not checking equality of the sets, but you are checking that the set of names is podSetUpdates is a subset of the names in podSets.

File: pkg/webhooks/workload_webhook.go [hunk 6]
```diff
@@ -182,6 +184,87 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
...
+}
+
+func validatePodSetUpdates(acs *kueue.AdmissionCheckState, obj *kueue.Workload, basePath *field.Path) field.ErrorList {
+	var allErrs field.ErrorList
+
+	knowPodSets := make(sets.Set[string], len(obj.Spec.PodSets))
+	for i := range obj.Spec.PodSets {
+		name := obj.Spec.PodSets[i].Name
+		knowPodSets.Insert(name)
+	}
```
Comment (trasc) [inline pkg/webhooks/workload_webhook.go:204]: I think  this can be replace with something like
```suggestion
	knowPodSets := sets.New(slices.Map(obj.Spec.PodSets,{// return name here})...)
```
and maybe do it only once it the caller function

File: pkg/webhooks/workload_webhook.go [hunk 7]
```diff
@@ -182,6 +184,87 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
...
+	for i := range acs.PodSetUpdates {
+		psu := &acs.PodSetUpdates[i]
+		psuPath := basePath.Index(i)
+		for _, msg := range validation.IsDNS1123Label(psu.Name) {
+			allErrs = append(allErrs, field.Invalid(psuPath.Child("name"), psu.Name, msg))
+		}
```
Comment (trasc) [inline pkg/webhooks/workload_webhook.go:210]: We don't really care if it's `IsDNS1123Label` as long as the name is found in the list of podsets.

Comment (stuton) [reply pkg/webhooks/workload_webhook.go]: removed https://github.com/kubernetes-sigs/kueue/pull/1220/commits/0943f326b3dc45a32e58f6899a8bbf4b755e07db

File: pkg/webhooks/workload_webhook_test.go (hunk 4 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook_test.go]: added https://github.com/kubernetes-sigs/kueue/pull/1220/commits/0943f326b3dc45a32e58f6899a8bbf4b755e07db

File: pkg/webhooks/workload_webhook.go [hunk 8]
```diff
@@ -182,6 +185,103 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
...
+	var allErrs field.ErrorList
+
+	knowPodSets := sets.New(slices.Map(obj.Spec.PodSets, func(ps *kueue.PodSet) string {
+		return ps.Name
+	})...)
+
+	for i := range acs.PodSetUpdates {
+		psu := &acs.PodSetUpdates[i]
+		psuPath := basePath.Index(i)
+		if found := knowPodSets.Has(psu.Name); !found {
```
Comment (tenzen-y) [inline pkg/webhooks/workload_webhook.go:211]:
```suggestion
		if !knowPodSets.Has(psu.Name) {
```

File: pkg/webhooks/workload_webhook.go [hunk 9]
```diff
@@ -182,6 +185,103 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
...
+			allErrs = append(allErrs, field.NotSupported(psuPath.Child("name"), psu.Name, knowPodSets.UnsortedList()))
+		}
+		allErrs = append(allErrs, validateTolerations(psu.Tolerations, psuPath.Child("tolerations"))...)
+		allErrs = append(allErrs, apivalidation.ValidateAnnotations(psu.Annotations, psuPath.Child("annotations"))...)
+		allErrs = append(allErrs, metav1validation.ValidateLabels(psu.Labels, psuPath.Child("labels"))...)
```
Comment (tenzen-y) [inline pkg/webhooks/workload_webhook.go:216]: Can we validate nodeSelector, as well?

https://github.com/kubernetes/kubernetes/blob/57d3cc66050545d7fefb0841e750a0a41df14144/pkg/apis/core/validation/validation.go#L4218-L4219

File: pkg/webhooks/workload_webhook_test.go
Comment (tenzen-y) [inline pkg/webhooks/workload_webhook_test.go:1]: Can you update the valid case?

**Comment by tenzen-y** [comment]
otherwise lgtm

File: pkg/webhooks/workload_webhook.go [hunk 10]
```diff
@@ -182,6 +185,103 @@ func validateContainer(c *corev1.Container, path *field.Path) field.ErrorList {
 	return allErrs
 }
 
+func validateAdmissionChecks(obj *kueue.Workload, basePath *field.Path) field.ErrorList {
+	var allErrs field.ErrorList
+	for i := range obj.Status.AdmissionChecks {
+		admissionChecksPath := basePath.Index(i)
+		ac := &obj.Status.AdmissionChecks[i]
+		if len(ac.PodSetUpdates) > 0 && (len(ac.PodSetUpdates) != len(obj.Spec.PodSets)) {
```
Comment (alculquicondor) [inline pkg/webhooks/workload_webhook.go:193]: nit
```suggestion
		if len(ac.PodSetUpdates) > 0 && len(ac.PodSetUpdates) != len(obj.Spec.PodSets) {
```

File: pkg/webhooks/workload_webhook.go (hunk 9 above)
Comment (alculquicondor) [reply pkg/webhooks/workload_webhook.go:216]: The nodeSelector is much simpler than that. We can just use `ValidateLabels` again.

File: pkg/webhooks/workload_webhook_test.go [hunk 11]
```diff
@@ -232,6 +234,48 @@ func TestValidateWorkload(t *testing.T) {
 				field.Invalid(firstPodSetSpecPath.Child("containers").Index(0).Child("resources", "requests").Key(string(corev1.ResourcePods)), nil, ""),
 			},
 		},
+		"should podSetUpdates have the same number of podSets": {
```
Comment (alculquicondor) [inline pkg/webhooks/workload_webhook_test.go:237]: Add one case for empty podSetUpdates, as that's valid

File: pkg/webhooks/workload_webhook_test.go [hunk 12]
```diff
@@ -466,6 +510,25 @@ func TestValidateWorkloadUpdate(t *testing.T) {
 				field.Invalid(field.NewPath("spec").Child("priorityClassName"), nil, ""),
 			},
 		},
+		"podSetUpdates should be immutable when state is ready": {
```
Comment (alculquicondor) [inline pkg/webhooks/workload_webhook_test.go:513]: Add a case for updates in other fields where the podSetUpdates don't change

File: pkg/webhooks/workload_webhook_test.go [hunk 13]
```diff
@@ -232,6 +234,48 @@ func TestValidateWorkload(t *testing.T) {
...
+				*testingutil.MakePodSet("first", 1).Obj(),
+				*testingutil.MakePodSet("second", 1).Obj(),
+			).AdmissionChecks(
+				kueue.AdmissionCheckState{PodSetUpdates: []kueue.PodSetUpdate{{Name: "first"}}},
+			).Obj(),
+			wantErr: field.ErrorList{
+				field.Invalid(podSetUpdatePath, nil, "must have the same number of podSetUpdates as the podSets"),
+			},
+		},
+		"should the set of names in podSetUpdates to be matching with podSets": {
```
Comment (alculquicondor) [inline pkg/webhooks/workload_webhook_test.go:248]: add a case where they match

File: pkg/webhooks/workload_webhook.go (hunk 9 above)
Comment (tenzen-y) [reply pkg/webhooks/workload_webhook.go:216]: It makes sense. We don't need to validate `operator`.

File: pkg/webhooks/workload_webhook_test.go (hunk 12 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook_test.go:513]: IIUC this test specifically checks for changes in the label field when `podsetupdates` must be immutable. You'd like to see a test that allows us to change fields?

File: pkg/webhooks/workload_webhook_test.go (hunk 11 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook_test.go:241]: added https://github.com/kubernetes-sigs/kueue/pull/1220/commits/7799023ffef622e04d748162ae003fbf416f5ac9

File: pkg/webhooks/workload_webhook_test.go
Comment (stuton) [reply pkg/webhooks/workload_webhook_test.go:1]: added case with checking nodeselector https://github.com/kubernetes-sigs/kueue/pull/1220/commits/7799023ffef622e04d748162ae003fbf416f5ac9

File: pkg/webhooks/workload_webhook_test.go (hunk 13 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook_test.go]: added https://github.com/kubernetes-sigs/kueue/pull/1220/commits/7799023ffef622e04d748162ae003fbf416f5ac9

File: pkg/webhooks/workload_webhook.go [hunk 14]
```diff
@@ -208,28 +208,28 @@ func validatePodSetUpdates(acs *kueue.AdmissionCheckState, obj *kueue.Workload,
 	for i := range acs.PodSetUpdates {
 		psu := &acs.PodSetUpdates[i]
 		psuPath := basePath.Index(i)
-		if found := knowPodSets.Has(psu.Name); !found {
+		if !knowPodSets.Has(psu.Name) {
 			allErrs = append(allErrs, field.NotSupported(psuPath.Child("name"), psu.Name, knowPodSets.UnsortedList()))
```
Comment (mimowo) [inline pkg/webhooks/workload_webhook.go:212]: nit: I would suggest to return the list sorted. Returning unsorted could add something to remember about in integration tests.

Comment (tenzen-y) [reply pkg/webhooks/workload_webhook.go:212]: +1

We can use the `sets.List()` function.

Comment (stuton) [reply pkg/webhooks/workload_webhook.go]: updated https://github.com/kubernetes-sigs/kueue/pull/1220/commits/b219249d415c88de69843728c446aadc55cc43ea

File: pkg/webhooks/workload_webhook_test.go [hunk 15]
```diff
@@ -232,6 +234,70 @@ func TestValidateWorkload(t *testing.T) {
...
+			wantErr: field.ErrorList{
+				field.NotSupported(firstAdmissionChecksPath.Child("podSetUpdates").Index(1).Child("name"), nil, nil),
+			},
+		},
+		"matched names in podSetUpdates with names in podSets": {
+			workload: testingutil.MakeWorkload(testWorkloadName, testWorkloadNamespace).PodSets(
+				*testingutil.MakePodSet("first", 1).Obj(),
+				*testingutil.MakePodSet("second", 1).Obj(),
+			).AdmissionChecks(
+				kueue.AdmissionCheckState{PodSetUpdates: []kueue.PodSetUpdate{{Name: "first"}, {Name: "second"}}},
```
Comment (tenzen-y) [inline pkg/webhooks/workload_webhook_test.go:268]: Can we add valid values such as annotations, tolerations, and so on?

File: pkg/webhooks/workload_webhook_test.go (hunk 12 above)
Comment (alculquicondor) [reply pkg/webhooks/workload_webhook_test.go:535]: I'd like to see a test where `podSetUpdates` don't change, but other fields do. In other words: a test for the case where the validation passes.

File: pkg/webhooks/workload_webhook_test.go (hunk 15 above)
Comment (stuton) [reply pkg/webhooks/workload_webhook_test.go]: added https://github.com/kubernetes-sigs/kueue/pull/1220/commits/950ad18ea9deb450786c49b83c54e7fc31510a24

File: pkg/webhooks/workload_webhook_test.go (hunk 11 above)
Comment (alculquicondor) [reply pkg/webhooks/workload_webhook_test.go:244]: ah, sorry, I missed it.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve
