### PR TITLE
Fix generateName for StatefulSets by including UID in workload name

### LINKED ISSUE #8687: Create statefulsets with generatedName always produce the same workload name `statefulset--d7705`
**What happened**:

Create statefulsets with `kubectl create -f` and `metadata.generateName` in the yaml file. The generated workload is always `statefulset--d7705`, causing severe problem that you cannot run another statefulset with the same yaml file.

**What you expected to happen**:

The second statefulset run smoothly with a different generated name if there is enough resources in the queue.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install kueue 0.15.2 in kubernetes 1.35
2. Enable statefulset by edit configmap `kueue-manager-config` (add `statefulset` to `integrations.frameworks`)
3. Create resourceflavor, clusterqueue, localqueue by `kubectl apply -f rf_cq_lq.yaml`
4. Run `kubectl create -f sleep_sts.yaml`, the statefulset runs successfully
5. Run `kubectl create -f sleep_sts.yaml` again, the new statefulset cannot run (come into READY state)
6. Check the existing workload name is `statefulset--d7705`
7. Delete all statefulset and recreate one, and you can see the name of workload is still `statefulset--d7705`

The mentioned `rf_cq_lq.yaml` file:

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
spec:
  nodeLabels:
    node-group: default
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: test
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
        - pods
      flavors:
        - name: default
          resources:
            - name: cpu
              nominalQuota: 8
            - name: memory
              nominalQuota: 64Gi
            - name: pods
              nominalQuota: 8
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: default
  name: test
spec:
  clusterQueue: test
```

The mentioned `sleep_sts.yaml` file:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generateName: sleep-
  labels:
    kueue.x-k8s.io/queue-name: test
spec:
  serviceName: sleep-service
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - image: busybox:1.37.0-glibc
          imagePullPolicy: IfNotPresent
          name: sleep-busybox
          command: ["sh", "-c", "trap exit INT TERM; sleep 30s & wait"]
          resources:
            requests:
              cpu: "1"
              memory: 100Mi
            limits:
              cpu: "1"
              memory: 100Mi
```

**Anything else we need to know?**:

No.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.35.0
- Kueue version (use `git describe --tags --dirty --always`): Installed by `helm install kueue oci://registry.k8s.io/kueue/charts/kueue --version=0.15.2`
- Cloud provider or hardware configuration: 3 Nodes with 16 CPUs, 64GiB memory for each
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.5 LTS
- Kernel (e.g. `uname -a`): 5.15.0-164-generic SMP x86_64 GNU/Linux
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

`GetWorkloadName` previously used only the StatefulSet name with an empty UID, causing workload name collisions when multiple StatefulSets shared a `generateName` prefix. This PR now includes the UID in the workload name hash.

Since the UID is not available at webhook time, labels that depend on the workload name have been moved from the webhook to the reconciler.

For MultiKueue compatibility, this PR adds `GetOwnerUID` (following the LWS pattern) so that worker-cluster copies use the management cluster’s UID via `MultiKueueOriginUIDAnnotation`.

#### Which issue(s) this PR fixes:

Fixes #8687

#### Does this PR introduce a user-facing change?

```release-note
StatefulSet integration: fix the bug that when using `generateName` the Workload names generated
for two different StatefulSets would conflict, not allowing to run the second StatefulSet.
```

### CODE REVIEW

**Comment by IrvingMg** [comment]
@DavideRutigliano @mbobrovskyi PTAL

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 1]
```diff
@@ -104,6 +115,61 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
...
+	podList := &corev1.PodList{}
+	if sts != nil {
+		if err := r.client.List(ctx, podList,
+			client.InNamespace(req.Namespace),
+			client.MatchingLabels(sts.Spec.Selector.MatchLabels),
+		); err != nil {
+			return nil, err
+		}
+		return slices.DeleteFunc(podList.Items, func(pod corev1.Pod) bool {
+			return !isManagedByStatefulSet(&pod, sts.UID)
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go]: I don’t think we need this check. We already select the pods using matchLabels, which gives us exactly the pods we need.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 2]
```diff
@@ -104,6 +115,61 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
...
+
+	if err := r.client.List(ctx, podList,
+		client.InNamespace(req.Namespace),
+		client.MatchingLabels{constants.ManagedByKueueLabelKey: constants.ManagedByKueueLabelValue},
+	); err != nil {
+		return nil, err
+	}
+	return slices.DeleteFunc(podList.Items, func(pod corev1.Pod) bool {
+		return !isOwnedByStatefulSetName(&pod, req.Name)
+	}), nil
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go]: This is not good. There could be thousands of pods in this namespace. We need to add indexer for this.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 3]
```diff
@@ -41,8 +45,10 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/reconcile"
 
 	kueue "sigs.k8s.io/kueue/apis/kueue/v1beta2"
+	"sigs.k8s.io/kueue/pkg/constants"
+	controllerconstants "sigs.k8s.io/kueue/pkg/controller/constants"
 	"sigs.k8s.io/kueue/pkg/controller/jobframework"
-	podcontroller "sigs.k8s.io/kueue/pkg/controller/jobs/pod/constants"
+	podconstants "sigs.k8s.io/kueue/pkg/controller/jobs/pod/constants"
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go:48]: Could you please create prepare PR to reduce changes?

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 4]
```diff
@@ -104,6 +115,61 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
...
+			return !isManagedByStatefulSet(&pod, sts.UID)
+		}), nil
+	}
+
+	if err := r.client.List(ctx, podList,
+		client.InNamespace(req.Namespace),
+		client.MatchingLabels{constants.ManagedByKueueLabelKey: constants.ManagedByKueueLabelValue},
+	); err != nil {
+		return nil, err
+	}
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go]: I also thinking about case when we don't have statefulset and don't have ownerReference. In that case it could be possible zombie pods.

[Here](https://github.com/epam/kubernetes-kueue/blob/d1344c5dc1fadd280af0499077dce85d4cc0d438/pkg/controller/jobs/statefulset/statefulset_reconciler.go#L360-L363) we catch ADDED event. But still we skipping pods without ownerReference [here](https://github.com/epam/kubernetes-kueue/blob/d1344c5dc1fadd280af0499077dce85d4cc0d438/pkg/controller/jobs/statefulset/statefulset_reconciler.go#L376-L387).

I would propose creating a separate statufelset_pod_controller for this, similar to what we did in LWS, to prevent this case.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 5]
```diff
@@ -104,6 +115,61 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
...
+	return slices.DeleteFunc(podList.Items, func(pod corev1.Pod) bool {
+		return !isOwnedByStatefulSetName(&pod, req.Name)
+	}), nil
+}
+
+func (r *Reconciler) labelPods(ctx context.Context, workloadName string, sts *appsv1.StatefulSet, pods []corev1.Pod) error {
+	log := ctrl.LoggerFrom(ctx)
+	queueName := string(jobframework.QueueNameForObject(sts))
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go]:
```suggestion
	queueName := jobframework.QueueNameForObject(sts)
```

File: pkg/controller/jobs/statefulset/statefulset_reconciler_test.go [hunk 6]
```diff
@@ -36,6 +37,8 @@ import (
 	statefulsettesting "sigs.k8s.io/kueue/pkg/util/testingjobs/statefulset"
 )
 
+const testUID = types.UID("sts")
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_reconciler_test.go]:
```suggestion
const testUID = "sts"
```

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go (hunk 3 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go:48]: Opened PR: https://github.com/kubernetes-sigs/kueue/pull/9274

File: pkg/controller/jobs/statefulset/statefulset_reconciler_test.go (hunk 6 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_reconciler_test.go]: Done.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go (hunk 5 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Done.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go (hunk 1 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Dropped it.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go (hunk 2 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: As the pod reconciler has been added, this logic was removed.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go (hunk 4 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Done. I've added `pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go`.

File: pkg/controller/jobs/statefulset/statefulset_multikueue_adapter.go [hunk 7]
```diff
@@ -72,6 +72,11 @@ func (b *multiKueueAdapter) SyncJob(ctx context.Context, localClient client.Clie
 	remoteStatefulSet.Labels[constants.PrebuiltWorkloadLabel] = workloadName
 	remoteStatefulSet.Labels[kueue.MultiKueueOriginLabel] = origin
 
+	if remoteStatefulSet.Annotations == nil {
+		remoteStatefulSet.Annotations = map[string]string{}
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_multikueue_adapter.go]:
```suggestion
		remoteStatefulSet.Annotations = make(map[string]string, 1)
```

**Comment by mimowo** [comment]
@IrvingMg do you understand the issue behind the e2e tests failing https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9091/pull-kueue-test-e2e-multikueue-main/2023423325627224064? Do we have a path forward for fixing it?

**Comment by IrvingMg** [comment]
> @IrvingMg do you understand the issue behind the e2e tests failing https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9091/pull-kueue-test-e2e-multikueue-main/2023423325627224064? Do we have a path forward for fixing it?

Yes, I’ve been looking into it and am currently working on the fix. The issue seems to be related to splitting the reconciliation process after adding the StatefulSet pod reconciler, which is causing the workload to miss the StatefulSet owner reference.

**Comment by IrvingMg** [comment]
The main problem with MultiKueue tests comes from a bug in how StatefulSets were integrated into MultiKueue. (https://github.com/kubernetes-sigs/kueue/pull/8611). The issue is that MultiKueue uses the pod adapter instead of the StatefulSet adapter, so it treats the StatefulSet as just a group of pods. Because of this, no StatefulSet is created in the worker cluster.

I have created a new PR to fix this issue: https://github.com/kubernetes-sigs/kueue/pull/9344

File: pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go [hunk 8]
```diff
@@ -0,0 +1,261 @@
+/*
+Copyright The Kubernetes Authors.
+
+Licensed under the Apache License, Version 2.0 (the "License");
```
Comment (mszadkow) [inline pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go:4]: This file seems to be un-relevant refactoring, can we extract this change to a separate PR?

Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go:4]: Yeah, this PR will be based, once https://github.com/kubernetes-sigs/kueue/pull/9344 is merged.

Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go:4]: Done. PR rebased.

**Comment by IrvingMg** [comment]
> Looks great, but I have a doubt about pre-existing StatefulSets. Can you verify what will happen with them? In particular, I think we may create another Workload resulting in double-counting the quota. Ideally, we can handle that gracefully and continue to operate using the old Workloads, or re-create them with minimal downtime. Let me know what you find out.

I manually checked the behavior and confirmed that workload duplication and double-counted quota do happen.

To fix this, I added a fallback for existing STS. During reconciliation, if the workload is not found with the new UID-based name, the controller checks the old (non-UID) name. If it finds an existing workload with the old name, it reuses it instead of creating a new one. This prevents duplicate workloads and avoids double-counting quota, without downtime.

File: pkg/controller/jobs/statefulset/statefulset_webhook.go [hunk 9]
```diff
@@ -185,14 +186,26 @@ func (wh *Webhook) ValidateUpdate(ctx context.Context, oldSTSObj, newSTSObj *app
...
+				switch {
+				case client.IgnoreNotFound(err) != nil:
 					return nil, err
-				} else if err == nil {
+				case err == nil:
 					allErrs = append(allErrs, field.Forbidden(replicasPath, "workload from previous scale-down is still being deleted"))
+				default:
+					// TODO(v0.20): Remove legacy fallback.
+					legacyName := GetWorkloadName("", oldStatefulSet.GetName())
+					if legacyName != workloadName {
```
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go]: Why the check ` legacyName != workloadName`. IIUC this is just a micro optimization to skip extra Get which will happen once in a million: `16^5`. Unless I'm missing something we can just save on complexity (and also cover the code better in tests, I doubt both branches of the check are covered in tests currently).

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 10]
```diff
@@ -79,21 +79,31 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
...
-	sts := &appsv1.StatefulSet{}
-	err := r.client.Get(ctx, req.NamespacedName, sts)
-	if client.IgnoreNotFound(err) != nil {
-		return ctrl.Result{}, err
+	wlName := GetWorkloadName(GetOwnerUID(sts), sts.Name)
+
+	// TODO(v0.20): Remove legacy fallback.
+	// Fall back to pre-v0.17 workload name (without UID) for upgrade compatibility.
+	legacyName := GetWorkloadName("", sts.Name)
+	if legacyName != wlName {
```
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go]: This check looks extra as commented in :  https://github.com/kubernetes-sigs/kueue/pull/9091/changes#r2885425499

However, I'm also thinking if we could commonize the code by a helper like `determineWorkloadName`, and the fallback would only be there.

**Review by mimowo — COMMENTED** [review]
LGTM, just nits to deduplicate the checks for the legacy wlName fallback

File: pkg/controller/jobs/statefulset/statefulset_webhook.go (hunk 9 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go]: Yes, the idea was to skip an extra get, but I've dropped it.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go (hunk 10 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Done. I've commonized it in the `findWorkloadName` func.

File: pkg/controller/jobs/statefulset/statefulset_webhook.go [hunk 11]
```diff
@@ -185,14 +186,24 @@ func (wh *Webhook) ValidateUpdate(ctx context.Context, oldSTSObj, newSTSObj *app
...
+				case err == nil:
 					allErrs = append(allErrs, field.Forbidden(replicasPath, "workload from previous scale-down is still being deleted"))
+				default:
+					// TODO(v0.20): Remove legacy fallback.
+					legacyName := GetWorkloadName("", oldStatefulSet.GetName())
+					err = wh.client.Get(ctx, client.ObjectKey{Namespace: ns, Name: legacyName}, &wl)
+					if client.IgnoreNotFound(err) != nil {
+						return nil, err
+					} else if err == nil {
+						allErrs = append(allErrs, field.Forbidden(replicasPath, "workload from previous scale-down is still being deleted"))
```
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go]: Hm, could we restructure the code to use the findWorkloadName helper?

File: pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go [hunk 12]
```diff
@@ -129,7 +130,21 @@ func (r *PodReconciler) setDefault(ctx context.Context, pod *corev1.Pod) (bool,
...
+		legacyName := GetWorkloadName("", sts.Name)
+		if legacyName != wlName {
+			wl := &kueue.Workload{}
+			if err := r.client.Get(ctx, client.ObjectKey{Namespace: pod.Namespace, Name: legacyName}, wl); err == nil {
+				wlName = legacyName
+			} else if !apierrors.IsNotFound(err) {
+				return false, err
+			}
+		}
+	}
```
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go]: Could we restructure the code to us use the findWorkloadName helper?

File: pkg/controller/jobs/statefulset/statefulset_webhook.go (hunk 11 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go]: Done.

File: pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go (hunk 12 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_pod_reconciler.go]: Done.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 13]
```diff
@@ -181,6 +177,22 @@ func (r *Reconciler) syncQueueLabel(ctx context.Context, sts *appsv1.StatefulSet
...
+// TODO(#9497, v0.20): Remove legacy fallback.
+func findWorkloadName(ctx context.Context, c client.Client, sts *appsv1.StatefulSet) string {
+	wlName := GetWorkloadName(GetOwnerUID(sts), sts.Name)
+	wl := &kueue.Workload{}
+	if apierrors.IsNotFound(c.Get(ctx, client.ObjectKey{Namespace: sts.Namespace, Name: wlName}, wl)) {
+		legacyName := GetWorkloadName("", sts.Name)
+		if c.Get(ctx, client.ObjectKey{Namespace: sts.Namespace, Name: legacyName}, wl) == nil {
+			ctrl.LoggerFrom(ctx).V(3).Info("Using legacy workload name", "legacyName", legacyName, "newName", wlName)
+			return legacyName
+		}
```
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go]: /hold

Comment (mimowo) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Let's propagate any non-NotFound errors and return, to avoid silencing some errors.

Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_reconciler.go]: Done.
