### PR TITLE
Disabled scheduler on "should requeued after job status ready" test.

### LINKED ISSUE #2155: Flaky Test: Job controller interacting with scheduler when waitForPodsReady enabled when workload evicted due pods ready timeout should requeued after job status ready
/kind flake
**What happened**:

Flaky Test, `Job controller interacting with scheduler when waitForPodsReady enabled when workload evicted due pods ready timeout should requeued after job status ready`:

```shell
{Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/integration/controller/jobs/job/job_controller_test.go:2007 with:
Expected
    <*int32 | 0xc000eb46e8>: 2
to equal
    <*int32 | 0xc000eb46ec>: 1 failed [FAILED] Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/integration/controller/jobs/job/job_controller_test.go:2007 with:
Expected
    <*int32 | 0xc000eb46e8>: 2
to equal
    <*int32 | 0xc000eb46ec>: 1
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/controller/jobs/job/job_controller_test.go:2041 @ 05/07/24 12:58:46.121
}
```

**What you expected to happen**:

No happen

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2151/pull-kueue-test-integration-main/1787828665795481600

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Disable scheduler on "should requeued after job status ready" test.

#### Which issue(s) this PR fixes:

Fixes #2155 and #2158

#### Special notes for your reviewer:
Related for this comment https://github.com/kubernetes-sigs/kueue/pull/2158#discussion_r1593690691.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 1]
```diff
@@ -1912,13 +1912,14 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler when waitForP
 		waitForPodsReady := &configapi.WaitForPodsReady{
 			Enable:         true,
 			BlockAdmission: ptr.To(true),
-			Timeout:        &metav1.Duration{Duration: 10 * time.Millisecond},
+			Timeout:        &metav1.Duration{Duration: 250 * time.Millisecond},
 			RequeuingStrategy: &configapi.RequeuingStrategy{
 				Timestamp:          ptr.To(configapi.EvictionTimestamp),
-				BackoffBaseSeconds: ptr.To[int32](1),
+				BackoffBaseSeconds: ptr.To[int32](3),
```
Comment (mimowo) [inline test/integration/controller/jobs/job/job_controller_test.go:1918]: Why is this changed? Similarly, I prefer the small value, so that the test runs faster. Without scheduler it should not flake.

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 2]
```diff
@@ -1912,13 +1912,14 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler when waitForP
 		waitForPodsReady := &configapi.WaitForPodsReady{
 			Enable:         true,
 			BlockAdmission: ptr.To(true),
-			Timeout:        &metav1.Duration{Duration: 10 * time.Millisecond},
+			Timeout:        &metav1.Duration{Duration: 250 * time.Millisecond},
```
Comment (mimowo) [inline test/integration/controller/jobs/job/job_controller_test.go:1915]: Why is this changed? I would suggest keeping 10ms if it was working ok

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 3]
```diff
@@ -2004,35 +2011,9 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler when waitForP
 				g.Expect(*createdJob.Status.Ready).Should(gomega.Equal(int32(1)))
 				g.Expect(k8sClient.Get(ctx, wlKey, wl)).Should(gomega.Succeed())
 				g.Expect(wl.Status.RequeueState).ShouldNot(gomega.BeNil())
-				// Assert count>0 since the workload may get requeued and evicted
```
Comment (mimowo) [inline test/integration/controller/jobs/job/job_controller_test.go:2007]: I think now we can also remove the section above:
```
ginkgo.By("setting job status ready")
```
Right?

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 4]
```diff
@@ -2004,35 +2011,9 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler when waitForP
...
-				// more than once before we mark the Job status as ready.
-				g.Expect(ptr.Deref(wl.Status.RequeueState.Count, 0)).Should(gomega.BeNumerically(">", 0))
+				g.Expect(wl.Status.RequeueState.Count).Should(gomega.Equal(ptr.To[int32](1)))
 				g.Expect(wl.Status.RequeueState.RequeueAt).Should(gomega.BeNil())
 				g.Expect(wl.Status.Conditions).To(gomega.ContainElements(
-					gomega.BeComparableTo(metav1.Condition{
```
Comment (mimowo) [inline test/integration/controller/jobs/job/job_controller_test.go:2012]: Please keep asserts on the conditions. IIUC we should have:
WorkloadPodsReady=False
WorkloadQuotaReserved=False
WorkloadEvicted=True
WorkloadAdmitted=False
WorkloadRequeued=True

Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go:2012]: Yes, you right. Ok, will add it.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go:1915]: I'm not sure why but sometimes timeout error with 10ms.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 3 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go:2007]: Oh yes, you right, it's not need.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go:1915]: Timeout 10ms, BackoffBaseSeconds: 2s working for me fine. Not sure about Flaky...

**Comment by mbobrovskyi** [comment]
Integration passed 2/5

/test pull-kueue-test-integration-main

**Comment by mbobrovskyi** [comment]
Integration passed 3/5

/test pull-kueue-test-integration-main

**Comment by mbobrovskyi** [comment]
Integration passed 4/5

/test pull-kueue-test-integration-main

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/controller/jobs/job/job_controller_test.go]: I'm surprised still that you need to set the base to 2s. Could you double check if the base=1s results in flakes? Maybe it was due to some other changes? Maybe post the diff for the conditions.

**Comment by mbobrovskyi** [comment]
Integration passed 5/5

/test pull-kueue-test-integration-main

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go]: Unfortunately, not enough 1s. Increased to 2s.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/controller/jobs/job/job_controller_test.go]: Thanks for pointing out where the timeout happens. Now I understand, this is because we assert that `Requeued=False` just after eviction, and we only have `BackoffBaseSeconds` for the assertion to succeed. So, setting `BackoffBaseSeconds` to 2s (or 3s) makes sense. 

I also think we could split this `It` into two, with two different values for `BackoffBaseSeconds`. One large, which will be used to assert that `Requeued=False`, and one short to assert that `Requeued=True`. Similarly as we do the timeouts [here](https://github.com/kubernetes-sigs/kueue/blob/main/test/integration/scheduler/podsready/scheduler_test.go#L129). However, it sounds more involving so we can probably wait until we have more test case scenarios needing the specific configs.

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 5]
```diff
@@ -1896,7 +1896,7 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler", ginkgo.Orde
 	})
 })
 
-var _ = ginkgo.Describe("Job controller interacting with scheduler when waitForPodsReady enabled", ginkgo.Ordered, ginkgo.ContinueOnFailure, func() {
+var _ = ginkgo.Describe("Job controller interacting with Workload controller when waitForPodsReady enabled", ginkgo.Ordered, ginkgo.ContinueOnFailure, func() {
```
Comment (mimowo) [inline test/integration/controller/jobs/job/job_controller_test.go:1899]:
```suggestion
var _ = ginkgo.Describe("Job controller interacting with Workload controller when waitForPodsReady with requeuing strategy is enabled", ginkgo.Ordered, ginkgo.ContinueOnFailure, func() {
```
nit

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 6]
```diff
@@ -1957,13 +1958,14 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler when waitForP
 			wl := &kueue.Workload{}
```
Comment (mimowo) [inline test/integration/controller/jobs/job/job_controller_test.go:1958]: Please also rename the `It` above: "should requeued after job status ready" -> "should re-queue a workload evicted due to PodsReady timeout after the backoff elapses"

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go]: I propose to make it on follow up.

**Comment by mimowo** [comment]
/lgtm
/approve
Thanks! Feel free to follow up with the splitting idea in https://github.com/kubernetes-sigs/kueue/pull/2161#discussion_r1595141135, but consider it low priority, we can delay until we still observe flakes.
