### PR TITLE
Changed logic of pods ready cond

### LINKED ISSUE #886: Flaky test TestWaitForPodsReadyCancelled
**What happened**:
Test failed during PR #878, retry worked.
**What you expected to happen**:
The test to succeed.
**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/878/pull-kueue-test-unit-main/1671583007175086080
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by stuton**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Trying to solve race condition when context is done

#### Which issue(s) this PR fixes:

Fixes #886

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/cache/cache.go [hunk 1]
```diff
@@ -220,18 +220,35 @@ func (c *Cache) WaitForPodsReady(ctx context.Context) {
...
+		defer c.Unlock()
+		defer close(ch)
+		c.podsReadyCond.Wait()
+		ch <- struct{}{}
+	}
+
+	podsReadyCondCh := make(chan any)
+
 	for {
 		if c.podsReadyForAllAdmittedWorkloads(ctx) {
```
Comment (alculquicondor) [inline pkg/cache/cache.go:235]: it doesn't look like this function needs the `ctx`. We can pass a the `log` instead.
You can do it in this PR.

**Review by alculquicondor — COMMENTED** [review]
This looks very complicated :)

I think the bug is that `CleanUpOnContext` doesn't obtain the lock before calling broadcast.

File: pkg/cache/cache.go [hunk 2]
```diff
@@ -220,18 +220,35 @@ func (c *Cache) WaitForPodsReady(ctx context.Context) {
...
+
+	podsReadyCond := func(ch chan any) {
+		c.Lock()
+		defer c.Unlock()
+		defer close(ch)
+		c.podsReadyCond.Wait()
+		ch <- struct{}{}
+	}
+
+	podsReadyCondCh := make(chan any)
```
Comment (tenzen-y) [inline pkg/cache/cache.go:232]:
```suggestion
	podsReadyCondCh := make(chan struct{})
	defer close(podsReadyCondCh)
```

Can we use `struct{}` typed to reduce the amount of memory?
Also, should we close this channel?

Comment (stuton) [reply pkg/cache/cache.go]: sure, changed to struct type. Yeah, the channel is already closed [inside goroutine](https://github.com/kubernetes-sigs/kueue/pull/915/files#diff-964e351ee2375d359c78d69e514c4edc42577219761c4475f391ed2daf715e51R128)

Comment (tenzen-y) [reply pkg/cache/cache.go]: > the channel is already closed inside goroutine

Ah, I see. I missed the line. Also, we shouldn't call `defer` inside the infinity loop since the memory is caused by the `defer`.

So, your code looks good, thanks!

File: pkg/cache/cache.go [hunk 3]
```diff
@@ -117,38 +118,46 @@ func (c *Cache) WaitForPodsReady(ctx context.Context) {
...
-	c.Lock()
-	defer c.Unlock()
-
 	log := ctrl.LoggerFrom(ctx)
+
+	podsReadyCond := func(ch chan struct{}) {
+		c.Lock()
+		c.podsReadyCond.Wait()
+		c.Unlock()
+		close(ch)
```
Comment (tenzen-y) [inline pkg/cache/cache.go:127]:
```suggestion
		c.Lock()
		defer c.Unlock()
		defer close(ch)		
		c.podsReadyCond.Wait()
```

@stuton Should we use `defer` to catch panic?

File: pkg/cache/cache.go [hunk 4]
```diff
@@ -117,38 +118,46 @@ func (c *Cache) WaitForPodsReady(ctx context.Context) {
 		return
 	}
 
-	c.Lock()
-	defer c.Unlock()
-
 	log := ctrl.LoggerFrom(ctx)
```
Comment (tenzen-y) [inline pkg/cache/cache.go:121]: Can you address @alculquicondor's comment?

Comment (tenzen-y) [reply pkg/cache/cache.go:121]: nvm
Sorry, this is my misunderstanding.

File: pkg/cache/cache.go (hunk 3 above)
Comment (stuton) [reply pkg/cache/cache.go]: Yeah, you right

File: pkg/cache/cache.go [hunk 5]
```diff
@@ -117,38 +118,46 @@ func (c *Cache) WaitForPodsReady(ctx context.Context) {
...
+
+	podsReadyCond := func(ch chan struct{}) {
```
[the remark this answers is not in the document]
Comment (stuton) [reply pkg/cache/cache.go:123]: yes, the main problem is in the default case in a select statement, it becomes non-blocking and when context is canceled exactly after of passing the first condition of select, but before calling the function 'Wait'. If we put the channel instead of default case we'll wait until it could receive 'close' from podsReadyCondCh.

File: pkg/cache/cache.go [hunk 6]
```diff
@@ -121,11 +122,13 @@ func (c *Cache) WaitForPodsReady(ctx context.Context) {
 	defer c.Unlock()
 
 	log := ctrl.LoggerFrom(ctx)
+
```
Comment (trasc) [inline pkg/cache/cache.go:125]: nit: remove

File: pkg/cache/cache.go [hunk 7]
```diff
@@ -121,11 +122,13 @@ func (c *Cache) WaitForPodsReady(ctx context.Context) {
...
 	for {
-		if c.podsReadyForAllAdmittedWorkloads(ctx) {
+		if c.podsReadyForAllAdmittedWorkloads(log) {
 			return
 		}
 		log.V(3).Info("Blocking admission as not all workloads are in the PodsReady condition")
+
```
Comment (trasc) [inline pkg/cache/cache.go:131]: nit: remove

**Review by alculquicondor — COMMENTED** [review]
/approve
/hold cancel
