### PR TITLE
[Fair Sharing] Fix Rounding Bug

### LINKED ISSUE #6774: [FS] Workloads submitted to 0 weight ClusterQueue may end up in infinite preemption cycle
**What happened**:
When there are two CQs with weight 0 that point to the same Cohort, Kueue may end up in an infinite cycle of preemption. This is because the DRS share is always `maxInt`, no matter how many Workloads are submitted/preempted to a given CQ

I've also reproduced this with a different configuration by setting CQs' weights to a large number (10mils) so CQ's `.weightedShare` doesnt change after preemption. This seems to be the core of the issue

**What you expected to happen**:
No infinite preemption cycle

**How to reproduce it (as minimally and precisely as possible)**:
Manifest for queue's hierarchy:

```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-flavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: Cohort
metadata:
  name: "top-cohort"
spec:
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 8
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "best-effort-cq-a"
spec:
  namespaceSelector: {}
  cohort: "top-cohort"
  fairSharing:
      weight: "0"  #1
  preemption:
    reclaimWithinCohort: Any
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 0
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "best-effort-cq-b"
spec:
  namespaceSelector: {}
  cohort: "top-cohort"
  fairSharing:
    weight: "0"  #1
  preemption:
    reclaimWithinCohort: Any
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 0
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "best-effort-lq-a"
spec:
  clusterQueue: "best-effort-cq-a"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "best-effort-lq-b"
spec:
  clusterQueue: "best-effort-cq-b"
```

Job manifest: 
```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: best-effort-b-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: best-effort-lq-b
spec:
  parallelism: 1
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: alpine
        command: ["/bin/sleep", "infinity"]
        resources:
          requests:
            cpu: 4
      restartPolicy: Never
```

1. Submit 2 jobs to the CQ-A
2. Submit a job to the CQ-B
3. Observe that only one job from CQ-A is running and there's infinite preemption cycle between the second job from CQ-A and the job from CQ-B 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by gabesaba**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We fix two FairSharing bugs:
1) Lack of precision when dividing integers in FairSharing. This is especially relevant to ClusterQueues/Cohorts with high FairSharing Weight, or large quotas
2) ClusterQueues/Cohorts with weight 0 infinite preemption loop.

#### Which issue(s) this PR fixes:
Fixes #6774

Potentially fixes https://github.com/kubernetes-sigs/kueue/issues/4247, though we should discuss there whether we want to surface a more precise value in metrics/status

See also https://github.com/kubernetes-sigs/kueue/issues/6577. This builds upon https://github.com/kubernetes-sigs/kueue/pull/6617, removing the 1 DRS special case, while still passing the unit tests introduced in that PR.

#### Special notes for your reviewer:

1) Please apply extra scrutiny to the use of `float64`.
2) Please note the change in logging in `fair_sharing_iterator.go` @amy 
  a) Does this precision LGTY?
  b) We will log +Inf for borrowing 0 weight Cohorts/ClusterQueues. I could also log the unweightedRatio. WDYT?

#### Does this PR introduce a user-facing change?
```release-note
- Fix FairSharing bug caused by rounding (large quotas or high FairSharing weight)
- Fix zero FairSharing weight preemption loop
```

### CODE REVIEW

**Comment by mimowo** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6925/pull-kueue-test-e2e-main-1-34/1969018657983959040
```
End To End Suite: kindest/node:v1.34.0: [It] Fair Sharing when the cluster queue starts borrowing should update the ClusterQueue.status.fairSharing.weightedShare expand_less	11s
{Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/fair_sharing_test.go:114 with:
Expected
    <int32>: 0
to equal
    <int32>: 4 failed [FAILED] Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/fair_sharing_test.go:114 with:
Expected
    <int32>: 0
to equal
    <int32>: 4
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/fair_sharing_test.go:125 @ 09/19/25 12:58:44.078
}
```
This issue was only found by e2e tests. Can we also add a unit test to catch it earlier?

File: pkg/cache/scheduler/fair_sharing.go [hunk 1]
```diff
@@ -38,17 +39,81 @@ type dominantResourceShareNode interface {
...
+		return math.Inf(1)
+	}
+	return float64(d.unweightedRatio) * 1000.0 / float64(d.fairWeight.MilliValue())
+}
+
+// CompareDRS compares two DRS values. A lower value
+// indicates that the ClusterQueue/Cohort with this
+// value should be preferred for scheduling, while
+// a higher value preferred for preemption.
+func CompareDRS(a, b DRS) int {
```
Comment (mimowo) [inline pkg/cache/scheduler/fair_sharing.go:78]: Any particular reason why this is not implementing the comparable interface, like `func (a DRS) Compare(b DRS) int {`?

File: pkg/cache/scheduler/fair_sharing.go [hunk 2]
```diff
@@ -38,17 +39,81 @@ type dominantResourceShareNode interface {
...
+// DRS contains the DominantResourceShare for some
+// node, with convenence methods for precise comparison.
+type DRS struct {
+	fairWeight       *resource.Quantity
+	unweightedRatio  float64
+	dominantResource corev1.ResourceName
+}
+
+// NegativeDRS is used as a starting point for comparisons.
+func NegativeDRS() DRS {
```
Comment (mimowo) [inline pkg/cache/scheduler/fair_sharing.go:51]: nit/question, maybe more natural to make it `func (a DRS) Negate() DRS`?

File: pkg/cache/scheduler/fair_sharing.go [hunk 3]
```diff
@@ -38,17 +39,81 @@ type dominantResourceShareNode interface {
...
+func (d DRS) IsZero() bool {
+	return d.unweightedRatio == 0
+}
+
+func (d DRS) PreciseWeightedShare() float64 {
+	if d.IsZero() {
+		return 0.0
+	}
+	if d.fairWeight.IsZero() {
+		return math.Inf(1)
```
Comment (mimowo) [inline pkg/cache/scheduler/fair_sharing.go:69]: Is this just for logging purposes or might be use for comparison too?

Worth adding a comment to clarify, it looks very magical.

File: pkg/cache/scheduler/fair_sharing.go (hunk 2 above)
Comment (gabesaba) [reply pkg/cache/scheduler/fair_sharing.go:51]: I can make this change. Honestly, I dislike this `NegativeDRS` altogether, it feels hacky. After this merges, I may do a refactor to make it not necessary.

File: pkg/cache/scheduler/fair_sharing.go (hunk 1 above)
Comment (gabesaba) [reply pkg/cache/scheduler/fair_sharing.go:78]: I tried both, and this one was less verbose, especially in `strategy.go`

File: pkg/cache/scheduler/fair_sharing.go (hunk 3 above)
Comment (gabesaba) [reply pkg/cache/scheduler/fair_sharing.go:69]: I think the only branch that will hit it in the end is logging, since we only call PreciseWeightedShare otherwise when both weights are > 0

I'll add a comment

File: pkg/cache/scheduler/fair_sharing.go (hunk 2 above)
Comment (mimowo) [reply pkg/cache/scheduler/fair_sharing.go:51]: Not a blocker by any means, I was just thinking it might be better interface, but Im not convinced it is worth the time.Up to you

File: pkg/cache/scheduler/fair_sharing.go (hunk 1 above)
Comment (mimowo) [reply pkg/cache/scheduler/fair_sharing.go:78]: ack

**Comment by gabesaba** [comment]
> This issue was only found by e2e tests. Can we also add a unit test to catch it earlier?

Sure, once I root cause. I'm at a loss for what is happening, as this is not even a scenario with competition for scheduling or preemption, and the line that is failing has to do with admission, not DRS
https://github.com/kubernetes-sigs/kueue/blob/bdbcd30e87564cefcb1bd61e4d4e09f5bafcc1c0/test/e2e/singlecluster/fair_sharing_test.go#L114

File: pkg/scheduler/preemption/fairsharing/strategy.go [hunk 4]
```diff
@@ -16,28 +16,30 @@ limitations under the License.
...
 // LessThanOrEqualToFinalShare implements Rule S2-a in https://sigs.k8s.io/kueue/keps/1714-fair-sharing#choosing-workloads-from-clusterqueues-for-preemption
 func LessThanOrEqualToFinalShare(preemptorNewShare PreemptorNewShare, _ TargetOldShare, targetNewShare TargetNewShare) bool {
-	return int(preemptorNewShare) <= int(targetNewShare)
+	return schdcache.CompareDRS(schdcache.DRS(preemptorNewShare), schdcache.DRS(targetNewShare)) <= 0
 }
 
 // LessThanInitialShare implements rule S2-b in https://sigs.k8s.io/kueue/keps/1714-fair-sharing#choosing-workloads-from-clusterqueues-for-preemption
 func LessThanInitialShare(preemptorNewShare PreemptorNewShare, targetOldShare TargetOldShare, _ TargetNewShare) bool {
-	return int(preemptorNewShare) < int(targetOldShare)
+	return schdcache.CompareDRS(schdcache.DRS(preemptorNewShare), schdcache.DRS(targetOldShare)) < 0
```
Comment (tenzen-y) [inline pkg/scheduler/preemption/fairsharing/strategy.go:44]: Doesn't this increase the preemptions? IIUC, this new algorithm evaluates DRS as a float.
Then, the new one distinguishes between `1.1 < 1.2` and `1.0 < 1.0`.
Before this PR, `1.1 < 1.2` will not trigger the preemption because each drs is rounded down to `1`.
But, after this PR, `1.1 < 1.2` will trigger the preemption.

My concern is that this makes friction like Wl A preempts B, after that C preempts B, then D preempts C...

Comment (mimowo) [reply pkg/scheduler/preemption/fairsharing/strategy.go:44]: I think the situation when a workload with lower DRS, but under the same bucket preempts is possible after the change indeed. However, I think this would be "corner case". I don't think this is a large scale concern actually. I even think it is more fair, even if you have DRS lower by 0.01, it is still lower, so you are in right to be running.

The way we handle the corner case currently is worse, because it leads to the infinite preemptions. 

Due to the bucketing this proof does not work, and cyclic preemptions are possible: https://github.com/kubernetes-sigs/kueue/pull/6888#discussion_r2356408373.

Comment (tenzen-y) [reply pkg/scheduler/preemption/fairsharing/strategy.go:44]: Oh, I didn't catch the notification the PR. Let me see that ...
Just for clarifications, my concerns is for mostly the situation where all DRS are mostly same.

File: pkg/cache/scheduler/fair_sharing.go (hunk 1 above)
Comment (ichekrygin) [reply pkg/cache/scheduler/fair_sharing.go:78]: It appears that `CompareDRS(...)` can still return `0`. I'm not sure if this happens only in theory or if it's encountered in practice, but based on the current implementation, it seems like a supported case.

I am probably missing more context(details) but IIUC the issue, the `0` is what leads to the preemption cycles? I wanted to clarify if that's the core of the issue.

File: pkg/scheduler/preemption/fairsharing/strategy.go (hunk 4 above)
Comment (mimowo) [reply pkg/scheduler/preemption/fairsharing/strategy.go:44]: Also note that bucketing does not really prevent the phenomenon you mentioned Yuki. We still may have a workload with DRS 0.95 (runderd to 0) preempting workload with DRS 1.05 (rounded to 1). It just makes it less likely but also harder to understand / debug.

File: pkg/cache/scheduler/cache.go [hunk 5]
```diff
@@ -707,10 +707,10 @@ func (c *Cache) Usage(cqObj *kueue.ClusterQueue) (*ClusterQueueUsageStats, error
 	}
 
 	if c.fairSharingEnabled {
-		weightedShare, _ := dominantResourceShare(cq, nil)
-		stats.WeightedShare = int64(weightedShare)
+		drs := dominantResourceShare(cq, nil)
+		weightedShare, _ := drs.roundedWeightedShare()
+		stats.WeightedShare = weightedShare
```
Comment (amy) [inline pkg/cache/scheduler/cache.go:712]: Let's make a followup github issue to change this user facing stat to a float64

File: pkg/cache/scheduler/fair_sharing.go [hunk 6]
```diff
@@ -59,30 +124,21 @@ func dominantResourceShare(node dominantResourceShareNode, wlReq resources.Flavo
...
 	}
 
-	var drs int64 = -1
-	var dRes corev1.ResourceName
-
 	lendable := calculateLendable(node.parentHRN())
 	for rName, b := range borrowing {
 		if lr := lendable[rName]; lr > 0 {
-			ratio := b * 1000 / lr
+			ratio := float64(b) * 1000.0 / float64(lr)
```
Comment (amy) [inline pkg/cache/scheduler/fair_sharing.go:133]: Also happy with float64. But want to point out its not the multiplication idea suggested by @PBundyra here: https://github.com/kubernetes-sigs/kueue/issues/6774#issuecomment-3291706679

**Comment by amy** [comment]
> > This issue was only found by e2e tests. Can we also add a unit test to catch it earlier?
> 
> Sure, once I root cause. I'm at a loss for what is happening, as this is not even a scenario with competition for scheduling or preemption, and the line that is failing has to do with admission, not DRS
> 
> https://github.com/kubernetes-sigs/kueue/blob/bdbcd30e87564cefcb1bd61e4d4e09f5bafcc1c0/test/e2e/singlecluster/fair_sharing_test.go#L114

@gabesaba Pulled down your branch to debug a little. I think this is scoped to failing to update the status somehow. When I look at controller logs for the test, I do see this `Workload successfully admitted and assigned flavors` seen here: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/scheduler/scheduler.go#L638

**Comment by amy** [comment]
@gabesaba debugged a little by pulling your branch. 

I think Kueue is successfully admitting it at some point... so the failure is at detecting the CQ status change in the test framework. Here's some sample logs from the kueue controller manager (I added prefix `hithit` for job names as a sanity check 😅 so ignore that):
```
2025-09-19T21:34:35.02938696Z stderr F 2025-09-19T21:34:35.02932171Z	LEVEL(-2)	scheduler	scheduler/scheduler.go:638	Workload successfully admitted and assigned flavors	{"schedulingCycle": 3, "workload": {"name":"job-hithitj4-5d11e","namespace":"ns-nxjkr"}, "clusterQueue": {"name":"cq1"}, "parentCohort": {"name":"cohort"}, "rootCohort": {"name":"cohort"}, "assignments": [{"name":"main","flavors":{"cpu":"rf","memory":"rf"},"resourceUsage":{"cpu":"3","memory":"600Mi"},"count":3}]}
2025-09-19T21:34:35.02938971Z stderr F 2025-09-19T21:34:35.029341585Z	DEBUG	events	recorder/recorder.go:104	Quota reserved in ClusterQueue cq1, wait time since queued was 0s	{"type": "Normal", "object": {"kind":"Workload","namespace":"ns-nxjkr","name":"job-hithitj4-5d11e","uid":"516701f0-02a9-489d-89dc-0c8987865285","apiVersion":"kueue.x-k8s.io/v1beta1","resourceVersion":"1299"}, "reason": "QuotaReserved"}
2025-09-19T21:34:35.029390377Z stderr F 2025-09-19T21:34:35.029345335Z	DEBUG	events	recorder/recorder.go:104	Admitted by ClusterQueue cq1, wait time since reservation was 0s	{"type": "Normal", "object": {"kind":"Workload","namespace":"ns-nxjkr","name":"job-hithitj4-5d11e","uid":"516701f0-02a9-489d-89dc-0c8987865285","apiVersion":"kueue.x-k8s.io/v1beta1","resourceVersion":"1299"}, "reason": "Admitted"}
2025-09-19T21:34:35.029423669Z stderr F 2025-09-19T21:34:35.029383669Z	LEVEL(-3)	jobframework/reconciler.go:743	stop walking up as the owner is not found	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"hithitj4","namespace":"ns-nxjkr"}, "namespace": "ns-nxjkr", "name": "hithitj4", "reconcileID": "d4696502-3683-4c15-84e3-1cee5b08e088", "job": "ns-nxjkr/hithitj4", "gvk": "batch/v1, Kind=Job", "currentObj": {"name":"hithitj4","namespace":"ns-nxjkr"}}
2025-09-19T21:34:35.029426169Z stderr F 2025-09-19T21:34:35.029394752Z	LEVEL(-2)	jobframework/reconciler.go:394	Reconciling Job	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"hithitj4","namespace":"ns-nxjkr"}, "namespace": "ns-nxjkr", "name": "hithitj4", "reconcileID": "d4696502-3683-4c15-84e3-1cee5b08e088", "job": "ns-nxjkr/hithitj4", "gvk": "batch/v1, Kind=Job"}
2025-09-19T21:34:35.029472044Z stderr F 2025-09-19T21:34:35.029429752Z	LEVEL(-3)	jobframework/reconciler.go:479	update reclaimable counts if implemented by the job	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"hithitj4","namespace":"ns-nxjkr"}, "namespace": "ns-nxjkr", "name": "hithitj4", "reconcileID": "d4696502-3683-4c15-84e3-1cee5b08e088", "job": "ns-nxjkr/hithitj4", "gvk": "batch/v1, Kind=Job"}
2025-09-19T21:34:35.02947446Z stderr F 2025-09-19T21:34:35.029445377Z	LEVEL(-2)	jobframework/reconciler.go:557	Job admitted, unsuspending	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"hithitj4","namespace":"ns-nxjkr"}, "namespace": "ns-nxjkr", "name": "hithitj4", "reconcileID": "d4696502-3683-4c15-84e3-1cee5b08e088", "job": "ns-nxjkr/hithitj4", "gvk": "batch/v1, Kind=Job"}
```
```
2025-09-19T21:34:35.029335377Z stderr F 2025-09-19T21:34:35.02925721Z	LEVEL(-2)	workload-reconciler	core/workload_controller.go:770	Workload update event	{"workload": {"name":"job-hithitj4-5d11e","namespace":"ns-nxjkr"}, "queue": "lq1", "status": "admitted", "prevStatus": "pending", "clusterQueue": "cq1"}
```
---
Interestingly... I do see admitted set as 4 here:
https://github.com/gabesaba/kueue/blob/ecb668d3c7a6835cc69a1d0fdf8240c46caa9c8f/pkg/cache/scheduler/cache.go#L706
```
stats := &ClusterQueueUsageStats{
  ...
  AdmittedWorkloads:  cq.admittedWorkloadsCount, // at some point hits 4 here 
}
```
---
Hmmm... I also see the admitted workload status update rapidly change from 4 -> 3 -> 0
https://github.com/gabesaba/kueue/blob/ecb668d3c7a6835cc69a1d0fdf8240c46caa9c8f/pkg/controller/core/clusterqueue_controller.go#L555
```
cq.Status.AdmittedWorkloads = int32(stats.AdmittedWorkloads)
log.Println("HIT HIT HIT actual status update", cq.Status.AdmittedWorkloads)
...
changed := meta.SetStatusCondition(&cq.Status.Conditions, metav1.Condition{...
```
My timestamps:
```
2025-09-19T22:20:24.092748631Z - 4
2025-09-19T22:20:24.097503131Z - 4
2025-09-19T22:20:26.110736216Z - 3
2025-09-19T22:20:26.117584216Z - 3
2025-09-19T22:20:27.123405299Z - 0
2025-09-19T22:20:27.134070716Z - 0
```

This code path is hit and there's no errors: 
`err := r.client.Status().Update(ctx, cq)`
https://github.com/gabesaba/kueue/blob/ecb668d3c7a6835cc69a1d0fdf8240c46caa9c8f/pkg/controller/core/clusterqueue_controller.go#L576

---
I have 3 side by side terminals:
1. running the test and extending timeout
2. `kubectl get clusterqueue -w` -> status never changes
3. `kubectl get jobs --all-namespaces -w` -> runs to completion
```
Amys-MacBook-Pro:kueue amychen$ kubectl get jobs --all-namespaces -w
NAMESPACE   NAME       STATUS    COMPLETIONS   DURATION   AGE
ns-r6wp9    hithitj1   Running   0/3                      0s
ns-r6wp9    hithitj2   Running   0/3                      0s
ns-r6wp9    hithitj3   Running   0/3                      0s
ns-r6wp9    hithitj2   Suspended   0/3                      0s
ns-r6wp9    hithitj1   Suspended   0/3                      0s
ns-r6wp9    hithitj3   Suspended   0/3                      0s
ns-r6wp9    hithitj4   Running     0/3                      0s
ns-r6wp9    hithitj4   Suspended   0/3                      0s
ns-r6wp9    hithitj2   Suspended   0/3                      0s
ns-r6wp9    hithitj3   Suspended   0/3                      0s
ns-r6wp9    hithitj4   Suspended   0/3                      0s
ns-r6wp9    hithitj2   Running     0/3           0s         0s
ns-r6wp9    hithitj4   Running     0/3           0s         0s
ns-r6wp9    hithitj3   Running     0/3           0s         0s
ns-r6wp9    hithitj1   Suspended   0/3                      0s
ns-r6wp9    hithitj1   Running     0/3           0s         0s
ns-r6wp9    hithitj1   SuccessCriteriaMet   0/3           3s         3s
ns-r6wp9    hithitj1   Complete             3/3           3s         3s
ns-r6wp9    hithitj2   SuccessCriteriaMet   0/3           3s         3s
ns-r6wp9    hithitj4   SuccessCriteriaMet   0/3           3s         3s
ns-r6wp9    hithitj3   SuccessCriteriaMet   0/3           3s         3s
ns-r6wp9    hithitj2   Complete             3/3           3s         3s
ns-r6wp9    hithitj4   Complete             3/3           3s         3s
ns-r6wp9    hithitj3   Complete             3/3           3s         3s
```
4. `kubectl get workloads -w`
```
Amys-MacBook-Pro:kueue amychen$ kubectl get workloads --all-namespaces -w
NAMESPACE   NAME                 QUEUE   RESERVED IN   ADMITTED   FINISHED   AGE
ns-f8s62    job-hithitj1-5fa5f   lq1     cq1           True       True       2m20s
ns-f8s62    job-hithitj2-be2e6   lq1     cq1           True       True       2m20s
ns-f8s62    job-hithitj3-92f78   lq1     cq1           True       True       2m20s
ns-f8s62    job-hithitj4-d3180   lq1     cq1           True       True       2m20s
```

---

so... I think if you change this, should do the trick: https://github.com/gabesaba/kueue/blob/ecb668d3c7a6835cc69a1d0fdf8240c46caa9c8f/test/e2e/singlecluster/fair_sharing_test.go#L99

`util.BehaviorExitFast` -> `util.BehaviorWaitForDeletion`

File: pkg/cache/scheduler/fair_sharing.go [hunk 7]
```diff
@@ -38,17 +39,81 @@ type dominantResourceShareNode interface {
...
+}
+
+func (d DRS) PreciseWeightedShare() float64 {
+	if d.IsZero() {
+		return 0.0
+	}
+	if d.fairWeight.IsZero() {
+		return math.Inf(1)
+	}
+	return float64(d.unweightedRatio) * 1000.0 / float64(d.fairWeight.MilliValue())
```
Comment (amy) [inline pkg/cache/scheduler/fair_sharing.go:69]: I see. So... MilliValue seems to collapse at `0.0001` based off https://github.com/kubernetes-sigs/kueue/issues/4247#issuecomment-3312129775

And resource.Quantity collapses at `1.0000000000000002e-07` (is that correct?) This one is okay for drs value. 

For weight precision, I can check in our clusters how many weights we have that go up to `0.0001`. Looks okay for now!

File: pkg/cache/scheduler/fair_sharing.go (hunk 1 above)
Comment (mimowo) [reply pkg/cache/scheduler/fair_sharing.go:78]: Yes, it might return 0, but I think this is fine. This may happen for two CQ with identical set of workloads.

However, the key issue with bucketing that it breaks `DRS_A_pending < DRS_A_admitted` (for the same workload): https://github.com/kubernetes-sigs/kueue/pull/6888#discussion_r2356408373. So with higher resolution DRS will be sensitive enough to detect that.

**Comment by gabesaba** [comment]
> @gabesaba debugged a little by pulling your branch.

Thank you, this proved extremely helpful :). The problem was that the weighted share changed from `111` to `112`. Because of the Eventually test, we started observing the AdmittedWorkloads portion fail once those workloads finished (a red herring!). I will update to `BehaviorWaitForDeletion` in a separate PR, so I can update it for all tests

edit: some tests rely on pods finishing (`BehaviorExitFast`), so will only update for FairSharing e2e test

File: pkg/cache/scheduler/fair_sharing.go (hunk 7 above)
Comment (gabesaba) [reply pkg/cache/scheduler/fair_sharing.go:69]: I changed `MilliValue` to `AsFloat64Slow`, so we at least represent FairSharing weight down to `10^-6`, rather than just  `10^-3`

**Comment by mimowo** [comment]
> I will update to BehaviorWaitForDeletion in a separate PR, so I can update it for all tests

Nice, and we can cherrypick independently

File: pkg/cache/scheduler/fair_sharing.go (hunk 6 above)
Comment (gabesaba) [reply pkg/cache/scheduler/fair_sharing.go:133]: This is still an option, but I don't see a benefit, unless we think that float precision will be a problem, which I don't. If we switch to this implementation, we will need to use [math/big](https://pkg.go.dev/math/big) to avoid any overflow bugs

File: pkg/cache/scheduler/cache.go (hunk 5 above)
Comment (gabesaba) [reply pkg/cache/scheduler/cache.go:712]: https://github.com/kubernetes-sigs/kueue/issues/6938

File: pkg/cache/scheduler/fair_sharing.go (hunk 6 above)
Comment (mimowo) [reply pkg/cache/scheduler/fair_sharing.go:133]: So, let's see:
1. float64 with division is enough for all practical cases. If we ever lack precision then the consequence is known - infinite preemption loop.
2. int64  with multiply is enough for all practical cases, but technically `weight * borrowing * lendable`  could exceed MaxInt64. The consequences of overflow are hard to predict, so we would mitigate by some check 
3. math/big with multiply is fully correct, but may have some performance penalty.

I'm ok either with (1.) or (3.).

**Review by mimowo — COMMENTED** [review]
Thank you 👍 

/lgtm
/approve
/cherrypick release-0.13
/cherrypick release-0.12

**Comment by mimowo** [comment]
> See also https://github.com/kubernetes-sigs/kueue/issues/6577. This builds upon https://github.com/kubernetes-sigs/kueue/pull/6617, removing the 1 DRS special case, while still passing the unit tests introduced in that PR.

Awesome! Nice to see "precise" values for calculations, but "Ceil" for the API which results in the 1DRS special case.

**Comment by mimowo** [comment]
FYI. I mark it tentatively as cherrypick to both 0.12 and 0.13, but I'm aware it may require manual conflict resolution. 

Let us know @amy what is the minimial version would be ok for you. Maybe 0.13+ is enough, wdyt?

Let us know @gabesaba how it is, maybe not to bad to CP to 0.12 anyway.

File: pkg/scheduler/preemption/fairsharing/strategy.go (hunk 4 above)
Comment (tenzen-y) [reply pkg/scheduler/preemption/fairsharing/strategy.go:44]: > Also note that bucketing does not really prevent the phenomenon you mentioned Yuki. We still may have a workload with DRS 0.95 (runderd to 0) preempting workload with DRS 1.05 (rounded to 1). It just makes it less likely but also harder to understand / debug.

IIUC, in that situation, the DRS 0.95 is rounded to 1 (https://github.com/kubernetes-sigs/kueue/blob/8f07b5b1599ad9585e79134d2f831bca8dd523f7/pkg/cache/scheduler/fair_sharing.go#L85)
The comparison 1 == 1 will happen, then no preemption.

Am I missing anything?

Comment (mimowo) [reply pkg/scheduler/preemption/fairsharing/strategy.go:44]: Ah, ok you are right (actually do to the hack which this PR elegantly removes)

Still there are cases where with bucketing we may fall into different buckets even if the DRS are arbitrarily close. 

Maybe 1.99 is rounded by floor as 1 while 2.01 to 2.

Same if we use traditional round:
1.49 goes to 1.0 while 1.51 goes to 2.0.

So I think the case when two workloads with close DRS preempt each other will also happen with any bucketing.

Comment (tenzen-y) [reply pkg/scheduler/preemption/fairsharing/strategy.go:44]: Yes, both approaches could cause friction.
TBH, it's hard to imagine which DRS friction case (this approach vs the first implemented approach) could happen more in a large env.

So, let's see if any additional feedback after this approach has been released.

Comment (gabesaba) [reply pkg/scheduler/preemption/fairsharing/strategy.go:44]: > > Also note that bucketing does not really prevent the phenomenon you mentioned Yuki. We still may have a workload with DRS 0.95 (runderd to 0) preempting workload with DRS 1.05 (rounded to 1). It just makes it less likely but also harder to understand / debug.
> 
> IIUC, in that situation, the DRS 0.95 is rounded to 1 (
> 
> https://github.com/kubernetes-sigs/kueue/blob/8f07b5b1599ad9585e79134d2f831bca8dd523f7/pkg/cache/scheduler/fair_sharing.go#L85
> 
> )
> The comparison 1 == 1 will happen, then no preemption.
> Am I missing anything?

With the LessThanOrEqual strategy, both rounding to 1 could cause a problem

**Comment by amy** [comment]
@mimowo 
> Let us know @amy what is the minimial version would be ok for you. Maybe 0.13+ is enough, wdyt?

yeah 13+ is good. We're moving past 12 and upgrading to 13+ due to other flavor bug fixes anyways.

**Comment by tenzen-y** [comment]
@gabesaba we will release the new v0.13 patch version same as v0.14.0. So, could you manually create cherry-pick PR by the date?

File: pkg/scheduler/preemption/fairsharing/strategy.go (hunk 4 above)
Comment (tenzen-y) [reply pkg/scheduler/preemption/fairsharing/strategy.go:44]: > With the LessThanOrEqual strategy, both rounding to 1 could cause a problem

Yes, as we discussed in this thread, it looks like both approaches have different corner cases. So, let's see if additional bugs are not reported after releasing this patch.

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
FS: Fix the following FairSharing bugs:
- Incorrect DominantResourceShare caused by rounding (large quotas or high FairSharing weight)
- Preemption loop caused by zero FairSharing weight
```
