### PR TITLE
TAS: filter irrelevant non-TAS pod updates

### LINKED ISSUE #10269: Large heap retained by zap logger clones in reconcile loops (19K-pod cluster)
**What happened**:

On a large cluster (19K pods, 1571 nodes, 277 Kueue Workloads), the kueue-controller-manager holds ~190 MB of heap from per-reconcile zap logger allocations. Top inuse allocators from `go tool pprof`:

| inuse_space | Function |
|-------------|----------|
| 60.56 MB | `go.uber.org/zap/internal/bufferpool.init.NewPool.func1` |
| 44.54 MB | `go.uber.org/zap/zapcore.(*jsonEncoder).clone` |
| 8.50 MB | `go.uber.org/zap.(*Logger).clone` |
| 77.06 MB cum | `github.com/go-logr/zapr.(*zapLogger).WithValues` |

Each reconcile calls `WithValues` which clones the logger, core, and encoder, drawing a new buffer from `bufferpool`. Under sustained throughput (~thousands of reconciles/sec across all controllers), the sync.Pool refills faster than GC drains it. The per-reconcile `reconcileID` prevents caching.

The call chain per reconcile:

```
reconcileHandler -> NewLogConstructor.func1
  -> zapr.WithValues -> zap.Logger.With -> ioCore.With
    -> jsonEncoder.Clone -> bufferpool.Get  (x2 per reconcile)
```

The default `LogConstructor` chains two `WithValues` calls (controller name, then namespace/name/reconcileID), producing two full clone-and-encode cycles per reconcile.

**What you expected to happen**:

Per-reconcile logger allocations should not dominate the heap profile (~190 MB at this scale).

**How to reproduce it (as minimally and precisely as possible)**:

On a cluster with >= 15K pods and Kueue managing >= 200 workloads:

1. Enable pprof (`pprofBindAddress: :8083` in the ConfigMap)
2. At steady state, capture the heap profile:
   ```
   kubectl port-forward -n kueue-system pod/<kueue-pod> 8083:8083
   go tool pprof -inuse_space http://localhost:8083/debug/pprof/heap
   ```
3. Run `top 20`. The top allocators are `bufferpool`, `jsonEncoder.clone`, and `zapr.WithValues`.

**Proposed fix: cache the base logger per controller**

Override `LogConstructor` to cache the controller-level logger at setup and call `WithValues` once per reconcile instead of twice:

```go
controllerLogger := baseLogger.WithValues("controller", name) // once at setup
opts.LogConstructor = func(req *reconcile.Request) logr.Logger {
    if req == nil {
        return controllerLogger
    }
    return controllerLogger.WithValues(
        "namespace", req.Namespace,
        "name", req.Name,
        "reconcileID", uuid.NewUUID(),
    )
}
```

This halves per-reconcile encoder clones and can be implemented entirely within Kueue. For broader improvement, `go-logr/zapr` could expose `WithLazy` ([zap v1.26.0+](https://github.com/uber-go/zap/pull/1319)), and controller-runtime could consolidate its `WithValues` chain ([#1290](https://github.com/kubernetes-sigs/controller-runtime/issues/1290)).

**Anything else we need to know?**:

In our case the highest-throughput controller was `NonTasUsageReconciler` (TAS), reconciling all 19K pods. Disabling `TopologyAwareScheduling` dropped zap-related heap from ~190 MB to ~1 MB. The problem affects any high-throughput controller at scale.

Related upstream issues:
- [uber-go/zap#1348](https://github.com/uber-go/zap/issues/1348) -- proposes mutable cores to avoid clone overhead (open)
- [uber-go/zap#1319](https://github.com/uber-go/zap/pull/1319) -- `WithLazy` merged in v1.26.0; defers field encoding until first write
- [controller-runtime#1290](https://github.com/kubernetes-sigs/controller-runtime/issues/1290) -- `WithValues` bypasses `KubeAwareEncoder` (open)
- [kueue#3818](https://github.com/kubernetes-sigs/kueue/issues/3818) -- high memory at 90K jobs; root cause was cache retention, not loggers

**Environment**:
- Kubernetes version: v1.31.x (GKE)
- Kueue version: v0.16.2
- controller-runtime: v0.22.4
- go.uber.org/zap: v1.27.1
- Cloud provider: GKE (19K pods, 1571 nodes)

### PR DESCRIPTION
**Pull request by MatteoFari**
#### What type of PR is this?
/kind bug
/area tas

#### What this PR does / why we need it:
Filters Pod updates that do not matter in NonTasUsageReconciler.

Before this change, the controller reconciled every update for scheduled non-TAS Pods. Now it only reconciles when a non-TAS Pod gets scheduled, moves to a different node, or finishes. 
#### Which issue(s) this PR fixes:

Fixes #10269

#### Does this PR introduce a user-facing change?

```release-note
TAS: reduce the churn on the TAS-enabled controller, called NonTasUsageReconciler, by skipping triggering
of the Reconcile on Pod changes which are irrelevant from the controller point-of-view.
```

### CODE REVIEW

File: pkg/controller/tas/non_tas_usage_controller.go [hunk 1]
```diff
@@ -89,8 +90,21 @@ func (r *NonTasUsageReconciler) Create(e event.TypedCreateEvent[*corev1.Pod]) bo
...
+		return false
+	}
+	if oldPod.Spec.NodeName != newPod.Spec.NodeName {
+		return true
+	}
+	if !utilpod.IsTerminated(oldPod) && utilpod.IsTerminated(newPod) {
+		return true
+	}
+	return false
+}
```
Comment (mimowo) [inline pkg/controller/tas/non_tas_usage_controller.go:106]: I think this works well, so I can merge, but let me ask you an opinion about the alternative. I think the alternative will be easier to follow:

```golang
func belongsToNonTASCache(pod *corev1.Pod) bool {
	if utiltas.IsTAS(pod) {
		return false
	} else if len(pod.Spec.NodeName) == 0 {
		return false
	} else if util.IsTerminated(pod) {
        return false
    }
	return true
}
```

Then:

Create: `return belongsToNonTASCache(newPod)`
Update: `return belongsToNonTASCache(oldPod) !=  belongsToNonTASCache(newPod)`
Delete: `return belongsToNonTASCache(oldPod)`

So basically in this way the Create and Delete are just special cases for Update, because in case of Create we can assume `belongsToNonTASCache(oldPod=nil) = false`, and in case of Delete analogously `belongsToNonTASCache(newPod=nil) = false`, so the other needs to be true.

cc let me also cc @gabesaba who worked on the original impl.

**Comment by mimowo** [comment]
/test pull-kueue-test-integration-baseline-main
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10488/pull-kueue-test-integration-baseline-main/2044336373787267072 looks like a known unrelated flake:
https://github.com/kubernetes-sigs/kueue/issues/10321

File: pkg/controller/tas/non_tas_usage_controller.go (hunk 1 above)
Comment (MatteoFari) [reply pkg/controller/tas/non_tas_usage_controller.go:106]: I think the alternative is easier to follow too.

One thing I am a bit unsure about is the case where the Pod changes from belonging to the non-TAS cache to not belonging anymore, while the new Pod is still not terminated. Right now `Reconcile` always fetches the Pod and calls `TASCache().Update(&pod, log)`, and that cache update does not enforce `belongsToNonTASCache` on its own.

So I think it is safe only if we also handle that case by deleting the Pod from the cache instead of updating it. Otherwise a transition like scheduled non-TAS -> scheduled TAS could still reconcile, but then add/update the new Pod in the cache instead of removing it.

Comment (gabesaba) [reply pkg/controller/tas/non_tas_usage_controller.go:106]: We had this discussion during the original implementation, and decided that we don't need to handle the non-TAS to TAS case: https://github.com/kubernetes-sigs/kueue/pull/8484#discussion_r2690452272

Comment (mimowo) [reply pkg/controller/tas/non_tas_usage_controller.go:106]: Indeed, but "don't need to handle" does not imply "don't handle", and my attention back then wasn't focused on the corner case.

Now looking at this it seems support that only requires  `if belongsToNonTASCache() Update else DeletePodByKey()` inside the Reconcile.

And at the expense of the single "if" we also express the intention better, so that the reader of the Reconcile function does not need to worry what is the transitioning.

Comment (gabesaba) [reply pkg/controller/tas/non_tas_usage_controller.go:106]: This sounds good to me. It mitigates cache corruption risk by explicitly handling all cases (even ones that require unexpected/adversarial user intervention)

Comment (mimowo) [reply pkg/controller/tas/non_tas_usage_controller.go:106]: @MatteoFari let's update as per https://github.com/kubernetes-sigs/kueue/pull/10488#discussion_r3085253452 + the extra "if" in the Reconcile. Feel free to still keep ShouldReconcilePodUpdate as the wrapper for the transition detection check.

**Review by mimowo — COMMENTED** [review]
Thank you 👍 
/lgtm
/approve
/cherrypick release-0.17
/cherrypick release-0.16

**Comment by mimowo** [comment]
/release-note-edit
```release-note
TAS: reduce the churn on the TAS-enabled controller, called NonTasUsageReconciler, by skipping triggering
of the Reconcile on Pod changes which are irrelevant from the controller point-of-view.
```
