### PR TITLE
Record events when QuotaReservation and Admition take place.

### LINKED ISSUE #1392: Admitted event reported when only quota is reserved
**What happened**:

When using admission checks, and the Workload gets the QuotaReserved, we get an event:

```
Normal  Admitted  5m57s  kueue-admission  Admitted by ClusterQueue dws-cluster-queue, wait time was 0s
```

This is not accurate, as at this point the workload is not admitted.

https://github.com/kubernetes-sigs/kueue/blob/0385c104ce0dc98011a4bbd28836a9fdb466a173/pkg/scheduler/scheduler.go#L454

**What you expected to happen**:

Two events, one for when the workload gets the quota reservation and one when it gets admitted.
If admission checks are not configured (or in other words, admission happens instantly, prefer to have just one event for Admitted)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Record  different events when QuotaReservation and Admition take place.
#### Which issue(s) this PR fixes:

Fixes #1392 

#### Does this PR introduce a user-facing change?

```release-note
Added event for QuotaReserved and fixed event for Admitted to trigger when admission checks complete
```

### CODE REVIEW

File: pkg/controller/core/workload_controller.go [hunk 1]
```diff
@@ -153,7 +156,14 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 	}
 
 	if workload.SyncAdmittedCondition(&wl) {
-		return ctrl.Result{}, workload.ApplyAdmissionStatus(ctx, r.client, &wl, true)
+		if err := workload.ApplyAdmissionStatus(ctx, r.client, &wl, true); err != nil {
+			return ctrl.Result{}, err
+		}
+		if workload.IsAdmitted(&wl) {
+			waitTime := time.Since(wl.CreationTimestamp.Time)
```
Comment (alculquicondor) [inline pkg/controller/core/workload_controller.go:163]: I just realized that this is wrong sometimes. The wait time is either the CreationTimestamp or the LastTransitionTime for the WorkloadEvicted, if it exists.

File: pkg/controller/core/workload_controller_test.go [hunk 2]
```diff
@@ -290,3 +297,53 @@ func TestSyncCheckStates(t *testing.T) {
...
 	}
 }
+
+func TestReconcile(t *testing.T) {
+	cases := map[string]struct {
+		workload   *kueue.Workload
+		wantError  error
+		wantEvents []utiltesting.EventRecord
+	}{
+		"admit": {
```
Comment (alculquicondor) [inline pkg/controller/core/workload_controller_test.go:307]: Add another case where the workload is already admitted: there shouldn't be any event in that case.

File: pkg/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -1107,10 +1164,10 @@ func TestSchedule(t *testing.T) {
 
 			ctx, cancel := context.WithTimeout(ctx, queueingTimeout)
 			go qManager.CleanUpOnContext(ctx)
-			defer cancel()
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler_test.go:1110]: why change this?

File: pkg/controller/core/workload_controller_test.go (hunk 2 above)
Comment (trasc) [reply pkg/controller/core/workload_controller_test.go:307]: done

File: pkg/controller/core/workload_controller.go (hunk 1 above)
Comment (trasc) [reply pkg/controller/core/workload_controller.go]: The problem is that the evicted cond is updated when it gets the new reservation, let's add tome since reservation for"Admitted"

**Review by alculquicondor — COMMENTED** [review]
/approve

File: pkg/scheduler/scheduler_test.go [hunk 4]
```diff
@@ -1044,7 +1103,7 @@ func TestSchedule(t *testing.T) {
 				defer features.SetFeatureGateDuringTest(t, features.PartialAdmission, false)()
 			}
 			ctx, _ := utiltesting.ContextWithLog(t)
-			scheme := runtime.NewScheme()
+			//scheme := runtime.NewScheme()
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/scheduler/scheduler_test.go]: done

File: pkg/controller/core/workload_controller.go [hunk 5]
```diff
@@ -153,7 +156,15 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 	}
 
 	if workload.SyncAdmittedCondition(&wl) {
-		return ctrl.Result{}, workload.ApplyAdmissionStatus(ctx, r.client, &wl, true)
+		if err := workload.ApplyAdmissionStatus(ctx, r.client, &wl, true); err != nil {
+			return ctrl.Result{}, err
+		}
+		if workload.IsAdmitted(&wl) {
+			if c := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadQuotaReserved); c != nil {
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:163]: is this check necessary? Can a workload have the Admitted condition, but not QuotaReserved? Looking here the workload will not get Admitted condition if the quota is not reserved: https://github.com/kubernetes-sigs/kueue/blob/615dc8e42d160174962f379dd8767e95298a1457/pkg/workload/admissionchecks.go#L51C7-L51C23.

File: pkg/controller/core/workload_controller_test.go [hunk 6]
```diff
@@ -290,3 +297,63 @@ func TestSyncCheckStates(t *testing.T) {
...
+				Obj(),
+			wantEvents: []utiltesting.EventRecord{
+				{
+					Key:       types.NamespacedName{Namespace: "ns", Name: "wl"},
+					EventType: "Normal",
+					Reason:    "Admitted",
+				},
+			},
+		},
+		"admited": {
```
Comment (mimowo) [inline pkg/controller/core/workload_controller_test.go:323]:
```suggestion
		"already admitted": {
```
nit

File: pkg/scheduler/scheduler.go [hunk 7]
```diff
@@ -450,8 +451,15 @@ func (s *Scheduler) admit(ctx context.Context, e *entry, mustHaveChecks sets.Set
...
 		err := s.applyAdmission(ctx, newWorkload)
 		if err == nil {
-			waitTime := time.Since(e.Obj.CreationTimestamp.Time)
-			s.recorder.Eventf(newWorkload, corev1.EventTypeNormal, "Admitted", "Admitted by ClusterQueue %v, wait time was %.0fs", admission.ClusterQueue, waitTime.Seconds())
+			waitStarted := e.Obj.CreationTimestamp.Time
+			if c := apimeta.FindStatusCondition(e.Obj.Status.Conditions, kueue.WorkloadEvicted); c != nil {
+				waitStarted = c.LastTransitionTime.Time
+			}
+			waitTime := time.Since(waitStarted)
+			s.recorder.Eventf(newWorkload, corev1.EventTypeNormal, "QuotaReserved", "Quota reserved in ClusterQueue %v, wait time was %.0fs", admission.ClusterQueue, waitTime.Seconds())
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go:459]:
```suggestion
			s.recorder.Eventf(newWorkload, corev1.EventTypeNormal, "QuotaReserved", "Quota reserved in ClusterQueue %v, wait time since queued was %.0fs", admission.ClusterQueue, waitTime.Seconds())
```
nit

File: pkg/controller/core/workload_controller.go [hunk 8]
```diff
@@ -153,7 +156,15 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
+				r.recorder.Eventf(&wl, corev1.EventTypeNormal, "Admitted", "Admitted by ClusterQueue %v, wait time after reservation was %.0fs", wl.Status.Admission.ClusterQueue, time.Since(c.LastTransitionTime.Time).Seconds())
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:164]:
```suggestion
				r.recorder.Eventf(&wl, corev1.EventTypeNormal, "Admitted", "Admitted by ClusterQueue %v, wait time since reservation was %.0fs", wl.Status.Admission.ClusterQueue, time.Since(c.LastTransitionTime.Time).Seconds())
```
nit

File: pkg/scheduler/scheduler.go [hunk 9]
```diff
@@ -450,8 +451,15 @@ func (s *Scheduler) admit(ctx context.Context, e *entry, mustHaveChecks sets.Set
...
+			if workload.IsAdmitted(newWorkload) {
+				s.recorder.Eventf(newWorkload, corev1.EventTypeNormal, "Admitted", "Admitted by ClusterQueue %v, wait time after reservation was 0s ", admission.ClusterQueue)
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go:461]:
```suggestion
				s.recorder.Eventf(newWorkload, corev1.EventTypeNormal, "Admitted", "Admitted by ClusterQueue %v, wait time since reservation was 0s", admission.ClusterQueue)
```
nit

File: pkg/scheduler/scheduler_test.go [hunk 10]
```diff
@@ -1153,6 +1209,12 @@ func TestSchedule(t *testing.T) {
 			if diff := cmp.Diff(tc.wantInadmissibleLeft, qDumpInadmissible); diff != "" {
 				t.Errorf("Unexpected elements left in inadmissible workloads (-want,+got):\n%s", diff)
 			}
+
+			if len(tc.wantEvents) > 0 {
```
Comment (mimowo) [inline pkg/scheduler/scheduler_test.go:1213]: Can we drop this check, and always compare? It may detect us some wrong events where we didn't expect them (so we left `wantEvents empty).

**Review by mimowo — COMMENTED** [review]
LGTM overall, just a couple of nits

File: pkg/controller/core/workload_controller.go (hunk 5 above)
Comment (trasc) [reply pkg/controller/core/workload_controller.go]: fair point, done

File: pkg/controller/core/workload_controller.go (hunk 8 above)
Comment (trasc) [reply pkg/controller/core/workload_controller.go]: done

File: pkg/controller/core/workload_controller_test.go (hunk 6 above)
Comment (trasc) [reply pkg/controller/core/workload_controller_test.go]: done

File: pkg/scheduler/scheduler.go (hunk 7 above)
Comment (trasc) [reply pkg/scheduler/scheduler.go]: done

File: pkg/scheduler/scheduler.go (hunk 9 above)
Comment (trasc) [reply pkg/scheduler/scheduler.go]: done

File: pkg/scheduler/scheduler_test.go (hunk 10 above)
Comment (trasc) [reply pkg/scheduler/scheduler_test.go:1213]: There are 19 tests and 48 events to take into account , some of them might not be in a strict order ,  and not directly related to Admission/QuotaReservation.

Let's open a follow-up issue for this if necessary.

Comment (mimowo) [reply pkg/scheduler/scheduler_test.go:1213]: sgtm

**Comment by alculquicondor** [comment]
/kind bug
/remove-kind feature
/cherry-pick release-0.5
Because the existing events say "admitted", when it actually refers to quota reservation.

/release-note-edit
```release-note
Added event for QuotaReserved and fixed event for Admitted to trigger when admission checks complete
```

**Comment by alculquicondor** [comment]
/retest
(due to flaky test)

**Comment by alculquicondor** [comment]
/reopen
@trasc please prepare a cherry-pick for release-0.5
