### PR TITLE
Fix: lock cleanup broadcast to avoid missed wakeup

### LINKED ISSUE #8434: Waiting queue lock issue
May I ask…
In the sigs.k8s.io/kueue/pkg/cache/queue package, the CleanUpOnContext function does not acquire a lock on the broadcast when it is called, which may lead to conflicts.
If the waiting queue has not yet entered wait, then the Broadcast signal will be lost, causing it to remain stuck in wait.

### PR DESCRIPTION
**Pull request by yashnib**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix a potential lost-wakeup race in the waiting queue manager by ensuring CleanUpOnContext acquires the queue mutex before broadcasting on the condition variable. Previously, the broadcast could occur without holding the same lock used by cond.Wait(), allowing a waiter to miss the signal and block indefinitely during shutdown/cancellation. This change aligns the implementation with sync.Cond’s expected locking pattern and adds a regression test to catch the race and prevent future hangs.

#### Which issue(s) this PR fixes:
Fixes #8434

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @sohankunkerkar would you like to review?

File: pkg/cache/queue/manager.go [hunk 1]
```diff
@@ -704,6 +704,10 @@ func (m *Manager) UpdateWorkload(log logr.Logger, w *kueue.Workload, opts ...wor
 // Heads.
 func (m *Manager) CleanUpOnContext(ctx context.Context) {
 	<-ctx.Done()
+	// Hold the same lock used by cond.Wait to avoid lost wakeups between
+	// checking ctx.Done() in Heads and entering Wait.
```
Comment (sohankunkerkar) [inline pkg/cache/queue/manager.go:708]: The fix is correct and matches the existing pattern.

File: pkg/cache/queue/manager_test.go [hunk 2]
```diff
@@ -1492,6 +1493,43 @@ func TestHeadsCancelled(t *testing.T) {
 	}
 }
 
+// TestHeadsCancelledNoLostWakeup verifies that cancellation does not leave Heads
+// stuck in cond.Wait due to a missed broadcast from CleanUpOnContext.
+func TestHeadsCancelledNoLostWakeup(t *testing.T) {
+	ctx, _ := utiltesting.ContextWithLog(t)
+	manager := NewManager(utiltesting.NewFakeClient(), nil)
+
+	prevProcs := runtime.GOMAXPROCS(2)
```
Comment (sohankunkerkar) [inline pkg/cache/queue/manager_test.go]: Can you add a comment on this why you chose `GOMAXPROCS(2)`?

File: pkg/cache/queue/manager_test.go [hunk 3]
```diff
@@ -1492,6 +1493,43 @@ func TestHeadsCancelled(t *testing.T) {
...
+		headsCtx, cancel := context.WithCancel(ctx)
+		headsDone := make(chan []workload.Info, 1)
+
+		go manager.CleanUpOnContext(headsCtx)
+		go func() {
+			headsDone <- manager.Heads(headsCtx)
+		}()
+
+		// Increase the chance of cancellation racing with the transition to Wait.
+		for j := 0; j < 3; j++ {
```
Comment (sohankunkerkar) [inline pkg/cache/queue/manager_test.go]: `runtime.Gosched()` and `time.Sleep(0)` are scheduling hints, not ordering guarantees. I suspect the test could pass even without the fix on most runs. IOW, this lacks deterministic behavior.

File: pkg/cache/queue/manager_test.go [hunk 4]
```diff
@@ -1492,6 +1493,43 @@ func TestHeadsCancelled(t *testing.T) {
...
+		}
+		cancel()
+
+		select {
+		case heads := <-headsDone:
+			if len(heads) != 0 {
+				t.Fatalf("iteration %d: GetHeads returned elements, expected none", i)
+			}
+		case <-time.After(500 * time.Millisecond):
+			t.Fatalf("iteration %d: Heads got stuck after context cancellation", i)
```
Comment (sohankunkerkar) [inline pkg/cache/queue/manager_test.go:1524]: If this fires, the `CleanUpOnContext` goroutine from this iteration is still alive (blocked on m.Lock() or <-ctx.Done()), and Heads is stuck in `cond.Wait()`. t.Fatalf stops the test but doesn't kill those goroutines.
I feel the stale `CleanUpOnContext` goroutines from previous iterations can leak into subsequent ones.

**Comment by mimowo** [comment]
Thank you 👍 
/approve
Leaving lgtm to @sohankunkerkar

**Review by sohankunkerkar — APPROVED** [review]
Thanks!
/lgtm
