### PR TITLE
Fix "Failed Pod can be replaced in group" flaky test.

### LINKED ISSUE #2729: Flaky Test: Pod groups when Single CQ Failed Pod can be replaced in group
**What happened**:

Flaky Test for  `End To End Suite: kindest/node:v1.27.13: [It] Pod groups when Single CQ Failed Pod can be replaced in group`.

```shell
{Timed out after 5.001s.
Expected
    <v1.PodPhase>: Pending
to equal
    <v1.PodPhase>: Failed failed [FAILED] Timed out after 5.001s.
Expected
    <v1.PodPhase>: Pending
to equal
    <v1.PodPhase>: Failed
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/pod_test.go:220 @ 07/29/24 04:13:50.231
}
```

**What you expected to happen**:
It never happened any errors.

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-e2e-main-1-27/1817773432788488192

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:
To fix "Failed Pod can be replaced in group" flaky test.

#### Which issue(s) this PR fixes:

Fixes #2729

#### Special notes for your reviewer:
Sometimes kubernetes don't have time to terminate all containers and change phase from `Pending` to `Failed`. It's not scope of kueue so we can set `LongTimeout`.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/singlecluster/pod_test.go [hunk 1]
```diff
@@ -217,7 +217,7 @@ var _ = ginkgo.Describe("Pod groups", func() {
 					var p corev1.Pod
 					gomega.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(group[0]), &p)).To(gomega.Succeed())
 					return p.Status.Phase
-				}, util.Timeout, util.Interval).Should(gomega.Equal(corev1.PodFailed))
+				}, util.LongTimeout, util.Interval).Should(gomega.Equal(corev1.PodFailed))
```
Comment (mimowo) [inline test/e2e/singlecluster/pod_test.go:220]: I suspect what happens is that we may occasionally hit with SIGTERM the pod before the SIGTERM trap is registered, and then it takes by default 30s before sending SIGKILL. 
Maybe we can try first setting for this case `TerminationGracePeriod(1).` on the PodSpec and use longer timeout only if this repeats.

I agree it is not responsibility of Kueue to test kubelet, but we should also try to keep the tests executing fast, and extending the timeout may cover some possible optimizations.

Comment (mbobrovskyi) [reply test/e2e/singlecluster/pod_test.go:220]: TerminationGracePeriod(1) helped a little bit but still have this error.

Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go:220]: This is surprising. How do you tell? Did you run the test locally in a loop and it still failed?

Comment (mbobrovskyi) [reply test/e2e/singlecluster/pod_test.go:220]: Yes, I reduced resources and run test with `--until-it-fails`.

Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go:220]: I see, thank you for doing so. As you have the reproducible setup two asks to better understand the nature of the issue:
1. How often,roughly, does it happen
2. Could you check if waiting for the pod to be Running before deleting + using terminationGracwPeeiod makes it stable?

Comment (mbobrovskyi) [reply test/e2e/singlecluster/pod_test.go:220]: 1. It's about 1 of 10 is failed.
2. Yes, you right, checking for Running makes it stable.

Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go:220]: I see, thank you for the research. I don't have a strong view here. On one hand the test would run slightly faster and more predictable, on the other there is some complexity and extra code to wait for running.

I would be slightly leaning to wait for running + use terminatingGracefulPeriod in that case, so that we can compensate the complexity with a STEP comment, for example `ginkgo.By("Await for the Pod to be running to allow fast termination by Kubelet")`.

WDYT?

**Comment by mimowo** [comment]
/lgtm
/approve
Thanks!

File: test/e2e/singlecluster/pod_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/e2e/singlecluster/pod_test.go]: Yes, totally agree with you.

**Comment by mimowo** [comment]
/cherry-pick release-0.8
To make the release branch more stable.
