### PR TITLE
Wait for the prebuild workload.

### LINKED ISSUE #3051: [Flaking test] Kueue when Creating a Job With Queueing Should run with prebuilt workload
**What happened**:

The test flaked: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-e2e-main-1-28/1834993639869124608

image

**What you expected to happen**:

No flakes.

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the CI build.

**Anything else we need to know?**:

```
End To End Suite: kindest/node:v1.28.9: [It] Kueue when Creating a Job With Queueing Should run with prebuilt workload expand_less	6s
{Timed out after 5.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/e2e_test.go:185 with:
Expected
    <[]v1.OwnerReference | len:0, cap:0>: nil
to contain element matching
    <*matchers.BeComparableToMatcher | 0xc0005792c0>: {
        Expected: <v1.OwnerReference>{
            APIVersion: "",
            Kind: "",
            Name: "test-job",
            UID: "d2e2bd31-0087-4759-a306-253b308d837f",
            Controller: nil,
            BlockOwnerDeletion: nil,
        },
        Options: [
            <*cmp.pathFilter | 0xc0006aa870>{
                core: {},
                fnc: 0x633f20,
                opt: <cmp.ignore>{core: {}},
            },
        ],
    } failed [FAILED] Timed out after 5.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/e2e_test.go:185 with:
Expected
    <[]v1.OwnerReference | len:0, cap:0>: nil
to contain element matching
    <*matchers.BeComparableToMatcher | 0xc0005792c0>: {
        Expected: <v1.OwnerReference>{
            APIVersion: "",
            Kind: "",
            Name: "test-job",
            UID: "d2e2bd31-0087-4759-a306-253b308d837f",
            Controller: nil,
            BlockOwnerDeletion: nil,
        },
        Options: [
            <*cmp.pathFilter | 0xc0006aa870>{
                core: {},
                fnc: 0x633f20,
                opt: <cmp.ignore>{core: {}},
            },
        ],
    }
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/e2e_test.go:190 @ 09/14/24 16:39:35.489
}
```

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Wait for the prebuilt Workload if a Job is running before it.

#### Which issue(s) this PR fixes:

Fixes #3051

#### Special notes for your reviewer:
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3131#issuecomment-2413187780.

#### Does this PR introduce a user-facing change?

```release-note
Best effort support for scenarios when the Job is created at the same time as prebuilt workload or momentarily before the workload. In that case an error is logged to indicate that creating a Job before prebuilt-workload is outside of the intended use.
```

### CODE REVIEW

File: pkg/controller/jobframework/reconciler.go [hunk 1]
```diff
@@ -386,6 +388,10 @@ func (r *JobReconciler) ReconcileGenericJob(ctx context.Context, req ctrl.Reques
 				log.V(3).Info("Handling job with no workload found an existing workload")
 				return ctrl.Result{Requeue: true}, nil
 			}
+			if errors.Is(err, ErrPrebuildWorkloadNotFound) {
+				log.V(2).Info("Prebuilt workload not found. Requeue in 1 second.")
+				return ctrl.Result{RequeueAfter: time.Second}, nil
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:393]: Do you know if returning error works here? Having exponential backoff would be slightly better, but we can use 1s if there are some complications with it.

**Comment by mimowo** [comment]
Please also add "Fixes https://github.com/kubernetes-sigs/kueue/issues/3051" to the description.

**Comment by mbobrovskyi** [comment]
> Please also add "Fixes #3051" to the description.

IIUC correct https://github.com/kubernetes-sigs/kueue/pull/3131#issuecomment-2419065194 it's not fixing https://github.com/kubernetes-sigs/kueue/issues/3051.

**Comment by mimowo** [comment]
Hm, I thought it does, because the integration test passes. I would prefer to better understand the issue in the https://github.com/kubernetes-sigs/kueue/pull/3131#issuecomment-2419065194 comment then before merging any of the solutions.

File: pkg/controller/jobframework/reconciler.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:393]: > Do you know if returning error works here?

It works, but I think in this case we will have an infinite loop if we don't create a Workload.

Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:393]: > Having exponential backoff would be slightly better

Not sure about this. If we create a Workload, for example, after long period, we might need to wait for backoff.

Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go:393]: Yes, but on this case we have a pause at least for 1 second.

Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go:393]: I know,. Still if someone is using prevuilt workload this way it is better to leave a trace in the logs for investigation. We don't need to support this use case perfect until we have such requests from users.

**Comment by mimowo** [comment]
I would suggest, for simplicity, move forward with this PR, and:
1. Return an error (to make the delays exponential)
2. In the release note say: 'Best effort support for scenarios when the Job is created at the same time as prebuilt workload or momentarily before the workload. In that case an error is logged to indicate that creating a Job before prebuilt-workload is outside of the intended use. 
3. Update the docs for the prebuild workload annotation to say that the intended use of prebuilt workload is to create the Job once the workload is created. In other scenarios the behavior is undefined

File: pkg/controller/jobframework/reconciler.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go]: Done

**Comment by mbobrovskyi** [comment]
> I would suggest, for simplicity, move forward with this PR, and:
> 
> 1. Return an error (to make the delays exponential)
> 2. In the release note say: 'Best effort support for scenarios when the Job is created at the same time as prebuilt workload or momentarily before the workload. In that case an error is logged to indicate that creating a Job before prebuilt-workload is outside of the intended use.
> 3. Update the docs for the prebuild workload annotation to say that the intended use of prebuilt workload is to create the Job once the workload is created. In other scenarios the behavior is undefined

Done

**Comment by mimowo** [comment]
please check why the unit tests fail and adjust if ok

**Comment by mbobrovskyi** [comment]
> please check why the unit tests fail and adjust if ok

Done

**Comment by mimowo** [comment]
> Thanks, please follow up with the docs update suggestion for the label

Oh, I see it is already added [here](https://github.com/kubernetes-sigs/kueue/pull/3255/files#diff-af0c8017a30830bf4d8b35a4cf270417c300285560948cc7e3d90c2622d9feb0R118-R119). No need for follow up here.
