### PR TITLE
Integration test for preemption from AC flavors.

### LINKED ISSUE #6966: Job stuck on "invalid patch" while being preempted (in unclucky cases involving Admission Checks & "round" RAM requests)
**Reproduction steps**:

1. (Optional) Modify the config of `kueue-controller-manager`: set `spec.container.args.--zap-log-level` to 10. \
   (This is just to have more logs available)

2. Use [this config](https://pastebin.com/9PzLqqc1) - basically 1 ClusterQueue with the following setup:

   | Flavor name | CPU quota | RAM quota | AdmissionCheck |
   |-------------|-----------|-----------|----------------|
   | `flavor-ac` | 0.75      | 5G        | `sample-prov`  |
   | `flavor-2`  | 0.5       | 5G        | -              |

   The two flavors are attached to disjoint sets of nodes (using node labels). \
   The nodes are large enough to fit the Jobs specified below, with a safe margin. \
   (The AC is technically there but no action from the autoscaler is actually needed - the node pool is already large enough).

3. Create, in order, the following 2 Jobs:

   | Config                                | Job name             | CPU request | RAM request | Priority |
   |---------------------------------------|----------------------|-------------|-------------|----------|
   | [YAML](https://pastebin.com/EHVZXiZN) | sample-job-1-_xxxxx_ | 0.5         | 220M        | -        |
   | [YAML](https://pastebin.com/j1Wr4CUv) | sample-job-2-_xxxxx_ | 750m        | 220M        | 1000     |

   After creating Job1, wait for its Pod to be running. Only then create Job2.

**What happened**:

After creating Job1: 
* there's one running Pod, scheduled on the AC flavor.

After creating Job2:
* Kueue assigns Job2 to `flavor-ac`, because `flavor-2` is not large enough.
* Kueue decides to preempt Job1 from `flavor-ac` to give place for Job2.
   
  Image

* **bug:** Job1 is _stuck on being preempted_. \
  The corresponding Workload remains in the state shown in the above screenshot indefinitely. (For at least 30 minutes).
  Looking at Kueue logs (level=10) reveals an error in patching the new preempted state:

  ```
  \"message\":\"Workload.kueue.x-k8s.io \\\"job-sample-job-1-9qkhm-dfd40\\\" is invalid: [
  status.admission.podSetAssignments: Invalid value: \\\"null\\\": admission.podSetAssignments in body must be of type array: \\\"null\\\",
  status.admission.clusterQueue: Required value, \\u003cnil\\u003e: Invalid value: \\\"null\\\":
  some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
  ]\"
  ```

  (a bit more logs available [here](https://pastebin.com/FziSEY1z))

* As a result, Job1 is never scheduled again. Also, Job2 is never scheduled at all, as it keeps waiting for a successful preemption of Job1:

  Image

   So, from the user's perspective, these 2 Jobs land in a **deadlock** state.

**What you expected to happen**:

Expected outcome:

* No errors thrown by the "preempting patch" for Job1.
* Job1 successfully preempted and then re-admitted on `flavor-2` (where it fits).
* Job2 successfully running on `flavor-ac`.

**Anything else we need to know?**:

* I'm observing this deterministically - but only in rare unlucky cases (see below).
* The expected outcome does indeed happen if we are more lucky - for example, if we do _either_ of the following:
  * detach the `AdmissionCheckStrategy` from `flavor-ac`, or
  * remove RAM request from Job1, or
  * change RAM request of Job1 from `220M` to `220Mi` (!)
* I have created an integration test (available [here](https://github.com/olekzabl/kueue/blob/38eef366ed6a3e6b64b08ab8c9800abc20d5cca3/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1848-L1977), to be soon turned into a PR) which reproduces this issue, and documents a long list of cases when it does / does not happen.
  For now, the **apparent trigger** is that: 

  * `flavor-ac` uses the Admission Check, and 
  * Job1 requests RAM, and 
  * the raw byte count of its RAM request is divisible by 1000, but not equal to 1000, and not divisible by 128 000.

  (Yes, I know it sounds unbelievably weird - but please look at the test cases - they just tell it).

**Environment**:
- Kubernetes version (use `kubectl version`):
  - Client Version: v1.33.4-dispatcher
  - Kustomize Version: v5.6.0
  - Server Version: v1.33.4-gke.1134000
- Kueue version (use `git describe --tags --dirty --always`): \
  Git N/A, I used the 0.13.4 release:
  ```
  kubectl apply --server-side -f https://github.com/kubernetes-sigs/kueue/releases/download/v0.13.4/manifests.yaml
  ```
- Cloud provider or hardware configuration: \
  GKE, and specifically:
  - cluster version = nodes version = 1.33.4-gke.1134000
  - node image type = `cos_containerd`
  - `flavor-ac` based on 4 nodes of type `e2-standard-2`, with GKE autoscaler set to "4-6 nodes"
  - `flavor-2` based on 2 nodes of type `n2-standard-2`
- OS (e.g: `cat /etc/os-release`): _[unable to find out right now]_
- Kernel (e.g. `uname -a`): _[unable to find out right now]_
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by olekzabl**
#### What type of PR is this?

Adding tests, mostly to faithfully document the current Kueue behavior. \
So I guess this counts as:

/kind documentation

#### What this PR does / why we need it:

I'm adding a new integration test (parametrized, with numerous sub-cases), to document Kueue behavior around 2 recent issues related to preempting workloads which have been scheduled with an AdmissionCheck:

* For #5477, it documents that, although the `AdmissionChecks` in workload status may be in an undesired state temporarily, they ultimately get corrected by the Workload Controller.
* For #6966, it documents a surprising class of scenarios when preemption is stuck on HTTP request validation.

#### Which issue(s) this PR fixes:

For #5477, this PR may lead to closing it as WAI - or at least to decreasing its priority.

For #6966, this PR does not fix it - but it should help in diagnosing.

#### Special notes for your reviewer:

I have doubts about how this test should be ideally organized, and I'm open to feedback on this. \
The main points I'm not sure about:

1. Is it fine to have one test scenario packed with so many parameters, or should I be "more DAMP and less DRY"? \
   On one hand, I understand that too many `if`s in the test scenario can harm their readability. \
   OTOH, given that my test space already has `if`s on several independent dimensions (use RAM or not? expect success or deadlock? use AC on 1st flavor, or both, or none?) - applying "strict DAMP" would mean duplicating this test into _twelve_ separate `Describe` suites. (With more possibly to come if we invent other useful variations). This sounds like a maintenance nightmare. \
   Therefore, while I'm open for _some_ splitting and duplication, I've so far postponed it until it's actually requested in the review.

   To reduce the "deficit of DAMP" in these tests, I've tried hard to make each of the [test cases](https://github.com/kubernetes-sigs/kueue/blob/6616deae5d3068e3171e48ce53d5ab3bd6c168b2/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1998-L2131) self-explaining, mostly by introducing helper names.

2. It's a bit unusual to have integration tests documenting _unintended behavior_ (which is the case for the `stuck` family here). \
   I believe this has a clear value: it not only shows things _don't go right_, it also shows _in detail how they go wrong_ (by explicit failure expectations: [1](https://github.com/kubernetes-sigs/kueue/blob/6616deae5d3068e3171e48ce53d5ab3bd6c168b2/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1879-L1887), [2](https://github.com/kubernetes-sigs/kueue/blob/6616deae5d3068e3171e48ce53d5ab3bd6c168b2/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1903-L1911), [3](https://github.com/kubernetes-sigs/kueue/blob/6616deae5d3068e3171e48ce53d5ab3bd6c168b2/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1961-L1969), [4](https://github.com/kubernetes-sigs/kueue/blob/6616deae5d3068e3171e48ce53d5ab3bd6c168b2/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1984-L1992)). \
   Yet, this also brings disadvantages, of at least 2 kinds:
   - general mental confusion ("test passed" now means "Kueue failed", and conversely);
   - possible prevention of improvement (imagine someone _accidentally_ fixes #6966 with their PR; then that PR will be technically _blocked_ by the proposed integration test, until someone realizes that the right thing to do is just to replace `stuck` with `works` as the "expected outcome").

   I've been thinking how to address this tradeoff best. \
   One option would be to insert the `stuck` cases but commented out. Though this would count as adding dead code, also feeling unhealthy. \
   So, my best idea is to have them uncommented, but with every expectation "which we'd actually _welcome to fail_" equipped with a comment explaining this - like e.g. [here](https://github.com/kubernetes-sigs/kueue/blob/6616deae5d3068e3171e48ce53d5ab3bd6c168b2/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1907-L1909).

   Opinions on this are welcome.

3. Last, on the simple technical level, I'm not sure if this test still fits into `provisioning_test.go`, or should be rather placed in a separate file. (Or even folder?)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
/ok-to-test
/assign @PBundyra 
for the first pass

**Comment by mimowo** [comment]
@olekzabl please update the PR description to wrap the "NONE" into the release-note block. This is needed by our automation to remove the `do-not-merge/release-note-label-needed` label from the PR.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 1]
```diff
@@ -1997,119 +1997,119 @@ var _ = ginkgo.Describe("Provisioning with scheduling", ginkgo.Ordered, ginkgo.C
 		},
 		// *** TEST CASES FOR https://github.com/kubernetes-sigs/kueue/issues/5477 ***
 
-		testCase(works, firstFlavorAC, noMemory, defaultCpu),
-		testCase(works, bothAC, noMemory, defaultCpu),
+		testCase(works, firstFlavorAC, noMemory, defaultCPU),
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: nit, instead of listing the calls could you change the structure to use testCases? This is much more idiomatic in golang, see: https://go.dev/wiki/TableDrivenTests

Also, I think this is a bit too many integration tests, so while this is ok for experimentation we should reduce the number to only those capturing different execution paths.

**Comment by mimowo** [comment]
/assign @PBundyra 
ptal

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 1 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: > nit, instead of listing the calls could you change the structure to use testCases? This is much more idiomatic in golang, see: https://go.dev/wiki/TableDrivenTests

Apologies, I'm not sure if I understand.

This is a table-driven test already. (Specifically, a `ginkgo.DescribeTable`). 

My `testCase` is not a function call "run the test"; it's a tiny wrapper around `ginkgo.Entry` (just to get rid of the `nil` param).

I can replace `testCase(...)` with `ginkgo.Entry(nil, ...)` everywhere if it helps.

But is this what you meant?

Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Ah sorry, I didn't check carefully (leaving full review to @PBundyra ), so I didn't notice `testCase` is a wrapper around `ginkgo.Entry(nil, ...)`. 

> I can replace testCase(...) with ginkgo.Entry(nil, ...) everywhere if it helps.

Yes, I think I prefer to use this layer for two reasons:
1. it is surprising as not broadly used in the codebase
2. it does not supply the "description" for the entry. I think as we limit the number of test cases we should keep only those which bring functionally different scenarios, and describe each of them, emphasizing what is essential about them.

Comment (tenzen-y) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: I have strong objections for `ginkgo.Entry` here.
In case of webhook validation tests, table-driven cases could help us since the verifications are just executing CRUD objects w/o additional fat operations.

However, such these proposed test cases, those have a lot of custom operations. 
As you learned in contributor guide, the verbosity is respected rather than reusability in test.
Thus, It should be better avoiding both `ginkgo.Entry` and `testCase`.

Those should be implemented in BDD style.

Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Updates:

* I reduced the number of test cases from 109 to 21. \
  I chose them to keep "the key points of the story". \
  I'm hoping this reduction is sufficient; otherwise I'd ask for some suggestions what else to cut out.

* I replaced `testCase(...)` with `ginkgo.Entry(nil, ...)`. \
  I agree with point 1 of your rationale.

* As for point 2:

  > it does not supply the "description" for the entry

  I did my best to supply this, by:
  * introducing a "sub-language of names" to get possibly clear param descriptions like
    ```
    (stuck, bothAC, noMemory, defaultCpu)
    ```
  * using a custom description generator ([here](https://github.com/kubernetes-sigs/kueue/blob/518082aee7ee78757138e72a1723dec2fcea623a/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1991-L1993); also note the sub-stringers like [these](https://github.com/kubernetes-sigs/kueue/blob/518082aee7ee78757138e72a1723dec2fcea623a/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1620-L1634))
  * leaving plenty of comments inside the list of cases to guide the reader through their role.

  If I was to specify a unique string description next to each test case, I think it'd clutter them more than help. \
  (But if reviewers disagree with that, I'll try to adhere :)

Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: @tenzen-y 

> Thus, It should be better avoiding both ginkgo.Entry and testCase.
> Those should be implemented in BDD style.

If I was to follow this entirely, then I think I'd need to give up one of the goals of this PR. Namely: to allow a systematic verification under which circumstances the issue #6966 hits and under which it doesn't.

My findings so far is that #6966 hits under a conjunction of 3 conditions (in short: AC was used, RAM was requested, and the RAM config satisfies _some weird condition_ on the number of bytes). I was asked to send out an integration test verifying these claims. To achieve that goal, at the _very least_, I need the RAM request to be injectable as a parameter. (Because there, at least ~10 distinct values should be tested to reveal the picture).

So, thinking of the "least DRY" way that could work here, it would be 5 or 6 separate suites, with **2** of them **still parametrized**:

* Bare minimum:
  * `works, firstFlavorAC, noMemory, defaultCPU` for both #5477 and #6966
  * `works, bothAC, noMemory, defaultCPU` for 5477
  * `works, noAC, memory("5G", "200M", defaultCPU)` for 6966
  * `works, firstFlavorAC, memory("5G", PARAM), defaultCPU` for 6966 - *parametrized* with a single string
  * `stuck, firstFlavorAC, memory("5G", PARAM), defaultCPU` for 6966 - *parametrized* with a single string
* Nice to have:
  * `works, noAC, memory("5G", "200Mi"), cpu("3000", "2000")` for 6966 - to show that CPU divisible by 1000 is not problematic

TBH I'm not very happy about that perspective - because if anyone comes in X weeks and asks another research question on #6966 (what if we introduce feature Y to the picture? what if we switch the value of Z to W? etc.) - it may lead to repeated work in several of those scenarios.

But if this is agreed upon, I can refactor into this shape.

WDYT?

Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: My intuition tells me that matrix tests are great for experimentation and probing of the behavior to better understand the problem surface.However , when it comes to merging we should focus solely on the limited number of cases which trigger the unexpected behavior and describe them well. 

Matrix tests without described intention will be hard to understand in the future, for example if they fail it will be unclear if for a good or bad reason.

I will think about this more next week, but it may need to wait until 0.14 is out (Wednesday+) so that reviewers can get deeper into the issue faced.

Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: > My intuition tells me that matrix tests are great for experimentation and probing of the behavior to better understand the problem surface.However , when it comes to merging we should focus solely on the limited number of cases which trigger the unexpected behavior and describe them well.

This sounds good, as long as _merging_ indeed happens once _experimentation and probing_ is finished.

* For #5477, this is applicable: we have just [2 relevant cases](https://github.com/kubernetes-sigs/kueue/blob/518082aee7ee78757138e72a1723dec2fcea623a/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1996-L1997) which I can split & de-parametrize.

* For #6966, it's less clear.

  I'm not sure if "experimentation and probing" has already finished here. \
  While I can reduce this PR e.g. to just 1 test case for undesired behavior, I'm not sure if there won't be a need to revert this reduction later on (at least locally, for experimenting again).

  For the good, I _have sent_ out this PR in its full shape. Hence, its original state has been "officially snapshotted" in Git history, moreover, with all my test cases passing (e.g. [here](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7010/pull-kueue-test-integration-baseline-main/1971563156492783616)). \
  Now, anyone can pull & continue investigating from there, if there's a need. \
  (Up to a threat of getting outdated, but it's still a win). \
  So _now_ I'm more willing to reduce this PR than when I was _sending_ it.

  And then, in fact, even retaining just 1 `stuck` case is unhealthy in some way. \
  It'd be an integration test documenting an _undesired_ behavior, which I'm still not sure how to deal best with. (See point 2 of my initial comment on this PR).

So - maybe _now_ the best approach is to leave only [these 2 cases](https://github.com/kubernetes-sigs/kueue/blob/518082aee7ee78757138e72a1723dec2fcea623a/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1996-L1997) (split to 2 independent scenarios), and give up merging any evidence for #6966?

Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: > I'm not sure if "experimentation and probing" has already finished here.

Yes, me neither. I will look at this closer after 0.14.0 release is out. Maybe in the meanwhile @PBundyra can recommend a path.

Comment (PBundyra) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: > * For [Investigate and fix if there is a bug when workload is evicted in CQ using AdmissionCheckStrategy #5477](https://github.com/kubernetes-sigs/kueue/issues/5477), this is applicable: we have just [2 relevant cases](https://github.com/kubernetes-sigs/kueue/blob/518082aee7ee78757138e72a1723dec2fcea623a/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1996-L1997) which I can split & de-parametrize.

That's a good idea. We should decouple the two issues mentioned in the description. Let's have a separate PR that adds the two integration tests for #5477 that are implemented as other tests in BDD style. Regardless of the other issues it would be good to have them

Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: > So - maybe now the best approach is to leave only [these 2 cases](https://github.com/kubernetes-sigs/kueue/blob/518082aee7ee78757138e72a1723dec2fcea623a/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1996-L1997) (split to 2 independent scenarios), and give up merging any evidence for https://github.com/kubernetes-sigs/kueue/issues/6966?

Done.

I now have 2 `It`s which are much similar to each other - and I guess it essentially should stay so.

(Typically we could look for some expectations which are fine to be kept just in one test case - but in this case, pretty much every expectation is _story-building_, in that it ensures the following ones are executed in an appropriate context).

PTAL

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 2]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
 		})
 	})
 })
+
+var _ = ginkgo.Describe("Provisioning with scheduling", ginkgo.Ordered, ginkgo.ContinueOnFailure, func() {
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1517]: Can we consolidate existing and new tests into a single Describe block, this way the execution of test is slightly faster

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 3]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+
+				lq = testing.MakeLocalQueue("queue", ns.Name).ClusterQueue(cq.Name).Obj()
+				util.MustCreate(ctx, k8sClient, lq)
+				util.ExpectLocalQueuesToBeActive(ctx, k8sClient, lq)
+			})
+
+			ginkgo.By("submit the Job", func() {
+				jobBuilder := testingjob.MakeJob("job1", ns.Name).
+					Queue(kueue.LocalQueueName(lq.Name)).
+					Request(corev1.ResourceCPU, "500m")
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1625]: Let's stick with Workloads only, there is no need to introduce another layer (Jobs) in integration tests

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 4]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					gomega.Expect(k8sClient.Get(ctx, wl2Key, &wlObj)).Should(gomega.Succeed())
+					g.Expect(workload.Status(&wlObj)).To(gomega.BeElementOf(
+						workload.StatusQuotaReserved,
+						workload.StatusAdmitted,
+					))
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("await for the Workload to be no longer Admitted on flavor-1", func() {
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]:
```suggestion
			ginkgo.By("await for the wl1 to be no longer Admitted on flavor-1", func() {
```

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 5]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+						psa := wlObj.Status.Admission.PodSetAssignments
+						isAdmittedOnFlavor1 = len(psa) == 1 &&
+							psa[0].Flavors[corev1.ResourceCPU] == flavor1Ref
+					}
+
+					g.Expect(isAdmittedOnFlavor1).To(gomega.BeFalse())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("await for the Workload to be Admitted on flavor-2", func() {
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]:
```suggestion
			ginkgo.By("await for the wl1 to be Admitted on flavor-2", func() {
```

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 6]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+			ginkgo.By("submit a high-priority job2", func() {
+				jobBuilder := testingjob.MakeJob("job2", ns.Name).
+					Queue(kueue.LocalQueueName(lq.Name)).
+					WorkloadPriorityClass(priorityClassName).
+					Request(corev1.ResourceCPU, "750m")
+				job2 := jobBuilder.Obj()
+				util.MustCreate(ctx, k8sClient, job2)
+				ginkgo.DeferCleanup(func() {
+					util.ExpectObjectToBeDeleted(ctx, k8sClient, job2, true)
+				})
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1691]: ditto

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 7]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+				wl2Key = types.NamespacedName{Name: workloadjob.GetWorkloadNameForJob(job2.Name, job2.UID), Namespace: ns.Name}
+			})
+
+			ginkgo.By("await for wl2 to be created", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, wl2Key, &wlObj)).Should(gomega.Succeed())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("await for wl2 to have QuotaReserved or be Admitted", func() {
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Let's avoid using OR here, I think the wl2 should have just QuotaReserved here on flavor-1, as it would be Admitted only after ProvisioningRequest was set to `Provisioned`

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 8]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+
+			ginkgo.By("submit the Job", func() {
+				jobBuilder := testingjob.MakeJob("job1", ns.Name).
+					Queue(kueue.LocalQueueName(lq.Name)).
+					Request(corev1.ResourceCPU, "500m")
+				job1 := jobBuilder.Obj()
+				util.MustCreate(ctx, k8sClient, job1)
+				ginkgo.DeferCleanup(func() {
+					util.ExpectObjectToBeDeleted(ctx, k8sClient, job1, true)
+				})
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1765]: ditto

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 9]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+					gomega.Expect(k8sClient.Get(ctx, wlKey, &wlObj)).Should(gomega.Succeed())
+					g.Expect(workload.Status(&wlObj)).To(gomega.Equal(workload.StatusAdmitted))
+					g.Expect(wlObj.Status.Admission.PodSetAssignments).Should(gomega.HaveLen(1))
+
+					var expectedFlavors = map[corev1.ResourceName]kueue.ResourceFlavorReference{
+						corev1.ResourceCPU: flavor2Ref,
+					}
+					g.Expect(wlObj.Status.Admission.PodSetAssignments[0].Flavors).To(gomega.Equal(expectedFlavors))
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: I think this is redundant as we already test in previous tests, can we check if there is AdmissionCheck2 in Workload's status instead?

File: test/integration/singlecluster/controller/admissionchecks/provisioning/suite_test.go [hunk 10]
```diff
@@ -67,8 +71,40 @@ var _ = ginkgo.AfterSuite(func() {
...
+
+		if opts.runJobController {
+			var err error
+			jobReconciler, err = job.NewReconciler(
+				ctx,
+				mgr.GetClient(),
+				mgr.GetFieldIndexer(),
+				mgr.GetEventRecorderFor(constants.JobControllerName))
+			gomega.Expect(err).NotTo(gomega.HaveOccurred())
+		}
```
Comment (PBundyra) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/suite_test.go]: Can we consolidate with the if below?

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 3 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1625]: Yeah, originally I was thinking about the potential interaction with this code: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/jobframework/reconciler.go#L536-L544

However, looking at the code it does not interact with the status.admissionChecks. 

I'm ok with both approaches as both have some merit:
- Job controller + scheduler + workload controller + prov req test the entire flow making sure there are not "unexpected" players
- as we now understand thanks to the [excellent summary](https://github.com/kubernetes-sigs/kueue/issues/5477#issuecomment-3330929574) that there is no issue thanks to workload_controller, but that was far from obvious at the beginning

No strong view.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1517]: Actually, it is ok to keep the interaction with Scheduler in the dedicated Describe. This is what we are doing for example [here](https://github.com/kubernetes-sigs/kueue/blob/40303177236412336043357d735493abfdb974c7/test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go#L444). I think it improves readability, the trade-off with running time is not clear to me.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 11]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+			ginkgo.By("await for the Workload to be Admitted on flavor-1", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					gomega.Expect(k8sClient.Get(ctx, wlKey, &wlObj)).Should(gomega.Succeed())
+					g.Expect(workload.Status(&wlObj)).To(gomega.Equal(workload.StatusAdmitted))
+					g.Expect(wlObj.Status.Admission.PodSetAssignments).Should(gomega.HaveLen(1))
+
+					var expectedFlavors = map[corev1.ResourceName]kueue.ResourceFlavorReference{
+						corev1.ResourceCPU: flavor1Ref,
+					}
+					g.Expect(wlObj.Status.Admission.PodSetAssignments[0].Flavors).To(gomega.Equal(expectedFlavors))
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: nit, I would inline that.

Also, `Status.Admission.PodSetAssignments` is already set on quota reservation, so I would prefer checking it there, so that it is early established we are using flavor-1. Here we can just check workload.IsAdmitted I think.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 4 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: I think this entire ginkgo.By can be dropped as the next one checks the workload is admitted to wl2. It could not be addmitted to both at the same time anyway.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 12]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					gomega.Expect(k8sClient.Get(ctx, wlKey, &wlObj)).Should(gomega.Succeed())
+					hasAc1 := false
+					for _, ac := range wlObj.Status.AdmissionChecks {
+						if ac.Name == kueue.AdmissionCheckReference(ac1.Name) {
+							hasAc1 = true
+							break
+						}
+					}
+					g.Expect(hasAc1).Should(gomega.BeFalse())
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Let's use some helper for that, maybe `admissioncheck.FindAdmissionCheck` and verfiy nil returned, or some gomega helper.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 13]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+			ginkgo.By("await for the Workload to be Admitted on flavor-1", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					gomega.Expect(k8sClient.Get(ctx, wlKey, &wlObj)).Should(gomega.Succeed())
+					g.Expect(workload.Status(&wlObj)).To(gomega.Equal(workload.StatusAdmitted))
+					g.Expect(wlObj.Status.Admission.PodSetAssignments).Should(gomega.HaveLen(1))
+
+					var expectedFlavors = map[corev1.ResourceName]kueue.ResourceFlavorReference{
+						corev1.ResourceCPU: flavor1Ref,
+					}
+					g.Expect(wlObj.Status.Admission.PodSetAssignments[0].Flavors).To(gomega.Equal(expectedFlavors))
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: inline

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 14]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+				wl2Key = types.NamespacedName{Name: workloadjob.GetWorkloadNameForJob(job2.Name, job2.UID), Namespace: ns.Name}
+			})
+
+			ginkgo.By("await for wl2 to be created", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, wl2Key, &wlObj)).Should(gomega.Succeed())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("await for wl2 to have QuotaReserved or be Admitted", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Don't use OR

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 15]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					gomega.Expect(k8sClient.Get(ctx, wl2Key, &wlObj)).Should(gomega.Succeed())
+					g.Expect(workload.Status(&wlObj)).To(gomega.BeElementOf(
+						workload.StatusQuotaReserved,
+						workload.StatusAdmitted,
+					))
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("await for the Workload to be no longer Admitted on flavor-1", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Drop this check

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 16]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+						psa := wlObj.Status.Admission.PodSetAssignments
+						isAdmittedOnFlavor1 = len(psa) == 1 &&
+							psa[0].Flavors[corev1.ResourceCPU] == flavor1Ref
+					}
+
+					g.Expect(isAdmittedOnFlavor1).To(gomega.BeFalse())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("await for the Workload to have QuotaReserved on flavor-2", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: This is not checking actually that the quota is reserved on flavor-2. Please add the assert on the `Status.Admission.PodSetAssignments`

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 17]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+			ginkgo.By("await for the Workload to be Admitted on flavor-2", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					gomega.Expect(k8sClient.Get(ctx, wlKey, &wlObj)).Should(gomega.Succeed())
+					g.Expect(workload.Status(&wlObj)).To(gomega.Equal(workload.StatusAdmitted))
+					g.Expect(wlObj.Status.Admission.PodSetAssignments).Should(gomega.HaveLen(1))
+
+					var expectedFlavors = map[corev1.ResourceName]kueue.ResourceFlavorReference{
+						corev1.ResourceCPU: flavor2Ref,
+					}
+					g.Expect(wlObj.Status.Admission.PodSetAssignments[0].Flavors).To(gomega.Equal(expectedFlavors))
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: I think this assert can be moved up into "await for the Workload to have QuotaReserved on flavor-2

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 18]
```diff
@@ -1511,3 +1513,431 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					gomega.Expect(k8sClient.Get(ctx, wlKey, &wlObj)).Should(gomega.Succeed())
+					hasAc1 := false
+					for _, ac := range wlObj.Status.AdmissionChecks {
+						if ac.Name == kueue.AdmissionCheckReference(ac1.Name) {
+							hasAc1 = true
+							break
+						}
+					}
+					g.Expect(hasAc1).Should(gomega.BeFalse())
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: As in the other case, let's use some helper to compactify.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/suite_test.go (hunk 10 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/suite_test.go]: I guess we could also eliminate the Job controller from the mix (as mentioned above). I don't have a strong opinion here, either way is fine.

**Review by mimowo — COMMENTED** [review]
Thank you, lgtm overall. It is really nice to see the issue we considered with @PBundyra a while ago is not happening here.

**Comment by mimowo** [comment]
@olekzabl I was able to repro the issue (2.) and I believe we are onto something buggy inside the api-server. Please split out the work to a separate PR (as WIP).

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 3 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1625]: Initially, I needed Jobs included to replicate #6966. \
And, if there's no strong preference against, I'd still prefer to keep Jobs here for this reason.

(Even though we agreed to remove the cases & parameters for replicating #6966 from this PR, @mimowo still asked me to prepare another draft PR with at least 1 test case replicating it. \
Because we may still need to play with that. \
And now, as I'm not yet sure if that PR is going to be ever merged - or just floating to be patched when necessary - I'd prefer that PR not to include "bringing back Jobs into test setup", if possible, as that would complicate the "floating patch" noticeably).

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 6 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1691]: I understand it's about including Jobs in the test setup. \
If so, ack that it happens also here; let's continue discussing in the original comment. \
I'll resolve here.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 8 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1765]: same as above; ack; resolving

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 11 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Moved as suggested, and inlined.

However, when _just inlining_, I got a line of 132 characters; felt too long. \
So I introduced a local var `psa` instead; I'm hoping that's fine.

https://github.com/kubernetes-sigs/kueue/blob/0ecfc5e78596cba1b0d8e34dc466ed49c96c0230/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1780-L1784

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 7 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Good point; it's a relict from the parametrized version. \
Done.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 4 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Removed.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 5 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Done.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 12 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Done.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 13 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Same story as in the [above comment](https://github.com/kubernetes-sigs/kueue/pull/7010/files/4ede7872988f5b6c2e2a876fd7b7b977d77c36b8#r2399524212).

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 14 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Done.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 15 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Done.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 16 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Done, PTAL

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 17 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: I would do it - however, I followed [another suggestion](https://github.com/kubernetes-sigs/kueue/pull/7010/files/4ede7872988f5b6c2e2a876fd7b7b977d77c36b8#r2399070137) from @PBundyra and removed the QuotaReserved step. \
And then, I chose to keep this here.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 18 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: Done.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 9 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: > I think this is redundant as we already test in previous tests

I'd feel safer driving the story until wl1 gets Admitted. \
If so, then not all of this is redundant, as I still need to await creation of the ProvisioningRequest, and fake its "provisioned" status. \
As a result, I removed the "await for QuotaReserved" - that one could be considered redundant & playing no story-building role.

> can we check if there is AdmissionCheck2 in Workload's status instead?

Added this as a separate `ginkgo.By` step.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/suite_test.go (hunk 10 above)
Comment (olekzabl) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/suite_test.go]: Consolidated. (I once tried it & failed. But now it works).

Not yet removing (as discussed in [this thread](https://github.com/kubernetes-sigs/kueue/pull/7010/files/4ede7872988f5b6c2e2a876fd7b7b977d77c36b8#r2399024532)).

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 1 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go]: lgtm overall, thanks for adjusting. We can continue investigation of the issue for which you proposed the matrix in a separate PR.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 3 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1625]: > Initially, I needed Jobs included to replicate #6966.

Indeed, once I played with the tests I understand why Job controller is important for replicating the other issue. 

I'm on board to keep it.

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Thank you for the test 👍 And I'm super happy working on the test helped to uncover https://github.com/kubernetes-sigs/kueue/issues/6966

Let's work on deeper understanding for that, and hopefully fixing.

**Comment by mimowo** [comment]
/cherrypick release-0.14
/cherrypick release-0.13
This is just a test, so no risk. It can be useful if cherrypicked, for avoiding future merge conflicts, when we follow up fixing the other issue.
