### PR TITLE
Fix MultiKueue admission check stuck pending for pod groups

### LINKED ISSUE #5891: MultiKueue the admission check remains Pending and workload is not Admitted for Pod integration
**What happened**:

When using Pod groups with MultiKueue the admission check remains "Pending", and the workload does not get the "Admitted" condition.

This misleading for cluster admins, because it does not show the workload as "Admitted". 

```
NAME                                    QUEUE        RESERVED IN     ADMITTED   FINISHED   AGE
workload.kueue.x-k8s.io/sample-group1   user-queue   cluster-queue              True       5m52s
workload.kueue.x-k8s.io/sample-group2   user-queue   cluster-queue              True       5m42s
```

This also means that the metrics for workloads are not accounted correctly (don't count running workloads as admitted). Further, WaitForPodsReady does not work.

**What you expected to happen**:

The workload is marked as "Admitted", and the admission check as "Ready".

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup multikueue environment as https://kueue.sigs.k8s.io/docs/tasks/manage/setup_multikueue/
2. Create a pod group as follows:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  generateName: sample-leader-
  labels:
    kueue.x-k8s.io/queue-name: user-queue
    kueue.x-k8s.io/pod-group-name: "sample-group1"
  annotations:
    kueue.x-k8s.io/pod-group-total-count: "3"
spec:
  restartPolicy: Never
  containers:
  - name: sleep
    image: busybox
    command: ["sh", "-c", 'echo "hello world from the leader pod" && sleep 60']
    resources:
      requests:
        cpu: 1
        memory: "1Gi"
---
apiVersion: v1
kind: Pod
metadata:
  generateName: sample-worker1-
  labels:
    kueue.x-k8s.io/queue-name: user-queue
    kueue.x-k8s.io/pod-group-name: "sample-group1"
  annotations:
    kueue.x-k8s.io/pod-group-total-count: "3"
spec:
  restartPolicy: Never
  containers:
  - name: sleep
    image: busybox
    command: ["sh", "-c", 'echo "hello world from the worker pod" && sleep 60']
    resources:
      requests:
        cpu: 1
        memory: "1Gi"
---
apiVersion: v1
kind: Pod
metadata:
  generateName: sample-worker2-
  labels:
    kueue.x-k8s.io/queue-name: user-queue
    kueue.x-k8s.io/pod-group-name: "sample-group1"
  annotations:
    kueue.x-k8s.io/pod-group-total-count: "3"
spec:
  restartPolicy: Never
  containers:
  - name: sleep
    image: busybox
    command: ["sh", "-c", 'echo "hello world from the worker pod" && sleep 60']
    resources:
      requests:
        cpu: 1
        memory: "1Gi"
```

**Anything else we need to know?**:

The culprit is here: https://github.com/kubernetes-sigs/kueue/blob/d15581acbb5ebb10de1db19f4bec4495c022d3e1/pkg/controller/jobs/pod/pod_multikueue_adapter.go#L90

This is probably not marked as false, because otherwise, when the workload was admitted, the Pod scheduling gate is removed.

One potential solution should be to just skip deleting the feature gate in the pod_controller code https://github.com/kubernetes-sigs/kueue/blob/d15581acbb5ebb10de1db19f4bec4495c022d3e1/pkg/controller/jobs/pod/pod_controller.go#L1373 when the workload has a multiKueue Admission check in its status.

Alternatively we could introduce a dedicated scheduling gate, such as "multikueue", but this seems more involving and not necessary.

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fixes MultiKueue admission check remaining stuck in Pending state for pod groups. The pod's `KeepAdmissionCheckPending()` was returning true, preventing the admission check from transitioning to Ready when the workload got reservation on a worker cluster. This caused the workload to never show Admitted: True.

#### Which issue(s) this PR fixes:

Fixes #5891 

#### Does this PR introduce a user-facing change?

```release-note
MultiKueue: fix the bug that for Pod integration the AdmissionCheck status would be kept Pending indefinitely,
even when the Pods are already running.

The analogous fix is also done for the batch/Job when the MultiKueueBatchJobWithManagedBy feature gate  is disabled.
```

### CODE REVIEW

File: pkg/controller/jobs/pod/pod_controller.go [hunk 1]
```diff
@@ -259,6 +260,16 @@ func (p *Pod) Suspend() {
...
 
+	wlName := p.workloadName()
+	wl := &kueue.Workload{}
+	if err := c.Get(ctx, types.NamespacedName{Name: wlName, Namespace: p.pod.Namespace}, wl); err == nil {
+		if ac, _ := admissioncheck.GetMultiKueueAdmissionCheck(ctx, c, wl); ac != nil {
+			log.V(2).Info("Workload has MultiKueue admission check, skipping local pod ungating",
+				"workload", klog.KObj(wl), "admissionCheck", ac.Name)
+			return nil
+		}
+	}
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/pod/pod_controller.go]: Can we move it to Skip()?

File: pkg/controller/jobs/pod/pod_controller.go [hunk 2]
```diff
@@ -259,6 +260,16 @@ func (p *Pod) Suspend() {
 func (p *Pod) Run(ctx context.Context, c client.Client, podSetsInfo []podset.PodSetInfo, recorder record.EventRecorder, msg string) error {
 	log := ctrl.LoggerFrom(ctx)
 
+	wlName := p.workloadName()
+	wl := &kueue.Workload{}
+	if err := c.Get(ctx, types.NamespacedName{Name: wlName, Namespace: p.pod.Namespace}, wl); err == nil {
+		if ac, _ := admissioncheck.GetMultiKueueAdmissionCheck(ctx, c, wl); ac != nil {
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/pod/pod_controller.go]: Please check if feature gate enabled.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 3]
```diff
@@ -259,6 +260,16 @@ func (p *Pod) Suspend() {
...
+			log.V(2).Info("Workload has MultiKueue admission check, skipping local pod ungating",
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/pod/pod_controller.go]: Is it enough to check? Do we need to check is it exists on ClusterQueue?

File: pkg/controller/jobs/pod/pod_controller.go (hunk 2 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_controller.go]: Done.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 1 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_controller.go]: Not sure if we should move it. Skip is usually used to skip reconciliation, but in this case we don’t want to skip reconciliation, only the pod ungating. Also, moving it to Skip would require adding a client to the Pod struct.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 3 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_controller.go]: I don't think it's needed. `GetMultiKueueAdmissionCheck()` checks `wl.Status.AdmissionChecks`, which, as I understand, is populated based on the ClusterQueue configuration where the workload is queued. 

So if the admission check exists in the workload status, it means the ClusterQueue has that admission check configured.

Comment (mbobrovskyi) [reply pkg/controller/jobs/pod/pod_controller.go]: Ah, you right. Thank you!

File: pkg/controller/jobs/pod/pod_controller.go [hunk 4]
```diff
@@ -259,6 +260,18 @@ func (p *Pod) Suspend() {
 func (p *Pod) Run(ctx context.Context, c client.Client, podSetsInfo []podset.PodSetInfo, recorder record.EventRecorder, msg string) error {
 	log := ctrl.LoggerFrom(ctx)
 
+	if features.Enabled(features.MultiKueue) {
+		wlName := p.workloadName()
+		wl := &kueue.Workload{}
+		if err := c.Get(ctx, types.NamespacedName{Name: wlName, Namespace: p.pod.Namespace}, wl); err == nil {
+			if ac, _ := admissioncheck.GetMultiKueueAdmissionCheck(ctx, c, wl); ac != nil {
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/pod/pod_controller.go]: Why we are skipping error?

File: pkg/controller/jobs/pod/pod_controller.go [hunk 5]
```diff
@@ -259,6 +260,18 @@ func (p *Pod) Suspend() {
 func (p *Pod) Run(ctx context.Context, c client.Client, podSetsInfo []podset.PodSetInfo, recorder record.EventRecorder, msg string) error {
 	log := ctrl.LoggerFrom(ctx)
 
+	if features.Enabled(features.MultiKueue) {
+		wlName := p.workloadName()
+		wl := &kueue.Workload{}
+		if err := c.Get(ctx, types.NamespacedName{Name: wlName, Namespace: p.pod.Namespace}, wl); err == nil {
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/pod/pod_controller.go]: I'm wondering if we can propagate workload here instead of fetching it again.

Comment (kshalot) [inline pkg/controller/jobs/pod/pod_controller.go]: If the pod has the MultiKueue admission check, but the error is not `nil` for some reason (or in the line below), wouldn't this fall through to the regular ungating logic?

Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_controller.go]: We can pass the workload from the startJob function, which is the caller of Run, but that would require changing the ComposableJob interface. That would probably be cleaner, but it also means more changes. Is it acceptable to modify the interface? WDYT?

File: pkg/controller/jobs/pod/pod_controller.go (hunk 4 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_controller.go]: Right, I missed this. I've updated it to check the error. Thanks.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 5 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_controller.go]: Right, I've updated it to check the error and return it if err != nil, except when the error is not found.

File: pkg/controller/jobs/pod/pod_multikueue_adapter.go [hunk 6]
```diff
@@ -87,7 +87,7 @@ func (b *multiKueueAdapter) DeleteRemoteObject(ctx context.Context, remoteClient
 }
 
 func (b *multiKueueAdapter) KeepAdmissionCheckPending() bool {
-	return true
+	return false
```
Comment (olekzabl) [inline pkg/controller/jobs/pod/pod_multikueue_adapter.go:90]: Not directly related to this PR, but still let me ask, for my better understanding:
If this is the desired fix for Pods, then why wouldn't we want it also for other workload types?

AFAICS, with this fix, `KeepAdmissionCheckPending` will return `false` in all cases, except for Jobs when the `MultiKueueBatchJobWithManagedBy` FG is disabled:

https://github.com/kubernetes-sigs/kueue/blob/8839688ba32cc47f485edffb5e07463d0da18369/pkg/controller/jobs/job/job_multikueue_adapter.go#L173-L175

Does it mean that, when the FG is disabled, #5891 affects also Jobs? (Specifically: Jobs admitted on the worker via MultiKueue will show up as non-admitted in `kubectl` on the manager, confusing human users).
Or should Jobs be treated differently from Pods, for some reason?

File: pkg/controller/jobs/pod/pod_controller.go (hunk 5 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/pod/pod_controller.go]: Yeah, I think it's ok to extend interface.

File: pkg/controller/jobs/pod/pod_multikueue_adapter.go (hunk 6 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_multikueue_adapter.go:90]: That's a good point. I think you're right. When MultiKueueBatchJobWithManagedBy is disabled, we will have the same visibility issue as we do for pods. I'm going to include a fix for that scenario as well.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 7]
```diff
@@ -260,6 +260,25 @@ func (p *Pod) Suspend() {
...
 	log := ctrl.LoggerFrom(ctx)
 
+	if features.Enabled(features.MultiKueue) {
+		wlName := p.workloadName()
+		wl := &kueue.Workload{}
+		if err := client.IgnoreNotFound(c.Get(ctx, types.NamespacedName{Name: wlName, Namespace: p.pod.Namespace}, wl)); err != nil {
+			log.V(3).Info("Failed to get workload for MultiKueue check", "workload", wlName, "error", err)
+			return err
+		}
+		ac, err := admissioncheck.GetMultiKueueAdmissionCheck(ctx, c, wl)
```
Comment (kshalot) [inline pkg/controller/jobs/pod/pod_controller.go]: Should we ignore workload not found errors? I'm not really sure what it means in this case... but I think we'd expect the workload to be there, so it feels unintuitive to just move forward after this error.

Right now the execution will continue to line 270, initialize `ac, err := nil, nil` and then fall out of the block and proceed to line 282, the regular ungating logic.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 5 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_controller.go]: Done. I've modified the interface to pass the workload as an argument to the Run method.

File: pkg/controller/jobs/pod/pod_multikueue_adapter.go (hunk 6 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_multikueue_adapter.go:90]: Done. I've applied the changes for the job as well. Since, after this change, all implementations of `KeepAdmissionCheckPending` were returning false, I've removed the method from the interface to simplify the code.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 7 above)
Comment (IrvingMg) [reply pkg/controller/jobs/pod/pod_controller.go]: Since https://github.com/kubernetes-sigs/kueue/pull/8189#discussion_r2613953618, we no longer need to fetch the workload. However, I've added a log in case we receive wl == nil, similar to when the workload is not found. 

As I understand it, this scenario should not happen in Run(), but if we ever hit that unusual case, I think the safest approach is to proceed normally and ungate the pod, since we cannot ensure that it has a MultiKueue AC.

File: pkg/controller/jobs/job/job_multikueue_adapter.go [hunk 8]
```diff
@@ -170,10 +170,6 @@ func (b *multiKueueAdapter) DeleteRemoteObject(ctx context.Context, remoteClient
 	return client.IgnoreNotFound(remoteClient.Delete(ctx, &job, client.PropagationPolicy(metav1.DeletePropagationBackground)))
 }
 
-func (b *multiKueueAdapter) KeepAdmissionCheckPending() bool {
-	return !features.Enabled(features.MultiKueueBatchJobWithManagedBy)
```
Comment (olekzabl) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:174]: Let me double-check: can this be done without any change in the Job controller?

For Pods, you're changing the logic in `pod_controller.go` - so that promoting the MK AC from "Pending" to "Ready" will not prematurely activate the Pod.
So I imagined that, while touching the code here, you'd do sth analogous for Jobs (at least when the FG is disabled) - but I don't see it done.

(And, to my confusion, I saw one comment from you about moving the logic `(p *Pod) Run(...)` to somewhere else - matching what I imagined you'd do - however, that comment got later reworded, and the logic seems not moved in the end. Can you explain what happened? Or maybe I'm seeing old code due to a missing push?)

Comment (IrvingMg) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:174]: The visibility issue described in #5891 for the admitted column is fixed by making `KeepAdmissionCheckPending` return `false` (or removing it entirely). However, this change causes us to allow local pod creation in cluster queues with MultiKueue Admission Check, which is incorrect. To keep the pods "suspended," we skip pod ungating instead.

For jobs, we have two cases depending on whether the feature gate is enabled:

  - If enabled, `KeepAdmissionCheckPending` was already returning `false`, which shows the correct admitted values and also prevents local execution thanks to the job.Spec.ManagedBy field.
  - If disabled, `KeepAdmissionCheckPending` was returning `true`, which prevented local execution because the job remained suspended, but we hit the visibility issue described in #5891, as you pointed out.

So with this fix, making `KeepAdmissionCheckPending` always return `false`, you're right: I'm fixing the visibility issue when the feature gate is disabled, but missing a check to prevent local execution. In this scenario, with the feature gate disabled, there's no mechanism to prevent it.

I got mixed up by the various scenarios, but I've updated it to include the check for jobs as well. Thanks!

File: pkg/controller/jobframework/reconciler.go [hunk 9]
```diff
@@ -1139,11 +1140,25 @@ func (r *JobReconciler) startJob(ctx context.Context, job GenericJob, object cli
...
 
+	log := ctrl.LoggerFrom(ctx)
+
 	if cj, implements := job.(ComposableJob); implements {
-		if err := cj.Run(ctx, r.client, info, r.record, msg); err != nil {
+		if err := cj.Run(ctx, r.client, info, r.record, msg, wl); err != nil {
 			return err
 		}
 	} else {
+		if !features.Enabled(features.MultiKueueBatchJobWithManagedBy) {
```
Comment (kshalot) [inline pkg/controller/jobframework/reconciler.go]: The `features.MultiKueueBatchJobWithManagedBy` check was previously only performed for `batch/Job` and now IIUC it also impact all other workloads except `Pod`. Or am I missing something?

Comment (kshalot) [inline pkg/controller/jobframework/reconciler.go]: Shouldn't `features.Enabled(features.MultiKueue)` be checked as well?

File: pkg/controller/jobframework/reconciler.go [hunk 10]
```diff
@@ -1139,11 +1140,25 @@ func (r *JobReconciler) startJob(ctx context.Context, job GenericJob, object cli
...
+			skip, err := admissioncheck.ShouldSkipLocalExecution(ctx, r.client, wl)
+			if err != nil {
+				log.V(3).Info("Failed to check for MultiKueue admission check", "workload", klog.KObj(wl), "error", err)
+				return err
+			}
+			if skip {
+				log.V(3).Info("Workload has MultiKueue admission check, skipping local job start", "workload", klog.KObj(wl))
+				return nil
+			}
+		}
```
Comment (kshalot) [inline pkg/controller/jobframework/reconciler.go:1160]: This logic and the logic in the pod controller look identical, I'm wondering whether it wouldn't be cleaner to have this check in a single place, before `cj, implements := job.(ComposableJob)` - a block that checks whether we are in the context of MultiKueue and on the manager cluster (skip in that case, otherwise perform the "regular" logic).

File: pkg/controller/jobframework/reconciler.go (hunk 9 above)
Comment (IrvingMg) [reply pkg/controller/jobframework/reconciler.go]: Right, this should impact only batch/job. I've added a check.

Comment (IrvingMg) [reply pkg/controller/jobframework/reconciler.go]: Done.

File: pkg/controller/jobframework/reconciler.go (hunk 10 above)
Comment (IrvingMg) [reply pkg/controller/jobframework/reconciler.go:1160]: Done.

File: pkg/controller/jobs/job/job_multikueue_adapter.go (hunk 8 above)
Comment (mimowo) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:174]: Wait, don't remove it in this PR. 

First, the feature gate might be disabled still by users while in Beta.
Second, I would like to be able to backport this PR as a bugfix as it seems fairly limited in scope and no new API.

File: pkg/controller/admissionchecks/multikueue/externalframeworks/adapter.go [hunk 11]
```diff
@@ -160,13 +160,6 @@ func (a *Adapter) DeleteRemoteObject(ctx context.Context, remoteClient client.Cl
 	return client.IgnoreNotFound(remoteClient.Delete(ctx, obj, client.PropagationPolicy(metav1.DeletePropagationBackground)))
 }
 
-// KeepAdmissionCheckPending returns false,
-// indicating that admission checks should not be kept pending by default.
-// This can be overridden by specific adapters if needed.
-func (a *Adapter) KeepAdmissionCheckPending() bool {
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/externalframeworks/adapter.go:166]: Yeah, I like getting rid of this function, but please don't couple to this bugfix PR, as mentioned in https://github.com/kubernetes-sigs/kueue/pull/8189/changes#r2622191492

**Review by mimowo — COMMENTED** [review]
LGTM overall

File: pkg/controller/admissionchecks/multikueue/externalframeworks/adapter.go (hunk 11 above)
Comment (IrvingMg) [reply pkg/controller/admissionchecks/multikueue/externalframeworks/adapter.go:166]: Done. I reverted this change.

File: pkg/controller/jobs/job/job_multikueue_adapter.go (hunk 8 above)
Comment (IrvingMg) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:174]: Done. I reverted the change but kept the logic to return false. Although removed from `KeepAdmissionCheckPending`,  the feature gate is still needed for https://github.com/kubernetes-sigs/kueue/blob/82e03d0fd7ea0375a90a0c0c1bb6a42224ac1f83/pkg/controller/jobframework/reconciler.go#L1146-L1148

**Comment by IrvingMg** [comment]
/retest

Due to #8254

**Comment by mbobrovskyi** [comment]
/retest

Now it should work

**Comment by mimowo** [comment]
/release-note-edit
```release-note
MultiKueue: fix the bug that for Pod integration the AdmissionCheck status would be kept Pending indefinitely, even when the Pods are already running. It also makes the analogous change for batch/Job when MultiKueueBatchJobWithManagedBy is disabled.
```

**Comment by mimowo** [comment]
/release-note-edit
```release-note
MultiKueue: fix the bug that for Pod integration the AdmissionCheck status would be kept Pending indefinitely,
even when the Pods are already running.

The analogous fix is also done for the batch/Job when the MultiKueueBatchJobWithManagedBy feature gate  is disabled.
```

**Comment by mimowo** [comment]
@IrvingMg please prepare the cherrypick manually for 0.14
