### PR TITLE
Fix e2e tests on MacOS.

### LINKED ISSUE #8638: Kueue: e2e tests hang on macOS due to incompatible Bash parameter
**What happened**:
When trying to run e2e tests on MacOS, execution gets stuck.

**What you expected to happen**:
Execution should end successfully.

**How to reproduce it (as minimally and precisely as possible)**:
I'm following the steps provided [here](https://kueue.sigs.k8s.io/docs/contribution_guidelines/testing/#running-e2e-tests-using-custom-build).
1. Run `make kind-image-build`
2. Run `make test-e2e`

**Actual behavior:**
After running step 2, execution gets stuck on step "_namespace/kueue-system serverside-applied_". It keeps in this state for hours, until user manually stops it. 

**Anything else we need to know?**:
After debugging, it was discovered that execution stops at this code point: https://github.com/kubernetes-sigs/kueue/blob/main/hack/e2e-common.sh#L360

On local tests, if we change this line from:
`build_output=${build_output//kueue-system/$KUEUE_NAMESPACE}`
to:
`build_output=$(echo "$build_output" | sed "s/kueue-system/$KUEUE_NAMESPACE/g")`
an execute the steps again, execution finishes successfully.

Looking at a PR from last year, it was checked that in the past the command used to be `build_output=$(echo "$build_output" | sed "s/kueue-system/$KUEUE_NAMESPACE/g")`. I'm not sure why it changed but, it would be good if we could add it back so execution on MacOS passes again.

[log.txt](https://github.com/user-attachments/files/24674760/log.txt)

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
ProductName:            macOS (m1)
ProductVersion:         26.2
BuildVersion:           25C56
- Kernel (e.g. `uname -a`): 
Darwin Kernel Version 25.2.0
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix e2e tests on MacOS.

#### Which issue(s) this PR fixes:

Fixes #8638

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
cc: @anahas-redhat

File: hack/e2e-common.sh [hunk 1]
```diff
@@ -357,7 +353,8 @@ function helm_install {
 function build_and_apply_kueue_manifests {
     local build_output
     build_output=$($KUSTOMIZE build "$2")
-    build_output=${build_output//kueue-system/$KUEUE_NAMESPACE}
+    # shellcheck disable=SC2001 # bash parameter substitution does not work on macOS
+    build_output=$(echo "$build_output" | sed "s/kueue-system/$KUEUE_NAMESPACE/g")
```
Comment (tenzen-y) [inline hack/e2e-common.sh:357]: Yes, the previous replacement grammar is a bash-specific extended one: https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html#:~:text=%24%7Bparameter//pattern/string%7D

So, if developers use other shells like zsh, fish... , this script might not work well.

I'm wondering if we should require all developers to use Bash for Kueue development.
But, for now, let's merge this one.
