### PR TITLE
Non-admitted workloads with QuotaReserved condition are shown as Admitted by kubectl

### LINKED ISSUE #1790: Non-admitted workloads with QuotaReserved condition are shown as Admitted by kubectl
**What happened**:

I have a workload in QuotaReserved condition, which is visible with kubectl describe:
```yaml
...
  Admission Checks:
    Last Transition Time:  2024-03-04T10:55:16Z
    Message:               
    Name:                  sample-multikueue
    State:                 Pending
  Conditions:
    Last Transition Time:  2024-03-04T10:55:16Z
    Message:               Quota reserved in ClusterQueue cluster-queue
    Reason:                QuotaReserved
    Status:                True
    Type:                  QuotaReserved
Events:
  Type    Reason         Age   From             Message
  ----    ------         ----  ----             -------
  Normal  QuotaReserved  43s   kueue-admission  Quota reserved in ClusterQueue cluster-queue, wait time since queued was 1s
```
However, the output of kubectl get suggests it is already admitted (I find this misleading):

```
> kubectl get workloads -owide                                                      
NAME                           QUEUE        ADMITTED BY     AGE
jobset-sleep-job-5xh9k-af81b   user-queue   cluster-queue   2m5s
```

**What you expected to happen**:

The output of kubectl get should clearly indicate that the workload is not admitted yet. Note that a workload may remain in the
QuotaReserved state for a long time.

One idea would be to have a new column "STATUS" which could have values: "Pending" "QuotaReserved", "Admitted".

**How to reproduce it (as minimally and precisely as possible)**:

Use admission check for ProvisioningRequest or MultiKueue, then the workload may stay in "QuotaReserved" state long enough to observe the discrepancy.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by vladikkuzn**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
* Renames "Admitted by" to "Reserving in" printed column of `kubectl get workload`
* Adds "Admitted" printed column to `kubectl get workload`

#### Which issue(s) this PR fixes:

Fixes #1790

#### Does this PR introduce a user-facing change?

```release-note
Improve the kubectl output for workloads using admission checks.
```

### CODE REVIEW

File: apis/kueue/v1beta1/workload_types.go [hunk 1]
```diff
@@ -330,9 +330,10 @@ const (
 // +kubebuilder:object:root=true
 // +kubebuilder:storageversion
 // +kubebuilder:subresource:status
-// +kubebuilder:printcolumn:name="Queue",JSONPath=".spec.queueName",type=string,description="Name of the queue this workload was submitted to"
-// +kubebuilder:printcolumn:name="Admitted by",JSONPath=".status.admission.clusterQueue",type=string,description="Name of the ClusterQueue that admitted this workload"
-// +kubebuilder:printcolumn:name="Age",JSONPath=".metadata.creationTimestamp",type=date,description="Time this workload was created"
+// +kubebuilder:printcolumn:name="Queue",JSONPath=".spec.queueName",type="string",priority=0,description="Name of the queue this workload was submitted to"
+// +kubebuilder:printcolumn:name="Reserving in",JSONPath=".status.admission.clusterQueue",type="string",priority=0,description="Name of the ClusterQueue where the workload is reserving quota"
+// +kubebuilder:printcolumn:name="Admitted",JSONPath=".status.conditions[?(@.type=='Admitted')].status",type="string",priority=10,description="Admission status"
```
Comment (mimowo) [inline apis/kueue/v1beta1/workload_types.go:335]: I think the column is important enough, for users of admission checks, to include it in the standard output.

Comment (mimowo) [inline apis/kueue/v1beta1/workload_types.go:335]: Does the syntax allow to output the time since admission, instead of True/False/Unknown, but only for admitted workloads, based on the Last transition time?

**Review by mimowo — COMMENTED** [review]
Overall lgtm.

File: apis/kueue/v1beta1/workload_types.go (hunk 1 above)
Comment (mimowo) [reply apis/kueue/v1beta1/workload_types.go]: I see, I'm ok with just True/False.

**Comment by mimowo** [comment]
/release-note-edit ```Improve the kubectl output for workloads using admission checks```

**Comment by mimowo** [comment]
/release-note-edit```
Improve the kubectl output for workloads using admission checks
```

**Comment by mimowo** [comment]
/release-note-edit ```
Improve the kubectl output for workloads using admission checks
```

**Comment by mimowo** [comment]
Ok, not sure what I do wrong :) Please update the release note manually

**Comment by tenzen-y** [comment]
/release-note-edit 

```release-note
Improve the kubectl output for workloads using admission checks
```

**Review by mimowo — COMMENTED** [review]
/lgtm
/assign @tenzen-y @alculquicondor

File: apis/kueue/v1beta1/workload_types.go [hunk 2]
```diff
@@ -330,9 +330,10 @@ const (
 // +kubebuilder:object:root=true
 // +kubebuilder:storageversion
 // +kubebuilder:subresource:status
-// +kubebuilder:printcolumn:name="Queue",JSONPath=".spec.queueName",type=string,description="Name of the queue this workload was submitted to"
-// +kubebuilder:printcolumn:name="Admitted by",JSONPath=".status.admission.clusterQueue",type=string,description="Name of the ClusterQueue that admitted this workload"
-// +kubebuilder:printcolumn:name="Age",JSONPath=".metadata.creationTimestamp",type=date,description="Time this workload was created"
+// +kubebuilder:printcolumn:name="Queue",JSONPath=".spec.queueName",type="string",description="Name of the queue this workload was submitted to"
+// +kubebuilder:printcolumn:name="Reserving in",JSONPath=".status.admission.clusterQueue",type="string",description="Name of the ClusterQueue where the workload is reserving quota"
```
Comment (tenzen-y) [inline apis/kueue/v1beta1/workload_types.go:334]:
```suggestion
// +kubebuilder:printcolumn:name="Reserved in",JSONPath=".status.admission.clusterQueue",type="string",description="Name of the ClusterQueue where the workload is reserving quota"
```

Actually, we already reserved in specific clusterQueue, and the workload has the `QuotaReserved` condition. So I'm curious about whether we should use `Reserved in`.
@mimowo WDYT?

**Comment by mimowo** [comment]
Experiment after I got the recipe from Yuki :)
/release-note-edit
\```release-note
Improve the kubectl output for workloads using admission checks.
\```

**Review by tenzen-y — COMMENTED** [review]
@vladikkuzn Could you update documentation like here?
https://github.com/kubernetes-sigs/kueue/blob/f1f0223fd9079f371bcfee143b4221821923d204/site/content/en/docs/tasks/run/run_cronjobs.md?plain=1#L78

File: apis/kueue/v1beta1/workload_types.go (hunk 2 above)
Comment (mimowo) [reply apis/kueue/v1beta1/workload_types.go:334]: I'm ok with either `Reserved` and `Reserving`. I guess `Reserved` might be less ambiguous indeed.

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Improve the kubectl output for workloads using admission checks.
```

**Comment by mimowo** [comment]
Yay, this worked: 
image

**Comment by alculquicondor** [comment]
Thanks!

/lgtm
/approve

**Comment by alculquicondor** [comment]
@tenzen-y what's your sentiment? should we attempt a manual cherry-pick?

**Comment by alculquicondor** [comment]
@vladikkuzn could you produce a manual cherry-pick?
You can use `./hack/cherry_pick-pull.sh release-0.6 1991` to get started.
