### PR TITLE
Fix SimulateWorkloadRemoval bug

### LINKED ISSUE #7015: Workloads unable to use cohort guarantees (hierarchical cohorts, fair sharing, multiple flavors.)
**What happened**:

Kueue version = 0.13.4
Featuregate: FlavorFungibilityImplicitPreferenceDefault=True

When hierarchical cohorts are used with multiple flavors, a workload is unable to schedule in a flavor where its parent cohort has guarantees (i.e. another clusterqueue in the same subtree has unused nominal quota), when capacity in the flavor is fully occupied through borrowing by another cohort.

**What you expected to happen**:

If there are unused guarantees under the parent cohort, a workload should always be able to schedule, no matter what flavor it is.

**How to reproduce it (as minimally and precisely as possible)**:

Example:
Total Size of Cluster:
- Flavor-1 = 10
- Flavor-2 = 10

Image

If we submit 18 workloads (each using resources = 1) to clusterqueue "cq-p1", we observe that it schedules 10 workloads in Flavor-1 and 8 workloads in Flavor-2. 
Next, if we submit 2 workloads (each using 1 resource) to clusterqueue "cq-p4" which is part of cohort-B, it does not schedule at all. This is bad since, it is not able to borrow within the cohort, even when there is unused capacity on the cluster. This violates the guarantees at the parent cohort level.

All clusterqueues use the following:
```
Flavor Fungibility:
    When Can Borrow:   TryNextFlavor
    When Can Preempt:  TryNextFlavor
  Namespace Selector:
  Preemption:
    Borrow Within Cohort:
      Max Priority Threshold:  80000
      Policy:                  LowerPriority
    Reclaim Within Cohort:     Any
    Within Cluster Queue:      LowerPriority
  Queueing Strategy:           BestEffortFIFO
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.32.7
- Kueue version (use `git describe --tags --dirty --always`): 0.13.4
- Feature Flag enabled: **FlavorFungibilityImplicitPreferenceDefault=True**

### PR DESCRIPTION
**Pull request by gabesaba**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
During `SimulateWorkloadRemoval`, we were removing usage from the wrong ClusterQueue. I noticed this while debugging why we were assigning a suboptimal flavor in the context of #7015.

Because of this, in certain paths (notably [PreemptionOracle](https://github.com/kubernetes-sigs/kueue/blob/50b7ed542f9aef732cdbf95eb798f18308a577cb/pkg/scheduler/preemption/preemption_oracle.go#L60-L62)), we were claiming that [borrowingLevel=0](https://github.com/kubernetes-sigs/kueue/blob/50b7ed542f9aef732cdbf95eb798f18308a577cb/pkg/scheduler/flavorassigner/flavorassigner.go#L325-L330) for `Preempt` mode, but borrowingLevel>0 for `Fit` mode (after preemption successfully completed). In combination with `FlavorFungibilityImplicitPreferenceDefault=true`, this resulted in selecting the flavor with (`Preempt`, 0) mode incorrectly (because 0 is not accurate) over the flavor in which preemption already completed (`Fit`, 1).

#### Which issue(s) this PR fixes:
Fixes #7015

#### Does this PR introduce a user-facing change?
```release-note
Fix bug in workload usage removal simulation that results in inaccurate flavor assignment
```

### CODE REVIEW

File: pkg/cache/scheduler/snapshot.go [hunk 1]
```diff
@@ -52,14 +52,31 @@ func (s *Snapshot) RemoveWorkload(wl *workload.Info) {
...
 	cq := s.ClusterQueue(wl.ClusterQueue)
 	cq.Workloads[workload.Key(wl.Obj)] = wl
 	cq.AddUsage(wl.Usage())
 }
 
+// SimulateWorkloadRemoval modifies the snapshot by removing the usage
+// corresponding to the list of workloads from workloads' respective
+// ClusterQueues. It returns a function which can be used to restore
+// this usage.
+func (s *Snapshot) SimulateWorkloadRemoval(workloads []*workload.Info) func() {
```
Comment (mimowo) [inline pkg/cache/scheduler/snapshot.go:67]: Why moving at the same time? Is the move necessary or just a drive by cleanup?

Comment (gabesaba) [reply pkg/cache/scheduler/snapshot.go:67]: since this is now a method on the snapshot, not CQ. If you prefer, I can leave there for smaller diff, and move later.

**Comment by mimowo** [comment]
I think this failure is due to https://github.com/kubernetes-sigs/kueue/issues/7078

/test pull-kueue-test-integration-multikueue-main

**Comment by mimowo** [comment]
> Fix bug in workload usage removal simulation during scheduling

@gabesaba please update the note in the user-observable terms.

**Comment by gabesaba** [comment]
> > Fix bug in workload usage removal simulation during scheduling
> 
> @gabesaba please update the note in the user-observable terms.

done.

File: pkg/cache/scheduler/snapshot.go (hunk 1 above)
Comment (mimowo) [reply pkg/cache/scheduler/snapshot.go:67]: I see, not necessarily

Comment (mimowo) [reply pkg/cache/scheduler/snapshot.go:67]: Actually, maybe better to move to make sure cherrypick is easier

Comment (mimowo) [reply pkg/cache/scheduler/snapshot.go:67]: so that maybe we can include it today

Comment (mimowo) [reply pkg/cache/scheduler/snapshot.go:67]: ah, ok you need entire snapshot to do `cq := s.ClusterQueue(w.ClusterQueue)`. Let's keep it where it is then

File: pkg/cache/scheduler/snapshot.go [hunk 2]
```diff
@@ -52,14 +52,31 @@ func (s *Snapshot) RemoveWorkload(wl *workload.Info) {
...
+	for _, w := range workloads {
```
Comment (mimowo) [inline pkg/cache/scheduler/snapshot.go:73]: I think it is safer to revert this code. 
```
	usage := make([]workload.Usage, 0, len(workloads))
	for _, w := range workloads {
		usage = append(usage, w.Usage())
	}
```
I synced with @gabesaba it is better to revert, because otherwise some controller doing eviction could change `w.Usage()` in the meanwhile. as w is a pointer

Comment (gabesaba) [reply pkg/cache/scheduler/snapshot.go:73]: Done.

**Review by mimowo — COMMENTED** [review]
/lgtm 
/approve
/cherrypick release-0.13
/cherrypick release-0.12

**Comment by mimowo** [comment]
> /cherrypick release-0.12

I think it is fair to skip in 0.12. Seems like the bug is tricky to repro (the scenario Gabe found is using FlavorFungibilityImplicitPreferenceDefault=true). And no user requested so far, this was discovered by Gabe during debugging.

**Comment by tenzen-y** [comment]
Based on discussion w/ @mimowo offline, we decided not to cherry-pick this PR to release-0.12 since it's hard to reproduce the observed bug in the situations w/o FlavorFungibilityImplicitPreferenceDefault FG.

The reproduced environments are only situations w/ FlavorFungibilityImplicitPreferenceDefault.
