### PR TITLE
don't update PodsReady condition timely

### LINKED ISSUE #7363: jobframework JobReconciler don't update PodsReady condition timely when updata status failed
**What happened**:
when enable `waitForPodsReady` feature,  submit  [batch job](https://kubernetes.io/docs/concepts/workloads/controllers/job/),  the jobframework [JobReconciler](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/jobframework/reconciler.go#L514) don't update PodsReady condition timely when update status failed, the error message is as follows
```
{"level":"error","ts":"2025-10-23T09:54:18.123509681Z","caller":"jobframework/reconciler.go:523","msg":"Updating workload status","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"k8s-job-20m-mxy","namespa
ce":"default"},"namespace":"default","name":"k8s-job-20m-mxy","reconcileID":"23c12b4b-786f-42f5-bd58-a10213f56e19","job":"default/k8s-job-20m-mxy","gvk":"batch/v1, Kind=Job","error":"Internal error occurred: failed calling webhook \"vwork
load.kb.io\": Post \"https://kueue-webhook-service.kueue-system.svc:443/validate-kueue-x-k8s-io-v1beta1-workload?timeout=10s\": dial tcp 169.169.109.130:443: connect: connection refused","stacktrace":"sigs.k8s.io/kueue/pkg/controller/jobf
ramework.(*JobReconciler).ReconcileGenericJob\n\t/Users/didi/ml/kueue/pkg/controller/jobframework/reconciler.go:523\nsigs.k8s.io/kueue/pkg/controller/jobframework.(*genericReconciler).Reconcile\n\t/Users/didi/ml/kueue/pkg/controller/jobfr
amework/reconciler.go:1522\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/Users/didi/ml/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controlle
r-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/Users/didi/ml/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:340\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Contro
ller[...]).processNextWorkItem\n\t/Users/didi/ml/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:300\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1\n\t/Users/didi
/ml/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:202"}
```
**What you expected to happen**:
set PodsReady condition to True timely when updata status failed

**How to reproduce it (as minimally and precisely as possible)**:

for example, in the above situation, access to the webhook sometimes works and sometimes doesn't.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version: master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by olderTaoist**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:

JobReconciler don't update PodsReady condition timely when updata status failed. no event triggers reconcile, need manually trigger the workload update.

#### Which issue(s) this PR fixes:

Fixes #7363

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
Thank you for the fix, lgtm, but can you think of adding a test for it?

**Comment by mimowo** [comment]
Please also update the "Does this PR introduce a user-facing change?" section to describe the fix. It will land in release notes for users.

**Comment by mimowo** [comment]
cc @PBundyra ptal

**Comment by olderTaoist** [comment]
> Thank you for the fix, lgtm, but can you think of adding a test for it?

let me think about how to write a single test. I also accidentally discovered that in our k8s environment, accessing the webhook through the service (kube-proxy) failed probabilistically, resulting in the PodReady status not being updated timely and subsequent tasks being unable to be scheduled.

File: pkg/controller/jobframework/reconciler.go [hunk 1]
```diff
@@ -514,6 +514,9 @@ func (r *JobReconciler) ReconcileGenericJob(ctx context.Context, req ctrl.Reques
 			err := workload.UpdateStatus(ctx, r.client, wl, condition.Type, condition.Status, condition.Reason, condition.Message, constants.JobControllerName, r.clock)
 			if err != nil {
 				log.Error(err, "Updating workload status")
+				return ctrl.Result{
+					RequeueAfter: 0,
+				}, err
```
Comment (PBundyra) [inline pkg/controller/jobframework/reconciler.go]:
```suggestion
				return ctrl.Result{}, client.IgnoreNotFound(err)
```

Comment (olderTaoist) [reply pkg/controller/jobframework/reconciler.go]: Done as you saied. because my use case is that when a job's podready status is false (no timeout), it will block all subsequent jobs, i wanted the Reconciler to reconcile immediately, so I didn't use the default behavior of controller-runtime.

**Comment by olderTaoist** [comment]
> Thank you for the fix, lgtm, but can you think of adding a test for it?

Done

File: pkg/controller/jobframework/reconciler.go (hunk 1 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: IIUC, the `return ctrl.Result{}, client.IgnoreNotFound(err)` will make reconciler requeue the request right away. Am I missing something?

File: pkg/controller/jobframework/reconciler_test.go [hunk 2]
```diff
@@ -714,3 +718,280 @@ func TestProcessOptions(t *testing.T) {
...
+	)
+	testCases := []struct {
+		name      string
+		workload  *kueue.Workload
+		job       jobframework.GenericJob
+		wantError error
+	}{
+		{
+			name: "update podready condition failed",
+			workload: &kueue.Workload{
```
Comment (PBundyra) [inline pkg/controller/jobframework/reconciler_test.go]: Thanks for coming up with this test. Could you please use the wrapper you can find in: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/util/testing/v1beta2/wrappers.go#L63

File: pkg/controller/jobframework/reconciler_test.go [hunk 3]
```diff
@@ -28,20 +30,26 @@ import (
...
+	"sigs.k8s.io/controller-runtime/pkg/client/interceptor"
 	"sigs.k8s.io/jobset/api/jobset/v1alpha2"
-
 	configapi "sigs.k8s.io/kueue/apis/config/v1beta2"
 	kueue "sigs.k8s.io/kueue/apis/kueue/v1beta2"
 	mocks "sigs.k8s.io/kueue/internal/mocks/controller/jobframework"
 	"sigs.k8s.io/kueue/pkg/controller/constants"
 	"sigs.k8s.io/kueue/pkg/controller/core/indexer"
+	"sigs.k8s.io/kueue/pkg/controller/jobframework"
+	. "sigs.k8s.io/kueue/pkg/controller/jobframework"
```
Comment (PBundyra) [inline pkg/controller/jobframework/reconciler_test.go]: Please remove the duplicate

File: pkg/controller/jobframework/reconciler.go (hunk 1 above)
Comment (olderTaoist) [reply pkg/controller/jobframework/reconciler.go]: when `Reconcile` return error,  controller-runtime default retry mechanism uses a rate limiter.

File: pkg/controller/jobframework/reconciler_test.go (hunk 3 above)
Comment (olderTaoist) [reply pkg/controller/jobframework/reconciler_test.go]: Done

File: pkg/controller/jobframework/reconciler_test.go [hunk 4]
```diff
@@ -714,3 +720,169 @@ func TestProcessOptions(t *testing.T) {
...
+		job       GenericJob
+		wantError error
+	}{
+		{
+			name: "update podready condition failed",
+			workload: utiltestingapi.MakeWorkload("job-test-job-podready-fail", metav1.NamespaceDefault).
+				Generation(1).UID("job-test-job-podready-fail").Finalizers(kueue.ResourceInUseFinalizerName).
+				Label(constants.JobUIDLabel, "test-job-podready-fail").ControllerReference(testGVK,
+				"test-job-podready-fail", "test-job-podready-fail").Queue(testLocalQueueName).
+				Priority(0).PodSets(kueue.PodSet{
```
Comment (PBundyra) [inline pkg/controller/jobframework/reconciler_test.go]: Can any of these fields be removed so the test is a minimal repro of the case we want to test? I'm pretty confident e.g. Priority is redundant, can we verify the rest?

Comment (olderTaoist) [reply pkg/controller/jobframework/reconciler_test.go]: already remove generation、uid and priority. 

- `OwnerReference`:  used to get workload of `GenericJob` 
- `PodSets`:  used to determine if the workload belongs to a `GenericJob`
-  the rest are all basic fields of the workload

Comment (PBundyra) [reply pkg/controller/jobframework/reconciler_test.go]: Thanks, last nits I have are:
1) Can each builder method be in a separate line so it reads better
2) Can we transform the list of test cases into map where key is the name of the test and value is the test case itself?

Comment (olderTaoist) [reply pkg/controller/jobframework/reconciler_test.go]: Done

File: pkg/controller/jobframework/reconciler_test.go [hunk 5]
```diff
@@ -707,3 +719,136 @@ func TestProcessOptions(t *testing.T) {
...
+					Message:            "The workload is admitted",
+					LastTransitionTime: metav1.NewTime(time.Now()),
+				}).
+				Condition(metav1.Condition{
+					Type:               kueue.WorkloadPodsReady,
+					Status:             metav1.ConditionFalse,
+					Reason:             kueue.WorkloadWaitForStart,
+					Message:            "Not all pods are ready or succeeded",
+					LastTransitionTime: metav1.NewTime(time.Now()),
+				}).
```
Comment (PBundyra) [inline pkg/controller/jobframework/reconciler_test.go:747]:
```suggestion
				Conditions(metav1.Condition{
					Type:               kueue.WorkloadAdmitted,
					Status:             metav1.ConditionTrue,
					Reason:             "Admitted",
					Message:            "The workload is admitted",
					LastTransitionTime: metav1.NewTime(time.Now()),
				}, metav1.Condition{
					Type:               kueue.WorkloadPodsReady,
					Status:             metav1.ConditionFalse,
					Reason:             kueue.WorkloadWaitForStart,
					Message:            "Not all pods are ready or succeeded",
					LastTransitionTime: metav1.NewTime(time.Now()),
				}).
```

`Conditions()` overwrites previous conditions while `Condition()` doesn't. Here it didn't lead to any mistakes but let's stick with one method

File: pkg/controller/jobframework/reconciler_test.go [hunk 6]
```diff
@@ -707,3 +719,136 @@ func TestProcessOptions(t *testing.T) {
...
```
Comment (PBundyra) [inline pkg/controller/jobframework/reconciler_test.go:786]: ditto

File: pkg/controller/jobframework/reconciler_test.go (hunk 5 above)
Comment (olderTaoist) [reply pkg/controller/jobframework/reconciler_test.go:747]: it's  my silly mistake, the intention was to use two condition or conditions

File: pkg/controller/jobframework/reconciler_test.go (hunk 6 above)
Comment (olderTaoist) [reply pkg/controller/jobframework/reconciler_test.go:786]: Done

**Comment by mimowo** [comment]
Looks great 👍 
/lgtm
/approve
/cherrypick release-0.14
/cherrypick release-0.13

In case @PBundyra has some additional comments. 
/hold

**Comment by PBundyra** [comment]
/hold cancel
Thank you @olderTaoist, great job!

**Comment by mimowo** [comment]
```
=== Failed
=== FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady/update_podready_condition_failed (0.06s)
    reconciler.go:316: "level"=2 "msg"="Namespace not found; skipping selector check" "job"="default/test-job-podready-fail" "gvk"="batch/v1, Kind=Job" "namespace"="default"
    reconciler_test.go:843: unexpected reconcile error want Internal error occurred: failed calling webhook got %!s(<nil>))
=== FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady (0.11s)
=== FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady/update_podready_condition_failed (0.05s)
    reconciler.go:316: "level"=2 "msg"="Namespace not found; skipping selector check" "job"="default/test-job-podready-fail" "gvk"="batch/v1, Kind=Job" "namespace"="default"
    reconciler_test.go:843: unexpected reconcile error want Internal error occurred: failed calling webhook got %!s(<nil>))
=== FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady (0.09s)
=== FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady/update_podready_condition_failed (0.04s)
    reconciler.go:316: "level"=2 "msg"="Namespace not found; skipping selector check" "job"="default/test-job-podready-fail" "gvk"="batch/v1, Kind=Job" "namespace"="default"
    reconciler_test.go:843: unexpected reconcile error want Internal error occurred: failed calling webhook got %!s(<nil>))
```
from https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7364/pull-kueue-test-unit-main/1986730061528567808
This looks related, ptal, putting on hold until investigated
/hold

**Comment by olderTaoist** [comment]
> ```
> === Failed
> === FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady/update_podready_condition_failed (0.06s)
>     reconciler.go:316: "level"=2 "msg"="Namespace not found; skipping selector check" "job"="default/test-job-podready-fail" "gvk"="batch/v1, Kind=Job" "namespace"="default"
>     reconciler_test.go:843: unexpected reconcile error want Internal error occurred: failed calling webhook got %!s(<nil>))
> === FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady (0.11s)
> === FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady/update_podready_condition_failed (0.05s)
>     reconciler.go:316: "level"=2 "msg"="Namespace not found; skipping selector check" "job"="default/test-job-podready-fail" "gvk"="batch/v1, Kind=Job" "namespace"="default"
>     reconciler_test.go:843: unexpected reconcile error want Internal error occurred: failed calling webhook got %!s(<nil>))
> === FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady (0.09s)
> === FAIL: pkg/controller/jobframework TestReconcileGenericJobWithWaitForPodsReady/update_podready_condition_failed (0.04s)
>     reconciler.go:316: "level"=2 "msg"="Namespace not found; skipping selector check" "job"="default/test-job-podready-fail" "gvk"="batch/v1, Kind=Job" "namespace"="default"
>     reconciler_test.go:843: unexpected reconcile error want Internal error occurred: failed calling webhook got %!s(<nil>))
> ```
> 
> from https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7364/pull-kueue-test-unit-main/1986730061528567808 This looks related, ptal, putting on hold until investigated /hold

the [ManagedJobsNamespaceSelectorAlwaysRespected](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/features/kube_features.go#L294) feature is enabled by default(version 0.15) in the recent merge. need create namespace as fellow:
```
managedNamespace := utiltesting.MakeNamespaceWrapper(metav1.NamespaceDefault).
				Label("managed-by-kueue", "true").
				Obj()
builder := utiltesting.NewClientBuilder(batchv1.AddToScheme, kueue.AddToScheme).
				WithObjects(tc.workload, tc.job.Object(), managedNamespace)
```

**Comment by mimowo** [comment]
This makes perfect sense, it will require a bit of tweaking when backporting, 
I think this PR classifies as a bugfix, so it would be good if you can prepare the backports, you can use the ./hack/cherry_pick_pull.sh script

/unhold
/lgtm

**Comment by mimowo** [comment]
I think this isn't really user observable thing. Or it is very hard to observe, removing from release notes.

/release-note-edit
```release-note
NONE
```
