### PR TITLE
Helm: ensure Chart version matches version in registry

### LINKED ISSUE #4928: Helm: inconsistency between version in repo and chart metadata
**What happened**:

Installing `kueue` Helm chart using Helm Terraform provider leads to errors.

**What you expected to happen**:

Installation should work as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Snippet:

```hcl
resource "helm_release" "kueue" {
  chart   = "oci://registry.k8s.io/kueue/charts/kueue"
  version = "0.11.3"

  name      = "kueue"
  namespace = "kueue-system"
  create_namespace = true
}
```

When running `terraform apply`, the Helm release turns `0.11.3` into `v0.11.3` which leads to the chart failing to download.

```
Error: could not download chart: registry.k8s.io/kueue/charts/kueue:v0.11.3: not found
```

**Anything else we need to know?**:

The issue is caused by an inconsistency between the `version` field, reported in the `Chart.yaml` and the actual version used for publishing in the OCI registry.

Example: registry uses `0.11.3` but `Chart.yaml` indicates `version: v0.11.3`

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): 0.11.3
- Cloud provider or hardware configuration: AWS/EKS
- Install tools: Terraform 1.8.2, Helm provider 2.17.0

### PR DESCRIPTION
**Pull request by j-vizcaino**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This fixes an inconsistency between Helm chart version in OCI registry and version reported by the chart metadata (`Chart.yaml`)

#### Which issue(s) this PR fixes:

Fixes #4928 

#### Special notes for your reviewer:

Tested locally

* comment the last line of the script (to prevent pushing to registry)
* run `./hack/push-chart.sh`
* go to `bin`
* extract `kueue-0.11.3.tgz`
* `cat kueue/Chart.yaml`
```
> cat Chart.yaml

```yaml
apiVersion: v2
appVersion: v0.11.3-dirty
description: Kueue is a set of APIs and controller for job queueing. It is a job-level
  manager that decides when a job should be admitted to start (as in pods can be created)
  and when it should stop (as in active pods should be deleted).
name: kueue
type: application
version: 0.11.3-dirty
```

#### Does this PR introduce a user-facing change?

No: the chart version reported in the registry stays the same (no `v` prefix); only the chart metadata is changed.

```release-note
NONE
```

### CODE REVIEW

File: hack/push-chart.sh [hunk 1]
```diff
@@ -35,7 +35,9 @@ readonly k8s_registry="registry.k8s.io/kueue"
 readonly semver_regex='^v([0-9]+)(\.[0-9]+){1,2}$'
 
 image_repository=${IMAGE_REPO}
-chart_version=${GIT_TAG}
+app_version=${GIT_TAG}
+# Strip leading v from version
+chart_version=${app_version/v/}
```
Comment (mimowo) [inline hack/push-chart.sh:40]: It seems this would strip v from any place? This can be trick to debug if we ever add sufixes to version (currently only rc). Check of we can strip only first.

Comment (j-vizcaino) [reply hack/push-chart.sh:40]: Hey, thanks, I considered that but went with the simplest approach (Bash).
`sed` can easily be leveraged to strip leading `v`, if you believe this is really an issue.

Comment (mimowo) [reply hack/push-chart.sh:40]: Would a trick like here work; https://stackoverflow.com/questions/19571391/remove-prefix-with-make?
Maybe `$(app_version:v%=%)`?

**Comment by mimowo** [comment]
cc @tenzen-y can you give it a pass?

File: hack/push-chart.sh (hunk 1 above)
Comment (j-vizcaino) [reply hack/push-chart.sh:40]: It probably would, but IIRC, the script has the ability to figure out the version automatically based on the Git tag, so I suspect it would be preferable to have the interpolation happen within the script itself rather than injected from the caller (Makefile).

Also, having this self-contained makes testing easier (just calling the script), instead of having the implicit requirement of being called from `make`.

I'll update the MR with the `sed` version today.

Comment (tenzen-y) [reply hack/push-chart.sh:40]: +1 on @mimowo 
Semantic Versioning allows us to add `v` in arbitrary place: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

If we replace every `v` with this script, this may cause a bug.

Comment (mimowo) [reply hack/push-chart.sh:40]: > it would be preferable to have the interpolation happen within the script itself rather than injected from the caller (Makefile).

Yeah, I'm not questioning that. Making the stripping inside the bash script as currently is even better. Not sure about the syntax, but surely we can figure out something.

Comment (j-vizcaino) [reply hack/push-chart.sh]: Fixed it in the latest version of the change.

Examples

```shell
$ echo v1.2.3 | sed -e 's/^v//'
1.2.3
$ echo v1.2.3+v123 | sed -e 's/^v//'
1.2.3+v123
$ echo 1.2.3+v123 | sed -e 's/^v//'
1.2.3+v123
```

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Leaving final tagging to @tenzen-y . Thanks!
/hold

**Comment by mimowo** [comment]
@j-vizcaino ptal at the failure

File: hack/push-chart.sh (hunk 1 above)
Comment (j-vizcaino) [reply hack/push-chart.sh]: CI got my back: turns out there was a magic notation to do this with Bash. Went with this solution instead.

**Comment by mimowo** [comment]
/retest
this is unrelated flake

**Review by tenzen-y — COMMENTED** [review]
LGTM
Thank you

/lgtm
/approve
/hold cancel

**Comment by tenzen-y** [comment]
@j-vizcaino could you manually open cherry-pick PR against release-0.10 and release-0.11 branches?
