### PR TITLE
Remove deleted pending workloads from the cache so the visibility API results are correct

### LINKED ISSUE #1555: A pending workload that's deleted is still listed in the visibility API `pendingworkloads` results
**What happened**:

If a pending workload is deleted, querying the visibility API stills reports the workload. 

**What you expected to happen**:

The workload should not be listed in the `pendingworkloads` sub-resource after it's deleted.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a workload such that it's going to be pending
2. Delete the job / workload
3. Query the visibility API

**Anything else we need to know?**:

Once the operator Pod is deleted / has restarted, the results are corrected.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25.3
- Kueue version (use `git describe --tags --dirty --always`): v0.6.0-devel-146-ged81667f-dirty

### PR DESCRIPTION
**Pull request by astefanutti**
This fixes #1555 and also adds an integration test as suggested in https://github.com/kubernetes-sigs/kueue/issues/1555#issuecomment-1912423532.

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #1555

#### Does this PR introduce a user-facing change?

```release-note
Remove deleted pending workloads from the cache
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Is the issue also reflected in `ClusterQueue.status`? I believe it is. It would be much simpler to test for that and also we could cherry-pick to 0.5.
The visibility server doesn't exist in 0.5, so we can't cherry-pick it.

**Comment by mimowo** [comment]
/retest
the failures are due flakes which are now fixed: https://github.com/kubernetes-sigs/kueue/pull/1676

File: pkg/visibility/api/rest/utils.go [hunk 1]
```diff
@@ -39,7 +40,7 @@ func newPendingWorkload(wlInfo *workload.Info, positionInLq int32, positionInCq
 			CreationTimestamp: wlInfo.Obj.CreationTimestamp,
 		},
 		PositionInClusterQueue: int32(positionInCq),
-		Priority:               *wlInfo.Obj.Spec.Priority,
+		Priority:               priority.Priority(wlInfo.Obj),
```
Comment (mimowo) [inline pkg/visibility/api/rest/utils.go:43]: Is it directly related to the issue or drive-by fix? Why is it needed / useful?

**Comment by mimowo** [comment]
> Is the issue also reflected in ClusterQueue.status? I believe it is. It would be much simpler to test for that and also we could cherry-pick to 0.5.

I think the bug is also impacting the `eq.status.pendingWorkloads` counter, so we could use this to verify the fix works at the level of integration tests.

File: pkg/visibility/server.go [hunk 2]
```diff
@@ -47,12 +47,11 @@ type server struct {
 
 // CreateAndStartVisibilityServer creates visibility server injecting KueueManager and starts it
 func CreateAndStartVisibilityServer(kueueMgr *queue.Manager, ctx context.Context) {
-	config := newVisibilityServerConfig()
```
Comment (mimowo) [inline pkg/visibility/server.go:50]: Are these changes needed for the fix, or drive-by cleanup? If just cleanup maybe a dedicated PR is preferred IMO.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve
/cherry-pick release-0.5

File: pkg/visibility/server.go (hunk 2 above)
Comment (astefanutti) [reply pkg/visibility/server.go]: These changes were necessary for setting up the integration tests for the visibility API, to make it possible to reuse the API server configuration for the test client.

I've removed those integration tests altogether so these changes are not needed anymore.

**Comment by astefanutti** [comment]
> Is the issue also reflected in `ClusterQueue.status`? I believe it is. It would be much simpler to test for that and also we could cherry-pick to 0.5. The visibility server doesn't exist in 0.5, so we can't cherry-pick it.

You're right! I've removed the integration tests for the visibility API, and added a test case to the existing cluster queue controller integration tests, that verifies the fix.

I've kept it as minimal as possible this time, but feel free to suggest any other test cases that you think could be useful to add there.

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 3]
```diff
@@ -362,6 +362,63 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Ordered, ginkgo.Contin
...
 
+		ginkgo.It("Should update status and report metrics when a pending workload is deleted", func() {
+			workload := testing.MakeWorkload("one", ns.Name).Queue(localQueue.Name).
+				Request(corev1.ResourceCPU, "5").Obj()
+
+			ginkgo.By("Creating a workload", func() {
+				gomega.Expect(k8sClient.Create(ctx, workload)).To(gomega.Succeed())
+			})
+
+			// Pending workloads count is incremented as the workload is inadmissible
```
Comment (mimowo) [inline test/integration/controller/core/clusterqueue_controller_test.go:373]: non-blocking nit: I would prefer to turn the comment into ginkgo step. Maybe ginkgo.By("await until the pending workload count is incremented as the workload is inadmissible, because the ResourceFlavors don't exist"). This way the comment is also logged, which can make debugging easier.

File: test/integration/controller/core/clusterqueue_controller_test.go [hunk 4]
```diff
@@ -362,6 +362,63 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Ordered, ginkgo.Contin
...
+			}, ignoreConditionTimestamps, ignorePendingWorkloadsStatus))
+
+			util.ExpectPendingWorkloadsMetric(clusterQueue, 0, 1)
+			util.ExpectReservingActiveWorkloadsMetric(clusterQueue, 0)
+
+			ginkgo.By("Deleting the pending workload", func() {
+				gomega.Expect(k8sClient.Delete(ctx, workload)).To(gomega.Succeed())
+			})
+
+			// Pending workloads count is decrement as the deleted workload has been removed from the queue.
```
Comment (mimowo) [inline test/integration/controller/core/clusterqueue_controller_test.go:400]: non-blocking nit: same here - turn into ginkgo step

**Review by mimowo — COMMENTED** [review]
/lgtm
Just non-blocking nits to improve readability of the test.
/assign @tenzen-y @alculquicondor

File: test/integration/controller/core/clusterqueue_controller_test.go (hunk 3 above)
Comment (astefanutti) [reply test/integration/controller/core/clusterqueue_controller_test.go:373]: Agreed. Actually I saw an existing comment and somehow decided to choose that style, but I would have chosen the `ginkgo.By` stanza otherwise. Let me know if you feel like it's worth I open a follow-up PR.

Comment (mimowo) [reply test/integration/controller/core/clusterqueue_controller_test.go:373]: I didn't notice the PR was approved actually, and though you would have time to apply the remark. I'm ok either way, as you feel.
