### PR TITLE
Fix inadmissible workload stuck after priority update

### LINKED ISSUE #9621: Kueue when Creating a Job With Queueing Should allow updating the workload's priority through the job
**Which test is flaking?**:
Kueue when Creating a Job With Queueing Should allow updating the workload's priority through the job
**Link to failed CI job or steps to reproduce locally**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9617/pull-kueue-test-e2e-main-1-33/2028383367677874176
**Failure message or logs**:
```
End To End Suite: kindest/node:v1.33.7: [It] Kueue when Creating a Job With Queueing Should allow updating the workload's priority through the job [area:singlecluster, feature:job] expand_less	14s
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/job_test.go:534 with:
Expected
    <bool>: true
to be false failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/job_test.go:534 with:
Expected
    <bool>: true
to be false
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/job_test.go:535 @ 03/02/26 08:40:19.903
}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by sohankunkerkar**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #9621 

#### Special notes for your reviewer:
When a workload's spec changes while the scheduler is evaluating it, `RequeueWorkload.info.Update` refreshes the inadmissible entry to the latest version, causing `PushOrUpdate`'s spec comparison to see no change and leaving the workload stuck in inadmissible. Track the evaluated generation at Pop() time so `PushOrUpdate` detects spec changes under the CQ lock regardless of caller freshness.

I ran the failed test with this change in a loop (200 times) and it works fine.

#### Does this PR introduce a user-facing change?

```release-note
Scheduling: Fix a race where updated workload priority could remain stuck in the inadmissible queue and delay rescheduling.
```

### CODE REVIEW

File: pkg/cache/queue/cluster_queue.go [hunk 1]
```diff
@@ -109,6 +109,10 @@ type ClusterQueue struct {
 	// inflight indicates the workload that was last popped by scheduler.
 	inflight *workload.Info
 
+	// lastEvaluatedGeneration stores each workload's Generation at Pop time,
+	// so PushOrUpdate can detect spec changes masked by RequeueWorkload's info.Update.
+	lastEvaluatedGeneration map[workload.Reference]int64
```
Comment (mwielgus) [inline pkg/cache/queue/cluster_queue.go]: Why not put it into https://github.com/kubernetes-sigs/kueue/blob/main/pkg/workload/workload.go#L187 ?

File: pkg/cache/queue/cluster_queue_test.go [hunk 2]
```diff
@@ -242,6 +242,50 @@ func TestPushOrUpdateSkipsInflightWorkload(t *testing.T) {
 	}
 }
 
+func TestPushOrUpdateMovesInadmissibleWhenGenerationChanged(t *testing.T) {
```
Comment (mwielgus) [inline pkg/cache/queue/cluster_queue_test.go]: Is it possible to have tests with backoff as well?

File: pkg/cache/queue/cluster_queue.go (hunk 1 above)
Comment (sohankunkerkar) [reply pkg/cache/queue/cluster_queue.go]: Yeah, I think it would be cleaner. will fix that.

File: pkg/cache/queue/cluster_queue_test.go [hunk 3]
```diff
@@ -242,6 +242,84 @@ func TestPushOrUpdateSkipsInflightWorkload(t *testing.T) {
...
+
+	if active, _ := cq.Dump(); len(active) != 1 {
+		t.Errorf("expected workload on heap after generation change, got %d", len(active))
+	}
+	if inadmissible, _ := cq.DumpInadmissible(); len(inadmissible) != 0 {
+		t.Errorf("expected no inadmissible workloads after generation change, got %d", len(inadmissible))
+	}
+}
+
+func TestPushOrUpdateWithBackoffKeepsInadmissibleWhenGenerationChanged(t *testing.T) {
```
Comment (mimowo) [inline pkg/cache/queue/cluster_queue_test.go]: There is a signifficant overlap between the unit tests in setup, and asserts. Would it be feasible to combine them both into table-driven tests?

Comment (sohankunkerkar) [reply pkg/cache/queue/cluster_queue_test.go]: Fixed!

**Comment by mimowo** [comment]
Thank you 👍 
/lgtm
/approve
/cherrypick release-0.16
/cherrypick release-0.15
