### PR TITLE
[kueuectl] Delete the corresponding Job when deleting a Workload.

### LINKED ISSUE #2975: [kueuectl] delete workload command should delete the Job & workload
**What happened**:

The `kueuectl delete workload` command only deletes the workload, rather than the Job.
This means that the job gets restarted rather than deleted.

**What you expected to happen**:

The Job & workload gets deleted. If the workload is deleted by the core Kueue, then deleting the Job by kueuectl is enough.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Job
2. Get the workload name by `kueuectl list workload`
3. Invoke `kueuectl delete workload <name>`

Issue: the Job remains. As a result `kueuectl list workload` keeps displaying the workload (now recreated).

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
- Create separate command for deleting the Workload and its corresponding Job(s),
- Improve `WorkloadNameFunc` to allow autocompletion for multiple resource names in arguments.

#### Which issue(s) this PR fixes:

Fixes #2975

#### Does this PR introduce a user-facing change?

```release-note
CLI: Delete the corresponding Job when deleting a Workload.
```

### CODE REVIEW

File: cmd/kueuectl/app/delete/delete_workload.go [hunk 1]
```diff
@@ -0,0 +1,372 @@
...
+		workloads = append(workloads, wl)
+		if len(wl.OwnerReferences) > 0 {
+			haveAssociatedWorkloads = true
+		}
+	}
+
+	return workloads, haveAssociatedWorkloads, nil
+}
+
+func (o *WorkloadOptions) getWorkloadResources(workloads []*v1beta1.Workload) (map[*v1beta1.Workload][]GroupVersionResourceName, error) {
```
Comment (trasc) [inline cmd/kueuectl/app/delete/delete_workload.go:284]: Maybe we should not put too much pressure on this now but, the first owner may not be the actual (root) owner of the wl for example in case of  [FluxMiniclusters](https://kueue.sigs.k8s.io/docs/tasks/run/flux_miniclusters/), [deployments](https://github.com/kubernetes-sigs/kueue/tree/main/pkg/controller/jobs/deployment) and probably more, both the fist layer owner and the workload will be recreated.

File: cmd/kueuectl/app/delete/delete_workload_test.go
Comment (trasc) [inline cmd/kueuectl/app/delete/delete_workload_test.go:1]: nit: some of the test descriptions can be rephrased.

File: cmd/kueuectl/app/delete/delete_workload_test.go [hunk 2]
```diff
@@ -0,0 +1,429 @@
...
+	}{
+		"shouldn't delete a workload because no arguments": {
+			args:    []string{},
+			wantErr: "requires at least 1 arg(s), only received 0",
+		},
+		"shouldn't delete a workload because not confirmed": {
+			args: []string{"wl1"},
+			workloads: []runtime.Object{
+				testingworkload.MakeWorkload("wl1", metav1.NamespaceDefault).OwnerReference(jobGVK, "j1", "").Obj(),
+				testingworkload.MakeWorkload("wl2", metav1.NamespaceDefault).Obj(),
```
Comment (trasc) [inline cmd/kueuectl/app/delete/delete_workload_test.go:66]: is this needed?

File: cmd/kueuectl/app/delete/delete_workload_test.go [hunk 3]
```diff
@@ -0,0 +1,429 @@
...
+			},
+			jobs: []runtime.Object{
+				&bactchv1.Job{ObjectMeta: metav1.ObjectMeta{Name: "j1", Namespace: metav1.NamespaceDefault}},
+				&bactchv1.Job{ObjectMeta: metav1.ObjectMeta{Name: "j2", Namespace: metav1.NamespaceDefault}},
```
Comment (trasc) [inline cmd/kueuectl/app/delete/delete_workload_test.go:70]: is this needed?

File: cmd/kueuectl/app/delete/delete_workload_test.go [hunk 4]
```diff
@@ -0,0 +1,429 @@
...
+			},
+			wantOut: `This operation will also delete:
+  - jobs.batch/j1 associated with the wl1 workload
+Do you want to proceed (y/n)? Deletion is canceled
+`,
+		},
+		"should delete a workload without confirmation because no associated job": {
+			args: []string{"wl2"},
+			workloads: []runtime.Object{
+				testingworkload.MakeWorkload("wl1", metav1.NamespaceDefault).OwnerReference(jobGVK, "j1", "").Obj(),
```
Comment (trasc) [inline cmd/kueuectl/app/delete/delete_workload_test.go:98]: is this needed?

File: cmd/kueuectl/app/delete/delete_workload_test.go [hunk 5]
```diff
@@ -0,0 +1,429 @@
...
+				testingworkload.MakeWorkload("wl2", metav1.NamespaceDefault).Obj(),
+			},
+			jobs: []runtime.Object{
+				&bactchv1.Job{ObjectMeta: metav1.ObjectMeta{Name: "j1", Namespace: metav1.NamespaceDefault}},
+				&bactchv1.Job{ObjectMeta: metav1.ObjectMeta{Name: "j2", Namespace: metav1.NamespaceDefault}},
```
Comment (trasc) [inline cmd/kueuectl/app/delete/delete_workload_test.go:103]: is this needed?

File: cmd/kueuectl/app/delete/delete_workload_test.go [hunk 6]
```diff
@@ -0,0 +1,429 @@
...
+				Items: []bactchv1.Job{
+					{
+						TypeMeta:   metav1.TypeMeta{Kind: "Job", APIVersion: "batch/v1"},
+						ObjectMeta: metav1.ObjectMeta{Name: "j1", Namespace: metav1.NamespaceDefault},
+					},
+					{
+						TypeMeta:   metav1.TypeMeta{Kind: "Job", APIVersion: "batch/v1"},
+						ObjectMeta: metav1.ObjectMeta{Name: "j2", Namespace: metav1.NamespaceDefault},
+					},
+				},
```
Comment (trasc) [inline cmd/kueuectl/app/delete/delete_workload_test.go:120]: is this needed?


the same goes for most of the tests in this file

File: cmd/kueuectl/app/passthrough/passthrough.go [hunk 7]
```diff
@@ -23,55 +23,92 @@ import (
...
+	"sigs.k8s.io/kueue/cmd/kueuectl/app/delete"
+	"sigs.k8s.io/kueue/cmd/kueuectl/app/util"
 )
 
-type passThroughType struct {
+type passThroughCommand struct {
 	name    string
+	short   string
 	aliases []string
 }
```
Comment (trasc) [inline cmd/kueuectl/app/passthrough/passthrough.go:36]: I don't like this "type reuse", lets keep `passThroughType`  and define a different one for command if necessary (but for mentioning that it's a pass to kubectl is sufficient)/

File: keps/2076-kueuectl/README.md [hunk 8]
```diff
@@ -330,6 +331,16 @@ kueuectl resume workload name --namespace=ns
 Output:
 None.
 
+### Delete Workload
+
+Delete the given Workload and corresponding to it Job.
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply keps/2076-kueuectl/README.md]: Done

File: cmd/kueuectl/app/delete/delete_workload.go [hunk 9]
```diff
@@ -0,0 +1,372 @@
...
+			err := o.Complete(clientGetter, cmd, args)
+			if err != nil {
+				return err
+			}
+
+			return o.Run(cmd.Context())
+		},
+	}
+
+	cmd.Flags().BoolVarP(&o.Confirmed, "yes", "y", false, "Confirm the deletion of the workload.")
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply cmd/kueuectl/app/delete/delete_workload.go]: Done

File: cmd/kueuectl/app/delete/delete_workload.go [hunk 10]
```diff
@@ -0,0 +1,372 @@
...
+		PrintFlags: genericclioptions.NewPrintFlags("deleted").WithTypeSetter(scheme.Scheme),
+		IOStreams:  streams,
+	}
+}
+
+func NewWorkloadCmd(clientGetter util.ClientGetter, streams genericiooptions.IOStreams) *cobra.Command {
+	o := NewWorkloadOptions(streams)
+
+	cmd := &cobra.Command{
+		Use:                   "workload NAME [--cascade STRATEGY] [--dry-run STRATEGY]",
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply cmd/kueuectl/app/delete/delete_workload.go]: Also added `--all` flag.

File: cmd/kueuectl/app/passthrough/passthrough.go (hunk 7 above)
Comment (mbobrovskyi) [reply cmd/kueuectl/app/passthrough/passthrough.go]: Reverted.

File: cmd/kueuectl/app/delete/delete_workload_test.go (hunk 6 above)
Comment (mbobrovskyi) [reply cmd/kueuectl/app/delete/delete_workload_test.go:120]: But I agree that it's not need for current case.

File: cmd/kueuectl/app/delete/delete_workload.go (hunk 1 above)
Comment (mbobrovskyi) [reply cmd/kueuectl/app/delete/delete_workload.go:284]: This is a good point! We can address the root owner and delete it. However, a deployment can create multiple workloads. Deleting the deployment will also remove all associated workloads.

**Comment by mwielgus** [comment]
Can you either split the PR or add description what else, apart from delete, is being done there and why these changes need to go together?

**Comment by mbobrovskyi** [comment]
> Can you either split the PR or add description what else, apart from delete, is being done there and why these changes need to go together?

Yeah, I think it's a good idea. Created three separate PRs:

- https://github.com/kubernetes-sigs/kueue/pull/3100
- https://github.com/kubernetes-sigs/kueue/pull/3101
- https://github.com/kubernetes-sigs/kueue/pull/3104
- https://github.com/kubernetes-sigs/kueue/pull/3105

Another changes related only to this pull request.

File: cmd/kueuectl/app/passthrough/passthrough.go (hunk 7 above)
Comment (mbobrovskyi) [reply cmd/kueuectl/app/passthrough/passthrough.go]: > and define a different one for command if necessary (but for mentioning that it's a pass to kubectl is sufficient)/

Ah sorry missed it.

File: cmd/kueuectl/app/delete/delete_workload.go (hunk 1 above)
Comment (mbobrovskyi) [reply cmd/kueuectl/app/delete/delete_workload.go:284]: To ensure we do not lose context, let's continue the discussion at https://github.com/kubernetes-sigs/kueue/pull/3101#discussion_r1768696280.

**Comment by mimowo** [comment]
/approve
The KEP update is merging, leaving lgtm to @trasc

**Comment by mimowo** [comment]
/hold 
Also in case @mwielgus would like to give it a pass

File: cmd/kueuectl/app/delete/delete_workload.go [hunk 11]
```diff
@@ -0,0 +1,386 @@
...
+		}
+
+		if o.DryRunStrategy == util.DryRunServer {
+			deleteOptions.DryRun = []string{metav1.DryRunAll}
+		}
+
+		for _, nr := range nrs {
+			if o.DryRunStrategy != util.DryRunClient {
+				if err := o.DynamicClient.Resource(nr.GroupVersionResource).Namespace(wl.Namespace).
+					Delete(ctx, nr.Name, deleteOptions); client.IgnoreNotFound(err) != nil {
```
Comment (trasc) [inline cmd/kueuectl/app/delete/delete_workload.go:365]: If deleteOptions has `Orphan`  PropagationPolicy, the workload will not be deleted as described in the command's description.

Comment (mimowo) [reply cmd/kueuectl/app/delete/delete_workload.go:364]: The cascade option for the delete Workload mixes two layers of abstraction: on one hand we use Workload as a concept representing computation, on the other hand we use the technical option `--cascade` referring to ownerRaference mangement. 

So, I would suggest not supporting the `cascade` for deleting Workloads, and to use the default delete strategy (Background) for Jobs. This would be consistent with the KEP, and be sufficient until we have some use cases for supporting the cascade.

Comment (mbobrovskyi) [reply cmd/kueuectl/app/delete/delete_workload.go:355]: Done

**Review by trasc — COMMENTED** [review]
/lgtm

**Comment by mimowo** [comment]
/approve
Thanks for moving this to completion.

> /hold
> Also in case @mwielgus would like to give it a pass

I believe since Marcin lgtm'ed the KEP we are good to go.
/hold cancel
