### PR TITLE
Fix live-updates for kubernetes Job getting stuck occasionally

### LINKED ISSUE #3581: [Flaky multikueue e2e] MultiKueue when Creating a multikueue admission check Should run a job on worker if admitted
**What happened**:

End To End MultiKueue Suite: kindest/node:v1.30.0: [It] MultiKueue when Creating a multikueue admission check Should run a job on worker if admitted

```
{Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:231 with:
Expected
    <bool>: true
to be false failed [FAILED] Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:231 with:
Expected
    <bool>: true
to be false
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:232 @ 11/18/24 14:17:15.278
}
```

**What you expected to happen**:
No random failures

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3580/pull-kueue-test-multikueue-e2e-release-0-9/1858512622475808768

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #3600: [multiKueue flakes] Creating a multikueue admission check Should run a job on worker if admitted
/kind flake

**What happened**:

The multikueue e2e test failed on unrelated branch: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3591/pull-kueue-test-multikueue-e2e-main/1859173059118764032

**What you expected to happen**:

To flakes

**How to reproduce it (as minimally and precisely as possible)**:

Run on CI

**Anything else we need to know?**:

```
{Timed out after 5.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:229 with:
Expected
    <bool>: true
to be false failed [FAILED] Timed out after 5.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:229 with:
Expected
    <bool>: true
to be false
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:230 @ 11/20/24 10:02:46.412
}
```

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:
Adds a check when syncing jobs on multikueue to avoid trying to patch the spec before resuming the job.

#### Which issue(s) this PR fixes:

Fixes #3581 

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug which occasionally prevented updates to the PodTemplate of the Job on the management cluster
when starting a Job (e.g. updating nodeSelectors), when using `MultiKueueBatchJobWithManagedBy` enabled.
```

### CODE REVIEW

File: pkg/controller/jobs/job/job_multikueue_adapter.go [hunk 1]
```diff
@@ -49,6 +50,12 @@ func (b *multikueueAdapter) SyncJob(ctx context.Context, localClient client.Clie
 		return err
 	}
 
+	log := ctrl.LoggerFrom(ctx)
+	if ptr.Deref(localJob.Spec.Suspend, false) { // Ensure the job is resumed before updating its status; otherwise, it will fail when patching the spec.
```
Comment (mimowo) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:54]: This changes the implementation - is this actually a bug? If so, we should add a release note describing the scenario that is fixed

Comment (mimowo) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:54]: Could you maybe explain a bit more what is the update that is failing trying to update in the spec?

Comment (mimowo) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:54]: Ah I think I know what you mean, k8s core blocks update of pod template if the job is running. And it determines that the job is running because status.startTime Is not bil

Comment (mbobrovskyi) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:54]: I think we should check it after the remote is created.

Comment (mbobrovskyi) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:54]: The same issue can occur in other adapters. It would be great to implement this in them as well.

Comment (mbobrovskyi) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:54]: It would be great to add a test case to verify skipping.

**Review by mbobrovskyi — COMMENTED** [review]
/cc @mszadkow

File: pkg/controller/jobs/job/job_multikueue_adapter.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:54]: FYI: [here](https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/pkg/registry/batch/job/strategy.go#L192-L194) and [here](https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/pkg/apis/batch/validation/validation.go#L641-L662) are the relevant places in the core k8s which reject the spec update if the status is already updated (status.startTime != nil).

Comment (mimowo) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:54]: nit: Move the comment below, we don't inline comments with code

**Comment by mimowo** [comment]
Proposal:
/release-note-edit
```release-note
Fix a bug which occasionally prevented updates to the PodTemplate of the Job on the management cluster
when starting a Job (e.g. updating nodeSelectors), when using `MultiKueueBatchJobWithManagedBy` enabled.
```

**Comment by mimowo** [comment]
IIUC this is not just a fix for flaky tests, but an important bugfix for the issue which could affect production systems.
I agree it would be great to also apply the same approach for other Job CRDs  - they may or may not have similar
validation, but we also care about consistency.

**Comment by mbobrovskyi** [comment]
@IrvingMg please update description with

```Fixes #3581```

File: pkg/controller/jobs/job/job_multikueue_adapter.go (hunk 1 above)
Comment (mszadkow) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:54]: exactly, changing it here is blind change, let's only modify if remote has started

Comment (mszadkow) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:54]: more tests! agree

Comment (IrvingMg) [reply pkg/controller/jobs/job/job_multikueue_adapter.go]: Done.

**Comment by IrvingMg** [comment]
> IIUC this is not just a fix for flaky tests, but an important bugfix for the issue which could affect production systems. I agree it would be great to also apply the same approach for other Job CRDs - they may or may not have similar validation, but we also care about consistency. For other Jobs I'm ok with a follow up, if this makes this PR land before 0.9.2.

Open #3730

File: pkg/controller/jobs/job/job_multikueue_adapter.go (hunk 1 above)
Comment (IrvingMg) [reply pkg/controller/jobs/job/job_multikueue_adapter.go]: Open #3730

Comment (mimowo) [reply pkg/controller/jobs/job/job_multikueue_adapter.go]: This could be covered in integration test probably. right?

Comment (IrvingMg) [reply pkg/controller/jobs/job/job_multikueue_adapter.go]: This bug seems hard to reproduce in a test case as it requires causing a failure in the reconciler of the local job while sync it with the remote one. 

However, this bug was originally caught in multikueue e2e tests and after running them several times with this fix, the error didn't occur anymore.

Comment (mimowo) [reply pkg/controller/jobs/job/job_multikueue_adapter.go]: > This bug seems hard to reproduce in a test case as it requires causing a failure in the reconciler of the local job while sync it with the remote one.

I see, in that case I don't have a better test idea, maybe a unit test.

> However, this bug was originally caught in multikueue e2e tests and after running them several times with this fix, the error didn't occur anymore.

Yes, this is covered, just flaky, so I'm ok to accept as is. Feel free to follow up with unit tests or extra tests when working on https://github.com/kubernetes-sigs/kueue/issues/3730

**Comment by mimowo** [comment]
/lgtm
/approve
/retitle Fix live-updates for kubernetes Job getting stuck occasionally
