### PR TITLE
Fix Scheduler when ClusterQueue head has inadmissible workload sticky workload deleted, next workload can admit integration test

### LINKED ISSUE #7470: [flaky test] Scheduler when ClusterQueue head has inadmissible workload sticky workload deleted, next workload can admit
/kind flake

**What happened**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7447/pull-kueue-test-integration-baseline-main/1984049822797139968
**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:
```
Scheduler Fair Sharing Suite: [It] Scheduler when ClusterQueue head has inadmissible workload sticky workload deleted, next workload can admit expand_less	14s
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:695 with:
Expected
    <int>: 0
to equal
    <int>: 1 failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:695 with:
Expected
    <int>: 0
to equal
    <int>: 1
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:982 @ 10/31/25 00:25:41.377
}
```

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:

Fix Scheduler when ClusterQueue head has inadmissible workload sticky workload deleted, next workload can admit integration test.

#### Which issue(s) this PR fixes:

Fixes #7470

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go [hunk 1]
```diff
@@ -953,34 +955,40 @@ var _ = ginkgo.Describe("Scheduler", ginkgo.Ordered, ginkgo.ContinueOnFailure, f
...
 			stickyWorkload := createWorkloadWithPriority("cq1", "3", 99)
 
+			ginkgo.By("Validate pending workloads")
+			util.ExpectPendingWorkloadsMetric(cq1, 2, 0)
+
 			ginkgo.By("Another admissible workload in queue1")
 			createWorkloadWithPriority("cq1", "3", 0)
 
+			ginkgo.By("Validate pending workloads")
+			util.ExpectPendingWorkloadsMetric(cq1, 3, 0)
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: /hold
The test asserts should not expect the inadmissible workload being counted as active, even if that happens for a short while.

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go [hunk 2]
```diff
@@ -953,34 +955,40 @@ var _ = ginkgo.Describe("Scheduler", ginkgo.Ordered, ginkgo.ContinueOnFailure, f
 
 		ginkgo.It("sticky workload deleted, next workload can admit", func() {
 			ginkgo.By("Creating borrowing workloads in queue2")
-			createWorkload("cq2", "1")
-			createWorkload("cq2", "1")
-			util.ExpectAdmittedWorkloadsTotalMetric(cq2, "", 2)
+			createWorkloadWithPriority("cq2", "2", 0)
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: is this priority change needed to make the test stable?

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go (hunk 1 above)
Comment (mimowo) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: /unhold
I think I understand, so after the sticky workload is created the inadmissible workload is requeued, but because the head is stick and so the inadmissible workload is not counted as inadmissible but active. this is a weird side effect. 

I'm okish with that but it warrants a comment, otoh I'm thinking it might be easier to follow if we first create the sticky, and only then the inadmissible. then the test does not need to rely on this weird behavior. 

I think ideally we would not move the inadmissible workload to active after sticky creation. but I'm not yet sure, it is not a high prio issue for now anyway

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: Looks like there’s no need — I tested it with 50 repeats, and it works.

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: > I think ideally we would not move the inadmissible workload to active after sticky creation. but I'm not yet sure, it is not a high prio issue for now anyway

The same issue:

```
			ginkgo.By("Create admissible workloads in queue1")
			stickyWorkload := createWorkloadWithPriority("cq1", "3", 99)

			ginkgo.By("Validate pending workloads")
			util.ExpectPendingWorkloadsMetric(cq1, 1, 0)

			ginkgo.By("Create inadmissible workload in queue1")
			createWorkloadWithPriority("cq1", "4", 999)

			ginkgo.By("Verify doesn't admit")
			util.ExpectPendingWorkloadsMetric(cq1, 2, 0)
```

Comment (mimowo) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: I wouldn't call it an issue, yes the inadmissible workload is counted as active, but I think in this order of adding it is more clear to the reader. The second workload is not evaluated despite priority because the head is already taken by the sticky workload.

Comment (mimowo) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: I would propose to just make the comments more explanatory, maybe:

```
ginkgo.By("Create admissible workloads in queue1")
stickyWorkload := createWorkloadWithPriority("cq1", "3", 99)

ginkgo.By("Verify the workload is counted as pending active")
util.ExpectPendingWorkloadsMetric(cq1, 1, 0)

ginkgo.By("Create inadmissible workload in queue1")
createWorkloadWithPriority("cq1", "4", 999)

ginkgo.By("Verify the inadmissible workload is also counted as pending active since the head is already taken by the sticky workload")
util.ExpectPendingWorkloadsMetric(cq1, 2, 0)
```

Comment (mbobrovskyi) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: The inadmissible workload is also counted as pending active since the head is already taken by the sticky workload. I’ve updated the ginkgo.By text accordingly.

**Comment by mimowo** [comment]
/hold
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7604/pull-kueue-test-integration-baseline-main/1988607604368084992
is related for sure
