### PR TITLE
Prefer Reclamation over Priority Based Preemption

### LINKED ISSUE #2720: Prioritize reclamation over priority-based preemption across multiple RFs
**What would you like to be added**:

We have a cohort with CQ with `WhenCanPreempt: TryNextFlavor`.

Assume there are 2 ResourceFlavors and both require preemption to accommodate a new workload. 

The first RF requires priority based preemption inside the CQ, while the second RF could accommodate just based on reclamation. Currently, we would pick the first RF as the second does not "improve" the assignment. 

However, picking the second RF should be considered an improvement of the assignment, because reclamation should be preferred over priority-based preemption. Note that, if there is one RF we prioritize reclamation (preemptions by borrowing workloads).

We may consider a feature gate if this change seems risky.

**Why is this needed**:

To properly prioritize preemptions in case of multiple RFs. This can be useful in a situation when different RF are equivalent in terms of machine price, but they are used to represent node groups in different zones. In that a team has some nominal quota in every zone, and prefers to use the quota.

**How to reproduce it (as minimally and precisely as possible)**:

Create the following structure:

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "zone-a"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "zone-b"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue1"
spec:
  cohort: "cohort"
  flavorFungibility:
    whenCanBorrow: TryNextFlavor
    whenCanPreempt: TryNextFlavor
  preemption:
    withinClusterQueue: LowerPriority
    reclaimWithinCohort: Any
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "zone-a"
      resources:
      - name: "cpu"
        nominalQuota: 3
      - name: "memory"
        nominalQuota: 12Gi
    - name: "zone-b"
      resources:
      - name: "cpu"
        nominalQuota: 3
      - name: "memory"
        nominalQuota: 12Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue2"
spec:
  cohort: "cohort"
  flavorFungibility:
    whenCanBorrow: TryNextFlavor
    whenCanPreempt: TryNextFlavor
  preemption:
    withinClusterQueue: LowerPriority
    reclaimWithinCohort: Any
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "zone-a"
      resources:
      - name: "cpu"
        nominalQuota: 3
      - name: "memory"
        nominalQuota: 12Gi
    - name: "zone-b"
      resources:
      - name: "cpu"
        nominalQuota: 3
      - name: "memory"
        nominalQuota: 12Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue1"
spec:
  clusterQueue: "cluster-queue1"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue2"
spec:
  clusterQueue: "cluster-queue2"
```
Then, we have 3 jobs: `sample1-low.yaml`, `sample2-low.yaml` and `sample1-mid.yaml`. 
`sample1-low` is as follows:
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample1-low-job-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue1
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      priorityClassName: "low-priority"
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["600s"]
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Never
```
`sample2-low.yaml` is analogous. but creates the Job is CQ2, whereas `sample1-mid.yaml` is just mid priority.

Now: 
1. create 2 Jobs `sample2-low.yaml` to exhaust nominal capacity of CQ2 in zone-a and zone-b
2. create `sample1-low.yaml` to exhaust nominal quota of CQ1 in zone-a
3. create `sample2-mid-yaml`.

**Issue**
The new workload preempts from zone-a using priority-based preemption while it could still do reclamation in zone-b.

### PR DESCRIPTION
**Pull request by gabesaba**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We update `FlavorSelector` to simulate preemption, to determine if a workload can reclaim capacity from its Cohort in one Flavor, rather than preempting its workloads in another Flavor. This matches behavior in the single Flavor case, where a ClusterQueue prioritizes preempting workloads in its Cohort, before preempting its own workloads.

#### Which issue(s) this PR fixes:
Fixes #2720

#### Does this PR introduce a user-facing change?
```release-note
Update Flavor selection logic to prefer Flavors which allow reclamation of lent nominal quota, over Flavors which require preempting workloads within the ClusterQueue. This matches the behavior in the single Flavor case.
```

### CODE REVIEW

File: pkg/scheduler/preemption/preemption_oracle.go [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+// FlavorResource by reclaiming its nominal quota which it lent to its
+// Cohort.
+func (p *PreemptionOracle) IsReclaimPossible(log logr.Logger, cq *cache.ClusterQueueSnapshot, wl workload.Info, fr resources.FlavorResource, quantity int64) bool {
+	if cq.Usage[fr]+quantity > cq.QuotaFor(fr).Nominal {
+		return false
+	}
+
+	for _, candidate := range p.preemptor.getTargets(log, wl, resources.FlavorResourceQuantities{fr: quantity}, sets.New(fr), p.snapshot) {
+		if candidate.WorkloadInfo.ClusterQueue == cq.Name {
+			return false
```
Comment (mimowo) [inline pkg/scheduler/preemption/preemption_oracle.go:31]: Do we have any test which exercises if this is needed? If no, it would be good to have it.

**Review by mimowo — COMMENTED** [review]
LGTM, it is quite impressive how small the fix is. I'm wondering if we have enough test coverage for the oracle though.

File: pkg/scheduler/flavorassigner/flavorassigner_test.go [hunk 2]
```diff
@@ -1969,6 +1976,159 @@ func TestAssignFlavors(t *testing.T) {
...
+			workloadRequests: utiltesting.MakePodSet("main", 1).Request("gpu", "10"),
+			testClusterQueueUsage: resources.FlavorResourceQuantities{
+				{Flavor: "uno", Resource: "gpu"}: 1,
+				{Flavor: "due", Resource: "gpu"}: 1,
+				{Flavor: "tre", Resource: "gpu"}: 1,
+			},
+			wantMode:      Preempt,
+			wantAssigment: rfMap{"gpu": "uno"},
+		},
+		"Select second flavor where gpu reclamation is possible, as compute Fits": {
```
Comment (PBundyra) [inline pkg/scheduler/flavorassigner/flavorassigner_test.go:2040]:
```suggestion
		"Select third flavor where gpu reclamation is possible, as compute Fits": {
```

File: pkg/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -2313,6 +2313,67 @@ func TestSchedule(t *testing.T) {
...
+				*utiltesting.MakeWorkload("preemptor", "eng-alpha").
+					Priority(100).
+					Queue("other").
+					Request("gpu", "6").
+					Obj(),
+			},
+			wantPreempted: sets.New("eng-beta/b1"),
+			wantLeft: map[string][]string{
+				"other-alpha": {"eng-alpha/preemptor"},
+			},
```
Comment (PBundyra) [inline pkg/scheduler/scheduler_test.go:2371]: Since `eng-alpha/a1` has lower priority than `eng-alpha/preemptor` shouldn't `a1` be preempted, and `preemptor` be admitted?

**Comment by PBundyra** [comment]
When reclamation meets required quota only partially, do we still reclaim as much as possible and then preempt the rest, or do we just preempt the whole missing quota?

File: pkg/scheduler/scheduler_test.go (hunk 3 above)
Comment (gabesaba) [reply pkg/scheduler/scheduler_test.go:2371]: `preemptor` will be admitted - but in a future cycle (the way these tests are setup, we expect to see it in wantLeft, since it didnt `Fit` this cycle). It was correct here to preempt `b1`, as we have a preference (after this PR) to reclaim capacity, rather than preempt another workload in the same CQ.

**Comment by gabesaba** [comment]
> When reclamation meets required quota only partially, do we still reclaim as much as possible and then preempt the rest, or do we just preempt the whole missing quota?

Yes, we will preempt the workloads which reclaim capacity first. But, it is possible we won't end up preempting them if we can get all the resources we need from a workload in our CQ, as we attempt to add back workloads after the fit - the step [here](https://github.com/kubernetes-sigs/kueue/blob/21e9ac330cb6624f555668ccaca347a61c1f81ac/pkg/scheduler/preemption/preemption.go#L276-L289)

**Comment by mimowo** [comment]
/approve
Will wait with lgtm for a little while in case @PBundyra has some additional comments.

**Comment by PBundyra** [comment]
LGTM @mimowo

**Comment by mimowo** [comment]
/lgtm
Thanks!

**Comment by mimowo** [comment]
@gabesaba PTAL what is the best way to backport it.

File: pkg/scheduler/preemption/preemption_oracle.go [hunk 4]
```diff
@@ -0,0 +1,35 @@
+package preemption
```
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption_oracle.go:1]: Add copyright

File: pkg/scheduler/flavorassigner/flavorassigner_test.go [hunk 5]
```diff
@@ -41,6 +42,12 @@ type cohortResources struct {
 	usage                resources.FlavorResourceQuantities
 }
 
+type testOracle struct{}
```
Comment (alculquicondor) [inline pkg/scheduler/flavorassigner/flavorassigner_test.go:45]: why add this, as opposed to use the real object (or not have an intermediary object at all)?

Comment (gabesaba) [reply pkg/scheduler/flavorassigner/flavorassigner_test.go:45]: dependency graph - preemption depends on flavor assigner, and refactoring was non-trivial

File: pkg/scheduler/preemption/preemption_oracle.go (hunk 4 above)
Comment (gabesaba) [reply pkg/scheduler/preemption/preemption_oracle.go:1]: #2900
