### PR TITLE
Unblock scheduler after failed preemption(s)

### LINKED ISSUE #5590: Kueue Scheduler getting stuck if preemption request fails
**What happened**:

When IssuePreemptions returns an error, and there are no successfully preempted workloads, then scheduler "gives up" and does not retry. 

**What you expected to happen**:

Scheduler to retry regardless if there were any successful preemptions or not. Surprisingly scheduler would retry if there are some.

Here is the code in question: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/scheduler/scheduler.go#L266-L273

**How to reproduce it (as minimally and precisely as possible)**:

Inject an random error for the preemption request like [here](https://github.com/kubernetes-sigs/kueue/pull/5589/files#diff-cd44f6e671ae7fdc7882224c13986f4b1b98e1ea45f65bdbcc9ae185d8e91496R195-R197)

**Anything else we need to know?**:

This bug was discovered when investigating https://github.com/kubernetes-sigs/kueue/issues/5511

This may not be a huge issue for production systems with a constant inflow of Jobs which would trigger scheduling, but it might be a very hard to debug situation if there is no inflow - say the admin sent "hero" job and is observing the system.

### PR DESCRIPTION
**Pull request by olekzabl**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #5590

#### Special notes for your reviewer:

This PR is currently split into 2 commits:

* The first commit is small, and fixes the issue. \
  (In short, we're roughly aligned with @mimowo that it does. \
  For details, see the discussion in #5590, starting from [this comment](https://github.com/kubernetes-sigs/kueue/issues/5590#issuecomment-3532620377))

* The second commit is my attempt to give this fix any reasonable test coverage. \
  I chose integration tests (to verify the whole path of "preemption error -> retry -> desired outcome"). \
  However, for that, I needed _selectively injecting_ fake errors into K8s client, in integration tests, which AFAICS has been never done in Kueue. \
  Hence, I needed some custom tweaking of the test setup to achieve that.
  I'm curious about reviewers' opinions whether this is nice enough.

The test coverage may be not yet as full as I'd wish (for example, I haven't cared for testing the "preemption failed" vs. "sticky workloads" interaction); yet, as I'm hearing this issue gained some urgency, I'm un-drafting this PR now, hoping that it may be good to go as it is. Then, further tests may come in a follow-up PR. (Tracked in issue #7806).

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug that an error during workload preemption could leave the scheduler stuck without retrying.
```

### CODE REVIEW

**Comment by olekzabl** [comment]
@gabesaba @mbobrovskyi May I ask for a review at this point?

While this is still technically a draft (due to non-perfect test coverage), I'd like to verify my testing approach with you before I continue work on that. And the code written so far I've already tried to "polish" reasonably.

Please see the PR description for more context.

**Comment by olekzabl** [comment]
Un-drafting now (see comment on the bottom of PR description)

/assign mimowo
as I heard you'd like to review

**Comment by mimowo** [comment]
Leaving review to @PBundyra, but please set the release note.

**Comment by olekzabl** [comment]
> please set the release note.

Done.

File: pkg/scheduler/preemption/preemption_hierarchical_test.go [hunk 1]
```diff
@@ -1856,13 +1856,16 @@ func TestHierarchicalPreemptions(t *testing.T) {
 			wlInfo := workload.NewInfo(tc.incoming)
 			wlInfo.ClusterQueue = tc.targetCQ
 			targets := preemptor.GetTargets(log, *wlInfo, tc.assignment, snapshotWorkingCopy)
-			preempted, err := preemptor.IssuePreemptions(ctx, wlInfo, targets, snapshotWorkingCopy.ClusterQueue(wlInfo.ClusterQueue))
+			preempted, failed, err := preemptor.IssuePreemptions(ctx, wlInfo, targets, snapshotWorkingCopy.ClusterQueue(wlInfo.ClusterQueue))
```
Comment (Singularity23x0) [inline pkg/scheduler/preemption/preemption_hierarchical_test.go:1859]: Nit: Is this a specific case where "failed" is equal to the amount of errors? Or do we always expect the amount of errors to be equal to the amount of failed preemptions? If yes I'd vouch for using "failed" instead of "errors" to resolve this ambiguity, otherwise ignore.

File: test/integration/framework/framework.go [hunk 2]
```diff
@@ -160,9 +172,13 @@ func (f *Framework) SetupClient(cfg *rest.Config) (context.Context, client.Clien
 	return ctx, k8sClient
 }
 
-func (f *Framework) StartManager(ctx context.Context, cfg *rest.Config, managerSetup ManagerSetup) {
+func (f *Framework) StartManager(ctx context.Context, cfg *rest.Config, managerSetup ManagerSetup, opts ...ManagerSetupOption) {
```
Comment (Singularity23x0) [inline test/integration/framework/framework.go]: Why are we using `ManagerSetupOption` defined as `type ManagerSetupOption func(*managerSetupOptions)
`?

We could just use `type ManagerSetupOption func(*manager.Options)` and later directly call

```
for _, opt := range opts {
			opt(&mgrOpts)
		}
```

File: test/integration/singlecluster/scheduler/suite_test.go [hunk 3]
```diff
@@ -100,3 +115,44 @@ func managerAndSchedulerSetup(ctx context.Context, mgr manager.Manager) {
...
+		return nil, err
+	}
+	funcs := interceptor.Funcs{
+		SubResourcePatch: wrapFakeSubResourcePatch(&fakeSubResourcePatch, baseClient),
+	}
+	client := interceptor.NewClient(baseClient, funcs)
+	return client, nil
+}
+
+func wrapFakeSubResourcePatch(f *fakeClientCallSpec, baseK8sClient client.Client) func(context.Context, client.Client, string, client.Object, client.Patch, ...client.SubResourcePatchOption) error {
```
Comment (Singularity23x0) [inline test/integration/singlecluster/scheduler/suite_test.go]: For readability I recommend aliasing `func(context.Context, client.Client, string, client.Object, client.Patch, ...client.SubResourcePatchOption) error`.

Overall it seems like this method signature is what is actually a SubResourcePatch, and the field we call `fakeSubResourcePatch` (in newInterceptedClient) is not a SubResourcePatch but rather  a fakeClientCallSpec, which is confusing.

Id propose renaming the parameter accordingly (e.g. `fakeClientSubResourcePatchSpec`), aliasing the signature as `subResourcePatch` and renaming the method to `createFakeSubResourcePatch`.

Alternatively we could reorganize to make `fakeSubResourcePatch` already be the func created with `wrapFakeSubResourcePatch`/`createFakeSubResourcePatch ` and pass it here directly. Then we would call this method in the "Should retry on failed preemptions" test itself.

Either way I think some refactor is needed to improve the readability of this part. Thoughts?

File: pkg/scheduler/preemption/preemption_hierarchical_test.go (hunk 1 above)
Comment (olekzabl) [reply pkg/scheduler/preemption/preemption_hierarchical_test.go:1859]: What do you mean by "errors"?

To clarify: `err` returned by `IssuePreemptions` is not a list of errors; it's arbitrarily chosen one of them (if any), else `nil`.

As for `failed`, it's the number of all failed preemptions, so not deducible from `err`.
However, in fact, I don't need this `failed` for anything else than nicer logging.
I can drop it completely if it's controversial.

File: test/integration/framework/framework.go (hunk 2 above)
Comment (olekzabl) [reply test/integration/framework/framework.go]: Indeed, we could. (TBH I overlooked that possibility).

I'm hesitating if we should. 
One hand, this shortens the code.
On the other hand, this gives more exposition of all the fields of `manager.Options` down to our test setup.
With the current structure of types, we keep it more blackboxed: only `NewClient` is "explicitly vetted" to be manipulated with; other fields of `manager.Options` may be also included in the future, but only upon an explicit broadening of `managerSetupOptions` (which we'd have to peer-review). I see some value in that.

So I'm not sure, and I'm fine with either way.

Any other thoughts?

File: pkg/scheduler/preemption/preemption_hierarchical_test.go (hunk 1 above)
Comment (Singularity23x0) [reply pkg/scheduler/preemption/preemption_hierarchical_test.go:1859]: This one boils down to the signature, where the return values are `(preempted int, errors int, exampleError error)` - the second one is denoted as 'errors' and is later used to populate the 'failed' field, hence my question.

File: test/integration/singlecluster/scheduler/suite_test.go (hunk 3 above)
Comment (olekzabl) [reply test/integration/singlecluster/scheduler/suite_test.go]: Good points, thanks.

I followed your suggested direction, though a bit differently:

> renaming the parameter accordingly

Do you mean `f`? This is local (to this function), and I recall Go style likes short local names.
For now I kept `f`.

Or do you mean the global var `fakeSubResourcePatch`? That would make sense.
I renamed that, though slightly differently (dropping `Client`).

> aliasing the signature as `subResourcePatch`

Done, though I added `Fn`. (Because "patch" is often meant as "the object (part) to be patched". While here we mean the function).

> renaming the method to `createFakeSubResourcePatch`

Done, though I changed the name. (`create...` is Java style; Go likes nouns more).

---

PTAL

File: pkg/scheduler/preemption/preemption_hierarchical_test.go (hunk 1 above)
Comment (olekzabl) [reply pkg/scheduler/preemption/preemption_hierarchical_test.go:1859]: Ah I see :+1: 
Changed to `failedPreemptions`. (`failed` could sound like "failed workloads").

File: test/integration/framework/framework.go (hunk 2 above)
Comment (Singularity23x0) [reply test/integration/framework/framework.go]: After further study of the code - the ManagerSetup field already does what I described, just in a single method.
So going a step further, we could use `managerSetup ...ManagerSetup`, or even forgo this whole change and just update the method in the test - see comment in `test/integration/singlecluster/scheduler/suite_test.go`.

File: test/integration/singlecluster/scheduler/suite_test.go [hunk 4]
```diff
@@ -62,14 +74,18 @@ var _ = ginkgo.BeforeSuite(func() {
 		WebhookPath: util.WebhookPath,
 	}
 	cfg = fwk.Init()
-	ctx, k8sClient = fwk.SetupClient(cfg)
-	fwk.StartManager(ctx, cfg, managerAndSchedulerSetup)
+	ctx, k8sClient = setupInterceptedClient()
+	fwk.StartManager(ctx, cfg, managerAndSchedulerSetup, framework.WithNewClient(newInterceptedClient))
```
Comment (Singularity23x0) [inline test/integration/singlecluster/scheduler/suite_test.go:78]: Alternatively:

```suggestion
	fwk.StartManager(ctx, cfg, func (ctx context.Context, mgr manager.Manager) {
		mgr.NewClient = newInterceptedClient
		managerAndSchedulerSetup(ctx, mgr)
	})
```

File: test/integration/singlecluster/scheduler/suite_test.go (hunk 3 above)
Comment (Singularity23x0) [reply test/integration/singlecluster/scheduler/suite_test.go]: > Or do you mean the global var fakeSubResourcePatch?

A: Yes.

Overall: LGTM

File: pkg/scheduler/preemption/preemption_hierarchical_test.go (hunk 1 above)
Comment (Singularity23x0) [reply pkg/scheduler/preemption/preemption_hierarchical_test.go:1859]: LGTM

File: test/integration/singlecluster/scheduler/suite_test.go (hunk 4 above)
Comment (olekzabl) [reply test/integration/singlecluster/scheduler/suite_test.go:78]: This doesn't build. `mgr` has no field `NewClient`. (I just tried it, to make sure).

`NewClient` is a field in `manager.Options`, not in `Manager` itself. AFAIU we need to pass it to the "constructor" of our `Manager` instance. Trying to set it on an already-built `Manager` is too late (unless we create some new hooks even deeper down the code - however, that deeper layer is outside Kueue codebase...)

**Comment by olekzabl** [comment]
@Singularity23x0 

> _After further study of the code - the ManagerSetup field already does what I described, just in a single method.
So going a step further, we could use managerSetup ...ManagerSetup_

For some reason I'm technically unable to reply to this comment "at its place", so I'll reply here:

It's same story as in [this thread](https://github.com/kubernetes-sigs/kueue/pull/7665#discussion_r2546506257) - `ManagerSetup` is a function which takes an already-created `Manager` as an argument, and at that point AFAIU it's too late to pass a `NewClient` to it. So I'm not following what I could do here.

File: pkg/scheduler/scheduler.go [hunk 5]
```diff
@@ -296,13 +296,16 @@ func (s *Scheduler) schedule(ctx context.Context) wait.SpeedSignal {
...
+			preempted, errors, err := s.preemptor.IssuePreemptions(ctx, &e.Info, preemptionTargets, e.clusterQueueSnapshot)
 			if err != nil {
 				log.Error(err, "Failed to preempt workloads")
 			}
 			if preempted != 0 {
 				e.inadmissibleMsg += fmt.Sprintf(". Pending the preemption of %d workload(s)", preempted)
 				e.requeueReason = qcache.RequeueReasonPendingPreemption
+			} else {
+				e.inadmissibleMsg += fmt.Sprintf(". Preempting %d workload(s) failed, will retry.", errors)
+				e.requeueReason = qcache.RequeueReasonPreemptionFailed
```
Comment (pajakd) [inline pkg/scheduler/scheduler.go]: `else` ? we cannot have both `preempted = 0` and `errors = 0`, right?

Comment (olekzabl) [reply pkg/scheduler/scheduler.go]: Good question. For some reason I thought we can't but, even if correct, it depends on other functions etc.

So - it seems good to express our intent explicitly. Done.

File: test/integration/framework/framework.go (hunk 2 above)
Comment (olekzabl) [reply test/integration/framework/framework.go]: Ah, now I found a way to reply in-thread.
See my earlier reply [here](https://github.com/kubernetes-sigs/kueue/pull/7665#issuecomment-3560057021).

File: pkg/scheduler/preemption/preemption_test.go [hunk 6]
```diff
@@ -4144,13 +4144,16 @@ func TestPreemption(t *testing.T) {
...
+			preempted, failed, err := preemptor.IssuePreemptions(ctx, wlInfo, targets, snapshotWorkingCopy.ClusterQueue(wlInfo.ClusterQueue))
 			if err != nil {
 				t.Fatalf("Failed doing preemption")
 			}
 			if preempted != tc.wantPreempted {
 				t.Errorf("Reported %d preemptions, want %d", preempted, tc.wantPreempted)
 			}
+			if failed != 0 {
+				t.Errorf("Reported %d failed preemptions, want 0", failed)
+			}
```
Comment (pajakd) [inline pkg/scheduler/preemption/preemption_test.go:4156]: Have you considered adding unit test(s) for this change (here or in pkg/scheduler/scheduler_test.go)?

File: test/integration/singlecluster/scheduler/preemption_test.go [hunk 7]
```diff
@@ -144,6 +145,51 @@ var _ = ginkgo.Describe("Preemption", func() {
...
+			fakeSubResourcePatchSpec = func(obj client.Object) (fakeClientUsage, error) {
+				wl, ok := obj.(*kueue.Workload)
+				if !ok {
+					return fallThrough, nil
+				}
+				if cond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadEvicted); cond == nil || cond.Status != metav1.ConditionTrue {
+					return fallThrough, nil
+				}
+				// Ignore patches triggered by util.FinishEvictionForWorkloads()
+				if cond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadQuotaReserved); cond != nil && cond.Status == metav1.ConditionFalse && cond.Message == "By test" {
```
Comment (pajakd) [inline test/integration/singlecluster/scheduler/preemption_test.go:159]: nit: if someone changes that "By test" message, we might start getting failures here? Perhaps add a constant to test/util/constants.go with this message.

**Comment by pajakd** [comment]
Left a few non-blocking comments but overall lgtm

File: test/integration/singlecluster/scheduler/preemption_test.go (hunk 7 above)
Comment (olekzabl) [reply test/integration/singlecluster/scheduler/preemption_test.go:159]: I considered it - but then I noticed lots of `"by test"` literals spread across our tests.
So I concluded adding such constant would go a bit against our current conventions.

File: pkg/scheduler/preemption/preemption_test.go (hunk 6 above)
Comment (olekzabl) [reply pkg/scheduler/preemption/preemption_test.go:4156]: I considered - but (as mentioned in description of this PR) I started with smaller coverage due to reported urgency of this PR.

Since you ask about it, I opened a follow-up issue: #7806

File: test/integration/singlecluster/scheduler/suite_test.go (hunk 4 above)
Comment (Singularity23x0) [reply test/integration/singlecluster/scheduler/suite_test.go:78]: Ahh I see.

File: test/integration/framework/framework.go (hunk 2 above)
Comment (Singularity23x0) [reply test/integration/framework/framework.go]: Ok, i see the issue. 

Well then as I stated - I think updating mgrOptions directly instead of using managerSetupOptions removes unnecessary busywork and the cost of direct access to options seems negligible given we are talking about tests.

But leaving as is is also okay - leaving it up to you to decide.

**Review by Singularity23x0 — APPROVED** [review]

File: test/integration/framework/framework.go (hunk 2 above)
Comment (olekzabl) [reply test/integration/framework/framework.go]: After thinking of it again - done.

**Comment by PBundyra** [comment]
Nice, thanks!
/lgtm

**Comment by mimowo** [comment]
@olekzabl please prepare CPs manually in case the automated cherrypick fails

**Comment by olekzabl** [comment]
> @olekzabl please prepare CPs manually in case the automated cherrypick fails

Hmm, I don't see any activity from [k8s-infra-cherrypick-robot](https://github.com/k8s-infra-cherrypick-robot) following your earlier cherrypick slash-commands. No idea why.

I'll retry these commands below, though not sure if I have permissions for this.

File: test/integration/singlecluster/scheduler/suite_test.go [hunk 8]
```diff
@@ -100,3 +116,44 @@ func managerAndSchedulerSetup(ctx context.Context, mgr manager.Manager) {
 	err = sched.Start(ctx)
 	gomega.Expect(err).NotTo(gomega.HaveOccurred())
 }
+
+func setupInterceptedClient() (context.Context, client.Client) {
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/suite_test.go:120]: btw, I think it is nice to see this PR paves the way for simulating API server errors. We have some older code which is not tested wrt error handling because we never added the mechanism. For example https://github.com/kubernetes-sigs/kueue/pull/7364, but many more in the past.

Now I can refer to this PR as an example for covering error cases in integration tests. Thanks ! 

cc @PBundyra @pajakd .
