### PR TITLE
TAS: NodeHotSwap should not add "late pods" to UnhealthyNodes

### LINKED ISSUE #10750: TAS: NodeHotSwap should not add "late pods" to UnhealthyNodes
**What happened**:

**What you expected to happen**:

TAS: NodeHotSwap should not add "late pods" to UnhealthyNodes. 

This is something we encountered investigating the incident mostly fixed by https://github.com/kubernetes-sigs/kueue/issues/10660, but this issue still remains - the "late pods" should not be added to UnhealthyNodes on re-admission.

Consider the following scenario:
1. Workload is running, all Pods are running
2. One of the pods (on Node "x") starts to terminate, and roughly at the same time the Workload is evicted (for another reason) - this removes the Pod from Unhealthy Pods
3. the Pod is terminating very long, either due to Node "x" failure, or just long terminationGracePeriodSeconds
4. the workload is re-admitted and the Pods get to run, the new toplogyAssignement does not mention node "x"
5. the "late pod" - terminating from (2.) is still added to UnhealthyNodes - this triggers unnecessary work by Kueue scheduler 

**How to reproduce it (as minimally and precisely as possible)**:

 I think we can repro  that in integration or e2e tests.

**Anything else we need to know?**:

The scenario encountered on the real cluster also included a custom admission check, but AFAIK it is not relevant for the repro.

### PR DESCRIPTION
**Pull request by j-skiba**
#### What type of PR is this?
/kind bug
/area tas

#### What this PR does / why we need it:
A workload's UnhealthyNodes list may be polluted by nodes that no longer belong to the workload if 'late pods' are still present on them.

#### Which issue(s) this PR fixes:
Fixes #10750

#### Does this PR introduce a user-facing change?
```release-note
TAS: Refine the NodeHotSwap logic to ensure that UnhealthyNodes are only updated for workloads currently assigned to a Node via a topology topology assignment. This prevents "late pods" from stale topologies from triggering inaccurate health reporting.
```

> AI Assistance Disclosure: This pull request was created with the assistance of AI

### CODE REVIEW

File: test/integration/singlecluster/tas/tas_test.go [hunk 1]
```diff
@@ -1535,6 +1535,110 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
 					util.ExpectWorkloadsToBePending(ctx, k8sClient, wl2)
 				})
 			})
+
+			ginkgo.It("should not add unhealthy node when node is deleted but late pods exist", framework.SlowSpec, func() {
```
Comment (j-skiba) [inline test/integration/singlecluster/tas/tas_test.go:1539]: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10760/pull-kueue-test-integration-extended-main/2048638833209118720

```bash
{ failed [FAILED] Failed after 0.262s.
The function passed to Consistently failed at /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/tas/tas_test.go:1627 with:
Expected
    <[]v1beta2.UnhealthyNode | len:1, cap:1>: [{Name: "x3"}]
to be empty
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/tas/tas_test.go:1628 @ 04/27/26 06:03:55.181
}
```

File: pkg/controller/tas/node_controller_test.go [hunk 2]
```diff
@@ -317,6 +339,55 @@ func TestNodeFailureReconciler(t *testing.T) {
...
+					Annotation(kueue.WorkloadAnnotation, wlName).
+					Annotation(kueue.PodSetUnconstrainedTopologyAnnotation, "true").
+					NodeSelector(corev1.LabelHostname, nodeName).
+					StatusPhase(corev1.PodPending).
+					Obj(),
+			},
+			reconcileRequests:    []reconcile.Request{{NamespacedName: types.NamespacedName{Name: nodeName}}},
+			wantUnhealthyNodes:   nil,
+			ignoreUnhealthyNodes: false,
+		},
```
Comment (j-skiba) [inline pkg/controller/tas/node_controller_test.go:369]: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10760/pull-kueue-test-unit-main/2048650511183253504
```bash
{Failed  === RUN   TestNodeFailureReconciler/NodeReady_missing,_late_pod_exists_for_reassigned_workload_->_UnhealthyNodes_not_polluted
    node_controller.go:133: "level"=2 "msg"="Reconcile Node"
    node_controller.go:173: "level"=3 "msg"="NodeReady condition is missing. Marking as failed immediately"
    node_controller_test.go:1035: Unexpected unhealthyNodes in status (-want/+got):
          []v1beta2.UnhealthyNode(
        - 	nil,
        + 	{{Name: "test-node-name"}},
          )
--- FAIL: TestNodeFailureReconciler/NodeReady_missing,_late_pod_exists_for_reassigned_workload_->_UnhealthyNodes_not_polluted (0.06s)
}
```

File: pkg/controller/tas/node_controller_test.go [hunk 3]
```diff
@@ -317,6 +339,55 @@ func TestNodeFailureReconciler(t *testing.T) {
...
+					NodeSelector(corev1.LabelHostname, nodeName).
+					StatusPhase(corev1.PodPending).
+					Obj(),
+			},
+			reconcileRequests:    []reconcile.Request{{NamespacedName: types.NamespacedName{Name: nodeName}}},
+			wantUnhealthyNodes:   nil,
+			ignoreUnhealthyNodes: false,
+			injectPatchError:     true,
+			wantError:            false,
+		},
```
Comment (j-skiba) [inline pkg/controller/tas/node_controller_test.go:389]: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10760/pull-kueue-test-unit-main/2048650511183253504
```bash
{Failed  === RUN   TestNodeFailureReconciler/Node_NotReady,_timer_expired,_patch_fails_during_removal_->_UnhealthyNodes_not_polluted
    node_controller.go:133: "level"=2 "msg"="Reconcile Node"
    node_controller.go:179: "level"=3 "msg"="Node is not ready and NodeFailureDelay timer expired, marking as failed"
    node_controller.go:584: "msg"="Failed to patch workload status" "error"="injected patch error on removal" "workload"={"name"="test-workload" "namespace"="default"}
    node_controller_test.go:1025: Reconcile() error = injected patch error on removal, wantError false for request /test-node-name
    node_controller_test.go:1035: Unexpected unhealthyNodes in status (-want/+got):
          []v1beta2.UnhealthyNode(
        - 	nil,
        + 	{{Name: "test-node-name"}},
          )
--- FAIL: TestNodeFailureReconciler/Node_NotReady,_timer_expired,_patch_fails_during_removal_->_UnhealthyNodes_not_polluted (0.04s)
}
```

File: pkg/controller/tas/node_controller_test.go [hunk 4]
```diff
@@ -317,6 +339,55 @@ func TestNodeFailureReconciler(t *testing.T) {
...
+				testingpod.MakePod("late-pod", nsName).
+					Annotation(kueue.WorkloadAnnotation, wlName).
+					Annotation(kueue.PodSetUnconstrainedTopologyAnnotation, "true").
+					NodeSelector(corev1.LabelHostname, nodeName).
+					StatusPhase(corev1.PodPending).
+					Obj(),
+			},
+			reconcileRequests:    []reconcile.Request{{NamespacedName: types.NamespacedName{Name: nodeName}}},
+			wantUnhealthyNodes:   nil,
+			ignoreUnhealthyNodes: false,
```
Comment (j-skiba) [inline pkg/controller/tas/node_controller_test.go:368]: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10760/pull-kueue-test-unit-main/2048650511183253504
```bash
{Failed  === RUN   TestNodeFailureReconciler/Node_Deleted,_late_pod_exists_for_reassigned_workload_->_UnhealthyNodes_not_polluted
    node_controller.go:133: "level"=2 "msg"="Reconcile Node"
    node_controller.go:167: "level"=3 "msg"="Node not found. Marking as failed immediately"
    node_controller_test.go:1035: Unexpected unhealthyNodes in status (-want/+got):
          []v1beta2.UnhealthyNode(
        - 	nil,
        + 	{{Name: "test-node-name"}},
          )
--- FAIL: TestNodeFailureReconciler/Node_Deleted,_late_pod_exists_for_reassigned_workload_->_UnhealthyNodes_not_polluted (0.07s)
}
```

File: test/integration/singlecluster/tas/tas_test.go [hunk 5]
```diff
@@ -1535,6 +1535,218 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+					podToCleanup := &corev1.Pod{}
+					gomega.Eventually(func(g gomega.Gomega) {
+						g.Expect(k8sClient.Get(ctx, apitypes.NamespacedName{Name: terminatingPodName, Namespace: ns.Name}, podToCleanup)).To(gomega.Succeed())
+						podToCleanup.Finalizers = nil
+						g.Expect(k8sClient.Update(ctx, podToCleanup)).Should(gomega.Succeed())
+						g.Expect(client.IgnoreNotFound(k8sClient.Delete(ctx, podToCleanup))).To(gomega.Succeed())
+					}, util.Timeout, util.Interval).Should(gomega.Succeed())
+				})
+			})
+
```
Comment (j-skiba) [inline test/integration/singlecluster/tas/tas_test.go:1749]: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10760/pull-kueue-test-integration-extended-main/2048668443435077632
```bash
{ failed [FAILED] Failed after 0.261s.
The function passed to Consistently failed at /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/tas/tas_test.go:1735 with:
Expected
    <[]v1beta2.UnhealthyNode | len:1, cap:1>: [{Name: "x3"}]
to be empty
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/tas/tas_test.go:1736 @ 04/27/26 07:48:54.612
}
```

File: pkg/controller/tas/node_controller.go [hunk 6]
```diff
@@ -304,25 +306,19 @@ func groupPodsByWorkload(pods []corev1.Pod) map[types.NamespacedName][]*corev1.P
...
-func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string, nodeSelectorPodsByWorkload map[types.NamespacedName][]*corev1.Pod) (sets.Set[types.NamespacedName], error) {
-	var workloadsOnNode kueue.WorkloadList
-	if err := r.client.List(ctx, &workloadsOnNode, client.MatchingFields{indexer.AdmittedWorkloadNodesKey: nodeName}); err != nil {
-		return nil, fmt.Errorf("failed to list workloads: %w", err)
-	}
-	tasWorkloadsOnNode := sets.New[types.NamespacedName]()
-	for i := range workloadsOnNode.Items {
-		wl := &workloadsOnNode.Items[i]
-		tasWorkloadsOnNode.Insert(types.NamespacedName{Name: wl.Name, Namespace: wl.Namespace})
+func (r *nodeReconciler) getWorkloadsFromLatePods(
```
Comment (pajakd) [inline pkg/controller/tas/node_controller.go]: Lets add a comment what this function does.

File: pkg/controller/tas/node_controller.go [hunk 7]
```diff
@@ -331,9 +327,23 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
 		if !workload.IsFinished(&wl) && !workload.IsEvicted(&wl) {
-			tasWorkloadsOnNode.Insert(wlKey)
+			latePodWorkloads.Insert(wlKey)
 		}
 	}
+	return latePodWorkloads, nodeSelectorPodsByWorkload, nil
+}
+
+// getWorkloadsOnNode gets all workloads that have the given node assigned in TAS topology assignment
+func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string) (sets.Set[types.NamespacedName], error) {
```
Comment (pajakd) [inline pkg/controller/tas/node_controller.go]: I'm thinking about renames to include the method of selecting the workloads on the node. The names will be long but perhaps will make the code easier to follow? WDYT?

getWorkloadsOnNode -> getWorkloadsOnNodeFromTASAssignment
getWorkloadsFromLatePods -> getWorkloadsOnNodeFromLatePods

File: pkg/controller/tas/node_controller_test.go [hunk 8]
```diff
@@ -74,6 +77,24 @@ func TestNodeFailureReconciler(t *testing.T) {
...
+					TopologyAssignment(utiltestingapi.MakeTopologyAssignment([]string{corev1.LabelHostname}).
+						Domains(utiltestingapi.MakeTopologyDomainAssignment([]string{nodeName2}, 1).Obj()).
+						Obj()).
+					Obj()).
+				Obj(), testStartTime,
+		).
+		AdmittedAt(true, testStartTime).
+		Obj()
+	workloadReassignedWithUnhealthyNode := workloadReassigned.DeepCopy()
+	workloadReassignedWithUnhealthyNode.Status.UnhealthyNodes = []kueue.UnhealthyNode{{Name: nodeName}}
```
Comment (pajakd) [inline pkg/controller/tas/node_controller_test.go]: do we use this variable somewhere? we should not see this state, right?

File: pkg/controller/tas/node_controller.go (hunk 7 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: sounds good. Actually I think that `getWorkloads*LatePods` might be even a little misleading, practically the function doesn't necessarily get workloads from "late pods", it gets workloads from any pods that have specific nodeSelector, the "lateness" of the pod is decided later. I would propose something like `getWorkloadsFromPodsOnNode` and the second one `getWorkloadsOnNodeFromTASAssignment`. wdyt?

File: test/integration/singlecluster/tas/tas_test.go (hunk 1 above)
Comment (pajakd) [reply test/integration/singlecluster/tas/tas_test.go:1539]: I assume this is a result of test run prior to code change.

File: pkg/controller/tas/node_controller_test.go (hunk 8 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller_test.go]: it was unused, removed

File: test/integration/singlecluster/tas/tas_test.go (hunk 1 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:1539]: correct

File: test/integration/singlecluster/tas/tas_test.go [hunk 9]
```diff
@@ -1535,6 +1535,218 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+				})
+
+				ginkgo.By("verify unhealthy nodes is not polluted", func() {
+					gomega.Consistently(func(g gomega.Gomega) {
+						g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(wl), wl)).To(gomega.Succeed())
+						g.Expect(wl.Status.UnhealthyNodes).Should(gomega.BeEmpty())
+					}, util.ConsistentDuration, util.Interval).Should(gomega.Succeed())
+				})
+
+				ginkgo.By("cleanup pod finalizer", func() {
```
Comment (pajakd) [inline test/integration/singlecluster/tas/tas_test.go:1739]: do we need it? I guess the test could stop after verifying that we don't unnecessarily add to unhealthy nodes.

Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:1739]: As I understand it, the pod with the finalizer will persist until all tests finish unless we explicitly remove that finalizer.

File: test/integration/singlecluster/tas/tas_test.go [hunk 10]
```diff
@@ -1535,6 +1535,218 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+							podCopy.Finalizers = append(podCopy.Finalizers, "kueue.x-k8s.io/dummy-finalizer")
+							gomega.Expect(k8sClient.Update(ctx, podCopy)).Should(gomega.Succeed())
+							gomega.Expect(k8sClient.Delete(ctx, podCopy)).Should(gomega.Succeed())
+						} else {
+							gomega.Expect(k8sClient.Delete(ctx, podCopy)).Should(gomega.Succeed())
+						}
+					}
+				})
+
+				ginkgo.By("make node NotReady to trigger node replacement", func() {
```
Comment (pajakd) [inline test/integration/singlecluster/tas/tas_test.go]: "make node x3 ..."

File: pkg/controller/tas/node_controller.go (hunk 7 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done.

I also moved `listPodsAssignedByNodeSelector` call outside of `getWorkloadsFromPodsOnNode` - I think it makes more sense this way because we don't have to return `nodeSelectorPodsByWorkload` from `getWorkloadsFromPodsOnNode`.

File: pkg/controller/tas/node_controller.go (hunk 6 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: test/integration/singlecluster/tas/tas_test.go (hunk 10 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: updated

**Comment by mimowo** [comment]
Thank you!
/lgtm
/approve
/cherrypick release-0.17
/cherrypick release-0.16

**Comment by mimowo** [comment]
/release-note-edit
```release-note
TAS: Refine the NodeHotSwap logic to ensure that UnhealthyNodes are only updated for workloads currently assigned to a Node via a topology topology assignment. This prevents "late pods" from stale topologies from triggering inaccurate health reporting.
```
