### PR TITLE
Fix integration tests fail after upgrade to 1.32.

### LINKED ISSUE #4027: Integration tests fail after upgrade to 1.32
**What happened**:

The integration tests fail due to new validation.

https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-integration-main

**What you expected to happen**:

The integration tests should pass.

**How to reproduce it (as minimally and precisely as possible)**:

Every periodic build will fail. Also, run locally the integration tests with;

INTEGRATION_NPROCS=4 INTEGRATION_TARGET=./test/integration/controller/jobs/job make test-integration

**Anything else we need to know?**:

The tests are marked as "slow" so didn't fail the attempt to merge.
When marking Job as complete we need to also set the StartTime, Completion time and the SuccessCriteriaMet condition. Some tests already do it.

```
{Expected success, but got an error:
    <*errors.StatusError | 0xc0009443c0>: 
    Job.batch "test-job" is invalid: [status.completionTime: Required value: completionTime is required for Complete jobs, status.conditions: Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition, status.startTime: Required value: startTime is required for finished job]
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Job.batch \"test-job\" is invalid: [status.completionTime: Required value: completionTime is required for Complete jobs, status.conditions: Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition, status.startTime: Required value: startTime is required for finished job]",
            Reason: "Invalid",
            Details: {
                Name: "test-job",
                Group: "batch",
                Kind: "Job",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueRequired",
                        Message: "Required value: completionTime is required for Complete jobs",
                        Field: "status.completionTime",
                    },
                    {
                        Type: "FieldValueInvalid",
                        Message: "Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition",
                        Field: "status.conditions",
                    },
                    {
                        Type: "FieldValueRequired",
                        Message: "Required value: startTime is required for finished job",
                        Field: "status.startTime",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc0009443c0>: 
    Job.batch "test-job" is invalid: [status.completionTime: Required value: completionTime is required for Complete jobs, status.conditions: Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition, status.startTime: Required value: startTime is required for finished job]
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Job.batch \"test-job\" is invalid: [status.completionTime: Required value: completionTime is required for Complete jobs, status.conditions: Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition, status.startTime: Required value: startTime is required for finished job]",
            Reason: "Invalid",
            Details: {
                Name: "test-job",
                Group: "batch",
                Kind: "Job",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueRequired",
                        Message: "Required value: completionTime is required for Complete jobs",
                        Field: "status.completionTime",
                    },
                    {
                        Type: "FieldValueInvalid",
                        Message: "Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition",
                        Field: "status.conditions",
                    },
                    {
                        Type: "FieldValueRequired",
                        Message: "Required value: startTime is required for finished job",
                        Field: "status.startTime",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/controller/jobs/job/job_controller_test.go:275 @ 01/21/25 06:18:52.853

```

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:
Fix integration tests fail after upgrade to 1.32.

#### Which issue(s) this PR fixes:

Fixes #4027

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thank you for fixing this.
That makes sense for this patch since we changed batch/v1 Job completion mechanism when we introduced JobSuccessPolicy: https://github.com/kubernetes/kubernetes/pull/126067

```
Graduate the Job SuccessPolicy to Beta.

The new reason label, "SuccessPolicy" and "CompletionsReached" are added to the "jobs_finished_total" metric.
Additionally, If we enable the "JobSuccessPolicy" feature gate, the Job gets "CompletionsReached" reason for the "SuccessCriteriaMet" and "Complete" condition type
when the number of succeeded Job Pods (".status.succeeded") reached the desired completions (".spec.completions").
```

My question is the reason why this change happened in v1.32? We enabled this feature by default in v1.31.

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 1]
```diff
@@ -265,13 +265,22 @@ var _ = ginkgo.Describe("Job controller", ginkgo.Ordered, ginkgo.ContinueOnFailu
 		}, util.ConsistentDuration, util.Interval).Should(gomega.Succeed())
 
 		ginkgo.By("checking the workload is finished when job is completed")
+		createdJob.Status.StartTime = ptr.To(metav1.Now())
```
Comment (gabesaba) [inline test/integration/controller/jobs/job/job_controller_test.go:268]: is there any chance of flakiness if metav1.Now() returns a later time in one of the following calls? if so, can we store as variable and reuse it? otherwise, i like it this way

**Review by gabesaba — COMMENTED** [review]
/lgtm

thanks for the fix

**Comment by mbobrovskyi** [comment]
> My question is the reason why this change happened in v1.32? We enabled this feature by default in v1.31.

I remember adding these updates in v1.31, but only for MultiKueue https://github.com/kubernetes-sigs/kueue/pull/2402/commits/0a131303374423280e114cbb5ac207ee11722503.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 1 above)
Comment (tenzen-y) [reply test/integration/controller/jobs/job/job_controller_test.go:268]: I think that there is no flakiness since we verify only .type and .status in Line 287.

**Comment by tenzen-y** [comment]
> > My question is the reason why this change happened in v1.32? We enabled this feature by default in v1.31.
> 
> I remember adding these updates in v1.31, but only for MultiKueue (see [here](https://github.com/kubernetes-sigs/kueue/pull/2402/commits/0a131303374423280e114cbb5ac207ee11722503)).

Ah, I see. That makes sense. Thank you for pointing out!
/approve

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/integration/controller/jobs/job/job_controller_test.go]: I can't see some validation on Kubernetes part. But to be make sure that it will not happens I added now variable to use common time and using reconciler ([2d77757](https://github.com/kubernetes-sigs/kueue/pull/4029/commits/2d777578e01f9c1ce1134da9e971aff42e750264)).
