### PR TITLE
[Cache] Sort resourceUsages according to resourceName

### LINKED ISSUE #902: ClusterQueue update events continue to fire forever
**What happened**:
`ClusterQueueStatus.flavorsUsage.resources` with random order continues to fire ClusterQueue update events forever, and the number of reconciles will explode.
Therefore kueue-controller-manager much increases the load of kube-apiserver and etcd.

**What you expected to happen**:
ClusterQueues aren't updated if the old and the new ones have the same usage.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25
- Kueue version (use `git describe --tags --dirty --always`): v0.3.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
The resourceUsages should be in a stable order to avoid endless creation of update events.
So, I added processes to sort resourceUsages according to resourceName in ClusterQueue and LocalQueue. 

#### Which issue(s) this PR fixes:

Fixes #902

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug that updates events for clusterQueues are created endlessly.
```

### CODE REVIEW

File: pkg/cache/cache_test.go [hunk 1]
```diff
@@ -1449,15 +1481,18 @@ func TestClusterQueueUsage(t *testing.T) {
...
-			if err != nil {
-				t.Fatalf("Couldn't get usage: %v", err)
-			}
-			if diff := cmp.Diff(tc.wantUsedResources, resources); diff != "" {
-				t.Errorf("Unexpected used resources (-want,+got):\n%s", diff)
-			}
-			if workloads != tc.wantWorkloads {
-				t.Errorf("Got %d workloads, want %d", workloads, tc.wantWorkloads)
+			// We must check whether the same order of 'flavorUsage' is returned.
+			for i := 0; i < 10; i++ {
```
Comment (alculquicondor) [inline pkg/cache/cache_test.go:1485]: Do we need to test this many times? We already run the entire suite of unit tests 3 times. I suspect that flakiness would be enough.

**Review by alculquicondor — COMMENTED** [review]
/approve
I would just remove the loops

File: pkg/cache/cache_test.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/cache/cache_test.go]: It makes sense.
Done.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
let's cherry-pick as well.
I think we can do a last patch release of 0.3 along with 0.4

**Comment by tenzen-y** [comment]
> let's cherry-pick as well.
> I think we can do a last patch release of 0.3 along with 0.4

That's great!

/cherrypick release-0.3
