### PR TITLE
Fix flaky PyTorchJob e2e test

### LINKED ISSUE #7947: [flaky test] TopologyAwareScheduling for PyTorchJob when Creating a PyTorchJob Should place pods based on the ranks-ordering
**What happened**:

failed on unrelated branch: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7936/pull-kueue-test-e2e-tas-release-0-13/1993989254161633280

**What you expected to happen**:
no fail
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:
```
End To End TAS Suite: kindest/node:v1.33.1: [It] TopologyAwareScheduling for PyTorchJob when Creating a PyTorchJob Should place pods based on the ranks-ordering expand_less	48s
{Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:222 with:
Expected
    <[]v1.Pod | len:1, cap:1>: [
        {
            TypeMeta: {Kind: "", APIVersion: ""},
            ObjectMeta: {
                Name: "ranks-pytorch-worker-1",
                GenerateName: "",
                Namespace: "e2e-tas-pytorchjob-8xk46",
                SelfLink: "",
                UID: "dd80373b-b110-4225-9bee-61c69c46255d",
                ResourceVersion: "4945",
                Generation: 3,
                CreationTimestamp: {
                    Time: 2025-11-27T10:38:13Z,
                },
                DeletionTimestamp: {
                    Time: 2025-11-27T10:38:44Z,
                },
                DeletionGracePeriodSeconds: 30,
                Labels: {
                    "kueue.x-k8s.io/podset": "worker",
                    "kueue.x-k8s.io/tas": "true",
                    "training.kubeflow.org/job-name": "ranks-pytorch",
                    "training.kubeflow.org/operator-name": "pytorchjob-controller",
                    "training.kubeflow.org/replica-index": "1",
                    "training.kubeflow.org/replica-type": "worker",
                },
                Annotations: {
                    "kueue.x-k8s.io/workload": "pytorchjob-ranks-pytorch-d7bd1",
                    "kueue.x-k8s.io/podset-preferred-topology": "cloud.provider.com/topology-block",
                },
                OwnerReferences: [
                    {
                        APIVersion: "kubeflow.org/v1",
                        Kind: "PyTorchJob",
                        Name: "ranks-pytorch",
                        UID: "c6c9b129-515a-40d9-a374-12aa1d4df178",
                        Controller: true,
                        BlockOwnerDeletion: true,
                    },
                ],
                Finalizers: nil,
                ManagedFields: [
                    {
                        Manager: "manager",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2025-11-27T10:38:13Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kueue.x-k8s.io/podset-preferred-topology\":{},\"f:kueue.x-k8s.io/workload\":{}},\"f:labels\":{\".\":{},\"f:kueue.x-k8s.io/podset\":{},\"f:kueue.x-k8s.io/tas\":{},\"f:training.kubeflow.org/job-name\":{},\"f:training.kubeflow.org/operator-name\":{},\"f:training.kubeflow.org/replica-index\":{},\"f:training.kubeflow.org/replica-type\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"c6c9b129-515a-40d9-a374-12aa1d4df178\\\"}\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"pytorch\\\"}\":{\".\":{},\"f:args\":{},\"f:env\":{\".\":{},\"k:{\\\"name\\\":\\\"MASTER_ADDR\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"MASTER_PORT\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_MASTER_ADDR\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_MASTER_PORT\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_NNODES\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_NODE_RANK\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_NPROC_PER_NODE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PYTHONUNBUFFERED\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RANK\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"WORLD_SIZE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}}},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:name\":{},\"f:ports\":{\".\":{},\"k:{\\\"containerPort\\\":23456,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:containerPort\":{},\"f:name\":{},\"f:protocol\":{}}},\"f:resources\":{\".\":{},\"f:limits\":{\".\":{},\"f:example.com/gpu\":{}},\"f:requests\":{\".\":{},\"f:example.com/gpu\":{}}},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{}}},\"f...

Gomega truncated this representation as it exceeds 'format.MaxLength'.
Consider having the object provide a custom 'GomegaStringer' representation
or adjust the parameters in Gomega's 'format' package.

Learn more here: https://onsi.github.io/gomega/#adjusting-output

to be empty failed [FAILED] Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:222 with:
Expected
    <[]v1.Pod | len:1, cap:1>: [
        {
            TypeMeta: {Kind: "", APIVersion: ""},
            ObjectMeta: {
                Name: "ranks-pytorch-worker-1",
                GenerateName: "",
                Namespace: "e2e-tas-pytorchjob-8xk46",
                SelfLink: "",
                UID: "dd80373b-b110-4225-9bee-61c69c46255d",
                ResourceVersion: "4945",
                Generation: 3,
                CreationTimestamp: {
                    Time: 2025-11-27T10:38:13Z,
                },
                DeletionTimestamp: {
                    Time: 2025-11-27T10:38:44Z,
                },
                DeletionGracePeriodSeconds: 30,
                Labels: {
                    "kueue.x-k8s.io/podset": "worker",
                    "kueue.x-k8s.io/tas": "true",
                    "training.kubeflow.org/job-name": "ranks-pytorch",
                    "training.kubeflow.org/operator-name": "pytorchjob-controller",
                    "training.kubeflow.org/replica-index": "1",
                    "training.kubeflow.org/replica-type": "worker",
                },
                Annotations: {
                    "kueue.x-k8s.io/workload": "pytorchjob-ranks-pytorch-d7bd1",
                    "kueue.x-k8s.io/podset-preferred-topology": "cloud.provider.com/topology-block",
                },
                OwnerReferences: [
                    {
                        APIVersion: "kubeflow.org/v1",
                        Kind: "PyTorchJob",
                        Name: "ranks-pytorch",
                        UID: "c6c9b129-515a-40d9-a374-12aa1d4df178",
                        Controller: true,
                        BlockOwnerDeletion: true,
                    },
                ],
                Finalizers: nil,
                ManagedFields: [
                    {
                        Manager: "manager",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2025-11-27T10:38:13Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kueue.x-k8s.io/podset-preferred-topology\":{},\"f:kueue.x-k8s.io/workload\":{}},\"f:labels\":{\".\":{},\"f:kueue.x-k8s.io/podset\":{},\"f:kueue.x-k8s.io/tas\":{},\"f:training.kubeflow.org/job-name\":{},\"f:training.kubeflow.org/operator-name\":{},\"f:training.kubeflow.org/replica-index\":{},\"f:training.kubeflow.org/replica-type\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"c6c9b129-515a-40d9-a374-12aa1d4df178\\\"}\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"pytorch\\\"}\":{\".\":{},\"f:args\":{},\"f:env\":{\".\":{},\"k:{\\\"name\\\":\\\"MASTER_ADDR\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"MASTER_PORT\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_MASTER_ADDR\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_MASTER_PORT\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_NNODES\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_NODE_RANK\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PET_NPROC_PER_NODE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"PYTHONUNBUFFERED\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RANK\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"WORLD_SIZE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}}},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:name\":{},\"f:ports\":{\".\":{},\"k:{\\\"containerPort\\\":23456,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:containerPort\":{},\"f:name\":{},\"f:protocol\":{}}},\"f:resources\":{\".\":{},\"f:limits\":{\".\":{},\"f:example.com/gpu\":{}},\"f:requests\":{\".\":{},\"f:example.com/gpu\":{}}},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{}}},\"f...

Gomega truncated this representation as it exceeds 'format.MaxLength'.
Consider having the object provide a custom 'GomegaStringer' representation
or adjust the parameters in Gomega's 'format' package.

Learn more here: https://onsi.github.io/gomega/#adjusting-output

to be empty
In [AfterEach] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/tas/pytorch_test.go:79 @ 11/27/25 10:39:00.836
}
```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind flake
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #7947

#### Special notes for your reviewer:

see: https://github.com/kubernetes-sigs/kueue/issues/7947#issuecomment-3585353971 and the follow up comment

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go [hunk 1]
```diff
@@ -92,7 +92,8 @@ func (j *PyTorchJobWrapper) PyTorchReplicaSpecsOnlyMasterDefault() *PyTorchJobWr
 						},
 					},
 				},
-				NodeSelector: map[string]string{},
+				NodeSelector:                  map[string]string{},
+				TerminationGracePeriodSeconds: ptr.To[int64](1),
```
Comment (mimowo) [inline pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go:96]: I'm also considering making it opt-in per test, but it seems to me there can be more tests affected, so we would need to add it to all probably. I think we can have a function to opt-out in the future if some test needs longer termination, but I doubt that.

Comment (tenzen-y) [reply pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go:96]: Ideally, I would like to have E2E test dedicated wrappers like `PyTorchReplicaSpecsOnlyMasterDefaultWithTerminationGracePeriodSeconds` since this field doesn't matter for UTs and integration Test.

But, for now, this change could contribute to making flaky tests silent.
So, we can merge this PR for right now.
