### PR TITLE
Fix "Deployment should admit workloads after change queue-name if AvailableReplicas = 0" e2e test.

### LINKED ISSUE #5161: [Flaky E2E Test]: Deployment should admit workloads after change queue-name if AvailableReplicas = 0
**What happened**:
End To End Suite: kindest/node:v1.30.10: [It] Deployment should admit workloads after change queue-name if AvailableReplicas = 0

```
{Expected
    <[]v1.Condition | len:0, cap:0>: nil
to have condition type QuotaReserved and status False failed [FAILED] Expected
    <[]v1.Condition | len:0, cap:0>: nil
to have condition type QuotaReserved and status False
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/deployment_test.go:168 @ 05/05/25 11:22:26.192
}
```

**What you expected to happen**:

No errors

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5160/pull-kueue-test-e2e-main-1-30/1919348839219728384

**Anything else we need to know?**:

/kind flake

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind flake
/kind failing-test

#### What this PR does / why we need it:
Fix "Deployment should admit workloads after change queue-name if AvailableReplicas = 0" e2e test.

#### Which issue(s) this PR fixes:

Fixes #5161

#### Special notes for your reviewer:
The problem is that sometimes workloads don’t have enough time to reach QuotaReservation=false (which we're checking below) after the pods running. We should use `gomega.Eventually` to ensure this condition is met.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/singlecluster/deployment_test.go [hunk 1]
```diff
@@ -154,20 +152,17 @@ var _ = ginkgo.Describe("Deployment", func() {
 		pods := &corev1.PodList{}
 		gomega.Expect(k8sClient.List(ctx, pods, client.InNamespace(ns.Name),
 			client.MatchingLabels(deployment.Spec.Selector.MatchLabels))).To(gomega.Succeed())
+		gomega.Expect(pods.Items).To(gomega.HaveLen(3))
```
Comment (mimowo) [inline test/e2e/singlecluster/deployment_test.go:155]: Please describe (also in PR description) what was the problem and why the change helps.

Comment (mbobrovskyi) [reply test/e2e/singlecluster/deployment_test.go:155]: The problem is that sometimes workloads don’t have enough time to reach QuotaReservation=false (which we're checking below) after the pods start running. We should use `gomega.Eventually` to ensure this condition is met.

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Thanks!
/cherry-pick release-0.11
/cherry-pick release-0.10
