### PR TITLE
Add E2E regression tests for HA follower cache stale ghost workload bug

### LINKED ISSUE #10529: Add e2e tests for failover after the leader is changed
**What would you like to be added**:

I would like to add e2e tests, probably in the "customconfigs" suite which would detect the bug reported in https://github.com/kubernetes-sigs/kueue/issues/10495. In particular we want to check the preemptions are not blocked on the bug.

In particular they could guard against regressions related to any potential changes due to https://github.com/kubernetes-sigs/kueue/issues/10553

**Why is this needed**:

To ensure the problem does not return as a regression again. This bit of code seems quite sensitive yet not well tested.

### PR DESCRIPTION
**Pull request by reruno**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #10529

#### Special notes for your reviewer:

I reverted https://github.com/kubernetes-sigs/kueue/pull/10518 to break the newly added test, to see if the test catches regression that it suppose to catch 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by reruno** [comment]
I reverted https://github.com/kubernetes-sigs/kueue/pull/10518 to break the newly added test, to see if the test catches regression that it suppose to catch

The test failed as expected here are the results 
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10811/pull-kueue-test-e2e-sequential-baseline-main/2049041361864232960

File: test/e2e/sequential/baseline/ha_failover_test.go [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+		util.MustCreate(ctx, k8sClient, wl1)
+		util.ExpectWorkloadsToBeAdmitted(ctx, k8sClient, wl1)
+
+		ginkgo.By("deleting workload-1")
+		util.ExpectObjectToBeDeleted(ctx, k8sClient, wl1, true)
+
+		ginkgo.By("forcing a leader failover so the former follower becomes the new leader")
+		util.ForceLeaderFailover(ctx, k8sClient)
+
+		ginkgo.By("creating workload-2 and expecting the new leader to admit it")
```
Comment (mszadkow) [inline test/e2e/sequential/baseline/ha_failover_test.go:86]: I think we are missing the part of `check the preemptions are not blocked on the bug`.
There is no workload that needs to be preempted

File: test/e2e/sequential/baseline/ha_failover_test.go [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+	"github.com/onsi/ginkgo/v2"
+	"github.com/onsi/gomega"
+	corev1 "k8s.io/api/core/v1"
+
+	kueue "sigs.k8s.io/kueue/apis/kueue/v1beta2"
+	utiltestingapi "sigs.k8s.io/kueue/pkg/util/testing/v1beta2"
+	"sigs.k8s.io/kueue/test/util"
+)
+
+var _ = ginkgo.Describe("HA Failover", ginkgo.Label("feature:hafailover"), func() {
```
Comment (mbobrovskyi) [inline test/e2e/sequential/baseline/ha_failover_test.go]:
```suggestion
var _ = ginkgo.Describe("HA Failover", ginkgo.Label("feature:ha"), func() {
```
?

Comment (mbobrovskyi) [inline test/e2e/sequential/baseline/ha_failover_test.go]: Also, could you please add this to the documentation (https://github.com/kubernetes-sigs/kueue/blob/9a434bf1e825875a5af480515288385dfff3a511/Makefile-test.mk#L135 and https://github.com/kubernetes-sigs/kueue/blob/9a434bf1e825875a5af480515288385dfff3a511/site/content/en/docs/contribution_guidelines/testing.md?plain=1#L244)?

Comment (reruno) [reply test/e2e/sequential/baseline/ha_failover_test.go]: I named the feature after the filename, we do that in other files as well 
```
# test/e2e/sequential/baseline/podintegrationautoenablement_test.go
var _ = ginkgo.Describe("Auto-Enablement of Pod Integration for Pod-Dependent Frameworks", ginkgo.Label("feature:podintegrationautoenablement"), ginkgo.Ordered, func() {
```

File: test/e2e/sequential/baseline/ha_failover_test.go [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+
+		lq := utiltestingapi.MakeLocalQueue("lq", ns.Name).ClusterQueue("cq").Obj()
+		util.CreateLocalQueuesAndWaitForActive(ctx, k8sClient, lq)
+		ginkgo.DeferCleanup(func() {
+			util.ExpectObjectToBeDeleted(ctx, k8sClient, lq, true)
+		})
+
+		ginkgo.By("admitting workload-a so it enters both leader and follower caches")
+		wl1 := utiltestingapi.MakeWorkload("workload-1", ns.Name).
+			Queue(kueue.LocalQueueName("lq")).
```
Comment (mbobrovskyi) [inline test/e2e/sequential/baseline/ha_failover_test.go]:
```suggestion
			Queue(kueue.LocalQueueName(lq.Name)).
```

File: test/e2e/sequential/baseline/ha_failover_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/e2e/sequential/baseline/ha_failover_test.go]: Hmm, interesting. I thought we should specify the feature name.

File: test/e2e/sequential/baseline/ha_failover_test.go (hunk 3 above)
Comment (mbobrovskyi) [reply test/e2e/sequential/baseline/ha_failover_test.go]: Also other places.

File: test/util/e2e.go [hunk 4]
```diff
@@ -529,6 +529,34 @@ func waitForKueueAvailability(ctx context.Context, k8sClient client.Client, chec
...
+	gomega.Expect(k8sClient.Get(ctx, leaseKey, lease)).To(gomega.Succeed())
+
+	holderIdentity := ptr.Deref(lease.Spec.HolderIdentity, "")
+	gomega.Expect(holderIdentity).NotTo(gomega.BeEmpty(), "expected a current leader to be elected")
+	leaderPodName := strings.SplitN(holderIdentity, "_", 2)[0]
+
+	ginkgo.By(fmt.Sprintf("Deleting leader pod %q to force failover", leaderPodName))
+	leaderPod := &corev1.Pod{}
+	gomega.Expect(k8sClient.Get(ctx, types.NamespacedName{Namespace: kueueNS, Name: leaderPodName}, leaderPod)).To(gomega.Succeed())
+	gomega.Expect(k8sClient.Delete(ctx, leaderPod)).To(gomega.Succeed())
```
Comment (mbobrovskyi) [inline test/util/e2e.go]:
```suggestion
	leaderPod := &corev1.Pod{ObjectMeta: metav1.ObjectMeta{Namespace: kueueNS, Name: leaderPodName}}
	gomega.Expect(k8sClient.Delete(ctx, leaderPod)).To(gomega.Succeed())
```

File: test/e2e/sequential/baseline/ha_failover_test.go [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+		gomega.Expect(util.DeleteNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
+		util.WaitForKueueAvailabilityNoRestartCountCheck(ctx, k8sClient)
+	})
+
+	// Verifies the regression: ghost workload blocks admission of a new workload
+	// on the newly elected leader.
+	ginkgo.It("should admit a workload after leader failover when a previously admitted workload was deleted", func() {
+		rf := utiltestingapi.MakeResourceFlavor("rf").Obj()
+		util.MustCreate(ctx, k8sClient, rf)
+		ginkgo.DeferCleanup(func() {
```
Comment (mbobrovskyi) [inline test/e2e/sequential/baseline/ha_failover_test.go]: Can we move it to BeforeEach/AfterEach ?

File: test/e2e/sequential/baseline/ha_failover_test.go (hunk 2 above)
Comment (mbobrovskyi) [inline test/e2e/sequential/baseline/ha_failover_test.go]: It looks like there are no config changes or restarts required. Can we move it to singlecluster?

Comment (mszadkow) [reply test/e2e/sequential/baseline/ha_failover_test.go]: But we delete one of the pods of the kueue-controller-manager

Comment (reruno) [reply test/e2e/sequential/baseline/ha_failover_test.go]: We forcefully remove one of the controller managers, This may affect other tests in singlecluster. The sequential  will ensure that the test's forceful removal of controller manager will not affect other test run.

Comment (mbobrovskyi) [reply test/e2e/sequential/baseline/ha_failover_test.go]: Sounds reasonable.

File: test/e2e/sequential/baseline/ha_failover_test.go (hunk 1 above)
Comment (reruno) [reply test/e2e/sequential/baseline/ha_failover_test.go:86]: Added new test case 
`"should admit a high-priority workload after lower-priority workload-1 removal and leader failover with preemption of existing lower-priority workload-2"`

**Comment by mimowo** [comment]
Awesome, thank you for the PR and reviewing it 👍  Having the tests will help us prevent nasty bugs like https://github.com/kubernetes-sigs/kueue/issues/10495 in the future.

**Comment by mimowo** [comment]
/cherrypick release-0.17
/cherrypick release-0.16
So that we can also cover the previous branches with the new test. Ideally the test would have accompanied the bugfix and be cherrypicked back then, but at that point we only relied on manual testing.

**Comment by mimowo** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10811/pull-kueue-test-e2e-sequential-baseline-main/2049803326844833792

This failure looks quite related, let's make sure the test is stable before merging

**Comment by reruno** [comment]
> https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10811/pull-kueue-test-e2e-sequential-baseline-main/2049803326844833792
> 
> This failure looks quite related, let's make sure the test is stable before merging

Fixed the issue, I had to reset kueue configuration before test run, that was the problem

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Thanks 👍
