### PR TITLE
MultiKueue + TAS setup script: bump Kueue to 0.16

### LINKED ISSUE #7350: [MultiKueue] Eviction initiated on manager doesn't work
**What happened**:
I'm trying to create high priority job to preempt low priority job but it is not working as expect. The workload stuck on.

Status from high priority job:

```yaml
- lastTransitionTime: "2025-10-23T06:33:18Z"
   message: 'couldn''t assign flavors to pod set main: insufficient unused quota
    for memory in flavor default, 1953125Ki more needed. Pending the preemption
    of 1 workload(s)'
   observedGeneration: 1
   reason: Pending
   status: "False"
   type: QuotaReserved
```

Status from low priority job:

```yaml
conditions:
  - lastTransitionTime: "2025-10-23T06:33:17Z"
   message: Quota reserved in ClusterQueue q1
   observedGeneration: 1
   reason: QuotaReserved
   status: "True"
   type: QuotaReserved
  - lastTransitionTime: "2025-10-23T06:33:18Z"
   message: 'Preempted to accommodate a workload (UID: 9f542104-a9e2-4344-ad2e-9c136204da18,
    JobUID: a20d0a6a-64a3-46ce-9b95-8cfb3bf6e675) due to prioritization in the
    ClusterQueue'
   observedGeneration: 1
   reason: Preempted
   status: "True"
   type: Evicted
  - lastTransitionTime: "2025-10-23T06:33:18Z"
   message: The workload is admitted
   observedGeneration: 1
   reason: Admitted
   status: "True"
   type: Admitted
  - lastTransitionTime: "2025-10-23T06:33:18Z"
   message: 'Preempted to accommodate a workload (UID: 9f542104-a9e2-4344-ad2e-9c136204da18,
    JobUID: a20d0a6a-64a3-46ce-9b95-8cfb3bf6e675) due to prioritization in the
    ClusterQueue'
   reason: InClusterQueue
   status: "True"
   type: Preempted
```

Logs from the manager cluster occurring in a loop:

```
2025-10-23T07:13:10.668141483Z	DEBUG	events	recorder/recorder.go:104	couldn't assign flavors to pod set main: insufficient unused quota for memory in flavor default, 1953125Ki more needed. Pending the preemption of 1 workload(s)	{"type": "Warning", "object": {"kind":"Workload","namespace":"multikueue-vggw9","name":"job-job2-f620a","uid":"4cc488da-107c-4814-8248-b44ac9462816","apiVersion":"kueue.x-k8s.io/v1beta1","resourceVersion":"14153"}, "reason": "Pending"}
2025-10-23T07:13:10.76844517Z	LEVEL(-3)	scheduler	queue/manager.go:661	Obtained ClusterQueue heads	{"schedulingCycle": 12168, "count": 1}
2025-10-23T07:13:10.768592836Z	LEVEL(-3)	scheduler	scheduler/fair_sharing_iterator.go:69	Returning workload from ClusterQueue without Cohort	{"schedulingCycle": 12168, "clusterQueue": {"name":"q1"}, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}}
2025-10-23T07:13:10.768610128Z	LEVEL(-2)	scheduler	scheduler/scheduler.go:252	Attempting to schedule workload	{"schedulingCycle": 12168, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}, "clusterQueue": {"name":"q1"}}
2025-10-23T07:13:10.768633711Z	LEVEL(-3)	scheduler	preemption/preemption.go:190	Preemption ongoing	{"schedulingCycle": 12168, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}, "clusterQueue": {"name":"q1"}, "targetWorkload": {"name":"job-job1-6f320","namespace":"multikueue-vggw9"}, "preemptingWorkload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}}
2025-10-23T07:13:10.768676628Z	LEVEL(-3)	scheduler	scheduler/logging.go:42	Workload evaluated for admission	{"schedulingCycle": 12168, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}, "clusterQueue": {"name":"q1"}, "status": "", "reason": "couldn't assign flavors to pod set main: insufficient unused quota for memory in flavor default, 1953125Ki more needed. Pending the preemption of 1 workload(s)"}
2025-10-23T07:13:10.768709211Z	LEVEL(-2)	scheduler	scheduler/scheduler.go:778	Workload re-queued	{"schedulingCycle": 12168, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}, "clusterQueue": {"name":"q1"}, "queue": {"name":"q1","namespace":"multikueue-vggw9"}, "requeueReason": "PendingPreemption", "added": true, "status": ""}
```

**What you expected to happen**:
The high priority job should be successfully admitted.

**How to reproduce it (as minimally and precisely as possible)**:
- Create low priority job
- Create high priority job

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by olekzabl**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

It bumps the Kueue version used in the [MultiKueue + TAS setup script](https://kueue.sigs.k8s.io/docs/tasks/dev/setup_multikueue_development_environment/) from 0.15.0 to 0.16.0.

Kueue 0.16 brings some relevant improvements, e.g. #8151 which fixed #7350.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

I wonder if we have some `latest-stable` tag or so? Then it'd be perfect to use it here.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by olekzabl** [comment]
@kshalot PTAL

File: site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh [hunk 1]
```diff
@@ -18,7 +18,7 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
-KUEUE_VERSION="${KUEUE_VERSION:-v0.15.0}"
+KUEUE_VERSION="${KUEUE_VERSION:-v0.16.0}"
```
Comment (mbobrovskyi) [inline site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh]:
```suggestion
DEFAULT_KUEUE_VERSION=v0.16.1
KUEUE_VERSION="${KUEUE_VERSION:-${DEFAULT_KUEUE_VERSION}}"
```

File: site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh [hunk 2]
```diff
@@ -38,7 +38,7 @@ while [[ $# -gt 0 ]]; do
             echo "Unknown option: $1"
             echo "Usage: $0 [--main] [--version VERSION]"
             echo "  --main           Use main branch instead of released version"
-            echo "  --version        Specify Kueue version (default: v0.15.0)"
+            echo "  --version        Specify Kueue version (default: v0.16.0)"
```
Comment (mbobrovskyi) [inline site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh]:
```suggestion
            echo "  --version        Specify Kueue version (default: ${DEFAULT_KUEUE_VERSION})"
```

**Comment by mimowo** [comment]
/approve
leaving LGTM to @mbobrovskyi

File: site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh (hunk 1 above)
Comment (kshalot) [inline site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh]: How do we want to keep this up to date?

How about sth like:
```sh
git tag | grep -v '-' | sort -V | tail -n 1
```

I think this script is usually ran in the context of the GitHub repo, even in the docs:
https://kueue.sigs.k8s.io/docs/tasks/dev/setup_multikueue_development_environment/#automated-setup

But we could add some default to be safe if you prefer.

I'm not sure what's the alternative. Make this part of the release checklist? Manually bump from time to time when we feel like it?

Comment (kshalot) [reply site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh]: From what I can see, there are several places where the version is hardcoded.

1. In the doc it's still set to `0.15.0`: https://kueue.sigs.k8s.io/docs/tasks/dev/setup_multikueue_development_environment/#step-2-install-kueue-on-all-clusters
2. `kueue-populator` is hardcoded to `0.16.0`: https://github.com/kubernetes-sigs/kueue/blob/3b299a308129f840bd01f53f3a038015fbc801fc/cmd/experimental/kueue-populator/run-e2e.sh#L24
Btw. doesn't this mean that there is a version skew between the manifests version and the code that the populator tests are running? I don't see anything overriding `KUEUE_VERSION` here or in test-infra. cc @mimowo

Comment (mimowo) [reply site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh]: > How about sth like: git tag | grep -v '-' | sort -V | tail -n 1

This is reasonable, but may give unexpected results on historical release branches. For example may end up building 0.15.5 release using 0.16.3 dependency, resulting in release failure. So we need to be more careful I think.

> I'm not sure what's the alternative. Make this part of the release checklist? Manually bump from time to time when we feel like it?

Maybe the alternative is to bump it during the release process, for that we have the Makefile target: `prepare-release-branch`. Then, on release branches we will keep updating to the lastest patch. On the main branch we will update to the "0" patch, next will be 0.17.0.  On top of that we could manually bump to the latest patch on-demand. 

Still, to avoid surprises on releases, I would rather use what is put in plain text, rather than magic like `git tag | grep -v '-' | sort -V | tail -n 1`, but no strong view here - fine as long as we make it reliable.

> Btw. doesn't this mean that there is a version skew between the manifests version and the code that the populator tests are running? I don't see anything overriding KUEUE_VERSION here or in test-infra. cc @mimowo

Yeah, it is probably not ideal. This is the same we do for KueueViz. OTOH, handling version skew is "normal" - users cannot bump both components atomically anyway. So using the latest full release bumped by `prepare-release-branch` seems reasonable to me.

Comment (mimowo) [reply site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh]: ok, we can address the automation in a follow up, could you just for now bump to 0.16.1 which is the latest?
Basically addressing comments by @mbobrovskyi makes sense to me.

Comment (olekzabl) [reply site/static/examples/multikueue/dev/setup-kind-multikueue-tas.sh]: > _could you just for now bump to 0.16.1 which is the latest?_
> _Basically addressing comments by @mbobrovskyi makes sense to me._

Done that :)

**Comment by mimowo** [comment]
/lgtm 
/approve
/cherrypick website
Let me open a follow up issue to automate it on releases

**Comment by mimowo** [comment]
> Let me open a follow up issue to automate it on releases

Actually, I have a better idea (I think). Instead of the custom script which needs to be maintained for the website, we could have a dedicated CI job testing the MultiKueue-TAS setup. Similarly as we are testing MultiKueue+DRA here: https://github.com/kubernetes-sigs/kueue/tree/main/test/e2e/multikueue-dra.

Given the importance of both MultiKueue and TAS I think this makes sense. Then, developers would just execute locally `E2E_MODE=dev make kind-image-build test-multikueue-tas-e2e`, as describe here: https://kueue.sigs.k8s.io/docs/contribution_guidelines/testing/

And the script will be self-maintained by the tests.

**Comment by mimowo** [comment]
Opened proposal issue: https://github.com/kubernetes-sigs/kueue/issues/9380

**Comment by olekzabl** [comment]
> Actually, I have a better idea (I think). Instead of the custom script which needs to be maintained for the website, we could have a dedicated CI job testing the MultiKueue-TAS setup. Similarly as we are testing MultiKueue+DRA here: https://github.com/kubernetes-sigs/kueue/tree/main/test/e2e/multikueue-dra.
> 
> Given the importance of both MultiKueue and TAS I think this makes sense. Then, developers would just execute locally `E2E_MODE=dev make kind-image-build test-multikueue-tas-e2e`, as describe here: https://kueue.sigs.k8s.io/docs/contribution_guidelines/testing/
> 
> And the script will be self-maintained by the tests.

While #9380 makes sense, I'd be still happy to have sth not requiring local dev build.

`make kind-image-build` takes some time, while recently I used `setup-kind-multikueue-tas.sh` up to several times per hour (often "actively waiting" for it to finish).

**Comment by mimowo** [comment]
> I'd be still happy to have sth not requiring local dev build.

Do you mean to have something that works on the GKE cluster rather than Kind?

Indeed, while `E2E_MODE=dev` can reuse existing clusters it is not able to provision clusters on GKE, so it may not be as friendly as `setup-kind-multikueue-tas.sh` in some cases. If there are good use cases, I'm ok to keep both solutions for now.

FWIIW: In case of using the Kind cluster you should be able to skip the `kind-image-build`  goal if nothing changed in the code.

**Comment by olekzabl** [comment]
> Do you mean to have something that works on the GKE cluster rather than Kind?

No, I meant kind, but using a released Kueue image. So that I don't have to build the image locally.

> FWIIW: In case of using the Kind cluster you should be able to skip the kind-image-build goal if nothing changed in the code.

Interesting. I'll check that. Though I'd assume for this I need to have a `vX.Y.Z` branch checked out in my local repo? Or can it skip building also on a clean `main`?

**Comment by mimowo** [comment]
> No, I meant kind, but using a released Kueue image. So that I don't have to build the image locally.

Good question. I always build it myself 

> Interesting. I'll check that. Though I'd assume for this I need to have a vX.Y.Z branch checked out in my local repo?
> Or can it skip building also on a clean main?

I think for now we need to rebuild from the specific branch. Let me open an issue to investigate / add this option of reusing a released version. 

Opened: https://github.com/kubernetes-sigs/kueue/issues/9415
