### PR TITLE
Fix stuck pods bug for node replacement

### LINKED ISSUE #9616: Terminate forever pending pods for node replacement
**What happened**:

After pods are assigned to some node by topology assignment and before are ungated (and given `nodeSelector` for that specific node) it might happen that in between these two events a node can be tainted or become `NotReady`. In such scenario these pods would be stuck in `Pending` state as they are bound to a node by `nodeSelector` but will not be scheduled on a node because of a taint or `NotReady` condition.

 Pods would be stuck like this and replacement pods would not be created because the existing pending pods are still waiting to be scheduled.

That is necessary for node replacement mechanism to work as expected. Currently topology assignment for a workload will be updated but the pods will stay `Pending` forever until deleted manually.

**What you expected to happen**:

We should handle such pods as described here - https://github.com/kubernetes-sigs/kueue/blob/main/keps/2724-topology-aware-scheduling/README.md#tainted-nodes-treatment

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/kubernetes-sigs/kueue/pull/9615 - shown here as an e2e test

**Anything else we need to know?**:
---

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by j-skiba**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

https://github.com/kubernetes-sigs/kueue/pull/8997#discussion_r2863877179

After pods are assigned to some node by topology assignment and before are ungated (and given nodeSelector for that specific node) it might happen that in between these two events a node can be tainted or become NotReady. In such scenario these pods would be stuck in Pending state as they are bound to a node by nodeSelector but will not be scheduled on a node because of a taint or NotReady condition.

Pods would be stuck like this and replacement pods would not be created because the existing pending pods are still waiting to be scheduled.

This PR introduces mechanism of waiting for all pods expected to be on a node. Only then when all pods are there we proceed with unhealthy node handling.

#### Which issue(s) this PR fixes:
Fixes #9616

#### Does this PR introduce a user-facing change?

```release-note
TAS: Fixed a bug where pods could become stuck in a `Pending` state during node replacement.
This may occur when a node gets tainted or `NotReady` after the topology assignment phase, but before
the pods are ungated.
```

### CODE REVIEW

File: pkg/controller/tas/node_failure_controller.go [hunk 1]
```diff
@@ -396,6 +423,44 @@ func (r *nodeFailureReconciler) reconcileWorkloadsOnNode(ctx context.Context, no
...
+		if pod.Status.Phase == corev1.PodPending && !utilpod.HasGate(pod, kueue.TopologySchedulingGate) {
+			podsToTerminate = append(podsToTerminate, pod)
+		} else {
+			hasPodsToRetain = true
+		}
+	}
+	return
+}
+
+func (r *nodeFailureReconciler) terminatePods(ctx context.Context, pods []*corev1.Pod) error {
```
Comment (mwielgus) [inline pkg/controller/tas/node_failure_controller.go]: The name of the function suggests that the pods are terminated. Yet, only the status of the pod is updated. Either:
* delete the pod,
* provide comment,
* rename the funciton.

Comment (mimowo) [reply pkg/controller/tas/node_failure_controller.go]: Setting the Pod's phase to Failed triggers Pod termination by Kubelet. We may clarify that in the comment indeed.

File: pkg/controller/tas/node_failure_controller.go [hunk 2]
```diff
@@ -453,6 +515,72 @@ func (r *nodeFailureReconciler) addUnhealthyNode(ctx context.Context, wl *kueue.
...
+// (spec.nodeName) or by having a TAS assignment that maps to this node (via nodeSelector).
+func isPodAssignedToNode(pod *corev1.Pod, nodeName string, levels []string) bool {
+	if pod.Spec.NodeName != "" {
+		return pod.Spec.NodeName == nodeName
+	}
+	if len(pod.Spec.NodeSelector) == 0 || len(levels) == 0 {
+		return false
+	}
+	key := levels[len(levels)-1]
+	val, ok := pod.Spec.NodeSelector[key]
```
Comment (mwielgus) [inline pkg/controller/tas/node_failure_controller.go]: It is not always guaranteed that the lowest level of topology is node. What happens if it is not?

File: pkg/controller/tas/node_failure_controller.go (hunk 1 above)
Comment (j-skiba) [reply pkg/controller/tas/node_failure_controller.go]: I renamed the method to `markPodsFailed`

File: pkg/controller/tas/node_failure_controller.go (hunk 2 above)
Comment (j-skiba) [reply pkg/controller/tas/node_failure_controller.go]: I added check if hostname is the lowest level and then if they match. Otherwise it would be hard to tell what we should do if hostname is not the lowest level

File: test/e2e/tas/hotswap_test.go [hunk 3]
```diff
@@ -498,6 +498,200 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+								corev1.ResourceCPU: resource.MustParse("200m"),
+								extraResource:      resource.MustParse("1"),
+							},
+							Limits: corev1.ResourceList{
+								corev1.ResourceCPU: resource.MustParse("200m"),
+								extraResource:      resource.MustParse("1"),
+							},
+						},
+					},
+				}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: nit, I think we could we use the Wrapper (builders) for setting tat

File: test/e2e/tas/hotswap_test.go [hunk 4]
```diff
@@ -498,6 +498,200 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+					kueue.PodSetSliceRequiredTopologyAnnotation: utiltesting.DefaultBlockTopologyLevel,
+					kueue.PodSetSliceSizeAnnotation:             "3",
+				}
+				sampleJob.Spec.CompletionMode = ptr.To(batchv1.IndexedCompletion)
+				sampleJob.Spec.BackoffLimit = ptr.To[int32](1)
+
+				// Add the artificial scheduling gate to the pod template
+				sampleJob.Spec.Template.Spec.SchedulingGates = []corev1.PodSchedulingGate{
+					{Name: artificialGate},
+				}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: Same here, if some helpers are missing like for scheduling gates, then let's add them to build a useful library of helpers for the future.

File: test/e2e/tas/hotswap_test.go [hunk 5]
```diff
@@ -498,6 +498,200 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+						g.Expect(wls.Items).To(gomega.HaveLen(1))
+						g.Expect(wls.Items[0].Status.Admission).NotTo(gomega.BeNil())
+						g.Expect(wls.Items[0].Status.Admission.PodSetAssignments).To(gomega.HaveLen(1))
+						g.Expect(wls.Items[0].Status.Admission.PodSetAssignments[0].TopologyAssignment).NotTo(gomega.BeNil())
+						wlName = wls.Items[0].Name
+					}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+				})
+
+				wlKey := client.ObjectKey{Name: wlName, Namespace: ns.Name}
+				initialNodes := []string{"kind-worker", "kind-worker2", "kind-worker3"}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: nit, could we easily read the nodes from the `TopologyAssignment`?

File: test/e2e/tas/hotswap_test.go [hunk 6]
```diff
@@ -498,6 +498,200 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+					for _, p := range pods.Items {
+						gomega.Eventually(func(g gomega.Gomega) {
+							updatedPod := &corev1.Pod{}
+							g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(&p), updatedPod)).To(gomega.Succeed())
+							newGates := []corev1.PodSchedulingGate{}
+							for _, g := range updatedPod.Spec.SchedulingGates {
+								if g.Name != artificialGate {
+									newGates = append(newGates, g)
+								}
+							}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: We already have a helper to ungate a pod in https://github.com/kubernetes-sigs/kueue/blob/f8f2a53b55f48ad7e544e26d7be49cf308e6698f/pkg/util/pod/pod.go#L48
can we reuse?

File: test/e2e/tas/hotswap_test.go [hunk 7]
```diff
@@ -498,6 +498,200 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+							updatedPod.Spec.SchedulingGates = newGates
+							g.Expect(k8sClient.Update(ctx, updatedPod)).To(gomega.Succeed())
+						}, util.Timeout, util.Interval).Should(gomega.Succeed())
+					}
+				})
+
+				var replacementPodName string
+				ginkgo.By("Wait for the victim pod to be Failed and the replacement pod to be created", func() {
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: nit, This assert is pretty heave, can we split into two phases?

File: test/e2e/tas/hotswap_test.go [hunk 8]
```diff
@@ -498,6 +498,200 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+						g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: replacementPodName, Namespace: ns.Name}, updatedPod)).To(gomega.Succeed())
+						foundArtificialGate := false
+						newGates := []corev1.PodSchedulingGate{}
+						for _, gate := range updatedPod.Spec.SchedulingGates {
+							if gate.Name == artificialGate {
+								foundArtificialGate = true
+							} else {
+								newGates = append(newGates, gate)
+							}
+						}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: Also this looks like one-liner with the helpers for ungating we have

File: test/e2e/tas/hotswap_test.go [hunk 9]
```diff
@@ -498,6 +498,200 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+							updatedPod.Spec.SchedulingGates = newGates
+							g.Expect(k8sClient.Update(ctx, updatedPod)).To(gomega.Succeed())
+							g.Expect(foundArtificialGate).To(gomega.BeFalse(), "Still found artificial gate, retrying...")
+						}
+					}, util.Timeout, util.Interval).Should(gomega.Succeed())
+				})
+
+				ginkgo.By("Check that the topology assignment is updated with the new node in the same block", func() {
+					expectedNodes := []string{}
+					for _, n := range []string{"kind-worker", "kind-worker2", "kind-worker3", "kind-worker4"} {
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: Why the assignment still has `kind-worker` (4 workers in total). I would expect after the replacement we will only have 3 workers, new ones (one per Pod). We still will have 3 running pods iiuc.

File: pkg/controller/tas/node_failure_controller.go [hunk 10]
```diff
@@ -234,63 +248,67 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
+	return workloadHealthCheck{status: workloadHealthy}, nil
 }
 
-// listPodsForWorkload returns pods belonging to a workload.
-func (r *nodeFailureReconciler) listPodsForWorkload(ctx context.Context, wl *kueue.Workload) ([]*corev1.Pod, error) {
-	return ListPodsForWorkloadSlice(ctx, r.client, wl.Namespace, workloadslicing.SliceName(wl))
+func (r *nodeFailureReconciler) checkPodsOnNode(ctx context.Context, nodeName string, wl *kueue.Workload, wlKey types.NamespacedName, untolerated []corev1.Taint, ready bool) (workloadHealthCheck, error) {
+	podsAssigned, hasGatedPods, err := r.getPodsAssignedToNode(ctx, wl, nodeName)
+	if err != nil {
+		return workloadHealthCheck{status: workloadHealthy}, fmt.Errorf("failed to get pods assigned to node %s: %w", nodeName, err)
```
Comment (mimowo) [inline pkg/controller/tas/node_failure_controller.go]: Maybe the behavior is the same, but should't we return workloadHealthUnknown - if we couldn't list the pods, then we couldn't determine the health. Unless I'm missing something.

File: pkg/controller/tas/node_controller.go [hunk 11]
```diff
@@ -396,6 +420,44 @@ func (r *nodeFailureReconciler) reconcileWorkloadsOnNode(ctx context.Context, no
...
 
+func classifyPodsForReplacement(pods []*corev1.Pod) (podsToTerminate []*corev1.Pod, hasPodsToRetain bool) {
+	for _, pod := range pods {
+		if !pod.DeletionTimestamp.IsZero() || utilpod.IsTerminated(pod) {
+			continue
+		}
+		if pod.Status.Phase == corev1.PodPending && !utilpod.HasGate(pod, kueue.TopologySchedulingGate) {
+			podsToTerminate = append(podsToTerminate, pod)
+		} else {
+			hasPodsToRetain = true
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: This information is redundant, if you need it then declare the variable outside. You can just derive it by `hasPodsToRetain := len(input)  > len(podsToTerminate)`

File: pkg/controller/tas/node_failure_controller.go [hunk 12]
```diff
@@ -234,63 +248,67 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
+		// but they are still pending nodeSelector injection by TopologyUngater.
+		log := ctrl.LoggerFrom(ctx).WithValues("workload", klog.KRef(wlKey.Namespace, wlKey.Name))
+		log.V(2).Info("Found gated pods for assigned workload, waiting for TopologyUngater to inject nodeSelector")
+		return workloadHealthCheck{status: workloadHealthUnknown}, nil
+	}
+
+	// Identify pods that need to be terminated (pending pods on tainted nodes)
+	// and check if there are any pods that should be retained (e.g. running or gated).
+	podsToTerminate, hasPodsToRetain := classifyPodsForReplacement(podsAssigned)
+	if len(podsToTerminate) > 0 && (len(untolerated) > 0 || !ready) {
```
Comment (mimowo) [inline pkg/controller/tas/node_failure_controller.go]: Could we check `&& (len(untolerated) > 0 || !ready)` already inside `classifyPodsForReplacement`? 
I think this is confusing that we say `podsToTerminate` from `classifyPodsForReplacement`, but later check some extra conditions if they are "really to terminate"

File: pkg/controller/tas/node_failure_controller.go [hunk 13]
```diff
@@ -234,63 +248,67 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
-// listPodsForWorkload returns pods belonging to a workload.
-func (r *nodeFailureReconciler) listPodsForWorkload(ctx context.Context, wl *kueue.Workload) ([]*corev1.Pod, error) {
-	return ListPodsForWorkloadSlice(ctx, r.client, wl.Namespace, workloadslicing.SliceName(wl))
+func (r *nodeFailureReconciler) checkPodsOnNode(ctx context.Context, nodeName string, wl *kueue.Workload, wlKey types.NamespacedName, untolerated []corev1.Taint, ready bool) (workloadHealthCheck, error) {
+	podsAssigned, hasGatedPods, err := r.getPodsAssignedToNode(ctx, wl, nodeName)
+	if err != nil {
+		return workloadHealthCheck{status: workloadHealthy}, fmt.Errorf("failed to get pods assigned to node %s: %w", nodeName, err)
+	}
+
+	if hasGatedPods && len(podsAssigned) == 0 {
```
Comment (mimowo) [inline pkg/controller/tas/node_failure_controller.go]: This feels flaky. What if the Pods are just not created yet. Then we will have `hasGatedPods=false`.

So, I'm thinking we can step into `return workloadHealthCheck{status: workloadUnhealthy}, nil`, meaning replacing the Node, but without termination , and if the Pods get created just a little bit later before the replacement is done they may still land on the old node.

One solution for such (rare) cases could be waitForPodsReady.recoveryTimeout, but I'm wondering if we could do better.

So, I'm wondering we should wait for all Pods to be created here to collect them all for termination. We can determine the expected number of Pods based on the TopologyAssignment.

Let me know if I'm missing something. Quite possible, because the logic here is rather tricky.

File: pkg/controller/tas/node_controller.go [hunk 14]
```diff
@@ -360,15 +378,21 @@ func (r *nodeFailureReconciler) reconcileWorkloadsOnNode(ctx context.Context, no
...
 		if err != nil {
 			return ctrl.Result{}, err
 		}
 
-		switch status {
+		if len(result.podsToTerminate) > 0 {
+			if err := r.markPodsFailed(ctx, result.podsToTerminate); err != nil {
+				return ctrl.Result{}, fmt.Errorf("marking pods as failed: %w", err)
+			}
+		}
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go:476]: I have a doubt here - if there are multiple nodes for which the workload is unhealthy, eg. a disconnected rack, then we don't need to terminate the Pods at all - we could just rely on the eviction, right?

I guess it is ok-ish, but if feasible I would like to limit the termination only to the pods when we have no choice.

Let me know if you already analyzed that and concluded this is not easy. I guess it is ok-ish for Kueue to terminate them all, but it is also unnecessary work, because the eviction will trigger deletion of them anyway.

File: pkg/controller/tas/node_failure_controller.go (hunk 13 above)
Comment (j-skiba) [reply pkg/controller/tas/node_failure_controller.go]: Maybe we should react on pod events.

Then we could leave the logic there more or less as it is now and react on late pods and mark them as failed if necessary.

File: pkg/controller/tas/node_controller.go (hunk 14 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go:476]: We could do that by moving this code after `handleUnhealthyNode` call - https://github.com/kubernetes-sigs/kueue/pull/9615/changes#diff-93673c3cede5afdcdae4bf5c2f6458b3eb861d36947784567c1e73d309e73e21L380

Comment (j-skiba) [reply pkg/controller/tas/node_controller.go:476]: by that we would not call `markPodsFailed` twice

File: pkg/controller/tas/node_failure_controller.go (hunk 13 above)
Comment (mimowo) [reply pkg/controller/tas/node_failure_controller.go]: Yes I belive reacting to pod events is the goos idea. Im just not sure if this is needed foe the PR or later refactor. Hard to tell without getting hands dirty

Comment (mimowo) [reply pkg/controller/tas/node_failure_controller.go]: I **think** for now I would rely on the 1s reconcile while Unhealthy as currently, to avoid any bigger refactor.

File: pkg/controller/tas/node_controller.go (hunk 11 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: I think we need this because there is
```go
if !pod.DeletionTimestamp.IsZero() || utilpod.IsTerminated(pod) {
	continue
}
```
above and it filters some pods out.

Let's say 3/4 pods succeeded and 1 is pending then with `hasPodsToRetain := len(input)  > len(podsToTerminate)` we would give invalid information

File: pkg/controller/tas/node_failure_controller.go (hunk 13 above)
Comment (j-skiba) [reply pkg/controller/tas/node_failure_controller.go]: I've been thinking about this and I think to properly handle all scenarios it might be necessary to implement event driven approach. An example is described here https://github.com/kubernetes-sigs/kueue/pull/9710 - `Event-Driven Correctness over Polling`

Comment (j-skiba) [reply pkg/controller/tas/node_failure_controller.go]: I think the final solution would be to do this

> So, I'm wondering we should wait for all Pods to be created here to collect them all for termination. We can determine the expected number of Pods based on the TopologyAssignment.

but also act on events

File: test/e2e/tas/hotswap_test.go (hunk 3 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/e2e/tas/hotswap_test.go (hunk 4 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/e2e/tas/hotswap_test.go (hunk 6 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/e2e/tas/hotswap_test.go (hunk 7 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/e2e/tas/hotswap_test.go (hunk 8 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/e2e/tas/hotswap_test.go (hunk 9 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: It was basically filtering out node that was unhealthy.
I changed that to use slices.DeleteFunc like in other tests.

File: pkg/controller/tas/node_failure_controller.go (hunk 10 above)
Comment (j-skiba) [reply pkg/controller/tas/node_failure_controller.go]: yes `workloadHealthUnknown` makes more sense - fixed

File: pkg/controller/tas/node_failure_controller.go (hunk 13 above)
Comment (j-skiba) [reply pkg/controller/tas/node_failure_controller.go]: Changes summary:

- now we wait for all expected pods to be present on a node, when we finally have all of the expected pods on the node then we proceed with handling of an unhealthy node followed by optional stuck pending pods termination
- late stuck pending pods that were recreated after termination of stuck pending by the node failure controller are handled by event based handling

File: pkg/controller/tas/indexer/indexer.go [hunk 15]
```diff
@@ -54,6 +55,22 @@ func indexPodWorkload(o client.Object) []string {
...
 }
 
+func indexPodNodeName(o client.Object) []string {
+	pod, ok := o.(*corev1.Pod)
+	if !ok || !utiltas.IsTAS(pod) {
+		return nil
+	}
+	if pod.Spec.NodeName != "" {
+		return []string{pod.Spec.NodeName}
+	}
```
Comment (mimowo) [inline pkg/controller/tas/indexer/indexer.go]: Wait, I think the new code should only be terminating Pods which are unschedulable. Such Pods by definition don't have NodeName. Terminating Pods with NodeName set is risky as it may mean killing Pods which are doing useful work.

Unless, I'm missing something.

File: pkg/controller/tas/node_controller.go [hunk 16]
```diff
@@ -257,6 +275,26 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
+	if err := r.client.List(ctx, &podList, client.MatchingFields{indexer.PodNodeNameKey: nodeName}); err != nil {
+		return nil, fmt.Errorf("failed to list pods bound to node: %w", err)
+	}
+
+	for i := range podList.Items {
+		pod := &podList.Items[i]
+		wlName := pod.Labels[kueue.WorkloadAnnotation]
+		if wlName == "" {
+			wlName = pod.Annotations[kueue.WorkloadAnnotation]
+		}
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: We already have a helper to find all Pods assigned to a Workload. If we need to pass extra limitation like the nodeName, then we should extend the existing helper with the new filtering option. 

The code I'm reading is almost certainly buggy in combination with workload slices.

File: pkg/controller/tas/node_controller.go [hunk 17]
```diff
@@ -281,63 +319,91 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
+			continue
+		}
+		for domain := range utiltas.InternalSeqFrom(psa.TopologyAssignment) {
+			if len(domain.Values) > 0 && domain.Values[len(domain.Values)-1] == nodeName {
+				expected += domain.Count
+			}
+		}
+	}
+	return expected
+}
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: Could we move the helper to `pkg/util/tas/tas_assignment.go`, maybe just pass ` wl.Status.Admission.PodSetAssignments ` instead of the entire workload.

File: pkg/controller/tas/node_controller.go [hunk 18]
```diff
@@ -435,6 +505,19 @@ func (r *nodeReconciler) reconcileWorkloadsOnNode(ctx context.Context, nodeName
 		}
 	}
 
+	for wlKey, pods := range podsToTerminateMap {
+		var wl kueue.Workload
+		err := r.client.Get(ctx, wlKey, &wl)
+		if client.IgnoreNotFound(err) != nil {
+			return ctrl.Result{}, fmt.Errorf("failed to get workload to check eviction status: %w", err)
+		}
+		if err == nil && !workload.IsEvicted(&wl) {
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I think this is not going to work, because we may not see the "wl" to be already patched, because of the delay in the event propagation. Even if our controller sent the "eviction request" it still takes time to receive it back from the API server. That is why we check `if !evictedNow && !workload.IsEvicted(&wl) {` inside handleUnhealthyNode.

File: pkg/controller/tas/node_controller.go (hunk 11 above)
Comment (mimowo) [reply pkg/controller/tas/node_controller.go]: The code evolved, but in the current shape I think the assignment `hasPodsToRetain = true` is just no-op

File: test/e2e/tas/hotswap_test.go [hunk 19]
```diff
@@ -498,6 +472,187 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+						for _, p := range pods.Items {
+							g.Expect(p.Spec.SchedulingGates).To(gomega.ContainElement(corev1.PodSchedulingGate{Name: artificialGate}))
+						}
+					}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+				})
+
+				initialUIDs := map[string]struct{}{}
+				for _, p := range pods.Items {
+					initialUIDs[string(p.UID)] = struct{}{}
+				}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: nit, use sets when this is enough, using maps to represent is not that readable

File: pkg/controller/tas/indexer/indexer.go (hunk 15 above)
Comment (j-skiba) [reply pkg/controller/tas/indexer/indexer.go]: right, that wasn't necessary. I changed that to 
```
	if pod.Spec.NodeSelector != nil && pod.Spec.NodeName == "" {
```

File: pkg/controller/tas/node_controller.go (hunk 16 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: I changed the code to use `ListPodsForWorkloadSlice`

File: pkg/controller/tas/node_controller.go (hunk 17 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/controller/tas/node_controller.go (hunk 18 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: right, that might happen.
I changed handleUnhealthyNode to return set of evicted workloads which can be used here to decide whether we handle pending pods.

File: test/e2e/tas/hotswap_test.go (hunk 19 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/e2e/tas/hotswap_test.go [hunk 20]
```diff
@@ -498,6 +472,187 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+						var replacementPod *corev1.Pod
+
+						for i := range pods.Items {
+							p := &pods.Items[i]
+							if p.Labels["batch.kubernetes.io/job-completion-index"] == "0" {
+								if _, ok := initialUIDs[string(p.UID)]; !ok {
+									replacementPod = p
+								}
+							}
+						}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: This look virtually like the code above: https://github.com/kubernetes-sigs/kueue/pull/9615/changes#diff-07939b70cb6f47dc8ed23bf44f1209770fd51fb091afc047fb4d8352b09c94e9R591-R602

Can we have a helper for it?

Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/e2e/tas/hotswap_test.go [hunk 21]
```diff
@@ -720,3 +687,35 @@ func expectPodsOnNodes(ctx context.Context, k8sClient client.Client, nsName stri
...
+		foundPod = nil
+		for i := range pods.Items {
+			p := &pods.Items[i]
+			if p.Labels["batch.kubernetes.io/job-completion-index"] == index {
+				if initialUIDs.Has(string(p.UID)) == wantInitialUID {
+					foundPod = p
+					break
+				}
+			}
+		}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: Extract this into a helper findPodByIndex()

Comment (mimowo) [reply test/e2e/tas/hotswap_test.go]: Actually that was my original ask, I don't think we need helper wrapping the entire Eventually

Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: ohh, ok - done

File: pkg/controller/tas/node_controller.go [hunk 22]
```diff
@@ -281,63 +320,72 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
+
+	podsToTerminate, hasPodsToRetain := classifyPodsForReplacement(podsAssigned, expectedOnNode)
+
+	if expectedOnNode == 0 {
+		// This node is not part of the workload's topology assignment. If pods are assigned
+		// here (e.g., late pods with old node selectors), they are stray and must be terminated.
+		return workloadHealthCheck{status: workloadHealthy, podsToTerminate: podsToTerminate}, nil
+	}
+
+	if int32(len(podsAssigned)) < expectedOnNode || hasGatedPods || (hasPodsToRetain && (len(untolerated) == 0 || features.Enabled(features.TASReplaceNodeOnPodTermination))) {
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: This check makes my head spinning. Please extract to a separete helper function and add comments to the individual checks explaining their reasoning.

File: pkg/controller/tas/node_controller.go [hunk 23]
```diff
@@ -500,6 +610,66 @@ func (r *nodeReconciler) addUnhealthyNode(ctx context.Context, wl *kueue.Workloa
...
+		return psa.TopologyAssignment.Levels
+	}
+
+	return nil
+}
+
+// getPodsAssignedToNode returns a list of pods that are assigned to the node (via spec.nodeName)
+// or are assigned by topology assignment but are not scheduled to the node (e.g. because of a taint).
+// It also returns a boolean indicating if there are any pods assigned to the Workload's topology
+// that are still gated by TopologySchedulingGate (missing nodeSelector).
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I think this function is conceptually very tricky because it mixes Pods which are assigned by TopologyAssignement with those which are bound via NodeName. These are very different classes of Pods, because we never want to terminate those which are bound (IIUC). So, I'm trying now to understand why we need both classes tracked, but also thinking if we could split them (return in separete slices). 

I'm not yet committed to that view, because I still don't understand the code overall. Some explanation would help, trying to understand in the meanwhile .

File: pkg/controller/tas/node_controller_test.go [hunk 24]
```diff
@@ -92,6 +92,22 @@ func TestNodeFailureReconciler(t *testing.T) {
 		AdmittedAt(true, testStartTime).
 		Obj()
 
+	workloadWithTwoExpectedPods := utiltestingapi.MakeWorkload(wlName, nsName).
```
Comment (mimowo) [inline pkg/controller/tas/node_controller_test.go:96]: thank you for the test, I think for this changes we need unit tests like this. Do they cover 100 percent of the new Reconcile code? At least not counting errors. You can use the golang coverage tool to check that

File: pkg/controller/tas/node_controller.go (hunk 22 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/controller/tas/node_controller_test.go (hunk 24 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller_test.go:96]: I ran it and found two things:
- I think we don't need
```go
	// If there are gated pods, the assignment/admission process is still ongoing.
	if hasGatedPods {
		return true
	}
```
it's already checked by `podsAssigned < expectedOnNode`
- refactored `getWorkloadStatus` to get better coverage
- added more unit tests to increase coverage

Comment (j-skiba) [reply pkg/controller/tas/node_controller_test.go:96]:
```bash
ok  	sigs.k8s.io/kueue/pkg/controller/tas	(cached)	coverage: 63.6% of statements
	sigs.k8s.io/kueue/pkg/controller/tas/indexer		coverage: 0.0% of statements
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:110:		WithWatchers				0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:133:		Reconcile				82.1%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:179:		Generic					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:183:		Create					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:189:		Update					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:208:		Delete					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:219:		newNodeReconciler			75.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:241:		logger					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:245:		notifyWatchers				0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:251:		SetupWithManager			0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:271:		getWorkloadsOnNode			81.2%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:302:		hasTASAssignmentOnNode			83.3%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:323:		getWorkloadStatus			95.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:366:		checkPodsOnNode				88.9%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:389:		shouldWait				100.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:413:		evictWorkloadIfNeeded			81.8%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:433:		handleUnhealthyNode			57.7%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:471:		reconcileWorkloadsOnNode		85.7%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:534:		classifyPodsForReplacement		100.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:552:		markPodsFailed				80.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:577:		handleHealthyNode			59.1%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:611:		removeUnhealthyNodes			83.3%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:623:		addUnhealthyNode			80.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:635:		isPodAssignedToNode			80.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:645:		getTopologyAssignmentLevelsForPod	87.5%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:664:		getPodsAssignedToNode			92.9%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:687:		checkTaintTolerations			88.2%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:719:		classifyNoExecuteTaints			90.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:747:		Create					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:751:		Update					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:755:		Delete					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:759:		Generic					0.0%
sigs.k8s.io/kueue/pkg/controller/tas/node_controller.go:762:		queueReconcileForPod			0.0%
```

File: pkg/controller/tas/node_controller.go [hunk 25]
```diff
@@ -253,10 +275,27 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
+		wlKey := types.NamespacedName{Name: wl.Name, Namespace: wl.Namespace}
 		if hasTASAssignmentOnNode(&wl, nodeName) {
-			tasWorkloadsOnNode.Insert(types.NamespacedName{Name: wl.Name, Namespace: wl.Namespace})
+			tasWorkloadsOnNode.Insert(wlKey)
+			continue
+		}
+
+		// Also find workloads from any pods that are bound to this node,
+		// because they might be stale "late" pods for a workload that has already
+		// been reassigned to another node.
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]:
```suggestion
		// Also find workloads from any pods that are assigned by TopologyAssignement,
		//  but not bound yet, to this node,
		// because they might be stale "late" pods for a workload that has already
		// been reassigned to another node.
```

File: pkg/controller/tas/node_controller.go [hunk 26]
```diff
@@ -443,6 +531,48 @@ func (r *nodeReconciler) reconcileWorkloadsOnNode(ctx context.Context, nodeName
...
+	for _, pod := range pods {
+		if !pod.DeletionTimestamp.IsZero() || utilpod.IsTerminated(pod) {
+			continue
+		}
+		switch {
+		case expectedOnNode > 0 && pod.Status.Phase == corev1.PodPending && !utilpod.HasGate(pod, kueue.TopologySchedulingGate):
+			podsToTerminate = append(podsToTerminate, pod)
+		case expectedOnNode == 0:
+			// Orphaned late pods without any expected nodes must be terminated
+			podsToTerminate = append(podsToTerminate, pod)
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I think the only check relevant here is `pod.Status.Phase == corev1.PodPending` (together with the ` !pod.DeletionTimestamp.IsZero() || utilpod.IsTerminated(pod) ` checked already above

File: pkg/controller/tas/node_controller.go [hunk 27]
```diff
@@ -281,63 +320,92 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
-				allPodsTerminated = false
-				break
-			}
+func (r *nodeReconciler) checkPodsOnNode(ctx context.Context, nodeName string, wl *kueue.Workload, untolerated []corev1.Taint, expectedOnNode int32) (workloadHealthCheck, error) {
+	podsAssigned, err := r.getPodsAssignedToNode(ctx, wl, nodeName)
+	if err != nil {
+		return workloadHealthCheck{status: workloadHealthUnknown}, fmt.Errorf("failed to get pods assigned to node %s: %w", nodeName, err)
+	}
+
+	podsToTerminate, hasPodsToRetain := classifyPodsForReplacement(podsAssigned, expectedOnNode)
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]:
```suggestion
	podsToTerminate, hasRunningPods := classifyPodsForReplacement(podsAssigned, expectedOnNode)
```

File: pkg/controller/tas/node_controller.go [hunk 28]
```diff
@@ -281,63 +320,92 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
+		return workloadHealthCheck{status: workloadHealthUnknown}, nil
+	}
+
+	return workloadHealthCheck{status: workloadUnhealthy, podsToTerminate: podsToTerminate}, nil
+}
+
+// shouldWait encapsulates the logic for deciding if we need to
+// wait for pods to be fully created and assigned before declaring a node failure.
+func shouldWait(podsAssigned, expectedOnNode int32, hasPodsToRetain bool, untoleratedCount int) bool {
+	// Not all expected pods have been created and assigned to the node yet.
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I have a doubt we need this check. My understading is that after we added the podHandler we will be able to terminate Pods as they get created without the need to wait for all of them to accumulate. TBD

File: pkg/controller/tas/node_controller.go (hunk 25 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: changed

File: pkg/controller/tas/node_controller.go (hunk 26 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/controller/tas/node_controller.go (hunk 27 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/controller/tas/node_controller.go [hunk 29]
```diff
@@ -281,63 +320,82 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
-func (r *nodeReconciler) listPodsForWorkload(ctx context.Context, wl *kueue.Workload) ([]*corev1.Pod, error) {
-	return ListPodsForWorkloadSlice(ctx, r.client, wl.Namespace, workloadslicing.SliceName(wl))
+// shouldWait encapsulates the logic for deciding if we need to
+// wait for pods to be fully created and assigned before declaring a node failure.
+func shouldWait(podsAssigned, expectedOnNode int32, hasPodsToRetain bool, untoleratedCount int) bool {
+	if untoleratedCount == 0 {
+		return podsAssigned < expectedOnNode || hasPodsToRetain
+	}
+
+	if hasPodsToRetain && features.Enabled(features.TASReplaceNodeOnPodTermination) {
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]:
```suggestion
	if hasRunningPods && features.Enabled(features.TASReplaceNodeOnPodTermination) {
```

File: pkg/controller/tas/node_controller.go [hunk 30]
```diff
@@ -553,3 +724,54 @@ func classifyNoExecuteTaints(ctx context.Context, taints []corev1.Taint, podSets
...
+	}
+	if !utiltas.IsTAS(pod) {
+		// skip non-TAS pods
+		return
+	}
+
+	if pod.Status.Phase != corev1.PodPending {
+		// Only trigger the logic for situations when a pod is "late" and "pending"
+		return
+	}
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I think this check is unnecessary because below we check `spec.nodeName == ""` which entails the pod is pending

File: pkg/controller/tas/node_controller.go [hunk 31]
```diff
@@ -553,3 +724,54 @@ func classifyNoExecuteTaints(ctx context.Context, taints []corev1.Taint, podSets
...
+
+	nodeName := pod.Spec.NodeName
+	if nodeName == "" && pod.Spec.NodeSelector != nil {
+		nodeName = pod.Spec.NodeSelector[corev1.LabelHostname]
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: this shadows the nodeName var, maybe it would be better for readability to keep it separete, maybe :


```golang

	if len(pod.Spec.NodeName) && pod.Spec.NodeSelector != nil && len(pod.Spec.NodeSelector[corev1.LabelHostname]) > 0 {
		req := reconcile.Request{
			NamespacedName: types.NamespacedName{
				Name: pod.Spec.NodeSelector[corev1.LabelHostname],
			},
		}
		q.Add(req)
	}
```
or something along the lines

File: test/e2e/tas/hotswap_test.go [hunk 32]
```diff
@@ -498,6 +472,156 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+						wlName = wls.Items[0].Name
+						topologyAssignment = wls.Items[0].Status.Admission.PodSetAssignments[0].TopologyAssignment
+					}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+				})
+
+				wlKey := client.ObjectKey{Name: wlName, Namespace: ns.Name}
+				var initialNodes []string
+				for domain := range tas.InternalSeqFrom(topologyAssignment) {
+					initialNodes = append(initialNodes, domain.Values...)
+				}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: nit you can use slices.Collect to collect the sequence

File: test/e2e/tas/hotswap_test.go [hunk 33]
```diff
@@ -498,6 +472,156 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+						for _, p := range pods.Items {
+							g.Expect(p.Spec.SchedulingGates).To(gomega.ContainElement(corev1.PodSchedulingGate{Name: artificialGate}))
+						}
+					}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+				})
+
+				initialUIDs := sets.New[string]()
+				for _, p := range pods.Items {
+					initialUIDs.Insert(string(p.UID))
+				}
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: probably no need to cast to string, we can use typed UUID, and just collect to set, iirc sets.New(slices...)

File: test/e2e/tas/hotswap_test.go [hunk 34]
```diff
@@ -498,6 +472,156 @@ var _ = ginkgo.Describe("Hotswap for Topology Aware Scheduling", ginkgo.Ordered,
...
+							g.Expect(utilpod.HasGate(updatedPod, artificialGate)).To(gomega.BeFalse(), "Still found artificial gate, retrying...")
+						}
+					}, util.Timeout, util.Interval).Should(gomega.Succeed())
+				})
+
+				ginkgo.By("Check that the topology assignment is updated with the new node in the same block", func() {
+					expectedNodes := slices.DeleteFunc([]string{"kind-worker", "kind-worker2", "kind-worker3", "kind-worker4"}, func(n string) bool {
+						return n == node.Name
+					})
+					gomega.Expect(expectedNodes).To(gomega.HaveLen(3))
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: use initialNodes as the basis. Remove node.Name from the set and add `kind-worker4` to avoid repeating all node names.

Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: use initialNodes as the basis. Remove node.Name from the set and add `kind-worker4` to avoid repeating all node names.

File: test/e2e/tas/hotswap_test.go [hunk 35]
```diff
@@ -563,5 +687,22 @@ func expectPodsOnNodes(ctx context.Context, k8sClient client.Client, nsName stri
...
+func findByPodIndex(ctx context.Context, k8sClient client.Client, g gomega.Gomega, nsName, jobName, index string, initialUIDs sets.Set[string], wantInitialUID bool) *corev1.Pod {
+	pods := &corev1.PodList{}
+	g.Expect(k8sClient.List(ctx, pods, client.InNamespace(nsName), client.MatchingLabels{
+		"job-name": jobName,
+	})).To(gomega.Succeed())
+
+	for i := range pods.Items {
+		p := &pods.Items[i]
+		if p.Labels["batch.kubernetes.io/job-completion-index"] == index {
+			if initialUIDs.Has(string(p.UID)) == wantInitialUID {
```
Comment (mimowo) [inline test/e2e/tas/hotswap_test.go]: I think we don't need `wantInitialUID`  - it should be enough to check the index, and if belongs to the "initial" set.

File: test/util/util.go [hunk 36]
```diff
@@ -714,6 +710,27 @@ func BindPodWithNode(ctx context.Context, k8sClient client.Client, nodeName stri
 	}
 }
 
+func ExpectPodTerminatedByKueueCondition(ctx context.Context, k8sClient client.Client, podKey client.ObjectKey, reason string) {
+	ginkgo.GinkgoHelper()
+	gomega.EventuallyWithOffset(1, func(g gomega.Gomega) {
```
Comment (mimowo) [inline test/util/util.go]:
```suggestion
	gomega.Eventually( func(g gomega.Gomega) {
```
when using helper, then iirc it resets the offset counting

File: pkg/controller/tas/node_controller.go [hunk 37]
```diff
@@ -500,6 +617,60 @@ func (r *nodeReconciler) addUnhealthyNode(ctx context.Context, wl *kueue.Workloa
...
+	if found && psa.TopologyAssignment != nil {
+		return psa.TopologyAssignment.Levels
+	}
+
+	return nil
+}
+
+// getPodsAssignedToNode returns a list of pods that are assigned to the node (via spec.nodeName)
+// or are assigned by topology assignment but are not scheduled to the node (e.g. because of a taint).
+func (r *nodeReconciler) getPodsAssignedToNode(ctx context.Context, wl *kueue.Workload, nodeName string) ([]*corev1.Pod, error) {
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I would prefer to avoid mixing running pods and pending pods as results of the same function, because they are handled differently. 

To detemine the list of "RUnning" pods we can use the already indexed spec.nodeName field at the controller runtime. iiuc we don't need full list of such pods, just information if there is at least one running, so that shouldWait answers true.

To determine the list of Pending pods assigned to the node by topology assignement we could use our index, ie. indexPodNodeSelectorHostname

File: pkg/controller/tas/node_controller.go [hunk 38]
```diff
@@ -553,3 +724,54 @@ func classifyNoExecuteTaints(ctx context.Context, taints []corev1.Taint, podSets
...
+		nodeName = pod.Spec.NodeSelector[corev1.LabelHostname]
+	}
+
+	if nodeName != "" {
+		req := reconcile.Request{
+			NamespacedName: types.NamespacedName{
+				Name: nodeName,
+			},
+		}
+		q.Add(req)
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: nit, would probably add some batch period here to avoid too many node reconciles in case multiple pods are ungated and are targeting the same node

File: pkg/controller/jobs/pod/pod_controller.go [hunk 39]
```diff
@@ -541,6 +541,12 @@ func SetupIndexes(ctx context.Context, indexer client.FieldIndexer) error {
 	if err := jobframework.SetupWorkloadOwnerIndex(ctx, indexer, gvk); err != nil {
 		return err
 	}
+	if err := indexer.IndexField(ctx, &corev1.Pod{}, "spec.nodeName", func(o client.Object) []string {
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_controller.go]: Move the indexer to a constant along with other index keys, PodNodeNameKey feels reasonable.
Actually this indexer should be registered along with core indexers. The Pod controller might be disabled on environments where the "Pod" integration is disabled.

File: pkg/controller/tas/node_controller_test.go [hunk 40]
```diff
@@ -113,17 +113,21 @@ func TestNodeFailureReconciler(t *testing.T) {
 
 	basePod := testingpod.MakePod("test-pod", nsName).
 		Annotation(kueue.WorkloadAnnotation, wlName).
+		Annotation(kueue.PodSetPreferredTopologyAnnotation, "true").
```
Comment (mimowo) [inline pkg/controller/tas/node_controller_test.go]: Use unconstrained to make it more realistic. The value for "preferred"  would be a level name,

File: pkg/controller/tas/node_controller_test.go [hunk 41]
```diff
@@ -738,6 +703,12 @@ func TestNodeFailureReconciler(t *testing.T) {
 			if err := utiltesting.AsIndexer(clientBuilder).IndexField(ctx, &corev1.Pod{}, coreindexer.WorkloadSliceNameKey, coreindexer.IndexPodWorkloadSliceName); err != nil {
 				t.Fatalf("Could not setup WorkloadSliceNameKey index: %v", err)
 			}
+			if err := utiltesting.AsIndexer(clientBuilder).IndexField(ctx, &corev1.Pod{}, "spec.nodeName", func(o client.Object) []string {
+				pod := o.(*corev1.Pod)
+				return []string{pod.Spec.NodeName}
+			}); err != nil {
+				t.Fatalf("Could not setup spec.nodeName index: %v", err)
```
Comment (mimowo) [inline pkg/controller/tas/node_controller_test.go]: Use the named indexer as proposed in anoher comment

File: test/integration/singlecluster/tas/suite_test.go [hunk 42]
```diff
@@ -115,6 +115,12 @@ func managerSetup(resourceTransformations ...config.ResourceTransformation) func
 		err = tasindexer.SetupIndexes(ctx, mgr.GetFieldIndexer())
 		gomega.Expect(err).NotTo(gomega.HaveOccurred())
 
+		err = mgr.GetFieldIndexer().IndexField(ctx, &corev1.Pod{}, "spec.nodeName", func(o client.Object) []string {
+			pod := o.(*corev1.Pod)
+			return []string{pod.Spec.NodeName}
+		})
```
Comment (mimowo) [inline test/integration/singlecluster/tas/suite_test.go]: reuse named indexer as proposed in another comment

File: pkg/controller/tas/node_controller.go [hunk 43]
```diff
@@ -500,6 +599,54 @@ func (r *nodeReconciler) addUnhealthyNode(ctx context.Context, wl *kueue.Workloa
...
 }
 
+// getPodsToTerminate returns a list of pending pods that are assigned to the node
+// (either scheduled or just assigned via topology), and a boolean indicating
+// if there is at least one pod to retain (e.g. running pod).
+func (r *nodeReconciler) getPodsToTerminate(ctx context.Context, wl *kueue.Workload, nodeName string) ([]*corev1.Pod, bool, error) {
+	sliceName := workloadslicing.SliceName(wl)
+
+	scheduledPods, err := ListPodsForWorkloadSlice(ctx, r.client, wl.Namespace, sliceName, client.MatchingFields{
+		"spec.nodeName": nodeName,
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: Use the const key for the indexer

File: pkg/controller/tas/node_controller.go [hunk 44]
```diff
@@ -500,6 +599,54 @@ func (r *nodeReconciler) addUnhealthyNode(ctx context.Context, wl *kueue.Workloa
...
+	})
+	if err != nil {
+		return nil, false, fmt.Errorf("list topology assigned pods: %w", err)
+	}
+	var hasRunningPods bool
+	for _, pod := range scheduledPods {
+		if !pod.DeletionTimestamp.IsZero() || utilpod.IsTerminated(pod) {
+			continue
+		}
+		if pod.Status.Phase == corev1.PodRunning {
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: Actually, we don't need this extra check. From the scheduling perspective it does not matter if the Pod is "Running" phase or not. What matters is if "scheduled", because it might be for example yet pulling large AI image. It is already "progressing". We could rename "hasRunningPods" to "hasProgressingPods'.

Comment (mimowo) [reply pkg/controller/tas/node_controller.go]: Please also extract listprogressingPods to a helper, together with calling ListPodsForWorkloadSlice

File: pkg/controller/tas/node_controller.go [hunk 45]
```diff
@@ -500,6 +599,54 @@ func (r *nodeReconciler) addUnhealthyNode(ctx context.Context, wl *kueue.Workloa
...
+	}
+
+	var podsToTerminate []*corev1.Pod
+	for _, pod := range scheduledPods {
+		if !pod.DeletionTimestamp.IsZero() || utilpod.IsTerminated(pod) {
+			continue
+		}
+		if pod.Status.Phase == corev1.PodPending && !utilpod.HasGate(pod, kueue.TopologySchedulingGate) {
+			podsToTerminate = append(podsToTerminate, pod)
+		}
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: Yeah, we cannot terminate those - see the comment above. These pods might be already doing useful work, just pulling the image

File: pkg/controller/tas/node_controller.go [hunk 46]
```diff
@@ -281,63 +319,80 @@ func hasTASAssignmentOnNode(wl *kueue.Workload, nodeName string) bool {
...
+func shouldWait(hasRunningPods bool, untoleratedCount int) bool {
+	if untoleratedCount == 0 {
+		return hasRunningPods
+	}
+
+	if hasRunningPods && features.Enabled(features.TASReplaceNodeOnPodTermination) {
+		return true
+	}
+
+	return false
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: `return hasRunningPods && features.Enabled(features.TASReplaceNodeOnPodTermination)`

nit

File: pkg/controller/core/indexer/indexer.go [hunk 47]
```diff
@@ -247,6 +258,9 @@ func Setup(ctx context.Context, indexer client.FieldIndexer) error {
 		if err := indexer.IndexField(ctx, &corev1.Pod{}, WorkloadSliceNameKey, IndexPodWorkloadSliceName); err != nil {
 			return fmt.Errorf("setting index on workloadSliceName for Pod: %w", err)
 		}
+		if err := indexer.IndexField(ctx, &corev1.Pod{}, PodNodeNameKey, IndexPodNodeName); err != nil {
+			return fmt.Errorf("setting index on %s for Pod: %w", PodNodeNameKey, err)
+		}
```
Comment (mimowo) [inline pkg/controller/core/indexer/indexer.go]: register the indexer oly when TAS is enabled

Comment (mimowo) [reply pkg/controller/core/indexer/indexer.go]: or move next to the other TAS indexer, we can move here when there are other users of it

File: pkg/util/tas/tas_assignment.go [hunk 48]
```diff
@@ -312,3 +312,40 @@ func ComputeUsagePerDomain(ta *TopologyAssignment, singlePodRequests resources.R
...
+			continue
+		}
+		for domain := range InternalSeqFrom(psa.TopologyAssignment) {
+			if len(domain.Values) > 0 && domain.Values[len(domain.Values)-1] == nodeName {
+				return true
+			}
+		}
+	}
+	return false
+}
```
Comment (mimowo) [inline pkg/util/tas/tas_assignment.go:328]: Implement trivially by calling ExpectedPodsOnNode and checking is len()>-0

File: pkg/util/tas/tas_assignment.go [hunk 49]
```diff
@@ -312,3 +312,40 @@ func ComputeUsagePerDomain(ta *TopologyAssignment, singlePodRequests resources.R
...
+			continue
+		}
+		for domain := range InternalSeqFrom(psa.TopologyAssignment) {
+			if len(domain.Values) > 0 && domain.Values[len(domain.Values)-1] == nodeName {
+				expected += domain.Count
+			}
+		}
+	}
+	return expected
+}
```
Comment (mimowo) [inline pkg/util/tas/tas_assignment.go]: add unit tests

File: pkg/controller/tas/node_controller.go [hunk 50]
```diff
@@ -553,3 +674,44 @@ func classifyNoExecuteTaints(ctx context.Context, taints []corev1.Taint, podSets
...
+func (h *nodeFailurePodHandler) Generic(_ context.Context, _ event.GenericEvent, _ workqueue.TypedRateLimitingInterface[reconcile.Request]) {
+}
+
+func (h *nodeFailurePodHandler) queueReconcileForPod(object client.Object, q workqueue.TypedRateLimitingInterface[reconcile.Request]) {
+	pod, isPod := object.(*corev1.Pod)
+	if !isPod {
+		return
+	}
+	if !utiltas.IsTAS(pod) {
+		// skip non-TAS pods
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: nit, but this is self explanatory. I think comments are useful if they bring some readabilty, here the comment just eats one line

File: pkg/controller/tas/indexer/indexer.go [hunk 51]
```diff
@@ -54,6 +55,19 @@ func indexPodWorkload(o client.Object) []string {
 	return []string{value}
 }
 
+func indexPodNodeSelectorHostname(o client.Object) []string {
+	pod, ok := o.(*corev1.Pod)
+	if !ok || !utiltas.IsTAS(pod) {
+		return nil
+	}
+	if pod.Spec.NodeSelector != nil && pod.Spec.NodeName == "" {
```
Comment (olekzabl) [inline pkg/controller/tas/indexer/indexer.go]: I'm concerned about the `&& pod.Spec.NodeName == ""` part.

I understand it makes the indexing a bit lighter (assuming we currently need the index only for pods satisfying this condition).
OTOH, this creates a readability issue (a potential surprise): in the future, someone else might want to search for Pods by `spec.nodeSelector`, and expect _all_ matching results there.

WDYT? Are there precedents in the code for such "non-trivial indexes"?

File: pkg/util/tas/tas_assignment.go [hunk 52]
```diff
@@ -312,3 +312,40 @@ func ComputeUsagePerDomain(ta *TopologyAssignment, singlePodRequests resources.R
 	}
 	return usage
 }
+
+func ExpectedPodsOnNode(psa []kueue.PodSetAssignment, nodeName string) int32 {
```
Comment (olekzabl) [inline pkg/util/tas/tas_assignment.go]: I wonder if this function is really needed?
AFAICS the only thing you ever do with its result is checking whether it `== 0` or not.
But this question is already answered by `HasTASAssignmentOnNode` just below.
(Which is more efficient - as it doesn't count until the end).

So it seems you could migrate to using that fn and remove this one?

File: pkg/util/tas/tas_assignment.go [hunk 53]
```diff
@@ -312,3 +312,40 @@ func ComputeUsagePerDomain(ta *TopologyAssignment, singlePodRequests resources.R
...
+				expected += domain.Count
+			}
+		}
+	}
+	return expected
+}
+
+func HasTASAssignmentOnNode(psa []kueue.PodSetAssignment, nodeName string) bool {
+	for i := range psa {
+		psa := psa[i]
```
Comment (olekzabl) [inline pkg/util/tas/tas_assignment.go]: Nit: you can naturally save a line

```suggestion
func HasTASAssignmentOnNode(psas []kueue.PodSetAssignment, nodeName string) bool {
	for _, psa := range psas {
```

File: pkg/controller/tas/node_controller.go [hunk 54]
```diff
@@ -500,6 +573,54 @@ func (r *nodeReconciler) addUnhealthyNode(ctx context.Context, wl *kueue.Workloa
...
+func (r *nodeReconciler) hasProgressingPods(ctx context.Context, wl *kueue.Workload, nodeName string) (bool, error) {
+	sliceName := workloadslicing.SliceName(wl)
+	pods, err := ListPodsForWorkloadSlice(ctx, r.client, wl.Namespace, sliceName, client.MatchingFields{
+		coreindexer.PodNodeNameKey: nodeName,
+	})
+	if err != nil {
+		return false, err
+	}
+	for i := range pods {
+		pod := pods[i]
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]:
```suggestion
	for _, pod := range pods {
```

File: pkg/controller/tas/node_controller.go [hunk 55]
```diff
@@ -253,91 +276,97 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
+			tasWorkloadsOnNode.Insert(wlKey)
 			continue
 		}
-		if !utiltas.IsLowestLevelHostname(topologyAssignment.Levels) {
-			continue
+
+		// Also find workloads from any pods that are assigned to this node by TopologyAssignment
+		// but not yet bound. These might be stale "late" pods for a workload that has already
+		// been reassigned to another node.
+		pods, err := r.listTopologyAssignedPods(ctx, &wl, nodeName)
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]: I feel this function name is misleading.
The code now looks essentially like this:

> Check `HasTASAssignmentOnNode`. But this may miss some cases.
> So to catch those, check `listTopologyAssignedPods`.

But "topology assigned" sounds very similar to "TAS assignment".
While what we really use to "catch missed cases" is Pod's _node selector_.

So maybe rather `listNodeSelectorAssignedPods`?

File: pkg/controller/tas/node_controller.go [hunk 56]
```diff
@@ -253,91 +276,97 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
+		if err != nil {
+			return nil, fmt.Errorf("failed to list pods bound to node for workload %s: %w", wlKey.String(), err)
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]: What do you mean by "bound"?
The comment above speaks about looking for Pods "_not_ yet _bound_".
OTOH this log speaks about "listing _bound_ pods".
I'm confused.

File: pkg/controller/tas/node_controller.go [hunk 57]
```diff
@@ -500,6 +573,54 @@ func (r *nodeReconciler) addUnhealthyNode(ctx context.Context, wl *kueue.Workloa
...
+		return false, err
+	}
+	for i := range pods {
+		pod := pods[i]
+		if !pod.DeletionTimestamp.IsZero() || utilpod.IsTerminated(pod) {
+			continue
+		}
+		return true, nil
+	}
+	return false, nil
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]: (Optional - for me it's more readable this way)

```suggestion
    hasProgressingPods := slices.ContainsFunc(pods, func (pod *corev1.Pod) bool {
      return pod.DeletionTimestamp.IsZero() && !utilpod.IsTerminated(pod)
    })
    return hasProgressingPods, nil
```

File: pkg/controller/tas/node_controller.go (hunk 55 above)
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]: This does API `List` under the hood. Is the result cached by the client library?

Asking because, IIUC, when the fetched list is not empty (and when `HasTASAssignmentOnNode` returns false), this list will be dropped in this method but then retrieved _again_ in `getPodsToTerminate`.

So I'm wondering if we're certain that cache will prevent re-fetching on the API level?
(And if not, should we try to pass the results from here to there?)

File: pkg/controller/tas/node_controller.go [hunk 58]
```diff
@@ -253,91 +276,97 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
+	case !ready:
+		if !features.Enabled(features.TASReplaceNodeOnPodTermination) {
+			return workloadHealthCheck{status: workloadUnhealthy}, nil
 		}
-	} else if !ready && features.Enabled(features.TASReplaceNodeOnPodTermination) {
 		// NotReady node
-		shouldWait = true
-	}
+		return r.checkPodsOnNode(ctx, nodeName, wl, nil, expectedOnNode)
+	case ready && !features.Enabled(features.TASReplaceNodeOnNodeTaints):
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]: Nit: this part can be removed (due to the previous `case`).

```suggestion
	case !features.Enabled(features.TASReplaceNodeOnNodeTaints):
```

File: pkg/controller/tas/node_controller.go [hunk 59]
```diff
@@ -253,91 +276,97 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
-func (r *nodeReconciler) listPodsForWorkload(ctx context.Context, wl *kueue.Workload) ([]*corev1.Pod, error) {
-	return ListPodsForWorkloadSlice(ctx, r.client, wl.Namespace, workloadslicing.SliceName(wl))
+// shouldWait encapsulates the logic for deciding if we need to
+// wait for pods to be fully created and assigned before declaring a node failure.
+func shouldWait(hasProgressingPods bool, untoleratedCount int) bool {
+	if untoleratedCount == 0 {
+		return hasProgressingPods
+	}
+
+	return hasProgressingPods && features.Enabled(features.TASReplaceNodeOnPodTermination)
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]: Optional: for me it feels easier to read

```suggestion
	return hasProgressingPods && (untoleratedCount == 0 || features.Enabled(features.TASReplaceNodeOnPodTermination))
```

File: pkg/controller/tas/node_controller.go [hunk 60]
```diff
@@ -73,9 +84,9 @@ const (
 	// and is ready for eviction (e.g. all of its pods on the node have fully terminated).
 	workloadUnhealthy
 
-	// workloadTemporarilyHealthy indicates that the workload will need to be evicted from the node,
+	// workloadHealthUnknown indicates that the workload will need to be evicted from the node,
 	// but is not ready yet (e.g. pods are still terminating, or taints are only temporarily tolerated).
-	workloadTemporarilyHealthy
+	workloadHealthUnknown
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go:87]: This name does not feel to fit the description.
Basically, "we know we should evict but not now" != "we don't know".

OTOH, I see in the code below that you started to use this case for various `err != nil` cases, so I guess that's why the rename.

I'd propose to consider how "stable" it is in your logic that the error cases fall into the "evict later" bucket. And then:
- If it's stable -> rename this to `workloadToBeEvictedLater` or so.
- If it's unstable (i.e. might change) -> have both `workloadHealthUnknown` and `workloadToBeEvictedLater` here. 
  They'll be handled same way for now but it's an implementation detail.

WDYT?

File: pkg/controller/tas/node_controller.go [hunk 61]
```diff
@@ -253,91 +276,97 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
 			}
+			return r.checkPodsOnNode(ctx, nodeName, wl, untolerated, expectedOnNode)
 		}
-		if allPodsTerminated {
-			return workloadUnhealthy, nil
+		if len(temporarilyTolerated) > 0 {
+			return r.checkPodsOnNode(ctx, nodeName, wl, untolerated, expectedOnNode)
 		}
-		return workloadTemporarilyHealthy, nil
+		return workloadHealthCheck{status: workloadHealthy}, nil
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go:374]: Here in some cases we check for "pods to terminate" and in some cases we don't. Why so?

File: pkg/controller/tas/node_controller.go [hunk 62]
```diff
@@ -253,91 +276,97 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
+		if len(untolerated) > 0 {
+			if !features.Enabled(features.TASReplaceNodeOnPodTermination) {
+				return workloadHealthCheck{status: workloadUnhealthy}, nil
 			}
+			return r.checkPodsOnNode(ctx, nodeName, wl, untolerated, expectedOnNode)
 		}
-		if allPodsTerminated {
-			return workloadUnhealthy, nil
+		if len(temporarilyTolerated) > 0 {
+			return r.checkPodsOnNode(ctx, nodeName, wl, untolerated, expectedOnNode)
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]: In the old code, this flipped `shouldWait` to true, i.e. shifted from "healthy" to "evict later".
In the new code, it doesn't (because you pass `untolerated` to the function, which is empty).
Why so?

File: pkg/controller/tas/node_controller.go [hunk 63]
```diff
@@ -253,91 +276,97 @@ func (r *nodeReconciler) getWorkloadsOnNode(ctx context.Context, nodeName string
...
 		}
-		return workloadTemporarilyHealthy, nil
+		return workloadHealthCheck{status: workloadHealthy}, nil
+	}
+}
+
+func (r *nodeReconciler) checkPodsOnNode(ctx context.Context, nodeName string, wl *kueue.Workload, untolerated []corev1.Taint, expectedOnNode int32) (workloadHealthCheck, error) {
```
Comment (olekzabl) [inline pkg/controller/tas/node_controller.go]: `untolerated` is almost unused. You only look at the count, and specifically whether it's 0.

How about e.g. `hasUntolerated bool` instead?

File: pkg/controller/tas/node_controller.go (hunk 29 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/controller/tas/node_controller.go (hunk 30 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: yes, that wasn't necessary - removed

File: pkg/controller/tas/node_controller.go (hunk 31 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: refactored

File: test/e2e/tas/hotswap_test.go (hunk 33 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/e2e/tas/hotswap_test.go (hunk 34 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: done

File: test/util/util.go (hunk 36 above)
Comment (j-skiba) [reply test/util/util.go]: done

File: pkg/controller/tas/node_controller.go (hunk 37 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: I refactored this into 
```go
// getPodsToTerminate returns a list of pending pods that are assigned to the node by topology (but not yet scheduled),
// and a boolean indicating if there is at least one pod to retain (e.g. any scheduled pod).
func (r *nodeReconciler) getPodsToTerminate(ctx context.Context, wl *kueue.Workload, nodeName string) ([]*corev1.Pod, bool, error)
```
and now they are using the both indexers to list the pods

File: pkg/controller/tas/node_controller.go (hunk 38 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: added 100ms batch period

File: pkg/controller/jobs/pod/pod_controller.go (hunk 39 above)
Comment (j-skiba) [reply pkg/controller/jobs/pod/pod_controller.go]: done

File: pkg/controller/tas/node_controller_test.go (hunk 40 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller_test.go]: done

File: pkg/controller/tas/node_controller_test.go (hunk 41 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller_test.go]: done

File: test/integration/singlecluster/tas/suite_test.go (hunk 42 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/suite_test.go]: done

File: pkg/controller/tas/node_controller.go (hunk 43 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/controller/tas/node_controller.go (hunk 44 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/controller/tas/node_controller.go (hunk 50 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/util/tas/tas_assignment.go (hunk 49 above)
Comment (j-skiba) [reply pkg/util/tas/tas_assignment.go]: done

File: pkg/util/tas/tas_assignment.go (hunk 48 above)
Comment (j-skiba) [reply pkg/util/tas/tas_assignment.go:328]: done

File: pkg/controller/core/indexer/indexer.go (hunk 47 above)
Comment (j-skiba) [reply pkg/controller/core/indexer/indexer.go]: moved to tas indexers

File: test/e2e/tas/hotswap_test.go (hunk 35 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: that was for finding if the replacement pod is really a replacement pod. The initial pod and the replacement one have the same job index.

Nevertheless I agree that was unnecessary and I replaced that part so now replacement pod identification is based on `spec.nodeName` - it's easier this way

File: pkg/util/tas/tas_assignment.go (hunk 52 above)
Comment (j-skiba) [reply pkg/util/tas/tas_assignment.go]: yes, we can use just one function - refactored

File: pkg/controller/tas/node_controller.go (hunk 55 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: renamed to listNodeSelectorAssignedPods

File: pkg/controller/tas/node_controller.go (hunk 57 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: I agree, it looks better - done

File: pkg/controller/tas/node_controller.go (hunk 56 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: that was left after refactoring. I removed that

File: pkg/controller/tas/node_controller.go (hunk 63 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: looks good - done

File: pkg/controller/tas/node_controller.go (hunk 55 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: these calls use indexer so the result is cached.

We could list all pods for the node once at the beginning of the reconcile loop, group them by workload, pass the data down through the reconciliation flow.

I will try doing this

File: pkg/controller/tas/node_controller.go (hunk 62 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: I think it's fine. The old `shouldWait` is the new `checkPodsOnNode` and they do almost the same things.

Previously some of the cases for untolerated/tempTolerated were handled before `shouldWait` - https://github.com/kubernetes-sigs/kueue/blob/baf8a94160fe65077c17a1387c57055c6309ac01/pkg/controller/tas/node_controller.go#L299

File: pkg/controller/tas/indexer/indexer.go (hunk 51 above)
Comment (j-skiba) [reply pkg/controller/tas/indexer/indexer.go]: I don't see any 'non-trivial' indexes, there are some with filtering but the filters they apply are more 'expected' like here https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/core/indexer/indexer.go. I think it might be better keep the indexer more generic and keep the node replacement related logic in `node_controller.go`.

I removed the `&& pod.Spec.NodeName == ""` check and moved it to `node_controller.go`.

File: pkg/controller/tas/node_controller.go (hunk 45 above)
Comment (mimowo) [reply pkg/controller/tas/node_controller.go]: The comment is outdated by now, please resolve

File: pkg/controller/tas/node_controller.go (hunk 11 above)
Comment (mimowo) [reply pkg/controller/tas/node_controller.go]: The comment is outdated by now, please resolve

File: pkg/controller/tas/node_failure_controller.go (hunk 12 above)
Comment (mimowo) [reply pkg/controller/tas/node_failure_controller.go]: The comment is outdated by now, please resolve

File: pkg/controller/tas/node_failure_controller.go (hunk 13 above)
Comment (mimowo) [reply pkg/controller/tas/node_failure_controller.go]: The comment is outdated by now, please resolve

File: pkg/controller/tas/node_controller.go (hunk 23 above)
Comment (mimowo) [reply pkg/controller/tas/node_controller.go]: The comment is outdated by now, please resolve

File: pkg/controller/tas/node_controller.go (hunk 60 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go:87]: Sounds good to me

I used `workloadToBeObserved` instead of `workloadToBeEvictedLater`. Eviction of a workload happens only when there are > 1 unhealthy nodes and I think it describes the situation better

File: test/e2e/tas/hotswap_test.go (hunk 32 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: outdated

File: pkg/controller/tas/node_controller.go (hunk 28 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: we no longer wait for all pods to land on node

File: pkg/controller/tas/node_controller.go (hunk 61 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go:374]: I think the code has changed  or I'm not following here, could you explain?

File: pkg/controller/tas/node_controller.go (hunk 55 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done, could you take a look if this is fine?

File: test/e2e/tas/hotswap_test.go (hunk 5 above)
Comment (j-skiba) [reply test/e2e/tas/hotswap_test.go]: outdated

File: test/util/util.go [hunk 64]
```diff
@@ -716,6 +710,27 @@ func BindPodWithNode(ctx context.Context, k8sClient client.Client, nodeName stri
...
```
Comment (mimowo) [inline test/util/util.go]: nit, `Eventually(`

Comment (j-skiba) [reply test/util/util.go]: done

File: pkg/controller/tas/node_controller.go (hunk 62 above)
Comment (olekzabl) [reply pkg/controller/tas/node_controller.go]: OK I think I got it, thanks.

File: pkg/controller/tas/node_controller.go (hunk 61 above)
Comment (olekzabl) [reply pkg/controller/tas/node_controller.go:374]: Indeed the code has changed.
So let's look at the current version, [this switch](https://github.com/j-skiba/kueue/blob/298f1f62edc8f2ac39e2f83e70ff6995175d9b8f/pkg/controller/tas/node_controller.go#L352-L378).
Sometimes we call `checkPodsOnNode`, sometimes we don't. 
When we don't, the resulting `workloadHealthCheck` will have `podsToTerminate` unset (= empty).
This happens in 3 cases:
- when the FG `TASReplaceNodeOnPodTermination` is disabled
- [here](https://github.com/j-skiba/kueue/blob/298f1f62edc8f2ac39e2f83e70ff6995175d9b8f/pkg/controller/tas/node_controller.go#L364)
- [here](https://github.com/j-skiba/kueue/blob/298f1f62edc8f2ac39e2f83e70ff6995175d9b8f/pkg/controller/tas/node_controller.go#L377)

I'm trying to understand if all these 3 cases are intended?

File: pkg/controller/tas/node_controller.go (hunk 55 above)
Comment (olekzabl) [reply pkg/controller/tas/node_controller.go]: Looks good, thank you!

File: pkg/controller/tas/node_controller.go (hunk 61 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go:374]: Yes, that's all intended.
1. When the fg is disabled we don't wait for the pods do we don't call `checkPodsOnNode`
2. This is a path when nothing happens when a node is reconciled when a taint appears but the `TASReplaceNodeOnNodeTaints` feature is disabled. Basically it a behavior that would be observed before the feature was implemented
3. This is reached when a node becomes healthy - a taint is removed or becomes ready

File: pkg/controller/tas/node_controller.go [hunk 65]
```diff
@@ -125,33 +146,53 @@ func (r *nodeReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.
...
-	affectedWorkloads, err := r.getWorkloadsOnNode(ctx, req.Name)
+	var readyCondition *corev1.NodeCondition
+	if nodeExists {
+		readyCondition = utiltas.GetNodeCondition(&node, corev1.NodeReady)
+	}
+
+	var timerExpired bool
+	if readyCondition != nil && readyCondition.Status != corev1.ConditionTrue {
+		timeSinceNotReady := r.clock.Now().Sub(readyCondition.LastTransitionTime.Time)
+		if timeSinceNotReady >= NodeFailureDelay {
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: nit, the common pattern is to compute `remainingTime := `, check if > 0, and if so then pass to `RequeueAfter`

File: test/integration/singlecluster/tas/tas_test.go [hunk 66]
```diff
@@ -1284,12 +1327,22 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
 					))
 				})
 
+				createPodsForWorkload(wl1, ns.Name, false, true)
```
Comment (mimowo) [inline test/integration/singlecluster/tas/tas_test.go]: Hold on, are the changes to pre-existing tests required? If no I would rather have a dedicated test Describe / When. The changes to pre-existing tests make it really hard to assess what is changed.

File: test/integration/singlecluster/tas/tas_test.go [hunk 67]
```diff
@@ -1388,14 +1451,16 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+
 				ginkgo.By("making the node NotReady 30s in the past", func() {
 					nodeToUpdate := &corev1.Node{}
 					gomega.Expect(k8sClient.Get(ctx, apitypes.NamespacedName{Name: nodeName}, nodeToUpdate)).Should(gomega.Succeed())
 
 					util.SetNodeCondition(ctx, k8sClient, nodeToUpdate, &corev1.NodeCondition{
 						Type:               corev1.NodeReady,
 						Status:             corev1.ConditionFalse,
-						LastTransitionTime: metav1.NewTime(time.Now().Add(-tas.NodeFailureDelay)),
+						LastTransitionTime: metav1.NewTime(time.Now().Add(-tas.NodeFailureDelay - time.Minute)),
```
Comment (mimowo) [inline test/integration/singlecluster/tas/tas_test.go]: Is this change necessary? Again, I would prefer to separate the tests.

**Review by mimowo — COMMENTED** [review]
LGTM overall, but I don't feel confident about changing pre-existing tests, it is unclear to me if the changes are necessary or drive-by.

File: test/integration/singlecluster/tas/tas_test.go [hunk 68]
```diff
@@ -1997,8 +2074,8 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
 					}, util.ConsistentDuration, util.ShortInterval).Should(gomega.Succeed())
 				})
 
-				ginkgo.By("deleting the pod", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/tas/tas_test.go:2022]: wyy is the test changed. Does it still capture the same intention?

File: test/integration/singlecluster/tas/tas_test.go (hunk 66 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: I think it makes sense to add pods to these tests especially that this PR includes some logic related to nodeSelector, nodeName, pod phase checks. I would say that it would be better to have these tests with `createPodsForWorkload` calls and without them to check if the controller works properly with and without pods - the result should be the same but the logic in controller is rather complicated.

File: test/integration/singlecluster/tas/tas_test.go (hunk 67 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: that wasn't necessary - removed

File: test/integration/singlecluster/tas/tas_test.go (hunk 68 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:2022]: I think it reflects problem with nodes and pods more accurately. When a node has problems then pod is more likely to be moved to failed state than deleted instantly.

File: test/integration/singlecluster/tas/tas_test.go (hunk 66 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: I rearranged the tests in this commit https://github.com/kubernetes-sigs/kueue/pull/9615/commits/23c2cfea11f2b27460e3596e34150f2dc074b307. The change is big so the problem with reviewability is even bigger but on the other hand I think it would be good to have them. wdyt?

File: test/integration/singlecluster/tas/tas_test.go [hunk 69]
```diff
@@ -1286,117 +1329,382 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
 
-				ginkgo.By("creating a workload", func() {
-					wl1 = utiltestingapi.MakeWorkload("wl1", ns.Name).
-						PodSets(*utiltestingapi.MakePodSet("worker", 2).
-							PreferredTopologyRequest(utiltesting.DefaultBlockTopologyLevel).
-							Obj()).
-						Queue(kueue.LocalQueueName(localQueue.Name)).Request(corev1.ResourceCPU, "1").Obj()
-					util.MustCreate(ctx, k8sClient, wl1)
-				})
+			for _, withPods := range []bool{true, false} {
```
Comment (mimowo) [inline test/integration/singlecluster/tas/tas_test.go]: Can we not touch the existing tests? This makes it virtually non-reviewable.

I would really  prefer some focused integration tests on handling the stuck Pods, rather than just generic re-run of the same tests.

File: test/integration/singlecluster/tas/tas_test.go [hunk 70]
```diff
@@ -2210,13 +2351,21 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
 					nodeName = ta.Domains[0].Values[0]
 				})
 
+				createPodsForWorkload(wl1, ns.Name, false, true)
```
Comment (mimowo) [inline test/integration/singlecluster/tas/tas_test.go]: Can we also drop that change from pre-existing tests?

File: test/integration/singlecluster/tas/tas_test.go (hunk 69 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: done, reverted the additions the preexisting tests

File: test/integration/singlecluster/tas/tas_test.go (hunk 70 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: removed

File: test/integration/singlecluster/tas/tas_test.go (hunk 66 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: changes in tests reverted

File: test/integration/singlecluster/tas/tas_test.go (hunk 68 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:2022]: code removed

File: pkg/controller/tas/node_controller.go (hunk 65 above)
Comment (mimowo) [reply pkg/controller/tas/node_controller.go]:
```golang
remainingTime := NodeFailureDelay- timeSinceNotReady
timerExpired := remainingTime <= 0
if !timerExpired && !features.Enabled(features.TASReplaceNodeOnPodTermination) {
   return return ctrl.Result{RequeueAfter: remainingTime}, nil
}
```
nit, I think this is smenatically the same, but following the pattern to name the "remainingTime" as a variable.

File: pkg/controller/tas/node_controller.go [hunk 71]
```diff
@@ -125,33 +146,53 @@ func (r *nodeReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.
...
-	if isReady || features.Enabled(features.TASReplaceNodeOnPodTermination) {
-		return r.reconcileWorkloadsOnNode(ctx, req.Name, &node, affectedWorkloads)
+	if timerExpired {
+		log.V(3).Info("Node is not ready and NodeFailureDelay timer expired, marking as failed")
+		evictedWorkloads, err := r.handleUnhealthyNode(ctx, req.Name, affectedWorkloads)
+		if err != nil {
+			return ctrl.Result{}, err
+		}
+		// Only reconcile workloads that were not evicted.
+		affectedWorkloads = affectedWorkloads.Difference(evictedWorkloads)
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go:186]: just question: Is it just perf optimization, or needed for correctness?

File: pkg/controller/tas/node_controller.go [hunk 72]
```diff
@@ -245,99 +289,112 @@ func (r *nodeReconciler) SetupWithManager(mgr ctrl.Manager, cfg *config.Configur
...
+	return groupPodsByWorkload(podList.Items), nil
+}
+
+func groupPodsByWorkload(pods []corev1.Pod) map[types.NamespacedName][]*corev1.Pod {
+	nodeSelectorPodsByWorkload := make(map[types.NamespacedName][]*corev1.Pod)
+	for i := range pods {
+		pod := &pods[i]
+		wlName := coreindexer.IndexPodWorkloadSliceName(pod)
+		if len(wlName) > 0 {
+			key := types.NamespacedName{Name: wlName[0], Namespace: pod.Namespace}
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I think this use case we should use the Workload name annotation rather than slice. The SliceName corresponds to the name of the first workload in the chain. I think it is not relevant here as it may not exist any longer..

File: pkg/controller/tas/node_controller.go [hunk 73]
```diff
@@ -245,99 +289,112 @@ func (r *nodeReconciler) SetupWithManager(mgr ctrl.Manager, cfg *config.Configur
...
+	var podList corev1.PodList
+	if err := r.client.List(ctx, &podList, client.MatchingFields{indexer.PodNodeSelectorHostnameKey: nodeName}); err != nil {
+		return nil, fmt.Errorf("failed to list pods for node selector %s: %w", nodeName, err)
+	}
+
+	return groupPodsByWorkload(podList.Items), nil
+}
+
+func groupPodsByWorkload(pods []corev1.Pod) map[types.NamespacedName][]*corev1.Pod {
+	nodeSelectorPodsByWorkload := make(map[types.NamespacedName][]*corev1.Pod)
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: nit `result`

File: pkg/controller/tas/node_controller.go [hunk 74]
```diff
@@ -245,99 +289,112 @@ func (r *nodeReconciler) SetupWithManager(mgr ctrl.Manager, cfg *config.Configur
...
+	}
+
+	if !hasTASAssignment {
+		// This node is not part of the workload's topology assignment. If pods are assigned
+		// here (e.g., late pods with old node selectors), they are stray and must be terminated.
+		return workloadHealthCheck{status: workloadHealthy, podsToTerminate: podsToTerminate}, nil
+	}
+
+	if hasProgressingPods && (!hasUntoleratedTaints || features.Enabled(features.TASReplaceNodeOnPodTermination)) {
+		return workloadHealthCheck{status: workloadToBeObserved, podsToTerminate: podsToTerminate}, nil
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I think using `workloadToBeObserved` might be problematic and unnecessary here. This code path will be used for "healthy" scenarios when taints exist, note that taints are used for all healthy gpu and tpu nodes, so this effectively means monitoring all such nodes in the cluster continously every 1s.

I think this was more of a hack prior to introduction of the podHandler, and now we should be able to just react to pod transitions.

Let me know if you encounter some complications here

Comment (mimowo) [reply pkg/controller/tas/node_controller.go]: iiuc this will require extending the pod event handler to also react to pods which are terminating, something like this:
```golang
	if len(pod.Spec.NodeName) > 0 && (pod.DeletionTimestamp != nil !|| podutil.Isterminal(pod)) {
		req := reconcile.Request{
			NamespacedName: types.NamespacedName{
				Name: pod.Spec.NodeSelector[corev1.LabelHostname],
			},
		}
		q.AddAfter(req, nodeReconcileBatchPeriod)
	}
```

File: pkg/controller/tas/node_controller.go (hunk 71 above)
Comment (mimowo) [reply pkg/controller/tas/node_controller.go:186]: I think there might be a subtle race condition here in case there is a follow up Reconciel (to the reconcile which decided to evict a workload), and the  follow up Reconcile does not yet see the workload is evicted then it may take a decision to terminate the Pods. I'm not totally sure this would happen, but if this is the worst case scenario then I'm fine with it.

File: pkg/controller/tas/node_controller.go (hunk 72 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: changed to use workload name annotation

File: pkg/controller/tas/node_controller.go (hunk 74 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: also removed workloadToBeObserved and moved the controller to pod event driven

File: pkg/controller/tas/node_controller.go (hunk 71 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go:186]: that's mostly optimization, I wasn't considering it that way but that solves this too

File: pkg/controller/tas/node_controller.go (hunk 65 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: pkg/controller/tas/node_controller.go [hunk 75]
```diff
@@ -49,33 +51,41 @@ import (
...
 	utiltas "sigs.k8s.io/kueue/pkg/util/tas"
 	"sigs.k8s.io/kueue/pkg/workload"
 	"sigs.k8s.io/kueue/pkg/workloadslicing"
 )
 
-type workloadStatus int
-
 const (
 	nodeMultipleFailuresEvictionMessageFormat = "Workload eviction triggered due to multiple TAS assigned node failures, including: %s"
 	podTerminationCheckPeriod                 = 1 * time.Second
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: question: do we still need it? It does not seem used

File: pkg/controller/tas/node_controller.go [hunk 76]
```diff
@@ -553,3 +674,51 @@ func classifyNoExecuteTaints(ctx context.Context, taints []corev1.Taint, podSets
...
+	}
+
+	// queue for potential stuck pending pods
+	if len(pod.Spec.NodeName) == 0 && pod.Spec.NodeSelector != nil && len(pod.Spec.NodeSelector[corev1.LabelHostname]) > 0 {
+		req := reconcile.Request{
+			NamespacedName: types.NamespacedName{
+				Name: pod.Spec.NodeSelector[corev1.LabelHostname],
+			},
+		}
+		q.AddRateLimited(req)
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: I would rather batch the reconciles. Previously we observed with 1s delay anyway, so I propose to introduce a const `reconcileBatchPeriod` and use it for `q.AddAfter`.

File: pkg/controller/tas/node_controller.go (hunk 75 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: no, it's no longer used - removed.

File: pkg/controller/tas/node_controller.go (hunk 76 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: are you sure `q.AddAfter` does batching?

Comment (mimowo) [reply pkg/controller/tas/node_controller.go]: Yes, batching in time, by key. When there are multiple events calling AddAfter within 1s (for the same key), they will trigger only one reconcile, the nearest one.

Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: this is description of the interface 

```go
// TypedDelayingInterface is an Interface that can Add an item at a later time. This makes it easier to
// requeue items after failures without ending up in a hot-loop.
type TypedDelayingInterface[T comparable] interface {
	TypedInterface[T]
	// AddAfter adds an item to the workqueue after the indicated duration has passed
	AddAfter(item T, duration time.Duration)
}
```

I think it just adds some delay

Comment (mimowo) [reply pkg/controller/tas/node_controller.go]: Yeah deduplication is not mentioned in the comment, but take a look at the TestDeduping unit test for the delaying workqueue: https://github.com/kubernetes/kubernetes/blob/7d56731021ecb86428eea2cd910f0406372c897f/staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go#L72

Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: alright, I brought back the 100ms period
