### PR TITLE
fix: PropagateResourceRequests map equality check

### LINKED ISSUE #5058: PropagateResourceRequests always generates diff on CPU
PropagateResourceRequests always generates a diff on CPU apparently, which was spamming reconciles

from added logging
```
Mismatch in resource requests for workload main: main != main, OR amounts: true
resources: v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:10, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"10", Format:"DecimalSI"}}
  rlList: v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:10000, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}}
```
okay, integral CPU vs millicpu

https://github.com/kubernetes-sigs/kueue/blob/3279d9c05817e465229fac6bdc64250c890ea7dd/pkg/resources/requests.go#L102-L104

let's try milli cpu with a non-integral value
```
resources: v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:9001, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"9001m", Format:"DecimalSI"}}
  rlList: v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:9001, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}}
```
oh...the internally generated private string field differs during reflection comparison...because maps.Equal just calls direct struct equality for the entries https://cs.opensource.google/go/go/+/refs/tags/go1.24.2:src/maps/maps.go;l=22

switching to cmp.Equal resolves that

**What happened**:

they are not equal

**What you expected to happen**:

equality should pass for semantically equal values

**How to reproduce it (as minimally and precisely as possible)**:

Create an integration test with workloads blocked on CPU quota using integral CPU requests (e.g. "10"), it will generate a diff. Add logs in code to see the value of private fields that are different.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alexeldeib**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

fix infinite inequality loop for propagate resource requests check

#### Which issue(s) this PR fixes:

Fixes #5058

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where PropagateResourceRequests would always trigger an API status patch call.
```

### CODE REVIEW

**Comment by mimowo** [comment]
/assign @dgrove-oss 
could you give it a pass?

**Comment by mimowo** [comment]
oh I see @dgrove-oss is on holiday (based on slack status), leaving review to @PBundyra or @mbobrovskyi

**Comment by mimowo** [comment]
/approve
Leaving review to either @mbobrovskyi @PBundyra or @gabesaba

File: pkg/workload/workload.go [hunk 1]
```diff
@@ -652,7 +652,7 @@ func PropagateResourceRequests(w *kueue.Workload, info *Info) bool {
 		match := true
 		for idx := range w.Status.ResourceRequests {
 			if w.Status.ResourceRequests[idx].Name != info.TotalRequests[idx].Name ||
-				!maps.Equal(w.Status.ResourceRequests[idx].Resources, info.TotalRequests[idx].Requests.ToResourceList()) {
+				!IsResourceListEqual(w.Status.ResourceRequests[idx].Resources, info.TotalRequests[idx].Requests.ToResourceList()) {
```
Comment (tenzen-y) [inline pkg/workload/workload.go:655]:
```suggestion
				!equality.Semantic.DeepEqual(w.Status.ResourceRequests[idx].Resources, info.TotalRequests[idx].Requests.ToResourceList()) {
```

The kubernetes `Semantic.DeepEqual` allows us to verify same thing. You can try the following codes.

```go
func main() {
	a := corev1.ResourceList{"cpu": *resource.NewScaledQuantity(10, 0)}
	b := corev1.ResourceList{"cpu": *resource.NewScaledQuantity(10000, -3)}
	fmt.Println(equality.Semantic.DeepEqual(a, b))
}
```

File: pkg/workload/workload.go [hunk 2]
```diff
@@ -671,6 +671,19 @@ func PropagateResourceRequests(w *kueue.Workload, info *Info) bool {
...
+		return false
+	}
+	for k, v1 := range m1 {
+		if v2, ok := m2[k]; !ok || !v1.Equal(v2) {
+			return false
+		}
+	}
+	return true
+}
+
```
Comment (tenzen-y) [inline pkg/workload/workload.go:686]:
```suggestion
```

**Review by tenzen-y — COMMENTED** [review]
/approve cancel

File: pkg/workload/workload.go (hunk 1 above)
Comment (alexeldeib) [reply pkg/workload/workload.go:655]: ah, nice

File: pkg/workload/workload.go [hunk 3]
```diff
@@ -28,6 +28,7 @@ import (
 	corev1 "k8s.io/api/core/v1"
 	apimeta "k8s.io/apimachinery/pkg/api/meta"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/api/equality"
```
Comment (tenzen-y) [inline pkg/workload/workload.go:31]: You can resolve CI errors with `make lint-fix` command in your local, I believe.

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5110/pull-kueue-verify-main/1915868931055161344

File: pkg/workload/workload_test.go [hunk 4]
```diff
@@ -889,3 +889,66 @@ func TestAdmissionCheckStrategy(t *testing.T) {
...
+				}},
+			},
+			want: true,
+		},
+	}
+	for name, tc := range cases {
+		t.Run(name, func(t *testing.T) {
+			got := PropagateResourceRequests(tc.wl, tc.info)
+			if diff := cmp.Diff(tc.want, got); diff != "" {
+				t.Errorf("PropagateResourceRequests() returned (-want,+got):\n%s", diff)
```
Comment (tenzen-y) [inline pkg/workload/workload_test.go:950]:
```suggestion
				t.Errorf("Unexpected PropagateResourceRequests() result (-want,+got):\n%s", diff)
```

Clarifications.

File: pkg/workload/workload_test.go [hunk 5]
```diff
@@ -889,3 +889,66 @@ func TestAdmissionCheckStrategy(t *testing.T) {
 		})
 	}
 }
+
+func TestPropagateResourceRequests(t *testing.T) {
```
Comment (tenzen-y) [inline pkg/workload/workload_test.go:893]: could you add multiple resource types in addition to CPU something like memory?

**Review by tenzen-y — COMMENTED** [review]
Otherwise lgtm, thank you

File: pkg/workload/workload_test.go (hunk 5 above)
Comment (alexeldeib) [reply pkg/workload/workload_test.go:893]: added a few variations with cpu, memory, gpu (extended resource)

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve
