### PR TITLE
Use --force-conflicts on kubectl apply.

### LINKED ISSUE #9088: conflict with "multikueue.test" using v1
**What happened**:

```
error: Apply failed with 1 conflict: conflict with "multikueue.test" using v1: .data.controller_manager_config.yaml
```

**What you expected to happen**:

No errors

**How to reproduce it (as minimally and precisely as possible)**:

Execute twice:

Use focus for this test case:

```
ginkgo.FIt("Should be able to use ClusterProfile as way to connect worker cluster", func() {
```

```sh
E2E_MODE=dev make kind-image-build test-multikueue-e2e
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

Use --force-conflicts on kubectl apply.

#### Which issue(s) this PR fixes:

Fixes #9088

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: hack/e2e-common.sh [hunk 1]
```diff
@@ -513,7 +513,7 @@ function build_and_apply_kueue_manifests {
     build_output=$($KUSTOMIZE build "$2")
     # shellcheck disable=SC2001 # bash parameter substitution does not work on macOS
     build_output=$(echo "$build_output" | sed "s/kueue-system/$KUEUE_NAMESPACE/g")
-    echo "$build_output" | kubectl apply --kubeconfig="$1" --server-side -f -
+    echo "$build_output" | kubectl apply --kubeconfig="$1" --server-side --force-conflicts -f -
```
Comment (mimowo) [inline hack/e2e-common.sh]: Can we do it only in the dev mode? I know this is harmless in the CI mode, but maybe it could be raising questions: why we do it? So, I think it is cleaner to hide it behind "if" and add a comment

Comment (mbobrovskyi) [reply hack/e2e-common.sh]: I think we should use --force-conflicts only if Kueue already exists. So in “ci” mode, it shouldn’t be executed.

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Thank you 👍

File: hack/e2e-common.sh (hunk 1 above)
Comment (mimowo) [reply hack/e2e-common.sh]: exactly, new new code is matching my expectations

**Comment by mimowo** [comment]
/test pull-kueue-test-e2e-certmanager-main

looks like infra failiure
