### PR TITLE
Fix memory leak due to workload entries left in MultiKueue cache

### LINKED ISSUE #3818: Unexpectedly High Memory Usage during idle state
**What happened**: Firstly, I raised the resource limit to 16gb for the kueue-controller-manager and had submitted over 90,000 jobs to the kueue when I'd noticed the kueue-controller-manager memory usage jump to ~10gb. After all the jobs have been completed, I still notice that the kueue-controller-manager is using ~5gb memory. This is the memory usage during an idle state after all the jobs have completed.

`kubectl top pod -n kueue-system`
image

**What you expected to happen**: I was expecting the memory usage to drop down to ~500mb since that was the original limit for the kueue-controller-manager.

**How to reproduce it (as minimally and precisely as possible)**: Submit a large number of jobs, which each job taking a considerable amount if time (average job execution time : 5m). Submit a whole lot of them, and monitor the memory usage.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.30.5-gke.1443001
- Kueue version: v0.9.1
- Cloud provider or hardware configuration: GCP - Google Kubernetes Engine
- OS (e.g: `cat /etc/os-release`): linux/amd64
- GoVersion: go1.22.6 X:boringcrypto
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #3818 

#### Special notes for your reviewer:

I have unit tests added and they fail without the change:
```
--- FAIL: TestWlReconcile (0.22s)
    --- FAIL: TestWlReconcile/deleted_MultiKueue_workload_is_deleted_from_cache_-_the_worker_will_be_deleted_by_GC (0.01s)
        /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/pkg/controller/admissionchecks/multikueue/workload_test.go:1166: unexpected deletedWlCache len 1 expecting 0
    --- FAIL: TestWlReconcile/deleted_regular_workload_is_removed_from_the_cache (0.01s)
        /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/pkg/controller/admissionchecks/multikueue/workload_test.go:1166: unexpected deletedWlCache len 1 expecting 0
```

#### Does this PR introduce a user-facing change?

```release-note
Fix memory leak due to workload entries left in MultiKueue cache. The leak affects the 0.9.0 and 0.9.1 
releases which enable MultiKueue by default, even if MultiKueue is not explicitly used on the cluster.
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
I think that this is still work on unit testings.
/hold

**Comment by mimowo** [comment]
/hold cancel
The tests are added (updated the PR description to show how they fail when the line deleting the entry from cache is commented out).

**Comment by PBundyra** [comment]
/lgtm
Thanks @mimowo

File: pkg/controller/admissionchecks/multikueue/workload_test.go [hunk 1]
```diff
@@ -95,6 +95,41 @@ func TestWlReconcile(t *testing.T) {
...
+					Label(kueue.MultiKueueOriginLabel, defaultOrigin).
+					Obj(),
+			},
+			wantManagersJobs: []batchv1.Job{*baseJobManagedByKueueBuilder.Clone().Obj()},
+			wantWorker1Workloads: []kueue.Workload{
+				*baseWorkloadBuilder.Clone().
+					Label(kueue.MultiKueueOriginLabel, defaultOrigin).
+					Obj(),
+			},
+		},
```
Comment (tenzen-y) [inline pkg/controller/admissionchecks/multikueue/workload_test.go:132]: Could we add a case where the checkState has Retry or Pending?
We want to verify if the workloads are not removed from the cache.

**Review by tenzen-y — COMMENTED** [review]
Basically, lgtm
/hold

File: pkg/controller/admissionchecks/multikueue/workload_test.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/admissionchecks/multikueue/workload_test.go:132]: We can in a follow up cleanup PR. This is not direcltly related to the PR. Actually, such workloads will be deleted from cache, but after removing the workloads on the worker clusters.

Comment (tenzen-y) [reply pkg/controller/admissionchecks/multikueue/workload_test.go:132]: Yes, this is not in a hurry.
I'm ok with followup.
