### PR TITLE
Fix nil panic in tas node controller when referencing nil .status.admission.  

### LINKED ISSUE #10640: TAS: node reconciler panics
**What happened**:

We observe panics from the node reconciler

```
{"level":"error","ts":"2026-04-21T05:19:10.728242575Z","logger":"tas-node-reconciler","caller":"runtime/runtime.go:142","msg":"Observed a panic","replica-role":"leader","name":"xyz,"reconcileID":"524a9e82-6b6d-4135-b598-032e1627baac","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"goroutine 1704 [running]:\[nk8s.io/apimachinery/pkg/util/runtime.logPanic(](http://nk8s.io/apimachinery/pkg/util/runtime.logPanic(){0x38e2c78, 0xc006ac4600}, {0x2dd2a40, 0x564c880})\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:132 +0xbc\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).Reconcile.func1()\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:202 +0x10e\npanic({0x2dd2a40?, 0x564c880?})\n\t/usr/local/go/src/runtime/panic.go:783 +0x132\[nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).getWorkloadStatus(0xc0002d4ee0,](http://nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).getWorkloadStatus(0xc0002d4ee0,) {0x38e2c78, 0xc006ac4600}, {0xc0018b5020, 0x15}, 0xc006425c08, {{0xc00189bbe0, 0xa}, {0xc001830b00, 0x3f}}, ...)\n\t/workspace/pkg/controller/tas/node_controller.go:351 +0x1be\[nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).reconcileWorkloadsOnNode(0xc0002d4ee0,](http://nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).reconcileWorkloadsOnNode(0xc0002d4ee0,) {0x38e2c78, 0xc006ac4600}, {0xc0018b5020, 0x15}, 0xc006425c08, 0xc006ac5020, 0xc006ac4f30)\n\t/workspace/pkg/controller/tas/node_controller.go:474 +0x3b3\[nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).Reconcile(0xc0002d4ee0,](http://nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).Reconcile(0xc0002d4ee0,) {0x38e2c78, 0xc006ac4600}, {{{0x0?, 0xb?}, {0xc0018b5020?, 0x2000000000000?}}})\n\t/workspace/pkg/controller/tas/node_controller.go:189 +0x3e5\[nsigs.k8s.io/kueue/pkg/controller/core.(*leaderAwareReconciler).Reconcile(0xc0049a3140,](http://nsigs.k8s.io/kueue/pkg/controller/core.(*leaderAwareReconciler).Reconcile(0xc0049a3140,) {0x38e2c78, 0xc006ac4600}, {{{0x0?, 0x1d9aba6?}, {0xc0018b5020?, 0x0?}}})\n\t/workspace/pkg/controller/core/leader_aware_reconciler.go:77 +0x162\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).Reconcile(0xc006ac4570, {0x38e2c78?, 0xc006ac4600}, {{{0x0, 0x0?}, {0xc0018b5020?, 0x0?}}})\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0x1ab\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).reconcileHandler(0x39296a0, {0x38e2cb0, 0xc004868960}, {{{0x0, 0x0}, {0xc0018b5020, 0x15}}}, 0x0)\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:479 +0x39c\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).processNextWorkItem(0x39296a0, {0x38e2cb0, 0xc004868960})\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:438 +0x21b\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).Start.func1.1()\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:313 +0x85\ncreated by[ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).Start.func1 in goroutine 890\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:309 +0x26b\n","stacktrace":"[k8s.io/apimachinery/pkg/util/runtime.logPanic](http://k8s.io/apimachinery/pkg/util/runtime.logPanic)\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:142\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).Reconcile.func1\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:202\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:783\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:262\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:925\[nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).getWorkloadStatus](http://nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).getWorkloadStatus)\n\t/workspace/pkg/controller/tas/node_controller.go:351\[nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).reconcileWorkloadsOnNode](http://nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).reconcileWorkloadsOnNode)\n\t/workspace/pkg/controller/tas/node_controller.go:474\[nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).Reconcile](http://nsigs.k8s.io/kueue/pkg/controller/tas.(*nodeReconciler).Reconcile)\n\t/workspace/pkg/controller/tas/node_controller.go:189\[nsigs.k8s.io/kueue/pkg/controller/core.(*leaderAwareReconciler).Reconcile](http://nsigs.k8s.io/kueue/pkg/controller/core.(*leaderAwareReconciler).Reconcile)\n\t/workspace/pkg/controller/core/leader_aware_reconciler.go:77\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).Reconcile\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).reconcileHandler\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:479\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).processNextWorkItem\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:438\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[..).]).Start.func1.1\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:313"}
```

**What you expected to happen**:

No panic

**How to reproduce it (as minimally and precisely as possible)**:

TBD, but it seems this might be happening for workloads evicted in the meanwhile

### PR DESCRIPTION
**Pull request by j-skiba**
#### What type of PR is this?
/kind bug
/area tas

#### What this PR does / why we need it:
Add nil check for workload status admission field before accessing it for further TAS assignment checks

#### Which issue(s) this PR fixes:
Fixes #10640

#### Special notes for your reviewer:
It's almost the same as https://github.com/kubernetes-sigs/kueue/pull/10036

#### Does this PR introduce a user-facing change?
```release-note
TAS: Fix nil pointer panic in TAS node reconciler when unadmitted workloads exist in the cluster.
```

### CODE REVIEW

File: pkg/controller/tas/node_controller.go [hunk 1]
```diff
@@ -355,7 +355,10 @@ func (r *nodeReconciler) getWorkloadStatus(
 	}
 
 	ready := utiltas.IsNodeStatusConditionTrue(node.Status.Conditions, corev1.NodeReady)
-	hasTASAssignment := utiltas.HasTASAssignmentOnNode(wl.Status.Admission.PodSetAssignments, nodeName)
+	hasTASAssignment := false
+	//if wl.Status.Admission != nil {
+	hasTASAssignment = utiltas.HasTASAssignmentOnNode(wl.Status.Admission.PodSetAssignments, nodeName)
```
Comment (mimowo) [inline pkg/controller/tas/node_controller.go]: Could we maybe pass entire `wl.Status.Admission` to `HasTASAssignmentOnNode` and check for the nilness inside?

File: test/integration/singlecluster/tas/tas_test.go [hunk 2]
```diff
@@ -522,6 +522,58 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
 		})
 	})
 
+	ginkgo.When("Workload without admission has pods with node selector", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/tas/tas_test.go:525]: Thank you for the integration test 👍

File: pkg/controller/tas/node_controller.go (hunk 1 above)
Comment (j-skiba) [reply pkg/controller/tas/node_controller.go]: done

File: test/integration/singlecluster/tas/tas_test.go (hunk 2 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:525]: reproduction logs: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10641/pull-kueue-test-integration-baseline-main/2046514558276734976

Comment (mimowo) [reply test/integration/singlecluster/tas/tas_test.go:525]: Actually, can you clarify how https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10641/pull-kueue-test-integration-baseline-main/2046514558276734976 reproduced the issue? I don't see any "panic" in the [build-logs](https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10641/pull-kueue-test-integration-baseline-main/2046514558276734976/build-log.txt).

Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:525]: I think I should have run `extended` suite.

Locally I get this:
```bash
make test-integration INTEGRATION_TARGET="./test/integration/singlecluster/tas" GINKGO_ARGS="--focus 'Workload without admission'"
```
https://gist.github.com/j-skiba/1a311e0188ace3b6fff2188b0d45c6e9

**Comment by mimowo** [comment]
/lgtm
/approve
Thank you 👍

**Comment by mimowo** [comment]
@j-skiba please prepare the CP to 0.16
