### PR TITLE
fix: ensure conversion webhook CA bundles are injected during upgrades

### LINKED ISSUE #7344: Helm deployment is broken
**What happened**:
When I deploy Kueue using the helm deployment at head 

```
$ git clone git@github.com:kubernetes-sigs/kueue.git
$ cd kueue/charts
$ helm install kueue kueue/ --create-namespace --namespace kueue-system
```

And deploy a localQueue, I get the following error

```
$ k get localqueue
Error from server: conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post "https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

This doesn't happen if using the released version of the helm chart.

**What you expected to happen**:
For the following command to return without an error
```
$ k get localqueue
```

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.33
- Kueue version (use `git describe --tags --dirty --always`): f2aff8485
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sohankunkerkar**
During upgrades with pre-existing LQ/CQ, the API server fails conversion with 'x509: certificate signed by unknown authority' because cert-controller doesn't inject CA bundles into CRD conversion webhook configurations. This fix manually injects CA bundles into kueue.x-k8s.io CRDs, registers webhooks before manager start so conversion endpoints are ready when caches sync.

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #7344

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: cmd/kueue/main.go [hunk 1]
```diff
@@ -428,6 +428,10 @@ func setupControllers(ctx context.Context, mgr ctrl.Manager, cCache *schdcache.C
 func setupProbeEndpoints(mgr ctrl.Manager, certsReady <-chan struct{}) error {
 	defer setupLog.Info("Probe endpoints are configured on healthz and readyz")
 
+	// Retrieve the webhook server interface early to avoid overhead in the loop
```
Comment (mimowo) [inline cmd/kueue/main.go]: avoiding overhead is not a convincing argument, probably premature optimization, the question if this is relevant change for the fix and why

Comment (sohankunkerkar) [reply cmd/kueue/main.go]: Yeah, I don't think we need this anymore.

**Comment by mimowo** [comment]
looks like the failure might be related to changes: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7772/pull-kueue-test-e2e-main-1-34/1991909973134675968

https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7772/pull-kueue-test-e2e-main-1-34/1991909973134675968/artifacts/run-test-e2e-singlecluster-1.34.0/kind-worker/pods/kueue-system_kueue-controller-manager-84b98fd797-h85gl_86385d89-4b07-49ba-84d0-bcd3b6ce8ff7/manager/0.log

**Comment by sohankunkerkar** [comment]
> looks like the failure might be related to changes: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7772/pull-kueue-test-e2e-main-1-34/1991909973134675968
> 
> https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7772/pull-kueue-test-e2e-main-1-34/1991909973134675968/artifacts/run-test-e2e-singlecluster-1.34.0/kind-worker/pods/kueue-system_kueue-controller-manager-84b98fd797-h85gl_86385d89-4b07-49ba-84d0-bcd3b6ce8ff7/manager/0.log

I’ve now added leader election to the bootstrap manager, so only one instance attempts to generate certs. Let’s see if it helps.

File: charts/kueue/templates/rbac/role.yaml [hunk 2]
```diff
@@ -38,6 +38,7 @@ rules:
       - limitranges
       - namespaces
       - nodes
+      - secrets
```
Comment (mimowo) [inline charts/kueue/templates/rbac/role.yaml]: I don't think we should be giving the controller the global access to secrets, this was raised as a security issue in the past: https://github.com/kubernetes-sigs/kueue/pull/7188. IIUC the code only needs to read the secret in kueue-system, so for that we should already have RBAC

File: pkg/util/cert/cert.go [hunk 3]
```diff
@@ -99,3 +167,97 @@ func deriveWebhookBaseName(webhookServiceName string) string {
...
+			return nil, err
+		}
+		time.Sleep(2 * time.Second)
+	}
+	err = errors.New("timeout waiting for CA certificate")
+	log.Error(err, "CA bundle injection failed")
+	return nil, err
+}
+
+func injectCABundlesIntoCRDs(mgr ctrl.Manager, crdNames []string, caData []byte, log logr.Logger) error {
```
Comment (mimowo) [inline pkg/util/cert/cert.go]: If we are starting the bootstrap manager, then I think we could register the cert rotator into it. And It would do all the retrying for us. Maybe I'm missing something, but it would allow to drop a lot of the  code.

File: charts/kueue/templates/rbac/role.yaml (hunk 2 above)
Comment (sohankunkerkar) [reply charts/kueue/templates/rbac/role.yaml]: Yeah, good catch!

File: pkg/util/cert/cert.go (hunk 3 above)
Comment (sohankunkerkar) [reply pkg/util/cert/cert.go]: ~I simplified the flow by moving cert generation and CA injection to the bootstrap manager using cert-rotator, but  kept the retry logic as-is to address transient API server errors (already saw a few flakes for the 1.32/1.33/1.34 e2e jobs ), and added leader election to avoid concurrent updates.~
~I didn't change the logic for the CRD conversion webhook CA injection, since cert-rotator doesn’t support CRDs and only handles Mutating/Validating webhook configs.~

Edit:
I guess we don't need this as cert rotator does CRD conversion webhooks via the CRDConversion type

File: cmd/kueue/main.go [hunk 4]
```diff
@@ -204,6 +204,16 @@ func main() {
 		kubeConfig.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(*cfg.ClientConnection.QPS, int(*cfg.ClientConnection.Burst))
 	}
 	setupLog.V(2).Info("K8S Client", "qps", *cfg.ClientConnection.QPS, "burst", *cfg.ClientConnection.Burst)
+
+	// Bootstrap certificates before creating the main manager
```
Comment (kannon92) [inline cmd/kueue/main.go:208]: What about cert manager users?

Comment (sohankunkerkar) [reply cmd/kueue/main.go:208]: This change doesn’t affect cert-manager users. When internal cert management is disabled, cert-manager’s CA injector still handles the CA bundle injection as long as the CRDs have the `cert-manager.io/inject-ca-from` annotation. The Helm chart already sets this. We just need to handle the Kustomize flow, where users enable it through the [CERTMANAGER] patches.

File: test/e2e/upgrade/upgrade_validation_test.go [hunk 5]
```diff
@@ -0,0 +1,182 @@
...
+						"container", containerStatus.Name,
+						"restarts", containerStatus.RestartCount,
+						"ready", containerStatus.Ready)
+				}
+			}
+		}
+	})
+
+	ginkgo.It("should admit jobs using pre-existing LocalQueue", func() {
+		const jobNamespace = "default"
```
Comment (kannon92) [inline test/e2e/upgrade/upgrade_validation_test.go:127]: We should generate a namespace for this test and tear it down.

File: pkg/util/cert/cert.go [hunk 6]
```diff
@@ -38,17 +42,89 @@ const (
...
+
+	// Wait for cert-rotator to complete cert generation and CA injection
+	log.Info("Waiting for certificate generation and CA injection to complete")
+	<-certsReady
+	log.Info("Certificates ready and CA bundles injected")
+
+	log.Info("Stopping bootstrap manager")
+	bootstrapCancel()
+
+	time.Sleep(1 * time.Second)
```
Comment (mimowo) [inline pkg/util/cert/cert.go]: This sleep should not be necessary. I think you added to mitigate flakes as the bootstrapManager can take time to complete. We should wait explicitly instead:
```golang
bootstrapCtx, bootstrapCancel := context.WithCancel(context.Background())
defer bootstrapCancel()

managerStopped := make(chan struct{})
go func() {
	log.Info("Starting bootstrap manager")
	if err := bootstrapMgr.Start(bootstrapCtx); err != nil {
       	log.Error(err, "Bootstrap manager failed")
	}
	close(managerStopped)                   // <- notify it is stopped
}()

// Wait for cert-rotator to complete cert generation and CA injection
log.Info("Waiting for certificate generation and CA injection to complete")
<-certsReady
log.Info("Certificates ready and CA bundles injected")

log.Info("Stopping bootstrap manager")
bootstrapCancel()

log.Info("Waiting for the bootstrap manager to stop")
<-managerStopped

log.Info("Certificate bootstrap complete")
return nil
```

File: test/e2e/upgrade/upgrade_validation_test.go [hunk 7]
```diff
@@ -0,0 +1,182 @@
...
+			fromVersion = "unknown"
+		}
+		ginkgo.GinkgoLogr.Info("Starting upgrade validation test", "fromVersion", fromVersion)
+		ginkgo.By("Waiting for deployment to rollout")
+		util.WaitForKueueAvailabilityNoRestartCountCheck(ctx, k8sClient)
+
+		ginkgo.By("Giving certificate bootstrap time to complete")
+		// We need to wait for the conversion webhook to be ready before the controller
+		// can successfully list v1beta1 resources (which triggers conversion to v1beta2).
+		time.Sleep(util.Timeout)
```
Comment (mimowo) [inline test/e2e/upgrade/upgrade_validation_test.go]: This should not be needed. It is a custom wait for 10s which is not good practice.

File: test/e2e/upgrade/upgrade_validation_test.go [hunk 8]
```diff
@@ -0,0 +1,182 @@
...
+)
+
+var _ = ginkgo.Describe("Upgrade Validation", ginkgo.Ordered, func() {
+	ginkgo.It("should have completed upgrade successfully", func() {
+		fromVersion := upgradeFrom
+		if fromVersion == "" {
+			fromVersion = "unknown"
+		}
+		ginkgo.GinkgoLogr.Info("Starting upgrade validation test", "fromVersion", fromVersion)
+		ginkgo.By("Waiting for deployment to rollout")
```
Comment (mimowo) [inline test/e2e/upgrade/upgrade_validation_test.go]: Such logs are already added inside the function

File: test/e2e/upgrade/upgrade_validation_test.go [hunk 9]
```diff
@@ -0,0 +1,182 @@
...
+		util.WaitForKueueAvailabilityNoRestartCountCheck(ctx, k8sClient)
+
+		ginkgo.By("Giving certificate bootstrap time to complete")
+		// We need to wait for the conversion webhook to be ready before the controller
+		// can successfully list v1beta1 resources (which triggers conversion to v1beta2).
+		time.Sleep(util.Timeout)
+
+		ginkgo.By("Waiting for conversion webhook to be ready")
+		// Verify the conversion webhook is working by listing LocalQueues
```
Comment (mimowo) [inline test/e2e/upgrade/upgrade_validation_test.go]: nit, drop the comment, and make sure the intention is expressed in the ginkgo.By

File: test/e2e/upgrade/upgrade_validation_test.go [hunk 10]
```diff
@@ -0,0 +1,182 @@
...
+			mwc := &admissionregistrationv1.MutatingWebhookConfiguration{}
+			g.Expect(k8sClient.Get(ctx, client.ObjectKey{Name: "kueue-mutating-webhook-configuration"}, mwc)).To(gomega.Succeed())
+
+			hasCABundle := false
+			for _, webhook := range mwc.Webhooks {
+				if len(webhook.ClientConfig.CABundle) > 0 {
+					hasCABundle = true
+					break
+				}
+			}
```
Comment (mimowo) [inline test/e2e/upgrade/upgrade_validation_test.go]: nit, simplify following 
```golang
				for _, webhook := range mwc.Webhooks {
					g.Expect(webhook.ClientConfig.CABundle).ToNot(gomega.BeEmpty())
				}
```

File: test/e2e/upgrade/upgrade_validation_test.go [hunk 11]
```diff
@@ -0,0 +1,182 @@
...
+
+	ginkgo.It("should read pre-existing ClusterQueue without x509 errors", func() {
+		cq := &kueue.ClusterQueue{}
+		cqKey := types.NamespacedName{Name: "upgrade-test-cq"}
+		gomega.Expect(k8sClient.Get(ctx, cqKey, cq)).To(gomega.Succeed())
+	})
+
+	ginkgo.It("should have webhook secret with valid certificates", func() {
+		secret := &corev1.Secret{}
+		secretKey := types.NamespacedName{Name: "kueue-webhook-server-cert", Namespace: "kueue-system"}
```
Comment (mimowo) [inline test/e2e/upgrade/upgrade_validation_test.go]:
```suggestion
		secretKey := types.NamespacedName{Name: "kueue-webhook-server-cert", Namespace: kueueNS}
```
nit, so that the tests can be run in another namespace potentially (same comment in other places)

File: Makefile-test.mk [hunk 12]
```diff
@@ -202,6 +208,29 @@ run-test-e2e-certmanager-%:
 		E2E_USE_HELM=$(E2E_USE_HELM) \
 		./hack/e2e-test.sh
 
+run-test-e2e-upgrade-%: K8S_VERSION = $(@:run-test-e2e-upgrade-%=%)
+run-test-e2e-upgrade-%:
+	@echo Running upgrade e2e for k8s ${K8S_VERSION}
+	E2E_KIND_VERSION="kindest/node:v$(K8S_VERSION)" KIND_CLUSTER_NAME=$(KIND_CLUSTER_NAME) CREATE_KIND_CLUSTER=$(CREATE_KIND_CLUSTER) \
+		ARTIFACTS="$(ARTIFACTS)/$@" IMAGE_TAG=$(IMAGE_TAG) GINKGO_ARGS="$(GINKGO_ARGS)" \
+		KIND_CLUSTER_FILE="kind-cluster.yaml" E2E_TARGET_FOLDER="upgrade" \
+		KUEUE_UPGRADE_FROM_VERSION="v0.14.4" \
```
Comment (mimowo) [inline Makefile-test.mk]: nit, move the v0.14.4 to a dedicated var so that we have single place to bump the future

File: cmd/kueue/main.go [hunk 13]
```diff
@@ -265,15 +275,18 @@ func main() {
...
-	// Controllers who register after manager starts will start directly.
-	go func() {
-		if err := setupControllers(ctx, mgr, cCache, queues, certsReady, &cfg, serverVersionFetcher); err != nil {
-			setupLog.Error(err, "Unable to setup controllers")
-			os.Exit(1)
-		}
-	}()
+	// Register webhooks early so handlers are present when the manager starts
+	// the webhook server. This avoids a race where controllers try to list
+	// converted resources before the webhook is serving with valid certs.
```
Comment (mimowo) [inline cmd/kueue/main.go]: I don't think this is necessary. The order of declaration does not matter for the manager to start. It will start in Start function. So I suggest to drop the comment as it could be misleading and move back the function. Unless you can demonstate (maybe another experimental PR that it fails without it). I would speculate the reason is some flakes you expirienced due to the 1s delay.

**Review by mimowo — COMMENTED** [review]
Overall LGTM, the custom sleep is the main issue I would like to eliminate and we can merge. I'm going to do another release candidate soon after that

**Comment by mimowo** [comment]
I don't think we need a release note. The bug hasn't been released yet. On the previous versions upgrades the certs were rotated on upgrades.
/release-note-edit
```release-note
NONE
```

File: test/e2e/upgrade/suite_test.go [hunk 14]
```diff
@@ -0,0 +1,83 @@
...
+		ginkgo.Fail("KUEUE_UPGRADE_FROM_VERSION environment variable must be set")
+	}
+
+	ginkgo.GinkgoLogr.Info("Starting upgrade test suite",
+		"upgradeFrom", upgradeFrom,
+		"namespace", kueueNS)
+
+	var err error
+	err = apiextensionsv1.AddToScheme(scheme.Scheme)
+	gomega.Expect(err).NotTo(gomega.HaveOccurred())
```
Comment (mimowo) [inline test/e2e/upgrade/suite_test.go]: Move adding this to CreateClientUsingCluster
as in https://github.com/kubernetes-sigs/kueue/pull/7824

File: test/e2e/upgrade/upgrade_validation_test.go (hunk 5 above)
Comment (sohankunkerkar) [reply test/e2e/upgrade/upgrade_validation_test.go:127]: The test intentionally uses the default namespace because the upgrade script creates a pre-existing LocalQueue there and the test needs to verify that it still works after the upgrade. Using a generated namespace wouldn’t test upgrade behavior.

Comment (kannon92) [reply test/e2e/upgrade/upgrade_validation_test.go:127]: Well we probably shouldn't use default.

Comment (mimowo) [reply test/e2e/upgrade/upgrade_validation_test.go:127]: what are the downsides of using default here @kannon92?

I think we normally create namespaces for dwbuggability, but in this case the testing Job is  very limited in scope anyway.

In any case I think it is something we can cleanup in a follow up. I think the priority now is to have the test which proves it is fixed, have release candidate for testing by early users

Comment (mimowo) [reply test/e2e/upgrade/upgrade_validation_test.go]: what are the downsides of using default here @kannon92?

I think we normally create namespaces for debuggability, but in this case the testing Job is  very limited in scope anyway.

In any case I think it is something we can cleanup in a follow up. I think the priority now is to have the test which proves it is fixed, have release candidate for testing by early users

Comment (kannon92) [reply test/e2e/upgrade/upgrade_validation_test.go:127]: At least for normal distributions default is usually locked down. I was thinking that for openshift we may have difficulities submitting jobs to default namespace unless the client has admin access.

But I'm fine to iterate on this if we need to fix this.

Comment (mimowo) [reply test/e2e/upgrade/upgrade_validation_test.go:127]: Yeah, sure. Using default namespace is not good for production use. For testing it is also not ideal, because if something goes wrong (test fails) it is likely to impact downstream tests. However, here we don't really have any downstream tests yet. So, I think we can iterate later as a follow up.

Comment (sohankunkerkar) [reply test/e2e/upgrade/upgrade_validation_test.go:127]: Yeah, I will do this as a follow up.

File: test/e2e/upgrade/suite_test.go (hunk 14 above)
Comment (sohankunkerkar) [reply test/e2e/upgrade/suite_test.go]: Yeah, that make sense!

File: test/e2e/upgrade/upgrade_validation_test.go (hunk 9 above)
Comment (mimowo) [reply test/e2e/upgrade/upgrade_validation_test.go]: I see this is resolved

File: test/e2e/upgrade/upgrade_validation_test.go (hunk 8 above)
Comment (mimowo) [reply test/e2e/upgrade/upgrade_validation_test.go]: this is resolved in code now

File: test/e2e/upgrade/upgrade_validation_test.go (hunk 7 above)
Comment (mimowo) [reply test/e2e/upgrade/upgrade_validation_test.go]: this is resolved in code now i think

**Comment by mimowo** [comment]
/lgtm
/approve
Thank you 👍 Seems like we are good to have the next release candidate, let me proceed after it is merged

File: pkg/util/cert/cert.go [hunk 15]
```diff
@@ -38,17 +41,92 @@ const (
 // +kubebuilder:rbac:groups="admissionregistration.k8s.io",resources=validatingwebhookconfigurations,verbs=get;list;watch;update
 // +kubebuilder:rbac:groups="apiextensions.k8s.io",resources=customresourcedefinitions,verbs=get;list;watch;update
 
-// ManageCerts creates all certs for webhooks. This function is called from main.go.
+// BootstrapCerts creates a minimal manager to generate certificates and inject CA bundles.
+// This function blocks until certificates are ready and CA bundles are injected into CRDs.
+func BootstrapCerts(kubeConfig *rest.Config, cfg config.Configuration) error {
```
Comment (tenzen-y) [inline pkg/util/cert/cert.go:46]: We might be able to remove this once we stop supporting v1beta1 since it means removing conversion webhooks.
But, in the graduation from v1beta2 to v1, these bootstrap certs should exist.

So, we probably maintain this mechanism in the next half year.
