### PR TITLE
Deactivate ClusterQueue if there is no Topology

### LINKED ISSUE #3645: TAS: CQ is not deactivated when there is no Topology
**What happened**:

When a user creates a CQ pointing to TAS RF without Topology, then the CQ is not deactivated.

There is no way to know the Topology is missing other than creating a workload, but even then the error message is unclear; 

**What you expected to happen**:

Deactivate the CQ, similarly as we deactivate it for other mis-configuration issues, such as a missing RF.

**How to reproduce it (as minimally and precisely as possible)**:

Create the TAS structure without Topology, then create a workload targeting the CQ

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind feature
/kind bug

#### Which issue(s) this PR fixes:

Fixes #3645 

#### Does this PR introduce a user-facing change?

```release-note
TAS: The CQ referencing a Topology is deactivated if the topology does not exist.
```

### CODE REVIEW

**Comment by mimowo** [comment]
FYI: I repro the data race issue locally, will investigate and push the update, most likely tomorrow

File: test/integration/tas/tas_test.go [hunk 1]
```diff
@@ -539,8 +546,82 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+				})
+
+				var wl *kueue.Workload
+				ginkgo.By("creating a workload which requires block and can fit", func() {
+					wl = testing.MakeWorkload("wl", ns.Name).
+						Queue(localQueue.Name).Request(corev1.ResourceCPU, "1").Obj()
+					wl.Spec.PodSets[0].Count = 2
+					wl.Spec.PodSets[0].TopologyRequest = &kueue.PodSetTopologyRequest{
+						Required: ptr.To(testing.DefaultBlockTopologyLevel),
+					}
```
[the remark this answers is not in the document]
Comment (mimowo) [reply test/integration/tas/tas_test.go:610]: sure, that was just a quick copy-paste, let me clean it up

File: pkg/controller/tas/resource_flavor.go [hunk 2]
```diff
@@ -142,6 +143,8 @@ var _ handler.EventHandler = (*topologyHandler)(nil)
 // topologyHandler handles node update events.
```
Comment (PBundyra) [inline pkg/controller/tas/resource_flavor.go:143]: Can we update this comment?

File: pkg/controller/tas/resource_flavor.go [hunk 3]
```diff
@@ -158,13 +161,16 @@ func (h *topologyHandler) Create(ctx context.Context, e event.CreateEvent, q wor
 		return
 	}
 
+	defer h.notifyTopologyWatchers(nil, topology)
+
 	// trigger reconcile for TAS flavors affected by the node being created or updated
```
Comment (PBundyra) [inline pkg/controller/tas/resource_flavor.go:166]: Is the reconcile loop triggered if the nodes are created/updated or topology?

Comment (mimowo) [reply pkg/controller/tas/resource_flavor.go]: topology, that was a stale comment. Fixed.

File: pkg/controller/core/clusterqueue_controller.go [hunk 4]
```diff
@@ -594,6 +613,34 @@ func (h *cqAdmissionCheckHandler) Generic(_ context.Context, e event.GenericEven
...
+	if !isTopology {
+		return
+	}
+	cqs := h.cache.ClusterQueuesUsingTopology(kueue.TopologyReference(topology.Name))
+	for _, cq := range cqs {
+		req := reconcile.Request{
+			NamespacedName: types.NamespacedName{
+				Name: cq,
+			}}
+		q.AddAfter(req, time.Second)
```
Comment (tenzen-y) [inline pkg/controller/core/clusterqueue_controller.go:640]: Why do we want to delay a second?
We usually set delay only when we can imagine Object operation frequently.
IIUC, the topology resources will not be modified frequently, right?

File: pkg/controller/core/core.go [hunk 5]
```diff
@@ -83,6 +83,7 @@ func SetupControllers(mgr ctrl.Manager, qManager *queue.Manager, cc *cache.Cache
 	).SetupWithManager(mgr, cfg); err != nil {
 		return "Workload", err
 	}
+	qManager.AddTopologyUpdateWatcher(cqRec)
```
Comment (tenzen-y) [inline pkg/controller/core/core.go:86]: Can we add topology watcher in the resonciler so that we can avoid to take the qManager lock?

File: pkg/controller/core/clusterqueue_controller.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/core/clusterqueue_controller.go:640]: Right, topology creations / deletes are rare. OTOH, 1s delay will not be a problem in most cases. I'm indifferent about the delay. I can delete it tentatively.

File: pkg/controller/core/core.go (hunk 5 above)
Comment (mimowo) [reply pkg/controller/core/core.go:86]: We don't need to the qManager lock, because the watchers are only added during startup.

I tried initially in reconciler, but this is problematic, because it would mean registering TAS RF reconciler in the CQ core reconciler, but this breaks the dependency - because currently TAS controllers are in a dedicated package. TAS reconcilers depend on core reconcilers, but not the other way round. So, placing the watchers in qManager breaks the dependency issue. I think we could use this pattern for other watchers. I think it works conceptually.

File: pkg/cache/clusterqueue_test.go [hunk 6]
```diff
@@ -1067,20 +1069,41 @@ func TestClusterQueueReadinessWithTAS(t *testing.T) {
 			wantReason:  kueue.ClusterQueueActiveReasonNotSupportedWithTopologyAwareScheduling,
 			wantMessage: "Can't admit new workloads: TAS is not supported with ProvisioningRequest admission check.",
 		},
+		{
+			name:         "TAS do not support ProvisioningRequest AdmissionCheck",
```
Comment (PBundyra) [inline pkg/cache/clusterqueue_test.go:1073]: Can we update the name of this scenario?

File: pkg/controller/core/clusterqueue_controller.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/core/clusterqueue_controller.go]: done

**Comment by PBundyra** [comment]
/hold
/lgtm
We agreed with @mimowo on running integration tests several dozen times to ensure they're not flaky. Thanks for the contriubtion

File: pkg/controller/core/core.go (hunk 5 above)
Comment (tenzen-y) [reply pkg/controller/core/core.go:86]: Uhm, I see. In that case, I think that we should restructure the package for the TAS so that we can distinguish the responsibility between each component.

But based on the release schedule, I'm ok with this implementation for now.

**Comment by mimowo** [comment]
> We agreed with @mimowo on running integration tests several dozen times to ensure they're not flaky. Thanks for the contriubtion

That's right, I have done over 50 repeats already of the two newly added integration tests and they passed every time, using the command with `--race`:
```
GINKGO_ARGS="--timeout=5h --repeat=100 --race" INTEGRATION_NPROCS=1 INTEGRATION_TARGET=./test/integration/tas/ make test-integration
```

**Comment by tenzen-y** [comment]
@mimowo Could you manually create the cherry-pick PR against release-0.9?

**Comment by mimowo** [comment]
Yes, I will try

**Comment by mimowo** [comment]
Prepared: https://github.com/kubernetes-sigs/kueue/pull/3819
