### PR TITLE
fix webhook registration when API is available

### LINKED ISSUE #4546: Deferred setup of controller/webhook for a Kind cannot remove noop webhook
**What happened**:
I deployed Kueue.
I waited until Kueue was running and deployed the AppWrapper controller.
The job framework's `waitForAPI` mechanisms triggered correctly because AppWrapper was now available on the API server.
However, the controller-runtime does not support _updating_ an already installed webhook.  It instead silently ignores the attempt to install a new webhook on an already covered endpoint.
As a result, Kueue's  defaulting/validating BaseWebhook were not  actually installed for the AppWrapper kind (because the noopWebhook has been installed). 
This resulted in failure to default `Suspend`.

**What you expected to happen**:

Kueue should correctly handle a Kind being added to the cluster after Kueue is installed without requiring a restart of the Kueue controller-manager.

**How to reproduce it (as minimally and precisely as possible)**:

See above description.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):  v0.11.0-devel-320-gc663d0b0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by dgrove-oss**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
Fixes webhook registration bug for enabled frameworks whose APIs were not available when the Kueue controller started.
#### Which issue(s) this PR fixes:

Fixes #4546 

#### Does this PR introduce a user-facing change?

```release-note
Fixes a bug that would result in default values not being properly set on creation for enabled integrations whose API was not available when the Kueue controller started.
```

### CODE REVIEW

File: pkg/controller/jobframework/setup.go [hunk 1]
```diff
@@ -92,6 +92,11 @@ func (m *integrationManager) setupControllers(ctx context.Context, mgr ctrl.Mana
 						log.Error(err, "Failed to setup controller and webhook for job framework")
 					}
 				})
+				// Webhook must be registered now.
+				// The controller-runtime silently ignores attempts to add a webhook to an already registered endpoint.
+				if err := cb.SetupWebhook(mgr, opts...); err != nil {
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:97]: For a while I was thinking if it is safe to register a webhook if the CRD is not installed yet, and I think it should be safe, because in this case no requests will be sent to the webhook. Thanks!

File: pkg/controller/jobframework/setup.go [hunk 2]
```diff
@@ -92,6 +92,11 @@ func (m *integrationManager) setupControllers(ctx context.Context, mgr ctrl.Mana
 						log.Error(err, "Failed to setup controller and webhook for job framework")
 					}
 				})
+				// Webhook must be registered now.
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:95]: Actually, maybe it is safer to register before spinning the waitForAPI goroutine to avoid the two calls to `SetupWebhook` racing. I bet there is a mutex inside the controller-runtime, but it seems just safer. wdyt?

Comment (mimowo) [inline pkg/controller/jobframework/setup.go:95]: Please also adjust the logging, the previous `logger.Info("No matching API in the server for job framework, skipped setup of controller and webhook")` is no longer true.

**Review by mimowo — COMMENTED** [review]
Overall LGTM, thanks for testing and finding the bug. I think we should cherry-pick this. 

Aside from nit comments I'm thinking how we could test it to avoid regressions (could be a follow up PR/ Issue depending on complexity). 

We already have integration tests using [envtest.InstallCRDs](https://github.com/kubernetes-sigs/kueue/blob/6e8d4143e4969d424597d9a30c7672f6ea1210fc/test/integration/singlecluster/controller/jobframework/setup/setup_controllers_test.go#L106).

I believe we could add an analogous test using BaseWebhook for AppWrapper or kubeflow using [envtest.WebhookInstallOptions.Install](https://github.com/kubernetes-sigs/kueue/blob/6e8d4143e4969d424597d9a30c7672f6ea1210fc/test/integration/singlecluster/controller/jobframework/setup/setup_controllers_test.go#L106). 

Let me know what you think about automated testing of this. For now, I'm ok to resort to manual testing, and open issue. OTOH, if you want to add the automated test in this PR then don't hesitate :) . cc @tenzen-y

File: pkg/controller/jobframework/setup.go (hunk 2 above)
Comment (dgrove-oss) [reply pkg/controller/jobframework/setup.go]: Done.

Comment (dgrove-oss) [reply pkg/controller/jobframework/setup.go]: Done

**Comment by dgrove-oss** [comment]
I think we should have a test case for this, but we should defer to a followup PR.  I think all we need is a test with manageJobsWithoutQueue name where we start the Kueue manager and then install the operator for any built-in integration that isn't part of core Kubernetes.

**Comment by mimowo** [comment]
> I think we should have a test case for this, but we should defer to a followup PR. 

Thanks, please do, if you have other priorities, then create a follow up issue.
