### PR TITLE
[ProvReq] Fix ProvReq not recreating after second failed attempt 

### LINKED ISSUE #6323: [ProvReq] Kueue doesnt recreate a ProvReq after second failed attempt
**What happened**:
When a ProvisioningRequest fails for the second time, Kueue doesnt recreate the ProvisioningRequest even with a large BackoffLimit

**What you expected to happen**:
Kueue to create a ProvisioningRequest as many times as configured

**How to reproduce it (as minimally and precisely as possible)**:
Is it reproduced by an integration test in the PR #6322  

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #6323 

#### Special notes for your reviewer:
It seems like Workload patch status's `.requeuState` was never copied properly so the provisioning controller always assumed the workload was never requeued before  

#### Does this PR introduce a user-facing change?

```release-note
ProvisioningRequest: Fix a bug that Kueue didn't recreate the next ProvisioningRequest instance after the
second (and consecutive) failed attempt.
```

### CODE REVIEW

File: pkg/controller/admissionchecks/provisioning/controller.go [hunk 1]
```diff
@@ -499,6 +499,7 @@ func (c *Controller) syncCheckStates(
 	wlInfo.update(wl, c.clock)
 	checksMap := slices.ToRefMap(wl.Status.AdmissionChecks, func(c *kueue.AdmissionCheckState) kueue.AdmissionCheckReference { return c.Name })
 	wlPatch := workload.BaseSSAWorkload(wl, true)
+	wlPatch.Status.RequeueState = wl.Status.RequeueState.DeepCopy()
```
Comment (mimowo) [inline pkg/controller/admissionchecks/provisioning/controller.go:502]: I'm surprised this does not panic if `wl.Status.RequeueState` is a nil. What prevents the panic here?

Comment (PBundyra) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: If it's nil than copy of it would be also nil

Comment (mimowo) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: sgtm, indeed 

```
// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequeueState.
func (in *RequeueState) DeepCopy() *RequeueState {
	if in == nil {
		return nil
	}
	out := new(RequeueState)
	in.DeepCopyInto(out)
	return out
}
```

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
 ProvisioningRequest: Fix a bug that Kueue recreates a ProvisioningRequest after the second failed attempt 
```

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 2]
```diff
@@ -1300,6 +1300,189 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
...
+				PodSets(
+					kueue.PodSetAssignment{
+						Name: "ps1",
+						Flavors: map[corev1.ResourceName]kueue.ResourceFlavorReference{
+							corev1.ResourceCPU: kueue.ResourceFlavorReference(rf.Name),
+						},
+						ResourceUsage: map[corev1.ResourceName]resource.Quantity{
+							corev1.ResourceCPU: resource.MustParse("3"),
+						},
+						Count: ptr.To[int32](3),
```
Comment (tenzen-y) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1363]: Could we use these wrapper functions?
https://github.com/kubernetes-sigs/kueue/blob/main/pkg/util/testing/wrappers.go#L625-L669

**Review by tenzen-y — COMMENTED** [review]
Thank you
Basically, LGTM

File: pkg/controller/admissionchecks/provisioning/controller.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: This makes sense. 

The root cause is probably that the ProvReq logic used wlPatch to reason about the retries, but it was not initialized, so it was behaving as it was first try.

Now, this may not be the only issue with the previous code, suppose:
1. ProvisioningRequest is set to Retry and RequeueState is initialized - ProvReq takes ownership of the field
2. on the second attempt the ProvisioningRequest wants to transition Pending -> Ready, and does not need to bump RequeueState as it is successful.  
Issue: Now, because it owns the field (step 1), and does not update it, it could clear the field on setting the AC to Ready. This may not be desired as other ACs may still be pending.

I'm not totally sure this could happen (just static code analysis). We could exercise this in a follow up integration test, if you support there was a bug indeed, so that we could prevent regression in the future.

Still, since we use SSA for ProvReq, we need to send each time every field the controller may own, so this initialization makes perfect sense to me.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 2 above)
Comment (PBundyra) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1363]: Yes absolutely. However I would like to do it in a follow-up and also clean up all the tests in this file

**Comment by mimowo** [comment]
/release-note-edit
```release-note
ProvisioningRequest: Fix a bug that Kueue didn't recreate the next ProvisioningRequest instance after the
second (and consecutive) failed attempt.
```

File: pkg/controller/admissionchecks/provisioning/controller.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: @PBundyra can you leave it unresolved? I think it actually contains useful discussion for future, just in case.

Comment (PBundyra) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: > Issue: Now, because it owns the field (step 1), and does not update it, it could clear the field on setting the AC to Ready. This may not be desired as other ACs may still be pending.

Why would it clear the field, if now it's part of the patch whether the controller changes it or not?

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 2 above)
Comment (tenzen-y) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1363]: Oh, I see.
As I can see other test cases in this file, those directly define the PodSetAssignment object.

I'm ok with this as a follow-up.

**Comment by tenzen-y** [comment]
Thanks!
/lgtm
/approve

/hold

for @mimowo

File: pkg/controller/admissionchecks/provisioning/controller.go (hunk 1 above)
Comment (PBundyra) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: Oh, did you mean the previous code had an issue and this doesnt?

Comment (mimowo) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: > Oh, did you mean the previous code had an issue and this doesnt?

Yes. I'm not totally sure the previous had it, because maybe just before sending the request we would still set the status.RequeueState, in that case no bug, just tricky code. 

However, the new code makes it clear that we want to send the field in SSA. So, this way we are sure the field is not dropped if ProvReq does not want to update it.

Comment (PBundyra) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: I modified locally one the test that fails the first ProvReq and the second ProvReq succeeds and I actually did not observe the RequeueState was reset with the previous code

Comment (mimowo) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: On the old code? Yeah, possible, as mentioned above, it was just not clear we would send it (maybe it is set somewhere inside the helper functions).

**Comment by mimowo** [comment]
/unhold
Thank you, the fix makes sense to me!
/cherrypick release-0.13
/cherrypick release-0.12

File: pkg/controller/admissionchecks/provisioning/controller.go (hunk 1 above)
Comment (PBundyra) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: I think you're right that the provisioning controller should always set it if it had the ownership for the whole time. But the workload controller also takes the ownership of that field when it requeues the workload after time surpassed `.requeueAfter`

Comment (mimowo) [reply pkg/controller/admissionchecks/provisioning/controller.go:502]: Ah yes, in that case we may be sending it sometimes unnecessarily grabing the ownership back even if we don't aim to update (for example ProvReq just wants to set Pending -> Ready).

In any case, the new code is easier to reason about, so fine. SSA is complicated which is another reason for https://github.com/kubernetes-sigs/kueue/issues/6158.

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go (hunk 2 above)
Comment (PBundyra) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:1363]: #6331
