### PR TITLE
test/util: wait for the kueue controller to acquire the leader lease

### LINKED ISSUE #5358: [flaky test] WaitForPodsReady has a tiny Timeout and no RecoveryTimeout should evict and requeue workload when pods readiness timeout is surpassed
/kind flake

**What happened**:

failure on unrelated branch https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5357/pull-kueue-test-e2e-customconfigs-main/1927021441526534144

**What you expected to happen**:

no failure

**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:
```
End To End Custom Configs handling Suite: kindest/node:v1.32.3: [It] ManageJobsWithoutQueueName when manageJobsWithoutQueueName=true and LocalQueueDefaulting=false should suspend a job expand_less	25s
{Expected success, but got an error:
    <*errors.StatusError | 0xc0008a26e0>: 
    resourceflavors.kueue.x-k8s.io "default" already exists
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "resourceflavors.kueue.x-k8s.io \"default\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "default",
                Group: "kueue.x-k8s.io",
                Kind: "resourceflavors",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc0008a26e0>: 
    resourceflavors.kueue.x-k8s.io "default" already exists
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "resourceflavors.kueue.x-k8s.io \"default\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "default",
                Group: "kueue.x-k8s.io",
                Kind: "resourceflavors",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
In [BeforeEach] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/customconfigs/managejobswithoutqueuename_test.go:72 @ 05/26/25 15:27:15.647
```

### PR DESCRIPTION
**Pull request by sohankunkerkar**
This change adds a `WaitForLeaderElection` helper that waits for the leader lease to be renewed after the restart start time. This ensures tests don't proceed until the new controller has actually acquired leadership.

After `UpdateKueueConfiguration` restarts the controller, `RestartKueueController` only waits for deployment availability (pods running) but not for leader election to complete.

#### What type of PR is this?
/kind flake

#### Which issue(s) this PR fixes:

Fixes #5358

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: test/util/e2e.go [hunk 1]
```diff
@@ -424,6 +427,20 @@ func WaitForKueueAvailabilityNoRestartCountCheck(ctx context.Context, k8sClient
 	waitForDeploymentAvailability(ctx, k8sClient, kcmKey)
 }
 
+// WaitForLeaderElection waits for the kueue controller to acquire the leader lease
+// after the given startTime to ensure the new controller has the lease.
+func WaitForLeaderElection(ctx context.Context, k8sClient client.Client, startTime time.Time) {
```
Comment (mimowo) [inline test/util/e2e.go:432]: Nice one, I think this is indeed why we had to wait 45s for some asserts
