### PR TITLE
TAS NodeHotSwap: fix the bug that allows workload to requeue by scheduler even if already deleted on TAS NodeHotSwap eviction

### LINKED ISSUE #8245: TAS NodeHotSwap: workload is requeued by scheduler even if already deleted
**What happened**:

TAS NodeHotSwap when tries to evict workload indefinitely if the workload is deleted in the meanwhile.

Each time after during the eviction attempt it sends a request to API server, slowing down scheduler.

**What you expected to happen**:

Scheduler should give up with the workload is deleted as we do in case of failed admission here: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/scheduler/scheduler.go#L667-L673

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix the bug that allows workload to requeue by scheduler even if already deleted on TAS NodeHotSwap eviction.

#### Which issue(s) this PR fixes:

Fixes #8245

#### Does this PR introduce a user-facing change?

```release-note
TAS NodeHotSwap: fixed the bug that allows workload to requeue by scheduler even if already deleted on TAS NodeHotSwap eviction.
```

### CODE REVIEW

File: pkg/scheduler/scheduler_tas_test.go [hunk 1]
```diff
@@ -589,6 +594,89 @@ func TestScheduleForTAS(t *testing.T) {
...
+							Domain(utiltestingapi.MakeTopologyDomainAssignment([]string{"x0"}, 1).Obj()).
+							Obj()).
+						Obj()).
+					Obj(),
+			},
+			wantEvents: []utiltesting.EventRecord{
+				utiltesting.MakeEventRecord("default", "foo", "SecondPassFailed", corev1.EventTypeWarning).
+					Message("couldn't assign flavors to pod set one: topology \"tas-three-level\" doesn't allow to fit any of 1 pod(s). Total nodes: 6; excluded: resource \"cpu\": 6").
+					Obj(),
+			},
```
Comment (mbobrovskyi) [inline pkg/scheduler/scheduler_tas_test.go:677]: /hold to fix this

File: pkg/scheduler/scheduler_tas_test.go [hunk 2]
```diff
@@ -589,6 +594,89 @@ func TestScheduleForTAS(t *testing.T) {
 					Obj(),
 			},
 		},
+		"workload with unhealthyNode annotation; second pass; preferred; no fit; FailFast (not found error on patch)": {
```
Comment (mimowo) [inline pkg/scheduler/scheduler_tas_test.go:596]: I'm not sure this test is really testing the essence of the problem. The important thing we want to check is that the workload was not requeued. 

I think it would be better to add an assert that the queue is empty. For example assert the number of pending workloads globally of for the selected queue.

For that we should skip calling requeueAndUpdate, as we do for admit: https://github.com/kubernetes-sigs/kueue/pull/8278/changes#diff-fb3d6b36d3cd727e1dd2353fb86c0aee0bfaae1c900e0f005ab913620021d551R663-R669

File: pkg/scheduler/scheduler.go [hunk 3]
```diff
@@ -589,14 +589,10 @@ func (s *Scheduler) getInitialAssignments(log logr.Logger, wl *workload.Info, sn
...
 	msg := fmt.Sprintf("Workload was evicted as there was no replacement for a failed node: %s", wl.Status.UnhealthyNodes[0].Name)
-	err := workload.Evict(
+	return workload.Evict(
 		ctx, s.client, s.recorder, wl, kueue.WorkloadEvictedDueToNodeFailures, msg, "", s.clock,
 		workload.EvictWithLooseOnApply(), workload.EvictWithRetryOnConflictForPatch(),
 	)
-	if err != nil {
-		return err
-	}
-	return nil
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go]: Let's avoid the drive-by changes which are distraction here and can make it more work to cherry-pick.

File: pkg/scheduler/scheduler.go [hunk 4]
```diff
@@ -249,7 +249,7 @@ func (s *Scheduler) schedule(ctx context.Context) wait.SpeedSignal {
 
 		if features.Enabled(features.TASFailedNodeReplacementFailFast) && workload.HasTopologyAssignmentWithUnhealthyNode(e.Obj) && mode != flavorassigner.Fit {
 			// evict workload we couldn't find the replacement for
-			if err := s.evictWorkloadAfterFailedTASReplacement(ctx, log, e.Obj.DeepCopy()); err != nil {
+			if err := s.evictWorkloadAfterFailedTASReplacement(ctx, log, e.Obj.DeepCopy()); client.IgnoreNotFound(err) != nil {
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go:252]: Nice, I think this should work indeed, because we will later skip calling requeueAndUpdate on e.status == evicted. Still, I'm not clear how the test is proving that.

File: pkg/scheduler/scheduler.go (hunk 3 above)
Comment (mbobrovskyi) [reply pkg/scheduler/scheduler.go]: Reverted and prepared cleanup https://github.com/kubernetes-sigs/kueue/pull/8285.

File: pkg/scheduler/scheduler_tas_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/scheduler/scheduler_tas_test.go:677]: /unhold

File: pkg/scheduler/scheduler_tas_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/scheduler/scheduler_tas_test.go:596]: > I think it would be better to add an assert that the queue is empty. For example assert the number of pending workloads globally of for the selected queue.

Actually we prevent it here https://github.com/kubernetes-sigs/kueue/blob/d24291fa6146c1ae11b401b60c1c11a78291eb53/pkg/scheduler/scheduler.go#L799-L803

Comment (mbobrovskyi) [reply pkg/scheduler/scheduler_tas_test.go:596]: In the unit test, we check for the SecondPassFailed event. If it exists, this error is not handled.

Comment (mimowo) [reply pkg/scheduler/scheduler_tas_test.go:596]: I see so when the workload is not Found, then we need to make sure it is not added to queues, and not added to secondPass - it is effectively forgotten.
However, I still don't understand how the tests prove that. 

So do you say after the first we still call requeueAndUpdate, but it is safe?

File: pkg/scheduler/scheduler.go (hunk 4 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go:252]: Regarding testing: I would much rather see in the testCase options a new param like `wantSecondPassQueueSize` and assert `wantSecondPassQueueSize==0` after the test cases.

File: pkg/scheduler/scheduler_tas_test.go (hunk 2 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler_tas_test.go:596]: The test proves it because if it was added, there would be an event emitted. Since there's no event in NotFound scenario, the workload is not added

Comment (mbobrovskyi) [reply pkg/scheduler/scheduler_tas_test.go:596]: > The test proves it because if it was added, there would be an event emitted. Since there's no event in NotFound scenario, the workload is not added

Yeah, that was my idea.

**Comment by mimowo** [comment]
Thank you 👍 

I have analyzed the code & tests and this is fixing the issue. I have also checked with debugger we indeed skip calling requeueAndUpdate. The tests are relying on side effect a bit, but I'm fine with that for now - they fail on the main branch.
/approve
/cherrypick release-0.15
/cherrypick release-0.14
