### PR TITLE
fix: invalid SSA patch due to field manager

### LINKED ISSUE #4934: scheduler.go uses ApplyAdmissionStatusPatch, fails on missing fields due to fieldManager
**What happened**:
We get an error like this during scheduler loop
```
{"level":"error","ts":"2025-04-09T12:39:42.128555256Z","logger":"scheduler","caller":"scheduler/scheduler.go:603","msg":"Could not update Workload status","schedulingCycle":1456,"error":"Workload.kueue.x-k8s.io \"jobset-xxxxxx" is invalid: [admissionChecks[0].lastTransitionTime: Required value, admissionChecks[0].message: Required value, admissionChecks[0].state: Required value, <nil>: Invalid value: \"null\": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]","stacktrace":"sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).requeueAndUpdate\n\t/workspace/pkg/scheduler/scheduler.go:603\nsigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).schedule\n\t/workspace/pkg/scheduler/scheduler.go:301\nsigs.k8s.io/kueue/pkg/util/wait.untilWithBackoff.func1\n\t/workspace/pkg/util/wait/backoff.go:43\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227\nsigs.k8s.io/kueue/pkg/util/wait.untilWithBackoff\n\t/workspace/pkg/util/wait/backoff.go:42\nsigs.k8s.io/kueue/pkg/util/wait.UntilWithBackoff\n\t/workspace/pkg/util/wait/backoff.go:34"}
```

This code manually constructs the patch rather than using the existing helper which correctly would patch admission checks and avoid the error https://github.com/kubernetes-sigs/kueue/blob/8dabaab58c4ede8adbddbee9053f2247ec9ec97e/pkg/scheduler/scheduler.go#L653-L659

the error is due to the `kueue-admission` field manager submitting an impartial patch for fields it is tracked as owner for. curiously this seems to force a failure rather than remove the field owner? I am able to provide a minimal repro of this but it requires custom ACC checks. it's possible it fails the update because there are multiple field owners (the ACC controller as well as kueue)? 

note: this is difficult to unit test with a fake client, as kueue currently uses this workaround due to fake client not fully supporting SSA https://github.com/kubernetes-sigs/kueue/blob/b6193e1932837d6d256c44257c1e1ab1a30104e3/pkg/scheduler/scheduler_test.go#L4068-L4073

the comment on the SSA helper hints at the issue https://github.com/kubernetes-sigs/kueue/blob/b6193e1932837d6d256c44257c1e1ab1a30104e3/pkg/util/testing/client.go#L148-L153

this is partly expected due to https://github.com/kubernetes-sigs/controller-runtime/issues/2341 // https://github.com/kubernetes/kubernetes/issues/115598#issuecomment-2210942918

however this leads to failed updates due to the field manager behavior, see the original error

**What you expected to happen**:

No error during patch, seems like `ApplyAdmissionStatus` already does the correct behavior, probably should just use that?

**How to reproduce it (as minimally and precisely as possible)**:

Create a jobset with ACC checks, ensure it is in a state that does not get nominated for some reason but attempts scheduling, it should hit this code path. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.29.12 and others (n/a)
- Kueue version (use `git describe --tags --dirty --always`): v0.10.4
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by alexeldeib**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix invalid SSA patch due to field manager (apparently)

#### Which issue(s) this PR fixes:

Fixes #4934

#### Special notes for your reviewer:

snipped from #4934 
> note: this is difficult to unit test with a fake client, as kueue currently uses this workaround due to fake client not fully supporting SSA
> the comment on the SSA helper hints at the issue
> this is partly expected due to https://github.com/kubernetes-sigs/controller-runtime/issues/2341 // https://github.com/kubernetes/kubernetes/issues/115598#issuecomment-2210942918
> however this leads to failed updates due to the field manager behavior, see the original error

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug which caused Kueue's Scheduler to build invalid SSA patch in some scenarios when  using
admission checks. This patch would be rejected with the following error message: 
Workload.kueue.x-k8s.io "job-xxxxxx" is invalid: [admissionChecks[0].lastTransitionTime: Required value
```

### CODE REVIEW

**Comment by alexeldeib** [comment]
not sure the best way to test this given the unit test issue. an integration test that does admit -> preempt might work but the quota will get reset anyway so not sure what you could assert on via integration tests for validation

other cases assert it doesn't return an error, which don't work for SSA behavior different from the helper 🙃

**Comment by mimowo** [comment]
cc @PBundyra who the most recently touched the code. I will probably book some time next week to check it too.

**Comment by alexeldeib** [comment]
hmmmMMM the integration test seems like hits a potentially legitimate data race? fun

```
Scheduler when using hierarchical cohorts preempts workloads to enforce fair share
/home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:330
  Captured StdOut/StdErr Output >>
  ==================
  WARNING: DATA RACE
  Read at 0x00c000f73cd0 by goroutine 517:
    k8s.io/apimachinery/pkg/api/meta.IsStatusConditionPresentAndEqual()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/k8s.io/apimachinery/pkg/api/meta/conditions.go:113 +0xce
    k8s.io/apimachinery/pkg/api/meta.IsStatusConditionFalse()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/k8s.io/apimachinery/pkg/api/meta/conditions.go:108 +0x7c
    sigs.k8s.io/kueue/pkg/queue.(*ClusterQueue).backoffWaitingTimeExpired()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/cluster_queue.go:177 +0x37
    sigs.k8s.io/kueue/pkg/queue.(*ClusterQueue).QueueInadmissibleWorkloads()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/cluster_queue.go:275 +0x464
    sigs.k8s.io/kueue/pkg/queue.requeueWorkloadsCohortSubtree()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/manager.go:557 +0x2c8
    sigs.k8s.io/kueue/pkg/queue.requeueWorkloadsCohortSubtree()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/manager.go:560 +0x54f
    sigs.k8s.io/kueue/pkg/queue.(*Manager).requeueWorkloadsCohort()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/manager.go:551 +0x424
    sigs.k8s.io/kueue/pkg/queue.(*Manager).AddOrUpdateCohort()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/manager.go:146 +0x1dd
    sigs.k8s.io/kueue/pkg/controller/core.(*CohortReconciler).Reconcile()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/controller/core/cohort_controller.go:151 +0x48d
    sigs.k8s.io/kueue/pkg/controller/core.(*leaderAwareReconciler).Reconcile()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/controller/core/leader_aware_reconciler.go:77 +0x23c
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Reconcile()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119 +0x1bd
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).reconcileHandler()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:334 +0x52f
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).processNextWorkItem()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:294 +0x3b2
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[go.shape.struct { k8s.io/apimachinery/pkg/types.NamespacedName }]).Start.func2.2()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:255 +0xe4
  Previous write at 0x00c000f73cd0 by goroutine 259:
    k8s.io/apimachinery/pkg/api/meta.SetStatusCondition()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/k8s.io/apimachinery/pkg/api/meta/conditions.go:59 +0x4e5
    sigs.k8s.io/kueue/pkg/workload.UnsetQuotaReservationWithCondition()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/workload/workload.go:500 +0x15d
    sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).requeueAndUpdate()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/scheduler/scheduler.go:654 +0xbab
    sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).schedule()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/scheduler/scheduler.go:299 +0x1dcf
    sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).schedule-fm()
        <autogenerated>:1 +0x47
    sigs.k8s.io/kueue/pkg/util/wait.untilWithBackoff.func1()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/util/wait/backoff.go:43 +0x58
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x41
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
        /home/prow/go/src/sigs.k8s.io/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xc4
    sigs.k8s.io/kueue/pkg/util/wait.untilWithBackoff()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/util/wait/backoff.go:42 +0x144
    sigs.k8s.io/kueue/pkg/util/wait.UntilWithBackoff()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/util/wait/backoff.go:34 +0xc9
    sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).Start.gowrap1()
        /home/prow/go/src/sigs.k8s.io/kueue/pkg/scheduler/scheduler.go:146 +0x4f
```

might need to poke at that more

**Comment by alexeldeib** [comment]
I guess there was a reason that code path did it differently since the quota unreservation on the base object creates the data race -- this should have the same effect

I will also bake a new image and try that in our infra next week to sanity test

**Comment by PBundyra** [comment]
Could you please confirm that the issue is caused by the invalid SSA, as it lacks `.admissioChecks` field, and not because the field has multiple owners?

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -653,6 +653,7 @@ func (s *Scheduler) requeueAndUpdate(ctx context.Context, e entry) {
 	if e.status == notNominated || e.status == skipped {
 		patch := workload.BaseSSAWorkload(e.Obj)
 		workload.AdmissionStatusPatch(e.Obj, patch, true)
+		workload.AdmissionChecksStatusPatch(e.Obj, patch, s.clock)
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go:656]: This looks sensible, but it would be great to repro the issue integration tests (we could probably use them to simulate the external admission check). cc @PBundyra

**Comment by alexeldeib** [comment]
> Could you please confirm that the issue is caused by the invalid SSA, as it lacks .admissioChecks field, and not because the field has multiple owners?

at least in our situation, it's both -- kueue and a custom ACC check both want to be field managers on the admission check. it seems like the correct fix is for kueue to issue the full intent in the patch? I am confused how a field owner would remove itself in this scenario though

**Comment by mimowo** [comment]
Ok, I looked a bit more (but haven't got time to confirm anything with an actual experiment). I believe that indeed we have a bug in Kueue, and there is a way to repro with integration tests.

First of all, IIUC, there are never two owners of a field in SSA, we can have only one owner - either Kueue or the external controller. So, generally the state of admission checks is under ownership of external controllers, but sometimes Kueue takes them over. When the external admission checks are taken over by Kueue I think Kueue should keep sending them, otherwise they would be deleted by API server (which I think is what happens here). I think API server deletes all fields owned by Kueue which haven't been sent. Otherwise, the intent of the actor as Kueue would not be clear - is not sending the owned field "I don't want to change it" or "I want to delete it".

So, I believe the fix in the current form is correct, but it would be great to have a repro. To repro I see that Kueue takes over the admission checks in the preemption path, ie. [here](https://github.com/kubernetes-sigs/kueue/blob/ebe37a32cd69f1e2d4215562716f35751ac03a4c/pkg/scheduler/preemption/preemption.go#L262). Not sure this is exactly your case. Then, we need to somehow make Kueue step into [here](https://github.com/kubernetes-sigs/kueue/blob/ebe37a32cd69f1e2d4215562716f35751ac03a4c/pkg/scheduler/scheduler.go#L654). This can be done if the workload is "skipped". It could be considered skipped if there was another workload in the cohort admitted before it, which took all the quota, see [here](https://github.com/kubernetes-sigs/kueue/blob/ebe37a32cd69f1e2d4215562716f35751ac03a4c/pkg/scheduler/scheduler.go#L254). The scenario is a bit involving to repro, let us know @alexeldeib if you want to give it a try.

**Comment by alexeldeib** [comment]
> IIUC, there are never two owners of a field in SSA

Is this true? I'm not an SSA pro admittedly. Here is the output on a live object -- it certainly looks like field ownership for the admission checks is simultaneously tracked by 3 owners: kueue, kueue-admission, and the custom ACC check.



```
# snipped for clarity
  managedFields:
  - apiVersion: kueue.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:admissionChecks:
          k:{"name":"check1"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:name: {}
            f:state: {}
          k:{"name":"check2"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:name: {}
            f:state: {}
        ...
    manager: custom-kueue-admission-check # edited
    operation: Apply
    subresource: status
    time: "2025-04-14T08:45:11Z"
  - apiVersion: kueue.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
...
        f:admissionChecks:
          k:{"name":"check1"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:name: {}
            f:state: {}
          k:{"name":"check2"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:name: {}
            f:state: {}
...
    manager: kueue-admission
    operation: Apply
    subresource: status
    time: "2025-04-14T08:45:11Z"
  - apiVersion: kueue.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:admissionChecks:
          .: {}
          k:{"name":"check1"}:
            .: {}
            f:name: {}
          k:{"name":"check2"}:
            .: {}
            f:name: {}
    manager: kueue
    operation: Update
    subresource: status
    time: "2025-04-14T08:15:10Z"
```

The k8s docs say this
> When two or more appliers set a field to the same value, they share ownership of that field. Any subsequent attempt to change the value of the shared field, by any of the appliers, results in a conflict. Shared field owners may give up ownership of a field by making a Server-Side Apply patch request that doesn't include that field

Weird in that case not sending the field triggers the bug...I was able to reproduce that by logging the patch, and admission checks is entirely unset.

re: the repro -- that makes sense, I need to try a repro and see how it looks to make the changes. not sure how hard that is yet but can try :D

**Comment by mimowo** [comment]
> Is this true? I'm not an SSA pro admittedly. Here is the output on a live object 

Actually, I wasn't sure about that statement. Indeed, it seems like a field may have multiple owners with SSA. Thank you for clarifying. 

Still, it seems, that once we own a field (such as workload's admissionChecks), then we need to keep sending them, otherwise the API server would assume we want to remove them.

**Comment by mimowo** [comment]
@alexeldeib let us know if you need some help with the integration test. The code fix itself lgtm.

**Comment by alexeldeib** [comment]
that works but it seems to race with workload controller on the update so it gets requeued in another scheduler loop
-_-

our prod queues tend to be fairly deep, maybe I can get away with creating 3+ workloads in diff queues -> wait for initial reconciliation to settle with ready checks -> finish blocking job in cohort -> 1 job gets scheduled, rest get skipped/reconciled by workload controller -> finish blocking job

but maybe that has the same issue...

confused why I can't hit it in integration tests, I also tried double patching field managers with multiple owners, something is funny!

**Comment by alexeldeib** [comment]
pushed an example of what i'm trying, this works but is not 100% reliably, trying to narrow down why

**Comment by mimowo** [comment]
I looked this morning into the integration test. Let's consider the following scenario:
0. setup: we have 2 CQs A and B in cohort "cohort", and A has an admission check (both have X nominal and no borrowing limit, so 2X capacity total)
1. we have workload wl1 (size 2X, priority 1) and QuotaReserve and set admission check to Ready, wait for Admitted condition by workload_controller
2. create wl2 (size 2X, priority 2) in CQ B which stays pending
3. create wl3 (size X, priority 3). wl3 preempts wl1, and both wl1 and wl2 are pending. wl1 has [admission checks reset](https://github.com/kubernetes-sigs/kueue/blob/3279d9c05817e465229fac6bdc64250c890ea7dd/pkg/scheduler/preemption/preemption.go#L262)
4. finish wl3, releasing quota so that wl2 and wl1 are considered in the same scheduling cycle, and both are marked "fit". Once wl2 (as higher priority) is admitted, wl1 stays pending and is "skipped". This should make the wl1 stepping into this [problematic code](https://github.com/kubernetes-sigs/kueue/blob/3279d9c05817e465229fac6bdc64250c890ea7dd/pkg/scheduler/scheduler.go#L659). So, in test we could await for the specific reason and message. 

If the problem is with inadmissibleWorkloads queue, I think we could use StrictFIFO queues which retry scheduling on every cycle.

Let me know if I'm missing something (haven't actually ran any experiments). I think if using BestEffortFIFO the issue might be indeed tricky to repro.

Another approach to the PR I would be ok accepting is to just wrap the [3 lines](https://github.com/kubernetes-sigs/kueue/blob/3279d9c05817e465229fac6bdc64250c890ea7dd/pkg/workload/workload.go#L712-L714):

```golang
	wlCopy := BaseSSAWorkload(w)
	AdmissionStatusPatch(w, wlCopy, strict)
	AdmissionChecksStatusPatch(w, wlCopy, clk)
```
into `PrepareAdmissionPatch`. Then, call it from both places (workload.go and scheduler.go). cc @PBundyra

**Comment by alexeldeib** [comment]
thanks for taking a look!

what you described is what I started with but made changes after struggling to repro precisely :) it was enough to simply have 2 queues to get wl1 admitted in q1 and then wl2 triggers the issue with q2, but then I started finding more issues (https://github.com/kubernetes-sigs/kueue/issues/5058 + https://github.com/kubernetes-sigs/kueue/issues/5061)

>If the problem is with inadmissibleWorkloads queue, I think we could use StrictFIFO queues which retry scheduling on every cycle.
> Let me know if I'm missing something (haven't actually ran any experiments). I think if using BestEffortFIFO the issue might be indeed tricky to repro.

good idea, but...is that...expected? I opened #5061 because it seems like a distinct issue, but it also seems wrong to me a workload can stuck indefinitely with best effort vs strict fifo? shouldn't it be requeued _eventually_, even if no other objects are created/deleted/reconciled?

I can remove the changes I made to requeue inadmissible workloads in workload_controller while testing, not sure if those have other negative effects (well, lot of CI is failing 😆 need to fix that), but wasn't sure if this was intended behavior or not

**Comment by mimowo** [comment]
Workload should never get stuck indefinitely, if it does then it is a bug. However, I would suggest to tackle the issues separately for the ease of reviewing. I haven't yet had the capacity to look deeply into that workload stuck issue, but it is very weird why this never happens in our tests, seems like something which should happen time to time if the conflict was the only culprit.

If indeed there is an issue, then we could fix either by detecting a conflict or periodic last resort schedules. Probably detecting a conflict is my preference but I guess ultimately we need both strategies.

**Comment by alexeldeib** [comment]
> I would suggest to tackle the issues separately for the ease of reviewing

will do, from my testing so far I expect strict fifo will requeue more frequently like you said and repro reliably

> it is very weird why this never happens in our tests

I agree, I will try to isolate it after this PR. just whittling away things we hit in practice. we rely heavily on ACC, I suspect [this codepath](https://github.com/kubernetes-sigs/kueue/blob/3279d9c05817e465229fac6bdc64250c890ea7dd/pkg/scheduler/scheduler.go#L355-L356) is hit rarely in tests outside provisioning check ACC. all other reasons to skip nomination avoid this behavior:
- CQ not existing is terminal, CQ inactive needs to wait for CQ update -> CQ reconcile also requeues inadmissible workloads automatically
- Workload validation failure typically require user action, so they are either terminal for the workload, or you change the limit range config and the workload fails a different way -> Workload create will also allow correct behavior if it's admitted on next pass.
- ns selector match is terminal

**Comment by alexeldeib** [comment]
*sigh*

I might put this aside for now and fix some of the other stuff I'm finding.

I was able to reliably reproduce the error a few times earlier, but after my latest rebase, I can't repro at all :D I don't see how any recent commits would it, but not sure what i'm missing. I manually ran a minimal repro outside kueue integration tests and verified the issue should exist.

I tried both approaches you mentioned, neither worked for me with best effort FIFO, with strict FIFO the requeuing seems to spam it into a state where it eventually gets the condition set.

> this will deactivate wl1, and thus evict and reset the AdmissionChecks. Now bot wl1 and wl2 are waiting
resume CQ A
> Once wl2 (as higher priority) is admitted, wl1 stays pending and is "skipped". This should make the wl1 stepping into the problematic code

wl1 gets stuck halfway pre-empted -- that seems like yet another different problem:
```
  admissionChecks:
  - lastTransitionTime: "2025-04-23T17:59:08Z"
    message: ""
    name: check1
    state: Pending
  - lastTransitionTime: "2025-04-23T17:59:08Z"
    message: ""
    name: check2
    state: Pending
  conditions:
  - lastTransitionTime: "2025-04-23T17:59:08Z"
    message: Quota reserved in ClusterQueue admission-preemption-cq
    observedGeneration: 1
    reason: QuotaReserved
    status: "True"
    type: QuotaReserved
  - lastTransitionTime: "2025-04-23T17:59:09Z"
    message: 'Preempted to accommodate a workload (UID: 11c66ebd-78f8-488d-997c-f76ce7046c94,
      JobUID: UNKNOWN) due to prioritization in the ClusterQueue'
    observedGeneration: 1
    reason: Preempted
    status: "True"
    type: Evicted
  - lastTransitionTime: "2025-04-23T17:59:09Z"
    message: 'Preempted to accommodate a workload (UID: 11c66ebd-78f8-488d-997c-f76ce7046c94,
      JobUID: UNKNOWN) due to prioritization in the ClusterQueue'
    reason: InClusterQueue
    status: "True"
    type: Preempted
```

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
/cherry-pick release-0.11 release-0.10
Kueue should always submit updates to all fields it owns, admissionCheck state in particular, otherwise, the api-server tries to delete the fields.

However, I see covering this particular patch by scheduler is tricky as shown by all the experiments. 

Still, this change does not break any existing tests, and it was manually tested to eliminate the issue with the invalid patch, so I'm ok to go with the commonizing of the code.

/hold
To leave the voice to @PBundyra who may also have some ideas about alternatives.

**Comment by PBundyra** [comment]
/hold cancel
Thank you @alexeldeib for detailed testing, I'm unholding this so we have a fix and can proceed with discussing other issues. > I was able to reliably reproduce the error a few times earlier, but after my latest rebase, I can't repro at all :D
Could you describe a scenario you used to reproduce earlier?
