### PR TITLE
TAS: Fix incorrect topology assignments under the situations where topology has insufficient allocatable Pods count

### LINKED ISSUE #4270: TAS: Incorrect Topology Assignment when topology allocatable Pods count are less than number of requested Pods
**What happened**:
TAS assigned topologies with nodes without enough allocatable pods count to TAS Workloads.
After that, the kube-scheduler failed to schedule pods to TAS assignment nodes.

**What you expected to happen**:
TAS considers allocatable pods count in the topologies.

**How to reproduce it (as minimally and precisely as possible)**:
You can see the actual situation in fixing PR (#4271) test cases, `workload does not get scheduled as the node capacity (.status.allocatable['pods']) is already used by non-TAS and TAS workloads` in `pkg/scheduler/scheduler_test.go`.

**Anything else we need to know?**:
The nodes have a limitation of allocatable pods count in `.status.allocatable["pods"]`, which is defaults are 110, and can be replaced by kubelet configurations.
However, the current TAS implementation has never considered the number of allocatable pods since `TASFlavorSnapshot` does not record how many [TAS|NonTAS] pods are scheduled to nodes in [`addNonTASUsage`](https://github.com/kubernetes-sigs/kueue/blob/5b426e99efffc546c3b3bcd4d5dbdcfa07e922fb/pkg/cache/tas_flavor_snapshot.go#L207-L212) and [`addTASUsage`](https://github.com/kubernetes-sigs/kueue/blob/5b426e99efffc546c3b3bcd4d5dbdcfa07e922fb/pkg/cache/tas_flavor_snapshot.go#L214-L226).

So, `TASFlavorSnapshot` consider allocatable Pod counts only from computing resources like CPU and Memory in the following: https://github.com/kubernetes-sigs/kueue/blob/5b426e99efffc546c3b3bcd4d5dbdcfa07e922fb/pkg/cache/tas_flavor_snapshot.go#L511

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
As I described in #4270, TAS accidentally assigns topologies with nodes without enough allocatable pods count.

#### Which issue(s) this PR fixes:

Fixes #4270

#### Does this PR introduce a user-facing change?

```release-note
TAS: Fix a bug that incorrect topologies are assigned to Workloads when topology has insufficient allocatable Pods count
```

### CODE REVIEW

File: pkg/cache/tas_cache_test.go [hunk 1]
```diff
@@ -1318,10 +1353,43 @@ func TestFindTopologyAssignment(t *testing.T) {
...
+			},
+			count:                   1,
+			wantReason:              `topology "default" doesn't allow to fit any of 1 pod(s)`,
+			enableTASLeastAllocated: true,
+		},
 	}
 	for name, tc := range cases {
 		t.Run(name, func(t *testing.T) {
-			ctx := context.Background()
+			ctx, _ := utiltesting.ContextWithLog(t)
```
Comment (tenzen-y) [inline pkg/cache/tas_cache_test.go:1392]: This was added as we can easily debug something powered by logging.

**Comment by tenzen-y** [comment]
/hold
to prevent accidentally merging

File: pkg/cache/tas_flavor_snapshot.go [hunk 2]
```diff
@@ -223,6 +224,7 @@ func (s *TASFlavorSnapshot) addTASUsage(domainID utiltas.TopologyDomainID, usage
 		s.leaves[domainID].tasUsage = resources.Requests{}
 	}
 	s.leaves[domainID].tasUsage.Add(usage)
+	s.leaves[domainID].tasUsage.Add(resources.Requests{corev1.ResourcePods: 1})
```
Comment (mimowo) [inline pkg/cache/tas_flavor_snapshot.go:227]: I think this is not accurate. For task workloads the number of pods in a domain needs to be taken from the assignment. I think to propagate this information we need to adjust a couple of structures, probably starting from `TopologyDomainRequests`.

Another alternative is to just iterate over all pods, not just non-TAS, and then update the snapshot. It is much easier in practice, but would require as too cache all pods.

File: pkg/cache/tas_flavor_snapshot.go [hunk 3]
```diff
@@ -272,6 +274,7 @@ func (s *TASFlavorSnapshot) FindTopologyAssignmentsForFlavor(flavorTASRequests F
 		for _, domain := range assignment.Domains {
 			domainID := utiltas.DomainID(domain.Values)
 			assumedDomainUsage := tr.SinglePodRequests.Clone()
+			assumedDomainUsage.Add(resources.Requests{corev1.ResourcePods: 1})
```
Comment (mimowo) [inline pkg/cache/tas_flavor_snapshot.go:277]: This should use `domain.Count` instead rather than one, as this is the number of assigned pods in the currently considered TAS workload.

File: pkg/cache/tas_cache_test.go (hunk 1 above)
Comment (mimowo) [reply pkg/cache/tas_cache_test.go:1392]: Please split out to separate PR.

**Review by mimowo — COMMENTED** [review]
Thanks for working on it. I think in the current form it remains inaccurate (still better than it was) as the code accounts 1 pods for each TAS workload domain. This is not necessarily true since the domains may have more pods assigned.

I see two approaches to make this fully correct:
1. propagate the exact numbers via a couple of structures, based on assignment
2. account for all pods one-by-one. Currently we only do it for non-TAS pods, but the same way we could iterate over TAS pods.

I believe (2.) is easier from the code perspective, but I would be leaning to start with (1.) , as (2.) will require iterating over more pods.

File: pkg/cache/tas_cache_test.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/cache/tas_cache_test.go:1392]: SGTM

File: pkg/cache/tas_flavor_snapshot.go (hunk 3 above)
Comment (tenzen-y) [reply pkg/cache/tas_flavor_snapshot.go:277]: IIUC, the current calculation seems to be correct since we multiply `assumedDomainUsage × count` in the next line: `assumedDomainUsage.Mul(int64(domain.Count))`. Please let me know if my understanding is not correct.

File: pkg/cache/tas_flavor_snapshot.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/cache/tas_flavor_snapshot.go:227]: Oh, that sounds correct. I will refine the`TopologyDomainRequests` to store the pod count.
Thanks.

File: pkg/cache/tas_cache_test.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/cache/tas_cache_test.go]: This was extracted to https://github.com/kubernetes-sigs/kueue/pull/4274

File: pkg/cache/tas_flavor_snapshot.go (hunk 3 above)
Comment (mimowo) [reply pkg/cache/tas_flavor_snapshot.go:277]: Ah, you are right indeed! Thanks for pointing that out.

**Comment by mimowo** [comment]
/assign @PBundyra 
I did a quick pass to spot some gaps, but another pair of eyes would be great.

File: pkg/scheduler/scheduler_test.go [hunk 4]
```diff
@@ -4876,6 +4886,73 @@ func TestScheduleForTAS(t *testing.T) {
...
+					Queue("tas-main").
+					ReserveQuota(
+						utiltesting.MakeAdmission("tas-main", "one").
+							Assignment(corev1.ResourceCPU, "tas-default", "150m").
+							AssignmentPodCount(2).
+							TopologyAssignment(&kueue.TopologyAssignment{
+								Levels: utiltas.Levels(&defaultSingleLevelTopology),
+								Domains: []kueue.TopologyDomainAssignment{
+									{
+										Count: 2,
```
Comment (tenzen-y) [inline pkg/scheduler/scheduler_test.go:4929]: @mimowo Once I increase assigned count from 1 to 2, this case failed as you mentioned in the first PR review.
Thank you for the feedback.

```
=== RUN   TestScheduleForTAS
=== RUN   TestScheduleForTAS/workload_does_not_get_scheduled_as_the_node_capacity_(.status.allocatable['pods'])_is_already_used_by_non-TAS_and_TAS_workloads
    resources.go:128: "msg"="Failed adjusting requests for LimitRanges" "error"="List on GroupVersionKind /v1, Kind=LimitRange specifies selector on field spec.hasContainerType, but no index with name spec.hasContainerType has been registered for GroupVersionKind /v1, Kind=LimitRange"
    scheduler.go:482: "level"=2 "msg"="Workload assumed in the cache" "schedulingCycle"=1 "workload"={"name"="foo" "namespace"="default"} "clusterQueue"={"name"="tas-main"}
    scheduler.go:506: "level"=2 "msg"="Workload successfully admitted and assigned flavors" "schedulingCycle"=1 "workload"={"name"="foo" "namespace"="default"} "clusterQueue"={"name"="tas-main"} "assignments"=[{"name"="one" "flavors"={"cpu"="tas-default"} "resourceUsage"={"cpu"={"Format"="DecimalSI"}} "count"=1 "topologyAssignment"={"levels"=["kubernetes.io/hostname"] "domains"=[{"values"=["x1"] "count"=1}]}}]
    scheduler_test.go:5054: Unexpected assigned clusterQueues in cache (-want,+got):
          map[string]v1beta1.Admission(
        - 	nil,
        + 	{
        + 		"default/foo": {ClusterQueue: "tas-main", PodSetAssignments: []v1beta1.PodSetAssignment{{...}}},
        + 	},
          )
    scheduler_test.go:5062: Unexpected elements left in inadmissible workloads (-want,+got):
          map[string][]string(
        - 	{"tas-main": {"default/foo"}},
        + 	nil,
          )
    scheduler_test.go:5065: unexpected events (-want/+got):
          []testing.EventRecord{
          	{
          		Key:       {Namespace: "default", Name: "foo"},
        - 		EventType: "Warning",
        + 		EventType: "Normal",
        - 		Reason:    "Pending",
        + 		Reason:    "QuotaReserved",
          		Message: strings.Join({
        - 			`couldn't assign flavors to pod set one: topology "tas-single-lev`,
        - 			`el" doesn't allow to fit any of 1 pod(s)`,
        + 			"Quota reserved in ClusterQueue tas-main, wait time since queued ",
        + 			"was 9223372037s",
          		}, ""),
          	},
        + 	{
        + 		Key:       s"default/foo",
        + 		EventType: "Normal",
        + 		Reason:    "Admitted",
        + 		Message:   "Admitted by ClusterQueue tas-main, wait time since reservation was 0s",
        + 	},
          }
--- FAIL: TestScheduleForTAS/workload_does_not_get_scheduled_as_the_node_capacity_(.status.allocatable['pods'])_is_already_used_by_non-TAS_and_TAS_workloads (0.00s)

--- FAIL: TestScheduleForTAS (0.01s)

FAIL

Process finished with the exit code 1
```

File: pkg/cache/tas_flavor_snapshot.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/cache/tas_flavor_snapshot.go]: @mimowo I addressed this here: https://github.com/kubernetes-sigs/kueue/pull/4271/commits/4653eccd3468cb8727b430850595c038af191d63

Thank you again for great catch :)

**Comment by PBundyra** [comment]
Do we need a separate logic for Pods? Does it differ from other allocatable node's resources? Can we maybe simplify this change by adding a Pod to the requested resource here https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/tas_flavor_snapshot.go#L301 ?

File: pkg/scheduler/scheduler_test.go (hunk 4 above)
Comment (mimowo) [reply pkg/scheduler/scheduler_test.go:4929]: ack

**Comment by tenzen-y** [comment]
> > Do we need separate logic for Pods? Does it differ from other allocatable node's resources? Can we maybe simplify this change by adding a Pod to the requested resource here https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/tas_flavor_snapshot.go#L301 ?
> 
> But how will you know how many pods are already used per domain?
> 
> At least I don't see how this would work, maybe modifying the PodTemplate for Workload would work, but this resource (pods) is "implicit" not requested by a user, so it is not tracked in PodTemplate, also it would be always equal "1". However, we generally try not to modify templates as requested by users. I think kube-scheduler also solves this problem by counting the pods implicitly: https://github.com/kubernetes/kubernetes/blob/87fcae2bc765e4f752bcf7dfbd0c57f75ec751a3/pkg/scheduler/framework/plugins/noderesources/fit.go#L503-L511.

Yes, that's correct. The problem is Pod does not have information pod count under the `resources` field, but we need to care that. So, instead of taking pod count from `requests`, we need to count it as @mimowo described.

**Comment by PBundyra** [comment]
> > > Do we need separate logic for Pods? Does it differ from other allocatable node's resources? Can we maybe simplify this change by adding a Pod to the requested resource here https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/tas_flavor_snapshot.go#L301 ?
> > 
> > 
> > But how will you know how many pods are already used per domain?
> > At least I don't see how this would work, maybe modifying the PodTemplate for Workload would work, but this resource (pods) is "implicit" not requested by a user, so it is not tracked in PodTemplate, also it would be always equal "1". However, we generally try not to modify templates as requested by users. I think kube-scheduler also solves this problem by counting the pods implicitly: https://github.com/kubernetes/kubernetes/blob/87fcae2bc765e4f752bcf7dfbd0c57f75ec751a3/pkg/scheduler/framework/plugins/noderesources/fit.go#L503-L511.
> 
> Yes, that's correct. The problem is Pod does not have information pod count under the `resources` field, but we need to care that based on nodes (topologies) allocatable. So, instead of taking pod count from `requests`, we need to count it as @mimowo described.

Didn't mean to modify PodTemplate, just to extend `requests` variable by `resources.Requests{corev1.ResourcePods: 1}` in the line I linked below. My point was, that if `requests` accounted for Pods properly, we could simplify logic in those places:
- https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-5414dcb324187d1d853329b419691cde79632a6d77e1a7c2b503dc1a3688c081R276
- https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-5414dcb324187d1d853329b419691cde79632a6d77e1a7c2b503dc1a3688c081R514
- https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-efe5cd799f015dadf76390b787b40d7f9244ac449d71d35de91b8eed1275d122R109-R112

> But how will you know how many pods are already used per domain?
IIUC we already store how many allocatable pods are on a node. Thus we could make calculation as for every other resource, add/subtract on the go

**Comment by mimowo** [comment]
Thanks for more details explanation. Maybe indeed some simplifications are possible. Indeed, we could try to track it as any other resource for leaf domains.

File: pkg/cache/tas_flavor_snapshot.go [hunk 5]
```diff
@@ -508,7 +510,8 @@ func (s *TASFlavorSnapshot) fillInCounts(requests resources.Requests,
 		if leafAssumedUsage, found := assumedUsage[leaf.domain.id]; found {
 			remainingCapacity.Sub(leafAssumedUsage)
 		}
-		leaf.state = requests.CountIn(remainingCapacity)
+		// Consider the situation where the allocatable Pods is less than allocatable resources from requests.CountIn().
+		leaf.state = min(requests.CountIn(remainingCapacity), int32(remainingCapacity[corev1.ResourcePods]))
```
Comment (mimowo) [inline pkg/cache/tas_flavor_snapshot.go:514]: I'm onboard with @PBundyra - it is worth trying to move this logic [here](https://github.com/kubernetes-sigs/kueue/blob/06d4c763ce03891dc0f869e42d5557f9831f1682/pkg/cache/tas_flavor_snapshot.go#L301). Especially, if it helps to remove the custom checks from other places it will make the PR smaller to cherry-pick.

**Comment by tenzen-y** [comment]
> > > > Do we need separate logic for Pods? Does it differ from other allocatable node's resources? Can we maybe simplify this change by adding a Pod to the requested resource here https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/tas_flavor_snapshot.go#L301 ?
> > > 
> > > 
> > > But how will you know how many pods are already used per domain?
> > > At least I don't see how this would work, maybe modifying the PodTemplate for Workload would work, but this resource (pods) is "implicit" not requested by a user, so it is not tracked in PodTemplate, also it would be always equal "1". However, we generally try not to modify templates as requested by users. I think kube-scheduler also solves this problem by counting the pods implicitly: https://github.com/kubernetes/kubernetes/blob/87fcae2bc765e4f752bcf7dfbd0c57f75ec751a3/pkg/scheduler/framework/plugins/noderesources/fit.go#L503-L511.
> > 
> > 
> > Yes, that's correct. The problem is Pod does not have information pod count under the `resources` field, but we need to care that based on nodes (topologies) allocatable. So, instead of taking pod count from `requests`, we need to count it as @mimowo described.
> 
> Didn't mean to modify PodTemplate, just to extend `requests` variable by `resources.Requests{corev1.ResourcePods: 1}` in the line I linked above. My point was, that if `requests` accounted for Pods properly, we could simplify logic in those places:
> 
> * https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-5414dcb324187d1d853329b419691cde79632a6d77e1a7c2b503dc1a3688c081R276
> * https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-5414dcb324187d1d853329b419691cde79632a6d77e1a7c2b503dc1a3688c081R514
> * https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-efe5cd799f015dadf76390b787b40d7f9244ac449d71d35de91b8eed1275d122R109-R112
> 
> > But how will you know how many pods are already used per domain?
> 
> IIUC we already store how many allocatable pods are on a node. Thus we could make calculation as for every other resource, add/subtract on the go

Thank you for expanding your recommendations. Let me see if the change will not affect user-facing assignment information (CRD).

File: pkg/cache/tas_flavor_snapshot.go (hunk 5 above)
Comment (tenzen-y) [reply pkg/cache/tas_flavor_snapshot.go:514]: Yes, that sounds reasonable. I'm trying that. Thank you for clarifying that.

**Comment by tenzen-y** [comment]
> > > > > Do we need separate logic for Pods? Does it differ from other allocatable node's resources? Can we maybe simplify this change by adding a Pod to the requested resource here https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/tas_flavor_snapshot.go#L301 ?
> > > > 
> > > > 
> > > > But how will you know how many pods are already used per domain?
> > > > At least I don't see how this would work, maybe modifying the PodTemplate for Workload would work, but this resource (pods) is "implicit" not requested by a user, so it is not tracked in PodTemplate, also it would be always equal "1". However, we generally try not to modify templates as requested by users. I think kube-scheduler also solves this problem by counting the pods implicitly: https://github.com/kubernetes/kubernetes/blob/87fcae2bc765e4f752bcf7dfbd0c57f75ec751a3/pkg/scheduler/framework/plugins/noderesources/fit.go#L503-L511.
> > > 
> > > 
> > > Yes, that's correct. The problem is Pod does not have information pod count under the `resources` field, but we need to care that based on nodes (topologies) allocatable. So, instead of taking pod count from `requests`, we need to count it as @mimowo described.
> > 
> > 
> > Didn't mean to modify PodTemplate, just to extend `requests` variable by `resources.Requests{corev1.ResourcePods: 1}` in the line I linked above. My point was, that if `requests` accounted for Pods properly, we could simplify logic in those places:
> > 
> > * https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-5414dcb324187d1d853329b419691cde79632a6d77e1a7c2b503dc1a3688c081R276
> > * https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-5414dcb324187d1d853329b419691cde79632a6d77e1a7c2b503dc1a3688c081R514
> > * https://github.com/kubernetes-sigs/kueue/pull/4271/files#diff-efe5cd799f015dadf76390b787b40d7f9244ac449d71d35de91b8eed1275d122R109-R112
> > 
> > > But how will you know how many pods are already used per domain?
> > 
> > 
> > IIUC we already store how many allocatable pods are on a node. Thus we could make calculation as for every other resource, add/subtract on the go
> 
> Thank you for expanding your recommendations. Let me see if the change will not affect user-facing assignment information (CRD).

I tried this approach, and it should work fine. 

But if we pass two or more Pods as requests like `{"pods": 2}` to the `CountIn()` function, it will be broken.
The `CountIn()` function is exposed, and the current impl can not enforce passing only 1 Pod request as a receiver. So, I would like to add any guard to the `CountIn()`. But we can do it in a separate PR since the refining does not directly contribute to this bug fixe. @mimowo @PBundyra

**Comment by tenzen-y** [comment]
@mimowo @PBundyra I pushed changes. PTAL, thanks.

**Comment by PBundyra** [comment]
\lgtm
Thank you!
It looks good to me, but I'll leave unholding to @mimowo for double-checking

**Comment by mimowo** [comment]
Looks great, thanks for reporting and fixing. 
/hold cancel
I would like to cherry pick this one. Hopefully there is not too many conflicts as TAS is changing rapidly.

**Comment by tenzen-y** [comment]
> Looks great, thanks for reporting and fixing. /hold cancel I would like to cherry pick this one. Hopefully there is not too many conflicts as TAS is changing rapidly.

Yeah, sure. @mimowo could you add lgtm tag?

**Comment by tenzen-y** [comment]
/cherry-pick release-0.9
/cherry-pick release-0.10

I do not think that bot can create cherry-pick, though
