### PR TITLE
[flaky test] should update workload TopologyAssignment after a node recovers

### LINKED ISSUE #6950: [flaky test] should update workload TopologyAssignment after a node recovers
**What happened**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-main/1970379300045590528

**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:

```
TopologyAwareScheduling Suite: [It] Topology Aware Scheduling when Single TAS Resource Flavor when Nodes are created before test with the hostname being the lowest level should update workload TopologyAssignment after a node recovers expand_less	14s
{Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/tas/tas_test.go:1224 with:
Expected object to be comparable, diff:   &v1beta1.TopologyAssignment{
  	Levels: {"kubernetes.io/hostname"},
  	Domains: []v1beta1.TopologyDomainAssignment{
  		{
- 			Values: []string{"x2"},
+ 			Values: []string{"x1"},
  			Count:  1,
  		},
  		{
- 			Values: []string{"x3"},
+ 			Values: []string{"x2"},
  			Count:  1,
  		},
  	},
  }
 failed [FAILED] Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/tas/tas_test.go:1224 with:
Expected object to be comparable, diff:   &v1beta1.TopologyAssignment{
  	Levels: {"kubernetes.io/hostname"},
  	Domains: []v1beta1.TopologyDomainAssignment{
  		{
- 			Values: []string{"x2"},
+ 			Values: []string{"x1"},
  			Count:  1,
  		},
  		{
- 			Values: []string{"x3"},
+ 			Values: []string{"x2"},
  			Count:  1,
  		},
  	},
  }
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/tas/tas_test.go:1234 @ 09/23/25 07:07:07.751
}
```

### PR DESCRIPTION
**Pull request by pajakd**
#### What type of PR is this?
/kind cleanup
/kind flake

#### What this PR does / why we need it:
Deflakes an integration test. The name of the test was misleading as it is about a node becoming available (not recovering). I checked the history of revisions of this test and it never tested the recovery of the node. I'm renaming it to avoid confusion. Also, it can only work if the FailFast flag is set to false. So, I'm changing the flag to false for the duration of the test. 

Tested by running this test in a loop for an ~hour.

#### Which issue(s) this PR fixes:

Fixes #6950

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by pajakd** [comment]
In https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6953/pull-kueue-test-integration-baseline-main/1970413210309758976 the fairshaing suite failed (perhaps) related to https://github.com/kubernetes-sigs/kueue/issues/6824

/retest-required

File: test/integration/singlecluster/tas/tas_test.go [hunk 1]
```diff
@@ -1225,8 +1227,8 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
 							&kueue.TopologyAssignment{
 								Levels: []string{corev1.LabelHostname},
 								Domains: []kueue.TopologyDomainAssignment{
-									{Count: 1, Values: []string{"x1"}},
 									{Count: 1, Values: []string{"x2"}},
+									{Count: 1, Values: []string{"x3"}},
```
Comment (tenzen-y) [inline test/integration/singlecluster/tas/tas_test.go:1231]: I checked that this PR is not needed to cherry-pick to release branches.
Because the release-branch has correct extected domains: https://github.com/kubernetes-sigs/kueue/blob/release-0.13/test/integration/singlecluster/tas/tas_test.go#L1232-L1233

Comment (mimowo) [reply test/integration/singlecluster/tas/tas_test.go:1231]: Thanks for checking! Yes, we swapped then unnecessarily only on main in this PR: https://github.com/kubernetes-sigs/kueue/commit/1dd1a506aec6560f47702789dbefa15de735f309#diff-95ef2b4868044a4fbcc96fcda6df858f3b79548d2e4548fafcd9280114928dfcR1231-L1234

cc @mbobrovskyi
