### PR TITLE
Follow-up of #2239

### LINKED ISSUE #2213: Plain Pod gets deleted once admitted via ProvisioningRequest (DWS)
**What happened**:

After a ProvisioningRequest using `provisioningClassName: queued-provisioning.gke.io` was provisioned, Kueue ungated the Pod and added the node selectors and annotations.

Then, it assumed that the Workload no longer matched the Pod, thus triggering the eviction process:

```
2024-05-16T17:46:26.776057524Z {"caller":"jobframework/reconciler.go:385", "controller":"v1_pod", "gvk":"/v1, Kind=Pod", "job":"kueue-dws/dws-pod", "level":"Level(-2)", "msg":"Job admitted, unsuspending", "name":"dws-pod", "namespace":"kueue-dws", "reconcileID":"b519d6ea-8dd9-4340-8990-c4da4a67ecd5", "ts":"2024-05-16T17:46:26.775893243Z"}
2024-05-16T17:46:26.777898261Z {"Workload":{…}, "caller":"core/workload_controller.go:150", "controller":"workload", "controllerGroup":"kueue.x-k8s.io", "controllerKind":"Workload", "level":"Level(-2)", "msg":"Reconciling Workload", "name":"pod-dws-pod-4e884", "namespace":"kueue-dws", "reconcileID":"b010ca53-2b15-4d19-87c7-51a044425dfe", "ts":"2024-05-16T17:46:26.777789892Z", "workload":{…}}
2024-05-16T17:46:27.056640239Z {"caller":"jobframework/reconciler.go:263", "controller":"v1_pod", "gvk":"/v1, Kind=Pod", "job":"kueue-dws/dws-pod", "level":"Level(-2)", "msg":"Reconciling Job", "name":"dws-pod", "namespace":"kueue-dws", "reconcileID":"c355b605-29b7-42f2-95bb-6ef81876ec1a", "ts":"2024-05-16T17:46:27.056497343Z"}
2024-05-16T17:46:27.056962616Z {"caller":"jobframework/reconciler.go:521", "controller":"v1_pod", "gvk":"/v1, Kind=Pod", "job":"kueue-dws/dws-pod", "level":"Level(-2)", "msg":"job with no matching workload, suspending", "name":"dws-pod", "namespace":"kueue-dws", "reconcileID":"c355b605-29b7-42f2-95bb-6ef81876ec1a", "ts":"2024-05-16T17:46:27.056832747Z"}
```

**What you expected to happen**:

The pod to run.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster and configure DWS using https://cloud.google.com/kubernetes-engine/docs/how-to/provisioningrequest
2. Create a plain Pod, for example:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dws-pod
  labels:
    kueue.x-k8s.io/queue-name: dws-local-queue
spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-l4"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["120s"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "500m"
            memory: "512Mi"
            nvidia.com/gpu: "1"
      restartPolicy: Never
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.29.4-gke.1447000`
- Kueue version (use `git describe --tags --dirty --always`): `v0.6.2`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by vladikkuzn**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Follow-up of #2239
#### Which issue(s) this PR fixes:

Fixes #2213

#### Special notes for your reviewer:
* Test for ignoreTolerations
* Add node selector to test to make sure it's not a part of equality check

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: pkg/util/equality/podset_test.go [hunk 1]
```diff
@@ -28,29 +28,34 @@ import (
...
+		ignoreTolerations bool
+		wantEqual         bool
 	}{
 		"different name": {
-			a:         []kueue.PodSet{*utiltestting.MakePodSet("ps", 10).SetMinimumCount(5).Obj()},
-			b:         []kueue.PodSet{*utiltestting.MakePodSet("ps2", 10).SetMinimumCount(5).Obj()},
-			wantEqual: true,
+			a:                 []kueue.PodSet{*utiltestting.MakePodSet("ps", 10).SetMinimumCount(5).Obj()},
+			b:                 []kueue.PodSet{*utiltestting.MakePodSet("ps2", 10).SetMinimumCount(5).Obj()},
+			ignoreTolerations: false,
```
Comment (alculquicondor) [inline pkg/util/equality/podset_test.go:39]: you can remove this line, to reduce the diff

**Review by trasc — COMMENTED** [review]
/lgtm

File: pkg/controller/jobs/job/job_controller_test.go [hunk 2]
```diff
@@ -2397,12 +2400,16 @@ func TestReconciler(t *testing.T) {
 				Key:      "tolerationkey2",
 				Operator: corev1.TolerationOpExists,
 				Effect:   corev1.TaintEffectNoSchedule,
-			}).Suspend(false).Obj(),
+			}).NodeSelector("node-label", "value").
```
Comment (trasc) [inline pkg/controller/jobs/job/job_controller_test.go:2403]: to prove that the node selectors have no impact, the selectors in the job should be different then the ones in the workload.

File: pkg/controller/jobs/job/job_controller_test.go [hunk 3]
```diff
@@ -2397,12 +2400,16 @@ func TestReconciler(t *testing.T) {
...
+				Suspend(false).
+				Obj(),
 			wantJob: *baseJobWrapper.Clone().Toleration(corev1.Toleration{
 				Key:      "tolerationkey2",
 				Operator: corev1.TolerationOpExists,
 				Effect:   corev1.TaintEffectNoSchedule,
-			}).Suspend(false).Obj(),
+			}).NodeSelector("node-label", "value").
```
Comment (trasc) [inline pkg/controller/jobs/job/job_controller_test.go:2410]: same

File: pkg/controller/jobs/job/job_controller_test.go [hunk 4]
```diff
@@ -2336,13 +2336,14 @@ func TestReconciler(t *testing.T) {
 				Key:      "tolerationkey2",
 				Operator: corev1.TolerationOpExists,
 				Effect:   corev1.TaintEffectNoSchedule,
-			}).
+			}).NodeSelector("node-label1", "value").
```
Comment (mimowo) [inline pkg/controller/jobs/job/job_controller_test.go:2339]: I don't think the test verifies currently that nodeSelectors don't matter for the equality check since the tolerations are changed. Maybe we can have a new test "the workload is not admitted and nodeSelectors change", but only changing the node selectors?

Comment (mimowo) [reply pkg/controller/jobs/job/job_controller_test.go:2339]: I would be fine with that approach. But we should have still have at least one higher-level test (like this) which corresponds to the reported bug. Maybe just rename the test "the workload is not admitted, tolerations and nodeSelectors change".

File: pkg/util/equality/podset_test.go [hunk 5]
```diff
@@ -28,9 +28,10 @@ import (
 
 func TestComparePodSetSlices(t *testing.T) {
 	cases := map[string]struct {
-		a         []kueue.PodSet
-		b         []kueue.PodSet
-		wantEqual bool
+		a                 []kueue.PodSet
+		b                 []kueue.PodSet
+		ignoreTolerations bool
+		wantEqual         bool
```
Comment (mimowo) [inline pkg/util/equality/podset_test.go:34]:
```suggestion
		want         bool
```
nit: or `wantResult`, or `wantEquivalent`. We check equivalence which is a slightly more relaxed concept than "equal"

**Review by mimowo — COMMENTED** [review]
/lgtm
