### PR TITLE
Add ConfigureSuiteReporting to test suites to fix double workload in …

### LINKED ISSUE #9923: Failed asserts result in recording the same workload twice
/kind bug

**What would you like to be cleaned**:

Example failure message: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9893/pull-kueue-test-integration-baseline-main/2033626544118697984

```
TopologyAwareScheduling Suite: [It] Topology Aware Scheduling when Single TAS Resource Flavor when Nodes are created before test with rack being the lowest level Should admit a previously inadmissible limits-only workload after another workload finishes expand_less	16s
{Timed out after 10.000s.
Unexpected workloads with QuotaReservation
    <*v1beta2.Workload | 0xc001479448>: metadata:
          creationTimestamp: "2026-03-16T19:47:15Z"
          generation: 1
          managedFields:
          - apiVersion: kueue.x-k8s.io/v1beta2
            fieldsType: FieldsV1
            fieldsV1:
              f:status:
                f:conditions:
                  k:{"type":"QuotaReserved"}:
                    .: {}
                    f:lastTransitionTime: {}
                    f:message: {}
                    f:observedGeneration: {}
                    f:reason: {}
                    f:status: {}
                    f:type: {}
                f:resourceRequests:
                  k:{"name":"worker"}:
                    .: {}
                    f:name: {}
                    f:resources:
                      f:cpu: {}
            manager: kueue-admission
            operation: Apply
            subresource: status
            time: "2026-03-16T19:47:15Z"
          - apiVersion: kueue.x-k8s.io/v1beta2
            fieldsType: FieldsV1
            fieldsV1:
              f:spec:
                .: {}
                f:active: {}
                f:podSets:
                  .: {}
                  k:{"name":"worker"}:
                    .: {}
                    f:count: {}
                    f:name: {}
                    f:template:
                      .: {}
                      f:metadata: {}
                      f:spec:
                        .: {}
                        f:containers:
                          .: {}
                          k:{"name":"c"}:
                            .: {}
                            f:name: {}
                            f:resources:
                              .: {}
                              f:limits:
                                .: {}
                                f:cpu: {}
                        f:restartPolicy: {}
                    f:topologyRequest:
                      .: {}
                      f:preferred: {}
                f:queueName: {}
            manager: tas.test
            operation: Update
            time: "2026-03-16T19:47:15Z"
          name: limits-pnly
          namespace: tas-4n5z4
          resourceVersion: "269"
          uid: 2b1d681b-0dbd-4d55-bea6-4748a123fe9d
        spec:
          active: true
          podSets:
          - count: 4
            name: worker
            template:
              metadata: {}
              spec:
                containers:
                - name: c
                  resources:
                    limits:
                      cpu: "1"
                restartPolicy: Never
            topologyRequest:
              preferred: cloud.provider.com/topology-block
          queueName: local-queue
        status:
          conditions:
          - lastTransitionTime: "2026-03-16T19:47:15Z"
            message: Workload no longer fits after processing another workload
            observedGeneration: 1
            reason: Pending
            status: "False"
            type: QuotaReserved
          resourceRequests:
          - name: worker
            resources:
              cpu: "4"
        

The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:372 with:
Expected
    <[]types.NamespacedName | len:0, cap:1>: []
to equal
    <[]types.NamespacedName | len:1, cap:1>: [
        {
            Namespace: "tas-4n5z4",
            Name: "limits-pnly",
        },
    ] failed [FAILED] Timed out after 10.000s.
Unexpected workloads with QuotaReservation
    <*v1beta2.Workload | 0xc001479448>: metadata:
          creationTimestamp: "2026-03-16T19:47:15Z"
          generation: 1
          managedFields:
          - apiVersion: kueue.x-k8s.io/v1beta2
            fieldsType: FieldsV1
            fieldsV1:
              f:status:
                f:conditions:
                  k:{"type":"QuotaReserved"}:
                    .: {}
                    f:lastTransitionTime: {}
                    f:message: {}
                    f:observedGeneration: {}
                    f:reason: {}
                    f:status: {}
                    f:type: {}
                f:resourceRequests:
                  k:{"name":"worker"}:
                    .: {}
                    f:name: {}
                    f:resources:
                      f:cpu: {}
            manager: kueue-admission
            operation: Apply
            subresource: status
            time: "2026-03-16T19:47:15Z"
          - apiVersion: kueue.x-k8s.io/v1beta2
            fieldsType: FieldsV1
            fieldsV1:
              f:spec:
                .: {}
                f:active: {}
                f:podSets:
                  .: {}
                  k:{"name":"worker"}:
                    .: {}
                    f:count: {}
                    f:name: {}
                    f:template:
                      .: {}
                      f:metadata: {}
                      f:spec:
                        .: {}
                        f:containers:
                          .: {}
                          k:{"name":"c"}:
                            .: {}
                            f:name: {}
                            f:resources:
                              .: {}
                              f:limits:
                                .: {}
                                f:cpu: {}
                        f:restartPolicy: {}
                    f:topologyRequest:
                      .: {}
                      f:preferred: {}
                f:queueName: {}
            manager: tas.test
            operation: Update
            time: "2026-03-16T19:47:15Z"
          name: limits-pnly
          namespace: tas-4n5z4
          resourceVersion: "269"
          uid: 2b1d681b-0dbd-4d55-bea6-4748a123fe9d
        spec:
          active: true
          podSets:
          - count: 4
            name: worker
            template:
              metadata: {}
              spec:
                containers:
                - name: c
                  resources:
                    limits:
                      cpu: "1"
                restartPolicy: Never
            topologyRequest:
              preferred: cloud.provider.com/topology-block
          queueName: local-queue
        status:
          conditions:
          - lastTransitionTime: "2026-03-16T19:47:15Z"
            message: Workload no longer fits after processing another workload
            observedGeneration: 1
            reason: Pending
            status: "False"
            type: QuotaReserved
          resourceRequests:
          - name: worker
            resources:
              cpu: "4"
        

The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:372 with:
Expected
    <[]types.NamespacedName | len:0, cap:1>: []
to equal
    <[]types.NamespacedName | len:1, cap:1>: [
        {
            Namespace: "tas-4n5z4",
            Name: "limits-pnly",
        },
    ]
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/tas/tas_test.go:603 @ 03/16/26 19:47:25.432
}
```

**Why is this needed**:

The workload is logged only once.

### PR DESCRIPTION
**Pull request by reruno**
…JUnit XML

#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
Add ConfigureSuiteReporting to test suites to fix double workload in JUnit XML
#### Which issue(s) this PR fixes:

Fixes #9923 

#### Special notes for your reviewer:
integration test doesn't work because I left a bad check inside of it to see how messages are rendered now after the fix

test integration error output in prow with no double workload 
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10153/pull-kueue-test-integration-baseline-main/2037549141281738752
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/controller/jobs/jobset/suite_test.go [hunk 1]
```diff
@@ -69,6 +69,11 @@ var _ = ginkgo.AfterSuite(func() {
 	fwk.Teardown()
 })
 
+var _ = ginkgo.ReportAfterSuite("Generate JUnit Report for test/integration/singlecluster/controller/jobs/jobset", func(report ginkgo.Report) {
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/jobset/suite_test.go]: Avoid repeating the path, everyone will just copy paste, just say "Generate JUnit Report". Then add more details in ConfigureSuiteReporting using GinkgoLog, where we have the path computed

File: test/util/util.go [hunk 2]
```diff
@@ -108,6 +109,26 @@ var SetupLoggerGetObservedLogs = sync.OnceValue(func() *observer.ObservedLogs {
...
+func ConfigureSuiteReporting(report ginkgo.Report) error {
+	junitConfig := reporters.JunitReportConfig{
+		OmitFailureMessageAttr: true,
+	}
+	suiteName := uniqueSuiteName(report.SuitePath)
+	reportPath := "junit-" + suiteName + ".xml"
+	if dir := os.Getenv("ARTIFACTS"); dir != "" {
+		reportPath = filepath.Join(dir, reportPath)
+	}
+	return reporters.GenerateJUnitReportWithConfig(report, reportPath, junitConfig)
```
Comment (mimowo) [inline test/util/util.go:125]: Add the message using GinkgoLog here, something like "Generating JUnit report to <path>"

**Comment by mimowo** [comment]
/cherrypick release-0.16
/cherrypick release-0.15
please prepare cherrypicks if the robot fails
