### PR TITLE
MultiKueue: fix eviction initiated by the manager cluster

### LINKED ISSUE #7350: [MultiKueue] Eviction initiated on manager doesn't work
**What happened**:
I'm trying to create high priority job to preempt low priority job but it is not working as expect. The workload stuck on.

Status from high priority job:

```yaml
- lastTransitionTime: "2025-10-23T06:33:18Z"
   message: 'couldn''t assign flavors to pod set main: insufficient unused quota
    for memory in flavor default, 1953125Ki more needed. Pending the preemption
    of 1 workload(s)'
   observedGeneration: 1
   reason: Pending
   status: "False"
   type: QuotaReserved
```

Status from low priority job:

```yaml
conditions:
  - lastTransitionTime: "2025-10-23T06:33:17Z"
   message: Quota reserved in ClusterQueue q1
   observedGeneration: 1
   reason: QuotaReserved
   status: "True"
   type: QuotaReserved
  - lastTransitionTime: "2025-10-23T06:33:18Z"
   message: 'Preempted to accommodate a workload (UID: 9f542104-a9e2-4344-ad2e-9c136204da18,
    JobUID: a20d0a6a-64a3-46ce-9b95-8cfb3bf6e675) due to prioritization in the
    ClusterQueue'
   observedGeneration: 1
   reason: Preempted
   status: "True"
   type: Evicted
  - lastTransitionTime: "2025-10-23T06:33:18Z"
   message: The workload is admitted
   observedGeneration: 1
   reason: Admitted
   status: "True"
   type: Admitted
  - lastTransitionTime: "2025-10-23T06:33:18Z"
   message: 'Preempted to accommodate a workload (UID: 9f542104-a9e2-4344-ad2e-9c136204da18,
    JobUID: a20d0a6a-64a3-46ce-9b95-8cfb3bf6e675) due to prioritization in the
    ClusterQueue'
   reason: InClusterQueue
   status: "True"
   type: Preempted
```

Logs from the manager cluster occurring in a loop:

```
2025-10-23T07:13:10.668141483Z	DEBUG	events	recorder/recorder.go:104	couldn't assign flavors to pod set main: insufficient unused quota for memory in flavor default, 1953125Ki more needed. Pending the preemption of 1 workload(s)	{"type": "Warning", "object": {"kind":"Workload","namespace":"multikueue-vggw9","name":"job-job2-f620a","uid":"4cc488da-107c-4814-8248-b44ac9462816","apiVersion":"kueue.x-k8s.io/v1beta1","resourceVersion":"14153"}, "reason": "Pending"}
2025-10-23T07:13:10.76844517Z	LEVEL(-3)	scheduler	queue/manager.go:661	Obtained ClusterQueue heads	{"schedulingCycle": 12168, "count": 1}
2025-10-23T07:13:10.768592836Z	LEVEL(-3)	scheduler	scheduler/fair_sharing_iterator.go:69	Returning workload from ClusterQueue without Cohort	{"schedulingCycle": 12168, "clusterQueue": {"name":"q1"}, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}}
2025-10-23T07:13:10.768610128Z	LEVEL(-2)	scheduler	scheduler/scheduler.go:252	Attempting to schedule workload	{"schedulingCycle": 12168, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}, "clusterQueue": {"name":"q1"}}
2025-10-23T07:13:10.768633711Z	LEVEL(-3)	scheduler	preemption/preemption.go:190	Preemption ongoing	{"schedulingCycle": 12168, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}, "clusterQueue": {"name":"q1"}, "targetWorkload": {"name":"job-job1-6f320","namespace":"multikueue-vggw9"}, "preemptingWorkload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}}
2025-10-23T07:13:10.768676628Z	LEVEL(-3)	scheduler	scheduler/logging.go:42	Workload evaluated for admission	{"schedulingCycle": 12168, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}, "clusterQueue": {"name":"q1"}, "status": "", "reason": "couldn't assign flavors to pod set main: insufficient unused quota for memory in flavor default, 1953125Ki more needed. Pending the preemption of 1 workload(s)"}
2025-10-23T07:13:10.768709211Z	LEVEL(-2)	scheduler	scheduler/scheduler.go:778	Workload re-queued	{"schedulingCycle": 12168, "workload": {"name":"job-job2-f620a","namespace":"multikueue-vggw9"}, "clusterQueue": {"name":"q1"}, "queue": {"name":"q1","namespace":"multikueue-vggw9"}, "requeueReason": "PendingPreemption", "added": true, "status": ""}
```

**What you expected to happen**:
The high priority job should be successfully admitted.

**How to reproduce it (as minimally and precisely as possible)**:
- Create low priority job
- Create high priority job

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #7350

#### Does this PR introduce a user-facing change?

```release-note
MultiKueue: fix the eviction when initiated by the manager cluster (due to eg. Preemption or WaitForPodsReady timeout).
```

### CODE REVIEW

**Comment by mimowo** [comment]
I havent yet read the code, but it woukd help a lot to
1. split the PR for handling eviction initiated by manager and worker, and only focus on preemption initiated by manager here
2. make that clear in the release note

For preemption initiated on worker we may need to still think. Maybe it makes more sense to initiate the eviction only in case of deactivation on worker.

**Comment by mbobrovskyi** [comment]
> 1. split the PR for handling eviction initiated by manager and worker, and only focus on preemption initiated by manager here

I implemented the eviction by preemption logic for the manager. I haven’t tested it on the worker yet, but it should probably work.

**Comment by mimowo** [comment]
Ok we can revisit that in a follow up.

Is it just for batch/Job? In the release note you say only for batch/Job, but you mark issue as Fixed by the PR. I think we should mark the issue finished when all Job rds are supported, unless some are particularly hard then we can open follow up issue.

**Comment by mbobrovskyi** [comment]
> Is it just for batch/Job? In the release note you say only for batch/Job, but you mark issue as Fixed by the PR. I think we should mark the issue finished when all Job rds are supported, unless some are particularly hard then we can open follow up issue.

No, it should work for all jobs. I’ll add tests to confirm this.

**Comment by mimowo** [comment]
Ok, do we have a test which shows that after eviction the workload can be scheduled on another worker? This is quite important.

Regarding preemption initiated by worker I would rather only evict on manager when deactivated on worker. So that worker behaves as if there was no manager for most cases. Otherwise I think it would be weird for ProReq to be removed from worker just after one failure if the limit is 3.

EDIT: still it is probably ok to leave it for later. propagating evoction is time from worker to manager is probably anyway better than always. Long term we may need extra configuration for that

**Comment by mbobrovskyi** [comment]
> Ok, do we have a test which shows that after eviction the workload can be scheduled on another worker? This is quite important.

Yes, this [integration](https://github.com/epam/kubernetes-kueue/blob/9b56d0419120002fd29e0d5b11347203ca824168/test/integration/multikueue/scheduler/scheduler_test.go#L349-L480) and [e2e](https://github.com/epam/kubernetes-kueue/blob/9b56d0419120002fd29e0d5b11347203ca824168/test/e2e/multikueue/e2e_test.go#L606-L679) tests.

**Comment by mbobrovskyi** [comment]
Here is the current logic:

1. Preempt the workload on the manager.
2. Copy eviction statuses (currently only Evict and Preemption) to the worker.
3. Complete the eviction on the worker and sync Job statuses.
4. Wait for the eviction to complete on the manager.

**Comment by mimowo** [comment]
Hm I'm not sure I'm happy about that. Rather than syncing conditions from manager to the worker I think we need to use dedicated one:
type: Evicted
reason: EvictedOnManagerDueToPreempted
message: Evicted on manager due to: 

The reason could also be just EvictedOnManager

And I wouldn't sync Preempted for now. This makes it assymetric because we also have other conditions. And it is not necessary for mechanism. Yes we need better observability, but this needs to be dedicated task. Syncing the Preempted condition will create more confusion than explanation

**Comment by mbobrovskyi** [comment]
> reason: EvictedOnManagerDueToPreempted

I’m not sure why we need this if it works fine without it. Adding this reason makes the logic more complex. We also need to check whether the Evict function is running on the manager or the worker.

**Comment by mimowo** [comment]
because syncing 
Evicted 
reason Preempted to manager is misleading. Instead of syncing also Preempted I prefer to just sync
Evicted
reason EvictedOnManager
this way the user, and tooling, can see it was evicted by manager and go there to investigate more. We will improve observability later.

**Comment by mimowo** [comment]
Or even better just set on worker
```
type: DeactivationTarget
reason: EvictedOnManagerCluster
```

EDIT: or as we synced with @mbobrovskyi let's go with `reason: EvictedOnManagerCluster`. This was it is more consistent with the other field names we introduced for MultiKueue like "clusterName" and "nominatedClusterNames". We don't need to include "MultiKueue" in the reason on names, because it is long and "cluster" is self-explanatory in the context.

**Comment by mimowo** [comment]
/retitle MultiKueue: fix eviction initiated by the manager cluster

**Comment by mimowo** [comment]
/release-note-edit
```release-note
MultiKueue: fix the eviction when initiated by the manager cluster (due to eg. Preemption or WairForPodsReady timeout).
```

**Comment by mbobrovskyi** [comment]
> Or even better just set on worker
> 
> ```
> type: DeactivationTarget
> reason: EvictedOnManagerCluster
> ```
> 
> EDIT: or as we synced with @mbobrovskyi let's go with `reason: EvictedOnManagerCluster`. This was it is more consistent with the other field names we introduced for MultiKueue like "clusterName" and "nominatedClusterNames". We don't need to include "MultiKueue" in the reason on names, because it is long and "cluster" is self-explanatory in the context.

Done

File: pkg/workload/workload.go [hunk 1]
```diff
@@ -1225,6 +1225,18 @@ func IsEvicted(w *kueue.Workload) bool {
 	return apimeta.IsStatusConditionTrue(w.Status.Conditions, kueue.WorkloadEvicted)
 }
 
+func IsMultiKueueWorkerWorkload(w *kueue.Workload) bool {
+	_, ok := w.Labels[kueue.MultiKueueOriginLabel]
+	return ok
+}
+
+func IsEvictedOnMultiKueueWorker(w *kueue.Workload) bool {
```
Comment (mimowo) [inline pkg/workload/workload.go]: Is this used? If not then drop (same with the other function)

Comment (mbobrovskyi) [reply pkg/workload/workload.go]: Thank you!

File: pkg/controller/jobs/job/job_multikueue_adapter.go [hunk 2]
```diff
@@ -64,7 +64,7 @@ func (b *multiKueueAdapter) SyncJob(ctx context.Context, localClient client.Clie
 	// the remote job exists
 	if err == nil {
 		if features.Enabled(features.MultiKueueBatchJobWithManagedBy) {
-			if fromObject(&localJob).IsSuspended() {
+			if fromObject(&localJob).IsSuspended() && !fromObject(&localJob).IsActive() {
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:66]: Oh, I think I also need to check with MultiKueueBatchJobWithManagedBy disabled.

Comment (mimowo) [inline pkg/controller/jobs/job/job_multikueue_adapter.go:66]: Hm, this change does not look right. Do we need it, and why?

**Comment by mimowo** [comment]
/retest
looks like infra

File: pkg/controller/jobs/job/job_multikueue_adapter.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:66]: Yes, this is correct. Otherwise, we can’t update the Job’s active status. After eviction, the Job is suspended but still marked as active, so we need to update the active status on the local Job.

Comment (mimowo) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:66]: sounds good

Comment (mimowo) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:66]: but it looks identical for all Job CRDs, so I would propose to introduce a helper like "ShouldSyncStatus"

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 3]
```diff
@@ -105,39 +110,23 @@ func (g *wlGroup) IsElasticWorkload() bool {
 	return workloadslicing.IsElasticWorkload(g.local)
 }
 
-// FirstReserving returns true if there is a workload reserving quota,
+// bestMatchByCondition returns true if there is a workload with a specified condition type,
```
Comment (olekzabl) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Nit: `bestMatchByCondition` can't return `true`, as it returns no `bool`.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 4]
```diff
@@ -364,7 +354,26 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
 
-	// 2. delete all workloads that are out of sync (other than scaled-down elastic workloads)
+	// 4. Handle workload evicted on manager cluster
+	remoteEvictCond, evictedRemote := group.bestMatchByCondition(kueue.WorkloadEvicted)
+	if remoteEvictCond != nil && strings.Contains(remoteEvictCond.Reason, WorkloadEvictedOnManagerCluster) {
+		remoteCl := group.remoteClients[evictedRemote].client
+		remoteWl := group.remotes[evictedRemote]
+
+		log = log.WithValues("remote", evictedRemote, "remoteWorkload", klog.KObj(remoteWl))
+		ctrl.LoggerInto(ctx, log)
```
Comment (olekzabl) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Isn't this no-op?
IIUC `LoggerInto` returns a new `Context` but has no side-effects.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 5]
```diff
@@ -399,9 +407,30 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
-			log.V(2).Error(err, "creating remote controller object", "remote", reservingRemote)
-			// We'll retry this in the next reconcile.
+		remoteCl := group.remoteClients[reservingRemote].client
+		remoteWl := group.remotes[reservingRemote]
+
+		log = log.WithValues("remote", reservingRemote, "remoteWorkload", klog.KObj(remoteWl))
+		ctrl.LoggerInto(ctx, log)
+
+		evictedCond := apimeta.FindStatusCondition(group.local.Status.Conditions, kueue.WorkloadEvicted)
+		if workload.HasQuotaReservation(group.local) && evictedCond != nil {
```
Comment (olekzabl) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Should we check that `evictedCond` has status "true"?
Or do we work under assumption that this one will never have status "false"?

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 6]
```diff
@@ -399,9 +407,30 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+					api.TruncateConditionMessage(fmt.Sprintf("Evicted on manager: %s", evictedCond.Message)),
+				), nil
+			})
+			if err != nil {
+				log.Error(err, "Failed to patch workload status")
+			}
+			return reconcile.Result{}, err
+		}
+
+		if err := group.jobAdapter.SyncJob(ctx, w.client, remoteCl, group.controllerKey, group.local.Name, w.origin); err != nil {
```
Comment (olekzabl) [inline pkg/controller/admissionchecks/multikueue/workload.go:431]: To verify my understanding: is this `SyncJob()` intended to catch a workload which has gone through the full following journey:

1. Evicted on the manager
2. Then, deactivated on the worker (by [your new code](https://github.com/kubernetes-sigs/kueue/blob/d65db1f4367f653e14c5ed81b8b0581781bd616a/pkg/controller/admissionchecks/multikueue/workload.go#L419))
3. Then, marked as "evicted on manager" on the worker
   (by the worker's workload controller, first [here](https://github.com/kubernetes-sigs/kueue/blob/aafa84e7666976cc09a81d84a16626b61f48eb46/pkg/controller/core/workload_controller.go#L302) and then [here](https://github.com/kubernetes-sigs/kueue/blob/aafa84e7666976cc09a81d84a16626b61f48eb46/pkg/controller/core/workload_controller.go#L400))
   - at which point, if only it persists long enough, it'd be caught by [the other `SyncJob()` added in this PR](https://github.com/kubernetes-sigs/kueue/blob/d65db1f4367f653e14c5ed81b8b0581781bd616a/pkg/controller/admissionchecks/multikueue/workload.go#L366)
4. Then _quickly_ 
   (so that the other `SyncJob()` didn't manage to catch it in state # 3)
   requeued on the worker up to having quota reserved _again_ there
   - at which point it'd [lose the evicted condition](https://github.com/kubernetes-sigs/kueue/blob/aafa84e7666976cc09a81d84a16626b61f48eb46/pkg/workload/workload.go#L772) on the worker, and hence no longer be caught as in # 3

?

If yes - maybe it's worth a comment, I spent a long time figuring this out.
If not - I'd be grateful for educating me :)

Or maybe there are other scenarios (besides what's described in #7350) that you wanted to cover by the way?

File: test/e2e/multikueue/e2e_test.go [hunk 7]
```diff
@@ -514,6 +528,156 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+			workerLowWorkload := &kueue.Workload{}
+
+			ginkgo.By("Checking that the low-priority workload is created and admitted in the manager cluster", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sManagerClient.Get(ctx, lowWlKey, managerLowWl)).To(gomega.Succeed())
+					g.Expect(workload.IsAdmitted(managerLowWl)).To(gomega.BeTrue())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Checking that the low-priority workload is created in worker1 and not in worker2, and that its spec matches the manager workload", func() {
```
Comment (olekzabl) [inline test/e2e/multikueue/e2e_test.go:552]: For my understanding: we know it'll land on worker1 because its CPU request (2) is too high for worker-2's CQ limit (1), right?
(And not because worker1 is "first" in some order, like alphabetical, or order of configuring things?)

File: test/e2e/multikueue/e2e_test.go [hunk 8]
```diff
@@ -514,6 +528,156 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+			ginkgo.By("Checking that the high-priority workload is created in worker1 and not in worker2, and that its spec matches the manager workload", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sWorker1Client.Get(ctx, highWlKey, workerHighWorkload)).To(gomega.Succeed())
+					g.Expect(workload.IsAdmitted(workerHighWorkload)).To(gomega.BeTrue())
+					g.Expect(workerHighWorkload.Spec).To(gomega.BeComparableTo(managerHighWl.Spec))
+					g.Expect(k8sWorker2Client.Get(ctx, highWlKey, &kueue.Workload{})).To(utiltesting.BeNotFoundError())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Checking that the low-priority workload is preempted in the manager clusters", func() {
```
Comment (olekzabl) [inline test/e2e/multikueue/e2e_test.go]:
```suggestion
			ginkgo.By("Checking that the low-priority workload is preempted in the manager cluster", func() {
```



also a few occurrences in `scheduler_test.go`

File: test/integration/multikueue/scheduler/scheduler_test.go [hunk 9]
```diff
@@ -0,0 +1,617 @@
...
+		util.CreateLocalQueuesAndWaitForActive(managerTestCluster.ctx, managerTestCluster.client, managerLq)
+
+		worker1Flavor = utiltestingapi.MakeResourceFlavor("fl").Obj()
+		util.MustCreate(worker1TestCluster.ctx, worker1TestCluster.client, worker1Flavor)
+
+		worker1Cq = utiltestingapi.MakeClusterQueue("cq1").
+			ResourceGroup(
+				*utiltestingapi.MakeFlavorQuotas(worker1Flavor.Name).
+					Resource(corev1.ResourceCPU, "1").
+					Resource(corev1.ResourceMemory, "2G").
```
Comment (olekzabl) [inline test/integration/multikueue/scheduler/scheduler_test.go]: This is flipped wrt. the e2e test; any reason for that?
(I'm guessing the logic could be easier to follow if it was unified between both tests)

File: test/integration/multikueue/scheduler/scheduler_test.go [hunk 10]
```diff
@@ -0,0 +1,617 @@
...
+				g.Expect(worker1TestCluster.client.Get(worker1TestCluster.ctx, client.ObjectKeyFromObject(lowJob), &createdJob)).To(gomega.Succeed())
+				createdJob.Status.StartTime = &startTime
+				createdJob.Status.Active = 1
+				createdJob.Status.Ready = ptr.To[int32](1)
+				g.Expect(worker1TestCluster.client.Status().Update(worker1TestCluster.ctx, &createdJob)).To(gomega.Succeed())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(managerTestCluster.client.Get(managerTestCluster.ctx, client.ObjectKeyFromObject(lowJob), &createdJob)).To(gomega.Succeed())
+				g.Expect(ptr.Deref(createdJob.Status.StartTime, metav1.Time{})).To(gomega.Equal(startTime))
```
Comment (olekzabl) [inline test/integration/multikueue/scheduler/scheduler_test.go]: Readability nit: why not just
```suggestion
				g.Expect(createdJob.Status.StartTime).To(gomega.Equal(&startTime))
```
?

AFAICS `gomega.Equals` [relies on](https://github.com/onsi/gomega/blob/a3ca2ca026268dc6acfc60a2e8393b33b428c507/matchers.go#L12) `reflect.DeepEquals`, which [does look into](https://cs.opensource.google/go/go/+/refs/tags/go1.25.5:src/reflect/deepequal.go;l=197) the values of pointers.

---

Looking at Kueue code, I could find `gomega.Equal()` already applied to pointers - though only of simple types.
(So I'm curious if there's any deeper trouble hiding?)

File: test/integration/multikueue/scheduler/scheduler_test.go [hunk 11]
```diff
@@ -0,0 +1,617 @@
...
+		workerHighWorkload := &kueue.Workload{}
+
+		ginkgo.By("Checking that the high-priority workload is created and admitted in the manager clusters", func() {
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(managerTestCluster.client.Get(managerTestCluster.ctx, highWlKey, managerHighWl)).To(gomega.Succeed())
+				g.Expect(workload.IsAdmitted(managerHighWl)).To(gomega.BeTrue())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+		})
+
+		ginkgo.By("Checking that the high-priority workload is created in worker1 and not in worker2, and that its spec matches the manager workload (MultiKueueBatchJobWithManagedBy disabled)", func() {
```
Comment (olekzabl) [inline test/integration/multikueue/scheduler/scheduler_test.go]: This feature is disabled in the other `.It()`.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 3 above)
Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Thank you! Rebase and opened the new issue for that https://github.com/kubernetes-sigs/kueue/pull/8307.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 4 above)
Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Fixed.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 5 above)
Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Oh, good catch! Thank you!

File: test/e2e/multikueue/e2e_test.go (hunk 8 above)
Comment (mbobrovskyi) [reply test/e2e/multikueue/e2e_test.go]: Fixed

File: pkg/controller/jobs/job/job_multikueue_adapter.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/job/job_multikueue_adapter.go:66]: Done

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 6 above)
Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > If yes - maybe it's worth a comment, I spent a long time figuring this out.

Yes, exactly – that’s the case.

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: Just only one case.

4. I would say that we are waiting for [`QuotaReserved=false`](https://github.com/epam/kubernetes-kueue/blob/d19b24318fe9f573b2a9a4a03105e6eaca5da633/pkg/controller/admissionchecks/multikueue/workload.go#L326-L336). 
5. Than we can remove it from worker.

File: test/e2e/multikueue/e2e_test.go (hunk 7 above)
Comment (mbobrovskyi) [reply test/e2e/multikueue/e2e_test.go:552]: > For my understanding: we know it'll land on worker1 because its CPU request (2) is too high for worker-2's CQ limit (1), right?

Yes, exactly.

File: test/integration/multikueue/scheduler/scheduler_test.go (hunk 9 above)
Comment (mbobrovskyi) [reply test/integration/multikueue/scheduler/scheduler_test.go]: Done

File: test/integration/multikueue/scheduler/scheduler_test.go (hunk 10 above)
Comment (mbobrovskyi) [reply test/integration/multikueue/scheduler/scheduler_test.go]: To be honest I just copy past this block code :). Let me fix it.

Comment (mbobrovskyi) [reply test/integration/multikueue/scheduler/scheduler_test.go]: Done

File: test/integration/multikueue/scheduler/scheduler_test.go (hunk 11 above)
Comment (mbobrovskyi) [reply test/integration/multikueue/scheduler/scheduler_test.go]: Fixed. Thank you!

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 6 above)
Comment (olekzabl) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: Hmm, and what if the worker, after all the steps 1-4 described by me above, _quickly_ admits the workload again?

So _quickly_ that this reconcile loop in the manager will miss the whole period when the Job had `.Status.Active = 0`. And so, the manager could _never_ call `UnsetQuotaReservation`?

Comment (olekzabl) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: My naive understanding is that as long as a workload has condition "evicted on the manager", the workload's scheduler should prevent re-admitting it.
(EDIT: or, maybe even prevent re-reserving quota on the worker - which would make the `SyncJob()` discussed in this comment no longer necessary).

However, I don't see it done in this PR. Also your response above suggests that it's not done.
Are there reasons not to add such prevention?

Because, without this prevention, I'm afraid we could be running in unnecessary circles: manager evicts -> worker deactivates -> worker re-admits -> manager evicts -> ...

Or I'll be happy to learn what I missed.

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > Hmm, and what if the worker, after all the steps 1-4 described by me above, quickly admits the workload again?

Not sure I got how is it possible? We deactivated workload in step 2 (https://github.com/kubernetes-sigs/kueue/blob/aafa84e7666976cc09a81d84a16626b61f48eb46/pkg/controller/core/workload_controller.go#L302). After that it will never set quota reserved to true.

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > My naive understanding is that as long as a workload has condition "evicted on the manager", the workload's scheduler should prevent re-admitting it.
> (EDIT: or, maybe even prevent re-reserving quota on the worker - which would make the SyncJob() discussed in this comment no longer necessary).

Worker will never admit this workload. We have .spec.active=false. Only one case if user reactivate it again manually.

Comment (olekzabl) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > > Hmm, and what if the worker, after all the steps 1-4 described by me above, quickly admits the workload again?
> 
> Not sure I got how is it possible? We deactivated workload in step 2 (
> 
> https://github.com/kubernetes-sigs/kueue/blob/aafa84e7666976cc09a81d84a16626b61f48eb46/pkg/controller/core/workload_controller.go#L302
> 
> ). After that it will never set quota reserved to true.

Hmm, so, in other words, you say we'll never reach step 4 of my story?
If so, what's the role of the `SyncJob()` discussed in this comment?

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > Hmm, so, in other words, you say we'll never reach step 4 of my story?

Yes, exactly.

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > If so, what's the role of the SyncJob() discussed in this comment?

To copy job .status.active field to manager.

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: This is the main issue we are trying to fix in this PR. As I mentioned [here](https://github.com/kubernetes-sigs/kueue/issues/7350#issuecomment-3485464140)
, the Job’s active status on the manager is greater than zero, which means the Job is considered active and the quota reservation is never released.

Comment (olekzabl) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > > If so, what's the role of the SyncJob() discussed in this comment?
> 
> To copy job .status.active fields to manager.

Oh yes, that I know.

But, in this PR, you're adding `SyncJob()` in two places of the code.
Why isn't the other place sufficient?
Why do we need it _also_ here?

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: After step 3, we should wait for the worker Job’s .status.active field to be released and then copy it to the manager.

Comment (olekzabl) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: So, what's the scenario in which [this `SyncJob()`](https://github.com/kubernetes-sigs/kueue/blob/342b472f7f1ce27bf415619602d67a8d8a2f604a/pkg/controller/admissionchecks/multikueue/workload.go#L366) could fail to do it?

Why do we _also_ need [this one](https://github.com/kubernetes-sigs/kueue/blob/342b472f7f1ce27bf415619602d67a8d8a2f604a/pkg/controller/admissionchecks/multikueue/workload.go#L431)?

They're _both_ added by you in this PR. I'm trying to understand why we need _both_, not just the upper one.

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > But, in this PR, you're adding SyncJob() in two places of the code.

Because we can’t proceed to the next step. In the following code, we check whether the spec on the manager matches the spec on the worker. If they don’t match, we remove the workload. We shouldn't do that.

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: > They're both added by you in this PR. I'm trying to understand why we need both, not just the upper one.

Nope. I added only this one https://github.com/kubernetes-sigs/kueue/blob/342b472f7f1ce27bf415619602d67a8d8a2f604a/pkg/controller/admissionchecks/multikueue/workload.go#L366.

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: We should keep both, because here https://github.com/kubernetes-sigs/kueue/blob/342b472f7f1ce27bf415619602d67a8d8a2f604a/pkg/controller/admissionchecks/multikueue/workload.go#L431 we have another scenario when we have QuotaReservation=true to sync job with manager.

Comment (olekzabl) [reply pkg/controller/admissionchecks/multikueue/workload.go:431]: Ahh. I see. Thank you for all your explanations, it helped :)

**Comment by mimowo** [comment]
Thank you 👍 
/lgtm
/approve
/cherrypick release-0.15
/cherrypick release-0.14

**Comment by mimowo** [comment]
/hold
Let's check https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/8151/pull-kueue-test-integration-multikueue-main/2001897528747888640

File: pkg/controller/jobs/job/job_multikueue_adapter.go [hunk 12]
```diff
@@ -74,21 +73,19 @@ func (b *multiKueueAdapter) SyncJob(ctx context.Context, localClient client.Clie
...
-				remoteFinished = true
-				break
-			}
+
+		_, _, updated := fromObject(&remoteJob).Finished(ctx)
+		if remoteJob.Status.Active != localJob.Status.Active {
+			updated = true
 		}
-		if remoteFinished {
+		if updated {
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/job/job_multikueue_adapter.go]: Actually, this change isn’t needed. We don’t copy the status when MultiKueueBatchJobWithManagedBy=false, so there’s no need to wait for Active=0.

Comment (mbobrovskyi) [reply pkg/controller/jobs/job/job_multikueue_adapter.go]: Yes, I tested it in real cluster and it works without this changes.

**Comment by mimowo** [comment]
/release-note-edit
```release-note
MultiKueue: fix the eviction when initiated by the manager cluster (due to eg. Preemption or WaitForPodsReady timeout).
```
