### PR TITLE
Ensure Job status is updated after remote completion

### LINKED ISSUE #5613: MutliKueue: Local Job status is not updated upon remote Job completion.
**What happened**:

In MultiKueue, the local `Job` status is not updated to reflect the termination state of the corresponding remote `Job`. This behavior contradicts the [MultiKueue batch/Job documentation](https://kueue.sigs.k8s.io/docs/concepts/multikueue/#batchjob), which states that the local Job's final status should be copied once the remote workload is marked as finished.

Final `Job`/`Workload` status appears as follows:

```
NAME             STATUS      COMPLETIONS   DURATION   AGE
job.batch/demo   Suspended   0/2                      79s

NAME                                     QUEUE   RESERVED IN   ADMITTED   FINISHED   AGE
workload.kueue.x-k8s.io/job-demo-4e5de   demo    demo                     True       79s
```

**What you expected to happen**:

Once the remote workload is marked as finished, the local Job should reflect its final state, e.g.:

```
NAME             STATUS     COMPLETIONS   DURATION   AGE
job.batch/demo   Complete   2/2           27s        32s

NAME                                     QUEUE   RESERVED IN   ADMITTED   FINISHED   AGE
workload.kueue.x-k8s.io/job-demo-bc108   demo    demo                     True       32s
```

**How to reproduce it (as minimally and precisely as possible)**:

Create a batch `Job` using the [MultiKueue batch/Job example](https://kueue.sigs.k8s.io/docs/tasks/run/multikueue/job/#example) and observe the local Job's status after the remote workload completes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.31.2`
- Kueue version (use `git describe --tags --dirty --always`): `latest release` or `main branch`
- Cloud provider or hardware configuration: `n/a`
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ichekrygin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fixes an issue where the local Job status was not updated to reflect the final state
of the remote Job when using MultiKueue with the default (disabled) 
MultiKueueBatchJobWithManagedBy feature gate. The update was previously 
skipped if the local Job remained suspended, contrary to documented behavior.

#### Which issue(s) this PR fixes:

Fixes #5613

#### Does this PR introduce a user-facing change?

```release-note
MultiKueue: Fix a bug that batch/v1 Job final state is not synced from Workload cluster to Management cluster when disabling the `MultiKueueBatchJobWithManagedBy` feature gate.
```

### CODE REVIEW

**Comment by mimowo** [comment]
/ok-to-test
please also tweak the release note to indicate this fix is for case when the feature gate is disabled

**Comment by mimowo** [comment]
@ichekrygin I think the change is very simple so I would be ok to approve it as is, but my preference would be to add an integration test under `test/integration/multikueue/jobs_test.go`. I think this would be similar to https://github.com/kubernetes-sigs/kueue/blob/ea83cef2adcfb700c457f5b4d34887f80fcb852c/test/integration/multikueue/jobs_test.go#L297
Tweaks needed:
- set MultiKueueBatchJobWithManagedBy to false
- drop `ManagedBy(kueue.MultiKueueControllerName).`
- drop the [section](https://github.com/kubernetes-sigs/kueue/blob/ea83cef2adcfb700c457f5b4d34887f80fcb852c/test/integration/multikueue/jobs_test.go#L358-L375)

Would you find cycles to add the test? Otherwise I can approve it and open follow up issue for contributors.

**Comment by mszadkow** [comment]
lgtm from my side too, just waiting for the decision on tests

**Review by tenzen-y — COMMENTED** [review]
Changes LGTM.
I agree with implementing integration tests as @mimowo described.

**Comment by tenzen-y** [comment]
Additionally, I would like to check if state is not propogated when local Job is suspended in UT: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/jobs/job/job_multikueue_adapter_test.go

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
MultiKueue: Fix a bug that batch/v1 Job final state is not synced from Workload cluster to Management cluster when disabling the `MultiKueueBatchJobWithManagedBy` feature gate.
```

**Comment by ichekrygin** [comment]
Hi everyone, thank you all for chiming in with your comments and suggestions.

I'll work on adding integration tests to cover this use case, as well as updating and improving the existing unit tests.

Regarding unit testing specifically: while it's currently possible to write tests for this logic, it's a bit cumbersome due to the structure of the `SyncJob` function. I believe this could be simplified by refactoring the logic to clearly separate the "create" and "update" flows, as shown below:

```go
func createRemoteJob(ctx context.Context, clnt client.Client, localJob *batchv1.Job, workloadName, workloadOrigin string) error {
	// ...
}

func syncRemoteJob(ctx context.Context, clnt client.Client, localJob, remoteJob *batchv1.Job) error {
	// ...
}

func (b *multiKueueAdapter) SyncJob(ctx context.Context, localClient client.Client, remoteClient client.Client, key types.NamespacedName, workloadName, origin string) error {
	localJob := &batchv1.Job{}
	if err := localClient.Get(ctx, key, localJob); err != nil {
		return fmt.Errorf("failed to retrieve local job: %w", err)
	}

	remoteJob := &batchv1.Job{}
	if err := remoteClient.Get(ctx, key, remoteJob); err != nil {
		if apierrors.IsNotFound(err) {
			return createRemoteJob(ctx, remoteClient, localJob, workloadName, origin)
		}
		return fmt.Errorf("failed to retrieve remote job: %w", err)
	}
	return syncRemoteJob(ctx, localClient, localJob, remoteJob)
}
```

This structure cleanly separates the concerns of handling Job creation vs. syncing an existing Job, and would make both unit and integration testing more focused and straightforward.

I’m aiming to keep my changes minimal and non-intrusive, but I’d be happy to contribute this refactor if the team is open to it.

 Please let me know your thoughts!

**Comment by mimowo** [comment]
Im ok with the refactor, but I would probably still prefer to unit test at the level of the exported function, so that downstream refactoring is still easy.

**Comment by ichekrygin** [comment]
> I would probably still prefer to unit test at the level of the exported function

Absolutely. Unit test coverage will be added for all three functions. The exported function will be covered in a simpler form, primarily focusing on error handling and the update vs. create branching logic, while more detailed tests will be written for the individual flow-specific functions.

**Comment by ichekrygin** [comment]
On the other hand, we could defer this refactor to a subsequent PR.
Speaking of which—what’s the preferred way to report general code cleanup opportunities in Kueue? Is there a common practice for filing such issues (e.g., via GitHub labels or discussion threads)?

**Comment by mimowo** [comment]
sgtm, but in the context of the PR, if the refactoring is not needed for adding the unit test, then I would go with minimal diff.

**Comment by mimowo** [comment]
> Speaking of which—what’s the preferred way to report general code cleanup opportunities in Kueue? Is there a common practice for filing such issues (e.g., via GitHub labels or discussion threads)?

for cleanups it is generally ok to submit PR directly if you have cycles time without issue.

However, If you observed something but don't have cycles, or you are unsure about the shape of the cleanup, then feel free to open an issue. There is community of people willing to grab such issues. You can also add /good-first-issue label.  We have the dedicated issue template for cleanups.

File: test/integration/multikueue/jobs_test.go [hunk 1]
```diff
@@ -264,33 +264,44 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Ordered, ginkgo.ContinueOnFailure,
...
 				createdJob.Status.CompletionTime = ptr.To(now)
 				g.Expect(worker1TestCluster.client.Status().Update(worker1TestCluster.ctx, &createdJob)).To(gomega.Succeed())
 			}, util.Timeout, util.Interval).Should(gomega.Succeed())
 
 			waitForWorkloadToFinishAndRemoteWorkloadToBeDeleted(wlLookupKey, finishJobReason)
+
+			// Assert local job status conditions.
+			localJob := &batchv1.Job{}
+			err := managerTestCluster.client.Get(managerTestCluster.ctx, client.ObjectKeyFromObject(job), localJob)
+			gomega.Expect(err).To(gomega.Succeed())
```
Comment (mimowo) [inline test/integration/multikueue/jobs_test.go]:
```suggestion
			gomega.Expect(managerTestCluster.client.Get(managerTestCluster.ctx, client.ObjectKeyFromObject(job), localJob)).To(gomega.Succeed())
```
nit, it is idiomatic to inline so that we don't add the variables.

File: test/integration/multikueue/jobs_test.go [hunk 2]
```diff
@@ -264,33 +264,44 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Ordered, ginkgo.ContinueOnFailure,
...
+			for _, condition := range testJobConditions {
+				gomega.Expect(assertJobStatusCondition(localJob.Status.Conditions, condition)).To(gomega.BeTrue())
```
Comment (mimowo) [inline test/integration/multikueue/jobs_test.go]: Actually this type of assert is quite difficult to debug, when it does not match. You only see false <> true.

Instead, it is usuaully better to use this method https://github.com/kubernetes-sigs/kueue/blob/9535437ade9479a691994dad69dbe093de50a3ef/test/integration/multikueue/jobs_test.go#L1263-L1268. Then it generates nice diff if something does not match (reason or status, message is ignored).

File: test/integration/multikueue/jobs_test.go (hunk 1 above)
Comment (ichekrygin) [reply test/integration/multikueue/jobs_test.go]: Ah.. right, was debugging error check - reverting.

File: test/integration/multikueue/jobs_test.go [hunk 3]
```diff
@@ -264,33 +264,44 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Ordered, ginkgo.ContinueOnFailure,
...
-					batchv1.JobCondition{
-						Type:               batchv1.JobComplete,
-						Status:             corev1.ConditionTrue,
-						LastProbeTime:      now,
-						LastTransitionTime: now,
-						Message:            finishJobReason,
-					},
-				)
+				testJobConditions[0] = batchv1.JobCondition{
+					Type:               batchv1.JobSuccessCriteriaMet,
```
Comment (mimowo) [inline test/integration/multikueue/jobs_test.go]: This may not be expected on older versions of k8s (before 1.32), please don't check.

File: test/integration/multikueue/jobs_test.go [hunk 4]
```diff
@@ -264,33 +264,43 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Ordered, ginkgo.ContinueOnFailure,
...
+				createdJob.Status.Conditions = append(createdJob.Status.Conditions, testJobConditions...)
 				createdJob.Status.Succeeded = 1
 				createdJob.Status.StartTime = ptr.To(now)
 				createdJob.Status.CompletionTime = ptr.To(now)
 				g.Expect(worker1TestCluster.client.Status().Update(worker1TestCluster.ctx, &createdJob)).To(gomega.Succeed())
 			}, util.Timeout, util.Interval).Should(gomega.Succeed())
 
 			waitForWorkloadToFinishAndRemoteWorkloadToBeDeleted(wlLookupKey, finishJobReason)
+
+			// Assert local job status conditions.
```
Comment (mimowo) [inline test/integration/multikueue/jobs_test.go]: I think this assert should be wrapped in Eventually. Otherwise we risk a flake.

File: test/integration/multikueue/jobs_test.go (hunk 3 above)
Comment (mimowo) [reply test/integration/multikueue/jobs_test.go]: I take it back. I see why you do it, because the validation requires by the API server.

**Comment by ichekrygin** [comment]
With the latest update, the failed assertion would look similar to:

```text
• [FAILED] [6.211 seconds]
MultiKueue [It] Should run a job on worker if admitted
/src/sigs.k8s.io/kueue/test/integration/multikueue/jobs_test.go:208

  [FAILED] Expected
      <[]v1.JobCondition | len:0, cap:0>: nil
  to contain element matching
      <*matchers.WithTransformMatcher | 0x140079a7340>: {
          Transform: <func(v1.JobCondition) v1.JobCondition>0x105cc6c40,
          Matcher: <*matchers.EqualMatcher | 0x14000ce2a00>{
              Expected: <v1.JobCondition>{
                  Type: "Complete",
                  Status: "True",
                  LastProbeTime: {
                      Time: 2025-06-11T22:32:44.248958-07:00,
                  },
                  LastTransitionTime: {
                      Time: 2025-06-11T22:32:44.248958-07:00,
                  },
                  Reason: "no reason",
                  Message: "Job finished successfully",
              },
          },
          transformArgType: <*reflect.rtype | 0x1064415c0>{
              t: {Size_: 0x70, PtrBytes: 0x68, Hash: 2396614163, TFlag: 7, Align_: 8, FieldAlign_: 8, Kind_: 25, Equal: 0x1051d0f80, GCData: 69, Str: 154914, PtrToThis: 4207680},
          },
          transformedValue: nil,
      }
  In [It] at: /src/sigs.k8s.io/kueue/test/integration/multikueue/jobs_test.go:302 @ 06/11/25 22:32:44.508
```

File: test/integration/multikueue/jobs_test.go [hunk 5]
```diff
@@ -264,10 +264,21 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Ordered, ginkgo.ContinueOnFailure,
...
+			now := metav1.Now()
+			// completedJobCondition that we will add to the remote job to indicate job completions,
+			// and the same condition that we expect to see on the local job status.
+			completedJobCondition := batchv1.JobCondition{
+				Type:               batchv1.JobComplete,
+				Status:             corev1.ConditionTrue,
+				LastProbeTime:      now,
+				LastTransitionTime: now,
+				Message:            finishJobReason,
+				Reason:             "no reason",
```
Comment (mimowo) [inline test/integration/multikueue/jobs_test.go]:
```suggestion
				Reason:             "FinishedByTestCode",
```
nit

**Comment by mimowo** [comment]
> With the latest update, the failed assertion would look similar to:

thx, this looks great, left some more nits.

**Comment by mimowo** [comment]
overall lgtm, but @ichekrygin please address this https://github.com/kubernetes-sigs/kueue/pull/5615#discussion_r2140719212

File: test/integration/multikueue/jobs_test.go (hunk 5 above)
Comment (ichekrygin) [reply test/integration/multikueue/jobs_test.go]: Ah, I see. I had used "no reason" temporarily to test the delta in assertions and forgot to remove it.
However, it looks like you're suggesting we should add a Reason value (which the original test didn't define)—is that a correct understanding?

Comment (mimowo) [reply test/integration/multikueue/jobs_test.go]: Feel free to leave it black. I just felt "no reason" looks a bit weird, but if you just drop it, then it is ok.

Comment (ichekrygin) [reply test/integration/multikueue/jobs_test.go]: It should be already removed in my latest update.

**Comment by mimowo** [comment]
/lgtm
/approve

The implementation lgtm, I have some concerns about tests in https://github.com/kubernetes-sigs/kueue/pull/5615#discussion_r2140713793, but we can address if proven to be problematic / flaky, for now we don't have evidence of that. 

Merging and cherrypicking since this is any important bugfix for the next patch release.

/cherrypick release-0.12
/cherrypick release-0.11
