### PR TITLE
Fix flaky integration tests for scheduling when WaitForPodsReady is enabled

### LINKED ISSUE #488: Flaky test for WaitForPodsReady if two workloads are considered in the same scheduling cycle
**What happened**:

/kind flake

Failing test:

```
Scheduler with WaitForPodsReady Suite: [It] SchedulerWithWaitForPodsReady when Scheduling workloads on clusterQueues Should block admission of one new workload if two are considered in the same scheduling cycle
```

**What you expected to happen**:

The test to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/415/pull-kueue-test-integration-main/1605630317664669696

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): main branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind failing-test
/kind flake
/kind bug

#### What this PR does / why we need it:

There are two newly added tests in scheduler_test.go which are failing occasionally due to different reasons: 
- fails due to a conflict when adding `PodsReady` condition to a newly admitted workload when another `WorkloadAdmitted` condition is added later by workload_reconclier.  Fixed by retrying of adding the condition.
- fails due to a random order at which workloads are admitted in the same scheduling cycle. Solved by adding a second before creating the second workload to ensure the order of admission.

#### Which issue(s) this PR fixes:

Fixes #488 

#### Special notes for your reviewer:

The proposed solutions are quick to do, but it seems both issues could be solved better.

First if we used SSA there should be no conflict between PodsReady and WorkloadAdmitted if used different field managers. 

Second we could modify the scheduler code to break the tie in a predictive manner, for example based on workload UIDs. Alternatively we could use a fake clock which will be handy anyway for testing timeouts.

Let me know if a follow up PRs are needed to improve if we are happy with the current solution.

### CODE REVIEW

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 1]
```diff
@@ -124,6 +127,8 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
 			ginkgo.By("creating two workloads but delaying cluster queue creation which has enough capacity")
 			prodWl := testing.MakeWorkload("prod-wl", ns.Name).Queue(prodQueue.Name).Request(corev1.ResourceCPU, "11").Obj()
 			gomega.Expect(k8sClient.Create(ctx, prodWl)).Should(gomega.Succeed())
+			// wait a second to ensure the CreationTimestamps differ and scheduler picks the first created to be admitted
+			time.Sleep(time.Second)
```
Comment (kerthcet) [inline test/integration/scheduler/podsready/scheduler_test.go:131]: If I understand correctly, this is because when sorting the entries in scheduling cycle, they have the same timestamp by chance?

Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:131]: Yes, and the resolution of the CreationTimestamp is 1s

Comment (alculquicondor) [reply test/integration/scheduler/podsready/scheduler_test.go:131]: or you could validate how many workloads are admitted (via metrics) without committing to which one is admitted.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve
/hold
in case you want to change the approach

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 1 above)
Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:131]: I'm thinking that when working on the timeouts I may need to introduce a fake clock and then the test could use it.

**Comment by mimowo** [comment]
/hold cancel
I think it is important to marge the fix quickly and potentially improve as a follow up. Using a fake clock may be also an alternative fix in the future.

**Comment by alculquicondor** [comment]
FTR: +1 on having a fake clock and SSA on controllers and/or test code.

**Comment by mimowo** [comment]
> FTR: +1 on having a fake clock and SSA on controllers and/or test code.

Ticketed as follow up issues: 
- https://github.com/kubernetes-sigs/kueue/issues/493
- https://github.com/kubernetes-sigs/kueue/issues/494
