### PR TITLE
Fix LeaderWorkerSet with manageJobsWithoutQueueName.

### LINKED ISSUE #4804: LeaderWorkerSet does not work when manageJobsWithoutQueuename is used
**What happened**:

LeaderWorkerSet does not work properly when manageJobsWithoutQueuename is used:
1. it does not run worker pods when queue-name is specified
2. it bypasses quota checks and runs leader pods when queue-name is not specified

**What you expected to happen**:

All pods are scheduling gated.

**How to reproduce it (as minimally and precisely as possible)**:

1. enable LWS integration and configure manageJobsWithoutQueuename: true
2. 
Create LWS:
```
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: leaderworkerset-multi-template
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  replicas: 3
  leaderWorkerTemplate:
    leaderTemplate:
      spec:
        containers:
        - name: nginx2
          image: nginx:1.14.2
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
          - containerPort: 8080
    size: 4
    workerTemplate:
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
          - containerPort: 8080
```

Issue: 
Pods don't run properly
```
> k get pods
NAME                                 READY   STATUS            RESTARTS   AGE
leaderworkerset-multi-template-0     1/1     Running           0          58s
leaderworkerset-multi-template-0-1   0/1     SchedulingGated   0          58s
leaderworkerset-multi-template-0-2   0/1     SchedulingGated   0          58s
leaderworkerset-multi-template-0-3   0/1     SchedulingGated   0          58s
leaderworkerset-multi-template-1     1/1     Running           0          58s
leaderworkerset-multi-template-1-1   0/1     SchedulingGated   0          58s
leaderworkerset-multi-template-1-2   0/1     SchedulingGated   0          58s
leaderworkerset-multi-template-1-3   0/1     SchedulingGated   0          58s
leaderworkerset-multi-template-2     1/1     Running           0          58s
leaderworkerset-multi-template-2-1   0/1     SchedulingGated   0          58s
leaderworkerset-multi-template-2-2   0/1     SchedulingGated   0          58s
leaderworkerset-multi-template-2-3   0/1     SchedulingGated   0          58s
```

Also, workloads look wrong:
```
> k get wl  
NAME                                                     QUEUE        RESERVED IN     ADMITTED   FINISHED   AGE
leaderworkerset-leaderworkerset-multi-template-0-49843   user-queue   cluster-queue   True                  7s
leaderworkerset-leaderworkerset-multi-template-1-0a62f   user-queue   cluster-queue   True                  7s
leaderworkerset-leaderworkerset-multi-template-2-67d82   user-queue   cluster-queue   True                  7s
pod-leaderworkerset-multi-template-0-1-b8d19                                                                7s
pod-leaderworkerset-multi-template-0-1deeb                                                                  7s
pod-leaderworkerset-multi-template-0-2-672ba                                                                7s
pod-leaderworkerset-multi-template-0-3-6a4d3                                                                7s
pod-leaderworkerset-multi-template-1-1-c39e1                                                                7s
pod-leaderworkerset-multi-template-1-2-b8ca2                                                                7s
pod-leaderworkerset-multi-template-1-3-aaf70                                                                7s
pod-leaderworkerset-multi-template-1-9472f                                                                  7s
pod-leaderworkerset-multi-template-2-1-1ec4c                                                                7s
pod-leaderworkerset-multi-template-2-2-e8505                                                                7s
pod-leaderworkerset-multi-template-2-3-8a7dc                                                                7s
pod-leaderworkerset-multi-template-2-b0301                                                                  7s
```

**Anything else we need to know?**:

I also tested without setting queueName, and this is also wrong - the leader pods start bypassing the quota checks.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix LeaderWorkerSet with manageJobsWithoutQueueName.

#### Which issue(s) this PR fixes:

Fixes #4804

#### Does this PR introduce a user-facing change?

```release-note
Fix bug which prevented using LeaderWorkerSet with manageJobsWithoutQueueName enabled. In particular, Kueue would create redundant workloads for each Pod, resulting in worker Pods suspended, while the leader Pods could bypass quota checks.
```

### CODE REVIEW

File: test/e2e/customconfigs/skipjobswithoutqueuename_test.go [hunk 1]
```diff
@@ -412,5 +415,50 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
 				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
 			})
 		})
+
+		ginkgo.It("should not suspend the pods created by a LeaderWorkerSet in the test namespace with queue-name label", func() {
```
Comment (mimowo) [inline test/e2e/customconfigs/skipjobswithoutqueuename_test.go:419]: Please also add a test confirming the LWS is properly suspended when "queue-name" is not set.

File: pkg/controller/jobframework/base_webhook.go [hunk 2]
```diff
@@ -67,7 +67,7 @@ func (w *BaseWebhook) Default(ctx context.Context, obj runtime.Object) error {
 	log := ctrl.LoggerFrom(ctx)
 	log.V(5).Info("Applying defaults")
 	ApplyDefaultLocalQueue(job.Object(), w.Queues.DefaultLocalQueueExist)
-	if err := ApplyDefaultForSuspend(ctx, job, w.Client, w.ManageJobsWithoutQueueName, w.ManagedJobsNamespaceSelector); err != nil {
+	if err := ApplyDefaultForSuspend(ctx, w.Client, job, w.Client, w.ManageJobsWithoutQueueName, w.ManagedJobsNamespaceSelector); err != nil {
```
Comment (dgrove-oss) [inline pkg/controller/jobframework/base_webhook.go:70]: We're already passing w.Client as a parameter.

File: pkg/controller/jobframework/defaults.go [hunk 3]
```diff
@@ -33,9 +33,9 @@ import (
 	"sigs.k8s.io/kueue/pkg/queue"
 )
 
-func ApplyDefaultForSuspend(ctx context.Context, job GenericJob, k8sClient client.Client,
+func ApplyDefaultForSuspend(ctx context.Context, c client.Client, job GenericJob, k8sClient client.Client,
```
Comment (dgrove-oss) [inline pkg/controller/jobframework/defaults.go:36]: c and k8sClient are the same; only pass it once.

File: pkg/controller/jobframework/base_webhook.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/controller/jobframework/base_webhook.go]: Wow, thanks!

File: pkg/controller/jobframework/defaults.go (hunk 3 above)
Comment (mbobrovskyi) [reply pkg/controller/jobframework/defaults.go]: Fixed.

**Comment by mimowo** [comment]
/retitle WIP: Fix LeaderWorkerSet with manageJobsWithoutQueueName. 
Please ping me when rebased and ready for review.

**Comment by mimowo** [comment]
And along with @dgrove-oss for initially pass

File: pkg/controller/jobs/pod/pod_webhook.go [hunk 4]
```diff
@@ -190,20 +179,23 @@ func (w *PodWebhook) Default(ctx context.Context, obj runtime.Object) error {
...
 	}
 
 	if suspend {
 		controllerutil.AddFinalizer(pod.Object(), podconstants.PodFinalizer)
-
-		if pod.pod.Labels == nil {
-			pod.pod.Labels = make(map[string]string)
-		}
-		pod.pod.Labels[constants.ManagedByKueueLabelKey] = constants.ManagedByKueueLabelValue
-
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/pod/pod_webhook.go:202]: In the `LeaderWorkerSet` integration, we set default values via the `LeaderWorkerSetPodReconciler` after `Pod` creation. 

https://github.com/kubernetes-sigs/kueue/blob/13574fcc4dc829cc86c36e3e15fc4d68739f074f/pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go#L127-L131

We are using this approach because we should wait for all `LeaderWorkerSet` labels to be applied and thats why we can't set it in the `Webhook` side.

It's possible that a `Pod` has the `ManagedByKueueLabel` but doesn't yet have the queue-name set and doesn't have prebuilt workload label. As a result, the `JobFramework` won't skip it, and it may create a workload for each `Pod`. 

We should ensure that we wait for the `LeaderWorkerSetPodReconciler` to apply the default values before setting the `ManagedByKueueLabel`.

File: pkg/controller/jobframework/defaults.go [hunk 5]
```diff
@@ -45,14 +45,13 @@ func ApplyDefaultForSuspend(ctx context.Context, job GenericJob, k8sClient clien
 	return nil
 }
 
-// +kubebuilder:rbac:groups="apps",resources=replicasets,verbs=get;list;watch
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/defaults.go:48]: Moved to pkg/controller/jobs/deployment/deployment_controller.go

File: test/e2e/customconfigs/skipjobswithoutqueuename_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/e2e/customconfigs/skipjobswithoutqueuename_test.go]: Done

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go [hunk 6]
```diff
@@ -625,6 +628,75 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.List(ctx, pods, client.MatchingLabels{
+						leaderworkersetv1.SetNameLabelKey: lws.Name,
+					}, client.InNamespace(lws.Namespace))).Should(gomega.Succeed())
+					g.Expect(pods.Items).To(gomega.HaveLen(3))
+					for _, pod := range pods.Items {
+						g.Expect(pod.Status.Phase).Should(gomega.Equal(corev1.PodRunning))
+					}
+				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+			})
```
Comment (mbobrovskyi) [inline test/e2e/customconfigs/managejobswithoutqueuename_test.go:675]: FYI: The queue-name label in LWS is immutable.

https://github.com/kubernetes-sigs/kueue/blob/89545d53c515daa07029b29577b5ec68de5b86f1/pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go#L138-L142

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go [hunk 7]
```diff
@@ -625,6 +628,75 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
...
+		})
+
+		ginkgo.It("should suspend the pods created by a LeaderWorkerSet in the test namespace without queue-name label", func() {
```
Comment (mbobrovskyi) [inline test/e2e/customconfigs/managejobswithoutqueuename_test.go:678]: FYI: The queue-name label in LWS is immutable.

https://github.com/kubernetes-sigs/kueue/blob/89545d53c515daa07029b29577b5ec68de5b86f1/pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go#L138-L142

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go [hunk 8]
```diff
@@ -625,6 +628,75 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
 				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
 			})
 		})
+
+		ginkgo.It("should not suspend the pods created by a LeaderWorkerSet in the test namespace with queue-name label", func() {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply test/e2e/customconfigs/managejobswithoutqueuename_test.go:632]: Yes, this PR fixing both cases.

> 1. it does not run worker pods when queue-name is specified

https://github.com/kubernetes-sigs/kueue/blob/42a03da0c49ed54d38f1f198f25a05ce19dd7646/test/e2e/customconfigs/managejobswithoutqueuename_test.go#L632

> 2. it bypasses quota checks and runs leader pods when queue-name is not specified

https://github.com/kubernetes-sigs/kueue/blob/42a03da0c49ed54d38f1f198f25a05ce19dd7646/test/e2e/customconfigs/managejobswithoutqueuename_test.go#L678

[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply test/e2e/customconfigs/managejobswithoutqueuename_test.go:632]: Also I extended second test case.

File: pkg/controller/jobframework/defaults.go (hunk 5 above)
Comment (mimowo) [reply pkg/controller/jobframework/defaults.go:48]: sgtm, we could even make another cleanup PR of this, but no strong view.

File: pkg/controller/jobs/deployment/deployment_webhook.go [hunk 9]
```diff
@@ -81,12 +82,13 @@ func (wh *Webhook) Default(ctx context.Context, obj runtime.Object) error {
 		if deployment.Spec.Template.Labels == nil {
 			deployment.Spec.Template.Labels = make(map[string]string, 1)
 		}
+		deployment.Spec.Template.Labels[constants.ManagedByKueueLabelKey] = constants.ManagedByKueueLabelValue
 		queueName := jobframework.QueueNameForObject(deployment.Object())
 		if queueName != "" {
-			deployment.Spec.Template.Labels[constants.QueueLabel] = queueName
+			deployment.Spec.Template.Labels[controllerconstants.QueueLabel] = queueName
```
Comment (mimowo) [inline pkg/controller/jobs/deployment/deployment_webhook.go:88]: Please revert drive-by cleanups. The PR is already large.

File: pkg/controller/jobs/deployment/deployment_controller.go [hunk 10]
```diff
@@ -38,18 +39,26 @@ const (
...
-		AddToScheme:    appsv1.AddToScheme,
-		DependencyList: []string{"pod"},
+		SetupIndexes:           SetupIndexes,
+		NewReconciler:          jobframework.NewNoopReconcilerFactory(gvk),
+		GVK:                    gvk,
+		SetupWebhook:           SetupWebhook,
+		JobType:                &appsv1.Deployment{},
+		AddToScheme:            appsv1.AddToScheme,
+		DependencyList:         []string{"pod"},
+		IsManagingObjectsOwner: isDeployment,
```
Comment (mimowo) [inline pkg/controller/jobs/deployment/deployment_controller.go:49]: This looks ok-ish, but I have no clue why we need to change it, please clarify.

File: pkg/controller/jobs/pod/pod_webhook.go [hunk 11]
```diff
@@ -190,20 +179,23 @@ func (w *PodWebhook) Default(ctx context.Context, obj runtime.Object) error {
 		}
 
 		suspend = jobframework.QueueNameForObject(pod.Object()) != "" || w.manageJobsWithoutQueueName
+		if suspend {
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_webhook.go:182]: Why is this moved?

File: pkg/controller/jobs/pod/pod_webhook.go [hunk 12]
```diff
@@ -190,20 +179,23 @@ func (w *PodWebhook) Default(ctx context.Context, obj runtime.Object) error {
...
-		if pod.pod.Labels == nil {
-			pod.pod.Labels = make(map[string]string)
-		}
-		pod.pod.Labels[constants.ManagedByKueueLabelKey] = constants.ManagedByKueueLabelValue
-
 		gate(&pod.pod)
 
 		if features.Enabled(features.TopologyAwareScheduling) {
 			if val, ok := pod.pod.Annotations[kueuealpha.PodGroupPodIndexLabelAnnotation]; ok {
+				if pod.pod.Labels == nil {
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_webhook.go:196]: This does not seem related to the issue, because it does not say about TAS. Is it a bugfix for TAS? If so, can we move to a dedicated bugfix?

File: pkg/controller/jobs/statefulset/statefulset_webhook.go [hunk 13]
```diff
@@ -32,14 +33,16 @@ import (
...
+	"sigs.k8s.io/kueue/pkg/constants"
+	controllerconstants "sigs.k8s.io/kueue/pkg/controller/constants"
 	"sigs.k8s.io/kueue/pkg/controller/jobframework"
 	podconstants "sigs.k8s.io/kueue/pkg/controller/jobs/pod/constants"
 	"sigs.k8s.io/kueue/pkg/queue"
 )
 
 type Webhook struct {
 	client                       client.Client
+	log                          logr.Logger
```
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go:45]: I don't see it used.

File: pkg/controller/jobs/statefulset/statefulset_reconciler.go [hunk 14]
```diff
@@ -170,8 +182,18 @@ func (r *Reconciler) handle(obj client.Object) bool {
...
+
+	ctx := context.Background()
+	log := r.log.WithValues("statefulset", klog.KObj(sts))
+	ctrl.LoggerInto(ctx, log)
+
 	// Handle only statefulset managed by kueue.
-	return jobframework.IsManagedByKueue(sts)
+	suspend, err := jobframework.WorkloadShouldBeSuspended(ctx, sts, r.client, r.manageJobsWithoutQueueName, r.managedJobsNamespaceSelector)
+	if err != nil {
+		log.Error(err, "Failed to determine suspend state")
```
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_reconciler.go:193]:
```suggestion
		log.Error(err, "Failed to determine if the StatefulSet should be managed by Kueue")
```
We are not determining the suspend state. We are determining if we should manage - if we manage then we change the suspend state accordingly.

File: pkg/controller/jobs/deployment/deployment_webhook.go [hunk 15]
```diff
@@ -81,12 +82,13 @@ func (wh *Webhook) Default(ctx context.Context, obj runtime.Object) error {
 		if deployment.Spec.Template.Labels == nil {
 			deployment.Spec.Template.Labels = make(map[string]string, 1)
 		}
+		deployment.Spec.Template.Labels[constants.ManagedByKueueLabelKey] = constants.ManagedByKueueLabelValue
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/jobs/deployment/deployment_webhook.go:85]: Yes, but deployment is suspend by parent and  I need this changes due to https://github.com/kubernetes-sigs/kueue/pull/4808#discussion_r2039303467.

File: pkg/controller/jobs/deployment/deployment_controller.go (hunk 10 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/deployment/deployment_controller.go:49]: We need this for case `Pod -> Deployment -> AppWrapper`.

File: pkg/controller/jobs/pod/pod_webhook.go (hunk 11 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/pod/pod_webhook.go:182]: https://github.com/kubernetes-sigs/kueue/pull/4808/files/42a03da0c49ed54d38f1f198f25a05ce19dd7646#r2039303467

Comment (mbobrovskyi) [reply pkg/controller/jobs/pod/pod_webhook.go:182]: https://github.com/kubernetes-sigs/kueue/pull/4808/files/42a03da0c49ed54d38f1f198f25a05ce19dd7646#r2039303467

Comment (mbobrovskyi) [reply pkg/controller/jobs/pod/pod_webhook.go:182]: https://github.com/kubernetes-sigs/kueue/pull/4808#discussion_r2039303467

File: pkg/controller/jobs/pod/pod_webhook.go (hunk 12 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/pod/pod_webhook.go:196]: This is not a fix. This changes need because I removed https://github.com/kubernetes-sigs/kueue/pull/4808/files/42a03da0c49ed54d38f1f198f25a05ce19dd7646#diff-8653db7737ac7710352223a2af7723aa2def7cc433c73b1d151c7502d2a9af17L198-L200

File: pkg/controller/jobs/pod/pod_webhook.go [hunk 16]
```diff
@@ -164,19 +163,9 @@ func (w *PodWebhook) Default(ctx context.Context, obj runtime.Object) error {
...
-				err := w.client.Get(ctx, client.ObjectKey{Name: owner.Name, Namespace: pod.pod.GetNamespace()}, rs)
-				if err != nil {
-					return fmt.Errorf("failed to get replicaset: %w", err)
-				}
-				owner = metav1.GetControllerOf(rs)
-			}
-			if owner != nil && jobframework.IsOwnerIntegrationEnabled(owner) {
-				return nil
-			}
+		ancestorJob, err := jobframework.FindAncestorJobManagedByKueue(ctx, w.client, nil, pod.Object(), w.manageJobsWithoutQueueName)
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_webhook.go:166]: Actually, this change looks very suspicious. Because assume we have a pod group which is not managed by a parent inetgration. Shouldn't we still execute the LocalQueueDefaulting? Maybe this is not covered by e2e test, but we need to make sure this works ok with LQ defaulting.

File: pkg/controller/jobs/deployment/deployment_controller.go (hunk 10 above)
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_controller.go:49]: I don't understand why - can you clarify.

File: pkg/controller/jobs/deployment/deployment_webhook.go (hunk 9 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/deployment/deployment_webhook.go:88]: Than not sure how to name `sigs.k8s.io/kueue/pkg/constants` package.

https://github.com/kubernetes-sigs/kueue/blob/45c67c81a3dd21a86c84dc7384556658bdd72caf/pkg/controller/jobs/deployment/deployment_webhook.go#L31-L32

`pkgconstants` sound weird.

File: pkg/controller/jobs/deployment/deployment_webhook.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_webhook.go:85]: I'm not convinced why we need it now, and we didn't need before. And it makes me anxious about issues during upgrade. Say from 0.11.1 to 0.11.4.

File: pkg/controller/jobs/deployment/deployment_webhook.go (hunk 9 above)
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_webhook.go:88]: The change itself might be ok, but it just does not belong to the PR, we can have a preparatory PR, but again, I'm not sure why we need any changes to the labels of deployment

**Comment by mimowo** [comment]
/hold
To avoid accidental merge. There are too many open questions at the moment IMO. The PR is quite large and hard to comprehend, I suspect there might be a regression wrt to LQ defaulting, and the new label on Deployment makes me anxious about upgrades. We need to carefully plan the fix, and split into smaller PRs as much as possible.

File: pkg/controller/jobs/deployment/deployment_webhook.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/jobs/deployment/deployment_webhook.go:85]: Previously, this wasn't needed because the logic was in the pod_webhook. I’ve moved it to the serving workload webhooks, which is required for the LeaderWorkerSet implementation.

[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_webhook.go:85]: Do you mean this logic: https://github.com/kubernetes-sigs/kueue/pull/4808/files#diff-8653db7737ac7710352223a2af7723aa2def7cc433c73b1d151c7502d2a9af17L167-L179, or some other?

I would actually prefer to keep the logic if it avoids the need to add the label. Especially if we need to cherry-pick.

File: pkg/controller/jobs/deployment/deployment_controller.go (hunk 10 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/deployment/deployment_controller.go:49]: Yes, this function is using to compare ownerReference with Deployment.

https://github.com/kubernetes-sigs/kueue/blob/45c67c81a3dd21a86c84dc7384556658bdd72caf/pkg/controller/jobframework/integrationmanager.go#L190-L196

https://github.com/kubernetes-sigs/kueue/blob/45c67c81a3dd21a86c84dc7384556658bdd72caf/pkg/controller/jobframework/integrationmanager.go#L339-L346

If this is true, we can return the JobType, and we can get empty Object for this Job. If false thats means that this this integration is not managed by Kueue.

https://github.com/kubernetes-sigs/kueue/blob/45c67c81a3dd21a86c84dc7384556658bdd72caf/pkg/controller/jobframework/reconciler.go#L637-L638

File: pkg/controller/jobs/deployment/deployment_webhook.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/jobs/deployment/deployment_webhook.go:85]: this one https://github.com/kubernetes-sigs/kueue/pull/4808#discussion_r2039303467

File: pkg/controller/jobs/deployment/deployment_controller.go [hunk 17]
```diff
@@ -38,18 +39,26 @@ const (
...
 	}))
 }
 
+func isDeployment(ref *metav1.OwnerReference) bool {
+	return ref.Kind == "Deployment" && ref.APIVersion == "apps/v1"
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/jobs/deployment/deployment_controller.go:54]: This is a really interesting case. I initially thought we needed it to disable certain integrations. I'm not entirely sure, though - maybe we can optimize it in a follow-up PR for other integrations as well.

File: pkg/controller/jobs/pod/pod_webhook.go (hunk 16 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/pod/pod_webhook.go:166]: I think you're right - that's the current logic we have. 

https://github.com/kubernetes-sigs/kueue/blob/64ae56ba621d8f7acf122b77c77dfc017ffe530e/pkg/controller/jobs/pod/pod_webhook.go#L177-L179

I'm not sure we should fix it in this PR.

Comment (mimowo) [reply pkg/controller/jobs/pod/pod_webhook.go:166]: I mean the case of plain pod - no owner - in that case we don't step into `if owner != nil && jobframework.IsOwnerIntegrationEnabled(owner) {` at all. Yet, in this case we would do the logic below for defaulting. Now, we skip the logic for defaulting as ancestorJob == nil. So, I think the PR in the current form regresses the case, unless I'm missing something.

Comment (mimowo) [reply pkg/controller/jobs/pod/pod_webhook.go:166]: >  Now, we skip the logic for defaulting as ancestorJob == nil.

My mistake, sorry, if ancestorJob == nil the code will actually move forward to LQ defaulting as before.

File: pkg/controller/jobs/deployment/deployment_controller.go (hunk 10 above)
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_controller.go:49]: ack, thanks, I see it is implemented analogously for other types, such as Job and JobSet. Feel free to resolve.

File: pkg/controller/jobs/deployment/deployment_controller.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_controller.go:54]: Yes, I see your implementation aligns with the implementation for other types, such as Job. So, I'm ok with the current approach. However, I don't see why we need IsManagingObjectsOwner at all - this could be checked based on GVK only. However, I agree it could be a follow up.

File: pkg/controller/jobs/deployment/deployment_webhook.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_webhook.go:85]: I see, thanks for explaining.

File: pkg/controller/jobs/pod/pod_webhook.go (hunk 11 above)
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_webhook.go:182]: Ok, got it. Thanks

File: pkg/controller/jobs/pod/pod_webhook.go (hunk 12 above)
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_webhook.go:196]: ack

File: pkg/util/testingjobs/statefulset/wrappers.go [hunk 18]
```diff
@@ -96,8 +98,24 @@ func (ss *StatefulSetWrapper) Name(n string) *StatefulSetWrapper {
...
-	ss.OwnerReferences = append(ss.OwnerReferences, ownerReference)
+// UID updates the uid of the StatefulSet
+func (ss *StatefulSetWrapper) UID(uid string) *StatefulSetWrapper {
+	ss.ObjectMeta.UID = types.UID(uid)
+	return ss
+}
+
+// OwnerReference adds a ownerReference to the StatefulSet.
+func (ss *StatefulSetWrapper) OwnerReference(ownerName string, ownerGVK schema.GroupVersionKind) *StatefulSetWrapper {
+	ss.ObjectMeta.OwnerReferences = append(
```
Comment (mimowo) [inline pkg/util/testingjobs/statefulset/wrappers.go:109]: Can we reuse AppendOwnerReference in pkg/util/testing/wrappers.go?

File: pkg/controller/jobs/deployment/deployment_webhook.go (hunk 9 above)
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_webhook.go:88]: Ack, after I understand why we change Deployment I'm ok with that change.

**Comment by mimowo** [comment]
/hold cancel
I think I now understand the changes before my main doubts:
1. there is no issue for the ManagedByKueueLabelKey label, the logic for setting it is moved from pod_webhook to webhooks corresponding to the Deploymnent, LWS ans STS, and it is set on Pod Templates. This is actually the main part of the fix for LWS as it allows to delay setting the ManagedByKueueLabelKey on LWS Pods, and set the label along with other required labels.
2. There is no change around LQ defaulting. I just made a mistake intepreting the code for the plain pod scenario, as admitted here: https://github.com/kubernetes-sigs/kueue/pull/4808#discussion_r2039741201. Still, the code is quite complex, and I think some bugs might be lurking there. 

I would love to see a little bit more of manual testing with LWS and LQ defaulting. In any case, LQ defaulting is still alpha, so I'm not too worried.

File: pkg/controller/jobframework/reconciler.go [hunk 19]
```diff
@@ -652,9 +652,11 @@ func FindAncestorJobManagedByKueue(ctx context.Context, c client.Client, record
 		}
 		currentObj = parentObj
 		if len(seen) > managedOwnersChainLimit {
-			record.Eventf(jobObj, corev1.EventTypeWarning, ReasonJobNestingTooDeep,
-				"Terminated search for Kueue-managed Job because ancestor depth exceeded limit of %d", managedOwnersChainLimit,
-			)
+			if record != nil {
```
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/jobframework/reconciler.go]: Done on [1833af8](https://github.com/kubernetes-sigs/kueue/pull/4808/commits/1833af82125ed7b930c37f697556b43d8e668a5a)

File: pkg/util/testingjobs/statefulset/wrappers.go (hunk 18 above)
Comment (mbobrovskyi) [reply pkg/util/testingjobs/statefulset/wrappers.go]: Done

**Comment by mimowo** [comment]
Proposal, I think the issue actually prevented using LWS with manageJobsWithoutQueueName. So we can emphasize this in the first sentence, then details.
/release-note-edit
```release-note
Fix bug which prevented using LeaderWorkerSet with manageJobsWithoutQueueName enabled. In particular, Kueue would create redundant workloads for each Pod, resulting in worker Pods suspended, while the leader Pods could bypass quota checks.
```

**Comment by mimowo** [comment]
/lgtm
/approve
/cherry-pick release-0.11
I think this is a great fix.

**Comment by mbobrovskyi** [comment]
I think we need to cherry-pick https://github.com/kubernetes-sigs/kueue/pull/4859 first.

**Comment by mbobrovskyi** [comment]
This PR also related to other. So I will create manual one.

**Comment by mbobrovskyi** [comment]
https://github.com/kubernetes-sigs/kueue/pull/4936

File: pkg/controller/jobs/deployment/deployment_controller.go (hunk 10 above)
Comment (mimowo) [reply pkg/controller/jobs/deployment/deployment_controller.go:49]: Opened https://github.com/kubernetes-sigs/kueue/issues/4940  to explore it more and cleanup potentially.
