### PR TITLE
Initialise FairSharing option when building options for cache.

### LINKED ISSUE #2422: [FairSharing] ClusterQueue status does not report stats
**What happened**:

When using FairSharing, the ClusterQueue.status.fairSharing field remains empty even if the ClusterQueue is borrowing.

**What you expected to happen**:

The ClusterQueue.status.fairSharing.weightedShare to be updated as soon as the cluster queue starts borrowing.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster like this:
```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-a"
spec:
  cohort: "cohort"
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-b"
spec:
  cohort: "cohort"
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-c"
spec:
  cohort: "cohort"
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "queue-a"
spec:
  clusterQueue: "cq-a"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "queue-b"
spec:
  clusterQueue: "cq-b"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "queue-c"
spec:
  clusterQueue: "cq-c"
```
Then create 4 Jobs like this:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  labels:
    kueue.x-k8s.io/queue-name: queue-a
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["10m"]
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Never
```
Then, inspect the clusterqueue-a:
```yaml
status:
  admittedWorkloads: 4
  conditions:
  - lastTransitionTime: "2024-06-17T10:24:20Z"
    message: Can admit new workloads
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Active
  fairSharing: {}
  flavorsReservation:
  - name: default-flavor
    resources:
    - borrowed: "3"
      name: cpu
      total: "12"
    - borrowed: "0"
      name: memory
      total: 2400Mi
  flavorsUsage:
  - name: default-flavor
    resources:
    - borrowed: "3"
      name: cpu
      total: "12"
    - borrowed: "0"
      name: memory
      total: 2400Mi
  pendingWorkloads: 0
  reservingWorkloads: 4
```
Issue: `status.fairSharing.weightedShare` is empty.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Initialise FairSharing option when building options for cache.

#### Which issue(s) this PR fixes:

Fixes #2422 

#### Special notes for your reviewer:
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kueue.x-k8s.io/v1beta1","kind":"ClusterQueue","metadata":{"annotations":{},"name":"cq-a"},"spec":{"cohort":"cohort","namespaceSelector":{},"resourceGroups":[{"coveredResources":["cpu","memory"],"flavors":[{"name":"default-flavor","resources":[{"name":"cpu","nominalQuota":9},{"name":"memory","nominalQuota":"36Gi"}]}]}]}}
  creationTimestamp: "2024-06-17T11:54:20Z"
  finalizers:
  - kueue.x-k8s.io/resource-in-use
  generation: 1
  name: cq-a
  resourceVersion: "1177"
  uid: cd4c73e6-1ec4-4f20-9ba5-ee089272b138
spec:
  cohort: cohort
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Never
    withinClusterQueue: Never
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - cpu
    - memory
    flavors:
    - name: default-flavor
      resources:
      - name: cpu
        nominalQuota: "9"
      - name: memory
        nominalQuota: 36Gi
  stopPolicy: None
status:
  admittedWorkloads: 4
  conditions:
  - lastTransitionTime: "2024-06-17T11:54:20Z"
    message: Can admit new workloads
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Active
  fairSharing:
    weightedShare: 111
  flavorsReservation:
  - name: default-flavor
    resources:
    - borrowed: "3"
      name: cpu
      total: "12"
    - borrowed: "0"
      name: memory
      total: 2400Mi
  flavorsUsage:
  - name: default-flavor
    resources:
    - borrowed: "3"
      name: cpu
      total: "12"
    - borrowed: "0"
      name: memory
      total: 2400Mi
  pendingWorkloads: 0
  reservingWorkloads: 4
```

#### Does this PR introduce a user-facing change?

```release-note
Initialise FairSharing option when building options for cache.
```

### CODE REVIEW

File: cmd/kueue/main.go [hunk 1]
```diff
@@ -160,6 +160,9 @@ func main() {
 		cacheOptions = append(cacheOptions, cache.WithExcludedResourcePrefixes(cfg.Resources.ExcludeResourcePrefixes))
 		queueOptions = append(queueOptions, queue.WithExcludedResourcePrefixes(cfg.Resources.ExcludeResourcePrefixes))
 	}
+	if cfg.FairSharing != nil {
+		cacheOptions = append(cacheOptions, cache.WithFairSharing(cfg.FairSharing.Enable))
```
Comment (mimowo) [inline cmd/kueue/main.go:164]: I'm wondering what is the best way to cover this with a test. We already have integration tests, but it slipped. Maybe it is a sign we should have an integration test suite for fair sharing, wdyt @alculquicondor ? In order to merge this quickly I'm ok with adding the test as a follow up.

Comment (trasc) [reply cmd/kueue/main.go:164]: It slipped because the integrations test don't use the main Kueue config,  an e2e test can cover this.

Comment (mimowo) [reply cmd/kueue/main.go:164]: Oh yes, I meant e2e

Comment (alculquicondor) [reply cmd/kueue/main.go:164]: Right, let's add an E2E test as a follow up.

**Review by alculquicondor — COMMENTED** [review]
/approve

File: cmd/kueue/main.go (hunk 1 above)
Comment (mimowo) [reply cmd/kueue/main.go:164]: I opened the issue to keep track of it: https://github.com/kubernetes-sigs/kueue/issues/2431

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Fix missing fairSharingStatus in ClusterQueue
```
