### PR TITLE
WaitForPodsReady: Reset .status.requeueState.count once the workload is deactivated

### LINKED ISSUE #2174: WaitForPodsReady: After a Workload is deactivated by exceeded the backoffLimit, the reactivated Workload could be immediately re-deactivated
**What happened**:

After the Workload is deactivated with `.spec.active=false` by exceeded re-queueing backoffLimit, if we manually reactivate it with `.spec.active=true`, it is immediately re-deactivated.

The root cause is the race condition between the workload-controller and kueue-scheduler by not resetting the `.status.requeueState.count` in the Workload while deactivating the Workload here: https://github.com/kubernetes-sigs/kueue/blob/0f0a315fe11704ee85bdc72fdc7f46d76d935a8e/pkg/controller/core/workload_controller.go#L196-L206.

So, the kueue-scheduler could pop the reactivated Workload from the queue before the `.status.requeueState.count` in the Workload here: https://github.com/kubernetes-sigs/kueue/blob/0f0a315fe11704ee85bdc72fdc7f46d76d935a8e/pkg/controller/core/workload_controller.go#L166-L170

Not resetting the `status.requeueState.count` is the intended behavior to notify users how many times the Job was requeued.
But, to avoid this race condition, we need to reset the `count` while deactivating the Workload.

**What you expected to happen**:
The reactivated Workload should be tried to re-queue until backoffLimit.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
If the Workload is deactivated, the workload resets the requeueState to avoid a race condition between the kueue-scheduler and the workload controller in the case of the deactivated workload.

When the workload is deactivated by exceeding the backoffLimitCount, the workload is added the `The workload is deactivated due to exceeding the maximum number of re-queuing retries`. I will introduce a dedicated reason in another PR to focus on fixing the bug.

#### Which issue(s) this PR fixes:

Fixes #2174

#### Special notes for your reviewer:
The cherry-pick was manually created here https://github.com/kubernetes-sigs/kueue/pull/2220.
Because we have significant changes in the mechanism of re-queuing between v0.6 and the main branch.

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug that causes the reactivated Workload to be immediately deactivated even though it doesn't exceed the backoffLimit.
```

### CODE REVIEW

File: pkg/controller/core/workload_controller_test.go [hunk 1]
```diff
@@ -835,24 +833,9 @@ func TestReconcile(t *testing.T) {
...
-					gotRequeueState := gotWorkload.Status.RequeueState
-					if gotRequeueState != nil && gotRequeueState.RequeueAt != nil {
-						if !gotRequeueState.RequeueAt.Equal(requeueState.RequeueAt) {
-							t.Errorf("Unexpected requeueState.requeueAt; gotRequeueAt %v needs to be after requeueAt %v", requeueState.RequeueAt, gotRequeueState.RequeueAt)
-						}
-					} else {
-						t.Errorf("Unexpected nil requeueState.requeuAt; requeueState.requeueAt shouldn't be nil")
-					}
-				}
-			}
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller_test.go:854]: This verification has been invalid since we introduced the fake clock.

**Comment by alculquicondor** [comment]
cc @mimowo

File: pkg/controller/core/workload_controller.go [hunk 2]
```diff
@@ -193,16 +186,26 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
+	} else {
+		var updated, evicted bool
+		if wl.Status.RequeueState != nil {
+			wl.Status.RequeueState = nil
+			updated = true
 		}
-		if wl.Status.Admission != nil {
-			metrics.ReportEvictedWorkloads(string(wl.Status.Admission.ClusterQueue), kueue.WorkloadEvictedByDeactivation)
+		if !apimeta.IsStatusConditionTrue(wl.Status.Conditions, kueue.WorkloadEvicted) {
+			workload.SetEvictedCondition(&wl, kueue.WorkloadEvictedByDeactivation, "The workload is deactivated")
```
Comment (alculquicondor) [inline pkg/controller/core/workload_controller.go:196]: What I don't like about this is that we are losing context as to why the workload was deactivated.

In addition to adding the evicted condition here, could we add it inside `reconcileNotReadyTimeout` so that, if the Kueue controller doesn't restart of fail to send the status update, we keep that information in the Evicted reason and message?

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 3]
```diff
@@ -265,31 +265,28 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
...
 			time.Sleep(podsReadyTimeout)
 			util.FinishEvictionForWorkloads(ctx, k8sClient, prodWl)
+
 			util.ExpectWorkloadsToHaveQuotaReservation(ctx, k8sClient, prodClusterQ.Name, prodWl)
 			util.ExpectQuotaReservedWorkloadsTotalMetric(prodClusterQ, 3)
 			util.ExpectAdmittedWorkloadsTotalMetric(prodClusterQ, 3)
-			time.Sleep(podsReadyTimeout)
 			ginkgo.By("evicted re-admitted workload should have 2 in the re-queue count")
 			util.ExpectWorkloadToHaveRequeueCount(ctx, k8sClient, client.ObjectKeyFromObject(prodWl), ptr.To[int32](2))
+			time.Sleep(podsReadyTimeout)
```
Comment (alculquicondor) [inline test/integration/scheduler/podsready/scheduler_test.go:274]: is this a real sleep?
can it be made a few miliseconds just for this test?

File: pkg/controller/core/workload_controller.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/core/workload_controller.go:196]: IIUC, we have the `status.requeueState` in this function, just before we clean it just above, can we use it in the message? We probably don't want to set "WorkloadInactive" reason prior to setting `active=false`.

I think long-term the cleanest would be if `active` was in status, then we could do the following in one request:
```yaml
active: false
conditions:
  Evicted: true
  Reason: PodsReadyTimeoutExceeded
  Message: The PodsReady timeout of 5min is exceeded
  Deactivated: true
  Reason: PodsReadyBackoffExceeded
  Message: Deactivated the workload after 5 attempts due to exceeding the PodsReady timeout.
```

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 3 above)
Comment (alculquicondor) [reply test/integration/scheduler/podsready/scheduler_test.go:274]: ping @tenzen-y

File: pkg/controller/core/workload_controller.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:196]: > IIUC, we have the status.requeueState in this function, just before we clean it just above, can we use it in the message, for example to say "The workload is deactivated due to 5 failed attempts to run all pods within the PodsReady timeout"? We probably don't want to set "WorkloadInactive" reason prior to setting active=false.

@mimowo Actually, we have the similar discussion here: https://github.com/kubernetes-sigs/kueue/issues/2175
So, could we work on enhancing the reason as another feature to focus on fixing the bug?

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 3 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:274]: @alculquicondor Thank you for reminding this. Does it mean that decreasing the timeout would be better?

https://github.com/kubernetes-sigs/kueue/blob/bd83e79ad4b9ac881004cefd35331f1b7a1f5a73/test/integration/scheduler/podsready/scheduler_test.go#L196

File: pkg/controller/core/workload_controller.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/core/workload_controller.go:196]: SGTM. I suspect you want to have #2175 in 0.7?

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 3 above)
Comment (alculquicondor) [reply test/integration/scheduler/podsready/scheduler_test.go:274]: yes. 3s is too long

File: pkg/controller/core/workload_controller.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:196]: > I suspect you want to have https://github.com/kubernetes-sigs/kueue/issues/2175 in 0.7?

Yes, I would like to include #2175 in v0.7.

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 3 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:274]: Let try it.

Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:274]: yeah, I'm even wondering if we could reduce 3s for other places, maybe we should review that

File: pkg/controller/core/workload_controller.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/core/workload_controller.go:196]: > So, could we work on enhancing the reason as another feature to focus on fixing the bug?

sgtm, I was actually suggesting that the current place is ok, since we have the data at hand if we want to build the message. I would be fine to build the message like "The workload is deactivated due to exceeding the PodsReady timeout 5 times in a row.". I'm also ok leave it for https://github.com/kubernetes-sigs/kueue/issues/2175.

**Review by mimowo — COMMENTED** [review]
LGTM overall

**Comment by tenzen-y** [comment]
I found that the current podsready integration test is not correct. So, I will fix the test in another PR, first.

File: pkg/controller/core/workload_controller.go [hunk 4]
```diff
@@ -194,16 +187,39 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
+			// The deactivation reason could be deduced as the maximum number of re-queuing retries if the workload met all criteria below:
+			//  1. The waitForPodsReady feature is enabled, which means that it has "PodsReady" condition.
+			//  2. The workload has already exceeded the PodsReadyTimeout.
+			//  3. The workload already has been re-queued previously, which means it doesn't have the requeueAt field.
+			//  4. The number of re-queued has already reached the waitForPodsReady.requeuingBackoffLimitCount.
+			if apimeta.IsStatusConditionFalse(wl.Status.Conditions, kueue.WorkloadPodsReady) &&
+				((!workload.HasRequeueState(&wl) && ptr.Equal(r.waitForPodsReady.requeuingBackoffLimitCount, ptr.To[int32](0))) ||
+					(workload.HasRequeueState(&wl) && wl.Status.RequeueState.RequeueAt == nil &&
+						ptr.Equal(wl.Status.RequeueState.Count, r.waitForPodsReady.requeuingBackoffLimitCount))) {
+				message = fmt.Sprintf("%s by exceeded the maximum number of re-queuing retries", message)
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller.go:204]: @mimowo @alculquicondor I added the dedicated message like this based on your recommendation. HDYT?
Also, let me try to add a dedicated reason in another enhancement PR.

**Comment by tenzen-y** [comment]
> I found that the current podsready integration test is not correct. So, I will fix the test in another PR, first.

I found that the test issues depend on resetting the whole of the `.status.requeueState` field. So, I fixed the issues in this PR.

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 5]
```diff
@@ -193,7 +193,7 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
 
 	var _ = ginkgo.Context("Short PodsReady timeout", func() {
 		ginkgo.BeforeEach(func() {
-			podsReadyTimeout = 3 * time.Second
+			podsReadyTimeout = 250 * time.Millisecond
```
Comment (tenzen-y) [inline test/integration/scheduler/podsready/scheduler_test.go:196]: I decreased the timeout to 250 ms in all short podsready timeout cases.
HDYT? @mimowo @alculquicondor

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:204]:
```suggestion
				message = fmt.Sprintf("%s due to exceeding the maximum number of re-queuing retries", message)
```
nit, I think it will read better

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 5 above)
Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:196]: nice win! This will speed up the tests. Can we even go below that, say 10ms?

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 6]
```diff
@@ -1892,6 +1892,7 @@ var _ = ginkgo.Describe("Job controller interacting with scheduler", ginkgo.Orde
 var _ = ginkgo.Describe("Job controller interacting with Workload controller when waitForPodsReady with requeuing strategy is enabled", ginkgo.Ordered, ginkgo.ContinueOnFailure, func() {
 	var (
 		backoffBaseSeconds int32
+		backLimitCount     *int32
```
Comment (mimowo) [inline test/integration/controller/jobs/job/job_controller_test.go:1895]:
```suggestion
		backoffLimitCount     *int32
```
nit

File: test/integration/controller/jobs/job/job_controller_test.go [hunk 7]
```diff
@@ -2060,6 +2064,51 @@ var _ = ginkgo.Describe("Job controller interacting with Workload controller whe
...
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, wlKey, wl)).Should(gomega.Succeed())
+				g.Expect(util.SetQuotaReservation(ctx, k8sClient, wl, admission)).Should(gomega.Succeed())
+				util.SyncAdmittedConditionForWorkloads(ctx, k8sClient, wl)
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+			ginkgo.By("checking the workload is evicted by deactivated due to PodsReadyTimeout")
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, wlKey, wl)).Should(gomega.Succeed())
+				g.Expect(wl.Status.RequeueState).Should(gomega.BeNil())
```
Comment (mimowo) [inline test/integration/controller/jobs/job/job_controller_test.go:2078]: nit: let's assert also `spec.active: false`.

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 8]
```diff
@@ -249,47 +249,60 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
...
 			prodWl := testing.MakeWorkload("prod", ns.Name).Queue(prodQueue.Name).Request(corev1.ResourceCPU, "2").Obj()
 			gomega.Expect(k8sClient.Create(ctx, prodWl)).Should(gomega.Succeed())
+
 			ginkgo.By("checking the 'prod' workload is admitted")
 			util.ExpectWorkloadsToHaveQuotaReservation(ctx, k8sClient, prodClusterQ.Name, prodWl)
 			util.ExpectQuotaReservedWorkloadsTotalMetric(prodClusterQ, 1)
 			util.ExpectAdmittedWorkloadsTotalMetric(prodClusterQ, 1)
-			ginkgo.By("exceed the timeout for the 'prod' workload")
-			time.Sleep(podsReadyTimeout)
+			util.AwaitWorkloadEvictionByPodsReadyTimeoutAndSetRequeuedCondition(ctx, k8sClient, client.ObjectKeyFromObject(prodWl), podsReadyTimeout)
```
Comment (mimowo) [inline test/integration/scheduler/podsready/scheduler_test.go:257]: No strong view here, but I prefer not to mix too many responsibilities into a single function, the name looks long. Maybe we can have two functions: `AwaitWorkloadEvictionByPodsReadyTimeout` and `SetRequeuedCondition`?

**Review by mimowo — COMMENTED** [review]
LGTM overall, just nits

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:204]: SGTM, thank you for this recommendation!

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 5 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:196]: I tried to use the 10ms, but test case the below failed:
https://github.com/kubernetes-sigs/kueue/blob/ff4ca7f566e4a12e13ffc3db62cbe896e7993685/test/integration/scheduler/podsready/scheduler_test.go#L261-L263

```shell
  [FAILED] Timed out after 25.000s.
  The function passed to Eventually failed at /Users/tenzen/go/src/sigs.k8s.io/kueue/test/util/util.go:354 with:
  Expected object to be comparable, diff:   &v1beta1.RequeueState{
  -     Count: &2,
  +     Count: &1,
        ... // 1 ignored field
    }
  
  In [It] at: /Users/tenzen/go/src/sigs.k8s.io/kueue/test/integration/scheduler/podsready/scheduler_test.go:261 @ 05/27/24 16:59:35.799
```

I guess that the workload controller could not observe the transition of the state.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 7 above)
Comment (tenzen-y) [reply test/integration/controller/jobs/job/job_controller_test.go:2078]: Oh, good point! Thanks!

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 8 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:257]: That sounds reasonable. Let me split this helper into two ones.
Thanks!

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go]: Done.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 6 above)
Comment (tenzen-y) [reply test/integration/controller/jobs/job/job_controller_test.go]: Done.

File: test/integration/controller/jobs/job/job_controller_test.go (hunk 7 above)
Comment (tenzen-y) [reply test/integration/controller/jobs/job/job_controller_test.go:2080]: Done.

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 8 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go]: Done.

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 5 above)
Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:196]: Hm, maybe this is because the scheduler admits the workload before we can set `active: false`. This might be the reason the time was set to 3s to make sure such race conditions don't happen. Probably reducing to 1s might be safer.

Also, for the new tests, maybe we could consider moving them here: https://github.com/kubernetes-sigs/kueue/blob/ff4ca7f566e4a12e13ffc3db62cbe896e7993685/test/integration/controller/jobs/job/job_controller_test.go#L1743C39-L1743C92. WDYT?

File: pkg/controller/core/workload_controller.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/core/workload_controller.go]: I think the dedicated message is useful

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 5 above)
Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:196]: > This guess doesn't seem to be correct since you added this case when you implemented the podsready feature here: https://github.com/kubernetes-sigs/kueue/commit/9d9336b9b54a646f4149e7ae717a566f1e40dd0c

makes sense, I don't remember why it was 3s, I'm ok to reduce it to as low value as possible, provided the tests continue to pass.

> I think that this case still valid to put here (scheduler+controller) since it would be better to keep observe not to happen the unexpected race conditions bwteen the scheduler and controllers.

Makes sense, on the other hand it exposes us to the race conditions. If you still think the tests are valuable with scheduler I'm ok to keep them here. Maybe we can consider two types of short timeouts: 10ms for tests which are not vulnerable to the race conditions, and longer 250ms or 1s for tests which are vulnerable?

Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:196]: > Makes sense, on the other hand it exposes us to the race conditions. If you still think the tests are valuable with scheduler I'm ok to keep them here. Maybe we can consider two types of short timeouts: 10ms for tests which are not vulnerable to the race conditions, and longer 250ms or 1s for tests which are vulnerable?

That sounds reasonable, but we need to restructure podsready test. So, could we just increase 250ms to 1s in this PR, and then could we try to restructure podsready integration test in followup PR?

@mimowo WDYT?

Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:196]: > That sounds reasonable, but we need to restructure podsready test. So, could we just increase 250ms to 1s in this PR, and then could we try to restructure podsready integration test in followup PR?

sgtm, thanks

File: pkg/controller/core/workload_controller.go [hunk 9]
```diff
@@ -194,16 +187,39 @@ func (r *WorkloadReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 		if updated {
 			return ctrl.Result{}, workload.ApplyAdmissionStatus(ctx, r.client, &wl, true)
 		}
-	} else if !apimeta.IsStatusConditionTrue(wl.Status.Conditions, kueue.WorkloadEvicted) {
-		// if job is not active and does not have condition reason of WorkloadEvictedByDeactivation, update its condition
-		workload.SetEvictedCondition(&wl, kueue.WorkloadEvictedByDeactivation, "The workload is deactivated")
-		if err := workload.ApplyAdmissionStatus(ctx, r.client, &wl, true); err != nil {
-			return ctrl.Result{}, fmt.Errorf("setting eviction: %w", err)
+	} else {
+		var updated, evicted bool
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:191]: Maybe it is better to declare `evicted` as `*string` as it is used to bump the metric. 

I worry that if we have a `bool`, then someone can forget updating line 219 when adding a new scenario for deactivation. WDYT?

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 5 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go]: Done.
Also I opened an issue: https://github.com/kubernetes-sigs/kueue/issues/2285

File: pkg/controller/core/workload_controller.go (hunk 9 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:191]: @mimowo Uhm, do you assume that the `evicted` has the reason for eviction? (here is `InactiveWorkload`)?

Comment (mimowo) [reply pkg/controller/core/workload_controller.go:191]: Oh, never mind, I thought for another scenario that Pods ready, but in that case it would still be WorkloadInactive

Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:191]: Yeah, after we introduce a dedicated reason, we may refacotr here somehow.

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 10]
```diff
@@ -249,47 +249,63 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
...
+			util.FinishEvictionForWorkloads(ctx, k8sClient, prodWl)
+			util.ExpectWorkloadsToHaveQuotaReservation(ctx, k8sClient, prodClusterQ.Name, prodWl)
+			util.ExpectQuotaReservedWorkloadsTotalMetric(prodClusterQ, 4)
+			util.ExpectAdmittedWorkloadsTotalMetric(prodClusterQ, 4)
+			util.AwaitWorkloadEvictionByPodsReadyTimeout(ctx, k8sClient, client.ObjectKeyFromObject(prodWl), podsReadyTimeout)
+			util.SetRequeuedConditionWithPodsReadyTimeout(ctx, k8sClient, client.ObjectKeyFromObject(prodWl))
+			util.FinishEvictionForWorkloads(ctx, k8sClient, prodWl)
+			util.ExpectWorkloadToHaveRequeueState(ctx, k8sClient, client.ObjectKeyFromObject(prodWl), &kueue.RequeueState{
+				Count: ptr.To[int32](1),
+			}, false)
```
Comment (mimowo) [inline test/integration/scheduler/podsready/scheduler_test.go:308]: No strong view, but it feels there is quite a potential for race conditions and flakes here. 

Could we just end the test on the previous check, that the `RequeueState` is nil, and the metric is incremented?

Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:308]: > No strong view, but it feels there is quite a potential for race conditions and flakes here.

I'm sure your concerns, but I think we need to have reactivation test to observe such https://github.com/kubernetes-sigs/kueue/issues/2174 bug.

So, let's replace the line 306-308 with verification of `spec.active=true`.
WDYT?

Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:308]: > I'm sure your concerns, but I think we need to have reactivation test to observe such https://github.com/kubernetes-sigs/kueue/issues/2174 bug.

That is true, but since we now check that `requeueState` is cleaned, I'm not sure how a similar bug could happen, maybe if this was stored in-memory, but I suppose the risk is minimal.

> So, let's replace the line 306-308 with verification of spec.active=true.

Testing for `spec.active=true` would be better for sure.

But also `ExpectWorkloadsToHaveQuotaReservation` is time-sensitive and has a potential for raciness, because the workload gets evicted soon later `AwaitWorkloadEvictionByPodsReadyTimeout`. Maybe just check that the metrics were bumped  - this approach would not be time-sensitive.

Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go:308]: @mimowo I think that there is no such race condition since this integration test doesn't have jobframework reconciler, which means the Job is never readmitted unless performing the `FinishEvictionForWorkloads`, right?

Comment (mimowo) [reply test/integration/scheduler/podsready/scheduler_test.go:308]: Ah, got it. So if the PodsReady timeout happens quickly then you would still pass the `ExpectWorkloadsToHaveQuotaReservation` (L300) check, because it is not removed until you call `FinishEvictionForWorkloads`. It convinces me there is no race condition indeed.

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 11]
```diff
@@ -249,47 +249,63 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
...
 				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(prodWl), prodWl)).Should(gomega.Succeed())
 				prodWl.Spec.Active = ptr.To(true)
 				g.Expect(k8sClient.Update(ctx, prodWl)).Should(gomega.Succeed())
-			}, util.Timeout, util.Interval).Should(gomega.Succeed(), "Reactivate inactive Workload")
-			gomega.Eventually(func(g gomega.Gomega) {
-				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(prodWl), prodWl)).Should(gomega.Succeed())
-				g.Expect(prodWl.Status.RequeueState).Should(gomega.BeNil())
 			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			util.FinishEvictionForWorkloads(ctx, k8sClient, prodWl)
+			util.ExpectWorkloadsToHaveQuotaReservation(ctx, k8sClient, prodClusterQ.Name, prodWl)
```
Comment (mimowo) [inline test/integration/scheduler/podsready/scheduler_test.go:300]: I would suggest to clarify the flow in this test by the comment:
```
// We await for re-admission. Then, the workload keeps the QuotaReserved
// condition even after timeout until FinishEvictionForWorkloads is called.
```

File: test/integration/scheduler/podsready/scheduler_test.go (hunk 10 above)
Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go]: Yes, exactly. I agree that comment would be helpful.

File: test/integration/scheduler/podsready/scheduler_test.go [hunk 12]
```diff
@@ -249,47 +249,65 @@ var _ = ginkgo.Describe("SchedulerWithWaitForPodsReady", func() {
...
 				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(prodWl), prodWl)).Should(gomega.Succeed())
 				prodWl.Spec.Active = ptr.To(true)
 				g.Expect(k8sClient.Update(ctx, prodWl)).Should(gomega.Succeed())
-			}, util.Timeout, util.Interval).Should(gomega.Succeed(), "Reactivate inactive Workload")
-			gomega.Eventually(func(g gomega.Gomega) {
-				g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(prodWl), prodWl)).Should(gomega.Succeed())
-				g.Expect(prodWl.Status.RequeueState).Should(gomega.BeNil())
 			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			// We await for re-admission. Then, the workload keeps the QuotaReserved condition
+			// even after timeout until FinishEvictionForWorkloads is called in line 307.
```
Comment (mimowo) [inline test/integration/scheduler/podsready/scheduler_test.go:301]:
```suggestion
			// even after timeout until FinishEvictionForWorkloads is called below.
```
nit

Comment (tenzen-y) [reply test/integration/scheduler/podsready/scheduler_test.go]: Done.

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
WaitForPodsReady: Fix a bug that causes the reactivated Workload to be immediately deactivated even though it doesn't exceed the backoffLimit.
```
