### PR TITLE
[multikueue] Remove remote objects synchronously when reachable.

### LINKED ISSUE #2320: [MultiKueue] When a JobSet is deleted on management cluster it takes up to 1min to delete from workers
**What happened**:

When running a MultiKueue environment you delete a JobSet on the manager it is not deleted instantly on the worker.
It takes up to 1min to delete the JobSet on worker by the garbage collector.

**What you expected to happen**:

When a user deleted the JobSet on manager it should be deleted instantaneously on a worker. 
Only if the delete request fails we fallback to the Garbage-collector mechanism

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup a MultiKueue environment. Single worker is enough for reproduction.
2. Create a JobSet
3. Delete the jobset on the management cluster

**Issue**: the mirror JobSet remains running on the worker for a prolonged amount of time.

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

 Remove the multikueue remote objects synchronously when reachable based on the filters cache workload content.

#### Which issue(s) this PR fixes:

Fixes #2320

#### Does this PR introduce a user-facing change?

```release-note
[multikueue] Remove remote objects synchronously when reachable.
```

### CODE REVIEW

File: test/integration/multikueue/multikueue_test.go [hunk 1]
```diff
@@ -707,6 +707,169 @@ var _ = ginkgo.Describe("Multikueue", func() {
 		})
 	})
 
+	ginkgo.It("Should remove the worker's workload and job after reconnect when the managers job and workload are deleted", func() {
```
Comment (mimowo) [inline test/integration/multikueue/multikueue_test.go:710]: I would like to have the baseline scenario tested, which does not involve breaking  connection with the worker. Just verify that the workload is deleted within 5s or 10s. I'm ok either with simplifying this test case or adding another one, but probably simplifying is my preferemce.

**Review by mimowo — COMMENTED** [review]
The implementation lgtm. As for testing, I would like to see a test case for the baseline scenario.

File: test/integration/multikueue/multikueue_test.go (hunk 1 above)
Comment (mimowo) [reply test/integration/multikueue/multikueue_test.go:710]: I see, so the test above asserts that the worker workload is removed eventually, but it also passed before the changes, probably because of LongTimeout= 45s which was typically long enough even for the GC-based mechanism. 

I would suggest to decrease the timeout for the test above to 5 or 10s, so that it would fail most often on the current master, but it will pass after the change.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 2]
```diff
@@ -59,6 +61,7 @@ type wlReconciler struct {
 	clusters          *clustersReconciler
 	origin            string
 	workerLostTimeout time.Duration
+	deletedWlCache    *utilmaps.SyncMap[string, *kueue.Workload]
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/workload.go:64]: I'm wondering if this could leak if MultiKueueGC removes the workload in the meanwhile, when the synchronous delete could fail, leaking the entry. Should we also delete the entry when performing MultiKueueGC?

File: test/integration/multikueue/multikueue_test.go (hunk 1 above)
Comment (trasc) [reply test/integration/multikueue/multikueue_test.go:710]: done

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 2 above)
Comment (trasc) [reply pkg/controller/admissionchecks/multikueue/workload.go:63]: The NotFound errors are ignored during the object deletion, other errors will trigger a new reconcile that will eventually get to remove the cache entry.
(I have extended a bit the unit tests)

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
@alculquicondor @tenzen-y I think it would be good to include this in 0.7.x line. WDYT?

**Comment by alculquicondor** [comment]
ok with me to cherry-pick.

**Comment by tenzen-y** [comment]
> /lgtm /approve @alculquicondor @tenzen-y I think it would be good to include this in 0.7.x line. WDYT?

SGTM

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
MultiKueue: Remove remote objects synchronously when the worker cluster is reachable.
```
