### PR TITLE
Ensure all group members own the workload [pod groups]

### LINKED ISSUE #1557: Pod group: Replacement Pods should be added as Workload owners
**What happened**:

When a Pod fails, it can be replaced with a new pod. However, the new pod doesn't become an owner of the Workload.

This could lead to a Workload from disappearing before all the Pod finalizers have been removed.

**What you expected to happen**:

The replacement Pod should be owner of the Workload. Excess pods should not be owners.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create pod group
2. Fail one pod
3. Create replacement pod

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The root cause for the workload removal was that the workload was only owned by the originally created pods, but not replacements. Once the job completes the workload is marked finished, and finalizers from all pods are removed.
Now, the preempted pods (originally created) are getting removed from the API server at this point, and because they are the only owners of the workloads, the workload has no more owners. As a consequence the workload gets removed by the garbage-collector. 

This is inconsistent with workloads completing without getting preempted. In that case the originally created pods are not deleted (even though they have their finalizers removed), and thus the workload is not removed.

#### Which issue(s) this PR fixes:

Fixes #1557

#### Special notes for your reviewer:

This PR will conflict with https://github.com/kubernetes-sigs/kueue/pull/1667 in `TestReconcile` in `pod_controller_test.go`, because both add a test case. The other PR introduces asserts on events in the unit test, which will be handy to verify the event introduced in this PR.

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug that a workload, representing a pod group, was deleted soon after being marked as finished. 
This affected which were preempted during their lifetime.
```

### CODE REVIEW

**Comment by mimowo** [comment]
/assign @yaroslava-serdiuk 
cc @alculquicondor

File: pkg/util/testing/wrappers.go [hunk 1]
```diff
@@ -218,17 +218,15 @@ func (w *WorkloadWrapper) AdmissionChecks(checks ...kueue.AdmissionCheckState) *
...
-		{
-			APIVersion:         gvk.GroupVersion().String(),
-			Kind:               gvk.Kind,
-			Name:               name,
-			UID:                types.UID(uid),
-			Controller:         &controller,
-			BlockOwnerDeletion: &blockDeletion,
-		},
-	}
+func (w *WorkloadWrapper) OwnerReference(gvk schema.GroupVersionKind, name, uid string, controller, blockDeletion *bool) *WorkloadWrapper {
```
Comment (alculquicondor) [inline pkg/util/testing/wrappers.go:221]: Is this change necessary? This new approach leads to much more code.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 2]
```diff
@@ -806,6 +806,28 @@ func (p *Pod) cleanupExcessPods(ctx context.Context, c client.Client, totalCount
 	return nil
 }
 
+func (p *Pod) EnsureWorkloadOwnedByAllMembers(ctx context.Context, c client.Client, r record.EventRecorder, workload *kueue.Workload) error {
+	if p.isGroup {
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:810]:
```
if !p.isGroup {
 return nil
}
```

File: pkg/controller/jobs/pod/pod_controller.go [hunk 3]
```diff
@@ -806,6 +806,28 @@ func (p *Pod) cleanupExcessPods(ctx context.Context, c client.Client, totalCount
...
+		oldOwnersCnt := len(workload.GetOwnerReferences())
+		for _, pod := range p.list.Items {
+			if err := controllerutil.SetOwnerReference(&pod, workload, c.Scheme()); err != nil {
+				return err
+			}
+		}
+		newOwnersCnt := len(workload.GetOwnerReferences())
+		if addedOwnersCnt := newOwnersCnt - oldOwnersCnt; addedOwnersCnt > 0 {
+			log := ctrl.LoggerFrom(ctx).WithValues("workload", klog.KObj(workload))
+			log.Info("Adding owner references for workload", "count", addedOwnersCnt)
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:820]:
```suggestion
			log.V(4).Info("Adding owner references for workload", "count", addedOwnersCnt)
```

Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller.go]: done

File: pkg/util/testing/wrappers.go (hunk 1 above)
Comment (mimowo) [reply pkg/util/testing/wrappers.go:229]: Not really, I reverted them by keeping the OwnerReference function.  For the need of my unit test I now introduce SetOwnerReference and SetControllerReference. These are analogs of the controllerutil functions, which either pass (nil, nil) or (true, true). So now, the changes are scoped to the TestReconcile unit test. If you like this approach I could have a follow up to eliminate the OwnerReference function and replace it with either of the two new functions.

Still, inside this test I add a bunch of "SetOwnerReference" and "SetControllerReference" lines. The alternatives I see:
1. have an extra param in the unit test like "verifyOwnerReferences" that would (1) skip the code of adding owner references, (2) use another set of cmpopts for the workload. 
2. have a dedicated unit test for this scenario, say TestReconcileWithOwnerReferences
3. do not add unit tests for owner references

IMO none of the alternatives is tempting. Indeed adding a bunch of lines seems like a lot of code, but easy to understand. WDYT?

File: pkg/util/testing/wrappers.go [hunk 4]
```diff
@@ -227,16 +227,29 @@ func (w *WorkloadWrapper) AdmissionChecks(checks ...kueue.AdmissionCheckState) *
...
+
+func (w *WorkloadWrapper) SetControllerReference(gvk schema.GroupVersionKind, name, uid string) *WorkloadWrapper {
+	w.appendOwnerReference(gvk, name, uid, ptr.To(true), ptr.To(true))
+	return w
+}
+
+func (w *WorkloadWrapper) SetOwnerReference(gvk schema.GroupVersionKind, name, uid string) *WorkloadWrapper {
+	w.appendOwnerReference(gvk, name, uid, nil, nil)
+	return w
+}
```
Comment (alculquicondor) [inline pkg/util/testing/wrappers.go:242]: for a follow up: we should only have `OwnerReference` and `ControllerReference`

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
/release-note-edit

```release-note
NONE
```

Unreleased feature.
