### PR TITLE
[TAS] Add FailFast mode to TAS on node failure

### LINKED ISSUE #5862: [TAS] Evict Workload after Kueue fails to find a replacement for a failed Node
**What would you like to be added**:
A feature that would evict Workload once Kueue cannot find a replacement for a failed Node

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Adds a FailFast mode to TAS on node failure. After Kueue tries to find a replacement for a failed node and fails it evicts the Workload 

#### Which issue(s) this PR fixes:

Fixes #5862

#### Special notes for your reviewer:
Currently the feature is behind feature gate, we will add dedicated API based on customers feedback

#### Does this PR introduce a user-facing change?

```release-note
TAS: Add FailFast on Node's failure handling mode
```

### CODE REVIEW

**Comment by mimowo** [comment]
@PBundyra is there any KEP update to the change?

**Comment by PBundyra** [comment]
> @PBundyra is there any KEP update to the change?

It's part of the PR

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -220,6 +221,33 @@ func (s *Scheduler) schedule(ctx context.Context) wait.SpeedSignal {
 		ctx := ctrl.LoggerInto(ctx, log)
 
 		mode := e.assignment.RepresentativeMode()
+
+		if workload.HasTopologyAssignmentWithNodeToReplace(e.Obj) && mode != flavorassigner.Fit && features.Enabled(features.TASFailedNodeReplacementFailFast) {
+			// evict the workload that couldn't find the replacement for a failed node
+			log.V(2).Info("Evicting workload with node replacement in TAS, as TASFailedNodeReplacementFailFast is enabled")
```
Comment (pajakd) [inline pkg/scheduler/scheduler.go]: I don't get this log line. "Evicting workload with node replacement" -- we did not find the replacement, right?  Did you mean "without node replacement" or "with a failed node without replacement"?

File: pkg/features/kube_features.go [hunk 2]
```diff
@@ -169,6 +169,12 @@ const (
 	//
 	// Enable replacement of failed node in TAS.
 	TASFailedNodeReplacement featuregate.Feature = "TASFailedNodeReplacement"
+
+	// owner: @pbundyra
+	// kep: https://github.com/kubernetes-sigs/kueue/tree/main/keps/2724-topology-aware-scheduling
+	//
+	// Evict Workload if Kueue couldn't find replacement for a failed node in TAS.
```
Comment (pajakd) [inline pkg/features/kube_features.go]: This change is not about evicting (because eviction would eventually happen anyway) but rather not retrying to find the replacement, right? So perhaps change "couldn't find replacement (...) in the first attempt"  or add "without retries" somewhere.

File: pkg/scheduler/scheduler.go [hunk 3]
```diff
@@ -220,6 +221,33 @@ func (s *Scheduler) schedule(ctx context.Context) wait.SpeedSignal {
 		ctx := ctrl.LoggerInto(ctx, log)
 
 		mode := e.assignment.RepresentativeMode()
+
+		if workload.HasTopologyAssignmentWithNodeToReplace(e.Obj) && mode != flavorassigner.Fit && features.Enabled(features.TASFailedNodeReplacementFailFast) {
+			// evict the workload that couldn't find the replacement for a failed node
```
Comment (pajakd) [inline pkg/scheduler/scheduler.go]: nit: above in kube_features.go you write "if Kueue couldn't find replacement" and here "workload couldn't find the replacement"

File: pkg/scheduler/scheduler.go [hunk 4]
```diff
@@ -220,6 +221,33 @@ func (s *Scheduler) schedule(ctx context.Context) wait.SpeedSignal {
 		ctx := ctrl.LoggerInto(ctx, log)
 
 		mode := e.assignment.RepresentativeMode()
+
+		if workload.HasTopologyAssignmentWithNodeToReplace(e.Obj) && mode != flavorassigner.Fit && features.Enabled(features.TASFailedNodeReplacementFailFast) {
```
Comment (pajakd) [inline pkg/scheduler/scheduler.go]: This is quite some code in the main scheduler function. How about extracting it into a separate function?

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Done

File: pkg/features/kube_features.go (hunk 2 above)
Comment (PBundyra) [reply pkg/features/kube_features.go]: Done

File: pkg/scheduler/scheduler.go (hunk 3 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Done

File: pkg/scheduler/scheduler.go (hunk 4 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Created a helper function, ptal

File: keps/2724-topology-aware-scheduling/README.md [hunk 5]
```diff
@@ -964,10 +966,10 @@ As an example let's analyze the assignment based on the size of a podset and sel
 mode. See the table below where the numbers are pods assigned to a particular node.
 The header for columns dedicated to nodes correspond node's initial capacity.
 
-| mode                   | Pods count | 6 | 5 | 4 | 3 | 2 |
```
Comment (mimowo) [inline keps/2724-topology-aware-scheduling/README.md:967]: nit, but why is this changed? I would suggest to eliminate distrctions as much as possible to make review easier.

File: keps/2724-topology-aware-scheduling/README.md [hunk 6]
```diff
@@ -1338,9 +1340,9 @@ the last domain.
 This algorithm was enabled by the `TASProfileMostFreeCapacity` feature flag and it
 was independent of PodSet's annotations:
 
-| featuregate/annotation     | preferred         | required          | unconstrained     |
```
Comment (mimowo) [inline keps/2724-topology-aware-scheduling/README.md:1341]: Same here, I'm not sure if I missed something, but it seems like noop change. Stil making sure nothing relevant is changed takes reviewers time.

File: keps/2724-topology-aware-scheduling/README.md (hunk 5 above)
Comment (PBundyra) [reply keps/2724-topology-aware-scheduling/README.md:967]: Must have been result of running `make toc-update` or `make generate-apiref`, probably the latter. I would keep this change the PR since it's cosmetic and clearly doesn't impact other parts of code

File: keps/2724-topology-aware-scheduling/README.md (hunk 6 above)
Comment (PBundyra) [reply keps/2724-topology-aware-scheduling/README.md:1341]: Ditto

File: keps/2724-topology-aware-scheduling/README.md (hunk 5 above)
Comment (mimowo) [reply keps/2724-topology-aware-scheduling/README.md:967]: why not submit in a separate cleanup PR? You say clearly, but actually I was checking every number anyway. 

but if you feel strongly about it then ok, feel free to resolve the comments.

File: pkg/scheduler/scheduler.go [hunk 7]
```diff
@@ -220,6 +221,26 @@ func (s *Scheduler) schedule(ctx context.Context) wait.SpeedSignal {
...
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go]: nit, First check feature gate to ensure any "new" functions are not called when disabled

File: test/integration/singlecluster/tas/tas_test.go [hunk 8]
```diff
@@ -1220,6 +1220,124 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+				})
+
+				ginkgo.By("making the node NotReady 30s in the past", func() {
+					nodeToUpdate := &corev1.Node{}
+					gomega.Expect(k8sClient.Get(ctx, apitypes.NamespacedName{Name: nodeName}, nodeToUpdate)).Should(gomega.Succeed())
+
+					util.SetNodeCondition(ctx, k8sClient, nodeToUpdate, &corev1.NodeCondition{
+						Type:               corev1.NodeReady,
+						Status:             corev1.ConditionFalse,
+						LastTransitionTime: metav1.NewTime(time.Now().Add(-tas.NodeFailureDelay)),
```
Comment (pajakd) [inline test/integration/singlecluster/tas/tas_test.go:1324]: We should make the node not ready now (not in the past) to check if FailFast works.

File: test/integration/singlecluster/tas/tas_test.go [hunk 9]
```diff
@@ -1220,6 +1220,124 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+
+				ginkgo.By("verify the workload is evicted due to no replacement possible", func() {
+					util.FinishEvictionForWorkloads(ctx, k8sClient, wl1)
+					gomega.Eventually(func(g gomega.Gomega) {
+						updatedWl := &kueue.Workload{}
+						g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(wl1), updatedWl)).To(gomega.Succeed())
+						annotations := updatedWl.GetAnnotations()
+						_, found := annotations[kueuealpha.NodeToReplaceAnnotation]
+						g.Expect(found).To(gomega.BeFalse())
+					}, util.Timeout, util.Interval).Should(gomega.Succeed())
```
Comment (pajakd) [inline test/integration/singlecluster/tas/tas_test.go:1361]: Just to be sure, this is testing the FailFast because of the timeouts, right? Without the FailFast feature gate this test would fail?

File: pkg/workload/workload.go [hunk 10]
```diff
@@ -957,6 +967,18 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
 	return nil
 }
 
+func RemoveAnnotation(ctx context.Context, cl client.Client, wl *kueue.Workload, annotation string) error {
```
Comment (mimowo) [inline pkg/workload/workload.go:970]: This function accepts the annotation as name, but hardcodes NodeToReplaceAnnotation

File: pkg/scheduler/scheduler.go (hunk 7 above)
Comment (mimowo) [inline pkg/scheduler/scheduler.go]: Please move the code to a dedicated function to offload the main body of scheduler loop with the details. Similarly as we do in case of IssuePreemptions.

File: pkg/scheduler/scheduler.go [hunk 11]
```diff
@@ -220,6 +221,26 @@ func (s *Scheduler) schedule(ctx context.Context) wait.SpeedSignal {
...
+			msg := fmt.Sprintf("Workload was evicted as there was no replacement for a failed node: %s", workload.NodeToReplace(e.Obj))
+			if err := workload.EvictWorkload(ctx, s.client, s.recorder, e.Obj, kueue.WorkloadEvictedDueToNodeFailures, msg, s.clock); err != nil {
+				log.V(2).Error(err, "Failed to evict workload after failed try to find a node replacement")
+				continue
+			}
+			if err := workload.RemoveAnnotation(ctx, s.client, e.Obj, kueuealpha.NodeToReplaceAnnotation); err != nil {
+				log.V(2).Error(err, fmt.Sprintf("Failed to remove annotation for node replacement %s", kueuealpha.NodeToReplaceAnnotation))
+				continue
+			}
+			// remove the wl from entries so it's not requeued after we evicted it
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go]: is it really needed? it seems evicted workload would not get requeued for second pass anyway as we check this in `NeedsSecondPass` function?

File: test/integration/singlecluster/tas/tas_test.go (hunk 9 above)
Comment (PBundyra) [reply test/integration/singlecluster/tas/tas_test.go:1361]: Without FailFast the workload would be never evicted. We need the 30 sec delay to to ensure the Workload has the proper annotation

File: pkg/scheduler/scheduler.go (hunk 7 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Done

File: pkg/workload/workload.go (hunk 10 above)
Comment (PBundyra) [reply pkg/workload/workload.go:970]: Done

File: pkg/scheduler/scheduler.go (hunk 7 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Done

**Review by mimowo — COMMENTED** [review]
LGTM overall as for alpha, but my worry is that we are waiting for 2 sequential requests in the scheduler cycle. Scheduling cycles are super important to be performant.

Two optimizations I see:
1. 1 request per workload when the annotation is inside status (https://github.com/kubernetes-sigs/kueue/issues/5560)
2. we issue the eviction requests to all affected workloads in parallel (similarly to IssuePreemptions)
3. (alternatively) scheduler could only mark the workload in cache as already tried. The actual eviction would happen by another controller, for example node failure controller.

I'm leaning to say that optimizing the scheduler main loop is a blocker for graduation of the TASFailedNodeReplacementFailFast feature gate to beta. 

@PBundyra please add a note to re-evaluate the optimization to the scheduler loop before graduating TASFailedNodeReplacementFailFast to beta.

cc @tenzen-y wdyt?

File: pkg/scheduler/scheduler.go (hunk 11 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: It wouldn't pass NeedsSecondPass but would be requeued as a Pending workload

**Comment by PBundyra** [comment]
> my worry is that we are waiting for 2 sequential requests in the scheduler cycle. Scheduling cycles are super important to be performant.

I agree with your worries, and I believe we should aim for replacing the annotation with the status field in v0.14. Added the note

File: pkg/scheduler/scheduler.go (hunk 11 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go]: Why is that wrong? It is normal that evicted workloads are re-queued. If we don't want to requeue the workload it should be de-activated.

File: test/integration/singlecluster/tas/tas_test.go [hunk 12]
```diff
@@ -1220,6 +1220,124 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+					gomega.Expect(k8sClient.Get(ctx, apitypes.NamespacedName{Name: nodeName}, nodeToUpdate)).Should(gomega.Succeed())
+
+					util.SetNodeCondition(ctx, k8sClient, nodeToUpdate, &corev1.NodeCondition{
+						Type:               corev1.NodeReady,
+						Status:             corev1.ConditionFalse,
+						LastTransitionTime: metav1.NewTime(time.Now().Add(-tas.NodeFailureDelay)),
+					})
+				})
+
+				ginkgo.By("verify the workload is evicted due to no replacement possible", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/tas/tas_test.go:1352]: Please extend the test, or add a dedicated one to demonstrate the workload gets admitted after eviction - in order to demonstrate it gets requeued.

Even thought the node replacement failed, the workload after requeue may get admitted to another rack (using topology-required: rack annotation), or fall to another ResourceFlavor.

**Comment by mimowo** [comment]
> I believe we should aim for replacing the annotation with the status field in v0.14.

Thanks, on top of the performance concerns, it is possible that the Evict request succeeds, but the RemoveAnnotation fails. If the workload gets re-admitted we may perform then unnecessary node replacement on the new flavor. 

The scenario is unlikely, but dealing with the annotation creates subtle issues.

File: test/integration/singlecluster/tas/tas_test.go (hunk 12 above)
Comment (PBundyra) [reply test/integration/singlecluster/tas/tas_test.go:1352]: Added the test

File: pkg/scheduler/scheduler.go (hunk 11 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Agree, reverted deleting from the entries

File: pkg/scheduler/scheduler.go [hunk 13]
```diff
@@ -486,6 +496,19 @@ func (s *Scheduler) getInitialAssignments(log logr.Logger, wl *workload.Info, sn
...
 
+func (s *Scheduler) evictWorkloadAfterFailedTASReplacement(ctx context.Context, log logr.Logger, wl *kueue.Workload) error {
+	log.V(2).Info("Evicting workload after failed try to find a node replacement; TASFailedNodeReplacementFailFast enabled")
+	msg := fmt.Sprintf("Workload was evicted as there was no replacement for a failed node: %s", workload.NodeToReplace(wl))
+	if err := workload.EvictWorkload(ctx, s.client, s.recorder, wl, kueue.WorkloadEvictedDueToNodeFailures, msg, s.clock); err != nil {
+		return err
+	}
+	if err := workload.RemoveAnnotation(ctx, s.client, wl, kueuealpha.NodeToReplaceAnnotation); err != nil {
+		log.V(2).Error(err, fmt.Sprintf("Failed to remove annotation for node replacement %s", kueuealpha.NodeToReplaceAnnotation))
+		return err
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go]: let's just return `fmt.Errorf("Failed to remove annotation for node replacement %s", kueuealpha.NodeToReplaceAnnotation)` as error to avoid double-logging as it will be logged upstream iiuc

File: pkg/scheduler/scheduler.go [hunk 14]
```diff
@@ -669,7 +692,12 @@ func (s *Scheduler) requeueAndUpdate(ctx context.Context, e entry) {
 	log.V(2).Info("Workload re-queued", "workload", klog.KObj(e.Obj), "clusterQueue", klog.KRef("", string(e.ClusterQueue)), "queue", klog.KRef(e.Obj.Namespace, string(e.Obj.Spec.QueueName)), "requeueReason", e.requeueReason, "added", added, "status", e.status)
 
 	if e.status == notNominated || e.status == skipped {
-		patch := workload.PrepareWorkloadPatch(e.Obj, true, s.clock)
+		// need to re-fetch the Workload in case it was updated in scheduler above
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go]: Actually, if we evicted the workload, then all this code below should not be necessary, because then the workload controller will carry the eviction, and so it will race at this point with scheduler to unset QuotaReservation. 

So, in that case I think it is better to just skip the logic below, am I missing something?

In any case the new code should be protected by `TASFailedNodeReplacementFailFast`, because we don't have so far any indication the "Get" is necessary in generic case.

File: pkg/scheduler/scheduler.go [hunk 15]
```diff
@@ -486,6 +496,19 @@ func (s *Scheduler) getInitialAssignments(log logr.Logger, wl *workload.Info, sn
 	return fullAssignment, nil
 }
 
+func (s *Scheduler) evictWorkloadAfterFailedTASReplacement(ctx context.Context, log logr.Logger, wl *kueue.Workload) error {
+	log.V(2).Info("Evicting workload after failed try to find a node replacement; TASFailedNodeReplacementFailFast enabled")
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go]:
```suggestion
	log.V(3).Info("Evicting workload after failed try to find a node replacement; TASFailedNodeReplacementFailFast enabled")
```

File: pkg/scheduler/scheduler.go (hunk 14 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go]: To achieve that, I think we could introduce new status evicted. Then, this entire block in scheduler would be skipped.

EDIT: even more, if status.evicted then we probably could skip the entire requeueAndUpdate, because it will be eventually requeued by workload_controller. This is probably why, in fact, removing the workload entry from entries was ok in the first iteration.

Comment (mimowo) [reply pkg/scheduler/scheduler.go]: Ok, as I read the code more, I would suggest to introduce status.evicted, just for this scenario now. When status.evicted then skip requeueAndUpdate `if e.status != assumed && e.status != evicted {`. This will ensure we log the details in `logAdmissionAttemptIfVerbose` as for any other workload processed by scheduler. 

EDIT: and add a comment along the lines "When the workload is evicted by scheduler we skip requeueAndUpdate. The eviction  process will be finalized by the workload controller."

File: pkg/scheduler/scheduler.go (hunk 15 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Done

File: pkg/scheduler/scheduler.go (hunk 13 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Done

File: pkg/scheduler/scheduler.go (hunk 14 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler.go]: Thanks, added

**Comment by mimowo** [comment]
/lgtm
/approve
Thanks! Nice improvement to TAS node hot swap as in static clusters it is unlikely for the following node replacement attempt to succeed, so it is expected by users to "fail fast" and evict the workload. 

There are some performance considerations as mentioned in https://github.com/kubernetes-sigs/kueue/pull/5861#pullrequestreview-2986043556, but they can be addressed in the future as this is an Alpha feature.

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
TAS: Add FailFast on Node's failure handling mode
```
