### PR TITLE
fix(metrics): convert milliCPU to CPU units

### LINKED ISSUE #10746: kueue_cohort_subtree_quota reports CPU as 1000x the actual value
**What happened**:
When exporting the cpu metric from kueue_cohort_subtree_quota, it shows up as 1000x the actual value
**What you expected to happen**:
i.e. 96 cpu in a resource flavor in a cohort should report as 96 cpu not 96000

**How to reproduce it (as minimally and precisely as possible)**:
curl metrics endpoint and grep for subtree
`curl https://localhost:8080/metrics | grep subtree`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.33
- Kueue version (use `git describe --tags --dirty --always`): 0.17.1
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by baoalvin1**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
in cohort subtree metrics `kueue_cohort_subtree_quota` and `kueue_cohort_subtree_resource_reservations` were reporting raw milliCPU values (e.g. 30000) instead of CPU units (e.g. 30.0), unlike the equivalent ClusterQueue metrics which correctly use resourceFloat(). Apply the same conversion in applyCohortMetricPoint and update the metric function signatures to accept float64.
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/kueue/issues/10746

#### Does this PR introduce a user-facing change?

```release-note
Observability: Fix kueue_cohort_subtree_quota and kueue_cohort_subtree_resource_reservations metrics incorrectly reporting raw milliCPU values instead of CPU units for CPU resources.
```

### CODE REVIEW

File: pkg/cache/scheduler/cohort_metrics_test.go [hunk 1]
```diff
@@ -352,18 +352,18 @@ func TestClearCohortMetrics_ClearsTargetAndAncestors(t *testing.T) {
...
-	expectGaugeValue(t, kueuemetrics.CohortSubtreeResourceReservations, cohortMetricLabels("root", frDefaultCPU), 13_000)
+	expectGaugeValue(t, kueuemetrics.CohortSubtreeQuota, cohortMetricLabels("ch1", frDefaultCPU), 18)
+	expectGaugeValue(t, kueuemetrics.CohortSubtreeQuota, cohortMetricLabels("ch2", frDefaultCPU), 14)
+	expectGaugeValue(t, kueuemetrics.CohortSubtreeQuota, cohortMetricLabels("root", frDefaultCPU), 62)
+	expectGaugeValue(t, kueuemetrics.CohortSubtreeResourceReservations, cohortMetricLabels("root", frDefaultCPU), 13)
 
 	cache.ClearCohortMetrics(log, "ch1")
 	expectGaugeCount(t, kueuemetrics.CohortSubtreeQuota, 0, cohortMetricLabels("ch1", frDefaultCPU))
 	expectGaugeCount(t, kueuemetrics.CohortSubtreeResourceReservations, 0, cohortMetricLabels("ch1", frDefaultCPU))
-	expectGaugeValue(t, kueuemetrics.CohortSubtreeQuota, cohortMetricLabels("ch2", frDefaultCPU), 14_000)
```
Comment (kannon92) [inline pkg/cache/scheduler/cohort_metrics_test.go:363]: Hmm. I wonder if this was by design considering we have tests covering this.

**Review by kannon92 — COMMENTED** [review]
Seeing the tests I'm wondering if this is by design. What would show up for CPU if it's actually using milliCPUs. 500 milli?

**Comment by kannon92** [comment]
Can you add a release note? This is a user facing bug.

**Comment by baoalvin1** [comment]
@kannon92 no it shows up as an int value, I think the tests are incorrect because the clusterqueue metrics are correct

**Comment by baoalvin1** [comment]
```
kueue_cohort_subtree_quota{cohort="cohort",flavor="flavor1",replica_role="leader",resource="cpu"} 96000
```
is what the /metrics endpoint outputs even though I only have 96 cpus in the flavor

File: pkg/cache/scheduler/cohort_metrics_test.go (hunk 1 above)
Comment (kannon92) [reply pkg/cache/scheduler/cohort_metrics_test.go:363]: cc @mimowo @tenzen-y 

Curious if you expect this behavior? Just surprised to see tests expecting this.

Comment (mimowo) [reply pkg/cache/scheduler/cohort_metrics_test.go:363]: Thanks for calling this out. I think this is a bug that just slipped reviewer attention.

cc @mszadkow in case he has some more thoughts here, but Im pretty sure a bug

Comment (mszadkow) [reply pkg/cache/scheduler/cohort_metrics_test.go:363]: fully agree, now as you pointed that out, I think it's a bug too

**Comment by mimowo** [comment]
Thanks 👍 
/lgtm
/approve
/cherrypick release-0.17

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Observability: Fix kueue_cohort_subtree_quota and kueue_cohort_subtree_resource_reservations metrics incorrectly reporting raw milliCPU values instead of CPU units for CPU resources.
```
