### PR TITLE
fix the suspend=true added to the job by the default job webhook has …

### LINKED ISSUE #757: The suspend=true added to the job by the default job webhook has not taken effect.
**What happened**:
When I create a job that contains one pod, occasionally the following situation will occur. Two pods will be created at the same time. The status of one pod is Terminating, and the status of the other pod is Pending. I think the Terminating pod should not be created
image
**What you expected to happen**:
I think the suspend=true added to the job by the default job webhook has not taken effect.
image

The address of the job object is different from the address of &Job{*job}. I added a test case for testing, and it is true, so the suspend=true added here will not take effect.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by fjding**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix the suspend=true added to the job by the default job webhook has not taken effect.

#### Which issue(s) this PR fixes:

Fixes  #757

#### Does this PR introduce a user-facing change?

```release-note
Fixed the suspend=true add to the job/mpijob by the default webhook has not taken effect.
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
@fjding Thanks for your contribution. Could you fix the MPIJob as well?

**Comment by fjding** [comment]
> @fjding Thanks for your contribution. Could you fix the MPIJob as well?

Sorry, I missed it,  I will re-update the pr

File: pkg/controller/jobs/job/job_controller.go [hunk 1]
```diff
@@ -121,11 +121,11 @@ func (h *parentWorkloadHandler) queueReconcileForChildJob(object client.Object,
 }
 
 type Job struct {
-	batchv1.Job
+	*batchv1.Job
 }
 
 func (j *Job) Object() client.Object {
-	return &j.Job
+	return j.Job
```
Comment (tenzen-y) [inline pkg/controller/jobs/job/job_controller.go:128]: I think we should return a pointer here.

File: pkg/controller/jobs/job/job_controller.go [hunk 2]
```diff
@@ -121,11 +121,11 @@ func (h *parentWorkloadHandler) queueReconcileForChildJob(object client.Object,
 }
 
 type Job struct {
-	batchv1.Job
+	*batchv1.Job
```
Comment (tenzen-y) [inline pkg/controller/jobs/job/job_controller.go:124]: Uhm... Instead of making this a pointer, adding a new function, `SetObject(obj client.Object)` might be better.
@alculquicondor @mimowo @kerthcet WDYT?

**Comment by alculquicondor** [comment]
tests are failing, could you investigate?

File: pkg/controller/jobs/job/job_controller.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/controller/jobs/job/job_controller.go:128]: Ah, I found `client.Object` is a interface. Thanks!

File: pkg/controller/jobs/job/job_controller.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/controller/jobs/job/job_controller.go:124]: My understanding of `func Object()` was incorrect. So, a pointer sounds better.

**Comment by fjding** [comment]
> tests are failing, could you investigate?

done

**Comment by tenzen-y** [comment]
@fjding This PR is related to a user-facing change. So instead of adding `None` to the release note, adding appropriate comments would be great.

**Review by tenzen-y — COMMENTED** [review]
@fjding Thank you!
/lgtm

**Comment by mimowo** [comment]
/lgtm thanks for fixing. 

Given the importance of the scenario I suggest we add an e2e test. Either in this or a follow up PR. WDYT @alculquicondor ?

**Comment by tenzen-y** [comment]
> /lgtm thanks for fixing.
> 
> Given the importance of the scenario I suggest we add an e2e test. Either in this or a follow up PR. WDYT @alculquicondor ?

+1

**Comment by alculquicondor** [comment]
-1 on e2e, but we should have an integration test for this.

**Comment by alculquicondor** [comment]
@fjding could you add one integration test for job in this PR?

/lgtm
/approve

You can do it in a follow up, but ideally we cherry-pick that one too.

**Comment by alculquicondor** [comment]
I guess we would face the same problem with e2e tests. Maybe it's not worth doing this?

**Comment by alculquicondor** [comment]
That wouldn't help, because we where passing the wrong object to that function.

The unit test needs to be for the Job webhook function (and MPIJob), if there isn't one already.

**Comment by tenzen-y** [comment]
> That wouldn't help, because we where passing the wrong object to that function.

That makes sense.

> The unit test needs to be for the Job webhook function (and MPIJob), if there isn't one already.

Yes, we don't have any unit tests for the Defaulter.

https://github.com/kubernetes-sigs/kueue/blob/8733524da55e277aeb5fb81445be979b86060f9e/pkg/controller/jobs/job/job_webhook_test.go

**Comment by alculquicondor** [comment]
Yes, but the e2e test would have the same problem than this https://github.com/kubernetes-sigs/kueue/pull/758#issuecomment-1545889365

**Comment by tenzen-y** [comment]
> Yes, but the e2e test would have the same problem than this [#758 (comment)](https://github.com/kubernetes-sigs/kueue/pull/758#issuecomment-1545889365)

Yes, it would be hard to verify the Defaulter in E2E :(

**Comment by tenzen-y** [comment]
In the integration test, as a hacky approach, we might be able to verify the Defaulter in the following:

1. Manually create a Workload with `Admitted=true`.
2. Create a Job with `Active=1`.

Although, I'm not sure whether the hacky test is worth it.

**Comment by tenzen-y** [comment]
For e2e, I don't have any good ideas.

**Comment by alculquicondor** [comment]
not worth, IMO. unit tests at the webhook level should be enough

**Comment by tenzen-y** [comment]
> not worth, IMO. unit tests at the webhook level should be enough

Agree. Let's go ahead :)
