### PR TITLE
[Flaky] Revisit RayJob TAS e2e tests to not count submitter job pod

### LINKED ISSUE #4508: Flaky Test: TopologyAwareScheduling for RayJob when Creating a RayJob Should place pods based on the ranks-ordering
**What happened**:
Failed the `End To End TAS Suite: kindest/node:v1.31.1: [It] TopologyAwareScheduling for RayJob when Creating a RayJob Should place pods based on the ranks-ordering` in periodic CI

```shell
{Timed out after 300.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/tas/rayjob_test.go:203 with:
Expected
    <[]v1.Pod | len:4, cap:4>: [
        {
            TypeMeta: {Kind: "", APIVersion: ""},
            ObjectMeta: {
                Name: "ranks-ray-raycluster-gpzrs-head-mm657",
                GenerateName: "ranks-ray-raycluster-gpzrs-head-",
                Namespace: "e2e-tas-rayjob-lgmbj",
                SelfLink: "",
                UID: "cbf00188-3d57-4dce-a72c-3c6827775792",
                ResourceVersion: "4265",
                Generation: 0,
                CreationTimestamp: {
                    Time: 2025-03-05T22:40:41Z,
                },
                DeletionTimestamp: nil,
                DeletionGracePeriodSeconds: nil,
                Labels: {
                    "kueue.x-k8s.io/tas": "true",
                    "ray.io/group": "headgroup",
                    "ray.io/identifier": "ranks-ray-raycluster-gpzrs-head",
                    "ray.io/is-ray-node": "yes",
                    "app.kubernetes.io/created-by": "kuberay-operator",
                    "kueue.x-k8s.io/podset": "head",
                    "ray.io/cluster": "ranks-ray-raycluster-gpzrs",
                    "ray.io/node-type": "head",
                    "app.kubernetes.io/name": "kuberay",
                },
                Annotations: {
                    "kueue.x-k8s.io/podset-preferred-topology": "cloud.provider.com/topology-rack",
                    "kueue.x-k8s.io/workload": "rayjob-ranks-ray-8120c",
                    "ray.io/ft-enabled": "false",
                },
                OwnerReferences: [
                    {
                        APIVersion: "ray.io/v1",
                        Kind: "RayCluster",
                        Name: "ranks-ray-raycluster-gpzrs",
                        UID: "0616b0a6-e920-481b-9516-db1f0880f2b1",
                        Controller: true,
                        BlockOwnerDeletion: true,
                    },
                ],
                Finalizers: nil,
                ManagedFields: [
                    {
                        Manager: "kuberay-operator",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2025-03-05T22:40:41Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kueue.x-k8s.io/podset-preferred-topology\":{},\"f:kueue.x-k8s.io/workload\":{},\"f:ray.io/ft-enabled\":{}},\"f:generateName\":{},\"f:labels\":{\".\":{},\"f:app.kubernetes.io/created-by\":{},\"f:app.kubernetes.io/name\":{},\"f:kueue.x-k8s.io/podset\":{},\"f:kueue.x-k8s.io/tas\":{},\"f:ray.io/cluster\":{},\"f:ray.io/group\":{},\"f:ray.io/identifier\":{},\"f:ray.io/is-ray-node\":{},\"f:ray.io/node-type\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"0616b0a6-e920-481b-9516-db1f0880f2b1\\\"}\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"head-container\\\"}\":{\".\":{},\"f:args\":{},\"f:command\":{},\"f:env\":{\".\":{},\"k:{\\\"name\\\":\\\"KUBERAY_GEN_RAY_START_CMD\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_ADDRESS\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_CLOUD_INSTANCE_ID\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:fieldRef\":{}}},\"k:{\\\"name\\\":\\\"RAY_CLUSTER_NAME\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:fieldRef\":{}}},\"k:{\\\"name\\\":\\\"RAY_DASHBOARD_ENABLE_K8S_DISK_USAGE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_NODE_TYPE_NAME\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:fieldRef\":{}}},\"k:{\\\"name\\\":\\\"RAY_PORT\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_USAGE_STATS_EXTRA_TAGS\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_USAGE_STATS_KUBERAY_IN_USE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"REDIS_PASSWORD\\\"}\":{\".\":{},\"f...

Gomega truncated this representation as it exceeds 'format.MaxLength'.
Consider having the object provide a custom 'GomegaStringer' representation
or adjust the parameters in Gomega's 'format' package.

Learn more here: https://onsi.github.io/gomega/#adjusting-output

to have length 5 failed [FAILED] Timed out after 300.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/tas/rayjob_test.go:203 with:
Expected
    <[]v1.Pod | len:4, cap:4>: [
        {
            TypeMeta: {Kind: "", APIVersion: ""},
            ObjectMeta: {
                Name: "ranks-ray-raycluster-gpzrs-head-mm657",
                GenerateName: "ranks-ray-raycluster-gpzrs-head-",
                Namespace: "e2e-tas-rayjob-lgmbj",
                SelfLink: "",
                UID: "cbf00188-3d57-4dce-a72c-3c6827775792",
                ResourceVersion: "4265",
                Generation: 0,
                CreationTimestamp: {
                    Time: 2025-03-05T22:40:41Z,
                },
                DeletionTimestamp: nil,
                DeletionGracePeriodSeconds: nil,
                Labels: {
                    "kueue.x-k8s.io/tas": "true",
                    "ray.io/group": "headgroup",
                    "ray.io/identifier": "ranks-ray-raycluster-gpzrs-head",
                    "ray.io/is-ray-node": "yes",
                    "app.kubernetes.io/created-by": "kuberay-operator",
                    "kueue.x-k8s.io/podset": "head",
                    "ray.io/cluster": "ranks-ray-raycluster-gpzrs",
                    "ray.io/node-type": "head",
                    "app.kubernetes.io/name": "kuberay",
                },
                Annotations: {
                    "kueue.x-k8s.io/podset-preferred-topology": "cloud.provider.com/topology-rack",
                    "kueue.x-k8s.io/workload": "rayjob-ranks-ray-8120c",
                    "ray.io/ft-enabled": "false",
                },
                OwnerReferences: [
                    {
                        APIVersion: "ray.io/v1",
                        Kind: "RayCluster",
                        Name: "ranks-ray-raycluster-gpzrs",
                        UID: "0616b0a6-e920-481b-9516-db1f0880f2b1",
                        Controller: true,
                        BlockOwnerDeletion: true,
                    },
                ],
                Finalizers: nil,
                ManagedFields: [
                    {
                        Manager: "kuberay-operator",
                        Operation: "Update",
                        APIVersion: "v1",
                        Time: {
                            Time: 2025-03-05T22:40:41Z,
                        },
                        FieldsType: "FieldsV1",
                        FieldsV1: {
                            Raw: "{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kueue.x-k8s.io/podset-preferred-topology\":{},\"f:kueue.x-k8s.io/workload\":{},\"f:ray.io/ft-enabled\":{}},\"f:generateName\":{},\"f:labels\":{\".\":{},\"f:app.kubernetes.io/created-by\":{},\"f:app.kubernetes.io/name\":{},\"f:kueue.x-k8s.io/podset\":{},\"f:kueue.x-k8s.io/tas\":{},\"f:ray.io/cluster\":{},\"f:ray.io/group\":{},\"f:ray.io/identifier\":{},\"f:ray.io/is-ray-node\":{},\"f:ray.io/node-type\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"0616b0a6-e920-481b-9516-db1f0880f2b1\\\"}\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"head-container\\\"}\":{\".\":{},\"f:args\":{},\"f:command\":{},\"f:env\":{\".\":{},\"k:{\\\"name\\\":\\\"KUBERAY_GEN_RAY_START_CMD\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_ADDRESS\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_CLOUD_INSTANCE_ID\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:fieldRef\":{}}},\"k:{\\\"name\\\":\\\"RAY_CLUSTER_NAME\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:fieldRef\":{}}},\"k:{\\\"name\\\":\\\"RAY_DASHBOARD_ENABLE_K8S_DISK_USAGE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_NODE_TYPE_NAME\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:fieldRef\":{}}},\"k:{\\\"name\\\":\\\"RAY_PORT\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_USAGE_STATS_EXTRA_TAGS\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"RAY_USAGE_STATS_KUBERAY_IN_USE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"REDIS_PASSWORD\\\"}\":{\".\":{},\"f...

Gomega truncated this representation as it exceeds 'format.MaxLength'.
Consider having the object provide a custom 'GomegaStringer' representation
or adjust the parameters in Gomega's 'format' package.

Learn more here: https://onsi.github.io/gomega/#adjusting-output

to have length 5
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/tas/rayjob_test.go:207 @ 03/05/25 22:45:41.951
}
```

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-tas-main/1897412525620727808

Image

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
We temporarily don't assert on the exact number of Pods as this flakes on Ray 1.2.2
 due to the submitter Pod and Job not being created occasionally 
(See https://github.com/kubernetes-sigs/kueue/issues/4508#issuecomment-2724257298 for more details).

#### Which issue(s) this PR fixes:

Fixes #4508 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/tas/rayjob_test.go [hunk 1]
```diff
@@ -89,11 +105,10 @@ var _ = ginkgo.Describe("TopologyAwareScheduling for RayJob", ginkgo.Ordered, fu
...
 		ginkgo.It("Should place pods based on the ranks-ordering", func() {
 			const (
-				headReplicas     = 1
-				workerReplicas   = 3
-				submitterReplica = 1
+				headReplicas   = 1
+				workerReplicas = 3
 			)
-			numPods := headReplicas + workerReplicas + submitterReplica
+			numPods := headReplicas + workerReplicas
```
[the remark this answers is not in the document]
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:111]: yes, good point

[the remark this answers is not in the document]
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:111]: Changed to:
`g.Expect(len(pods.Items)).Should(gomega.BeNumerically(">=", numPods))`

File: test/e2e/tas/rayjob_test.go [hunk 2]
```diff
@@ -179,7 +194,7 @@ var _ = ginkgo.Describe("TopologyAwareScheduling for RayJob", ginkgo.Ordered, fu
 					},
 					ObjectMeta: metav1.ObjectMeta{
 						Annotations: map[string]string{
-							kueuealpha.PodSetRequiredTopologyAnnotation: testing.DefaultBlockTopologyLevel,
+							kueuealpha.PodSetPreferredTopologyAnnotation: testing.DefaultBlockTopologyLevel,
```
[the remark this answers is not in the document]
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:197]: This was something I tested, but it shouldn't end up here, sorry.
Reverting this ofc

File: test/e2e/tas/rayjob_test.go [hunk 3]
```diff
@@ -45,6 +59,8 @@ var _ = ginkgo.Describe("TopologyAwareScheduling for RayJob", ginkgo.Ordered, fu
 	)
 
 	ginkgo.BeforeEach(func() {
+		format.RegisterCustomFormatter(podsFormatter)
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:62]: It feels like this should be an orthogonal change. Maybe we want to use this (or another) formatter for other tests.

Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:62]: Let me split it then

File: test/e2e/tas/rayjob_test.go [hunk 4]
```diff
@@ -197,13 +201,16 @@ var _ = ginkgo.Describe("TopologyAwareScheduling for RayJob", ginkgo.Ordered, fu
...
-			ginkgo.By("ensure all pods are created", func() {
+			ginkgo.By("ensure all pods are created and raycluster is ready", func() {
 				gomega.Eventually(func(g gomega.Gomega) {
 					g.Expect(k8sClient.List(ctx, pods, client.InNamespace(rayjob.Namespace))).To(gomega.Succeed())
-					g.Expect(pods.Items).Should(gomega.HaveLen(numPods))
+					g.Expect(len(pods.Items)).Should(gomega.BeNumerically(">=", numPods))
 					// The timeout is long to ensure all cluster pods are up and running.
 					// This is because the Ray image takes long time (around 170s on the CI)
 					// to load and then to sync with head.
+					createdRayJob := &rayv1.RayJob{}
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:211]: actually, o don't see a need to check the pods are running. checking that they get scheduled should be enough imo. I suggest to make the fix minimal. no need to add extra asserts. so that it is clear the assets are relaxed actually

File: test/e2e/tas/rayjob_test.go [hunk 5]
```diff
@@ -222,6 +223,20 @@ var _ = ginkgo.Describe("TopologyAwareScheduling for RayJob", ginkgo.Ordered, fu
 				gotAssignment := readAssignedNodes(pods.Items)
 				gomega.Expect(gotAssignment).Should(gomega.HaveLen(workerReplicas))
 			})
+
+			wlLookupKey := types.NamespacedName{
+				Name: workloadrayjob.GetWorkloadNameForRayJob(rayjob.Name, rayjob.UID), Namespace: ns.Name,
+			}
+			ginkgo.By("Waiting for the RayJob to finish", func() {
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:230]: Will this actually succeed in cases when we don't have the submitter Job and Pod created?

File: test/e2e/tas/rayjob_test.go [hunk 6]
```diff
@@ -222,6 +223,20 @@ var _ = ginkgo.Describe("TopologyAwareScheduling for RayJob", ginkgo.Ordered, fu
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					createdRayJob := &rayv1.RayJob{}
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(rayjob), createdRayJob)).To(gomega.Succeed())
+					g.Expect(createdRayJob.Status.JobDeploymentStatus).To(gomega.Equal(rayv1.JobDeploymentStatusComplete))
+					g.Expect(createdRayJob.Status.JobStatus).To(gomega.Equal(rayv1.JobStatusSucceeded))
+					finishReasonMessage := "Job finished successfully."
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:236]: Actually, I would prefer not o test the message in e2e tests. Message is free to change at any point.

File: test/e2e/tas/rayjob_test.go (hunk 5 above)
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:230]: No, but the benefit is we don't have to rely on the specific point in time when job submitter pod is created, only what it does.

File: test/e2e/tas/rayjob_test.go (hunk 6 above)
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:236]: sure, make sense, checking job status should be enough

File: test/e2e/tas/rayjob_test.go (hunk 5 above)
Comment (mimowo) [reply test/e2e/tas/rayjob_test.go:225]: Hm, so actually this PR would not fix the flake?

**Comment by mszadkow** [comment]
LWS is failing the CI

File: test/e2e/tas/rayjob_test.go (hunk 5 above)
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:225]: If there is deeper issue with RayJob submitter pod then not

Comment (mimowo) [reply test/e2e/tas/rayjob_test.go:225]: Maybe just drop the expectation about the workload finishing for now? From TAS PoV the most important thing is that the Pods get scheduled, and the lend on the consecutive kind-worker nodes. I know we don't have rank based ordering for Ray, but we could just check the set of workers, as done here: https://github.com/kubernetes-sigs/kueue/blob/69a9538f234aaeed55d825ac04e8c1338e62c5a7/test/e2e/tas/pod_group_test.go#L169-L183

Comment (mimowo) [reply test/e2e/tas/rayjob_test.go:225]: I would be ok-ish with that yes. However, this only asserts on the number of scheduled workers, but they could still be scattered. If they are scheduled by TAS they would not be scattered, so the assert on the set of workers is a bit stronger, confirming that TAS was used indeed, but this is not a strong view.

File: test/e2e/tas/rayjob_test.go [hunk 7]
```diff
@@ -200,7 +199,7 @@ var _ = ginkgo.Describe("TopologyAwareScheduling for RayJob", ginkgo.Ordered, fu
 			ginkgo.By("ensure all pods are created", func() {
 				gomega.Eventually(func(g gomega.Gomega) {
 					g.Expect(k8sClient.List(ctx, pods, client.InNamespace(rayjob.Namespace))).To(gomega.Succeed())
-					g.Expect(pods.Items).Should(gomega.HaveLen(numPods))
+					g.Expect(len(pods.Items)).Should(gomega.BeNumerically(">=", numPods))
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:202]: Add a comment like:
```
// TODO: strengthen the assert after moving to Ray >=1.3.1.
// We temporarily don't assert on the exact number of Pods as this flakes on Ray
// 1.2.2 due to the submitter Pod and Job not being created occasionally (See 
// https://github.com/kubernetes-sigs/kueue/issues/4508#issuecomment-2724257298
// for more details).
```

Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:207]: done

Comment (mimowo) [reply test/e2e/tas/rayjob_test.go:207]: Update `TODO(#4665)`

**Comment by mimowo** [comment]
```
Deleting cluster "kind" ...
ERROR: failed to delete cluster "kind": failed to delete nodes: command "docker rm -f -v kind-control-plane kind-worker kind-worker2" failed with error: exit status 1
Command Output: Error response from daemon: cannot remove container "/kind-control-plane": could not kill: tried to kill container, but did not receive an exit event
Error response from daemon: cannot remove container "/kind-worker": could not kill: tried to kill container, but did not receive an exit event
Error response from daemon: cannot remove container "/kind-worker2": could not kill: tried to kill container, but did not receive an exit event
make: *** [Makefile-test.mk:170: run-test-e2e-customconfigs-1.31.1] Error 1
+ EXIT_VALUE=2
```
infra failure not related to the pr
/test pull-kueue-test-e2e-customconfigs-main

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Thanks!

File: test/e2e/tas/rayjob_test.go (hunk 7 above)
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:207]: done

**Comment by mimowo** [comment]
/cherry-pick release-0.10
To make the release branch more stable
