### PR TITLE
[TAS] Fix LeastFreeCapacity algorithm for assignment that covers more than one node and there are empty nodes on the cluster

### LINKED ISSUE #8157: Unconstrained workload with LeastFreeCapacity Algorithm Scheduling Bug
**What happened**:
unconstrained workload cannot be scheduled at all if there is domain with 0 capacity

**What you expected to happen**:
It skips the 0 capacity domains and be assigned to other domains with capacity

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
When unconstrainted workload is used with LeastFreeCapacity, the domains are sorted ascend, the domains with 0 capacity will appear in the beginning of the queue which causes the  loop immediately exits.

```
sortedDomain = s.sortedDomains(sortedDomain[idx:], unconstrained)
for idx := 0; remainingSliceCount > 0 && idx < len(sortedDomain) && sortedDomain[idx].sliceState > 0; idx++ {
```
https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/scheduler/tas_flavor_snapshot.go#L1102-L1103

By removing the `sortedDomain[idx].sliceState > 0`, the job can be correctly scheduled

**Environment**:
- Kueue version (use `git describe --tags --dirty --always`): 0.15, when mixed profile is being used for unconstrainted workload

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When using LeastFreeCapacity algorithm TAS didn't schedule workloads that needed more than one node when there empty nodes in the cluster 

#### Which issue(s) this PR fixes:

Fixes #8157 

#### Does this PR introduce a user-facing change?

```release-note
TAS: Fix handling of admission for workloads using the LeastFreeCapacity algorithm when the  "unconstrained"
mode is used. In that case scheduling would fail if there is at least one node in the cluster which does not have
enough capacity to accommodate at least one Pod.
```

### CODE REVIEW

**Comment by PBundyra** [comment]
cc @mimowo

File: pkg/cache/scheduler/tas_flavor_snapshot.go [hunk 1]
```diff
@@ -1082,7 +1082,7 @@ func (s *TASFlavorSnapshot) findLevelWithFitDomains(levelIdx int, required bool,
 		// "unused" domains based on worker capacity (sliceState, state and then levelValues) and
 		// try to assign remaining workers.
 		idx := 0
-		for ; remainingLeaderCount > 0 && idx < len(sortedDomain) && sortedDomain[idx].leaderState > 0; idx++ {
```
Comment (mimowo) [inline pkg/cache/scheduler/tas_flavor_snapshot.go:1085]: This change look good, but it would be great to also add a small unit test for it

File: pkg/scheduler/scheduler_tas_test.go [hunk 2]
```diff
@@ -147,6 +147,42 @@ func TestScheduleForTAS(t *testing.T) {
 			Obj(),
 	}
 
+	//    r1
+	//  /  |  \
+	// x1  x2  x3
+	partiallyEmptyNodes := []corev1.Node{
```
Comment (mimowo) [inline pkg/scheduler/scheduler_tas_test.go]: I think `partiallyEmptyNodes` does not really capture the intention well, which is to say: "nodes with at least one instance which has no free capacity". Such nodes I would say are rather "full" or "exhausted" rather than "empty". 

Maybe "nodesWithExhaustedCapacity"?

Comment (mimowo) [reply pkg/scheduler/scheduler_tas_test.go]: or `nodesWithZeroCapacityInstance`

**Comment by mimowo** [comment]
Proposal to make it a bit more user oriented
/release-note-edit
```release-note
Fix handling of admission for workloads using the LeastFreeCapacity algorithm when the  "unconstrained"
mode is used. In that case scheduling would fail if there is at least one node in the cluster which does not have
enough capacity to accommodate at least one Pod.
```

File: pkg/cache/scheduler/tas_flavor_snapshot.go (hunk 1 above)
Comment (PBundyra) [reply pkg/cache/scheduler/tas_flavor_snapshot.go:1085]: Revert for now, will address it a follow-up PR

File: pkg/scheduler/scheduler_tas_test.go (hunk 2 above)
Comment (PBundyra) [reply pkg/scheduler/scheduler_tas_test.go]: Done

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
TAS: Fix handling of admission for workloads using the LeastFreeCapacity algorithm when the  "unconstrained"
mode is used. In that case scheduling would fail if there is at least one node in the cluster which does not have
enough capacity to accommodate at least one Pod.
```
