### PR TITLE
[sclability] Relax the expectations.

### LINKED ISSUE #2066: Scalability test is flaky
**What happened**:

It flaked on unrelated branch: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2047/pull-kueue-test-scheduling-perf-main/1783505231846313984

**What you expected to happen**:

Not flake

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the build on CI

**Anything else we need to know?**:

The asserts were only recently added so they may need tuning: https://github.com/kubernetes-sigs/kueue/pull/2043

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
- Extend the admission time for large workloads
- Only check the average mCPU usage of minimalkueue (not sys and user times)
- Extend the runner's timeout to 8 min
#### Which issue(s) this PR fixes:

Fixes #2066

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: test/scalability/checker/checker_test.go [hunk 1]
```diff
@@ -35,10 +35,8 @@ var (
 
 type RangeSpec struct {
 	Cmd struct {
-		MaxWallMs int64  `json:"maxWallMs"`
```
Comment (mimowo) [inline test/scalability/checker/checker_test.go:38]: Why changing this?

File: test/scalability/default_rangespec.yaml [hunk 2]
```diff
@@ -22,8 +16,8 @@ clusterQueueClassesMinUsage:
   cq: 56 #%
 
 wlClassesMaxAvgTimeToAdmissionMs:
-  # Average value 6666 (+/- 14%), setting at +20%
-  large: 8_000
+  # Average value 6666 (+/- 14%), setting at +35%
```
Comment (mimowo) [inline test/scalability/default_rangespec.yaml:19]: Can we have some methodology that allows us to estimate the expected ratio of failures? Maybe something along the lines [here](https://github.com/kubernetes-sigs/kueue/issues/2066#issuecomment-2077592505)? 

Otherwise it is unclear that this +35% mean. 

I'm ok to leave it as a follow up.

File: Makefile [hunk 3]
```diff
@@ -256,6 +256,7 @@ test-scalability: gotestsum run-scalability
 	$(GOTESTSUM) --junitfile $(ARTIFACTS)/junit.xml -- $(GO_TEST_FLAGS) ./test/scalability/checker  \
 		--summary=$(SCALABILITY_RUN_DIR)/summary.yaml \
 		--cmdStats=$(SCALABILITY_RUN_DIR)/minimalkueue.stats.yaml \
+		--timeout=8m \
```
Comment (mimowo) [inline Makefile:259]: Maybe 10m to be on the safer side? I guess if the test is interrupted we may not get the stats to investigate post-factum?

File: test/scalability/default_rangespec.yaml [hunk 4]
```diff
@@ -5,14 +5,8 @@
...
-  # Average value 351116.4 (+/- 0.9%), setting at +5%
-  maxWallMs: 368_000
-
-  # Average value 111500 (+/- 14%), setting at +20%
-  maxUserMs: 134_000
-
-  # Average value 27875 (+/- 16%), setting at +20%
-  maxSysMs: 34_000
+  # Average value 396 mCPU (+/- 8%), setting at +25%
+  mCPU: 500
```
Comment (mimowo) [inline test/scalability/default_rangespec.yaml:9]: I actually prefer not to measure average cpu, because it is hard to get intuition about if lower or higher is actually better. The previous measurements are more intuitive. I guess if there are too meany of them to set, then
I would suggest to control just for `maxWallMs` as the most intuitive.

File: test/scalability/default_rangespec.yaml (hunk 2 above)
Comment (trasc) [reply test/scalability/default_rangespec.yaml:19]: We'll need some kind of stable way of running an collecting the results, we don't at this point, and as we just saw the CI env is not very predictable.

File: test/scalability/checker/checker_test.go (hunk 1 above)
Comment (trasc) [reply test/scalability/checker/checker_test.go:38]: To not be tight to absolute values.

File: Makefile (hunk 3 above)
Comment (trasc) [reply Makefile:259]: The default is 5 , we should not double just because it did not fit in 5 min once.

File: test/scalability/default_rangespec.yaml (hunk 2 above)
Comment (mimowo) [reply test/scalability/default_rangespec.yaml:19]: Right, that is why I'm thinking about fitting the standard distribution of the results, with this approach we can account for the variance. If the variance is high, we will get a high threshold, that's ok.  Still, it will let us set the threshold to control the ratio of failures.

File: test/scalability/default_rangespec.yaml (hunk 4 above)
Comment (mimowo) [reply test/scalability/default_rangespec.yaml:9]: I think from the user's perspective what is important is the overall time, and this is what we should primarly control for.

File: test/scalability/checker/checker_test.go (hunk 1 above)
Comment (mimowo) [reply test/scalability/checker/checker_test.go:38]: As in the other comment, I prefer to use the more intuitive values. Can we please just focus this PR on fixing the flake, and bump the values?

File: Makefile (hunk 3 above)
Comment (mimowo) [reply Makefile:259]: As you prefer, just pointing out I would be fine with a higher value, so that we don't lose data in some cases.

File: test/scalability/default_rangespec.yaml (hunk 2 above)
Comment (trasc) [reply test/scalability/default_rangespec.yaml:19]: Why are we discussing things like this in a PR that should be a quick fix for a bug which may or may not block the CI pipeline. (Good thing that the load on the CI clusters has decrease and the tests are now passing :) )

File: test/scalability/default_rangespec.yaml (hunk 4 above)
Comment (alculquicondor) [reply test/scalability/default_rangespec.yaml:9]: I also don't see a direct relationship between CPU time and user-perceived performance.

If we are doing parallel algorithms, we would user more CPU and that's not necessarily bad.

File: test/scalability/default_rangespec.yaml (hunk 2 above)
Comment (mimowo) [reply test/scalability/default_rangespec.yaml:19]: I'm totally for a quick fix, I'm even surprised there is more changes than just bumping the thresholds. 

I just point out it will be good to follow up with some more methodological approach.

File: test/scalability/default_rangespec.yaml (hunk 4 above)
Comment (trasc) [reply test/scalability/default_rangespec.yaml:9]: 1. The difference when it comes to timing more or less direct will be detected by wl admission times or the runner's timeout if relevant. 

2. The CPU consumption matters also, I believe that the default deployment of kueue has 500nCPU allocated by default.

3. Checking absolute values of sys and user time is too much for our use-case.

Comment (alculquicondor) [reply test/scalability/default_rangespec.yaml:9]: > Checking absolute values of sys and user time is too much for our use-case.

I agree with this. But then we can just keep the wall time.

Regarding CPU utilization, I agree with the following:

> it is hard to get intuition about if lower or higher is actually better.

Comment (trasc) [reply test/scalability/default_rangespec.yaml:9]: If doing the same job quantity (static by config) and quality (expectations are checked) less CPU is better.

Comment (alculquicondor) [reply test/scalability/default_rangespec.yaml:9]: We might need to later optimize the algorithms using parallelism (and correspondingly increase the default CPU requests).

Once you have parallelism, CPU usage wouldn't account for how long we are waiting on locks.

Comment (trasc) [reply test/scalability/default_rangespec.yaml:9]: As long as the implementation requires extra resources (cpu, memmory, time) and we are aware of that there is no problem changing rangespec in the same pr.

Comment (trasc) [reply test/scalability/default_rangespec.yaml:12]: I've added back the wall time check, but when it comes to sys vs user time , we really should not care what the cpu is doing and continue to check the average mCPU consumption.

Comment (mimowo) [reply test/scalability/default_rangespec.yaml:12]: I'm happy for dropping `UserMs` and `SysMS`. I would suggest to also not add `mCPUUsed` and I'm happy to go forward with this PR.

File: Makefile (hunk 3 above)
Comment (mimowo) [reply Makefile]: Any reason to revert it? Are we expecting some flakes here still that we should address separately?

File: test/scalability/default_rangespec.yaml (hunk 4 above)
Comment (trasc) [reply test/scalability/default_rangespec.yaml:12]: > For example, my intuition tells me that in this https://github.com/kubernetes-sigs/kueue/pull/1952 we might have increased mCPU by avoiding waiting on List requests, and that is desired.

For this kind of case there is no problem to update the rangespec as well. 

The the reason of this checks should not be to set some absolute value to be respected but help us detect when we louse performance (having longer wait to admission times, having a drop in the cluster queue resource usage, using more memory, using more CPU) without a clear expectation for that to happen.

Comment (mimowo) [reply test/scalability/default_rangespec.yaml]: Having any of the checks goes beyond the [design doc](https://docs.google.com/document/d/1iO8CGO6kgav2JL6RKYnNYvkeQIHpFqB-SQqJ7eUsjPs/edit?tab=t.0#heading=h.e5jhgh56ju14). I'm ok to accept some of them for exploration purposes, but I'm afraid having the additional check, especially not so intuitive will add a chore.

Can we please make this PR a quick fix bumping the thresholds, and have a separate discussion on including extra thresholds?

Comment (trasc) [reply test/scalability/default_rangespec.yaml]: The check is doing the exact same thing, the only difference being that we judge sys and user times together.

Comment (mimowo) [reply test/scalability/default_rangespec.yaml]: I don't think we need the checks for sys time, user time or mCPU at all for now.

Comment (trasc) [reply test/scalability/default_rangespec.yaml]: Cpu is an important resource, just like memory, why should it be ignored?

Comment (mimowo) [reply test/scalability/default_rangespec.yaml]: For now we don't have a way to reliably set the thresholds. In order to move forward I suggest:
1. adjust in this PR the thresholds according to https://github.com/kubernetes-sigs/kueue/issues/2066#issuecomment-2079053502, this should help
2. follow up and do a small script that will automate it
3. discuss the new measurements, including mCPU with threshold set based on the script

Comment (alculquicondor) [reply test/scalability/default_rangespec.yaml]: That makes it less useful. Let's remove it.

Comment (trasc) [reply test/scalability/default_rangespec.yaml]: > That makes it less useful.

How?

**Comment by alculquicondor** [comment]
Since mCPU is just a transformation of the existing checks for system and user, we can assume this as not adding or removing anything.

In the future, I would like to remove the measurement of cpu entirely, as it doesn't directly map to user-perceived performance.

/lgtm
/approve
