### PR TITLE
Fix race in RemoveRemoteObjects where remote LWS is not deleted

### LINKED ISSUE #9178: [Flaky e2e]  MultiKueue when Creating a multikueue admission check Should sync a LeaderWorkerSet and run replicas on worker cluster
**Which test is flaking?**:
End To End MultiKueue Suite: kindest/node:v1.35.0: [It] MultiKueue when Creating a multikueue admission check Should sync a LeaderWorkerSet and run replicas on worker cluster

**Link to failed CI job or steps to reproduce locally**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9172/pull-kueue-test-e2e-multikueue-main/2021972406486175744

**Failure message or logs**:
```
{Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:126 with:
Error matcher expects an error.  Got:
    <nil>: nil failed [FAILED] Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:126 with:
Error matcher expects an error.  Got:
    <nil>: nil
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:543 @ 02/12/26 15:53:19.479
}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by sohankunkerkar**
When MultiKueueGC deletes the remote workload before the reconciler processes the deletion, RemoveRemoteObjects would early-return on `remWl == nil` without deleting the remote controller object (e.g., LWS).

Move `DeleteRemoteObject` before the nil check to ensure the remote controller object is always deleted regardless of remote workload state.

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #9178

#### Does this PR introduce a user-facing change?

```release-note
MultiKueue: Fix a bug that the remote Job object was occasionally left by MultiKueue GC, 
even when the corresponding Job object on the management cluster was deleted.
This issue was observed for LeaderWorkerSet.
```

### CODE REVIEW

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 1]
```diff
@@ -127,14 +127,18 @@ func (g *wlGroup) bestMatchByCondition(conditionType string) (*metav1.Condition,
 	return bestMatchCond, bestMatchRemote
 }
 
+// RemoveRemoteObjects deletes the remote controller object and workload for a cluster.
+// The controller object is deleted first to handle cases where GC has already removed
+// the remote workload.
 func (g *wlGroup) RemoveRemoteObjects(ctx context.Context, cluster string) error {
+	if err := g.jobAdapter.DeleteRemoteObject(ctx, g.remoteClients[cluster].client, g.controllerKey); err != nil {
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go:134]: Should we IgnoreNotFound() error?

Comment (sohankunkerkar) [reply pkg/controller/admissionchecks/multikueue/workload.go:134]: All `DeleteRemoteObject` implementations already wrap the delete with `client.IgnoreNotFound()`, so this is already handled internally

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:134]: Yes, but in that case we can't handle workloads, right?

Comment (sohankunkerkar) [reply pkg/controller/admissionchecks/multikueue/workload.go:134]: Correct, when `remWl` is nil, the remote workload is already gone, so there's nothing to handle. We just delete the controller object and return.

**Comment by mimowo** [comment]
/release-note-edit
```release-note
LeaderWorkerSet: Fix orphaned remote resources when deleting MultiKueue workloads under concurrent GC
```
/lgtm
/approve
/cherrypick release-0.16
/cherrypick release-0.15

**Comment by mimowo** [comment]
~This is very similar issue as for deleting Workloads from job reconciler. Could you follow up with commonizing the code~

**Comment by mimowo** [comment]
Let me rephrase the release note as the fix is general for MultiKueue. 
It seems it could also affect other Jobs, not only LWS, but I'm not sure. Any idea @sohankunkerkar if this
could be more generic than LWS?

/release-note-edit
```release-note
MultiKueue: Fix a bug that the remote Job object was occasionally left by MultiKueue GC, 
even when the corresponding Job object on the management cluster was deleted.
This issue was observed for LeaderWorkerSet.
```

**Comment by sohankunkerkar** [comment]
> Let me rephrase the release note as the fix is general for MultiKueue. It seems it could also affect other Jobs, not only LWS, but I'm not sure. Any idea @sohankunkerkar if this could be more generic than LWS?
> 
> /release-note-edit
> 
> ```
> MultiKueue: Fix a bug that the remote Job object was occasionally left by MultiKueue GC, 
> even when the corresponding Job object on the management cluster was deleted.
> This issue was observed for LeaderWorkerSet.
> ```

Yeah, that makes sense!
