### PR TITLE
Filter workload infos by namespace in pendingWorkloadsInLqREST.

### LINKED ISSUE #10575: Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job Should allow fetching information about position of pending workloads from different LocalQueues from different Namespaces
**Which test is flaking?**:
Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job Should allow fetching information about position of pending workloads from different LocalQueues from different Namespaces
**Link to failed CI job or steps to reproduce locally**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/10568/pull-kueue-test-e2e-main-1-34/2045087127292612608
**Failure message or logs**:
```
{ failed [FAILED] Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/visibility_test.go:531 with:
Expected object to be comparable, diff:   []v1beta2.PendingWorkload{
  	{ObjectMeta: {Namespace: "e2e-hh825", OwnerReferences: {{APIVersion: "batch/v1", Kind: "Job", Name: "lq-b-mid-prio"}}}, Priority: 75, LocalQueueName: "b", PositionInClusterQueue: 1, ...},
+ 	{
+ 		ObjectMeta:             v1.ObjectMeta{Namespace: "e2e-hh825", OwnerReferences: []v1.OwnerReference{{...}}},
+ 		Priority:               50,
+ 		LocalQueueName:         "b",
+ 		PositionInClusterQueue: 2,
+ 		PositionInLocalQueue:   1,
+ 	},
  }
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/visibility_test.go:532 @ 04/17/26 10:52:49.647
}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #10575

#### Special notes for your reviewer:

https://github.com/kubernetes-sigs/kueue/pull/10668#discussion_r3121744369.

#### Does this PR introduce a user-facing change?

```release-note
VisibilityOnDemand: Fixed a bug in the visibility endpoint, that listing workloads from a local queue includes
workloads from other LocalQueues in different namespaces, if the other LocalQueues have the same name.
```

### CODE REVIEW

File: test/e2e/singlecluster/visibility_test.go [hunk 1]
```diff
@@ -502,6 +502,14 @@ var _ = ginkgo.Describe("Kueue visibility server", ginkgo.Label("area:singleclus
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
 			})
 
+			ginkgo.By("Verify there is no info in nsA", func() {
+				gomega.Consistently(func(g gomega.Gomega) {
+					info, err := kueueClientset.VisibilityV1beta2().LocalQueues(nsA.Name).GetPendingWorkloadsSummary(ctx, localQueueB.Name, metav1.GetOptions{})
+					g.Expect(err).NotTo(gomega.HaveOccurred())
+					g.Expect(info.Items).Should(gomega.BeEmpty())
+				}, util.ConsistentDuration, util.ShortInterval).Should(gomega.Succeed())
+			})
```
Comment (mimowo) [inline test/e2e/singlecluster/visibility_test.go]: Instead of complicating the existing test, please add a dedicated one which creates two namespaces.

**Review by mimowo — COMMENTED** [review]
LGTM, thanks for the ifx 👍

File: test/e2e/singlecluster/visibility_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/e2e/singlecluster/visibility_test.go]: Done

**Comment by mimowo** [comment]
Thank you 👍 
/lgtm
/approve

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Observability: Fixed a bug in the visibility endpoint, that listing workloads from a local queue includes
workloads from other LocalQueues in different namespaces, if the other LocalQueues have the same name. 
```

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
VisibilityOnDemand: Fixed a bug in the visibility endpoint, that listing workloads from a local queue includes
workloads from other LocalQueues in different namespaces, if the other LocalQueues have the same name.
```
