### PR TITLE
[flaky test] AFS integration test makes Kueue panic / crash

### LINKED ISSUE #5898: [flaky test] AFS integration test makes Kueue panic / crash
/kind flake

**What happened**:

Example failed build where Kueue paniced: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-main/1942472892331593728

**What you expected to happen**:

No failures

**How to reproduce it (as minimally and precisely as possible)**:

run on CI

**Anything else we need to know?**:

```
[1mOutput from proc 4:[0m
  E0708 06:52:34.098576   34127 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
  	goroutine 229 [running]:
  	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x352b1d0, 0xc00138e090}, {0x2e22860, 0x47a1ef0})
  		/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:132 +0xdd
  	k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x352cab8, 0xc00049c000}, {0x2e22860, 0x47a1ef0}, {0x0, 0x0, 0x4b5652?})
  		/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0x185
  	k8s.io/apimachinery/pkg/util/runtime.HandleCrashWithContext({0x352cab8, 0xc00049c000}, {0x0, 0x0, 0x0})
  		/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:78 +0x69
  	panic({0x2e22860?, 0x47a1ef0?})
  		/usr/local/go/src/runtime/panic.go:792 +0x132
  	sigs.k8s.io/kueue/pkg/workload.(*Info).CalcLocalQueueFSUsage(0xc000782e80, {0x352b1d0, 0xc000bc9c80}, {0x3539bc0, 0xc0001f1710}, 0x0)
  		/home/prow/go/src/kubernetes-sigs/kueue/pkg/workload/workload.go:310 +0x1d3
  	sigs.k8s.io/kueue/pkg/cache.(*Cache).snapshotClusterQueue(0xc000492700, {0x352b1d0, 0xc000bc9c80}, 0xc000992800)
  		/home/prow/go/src/kubernetes-sigs/kueue/pkg/cache/snapshot.go:194 +0x1173
  	sigs.k8s.io/kueue/pkg/cache.(*Cache).Snapshot(0xc000492700, {0x352b1d0, 0xc000bc9c80})
  		/home/prow/go/src/kubernetes-sigs/kueue/pkg/cache/snapshot.go:142 +0xee8
  	sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).schedule(0xc0006400a0, {0x352b1d0, 0xc000a48120})
  		/home/prow/go/src/kubernetes-sigs/kueue/pkg/scheduler/scheduler.go:193 +0x397
  	sigs.k8s.io/kueue/pkg/util/wait.untilWithBackoff.func1()
  		/home/prow/go/src/kubernetes-sigs/kueue/pkg/util/wait/backoff.go:43 +0x59
  	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1({0xc000120380?, 0x0?})
  		/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x2f
  	k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1({0x352cab8, 0xc00049c000}, 0xc000067ec8)
  		/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:255 +0x9d
  	k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext({0x352cab8, 0xc00049c000}, 0xc000067ec8, {0x350a5c0, 0xc000516030}, 0x0)
  		/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xee
  	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00035df10, {0x350a5c0, 0xc000516030}, 0x0, 0xc00049c000)
  		/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x8b
  	sigs.k8s.io/kueue/pkg/util/wait.untilWithBackoff({0x352b1d0, 0xc000a48120}, 0xc00100e1c0, {0x351f020, 0xc000d8a008})
  		/home/prow/go/src/kubernetes-sigs/kueue/pkg/util/wait/backoff.go:42 +0x145
  	sigs.k8s.io/kueue/pkg/util/wait.UntilWithBackoff({0x352b1d0, 0xc000a48120}, 0xc00100e1c0)
  		/home/prow/go/src/kubernetes-sigs/kueue/pkg/util/wait/backoff.go:34 +0xca
  	created by sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).Start in goroutine 103
  		/home/prow/go/src/kubernetes-sigs/kueue/pkg/scheduler/scheduler.go:148 +0x234
   >
  panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  	panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29fac53]

  goroutine 229 [running]:
  k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x352cab8, 0xc00049c000}, {0x2e22860, 0x47a1ef0}, {0x0, 0x0, 0x4b5652?})
  	/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:114 +0x23a
  k8s.io/apimachinery/pkg/util/runtime.HandleCrashWithContext({0x352cab8, 0xc00049c000}, {0x0, 0x0, 0x0})
  	/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:78 +0x69
  panic({0x2e22860?, 0x47a1ef0?})
  	/usr/local/go/src/runtime/panic.go:792 +0x132
  sigs.k8s.io/kueue/pkg/workload.(*Info).CalcLocalQueueFSUsage(0xc000782e80, {0x352b1d0, 0xc000bc9c80}, {0x3539bc0, 0xc0001f1710}, 0x0)
  	/home/prow/go/src/kubernetes-sigs/kueue/pkg/workload/workload.go:310 +0x1d3
  sigs.k8s.io/kueue/pkg/cache.(*Cache).snapshotClusterQueue(0xc000492700, {0x352b1d0, 0xc000bc9c80}, 0xc000992800)
  	/home/prow/go/src/kubernetes-sigs/kueue/pkg/cache/snapshot.go:194 +0x1173
  sigs.k8s.io/kueue/pkg/cache.(*Cache).Snapshot(0xc000492700, {0x352b1d0, 0xc000bc9c80})
  	/home/prow/go/src/kubernetes-sigs/kueue/pkg/cache/snapshot.go:142 +0xee8
  sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).schedule(0xc0006400a0, {0x352b1d0, 0xc000a48120})
  	/home/prow/go/src/kubernetes-sigs/kueue/pkg/scheduler/scheduler.go:193 +0x397
  sigs.k8s.io/kueue/pkg/util/wait.untilWithBackoff.func1()
  	/home/prow/go/src/kubernetes-sigs/kueue/pkg/util/wait/backoff.go:43 +0x59
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1({0xc000120380?, 0x0?})
  	/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x2f
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1({0x352cab8, 0xc00049c000}, 0xc000067ec8)
  	/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:255 +0x9d
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext({0x352cab8, 0xc00049c000}, 0xc000067ec8, {0x350a5c0, 0xc000516030}, 0x0)
  	/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xee
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00035df10, {0x350a5c0, 0xc000516030}, 0x0, 0xc00049c000)
  	/home/prow/go/src/kubernetes-sigs/kueue/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x8b
  sigs.k8s.io/kueue/pkg/util/wait.untilWithBackoff({0x352b1d0, 0xc000a48120}, 0xc00100e1c0, {0x351f020, 0xc000d8a008})
  	/home/prow/go/src/kubernetes-sigs/kueue/pkg/util/wait/backoff.go:42 +0x145
  sigs.k8s.io/kueue/pkg/util/wait.UntilWithBackoff({0x352b1d0, 0xc000a48120}, 0xc00100e1c0)
  	/home/prow/go/src/kubernetes-sigs/kueue/pkg/util/wait/backoff.go:34 +0xca
  created by sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).Start in goroutine 103
  	/home/prow/go/src/kubernetes-sigs/kueue/pkg/scheduler/scheduler.go:148 +0x234
```

### PR DESCRIPTION
**Pull request by vladikkuzn**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Fixes flaky test

#### Which issue(s) this PR fixes:

Fixes #5898

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/workload/workload.go [hunk 1]
```diff
@@ -307,14 +307,18 @@ func (i *Info) CalcLocalQueueFSUsage(ctx context.Context, c client.Client, resWe
...
+	}
 	for resName, resVal := range lq.Status.FairSharing.AdmissionFairSharingStatus.ConsumedResources {
 		weight, found := resWeights[resName]
 		if !found {
 			weight = 1
 		}
 		usage += weight * resVal.AsApproximateFloat64()
 	}
-	if lq.Spec.FairSharing != nil && lq.Spec.FairSharing.Weight != nil {
+	if lq.Spec.FairSharing.Weight != nil {
```
Comment (mimowo) [inline pkg/workload/workload.go]: Is this related? If not then I would suggest to skip / separate PR potentially,.

Comment (mbobrovskyi) [reply pkg/workload/workload.go]: I think it's unnecessary to check for nil here since we’re already performing that check earlier:

https://github.com/kubernetes-sigs/kueue/blob/8cd51d42dee6ecee529d815efea170971529992a/pkg/workload/workload.go#L321

Comment (mimowo) [reply pkg/workload/workload.go]: let's put it in a separate PR, it is not related to the fix

File: pkg/workload/workload.go [hunk 2]
```diff
@@ -307,14 +307,18 @@ func (i *Info) CalcLocalQueueFSUsage(ctx context.Context, c client.Client, resWe
 		return 0, err
 	}
 	var usage float64
+	if lq.Status.FairSharing == nil || lq.Status.FairSharing.AdmissionFairSharingStatus == nil {
+		// If FairSharing is not enabled, return 0 usage.
```
Comment (mimowo) [inline pkg/workload/workload.go]: Does it really indicate it is not enabled? I think it may happen when the scheduling happens before the status is set / reconciled. 

Maybe it is better to say 'not enabled or initialized'

Comment (mimowo) [inline pkg/workload/workload.go]: This is an ok assumption for now, but may not be accurate when we introduce the entry penalty.

However, we can solve it later while working on the entry penalty. cc @mbobrovskyi

File: pkg/workload/workload.go (hunk 1 above)
Comment (mimowo) [reply pkg/workload/workload.go]: Above we are checking `lq.Status.FairSharing` and here we are checking `lq.Spec.FairSharin` (spec vs. status). It is not clear to my how checking status would prevent nil pointer in case spec is nil. Wouldn't the change cause Kueue crash if someone sets `lq.Spec.FairSharing` to nil (but had used FairSharing in the past, so lq.Status.FairSharing is not nil)? 

Causing Kueue crash by manipulating namespaced objects is not good.

In any case, let's discuss the change in a separate PR.
