### PR TITLE
[pods] Consider deleted pods without `spec.nodeName` inactive.

### LINKED ISSUE #2208: Deleted Pending Pods count as active in Pod Groups
**What happened**:

A Pending Pod (a Pod that doesn't have a scheduling gate, but it never got scheduled) is still considered as an "active" pod that cannot yet be replaced.

https://github.com/kubernetes-sigs/kueue/blob/eaa43d3f81050913826fa341b976e00b92832337/pkg/controller/jobs/pod/pod_controller.go#L731

**What you expected to happen**:

A replacement Pod for a Pod that never got scheduled should be allowed to run

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Pod, part of a pod group, with an unsatisfiable node-selector
2. Wait for the group to be admitted.
3. Delete the Pod manually
4. Create a replacement Pod (this Pod should not be deleted)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Consider deleted pods without `spec.nodeName` inactive and subject for pod replacement.

#### Which issue(s) this PR fixes:

Fixes #2208

#### Does this PR introduce a user-facing change?

```release-note
Consider deleted pods without `spec.nodeName` inactive and subject for pod replacement.
```

### CODE REVIEW

File: pkg/controller/jobs/pod/pod_controller.go [hunk 1]
```diff
@@ -736,10 +736,19 @@ func (p *Pod) notRunnableNorSucceededPods() []corev1.Pod {
 	return utilslices.Pick(p.list.Items, func(p *corev1.Pod) bool { return !isPodRunnableOrSucceeded(p) })
 }
 
+func isUnschedulable(p *corev1.Pod) bool {
+	for _, c := range p.Status.Conditions {
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go]: Generally the one problem I see with this is that we don't have any indication that an attempt to assign a node was made, however since someone or something has deleted the pod I think we can live with it.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 2]
```diff
@@ -1084,6 +1085,8 @@ func (p *Pod) FindMatchingWorkloads(ctx context.Context, c client.Client, r reco
 	activePods := p.runnableOrSucceededPods()
 	inactivePods := p.notRunnableNorSucceededPods()
 
+	log.Info("pods", "active", activePods, "inactive", inactivePods)
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_controller.go:1088]:
```suggestion
	log.V(5).Info("pods", "active", activePods, "inactive", inactivePods)
```
These are not just pod names, but entire pods (up to 1.5Mi each. potentially), so logging them unconditionally is excessive. 

Maybe we also wrap this with the level check for the logger.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 3]
```diff
@@ -739,7 +739,8 @@ func (p *Pod) notRunnableNorSucceededPods() []corev1.Pod {
 // isPodRunnableOrSucceeded returns whether the Pod can eventually run, is Running or Succeeded.
 // A Pod cannot run if it's gated and has a deletionTimestamp.
 func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
-	if p.DeletionTimestamp != nil && len(p.Spec.SchedulingGates) > 0 {
+	isPendingWithoutNode := p.Status.Phase == corev1.PodPending && p.Spec.NodeName == ""
+	if p.DeletionTimestamp != nil && (isPendingWithoutNode || len(p.Spec.SchedulingGates) > 0) {
```
Comment (mimowo) [inline pkg/controller/jobs/pod/pod_controller.go:743]: Why not just `if p.DeletionTimestamp != nil && p.Spec.NodeName == ""`? 

We know there are no `schedulingGates` if `p.Spec.NodeName != ""` because of this [check](https://github.com/kubernetes/kubernetes/blob/5ceb99dc6bae8a3013192439bdbee942d14de190/pkg/apis/core/validation/validation.go#L4987). Also, a pod with `p.Spec.NodeName == ""` is Pending (or Failed), so no need to check for Pending explicitly.

This would also match the logic in `gc_controller` [link](https://github.com/kubernetes/kubernetes/blob/5ceb99dc6bae8a3013192439bdbee942d14de190/pkg/controller/podgc/gc_controller.go#L303).

For the context, the users may want to implement the analogous logic in their controllers which create replacement pods, so that the replacement pods are safe (not handled as excess pods). So, the simpler the logic, the easier it would be for users to replicate.

**Comment by mimowo** [comment]
IIUC the check isn't so much about "unschedulable" pods, but about pods which can never succeed. An "uncheduled" pod (without the node), which is deleted, can never be successful, so we should keep the replacement pod. 

Maybe we should consider a rename `runnableOrSucceeded` -> `canEverSucceed` to better reflect the intention.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 2 above)
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go:1088]: I'll just remove it, It was just for debug.

**Comment by trasc** [comment]
> Maybe we should consider a rename `runnableOrSucceeded` -> `canEverSucceed` to better reflect the intention.

One can argue that the pod cannot succeed is it cannot run, additionally it very likely that  `runnableOrSucceeded`  was the result of a past debate, let's keep it as is.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 4]
```diff
@@ -737,9 +737,9 @@ func (p *Pod) notRunnableNorSucceededPods() []corev1.Pod {
 }
 
 // isPodRunnableOrSucceeded returns whether the Pod can eventually run, is Running or Succeeded.
-// A Pod cannot run if it's gated and has a deletionTimestamp.
+// A Pod cannot run if it's gated or has no node assignment while having a deletionTimestamp.
 func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
-	if p.DeletionTimestamp != nil && len(p.Spec.SchedulingGates) > 0 {
+	if p.DeletionTimestamp != nil && len(p.Spec.NodeName) == 0 {
```
Comment (mwielgus) [inline pkg/controller/jobs/pod/pod_controller.go:742]: Please rename the PR/commits to something more precise. The current title suggests that you will be marking all unschedulable pods (including these waiting for ClusterAutoscaler) as inactive, not only these that are already deleted and doesn't have a node name assigned.

File: test/e2e/singlecluster/pod_test.go [hunk 5]
```diff
@@ -254,6 +255,105 @@ var _ = ginkgo.Describe("Pod groups", func() {
 			util.ExpectWorkloadToFinish(ctx, k8sClient, client.ObjectKey{Namespace: ns.Name, Name: "group"})
 		})
 
+		ginkgo.It("Deleted Pending Unschedulable Pod can be replaced in group", func() {
```
Comment (mimowo) [inline test/e2e/singlecluster/pod_test.go:258]:
```suggestion
		ginkgo.It("Unscheduled Pod which is deleted can be replaced in group", func() {
```
Making the pod Unschedulable is just a way to make the test reliable. What matters is that the pod wasn't scheduled.

**Review by mimowo — COMMENTED** [review]
LGTM, just test-related comments

File: pkg/controller/jobs/pod/pod_controller.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobs/pod/pod_controller.go]: > Or even just the phase Pending.

I was thinking about it too, but this scenario is possible:
1. kubelet has already started the containers, and is about to transition `Pending` -> `Running`
2. The user deletes the pod so we have `deletionTimestamp != nil` and `Pending`
3. The patch by kubelet succeeds and the pod is `Running`
4. The containers complete successfully within graceful pod period  and kubelet transitions the pod to `Succeeded`

This is **super** unlikely, but possible. I'm ok either way, but maybe we stay on the safe side for now, just 
patching for the reported issue.

File: test/e2e/singlecluster/pod_test.go (hunk 5 above)
Comment (trasc) [reply test/e2e/singlecluster/pod_test.go]: done

File: test/e2e/singlecluster/pod_test.go [hunk 6]
```diff
@@ -254,6 +255,105 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					var p corev1.Pod
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(group[0]), &p)).To(gomega.Succeed())
+					g.Expect(p.DeletionTimestamp.IsZero()).NotTo(gomega.BeTrue())
+					g.Expect(p.Status.Phase).To(gomega.Equal(corev1.PodPending))
+					g.Expect(p.Spec.NodeName).To(gomega.BeEmpty())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Replacement pod starts, and the failed one is deleted", func() {
```
[the remark this answers is not in the document]
Comment (trasc) [reply test/e2e/singlecluster/pod_test.go]: The node selectors are part of the roleHash, a `group[1] ` copy cannot replace the `group[0] `

File: test/e2e/singlecluster/pod_test.go [hunk 7]
```diff
@@ -254,6 +255,105 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+				gomega.Expect(k8sClient.Create(ctx, rep)).To(gomega.Succeed())
+				gomega.Eventually(func(g gomega.Gomega) {
+					var p corev1.Pod
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(rep), &p)).To(gomega.Succeed())
+					g.Expect(p.Spec.SchedulingGates).To(gomega.BeEmpty())
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(group[0]), &p)).To(testing.BeNotFoundError())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Excess pod is deleted", func() {
```
[the remark this answers is not in the document]
Comment (trasc) [reply test/e2e/singlecluster/pod_test.go]: removed

File: pkg/controller/jobs/pod/pod_controller.go (hunk 4 above)
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go:742]: done

File: test/e2e/singlecluster/pod_test.go [hunk 8]
```diff
@@ -254,6 +255,86 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+					var p corev1.Pod
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(group[0]), &p)).To(gomega.Succeed())
+					g.Expect(p.DeletionTimestamp.IsZero()).NotTo(gomega.BeTrue())
+					g.Expect(p.Status.Phase).To(gomega.Equal(corev1.PodPending))
+					g.Expect(p.Spec.NodeName).To(gomega.BeEmpty())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("Replacement pod is un-gated, and the failed one is deleted", func() {
+				// Use a pod template that can succeed fast.
```
Comment (mimowo) [inline test/e2e/singlecluster/pod_test.go:325]: `group[0]` does not actually run, so the comment might be misleading

File: test/e2e/singlecluster/pod_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go]: I see, thanks for clarifying

File: test/e2e/singlecluster/pod_test.go (hunk 8 above)
Comment (trasc) [reply test/e2e/singlecluster/pod_test.go]: removed

File: test/e2e/singlecluster/pod_test.go [hunk 9]
```diff
@@ -254,6 +255,85 @@ var _ = ginkgo.Describe("Pod groups", func() {
...
+			group[0].Spec.NodeSelector = map[string]string{"missing-node-key": "missing-node-value"}
+
+			ginkgo.By("Group starts", func() {
+				for _, p := range group {
+					gomega.Expect(k8sClient.Create(ctx, p.DeepCopy())).To(gomega.Succeed())
+				}
+				gomega.Eventually(func(g gomega.Gomega) {
+					for _, origPod := range group {
+						var p corev1.Pod
+						gomega.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(origPod), &p)).To(gomega.Succeed())
```
Comment (tenzen-y) [inline test/e2e/singlecluster/pod_test.go:285]:
```suggestion
						g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(origPod), &p)).To(gomega.Succeed())
```

**Review by tenzen-y — COMMENTED** [review]
LGTM
just a nit

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Consider deleted pods without `spec.nodeName` inactive and subject for pod replacement.
```

File: test/e2e/singlecluster/pod_test.go (hunk 9 above)
Comment (trasc) [reply test/e2e/singlecluster/pod_test.go]: done

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
/release-note-edit

```release-note
Pod Integration: Consider deleted pods without `spec.nodeName` inactive and subject for pod replacement.
```
