### PR TITLE
[TAS] Do not reconcile on Nodes heartbeats

### LINKED ISSUE #8340: [TAS] TAS unnecessarily reacts on Nodes heartbeats
**What happened**:
`checkNodeSchedulingPropertiesChanged`  return `true` if the only difference is a resourceVersion.

As a result, `tas_resource_flavor_controller` regularly called `r.queues.QueueInadmissibleWorkloads(ctx, cqNames)` when it was not needed impacting BestEffortFIFO throughput

**What you expected to happen**:
Return `true` only on changes to fields that impact scheduling

**How to reproduce it (as minimally and precisely as possible)**:
Add UT to `pkg/controller/tas/resource_flavor_test.go`:

```
		"ResourceVersion changed": {
			oldNode:     baseNode.Clone().ResourceVersion("1").Obj(),
			newNode:     baseNode.Clone().ResourceVersion("2").Obj(),
			wantChanged: false,
		},
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #8340

#### Special notes for your reviewer:
Tested the changes manually on kind cluster:
Before the change on each heartbeat Kueue logged `Reconcile TAS Resource Flavor` (every 5 mins per node)
After the change there's no more reconciles

#### Does this PR introduce a user-facing change?

```release-note
TAS: fix a performance bug that continues reconciles of TAS ResourceFlavor (and related ClusterQueues) 
were triggered by updates to Nodes' heartbeat times.
```

### CODE REVIEW

**Comment by PBundyra** [comment]
cc @mimowo

File: pkg/controller/tas/resource_flavor.go [hunk 1]
```diff
@@ -236,7 +236,19 @@ func nodeBelongsToFlavor(node *corev1.Node, nodeLabels map[string]string, levels
...
+	node.ObjectMeta.ResourceVersion = ""
+
+	// ManagedFields often contain internal timestamps and high-churn metadata
+	node.ObjectMeta.ManagedFields = nil
+}
+
 // checkNodeSchedulingPropertiesChanged checks if the node update affects TAS scheduling.
 func checkNodeSchedulingPropertiesChanged(oldNode, newNode *corev1.Node) bool {
-	return !nodeSemantic.DeepEqual(oldNode, newNode)
+	o, n := oldNode.DeepCopy(), newNode.DeepCopy()
```
Comment (mimowo) [inline pkg/controller/tas/resource_flavor.go]: nit, this requires DeepCopying both versions of the node. I think it would be better and more consistent with the current code to just implement it inside `nodeSemantic`. We could have there nodeMetadataEqual, say:

```
func nodeMetadataEqual(a, b metav1.ObjectMeta) bool {
	aCopy, bCopy := a.DeepCopy(), b.DeepCopy()
    normalizeNodeMeta(aCopy)
    normalizeNodeMeta(bCopy)
	return equality.Semantic.DeepEqual(aCopy, bCopy)
}
```
or even better:
```
func nodeMetadataEqual(a, b metav1.ObjectMeta) bool {
	return equality.Semantic.DeepEqual(a.Labels, b.Labels)
}
```
but we can leave the second variant for follow up.

**Comment by mimowo** [comment]
/release-note-edit
```release-note
TAS: fix a performance bug that continues reconciles of TAS ResourceFlavor (and related ClusterQueues) 
were triggered by updates to Nodes' heartbeat times.
```

File: pkg/controller/tas/resource_flavor.go (hunk 1 above)
Comment (PBundyra) [reply pkg/controller/tas/resource_flavor.go]: Done

**Comment by mimowo** [comment]
Thank you 👍 
/lgtm
/approve
/cherrypick release-0.15
/cherrypick release-0.14

**Comment by PBundyra** [comment]
/hold
Let me verify the changes locally as well e2e

**Comment by PBundyra** [comment]
/hold cancel
Finished verifying locally and after refactor it works as well
