### PR TITLE
Fix flaky test#7809

### LINKED ISSUE #7809: Use ReserveQuotaAt/AdmittedAt instead of ReserveQuota/Admitted in unit tests.
/good-first-issue

**What would you like to be cleaned**:

We already had a lot of issues with like https://github.com/kubernetes-sigs/kueue/issues/7803. The problem is that many tests are still using the old ReserveQuota and Admitted wrappers instead of ReserveQuotaAt and AdmittedAt.

**Why is this needed**:

It helps eliminate flaky unit tests.

### PR DESCRIPTION
**Pull request by andrewseif**
#### What type of PR is this?
/kind cleanup
/kind flake

#### What this PR does / why we need it:
This PR affects all unit tests to make them call ReserveQuotaAt/AdmittedAt instead of ReserveQuota/Admitted, It helps eliminate flaky unit tests.

#### Which issue(s) this PR fixes:
Fixes #7809 

#### Does this PR introduce a user-facing change?
no

```release-note
NONE
```

### CODE REVIEW

**Review by mbobrovskyi — COMMENTED** [review]
Please remove `ReserveQuota()` and `Admitted()` from wrappers.

**Comment by mbobrovskyi** [comment]
Please add `Fixes` prefix before `#7809` in your PR description to automatically close an issue.

It should be like:

#### Which issue(s) this PR fixes:
Fixes #7809

**Comment by andrewseif** [comment]
> Please remove `ReserveQuota()` and `Admitted()` from wrappers.

Not sure what you mean by that? as in from comment or code? 👀

**Comment by mbobrovskyi** [comment]
> > Please remove `ReserveQuota()` and `Admitted()` from wrappers.
> 
> Not sure what you mean by that? as in from comment or code? 👀

You moved all ReserveQuota() to ReserveQuotaAt() and Admitted() to AdmittedAt(), so ReserveQuota() and Admitted() are no longer needed. We can remove [this](https://github.com/kubernetes-sigs/kueue/blob/0d7abafc7aace718e6fd14ac1c5f69babdcc6480/pkg/util/testing/v1beta2/wrappers.go#L167-L169) and [this](https://github.com/kubernetes-sigs/kueue/blob/0d7abafc7aace718e6fd14ac1c5f69babdcc6480/pkg/util/testing/v1beta2/wrappers.go#L191-L193), right?

**Comment by andrewseif** [comment]
> > > Please remove `ReserveQuota()` and `Admitted()` from wrappers.
> > 
> > 
> > Not sure what you mean by that? as in from comment or code? 👀
> 
> You moved all ReserveQuota() to ReserveQuotaAt() and Admitted() to AdmittedAt(), so ReserveQuota() and Admitted() are no longer needed. We can remove [this](https://github.com/kubernetes-sigs/kueue/blob/0d7abafc7aace718e6fd14ac1c5f69babdcc6480/pkg/util/testing/v1beta2/wrappers.go#L167-L169) and [this](https://github.com/kubernetes-sigs/kueue/blob/0d7abafc7aace718e6fd14ac1c5f69babdcc6480/pkg/util/testing/v1beta2/wrappers.go#L191-L193), right?

Correct, let me remove them and make sure they are not used anywhere else in the code, verify locally then push an update

File: pkg/scheduler/scheduler_tas_test.go [hunk 1]
```diff
@@ -53,6 +53,7 @@ import (
 )
 
 func TestScheduleForTAS(t *testing.T) {
+	now := time.Now().Truncate(time.Second)
```
Comment (mbobrovskyi) [inline pkg/scheduler/scheduler_tas_test.go:56]: It looks like we now have two variables, right? Can we use just one of them?

Another one in L2747 

```
				now := time.Now()
				fakeClock := testingclock.NewFakeClock(now)
```

File: pkg/controller/tas/node_failure_controller_test.go [hunk 2]
```diff
@@ -55,15 +55,15 @@ func TestNodeFailureReconciler(t *testing.T) {
...
+		ReserveQuotaAt(
 			utiltestingapi.MakeAdmission("cq").
 				PodSets(utiltestingapi.MakePodSetAssignment(kueue.DefaultPodSetName).
 					Assignment(corev1.ResourceCPU, "unit-test-flavor", "1").
 					TopologyAssignment(utiltestingapi.MakeTopologyAssignment([]string{corev1.LabelHostname}).
 						Domains(utiltestingapi.MakeTopologyDomainAssignment([]string{nodeName}, 1).Obj()).
 						Obj()).
 					Obj()).
-				Obj(),
+				Obj(), testStartTime,
```
Comment (mbobrovskyi) [inline pkg/controller/tas/node_failure_controller_test.go:66]: This is an interesting case. We create `testStartTime` variable (time.Now()), then create a fake clock and capture `now` variable from it. I think this can be optimized, but it’s probably better to address it in a follow-up to avoid mixing

File: pkg/controller/admissionchecks/provisioning/controller_test.go [hunk 3]
```diff
@@ -1676,13 +1676,14 @@ func TestReconcile(t *testing.T) {
 }
 
 func TestActiveOrLastPRForChecks(t *testing.T) {
+	now := time.Now().Truncate(time.Second)
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/provisioning/controller_test.go:1764]: I think we missed to add

```
controller.clock = testingclock.NewFakeClock(now)
```

File: pkg/controller/admissionchecks/provisioning/controller_test.go [hunk 4]
```diff
@@ -98,7 +98,7 @@ func requestWithCondition(r *autoscaling.ProvisioningRequest, conditionType stri
 }
 
 func TestReconcile(t *testing.T) {
-	now := time.Now()
+	now := time.Now().Truncate(time.Second)
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/provisioning/controller_test.go:102]: Also in this test.

```
controller.clock = fakeClock
```

File: pkg/scheduler/scheduler_tas_test.go (hunk 1 above)
Comment (andrewseif) [reply pkg/scheduler/scheduler_tas_test.go:56]: I thought these 2 variables are different, one creates a point in time and the other creates a mock clock that we can use to advance time in testing.

Comment (mbobrovskyi) [reply pkg/scheduler/scheduler_tas_test.go:56]: Nope. The idea is to use only one source of time – the same for conditions and the fake clock. That way, we’ll have a consistent time everywhere, which helps avoid flakiness.

File: pkg/controller/tas/node_failure_controller_test.go (hunk 2 above)
Comment (andrewseif) [reply pkg/controller/tas/node_failure_controller_test.go:66]: We can create a new Ticket after this one, to optimize the tests even more, if needed

File: pkg/controller/admissionchecks/provisioning/controller_test.go (hunk 3 above)
Comment (andrewseif) [reply pkg/controller/admissionchecks/provisioning/controller_test.go:1764]: what does the fakeClock do here? not sure why we need it.

**Comment by andrewseif** [comment]
this is an interesting [failure](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/8397/pull-kueue-verify-main/2004965533451030528): the error says "ReserveQuota undefined", but when I go to the error line its ResourceQuotaAt, and no ReserveQuota, is prow using a cache? 

this happened after I removed the wrapper methods, did I miss something?

**Comment by mbobrovskyi** [comment]
> this happened after I removed the wrapper methods, did I miss something?

I think you need rebase main branch.

File: cmd/kueuectl/app/clientgetter/client_getter.go
Comment (mbobrovskyi) [inline cmd/kueuectl/app/clientgetter/client_getter.go:1]: Why this changes?

Comment (mbobrovskyi) [reply cmd/kueuectl/app/clientgetter/client_getter.go:1]: Also other files.

Comment (mbobrovskyi) [reply cmd/kueuectl/app/clientgetter/client_getter.go:1]: Please keep only necessary changes.

Comment (andrewseif) [reply cmd/kueuectl/app/clientgetter/client_getter.go:1]: I think this happened from the rebase

Comment (andrewseif) [reply cmd/kueuectl/app/clientgetter/client_getter.go:1]: do you want me to remove this commit and try to rebase/merge again?

Comment (andrewseif) [reply cmd/kueuectl/app/clientgetter/client_getter.go:1]: I reverted and force pushed to fix the branch, now you should only see the tests, and not anything else 😄

File: pkg/controller/admissionchecks/provisioning/controller_test.go (hunk 4 above)
Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/provisioning/controller_test.go:102]: Please address this 🙏.

Comment (andrewseif) [reply pkg/controller/admissionchecks/provisioning/controller_test.go:102]: I left a comment on the above part asking for clarification, what should I do exactly? I don't get the controller.clock var, what is its use? don't  we already have a fakeClock?

Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/provisioning/controller_test.go:102]: Currently, we create the controller with `controller, err := NewController(...)` on L1689 using a real clock. In unit tests, we should replace it with a fake clock.

But I ok to fix it in follow-up.

File: cmd/importer/pod/import_test.go
Comment (mbobrovskyi) [inline cmd/importer/pod/import_test.go:1]: Same here. Inside `Import(...)`, we use a real clock. We should propagate the fake clock wherever it’s needed.
This can be addressed in a follow-up as well.

File: pkg/controller/admissionchecks/provisioning/controller_test.go (hunk 3 above)
Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/provisioning/controller_test.go:1764]: The same here. Let's fix this in follow-up.

**Review by mbobrovskyi — APPROVED** [review]
Awesome! Thank you so much!

/lgtm
/approve
