### PR TITLE
Fix scraper race condition on context cancellation

### LINKED ISSUE #9007: periodic-kueue-test-tas-scheduling-perf-release-0-15 is failing
**What happened**:

failing ci job periodic-kueue-test-tas-scheduling-perf-release-0-15

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-tas-scheduling-perf-release-0-15/2019382134803795968

**What you expected to happen**:

not failing

**How to reproduce it (as minimally and precisely as possible)**:

https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-tas-scheduling-perf-release-0-15

**Anything else we need to know?**:
```
2026-02-05T12:29:15.101336155Z	INFO	controller/controller.go:311	All workers finished	{"controller": "workload", "controllerGroup": "kueue.x-k8s.io", "controllerKind": "Workload"}
2026-02-05T12:29:15.101372706Z	INFO	manager/internal.go:559	Stopping and waiting for leader election runnables
2026-02-05T12:29:15.101397426Z	INFO	manager/internal.go:567	Stopping and waiting for caches
2026-02-05T12:29:15.101499577Z	INFO	manager/internal.go:571	Stopping and waiting for webhooks
2026-02-05T12:29:15.101539318Z	INFO	manager/internal.go:574	Stopping and waiting for HTTP servers
2026-02-05T12:29:15.101556808Z	INFO	manager/internal.go:578	Wait completed, proceeding to shutdown the manager
2026-02-05T12:29:15.101571818Z	INFO	Run manager	runner/main.go:435	End manager
2026-02-05T12:29:15.102777132Z	ERROR	Run metrics scraper	runner/main.go:451	Running the scraper	{"error": "Get \"http://localhost:41125/metrics\": context canceled"}
main.runScraper.func1
	/home/prow/go/src/kubernetes-sigs/kueue/test/performance/scheduler/runner/main.go:451
sync.(*WaitGroup).Go.func1
	/usr/local/go/src/sync/waitgroup.go:239
2026-02-05T12:29:15.131479731Z	INFO	Run command	runner/main.go:339	Cmd ended	{"stats": {"wallMs":600032,"userMs":10080,"sysMs":4854,"maxrss":121872}}
make[1]: *** [Makefile-test.mk:327: run-tas-performance-scheduler] Error 1
make[1]: Leaving directory '/home/prow/go/src/kubernetes-sigs/kueue'
make: *** [Makefile-test.mk:344: test-tas-performance-scheduler] Error 2
```

### PR DESCRIPTION
**Pull request by ikchifo**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Fixes a race condition in the performance test scraper that causes test failures.

When the context is canceled and the ticker fires simultaneously, Go's `select` may pick the ticker case. This causes `doScrape` to be called with an already-canceled context, resulting in a "context canceled" error that fails the test.

The fix checks if the context is canceled after a scrape error and treats it as a clean exit.

#### Which issue(s) this PR fixes:

Fixes #9007

#### Special notes for your reviewer:

The failing job logs show:
```
INFO  End manager
ERROR Running the scraper {"error": "Get \"http://localhost:41125/metrics\": context canceled"}
make: *** Error 1
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/performance/scheduler/runner/scraper/scraper.go [hunk 1]
```diff
@@ -117,6 +117,9 @@ func (s *Scraper) Run(ctx context.Context, output string) error {
 		case <-ticker.C:
 			err := s.doScrape(ctx, tw)
 			if err != nil {
+				if ctx.Err() != nil {
+					return nil
+				}
```
Comment (mimowo) [inline test/performance/scheduler/runner/scraper/scraper.go]: Thank you for the fix, this makes sense. Just a minor comment:

What about making the check more specific, like `errors.Is(ctx.Err(), context.Canceled)`

Comment (ikchifo) [reply test/performance/scheduler/runner/scraper/scraper.go]: Nice! Updated to make the check more specific.
