### PR TITLE
[TAS] Node failure controller should delete nodeToReplace annotation if a node recovers/reappears

### LINKED ISSUE #5571: [TAS] Node failure controller should delete nodeToReplace annotation if a node recovers/reappears
**What would you like to be added**:
Let's assume a Workload uses the whole capacity in a cluster. After node failure, a Workload gets annotated with nodeToReplace annotation. Let's say a node has then recovered and Workload can run as usual. After that Workload still have the annotation even if, there's no need to replace the node. It has a few consequences. First of all we waste scheduling cycle for a Workload that doesn't need the replacement. Secondly, if another node fails then the Workload will gets evicted while it shouldn't.

I'd like add a symmetric mechanism to current node failure controller, so it deletes the annotation if a node recovers/reappears.

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by pajakd**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Node failure controller removes the `NodeToReplace` annotation if the node recovers or reappears.

This is to handle the case where a node recovers (after the 30s `NodeFailureDelay` but before the 3m `RecoveryTimeout`). This is especially important if no replacement is possible for this node.

#### Which issue(s) this PR fixes:

Fixes #5571

#### Does this PR introduce a user-facing change?

```release-note
TAS: Fix a bug that the node failure controller tries to re-schedule Pods on the failure node even after the Node is recovered and reappears
```

### CODE REVIEW

File: pkg/controller/tas/node_failure_controller_test.go [hunk 1]
```diff
@@ -84,6 +84,12 @@ func TestNodeFailureReconciler(t *testing.T) {
 		Admitted(true).
 		Obj()
 
+	workloadWithAnnotation := baseWorkload.DeepCopy()
+	if workloadWithAnnotation.Annotations == nil {
+		workloadWithAnnotation.Annotations = make(map[string]string)
+	}
```
Comment (PBundyra) [inline pkg/controller/tas/node_failure_controller_test.go]:
```suggestion
		workloadWithAnnotation.Annotations = make(map[string]string)
```
Let's simplify since we know there are no annotations there

**Comment by PBundyra** [comment]
/lgtm
Thanks

File: pkg/controller/tas/node_failure_controller.go [hunk 2]
```diff
@@ -87,7 +87,12 @@ func (r *nodeFailureReconciler) Reconcile(ctx context.Context, req ctrl.Request)
 	}
 	readyCondition := utiltas.GetNodeCondition(&node, corev1.NodeReady)
 	if readyCondition.Status == corev1.ConditionTrue {
-		return ctrl.Result{}, nil
+		affectedWorkloads, err = r.getWorkloadsOnNode(ctx, req.Name)
+		if err != nil {
+			return ctrl.Result{}, err
+		}
+		patchErr := r.removeNodeToReplaceAnnotation(ctx, req.Name, affectedWorkloads)
+		return ctrl.Result{}, patchErr
```
Comment (tenzen-y) [inline pkg/controller/tas/node_failure_controller.go]:
```suggestion
		return ctrl.Result{}, r.removeNodeToReplaceAnnotation(ctx, req.Name, affectedWorkloads)
```

nit: we can directly return this error.

File: pkg/controller/tas/node_failure_controller_test.go [hunk 3]
```diff
@@ -84,6 +84,10 @@ func TestNodeFailureReconciler(t *testing.T) {
 		Admitted(true).
 		Obj()
 
+	workloadWithAnnotation := baseWorkload.DeepCopy()
+	workloadWithAnnotation.Annotations = make(map[string]string)
+	workloadWithAnnotation.Annotations[kueuealpha.NodeToReplaceAnnotation] = nodeName
```
Comment (tenzen-y) [inline pkg/controller/tas/node_failure_controller_test.go]:
```suggestion
	workloadWithAnnotation.Annotations := map[string]string{
		kueuealpha.NodeToReplaceAnnotation: nodeName,
	}
```

nit: I think we can directly initialize this map.

File: pkg/controller/tas/node_failure_controller.go [hunk 4]
```diff
@@ -323,3 +322,43 @@ func (r *nodeFailureReconciler) reconcileForReplaceNodeOnPodTermination(ctx cont
 		return ctrl.Result{}, patchErr
 	}
 }
+
+// removeNodeToReplaceAnnotation finds workloads with the specified node in the NodeToReplaceAnnotation
+// and removes the annotation
+func (r *nodeFailureReconciler) removeNodeToReplaceAnnotation(ctx context.Context, nodeName string, affectedWorkloads sets.Set[types.NamespacedName]) error {
+	var workloadProcessingErrors []error
+	for wlKey := range affectedWorkloads {
+		log := r.log.WithValues("workload", wlKey, "nodeName", nodeName)
```
Comment (tenzen-y) [inline pkg/controller/tas/node_failure_controller.go]:
```suggestion
	log := ctrl.LoggerFrom(ctx)
	for wlKey := range affectedWorkloads {
		log = log.WithValues("workload", wlKey)
```

We should use the propagated logger from reconciler since it has reconcile request objects.

File: pkg/controller/tas/node_failure_controller.go [hunk 5]
```diff
@@ -323,3 +322,43 @@ func (r *nodeFailureReconciler) reconcileForReplaceNodeOnPodTermination(ctx cont
...
+		// fetch workload.
+		var wl kueue.Workload
+		if err := r.client.Get(ctx, wlKey, &wl); err != nil {
+			if apierrors.IsNotFound(err) {
+				log.V(4).Info("Workload not found, skipping")
+			} else {
+				log.V(2).Error(err, "Failed to get workload")
```
Comment (tenzen-y) [inline pkg/controller/tas/node_failure_controller.go]:
```suggestion
				log.Error(err, "Failed to get workload")
```

Do we need this level even though this is an error message?

File: pkg/controller/tas/node_failure_controller.go [hunk 6]
```diff
@@ -323,3 +322,43 @@ func (r *nodeFailureReconciler) reconcileForReplaceNodeOnPodTermination(ctx cont
...
+				workloadProcessingErrors = append(workloadProcessingErrors, err)
+			}
+			continue
+		}
+
+		if wl.Annotations[kueuealpha.NodeToReplaceAnnotation] != nodeName {
```
Comment (tenzen-y) [inline pkg/controller/tas/node_failure_controller.go]:
```suggestion
		if wl.Annotations != nil &&  wl.Annotations[kueuealpha.NodeToReplaceAnnotation] != nodeName {
```

Isn't this potential null pointer?

File: pkg/controller/tas/node_failure_controller.go [hunk 7]
```diff
@@ -323,3 +322,43 @@ func (r *nodeFailureReconciler) reconcileForReplaceNodeOnPodTermination(ctx cont
...
+			continue
+		}
+
+		err := clientutil.Patch(ctx, r.client, &wl, true, func() (bool, error) {
+			log.V(4).Info(fmt.Sprintf("Removing node from %s annotation", kueuealpha.NodeToReplaceAnnotation), "failedNode", nodeName)
+			delete(wl.Annotations, kueuealpha.NodeToReplaceAnnotation)
+			return true, nil
+		})
+		if err != nil {
+			log.V(2).Error(err, "Failed to patch workload annotation")
```
Comment (tenzen-y) [inline pkg/controller/tas/node_failure_controller.go]:
```suggestion
			log.Error(err, "Failed to patch workload annotation")
```

Same question as the above error message.

**Review by tenzen-y — COMMENTED** [review]
Thank you

**Comment by tenzen-y** [comment]
/release-note-edit

```releease-note
TAS: Fix a bug that the node failure controller tries to re-schedule Pods on the failure node even after the Node is recovered and reappears
```

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
TAS: Fix a bug that the node failure controller tries to re-schedule Pods on the failure node even after the Node is recovered and reappears
```

**Comment by tenzen-y** [comment]
@pajakd @PBundyra Could you manually prepare the cherry-pick PR against release-0.12 branch?

**Comment by mimowo** [comment]
> @mimowo: https://github.com/kubernetes-sigs/kueue/pull/6325 failed to apply on top of branch "release-0.12":

@pajakd can you prepare the cherrypick?
