### PR TITLE
Fix preemption with TAS failure in the case of fulfilled pods count limit on Nodes

### LINKED ISSUE #4436: TAS with Preemption: Unexpected Pods count requests in findTopologyAssignment()
**What happened**:
In the `findTopologyAssignment()`, `requests` should have `{"pods": 1}` since requests is referenced to [`SinglePodRequests`](https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/cache/tas_flavor_snapshot.go#L322).

https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/cache/tas_flavor_snapshot.go#L317-L320

However, as I described in https://github.com/kubernetes-sigs/kueue/pull/4355#issuecomment-2685761682, when TAS with preemption, `SinglePodRequests` has `{"pods": 2}` in the following UT cases

- https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/scheduler/scheduler_test.go#L5187
- https://github.com/kubernetes-sigs/kueue/blob/cfed6f3fd7f0fa7394b5f3be79af8a8138a54650/pkg/scheduler/scheduler_test.go#L5248
- https://github.com/kubernetes-sigs/kueue/blob/cfed6f3fd7f0fa7394b5f3be79af8a8138a54650/pkg/scheduler/scheduler_test.go#L5334

**What you expected to happen**:
The `SinglePodRequests` has `{"pods": 1}` every time.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/4355/pull-kueue-test-unit-main/1894775753115963392

**Anything else we need to know?**:
The root cause is the unintended reuse of `tasPodSetRequests.SinglePodRequests` within a single schedulingCycle. We should use it as read-only objects. The reason why this happens only in the case of preemption is that `FindTopologyAssignmentsForWorkload()` is called twice only for the TAS with Preemption in the following:

- https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/scheduler/flavorassigner/flavorassigner.go#L407
- https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/scheduler/preemption/preemption.go#L586

Otherwise, `FindTopologyAssignmentsForWorkload()` is called only once within a single scheduling cycle.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #4439: TAS with Preemption: Failed to preempt workloads when the the sum of admitted and waiting pods count exceeds Node limit
**What happened**:
Preemptor with TAS failed to preempt candidates when sum of Pods count (admitted and head worklod pods) exceeds Node Pods count limit (`.status.allocatablePods["pods"]`).

The `FindTopologyAssitnmentForWorkload` with empty usage mode failed to find preemptees since the preemptor does not consider pod count (`"pods": X`) when it temporarily removes candidated workloads in the following:

**What you expected to happen**:
The preemptee is preempted by head higher priority workloads.

**How to reproduce it (as minimally and precisely as possible)**:
If we use the `.status.Allocatable["pods"]=1` in the following UT case, the test fails.
The test should succeed since the admitted workload, waiting workload, and node allocatable Pods have one pod.
The replacement from admitted and waiting workloads should happen since the node has enough pods allocatable count and waiting pod has higher priority than admitted one.

https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/scheduler/scheduler_test.go#L5187

**Anything else we need to know?**:
The root cause is `cq.removeUsage(wl.Usage())` does not consider the pods count (`{"pods": 1}`) since `wl.Usage()` takes TAS usage from `TASUsage()`. The only `TASFlavorCashe` knows completely TAS usage including pods count `{"pods": xx}`.

- https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/cache/snapshot.go#L44-L48
- https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/workload/workload.go#L243-L248
- https://github.com/kubernetes-sigs/kueue/blob/690e9762b796d28b057e31ec8298b09f9ede0e0d/pkg/workload/workload.go#L292-L297

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
I fixed two bugs as I described in #4436 and #4439.

The solution for #4436 is cloning the SinglePodRequests object to avoid write operation propagation.

The solution for #4439 is to count up and down the number of Pods in the `TASFlavorSnapshot.updateTASUsage`.
By this pods count, the preemptor can appropriately simulate if candidates preemptee allows higher workloads to make a room in the following:

https://github.com/kubernetes-sigs/kueue/blob/6e25ebfcf2491236e385f644e4f7280c3d315ead/pkg/scheduler/preemption/preemption.go#L289-L297

#### Which issue(s) this PR fixes:

Fixes #4436
Fixes #4439

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/cache/tas_flavor_snapshot.go [hunk 1]
```diff
@@ -321,7 +323,7 @@ func (s *TASFlavorSnapshot) findTopologyAssignment(
 	assumedUsage map[utiltas.TopologyDomainID]resources.Requests,
 	simulateEmpty bool) (*kueue.TopologyAssignment, string) {
 	topologyRequest := tasPodSetRequests.PodSet.TopologyRequest
-	requests := tasPodSetRequests.SinglePodRequests
+	requests := tasPodSetRequests.SinglePodRequests.Clone()
```
Comment (mimowo) [inline pkg/cache/tas_flavor_snapshot.go:326]: Would the new test fail without this change? 

If it continues to pass, then I would suggest to either: (1) add one more test case for this change, or (2) revert it and fix in a separate PR

**Review by mimowo — COMMENTED** [review]
LGTM one question about potentially one more test case

File: pkg/cache/tas_flavor_snapshot.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/cache/tas_flavor_snapshot.go:326]: > Would the new test fail without this change?

yes. because commit without this change unexpected pods count up as I described in https://github.com/kubernetes-sigs/kueue/issues/4436

Comment (tenzen-y) [reply pkg/cache/tas_flavor_snapshot.go:326]: We need to fix the order #4439 -> #4436 as I described in #4439.
Reversed order (#4436 -> #4439) does not work well.

Comment (mimowo) [reply pkg/cache/tas_flavor_snapshot.go:326]: sgtm

**Comment by tenzen-y** [comment]
/hold 
I observed another failure test cases...

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Awesome to see TAS preemptions being debugged and fixed as we go.

**Comment by mimowo** [comment]
/hold 
For the test failure

**Comment by tenzen-y** [comment]
> /hold I observed another failure test cases...

I am currently debugging

**Comment by tenzen-y** [comment]
Other 2 test cases failed

File: pkg/scheduler/scheduler_test.go [hunk 2]
```diff
@@ -5245,6 +5245,71 @@ func TestScheduleForTASPreemption(t *testing.T) {
 				},
 			},
 		},
+		"With pods count usage pressure on nodes: only low priority workload is preempted": {
+			// This test case demonstrates the baseline scenario where there
+			// is only one low-priority workload and it gets preempted even if node has pods count usage pressure.
+			nodes: []corev1.Node{
+				*singleNode.Clone().
```
Comment (mimowo) [inline pkg/scheduler/scheduler_test.go:5252]: I checked locally and it seems this to be the root cause for the failures of other tests, probably the Clone does not work as expected, maybe revert the wrappers changes and just create the locally for this test

Comment (tenzen-y) [reply pkg/scheduler/scheduler_test.go:5252]: Thank you for checking that. I found my poor mistake in another place :)

File: pkg/util/testingjobs/node/wrappers.go [hunk 3]
```diff
@@ -41,6 +41,11 @@ func (n *NodeWrapper) Obj() *corev1.Node {
 	return &n.Node
 }
 
+// Clone returns a deep copy of the NodeWrapper.
+func (n *NodeWrapper) Clone() *NodeWrapper {
+	return &NodeWrapper{Node: *n.Obj().DeepCopy()}
```
Comment (tenzen-y) [inline pkg/util/testingjobs/node/wrappers.go:46]: FYI: @mimowo I was forgotton to call `DeepCopy()` here 🙃

**Comment by mimowo** [comment]
/lgtm
/hold cancel
Thanks!

**Comment by tenzen-y** [comment]
TAS with Preemption has not been released yet. So. I do not add any release notes.
But it would be better to cherry-pick this since, technically, this is a potential bug in released branches.
@mimowo Any objections?

**Comment by mimowo** [comment]
I'm ok  to cherry pick as cleanup without release note
