### PR TITLE
Fix fair sharing flake due to data race after calling AsFloat64Slow

### LINKED ISSUE #6960: [integration tests flake]  fairsharing ./test/integration/singlecluster/scheduler/fairsharing
/kind flake

**What happened**:
failures on unreleated branches: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6944/pull-kueue-test-integration-baseline-main/1970474873939562496

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6942/pull-kueue-test-integration-baseline-main/1970475502288244736

**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:

```

There were failures detected in the following suites:
  fairsharing ./test/integration/singlecluster/scheduler/fairsharing
Test Suite Failed
make: *** [Makefile-test.mk:72: test-integration] Error 1
```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind flake

#### Which issue(s) this PR fixes:

Fixes #6960

#### Special notes for your reviewer:

It seems like regeression after https://github.com/kubernetes-sigs/kueue/pull/6925/files#diff-94a0ecf880b4ffc718449fd8ae642ff0c5bed4136b5458ac33e95c307d76b43bR71 because quantity.AsDec is stateful mutation: https://github.com/kubernetes/apimachinery/blob/da5b06e2fb6698d6db8866899150ec2c1b4518d9/pkg/api/resource/quantity.go#L538

No release note because the previous PR introducing the issue wasn't released yet.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
Data race detected after commit https://github.com/kubernetes-sigs/kueue/pull/6963/commits/27571b476a6bc3ec239e91c80495aa693cbc8e0c : https://github.com/kubernetes-sigs/kueue/issues/6960#issuecomment-3324295814

**Comment by mimowo** [comment]
passed after the change: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6963/pull-kueue-test-integration-baseline-main/1970501100524015616

**Comment by mimowo** [comment]
cc @gabesaba

**Comment by PBundyra** [comment]
/hold
for @gabesaba to take a look
/lgtm

File: pkg/cache/scheduler/fair_sharing.go [hunk 1]
```diff
@@ -68,7 +68,8 @@ func (d DRS) PreciseWeightedShare() float64 {
 		// branches never reach here.
 		return math.Inf(1)
 	}
-	return d.unweightedRatio / d.fairWeight.AsFloat64Slow()
+	frWeightCopy := d.fairWeight.DeepCopy()
```
Comment (mbobrovskyi) [inline pkg/cache/scheduler/fair_sharing.go:75]:
```suggestion
	// We make a copy to ensure the fairWeight object doesn’t change after calling AsFloat64Slow().
	// This can happen because quantity.AsDec performs a stateful mutation 
	// (see https://github.com/kubernetes/apimachinery/blob/da5b06e2fb6698d6db8866899150ec2c1b4518d9/pkg/api/resource/quantity.go#L538).
	frWeightCopy := d.fairWeight.DeepCopy()
```

Comment (mimowo) [reply pkg/cache/scheduler/fair_sharing.go:75]: Thanks, merging

Comment (mimowo) [reply pkg/cache/scheduler/fair_sharing.go:75]: Pushed updated version with the comment, slightly rephrased and added a note about the data race too.

**Comment by mbobrovskyi** [comment]
/lgtm
Thank you!

**Comment by mimowo** [comment]
> /hold
> for @gabesaba to take a look

/unhold
@gabesaba  already expressed his support for the idea under https://github.com/kubernetes-sigs/kueue/pull/6967#discussion_r2372650211

If Gabe has additional comments we can follow up, but I want to merge ASAP because now many branches are failing due to this issue.
