### PR TITLE
[kueue] Check certificates readiness before the webhook server.

### LINKED ISSUE #1700: MultiKueue e2e test flaky on startup
**What happened**:

e2e test failed on docs PR.

**What you expected to happen**:

No failure

**How to reproduce it (as minimally and precisely as possible)**:

 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1684/pull-kueue-test-e2e-main-1-29/1755244756142657536

**Anything else we need to know?**:

This is the message:
```
> Enter [BeforeEach] MultiKueue - /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:69 @ 02/07/24 15:11:34.098
[FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc0001406e0>: 
    Internal error occurred: failed calling webhook "vadmissioncheck.kb.io": failed to call webhook: the server could not find the requested resource
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Internal error occurred: failed calling webhook \"vadmissioncheck.kb.io\": failed to call webhook: the server could not find the requested resource",
            Reason: "InternalError",
            Details: {
                Name: "",
                Group: "",
                Kind: "",
                UID: "",
                Causes: [
                    {
                        Type: "",
                        Message: "failed calling webhook \"vadmissioncheck.kb.io\": failed to call webhook: the server could not find the requested resource",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 500,
        },
    }
```
The fix to startup Kueue was recently done: https://github.com/kubernetes-sigs/kueue/pull/1676
This seems similar, but slightly different, because this time the kueue logs show one of the managers was killed `kueue-controller-manager-57858fc6bb-xvbgg` and restarted after 1min, probably hitting some timeout (https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1684/pull-kueue-test-e2e-main-1-29/1755244756142657536/artifacts/run-test-multikueue-e2e-1.29.0/kind-manager-kueue-system-pods.log):

```
Name:             kueue-controller-manager-57858fc6bb-xvbgg
Namespace:        kueue-system
Priority:         0
Service Account:  kueue-controller-manager
Node:             kind-manager-control-plane/172.18.0.2
Start Time:       Wed, 07 Feb 2024 15:08:35 +0000
Labels:           control-plane=controller-manager
                  pod-template-hash=57858fc6bb
Annotations:      kubectl.kubernetes.io/default-container: manager
Status:           Running
IP:               10.244.0.6
IPs:
  IP:           10.244.0.6
Controlled By:  ReplicaSet/kueue-controller-manager-57858fc6bb
Containers:
  manager:
    Container ID:  containerd://7faccc1023e13b4e48ad495114e48c739b7cd1a23750426a24070e535c9bf7a9
    Image:         gcr.io/k8s-staging-kueue/kueue:v0.6.0-rc.1-37-gdba0454
    Image ID:      docker.io/library/import-2024-02-07@sha256:17e63be0a74e8ee4f7ba279e23f7a46945f4aab52f628c89f1de3aa3b2d0d574
    Ports:         8082/TCP, 9443/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /manager
    Args:
      --config=/controller_manager_config.yaml
      --zap-devel
      --zap-log-level=3
      --feature-gates=VisibilityOnDemand=true,MultiKueue=true
    State:          Running
      Started:      Wed, 07 Feb 2024 15:10:37 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 07 Feb 2024 15:08:36 +0000
      Finished:     Wed, 07 Feb 2024 15:10:36 +0000
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:
Check certificates readiness before checking if the webhook server is ready.
#### Which issue(s) this PR fixes:

Fixes #1700

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: cmd/kueue/main.go [hunk 1]
```diff
@@ -292,7 +293,12 @@ func setupProbeEndpoints(mgr ctrl.Manager) {
 	// the function, otherwise a not fully-initialized webhook server (without
 	// ready certs) fails the start of the manager.
 	if err := mgr.AddReadyzCheck("readyz", func(req *http.Request) error {
-		return mgr.GetWebhookServer().StartedChecker()(req)
+		select {
+		case <-certsReady:
```
Comment (mimowo) [inline cmd/kueue/main.go:297]: When we discussed this originally I wasn't sure if this is needed https://github.com/kubernetes-sigs/kueue/pull/1676#discussion_r1474188770. And I'm still not 100% sure, but the change reflects the intention, and it should be harmless. Also, the analogous change is done in another project: https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/d367fc08a261135b63d22aeb01c688317d9b7e02/cmd/manager/main.go#L296-L307, so I'm happy to try this fix.

File: cmd/kueue/main.go [hunk 2]
```diff
@@ -292,7 +293,12 @@ func setupProbeEndpoints(mgr ctrl.Manager) {
...
+			return mgr.GetWebhookServer().StartedChecker()(req)
+		case <-req.Context().Done():
```
Comment (mimowo) [inline cmd/kueue/main.go:299]: Maybe use `default` for certs not ready as in the other project:  https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/d367fc08a261135b63d22aeb01c688317d9b7e02/cmd/manager/main.go#L296-L307. For context done we probably can have another dedicated message to distinguish like closing the readiness probe ad the context is closed?

Comment (trasc) [reply cmd/kueue/main.go:299]: It depends if we want to keep the caller busy or not. 

/cc @alculquicondor

Comment (mimowo) [reply cmd/kueue/main.go:299]: I think it does not matter because at this point the only caller should be the kubelet readiness check probably, so I would prefer simplicity.

Comment (trasc) [reply cmd/kueue/main.go:299]: I there a spec on if we should block or not?

Comment (mimowo) [reply cmd/kueue/main.go:299]: From https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
```
Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.
```
So IIUC we are ok to close as long saying "not ok"

Comment (alculquicondor) [reply cmd/kueue/main.go:299]: we should close the connection ASAP, so let's use default.

Comment (trasc) [reply cmd/kueue/main.go]: done

File: cmd/kueue/main.go (hunk 1 above)
Comment (alculquicondor) [reply cmd/kueue/main.go:297]: @trasc can you give a rationale on why you think this fixes the issue?

From the logs, it does look like there is some condition between setting the certs and starting the manager, so I can see the relationship. But the specific set of events are unclear to me.

Comment (mimowo) [reply cmd/kueue/main.go:297]: From the old thread: https://github.com/kubernetes-sigs/kueue/pull/1676#discussion_r1473991998:
```
What I verified experimentally is that if I just call GetWebhookServer before WaitForCertsReady then the webhook is not initialized, and it stays that way.
```
I did this experiments just by modifying the code and calling GetWebhookServer before or after https://github.com/kubernetes-sigs/kueue/blob/c4a2255831a9284a0e6cc213d5938556ea209f49/cmd/kueue/main.go#L226. 

I think what might be now happening when the readiness probe is called between the readiness server is listening (probably does not require certs) and the certs are initialized.

**Comment by trasc** [comment]
> ups, looks like there is still an issue: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1707/pull-kueue-test-e2e-main-1-27/1755619946483683328: `error: timed out waiting for the condition on deployments/kueue-controller-manager`

yes , one of the managers did not get the certificates....  https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1707/pull-kueue-test-e2e-main-1-27/1755619946483683328/artifacts/run-test-multikueue-e2e-1.27.3/kind-worker2-control-plane/pods/kueue-system_kueue-controller-manager-77656c747d-bmrfm_e1741fd8-969b-4768-966c-f7f6b4708a76/manager/0.log, 

We could give up if the certificates are not ready in Xmin, the pod will be replaced and maybe we have better luck next time :)

Or extend that wait timeout.

**Comment by mimowo** [comment]
Maybe let's see if longer timeout helps, though it might be hard to confirm with certainty

File: cmd/kueue/main.go (hunk 1 above)
Comment (trasc) [reply cmd/kueue/main.go:297]: > @trasc can you give a rationale on why you think this fixes the issue?
> 
> From the logs, it does look like there is some race condition between setting the certs and starting the manager, so I can see the relationship. But the specific set of events are unclear to me.

Unfortunately I don't have anything concert, I suspect that it the original case, the Start hit in the middle of a rotation. But it's just a suspicion.

**Comment by trasc** [comment]
> Maybe let's see if longer timeout helps, though it might be hard to confirm with certainty
> 
> EDiT this way we will know if the issue repeats with timeout say 6m that is it pretty much non recoverable. Restarting the pod may cover a wide range of issues

I'll try it tomorrow.

**Comment by alculquicondor** [comment]
Did you mean timeout in the bash script?

**Comment by mimowo** [comment]
> Did you mean timeout in the bash script?

Yes

**Comment by mimowo** [comment]
What makes me yet curious is how the condition in the bash script was met in the first failure we saw. It must mean the server responded ok at least once, and must have been terminated later.

**Comment by alculquicondor** [comment]
/lgtm
/approve

Let's leave the timeout for another PR
