### PR TITLE
Fix e2e helper waiting for NodeReady after disruption

### LINKED ISSUE #10420: flaky test:  Failure Recovery Policy when the kubelet on a node goes down should unblock the stuck pod's parents that are being deleted with foreground propagation
**Which test is flaking?**:
 Failure Recovery Policy when the kubelet on a node goes down should unblock the stuck pod's parents that are being deleted with foreground propagation
**Link to failed CI job or steps to reproduce locally**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-customconfigs-release-0-17/2042973271896363008
**Failure message or logs**:
```
End To End Custom Configs handling Suite: kindest/node:v1.35.0: [It] Failure Recovery Policy when the kubelet on a node goes down should unblock the stuck pod's parents that are being deleted with foreground propagation [feature:failurerecoverypolicy] expand_less	2m49s
{ failed [FAILED] Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:1489 with:
Expected
    <[]v1.JobCondition | len:1, cap:1>: [
        {
            Type: "Suspended",
            Status: "False",
            LastProbeTime: {
                Time: 2026-04-11T14:48:50Z,
            },
            LastTransitionTime: {
                Time: 2026-04-11T14:48:50Z,
            },
            Reason: "JobResumed",
            Message: "Job resumed",
        },
    ]
to contain element matching
    <*matchers.BeComparableToMatcher | 0x31a027d91470>: {
        Expected: <v1.JobCondition>{
            Type: "Complete",
            Status: "True",
            LastProbeTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            Reason: "",
            Message: "",
        },
        Options: [
            <*cmp.pathFilter | 0x31a027e1be48>{
                core: {},
                fnc: 0x18182a0,
                opt: <cmp.ignore>{core: {}},
            },
        ],
    }
In [JustAfterEach] at: /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:1493 @ 04/11/26 14:49:35.18
}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind flake
/kind bug

#### Which issue(s) this PR fixes:

Fixes #10420

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @kshalot

**Review by mbobrovskyi — COMMENTED** [review]
Thank you!

/lgtm

File: test/util/util.go [hunk 1]
```diff
@@ -1504,6 +1504,7 @@ func waitForDummyWorkloadToRunOnNode(ctx context.Context, c client.Client, node
 			Queue(kueue.LocalQueueName(lq.Name)).
 			NodeSelector(corev1.LabelHostname, node.Name).
 			Image(GetAgnHostImage(), BehaviorExitFast).
+			RequestAndLimit(corev1.ResourceCPU, "200m").
```
Comment (kshalot) [inline test/util/util.go:1507]: QQ: Was this causing issues by not being set?

Comment (mimowo) [reply test/util/util.go:1507]: I don't think so, I just saw the Pod was running very long even though it is ExitFast, so I thought it might have been constrained on CPU very much https://github.com/kubernetes-sigs/kueue/issues/10420#issuecomment-4268724380

However, it is really hard to confirm what was the CPU usage at that time coming from other Pods to reject / confirm the hypothesis. 

So, giving the Pod some basic "guaranteed" 200m seems to make sense, to ensure it has some bare minimum to run.

Comment (mimowo) [reply test/util/util.go:1507]: So rather than showing: "it caused issues not being set" I'm saying:
1. without some guaranteed space we will never know
2. for consistency - all other Pods are given some bare minimum of 200m, so applying least surprise principle (LSP)

**Comment by mimowo** [comment]
Oh I see this needs to be CPed to 0.16 on top of https://github.com/kubernetes-sigs/kueue/pull/10120, let me try that one first, then mine

**Comment by mimowo** [comment]
Opened: https://github.com/kubernetes-sigs/kueue/pull/10582
