### PR TITLE
Increase workload finish timeout to tolerate slow kubelet phase trans…

### LINKED ISSUE #10306: [flaky test] JAX integration when JAX created should admit group with leader only
**Which test is flaking?**:

JAX integration when JAX created should admit group with leader only

**Link to failed CI job or steps to reproduce locally**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-release-0-16-1-33/2041394602723774464

**Failure message or logs**:
```
End To End Suite: kindest/node:v1.33.7: [It] JAX integration when JAX created should admit group with leader only [area:singlecluster, feature:jaxjob] expand_less	1m36s
{ failed [FAILED] Timed out after 45.001s.
Workload did not finish
    <*v1beta2.Workload | 0x1930d738008>: metadata:
          creationTimestamp: "2026-04-07T06:15:53Z"
          finalizers:
          - kueue.x-k8s.io/resource-in-use
          generation: 1
          labels:
            kueue.x-k8s.io/job-uid: 230c39a8-c968-47e1-b7d5-a0e43c37b83c
          managedFields:
          - apiVersion: kueue.x-k8s.io/v1beta2
            fieldsType: FieldsV1
            fieldsV1:
              f:metadata:
                f:labels:
                  f:kueue.x-k8s.io/job-uid: {}
              f:status:
                f:admission:
                  f:clusterQueue: {}
                  f:podSetAssignments:
                    k:{"name":"worker"}:
                      .: {}
                      f:count: {}
                      f:flavors:
                        f:cpu: {}
                        f:memory: {}
                      f:name: {}
                      f:resourceUsage:
                        f:cpu: {}
                        f:memory: {}
                f:conditions:
                  k:{"type":"Admitted"}:
                    .: {}
                    f:lastTransitionTime: {}
                    f:message: {}
                    f:observedGeneration: {}
                    f:reason: {}
                    f:status: {}
                    f:type: {}
                  k:{"type":"QuotaReserved"}:
                    .: {}
                    f:lastTransitionTime: {}
                    f:message: {}
                    f:observedGeneration: {}
                    f:reason: {}
                    f:status: {}
                    f:type: {}
            manager: kueue-admission
            operation: Apply
            subresource: status
            time: "2026-04-07T06:15:53Z"
          - apiVersion: kueue.x-k8s.io/v1beta2
            fieldsType: FieldsV1
            fieldsV1:
              f:metadata:
                f:finalizers:
                  .: {}
                  v:"kueue.x-k8s.io/resource-in-use": {}
                f:labels:
                  .: {}
                  f:kueue.x-k8s.io/job-uid: {}
                f:ownerReferences:
                  .: {}
                  k:{"uid":"230c39a8-c968-47e1-b7d5-a0e43c37b83c"}: {}
              f:spec:
                .: {}
                f:active: {}
                f:podSets:
                  .: {}
                  k:{"name":"worker"}:
                    .: {}
                    f:count: {}
                    f:name: {}
                    f:template:
                      .: {}
                      f:metadata: {}
                      f:spec:
                        .: {}
                        f:containers:
                          .: {}
                          k:{"name":"jax"}:
                            .: {}
                            f:args: {}
                            f:image: {}
                            f:name: {}
                            f:resources:
                              .: {}
                              f:requests:
                                .: {}
                                f:cpu: {}
                                f:memory: {}
                        f:restartPolicy: {}
                    f:topologyRequest:
                      .: {}
                      f:podIndexLabel: {}
                f:priority: {}
                f:queueName: {}
            manager: kueue
            operation: Update
            time: "2026-04-07T06:15:53Z"
          name: jaxjob-jax-simple-ed526
          namespace: jax-e2e-wnm7m
          ownerReferences:
          - apiVersion: kubeflow.org/v1
            blockOwnerDeletion: true
            controller: true
            kind: JAXJob
            name: jax-simple
            uid: 230c39a8-c968-47e1-b7d5-a0e43c37b83c
          resourceVersion: "2665"
          uid: 8223f2a2-27bd-482f-b97c-e4b8adc747ca
        spec:
          active: true
          podSets:
          - count: 2
            name: worker
            template:
              metadata: {}
              spec:
                containers:
                - args:
                  - netexec
                  image: registry.k8s.io/e2e-test-images/agnhost:2.62.0
                  name: jax
                  resources:
                    requests:
                      cpu: "1"
                      memory: 200Mi
                restartPolicy: Never
            topologyRequest:
              podIndexLabel: training.kubeflow.org/replica-index
          priority: 0
          queueName: jax-lq-jax-e2e-wnm7m
        status:
          admission:
            clusterQueue: jax-cq-jax-e2e-wnm7m
            podSetAssignments:
            - count: 2
              flavors:
                cpu: jax-rf-jax-e2e-wnm7m
                memory: jax-rf-jax-e2e-wnm7m
              name: worker
              resourceUsage:
                cpu: "2"
                memory: 400Mi
          conditions:
          - lastTransitionTime: "2026-04-07T06:15:53Z"
            message: Quota reserved in ClusterQueue jax-cq-jax-e2e-wnm7m
            observedGeneration: 1
            reason: QuotaReserved
            status: "True"
            type: QuotaReserved
          - lastTransitionTime: "2026-04-07T06:15:53Z"
            message: The workload is admitted
            observedGeneration: 1
            reason: Admitted
            status: "True"
            type: Admitted
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by reruno**
…itions

#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:
Increase workload finish timeout to tolerate slow kubelet phase transitions
#### Which issue(s) this PR fixes:

Fixes #10306 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/util/util.go [hunk 1]
```diff
@@ -541,7 +541,7 @@ func ExpectWorkloadToFinish(ctx context.Context, k8sClient client.Client, wlKey
 	gomega.EventuallyWithOffset(1, func(g gomega.Gomega) {
 		g.Expect(k8sClient.Get(ctx, wlKey, &wl)).To(gomega.Succeed())
 		g.Expect(wl.Status.Conditions).To(utiltesting.HaveConditionStatusTrue(kueue.WorkloadFinished), "it's finished")
-	}, MediumTimeout, Interval).Should(gomega.Succeed(), assertMsg("Workload did not finish", &wl))
+	}, LongTimeout, Interval).Should(gomega.Succeed(), assertMsg("Workload did not finish", &wl))
```
Comment (mimowo) [inline test/util/util.go:544]: Actually, I see this function is also used in integration tests where using 90s does not make sense, because they don't depend on the pod lifecycle. 

Could you instead introduce `ExpectWorkloadToFinishWithTimeout`, and use MediumTimeout for integration tests + e2e where the operation is not depending directly on Pod lifecycle, but at least for integration tests.

Comment (mimowo) [reply test/util/util.go:544]: cc @mbobrovskyi
