### PR TITLE
fix: retry kind cluster deletion to work around Docker race condition

### LINKED ISSUE #8908: [Flaky] failed to delete cluster "kind"
/kind flake

**What happened**:

```
Switched to context "kind-kind".
Deleting cluster "kind" ...

ERROR: failed to delete cluster "kind": failed to delete nodes: command "docker rm -f -v kind-worker kind-control-plane kind-worker2" failed with error: exit status 1

Command Output: kind-control-plane
Error response from daemon: cannot remove container "kind-worker": could not kill container: tried to kill container, but did not receive an exit event
Error response from daemon: cannot remove container "kind-worker2": could not kill container: tried to kill container, but did not receive an exit event
make: *** [Makefile-test.mk:176: run-test-e2e-singlecluster-1.32.11] Error 1
```

**What you expected to happen**:

No errors

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/8893/pull-kueue-test-e2e-main-1-32/2017169874874273792

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by nerdeveloper**
## Summary

Fixes #8908.

Adds retry logic with exponential backoff to `cluster_cleanup` in `hack/testing/e2e-common.sh` to work around a Docker daemon race condition that causes `kind delete cluster` to fail intermittently in CI.

## Root Cause

The Prow e2e jobs run Docker-in-Docker (Docker CE 28.x) inside privileged pods on Linux with significant IO contention. Under these conditions, Docker's internal container kill path hits a **hardcoded 2-second timeout** (`daemon/kill.go:200-202`) waiting for the container to acknowledge a SIGKILL. When the container process is in uninterruptible IO sleep (D-state), this timeout expires before the exit event propagates through containerd, and Docker returns:

`could not kill container: tried to kill container, but did not receive an exit event`

This is a confirmed, unfixed upstream Docker bug:
- [moby/moby#51028](https://github.com/moby/moby/issues/51028) — Root cause analysis (Docker 28.4.0, status: Parked)
- [moby/moby#51845](https://github.com/moby/moby/issues/51845) — Same bug with kind clusters specifically (Docker 29.1.4, status: Triage)

Both upstream reports confirm that **containers do exit, just 3-5 seconds late**. Docker then ignores the late exit event because the delete operation already failed. This means a retry after a short delay succeeds reliably.

## Testing

- Created and deleted a kind cluster through the modified `cluster_cleanup` — happy path returns immediately on first success

```release-note
NONE
```

### CODE REVIEW

File: hack/testing/e2e-common.sh [hunk 1]
```diff
@@ -159,7 +159,40 @@ export E2E_TEST_AGNHOST_IMAGE=${E2E_TEST_AGNHOST_IMAGE_WITH_SHA%%@*}
 
 # $1 cluster name
 function cluster_cleanup {
-    $KIND delete cluster --name "$1"
+    local cluster_name="$1"
+    local max_retries=3
+    local retry_delay=10
```
Comment (mbobrovskyi) [inline hack/testing/e2e-common.sh]: From the PR description, I see that we need to wait 3-5 seconds, right? Could we reduce this delay to, for example, 1 second and add exponential backoff? I think it’s better to increase retries rather than wait longer.

File: hack/testing/e2e-common.sh [hunk 2]
```diff
@@ -159,7 +159,40 @@ export E2E_TEST_AGNHOST_IMAGE=${E2E_TEST_AGNHOST_IMAGE_WITH_SHA%%@*}
...
+        containers=$(docker ps -aq --filter "label=io.x-k8s.kind.cluster=${cluster_name}" 2>/dev/null || true)
+        for cid in $containers; do
+            docker kill "$cid" 2>/dev/null || true
+            docker rm -f -v "$cid" 2>/dev/null || true
+        done
+
+        echo "Retrying in ${retry_delay}s..."
+        sleep "$retry_delay"
+        retry_delay=$((retry_delay * 2))
+    done
```
Comment (mbobrovskyi) [inline hack/testing/e2e-common.sh]: Do we need this? Does kind handle this the same way?

File: hack/testing/e2e-common.sh [hunk 3]
```diff
@@ -159,7 +159,40 @@ export E2E_TEST_AGNHOST_IMAGE=${E2E_TEST_AGNHOST_IMAGE_WITH_SHA%%@*}
...
+        # Docker/containerd race condition where 'docker rm -f' fails with
+        # "could not kill container ... did not receive an exit event".
+        # See https://github.com/kubernetes-sigs/kueue/issues/8908
+        echo "Forcing Docker container cleanup for cluster '$cluster_name'..."
+        local containers
+        containers=$(docker ps -aq --filter "label=io.x-k8s.kind.cluster=${cluster_name}" 2>/dev/null || true)
+        for cid in $containers; do
+            docker kill "$cid" 2>/dev/null || true
+            docker rm -f -v "$cid" 2>/dev/null || true
+        done
```
Comment (mbobrovskyi) [inline hack/testing/e2e-common.sh]: Do we need this? Does kind handle this the same way?

File: hack/testing/e2e-common.sh [hunk 4]
```diff
@@ -159,7 +159,40 @@ export E2E_TEST_AGNHOST_IMAGE=${E2E_TEST_AGNHOST_IMAGE_WITH_SHA%%@*}
...
+        if [ "$attempt" -eq "$max_retries" ]; then
+            break
+        fi
+
+        echo "WARNING: kind delete cluster '$cluster_name' failed (attempt $attempt/$max_retries)."
+
+        # Force-stop Docker containers before retrying. Works around a
+        # Docker/containerd race condition where 'docker rm -f' fails with
+        # "could not kill container ... did not receive an exit event".
+        # See https://github.com/kubernetes-sigs/kueue/issues/8908
```
Comment (mbobrovskyi) [inline hack/testing/e2e-common.sh]: Could you please add links to https://github.com/moby/moby/issues/51028
 and https://github.com/moby/moby/issues/51845
 in the comment? After the fix, we can probably revert these changes, right?

File: hack/testing/e2e-common.sh (hunk 1 above)
Comment (mimowo) [reply hack/testing/e2e-common.sh]: im ok with that but provided it does not complicate code too much. bash is pretty simple language. Failed cluster deletion happens very rarely, like 1/1000 probably, so I dont think we need to necessarily optimize the prrforamnce of it. Simple code is morr important here. If we can achieve exponential backoff simply, then sure

Comment (mbobrovskyi) [reply hack/testing/e2e-common.sh]: But we already have exponential backoff logic. Just optimization.

Comment (mimowo) [reply hack/testing/e2e-common.sh]: ack

File: hack/testing/e2e-common.sh (hunk 3 above)
Comment (mimowo) [reply hack/testing/e2e-common.sh]: yeah, I would assume that just retrying at the kind level is enough - it may not succeed 1/1000, but on the next attempt it will likely succeed, without our extra `docker kill`. wdyt? 

In other words, I assume retrying `$KIND delete cluster` should be enough

File: hack/testing/e2e-common.sh (hunk 1 above)
Comment (nerdeveloper) [reply hack/testing/e2e-common.sh]: Thanks, updated in 4ca5a2d. I switched to shorter exponential backoff and more retries: initial delay is now 1s with 5 attempts total (1s, 2s, 4s, 8s between retries). This keeps the workaround simple while covering the observed timing window.

File: hack/testing/e2e-common.sh (hunk 3 above)
Comment (nerdeveloper) [reply hack/testing/e2e-common.sh]: Agreed. Updated in 4ca5a2d to keep it simple: removed manual docker kill/rm and now retry only `$KIND delete cluster` with exponential backoff.

File: hack/testing/e2e-common.sh (hunk 4 above)
Comment (nerdeveloper) [reply hack/testing/e2e-common.sh]: Done in 4ca5a2d. I added both upstream links in the code comment (moby/moby#51028 and moby/moby#51845) and noted this workaround can be revisited once upstream fixes are available.

**Comment by mbobrovskyi** [comment]
Awesome! Thank you so much!

/lgtm
/approve

/hold if @mimowo want to add something

**Comment by mimowo** [comment]
Looks great, let's give it a try
/unhold
/cherrypick release-0.16
/cherrypick release-0.15
