### PR TITLE
Fix Kueue ownership traversal resulting in permission errors

### LINKED ISSUE #5235: Kueue controller is trying to access third party GVKs which doesn't have access to
**What happened**:

I'm trying to use Kueue with Kserve for model inference (through the Deployment and Pod integration) and I'm seeing many error logs in the Kueue controller manager like:

```
W0512 16:37:49.006396       1 reflector.go:569] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:108: failed to list *v1.PartialObjectMetadata: inferenceservices.serving.kserve.io is forbidden: User "system:serviceaccount:kueue-system:kueue-controller-manager" cannot list resource "inferenceservices" in API group "serving.kserve.io" at the cluster scope
E0512 16:37:49.006442       1 reflector.go:166] "Unhandled Error" err="sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:108: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: inferenceservices.serving.kserve.io is forbidden: User \"system:serviceaccount:kueue-system:kueue-controller-manager\" cannot list resource \"inferenceservices\" in API group \"serving.kserve.io\" at the cluster scope" logger="UnhandledError"
```

**What you expected to happen**:

No error logs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Clone this repo https://github.com/pierDipi/kueue-access-unknown-gvks
    `git clone git@github.com:pierDipi/kueue-access-unknown-gvks.git`
1. Run `kind create cluster`
2. Run `./repro.sh`
3. See error logs: `kubectl logs -n kueue-system -l=control-plane=controller-manager -f`

**Anything else we need to know?**: I don't want to give Kueue access to a resource that doesn't need to have access to.

**Environment**: KinD
- Kubernetes version (use `kubectl version`): 
  ```
  $ kubectl version
  # ...
  Server Version: v1.32.2
  ```
- Kueue version (use `git describe --tags --dirty --always`): 0.11.4 (latest as of today)
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Linux (Fedora)
- Kernel (e.g. `uname -a`): N/A

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind regression

#### Which issue(s) this PR fixes:

Fixes #5235

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug which prevented running Jobs (with queue-name label) owned by other Jobs for which Kueue does not 
have the necessary RBAC permissions (for example kserve or CronJob).
```

### CODE REVIEW

File: test/e2e/singlecluster/e2e_test.go [hunk 1]
```diff
@@ -118,6 +119,78 @@ var _ = ginkgo.Describe("Kueue", func() {
 			util.ExpectAllPodsInNamespaceDeleted(ctx, k8sClient, ns)
 		})
 
+		ginkgo.It("Should allow to schedule Jobs via CronJob", func() {
```
Comment (kannon92) [inline test/e2e/singlecluster/e2e_test.go:122]: Great test case! Thanks for adding it.

File: pkg/controller/jobframework/integrationmanager.go [hunk 2]
```diff
@@ -198,6 +199,20 @@ func (m *integrationManager) getList() []string {
...
+		if cbs.matchingOwnerReference(ownerRef) {
+			return true
+		}
+	}
+	for _, jt := range m.externalIntegrations {
+		if ownerReferenceMatchingGVK(ownerRef, jt.GetObjectKind().GroupVersionKind()) {
+			return true
+		}
+	}
+	return ownerRef.Kind == "ReplicaSet" && ownerRef.APIVersion == "apps/v1"
```
Comment (kannon92) [inline pkg/controller/jobframework/integrationmanager.go:213]: The first two blocks of code make sense to me.

The replicaSet does not. I'm sure this is correct but could you add a comment here explaining why?

Comment (mimowo) [reply pkg/controller/jobframework/integrationmanager.go:213]: Sure, we need to be able to walk up the ownerhip chain for Pod -> ReplicaSet -> Deployment. 

However, ReplicaSet is "technical detail" rather than an integration a user would like to enable or see in the config.

File: test/e2e/singlecluster/e2e_test.go (hunk 1 above)
Comment (mimowo) [reply test/e2e/singlecluster/e2e_test.go:122]: Thanks, the only downside is that sometimes the Job gets 1min to be created by the CronJob, because CronJob seems to only create with 1min resolution. I'm wondering if we could trick it: 
- create CronJob suspended
- patch CronJob status to indicate the last schedule was over 1min ago
- resume

I will check if this works, because I don't like wasting 1min (or 30s on average) for this test.

File: pkg/controller/jobframework/integrationmanager.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/jobframework/integrationmanager.go:213]: /hold
We have had one e2e test for this scenario, but we are missing unit test, I will add.

Comment (mimowo) [reply pkg/controller/jobframework/integrationmanager.go:213]: /unhold
added under "Pod -> ReplicaSet -> Deployment (queue-name) => Deployment". I tested it fails without this line.

**Comment by mimowo** [comment]
@kannon92 @dgrove-oss @tenzen-y This is ready for review I think.

File: pkg/controller/jobframework/integrationmanager.go (hunk 2 above)
Comment (dgrove-oss) [reply pkg/controller/jobframework/integrationmanager.go:213]: Makes sense.  Thanks for adding the extra test case.

**Review by dgrove-oss — APPROVED** [review]
lgtm.

**Review by dgrove-oss — APPROVED** [review]

File: pkg/controller/jobframework/integrationmanager.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/jobframework/integrationmanager.go:213]: will do soon

Comment (mimowo) [reply pkg/controller/jobframework/integrationmanager.go:216]: Done, ptal

**Review by dgrove-oss — APPROVED** [review]
/lgtm

**Review by kannon92 — COMMENTED** [review]
/lgtm

File: test/e2e/singlecluster/e2e_test.go [hunk 3]
```diff
@@ -118,6 +121,85 @@ var _ = ginkgo.Describe("Kueue", func() {
...
+			})
+
+			ginkgo.By("Patch the last start time to be in the past so that it starts immediately", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(cronJob), cronJob)).To(gomega.Succeed())
+					nextSchedule := cronJob.CreationTimestamp.Add(-2 * time.Minute)
+					cronJob.Status.LastScheduleTime = ptr.To(metav1.Time{Time: nextSchedule})
+					g.Expect(k8sClient.Status().Update(ctx, cronJob)).Should(gomega.Succeed())
+				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+			})
```
Comment (tenzen-y) [inline test/e2e/singlecluster/e2e_test.go:176]: We might want to move CronJob case to integration tests and emulate the kube-controller-manager behavior like https://github.com/kubernetes/kubectl/blob/88bb12ba04025e5b03a141ad26fca1c735d54e11/pkg/cmd/create/create_job.go#L254-L287

And we can expand Appwrapper E2E to verify the unknown owners.

**Review by tenzen-y — COMMENTED** [review]
Thank you

File: test/e2e/singlecluster/e2e_test.go (hunk 3 above)
Comment (mimowo) [reply test/e2e/singlecluster/e2e_test.go:176]: I would suggest to stay with e2e, for two reasons:
- emulating `kube-controller-manager` is generally hard
- it is easier to test RBAC permissions in e2e, I don't think we install them for integration tests, so it means a lot of extra work. 

wdyt @tenzen-y ?

Comment (tenzen-y) [reply test/e2e/singlecluster/e2e_test.go:176]: IIUC, this test case does not depend on any CronJob features. So, I think we can move this case to integration test, then could reduce E2E test duration.

Comment (mimowo) [reply test/e2e/singlecluster/e2e_test.go:176]: I'm just not sure we verify RBAC in integration tests, and the bug would only surface at the permission layer.

So, we may need to extend / refactor the integration tests to enable that check.

Comment (mimowo) [reply test/e2e/singlecluster/e2e_test.go:176]: @tenzen-y I synced with @kaisoz about moving forward with the "simple" its. As mentioned above the moving of the CronJob test is more involving as it requires enabling RBAC checks in the integration tests so that the test could pick up the original issue for which the  test was added. I believe this requires a separate issue on its own as this is not a "quick follow up" imo.
