### PR TITLE
Fix preemption algorithm to reduce the number of preemptions

### LINKED ISSUE #1974: Too many preemptions within ClusterQueue when already above nominal quota
**What happened**:

In #614, we allowed preemption to happen when a CQ is above nominal, with an end state where the CQ continues to be above nominal quota. However, the circumstances in which that happens are hard to predict.
More commonly, we do preemptions until the incoming workload and the already running workloads fit within the nominal quota only (no borrowing).
This is encoded here:
 https://github.com/kubernetes-sigs/kueue/blob/3347afb5a8681f4fd2a5f3b1a5be8c5c0ebac488/pkg/scheduler/preemption/preemption.go#L119-L125

There are two problems with this approach:
1. It can lead to a lot of unnecessary preemptions. In one case that was diagnosed in a real cluster, a high priority job that uses all of the nominal quota caused the preemption of all running workloads.
2. It's extremely hard to explain to users what the behavior is.

**What you expected to happen**:

I propose the following rules for preemption:

1. A workload is only eligible to do preemptions if it fits fully within nominal quota (current behavior).  _Rationale: If the workload goes above nominal by itself, then it's an easy target for preemption, losing all the advantage of preemption_ https://github.com/kubernetes-sigs/kueue/blob/3347afb5a8681f4fd2a5f3b1a5be8c5c0ebac488/pkg/scheduler/flavorassigner/flavorassigner.go#L555-L560
2. If existing workloads are under nominal, the workload is eligible to preempt from other cluster queues and from its own workloads (fits within existing behavior), but, in the final result, the CQ is not above nominal. _Rationale: if it was only able to preempt from its own clusterqueue, and all the resources are being borrowed by someone else, then the workload wouldn't fit in the cluster, even if it's under nominal_  https://github.com/kubernetes-sigs/kueue/blob/3347afb5a8681f4fd2a5f3b1a5be8c5c0ebac488/pkg/scheduler/preemption/preemption.go#L119
3. If existing workloads are above nominal (in other words, currently borrowing) and the workload fits within nominal by itself (rule 1), **the workload is only eligible to preempt workloads from its own cluster queue, but the end result of running workloads is allowed to be above nominal**. Note that here there is no risk of affecting other CQs in the cohort (this would be new behavior).

Once implemented, we should add the rules above into the user documentation.

**How to reproduce it (as minimally and precisely as possible)**:

- 3 CQs, A, B, C of with nominal quota 2 each and no borrowing limit.
- A has 3 workloads of size 1 with priority `-1`
- C has 3 workloads of size 1 with priority `0`
- A new workload of size 2 for CQ A of priority `0` comes in

Current behavior: all running workloads in A are preempted.
Wanted behavior: only 2 workloads in A are preempted.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #1974

#### Does this PR introduce a user-facing change?

```release-note
Fix preemption algorithm to reduce the number of preemptions within a ClusterQueue when reclamation is not possible.
```

### CODE REVIEW

File: pkg/scheduler/preemption/preemption.go [hunk 1]
```diff
@@ -116,6 +116,14 @@ func (p *Preemptor) GetTargets(wl workload.Info, assignment flavorassigner.Assig
 		}
 		return minimalPreemptions(&wl, assignment, snapshot, resPerFlv, candidates, true, allowBorrowingBelowPriority)
 	}
+
+	// the target queue is exhausted in all requested flavors, so preempting
+	// workloads from other cluster queues in the cohort is no help. so we
+	// only preempt workloads from the target cluster queue.
+	if isQueueExhaustedForAllRequestedFlavors(&wl, assignment, cq) {
```
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption.go:123]: could we instead pass this flag to `findCandidates`? I guess no, because we still need to allow borrowWithinCohort when enabled, right?

File: pkg/scheduler/preemption/preemption.go [hunk 2]
```diff
@@ -395,6 +403,28 @@ func workloadFits(wlReq cache.FlavorResourceQuantities, cq *cache.ClusterQueue,
 	return true
 }
 
+// is queue exhausted for all requested flavors
+func isQueueExhaustedForAllRequestedFlavors(wl *workload.Info, assignment flavorassigner.Assignment, cq *cache.ClusterQueue) bool {
+	wlReq := totalRequestsForAssignment(wl, assignment)
```
Comment (mimowo) [inline pkg/scheduler/preemption/preemption.go:408]: This line is repeated with `minimalPreemptions`. I think we should move it up, but for now keep it here to make the diff minimal.

File: pkg/scheduler/preemption/preemption.go (hunk 1 above)
Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go:123]: Right, but not only that, this is an optimization only if `allowBorrowing=false`. If `allowBorrowing=true` (as in a couple of other branches) we still need to include candidates from other cluster queues. Even if the target CQ is exhausted, because preempting workloads from other CQs may help.

Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go:123]: So, this is essentially only to skip the check below `targets := minimalPreemptions(&wl, assignment, snapshot, resPerFlv, candidates, false, nil)`. Maybe we can organize the code differently to make it cleaner.

File: pkg/scheduler/preemption/preemption.go [hunk 3]
```diff
@@ -395,6 +403,28 @@ func workloadFits(wlReq cache.FlavorResourceQuantities, cq *cache.ClusterQueue,
 	return true
 }
 
+// is queue exhausted for all requested flavors
+func isQueueExhaustedForAllRequestedFlavors(wl *workload.Info, assignment flavorassigner.Assignment, cq *cache.ClusterQueue) bool {
```
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption.go:407]:
```suggestion
func isQueueExhaustedInAnyRequestedFlavors(wl *workload.Info, assignment flavorassigner.Assignment, cq *cache.ClusterQueue) bool {
```

if I'm interpreting the logic correctly.

File: pkg/scheduler/preemption/preemption.go
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption.go:1]: let's add a test case in `preemption_test.go` as well.

File: pkg/scheduler/scheduler_test.go [hunk 4]
```diff
@@ -1403,6 +1403,352 @@ func TestSchedule(t *testing.T) {
...
+				"eng-alpha/a1": {
+					ClusterQueue: "other-alpha",
+					PodSetAssignments: []kueue.PodSetAssignment{
+						{
+							Name: "main",
+							Flavors: map[corev1.ResourceName]kueue.ResourceFlavorReference{
+								corev1.ResourceCPU: "on-demand",
+							},
+							ResourceUsage: corev1.ResourceList{
+								corev1.ResourceCPU: resource.MustParse("1000m"),
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler_test.go:1669]: I don't know when we started doing this, but it's just less readable.
```suggestion
								corev1.ResourceCPU: resource.MustParse("1"),
```

File: pkg/scheduler/scheduler_test.go [hunk 5]
```diff
@@ -1403,6 +1403,352 @@ func TestSchedule(t *testing.T) {
...
+							},
+							Count: ptr.To[int32](1),
+						},
+					},
+				},
+			},
+		},
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler_test.go:1751]: Can you add a test case for `A workload is only eligible to do preemptions if it fits fully within nominal quota`?

File: pkg/scheduler/preemption/preemption.go [hunk 6]
```diff
@@ -116,6 +116,14 @@ func (p *Preemptor) GetTargets(wl workload.Info, assignment flavorassigner.Assig
...
+
+	// the target queue is exhausted in all requested flavors, so preempting
+	// workloads from other cluster queues in the cohort is no help. so we
+	// only preempt workloads from the target cluster queue.
+	if isQueueExhaustedForAllRequestedFlavors(&wl, assignment, cq) {
+		return minimalPreemptions(&wl, assignment, snapshot, resPerFlv, sameQueueCandidates, true, nil)
+	}
+
 	targets := minimalPreemptions(&wl, assignment, snapshot, resPerFlv, candidates, false, nil)
 	if len(targets) == 0 {
```
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption.go:128]: Are we still reaching this branch with any of the test cases?

Comment (alculquicondor) [reply pkg/scheduler/preemption/preemption.go:128]: I'm tempted to remove it.

File: pkg/scheduler/preemption/preemption.go (hunk 2 above)
Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go]: Done

File: pkg/scheduler/preemption/preemption.go
Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go:1]: Good idea, I added both test cases there. Only keep the main one is scheduler_test.go

File: pkg/scheduler/scheduler_test.go (hunk 4 above)
Comment (mimowo) [reply pkg/scheduler/scheduler_test.go]: Done, and now I use `MakeAdmission` to make it even cleaner

File: pkg/scheduler/scheduler_test.go (hunk 5 above)
Comment (mimowo) [reply pkg/scheduler/scheduler_test.go:1635]: Done

File: pkg/scheduler/preemption/preemption.go (hunk 6 above)
Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go]: Yes, we have a failing unit test in `preemption_test.go`: "preempting locally and borrowing other resources in cohort, without cohort candidates" (yes it is using `reclaimWithinCohort: LowerPriority`, but I checked that it also fails if we change `reclaimWithinCohort` to `Any`. I would suggest keeping it (at least in this PR, and probably its removal would require a feature gate). 

However, your comment prompted me to think of a cleaner code structure, so that `return minimalPreemptions(wlReq, cq, assignment, snapshot, resPerFlv, sameQueueCandidates, true, nil)` appears only once in code. PTAL.

File: pkg/scheduler/preemption/preemption.go (hunk 3 above)
Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go]: That's right. I have updated it, and added some test that demonstrate a difference between "any" and "all", like "minimal preemptions when target queue is exhausted in one resource, but not the other".

File: pkg/scheduler/preemption/preemption.go [hunk 7]
```diff
@@ -114,16 +114,20 @@ func (p *Preemptor) GetTargets(wl workload.Info, assignment flavorassigner.Assig
...
 	}
-	targets := minimalPreemptions(&wl, assignment, snapshot, resPerFlv, candidates, false, nil)
-	if len(targets) == 0 {
-		// Another attempt. This time only candidates from the same queue, but
-		// with borrowing. The previous attempt didn't try borrowing and had broader
-		// scope of preemption.
-		targets = minimalPreemptions(&wl, assignment, snapshot, resPerFlv, sameQueueCandidates, true, nil)
+
+	// If the target queue is exhausted in any requested resource, then we skip
+	// the attempt of preemptions in the cohort, but without borrowing.
```
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption.go:121]: This comment is very confusing. Maybe the other way around:

Only try preemptions in the cohort, without borrowing, if the target clusterqueue is still
under nominal quota for all resources.

And with that, change the function name to `queueUnderNominalInAllRequestedResources`.

File: pkg/scheduler/preemption/preemption_test.go [hunk 8]
```diff
@@ -1062,6 +1090,205 @@ func TestPreemption(t *testing.T) {
 			wantPreempted:      nil,
 			enableLendingLimit: true,
 		},
+		"minimal preemptions when target queue is exhausted for the single requested resource": {
```
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption_test.go:1093]:
```suggestion
		"preemptions from cq when target queue is exhausted for the single requested resource": {
```

File: pkg/scheduler/preemption/preemption_test.go [hunk 9]
```diff
@@ -1062,6 +1090,205 @@ func TestPreemption(t *testing.T) {
...
+			targetCQ: "a",
+			assignment: singlePodSetAssignment(flavorassigner.ResourceAssignment{
+				corev1.ResourceCPU: &flavorassigner.FlavorAssignment{
+					Name: "default",
+					Mode: flavorassigner.Preempt,
+				},
+			}),
+			wantPreempted: sets.New("/a1", "/a2"),
+		},
+		"minimal preemptions when target queue is exhausted for two requested resources": {
```
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption_test.go:1139]:
```suggestion
		"preemptions from cq when target queue is exhausted for two requested resources": {
```

File: pkg/scheduler/preemption/preemption_test.go [hunk 10]
```diff
@@ -1062,6 +1090,205 @@ func TestPreemption(t *testing.T) {
...
+					Mode: flavorassigner.Preempt,
+				},
+				corev1.ResourceMemory: &flavorassigner.FlavorAssignment{
+					Name: "default",
+					Mode: flavorassigner.Preempt,
+				},
+			}),
+			wantPreempted: sets.New("/a1", "/a2"),
+		},
+		"minimal preemptions when target queue is exhausted for one requested resource, but not the other": {
```
Comment (alculquicondor) [inline pkg/scheduler/preemption/preemption_test.go:1196]:
```suggestion
		"preemptions from cq when target queue is exhausted for one requested resource, but not the other": {
```

File: pkg/scheduler/scheduler_test.go [hunk 11]
```diff
@@ -1403,6 +1403,237 @@ func TestSchedule(t *testing.T) {
 				"eng-beta": {"eng-beta/older_new"},
 			},
 		},
+		"minimal preemptions when target queue is exhausted": {
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler_test.go:1406]: remove either the first or second test case, as the specifics are covered in preemption_test.go

File: pkg/scheduler/preemption/preemption.go (hunk 7 above)
Comment (mimowo) [reply pkg/scheduler/preemption/preemption.go]: done

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
/release-note-edit
```
Fix preemption algorithm to reduce the number of preemptions within a ClusterQueue when reclamation is not possible.
```

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Fix preemption algorithm to reduce the number of preemptions within a ClusterQueue when reclamation is not possible.
```
