### PR TITLE
VisibilityOnDemand: inaccurate OpenAPI schema

### LINKED ISSUE #8873: VisibilityOnDemand: inaccurate OpenAPI schema
**What happened**:

When I upgrade Kueue version from v0.15.3 to v0.16.0, I faced the following errors in ArgoCD:

```shell
failed to load open api schema while syncing cluster cache: error getting openapi resources: SchemaError(sigs.k8s.io/kueue/apis/visibility/v1beta1.PendingWorkloadsSummary.items): unknown model in reference: "sigs.k8s.io~1kueue~1apis~1visibility~1v1beta1.PendingWorkload"
```

As a result, ArgoCD doesn't work well across all Argo Applications since ArgoCD keeps failing to construct the cluster cache inside ArgoCD.

**What you expected to happen**:
No scheme errors.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce this problem, we need to set up [ArgoCD](https://github.com/argoproj/argo-cd) and manage Kueue as an ArgoApplication.

**Anything else we need to know?**:
After I removed all APIServices (`v1beta1.visibility.kueue.x-k8s.io` and `v1beta2.visibility.kueue.x-k8s.io`) for the visibility servers, this error has gone away. 
If either removing only the v1beta1 APIService or only the v1beta2 APIService, the described error isn't resolved.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.34.2
- Kueue version (use `git describe --tags --dirty --always`): v0.16.0
- Cloud provider or hardware configuration: Baremetal
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by vladikkuzn**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes the generated OpenAPI for the VisibilityOnDemand APIs by assigning stable OpenAPI model names for visibility/v1beta1 and visibility/v1beta2 (via +k8s:openapi-model-package + generated zz_generated.model_name.go) and referencing types via OpenAPIModelName() in apis/visibility/openapi/zz_generated.openapi.go.
This prevents OpenAPI schema resolution failures like:
unknown model in reference: "…PendingWorkload"

#### Which issue(s) this PR fixes:

Fixes #8873

#### Does this PR introduce a user-facing change?

```release-note
VisibilityOnDemand: Fix Visibility API OpenAPI schema generation to prevent schema resolution errors when visibility v1beta1/v1beta2 APIServices are installed.

The visibility schema issues result in the following error when re-applying the manifest for Kueue 0.16.0:
`failed to load open api schema while syncing cluster cache: error getting openapi resources: SchemaError(sigs.k8s.io/kueue/apis/visibility/v1beta1.PendingWorkloadsSummary.items): unknown model in reference: "sigs.k8s.io~1kueue~1apis~1visibility~1v1beta1.PendingWorkload"`
```

### CODE REVIEW

File: hack/update-codegen.sh [hunk 1]
```diff
@@ -39,6 +39,7 @@ kube::codegen::gen_openapi \
   --boilerplate "${KUEUE_ROOT}/hack/boilerplate.go.txt" \
   --output-dir "${KUEUE_ROOT}/apis/visibility/openapi" \
   --output-pkg "${KUEUE_PKG}/apis/visibility/openapi" \
+  --output-model-name-file "zz_generated.model_name.go" \
```
Comment (mbobrovskyi) [inline hack/update-codegen.sh:42]: As I mentioned here: https://github.com/kubernetes-sigs/kueue/pull/8805#discussion_r2745047370, can we ignore the vendor directory?

**Comment by mimowo** [comment]
Folks, qq if we backport this fix to 0.16 branch will users be able to automatically upgrade 0.16.0 to 0.16.1 or we need extra steps for users?

File: hack/update-codegen.sh (hunk 1 above)
Comment (vladikkuzn) [reply hack/update-codegen.sh:42]: It already does, we just have different header, that's why it regenerates it
https://github.com/kubernetes/code-generator/blob/master/kube_codegen.sh#L62
https://github.com/kubernetes/code-generator/blob/master/kube_codegen.sh#L393


Fixed the header by adding new line

**Comment by vladikkuzn** [comment]
> Folks, qq if we backport this fix to 0.16 branch will users be able to automatically upgrade 0.16.0 to 0.16.1 or we need extra steps for users?

Checking

File: hack/update-codegen.sh (hunk 1 above)
Comment (mbobrovskyi) [reply hack/update-codegen.sh:42]: Hmm, but how is this related? I don’t get it.

**Comment by vladikkuzn** [comment]
> Folks, qq if we backport this fix to 0.16 branch will users be able to automatically upgrade 0.16.0 to 0.16.1 or we need extra steps for users?

Seems like it updates fine. 
How I checked: 
- run E2E_MODE=dev make kind-image-build test-e2e on main
- run E2E_MODE=dev make kind-image-build test-e2e on this branch

Result: error related to update of kuberay which is fixed in https://github.com/kubernetes-sigs/kueue/pull/8805

**Comment by mimowo** [comment]
Thabk you!
/approve
leaving final tagging to @mbobrovskyi 
/cherrypick release-0.16

File: hack/update-codegen.sh (hunk 1 above)
Comment (vladikkuzn) [reply hack/update-codegen.sh:42]: Here it touches header for apimachinery https://github.com/kubernetes/code-generator/blob/master/kube_codegen.sh#L419-L422
And it's hardcoded

Comment (mbobrovskyi) [reply hack/update-codegen.sh:42]: I see. Thank you for explanation!

**Comment by mbobrovskyi** [comment]
@vladikkuzn could you please fix verify?

**Comment by vladikkuzn** [comment]
Working on verify, it's also related to the header. With new line in header chart validation returns an error, while it's fully valid

**Comment by vladikkuzn** [comment]
@mbobrovskyi ptal at hack/internal/tools/yaml-processor/yamlproc/processor.go

**Comment by mbobrovskyi** [comment]
@vladikkuzn thank you so much for this fix!

/lgtm
/unhold

**Comment by mimowo** [comment]
/test  pull-kueue-test-integration-extended-main
known flake: https://github.com/kubernetes-sigs/kueue/issues/8809

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Fix Visibility API OpenAPI schema generation to prevent schema resolution errors when visibility v1beta1/v1beta2 APIServices are installed.

The visibility schema issues result in the following error when re-applying the manifest for Kueue 0.16.0:
`failed to load open api schema while syncing cluster cache: error getting openapi resources: SchemaError(sigs.k8s.io/kueue/apis/visibility/v1beta1.PendingWorkloadsSummary.items): unknown model in reference: "sigs.k8s.io~1kueue~1apis~1visibility~1v1beta1.PendingWorkload"`
```
