### PR TITLE
Fix: trigger workload requeue on ElasticJob scale-down

### LINKED ISSUE #6384: ElasticJob scale-down does not trigger re-scheduling of pending inadmissible workloads
**What happened**:

Currently, scaling down a `batch/v1.Job` with ElasticJob enabled does **not** trigger re-evaluation or re-submission of workloads that are pending due to prior admission failures (e.g., due to insufficient resources).

**What you expected to happen**:

When an ElasticJob scales down and releases resources, this should result in a corresponding update to the reclaimable pod count. In turn, the system should requeue and re-evaluate pending workloads in the same ClusterQueue for admission.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable the `ElasticJobsViaWorkloadSlices` feature gate.
2. Configure a LocalQueue and ClusterQueue according to Kueue documentation, e.g.:

```yaml
resourceGroups:
- coveredResources: ["cpu", "memory"]
  flavors:
    - name: "default-flavor"
      resources:
        - name: "cpu"
          nominalQuota: 2
        - name: "memory"
          nominalQuota: 36Gi
```

3. Create a `batch/v1.Job` with the following configuration:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-slice
  namespace: demo
  annotations:
    kueue.x-k8s.io/elastic-job: "true"
  labels:
    kueue.x-k8s.io/queue-name: demo
spec:
  parallelism: 3
  completions: 10
  template:
    spec:
      containers:
        - name: dummy-job
          image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
          args: ["600s"]
          resources:
            requests:
              cpu: "500m"
              memory: "100Mi"
      restartPolicy: Never
```

4. Observe CPU flavor utilization in the ClusterQueue and LocalQueue at `1500m`.
5. Submit a second Job with the same configuration.
6. Observe that the second Job remains in the **Pending** state due to insufficient available CPU quota (`500m` available, `1500m` required).
7. Scale down the first Job by patching `parallelism: 1`.
8. Observe that flavor utilization drops to `500m`.
9. However, the second Job remains in **Pending**, even though sufficient capacity is now available to admit it.

**Anything else we need to know?**:

This issue stems from the fact that ElasticJob does not update the `reclaimablePods` during scale-down, preventing the system from recognizing the reclaimed capacity and re-evaluating pending workloads.

**Environment**:

* Kubernetes version (use `kubectl version`):
* Kueue version (use `git describe --tags --dirty --always`):
* Cloud provider or hardware configuration:
* OS (e.g., `cat /etc/os-release`):
* Kernel (e.g., `uname -a`):
* Install tools:
* Others:

/bug

### PR DESCRIPTION
**Pull request by ichekrygin**
Ensure that scaling down an ElasticJob updates the reclaimablePods field in the workload status, allowing the scheduler to detect freed capacity and requeue pending workloads.

This resolves a bug where pending jobs remained unadmitted even after capacity was released by a scale-down operation.

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This resolves a bug where pending jobs remained unadmitted even after capacity was released by a scale-down operation.

#### Which issue(s) this PR fixes:

Fixes #6384

#### Does this PR introduce a user-facing change?

```release-note
ElasticJobs: Fix the bug that scheduling of the Pending workloads was not triggered on scale-down of the running 
elastic Job which could result in admitting one or more of the queued workloads.
```

### CODE REVIEW

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 1]
```diff
@@ -3226,6 +3223,84 @@ var _ = ginkgo.Describe("Job with elastic jobs via workload-slices support", gin
...
+					testJobBWorkload = &workloads.Items[0]
+					util.ExpectWorkloadsToBePending(ctx, k8sClient, testJobBWorkload)
+
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+				ginkgo.By("scale-down job-a to make room for job-b")
+				gomega.Eventually(func(g gomega.Gomega) {
+					testJobA.Spec.Parallelism = ptr.To(int32(1))
+					g.Expect(k8sClient.Update(ctx, testJobA)).Should(gomega.Succeed())
+				}).Should(gomega.Succeed())
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Please add some timeout, I also noticed they are missing in the old tests, so you could specify them too

File: pkg/controller/core/workload_controller.go [hunk 2]
```diff
@@ -810,7 +811,8 @@ func (r *WorkloadReconciler) Update(e event.TypedUpdateEvent[*kueue.Workload]) b
 				}
 			})
 		}
-	case prevStatus == workload.StatusAdmitted && status == workload.StatusAdmitted && !equality.Semantic.DeepEqual(e.ObjectOld.Status.ReclaimablePods, e.ObjectNew.Status.ReclaimablePods):
+	case prevStatus == workload.StatusAdmitted && status == workload.StatusAdmitted && !equality.Semantic.DeepEqual(e.ObjectOld.Status.ReclaimablePods, e.ObjectNew.Status.ReclaimablePods),
+		features.Enabled(features.ElasticJobsViaWorkloadSlices) && workloadslicing.ScaledDown(workload.ExtractPodSetCountsFromWorkload(e.ObjectOld), workload.ExtractPodSetCountsFromWorkload(e.ObjectNew)):
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go:815]: This looks good, but let me use this as an occasion to get understanding on how scale down works. 

When a user requests scale down: 
1. Do we release some quota during the scaledown before the pods are actually deleted, resulting in temporarily pods running over quota?
2. Do we keep more quota than needed until the scale up is finished?

IIUC ideally we would gradually release the quota (as the pods terminate and are accounted in reclaimablePods) until the scale down is finished. Once finished we cleanup `reclaimablePods` and update the podsets count, so that the scaled down workload looks as if it was created new. This workload property would make debugging easier.

Let me know if I'm potentially missing something.  If you agree, but assess this is more work I can lgtm / approve this one, so that we fix one issue at the time, let me know.

Comment (ichekrygin) [reply pkg/controller/core/workload_controller.go:815]: Currently, `batch/v1.Job` is the only framework that supports the ElasticJobsViaWorkloadSlices feature.
A scale-down is triggered when the user (or automation) updates the Job's `spec.parallelism` to a lower value. Kueue’s handling of this event is entirely reactionary. Once the `spec.parallelism` field is decreased, the Kubernetes Job controller proceeds to complete and remove the excess pods. Kueue, in parallel, observes the change and updates the associated Workload’s `spec.podSets[].count` to reflect the new, lower value.

Since both the K8s Job controller and the Kueue controller respond independently to the same job change, the pod removal and quota release happen concurrently. In practice, pod deletion often completes slightly before the Workload update and subsequent quota release. However, there are no guardrails to enforce strict ordering, nor is there coordination between the two controllers to ensure that quota is only released after the pods are gone. 

By the same token, there's no concept of gradual scale-down in this context. When a Job’s parallelism is reduced, for example, from 10 to 2, the Kubernetes Job controller will proceed to delete the `8` excess pods almost immediately. The deletions happen as fast as the controller and API server allow, and there's no stepwise or progressive reduction. So in practice, the scale-down is effectively instantaneous from the controller's point of view.

Comment (mimowo) [reply pkg/controller/core/workload_controller.go:815]: I see, actually the `reclaimablePods` are only [decremented when the terminated pods are Succeeded](https://github.com/kubernetes-sigs/kueue/blob/85c06dffa2de9b69c236b8fda610edbede0120e7/pkg/controller/jobs/job/job_controller.go#L213-L228). We should not make the assumption for pods deleted due to scale down. They may end in 0 or non zero exit code. So, I think it is correct not to rely on `reclaimablePods`.

I see this approach allows for pods running at the same beyond quota for a brief time. Since this is temporary only, I'm not very concerned about it. It would be ideal to release quota gradually, but it might be hard in practice, so we can leave it as a follow up feature on its own.

**Comment by mimowo** [comment]
/lgtm
/approve
/cherrypick release-0.13
Thanks 👍

**Comment by mimowo** [comment]
Proposal, ptal
/release-note-edit
```release-note
ElasticJobs: Fix the bug that scheduling of the Pending workloads was not triggered on scale-down of the running 
elastic Job which could result in admitting one or more of the queued workloads.
```
