### PR TITLE
fix: Modified job spec activates deactivated Workload. #6719

### LINKED ISSUE #6719: Modified resource activates deactivated Workload
**What happened**:
I have created PyTorchJob CR managed by Kueue, stopped the training by setting corresponding Workload `.spec.active` flag to `false`. However when I modified the PyTorchJob then corresponding Workload gets activated again.

**What you expected to happen**:
I was expecting Workload related to modified PyTorchJob to stay deactivated.

**How to reproduce it (as minimally and precisely as possible)**:
Install latest Training operator : `kubectl apply --server-side -k "github.com/kubeflow/training-operator.git/manifests/overlays/standalone?ref=v1.9.3"`
Setup sample Kueue resources:
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-flavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory", "pods"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
      - name: "pods"
        nominalQuota: 5
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: lq
spec:
  clusterQueue: cluster-queue 
```

Create sample PyTorchJob:
```
apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-sleep-job-small"
  labels:
    kueue.x-k8s.io/queue-name: lq
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: python:3.9-alpine
              command:
                - "python"
                - "-c"
                - "import time; print('Container started with small image, sleeping for 60s...'); time.sleep(60); print('Done sleeping.')"
```

Once corresponding training Pod starts stop the corresponding Workload:
```
for wl in $(kubectl get workload -n default -o jsonpath='{.items[*].metadata.name}'); do kubectl patch workload $wl -n default --type merge -p '{"spec":{"active":false}}'; done
```

Scale PyTorchJob:
```
kubectl patch pytorchjob pytorch-sleep-job-small --type merge -p '{"spec":{"pytorchReplicaSpecs":{"Worker":{"replicas":2}}}}'
```

Workload gets activated again.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.32.2
- Kueue version (use `git describe --tags --dirty --always`): v0.13.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Fedora 42
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When updating the workload, we should keep the spec.Active field unchanged, because Active is set to true by default, which does not match the current user's expected behavior.

https://github.com/kubernetes-sigs/kueue/blob/ae75bac9048c9c6dd30c1536b3b39527f92045c1/apis/kueue/v1beta2/workload_types.go#L59-L68

#### Which issue(s) this PR fixes:

Fixes #6719 

#### Does this PR introduce a user-facing change?

```release-note
JobFramework: Fixed a bug that allowed a deactivated workload to be activated.
```

### CODE REVIEW

File: pkg/controller/jobframework/reconciler.go [hunk 1]
```diff
@@ -1123,7 +1123,10 @@ func (r *JobReconciler) updateWorkloadToMatchJob(ctx context.Context, job Generi
 	if err != nil {
 		return nil, fmt.Errorf("can't construct workload for update: %w", err)
 	}
+	// preserve the active field, because workload.Spec.Active defaults to true
+	active := wl.Spec.Active
 	wl.Spec = newWl.Spec
+	wl.Spec.Active = active
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/reconciler.go]:
```suggestion
	newWl.Spec.Active = wl.Spec.Active
	wl.Spec = newWl.Spec
```

Comment (mbobrovskyi) [inline pkg/controller/jobframework/reconciler.go]: Can we add unit test?

Comment (chengjoey) [reply pkg/controller/jobframework/reconciler.go]: done

Comment (chengjoey) [reply pkg/controller/jobframework/reconciler.go]: done

File: pkg/controller/jobframework/reconciler.go [hunk 2]
```diff
@@ -1114,7 +1114,7 @@ func EquivalentToWorkload(ctx context.Context, c client.Client, job GenericJob,
 	return equality.ComparePodSetSlices(jobPodSets, wl.Spec.PodSets, workload.IsAdmitted(wl)), nil
 }
 
-func (r *JobReconciler) updateWorkloadToMatchJob(ctx context.Context, job GenericJob, object client.Object, wl *kueue.Workload) (*kueue.Workload, error) {
+func (r *JobReconciler) UpdateWorkloadToMatchJob(ctx context.Context, job GenericJob, object client.Object, wl *kueue.Workload) (*kueue.Workload, error) {
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/reconciler.go]: Can we avoid renaming this? Maybe add test case for ReconcileGenericJob()?

Comment (chengjoey) [reply pkg/controller/jobframework/reconciler.go]: done

File: pkg/controller/jobframework/reconciler_test.go [hunk 3]
```diff
@@ -150,6 +150,64 @@ func TestReconcileGenericJob(t *testing.T) {
 				*baseWl.Clone().Name("job-test-job-1").ResourceVersion("2").Obj(),
 			},
 		},
+		"update workload to match job preserves active=true": {
+			elasticJobsViaWorkloadSlicesEnabled: true,
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/reconciler_test.go]:
```suggestion
```

File: pkg/controller/jobframework/reconciler_test.go [hunk 4]
```diff
@@ -150,6 +150,64 @@ func TestReconcileGenericJob(t *testing.T) {
...
+			req:                                 baseReq,
+			job: baseJob.Clone().
+				SetAnnotation(workloadslicing.EnabledAnnotationKey, workloadslicing.EnabledAnnotationValue).
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/reconciler_test.go]:
```suggestion
```

File: pkg/controller/jobframework/reconciler_test.go [hunk 5]
```diff
@@ -150,6 +150,64 @@ func TestReconcileGenericJob(t *testing.T) {
...
+					PodSets(*utiltestingapi.MakePodSet("old", 2).Obj()).
+					Active(true).
+					Obj(),
+			},
+			wantWorkloads: []kueue.Workload{
+				*baseWl.Clone().Name("job-test-job-1").ResourceVersion("2").Active(true).Obj(),
+			},
+		},
+		"update workload to match job preserves active=false": {
+			elasticJobsViaWorkloadSlicesEnabled: true,
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/reconciler_test.go]:
```suggestion
```

File: pkg/controller/jobframework/reconciler_test.go [hunk 6]
```diff
@@ -150,6 +150,64 @@ func TestReconcileGenericJob(t *testing.T) {
...
+			req:                                 baseReq,
+			job: baseJob.Clone().
+				SetAnnotation(workloadslicing.EnabledAnnotationKey, workloadslicing.EnabledAnnotationValue).
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/reconciler_test.go]:
```suggestion
```

**Comment by mbobrovskyi** [comment]
/release-note-edit
```release-note
Fixed a bug that allowed a deactivated workload to be activated.
```

File: pkg/controller/jobframework/reconciler_test.go (hunk 6 above)
Comment (chengjoey) [reply pkg/controller/jobframework/reconciler_test.go]: done

**Review by mbobrovskyi — APPROVED** [review]
Thank you!

/lgtm
/approve

/cc @mimowo @tenzen-y

**Comment by mszadkow** [comment]
@chengjoey 
Can you confirm that unit tests fail without the fix?

**Comment by mbobrovskyi** [comment]
> @chengjoey Can you confirm that unit tests fail without the fix?

I’ve already checked it. Without these changes, the tests fail.

File: pkg/controller/jobframework/reconciler.go [hunk 7]
```diff
@@ -1123,6 +1123,8 @@ func (r *JobReconciler) updateWorkloadToMatchJob(ctx context.Context, job Generi
 	if err != nil {
 		return nil, fmt.Errorf("can't construct workload for update: %w", err)
 	}
+	// preserve the active field, because workload.Spec.Active defaults to true
+	newWl.Spec.Active = wl.Spec.Active
```
Comment (tenzen-y) [inline pkg/controller/jobframework/reconciler.go]: I'd like to move this processing to the `prepareWorkload` function implemented in https://github.com/kubernetes-sigs/kueue/blob/c2a5699a84bea2e19adaf00daef2546c5a7576e3/pkg/controller/jobframework/reconciler.go#L1344-L1345 so that we can avoid adding a new responsibility for updating workload-specific fields to this function.

`func (r *JobReconciler) prepareWorkload(ctx context.Context, job GenericJob, wl *kueue.Workload, active *bool) error {`

It would be better to minimize the number of functions to update Workload specs.

**Review by tenzen-y — COMMENTED** [review]
@chengjoey Thank you for creating this PR 👍

File: pkg/controller/jobframework/reconciler.go (hunk 7 above)
Comment (chengjoey) [reply pkg/controller/jobframework/reconciler.go]: done

File: pkg/controller/jobframework/reconciler.go [hunk 8]
```diff
@@ -1437,7 +1440,7 @@ func (r *JobReconciler) handleJobWithNoWorkload(ctx context.Context, job Generic
 	if err != nil {
 		return err
 	}
-	err = r.prepareWorkload(ctx, job, wl)
+	err = r.prepareWorkload(ctx, job, wl, nil)
```
Comment (tenzen-y) [inline pkg/controller/jobframework/reconciler.go]:
```suggestion
	err = r.prepareWorkload(ctx, job, wl, wl.Spec.Active)
```

Let's preserve the current Workload active parameter for future implementations.

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
JobFramework: Fixed a bug that allowed a deactivated workload to be activated.
```

File: pkg/controller/jobframework/reconciler.go (hunk 8 above)
Comment (chengjoey) [reply pkg/controller/jobframework/reconciler.go]: done

**Comment by tenzen-y** [comment]
@chengjoey Could you manually cherry-pick this commit to the release-0.14 branch?
You can use this script: https://github.com/kubernetes-sigs/kueue/blob/main/hack/cherry_pick_pull.sh.

**Comment by chengjoey** [comment]
> @chengjoey Could you manually cherry-pick this commit to the release-0.14 branch? You can use this script: https://github.com/kubernetes-sigs/kueue/blob/main/hack/cherry_pick_pull.sh.

#8445
