### PR TITLE
Fix flaky test issue

### LINKED ISSUE #1015: Flaky test: Queue controller Should update status when workloads are created
**What happened**:

The `Queue controller Should update status when workloads are created` is flaky:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1011/pull-kueue-test-integration-main/1683413143272820736

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by BinL233**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes `Flaky test: Queue controller Should update status when workloads are created`.
Uses `util.ExpectResourceFlavorToBeDeleted` to make sure that ResourceFlavors were deleted completely.
Put the deletion of ClusterQueue before the deletion of ResoueceFlavors to avoid the ResoueceFlavors deletion failure.
#### Which issue(s) this PR fixes:

Fixes #1015

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by kerthcet** [comment]
Track link: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1018/pull-kueue-test-e2e-main-1-26/1684507556703113216

**Comment by kerthcet** [comment]
Seems another flaky test, you can take time to fix it if you like @BinL233 anyway, this pr looks good to me.

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve

**Comment by BinL233** [comment]
> Seems another flaky test, you can take time to fix it if you like @BinL233 anyway, this pr looks good to me.

Sure. I will check it these days.

File: test/integration/controller/core/localqueue_controller_test.go [hunk 1]
```diff
@@ -66,11 +66,11 @@ var _ = ginkgo.Describe("Queue controller", func() {
 	})
 
 	ginkgo.AfterEach(func() {
+		gomega.Expect(util.DeleteLocalQueue(ctx, k8sClient, queue)).To(gomega.Succeed())
+		util.ExpectClusterQueueToBeDeleted(ctx, k8sClient, clusterQueue, true)
 		for _, rf := range resourceFlavors {
-			gomega.Expect(util.DeleteResourceFlavor(ctx, k8sClient, &rf)).To(gomega.Succeed())
+			util.ExpectResourceFlavorToBeDeleted(ctx, k8sClient, &rf, true)
```
Comment (mimowo) [inline test/integration/controller/core/localqueue_controller_test.go:72]: Question to check my understanding, is this because the ClusterQueue and RF use finalizers to clean up before actual deletion, so that, the actual deletion is asynchronous and we need to await until the Get for the objects returns "Not found".

**Review by mimowo — COMMENTED** [review]
/lgtm
just a question to double check my undestanding
/assign @alculquicondor
