### PR TITLE
Avoid unintentional patches to Quantity fields

### LINKED ISSUE #6966: Job stuck on "invalid patch" while being preempted (in unclucky cases involving Admission Checks & "round" RAM requests)
**Reproduction steps**:

1. (Optional) Modify the config of `kueue-controller-manager`: set `spec.container.args.--zap-log-level` to 10. \
   (This is just to have more logs available)

2. Use [this config](https://pastebin.com/9PzLqqc1) - basically 1 ClusterQueue with the following setup:

   | Flavor name | CPU quota | RAM quota | AdmissionCheck |
   |-------------|-----------|-----------|----------------|
   | `flavor-ac` | 0.75      | 5G        | `sample-prov`  |
   | `flavor-2`  | 0.5       | 5G        | -              |

   The two flavors are attached to disjoint sets of nodes (using node labels). \
   The nodes are large enough to fit the Jobs specified below, with a safe margin. \
   (The AC is technically there but no action from the autoscaler is actually needed - the node pool is already large enough).

3. Create, in order, the following 2 Jobs:

   | Config                                | Job name             | CPU request | RAM request | Priority |
   |---------------------------------------|----------------------|-------------|-------------|----------|
   | [YAML](https://pastebin.com/EHVZXiZN) | sample-job-1-_xxxxx_ | 0.5         | 220M        | -        |
   | [YAML](https://pastebin.com/j1Wr4CUv) | sample-job-2-_xxxxx_ | 750m        | 220M        | 1000     |

   After creating Job1, wait for its Pod to be running. Only then create Job2.

**What happened**:

After creating Job1: 
* there's one running Pod, scheduled on the AC flavor.

After creating Job2:
* Kueue assigns Job2 to `flavor-ac`, because `flavor-2` is not large enough.
* Kueue decides to preempt Job1 from `flavor-ac` to give place for Job2.
   
  Image

* **bug:** Job1 is _stuck on being preempted_. \
  The corresponding Workload remains in the state shown in the above screenshot indefinitely. (For at least 30 minutes).
  Looking at Kueue logs (level=10) reveals an error in patching the new preempted state:

  ```
  \"message\":\"Workload.kueue.x-k8s.io \\\"job-sample-job-1-9qkhm-dfd40\\\" is invalid: [
  status.admission.podSetAssignments: Invalid value: \\\"null\\\": admission.podSetAssignments in body must be of type array: \\\"null\\\",
  status.admission.clusterQueue: Required value, \\u003cnil\\u003e: Invalid value: \\\"null\\\":
  some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
  ]\"
  ```

  (a bit more logs available [here](https://pastebin.com/FziSEY1z))

* As a result, Job1 is never scheduled again. Also, Job2 is never scheduled at all, as it keeps waiting for a successful preemption of Job1:

  Image

   So, from the user's perspective, these 2 Jobs land in a **deadlock** state.

**What you expected to happen**:

Expected outcome:

* No errors thrown by the "preempting patch" for Job1.
* Job1 successfully preempted and then re-admitted on `flavor-2` (where it fits).
* Job2 successfully running on `flavor-ac`.

**Anything else we need to know?**:

* I'm observing this deterministically - but only in rare unlucky cases (see below).
* The expected outcome does indeed happen if we are more lucky - for example, if we do _either_ of the following:
  * detach the `AdmissionCheckStrategy` from `flavor-ac`, or
  * remove RAM request from Job1, or
  * change RAM request of Job1 from `220M` to `220Mi` (!)
* I have created an integration test (available [here](https://github.com/olekzabl/kueue/blob/38eef366ed6a3e6b64b08ab8c9800abc20d5cca3/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1848-L1977), to be soon turned into a PR) which reproduces this issue, and documents a long list of cases when it does / does not happen.
  For now, the **apparent trigger** is that: 

  * `flavor-ac` uses the Admission Check, and 
  * Job1 requests RAM, and 
  * the raw byte count of its RAM request is divisible by 1000, but not equal to 1000, and not divisible by 128 000.

  (Yes, I know it sounds unbelievably weird - but please look at the test cases - they just tell it).

**Environment**:
- Kubernetes version (use `kubectl version`):
  - Client Version: v1.33.4-dispatcher
  - Kustomize Version: v5.6.0
  - Server Version: v1.33.4-gke.1134000
- Kueue version (use `git describe --tags --dirty --always`): \
  Git N/A, I used the 0.13.4 release:
  ```
  kubectl apply --server-side -f https://github.com/kubernetes-sigs/kueue/releases/download/v0.13.4/manifests.yaml
  ```
- Cloud provider or hardware configuration: \
  GKE, and specifically:
  - cluster version = nodes version = 1.33.4-gke.1134000
  - node image type = `cos_containerd`
  - `flavor-ac` based on 4 nodes of type `e2-standard-2`, with GKE autoscaler set to "4-6 nodes"
  - `flavor-2` based on 2 nodes of type `n2-standard-2`
- OS (e.g: `cat /etc/os-release`): _[unable to find out right now]_
- Kernel (e.g. `uname -a`): _[unable to find out right now]_
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by brejman**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In case the job requests memory in decimal format (e.g. "1G"), the Workload's `status.admission.podSetAssignments[].resourceUsage.memory` is unintentionally patched due to Quantity round trip issues.

For example:

1. User requests 1G
2. 1G is converted to an internal representation (int64) as 1000000000
3. 1000000000 is converted to Quantity with BinarySI format
4. Quantity is sent to the API as "1000000000" because it isn't representable with a binary suffix
5. Quantity is read from the API as "1G" because lack of suffix is interpreted as DecimalSI format
6. The "1G" value is then sent to the API in a patch request intended for another field as a diff.

This PR changes no.3 to auto-detect the format and avoid unintentional diff.

While normally such diff shouldn't really matter other than adding some noise in managed fields, it hits https://github.com/kubernetes/kubernetes/issues/134902, which makes the workload impossible to evict.

#### Which issue(s) this PR fixes:

Fixes #6966 

#### Special notes for your reviewer:

This change makes it much more expensive to compute the Quantity.

I've considered a couple of alternatives:

1. Always use DecimalSI. This would fix the issue, but the Workload wouldn't use binary suffixes, e.g. "1Mi" would end up as "1048576"
2. Leave it be and wait for a fix to https://github.com/kubernetes/kubernetes/issues/134902. I think it's worth addressing this unintentional patch anyway, to avoid unintended consequences in the future.

#### Does this PR introduce a user-facing change?

```release-note
Fix eviction of jobs with memory requests in decimal format
```

### CODE REVIEW

**Comment by brejman** [comment]
/retest
Known issue https://github.com/kubernetes-sigs/kueue/issues/7390

**Comment by brejman** [comment]
Added integration test from #7217 @olekzabl

File: pkg/resources/requests.go [hunk 1]
```diff
@@ -108,15 +108,27 @@ func ResourceQuantity(name corev1.ResourceName, v int64) resource.Quantity {
...
 	}
 }
 
+// Ensures that the resulting Quantity roundtrips.
+// For example, 1000000 will be decimal (1M), while 1048576 will be binary (1Mi)
+func parseMaybeBinary(v int64) resource.Quantity {
+	binary := *resource.NewQuantity(v, resource.BinarySI)
+	final, err := resource.ParseQuantity(binary.String())
+	if err != nil {
+		// Should never happen
```
Comment (mimowo) [inline pkg/resources/requests.go:134]: log the error so that we can find out debugging that it went wrong

**Comment by mimowo** [comment]
@brejman please check locally (without putting all the cases here)  if this change addresses all the known problematic variants listed under the issue: https://github.com/kubernetes-sigs/kueue/issues/6966, in the PR: https://github.com/olekzabl/kueue/blob/38eef366ed6a3e6b64b08ab8c9800abc20d5cca3/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1848-L1977

File: pkg/resources/requests.go (hunk 1 above)
Comment (mimowo) [reply pkg/resources/requests.go:134]: Ah ok, this would never happen as the resource.Quantity `binary` was serialized by the library function, so it would need to be an internal serialization / deserialization bug in the library. I think this it is ok to assume this does not fail. In the worst case scenario we fallback to "binary" as before. 

Otherwise we would need to propagate the logger via 20 or so functions. So, I'm ok to avoid the complication for this case.

**Comment by mimowo** [comment]
/lgtm
/approve
/cherrypick release-0.14
/cherrypick release-0.13

Feel free to unhold if you confirm all cases are addressed by this change, as requested here: https://github.com/kubernetes-sigs/kueue/pull/7430#issuecomment-3472073650
/hold

File: pkg/resources/requests_test.go [hunk 2]
```diff
@@ -121,3 +123,76 @@ func TestCountIn(t *testing.T) {
...
+		"1M": {
+			resource: corev1.ResourceMemory,
+			value:    1000000,
+			expected: "1M",
+		},
+		"1.5M": {
+			resource: corev1.ResourceMemory,
+			value:    1500000,
+			expected: "1500k",
+		},
```
Comment (mimowo) [inline pkg/resources/requests_test.go:157]: Question, what it means "round-trips" in this context, since the serialization looks different: "1.5M" vs "1500k"?

**Comment by mimowo** [comment]
Actually, also have this question: https://github.com/kubernetes-sigs/kueue/pull/7430/files#r2480708605

**Comment by mimowo** [comment]
/lgtm cancel
Actually, I just tested locally - reverted the Implementation changes and the test is still passing, so seems like the test isn't really verifying the issue. Please double check that.

**Comment by mimowo** [comment]
Overall it would be good to have another pair on eyes on this, maybe @olekzabl or @PBundyra could review?

**Comment by brejman** [comment]
> Actually, I just tested locally - reverted the Implementation changes and the test is still passing, so seems like the test isn't really verifying the issue. Please double check that.

The change from no-suffix to decimal suffix doesn't seem to be detected as a diff anymore and I can't seem to reproduce the issue, even on older repo revisions, where I'm confident I was able to in the past. I'm taking a deeper look.

**Comment by brejman** [comment]
I checked again and it does reproduce on an old revision. #7369 makes it not reproducible. Still looking into why.

**Comment by mimowo** [comment]
interesting maybe the additional layer of convertion webhooks somehow fixes the issue by additional serialization/deserialization step. If this is confirmed your PR is still worth it, bevause it will allow to fix 0.13 and 0.14.

and also the issue would return when we move storage to v1beta2 and thus drop convertion webhooks again

File: pkg/resources/requests_test.go (hunk 2 above)
Comment (brejman) [reply pkg/resources/requests_test.go:157]: The test case name doesn't participate in the test logic. The initial value is int64 and not a string. I just found the 1.5 string easier to read, in particular for MiB.

I think if we parsed a string "1.5M", it wouldn't roundtrip and would serialize back to "1500k". But it's not a problem, because "1.5M" could only be provided as an input which is then converted to int64 before being sent to the API, and after that conversion it consistently roundtrips.

I updated the test case name

File: pkg/resources/requests_test.go [hunk 3]
```diff
@@ -121,3 +123,76 @@ func TestCountIn(t *testing.T) {
...
 	}
 }
+
+func TestResourceQuantityRoundTrips(t *testing.T) {
+	cases := map[string]struct {
+		resource corev1.ResourceName
+		value    int64
+		expected string
+	}{
+		"1": {
```
Comment (olekzabl) [inline pkg/resources/requests_test.go:133]: Can you also add 128k?
TBH I still don't know why this number played a special role in #6966 - but it did.

File: pkg/resources/requests.go [hunk 4]
```diff
@@ -108,15 +108,27 @@ func ResourceQuantity(name corev1.ResourceName, v int64) resource.Quantity {
...
-			return *resource.NewQuantity(v, resource.BinarySI)
+			return parseMaybeBinary(v)
 		}
 		return *resource.NewQuantity(v, resource.DecimalSI)
 	}
 }
 
+// Ensures that the resulting Quantity roundtrips.
+// For example, 1000000 will be decimal (1M), while 1048576 will be binary (1Mi)
+func parseMaybeBinary(v int64) resource.Quantity {
```
Comment (olekzabl) [inline pkg/resources/requests.go]: Nit: "parse" suggests it takes a string, which is not the case.

How about `canonicalizedBinaryQuantity(v)`?

File: pkg/resources/requests_test.go (hunk 3 above)
Comment (brejman) [reply pkg/resources/requests_test.go:133]: Good point, I added it to the test cases. 128k succeeds because it's the same as 125Ki, i.e. the number can be represented with a binary suffix. Only values that cannot be represented with a binary suffix but can be represented with a decimal suffix will cause the issue.

File: pkg/resources/requests.go (hunk 4 above)
Comment (brejman) [reply pkg/resources/requests.go]: You're right, using `parse` can be misleading. I'd like to encode in the name the fact that the result isn't necessarily using binary format. WDYT about "newQuantityWithBinaryPreference"?

**Comment by brejman** [comment]
/hold cancel

> @brejman please check locally (without putting all the cases here) if this change addresses all the known problematic variants listed under the issue: #6966, in the PR: https://github.com/olekzabl/kueue/blob/38eef366ed6a3e6b64b08ab8c9800abc20d5cca3/test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go#L1848-L1977

I patched the tests locally and changed the "stuck" expectation to "works". All test cases pass with the fix, and fail without it (checked before #7369). At HEAD the issue is not reproducible probably due to the conversion webhooks as noted previously.

PTAL

File: pkg/resources/requests.go (hunk 4 above)
Comment (brejman) [reply pkg/resources/requests.go]: We've converged to `newCanonicalQuantity(v, preferredFormat)`

**Comment by mimowo** [comment]
The cherrypicks need to be prepared "manually". The ./hack/cherry_pick_pull.sh script is useful for that
