### PR TITLE
Fix CrashLoopBackOff when using config/alpha-enabled.

### LINKED ISSUE #6663: CrashLoopBackOff when using config/alpha-enabled due to missing AdmissionFairSharing config
**What happened**:

When deploying Kueue with `config/alpha-enabled` (which uses `--feature-gates=AllAlpha=true`), the controller crashes with a nil pointer dereference resulting in CrashLoopBackOff

Reference thread : https://github.com/kubernetes-sigs/kueue/pull/6597#issuecomment-3220069521

The issue occurs because:
1. `AllAlpha=true` flag enables the AdmissionFairSharing feature
2. No `admissionFairSharing` configuration is provided in the default config (commented out in `kueue-manager-config` ConfigMap)
3. `cfg.AdmissionFairSharing = nil` (no config provided)
4. Scheduler calls `CalculateEntryPenalty(requests, nil)`
5. Crash at line 49: `afs.UsageSamplingInterval.Seconds()` when `afs` is nil

**What you expected to happen**:

The controller should start successfully when using `config/alpha-enabled`, either by:
- Providing a default configuration for AdmissionFairSharing when the feature is enabled
- Gracefully handling the nil configuration case

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy Kueue using alpha-enabled configuration:
   ```bash
   kubectl apply -k config/alpha-enabled
   ```
2. Observe controller pod in CrashLoopBackOff state:
   ```bash
   kubectl get pods -n kueue-system
   kubectl logs -n kueue-system -l app=kueue-controller-manager
   ```

**Anything else we need to know?**:

**Workarounds that work:**

1. Add nil check in `pkg/util/admissionfairsharing/admission_fair_sharing.go`:
   ```go
   func CalculateEntryPenalty(totalRequests corev1.ResourceList, afs *config.AdmissionFairSharing) corev1.ResourceList {
   	// Return empty penalty if no admission fair sharing config is provided
   	if afs == nil {
   		return corev1.ResourceList{}
   	}
   	alpha := CalculateAlphaRate(
   		afs.UsageSamplingInterval.Seconds(),
   		afs.UsageHalfLifeTime.Seconds(),
   	)
   	return resource.MulByFloat(totalRequests, alpha)
   }
   ```

2. Or provide explicit AdmissionFairSharing configuration in `kueue-manager-config` ConfigMap:
   ```yaml
   admissionFairSharing:
     usageHalfLifeTime: "168h"
     usageSamplingInterval: "5m"
     resourceWeights:
       cpu: 1
       memory: 1
   ```

This affects TrainJob v2 integration testing as the controller cannot start with alpha features enabled

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix CrashLoopBackOff when using config/alpha-enabled and missing AdmissionFairSharing config.

#### Which issue(s) this PR fixes:

Fixes #6663

#### Does this PR introduce a user-facing change?

```release-note
AFS: Fixed kueue-controller-manager crash when enabled AdmissionFairSharing feature gate without AdmissionFairSharing config.
```

### CODE REVIEW

**Comment by abhijeet-dhumal** [comment]
@mbobrovskyi @kannon92 
Please correct me here but as now we are setting `AllAlpha = true` resulting in AdmissionFairSharing feature enabled by default, is it ok to uncomment Admission Fair Sharing config here ? :  [kueue-manager-config](https://github.com/kubernetes-sigs/kueue/blob/0666f2ceb937a8f2d9198e381f9dd5cd19445d1a/charts/kueue/values.yaml#L164)
```
admissionFairSharing:
  usageHalfLifeTime: "168h"
  usageSamplingInterval: "5m"
  resourceWeights:
    cpu: 1
    memory: 1
```

**Comment by mbobrovskyi** [comment]
> @mbobrovskyi @kannon92 Please correct me here but as now we are setting `AllAlpha = true` resulting in AdmissionFairSharing feature enabled by default, is it ok to uncomment Admission Fair Sharing config here ? : [kueue-manager-config](https://github.com/kubernetes-sigs/kueue/blob/0666f2ceb937a8f2d9198e381f9dd5cd19445d1a/charts/kueue/values.yaml#L164)
> 
> ```
> admissionFairSharing:
>   usageHalfLifeTime: "168h"
>   usageSamplingInterval: "5m"
>   resourceWeights:
>     cpu: 1
>     memory: 1
> ```

This is an example. I don't think so we need to uncomment it.

File: pkg/util/admissionfairsharing/admission_fair_sharing.go [hunk 1]
```diff
@@ -45,6 +45,11 @@ func CalculateAlphaRate(sampling, halfLifeTime float64) float64 {
 }
 
 func CalculateEntryPenalty(totalRequests corev1.ResourceList, afs *config.AdmissionFairSharing) corev1.ResourceList {
+	// Return empty penalty if no admission fair sharing config is provided
+	if afs == nil {
+		return corev1.ResourceList{}
+	}
+
```
Comment (tenzen-y) [inline pkg/util/admissionfairsharing/admission_fair_sharing.go]: Should we disable entry penalty calculation at the scheduler level?

https://github.com/kubernetes-sigs/kueue/blob/ed155a674d27fd47c8d2d4a790ee920110ffa91b/pkg/scheduler/scheduler.go#L865

IIUC, when AFS is disabled, we can avoid entry penalty, right?

Comment (mbobrovskyi) [reply pkg/util/admissionfairsharing/admission_fair_sharing.go]: Done

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -623,7 +623,7 @@ func (s *Scheduler) admit(ctx context.Context, e *entry, cq *cache.ClusterQueueS
 	e.status = assumed
 	log.V(2).Info("Workload assumed in the cache")
 
-	if features.Enabled(features.AdmissionFairSharing) {
+	if s.admissionFairSharing != nil && features.Enabled(features.AdmissionFairSharing) {
```
Comment (tenzen-y) [inline pkg/scheduler/scheduler.go:626]: This is a follow-up comment. @mbobrovskyi Could you implement the following util function in https://github.com/kubernetes-sigs/kueue/tree/d442c2f6c9ae433c2dfeda305d51b04b513c73a4/pkg/util/admissionfairsharing, then check if AFS is enabled in everywhere?

```go
func EnabledAfs(afsConfig config.AdmissionFairSharing) bool {
    return afsConfig != nil && features.Enabled(features.AdmissionFairSharing)
}
```

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
AFS: Fixed kueue-controller-manager crash when enabled AdmissionFairSharing feature gate without AdmissionFairSharing config.
```
