### PR TITLE
Add health probe to bootstrap manager to fix liveness probe failures

### LINKED ISSUE #7844: [flaky e2e starup] "manager" in "kueue-controller-manager-59598f4b99-pc2h5" has restarted 1 times
/kind flake 

**What happened**:

failure on unrelated branch:  https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7827/pull-kueue-test-e2e-main-1-34/1992908904400424960

**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:

ci 
**Anything else we need to know?**:

```
End To End Suite: kindest/node:v1.34.0: [BeforeSuite] expand_less	34s
{Told to stop trying after 0.007s.
"manager" in "kueue-controller-manager-59598f4b99-pc2h5" has restarted 1 times failed [FAILED] Told to stop trying after 0.007s.
"manager" in "kueue-controller-manager-59598f4b99-pc2h5" has restarted 1 times
In [BeforeSuite] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/suite_test.go:73 @ 11/24/25 11:02:48.53
}
```
and I found the logs:

```
{"AdmissionFairSharing":true,"ConfigurableResourceTransformations":true,"DynamicResourceAllocation":false,"ElasticJobsViaWorkloadSlices":false,"FailureRecoveryPolicy":false,"FlavorFungibility":true,"FlavorFungibilityImplicitPreferenceDefault":false,"HierarchicalCohorts":true,"LendingLimit":true,"LocalQueueDefaulting":true,"LocalQueueMetrics":true,"ManagedJobsNamespaceSelectorAlwaysRespected":true,"MultiKueue":true,"MultiKueueAdaptersForCustomJobs":true,"MultiKueueAllowInsecureKubeconfigs":false,"MultiKueueBatchJobWithManagedBy":true,"MultiKueueClusterProfile":false,"ObjectRetentionPolicies":true,"PartialAdmission":true,"PrioritySortingWithinCohort":true,"PropagateBatchJobLabelsToWorkload":true,"ReclaimablePods":true,"SanitizePodSets":true,"TASBalancedPlacement":false,"TASFailedNodeReplacement":true,"TASFailedNodeReplacementFailFast":true,"TASProfileLeastFreeCapacity":false,"TASProfileMixed":true,"TASReplaceNodeOnPodTermination":true,"TopologyAwareScheduling":true,"VisibilityOnDemand":true,"WorkloadRequestUseMergePatch":false}}
2025-11-24T11:01:07.900702194Z stderr F 2025-11-24T11:01:07.900446511Z	LEVEL(-2)	setup	kueue/main.go:206	K8S Client	{"qps": 50, "burst": 100}
2025-11-24T11:01:07.984863254Z stderr F 2025-11-24T11:01:07.973859483Z	ERROR	setup	kueue/main.go:310	Skipping admission check controller setup: Provisioning Requests not supported (Possible cause: missing or unsupported cluster-autoscaler)	{"error": "no matches for kind \"ProvisioningRequest\" in version \"autoscaling.x-k8s.io/v1\""}
2025-11-24T11:01:07.984933095Z stderr F main.setupIndexes
2025-11-24T11:01:07.984938865Z stderr F 	/workspace/cmd/kueue/main.go:310
2025-11-24T11:01:07.984943295Z stderr F main.main
2025-11-24T11:01:07.984947545Z stderr F 	/workspace/cmd/kueue/main.go:251
2025-11-24T11:01:07.985049507Z stderr F runtime.main
2025-11-24T11:01:07.985056697Z stderr F 	/usr/local/go/src/runtime/proc.go:285
2025-11-24T11:01:07.990253588Z stderr F 2025-11-24T11:01:07.989909494Z	INFO	setup	kueue/main.go:453	Probe endpoints are configured on healthz and readyz
2025-11-24T11:01:07.990631542Z stderr F 2025-11-24T11:01:07.99045343Z	INFO	setup	cert/cert.go:90	Waiting for certificate generation to complete
2025-11-24T11:01:07.990963446Z stderr F 2025-11-24T11:01:07.990746704Z	INFO	setup	kueue/main.go:295	Starting manager
2025-11-24T11:01:07.991855927Z stderr F 2025-11-24T11:01:07.991582444Z	INFO	controller-runtime.metrics	server/server.go:208	Starting metrics server
```
which looks related

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

Add health probe to bootstrap manager to fix liveness probe failures. See: https://github.com/kubernetes-sigs/kueue/issues/7844#issuecomment-3579795581

#### Which issue(s) this PR fixes:

Fixes #7844 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/util/cert/cert.go [hunk 1]
```diff
@@ -53,11 +54,16 @@ func BootstrapCerts(kubeConfig *rest.Config, cfg config.Configuration) error {
 			BindAddress:    "0",
 			FilterProvider: filters.WithAuthenticationAndAuthorization,
```
Comment (mimowo) [inline pkg/util/cert/cert.go:55]: I'm wondering we should drop this in a follow up, this is not related to the bug. However, I think this was just copy-paste. We don't expose metrics in the bootstap manager (at least currently), so I think no need for the FilterProvider: WithAuthenticationAndAuthorization.

**Comment by mimowo** [comment]
/lgtm
/approve
Thank you 👍

File: pkg/util/cert/cert.go (hunk 1 above)
Comment (mimowo) [reply pkg/util/cert/cert.go:55]: Yeah, `BindAddress:    "0",` means disabling the server, so no need for `FilterProvider: filters.WithAuthenticationAndAuthorization,`, see: https://github.com/kubernetes-sigs/controller-runtime/blob/7e0e84b838402c1b9793d34cfadb99cfe8128313/pkg/metrics/server/server.go#L69

Comment (mimowo) [reply pkg/util/cert/cert.go:55]: In fact BindAddress=0 prevents reaching the FilterProvider code, see: https://github.com/kubernetes-sigs/controller-runtime/blob/7e0e84b838402c1b9793d34cfadb99cfe8128313/pkg/metrics/server/server.go#L119-L122

and only below we have: https://github.com/kubernetes-sigs/controller-runtime/blob/7e0e84b838402c1b9793d34cfadb99cfe8128313/pkg/metrics/server/server.go#L132-L139

so it is no-op, but confusing, please follow up to remove it @IrvingMg

File: pkg/util/cert/cert.go [hunk 2]
```diff
@@ -53,11 +54,16 @@ func BootstrapCerts(kubeConfig *rest.Config, cfg config.Configuration) error {
...
 		},
+		HealthProbeBindAddress: cfg.Health.HealthProbeBindAddress,
```
Comment (mbobrovskyi) [inline pkg/util/cert/cert.go:57]: /hold

I think we also need to add LivenessEndpointName.

Comment (mimowo) [reply pkg/util/cert/cert.go:57]: No need, it defaults to healthz, same as for the main manager

	// LivenessEndpointName, defaults to "healthz"
	// +optional
	LivenessEndpointName string `json:"livenessEndpointName,omitempty"`

Comment (IrvingMg) [reply pkg/util/cert/cert.go:57]: I'm not sure that we need it, it sets a default value if not defined. From docs:

```go
// Liveness probe endpoint name, defaults to "healthz"
    LivenessEndpointName string
```

Comment (mbobrovskyi) [reply pkg/util/cert/cert.go:57]: But what if user change?

Comment (mbobrovskyi) [reply pkg/util/cert/cert.go:57]: In main manager we are setting it https://github.com/epam/kubernetes-kueue/blob/d923e80795cab9913ee8c4103121843ac675d3ab/pkg/config/config.go#L76-L78.

Comment (IrvingMg) [reply pkg/util/cert/cert.go:57]: > But what if user change?

Yeah, that would be an issue, because I'm using default value for `bootstrapMgr.AddHealthzCheck("healthz", healthz.Ping)`.

Comment (mbobrovskyi) [reply pkg/util/cert/cert.go:57]: Yes, we should also change this as well. But probably in separate PR to don't mix changes.

Comment (IrvingMg) [reply pkg/util/cert/cert.go:57]: Okay, I can include this change in the follow up

Comment (mimowo) [reply pkg/util/cert/cert.go:57]: Yeah, thank you for pointing out! Yes indeed we also need to change pre-existing code as it does not respect LivenessEndpointName - in older versions it would also always use hardcoded healthz. 

So +1 to handle than in a follow up.
