### PR TITLE
[test][integration] Relax `CheckLatestEvent` to `CheckEventRecordedFor`.

### LINKED ISSUE #3144: [Flaky integration test] RayCluster controller Should reconcile RayClusters
/kind flake

**What happened**:
Flaky test on pull-kueue-test-integration-main:

RayCluster Controller Suite: [It] RayCluster controller Should reconcile RayClusters

```
{Timed out after 5.001s.
Expected
    <bool>: false
to be true failed [FAILED] Timed out after 5.001s.
Expected
    <bool>: false
to be true
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/controller/jobs/raycluster/raycluster_controller_test.go:192 @ 09/26/24 12:00:41.972
}
```

**What you expected to happen**:
No random failure.

**How to reproduce it (as minimally and precisely as possible)**:
Repeat the build: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/3143/pull-kueue-test-integration-main/1839271461601153024

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?
/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:
[test][integration] Relax `CheckLatestEvent` to `CheckEventRecordedFor`.

Instead of expecting that an event is recorded last, check that the event was recorded for a specific object.

#### Which issue(s) this PR fixes:

Fixes #3144

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
Is it fix for https://github.com/kubernetes-sigs/kueue/issues/3144?

**Comment by mbobrovskyi** [comment]
> > Is it fix for #3144?
> 
> It was not done for it specifically but it's fixing it. /cc @mbobrovskyi

Awesome. Thanks!

**Comment by trasc** [comment]
https://github.com/kubernetes-sigs/kueue/issues/3147 created for the e2e flake

**Comment by mimowo** [comment]
@mbobrovskyi would be great if you could provide the first review

File: pkg/util/testing/core.go [hunk 1]
```diff
@@ -69,6 +70,34 @@ func CheckLatestEvent(ctx context.Context, k8sClient client.Client,
...
+		item := events.Items[i]
+		if item.EventTime.Time.Before(t) {
+			lastIndexAfterTime = i + 1
+		}
+		if item.Reason == eventReason && item.Type == eventType && item.Note == eventNote {
+			return true, nil
+		}
+	}
+
+	return false, fmt.Errorf("event not found fater checking %d events", length-lastIndexAfterTime)
```
Comment (mbobrovskyi) [inline pkg/util/testing/core.go:98]:
```suggestion
	return false, fmt.Errorf("event not found after checking %d events", length-lastIndexAfterTime)
```

**Review by mbobrovskyi — COMMENTED** [review]
Overall LGTM.

File: pkg/util/testing/core.go [hunk 2]
```diff
@@ -69,6 +70,34 @@ func CheckLatestEvent(ctx context.Context, k8sClient client.Client,
 	return false, fmt.Errorf("mismatch with the latest event: got r:%v t:%v n:%v, reg %v", item.Reason, item.Type, item.Note, item.Regarding)
 }
 
+// CheckEventRecordedAfter checks if an event identified by eventReason, eventType, eventNote was recorded after the provided time t
+func CheckEventRecordedAfter(ctx context.Context, k8sClient client.Client,
```
Comment (mimowo) [inline pkg/util/testing/core.go:74]: Instead of relying on time, I suggest to have `CountMachingEventRecorded`, then in the tests record the current count, and await for the count to be incremented.

If we want to search for optimizations I would suggest to see if we could narrow down the List by namespace, or the target object.

File: pkg/util/testing/core.go [hunk 3]
```diff
@@ -69,6 +70,34 @@ func CheckLatestEvent(ctx context.Context, k8sClient client.Client,
...
+	if err := k8sClient.List(ctx, events, &client.ListOptions{}); err != nil {
+		return false, err
+	}
+
+	length := len(events.Items)
+	if length == 0 {
+		return false, errors.New("no events currently exist")
+	}
+
+	lastIndexAfterTime := 0
```
Comment (mimowo) [inline pkg/util/testing/core.go:87]: I don't like the optimization for the iteration over the list by timestamp. It adds complexity (I'm not sure we are even guaranteed that the events are sorted). Also, it does not improve performance in any meaningful way, because the full list needs to be fetched from API server (so serialized there), and deserialized in the client. Investigating potential flakes will eat us much more time than the potential gain.

File: pkg/util/testing/core.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/util/testing/core.go:74]: > Instead of relying on time, I suggest to have CountMachingEventRecorded, then in the tests record the current count, and await for the count to be incremented.

Honestly, I'm not sure if this is better than finding by time. I also think we might still encounter flaky tests in this case.

> If we want to search for optimizations I would suggest to see if we could narrow down the List by namespace, or the target object.

Yeah, I think it's make sense.

Comment (mbobrovskyi) [inline pkg/util/testing/core.go:74]: Do we need the previous implementation? It doesn't seem to be used anywhere.

Comment (mimowo) [reply pkg/util/testing/core.go:74]: Checking the counter before and after is a common approach, I don't see why this would have a potential to flake, but let me know if I'm missing something.

As for the time-based approach, the potential for flake I see is the optimization based on `lastIndexAfterTime`,  relies on the assumption that the list of events is sorted by time, I'm not sure this is always true. If we drop this check I think we can go ahead also with the approach.

Comment (mbobrovskyi) [reply pkg/util/testing/core.go:74]: > Checking the counter before and after is a common approach, I don't see why this would have a potential to flake, but let me know if I'm missing something.

Ah, I got your point. Yeah, it's make sense.

Comment (mimowo) [reply pkg/util/testing/core.go]: +1

Comment (trasc) [reply pkg/util/testing/core.go]: reworked

File: pkg/util/testing/core.go (hunk 3 above)
Comment (trasc) [reply pkg/util/testing/core.go]: reworked

File: pkg/util/testing/core.go [hunk 4]
```diff
@@ -47,26 +46,23 @@ func SingleContainerForRequest(request map[corev1.ResourceName]string) []corev1.
...
-		return true, nil
+	for i := range events.Items {
+		item := &events.Items[i]
+		if item.InvolvedObject.Name == ref.Name && item.Reason == eventReason && item.Type == eventType && item.Message == eventMessage {
+			return true, nil
+		}
 	}
-
-	return false, fmt.Errorf("mismatch with the latest event: got r:%v t:%v n:%v, reg %v", item.Reason, item.Type, item.Note, item.Regarding)
+	return false, fmt.Errorf("event not found fater checking %d events", len(events.Items))
```
Comment (mimowo) [inline pkg/util/testing/core.go:65]: Include the `eventReason`, `eventType`, `eventMessage` and namespace in the error message.

File: pkg/util/testing/core.go (hunk 2 above)
Comment (mimowo) [reply pkg/util/testing/core.go]: lgtm, left a nit about the error message in the other comment

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-integration-main

Due to https://github.com/kubernetes-sigs/kueue/issues/3149.

File: pkg/util/testing/core.go (hunk 4 above)
Comment (trasc) [reply pkg/util/testing/core.go]: done

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
