### PR TITLE
Fix running ginkgo when focus and label filter is used

### LINKED ISSUE #10087: e2e test filtering by labels does not work well  for kuberay (no tests executed when with ginkgo.FIt)
**What happened**:

I wanted to run kuberay test with focus, so I issue command
```
E2E_SKIP_REINSTALL=true GINKGO_ARGS="--label-filter=feature:kuberay" E2E_MODE=dev make kind-image-build test-e2e
```
and I selected one of the tests as focus by "ginkgo.FIt"

However, no test was run.

**What you expected to happen**:

I can run only a selected test using focus and the feature:kuberay label

**How to reproduce it (as minimally and precisely as possible)**:

```
E2E_SKIP_REINSTALL=true GINKGO_ARGS="--label-filter=feature:kuberay" E2E_MODE=dev make kind-image-build test-e2e
```
and I put in `ginkgo.FIt("Should run a rayjob with InTreeAutoscaling", func() {` on L198

results in 
```
Random Seed: 1774427525

Will run 0 of 88 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[ReportAfterSuite] Autogenerated ReportAfterSuite for --json-report --junit-report
autogenerated by Ginkgo
[ReportAfterSuite] PASSED [0.008 seconds]
------------------------------

Ran 0 of 88 Specs in 0.001 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 88 Skipped
PASS | FOCUSED

```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #10087 

#### Special notes for your reviewer:

Fix assisted with llm

I checked experimentally this works well:

```sh
GINKGO_ARGS="--repeat=1 --label-filter=feature:kuberay" E2E_MODE=dev make test-e2e
```
if the focus is enabled on a test with `ginkgo.FIt(`

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: hack/testing/e2e-common.sh [hunk 1]
```diff
@@ -1263,3 +1263,33 @@ EOF
...
+    eval "ginkgo_extra=($GINKGO_ARGS)"
+    rc=$?
+    (( had_noglob == 0 )) && set +f
+    (( rc == 0 )) || return "$rc"
+  fi
+
+  # Print the exact argv for troubleshooting quoting / flag-order issues.
+  printf 'running:' >&2
+  printf ' %q' "$GINKGO" run "${ginkgo_extra[@]}" "$@" >&2
+  printf '\n' >&2
```
Comment (mbobrovskyi) [inline hack/testing/e2e-common.sh:1292]:
```suggestion
  set -x
```

Can we use just `set -x` to enable debug mode? It should print executed commands

Comment (mimowo) [reply hack/testing/e2e-common.sh:1292]: but doesn't it leak outside the function? I think it would be weird if this function enables debug logging for all downstream functions

Comment (mbobrovskyi) [reply hack/testing/e2e-common.sh:1292]: I don't think so but to make sure we can set `set +x` after command.

Comment (kshalot) [reply hack/testing/e2e-common.sh:1292]: I think it will leak. That's why there's handling for `set -f` (globbing above).

But I'm wondering whether we could just run this function in a subshell (parentheses) instead of handling setting/unsetting. This would localize the setting to this function without having to manage it, but there might be some nuance with vars/envvars not being propagated.

Comment (mimowo) [reply hack/testing/e2e-common.sh:1292]: Actually I confirmed that it leaks, and so using `set +x` also leaks, see that output:


The "+" indicate the debug lines due to "set -x", and clearly that leaks outside the ginkgo helper.
```
validatingwebhookconfiguration.admissionregistration.k8s.io/kueue-validating-webhook-configuration serverside-applied
+ /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/hack/testing/../../bin/ginkgo run --repeat=0 --label-filter=feature:lws -procs=2 --junit-report=junit.xml --json-report=e2e.json --output-dir=/usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/run-test-e2e-singlecluster-1.35.0 -v ./test/e2e/singlecluster/...
Running Suite: End To End Suite: kindest/node:v1.35.0 - /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster
============================================================================================================================================
Random Seed: 1774618287

Will run 0 of 88 specs
Running in parallel across 2 processes
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[ReportAfterSuite] PASSED [0.010 seconds]
[ReportAfterSuite] Autogenerated ReportAfterSuite for --json-report --junit-report
autogenerated by Ginkgo
------------------------------

Ran 0 of 88 Specs in 0.080 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 88 Skipped


Ginkgo ran 1 suite in 3.829813788s
Test Suite Passed
Detected Programmatic Focus - setting exit status to 197
+ cleanup
+ '[' '!' -d /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/run-test-e2e-singlecluster-1.35.0 ']'
+ cluster_collect_artifacts kind ''
+ local name=kind
+ local kubeconfig=
+ kubectl_args=()
+ local -a kubectl_args
+ [[ -n '' ]]
+ kubectl config use-context kind-kind
Switched to context "kind-kind".
+ /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/hack/testing/../../bin/kind export logs /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/run-test-e2e-singlecluster-1.35.0 --name kind
Exporting logs for cluster "kind" to:
/usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/run-test-e2e-singlecluster-1.35.0
+ kubectl describe pods -n kueue-system
+ kubectl describe pods
+ e2e_should_delete_cluster
+ [[ dev != dev ]]
+ echo 'Keeping kind cluster '\''kind'\'' (E2E_MODE=dev).'
+ echo 'To delete it:'
+ echo '  kind delete clusters kind'
Keeping kind cluster 'kind' (E2E_MODE=dev).
To delete it:
  kind delete clusters kind
make: *** [Makefile-test.mk:183: run-test-e2e-singlecluster-1.35.0] Error 197
```

Using "set +x"  is also not ideal, because it leaks disabling debug, so if a developer runs `GINKGO_ARGS="--repeat=0 --label-filter=feature:lws" E2E_MODE=dev make SHELL=/bin/bash '.SHELLFLAGS=-x -c' test-e2e`, then using that command will disable debug

Comment (mimowo) [reply hack/testing/e2e-common.sh:1292]: > I think it will leak. That's why there's handling for `set -f` (globbing above).
> 
> But I'm wondering whether we could just run this function in a subshell (parentheses) instead of handling setting/unsetting. This would localize the setting to this function without having to manage it, but there might be some nuance with vars/envvars not being propagated.

Ok, I confirmed this works and does not leak:

```sh
run_e2e_ginkgo() (
  set -f
  set -x
  local ginkgo_extra=()
  local had_noglob=0
  local rc=0

  if [[ -n ${GINKGO_ARGS:-} ]]; then
    # Preserve the caller's globbing state. While reparsing GINKGO_ARGS we want
    # shell quoting to work, but we do not want '*' or '?' expanded to filenames.
    [[ $- == *f* ]] && had_noglob=1
    set -f
    eval "ginkgo_extra=($GINKGO_ARGS)"
    rc=$?
    (( had_noglob == 0 )) && set +f
    (( rc == 0 )) || return "$rc"
  fi

  "$GINKGO" run "${ginkgo_extra[@]}" "$@"
)
```
but the output looks quite messy:
```
+ ginkgo_extra=()
+ local ginkgo_extra
+ local had_noglob=0
+ local rc=0
+ [[ -n --repeat=0 --label-filter=feature:lws -procs=2 ]]
+ [[ efhuxB == *f* ]]
+ had_noglob=1
+ set -f
+ eval 'ginkgo_extra=(--repeat=0 --label-filter=feature:lws -procs=2)'
++ ginkgo_extra=(--repeat=0 --label-filter=feature:lws -procs=2)
+ rc=0
+ ((  had_noglob == 0  ))
+ ((  rc == 0  ))
+ /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/hack/testing/../../bin/ginkgo run --repeat=0 --label-filter=feature:lws -procs=2 --junit-report=junit.xml --json-report=e2e.json --output-dir=/usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/run-test-e2e-singlecluster-1.35.0 -v ./test/e2e/singlecluster/...
```
So, I think the tidy output from just "printf" is preferred. If someone is debugging a complex issue they could always use `make SHELL=/bin/bash '.SHELLFLAGS=-x -c' test-e2e`, but not strong view, it just seems overkill
