### PR TITLE
Fix Multikueue E2E script swallowing cluster creation errors and locking kubeconfig

### LINKED ISSUE #8983: [Flaky MultiKueue E2E] ERROR: unknown cluster
**Which test is flaking?**:

periodic-kueue-test-e2e-multikueue-release-0-15.Overall

**First observed in** (PR or commit, if known):

Periodic multikueue end to end tests.

**Link to failed CI job or steps to reproduce locally**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-multikueue-release-0-15/2019043147618717696

**Failure message or logs**:
```
ERROR: unknown cluster "kind-worker1"
ERROR: unknown cluster "kind-worker2"
ERROR: unknown cluster "kind-manager"
E0204 13:45:48.646569   29729 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.647444   29729 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.649390   29729 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.650429   29729 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.651226   29729 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.652047   29735 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0204 13:45:48.652873   29735 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.654823   29735 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.655587   29735 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.655755   29734 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.656652   29734 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.657437   29735 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0204 13:45:48.658617   29734 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.659342   29734 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.661264   29734 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0204 13:45:48.720866   29756 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.721947   29756 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.722839   29756 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.724717   29756 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.725077   29761 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.725412   29756 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.725881   29761 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0204 13:45:48.727372   29766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.727745   29761 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.728206   29766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.728422   29761 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.730089   29766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.730175   29761 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0204 13:45:48.730819   29766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0204 13:45:48.732669   29766 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by TapanManu**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:

If kind create cluster failed (e.g. due to OOM or network timeout), the script swallowed the background process error and continued running the Ginkgo suite against non-existent clusters. Additionally, concurrent kind delete commands in the cleanup phase caused a config.lock: file exists race condition, breaking local dev environments.

Fixes two issues:
1. Added a sequential wait loop after background cluster creation to ensure set -e instantly catches provisioning failures.

2. Made the cluster cleanup sequential to prevent kubeconfig lock collisions.

#### Which issue(s) this PR fixes:

Fixes #8983

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: hack/testing/e2e-multikueue-test.sh [hunk 1]
```diff
@@ -92,11 +92,12 @@ function kueue_deploy {
 trap cleanup EXIT
 startup 
 prepare_docker_images
-wait # for clusters creation
+for job in $(jobs -p); do wait "$job"; done # wait for clusters creation
```
Comment (mbobrovskyi) [inline hack/testing/e2e-multikueue-test.sh]: Is it failing on error? Should we do like this?

```suggestion
for job in $(jobs -p); do
    wait "$job" || { echo "Cluster creation failed!"; exit 1; }
done
```

Comment (TapanManu) [reply hack/testing/e2e-multikueue-test.sh]: thank you @mbobrovskyi , adding this message 👍🏻

File: hack/testing/e2e-multikueue-test.sh [hunk 2]
```diff
@@ -92,11 +92,12 @@ function kueue_deploy {
...
 startup 
 prepare_docker_images
-wait # for clusters creation
+for job in $(jobs -p); do wait "$job" || { echo "Cluster creation failed!"; exit 1; } done # wait for clusters creation
+
 kind_load "$MANAGER_KIND_CLUSTER_NAME" "$MANAGER_KUBECONFIG" &
 kind_load "$WORKER1_KIND_CLUSTER_NAME" "$WORKER1_KUBECONFIG" &
 kind_load "$WORKER2_KIND_CLUSTER_NAME" "$WORKER2_KUBECONFIG" &
-wait # for libraries installation
+for job in $(jobs -p); do wait "$job" || { echo "Library installation failed!"; exit 1; } done # wait for libraries installation
```
Comment (mbobrovskyi) [inline hack/testing/e2e-multikueue-test.sh]: /hold

Comment (mbobrovskyi) [reply hack/testing/e2e-multikueue-test.sh]:
```suggestion
for job in $(jobs -p); do wait "$job" || { echo ""Dependency installation failed!"; exit 1; } done # wait for libraries installation
```
Maybe like this?

Comment (mimowo) [reply hack/testing/e2e-multikueue-test.sh]: "Library installation failed" is pre-existing so no regression, but I agree""Dependency installation failed!" sounds better.

Comment (mimowo) [reply hack/testing/e2e-multikueue-test.sh]: Would you mind also untangling this one liner for readability as proposed here: https://github.com/kubernetes-sigs/kueue/pull/9604#discussion_r2868601794

File: hack/testing/e2e-multikueue-test.sh (hunk 1 above)
Comment (mimowo) [reply hack/testing/e2e-multikueue-test.sh]: Could you also untagle the one-liner to make it a bit more readable?

File: hack/testing/e2e-multikueue-test.sh (hunk 2 above)
Comment (TapanManu) [reply hack/testing/e2e-multikueue-test.sh]: sure 👍🏻

**Comment by mbobrovskyi** [comment]
Thank you!

/lgtm
/approve

**Comment by mbobrovskyi** [comment]
You can use /hack/cherry_pick_pull.sh for it.
