### PR TITLE
Fix JobSet integration with manageJobWithoutQueueName

### LINKED ISSUE #7649: Kueue is suspending JobSet that isn't supposed to manage
**What happened**:

When Kueue is configured like the following:

```
    manageJobsWithoutQueueName: true
    managedJobsNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: [ kube-system, kueue-system , test]
```
and a JobSet is created on the test namespace, which is a namespace not managed by Kueue, the jobs ends up suspended. However, the jobset is set to` suspended: false`.

```
$ kubectl get jobset -n test
NAME              TERMINALSTATE   RESTARTS   COMPLETED   SUSPENDED   AGE
sleep-job-x5ffx                   0                      false       16m
$ kubectl get job -n test
NAME                        STATUS      COMPLETIONS   DURATION   AGE
sleep-job-x5ffx-driver-0    Suspended   0/1                      16m
sleep-job-x5ffx-workers-0   Suspended   0/1                      16m
```

The jobs created for this jobset has the following events:
```
Events:
  Type    Reason            Age                      From                        Message
  ----    ------            ----                     ----                        -------
  Normal  SuccessfulDelete  10m                      job-controller              Deleted pod: sleep-job-x5ffx-driver-0-0-qm6jk
  Normal  SuccessfulCreate  10m                      job-controller              Created pod: sleep-job-x5ffx-driver-0-0-sth7c
  Normal  SuccessfulDelete  10m                      job-controller              Deleted pod: sleep-job-x5ffx-driver-0-0-sth7c
  Normal  Suspended         10m (x2 over 10m)        job-controller              Job suspended
  Normal  SuccessfulCreate  10m                      job-controller              Created pod: sleep-job-x5ffx-driver-0-0-qm6jk
  Normal  SuccessfulDelete  10m                      job-controller              Deleted pod: sleep-job-x5ffx-driver-0-0-v6n6j
  Normal  SuccessfulCreate  10m                      job-controller              Created pod: sleep-job-x5ffx-driver-0-0-v6n6j
  Normal  SuccessfulCreate  10m                      job-controller              Created pod: sleep-job-x5ffx-driver-0-0-fgl5w
  Normal  SuccessfulDelete  10m                      job-controller              Deleted pod: sleep-job-x5ffx-driver-0-0-fgl5w
  Normal  SuccessfulCreate  10m                      job-controller              Created pod: sleep-job-x5ffx-driver-0-0-47ndl
  Normal  SuccessfulDelete  10m                      job-controller              Deleted pod: sleep-job-x5ffx-driver-0-0-47ndl
  Normal  SuccessfulCreate  10m                      job-controller              Created pod: sleep-job-x5ffx-driver-0-0-4zjv9
  Normal  SuccessfulDelete  5m13s (x337 over 9m59s)  job-controller              (combined from similar events): Deleted pod: sleep-job-x5ffx-driver-0-0-b9drd
  Normal  Resumed           13s (x3203 over 10m)     job-controller              Job resumed
  Normal  Suspended         13s (x14709 over 10m)    batch/job-kueue-controller  Kueue managed child job suspended
```

No workload is created:
```
$ kubectl get workloads -A
No resources found
```

**What you expected to happen**:

Kueue wouldn't influence jobs that are skipped in the namespace specified at `managedJobsNamespaceSelector`.

**How to reproduce it (as minimally and precisely as possible)**:

Configure Kueue like the following:

```
    manageJobsWithoutQueueName: true
    managedJobsNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: [ kube-system, kueue-system , test]
```

Create the following jobset:
```
$ kubectl get jobset sleep-job-x5ffx -n test -o yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  creationTimestamp: "2025-11-13T17:25:26Z"
  generateName: sleep-job-
  generation: 1
  name: sleep-job-x5ffx
  namespace: test
  resourceVersion: "218271"
  uid: c9cd3c1e-624b-491c-98a2-fa1c3ef10779
spec:
  network:
    enableDNSHostnames: false
    publishNotReadyAddresses: true
    subdomain: some-subdomain
  replicatedJobs:
  - groupName: default
    name: workers
    replicas: 1
    template:
      metadata: {}
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata: {}
          spec:
            containers:
            - args:
              - 10s
              command:
              - sleep
              image: busybox
              name: sleep
              resources:
                requests:
                  cpu: "1"
                  memory: 200Mi
            restartPolicy: OnFailure
  - groupName: default
    name: driver
    replicas: 1
    template:
      metadata: {}
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata: {}
          spec:
            containers:
            - args:
              - 10s
              command:
              - sleep
              image: busybox
              name: sleep
              resources:
                requests:
                  cpu: "2"
                  memory: 200Mi
            restartPolicy: OnFailure
  startupPolicy:
    startupPolicyOrder: AnyOrder
  successPolicy:
    operator: All
  suspend: false
status:
  replicatedJobsStatus:
  - active: 0
    failed: 0
    name: workers
    ready: 0
    succeeded: 0
    suspended: 1
  - active: 0
    failed: 0
    name: driver
    ready: 0
    succeeded: 0
    suspended: 0
  restarts: 0
```
Check the jobs are suspended.

**Anything else we need to know?**:

When `manageJobsWithoutQueueName: true` is not specified, the jobs are not suspended as expected.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): v0.14.4, v0.13.9
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by MaysaMacedo**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

When `manageJobWithoutQueueName` is enabled and a namespace
is excluded from the namespace list to be managed by Kueue in the
`managedJobsNamespaceSelector` config, any asset without a queue name
created in that namespace should automatically be moved to running state and
not be managed by Kueue. This is not happening when the configuration of
`ManagedJobsNamespaceSelectorAlwaysRespected` is set to false. Let's fix
this issue by skipping the Kueue management of a job that doesn't match the
`managedJobsNamespaceSelector` and doesn't have a queue name defined.

#### Which issue(s) this PR fixes:

Fixes #7649

#### Does this PR introduce a user-facing change?

```release-note
Fix integration of `manageJobWithoutQueueName` and `managedJobsNamespaceSelector` with JobSet by ensuring that jobSets without a queue are  not managed by Kueue if are not selected by the  `managedJobsNamespaceSelector`.
```

### CODE REVIEW

**Comment by mimowo** [comment]
/assign @kannon92 
for first review pass

**Comment by kannon92** [comment]
Thanks for the tag. I will wait for this PR to not have WIP to review.

it looks like a legit test is failing so I think this is truly WIP atm.

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go [hunk 1]
```diff
@@ -88,6 +91,81 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					jobs := &batchv1.JobList{}
+					g.Expect(k8sClient.List(ctx, jobs, client.InNamespace(ns.Name))).To(gomega.Succeed())
+					for _, job := range jobs.Items {
+						g.Expect(job.Spec.Suspend).To(gomega.HaveValue(gomega.BeFalse()))
+						for _, job := range jobs.Items {
+							g.Expect(job.Status.Active).To(gomega.Equal(int32(1)))
+						}
+					}
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
```
Comment (mimowo) [inline test/e2e/customconfigs/managejobswithoutqueuename_test.go]: nit, I would give LongTimeout here to make sure it does not flake. Waiting for two Jobs to start may take a while if the

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go [hunk 2]
```diff
@@ -88,6 +91,81 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
...
+						},
+					).Obj()
+				util.MustCreate(ctx, k8sClient, newJobSet)
+			})
+
+			ginkgo.By("verifying that the jobs are not suspended", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					jobs := &batchv1.JobList{}
+					g.Expect(k8sClient.List(ctx, jobs, client.InNamespace(ns.Name))).To(gomega.Succeed())
+					for _, job := range jobs.Items {
```
Comment (mimowo) [inline test/e2e/customconfigs/managejobswithoutqueuename_test.go:146]: nit, `g.Expect(jobs.Items).To(gomega.HaveLen(2))`. Currently the assert will pass even if there are no Jobs created

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go [hunk 3]
```diff
@@ -88,6 +91,81 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
...
+							g.Expect(job.Status.Active).To(gomega.Equal(int32(1)))
+						}
+					}
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("verifying that the jobset is completed", func() {
+				gomega.Eventually(func(g gomega.Gomega) error {
+					createjobset := &v1alpha2.JobSet{}
+					gomega.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(newJobSet), createjobset)).To(gomega.Succeed())
```
Comment (mimowo) [inline test/e2e/customconfigs/managejobswithoutqueuename_test.go]:
```suggestion
					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(newJobSet), createjobset)).To(gomega.Succeed())
```

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go [hunk 4]
```diff
@@ -88,6 +91,81 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
...
+					if createjobset.Status.TerminalState == string(v1alpha2.JobSetCompleted) {
+						return nil
+					}
+					return errors.New("jobset is not completed")
```
Comment (mimowo) [inline test/e2e/customconfigs/managejobswithoutqueuename_test.go]:
```suggestion
					g.Expect(createjobset.Status.TerminalState).To(gomega.Equal(string(v1alpha2.JobSetCompleted)))
```

**Review by mimowo — COMMENTED** [review]
LGTM, just test nits

**Comment by mimowo** [comment]
/approve
Approve so that @kannon92 can stamp the final lgtm when the nits are addressed
/hold

**Comment by kannon92** [comment]
/lgtm

I think the CI is having some issues with the all the outages.

PR looks good so hopefully this will merge when things resolve themself.

/retest

**Comment by mimowo** [comment]
/cherrypick release-0.14
/cherrypick release-0.13
feel free to open the cherrypicks prs using the helper script hack/cherry_pick_pull.sh if this fails
