### PR TITLE
Fix workload slices when creation timestamps collide

### LINKED ISSUE #6161: [flaky integration test] Job with elastic jobs via workload-slices support when ElasticJobsViaWorkloadSlices is enabled when Job is opted in Should support job scale-down and scale-up
/kind flake

**What happened**:
failure on nighlty build: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-main/1948271619319271424
**What you expected to happen**:
no failures
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:

```
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/controller/jobs/job/job_controller_test.go:3211 with:
Expected
    <resource.Quantity>: {
        i: {value: 300, scale: -3},
        d: {Dec: nil},
        s: "300m",
        Format: "DecimalSI",
    }
to be equivalent to
    <resource.Quantity>: {
        i: {value: 200, scale: -3},
        d: {Dec: nil},
        s: "200m",
        Format: "DecimalSI",
    } failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/controller/jobs/job/job_controller_test.go:3211 with:
Expected
    <resource.Quantity>: {
        i: {value: 300, scale: -3},
        d: {Dec: nil},
        s: "300m",
        Format: "DecimalSI",
    }
to be equivalent to
    <resource.Quantity>: {
        i: {value: 200, scale: -3},
        d: {Dec: nil},
        s: "200m",
        Format: "DecimalSI",
    }
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/controller/jobs/job/job_controller_test.go:3212 @ 07/24/25 06:48:02.774
}
```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #6161

#### Special notes for your reviewer:

An alternative fix to https://github.com/kubernetes-sigs/kueue/pull/6194 proposed for #6161

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @ichekrygin

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -311,7 +311,7 @@ func (s *Scheduler) schedule(ctx context.Context) wait.SpeedSignal {
 		// Evict old workload-slice if any. Note: that oldWorkloadSlice is not nil only if
 		// this is a workload-slice enabled workload and there is an old slice to evict.
 		if features.Enabled(features.ElasticJobsViaWorkloadSlices) && oldWorkloadSlice != nil {
-			if err := s.replaceWorkloadSlice(ctx, oldWorkloadSlice.WorkloadInfo.ClusterQueue, e.Obj, oldWorkloadSlice.WorkloadInfo.Obj); err != nil {
+			if err := s.replaceWorkloadSlice(ctx, oldWorkloadSlice.WorkloadInfo.ClusterQueue, e.Obj, oldWorkloadSlice.WorkloadInfo.Obj.DeepCopy()); err != nil {
```
Comment (tenzen-y) [inline pkg/scheduler/scheduler.go:314]: Why do we need this deepcopy?

File: pkg/workloadslicing/workloadslicing.go [hunk 2]
```diff
@@ -125,8 +126,18 @@ func FindNotFinishedWorkloads(ctx context.Context, clnt client.Client, jobObject
...
+	replacedSlices := sets.New[workload.Reference]()
+	for _, w := range result {
+		if replacedKey := ReplacementForKey(&w); replacedKey != nil {
+			replacedSlices.Insert(*replacedKey)
+		}
+	}
+	// Filter out workloads with activated "Finished" condition.
+	return slices.DeleteFunc(result, func(w kueue.Workload) bool {
+		return replacedSlices.Has(workload.Key(&w))
 	}), nil
```
Comment (tenzen-y) [inline pkg/workloadslicing/workloadslicing.go]:
```suggestion
	return slices.DeleteFunc(list.Items, func(w kueue.Workload) bool {
		return ReplacementForKey(&w) == nil || apimeta.IsStatusConditionTrue(w.Status.Conditions, kueue.WorkloadFinished)
	}), nil
```

why do we need additional loops?

Comment (mimowo) [reply pkg/workloadslicing/workloadslicing.go]: Yes, I think we need a loop. The proposed code is not correct, imagine we have two active workloads: w1, and w2.
Here w2 has "replacementFor" w1. Now, we are looking which workload w3 should replace. We want to choose w2, as it is the only workload not indicated by "replacementFor" yet.

Comment (mimowo) [reply pkg/workloadslicing/workloadslicing.go]: I just pushed a new unit test TwoActiveWorkloadsSelectNotReplaced to demonstrate the scenario.

Comment (tenzen-y) [reply pkg/workloadslicing/workloadslicing.go]: Ah, I see. The list.Items contain both old and new WorkloadSlices.

In that case, couldn't we do the following?

```suggestion
	replacedSlices := sets.New[workload.Reference]()
	for _, wl := range list.Items {
		if replacedKey := ReplacementForKey(&wl); replacedKey != nil {
			replacedSlices.Insert(*replacedKey)
		}
	}
	return slices.DeleteFunc(list.Items, func(w kueue.Workload) bool {
		return replacedSlices.Has(workload.Key(&w)) || apimeta.IsStatusConditionTrue(w.Status.Conditions, kueue.WorkloadFinished)
	}), nil
```

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/scheduler/scheduler.go:314]: I resolved this one by myself.
In the FindNotFinishedWorkloads, we modify the WorkloadSlice.

In that case, I think that we should extract matched Workloads instead of removing items from original ones in FindNotFinishedWorkloads.

File: pkg/workloadslicing/workloadslicing.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/workloadslicing/workloadslicing.go]: https://github.com/kubernetes-sigs/kueue/pull/6203/files#r2236142599

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go:314]: Yeah, I copied it from the original PR, but I think it is not necessary for the flake. 

We can probably address it separately, but IIUC this is the reason:
- the function calls workloadslicing.Finish() with oldSlice, [here](https://github.com/kubernetes-sigs/kueue/blob/0a2277b044476aba895121ac49755b02ef4a7ca5/pkg/scheduler/scheduler.go#L845C28-L845C34).
- the "Finish" function adds the [Finished](https://github.com/kubernetes-sigs/kueue/blob/0a2277b044476aba895121ac49755b02ef4a7ca5/pkg/workloadslicing/workloadslicing.go#L102) condition to the in-memory object. If the request fails, then the in-memory object would remain modified wrongly.

Comment (mimowo) [reply pkg/scheduler/scheduler.go:314]: So, I actually think we need to DeepCopy to ensure it does not happen.

File: pkg/workloadslicing/workloadslicing.go (hunk 2 above)
Comment (mimowo) [reply pkg/workloadslicing/workloadslicing.go]: This will work too

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go:314]: Actually, when I revert DeepCopy it still flakes

File: pkg/workloadslicing/workloadslicing.go (hunk 2 above)
Comment (mimowo) [reply pkg/workloadslicing/workloadslicing.go]: Pushed according to the suggestion

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go:314]: TBH since it fixed the problem I would suggest to merge and follow up. 

The follow up is to fix the Patch status function so that the update function does not operate on the external object but on the local copy created just for the patch. 

I can try to fix today

Comment (mimowo) [reply pkg/scheduler/scheduler.go:314]: I think this issue just revealed a bigger issue with how we do patches, because they modify the external object. Now modifying external object is rarely critical, because most often they are used in controller Reconcile where controller runtime creates a copy just for lifetime of Reconcile, and in case of error we just return. In this case we update the in memory workload copy referenced by workload.Info.

Still, I believe we can improve our Patch functions and then just drop this extra DeepCopy

Comment (tenzen-y) [reply pkg/scheduler/scheduler.go:314]: The root cause for DeepCopy is the use of deletion from the input Workload approach.
So, we need to change the approach in the `FindNotFinishedWorkloads`.

But the changing approach goes beyond this PR scope.
So, let us try to do that in a follow-up PR.

**Comment by ichekrygin** [comment]
To clarify (after the PR merged): the use of `DeepCopy` is necessary, but it is **not related** to the workload slice `creationTimestamp` collision mentioned in the PR title.

The timestamp issue was a **separate edge-case**, observed during integration, where both the initial workload and its scaled-up successor were created within the same second (due to second-level precision). This led to incorrect sorting between the "old" and "new" slices.

The **reason for using `DeepCopy`** is to avoid a **race condition** between the scheduler and the workload controller, both of which may modify the **shared** workload object stored in the cache:

```go
clusterWorkloads[key] *workload.Info → workload.Info.Obj → *kueue.Workload
```

Without deep copying, both components could end up mutating the same underlying object, leading to inconsistent state and hard-to-debug side effects.
