### PR TITLE
TAS: fix computing assignment when multiple PodSets

### LINKED ISSUE #3494: TAS: pods remain suspended as topology assignment is invalid
**What happened**:

Pods for MPIJob remain suspended

**What you expected to happen**:

The topology assignment is correct for workers, pods get ungated.

**How to reproduce it (as minimally and precisely as possible)**:

I have repro, will share more details later.

based on the yaml
```yaml
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  generateName: pi
  labels:
    kueue.x-k8s.io/queue-name: tas-user-queue
spec:
  slotsPerWorker: 1
  runPolicy:
    suspend: true
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          annotations:
            kueue.x-k8s.io/podset-required-topology: "cloud.google.com/gce-topology-host"
        spec:
          containers:
          - image: mpioperator/mpi-pi:openmpi
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            command:
            - mpirun
            args:
            - -n
            - "2"
            - /home/mpiuser/pi
            resources:
              limits:
                cpu: 1
                memory: 1Gi
    Worker:
      replicas: 40
      template:
        metadata:
          annotations:
            kueue.x-k8s.io/podset-preferred-topology: "cloud.google.com/gce-topology-host"
        spec:
          containers:
          - image: mpioperator/mpi-pi:openmpi
            name: mpi-worker
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              limits:
                cpu: 1
                memory: 4Gi
```

**Anything else we need to know?**:

I see in status:
```yaml
status:
  admission:
    clusterQueue: tas-cluster-queue
    podSetAssignments:
    - count: 1
      flavors:
        cpu: tas-flavor
        memory: tas-flavor
      name: launcher
      resourceUsage:
        cpu: "1"
        memory: 1Gi
      topologyAssignment:
        domains:
        - count: 1
          values:
          - e2382b4746ceeed246a7dc78750ae29f
          - 9339de12ef53a7fad2d4b45ffadc8ac4
          - a38840ea668bd0baaea716ae16331daa
          - gke-tas-kueue-test-tas-node-pool-47374fa0-0czr
        levels:
        - cloud.google.com/gce-topology-block
        - cloud.google.com/gce-topology-subblock
        - cloud.google.com/gce-topology-host
        - kubernetes.io/hostname
    - count: 40
      flavors:
        cpu: tas-flavor
        memory: tas-flavor
      name: worker
      resourceUsage:
        cpu: "40"
        memory: 160Gi
      topologyAssignment:
        domains: []
        levels:
        - cloud.google.com/gce-topology-block
        - cloud.google.com/gce-topology-subblock
        - cloud.google.com/gce-topology-host
        - kubernetes.io/hostname
```
I have repro, working on fix.

It was reported first here: https://github.com/kubernetes-sigs/kueue/issues/3211#issuecomment-2458900114

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #3494

#### Special notes for your reviewer:

I reproduced the same issue for JobSet, so this is not specific to MPIJob. Any Job is affected with multiple PodSets requesting the same RF using the same topology.

The issue was the capacity for non-leaf nodes was counted twice. The newly added test fails on the main branch, the workload gets admitted by with empty assignment.

#### Does this PR introduce a user-facing change?

```release-note
Fix computing the topology assignment for workloads using multiple PodSets requesting the same
topology. In particular, it was possible for the set of topology domains in the assignment to be empty,
and as a consequence the pods would remain gated forever as the TopologyUngater would not have
topology assignment information.
```

### CODE REVIEW

File: pkg/cache/tas_flavor_snapshot.go [hunk 1]
```diff
@@ -344,6 +344,7 @@ func (s *TASFlavorSnapshot) fillInCounts(requests resources.Requests) {
 	lastLevelIdx := len(s.domainsPerLevel) - 1
 	for levelIdx := lastLevelIdx - 1; levelIdx >= 0; levelIdx-- {
 		for _, info := range s.domainsPerLevel[levelIdx] {
+			s.state[info.id] = 0
```
Comment (PBundyra) [inline pkg/cache/tas_flavor_snapshot.go:347]: Could we avoid reseting the `s.state` in lazy manner? Maybe we could add a dedicated function that would be called after building assignment for a podset

Comment (PBundyra) [reply pkg/cache/tas_flavor_snapshot.go:347]: Or even better, we could reset/initialize this `s.state` at the beginning of this function

Comment (mimowo) [reply pkg/cache/tas_flavor_snapshot.go]: Done  -the second option

**Comment by PBundyra** [comment]
Thanks
/lgtm
