### PR TITLE
Fix Pod finalizers for succeeded groups

### LINKED ISSUE #1898: Flaky E2E test for pod groups
**What happened**:

/kind flake

It seems that sometimes there is a lingering Pod with a finalizer.

```
Pod groups when Single CQ should allow to schedule a group of diverse pods

{Timed out after 30.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:300 with:
Expected
    <nil>: nil
to be a NotFound error failed [FAILED] Timed out after 30.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:300 with:
Expected
    <nil>: nil
to be a NotFound error
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:304 @ 03/25/24 17:25:47.542
}
```

**What you expected to happen**:

No flakiness

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1888/pull-kueue-test-e2e-main-1-29/1772312509823324160

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The initial attempt to clear finalizers after declaring a Workload as finished might fail partially. At this point, some succeeded pods might be gone, so the group can no longer be interpreted as finished. But we shouldn't be checking that again.

#### Which issue(s) this PR fixes:

Fixes #1898

#### Does this PR introduce a user-facing change?

```release-note
Fix Pods in Pod groups stuck with finalizers when deleted immediately after Succeeded
```

### CODE REVIEW

File: pkg/controller/jobframework/reconciler.go [hunk 1]
```diff
@@ -273,11 +273,8 @@ func (r *JobReconciler) ReconcileGenericJob(ctx context.Context, req ctrl.Reques
...
 
 	if wl != nil && apimeta.IsStatusConditionTrue(wl.Status.Conditions, kueue.WorkloadFinished) {
-		// Finalize the job if it's finished
-		if _, finished := job.Finished(); finished {
-			if err := r.finalizeJob(ctx, job); err != nil {
-				return ctrl.Result{}, err
-			}
+		if err := r.finalizeJob(ctx, job); err != nil {
+			return ctrl.Result{}, err
 		}
```
Comment (tenzen-y) [inline pkg/controller/jobframework/reconciler.go:278]: Since this PR, we always finalize the Job when the Job has WorkloadFinished condition.
So, is this workload-controller mechanism still needed?

https://github.com/kubernetes-sigs/kueue/blob/5023dd227e881936d4b2733d91a30c169426053b/pkg/controller/core/workload_controller.go#L158-L160

**Review by tenzen-y — COMMENTED** [review]
Basically, lgtm

File: pkg/controller/jobframework/reconciler.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/reconciler.go:278]: It still helps in the case of a rogue user manually deleting finalizers.

But I'm also never sure which cases we are missing when dealing with finalizers. So I prefer to keep it.

Comment (tenzen-y) [reply pkg/controller/jobframework/reconciler.go:278]: That makes sense.
Thank you for the clarification!
/lgtm

**Comment by alculquicondor** [comment]
Let's do a few runs

1/5 passed.

/test pull-kueue-test-integration-main
/test pull-kueue-test-e2e-main-1-29
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-27

**Comment by alculquicondor** [comment]
Oops, I put the `/cherry-pick` on the wrong PR. I'll close the new PR when it's created.

**Comment by alculquicondor** [comment]
2/5 passed.

/test pull-kueue-test-integration-main
/test pull-kueue-test-e2e-main-1-29
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-27

**Comment by alculquicondor** [comment]
3/5 passed.

/test pull-kueue-test-integration-main
/test pull-kueue-test-e2e-main-1-29
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-27

**Comment by alculquicondor** [comment]
4/5 passed.

/test pull-kueue-test-integration-main
/test pull-kueue-test-e2e-main-1-29
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-27
/hold cancel

**Comment by alculquicondor** [comment]
/release-note-edit

```release-note
Pod Integration: Fix Pods in Pod groups stuck with finalizers when deleted immediately after Succeeded
```
