### PR TITLE
Fix "should update workload TopologyAssignment when node fails" test time

### LINKED ISSUE #5435: The "should update workload TopologyAssignment when node fails" test takes 32s
**What would you like to be cleaned**:

This test takes >30s because we are waiting for [NodeFailureDelay](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/tas/constants.go#L29) =30s

See: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-main/1929423477341687808

I consider this technical debt we took during release, but we should follow up.

We should add an option to the nodeFailureReconciler code with the timeout, and minimal value should be passed for integration tests, say 10ms, when building the controllers for integration tests [here](https://github.com/kubernetes-sigs/kueue/blob/c5bbc5577b72a430b998d9d6991bba5ed1f9d445/test/integration/singlecluster/tas/suite_test.go#L91).

**Why is this needed**:

To do not waste 30s on every build unnecessarily.

### PR DESCRIPTION
**Pull request by pajakd**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #5435

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/util/util.go
Comment (tenzen-y) [inline test/util/util.go:1]: Is this related to the flake test fixes?
If not, could you open another PR?

Comment (mimowo) [reply test/util/util.go:1]: Actually, I think this is related, at least in the current form, because to use the `SetNodeCondition` function. With the new case added linter expects to use switch case.

File: test/util/util.go [hunk 1]
```diff
@@ -1072,20 +1072,23 @@ func DeactivateWorkload(ctx context.Context, c client.Client, key client.ObjectK
...
+		switch {
+		case condition == nil:
 			updatedNode.Status.Conditions = append(updatedNode.Status.Conditions, *newCondition)
 			changed = true
-		} else if condition.Status != newCondition.Status {
+		case condition.Status != newCondition.Status:
 			condition.Status = newCondition.Status
 			condition.LastTransitionTime = newCondition.LastTransitionTime
 			changed = true
+		case condition.LastTransitionTime != newCondition.LastTransitionTime:
```
Comment (mimowo) [inline test/util/util.go]: I would suggest to also check that `!newCondition.IsZero()`, otherwise we need to always remember to pass the LastTransitiontime to avoid overriding to zero.

File: test/util/util.go
Comment (mimowo) [reply test/util/util.go:1]: Hmm.  actually may not be needed indeed since we change the status - so I vote for separete PR.

Comment (pajakd) [reply test/util/util.go:1]: This change is not necessary to shorten the runtime of the test. It addresses the comment https://github.com/kubernetes-sigs/kueue/issues/5435#issuecomment-2929394769

I'll make a separate PR for it.

File: test/util/util.go (hunk 1 above)
Comment (pajakd) [reply test/util/util.go]: Done.

File: test/util/util.go
Comment (mimowo) [reply test/util/util.go:1]: Cool, so please align the PR titles

**Comment by mimowo** [comment]
/test pull-kueue-test-integration-baseline-main
this is known flake: https://github.com/kubernetes-sigs/kueue/issues/5395

**Comment by pajakd** [comment]
With the change the test takes 3s https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5440/pull-kueue-test-integration-baseline-main/1929500494951092224

image

File: test/util/util.go
Comment (pajakd) [reply test/util/util.go:1]: Opened a separate PR for the refactor https://github.com/kubernetes-sigs/kueue/pull/5446

Renamed this one to align with name of the issue.
