### PR TITLE
Fix customconfigs WaitForPodsReady E2E Tests.

### LINKED ISSUE #5358: [flaky test] WaitForPodsReady has a tiny Timeout and no RecoveryTimeout should evict and requeue workload when pods readiness timeout is surpassed
/kind flake

**What happened**:

failure on unrelated branch https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5357/pull-kueue-test-e2e-customconfigs-main/1927021441526534144

**What you expected to happen**:

no failure

**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:
```
End To End Custom Configs handling Suite: kindest/node:v1.32.3: [It] ManageJobsWithoutQueueName when manageJobsWithoutQueueName=true and LocalQueueDefaulting=false should suspend a job expand_less	25s
{Expected success, but got an error:
    <*errors.StatusError | 0xc0008a26e0>: 
    resourceflavors.kueue.x-k8s.io "default" already exists
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "resourceflavors.kueue.x-k8s.io \"default\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "default",
                Group: "kueue.x-k8s.io",
                Kind: "resourceflavors",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc0008a26e0>: 
    resourceflavors.kueue.x-k8s.io "default" already exists
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "resourceflavors.kueue.x-k8s.io \"default\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "default",
                Group: "kueue.x-k8s.io",
                Kind: "resourceflavors",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
In [BeforeEach] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/customconfigs/managejobswithoutqueuename_test.go:72 @ 05/26/25 15:27:15.647
```

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind flake
/kind failing-test

#### What this PR does / why we need it:
Fix customconfigs WaitForPodsReady E2E Tests.

#### Which issue(s) this PR fixes:

Fixes #5358

#### Special notes for your reviewer:
Originally, we updated the Kueue Configuration after creating the `ResourceFlavor`, `ClusterQueue`, and `LocalQueue` resources in `BeforeEach` block. However, this can lead to race conditions – especially when resources are being deleted and created, and the controller manager is restarted during that time. This may interrupt operations.

To avoid this, we should update the Kueue Configuration first, and only then create the resources.

Since `updateKueueConfiguration` is a slow operation, I’ve split each configuration update into a separate Describe block and moved the logic into the BeforeAll block. This approach will make it easier to extend and add new test cases in the future.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mykysha** [comment]
Thanks!
/lgtm

File: test/e2e/customconfigs/waitforpodsready_test.go [hunk 1]
```diff
@@ -99,284 +126,360 @@ var _ = ginkgo.Describe("WaitForPodsReady Job Controller E2E", ginkgo.Ordered, f
...
-				TerminationGracePeriod(1).
+	ginkgo.It("should evict and requeue workload when pods readiness timeout is surpassed", func() {
+		ginkgo.By("creating a suspended job so its pods never report Ready", func() {
+			job = testingjob.MakeJob("job-timeout", ns.Name).
+				Queue(kueue.LocalQueueName(lq.Name)).
+				Request(corev1.ResourceCPU, "2").
+				Parallelism(1).
 				Obj()
-			util.MustCreate(ctx, k8sClient, curlPod)
+			gomega.Expect(k8sClient.Create(ctx, job)).Should(gomega.Succeed())
```
Comment (tenzen-y) [inline test/e2e/customconfigs/waitforpodsready_test.go]:
```suggestion
			util.MustCreate(ctx, k8sClient, job)
```

Shouldn't we use the `util.MustCreate`?

**Comment by mimowo** [comment]
/approve
/cherrypick release-0.12
Thank you 👍

**Review by tenzen-y — COMMENTED** [review]
Overall LGTM, Thank you

Let me just confirm the main change on this PR.
Does this PR categorize the test cases by dedicated `ginkgo.Describe` instead of `ginkdo.When` so that we can avoid the race condition due to Kueue Config updating?

File: test/e2e/customconfigs/waitforpodsready_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/e2e/customconfigs/waitforpodsready_test.go]: Yep, we can. Let me update it everywhere.

Comment (tenzen-y) [reply test/e2e/customconfigs/waitforpodsready_test.go]: Thank you.
/lgtm
/hold cancel

**Comment by mbobrovskyi** [comment]
> Does this PR categorize the test cases by dedicated ginkgo.Describe instead of ginkdo.When so that we can avoid the race condition due to Kueue Config updating?

Yes. The main issue is that we create the `Namespace`, `LocalQueue`, `ClusterQueue`, and `ResourceFlavor` while also updating the Kueue configuration before restarting the `kueue-controller-manager`. This sequence can lead to race conditions, potentially causing data loss during the restart.

To address this, I propose creating all resources after restarting the `kueue-controller-manager`.

There are two possible solutions:

1. Use `updateKueueConfiguration` in a `Describe's` `BeforeEach` block—before creating `LocalQueue`, `ClusterQueue`, and `ResourceFlavor`.
2. Split the tests into separate `Describe` blocks and use `updateKueueConfiguration` in `BeforeAll`.

I believe the second solution is better. Since `updateKueueConfiguration` is a slow operation, running it in `BeforeAll` allows us to reuse the same configuration across multiple test cases. In the future, this will make it easier to extend tests without needing to restart the `kueue-controller-manager` unnecessarily, as long as the configuration remains the same.

File: test/e2e/customconfigs/waitforpodsready_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/e2e/customconfigs/waitforpodsready_test.go]: Done

**Comment by tenzen-y** [comment]
> > Does this PR categorize the test cases by dedicated ginkgo.Describe instead of ginkdo.When so that we can avoid the race condition due to Kueue Config updating?
> 
> Yes. The main issue is that we create the `Namespace`, `LocalQueue`, `ClusterQueue`, and `ResourceFlavor` while also updating the Kueue configuration before restarting the `kueue-controller-manager`. This sequence can lead to race conditions, potentially causing data loss during the restart.
> 
> To address this, I propose creating all resources after restarting the `kueue-controller-manager`.
> 
> There are two possible solutions:
> 
> 1. Use `updateKueueConfiguration` in a `Describe's` `BeforeEach` block—before creating `LocalQueue`, `ClusterQueue`, and `ResourceFlavor`.
> 2. Split the tests into separate `Describe` blocks and use `updateKueueConfiguration` in `BeforeAll`.
> 
> I believe the second solution is better. Since `updateKueueConfiguration` is a slow operation, running it in `BeforeAll` allows us to reuse the same configuration across multiple test cases. In the future, this will make it easier to extend tests without needing to restart the `kueue-controller-manager` unnecessarily, as long as the configuration remains the same.

That makes sense. Thank you for describing that.
