### PR TITLE
Include a Failed condition in Workloads

### LINKED ISSUE #1982: Include a Failed condition in Workloads
**What would you like to be added**:

A Failed condition when a Workload finishes because the corresponding Job failed, with a reason coming from the job integration.

Just a reason in the existing Finished condition could work, although that could lead to different job integrations choosing different strings for the common idea of "failed".

**Why is this needed**:

Improved visibility.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by vladikkuzn**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Replaces workload finished reason with succeeded and failed reasons

#### Which issue(s) this PR fixes:

Fixes #1982

#### Does this PR introduce a user-facing change?

```release-note
Workload finished reason replaced with succeeded and failed reasons
```

### CODE REVIEW

File: apis/kueue/v1beta1/workload_types.go [hunk 1]
```diff
@@ -326,6 +326,20 @@ const (
...
+	// WorkloadFinishedReasonSucceeded indicates that the workload finished successfully.
+	WorkloadFinishedReasonSucceeded = "Succeeded"
+
+	// WorkloadFinishedReasonFailed indicates that the workload finished with an error.
+	WorkloadFinishedReasonFailed = "Failed"
+
+	// WorkloadFinishedReasonAdmissionChecksRejected indicates that the workload was rejected by admission checks.
+	WorkloadFinishedReasonAdmissionChecksRejected = "AdmissionChecksRejected"
+
+	// WorkloadFinishedReasonOutOfSync indicates that the workload has finished because it was out of sync.
```
Comment (trasc) [inline apis/kueue/v1beta1/workload_types.go:339]:
```suggestion
	// WorkloadFinishedReasonOutOfSync indicates that the prebuilt workload is not in sync with its parent job.
```

File: apis/kueue/v1beta1/workload_types.go [hunk 2]
```diff
@@ -326,6 +326,20 @@ const (
 	WorkloadEvictedByDeactivation = "InactiveWorkload"
 )
 
+const (
+	// WorkloadFinishedReasonSucceeded indicates that the workload finished successfully.
+	WorkloadFinishedReasonSucceeded = "Succeeded"
+
+	// WorkloadFinishedReasonFailed indicates that the workload finished with an error.
```
Comment (trasc) [inline apis/kueue/v1beta1/workload_types.go:333]:
```suggestion
	// WorkloadFinishedReasonFailed indicates that the workload's job finished with an error.
```

File: pkg/controller/jobframework/interface.go [hunk 3]
```diff
@@ -44,7 +43,7 @@ type GenericJob interface {
 	// Finished means whether the job is completed/failed or not,
 	// condition represents the workload finished condition.
 	// Observed generation of the workload is set by the jobframework.
-	Finished() (condition metav1.Condition, finished bool)
+	Finished() (reason, message string, finished bool)
```
Comment (trasc) [inline pkg/controller/jobframework/interface.go:46]: Nit: How about instead of `reason` we use a `success` bool and pick the reason in the jobframework.

**Review by trasc — COMMENTED** [review]
Just some nits. otherwise LGTM.
/cc @alculquicondor

File: pkg/controller/jobframework/interface.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/interface.go:46]: +1. That would leave less room for custom implementation to return arbitrary strings that are hard to standardize.

**Review by trasc — COMMENTED** [review]
/lgtm

File: pkg/controller/jobs/job/job_controller.go [hunk 4]
```diff
@@ -289,18 +287,14 @@ func (j *Job) Finished() (metav1.Condition, bool) {
...
 
-	condition := metav1.Condition{
-		Type:               kueue.WorkloadFinished,
-		Status:             metav1.ConditionTrue,
-		Reason:             "JobFinished",
-		Message:            "Job finished successfully",
-		ObservedGeneration: j.Generation,
-	}
+	success = true
+	message = "Job finished successfully"
```
Comment (alculquicondor) [inline pkg/controller/jobs/job/job_controller.go:291]: instead, copy the message from the Succeeded or Failed condition. Apply the same recommendation for all the other job types.

If somehow the conditions have empty messages, then we can put these placeholder messages.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 5]
```diff
@@ -316,33 +316,29 @@ func (p *Pod) RestorePodSetsInfo(_ []podset.PodSetInfo) bool {
...
+	success = true
+	message = "Job finished successfully"
 
 	if !p.isGroup {
 		ph := p.pod.Status.Phase
 		finished = ph == corev1.PodSucceeded || ph == corev1.PodFailed
 
 		if ph == corev1.PodFailed {
-			condition.Message = "Job failed"
+			message = "Job failed"
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:329]: Copy the message from `p.pod.Status.Message` (also if Succeeded)

**Review by alculquicondor — COMMENTED** [review]
Let's go one step further :)

File: test/e2e/singlecluster/e2e_test.go [hunk 6]
```diff
@@ -207,7 +207,7 @@ var _ = ginkgo.Describe("Kueue", func() {
 						gomega.BeComparableTo(metav1.Condition{
 							Type:   kueue.WorkloadFinished,
 							Status: metav1.ConditionTrue,
-							Reason: "JobFinished",
+							Reason: kueue.WorkloadFinishedReasonFailed,
```
Comment (mimowo) [inline test/e2e/singlecluster/e2e_test.go:210]: I think it is better not to assert on the reason here, as I think it could flake. This is the reason we didn't assert for the message previously.

Comment (mimowo) [reply test/e2e/singlecluster/e2e_test.go:210]: It may flake because when the pods are running, and fully initialized, they handle SIGTERM with 0 exit code. So, sometimes the job with succeed.

If we want to make the assert, then we could use a non-zero termination code for the image, for example like [here](https://github.com/kubernetes-sigs/kueue/blob/944eea2f863a30c5077d8935d7489a42e8000ffa/test/e2e/singlecluster/pod_test.go#L195).

**Comment by mimowo** [comment]
You also need to adapt the MK tests, other than that LGTM. Thanks!

File: test/e2e/singlecluster/e2e_test.go (hunk 6 above)
Comment (mimowo) [reply test/e2e/singlecluster/e2e_test.go:210]: It should be guaranteed, because we have `BackoffLimit(0).`. So any pods failure results in Job failure.
