### PR TITLE
fixed flaky test

### LINKED ISSUE #674: Flaky test: Scheduler when Handling clusterQueue events Should re-enqueue by the update event of ClusterQueue
**What happened**:

This integration test failed in a PR:

```
Scheduler when Handling clusterQueue events Should re-enqueue by the update event of ClusterQueue
```

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/668/pull-kueue-test-integration-main/1643274100497453056

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mcariatm**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Flaky test: Scheduler when Handling clusterQueue events Should re-enqueue by the update event of ClusterQueue 
#### Which issue(s) this PR fixes:

Fixes #674

### CODE REVIEW

File: test/integration/scheduler/scheduler_test.go [hunk 1]
```diff
@@ -369,14 +369,19 @@ var _ = ginkgo.Describe("Scheduler", func() {
...
-				Name:           corev1.ResourceCPU,
-				NominalQuota:   resource.MustParse("6"),
-				BorrowingLimit: pointer.Quantity(resource.MustParse("0")),
-			}
-			gomega.Expect(k8sClient.Update(ctx, updatedCq)).Should(gomega.Succeed())
+			gomega.Eventually(func() error {
+				err := k8sClient.Get(ctx, types.NamespacedName{Name: cq.Name}, updatedCq)
+				if err != nil {
+					return err
+				}
```
Comment (tenzen-y) [inline test/integration/scheduler/scheduler_test.go:377]:
```suggestion
				gomega.Expect(k8sClient.Get(ctx, types.NamespacedName{Name: cq.Name}, updatedCq)).Should(gomega.Succeed)
```

Should we use the `gomega.Expect()` in the get operation?
IIUC, this operation should succeed every time.

**Review by tenzen-y — COMMENTED** [review]
@mcariatm Thank you for creating this PR!
/ok-to-test

File: test/integration/scheduler/scheduler_test.go (hunk 1 above)
Comment (mcariatm) [reply test/integration/scheduler/scheduler_test.go:377]: It is not in this test scope. It doesn't change test behavior.

Comment (tenzen-y) [reply test/integration/scheduler/scheduler_test.go:377]: Previously, line 372 verified whether the get operation succeeds once.

However, with this PR change,  this test passes even if the get operation failed.

So I think it would be better to mark this test as failed if the get operation failed.

Comment (mcariatm) [reply test/integration/scheduler/scheduler_test.go:377]: Here we test the scheduler functionality. Getting operation is relevant for API.

Comment (tenzen-y) [reply test/integration/scheduler/scheduler_test.go:377]: It sounds reasonable. I'm ok with this implementation.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve
