### PR TITLE
test: flaky localqueue integration stuck after termination fix

### LINKED ISSUE #5328: [Flaky test] Should be stuck in termination until admitted workloads finished running
/kind flake

**What happened**:

failure on unrelated branch: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5276/pull-kueue-test-integration-baseline-main/1925940251549765632

**What you expected to happen**:

no failure

**How to reproduce it (as minimally and precisely as possible)**:

ci

**Anything else we need to know?**:

```
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:539 with:
local_queue_status with status=True
Expected
    <float64>: 1
to equal
    <float64>: 0 failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:539 with:
local_queue_status with status=True
Expected
    <float64>: 1
to equal
    <float64>: 0
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/controller/core/clusterqueue_controller_test.go:919 @ 05/23/25 15:48:12.255
}
```

### PR DESCRIPTION
**Pull request by mykysha**
#### What type of PR is this?
/kind failing-test
/kind flake

#### What this PR does / why we need it:
Resolve the flaky behavior in the integration test

#### Which issue(s) this PR fixes:

Fixes #5328

#### Special notes for your reviewer:
Without the fix the issue was appearing once in ~200 runs, after the fix 3500 runs were made to verify that flakiness is resolved.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm

Awesome. Thank you so much!

File: test/util/util.go [hunk 1]
```diff
@@ -531,8 +531,8 @@ func ExpectLQByStatusMetric(lq *kueue.LocalQueue, status metav1.ConditionStatus)
 		if metrics.ConditionStatusValues[i] == status {
 			wantV = 1
 		}
-		metric := metrics.LocalQueueByStatus.WithLabelValues(lq.Name, lq.Namespace, string(s))
 		gomega.EventuallyWithOffset(1, func(g gomega.Gomega) {
+			metric := metrics.LocalQueueByStatus.WithLabelValues(lq.Name, lq.Namespace, string(s))
```
Comment (mbobrovskyi) [inline test/util/util.go:535]: /hold

Let me check something.

Comment (mbobrovskyi) [reply test/util/util.go:535]: I think it’s much better to wrap the entire `for` loop with `gomega.EventuallyWithOffset`.

Comment (mykysha) [reply test/util/util.go:535]: Agreed, updated

Comment (mbobrovskyi) [reply test/util/util.go:535]: Thank you!

/lgtm
/unhold

**Comment by mimowo** [comment]
/approve
thanks folks
/cherrypick release-0.12
/cherrypick release-0.11

**Review by tenzen-y — COMMENTED** [review]
Thank you

/lgtm
/approve
