### PR TITLE
Fixed "There are pending workloads due to capacity maxed by the admitted job" e2e test.

### LINKED ISSUE #2581: Flaky e2e: Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job
**What happened**:
```
{Timed out after 5.001s.
The matcher passed to Eventually returned the following error:
    <*errors.errorString | 0xc000916e80>: 
    NotFoundError expects an error
    {
        s: "NotFoundError expects an error",
    } failed [FAILED] Timed out after 5.001s.
The matcher passed to Eventually returned the following error:
    <*errors.errorString | 0xc000916e80>: 
    NotFoundError expects an error
    {
        s: "NotFoundError expects an error",
    }
In [AfterEach] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/visibility_test.go:133 @ 07/10/24 20:52:49.276
}
```

**What you expected to happen**:
No issue

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2553/pull-kueue-test-e2e-main-1-27/1811140041414545408
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2579/pull-kueue-test-e2e-main-1-29/1811357227194257408

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix "There are pending workloads due to capacity maxed by the admitted job" e2e test.

#### Which issue(s) this PR fixes:

Fixes #2581

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mszadkow** [comment]
How does this change help to fix the issue? I am curious :)

**Comment by mbobrovskyi** [comment]
Looks like missed removing jobs from nsB.

**Comment by mbobrovskyi** [comment]
But I think you right. We're creating jobs in `nsB` in the next cases but not in the failed.

File: test/e2e/singlecluster/visibility_test.go [hunk 1]
```diff
@@ -124,12 +124,19 @@ var _ = ginkgo.Describe("Kueue visibility server", func() {
 			})
 		})
 		ginkgo.AfterEach(func() {
-			gomega.Expect(k8sClient.Delete(ctx, lowPriorityClass)).To(gomega.Succeed())
-			gomega.Expect(k8sClient.Delete(ctx, midPriorityClass)).To(gomega.Succeed())
-			gomega.Expect(k8sClient.Delete(ctx, highPriorityClass)).To(gomega.Succeed())
-			gomega.Expect(util.DeleteObject(ctx, k8sClient, localQueueB)).Should(gomega.Succeed())
-			gomega.Expect(util.DeleteObject(ctx, k8sClient, localQueueA)).Should(gomega.Succeed())
 			gomega.Expect(util.DeleteAllJobsInNamespace(ctx, k8sClient, nsA)).Should(gomega.Succeed())
+			gomega.Expect(util.DeleteAllJobsInNamespace(ctx, k8sClient, nsB)).Should(gomega.Succeed())
```
Comment (mimowo) [inline test/e2e/singlecluster/visibility_test.go:128]: qq, a couple things are changed here:
- order of deletions, 
- added deletion of workloads
- retried delete for local queue and priorities

Do we actually know which of these changes is relevant for the fix?

**Comment by mimowo** [comment]
/lgtm 
but it would be nice to understand what is going on here as per https://github.com/kubernetes-sigs/kueue/pull/2608#discussion_r1677700448.

File: test/e2e/singlecluster/visibility_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/e2e/singlecluster/visibility_test.go:128]: Yes, this one 

```go
// Force remove workloads to be sure that cluster queue can be removed.
			gomega.Expect(util.DeleteWorkloadsInNamespace(ctx, k8sClient, nsA)).Should(gomega.Succeed())
			gomega.Expect(util.DeleteWorkloadsInNamespace(ctx, k8sClient, nsB)).Should(gomega.Succeed())
```

Comment (mimowo) [reply test/e2e/singlecluster/visibility_test.go:128]: Ah, reading this "But I think you right. We're creating jobs in nsB in the next test cases but not in the failed. So looks like kubernetes garbage collector didn't have time to remove workloads and we can't remove clusterqueue because workload exists." it seems the relevant are are actually: order of deletion, and force deletion of workloads.

Comment (mbobrovskyi) [reply test/e2e/singlecluster/visibility_test.go:128]: Yes, exactly.
