### PR TITLE
TAS: fix accounting for usage from TAS workloads using multiple resources

### LINKED ISSUE #3482: TAS: may report negative values of pods in messages for non-admitted workloads
**What happened**:

When a workload using preferred topology annotation cannot be admitted is sometimes reports negative number of pods in the status message of the workload.

**What you expected to happen**:

negative values of pods are never reported, it does not make sense.

**How to reproduce it (as minimally and precisely as possible)**:

I have a reproducible scenario, but it is yet not simplified enough to be included here. I will simplify and post.

Basically I create multiple jobs using preferred, and workload corresponding to the non-admitted job reports message like:
```
status:
  conditions:
  - lastTransitionTime: "2024-11-07T13:01:01Z"
    message: 'couldn''t assign flavors to pod set main: insufficient unused quota
      for cpu in flavor tas-flavor, 30 more needed, topology "gke-default" allows
      to fit only -18 out of 40 pod(s)'
    observedGeneration: 1
    reason: Pending
    status: "False"
    type: QuotaReserved
```

**Anything else we need to know?**:

It was reported first here: https://github.com/kubernetes-sigs/kueue/issues/3211#issuecomment-2458900114

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #3482

#### Does this PR introduce a user-facing change?

```release-note
Fix accounting for usage coming from TAS workloads using multiple resources. The usage was multiplied
by the number of resources requested by a workload, which could result in under-utilization of the cluster.
It also manifested itself in the message in the workload status which could contain negative numbers.
```

### CODE REVIEW

File: pkg/workload/workload.go [hunk 1]
```diff
@@ -261,15 +262,26 @@ func dropExcludedResources(input corev1.ResourceList, excludedPrefixes []string)
...
 	for _, ps := range i.TotalRequests {
 		if ps.TopologyRequest != nil {
-			result = append(result, ps.TopologyRequest.DomainRequests...)
+			psFlavors := sets.New[kueue.ResourceFlavorReference]()
+			for _, psFlavor := range ps.Flavors {
+				psFlavors.Insert(psFlavor)
+			}
+			for psFlavor := range psFlavors {
+				result[psFlavor] = append(result[psFlavor], ps.TopologyRequest.DomainRequests...)
+			}
```
Comment (hy00nc) [inline pkg/workload/workload.go:284]: Hi @mimowo thanks a lot for the quick fix. I'm trying to learn about TAS from your code and I have one question from a beginner's perspective (Maybe I'm asking some stupid question 😅 ):

If we append the same `DomainRequest` for all the flavors in a podset, could that mean we're multiplying the requests by the number of flavors, which can also cause discrepancy compared to the actual request? And if there are multiple flavors, how to we know which of the `DomainRequest` is taken from a specific flavor?

Comment (mimowo) [reply pkg/workload/workload.go:284]: Actually, currently we only support one flavor per TopologyRequest for PodSet. This is validated early [here]( https://github.com/kubernetes-sigs/kueue/blob/a672a315eace3eb745848cf2b9cae44156f39664/pkg/scheduler/flavorassigner/tas_flavorassigner.go#L81). This code I have added a bit more generic to accomodate multiple flavors used.

OTOH, it might be misleading, so I'm going to assume only one flavor is returned per topology request also here.

We have it planned to revisit the scenario of multiple flavors, under the [spreadsheet](https://docs.google.com/spreadsheets/d/1MXCjKZtAfqBTb61bJo46u7jIUqRIlu1NrYj1L8Xz-UU/). See "Investigate if possible to have two flavors for the same PodSet".

File: pkg/workload/workload.go [hunk 2]
```diff
@@ -261,15 +262,26 @@ func dropExcludedResources(input corev1.ResourceList, excludedPrefixes []string)
...
-	result := make([]TopologyDomainRequests, 0)
+func (i *Info) TASUsage() map[kueue.ResourceFlavorReference][]TopologyDomainRequests {
+	result := make(map[kueue.ResourceFlavorReference][]TopologyDomainRequests, 0)
 	for _, ps := range i.TotalRequests {
 		if ps.TopologyRequest != nil {
-			result = append(result, ps.TopologyRequest.DomainRequests...)
+			psFlavors := sets.New[kueue.ResourceFlavorReference]()
+			for _, psFlavor := range ps.Flavors {
+				psFlavors.Insert(psFlavor)
+			}
```
Comment (PBundyra) [inline pkg/workload/workload.go:281]:
```suggestion
			psFlavors := sets.New[kueue.ResourceFlavorReference](ps.Flavors)
```

File: pkg/workload/workload.go (hunk 1 above)
Comment (mimowo) [reply pkg/workload/workload.go]: On the second thought I cannot do it, because the TASUsage function returns usage for multiple flavors. Even though there is one flavor per PodSet we still may have multiple flavors used for workloads with multiple PodSets.

Still, I think in the current implementation the usage is accounted properly, the PodSets either:
1. use the same flavor, in that case each case the `DomainRequest` will be appended
2. use different flavors, in that case the usage will be accounted in the corresponding TAS flavors

File: pkg/cache/clusterqueue.go [hunk 3]
```diff
@@ -518,19 +518,23 @@ func (c *clusterQueue) reportActiveWorkloads() {
...
-				tasFlvCache.addUsage(tasUsage)
-			}
 		}
 		if m == -1 {
 			removeUsage(c, fr, q)
-			if tasFlvCache != nil {
-				tasFlvCache.removeUsage(tasUsage)
+		}
+	}
+	if features.Enabled(features.TopologyAwareScheduling) && wi.IsUsingTAS() {
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:529]: `IsUsingTAS` is just a performance optimization to avoid allocation inside `TASUsage`. I could move it to a dedicated PR, OTOH it is straighforward so I'm leaving it to reviewers.

cc @PBundyra

File: pkg/workload/workload.go [hunk 4]
```diff
@@ -261,15 +262,22 @@ func dropExcludedResources(input corev1.ResourceList, excludedPrefixes []string)
...
+}
+
 // TASUsage returns topology usage requested by the Workload
-func (i *Info) TASUsage() []TopologyDomainRequests {
-	if !features.Enabled(features.TopologyAwareScheduling) {
-		return nil
-	}
-	result := make([]TopologyDomainRequests, 0)
+func (i *Info) TASUsage() map[kueue.ResourceFlavorReference][]TopologyDomainRequests {
+	result := make(map[kueue.ResourceFlavorReference][]TopologyDomainRequests, 0)
```
Comment (PBundyra) [inline pkg/workload/workload.go:275]:
```suggestion
	result := make(map[kueue.ResourceFlavorReference][]TopologyDomainRequests, len(ps.Flavors))
```

Comment (mimowo) [reply pkg/workload/workload.go:275]: I don't have ps at this level

File: pkg/workload/workload.go (hunk 2 above)
Comment (mimowo) [reply pkg/workload/workload.go]: Ah, utilmaps.Values does not work as is does not deduplicate. We need "DistinctValues" (good that the new test picked it up), but not sure it warrants a new helper function. The suggestion from your comment does not compile. 
For now returning to how it was.

Comment (mimowo) [reply pkg/workload/workload.go:281]: reverted
