### PR TITLE
test: waitforpodsready e2e move curl-pod to test cases

### LINKED ISSUE #5302: [Flaky test]  WaitForPodsReady Job Controller E2E when WaitForPodsReady has a tiny Timeout and no RecoveryTimeout should evict and requeue workload when pods readiness timeout is surpassed
**What happened**:

Failure on unrelated branch https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5300/pull-kueue-test-e2e-customconfigs-main/1924833078941847552

**What you expected to happen**:

no failure

**How to reproduce it (as minimally and precisely as possible)**:

ci

**Anything else we need to know?**:
 
```
{Timed out after 133.023s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/e2e.go:355 with:
Unexpected error:
    <exec.CodeExitError>: 
    command terminated with exit code 28
    {
        Err: <*errors.errorString | 0xc000264040>{
            s: "command terminated with exit code 28",
        },
        Code: 28,
    }
occurred failed [FAILED] Timed out after 133.023s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/e2e.go:355 with:
Unexpected error:
    <exec.CodeExitError>: 
    command terminated with exit code 28
    {
        Err: <*errors.errorString | 0xc000264040>{
            s: "command terminated with exit code 28",
        },
        Code: 28,
    }
occurred
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/customconfigs/waitforpodsready_test.go:174 @ 05/20/25 14:34:09.404
}
```

### PR DESCRIPTION
**Pull request by mykysha**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Move curl pod management to test cases to ensure its availability and resolve test flakiness

#### Which issue(s) this PR fixes:

Fixes #5302

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mykysha** [comment]
After watching the resources in the failing test runs I've noticed that the curl-metrics pod was not failing, it was not present at all. Moving it's creation and cleanup to the `BeforeEach` and `AfterEach` blocks I've managed to have 50 consecutive test runs without failures, whereas previously I would be lucky to get 5

File: test/e2e/customconfigs/waitforpodsready_test.go [hunk 1]
```diff
@@ -95,12 +82,13 @@ var _ = ginkgo.Describe("WaitForPodsReady Job Controller E2E", ginkgo.Ordered, f
 		rf = testing.MakeResourceFlavor("default").Obj()
 		gomega.Expect(k8sClient.Create(ctx, rf)).Should(gomega.Succeed())
 
-		cq = testing.MakeClusterQueue("cq").
+		cq = testing.MakeClusterQueue("").
```
Comment (mimowo) [inline test/e2e/customconfigs/waitforpodsready_test.go:85]: Are these GenerateName changes required? If not I would propose to revert.

Comment (mykysha) [reply test/e2e/customconfigs/waitforpodsready_test.go:85]: Not specifically required, but they ensure that the metrics we check are for our specific and unique cq. Can revert, but I thought it should improve the test precision

Comment (mszadkow) [reply test/e2e/customconfigs/waitforpodsready_test.go:85]: Yeah, we lack that randomness in many tests. 
In result we e.g. can't run them in parallel.
I am all for it, however maybe keep them in separate PR.

Comment (mimowo) [reply test/e2e/customconfigs/waitforpodsready_test.go:85]: Let's revert if not required. If the PR helps it will never be totally clear to the future readers which change actually fixed the flake.

Also, it would not be consistent with other test suites. If we want to use genetated names for CQs we should do it more holistically across the codebase. I think code style consistency is improtant.

**Comment by mszadkow** [comment]
> After watching the resources in the failing test runs I've noticed that the curl-metrics pod was not failing, it was not present at all. Moving it's creation and cleanup to the `BeforeEach` and `AfterEach` blocks I've managed to have 50 consecutive test runs without failures, whereas previously I would be lucky to get 5

I saw that one too. 
It was not that it was off, missing some of the metrics, it was not present at all.
Nice catch and good that you found the solution

File: test/e2e/customconfigs/waitforpodsready_test.go (hunk 1 above)
Comment (mykysha) [reply test/e2e/customconfigs/waitforpodsready_test.go]: Reverted

Comment (mimowo) [reply test/e2e/customconfigs/waitforpodsready_test.go]: > In result we e.g. can't run them in parallel.

Good point. It would be a great preparatory task to enable running e2e tests in parallel, but let's make it across the codebase then and also for other resources (like Topologies).

**Comment by mimowo** [comment]
> Move curl pod management to test cases to ensure its availability and resolve test flakiness

could you maybe explain why this helps, and if you confirmed this locally?

**Comment by mykysha** [comment]
> could you maybe explain why this helps, and if you confirmed this locally?

As I've mentioned, I've ran the test 50 times with no failures, which is way more than it would be possible to without the changes.

As for "why?", I believe that having the pod to be in the same namespace as Kueue was resulting in it being sometimes taken away with the Kueue restarts defined in the tests. Moving the creation after the Kueue manager has been restarted seems to resolve the issue, as we create it when we have a running Kueue instance

**Comment by mimowo** [comment]
> As I've mentioned, I've ran the test 50 times with no failures, which is way more than it would be possible to without the changes.

Awesome 👍 

> As for "why?", I believe that having the pod to be in the same namespace as Kueue was resulting in it being sometimes taken away with the Kueue restarts defined in the tests. Moving the creation after the Kueue manager has been restarted seems to resolve the issue, as we create it when we have a running Kueue instance

I think namespaces generally should not matter for scheduling. 

One another possibility based on the symptomes, is that during the rolling restart of Kueue there are 2x more pods running for Kueue at the same time, and so the kube-scheduler may need to preempt the lower-priority pod. We could probably check that by inspecting the state of the curl-metrics pod at the beginning of each test.

The fact that you reproduced it locally, and run >50 times gives me enough evidence to go with the fix.

/lgtm
/approve
