### PR TITLE
Fixing a bug when provisioned condition is missing

### LINKED ISSUE #2149: Nil pointer dereference when handling the ProvisioningRequest's Accepted condition
**What happened**:
Kueue paniced because of nil pointer dereference. It tried to [dereference a nil pointer](https://github.com/kubernetes-sigs/kueue/blob/bd42edb21408a70d8e52c76ddc8713b78aedd966/pkg/controller/admissionchecks/provisioning/controller.go#L540), as the `autoscaling.Provisioned` condition was not present.

**What you expected to happen**:
Not panic

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by pajakd**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
When provisioning request has Accepted=True and Provisioned is nil we cannot dereference the Provisioned status. Fixing it by checking that Provisioned is explicitly set to False. Testing it by separately setting Accepted=True (leaving Provisioned empty) and only then changing Provisioned=False. 

#### Which issue(s) this PR fixes:

Fixes #2149

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug that there is a potential null pointer error in the provisioning request controller.
```

### CODE REVIEW

**Comment by PBundyra** [comment]
Lgtm, thanks!

**Comment by tenzen-y** [comment]
> There seems to be some flakiness in the `pull-kueue-test-integration-main`. It failed on the first run here. I saw some other runs earlier today that succeeded on the second try so I re-triggered.

Thanks. I opened a new issue: https://github.com/kubernetes-sigs/kueue/issues/2155

File: pkg/controller/admissionchecks/provisioning/controller.go [hunk 1]
```diff
@@ -531,12 +532,12 @@ func (c *Controller) syncCheckStates(ctx context.Context, wl *kueue.Workload, ch
...
 					updateCheckMessage(&checkState, apimeta.FindStatusCondition(pr.Status.Conditions, autoscaling.Provisioned).Message)
 				}
-			case prAccepted:
-				// we propagate the message from the provisioning request status into the workload
-				// this happens for provisioned = false (ETA updates) and also for provisioned = true
-				// to change to the "successfully provisioned" message after provisioning
+			case prAccepted && prProvisionedFalse:
+				// propagate the ETA update from the provisioning request into the workload
 				updated = updateCheckMessage(&checkState, apimeta.FindStatusCondition(pr.Status.Conditions, autoscaling.Provisioned).Message) || updated
 				updated = updateCheckState(&checkState, kueue.CheckStatePending) || updated
```
Comment (tenzen-y) [inline pkg/controller/admissionchecks/provisioning/controller.go:542]:
```suggestion
			case prAccepted:
				if provisionedCond := apimeta.FindStatusCondition(pr.Status.Conditions, autoscaling.Provisioned); provisionedCond != nil {
					// propagate the ETA update from the provisioning request into the workload
					updated = updateCheckMessage(&checkState, provisionedCond.Message) || updated
					updated = updateCheckState(&checkState, kueue.CheckStatePending) || updated
				}
```

It seems not to matter if the `Provisined` condition is False since the upon switch case `case prProvisioned:` already checked it, right?

File: pkg/controller/admissionchecks/provisioning/controller.go [hunk 2]
```diff
@@ -504,6 +504,7 @@ func (c *Controller) syncCheckStates(ctx context.Context, wl *kueue.Workload, ch
 
 			prFailed := apimeta.IsStatusConditionTrue(pr.Status.Conditions, autoscaling.Failed)
 			prProvisioned := apimeta.IsStatusConditionTrue(pr.Status.Conditions, autoscaling.Provisioned)
+			prProvisionedFalse := apimeta.IsStatusConditionFalse(pr.Status.Conditions, autoscaling.Provisioned)
```
Comment (tenzen-y) [inline pkg/controller/admissionchecks/provisioning/controller.go:507]:
```suggestion
```

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix a bug that there is a potential null pointer error in the provisioning request controller.
```

**Review by tenzen-y — COMMENTED** [review]
Thanks!
/lgtm
/approve
/cherry-pick release-0.6

**Comment by tenzen-y** [comment]
It seems that this bug is not in the release-0.6.

https://github.com/kubernetes-sigs/kueue/blob/0a69bb718c728bb5588b1d913921e3a524b05a44/pkg/controller/admissionchecks/provisioning/controller.go#L484-L512

/release-note-edit

```release-note
NONE
```
