### PR TITLE
[StatefulSet] Allow to change replicas without queue-name.

### LINKED ISSUE #3996: Kueue prevents scaling StatefulSets which aren't managed by Kueue
**What happened**:

Kueue prevents scaling StatefulSets which aren't managed by Kueue, and fails such attampts with the following error:
```
error: statefulsets.apps "nginx-statefulset" could not be patched: admission webhook "vstatefulset.kb.io" denied the request: spec.replicas: Invalid value: 4: field is immutable
```

**What you expected to happen**:

Kueue shouldn't block updating StatefulSets which aren't managed by it.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable the "statefulset" integration in the configmap (`kubectl edit configmap -nkueue-system -oyaml` and restart the kueue manager)
2. Create the "toy" StatefulSet without "queue-name": 

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.26
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
  serviceName: "nginx"
```
3. Attempt to update the StatefulSet spec.replicas from 3 to 4.

**Anything else we need to know?**:

The issue is present on 0.10 and 0.9.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Allow to change replicas  in StatefulSet without queue-name.

#### Which issue(s) this PR fixes:

Fixes #3996

#### Does this PR introduce a user-facing change?

```release-note
Fix bug that doesn't allow scaling StatefulSets which aren't managed by Kueue
```

### CODE REVIEW

**Comment by mimowo** [comment]
/hold
I need to first understand and align why we make this change. I see this needed for lws, but I expect we can instead make the skip decision based on the owner reference as we do already in other places.

**Comment by mimowo** [comment]
Also the current release note I think is not penetrable for users. It says what the code does but it does not say why a user would need to or what problem it solves from user perspective

**Comment by mimowo** [comment]
/reopen
Could you please @mbobrovskyi continue on the PR? I think it fixes a very important issue for 0.10:  https://github.com/kubernetes-sigs/kueue/issues/3996. Let me review the code details as I now understand the purpose.

File: pkg/controller/jobs/statefulset/statefulset_webhook.go [hunk 1]
```diff
@@ -142,21 +142,23 @@ func (wh *Webhook) ValidateUpdate(ctx context.Context, oldObj, newObj runtime.Ob
...
-	// Allow only scale down to zero and scale up from zero.
-	// TODO(#3279): Support custom resizes later
-	if newReplicas != 0 && oldReplicas != 0 {
-		allErrs = append(allErrs, apivalidation.ValidateImmutableField(
-			newStatefulSet.Spec.Replicas,
-			oldStatefulSet.Spec.Replicas,
-			replicasPath,
-		)...)
-	}
+	if newQueueName != "" {
```
Comment (mimowo) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go:145]: This covers 90% of cases. However, ideally, even if the StatefulSet has queue-name, but the owner is already managed by Kueue, then we don't do the validation. 

It is more of a corner case, but this could matter for the LWS integration or AppWrapper. 

Since this is a corner case I'm on a fence. I'm ok to merge as is, but maybe try to add the check @mbobrovskyi ?

Comment (mimowo) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go:145]: Maybe we introduce a helper function `isManagedByKueue`, and do both checks?
```
if parent managed by Kueue then 
 return false
else if hasQueueName
  return true
 return false
```

**Comment by mimowo** [comment]
> Also the current release note I think is not penetrable for users. It says what the code does but it does not say why a user > would need to or what problem it solves from user perspective. At least I'm puzzled by what is the user observable issue.

Sorry for the comment, in retrospect, I think the release note is good. Maybe we can just slightly tweak it:
```
Fix the bug that prevented scaling StatefulSets which aren't managed by Kueue when the "statefulset" integration is enabled.
```

**Comment by mimowo** [comment]
/hold cancel
I have a good grasp of the issue now. I think the only remaining remark is how to formulate the check. My proposal would be to first exclude StatefulSets which are owned by another CRD managed by Kueue as in the [comment](https://github.com/kubernetes-sigs/kueue/pull/3991#discussion_r1920019074), but I think this is not a blocking scenario here.

**Comment by mimowo** [comment]
/lgtm
/approve
I tested manually e2e and it solves https://github.com/kubernetes-sigs/kueue/issues/3996. Thanks!

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Fix the bug that prevented scaling StatefulSets which aren't managed by Kueue when the "statefulset" integration is enabled.
```
