### PR TITLE
TAS: fix topology assignment for the RayJob's submitter Job

### LINKED ISSUE #3716: TAS: Implement e2e tests for RayJob with TAS
**What would you like to be added**:
E2e tests for RayJob with TAS

**Why is this needed**:

Discussed here as well: https://github.com/kubernetes-sigs/kueue/pull/3704#discussion_r1866116694

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix the bug which didn't respect the TAS annotations on the template for the Ray submitter Job.
We needed a sanity check e2e test that proves RayJob support with TAS.

#### Which issue(s) this PR fixes:

Fixes #3716 

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug which didn't respect the TAS annotations on the template for the Ray submitter Job.
```

### CODE REVIEW

**Comment by mszadkow** [comment]
@gabesaba it's rebased and ready for review

**Comment by gabesaba** [comment]
/unassign

As I won't be able to take a look until next week

**Comment by mimowo** [comment]
/retitle TAS: fix topology assignment for the RayJob's submitter Job

**Comment by mimowo** [comment]
/remove-kind feature
/kind bug
@mszadkow please update also PR description to say "/kind bug"

File: pkg/controller/jobs/rayjob/rayjob_controller.go [hunk 1]
```diff
@@ -144,11 +144,16 @@ func (j *RayJob) PodSets() ([]kueue.PodSet, error) {
...
+			Count:    1,
+			Template: *getSubmitterTemplate(j),
 		}
 
-		submitterJobPodSet.Template = *getSubmitterTemplate(j)
+		// Create the TopologyRequest for the Submitter Job PodSet, based on the annotations
+		// in rayJob.Spec.SubmitterPodTemplate, which can be specified by the user.
+		if jobframework.IsTopologyRequestFound(&submitterJobPodSet.Template.ObjectMeta) {
+			submitterJobPodSet.TopologyRequest = jobframework.PodSetTopologyRequest(&j.Spec.SubmitterPodTemplate.ObjectMeta, nil, nil, nil)
+		}
```
Comment (mimowo) [inline pkg/controller/jobs/rayjob/rayjob_controller.go:156]:
```suggestion
   submitterJobPodSet.TopologyRequest = jobframework.PodSetTopologyRequest(&submitterJobPodSet.Template.ObjectMeta, nil, nil, nil)
```
why not just like this? The `PodSetTopologyRequest` function returns nil if there are not TAS annotations, so it should be safe to call without the extra "if". If this is the case then drop `IsTopologyRequestFound`

File: test/e2e/tas/rayjob_test.go [hunk 2]
```diff
@@ -0,0 +1,264 @@
...
+			Obj()
+		gomega.Expect(k8sClient.Create(ctx, clusterQueue)).Should(gomega.Succeed())
+		util.ExpectClusterQueuesToBeActive(ctx, k8sClient, clusterQueue)
+
+		localQueue = testing.MakeLocalQueue("local-queue", ns.Name).ClusterQueue(clusterQueue.Name).Obj()
+		gomega.Expect(k8sClient.Create(ctx, localQueue)).Should(gomega.Succeed())
+		util.ExpectLocalQueuesToBeActive(ctx, k8sClient, localQueue)
+	})
+	ginkgo.AfterEach(func() {
+		gomega.Expect(util.DeleteAllMPIJobsInNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:80]: Why DeleteAllMPIJobsInNamespace? This seems having nothing to do with RayJob

File: test/e2e/tas/rayjob_test.go [hunk 3]
```diff
@@ -0,0 +1,264 @@
...
+		gomega.Expect(util.DeleteNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
+		util.ExpectObjectToBeDeleted(ctx, k8sClient, clusterQueue, true)
+		util.ExpectObjectToBeDeleted(ctx, k8sClient, tasFlavor, true)
+		util.ExpectObjectToBeDeleted(ctx, k8sClient, topology, true)
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:84]: IIRC we should ensure all the pods are also deleted in the AfterEach to make sure they don't occupy the nodes affter tests. PTAL how this is done for other tests. cc @mbobrovskyi

File: test/e2e/tas/rayjob_test.go [hunk 4]
```diff
@@ -0,0 +1,264 @@
...
+			ginkgo.By("verify the submitter pod topology annotation", func() {
+				domain, level := readTopologyAnnotationFromRayJobSubmitterPod(pods.Items)
+				gomega.Expect(domain).Should(gomega.Equal(kueuealpha.PodSetRequiredTopologyAnnotation))
+				gomega.Expect(level).Should(gomega.Equal(testing.DefaultBlockTopologyLevel))
+			})
+		})
+	})
+})
+
+func readRankAssignmentsFromRayJobWorkerPods(pods []corev1.Pod) map[string]int {
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:238]: This name is very confusing. Let's just return the set of used nodes. Maybe "readAssignedNodes", which just returns the set of ".spec.NodeName"'s used by the worker pods.

File: test/e2e/tas/rayjob_test.go [hunk 5]
```diff
@@ -0,0 +1,264 @@
...
+					g.Expect(rayjob.Spec.Suspend).Should(gomega.BeFalse())
+				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			pods := &corev1.PodList{}
+			ginkgo.By("ensure all pods are created", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.List(ctx, pods, client.InNamespace(rayjob.Namespace))).To(gomega.Succeed())
+					g.Expect(pods.Items).Should(gomega.HaveLen(numPods))
+					// timeout is super long to ensure all cluster pods are up and running - rayimage takes long time to load and then to sync with head
```
[the remark this answers is not in the document]
Comment (mimowo) [reply test/e2e/tas/rayjob_test.go:202]: Also, how do we solve this issue for MultiKueue Ray tests? I didn't notice the very long timeout used there, do we pre-load the image there?

File: test/e2e/tas/rayjob_test.go (hunk 2 above)
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:80]: right, my mistake it should clear all ray jobs

File: test/e2e/tas/rayjob_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:202]: Oh no, we have the same issue there that this image is big and it's not about loading the image (which is preloaded).
Look here in mk e2e - https://github.com/kubernetes-sigs/kueue/blob/398c74d105743af8a3ad0d660323e5fdbfaf6e30/test/e2e/multikueue/e2e_test.go#L796

File: test/e2e/tas/rayjob_test.go (hunk 3 above)
Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:84]: this will be done by this: DeleteAllRayJobsInNamespace

File: test/e2e/tas/rayjob_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply test/e2e/tas/rayjob_test.go]: I see, please introduce `VeryLongTimeout=3min` for that rather than 5*time.LongTimeout ( which is hard to find), or StartupTimeout, which does not express the intention. it is ok to say StartupTime=VeryLongTimeout.

File: test/e2e/tas/rayjob_test.go [hunk 6]
```diff
@@ -0,0 +1,239 @@
...
+			ginkgo.By("verify the assignment of pods are as expected with rank-based ordering", func() {
+				gomega.Expect(k8sClient.List(ctx, pods, client.InNamespace(ns.Name))).To(gomega.Succeed())
+				workersAssignedNodes := readWorkersAssignedNodes(pods.Items)
+				gomega.Expect(workersAssignedNodes).Should(gomega.HaveLen(workerReplicas))
+			})
+		})
+	})
+})
+
+func readWorkersAssignedNodes(pods []corev1.Pod) map[string]int {
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:227]: Hm, actually can we make the assert more generic? Accept the type as a parameter. Then assert for all 3 roles (call this function 3 times and assert on the outputs).

File: test/e2e/tas/rayjob_test.go [hunk 7]
```diff
@@ -0,0 +1,239 @@
...
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.List(ctx, pods, client.InNamespace(ns.Name), listOpts)).To(gomega.Succeed())
+					g.Expect(pods.Items).Should(gomega.HaveLen(numPods))
+				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("verify the assignment of pods are as expected with rank-based ordering", func() {
+				gomega.Expect(k8sClient.List(ctx, pods, client.InNamespace(ns.Name))).To(gomega.Succeed())
+				workersAssignedNodes := readWorkersAssignedNodes(pods.Items)
+				gomega.Expect(workersAssignedNodes).Should(gomega.HaveLen(workerReplicas))
```
Comment (mimowo) [inline test/e2e/tas/rayjob_test.go:221]: Actually, could we keep the check on the actual node names and counts as before? It seems wasteful to compute them in the helper fuction, but not use to assert on. Unless it is flaky?

Comment (mimowo) [reply test/e2e/tas/rayjob_test.go:221]: Ah, yes, it is going to be flaky for CPU based asserts because it will depend on some other Pods we don't have control over, so could change with kind version for example, hmm.

Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:221]: sure, we can
no it's not flaky, it's just different from other types where we have replica/pod index label - where I could think of some general function with params

Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go:221]: right, I wouldn't bind to specific worker node numbers just if they were properly spread, I will rethink this slightly

Comment (mszadkow) [reply test/e2e/tas/rayjob_test.go]: thus let's stick to the set and check set size, that's it

**Comment by mszadkow** [comment]
@mimowo PTAL

File: pkg/controller/jobs/rayjob/rayjob_controller.go [hunk 8]
```diff
@@ -144,11 +144,14 @@ func (j *RayJob) PodSets() ([]kueue.PodSet, error) {
...
-			Count: 1,
+			Name:     submitterJobPodSetName,
+			Count:    1,
+			Template: *getSubmitterTemplate(j),
 		}
 
-		submitterJobPodSet.Template = *getSubmitterTemplate(j)
+		// Create the TopologyRequest for the Submitter Job PodSet, based on the annotations
+		// in rayJob.Spec.SubmitterPodTemplate, which can be specified by the user.
+		submitterJobPodSet.TopologyRequest = jobframework.PodSetTopologyRequest(&getSubmitterTemplate(j).ObjectMeta, nil, nil, nil)
```
Comment (mimowo) [inline pkg/controller/jobs/rayjob/rayjob_controller.go:154]: Why calling the `getSubmitterTemplate` function again? The results should already be available in `submitterJobPodSet.Template`?

Comment (mszadkow) [reply pkg/controller/jobs/rayjob/rayjob_controller.go:154]: Correct, they will be there anyway, equally valid, but more readable...fixing

**Comment by mimowo** [comment]
/test pull-kueue-test-e2e-main-1-31
Looks like an unrelated flake. I will open an issue for it.

**Comment by mimowo** [comment]
@mszadkow please prepare the cherry-pick manually, then we put the new PR https://github.com/kubernetes-sigs/kueue/pull/4498 on top

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
TAS: Fix the bug which didn't respect the TAS annotations on the template for the Ray submitter Job.
```
