### PR TITLE
[Fix] Set agnhost image in e2e tests

### LINKED ISSUE #7340: Make sure all e2e tests use valid images
**What happened**:

Some e2e tests, eg metrics_test.go test/e2e/singlecluster/metrics_test.go are using images which cannot be pull. All such occurences should be replaced with the valid Agnhost image.

**What you expected to happen**:

No such lines in the logs: 
```
Oct 21 20:10:48 kind-worker kubelet[221]: E1021 20:10:48.335028     221 log.go:32] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"docker.io/library/pause:latest\": failed to resolve reference \"docker.io/library/pause:latest\": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" image="pause:latest"
Oct 21 20:10:48 kind-worker kubelet[221]: E1021 20:10:48.335118     221 kuberuntime_image.go:43] "Failed to pull image" err="failed to pull and unpack image \"docker.io/library/pause:latest\": failed to resolve reference \"docker.io/library/pause:latest\": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" image="pause:latest"

```

**How to reproduce it (as minimally and precisely as possible)**:

CI: https://storage.googleapis.com/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-main-1-34/1980723728153055232/artifacts/run-test-e2e-singlecluster-1.34.0/kind-worker/kubelet.log

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We need to override image in our e2e tests to agnhost, otherwise testing wrapper default "pause" is used.
#### Which issue(s) this PR fixes:

Fixes #7340

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/util/testing/defaults.go [hunk 1]
```diff
@@ -47,3 +49,8 @@ func TestRayVersion() string {
 	}
 	return defaultVersion
 }
+
+// if args left empty the container will run the default `pause` command
+func DefaultTestImage() string {
+	return defaultE2eTestAgnHostImageOld
+}
```
Comment (mbobrovskyi) [inline pkg/util/testing/defaults.go]: Why here? Can we move it only for e2e?

File: pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go
Comment (mbobrovskyi) [inline pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go:1]: I don't think so we need to change unit tests.

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go
Comment (mbobrovskyi) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:1]: Also integration test not required.

File: pkg/util/testing/defaults.go (hunk 1 above)
Comment (mszadkow) [reply pkg/util/testing/defaults.go]: no, as e2e uses wrappers and wrappers are not in that package

Comment (mbobrovskyi) [reply pkg/util/testing/defaults.go]: We can override image.

Comment (mszadkow) [reply pkg/util/testing/defaults.go]: Yes, but I want to set a default image value to this

**Comment by mszadkow** [comment]
@mbobrovskyi this type of log is no longer existent in the kubelet.
```
Nov 06 12:23:39 kind-worker kubelet[233]: E1106 12:23:39.365965     233 kuberuntime_image.go:43] "Failed to pull image" err="failed to pull and unpack image \"docker.io/library/pause:latest\": failed to resolve reference \"docker.io/library/pause:latest\": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" image="pause:latest"
```

**Comment by mbobrovskyi** [comment]
/lgtm
Thank you!

**Comment by tenzen-y** [comment]
/cherry-pick release-0.13
/cherry-pick release-0.14

to make CI stable.

**Comment by mszadkow** [comment]
> /cherry-pick release-0.13 /cherry-pick release-0.14
> 
> to make CI stable.

I will make them manually
