### PR TITLE
Validate admission check applies to all flavors

### LINKED ISSUE #2021: [MultiKueue] Report ClusterQueue as inactive (misconfigured) if not applied to all flavors
**What would you like to be added**:

Fail validation for ClusterQueue in case the MultiKueue admission check is configured only for a subset of flavors. 
This can be now done with a similar mechanism to this: https://github.com/kubernetes-sigs/kueue/issues/1913. 

**Why is this needed**:

The managedBy field is immutable, so we cannot change it per flavor. 
To fail fast and avoid debugging of customer issues when using MultiKueue for a subset of flavors.

**Proposed approach**

A mechanism similar to this one: https://github.com/kubernetes-sigs/kueue/pull/1635

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Allow to validate if a MultiKueue admission check is configured only for a subset of flavors.

#### Which issue(s) this PR fixes:

Fixes #2021

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by trasc** [comment]
/retest
The failing test is tracked under #2045

File: pkg/cache/admissioncheck.go [hunk 1]
```diff
@@ -20,4 +20,5 @@ type AdmissionCheck struct {
 	Active                       bool
 	Controller                   string
 	SingleInstanceInClusterQueue bool
+	ApplyToAllFlavors            bool
```
Comment (trasc) [inline pkg/cache/admissioncheck.go:23]:
```suggestion
	ApplyOnlyToAllFlavors            bool
```

File: pkg/cache/clusterqueue.go [hunk 2]
```diff
@@ -87,6 +87,7 @@ type ClusterQueue struct {
 	hasMissingFlavors                          bool
 	hasMissingOrInactiveAdmissionChecks        bool
 	hasMultipleSingleInstanceControllersChecks bool
+	hasSpecificFlavorChecks                    bool
```
Comment (trasc) [inline pkg/cache/clusterqueue.go:90]: Maybe

```suggestion
	hasAllFlavorsChecksAppliedToSpecificFlavor                    bool
```

File: pkg/cache/clusterqueue.go [hunk 3]
```diff
@@ -372,6 +373,10 @@ func (c *ClusterQueue) inactiveReason() (string, string) {
 			reasons = append(reasons, "MultipleSingleInstanceControllerChecks")
 		}
 
+		if c.hasSpecificFlavorChecks {
+			reasons = append(reasons, "ChecksNotApplyToAllFlavors")
```
Comment (trasc) [inline pkg/cache/clusterqueue.go:377]:
```suggestion
			reasons = append(reasons, "AllFlavorsChecksAppliedToSpecificFlavor ")
```

**Review by trasc — COMMENTED** [review]
/lgtm

File: pkg/cache/clusterqueue_test.go [hunk 4]
```diff
@@ -646,6 +653,29 @@ func TestClusterQueueUpdateWithAdmissionCheck(t *testing.T) {
...
+					Controller: "controller2",
+				},
+				"check3": {
+					Active:                true,
+					Controller:            "controller3",
+					ApplyOnlyToAllFlavors: true,
+				},
+			},
+			wantStatus: pending,
+			wantReason: "AllFlavorsChecksAppliedToSpecificFlavor",
```
Comment (mimowo) [inline pkg/cache/clusterqueue_test.go:677]: It would be nice to describe more details in the message, for example "The Admission Check {name} (controlled by {controller}) can only be applied to all flavors, but applied to {list of flavors}.".

File: apis/kueue/v1beta1/admissioncheck_types.go [hunk 5]
```diff
@@ -104,6 +104,9 @@ const (
 	// Having multiple AdmissionChecks managed by the same controller where at least one has this condition
 	// set to true will cause the ClusterQueue to be marked as Inactive.
 	AdmissionChecksSingleInstanceInClusterQueue string = "SingleInstanceInClusterQueue"
+
+	// AdmissionCheckApplyOnlyToAllFlavors indicates if the AdmissionCheck cannot be applied at ResourceFlavor level.
+	AdmissionCheckApplyOnlyToAllFlavors string = "ApplyOnlyToAllFlavors"
```
Comment (mimowo) [inline apis/kueue/v1beta1/admissioncheck_types.go:109]: Maybe `FlavorIndependentAdmissionCheck` ?

**Review by mimowo — COMMENTED** [review]
The implementation lgtm, but the naming is confusing imo (proposed an alternative). Also, it would be helpful to have a message where we can point out the admission check, but we can leave for follow up.

**Comment by mimowo** [comment]
@IrvingMg please also update documentation for the MK admission check, can be done in a follow up.

File: pkg/cache/clusterqueue_test.go (hunk 4 above)
Comment (IrvingMg) [reply pkg/cache/clusterqueue_test.go:677]: Do you mean that we should include the details in the reason string? As in the other cases of  [`inactiveReason()`](https://github.com/kubernetes-sigs/kueue/pull/2047/files#diff-441da8393964615cf5b020d0afb9199588e157e50718e83b527788eb679391ecR356) method, currently we're returning just the reason without extra information.

File: pkg/cache/clusterqueue.go [hunk 6]
```diff
@@ -372,6 +373,10 @@ func (c *ClusterQueue) inactiveReason() (string, string) {
 			reasons = append(reasons, "MultipleSingleInstanceControllerChecks")
 		}
 
+		if c.hasClusterQueueLevelAdmissionCheckAppliedAtFlavorLevel {
+			reasons = append(reasons, "MultiKueueAdmissionCheckAppliedPerFlavor")
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:377]:
```suggestion
			reasons = append(reasons, "FlavorIndependentAdmissionCheckAppliedPerFlavor")
```
Let's call it that way since the condition checked in the if is more generic

File: pkg/cache/clusterqueue.go [hunk 7]
```diff
@@ -82,13 +82,14 @@ type ClusterQueue struct {
...
-	hasMissingOrInactiveAdmissionChecks        bool
-	hasMultipleSingleInstanceControllersChecks bool
-	admittedWorkloadsCount                     int
-	isStopped                                  bool
+	localQueues                                            map[string]*queue
+	podsReadyTracking                                      bool
+	hasMissingFlavors                                      bool
+	hasMissingOrInactiveAdmissionChecks                    bool
+	hasMultipleSingleInstanceControllersChecks             bool
+	hasClusterQueueLevelAdmissionCheckAppliedAtFlavorLevel bool
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:90]:
```suggestion
	hasFlavorIndependentAdmissionCheckAppliedAtFlavorLevel bool
```
for consistency

File: pkg/cache/clusterqueue_test.go [hunk 8]
```diff
@@ -646,6 +652,20 @@ func TestClusterQueueUpdateWithAdmissionCheck(t *testing.T) {
 			wantStatus: pending,
 			wantReason: "MultipleSingleInstanceControllerChecks",
 		},
+		{
+			name:     "Active clusterQueue with an AC per ResourceFlavor",
```
Comment (mimowo) [inline pkg/cache/clusterqueue_test.go:656]:
```suggestion
			name:     "Active clusterQueue with a FlavorIndependent AC applied per ResourceFlavor",
```

File: pkg/cache/clusterqueue_test.go (hunk 4 above)
Comment (mimowo) [reply pkg/cache/clusterqueue_test.go]: > Do you mean that we should include the details in the reason string?

The `reason` field is ok, this is just a camel-case summary. 

I was thinking about the `message` field that is set on the ClusterQueue's condition when `Active=False`. 
This indeed is returned as the second param from `inactiveReason`, and computed here as a concatenation of `reason` fields. However, it does not tell the user details, like which AC we are referring to.

To pass this information we would need to probably compute it inside `updateWithAdmissionChecks` and store [here](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/clusterqueue.go#L87-L91), probably as a map from reason to message.

Since this is a pre-existing limitation of the current structure of the code I'm ok to leave it as a follow up. WDYT?

Comment (IrvingMg) [reply pkg/cache/clusterqueue_test.go]: I agree, I think we can leave it as a follow up and include there the details for this and the rest of the admission checks as well.

Comment (mimowo) [reply pkg/cache/clusterqueue_test.go]: sgtm

File: pkg/cache/clusterqueue.go [hunk 9]
```diff
@@ -82,13 +82,14 @@ type ClusterQueue struct {
...
-	hasMissingOrInactiveAdmissionChecks        bool
-	hasMultipleSingleInstanceControllersChecks bool
-	admittedWorkloadsCount                     int
-	isStopped                                  bool
+	localQueues                                            map[string]*queue
+	podsReadyTracking                                      bool
+	hasMissingFlavors                                      bool
+	hasMissingOrInactiveAdmissionChecks                    bool
+	hasMultipleSingleInstanceControllersChecks             bool
+	hasFlavorIndependentAdmissionCheckAppliedAtFlavorLevel bool
```
Comment (mimowo) [inline pkg/cache/clusterqueue.go:90]:
```suggestion
	hasFlavorIndependentAdmissionCheckAppliedPerFlavor bool
```
nit, shorter and for consistency

**Comment by mimowo** [comment]
LGTM, remaining nit: https://github.com/kubernetes-sigs/kueue/pull/2047#discussion_r1579593642
/approve
/assign @alculquicondor

**Comment by mimowo** [comment]
/lgtm
Thanks

**Review by alculquicondor — COMMENTED** [review]
/approve
