### PR TITLE
Use kueue.x-k8s.io/resource-in-use finalizer for Topology.

### LINKED ISSUE #3821: Use kueue.x-k8s.io/resource-in-use finalizer for Topology
**What happened**:

Topology can be deleted easily at any time, even when in use.

**What you expected to happen**:

There should be some guard before accidental deletion, such as we have for ResourceFlavor - the kueue.x-k8s.io/resource-in-use finalizer. The Topology can be still deleted by admins, just requires either first deleting the ResourceFlavor, or deleting the finalizer.

**How to reproduce it (as minimally and precisely as possible)**:

Create the structure: LQ, CQ, RF, Topology. 

Now, the Topology can be deleted.

**Anything else we need to know?**:

Here is the analogous code handing the finalizer for ResourceFlavors: https://github.com/kubernetes-sigs/kueue/blob/e544dc8a447abfafb471886f9390af0a303b24d5/pkg/controller/core/resourceflavor_controller.go#L83-L108

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Use `kueue.x-k8s.io/resource-in-use` finalizer for Topology.

#### Which issue(s) this PR fixes:

Fixes #3821

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/cache/cache.go [hunk 1]
```diff
@@ -122,6 +123,7 @@ func New(client client.Client, opts ...Option) *Cache {
 	c := &Cache{
 		client:              client,
 		assumedWorkloads:    make(map[string]string),
+		topologies:          make(map[kueue.TopologyReference][]string),
```
Comment (mimowo) [inline pkg/cache/cache.go:126]: The existence of topologies is already tracked in cache in the tasCache. I don't want to duplicate the information.
I think you should be able to reuse that.

File: pkg/controller/core/clusterqueue_controller.go [hunk 2]
```diff
@@ -56,10 +56,6 @@ import (
 
 const snapshotWorkers = 5
 
-type ClusterQueueUpdateWatcher interface {
```
Comment (mimowo) [inline pkg/controller/core/clusterqueue_controller.go:59]: I don't understand why this is changed. Can you instead call the already existing update on topologyUpdateWatchers?

File: pkg/cache/cache.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/cache/cache.go:126]: We can't reuse it because resourceFlavor and topology are related to each other. If one resource is removed, the other will also be removed.

It would be also better to keep topologies on TASCache but I need to do a lot of changes. So I propose optimizing TASCache in a follow-up so that we can cache them independently.

**Comment by mimowo** [comment]
/hold
Overall I'm ok with the topology reconciler for that, but the comments https://github.com/kubernetes-sigs/kueue/pull/3824#discussion_r1883667499 and https://github.com/kubernetes-sigs/kueue/pull/3824#discussion_r1883661617 I think are blockers for now.

File: pkg/controller/core/clusterqueue_controller.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/controller/core/clusterqueue_controller.go:59]: I can't subscribe for `ClusterQueueUpdateWatcher` due to it is on the core `SetupControllers`.

Comment (mbobrovskyi) [reply pkg/controller/core/clusterqueue_controller.go:59]: No, we need to wait for update of clusterQueue.

Comment (mbobrovskyi) [reply pkg/controller/core/clusterqueue_controller.go:59]: I need to know about this changes

https://github.com/kubernetes-sigs/kueue/blob/bf8b06861d999fe892e4c0dcfa3c26716af28610/pkg/controller/tas/topology_controller.go#L179-L180

Comment (mimowo) [reply pkg/controller/core/clusterqueue_controller.go:59]: Again, this problem is already solved, please look into the previous referenced PR and I expect you will be able to follow the approach.

Comment (mbobrovskyi) [reply pkg/controller/core/clusterqueue_controller.go:59]: Which PR do you mean?

Comment (mimowo) [reply pkg/controller/core/clusterqueue_controller.go:59]: https://github.com/kubernetes-sigs/kueue/pull/3770

File: pkg/cache/cache.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/cache/cache.go:126]: Done

File: pkg/controller/core/clusterqueue_controller.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/controller/core/clusterqueue_controller.go]: Done

File: pkg/controller/tas/topology_controller.go [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+		// we'll ignore not-found errors, since there is nothing to do.
+		return ctrl.Result{}, client.IgnoreNotFound(err)
+	}
+
+	log := ctrl.LoggerFrom(ctx).WithValues("name", req.NamespacedName.Name)
+	log.V(2).Info("Reconcile Topology")
+
+	if !topology.DeletionTimestamp.IsZero() {
+		if controllerutil.ContainsFinalizer(topology, kueue.ResourceInUseFinalizerName) {
+			if flRefs := r.tasCache.ResourceFlavorsUsingTopology(kueue.TopologyReference(topology.Name)); len(flRefs) != 0 {
```
Comment (mimowo) [inline pkg/controller/tas/topology_controller.go:94]: Can we just use `for flName, flCache := range r.tasCache.Clone() {` instead of the new function?

**Comment by mimowo** [comment]
/hold cancel 
The PR looks much smaller and better after the recent changes. I would be ok to include it, left one comment for now. I will do one more careful pass.

**Comment by mimowo** [comment]
/hold 
for investigating / fixing the e2e test failures first

File: pkg/controller/tas/topology_controller.go (hunk 3 above)
Comment (mbobrovskyi) [reply pkg/controller/tas/topology_controller.go]: Done

**Comment by mimowo** [comment]
> /hold
> for investigating / fixing the e2e test failures first

/hold cancel

File: pkg/controller/tas/resource_flavor.go [hunk 4]
```diff
@@ -161,7 +161,7 @@ func (h *topologyHandler) Create(ctx context.Context, e event.CreateEvent, q wor
 		return
 	}
 
-	defer h.notifyTopologyWatchers(nil, topology)
+	defer h.queues.NotifyTopologyUpdateWatchers(nil, topology)
```
Comment (mimowo) [inline pkg/controller/tas/resource_flavor.go:164]: We could move the `topologyHandler` to the topology_controller.go, but it can be in a follow up. I see it would mean more changes.

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Awesome

**Comment by mimowo** [comment]
I prefer not to cherry-pick this because it requires changes to RBAC which are part of the installation manifests, and some users could get into troubles by just trying to change 0.9.1 to 0.9.2 in the image.
