### PR TITLE
Fix missing replica_role=leader metrics after HA role transition

### LINKED ISSUE #9288: There is no data for the kueue_cluster_queue_nominal_quota with replica_role=leader
**What happened**:

A user reports there is no data reported for the `kueue_cluster_queue_nominal_quota` metric when `replica_role=leader` filter is present. There is data returned for `replica_role=follower` filter.

**What you expected to happen**:

The `kueue_cluster_queue_nominal_quota` metric should also be returned for leader replica.

**How to reproduce it (as minimally and precisely as possible)**:

Forwarding issue reported by a user, but it should be just to create a deployment with two replicas, and check the metric for CQs. If this does not repro the issue we may investigate more. This issue was reported on 0.16.1.

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

After an HA role transition from `follower` to `leader`, gauge metrics were still tagged with `replica_role` set to `follower` and were never re-reported with `replica_role` set to `leader`.

This change adds an `OnTransition` callback to `RoleTracker` that clears stale follower metrics and resynchronizes all metric-emitting components.

#### Which issue(s) this PR fixes:

Fixes #9288 

#### Does this PR introduce a user-facing change?

```release-note
Observability: Fix missing replica_role=leader gauge metrics after HA role transition.
```

### CODE REVIEW

File: pkg/controller/core/clusterqueue_controller.go [hunk 1]
```diff
@@ -369,6 +369,31 @@ func (r *ClusterQueueReconciler) Generic(e event.TypedGenericEvent[*kueue.Cluste
 	return true
 }
 
+// ResyncMetrics re-reports CQ resource and weighted share gauge metrics.
+func (r *ClusterQueueReconciler) ResyncMetrics(ctx context.Context) {
+	if !r.reportResourceMetrics {
+		return
+	}
+	var cqList kueue.ClusterQueueList
```
Comment (mimowo) [inline pkg/controller/core/clusterqueue_controller.go]: don't we have access to the list of CQs in the cache? listing is ok-ish but event handlers don't have error handling and the list may fail with error

File: pkg/metrics/metrics.go [hunk 2]
```diff
@@ -847,6 +847,39 @@ func ReportCohortWeightedShare(cohort string, weightedShare float64, tracker *ro
 	CohortWeightedShare.WithLabelValues(cohort, roletracker.GetRole(tracker)).Set(weightedShare)
 }
 
+var roleTaggedGauges = []*prometheus.GaugeVec{
```
Comment (mimowo) [inline pkg/metrics/metrics.go]: Could we automate listing those by some fliters?

**Comment by IrvingMg** [comment]
> @IrvingMg From your experience, are the logger reporting the correct role, while metrics not ?
> 
> In my case, I can always see the scheduler thread role to be follower, even in single-replica setups.

Over the past days, we’ve been working on a few fixes for the roleTracker. One of them was related to the scheduler: https://github.com/kubernetes-sigs/kueue/pull/9429, so this might be the one you’re experiencing.

We also fixed a couple of issue related to logs missing the roleTracker: https://github.com/kubernetes-sigs/kueue/pull/9445 and https://github.com/kubernetes-sigs/kueue/pull/9433.

File: pkg/controller/core/clusterqueue_controller.go (hunk 1 above)
Comment (IrvingMg) [reply pkg/controller/core/clusterqueue_controller.go]: I removed the API calls and moved resource metrics reporting into Cache.ResyncMetrics(). Thanks.

File: pkg/metrics/metrics.go (hunk 2 above)
Comment (IrvingMg) [reply pkg/metrics/metrics.go]: I attempted to introduce a helper, `newRoleTaggedGaugeVec`, to add the role label and append it to the list automatically. 

However, this breaks the metrics doc generator because the helper hides `prometheus.NewGaugeVec`. 

I'd suggest to handle this in a follow-up.

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go [hunk 3]
```diff
@@ -1133,3 +1139,85 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Label("controller:clus
...
+			"cluster_queue": cq.Name,
+			"replica_role":  roletracker.RoleFollower,
+		}
+
+		ginkgo.By("Waiting for CQ to become active")
+		gomega.Eventually(func(g gomega.Gomega) {
+			var updatedCQ kueue.ClusterQueue
+			g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(cq), &updatedCQ)).To(gomega.Succeed())
+			g.Expect(apimeta.IsStatusConditionTrue(updatedCQ.Status.Conditions, kueue.ClusterQueueActive)).To(gomega.BeTrue())
+		}, util.Timeout, util.Interval).Should(gomega.Succeed())
```
Comment (mimowo) [inline test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]: We have a helper for that. ptal, I think we have a function even which already waits for the CQ to be active when creating

File: pkg/metrics/metrics.go (hunk 2 above)
Comment (mimowo) [reply pkg/metrics/metrics.go]: This is only used in roleTaggedGauges. So what I was thinking about is to list the metrics from `metrics.Registry`, and iterate over them. Then only clear those which belong to Kueue, and are guage. If this wouldn't work, then ok

File: pkg/cache/scheduler/cache.go [hunk 4]
```diff
@@ -905,6 +915,78 @@ func (c *Cache) MatchingClusterQueues(nsLabels map[string]string) sets.Set[kueue
...
+		metrics.ReportClusterQueueResourceUsage(cohort, cqName, fName, rName, resourceFloat(fr.Resource, cq.AdmittedUsage[fr]), c.roleTracker)
+	}
+	if c.fairSharingEnabled {
+		drs := dominantResourceShare(cq, nil)
+		weightedShare := drs.PreciseWeightedShare()
+		if weightedShare == math.Inf(1) {
+			weightedShare = math.NaN()
+		}
+		metrics.ReportClusterQueueWeightedShare(cqName, string(cohort), weightedShare, c.roleTracker)
+	}
```
Comment (mimowo) [inline pkg/cache/scheduler/cache.go]: This is a lot of code, don't we have already the code to report guage metrics we could call? I think we should try to commonize the code

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go (hunk 3 above)
Comment (IrvingMg) [reply test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]: Done.

File: pkg/cache/scheduler/cache.go (hunk 4 above)
Comment (IrvingMg) [reply pkg/cache/scheduler/cache.go]: Moved reporting to `clusterQueue.reportResourceMetrics()` and `LocalQueue.reportResourceMetrics()` struct methods, following the `reportActiveWorkloads` pattern.

File: pkg/metrics/metrics.go (hunk 2 above)
Comment (IrvingMg) [reply pkg/metrics/metrics.go]: The Prometheus client only allows reading metrics from the registry, so looks like it's not possible to clean up specific time series from it.

Instead, I added a `registerGaugeVecs()` function that registers each gauge and appends it to `allGaugeVecs`, ensuring it’s included in the role transition cleanup.

File: pkg/util/roletracker/tracker_test.go [hunk 5]
```diff
@@ -89,6 +89,65 @@ func TestRoleTracker_StartLeaderElection(t *testing.T) {
...
+	}{
+		{
+			name:            "called on election with previous role",
+			registerCb:      true,
+			closeChannel:    true,
+			expectCalled:    true,
+			expectPrevRole:  RoleFollower,
+			expectFinalRole: RoleLeader,
+		},
+	}
```
Comment (mszadkow) [inline pkg/util/roletracker/tracker_test.go]: This test seems to be missing some scenarios, otherwise I don't know why we need so many options

**Comment by mszadkow** [comment]
overall lgtm
please check the PR with manual tests -  it can reveal some issues that can't be catch in integration

File: pkg/util/roletracker/tracker_test.go (hunk 5 above)
Comment (IrvingMg) [reply pkg/util/roletracker/tracker_test.go]: Done. Added a couple more scenarios.

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go [hunk 6]
```diff
@@ -1133,3 +1139,81 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Label("controller:clus
...
+	})
+
+	ginkgo.BeforeEach(func() {
+		rf = utiltestingapi.MakeResourceFlavor("ha-transition-flavor").Obj()
+		util.MustCreate(ctx, k8sClient, rf)
+
+		cq = utiltestingapi.MakeClusterQueue("ha-transition-cq").
+			ResourceGroup(*utiltestingapi.MakeFlavorQuotas("ha-transition-flavor").Resource(corev1.ResourceCPU, "10").Obj()).
+			Obj()
+		util.MustCreate(ctx, k8sClient, cq)
```
Comment (mbobrovskyi) [inline test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]:
```suggestion
		util.CreateClusterQueuesAndWaitForActive(ctx, k8sClient, cq)
```

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go [hunk 7]
```diff
@@ -1133,3 +1139,81 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Label("controller:clus
...
+
+	ginkgo.It("Should resync metrics after role transition from follower to leader", func() {
+		followerLabels := map[string]string{
+			"cluster_queue": cq.Name,
+			"replica_role":  roletracker.RoleFollower,
+		}
+
+		ginkgo.By("Waiting for CQ to become active")
+		util.ExpectClusterQueuesToBeActive(ctx, k8sClient, cq)
+
```
Comment (mbobrovskyi) [inline test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]:
```suggestion
```

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go [hunk 8]
```diff
@@ -1133,3 +1139,81 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Label("controller:clus
...
+var _ = ginkgo.Describe("ClusterQueue controller with RoleTracker", ginkgo.Label("controller:clusterqueue", "area:core"), ginkgo.Ordered, ginkgo.Serial, func() {
+	var (
+		electedChan   chan struct{}
+		trackerCancel context.CancelFunc
+		rf            *kueue.ResourceFlavor
+		cq            *kueue.ClusterQueue
+	)
+
+	ginkgo.BeforeAll(func() {
```
Comment (mbobrovskyi) [inline test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]:
```suggestion
	ginkgo.BeforeEach(func() {
```
nit: because if we add one more test, electedChan will never become active.

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go [hunk 9]
```diff
@@ -1133,3 +1139,81 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Label("controller:clus
...
+		electedChan = make(chan struct{})
+		tracker := roletracker.NewRoleTracker(electedChan)
+		var trackerCtx context.Context
+		trackerCtx, trackerCancel = context.WithCancel(ctx)
+		go tracker.Start(trackerCtx, ctrl.Log)
+		fwk.StartManager(ctx, cfg, managerAndControllerSetup(nil, withRoleTracker(tracker)))
+	})
+
+	ginkgo.AfterAll(func() {
+		trackerCancel()
```
Comment (mbobrovskyi) [inline test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]:
```suggestion
		if _, ok := <-electedChan; ok {
			close(electedChan)
		}
		trackerCancel()
```
Just to make sure that we close channel on failure.

File: test/integration/singlecluster/controller/core/suite_test.go [hunk 10]
```diff
@@ -104,11 +115,20 @@ func managerAndControllerSetup(controllersCfg *config.Configuration, options ...
 
 		controllersCfg.Metrics.EnableClusterQueueResources = true
 
-		cCache := schdcache.New(mgr.GetClient())
-		queues := util.NewManagerForIntegrationTests(ctx, mgr.GetClient(), cCache)
+		cacheOpts := []schdcache.Option{
+			schdcache.WithResourceMetrics(controllersCfg.Metrics.EnableClusterQueueResources),
+		}
+		var queueOpts []qcache.Option
+		if opts.roleTracker != nil {
```
Comment (mbobrovskyi) [inline test/integration/singlecluster/controller/core/suite_test.go]: I think we can avoid this if and propagate this options directly.

File: pkg/controller/core/core.go [hunk 11]
```diff
@@ -102,6 +103,15 @@ func SetupControllers(mgr ctrl.Manager, qManager *qcache.Manager, cc *schdcache.
...
 	qManager.AddTopologyUpdateWatcher(cqRec)
 	qManager.AddWorkloadUpdateWatcher(qRec)
+
+	if roleTracker != nil {
+		roleTracker.OnTransition(func(previousRole string) {
+			metrics.ClearGaugeMetricsForRole(previousRole)
+			cc.ResyncMetrics()
+			qManager.ResyncMetrics()
+		})
+	}
```
Comment (kshalot) [inline pkg/controller/core/core.go]: Nit: Should this be inside `SetupControllers` or higher, a little bit closer to where the role tracker is initialized (I guess this would be the `main` func)? `cc`, `qManager` and `roleTracker`  are all passed from main and I don't see any local var being referenced here so this is not a closure either.

File: pkg/util/roletracker/tracker.go [hunk 12]
```diff
@@ -51,12 +52,22 @@ func NewFakeRoleTracker(role string) *RoleTracker {
 	return rt
 }
 
+// OnTransition registers a callback invoked after the role changes,
+// receiving the previous role. Must be called before Start.
+func (rt *RoleTracker) OnTransition(fn func(previousRole string)) {
+	rt.onTransition = fn
+}
```
Comment (kshalot) [inline pkg/util/roletracker/tracker.go]: Nit: I'm wondering about the naming, because `OnTransition` is essentially `OnElected` in our case, right? From what I understand, there is no way for this to trigger with `previousRole` being anything other than "follower". And IIUC there is no way for this to be triggered more than once per replica.

I'd consider making the code a little less flexible but more explicit, unless there is some case here that I'm missing. WDYT?

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go (hunk 6 above)
Comment (IrvingMg) [reply test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]: Done.

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go (hunk 7 above)
Comment (IrvingMg) [reply test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]: Done.

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go (hunk 8 above)
Comment (IrvingMg) [reply test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]: Done. Also updated to `AfterEach`.

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go (hunk 9 above)
Comment (IrvingMg) [reply test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]: Done.

File: test/integration/singlecluster/controller/core/suite_test.go (hunk 10 above)
Comment (IrvingMg) [reply test/integration/singlecluster/controller/core/suite_test.go]: Done. Now always passes both options unconditionally.

File: pkg/controller/core/core.go (hunk 11 above)
Comment (IrvingMg) [reply pkg/controller/core/core.go]: Done. Moved it to main() right after queues is created.

File: pkg/util/roletracker/tracker.go (hunk 12 above)
Comment (IrvingMg) [reply pkg/util/roletracker/tracker.go]: Good idea. I renamed it to `onElected` and remove the `previousRole` param.

File: pkg/metrics/metrics.go [hunk 13]
```diff
@@ -847,6 +847,18 @@ func ReportCohortWeightedShare(cohort string, weightedShare float64, tracker *ro
...
+
+// ClearGaugeMetricsForRole deletes all gauge metric time series matching
+// replica_role=role. Called during HA role transitions to remove stale
+// time series reported under the old role.
+func ClearGaugeMetricsForRole(role string) {
+	lbls := prometheus.Labels{"replica_role": role}
+	for _, g := range allGaugeVecs {
+		g.DeletePartialMatch(lbls)
+	}
+}
```
Comment (kshalot) [inline pkg/metrics/metrics.go:892]: If there are >1 followers, won't this remove the gauges for all of them? Or are they implicitly scoped to a replica?

I'm asking as a precaution, because from what I can see it was tested with 1 follower and 1 leader.

Comment (IrvingMg) [reply pkg/metrics/metrics.go:892]: This should run only on the replica that transitions. As I understand it, each replica has its own registry, so clearing them should be scoped to that replica.

Comment (kshalot) [reply pkg/metrics/metrics.go:892]: Yeah, that was my understanding, but wanted to double check

File: pkg/cache/scheduler/clusterqueue.go [hunk 14]
```diff
@@ -492,6 +493,40 @@ func (c *clusterQueue) reportActiveWorkloads() {
...
+		if quota.BorrowingLimit != nil {
+			borrowing = resourceFloat(fr.Resource, *quota.BorrowingLimit)
+		}
+		if quota.LendingLimit != nil {
+			lending = resourceFloat(fr.Resource, *quota.LendingLimit)
+		}
+		metrics.ReportClusterQueueQuotas(cohort, cqName, fName, rName, nominal, borrowing, lending, c.roleTracker)
+		metrics.ReportClusterQueueResourceReservations(cohort, cqName, fName, rName, resourceFloat(fr.Resource, c.resourceNode.Usage[fr]), c.roleTracker)
+		metrics.ReportClusterQueueResourceUsage(cohort, cqName, fName, rName, resourceFloat(fr.Resource, c.AdmittedUsage[fr]), c.roleTracker)
+	}
```
Comment (kshalot) [inline pkg/cache/scheduler/clusterqueue.go:516]: Unless I'm missing something, I see some overlap between this and existing code, like this:
https://github.com/kubernetes-sigs/kueue/blob/307e822b65f945b7f0a963d25ccf3d41c9571482/pkg/controller/core/clusterqueue_controller.go#L381-L411

Or this for LQ:
https://github.com/kubernetes-sigs/kueue/blob/307e822b65f945b7f0a963d25ccf3d41c9571482/pkg/controller/core/localqueue_controller.go#L374-L385

I suspect there are some differences in how to handle a total re-sync and updates like in those snippets, but maybe there is some way to re-use the logic. Or at least maybe gather it in some place? WDYT?

File: pkg/cache/scheduler/cache.go [hunk 15]
```diff
@@ -905,6 +914,38 @@ func (c *Cache) MatchingClusterQueues(nsLabels map[string]string) sets.Set[kueue
...
+		cq.reportActiveWorkloads()
+		if c.resourceMetricsEnabled {
+			cq.reportResourceMetrics(c.fairSharingEnabled)
+		}
+		if features.Enabled(features.LocalQueueMetrics) {
+			for _, lq := range cq.localQueues {
+				lq.reportActiveWorkloads(c.roleTracker)
+				if c.resourceMetricsEnabled {
+					lq.reportResourceMetrics(cq.resourceNode.Quotas, c.roleTracker)
+				}
```
Comment (kshalot) [inline pkg/cache/scheduler/cache.go]: To illustrate my point from [this comment](https://github.com/kubernetes-sigs/kueue/pull/9487/files#r2904826910) - here we will only report LQ resource metrics if `c.resourceMetricsEnabled` (which is `controllersCfg.Metrics.EnableClusterQueueResources`), but I don't think this check is performed in the other LQ metrics logic, which seems to only check `features.Enabled(features.LocalQueueMetrics)`:
https://github.com/kubernetes-sigs/kueue/blob/307e822b65f945b7f0a963d25ccf3d41c9571482/pkg/controller/core/localqueue_controller.go#L228-L230

So, unless I'm missing something, there logic diverges here.

File: pkg/cache/scheduler/clusterqueue.go (hunk 14 above)
Comment (IrvingMg) [reply pkg/cache/scheduler/clusterqueue.go:516]: Yeah, the common part is that they call the same `metrics.Report*` functions. However, the rest differs because they read from different data sources: the cache uses maps, while the controller uses API objects. So I don’t think they can be commonized much, or that there would be much benefit in doing so.

File: pkg/cache/scheduler/cache.go (hunk 15 above)
Comment (IrvingMg) [reply pkg/cache/scheduler/cache.go]: Good catch. Removed the `c.resourceMetricsEnabled` check, LQ resource metrics should be gated only by the `LocalQueueMetrics` feature gate.

File: pkg/cache/scheduler/clusterqueue.go (hunk 14 above)
Comment (mimowo) [reply pkg/cache/scheduler/clusterqueue.go:516]: I agree with @kshalot . I believe this is the same motivation and sentiment as in my comment here: https://github.com/kubernetes-sigs/kueue/pull/9487#discussion_r2865072597

Sure, the code has similar structure in both places, but I cannot imagine a reviewer would notice if someone forgot to adjust the MetricsResync when introducing a new metric. A contributor may notice by following the links (function references). The reviewer is almost certainly lost, unless she/he or checkout the code.

I agree that currently both functions use different data sources, but could we replace the existing occurrences with the new ones: https://github.com/kubernetes-sigs/kueue/blob/307e822b65f945b7f0a963d25ccf3d41c9571482/pkg/controller/core/clusterqueue_controller.go#L381-L411

I believe the correct approach is for both places to use the cache as the data source. This is something I discussed in the past with @mbobrovskyi on the occassion of a metric for finished workloads, was that our current model of building metrics based on statuses is too constraining. I prefer the status and the metrics to both have the source in cache.

wdyt @IrvingMg . If we agree it does not necessarily mean it needs to be this PR, but we could open a follow up issue to commonize the approach.

File: pkg/cache/queue/manager.go [hunk 16]
```diff
@@ -855,14 +834,29 @@ func (m *Manager) queueSecondPass(ctx context.Context, w *kueue.Workload, iterat
...
-	wInfo.UpdateSchedulingHash(log)
 	wInfo.SecondPassIteration = iteration
 	if m.secondPassQueue.queue(wInfo) {
 		log.V(3).Info("Workload queued for second pass of scheduling", "workload", workload.Key(w))
 		m.Broadcast()
 	}
 }
 
+// ResyncMetrics re-reports pending and finished workload gauge metrics.
+func (m *Manager) ResyncMetrics() {
```
Comment (mimowo) [inline pkg/cache/queue/manager.go]:
```suggestion
func (m *Manager) ResyncGuageMetrics() {
```
nit, I think this is by design only related to guage metrics, right?

File: pkg/cache/scheduler/cache.go [hunk 17]
```diff
@@ -905,6 +914,36 @@ func (c *Cache) MatchingClusterQueues(nsLabels map[string]string) sets.Set[kueue
 	return cqs
 }
 
+// ResyncMetrics re-reports CQ/LQ status, active workload, resource, and weighted share gauge metrics.
+func (c *Cache) ResyncMetrics() {
```
Comment (mimowo) [inline pkg/cache/scheduler/cache.go]:
```suggestion
func (c *Cache) ResyncGuageMetrics() {
```

File: cmd/kueue/main.go [hunk 18]
```diff
@@ -334,6 +335,14 @@ func main() {
 		os.Exit(1)
 	}
 
+	if roleTracker != nil {
+		roleTracker.OnElected(func() {
+			metrics.ClearGaugeMetricsForRole(roletracker.RoleFollower)
+			cCache.ResyncMetrics()
+			queues.ResyncMetrics()
```
Comment (mimowo) [inline cmd/kueue/main.go]:
```suggestion
			cCache.ResyncGuageMetrics()
			queues.ResyncGuageMetrics()
```

File: pkg/cache/scheduler/clusterqueue.go (hunk 14 above)
Comment (IrvingMg) [reply pkg/cache/scheduler/clusterqueue.go:516]: Okay, I've created an issue for the follow-up: https://github.com/kubernetes-sigs/kueue/issues/9793

File: pkg/cache/queue/manager.go (hunk 16 above)
Comment (IrvingMg) [reply pkg/cache/queue/manager.go]: Right. Renamed.

File: pkg/cache/scheduler/cache.go (hunk 17 above)
Comment (IrvingMg) [reply pkg/cache/scheduler/cache.go]: Done.

File: cmd/kueue/main.go (hunk 18 above)
Comment (IrvingMg) [reply cmd/kueue/main.go]: Done.

**Comment by mimowo** [comment]
@IrvingMg please prepare cherrypicks manually in case of conflicts
