### PR TITLE
Verify if pod placement based on labels is correct

### LINKED ISSUE #9210: Wrong pod placement when node replacement is performed
**What happened**:

Let's consider the following scenario:

Topology:
```yaml
apiVersion: kueue.x-k8s.io/v1beta2
kind: Topology
metadata:
  name: "default"
spec:
  levels:
  - nodeLabel: "cloud.provider.com/topology-block"
  - nodeLabel: "cloud.provider.com/topology-rack"
  - nodeLabel: "kubernetes.io/hostname"
```

Node	Topology
node1	"b1", "r1", "node1"
node2	"b1", "r1", "node2"
node3	"b1", "r1", "node3"

Jobset:
```yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: tas-jobset
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: tas-user-queue
spec:
  replicatedJobs:
  - name: workers
    replicas: 1
    template:
      spec:
        parallelism: 2
        completions: 2
        backoffLimit: 10
        template:
          metadata:
            annotations:
              kueue.x-k8s.io/podset-required-topology: cloud.provider.com/topology-block
          spec:
            containers:
            - name: sleep
              image: busybox
              command: ["sleep", "100000"]
              resources:
                requests:
                  cpu: "40"
            restartPolicy: Never
```

Here's the current flow of the process:

- The 2 pods of the jobset land on `node1` and `node2`
- `node1` enters into `NotReady` state
- a pod running on the `node1` is deleted
- `node_failure_controller` reacts on the change and executes node replacement procedure and `node3` is chosen as a replacement for `node1`. So the new topology assignment is [`node2`, `node3`]

The Terminating pod on the NotReady node will probably not be removed quickly because of nature of the problem with NotReady state (connection issues, kubelet problems etc.).

When the replacement pods are created they are given a scheduling gate and are handled by topology ungater - https://github.com/kubernetes-sigs/kueue/blob/bf5ff17e5a02c6af61509b96bbb268d4ef48fbce/pkg/controller/tas/topology_ungater.go#L160.

- `Reconcile` is called - https://github.com/kubernetes-sigs/kueue/blob/bf5ff17e5a02c6af61509b96bbb268d4ef48fbce/pkg/controller/tas/topology_ungater.go#L160
- https://github.com/kubernetes-sigs/kueue/blob/bf5ff17e5a02c6af61509b96bbb268d4ef48fbce/pkg/controller/tas/topology_ungater.go#L222 all non terminated pods are listed (Terminating pods are included in the list)
- we start assigning pods to domains - https://github.com/kubernetes-sigs/kueue/blob/bf5ff17e5a02c6af61509b96bbb268d4ef48fbce/pkg/controller/tas/topology_ungater.go#L243
- we try to read ranks from labels - https://github.com/kubernetes-sigs/kueue/blob/bf5ff17e5a02c6af61509b96bbb268d4ef48fbce/pkg/controller/tas/topology_ungater.go#L446 but it fails here https://github.com/kubernetes-sigs/kueue/blob/bf5ff17e5a02c6af61509b96bbb268d4ef48fbce/pkg/controller/tas/topology_ungater.go#L489 because the terminating pod occupies index 0. Because of that we fallback to greedy assignment - https://github.com/kubernetes-sigs/kueue/blob/bf5ff17e5a02c6af61509b96bbb268d4ef48fbce/pkg/controller/tas/topology_ungater.go#L354
- the pods are correctly assigned to [`node2`, node3`]

The problem is that if the terminating pod wasn't there then reading ranks from labels would succeed and we would end up with the replacement pod assigned to `node2` and the final result would be the following: `pod1` -> node2, `pod2` -> `node2`. That's because the `pod2` was running undisrupted and only the `pod1` needed to be ungated.

**What you expected to happen**:

I would expect the process to behave the same in both situations: with and without the terminating pod

**How to reproduce it (as minimally and precisely as possible)**:

Discovered when testing https://github.com/kubernetes-sigs/kueue/pull/8964 - here pods are removed quickly enough so the Terminating pods are not included when assigning domains to pods.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by j-skiba**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

Make pod assignment behave correctly for node replacement

#### Which issue(s) this PR fixes:
Fixes #9210

#### Does this PR introduce a user-facing change?

```release-note
TAS: fix a bug where NodeHotSwap may assign a Pod, based on rank-ordering, to a node which is already
occupied by another running Pod.
```

### CODE REVIEW

**Comment by j-skiba** [comment]
the added integration test WITHOUT the verification fix:
```bash
[FAILED] Timed out after 10.001s.
  The function passed to Eventually failed at .../test/integration/singlecluster/tas/tas_test.go:1747 with:
  Expected
      <string>: x3
  to equal
      <string>: x1
  In [It] at: .../test/integration/singlecluster/tas/tas_test.go:1748 @ 02/13/26 11:23:37.76
```

File: pkg/controller/tas/topology_ungater.go [hunk 1]
```diff
@@ -500,3 +501,40 @@ func isAdmittedByTAS(w *kueue.Workload) bool {
...
+
+func verifyDomainsForRanks(
+	log logr.Logger,
+	psa *kueue.PodSetAssignment,
+	rankToPod map[int]*corev1.Pod) bool {
+	totalPodCount := 0
+	for count := range utiltas.PodCounts(psa.TopologyAssignment) {
+		totalPodCount += int(count)
+	}
+	rankToDomainID := make([]utiltas.TopologyDomainID, totalPodCount)
```
Comment (sohankunkerkar) [inline pkg/controller/tas/topology_ungater.go:515]: nit: consider extracting the `rankToDomainID` computation to pkg/util/tas/ as a utility. As I was thinking about it, this mapping will be useful for elastic workloads, preemption, and DRA integration.

Comment (j-skiba) [reply pkg/controller/tas/topology_ungater.go:515]: done

File: pkg/controller/tas/topology_ungater.go [hunk 2]
```diff
@@ -358,18 +360,7 @@ func assignGatedPodsToDomainsByRanks(
...
-	}
-	rankToDomainID := make([]utiltas.TopologyDomainID, totalPodCount)
-	index := int32(0)
-	for domain := range utiltas.InternalSeqFrom(psa.TopologyAssignment) {
-		for s := range domain.Count {
-			rankToDomainID[index+s] = utiltas.DomainID(domain.Values)
-		}
-		index += domain.Count
-	}
+	rankToDomainID := utiltas.RankToDomainID(psa.TopologyAssignment)
```
Comment (tenzen-y) [inline pkg/controller/tas/topology_ungater.go]: Why do we need to recalculate RankToDomainID?

File: pkg/controller/tas/topology_ungater.go [hunk 3]
```diff
@@ -348,8 +348,10 @@ func assignGatedPodsToDomains(
 	psReq *kueue.PodSetTopologyRequest,
 	offset int32,
 	maxRank int32) []podWithDomain {
-	if rankToGatedPod, ok := readRanksIfAvailable(log, psa, pods, psReq, offset, maxRank); ok {
-		return assignGatedPodsToDomainsByRanks(psa, rankToGatedPod)
+	if rankToPod, ok := readRanksIfAvailable(log, psa, pods, psReq, offset, maxRank); ok {
+		if verifyDomainsForRanks(log, psa, rankToPod) {
```
Comment (tenzen-y) [inline pkg/controller/tas/topology_ungater.go]: The `readRanksIfAvailable` is already responsible for verification (`ifAvailable`).
So, should we consolidate `verifyDomainsForRanks` and `readRanksIfAvailable`?

The consolidation could also avoid calling `RankToDomainID` twice.

File: test/integration/singlecluster/tas/tas_test.go [hunk 4]
```diff
@@ -1678,6 +1681,73 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+						Label(batchv1.JobCompletionIndexAnnotation, "0"). // rank 0
+						Label(jobset.JobIndexKey, "0").
+						Label(jobset.ReplicatedJobReplicas, "1").
+						Label(constants.PodSetLabel, "worker").
+						TopologySchedulingGate().
+						Obj()
+					util.MustCreate(ctx, k8sClient, p0)
+				})
+
+				ginkgo.By("verify p0 is ungated and assigned to a node other than x4 since x4 is occupied", func() {
```
Comment (tenzen-y) [inline test/integration/singlecluster/tas/tas_test.go]:
```suggestion
				ginkgo.By("verify p0 is ungated and assigned to a node other than x3 since x3 is occupied", func() {
```

Isn't it `x3`? Because p1 was assigned to `x3`.

**Review by tenzen-y — COMMENTED** [review]
Thank you for working on that.

File: test/integration/singlecluster/tas/tas_test.go [hunk 5]
```diff
@@ -1678,6 +1681,73 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
 					}, util.Timeout, util.Interval).Should(gomega.Succeed())
 				})
 			})
+			ginkgo.It("should fallback to greedy assignment when replacement pod conflicts with already running pod", framework.SlowSpec, func() {
```
Comment (mimowo) [inline test/integration/singlecluster/tas/tas_test.go:1685]: I'm not clear how this test matches the scenario described in the release note "Fixes incorrect pod placement during node replacement when terminating pods are deleted rapidly." , since this test does not delete any pods.

**Comment by mimowo** [comment]
Could you describe what the user-facing problem is with the old code?

In particular I'm reading in the release note "Fixes incorrect pod placement", here I have some questions:
1. How was the placement incorrect?
2. How does it happen that the placement is incorrect? Should we rather fix the node hot swap to prevent that in the first place, rather than fix it later?

I'm thinking maybe rather than fixing incorrect placements we should prevent them in the first place.

**Comment by mimowo** [comment]
Also note that, as long as the "old pod" is terminating we don't need to change the assignment strategy - it will be gone "soon", and the new Pod with the same index will be able to take its place.

File: test/integration/singlecluster/tas/tas_test.go (hunk 5 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:1685]: In a scenario when one of two pods is terminated quickly and this one when there is only one pod initially the result is the same - TAS ungater sees just one pod when starts calculating assignments.

**Comment by j-skiba** [comment]
> 1. How was the placement incorrect?

Given the scenario from the [issue](https://github.com/kubernetes-sigs/kueue/issues/9210).
The initial pod assignments would be [`node1`, `node2`]. After `node1` failure and node replacement the topology assignment would be [`node2`, `node3`] where the pod on `node2` would be running undisrupted so the replacement pod should be scheduled on `node3`, but the terminating pod was deleted quickly enough so it was assigned nodeSelectors for `node2` because of its job labels (index 0).
Usually that doesn't happen because the terminating pod exists and has a conflicting job label and because of that there is fallback to the greedy assignment.

So in case where there were 2 pods that use 40 cpus each while there were nodes with 50 cpus then in the described scenario we would end up with 2 pods scheduled on `node2` where only one pod can run because there is no space for 2 pods that use 40 cpus each.

> 2. How does it happen that the placement is incorrect? Should we rather fix the node hot swap to prevent that in the first place, rather than fix it later?

I don't think we should do anything with the hotswap. I think that node replacement is the right thing to do because the node and the pod are nonfunctional. I would say the problem is with the placement of the pods that was working based on the conflicting job labels and it luckily resulted in sensible placement of the pods.

> Also note that, as long as the "old pod" is terminating we don't need to change the assignment strategy - it will be gone "soon", and the new Pod with the same index will be able to take its place.

I think that's even a worse scenario because it would trigger the bug.
Also when there are problems with kubelet on the node it might take some more time to mark the pod as terminated.

File: test/integration/singlecluster/tas/tas_test.go (hunk 5 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:1685]: it's the same from the point of view of this call - https://github.com/kubernetes-sigs/kueue/blob/bf5ff17e5a02c6af61509b96bbb268d4ef48fbce/pkg/controller/tas/topology_ungater.go#L222

File: pkg/controller/tas/topology_ungater.go (hunk 3 above)
Comment (j-skiba) [reply pkg/controller/tas/topology_ungater.go]: I moved `utiltas.RankToDomainID` to be called before `readRanksIfAvailable` and `assignGatedPodsToDomainsByRanks` and pass them as an argument, also moved the `verify` function into `readRanksIfAvailable`.

**Comment by mimowo** [comment]
> The initial pod assignments would be [node1, node2]. After node1 failure and node replacement the topology assignment would be [node2, node3] where the pod on node2 would be running undisrupted so the replacement pod should be scheduled on node3, but the terminating pod was deleted quickly enough so it was assigned nodeSelectors for node2 because of its job labels (index 0).
Usually that doesn't happen because the terminating pod exists and has a conflicting job label and because of that there is fallback to the greedy assignment.

Thank you for explaining. This makes sense, I will add comments to individual lines to make it more clear. I can see that the node how swap `[node2, node3]` is correct. What is faulty is the better "conflict" detection and fallback to the non-rank based algorithm. In the future we may need some knob for the NodeHotSwap to evict even if replace is possible, because some Jobs will not be able to tolerate the "out-of-order" placement after the NodeHotSwap.

> I think that's even a worse scenario because it would trigger the bug.
Also when there are problems with kubelet on the node it might take some more time to mark the pod as terminated.

If there is no kubelet running to transition the nodes to terminated state, then we have a bigger problem. To mitigate that we have already developed the Failure Recovery: https://kueue.sigs.k8s.io/docs/tasks/manage/setup_failure_recovery/.

File: pkg/controller/tas/topology_ungater.go [hunk 6]
```diff
@@ -440,6 +430,25 @@ func readRanksIfAvailable(log logr.Logger,
 		}
 		return nil, false
 	}
+
+	for rank, pod := range result {
+		if utilpod.HasGate(pod, kueue.TopologySchedulingGate) {
+			continue
+		}
+		if rank >= len(rankToDomainID) {
```
Comment (mimowo) [inline pkg/controller/tas/topology_ungater.go]: IIUC this should never happen, or do you see a scenario when it might? If this is an anomaly we should log that.

Comment (j-skiba) [reply pkg/controller/tas/topology_ungater.go]: it's redundant. I removed that

File: pkg/controller/tas/topology_ungater.go [hunk 7]
```diff
@@ -440,6 +430,25 @@ func readRanksIfAvailable(log logr.Logger,
...
+			continue
+		}
+		expectedDomainID := rankToDomainID[rank]
+		levelKeys := psa.TopologyAssignment.Levels
+		podLevelValues := utiltas.LevelValues(levelKeys, pod.Spec.NodeSelector)
+		podDomainID := utiltas.DomainID(podLevelValues)
+
+		if expectedDomainID != podDomainID {
+			log.V(3).Info("Topology assignment mismatch for running pod", "pod", klog.KObj(pod), "rank", rank, "expectedDomainID", expectedDomainID, "actualDomainID", podDomainID)
```
Comment (mimowo) [inline pkg/controller/tas/topology_ungater.go]:
```suggestion
			log.V(3).Info("There is a mismatch for a running pod between the domain expected based on the rank-based ordering, and the actual node selectors", "pod", klog.KObj(pod), "rank", rank, "expectedDomainID", expectedDomainID, "actualDomainID", podDomainID)
```

File: test/integration/singlecluster/tas/tas_test.go (hunk 5 above)
Comment (mimowo) [reply test/integration/singlecluster/tas/tas_test.go:1685]: Ok please add a comment to describe the screnario simulated by the integration test. Along the lines of the description in https://github.com/kubernetes-sigs/kueue/pull/9211#issuecomment-3907107596. Ofc adjust node names, etc.

**Comment by mimowo** [comment]
This PR is going to be cherrypicked, let's squash the commits before merging, for the ease of cherrypicking.

File: test/integration/singlecluster/tas/tas_test.go (hunk 5 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go:1685]: done

**Comment by j-skiba** [comment]
@mimowo commits are squashed

File: pkg/util/tas/tas_assignment.go [hunk 8]
```diff
@@ -130,6 +130,22 @@ func InternalFrom(ta *kueue.TopologyAssignment) *TopologyAssignment {
 	}
 }
 
+func RankToDomainID(ta *kueue.TopologyAssignment) []TopologyDomainID {
```
Comment (tenzen-y) [inline pkg/util/tas/tas_assignment.go]: I think that this commonized function could be removed and move the mechanism to the original space because we execute these steps only once.

Comment (j-skiba) [reply pkg/util/tas/tas_assignment.go]: done

**Comment by tenzen-y** [comment]
@j-skiba could you address the above format issue?

File: test/integration/singlecluster/tas/tas_test.go [hunk 9]
```diff
@@ -1678,6 +1681,81 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
 					}, util.Timeout, util.Interval).Should(gomega.Succeed())
 				})
 			})
+			// Fixes #9210
```
Comment (tenzen-y) [inline test/integration/singlecluster/tas/tas_test.go]:
```suggestion
			// Fixes https://github.com/kubernetes-sigs/kueue/issues/9210
```

nits.

Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: fixed

File: pkg/controller/tas/topology_ungater.go
Comment (tenzen-y) [inline pkg/controller/tas/topology_ungater.go:1]: This is just a confirmation.

Based on my understanding, you didn't add the UTs to topology_ungater_test.go since greedy assignment is not stable, and it's challenging to verify the exact Node-Pod assignment match, right?

**Comment by mimowo** [comment]
/release-note-edit
```release-note
TAS: fix a bug where NodeHotSwap may assign a Pod, based on rank-ordering, to a node which is already
occupied by another running Pod.
```

File: test/integration/singlecluster/tas/tas_test.go [hunk 10]
```diff
@@ -1678,6 +1681,81 @@ var _ = ginkgo.Describe("Topology Aware Scheduling", ginkgo.Ordered, func() {
...
+						}),
+					))
+				})
+
+				var p1 *corev1.Pod
+				ginkgo.By("creating p1 manually assigned to x3 (assigned to rank 0) but given rank 1 to simulate mismatch", func() {
+					p1 = testingpod.MakePod("p1-running", ns.Name).
+						Annotation(kueue.WorkloadAnnotation, wl1.Name).
+						Annotation(kueue.PodSetRequiredTopologyAnnotation, utiltesting.DefaultBlockTopologyLevel).
+						Label(batchv1.JobCompletionIndexAnnotation, "0"). // rank 1
```
Comment (tenzen-y) [inline test/integration/singlecluster/tas/tas_test.go]:
```suggestion
						Label(batchv1.JobCompletionIndexAnnotation, "1"). // rank 1
```

Is it `1` because p1 is a rank 1 Pod, right?

**Comment by tenzen-y** [comment]
Otherwise LGTM from my PoV.

File: pkg/controller/tas/topology_ungater.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/tas/topology_ungater.go:515]: thx for the comment, it makes sense

File: test/integration/singlecluster/tas/tas_test.go (hunk 10 above)
Comment (j-skiba) [reply test/integration/singlecluster/tas/tas_test.go]: that's right, jobset pod would have `1` here, fixed that

File: pkg/controller/tas/topology_ungater.go
Comment (j-skiba) [reply pkg/controller/tas/topology_ungater.go:1]: actually, I think I lost a unit test when I was squashing commits, I brought the test back.

**Comment by mimowo** [comment]
/lgtm
/approve
Thank you 👍
