### PR TITLE
[FairSharing] Use flavor based borrowing information in entire root cohort - CQ tree when deciding if a workload needs borrowing

### LINKED ISSUE #10126: [Fair Sharing] Incorrect admission ordering with FairSharingPrioritizeNonBorrowing
**What happened**:

Suppose the following structure

```
- Root-Cohort
  - Cohort-A (10 CPUs)
    - CQ-A
  - Cohort-B
    - CQ-B (5 CPUs)
    - CQ-C
```

Then:

```
- submit 10cpu workload to CQ-C
- workload admits to CQ-C
- submit 5 cpu workload to each of CQ-A and CQ-B
- workload from CQ-B admits
```

**What you expected to happen**:
workload from CQ-A should admit, as Cohort-A is not borrowing, while Cohort-B is.

**How to reproduce it (as minimally and precisely as possible)**:
See (LLM generated) test case: https://github.com/kubernetes-sigs/kueue/commit/be3e92c984ce93b772f557200d6e1e36ae84d45b

```
go test ./pkg/scheduler/ -run "TestSchedule/with_fair_sharing:_hierarchical_nominal-first" -count=1
```

This test passes with flag disabled.

**Anything else we need to know?**:
See #9484 for definition of this flag

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mukund-wayve**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fixes `FairSharingPrioritizeNonBorrowing` in hierarchical cohorts by checking borrowing at every level of the cohort tree (CQ to root), not just at the CQ level. The check is per-flavor: a subtree borrowing on one flavor does not penalize workloads requesting a different flavor where the subtree has ample quota. The DRS struct now exposes which FlavorResources are borrowed, enabling callers to query borrowing against any set of flavors.

#### Which issue(s) this PR fixes:

Fixes #10126 

#### Does this PR introduce a user-facing change?

```release-note
FairSharing: Fix `FairSharingPrioritizeNonBorrowing` to check per-flavor borrowing at every hierarchy level in hierarchical cohorts, not just at the ClusterQueue level.
```

### CODE REVIEW

File: pkg/cache/scheduler/fair_sharing.go [hunk 1]
```diff
@@ -47,13 +47,21 @@ type DRS struct {
...
+	// currently borrowing on.
+	borrowedFRs []resources.FlavorResource
 }
 
 // NegativeDRS is used as a starting point for comparisons.
 func NegativeDRS() DRS {
 	return DRS{unweightedRatio: -1, dominantResource: "", fairWeight: defaultWeight}
 }
 
+// BorrowingDRS returns a DRS that is borrowing on the given FlavorResources.
```
Comment (mwielgus) [inline pkg/cache/scheduler/fair_sharing.go]: This seems to be a test utility. Consider moving it to some test utility file.

File: pkg/scheduler/fair_sharing_iterator.go [hunk 2]
```diff
@@ -161,27 +162,35 @@ type drsKey struct {
...
-	// CQ's nominal entitlement on another flavor.
+	aDrs := e.drsValues[drsKey{parentCohort: parentCohort, workloadKey: workload.Key(a.Obj)}]
+	bDrs := e.drsValues[drsKey{parentCohort: parentCohort, workloadKey: workload.Key(b.Obj)}]
+
 	if features.Enabled(features.FairSharingPrioritizeNonBorrowing) {
-		aRequiresBorrowing := a.assignment.RequiresBorrowing()
-		bRequiresBorrowing := b.assignment.RequiresBorrowing()
-		if aRequiresBorrowing != bRequiresBorrowing {
-			return !aRequiresBorrowing
+		// 1. Per-flavor subtree non-borrowing: prefer workloads whose
```
Comment (mwielgus) [inline pkg/scheduler/fair_sharing_iterator.go]: Maybe update KEP/docs as well?

File: pkg/scheduler/scheduler_test.go
Comment (mwielgus) [inline pkg/scheduler/scheduler_test.go:10968]: @mimowo @gabesaba - this file is growing way too large.

Comment (mimowo) [reply pkg/scheduler/scheduler_test.go:10968]: agree, opened the issue https://github.com/kubernetes-sigs/kueue/issues/10166 to track it independently

**Comment by mimowo** [comment]
cc @pajakd ptal

File: pkg/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -3110,6 +3110,653 @@ func TestSchedule(t *testing.T) {
...
+			},
+			wantLeft: map[kueue.ClusterQueueReference][]workload.Reference{
+				"cq-b": {"eng-alpha/wl-b"},
+			},
+		},
+		//            ROOT
+		//       /            \
+		// COHORT-A (6/18)    COHORT-B (20/18)
+		//   /         \        /         \
+		// cq-a1 (0/5) cq-a2 (6/3)  cq-b (0/5) cq-c (20/3)
```
Comment (pajakd) [inline pkg/scheduler/scheduler_test.go]: Add some whitespaces to fix the picture (looks as if `cq-a2` belonged to both cohorts :) ).

File: pkg/scheduler/scheduler_test.go [hunk 4]
```diff
@@ -3110,6 +3110,653 @@ func TestSchedule(t *testing.T) {
...
+		//       admitted: 5 spot           admitted: 8 on-demand
+		//
+		// Shown as (usage/subtreeQuota). Both cohorts borrow from
+		// ROOT, but on different flavors.
+		// After pending workloads (both request on-demand):
+		// wl-a (cq-a, 3 on-demand) -> COHORT-A on-demand (3/10), not borrowing
+		// wl-b (cq-b, 3 on-demand) -> COHORT-B on-demand (11/5), borrowing
+		//
+		// Per-flavor gate prefers wl-a: COHORT-A is not borrowing
+		// on-demand despite borrowing spot.
```
Comment (pajakd) [inline pkg/scheduler/scheduler_test.go]: I don't see what is this test testing. We have 7 units of on-demand available and two workloads asking for 3 each. Both of them get in. Even if the preference was the other way around (wl-b preferred over wl-a), the outcome would be the same, no? I think two workload asking for 4 units each would test what we want (see that wl-a gets in and wl-b stays pending).

File: pkg/cache/scheduler/fair_sharing_test.go [hunk 5]
```diff
@@ -831,3 +831,100 @@ func TestDominantResourceShare(t *testing.T) {
...
+		usage                    resources.FlavorResourceQuantities
+		requestedFRs             resources.FlavorResourceQuantities
+		wantBorrowingOnRequested bool
+		wantBorrowing            bool
+	}{
+		"borrows on requested flavor": {
+			usage:                    resources.FlavorResourceQuantities{cpuDefault: 3_000},
+			requestedFRs:             resources.FlavorResourceQuantities{cpuDefault: 1_000},
+			wantBorrowingOnRequested: true,
+			wantBorrowing:            true,
```
Comment (pajakd) [inline pkg/cache/scheduler/fair_sharing_test.go:851]: perhaps give context (quota values) in a comment somewhere higher to make it easier to understand the testcases.

File: pkg/scheduler/fair_sharing_iterator.go [hunk 6]
```diff
@@ -208,22 +217,27 @@ func (e *entryComparer) less(a, b *entry, parentCohort kueue.CohortReference) bo
...
 			continue
 		}
+		usage := entry.assignmentUsage()
 		// We add workload's usage to CQ, so that all
 		// subsequent DRS include the admission of workload.
-		revert := cq.SimulateUsageAddition(entry.assignmentUsage())
+		revert := cq.SimulateUsageAddition(usage)
+
+		wlKey := workload.Key(entry.Obj)
+		e.requestedFRs[wlKey] = usage.Quota
```
Comment (pajakd) [inline pkg/scheduler/fair_sharing_iterator.go]: Shouldn't this be behind the featuregate? (I know that reading of this is so perhaps writing should be too)

File: pkg/scheduler/scheduler_test.go (hunk 4 above)
Comment (mukund-wayve) [reply pkg/scheduler/scheduler_test.go]: Good catch. I've change it to 4 and now we can see what wl-b is pending while wl-a gets in

File: pkg/cache/scheduler/fair_sharing_test.go (hunk 5 above)
Comment (mukund-wayve) [reply pkg/cache/scheduler/fair_sharing_test.go:851]: Done

File: pkg/scheduler/fair_sharing_iterator.go (hunk 6 above)
Comment (mukund-wayve) [reply pkg/scheduler/fair_sharing_iterator.go]: Done

File: pkg/cache/scheduler/fair_sharing.go (hunk 1 above)
Comment (mukund-wayve) [reply pkg/cache/scheduler/fair_sharing.go]: done

File: pkg/scheduler/fair_sharing_iterator.go (hunk 2 above)
Comment (mimowo) [reply pkg/scheduler/fair_sharing_iterator.go]: ai think we could update the fair sharing KEP with handling the special case

Comment (mukund-wayve) [reply pkg/scheduler/fair_sharing_iterator.go]: Done
