### PR TITLE
[Dev mode] Trying to reuse a newly created cluster fails

### LINKED ISSUE #8780: [Dev mode] Trying to reuse a newly created cluster fails
**What happened**:

I tried to run `E2E_MODE=dev make kind-image-build test-e2e` twice (with tests focused), but it fails on the second attempt.

**What you expected to happen**:

Re-run e2e tests on a cluster created by the previous run

**How to reproduce it (as minimally and precisely as possible)**:

1. Mark some test as focused using "FIt"
2. Run `E2E_MODE=dev make kind-image-build test-e2e` all good
3. Rerun `E2E_MODE=dev make kind-image-build test-e2e` fails with `error: SchemaError(sigs.k8s.io/kueue/apis/visibility/v1beta1.PendingWorkloadsSummary.items): unknown model in reference: "sigs.k8s.io~1kueue~1apis~1visibility~1v1beta1.PendingWorkload"`

**Anything else we need to know?**:

This is a follow up to https://github.com/kubernetes-sigs/kueue/issues/8093

### PR DESCRIPTION
**Pull request by vladikkuzn**
#### What type of PR is this?
/kind regression

#### What this PR does / why we need it:
To be able to reinstall kueue

#### Which issue(s) this PR fixes:

Fixes #8780

#### Special notes for your reviewer:
- KubeRay re-installation (since it's only available via `kubectl create`)
- Fix of unbound variable for mac (kubeconfig_args[@])

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/singlecluster/aggregated_openapi_test.go [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+		gomega.Eventually(func(g gomega.Gomega) {
+			doc, err := discoveryClient.OpenAPISchema()
+			g.Expect(err).NotTo(gomega.HaveOccurred())
+
+			// This is the same reference validation used by kubectl's OpenAPI schema loader.
+			_, err = proto.NewOpenAPIData(doc)
+			g.Expect(err).NotTo(gomega.HaveOccurred())
+		}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+	})
+})
```
Comment (vladikkuzn) [inline test/e2e/singlecluster/aggregated_openapi_test.go:48]: This is the problem
Is there any way to solve it without disabling client side validation?

File: hack/e2e-common.sh [hunk 2]
```diff
@@ -625,7 +631,7 @@ function upgrade_test_flow {
     curl -sL "${KUEUE_OLD_VERSION_MANIFEST}" | \
       sed "s|registry.k8s.io/kueue/kueue:${old_version}|${old_image}|g" | \
       sed 's|imagePullPolicy: Always|imagePullPolicy: IfNotPresent|g' | \
-      kubectl apply --server-side -f -
+      kubectl apply --server-side --validate=false -f -
```
Comment (vladikkuzn) [inline hack/e2e-common.sh]: The solution: disable client side validation `--validate=false`

File: test/e2e/singlecluster/aggregated_openapi_test.go (hunk 1 above)
Comment (mimowo) [reply test/e2e/singlecluster/aggregated_openapi_test.go:48]: Thank you for investigating and reporting the problem!

File: hack/e2e-common.sh (hunk 2 above)
Comment (mimowo) [reply hack/e2e-common.sh]: IIUC this is only needed for pre-existing clusters, so it would be better to use it only then.

File: test/e2e/singlecluster/aggregated_openapi_test.go (hunk 1 above)
Comment (mimowo) [reply test/e2e/singlecluster/aggregated_openapi_test.go:48]: IIUC this could also affect our users who want to deploy a new version of Kueue on an existing cluster, wdyt? I'm wondering this wasn't an issue in the past, do you know if something has changed?

File: apis/visibility/openapi/zz_generated.openapi.go
Comment (vladikkuzn) [inline apis/visibility/openapi/zz_generated.openapi.go:1]: `make verify` doesn't regenerate it, so on which stage is this file regenerated?

File: hack/e2e-common.sh
Comment (mbobrovskyi) [inline hack/e2e-common.sh:1]: I think we can split this PR. Could we move the OpenAPI fix to a separate PR? We need to cherry-pick only fix into release-0.16.

File: vendor/k8s.io/apimachinery/pkg/api/resource/zz_generated.model_name.go
Comment (mbobrovskyi) [inline vendor/k8s.io/apimachinery/pkg/api/resource/zz_generated.model_name.go:1]: Why this changes?

File: hack/update-codegen.sh [hunk 3]
```diff
@@ -39,6 +39,7 @@ kube::codegen::gen_openapi \
   --boilerplate "${KUEUE_ROOT}/hack/boilerplate.go.txt" \
   --output-dir "${KUEUE_ROOT}/apis/visibility/openapi" \
   --output-pkg "${KUEUE_PKG}/apis/visibility/openapi" \
+  --output-model-name-file "zz_generated.model_name.go" \
```
Comment (mbobrovskyi) [inline hack/update-codegen.sh:42]: Do we need this changes?

**Comment by mimowo** [comment]
Thank you for working on this. IIUC this is a production issue as mentioned in the comment https://github.com/kubernetes-sigs/kueue/issues/8780#issuecomment-3818993262, and the related issue by @tenzen-y https://github.com/kubernetes-sigs/kueue/issues/8873, so please add a release note. I think we will need to cherrypick this one to 0.16.x.

File: hack/update-codegen.sh (hunk 3 above)
Comment (vladikkuzn) [reply hack/update-codegen.sh:42]: Yes, this is the change to get the model names generated

Comment (mbobrovskyi) [reply hack/update-codegen.sh:42]: I tried running it without this, and it seems to work. Could you please double-check?

Comment (vladikkuzn) [reply hack/update-codegen.sh:42]: https://github.com/kubernetes/code-generator/blob/5646ad859d2ac6e7246b304f5d6ec62b89d5b8cc/examples/hack/update-codegen.sh#L48

Comment (vladikkuzn) [reply hack/update-codegen.sh:42]: If it's empty it shoudn't be generated https://github.com/kubernetes/kube-openapi/blob/master/cmd/openapi-gen/openapi-gen.go#L55

Comment (mbobrovskyi) [reply hack/update-codegen.sh:42]: Yes, you’re right. Thanks for double-checking. Just one thing: with this line, it also generates files for the vendor directory. Can we ignore vendor?

**Comment by mimowo** [comment]
Thank you for working on this 👍 
/approve
LGTM, but leaving tagging to @mbobrovskyi

File: hack/e2e-common.sh [hunk 4]
```diff
@@ -117,15 +117,18 @@ function cluster_collect_artifacts {
     local name=$1
     local kubeconfig=${2:-}
 
-    local kubeconfig_args=()
     if [[ -n "${kubeconfig}" ]]; then
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh:174]: Can we keep arg required?

File: hack/e2e-common.sh [hunk 5]
```diff
@@ -485,10 +484,29 @@ function install_mpi {
...
+    # "kubectl create -k" is used instead of apply (https://github.com/ray-project/kuberay/issues/504),
+    # but it is not idempotent: it exits non-zero if any objects already exist.
+    #
+    # For dev reruns, we want idempotence:
+    # - if KubeRay looks fully installed, skip
+    if [[ "${E2E_MODE}" == "dev" ]]; then
+        if kubectl get deployment "$kubeconfig_arg" kuberay-operator -n default >/dev/null 2>&1; then
+            echo "KubeRay operator deployment already exists; skipping install (E2E_MODE=dev)."
+            return 0
+        fi
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh]: IIUC, we’re skipping creation of the KubeRay operator if it already exists. Should we remove and recreate it in that case? It would be great to do that only when the version has changed.

Comment (mimowo) [reply hack/e2e-common.sh]: We can, otoh the development clusters aren't really "long living", so I expect developers to be fine to re-create a cluster when a new version of KubeRay is released :) I consider this mode mostly for quick re-run of Kueue tests.

So, TBH, I wouldn't worry about it, we can always improve if proven useful for someone.

**Comment by mimowo** [comment]
/lgtm
I have already tested this locally to provision and re-run e2e tests for TAS, thank you 👍 

I think this is a reasonable ask https://github.com/kubernetes-sigs/kueue/pull/8805#discussion_r2746311325 but we can cover in a follow up / when needed.

**Comment by mimowo** [comment]
/hold
Actually this worked because I commented out installing some of the controllers, when I tried unconmmenting installtion of all controllers, then it failed on mpi controller:

```
namespace/mpi-operator serverside-applied
customresourcedefinition.apiextensions.k8s.io/mpijobs.kubeflow.org serverside-applied
serviceaccount/mpi-operator serverside-applied
clusterrole.rbac.authorization.k8s.io/kubeflow-mpijobs-edit serverside-applied
clusterrole.rbac.authorization.k8s.io/kubeflow-mpijobs-view serverside-applied
clusterrole.rbac.authorization.k8s.io/mpi-operator serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/mpi-operator serverside-applied
deployment.apps/mpi-operator serverside-applied
error: Apply failed with 1 conflict: conflict with "clusterrole-aggregation-controller": .rules
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
Set the current-context in a kubeconfig file.

Aliases:
use-context, use

Examples:
  # Use the context for the minikube cluster
  kubectl config use-context minikube
```

**Comment by mimowo** [comment]
@vladikkuzn it could be great if you can also look into the issue with reusing cluster when mpicontroller is installed

**Comment by vladikkuzn** [comment]
> @vladikkuzn it could be great if you can also look into the issue with reusing cluster when mpicontroller is installed

Indeed, there's:
```
deployment.apps/mpi-operator serverside-applied
error: Apply failed with 1 conflict: conflict with "clusterrole-aggregation-controller": .rules
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
```
Taking a look

UPD: This is the problem: https://github.com/fluxcd/flux2/issues/2472#issuecomment-1862770622

**Comment by vladikkuzn** [comment]
I think it's better to fix in the upstream: https://github.com/kubeflow/mpi-operator/pull/766
Or even open a pr in k8s/k8s for ClusterRole

In the meanwhile prepared a workaround in this PR
/cc @tenzen-y

**Comment by mimowo** [comment]
Thank you, I was using this mode e2e test mode a little bit recently. 

One observation is that it takes quite a while to load all the images for all the kind workers, especially if one is doing the TAS e2e tests. So, I always need to find code in the bash scrips to comment out the section for installing the operators (MPI, Ray etc). I would be ok to install them once.

So, I'm thinking it would be better, by default, to skip loading the images completely if the operator is already running on the cluster? I think it is fair to assume just rebuilding Kueue is the main use-case, and optimize for it. 

It could be a follow up, but IIUC this approach would also help with MPIJOb - instead of updating just skip installing, wdyt?

**Comment by vladikkuzn** [comment]
@mimowo Yeah, I think it's not so common that you need to update external(non-kueue) operators every time

**Comment by mimowo** [comment]
> @mimowo Yeah, I think it's not so common that you need to update external(non-kueue) operators every time

Yeah, that is my thinking too. I think this should rather be some extra option, like "E2E_ENFORE_OPERATOR_UPDATE", but I think the default behavior should be just skip all the steps, because they are costly, and so we need to comment out the code anyway.

**Comment by vladikkuzn** [comment]
I've added the E2E_ENFORCE_OPERATOR_UPDATE flag to force-install CRDs
It uses `kube-system/e2e-operator-cache` configmap to store which operators are installed to keep the state between runs. If needed, I can store operator versions to this configmap and update operator on version change

File: hack/e2e-common.sh [hunk 6]
```diff
@@ -290,39 +357,89 @@ function kind_load {
         cluster_kind_load "$1"
     fi
     if [[ -n ${APPWRAPPER_VERSION:-} && ("$GINKGO_ARGS" =~ feature:appwrapper || ! "$GINKGO_ARGS" =~ "--label-filter") ]]; then
-        install_appwrapper "$1" "$2"
+        if e2e_should_skip_operator "appwrapper" "$2"; then
+            echo "AppWrapper already installed; skipping install (E2E_MODE=dev)."
+        else
+            install_appwrapper "$1" "$2"
+            e2e_record_operator_installed "appwrapper" "$2"
```
Comment (mimowo) [inline hack/e2e-common.sh]: I'm not sure how this works. Is this cache just "in memory"? Then essentially we will install all the operators anyway, unless I'm missing something. 

I was thinking we will detect if the operator is installed by checking for example if the deployment exists.

Comment (vladikkuzn) [reply hack/e2e-common.sh]: It uses kube-system/e2e-operator-cache configmap to store which operators are installed, so the state is persisted in the k8s

Comment (mimowo) [reply hack/e2e-common.sh]: Nice, I didn't know. So this is ok I think.

**Comment by mimowo** [comment]
/approve
Let me ask for review @mbobrovskyi or maybe @IrvingMg

File: Makefile-test.mk [hunk 7]
```diff
@@ -48,6 +48,8 @@ E2E_RUN_ONLY_ENV ?= false
 E2E_USE_HELM ?= false
 E2E_MODE ?= ci
 KUEUE_UPGRADE_FROM_VERSION ?= v0.14.8
+# When truthy, force re-installing external operators (MPI, Ray, etc.) on each run, even in E2E_MODE=dev.
+E2E_ENFORCE_OPERATOR_UPDATE ?=
```
Comment (mbobrovskyi) [inline Makefile-test.mk]:
```suggestion
E2E_ENFORCE_OPERATOR_UPDATE ?= false
```
?

File: hack/e2e-common.sh [hunk 8]
```diff
@@ -117,15 +184,15 @@ function cluster_collect_artifacts {
     local name=$1
     local kubeconfig=${2:-}
 
-    local kubeconfig_args=()
+    local -a kubectl_args=()
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh:173]: Oh, it's a lot of changes... I'm wondering if we can move this changes in separate PR. WDYT?

File: hack/e2e-common.sh [hunk 9]
```diff
@@ -30,8 +30,75 @@ if [[ "${E2E_MODE}" != "ci" && "${E2E_MODE}" != "dev" ]]; then
...
+    marker=$(e2e_operator_cache_get "${key}" "${kubeconfig}")
+    [[ -n "${marker}" ]]
+}
+
+function e2e_record_operator_installed {
+    local key=$1
+    local kubeconfig=${2:-}
+
+    e2e_operator_cache_set_installed "${key}" "${kubeconfig}"
+}
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh]: Why this wrapper?

File: hack/e2e-common.sh [hunk 10]
```diff
@@ -30,8 +30,75 @@ if [[ "${E2E_MODE}" != "ci" && "${E2E_MODE}" != "dev" ]]; then
...
+    local -a kubectl_args=()
+    if [[ -n "${kubeconfig}" ]]; then
+        kubectl_args+=(--kubeconfig="${kubeconfig}")
+    fi
+
+    # Ensure the ConfigMap exists (idempotent).
+    kubectl ${kubectl_args[@]+"${kubectl_args[@]}"} -n "${E2E_OPERATOR_CACHE_NAMESPACE}" \
+        create configmap "${E2E_OPERATOR_CACHE_CONFIGMAP}" \
+        --from-literal=initialized=true \
+        --dry-run=client -o yaml \
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh]: What’s the idea behind this? If we use --dry-run=client, it’s not executed on the server side, so we would have to apply it on every run, right?

File: hack/e2e-common.sh (hunk 8 above)
Comment (vladikkuzn) [reply hack/e2e-common.sh:173]: https://github.com/kubernetes-sigs/kueue/pull/9001

File: hack/e2e-common.sh (hunk 10 above)
Comment (vladikkuzn) [reply hack/e2e-common.sh]: - kubectl create configmap ... --dry-run=client -o yaml: does not create anything in the cluster; it renders the ConfigMap manifest to stdout as YAML.
- Pipe into kubectl apply ... -f -: apply consumes that YAML and creates it if it doesn’t exist or reconciles it if it already exists → that’s the idempotency (unlike plain kubectl create, which would error on “AlreadyExists”).
- --from-literal=initialized=true: ensures the ConfigMap has at least one stable .data entry even before any operator-specific keys are patched in later.

File: hack/e2e-common.sh [hunk 11]
```diff
@@ -324,39 +384,89 @@ function kind_load {
...
         # In order for MPI-operator and Training-operator to work on the same cluster it is required that:
         # 1. 'kubeflow.org_mpijobs.yaml' is removed from base/crds/kustomization.yaml - https://github.com/kubeflow/training-operator/issues/1930
         # 2. Training-operator deployment is modified to enable all kubeflow jobs except for mpi -  https://github.com/kubeflow/training-operator/issues/1777
-        install_kubeflow "$1" "$2"
+        if e2e_should_skip_operator "kubeflow-training-operator" "$2"; then
+            echo "Kubeflow Training Operator already installed; skipping install (E2E_MODE=dev)."
+        else
+            install_kubeflow "$1" "$2"
+            e2e_operator_cache_set_installed "kubeflow-training-operator" "$2"
+        fi
```
Comment (mimowo) [inline hack/e2e-common.sh]: This pattern seems to repeat. I would prefer to deduplicate with a helper function like `e2e_ensure_operator_installed`, eg. e2e_ensure_operator_installed "kubeflow-training-operator". Then the helper found dispatch to install_mpi and so on.

File: hack/e2e-common.sh (hunk 10 above)
Comment (vladikkuzn) [reply hack/e2e-common.sh]: ### Can `kubectl create ... || true` be used?

**It can, but it’s weaker and a bit riskier** than the current `--dry-run | apply` pattern.

- **What it does well**: if the ConfigMap is missing, it creates it; if it already exists, `kubectl create` fails with `AlreadyExists` and `|| true` suppresses that, so the script continues.
- **Main downsides**:
  - **It masks real failures** too (RBAC denial, wrong kubeconfig/context, API timeout, etc.), not just `AlreadyExists`. You’ll only notice later when the `patch` fails (or worse, something silently doesn’t get set).
  - **It won’t “repair” an existing ConfigMap** to ensure `data.initialized=true` is present. The current `apply` form will enforce that field.

If you wanted the “create only if missing” behavior without masking errors, you’d typically do a conditional check (`get` then `create`), but the current `apply` approach is the usual clean idempotent way.

### Does the current version override the ConfigMap on the second run?

**No, it doesn’t “replace” the whole ConfigMap.**

- `kubectl create ... --dry-run=client -o yaml` **does not touch the cluster**; it only generates YAML.
- Piping into `kubectl apply --server-side -f -` will **create if missing** or **merge** the declared fields if it exists.
- In your case, that manifest only declares **one key**: `data.initialized=true`. On subsequent runs it will keep that key set, and **it will not wipe other `data` keys** that were added later (like `data.${key}=installed` from the `patch`), because server-side apply tracks field ownership at the map-key level.

File: hack/e2e-common.sh (hunk 11 above)
Comment (vladikkuzn) [reply hack/e2e-common.sh]: Extracted to a helper, let me know if it looks better

File: hack/e2e-common.sh [hunk 12]
```diff
@@ -30,8 +30,121 @@ if [[ "${E2E_MODE}" != "ci" && "${E2E_MODE}" != "dev" ]]; then
     exit 2
 fi
 
+# When set (truthy), external operators are forcefully re-installed even in E2E_MODE=dev.
+export E2E_ENFORCE_OPERATOR_UPDATE="${E2E_ENFORCE_OPERATOR_UPDATE:-}"
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh]:
```suggestion
export E2E_ENFORCE_OPERATOR_UPDATE="${E2E_ENFORCE_OPERATOR_UPDATE:-false}"
```

File: hack/e2e-common.sh [hunk 13]
```diff
@@ -320,43 +433,46 @@ function cluster_kind_load {
 function kind_load {
     kubectl config --kubeconfig="$2" use-context "kind-$1"
 
+    local e2e_cluster_name=$1
+    local e2e_kubeconfig=$2
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh:377]: Do we need this?

Comment (mbobrovskyi) [reply hack/e2e-common.sh:377]: Actually, why we don't propagate it?

File: hack/e2e-common.sh (hunk 11 above)
Comment (mimowo) [reply hack/e2e-common.sh]: It looks much better , thank you 👍

File: hack/e2e-common.sh (hunk 13 above)
Comment (vladikkuzn) [reply hack/e2e-common.sh:377]: It's propagated but not explicitly: 
```
local cluster_name=${2:-${e2e_cluster_name:-}}
local kubeconfig=${3:-${e2e_kubeconfig:-}}
```

**Comment by mimowo** [comment]
/hold
@vladikkuzn please confirm experimentally it works well. I just tried on a new cluster. No JobSet installed, but I got message `JobSet already installed; skipping install (E2E_MODE=dev).`, and the tests failed 

```
 STEP: Checking no restarts for the controller: "kueue-system/kueue-controller-manager" @ 02/06/26 12:08:34.911
  "level"=0 "msg"="Deployment is available" "deployment"={"name"="kueue-controller-manager" "namespace"="kueue-system"} "noRestarts"=true "waitingTime"="16.897655ms"
  STEP: Waiting for availability of deployment: "jobset-system/jobset-controller-manager" @ 02/06/26 12:08:34.914
  [FAILED] in [BeforeSuite] - /xyz/go/src/sigs.k8s.io/kueue/test/util/e2e.go:326 @ 02/06/26 12:13:34.916
[BeforeSuite] [FAILED] [300.025 seconds]
[BeforeSuite] 
/xyz/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/suite_test.go:59

  [FAILED] Timed out after 300.001s.
  The function passed to Eventually failed at /xyz/go/src/sigs.k8s.io/kueue/test/util/e2e.go:277 with:
  Expected success, but got an error:
      <*errors.StatusError | 0xc000157b80>: 
      deployments.apps "jobset-controller-manager" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "deployments.apps \"jobset-controller-manager\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "jobset-controller-manager",
                  Group: "apps",
                  Kind: "deployments",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  In [BeforeSuite] at: /xyz/go/src/sigs.k8s.io/kueue/test/util/e2e.go:326 @ 02/06/26 12:13:34.916
------------------------------
[DeferCleanup (Suite)] 
/xyz/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/suite_test.go:70
[DeferCleanup (Suite)] PASSED [0.000 seconds]
```

That was a fresh new cluster created on the first use:
```
Running e2e for k8s 1.33.4
E2E_KIND_VERSION="kindest/node:v1.33.4" KIND_CLUSTER_NAME=kind \
	ARTIFACTS="/xyz/go/src/sigs.k8s.io/kueue/bin/run-test-e2e-singlecluster-1.33.4" IMAGE_TAG=us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue:v0.17.0-devel-79-g4771f81ff-dirty GINKGO_ARGS="" \
	E2E_MODE=dev \
	E2E_ENFORCE_OPERATOR_UPDATE=false \
	APPWRAPPER_VERSION=v1.1.2 \
	JOBSET_VERSION=v0.11.0 \
	KUBEFLOW_VERSION=v1.9.3 \
	KUBEFLOW_TRAINER_VERSION=v2.1.0 \
	LEADERWORKERSET_VERSION=v0.8.0 \
	KUBERAY_VERSION=v1.5.1 RAY_VERSION=2.41.0 RAYMINI_VERSION=0.0.1 USE_RAY_FOR_TESTS="raymini" \
	KIND_CLUSTER_FILE="kind-cluster.yaml" E2E_TARGET_FOLDER="singlecluster" \
	TEST_LOG_LEVEL=-3 \
	E2E_RUN_ONLY_ENV=false \
	E2E_USE_HELM=false \
	./hack/e2e-test.sh
Creating kind cluster (E2E_MODE=dev): kind
registry.k8s.io/e2e-test-images/agnhost@sha256:b
```

**Comment by mimowo** [comment]
Maybe I didn't use the latest version, but it was a version from today. Let me know if it works after latest changes and I just need to update.

**Comment by vladikkuzn** [comment]
I have just confirmed the behaviour @mimowo 

I think you have the following situation:
- `kubectl get -n kube-system cm e2e-operator-cache -o yaml | grep "jobset: installed"` - CM says jobset is installed, but the controller manager deployment `kubectl get deployment -n jobset-system jobset-controller-manager` was deleted manually. As I don't check the controller manager deployment, it fully relies on CM

Run to install jobset:
`E2E_ENFORCE_OPERATOR_UPDATE=true E2E_MODE=dev GINKGO_ARGS="--label-filter=feature:jobset" make kind-image-build test-e2e`

All the subsequent runs won't install jobset:
`E2E_ENFORCE_OPERATOR_UPDATE=false E2E_MODE=dev GINKGO_ARGS="--label-filter=feature:jobset" make kind-image-build test-e2e`

I can try to make it fully rely on the controller manager deployment, if you think it's more reliable choice, then CM

**Comment by mimowo** [comment]
> I have just confirmed the behaviour @mimowo

Awesome, thank you 👍 

>I think you have the following situation:
> kubectl get -n kube-system cm e2e-operator-cache -o yaml | grep "jobset: installed" 

Not really: 

```
❯ kubectl get cm/e2e-operator-cache -n kube-system -oyaml
apiVersion: v1
data:
  appwrapper: installed
  initialized: "true"
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-06T12:08:11Z"
  name: e2e-operator-cache
  namespace: kube-system
  resourceVersion: "668"
  uid: 703520c8-6586-47d7-94ea-09fcc6b2f5e4
```

Let me try again on the "head" of the branch.

**Comment by vladikkuzn** [comment]
Should be like this:
```
> kubectl get cm/e2e-operator-cache -n kube-system -o yaml
apiVersion: v1
data:
  appwrapper: installed
  initialized: "true"
  jobset: installed
  kubeflow-trainer: installed
  kubeflow-training-operator: installed
  kuberay: installed
  leaderworkerset: installed
kind: ConfigMap
metadata:
  ...
```

**Comment by mimowo** [comment]
Re-checking right now

**Comment by vladikkuzn** [comment]
Please let me know if you have any issues

**Comment by mimowo** [comment]
no luck. I deleted the cluster: `kind delete clusters kind`


Then repeated the command: `E2E_MODE=dev make kind-image-build run-test-e2e-singlecluster-1.33.4` and still the same issue, weird. Maybe something on my env, but I'm not sure what. 

Maybe indeed check the actual controller installation, would this be much effort?

**Comment by mimowo** [comment]
Hold on, let me retry, I didn't pull the latest version again.

Sorry for that again, my last commit was from 4th Feb, retrying again on latest.

**Comment by mimowo** [comment]
still no luck on my end, can maybe @mbobrovskyi confirm this works?

But in any case, I agree checking the actual controller, or at least namespace, will be less error prone than using the CM cache. I still have no idea what I'm doing wrong.

**Comment by mbobrovskyi** [comment]
For me the same:

```
apiVersion: v1
data:
  appwrapper: installed
  initialized: "true"
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-06T15:37:31Z"
  name: e2e-operator-cache
  namespace: kube-system
  resourceVersion: "620"
  uid: c7c77417-7a8e-4b94-b27b-aa8ca18ceacc
```

File: hack/e2e-common.sh [hunk 14]
```diff
@@ -30,8 +30,292 @@ if [[ "${E2E_MODE}" != "ci" && "${E2E_MODE}" != "dev" ]]; then
...
+    local force_reinstall=false
+
+    # In E2E_MODE=dev we reuse the kind cluster between runs. Decide whether we can skip an
+    # external operator install by checking the actual controller Deployment (and version).
+    if [[ "${E2E_MODE}" == "dev" ]] && ! e2e_is_truthy "${E2E_ENFORCE_OPERATOR_UPDATE}"; then
+        local ns=""
+        local deploy=""
+        local requested_version=""
+        local image_match=""
+        local installed_version=""
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh]: I’d propose propagating all these arguments from the install_* function. That way, we won’t need all these switch cases. This function should only return a boolean indicating whether installation is needed or not.

File: hack/e2e-common.sh (hunk 13 above)
Comment (mbobrovskyi) [reply hack/e2e-common.sh:377]: Oh, this isn’t obvious.

File: site/content/en/docs/contribution_guidelines/testing.md [hunk 15]
```diff
@@ -134,6 +134,9 @@ E2E_MODE=dev make kind-image-build test-multikueue-e2e
 E2E_MODE=dev GINKGO_ARGS="--until-it-fails" make kind-image-build  test-e2e
 ```
 
+When reusing a kept cluster in `E2E_MODE=dev`, external operators (MPI, KubeRay, etc.) are installed only once.
```
Comment (mbobrovskyi) [inline site/content/en/docs/contribution_guidelines/testing.md:138]:
```suggestion
Note: When reusing a kept cluster in `E2E_MODE=dev`, external operators (MPI, KubeRay, etc.) are installed only once.
```

Or maybe use {{% alert title="Note" color="primary" %}}

WDYT?

File: hack/e2e-common.sh [hunk 16]
```diff
@@ -30,8 +30,78 @@ if [[ "${E2E_MODE}" != "ci" && "${E2E_MODE}" != "dev" ]]; then
     exit 2
 fi
 
+# When set (truthy), external operators are forcefully re-installed_version even in E2E_MODE=dev.
+export E2E_ENFORCE_OPERATOR_UPDATE="${E2E_ENFORCE_OPERATOR_UPDATE:-false}"
+
 export KIND_VERSION="${E2E_KIND_VERSION/"kindest/node:v"/}"
 
+function e2e_is_truthy {
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh:38]: I’m not sure I understand what e2e_is_truthy means. Also, why do we return false when it’s true?

File: hack/e2e-common.sh [hunk 17]
```diff
@@ -30,8 +30,78 @@ if [[ "${E2E_MODE}" != "ci" && "${E2E_MODE}" != "dev" ]]; then
...
+        kubeflow-trainer) echo "Kubeflow Trainer" ;;
+        kubeflow-mpi-operator) echo "Kubeflow MPI operator" ;;
+        leaderworkerset) echo "LeaderWorkerSet" ;;
+        kuberay) echo "KubeRay operator" ;;
+        cert-manager) echo "cert-manager" ;;
+        clusterprofile-crd) echo "ClusterProfile CRD" ;;
+        dra-example-driver) echo "DRA example driver" ;;
+        *) echo "${key}" ;;
+    esac
+}
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh]: Why we need this?

File: hack/e2e-common.sh (hunk 16 above)
Comment (vladikkuzn) [reply hack/e2e-common.sh:38]: Converts "false" to a falsy value

File: site/content/zh-CN/docs/contribution_guidelines/testing.md [hunk 18]
```diff
@@ -134,6 +134,9 @@ E2E_MODE=dev make test-multikueue-e2e
 E2E_MODE=dev GINKGO_ARGS="--until-it-fails" make test-e2e
 ```
 
+当在 `E2E_MODE=dev` 下复用保留的集群时，外部算子（MPI、KubeRay 等）只会安装一次。
+如需在每次运行时强制重新安装它们，请设置 `E2E_ENFORCE_OPERATOR_UPDATE=true`。
```
Comment (vladikkuzn) [inline site/content/zh-CN/docs/contribution_guidelines/testing.md:138]:
```suggestion
{{% alert title="Note" color="primary" %}}
当在 `E2E_MODE=dev` 下复用保留的集群时，外部算子（MPI、KubeRay 等）只会安装一次。
如需在每次运行时强制重新安装它们，请设置 `E2E_ENFORCE_OPERATOR_UPDATE=true`。
{{% /alert %}}
```

Comment (mbobrovskyi) [reply site/content/zh-CN/docs/contribution_guidelines/testing.md:138]: LGTM

**Comment by mimowo** [comment]
/unhold
I confirmed it works as expected (at least in scenarios I tried). I will open some follow up issues

File: hack/e2e-common.sh [hunk 19]
```diff
@@ -320,43 +373,46 @@ function cluster_kind_load {
 function kind_load {
     kubectl config --kubeconfig="$2" use-context "kind-$1"
 
+    local e2e_cluster_name=$1
+    local e2e_kubeconfig=$2
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh:377]: Please revert this function – it doesn’t seem to be required for these changes.

File: hack/e2e-common.sh [hunk 20]
```diff
@@ -471,28 +527,145 @@ function build_and_apply_kueue_manifests {
...
+            local img=""
+            img=$(kubectl --kubeconfig="${kubeconfig}" -n "${ns}" get deployment "${deployment_name}" \
+                -o jsonpath='{.spec.template.spec.containers[?(@.name=="manager")].image}' 2>/dev/null || true)
+            installed_version=$(e2e_image_ref_get_tag "${img}" || true)
+            if [[ -n "${installed_version}" ]] && { [[ -z "${expected_version}" ]] || e2e_versions_match "${installed_version}" "${expected_version}"; }; then
+                echo "AppWrapper already installed (${installed_version}); skipping install (E2E_MODE=dev)."
+                return 0
+            fi
+            if [[ -n "${installed_version}" && -n "${expected_version}" ]]; then
+                echo "AppWrapper installed version (${installed_version}) does not match requested (${expected_version}); upgrading."
```
Comment (mimowo) [inline hack/e2e-common.sh:548]: I think this checking of versions isn't really needed. It makes the code much more complex, and this is for development mode only. Developers can easily just delete cluster and re-create on that occasion. However, I'm ok with that since already done, but we may need to simplify if this causes issues.

**Comment by mimowo** [comment]
/lgtm
/approve
Thank you 👍

**Comment by mimowo** [comment]
To address remaining comment from @mbobrovskyi : https://github.com/kubernetes-sigs/kueue/pull/8805#discussion_r2781154109 (and maybe more)

File: hack/e2e-common.sh [hunk 21]
```diff
@@ -471,28 +527,145 @@ function build_and_apply_kueue_manifests {
 # $1 cluster name
 # $2 kubeconfig option
 function install_appwrapper {
```
Comment (mbobrovskyi) [inline hack/e2e-common.sh:529]: I think we can extract this logic into a shared function since the logic is fairly common, but I’m fine addressing it in a follow-up.

File: hack/e2e-common.sh (hunk 19 above)
Comment (mimowo) [reply hack/e2e-common.sh:377]: Hm, even if not required is seems ok to improve readabiliy

**Comment by mimowo** [comment]
/unhold
Ok, I checked the PR and it looks reasonable, let's move forward

**Comment by mimowo** [comment]
Ok I recorded some nice to have follow ups I found when using the DEV mode:
- https://github.com/kubernetes-sigs/kueue/issues/9063
- https://github.com/kubernetes-sigs/kueue/issues/9052

ptal

File: hack/e2e-common.sh (hunk 19 above)
Comment (mbobrovskyi) [reply hack/e2e-common.sh:377]: Created follow-up PR https://github.com/kubernetes-sigs/kueue/pull/9064.

File: site/content/zh-CN/docs/contribution_guidelines/testing.md (hunk 18 above)
Comment (mbobrovskyi) [reply site/content/zh-CN/docs/contribution_guidelines/testing.md:138]: Created follow-up https://github.com/kubernetes-sigs/kueue/pull/9065.

File: hack/e2e-common.sh (hunk 19 above)
Comment (mimowo) [reply hack/e2e-common.sh:377]: Thanks 👍
