### PR TITLE
[workload] Get default resource values from LimitRanges

### LINKED ISSUE #541: Consider LimitRanges when calculating Workload usage
**What would you like to be added**:

Administrators can setup [LimitRanges](https://kubernetes.io/docs/concepts/policy/limit-range/#constraints-on-resource-limits-and-requests) per namespace to set default requests for Pods.

We should consider these defaults when creating a Workload.
It can be done in the Workload webhook so that it applies to any custom job, similar to #316.

Caveat: if a LimitRange is created after the Workload object is created, we will not have an accurate calculation of requests.

This issue is an spinoff from #485

**Why is this needed**:

LimitRanges are a common tool for admins to set defaults for a namespace.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

### LINKED ISSUE #590: Kueue deletes workloads for jobs with limits, but no requests
**What happened**:

Kueue creates and deletes in a loop (the cycle is <1s) a workload for a job with limits, but without requests.

**What you expected to happen**:

Kueue does not delete the workloads and allows the jobs to complete.

**How to reproduce it (as minimally and precisely as possible)**:

0. Setup Kueue with the `main` local queue
1. Create a job from the yaml
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-longrun-only-limits
  annotations:
    kueue.x-k8s.io/queue-name: main
spec:
  suspend: true
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: job-longrun
        image: centos:7
        resources:
          limits:
            cpu: 100m
            memory: "200Mi"
        command: ["bash"]
        args: ["-c", 'sleep 120 && echo "Hello world"']
        imagePullPolicy: IfNotPresent
  backoffLimit: 0
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master (before 1.27)
- Kueue version (use `git describe --tags --dirty --always`): master (before 0.3.0)
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Add the possibility to use default workload resource values based on [LimitRanges](https://kubernetes.io/docs/concepts/policy/limit-range/#constraints-on-resource-limits-and-requests) if present in the target namespace.

The order by which Requested resource values are set becomes:
1. Job spec
3. LimitRanges in the target namespace
2. Limits  set for the same container in the Job Spec

In addition, this provides a more generic alternative approach to fix #590, by moving the limits to request default in the workload controller without an impact to the workload's spec .

#### Which issue(s) this PR fixes:

Fixes #541, #590

### CODE REVIEW

**Comment by alculquicondor** [comment]
@kerthcet since this is related to #590, can you take a look?

**Comment by kerthcet** [comment]
> @kerthcet since this is related to #590, can you take a look?

Sure, but this will defer to tomorrow.
/assign

File: apis/kueue/webhooks/workload_webhook.go [hunk 1]
```diff
@@ -21,29 +21,73 @@ import (
...
+		return nil, err
+	}
+	if len(list.Items) == 0 {
+		return nil, nil
+	}
+
+	ret := make([]corev1.LimitRangeItem, 0, len(list.Items))
+
+	for _, lr := range list.Items {
+		for _, lri := range lr.Spec.Limits {
```
Comment (kerthcet) [inline apis/kueue/webhooks/workload_webhook.go:61]: I think we should only consider `defaults` here,  if no defaults, then we'll set defaults to limits.

File: pkg/controller/workload/job/job_controller.go [hunk 2]
```diff
@@ -619,14 +660,12 @@ func jobAndWorkloadEqual(job *batchv1.Job, wl *kueue.Workload) bool {
 		return false
 	}
 
-	// nodeSelector may change, hence we are not checking for
-	// equality of the whole job.Spec.Template.Spec.
-	if !equality.Semantic.DeepEqual(job.Spec.Template.Spec.InitContainers,
-		wl.Spec.PodSets[0].Spec.InitContainers) {
+	specHash, err := jobSpecHash(job)
```
Comment (kerthcet) [inline pkg/controller/workload/job/job_controller.go:663]: I think this is not what we want, before we validate that the job is semantically equal with workload, for workload might be created randomly, but now we just validate the job is not updated, if I understood correctly, then, we can compare the UID and ResourceVersion instead.

**Review by kerthcet — COMMENTED** [review]
Just take an overview of this PR, I think we have something to come to an agreement at first:
- About the defaulting orders:
   - Respect container resources first
   - Respect LimitRange, we should not defaulting the requests to limits as we want before applying the policy, it's a hard constraint required by the administrators.
   - Defaulting the requests to limits if not set
- About the validation
  - We should also reject the creation if violating the LimitRange, in validation I think.
  - If no request set in final, reject the creation also.
  
cc @alculquicondor for advices also.

File: pkg/controller/workload/job/job_controller.go (hunk 2 above)
Comment (trasc) [reply pkg/controller/workload/job/job_controller.go:663]: The difference between  `jobSpecHash` and UID+Resourece is taht the result of `jobSpecHash` will be the same ti the [Init]Containers specs are not changed.

From the equality point of view, indeed, now we check that the current version of the job is semantically equal to the job version at the creation of the workload, however , starting from the semantically equal job and applying the same default logic will create the same workload (the only exception for this being if LimitRanges change ).

**Comment by trasc** [comment]
> 



> Just take an overview of this PR, I think we have something to come to an agreement at first:
> 
> * About the defaulting orders:
>   
>   * Respect container resources first
>   * Respect LimitRange, we should not defaulting the requests to limits as we want before applying the policy, it's a hard constraint required by the administrators.
>   * Defaulting the requests to limits if not set
> * About the validation
>   
>   * We should also reject the creation if violating the LimitRange, in validation I think.
>   * If no request set in final, reject the creation also.
> 
> cc @alculquicondor for advices also.

For the defaulting order, in my opinion, the value set in the limits of the job has better chances to be closer to the actual need of the job that a value set for the entire namespace.

Regarding the validation, sure, it could be added.

File: apis/kueue/webhooks/workload_webhook.go (hunk 1 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go:61]: I'm afraid I don't understand.

File: apis/kueue/webhooks/workload_webhook.go [hunk 3]
```diff
@@ -21,29 +21,73 @@ import (
...
+	}
+	return ret, nil
+}
+
+type WorkloadWebhook struct {
+	getter LimitRangeProvider
+}
 
 func setupWebhookForWorkload(mgr ctrl.Manager) error {
+
```
[the remark this answers is not in the document]
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go]: done

File: apis/kueue/webhooks/workload_webhook.go [hunk 4]
```diff
@@ -21,29 +21,71 @@ import (
...
 	"k8s.io/klog/v2"
 	ctrl "sigs.k8s.io/controller-runtime"
 	"sigs.k8s.io/controller-runtime/pkg/webhook"
 
 	kueue "sigs.k8s.io/kueue/apis/kueue/v1alpha2"
 )
 
-type WorkloadWebhook struct{}
+// LimitRangeProvider - hepler interface able to privide LimitRanges
+type LimitRangeProvider interface {
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook.go:39]: We shouldn't need this interface.
The fake client already gives you the ability to populate objects in tests.

File: apis/kueue/webhooks/workload_webhook.go (hunk 1 above)
Comment (alculquicondor) [reply apis/kueue/webhooks/workload_webhook.go:60]: We need to consider all the fields. `min` and `max` would also affect the containers requests.

File: apis/kueue/webhooks/workload_webhook.go [hunk 5]
```diff
@@ -21,29 +21,71 @@ import (
...
+		return nil, err
+	}
+	if len(list.Items) == 0 {
+		return nil, nil
+	}
+
+	ret := make([]corev1.LimitRangeItem, 0, len(list.Items))
+	for _, lr := range list.Items {
+		for _, lri := range lr.Spec.Limits {
+			if lri.Type == corev1.LimitTypeContainer {
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook.go:61]: the controller-runtime client has indexing capabilities. Use them to avoid filtering at this level.
For example https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/core/indexer/indexer.go

File: apis/kueue/webhooks/workload_webhook.go [hunk 6]
```diff
@@ -21,29 +21,71 @@ import (
...
+	}
+	return ret, nil
+}
+
+type WorkloadWebhook struct {
+	getter LimitRangeProvider
+}
 
 func setupWebhookForWorkload(mgr ctrl.Manager) error {
+	client, err := cgcorev1.NewForConfig(mgr.GetConfig())
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook.go:74]: use the controller-runtime client instead: `mgr.GetClient`

File: apis/kueue/webhooks/workload_webhook.go [hunk 7]
```diff
@@ -21,29 +21,71 @@ import (
...
 		For(&kueue.Workload{}).
-		WithDefaulter(&WorkloadWebhook{}).
-		WithValidator(&WorkloadWebhook{}).
+		WithDefaulter(wh).
+		WithValidator(wh).
 		Complete()
 }
 
 // +kubebuilder:webhook:path=/mutate-kueue-x-k8s-io-v1alpha2-workload,mutating=true,failurePolicy=fail,sideEffects=None,groups=kueue.x-k8s.io,resources=workloads,verbs=create;update,versions=v1alpha2,name=mworkload.kb.io,admissionReviewVersions=v1
+//+kubebuilder:rbac:groups="",resources=limitranges,verbs=get;list
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook.go:88]:
```suggestion
//+kubebuilder:rbac:groups="",resources=limitranges,verbs=get;list;watch
```

This allows the controller-runtime client to cache the LimitRanges instead of querying every time.

File: apis/kueue/webhooks/workload_webhook.go [hunk 8]
```diff
@@ -76,13 +126,31 @@ func setContainersDefaults(containers []corev1.Container) {
...
-					c.Resources.Requests[k] = v.DeepCopy()
-				}
-			}
+			c.Resources.Requests = mergeResourceList(c.Resources.Requests, c.Resources.Limits)
+		}
+	}
+}
+
+func setContainersDefaultsFromLimitRanges(containers []corev1.Container, limits []corev1.LimitRangeItem) {
+	for _, ri := range limits {
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook.go:135]: can there be more than one Container LimitRange per namespace?

File: apis/kueue/webhooks/workload_webhook.go [hunk 9]
```diff
@@ -76,13 +126,31 @@ func setContainersDefaults(containers []corev1.Container) {
...
+		for i := range containers {
+			cr := &containers[i].Resources
+			cr.Limits = mergeResourceList(cr.Limits, ri.Default)
+			cr.Requests = mergeResourceList(cr.Requests, ri.DefaultRequest)
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook.go:139]: what about Min and Max?

File: apis/kueue/webhooks/workload_webhook_test.go [hunk 10]
```diff
@@ -398,3 +535,153 @@ func TestValidateWorkloadUpdate(t *testing.T) {
 		})
 	}
 }
+
+func TestListRangeGetter(t *testing.T) {
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook_test.go:539]: We shouldn't need this test once we use the controller-runtime client.

**Comment by kerthcet** [comment]
> For the defaulting order, in my opinion, the value set in the limits of the job has better chances to be closer to the actual need of the job that a value set for the entire namespace. The same happens for pods.

Defaulting Limits to Requests is not transparent to users, if we have LimitRange with defaultRequest set, workload can be constructed successfully, why we get involved with the `limits -> requests`? We used to do this just because workloads requires the requests.

File: apis/kueue/webhooks/workload_webhook.go (hunk 6 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go]: done

File: apis/kueue/webhooks/workload_webhook.go (hunk 7 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go]: done

File: apis/kueue/webhooks/workload_webhook.go [hunk 11]
```diff
@@ -65,6 +112,9 @@ func (w *WorkloadWebhook) Default(ctx context.Context, obj runtime.Object) error
 		podSet := &wl.Spec.PodSets[i]
 		setContainersDefaults(podSet.Spec.InitContainers)
 		setContainersDefaults(podSet.Spec.Containers)
+
+		setContainersDefaultsFromLimitRanges(podSet.Spec.InitContainers, nsLimitRanges)
+		setContainersDefaultsFromLimitRanges(podSet.Spec.Containers, nsLimitRanges)
```
[the remark this answers is not in the document]
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go]: This is how it works for pods.

File: apis/kueue/webhooks/workload_webhook.go (hunk 8 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go]: Yes, and our "merge" strategy is the same as the one used by  https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go

File: apis/kueue/webhooks/workload_webhook_test.go (hunk 10 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook_test.go]: removed

File: apis/kueue/webhooks/workload_webhook.go (hunk 8 above)
Comment (alculquicondor) [reply apis/kueue/webhooks/workload_webhook.go]: Please reference the relevant code from kubernetes/kubernetes in a comment.

File: apis/kueue/webhooks/workload_webhook.go [hunk 12]
```diff
@@ -65,24 +75,70 @@ func (w *WorkloadWebhook) Default(ctx context.Context, obj runtime.Object) error
...
+	}
+
+	ret := &corev1.ResourceRequirements{
+		Limits:   corev1.ResourceList{},
+		Requests: corev1.ResourceList{},
+	}
+	for _, lr := range list.Items {
+		for _, lri := range lr.Spec.Limits {
+			if lri.Type == corev1.LimitTypeContainer {
+				ret.Requests = mergeResourceList(ret.Requests, lri.DefaultRequest)
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook.go:104]: IIUC, `min` and `max` do not alter the values, they are just used for validation.

File: apis/kueue/webhooks/workload_webhook_test.go [hunk 13]
```diff
@@ -173,17 +176,169 @@ func TestWorkloadWebhookDefault(t *testing.T) {
...
-			wh := &WorkloadWebhook{}
+			wh := &WorkloadWebhook{client: testingutil.NewFakeClient(tc.limitRanges...)}
 			wlCopy := tc.wl.DeepCopy()
 			if err := wh.Default(context.Background(), wlCopy); err != nil {
 				t.Fatalf("Could not apply defaults: %v", err)
 			}
 			if diff := cmp.Diff(tc.wantWl, *wlCopy); diff != "" {
 				t.Errorf("Obtained wrong defaults (-want,+got):\n%s", diff)
 			}
+			t.Log(wlCopy)
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook_test.go:341]: remove this line

File: pkg/controller/workload/job/job_controller.go [hunk 14]
```diff
@@ -50,6 +53,10 @@ var (
 	parentWorkloadKey = ".metadata.parentWorkload"
 )
 
+const (
+	sourceSpecHashKey = "kueue.x-k8s.io/source-hash"
```
Comment (alculquicondor) [inline pkg/controller/workload/job/job_controller.go:57]: worth putting this in a more visible place, like `pkg/constants`

File: pkg/controller/workload/job/job_controller.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/workload/job/job_controller.go:657]: this question is still open

File: apis/kueue/webhooks/workload_webhook.go (hunk 1 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go]: Indeed we could also validate the boundaries, however I propose to do this in another Issue/PR otherwise it will get to hard to track. Also we should decide what should happen if the validation fails, as of now, the job controller will just endlessly to to create the workload and fail.

In my opinion,  tracking the defaults used in order to recreate the workload add too much coupling between  the job-controllers and the workloads, with very little added value (in practice I don't expect the `LimitRanges` to change very often).

File: pkg/controller/workload/job/job_controller.go (hunk 2 above)
Comment (trasc) [reply pkg/controller/workload/job/job_controller.go:657]: The only scenario in which could change the the the flow is when a workload is not scheduled because the an old default value douse not fit and it will fit with the new one.
What we could do is to extend the workload controller to watch the changes in the  LimitsRanges and mark the workloads using outdated values.  Then the job controllers can decide if they want to delete and recreate the workload. Do we want something like that?

File: apis/kueue/webhooks/workload_webhook.go (hunk 9 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go]: In my opinion Min and Max  should only be used in validation.

File: apis/kueue/webhooks/workload_webhook.go (hunk 12 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go:104]: yes

File: apis/kueue/webhooks/workload_webhook_test.go (hunk 13 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook_test.go:341]: done

File: pkg/controller/workload/job/job_controller.go (hunk 14 above)
Comment (trasc) [reply pkg/controller/workload/job/job_controller.go:57]: done

File: apis/kueue/webhooks/workload_webhook.go (hunk 5 above)
Comment (trasc) [reply apis/kueue/webhooks/workload_webhook.go]: Indexing could help, but only for the first loop, and in practice , is the same namespace, is unlikely to have multiple LimitRanges.

With the change in  `getDefaultsFromLimitRanges` these loops are only executed once for every web-hook call.

File: pkg/controller/workload/job/job_controller.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/workload/job/job_controller.go:654]: Let's assume LimitRanges never change. In that case, this is a fine solution and I would be ok merging it.

Realistically, LimitRanges can change, the next question is whether it's acceptable to be out-of-sync for a first iteration of LimitRange support. I think it's fine.

However, I'm afraid that once we add support for changing LimitRanges, we would just throw away this code based on hashes. Are we ok with that?

I think it's just more useful to directly write the code that handles changing LimitRanges. We don't need to add code to react to changes in LimitRange. It suffices to do the checks whenever there are changes in the Workload or Job object. If there are changes, we can just keep the current logic that deletes the Workload object. Once we decide to have a better support for this, we can change the code to update the Workload object instead.

Comment (trasc) [reply pkg/controller/workload/job/job_controller.go:654]: This part just keeps track of the sync between the job spec and the original (before defaulting is applied ) workload content and should not be impacted by the the limits changes.

Also #611 was opened to work on that resync.

**Comment by alculquicondor** [comment]
Instead of the hash, we might be better of storing the original requests as suggested in option 1 of https://github.com/kubernetes-sigs/kueue/issues/611#issuecomment-1458295397

**Comment by trasc** [comment]
> Instead of the hash, we might be better off storing the original requests as suggested in option 1 of [#611 (comment)](https://github.com/kubernetes-sigs/kueue/issues/611#issuecomment-1458295397)

Sure, but do we want to change the API in  this PR?

**Comment by alculquicondor** [comment]
Yes, because if we merge this PR, we will pretty much undo everything when we store the original requests.

**Comment by alculquicondor** [comment]
We can start simpler:

- Drop the hash
- Add a LimitRange rencociler that deletes every Workload in the namespace that is not admitted.

We don't expect that changes to LimitRange happen often and we can improve on this later.

**Comment by trasc** [comment]
For the api change should we go with something like 
```
type WorkloadSpec struct {
	// .....
	PodSets []PodSet `json:"podSets"`
	// this one will be set by the default webhook and used in scheduling
	SchedPodSets []PodSet `json:"schedPodSets"`

```

**Comment by trasc** [comment]
> Let's start with this [#600 (comment)](https://github.com/kubernetes-sigs/kueue/pull/600#issuecomment-1460323882), which should be good enough for this release.

If we drop the hash and not have a way to "remember" the original resources, in order to verify the equality of a job with it's workload we'll need to apply the default setting scheme every time we need to check the equality, otherwise we'll have a similar issue as #590 related to LimitRange defaulting.

**Comment by alculquicondor** [comment]
Right, we would have to add this somewhat complex verification in each job (batch, mpi, ray, etc) controller.

Then please proceed with option 1 of https://github.com/kubernetes-sigs/kueue/issues/611#issuecomment-1458295397

**Comment by kerthcet** [comment]
Left a comment here https://github.com/kubernetes-sigs/kueue/issues/611#issuecomment-1463236862

**Comment by alculquicondor** [comment]
> If the creation mutating webhook allows you to update the status. 

It doesn't. Then we need to put the calculated requests in the Spec.

File: apis/kueue/v1beta1/workload_types.go [hunk 15]
```diff
@@ -95,6 +95,13 @@ type PodSet struct {
 	// count is the number of pods for the spec.
 	// +kubebuilder:validation:Minimum=1
 	Count int32 `json:"count"`
+
+	// Total Request holds the pod's resource requirements, the values being
+	// maintained by the Kueue operator.
+	//
+	// The computation can take into account the cluster's LimitRange.
```
Comment (alculquicondor) [inline apis/kueue/v1beta1/workload_types.go:102]:
```suggestion
	// The computation takes into account defaults, RuntimeClass and LimitRange.
```

File: apis/kueue/webhooks/workload_webhook.go [hunk 16]
```diff
@@ -63,26 +74,84 @@ func (w *WorkloadWebhook) Default(ctx context.Context, obj runtime.Object) error
 	}
 	for i := range wl.Spec.PodSets {
 		podSet := &wl.Spec.PodSets[i]
-		setContainersDefaults(podSet.Template.Spec.InitContainers)
-		setContainersDefaults(podSet.Template.Spec.Containers)
+
+		// we apply the default request logic in a pod spec copy in order to compute the TotalResources
+		specCopy := podSet.Template.Spec.DeepCopy()
+		updatePodDefaultResources(specCopy, nsLimitRangesDefaults)
```
Comment (alculquicondor) [inline apis/kueue/webhooks/workload_webhook.go:80]: let's apply these defaults into the totals only, instead of modifying the pod template

File: pkg/cache/cache_test.go [hunk 17]
```diff
@@ -715,9 +715,11 @@ func TestCacheWorkloadOperations(t *testing.T) {
 		*utiltesting.MakePodSet("driver", 1).
 			Request(corev1.ResourceCPU, "10m").
 			Request(corev1.ResourceMemory, "512Ki").
+			TotalRequestFunc(workload.PodTotalRequests).
```
Comment (alculquicondor) [inline pkg/cache/cache_test.go:718]: Is there an scenario where we pass a different function?

If this is about avoiding a circular dependency, it might be better to call `workload.PodSetsTotalRequests` once in the test body function, instead of doing it in the wrappers.

File: pkg/controller/core/workload_controller.go [hunk 18]
```diff
@@ -425,3 +443,51 @@ func handlePodOverhead(log logr.Logger, wl *kueue.Workload, c client.Client) {
...
+
+	lst := kueue.WorkloadList{}
+	err := h.client.List(ctx, &lst, client.InNamespace(lr.Namespace), client.MatchingFields{indexer.WorkloadAdmittedKey: string(metav1.ConditionFalse)})
+	if err != nil {
+		log.Error(err, "Could not list the unatmitted workloads")
+	}
+	log.V(5).Info("deleting workloads", "count", len(lst.Items))
+
+	for _, w := range lst.Items {
+		log.V(5).Info("deleting", "workload", klog.KObj(&w))
```
Comment (alculquicondor) [inline pkg/controller/core/workload_controller.go:486]: Better move it after the Delete call

```suggestion
		log.V(2).Info("Deleted Workload due to changing LimitRange", "workload", klog.KObj(&w))
```

File: pkg/controller/core/workload_controller.go [hunk 19]
```diff
@@ -425,3 +443,51 @@ func handlePodOverhead(log logr.Logger, wl *kueue.Workload, c client.Client) {
...
+	//TODO: the eventHandler should get a context soon, and this could be dropped
+	// https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/handler/eventhandler.go
+	ctx := context.TODO()
+	log := ctrl.LoggerFrom(ctx).WithValues("limitRange", klog.KObj(lr))
+	ctx = ctrl.LoggerInto(ctx, log)
+
+	lst := kueue.WorkloadList{}
+	err := h.client.List(ctx, &lst, client.InNamespace(lr.Namespace), client.MatchingFields{indexer.WorkloadAdmittedKey: string(metav1.ConditionFalse)})
+	if err != nil {
+		log.Error(err, "Could not list the unatmitted workloads")
```
Comment (alculquicondor) [inline pkg/controller/core/workload_controller.go:481]:
```suggestion
		log.Error(err, "Could not list the unadmitted workloads")
```

File: apis/kueue/v1beta1/workload_types.go [hunk 20]
```diff
@@ -95,6 +95,13 @@ type PodSet struct {
...
+	// +optional
+	TotalRequests corev1.ResourceList `json:"totalRequests,omitempty"`
```
Comment (alculquicondor) [inline apis/kueue/v1beta1/workload_types.go:104]: If we move this field into status, we can do the calculations at the time of admission.
This means that we don't need to recreate Workloads. And after admission they will have the information in Status, which the cache can use.

File: pkg/cache/cache_test.go (hunk 17 above)
Comment (trasc) [reply pkg/cache/cache_test.go:718]: no, but workload package is also using the wrappers and I'm doing this to avoid circular dependencies

Comment (alculquicondor) [reply pkg/cache/cache_test.go:718]: Right. Then there are two alternatives:
1. Avoid making use of the wrappers in `workload_test.go`. These tests are small and intend to test multiple PodSpec fields that might not be worth to add in the wrappers.
2. Call some form of `workload.PodSetsTotalRequest` from the test body instead of in the wrappers.

**Review by alculquicondor — COMMENTED** [review]
With this PR, if a LimitRange changes, then the usage of admitted Workloads would change.

I think this is fine as an intermediate step given that we do have the same problem with RuntimeClass.

File: pkg/util/resource/resource.go [hunk 21]
```diff
@@ -0,0 +1,85 @@
...
+	if a.Cmp(b) > 0 {
+		return b
+	}
+	return a
+}
+
+// MergeResourceListKeepMin creates a new ResourceList holding all the values from a and b
+// and resolve potential conflicts by keeping the lowest value.
+func MergeResourceListKeepMin(a, b corev1.ResourceList) corev1.ResourceList {
+	return mergeResourceList(a, b, minQ)
```
Comment (alculquicondor) [inline pkg/util/resource/resource.go:73]: I would just inline the function here, because `minQ` is not useful on its own

File: pkg/util/limitrange/limitrange.go [hunk 22]
```diff
@@ -0,0 +1,104 @@
...
+	summary.MaxLimitRequestRatio = resource.MergeResourceListKeepMin(summary.MaxLimitRequestRatio, item.MaxLimitRequestRatio)
+	return summary
+}
+
+// SummaryCache provides a thread-safe cache mapping a string to a Summary
+// Like the standard map, reading from it is safe and will return a zero value
+type SummaryCache struct {
+	m sync.RWMutex
+
+	// in practice we'll have one for each namespace
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/util/limitrange/limitrange.go:60]: Just storing in status should be enough.
Usage from admitted workloads would just be calculated from the status.

[the remark this answers is not in the document]
Comment (trasc) [reply pkg/util/limitrange/limitrange.go:60]: Even so, when a change is done to the limit ranges, we'd want to trigger a readjustment of the total for all the unadmitted workloads within a namespace, without a cache for all of them we need to list the same set of limitRanges and compute the summary.

File: pkg/util/resource/resource.go (hunk 21 above)
Comment (trasc) [reply pkg/util/resource/resource.go]: done

File: pkg/util/limitrange/limitrange.go (hunk 22 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/util/limitrange/limitrange.go:60]: yes, and that is fine, because:
1. Usually there is just one.
2. The client already has a cache, so there are no API calls.

[the remark this answers is not in the document]
Comment (trasc) [reply pkg/util/limitrange/limitrange.go:60]: One other use-case for this validation could be to use it in the scheduler to validate that the resources do not fit the limits. (some ware in `nominate()`)

[the remark this answers is not in the document]
Comment (trasc) [reply pkg/util/limitrange/limitrange.go:60]: However, if you insist, we can drop it for now and deal with the validation when the time comes.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/util/limitrange/limitrange.go:60]: Validation can also list from the client.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/util/limitrange/limitrange.go:60]: Maintaining a cache in addition to the informer's cache adds several complications that has to payoff with a significant performance boost. It's not worth optimizing for limit ranges when they are usually just one.

[the remark this answers is not in the document]
Comment (trasc) [reply pkg/util/limitrange/limitrange.go]: done

File: pkg/cache/cache_test.go (hunk 17 above)
Comment (trasc) [reply pkg/cache/cache_test.go]: no longer needed

File: pkg/util/resource/resource_test.go [hunk 23]
```diff
@@ -0,0 +1,198 @@
...
+	type oper_result struct {
+		oper   func(a, b corev1.ResourceList) corev1.ResourceList
+		result corev1.ResourceList
+	}
+	cases := map[string]struct {
+		a        corev1.ResourceList
+		b        corev1.ResourceList
+		expected map[string]oper_result
+	}{
+		"asymetric": {
```
Comment (alculquicondor) [inline pkg/util/resource/resource_test.go:49]:
```suggestion
		"asymmetric": {
```

File: pkg/util/testing/wrappers.go [hunk 24]
```diff
@@ -499,3 +511,66 @@ func (rc *RuntimeClassWrapper) PodOverhead(resources corev1.ResourceList) *Runti
...
+							corev1.ResourceMemory: resource.MustParse("300M"),
+						},
+						Default: corev1.ResourceList{
+							corev1.ResourceCPU:    resource.MustParse("4"),
+							corev1.ResourceMemory: resource.MustParse("400M"),
+						},
+						Max: corev1.ResourceList{
+							corev1.ResourceCPU:    resource.MustParse("5"),
+							corev1.ResourceMemory: resource.MustParse("500M"),
+						},
```
Comment (alculquicondor) [inline pkg/util/testing/wrappers.go:543]: Remove these lines. It's too many constants hidden in just `MakeLimitRange`.

When we put some constants in other wrappers, they correspond to defaults or things that almost every test should need.

File: pkg/util/testing/wrappers.go [hunk 25]
```diff
@@ -499,3 +511,66 @@ func (rc *RuntimeClassWrapper) PodOverhead(resources corev1.ResourceList) *Runti
...
+	case "Min":
+		target = lr.Spec.Limits[0].Min
+	case "DefaultRequest":
+		target = lr.Spec.Limits[0].DefaultRequest
+	case "Default":
+		target = lr.Spec.Limits[0].Default
+	case "Max":
+	//nothing
+	default:
+		//just let it update the Max
```
Comment (alculquicondor) [inline pkg/util/testing/wrappers.go:568]: panic

File: test/integration/controller/core/workload_controller_test.go [hunk 26]
```diff
@@ -249,4 +252,144 @@ var _ = ginkgo.Describe("Workload controller", func() {
...
+			localQueue = testing.MakeLocalQueue("queue", ns.Name).ClusterQueue(clusterQueue.Name).Obj()
+			gomega.Expect(k8sClient.Create(ctx, localQueue)).To(gomega.Succeed())
+		})
+		ginkgo.AfterEach(func() {
+			gomega.Expect(util.DeleteNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
+			gomega.Expect(util.DeleteRuntimeClass(ctx, k8sClient, runtimeClass)).To(gomega.Succeed())
+			util.ExpectClusterQueueToBeDeleted(ctx, k8sClient, clusterQueue, true)
+		})
+
+		ginkgo.It("Should use the range defined requests, if not provided", func() {
```
Comment (alculquicondor) [inline test/integration/controller/core/workload_controller_test.go:274]:
```suggestion
		ginkgo.It("Should use the range defined default requests, if provided", func() {
```

File: pkg/controller/core/workload_controller.go [hunk 27]
```diff
@@ -425,3 +433,50 @@ func handlePodOverhead(log logr.Logger, wl *kueue.Workload, c client.Client) {
 		}
 	}
 }
+
+func (r *WorkloadReconciler) handlePodLimitRange(log logr.Logger, wl *kueue.Workload) {
+	ctx := context.Background()
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/core/workload_controller.go]: done

File: pkg/controller/core/workload_controller.go [hunk 28]
```diff
@@ -425,3 +433,50 @@ func handlePodOverhead(log logr.Logger, wl *kueue.Workload, c client.Client) {
...
+	// get the list of limit ranges
+	var list corev1.LimitRangeList
+	if err := r.client.List(ctx, &list, &client.ListOptions{Namespace: wl.Namespace}); err != nil {
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/core/workload_controller.go]: added

File: pkg/util/resource/resource_test.go [hunk 29]
```diff
@@ -0,0 +1,198 @@
...
+	}
+
+	type oper_result struct {
+		oper   func(a, b corev1.ResourceList) corev1.ResourceList
+		result corev1.ResourceList
+	}
+	cases := map[string]struct {
+		a        corev1.ResourceList
+		b        corev1.ResourceList
+		expected map[string]oper_result
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/util/resource/resource_test.go]: done

File: pkg/util/resource/resource_test.go [hunk 30]
```diff
@@ -0,0 +1,198 @@
...
+				"sum": {
+					oper: MergeResourceListKeepSum,
+					result: corev1.ResourceList{
+						corev1.ResourceCPU:    apiresource.MustParse("1500m"),
+						corev1.ResourceMemory: apiresource.MustParse("2Gi"),
+					},
+				},
+			},
+		},
+		"symetric": {
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/util/resource/resource_test.go]: done, thanks

File: pkg/util/testing/wrappers.go [hunk 31]
```diff
@@ -499,3 +511,66 @@ func (rc *RuntimeClassWrapper) PodOverhead(resources corev1.ResourceList) *Runti
 func (rc *RuntimeClassWrapper) Obj() *nodev1.RuntimeClass {
 	return &rc.RuntimeClass
 }
+
+type limitRangeBuider struct{ corev1.LimitRange }
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/util/testing/wrappers.go]: done

File: pkg/util/resource/resource_test.go (hunk 23 above)
Comment (trasc) [reply pkg/util/resource/resource_test.go]: done

File: pkg/util/testing/wrappers.go (hunk 24 above)
Comment (trasc) [reply pkg/util/testing/wrappers.go]: done

File: pkg/util/testing/wrappers.go (hunk 25 above)
Comment (trasc) [reply pkg/util/testing/wrappers.go]: done

File: pkg/controller/core/indexer/indexer.go [hunk 32]
```diff
@@ -58,6 +60,20 @@ func IndexWorkloadClusterQueue(obj client.Object) []string {
 	return []string{string(wl.Status.Admission.ClusterQueue)}
 }
 
+func IndexLimitRangeHasContainerType(obj client.Object) []string {
```
Comment (alculquicondor) [inline pkg/controller/core/indexer/indexer.go:63]: We might need to also check type Pod when we do validation (for min/max).

So an alternative implementation would be `IndexLimitRangeByType`. Then you can return all the types that the LimitRange has.

But we can leave this for later.

File: pkg/util/resource/resource_test.go [hunk 33]
```diff
@@ -0,0 +1,198 @@
...
+*/
+
+package resource
+
+import (
+	"testing"
+
+	"github.com/google/go-cmp/cmp"
+	corev1 "k8s.io/api/core/v1"
+	apiresource "k8s.io/apimachinery/pkg/api/resource"
```
Comment (alculquicondor) [inline pkg/util/resource/resource_test.go:24]: we avoid aliases when there are no conflicts.

File: pkg/util/testing/wrappers.go [hunk 34]
```diff
@@ -499,3 +511,55 @@ func (rc *RuntimeClassWrapper) PodOverhead(resources corev1.ResourceList) *Runti
...
+			},
+			Spec: corev1.LimitRangeSpec{
+				Limits: []corev1.LimitRangeItem{
+					{
+						Type:                 corev1.LimitTypeContainer,
+						Max:                  corev1.ResourceList{},
+						Min:                  corev1.ResourceList{},
+						Default:              corev1.ResourceList{},
+						DefaultRequest:       corev1.ResourceList{},
+						MaxLimitRequestRatio: corev1.ResourceList{},
```
Comment (alculquicondor) [inline pkg/util/testing/wrappers.go:532]: you could remove these lines.

**Review by alculquicondor — COMMENTED** [review]
Comments that can be done in follow ups

/lgtm
/approve

/label tide/merge-method-squash

File: pkg/util/testing/wrappers.go (hunk 34 above)
Comment (trasc) [reply pkg/util/testing/wrappers.go:532]: yes, but then you need to check / alocate the empty map for every value set

Comment (alculquicondor) [reply pkg/util/testing/wrappers.go:532]: ahhh, sorry, I forgot these were maps :)
