### PR TITLE
Fix flaky kuberay InTreeAutoscaling E2E pod replacement test

### LINKED ISSUE #10438: Flaky E2E: Kuberay Should run a rayjob with InTreeAutoscaling
**Which test is flaking?**:

End To End Suite: kindest/node:v1.34.3: [It] Kuberay Should run a rayjob with InTreeAutoscaling [area:singlecluster, feature:kuberay]

**Link to failed CI job or steps to reproduce locally**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-release-0-17-1-34/2043879343330955264

**Failure message or logs**:
```
8m20s
{ failed [FAILED] Timed out after 300.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/kuberay_test.go:419 with:
Expected 5 running worker pods after replacement
Expected
    <[]string | len:0, cap:0>: nil
to have length 5
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/kuberay_test.go:425 @ 04/14/26 02:55:36.871
}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by sohankunkerkar**
The RayJob was completing before the pod replacement step could verify 5 running workers, causing the test to find 0 pods and time out. Extend parallel task sleep from 8s to 60s to keep workers alive through the pod replacement cycle. Remove redundant scale-up assertions already covered by the test below.

#### What type of PR is this?
/kind flake

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/kueue/issues/10438

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/singlecluster/kuberay_test.go [hunk 1]
```diff
@@ -222,9 +222,11 @@ def my_task(x, s):
...
-# create workload slices, and schedule new workers.
-print(ray.get([my_task.remote(i, 8) for i in range(16)]))
+# 8 tasks with 60s sleep: enough demand to scale to 5 workers,
+# and keeps them alive through pod replacement verification.
+# With 5 workers, 8 tasks complete in ~120s (2 waves), leaving
+# headroom for the replacement step without hitting timeouts.
+print(ray.get([my_task.remote(i, 60) for i in range(8)]))
 
 # run tasks in sequence to trigger scaling down
 print([ray.get(my_task.remote(i, 1)) for i in range(32)])`,
```
Comment (mimowo) [inline test/e2e/singlecluster/kuberay_test.go]: iiuc we can also drop this step as scale down is already covered by the other test below too

File: test/e2e/singlecluster/kuberay_test.go
Comment (mimowo) [inline test/e2e/singlecluster/kuberay_test.go]: I think we can drop this step now too

Comment (mimowo) [inline test/e2e/singlecluster/kuberay_test.go]: Lets check if we could drop this step and still repro the the recently fixed bug, or at least shorten the task to 1s

File: test/e2e/singlecluster/kuberay_test.go [hunk 2]
```diff
@@ -222,9 +222,11 @@ def my_task(x, s):
 print([ray.get(my_task.remote(i, 1)) for i in range(4)])
 
 # run tasks in parallel to trigger autoscaling (scaling up)
-# Use longer sleep (8s) to give autoscaler time to detect demand,
-# create workload slices, and schedule new workers.
-print(ray.get([my_task.remote(i, 8) for i in range(16)]))
+# 8 tasks with 60s sleep: enough demand to scale to 5 workers,
```
Comment (mimowo) [inline test/e2e/singlecluster/kuberay_test.go]: Im wondering if we could reduce the number of replicas only to 2 so make the math simpler and debugging, and have 3 tasks so we should also have two waves guaranteed.

File: test/e2e/singlecluster/kuberay_test.go
Comment (sohankunkerkar) [reply test/e2e/singlecluster/kuberay_test.go]: Dropped entirely. Not needed for the pod replacement test.

File: test/e2e/singlecluster/kuberay_test.go (hunk 2 above)
Comment (sohankunkerkar) [reply test/e2e/singlecluster/kuberay_test.go]: Done. `MaxWorkerReplicas(2)` with 3 tasks at 60s. Added `MaxWorkerReplicas` setter to the rayjob wrapper.

File: test/e2e/singlecluster/kuberay_test.go (hunk 1 above)
Comment (sohankunkerkar) [reply test/e2e/singlecluster/kuberay_test.go]: Dropped from the script along with the scale-down verification step.

File: test/e2e/singlecluster/kuberay_test.go
Comment (sohankunkerkar) [reply test/e2e/singlecluster/kuberay_test.go]: Removed, along with the annotation check and `scaledUpPodNames`

**Review by mimowo — COMMENTED** [review]
Thank you 👍 
/lgtm
/approve
/cherrypick release-0.17
/cherrypick release-0.16
