### PR TITLE
fix: configure PodSetTopologyRequests only when TAS enabled

### LINKED ISSUE #4590: TAS: configure PodSetTopologyRequests only when TAS enabled
**What would you like to be cleaned**:

This code is currenlty activated all the time: https://github.com/kubernetes-sigs/kueue/blob/a454f0e133682887c8043b10cc360bc24f7d3924/pkg/controller/jobframework/tas.go#L26

However, this should only be applied in case when TopologyAwareScheduling is enabled.

**Why is this needed**:

There should be no TAS related code active when TAS is disabled.

This also complicates testing the fix in https://github.com/kubernetes-sigs/kueue/issues/4573.

### PR DESCRIPTION
**Pull request by mykysha**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
PodSetTopologyRequests are now configured only when TopologyAwareScheduling feature gate is enabled.

#### Which issue(s) this PR fixes:

Fixes #4590

#### Does this PR introduce a user-facing change?

```release-note
PodSetTopologyRequests are now configured only when TopologyAwareScheduling feature gate is enabled.
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

File: pkg/controller/jobs/appwrapper/appwrapper_controller_test.go [hunk 1]
```diff
@@ -132,6 +133,7 @@ func TestPodSets(t *testing.T) {
 
 	for name, tc := range testCases {
 		t.Run(name, func(t *testing.T) {
+			features.SetFeatureGateDuringTest(t, features.TopologyAwareScheduling, true)
```
Comment (mimowo) [inline pkg/controller/jobs/appwrapper/appwrapper_controller_test.go:136]: IIUC the tests would pass even without changing the code. Let's introduce a new param enableTopologyAwareScheduling, and add a sanity test when `enableTopologyAwareScheduling=false`.

Comment (mykysha) [reply pkg/controller/jobs/appwrapper/appwrapper_controller_test.go:136]: I've added these changes only to the tests that were failing, so enabling the feature gate is required. Will add a `enableTopologyAwareScheduling=false` case

Comment (mykysha) [reply pkg/controller/jobs/appwrapper/appwrapper_controller_test.go]: Added `enableTopologyAwareScheduling` to the affected tests, as well as sanity tests where it is intentionally disabled.

**Comment by mimowo** [comment]
/lgtm
/approve

I think this is actually a small bug. However, it is quite unlikely to hit users, because it would only set the PodSetTopologyRequest, if the TAS-specific annotations were used. Still, I'm leaning to mark it as a bug.
/remove-kind cleanuo
/kind bug

/cherry-pick release-0.11 release-0.10
