### PR TITLE
Fix the flaky visibility test

### LINKED ISSUE #9028: [flaky test] Kueue secure visibility server when Capacity is maxed by the admitted job Should allow fetching information about pending workloads in ClusterQueue
**Which test is flaking?**:

Kueue secure visibility server when Capacity is maxed by the admitted job Should allow fetching information about pending workloads in ClusterQueue

**Link to failed CI job or steps to reproduce locally**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9017/pull-kueue-test-e2e-certmanager-main/2019591424449712128

**Failure message or logs**:
```
Kueue secure visibility server when Capacity is maxed by the admitted job [It] Should allow fetching information about pending workloads in ClusterQueue
/home/prow/go/src/sigs.k8s.io/kueue/test/e2e/certmanager/visibility_test.go:72
  [FAILED] Timed out after 10.001s.
  The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/certmanager/visibility_test.go:122 with:
  Expected
      <*bool | 0xc0007eaf5a>: true
  to equal
      <*bool | 0xc0007eafa0>: false
  In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/certmanager/visibility_test.go:123 @ 02/06/26 02:09:38.494
------------------------------

------------------------------
```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?
/kind bug
/kind flake
#### Which issue(s) this PR fixes:

Fixes #9028

#### Special notes for your reviewer:

see analysis in https://github.com/kubernetes-sigs/kueue/issues/9028#issuecomment-3860060682

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @sohankunkerkar ptal
/cherrypick release-0.16
/cherrypick release-0.15

File: test/e2e/certmanager/visibility_test.go [hunk 1]
```diff
@@ -112,6 +112,7 @@ var _ = ginkgo.Describe("Kueue secure visibility server", func() {
 			})
 
 			ginkgo.By("Delete the first job to release the quota", func() {
+				gomega.Expect(util.DeleteObject(ctx, k8sClient, firstJob)).Should(gomega.Succeed())
 				gomega.Expect(util.DeleteAllPodsInNamespace(ctx, k8sClient, ns)).Should(gomega.Succeed())
```
Comment (mbobrovskyi) [inline test/e2e/certmanager/visibility_test.go]: Do we need this?

Comment (sohankunkerkar) [reply test/e2e/certmanager/visibility_test.go]: Yeah, I don't think we need `DeleteAllPodsInNamespace`

Comment (mimowo) [reply test/e2e/certmanager/visibility_test.go]: Done, also replaced with using ExpectObjectToBeDeleted to await for the Job deletion.

Comment (mimowo) [reply test/e2e/certmanager/visibility_test.go]: Ah, it is not so easy to delete a k8s job and release quota, because the default mode for k8s Job is orphan, rather than background, and thus the "Workload" continues to exist and occupy quota: https://github.com/kubernetes-sigs/kueue/issues/1789
