### PR TITLE
test: fix flaky perf test by distinguishing context cancellation from timeout

### LINKED ISSUE #8437: [Flaky Perf Test] Client rate limiter Wait returned an error: context canceled"
/kind flake

**What happened**:

```
2026-01-05T09:16:43.908919858Z	INFO	Run generator	runner/main.go:355	Generator done	{"duration": "1m6.177059136s"}
push_pin
2026-01-05T09:25:37.732719758Z	ERROR	Start recorder	runner/main.go:368	Recorder run	{"error": "context deadline exceeded"}
main.startRecorder.func1
	/home/prow/go/src/sigs.k8s.io/kueue/test/performance/scheduler/runner/main.go:368
sync.(*WaitGroup).Go.func1
	/usr/local/go/src/sync/waitgroup.go:239
2026-01-05T09:25:37.73283916Z	ERROR	runner/main.go:210	Error	{"error": "context deadline exceeded"}
main.main
	/home/prow/go/src/sigs.k8s.io/kueue/test/performance/scheduler/runner/main.go:210
runtime.main
	/usr/local/go/src/runtime/proc.go:285
```

```
2026-01-05T09:37:52.408133361Z	INFO	manager/internal.go:578	Wait completed, proceeding to shutdown the manager
2026-01-05T09:38:03.147201793Z	ERROR	controller/controller.go:474	Reconciler error	{"controller": "workload", "controllerGroup": "kueue.x-k8s.io", "controllerKind": "Workload", "Workload": {"name":"small-0-18-0","namespace":"cq-0-3-cohort-0"}, "namespace": "cq-0-3-cohort-0", "name": "small-0-18-0", "reconcileID": "ba829d26-4b2e-4c3d-9697-a4be8f8b7453", "error": "client rate limiter Wait returned an error: context canceled"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/home/prow/go/src/sigs.k8s.io/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:474
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/home/prow/go/src/sigs.k8s.io/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:421
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1
	/home/prow/go/src/sigs.k8s.io/kueue/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:296
```

**What you expected to happen**:

No issue

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/8436/pull-kueue-test-scheduling-perf-main/2008104395681566720

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sohankunkerkar**
The performance test creates ~15,000 workloads (5 cohorts × 6 queues × 500 workloads). Under heavy reconciliation, the default kube-apiserver limits (max-requests-inflight=400, max-mutating-requests-inflight=200) cause the envtest API server to become overwhelmed, resulting in "http2: client connection lost" errors when pending requests queue up
and connections time out.

#### What type of PR is this?
/kind flake

#### Which issue(s) this PR fixes:

Fixes #8437

#### Special notes for your reviewer:
I was referring to https://e-whisper.com/posts/51187/

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: test/performance/scheduler/runner/recorder/recorder.go [hunk 1]
```diff
@@ -400,7 +401,12 @@ func (r *Recorder) Run(ctx context.Context, genDone <-chan struct{}) error {
 	for {
 		select {
 		case <-ctx.Done():
-			return ctx.Err()
+			// DeadlineExceeded indicates that the recording exceeded
+			// the configured maximum duration and is treated as a recorder failure.
+			if errors.Is(ctx.Err(), context.DeadlineExceeded) {
```
Comment (mbobrovskyi) [inline test/performance/scheduler/runner/recorder/recorder.go]: Thanks for the PR!

I agree with the intent here – we want to treat deadline exceedance as a recorder failure while letting client disconnects succeed gracefully.

However, the current check makes everything except `DeadlineExceeded` return `nil`. Since `ctx.Err()` today is exhaustive (only `Canceled` or `DeadlineExceeded`), it works, but it's a bit fragile: if in the future someone wraps the error or a new cancellation reason appears, it would silently return `nil` even in failure cases.

I think it's safer to invert the logic and explicitly allow only `context.Canceled`.

```suggestion
			if !errors.Is(ctx.Err(), context.Canceled) {
				return ctx.Err()
			}
			return nil
```

WDYT?

Comment (sohankunkerkar) [reply test/performance/scheduler/runner/recorder/recorder.go]: Yeah, that makes sense! I think my approach was more about fail-open (unknown errors → success) but I think we should be defensive in this case as you mentioned.

Comment (sohankunkerkar) [reply test/performance/scheduler/runner/recorder/recorder.go]: Yeah, that makes sense! I think my approach was more about fail-open (unknown errors → success) but I think we should be defensive in this case as you mentioned.

**Comment by sohankunkerkar** [comment]
I think the root cause is the envtest API server becoming overwhelmed under the load of the performance test. After the generator finishes, the controller reconciles all these workloads, creating a thundering herd of API calls. The default kube-apiserver limits are:

```sh
 --max-requests-inflight=400 --max-mutating-requests-inflight=200
```
Under this load, requests queue up, the API server becomes overwhelmed, HTTP/2 connections time out, and we see "client connection lost" errors. How about we bump these numbers?

**Comment by tenzen-y** [comment]
> I think the root cause is the envtest API server becoming overwhelmed under the load of the performance test. After the generator finishes, the controller reconciles all these workloads, creating a thundering herd of API calls. The default kube-apiserver limits are:
> 
> ```shell
>  --max-requests-inflight=400 --max-mutating-requests-inflight=200
> ```
> 
> Under this load, requests queue up, the API server becomes overwhelmed, HTTP/2 connections time out, and we see "client connection lost" errors. How about we bump these numbers?

I think that increasing the limitations of in-flight requests would be worth it.
