### PR TITLE
Fix metrics certificate reload

### LINKED ISSUE #9005: Metrics TLS secret not hot-reloaded
**What happened**:

The kueue-controller-manager is failing to reload updated TLS certificates for its metrics endpoint. When cert-manager renews the certificate the controller continues to use the old, expired certificate. This results in "bad TLS handshake" errors during metrics scraping.

**What you expected to happen**:

The kueue-controller-manager should watch the mounted TLS secret and hot-reload the certificates when they are updated on disk, or the operator should trigger a rollout of the controller pods to pick up the new secret.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy Kueue (v0.14/v0.15) on a cluster with cert-manager.
Configure a Certificate for the metrics endpoint (e.g., metrics-server-cert).
Wait for the certificate to reach its renewal window or manually trigger a renewal via cmctl renew.
Observe that the metrics-server-cert Secret is updated with new data.
The scrape fails with a TLS handshake error because the manager is still serving the previous certificate.
Restarting the kueue-controller-manager pod fixes the issue.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  1.30
- Kueue version (use `git describe --tags --dirty --always`): v0.14/v0.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by MaysaMacedo**
#### What this PR does / why we need it:
This commit ensures that the metrics certificate
is reloaded in the server in case the certificate data
is updated.

#### Which issue(s) this PR fixes:

Fixes #9005

#### Special notes for your reviewer:
Assisted by Claude Code
#### Does this PR introduce a user-facing change?

```release-note
Metrics certificate is now reloaded when certificate data is updated. 
```

### CODE REVIEW

File: cmd/kueue/main.go [hunk 1]
```diff
@@ -208,6 +203,12 @@ func main() {
 			setupLog.Error(err, "Unable to initialize metrics certificate watcher")
 			os.Exit(1)
 		}
+		go func() {
+			if err := metricsCertWatcher.Start(context.Background()); err != nil {
```
Comment (sohankunkerkar) [inline cmd/kueue/main.go]: The cert watcher uses context.Background() while the rest of main.go relies on ctx from ctrl.SetupSignalHandler(), so it won’t shut down cleanly on SIGTERM.

How about you declare `metricsCertWatcher` outside the if block and add it to the manager via `mgr.Add(metricsCertWatcher)`, similar to sched and serverVersionFetcher, so the manager handles its lifecycle.

~Also, it would be good to add an E2E test that validates certificate reload via an actual TLS handshake.~

Comment (MaysaMacedo) [reply cmd/kueue/main.go]: I updated it. Thanks for the suggestion

File: test/e2e/certmanager/metrics_test.go [hunk 2]
```diff
@@ -179,6 +180,57 @@ var _ = ginkgo.Describe("Metrics", ginkgo.Ordered, func() {
 				expectMetricsToBeAvailable(curlPod.Name, curlContainerName, [][]string{expectedMetric})
 			})
 		})
+		ginkgo.It("should continue to expose metrics after the secret is re-created", func() {
```
Comment (kannon92) [inline test/e2e/certmanager/metrics_test.go:182]: Want to confirm that this e2e test actually verifies the issue.

Opened up https://github.com/kubernetes-sigs/kueue/pull/9076 to confirm.

File: test/e2e/certmanager/metrics_test.go [hunk 3]
```diff
@@ -179,6 +180,57 @@ var _ = ginkgo.Describe("Metrics", ginkgo.Ordered, func() {
...
+
+			ginkgo.By("verifying certificate content changed in curl-pod", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					newCertContent, _, err := util.KExecute(ctx, cfg, restClient, kueueNS, curlPod.Name, curlContainerName,
+						[]string{"/bin/sh", "-c", fmt.Sprintf("cat %s/ca.crt", certMountPath)})
+					g.Expect(err).NotTo(gomega.HaveOccurred())
+					g.Expect(initialCertContent).NotTo(gomega.BeEmpty())
+					g.Expect(newCertContent).NotTo(gomega.BeEmpty())
+					g.Expect(newCertContent).NotTo(gomega.Equal(initialCertContent), "Certificate content should have changed after secret recreation")
+				}, util.VeryLongTimeout, time.Second*30).Should(gomega.Succeed())
```
Comment (sohankunkerkar) [inline test/e2e/certmanager/metrics_test.go]: Any reason why it's `time.Second*30` and not `util.Interval`?

File: test/e2e/certmanager/metrics_test.go [hunk 4]
```diff
@@ -179,6 +180,57 @@ var _ = ginkgo.Describe("Metrics", ginkgo.Ordered, func() {
...
+			var initialCertContent []byte
+			ginkgo.By("reading initial certificate content from curl-pod", func() {
+				certContent, _, err := util.KExecute(ctx, cfg, restClient, kueueNS, curlPod.Name, curlContainerName,
+					[]string{"/bin/sh", "-c", fmt.Sprintf("cat %s/ca.crt", certMountPath)})
+				gomega.Expect(err).NotTo(gomega.HaveOccurred())
+				initialCertContent = certContent
+				gomega.Expect(initialCertContent).NotTo(gomega.BeEmpty())
+			})
+
+			ginkgo.By("deleting the secret", func() {
```
Comment (sohankunkerkar) [inline test/e2e/certmanager/metrics_test.go:200]: nit: The test covers delete→recreate, but the original bug is about cert-manager updating the secret in-place during renewal. It would be good to add that as test case here too.

File: test/e2e/certmanager/metrics_test.go (hunk 3 above)
Comment (MaysaMacedo) [reply test/e2e/certmanager/metrics_test.go]: That interval is too short `time.Millisecond * 250`, this means it would constantly be retrying to check the content of the cert file, without need, given it generally takes a while for the certificate to be updated within the container.

File: test/e2e/certmanager/metrics_test.go (hunk 4 above)
Comment (MaysaMacedo) [reply test/e2e/certmanager/metrics_test.go:200]: @sohankunkerkar do you have any thoughts on how to achieve that?

I have used the cert-manager pluging with kubectl to manually verify that https://cert-manager.io/v1.0-docs/usage/kubectl-plugin/

1. Fetch initial secret: `kubectl get secret kueue-metrics-server-cert -n kueue-system     -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -noout -serial`
2. `kubectl port-forward -n kueue-system svc/kueue-controller-manager-metrics-service 8443:8443 &`
3. Check that cert output is the same as step one when trying to reach server: `echo | openssl s_client -connect localhost:8443 2>/dev/null | openssl x509 -noout -serial`
4. Renew certificate: `kubectl cert-manager renew kueue-metrics-cert -n kueue-system`
5. Do step 1 until 3 again and check that the new outputs from 1 and 3 match.

Comment (sohankunkerkar) [reply test/e2e/certmanager/metrics_test.go:200]: Thanks for looking into this! Adding this test case would certainly introduce additional complexity. On second thought, the cert watcher relies on fsnotify, which handles both delete-and-recreate and in-place updates in the same way. I think we are good here.

File: test/e2e/certmanager/metrics_test.go (hunk 2 above)
Comment (kannon92) [reply test/e2e/certmanager/metrics_test.go:182]: And the e2e test does fail if we don't have this change so I think the test is solid!

**Comment by sohankunkerkar** [comment]
@mimowo @mbobrovskyi PTAL

**Review by mimowo — COMMENTED** [review]
Thank you!
/lgtm 
/approve
/cherrypick release-0.16
/cherrypick release-0.15

File: test/e2e/certmanager/metrics_test.go (hunk 3 above)
Comment (mbobrovskyi) [reply test/e2e/certmanager/metrics_test.go]: I think we should use util.Interval. Yes, it will retry many times, but that’s fine – this is a test, so we don’t need to worry about it. What’s more important is that we shouldn’t wait 30 seconds if it finishes after 250 ms. So I think util.Interval is the right choice here.

Comment (mbobrovskyi) [reply test/e2e/certmanager/metrics_test.go]: /hold

Comment (MaysaMacedo) [reply test/e2e/certmanager/metrics_test.go]: @mbobrovskyi It took more than one minute for the certificate to be updated:
```
  [1mSTEP:[0m verifying certificate content changed in curl-pod [38;5;243m@ 02/10/26 15:49:16.315[0m
  [1mSTEP:[0m checking that the metrics are still available [38;5;243m@ 02/10/26 15:50:46.939[0m
```
should we keep retrying every `time.Millisecond * 250` if we know it will thake this long?

Comment (MaysaMacedo) [reply test/e2e/certmanager/metrics_test.go]: in private, we agreed to update it to 1 sec

Comment (mbobrovskyi) [reply test/e2e/certmanager/metrics_test.go]: Thank you so much! 🙏

/lgtm
/unhold

**Comment by kannon92** [comment]
You don't need to spam this anymore. You will have to do a manual cherry-pick for release-0.15.

You can use hack/cherry-pick (or whatever its called) to help perform the cherry pick.
