### PR TITLE
BugFix: scale-up workload stuck pending not triggering preemption.

### LINKED ISSUE #6969: [ElasticJobs] scale-up workload stuck pending: preemption not triggered.
**What happened**:
When scaling up an ElasticJob (via WorkloadSlices), the scaled-up workload slice does not preempt or evict other workloads as expected. Instead, it remains in a "pending" (unadmitted) state.

**What you expected to happen**:
The scaled-up workload slice should preempt/evict lower-priority workloads as necessary and be successfully admitted.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a ClusterQueue and two WorkloadPriorityClasses: `low` and `high`.
2. Submit a regular `batchv1.Job` with low priority.
3. Submit an ElasticJob with high priority, still within the ClusterQueue quota capacity.
4. Scale up the ElasticJob so that it requires preemption/eviction of the low-priority job.

**Anything else we need to know?**:
N/A

**Environment**:

* Kubernetes version (use `kubectl version`):
* Kueue version (use `git describe --tags --dirty --always`): `v0.13.4`
* Cloud provider or hardware configuration:
* OS (e.g. `cat /etc/os-release`):
* Kernel (e.g. `uname -a`):
* Install tools:
* Others:

### PR DESCRIPTION
**Pull request by ichekrygin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR fixes bug when scaled-up workload stuck pending not triggering preemption.

#### Which issue(s) this PR fixes:

Fixes #6969

#### Does this PR introduce a user-facing change?

```release-note
ElasticJob workloads correctly trigger workload preemption in response to a scale-up event.
```

### CODE REVIEW

File: test/integration/singlecluster/scheduler/suite_test.go [hunk 1]
```diff
@@ -63,6 +65,7 @@ var _ = ginkgo.BeforeSuite(func() {
 	}
 	cfg = fwk.Init()
 	ctx, k8sClient = fwk.SetupClient(cfg)
+	gomega.Expect(utilfeature.DefaultMutableFeatureGate.SetFromMap(map[string]bool{string(features.ElasticJobsViaWorkloadSlices): true})).Should(gomega.Succeed())
```
Comment (tenzen-y) [inline test/integration/singlecluster/scheduler/suite_test.go]: We should avoid enabling such Alpha feature at global level. We should set the FG only in the affected case.
You can learn HOW in https://github.com/kubernetes-sigs/kueue/blob/c87e0c77e4e043af15078ccbbe766af8b0ba0aa6/test/integration/multikueue/dispatcher_test.go#L169

File: pkg/scheduler/flavorassigner/flavorassigner.go [hunk 2]
```diff
@@ -157,17 +168,23 @@ func (a *Assignment) ToAPI() []kueue.PodSetAssignment {
...
-			ps = *ps.ScaledTo(aps.Count)
+		// Either use replacement workload-slice or partial admission to scale usage.
+		if a.replaceWorkloadSlice != nil {
+			ps = *ps.ScaledTo(ps.Count - a.replaceWorkloadSlice.TotalRequests[i].Count)
+		} else {
+			aps := a.PodSets[i]
+			if aps.Count != ps.Count {
+				ps = *ps.ScaledTo(aps.Count)
+			}
 		}
```
Comment (mimowo) [inline pkg/scheduler/flavorassigner/flavorassigner.go:180]: Instead of doing two independent branches could we just decrement the value we are scaling?

Something like:
```golang
newCount := a.PodSets[i].Count
if a.replaceWorkloadSlice != nil {
  newCount -= a.replaceWorkloadSlice.TotalRequests[i].Count
}
ps = *ps.ScaledTo(newCount)
```
wdyt?

File: test/integration/singlecluster/scheduler/preemption_test.go [hunk 3]
```diff
@@ -999,4 +1002,103 @@ var _ = ginkgo.Describe("Preemption", func() {
...
+			q = testing.MakeLocalQueue("q", ns.Name).ClusterQueue(cq.Name).Obj()
+			util.MustCreate(ctx, k8sClient, q)
+		})
+
+		ginkgo.AfterEach(func() {
+			gomega.Expect(util.DeleteWorkloadsInNamespace(ctx, k8sClient, ns)).To(gomega.Succeed())
+			util.ExpectObjectToBeDeleted(ctx, k8sClient, cq, true)
+		})
+
+		ginkgo.It("Should preempt on-create Workloads with lower priority when there is not enough quota", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/preemption_test.go]: Does this "It" introduce additional coverage?

File: pkg/scheduler/scheduler.go [hunk 4]
```diff
@@ -537,7 +537,7 @@ func (s *Scheduler) getInitialAssignments(log logr.Logger, wl *workload.Info, sn
 		}
 	}
 
-	if features.Enabled(features.PartialAdmission) && wl.CanBePartiallyAdmitted() {
+	if features.Enabled(features.PartialAdmission) && wl.CanBePartiallyAdmitted() && replaceableWorkloadSlice == nil {
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go]: Do we have some test for this? IIUC the new integration tests (or the reported issue) also show up with the "PartialAdmission" disabled? So, I think this code change may not be exercised by the integration tests

Comment (mimowo) [reply pkg/scheduler/scheduler.go]: So, IIUC this code change is fixing a different issue. Also, I'm wondering if we shouldn't just disable PartialAdmission for ElasticJobs at the validation level. 

Let me know if I'm missing something.

Comment (ichekrygin) [reply pkg/scheduler/scheduler.go]: > So, IIUC this code change is fixing a different issue. Also, I'm wondering if we shouldn't just disable PartialAdmission for ElasticJobs at the validation level.

We already enforce that at the validation level. The purpose of this change is to add a sanity check, ensuring that PartialAdmission (PA) is never combined with ElasticJobs (EJ). It also serves as an explicit reminder at the scheduler level that PA is not compatible with EJ.

Please let me know if this addition is a "block", I am happy to revert this change.

File: test/integration/singlecluster/scheduler/suite_test.go (hunk 1 above)
Comment (ichekrygin) [reply test/integration/singlecluster/scheduler/suite_test.go]: Ah... yes. Good catch! For some reason I thought I need "feature" activation at the manager level. 
Reverted.

File: pkg/scheduler/scheduler.go (hunk 4 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go]: Let's cleanup the code. We can rely on validation, this is the common practice in k8s, to avoid checking against invariants which are satisfied by validation.

File: test/integration/singlecluster/scheduler/preemption_test.go (hunk 3 above)
Comment (ichekrygin) [reply test/integration/singlecluster/scheduler/preemption_test.go]: It’s updated (PTAL), with feature activation moved into the test-case scope.
This test is dedicated to validating that general workload preemption works — specifically, that an elastic workload can preempt another job outside of the scale-up context. In other words, it serves more as a sanity check.

Happy to remove it if we think it’s redundant.

File: pkg/scheduler/scheduler.go (hunk 4 above)
Comment (ichekrygin) [reply pkg/scheduler/scheduler.go]: done

File: test/integration/singlecluster/scheduler/preemption_test.go (hunk 3 above)
Comment (mimowo) [reply test/integration/singlecluster/scheduler/preemption_test.go]: I see the motivation. OTOH we already have a test exercising priority based preemption (in the simple case) for ElasticJobs  here: https://github.com/kubernetes-sigs/kueue/blob/785114f2014c36b9fda5cc15d5e157403b3997b2/test/integration/singlecluster/controller/jobs/job/job_controller_test.go#L3491-L3498

I know the pre-existing test is a bit more involving, but I'm unclear adding the new small test makes it easier to understand.

I would focus only on the issue at hand and drop the extra test. I would be happy to keep it if we haven't had the other preexisting test already.

Comment (ichekrygin) [reply test/integration/singlecluster/scheduler/preemption_test.go]: done!

**Comment by mimowo** [comment]
Thank you 👍 
/lgtm
/approve
/cherry-pick release-0.13

**Comment by mimowo** [comment]
@ichekrygin can you maybe prepare the cherry-pick? The ./hack/cherry_pick_pull.sh script is pretty useful for that.

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
ElasticJobs: workloads correctly trigger workload preemption in response to a scale-up event.
```
