### PR TITLE
Fix MultiKueue workload re-evaluation bug

### LINKED ISSUE #6738: Workload re-evaluation
**What happened**:
Existing workloads are not re-evaluated
when new clusters are added to MultiKueueConfig. 

**What you expected to happen**:
When new clusters are added, existing workloads should be evaluated.

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/kubernetes-sigs/kueue/pull/6732

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
#### What type of PR is this?
 /kind bug

#### What this PR does / why we need it:
 This PR fixes a bug where existing workloads were not re-evaluated when new clusters were added to a MultiKueueConfig. Previously, only newly created workloads would see the updated cluster list, causing existing workloads to miss opportunities to be scheduled on newly available clusters.
  **Root Cause**: The workload controller was not watching MultiKueueConfig changes, so existing workloads remained stuck with their original cluster nominations.

#### Which issue(s) this PR fixes:

Fixes #6738 

#### Does this PR introduce a user-facing change?

```release-note
Fix existing workloads not being re-evaluated when new clusters are added to MultiKueueConfig. Previously, only newly created workloads would see updated cluster lists.
```

### CODE REVIEW

**Comment by mimowo** [comment]
@ravisantoshgudimetla Thank you for the test. Please open an issue referencing the test. 

Do you foresee working on the issue in short or mid term yourself? I guess there is limited value merging the test without a fix

**Comment by ravisantoshgudimetla** [comment]
Created issue here: https://github.com/kubernetes-sigs/kueue/issues/6738. I can work on it in the next couple of weeks.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 1]
```diff
@@ -584,6 +584,54 @@ func newWlReconciler(c client.Client, helper *multiKueueStoreHelper, cRec *clust
...
+
+func (c *mkConfig) queueWorkloadsForConfig(ctx context.Context, configName string, q workqueue.TypedRateLimitingInterface[reconcile.Request]) {
+	admissionChecks := &kueue.AdmissionCheckList{}
+	if err := c.client.List(ctx, admissionChecks, client.MatchingFields{AdmissionCheckUsingConfigKey: configName}); err != nil {
+		return
+	}
+	for _, ac := range admissionChecks.Items {
+		workloads := &kueue.WorkloadList{}
+		if err := c.client.List(ctx, workloads, client.MatchingFields{WorkloadsWithAdmissionCheckKey: ac.Name}); err != nil {
+			continue
```
Comment (mimowo) [inline pkg/controller/admissionchecks/multikueue/workload.go:612]: log the error

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 2]
```diff
@@ -584,6 +584,54 @@ func newWlReconciler(c client.Client, helper *multiKueueStoreHelper, cRec *clust
...
+}
+
+func (c *mkConfig) Generic(context.Context, event.GenericEvent, workqueue.TypedRateLimitingInterface[reconcile.Request]) {
+	// no-op as we don't need to react to generic
+}
+
+func (c *mkConfig) queueWorkloadsForConfig(ctx context.Context, configName string, q workqueue.TypedRateLimitingInterface[reconcile.Request]) {
+	admissionChecks := &kueue.AdmissionCheckList{}
+	if err := c.client.List(ctx, admissionChecks, client.MatchingFields{AdmissionCheckUsingConfigKey: configName}); err != nil {
+		return
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Please log the error.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 3]
```diff
@@ -584,6 +584,54 @@ func newWlReconciler(c client.Client, helper *multiKueueStoreHelper, cRec *clust
...
+	}
+	for _, ac := range admissionChecks.Items {
+		workloads := &kueue.WorkloadList{}
+		if err := c.client.List(ctx, workloads, client.MatchingFields{WorkloadsWithAdmissionCheckKey: ac.Name}); err != nil {
+			continue
+		}
+		for _, wl := range workloads.Items {
+			q.Add(reconcile.Request{NamespacedName: client.ObjectKeyFromObject(&wl)})
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Use q.AddAfter.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 4]
```diff
@@ -584,6 +584,54 @@ func newWlReconciler(c client.Client, helper *multiKueueStoreHelper, cRec *clust
 	return r
 }
 
+type mkConfig struct {
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go]:
```suggestion
type mkConfigHandler struct {
```

File: pkg/controller/admissionchecks/multikueue/indexer.go [hunk 5]
```diff
@@ -65,5 +77,8 @@ func SetupIndexer(ctx context.Context, indexer client.FieldIndexer, configNamesp
 	if err := indexer.IndexField(ctx, &kueue.AdmissionCheck{}, AdmissionCheckUsingConfigKey, admissioncheck.IndexerByConfigFunction(kueue.MultiKueueControllerName, configGVK)); err != nil {
 		return fmt.Errorf("setting index on admission checks config: %w", err)
 	}
+	if err := indexer.IndexField(ctx, &kueue.Workload{}, WorkloadsWithAdmissionCheckKey, indexWorkloadsChecks); err != nil {
+		return fmt.Errorf("setting index on workloads checks: %w", err)
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/indexer.go]:
```suggestion
		return fmt.Errorf("setting index on workloads admission checks: %w", err)
```
nit

File: pkg/controller/admissionchecks/multikueue/indexer.go [hunk 6]
```diff
@@ -55,6 +57,16 @@ func indexUsingMultiKueueClusters(obj client.Object) []string {
 	return config.Spec.Clusters
 }
 
+func indexWorkloadsChecks(obj client.Object) []string {
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/indexer.go]:
```suggestion
func indexWorkloadsAdmissionChecks(obj client.Object) []string {
```
nit

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 7]
```diff
@@ -584,6 +584,54 @@ func newWlReconciler(c client.Client, helper *multiKueueStoreHelper, cRec *clust
...
+	client client.Client
+}
+
+func (c *mkConfig) Create(context.Context, event.CreateEvent, workqueue.TypedRateLimitingInterface[reconcile.Request]) {
+	// no-op as we don't need to react to new configs
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go:568]: If we allow deleting the config, can the user recreate it? What happens if the user deletes a config that was in use?

File: pkg/controller/admissionchecks/multikueue/indexer_test.go [hunk 8]
```diff
@@ -171,3 +171,77 @@ func TestListMultiKueueConfigsUsingMultiKueueClusters(t *testing.T) {
...
+			},
+			filter:   client.MatchingFields{WorkloadsWithAdmissionCheckKey: "ac1"},
+			wantList: []string{"wl1"},
+		},
+	}
+	for name, tc := range cases {
+		t.Run(name, func(t *testing.T) {
+			ctx, _ := utiltesting.ContextWithLog(t)
+			builder := getClientBuilder(ctx)
+			k8sclient := builder.Build()
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/indexer_test.go]:
```suggestion
			k8sClient := builder.Build()
```
nit

File: pkg/controller/admissionchecks/multikueue/indexer_test.go [hunk 9]
```diff
@@ -171,3 +171,77 @@ func TestListMultiKueueConfigsUsingMultiKueueClusters(t *testing.T) {
...
+				if err := k8sclient.Create(ctx, wl); err != nil {
+					t.Fatalf("Unable to create %q workload: %v", client.ObjectKeyFromObject(wl), err)
+				}
+			}
+
+			lst := &kueue.WorkloadList{}
+
+			gotListErr := k8sclient.List(ctx, lst, tc.filter)
+			if diff := cmp.Diff(tc.wantListError, gotListErr); diff != "" {
+				t.Errorf("unexpected list error (-want/+got):\n%s", diff)
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/indexer_test.go]:
```suggestion
				t.Errorf("unexpected error (-want/+got):\n%s", diff)
```
nit

File: pkg/controller/admissionchecks/multikueue/workload_test.go [hunk 10]
```diff
@@ -1489,3 +1490,34 @@ func TestNominateAndSynchronizeWorkers_MoreCases(t *testing.T) {
 		})
 	}
 }
+
+func TestConfigHandlerUpdate(t *testing.T) {
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload_test.go:1771]: Not sure I got what we are testing here?

File: test/integration/multikueue/dispatcher_test.go [hunk 11]
```diff
@@ -736,4 +739,289 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+				}
+				acs := admissioncheck.FindAdmissionCheck(createdWorkload.Status.AdmissionChecks, kueue.AdmissionCheckReference(isolatedAdmissionCheck.Name))
+				if acs == nil || acs.State != kueue.CheckStateReady {
+					return false
+				}
+				return createdWorkload.Status.ClusterName != nil && *createdWorkload.Status.ClusterName == workerCluster2.Name
+			}, util.Timeout, util.Interval).Should(gomega.BeTrue())
+		})
+
+		ginkgo.By("cleaning up test resources", func() {
```
Comment (mbobrovskyi) [inline test/integration/multikueue/dispatcher_test.go]: What if an error occurs in the middle of the code? Wrap the logic in a When() block and use AfterEach() for cleanup.

Comment (mbobrovskyi) [reply test/integration/multikueue/dispatcher_test.go]: Or actually maybe it's better to create separate Describe() block.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 7 above)
Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go:568]: The user should be able to re-create it. The reconciler will error and re-queue. In normal workflows, configs are created before workloads that reference them.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 4 above)
Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go]: We already have mkConfigHandler in admissioncheck.go, however I don't mind changing it to configHandler as we are already in multikueue package, so there is no need to stutter

File: pkg/controller/admissionchecks/multikueue/workload_test.go (hunk 10 above)
Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload_test.go:1771]: It's testing the "should we callback?" decision logic. I have updated it to use fakeQueue to check for actual objects.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 3 above)
Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Typically AddAfter is used for batching operations after given time. I'm not sure if it adds value here since these are rare admin driven action, for example if clusters get added/deleted frequently. Having said that, I'm ambivalent.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 1 above)
Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go:612]: Collecting errors and returning now - The logs are collected https://github.com/kubernetes-sigs/kueue/pull/6732/files#diff-a09b1d2caac9c60d2112a557a72bb2495f52f4c9ac6d161c3b30f1a3a6be24b6R557

File: test/integration/multikueue/dispatcher_test.go (hunk 11 above)
Comment (ravisantoshgudimetla) [reply test/integration/multikueue/dispatcher_test.go]: Done

**Comment by ravisantoshgudimetla** [comment]
@mbobrovskyi - Any other review comments. If not, can you approve it?

**Comment by ravisantoshgudimetla** [comment]
@mbobrovskyi and @mimowo - Any other review comments?

File: pkg/controller/admissionchecks/multikueue/indexer.go [hunk 12]
```diff
@@ -25,17 +25,17 @@ import (
...
+	UsingKubeConfigs               = "spec.kubeconfigs"
+	UsingMultiKueueClusters        = "spec.multiKueueClusters"
+	AdmissionCheckUsingConfigKey   = "spec.multiKueueConfig"
+	WorkloadsWithAdmissionCheckKey = "status.admissionChecks"
 )
 
-var (
-	configGVK = kueue.GroupVersion.WithKind("MultiKueueConfig")
-)
+var configGVK = kueue.GroupVersion.WithKind("MultiKueueConfig")
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/indexer.go]: nit: It looks like nothing changed. Please revert this changes.

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 13]
```diff
@@ -51,9 +51,7 @@ import (
 	"sigs.k8s.io/kueue/pkg/workload"
 )
 
-var (
-	realClock = clock.RealClock{}
-)
+var realClock = clock.RealClock{}
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go]: nit: And this.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 7 above)
Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:568]: So should we handle Create event?

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 14]
```diff
@@ -511,6 +509,62 @@ func newWlReconciler(c client.Client, helper *admissioncheck.MultiKueueStoreHelp
...
+		workloads := &kueue.WorkloadList{}
+		if err := c.client.List(ctx, workloads, client.MatchingFields{WorkloadsWithAdmissionCheckKey: admissionCheck.Name}); err != nil {
+			errs = append(errs, err)
+			continue
+		}
+		for _, workload := range workloads.Items {
+			q.Add(reconcile.Request{NamespacedName: client.ObjectKeyFromObject(&workload)})
+		}
+	}
+	return errors.Join(errs...)
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go:618]: Instead of returning the error, can we log it within this function? This would eliminate the need to initialize the var err []error variable.

File: pkg/controller/admissionchecks/multikueue/workload_test.go [hunk 15]
```diff
@@ -53,9 +53,7 @@ import (
 	_ "sigs.k8s.io/kueue/pkg/controller/jobs"
 )
 
-var (
-	errFake = errors.New("fake error")
-)
+var errFake = errors.New("fake error")
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload_test.go:58]: nit: Please revert.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/controller/admissionchecks/multikueue/workload.go:612]: There's no need to collect the errors and return it. We can log them here instead. Additionally, consider including admissionCheck in the log.

File: test/integration/multikueue/dispatcher_test.go [hunk 16]
```diff
@@ -717,3 +718,344 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+
+			remoteWorkload := &kueue.Workload{}
+			g.Expect(worker1TestCluster.client.Get(worker1TestCluster.ctx, workloadLookupKey, remoteWorkload)).To(gomega.Succeed())
+
+			g.Expect(worker2TestCluster.client.Get(worker2TestCluster.ctx, workloadLookupKey, remoteWorkload)).To(utiltesting.BeNotFoundError())
+		}, util.Timeout, util.Interval).Should(gomega.Succeed())
+	})
+
+	ginkgo.It("should re-evaluate existing workload when worker2 is added to config", func() {
+		features.SetFeatureGateDuringTest(ginkgo.GinkgoTB(), features.MultiKueueBatchJobWithManagedBy, true)
```
Comment (mbobrovskyi) [inline test/integration/multikueue/dispatcher_test.go]: You are using this feature in all test cases. Can we move it to BeforeEach()?

File: test/integration/multikueue/dispatcher_test.go [hunk 17]
```diff
@@ -717,3 +718,344 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+		util.ExpectObjectToBeDeleted(worker2TestCluster.ctx, worker2TestCluster.client, worker2Cq, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, multiKueueAC, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, managerMultiKueueConfig, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, workerCluster1, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, workerCluster2, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, managerMultiKueueSecret1, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, managerMultiKueueSecret2, true)
+	})
+
+	ginkgo.It("should create workload that requires more CPU than worker1 can provide", func() {
```
Comment (mbobrovskyi) [inline test/integration/multikueue/dispatcher_test.go]: What we are testing here?

File: test/integration/multikueue/dispatcher_test.go [hunk 18]
```diff
@@ -717,3 +718,344 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+		features.SetFeatureGateDuringTest(ginkgo.GinkgoTB(), features.MultiKueueBatchJobWithManagedBy, true)
+		job := testingjob.MakeJob("cpu-job", managerNs.Name).
+			ManagedBy(kueue.MultiKueueControllerName).
+			Queue(kueue.LocalQueueName(managerLq.Name)).
+			Request(corev1.ResourceCPU, "100m").
+			Obj()
+		gomega.Expect(managerTestCluster.client.Create(managerTestCluster.ctx, job)).To(gomega.Succeed())
+	})
+
+	ginkgo.It("should initially nominate only worker1 and set reservation", func() {
```
Comment (mbobrovskyi) [inline test/integration/multikueue/dispatcher_test.go]: Do we need this test?

File: test/integration/multikueue/dispatcher_test.go [hunk 19]
```diff
@@ -717,3 +718,344 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+
+		job := testingjob.MakeJob("cpu-job", managerNs.Name).
+			ManagedBy(kueue.MultiKueueControllerName).
+			Queue(kueue.LocalQueueName(managerLq.Name)).
+			Request(corev1.ResourceCPU, "100m").
+			Obj()
+		gomega.Expect(managerTestCluster.client.Create(managerTestCluster.ctx, job)).To(gomega.Succeed())
+		workloadLookupKey := types.NamespacedName{Name: workloadjob.GetWorkloadNameForJob(job.Name, job.UID), Namespace: managerNs.Name}
+
+		gomega.Eventually(func() error {
```
Comment (mbobrovskyi) [inline test/integration/multikueue/dispatcher_test.go]:
```suggestion
		gomega.Eventually(func(g gomeag.Gomega) {
```
Please use this pattern for consistency with other places.

Comment (mbobrovskyi) [reply test/integration/multikueue/dispatcher_test.go]: And also in other places.

File: test/integration/multikueue/dispatcher_test.go [hunk 20]
```diff
@@ -717,3 +718,344 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+		// Verify workloads get created on both worker clusters
+		gomega.Eventually(func(g gomega.Gomega) {
+			remoteWorkload1 := &kueue.Workload{}
+			g.Expect(worker1TestCluster.client.Get(worker1TestCluster.ctx, workloadLookupKey, remoteWorkload1)).To(gomega.Succeed())
+			remoteWorkload2 := &kueue.Workload{}
+			g.Expect(worker2TestCluster.client.Get(worker2TestCluster.ctx, workloadLookupKey, remoteWorkload2)).To(gomega.Succeed())
+		}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+	})
+
+	ginkgo.It("should assign workload to worker2 after reservation", func() {
```
Comment (mbobrovskyi) [inline test/integration/multikueue/dispatcher_test.go]: What exactly we are testing here?

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 21]
```diff
@@ -511,6 +509,62 @@ func newWlReconciler(c client.Client, helper *admissioncheck.MultiKueueStoreHelp
...
+
+	var errs []error
+	for _, admissionCheck := range admissionChecks.Items {
+		workloads := &kueue.WorkloadList{}
+		if err := c.client.List(ctx, workloads, client.MatchingFields{WorkloadsWithAdmissionCheckKey: admissionCheck.Name}); err != nil {
+			errs = append(errs, err)
+			continue
+		}
+		for _, workload := range workloads.Items {
+			q.Add(reconcile.Request{NamespacedName: client.ObjectKeyFromObject(&workload)})
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload.go]:
```suggestion
			q.AddAfter(reconcile.Request{NamespacedName: client.ObjectKeyFromObject(&workload)}, c.eventsBatchPeriod)
```
Please use AddAfter instead.

File: pkg/controller/admissionchecks/multikueue/workload_test.go [hunk 22]
```diff
@@ -1426,3 +1424,162 @@ func TestNominateAndSynchronizeWorkers_MoreCases(t *testing.T) {
...
+func (m *mockQueue) Len() int                                  { return 0 }
+func (m *mockQueue) Get() (reconcile.Request, bool)            { return reconcile.Request{}, false }
+func (m *mockQueue) Done(reconcile.Request)                    {}
+func (m *mockQueue) Forget(reconcile.Request)                  {}
+func (m *mockQueue) NumRequeues(reconcile.Request) int         { return 0 }
+func (m *mockQueue) AddRateLimited(reconcile.Request)          {}
+func (m *mockQueue) AddAfter(reconcile.Request, time.Duration) {}
+func (m *mockQueue) ShutDown()                                 {}
+func (m *mockQueue) ShutDownWithDrain()                        {}
+func (m *mockQueue) ShuttingDown() bool                        { return false }
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/multikueue/workload_test.go]:
```suggestion
type mockQueue struct {
	workqueue.TypedRateLimitingInterface[reconcile.Request]
	addAfter func(item reconcile.Request, duration time.Duration)
}

func (f *mockQueue) AddAfter(item reconcile.Request, duration time.Duration) {
	f.addAfter(item, duration)
}
```

**Comment by mimowo** [comment]
@ravisantoshgudimetla sorry for delayed review. I think it will not merge it for 0.14.0 as there are still many open comments. I will try to review this week after the release is out, and we can consider cherrypicking into 0.14.1.

Thank you for the PR. 

Maybe also @ichekrygin can give it a pass who knows MultiKueue pretty well by now.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 1 above)
Comment (ichekrygin) [reply pkg/controller/admissionchecks/multikueue/workload.go:612]: My take is that this helper is *expected* to return an error, which is then logged by the caller.
Logging it here while returning `nil` undermines the caller’s error-handling behavior.

I don’t have a strong stance on whether we should log or not, but returning an error here is consistent with both the function signature and the way callers handle errors. If the intent is to explicitly handle errors via logging, then we should consider changing the function signature to reflect that.

Note: just a few lines above, we return `err` for a similar `client.List` operation.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 21 above)
Comment (ichekrygin) [reply pkg/controller/admissionchecks/multikueue/workload.go]: That’s assuming we define `eventBatchPeriod` as a field in the `configHandler` struct, correct?

If that’s the case, what would you recommend as a value for the period?

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 14 above)
Comment (ichekrygin) [reply pkg/controller/admissionchecks/multikueue/workload.go:618]: I think this is related to the [comment above](https://github.com/kubernetes-sigs/kueue/pull/6732/files#r2392361023)

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 23]
```diff
@@ -525,6 +579,7 @@ func (w *wlReconciler) setupWithManager(mgr ctrl.Manager) error {
 		Named("multikueue_workload").
 		For(&kueue.Workload{}).
 		WatchesRawSource(source.Channel(w.clusters.wlUpdateCh, syncHndl)).
+		Watches(&kueue.MultiKueueConfig{}, &configHandler{client: w.client}).
```
Comment (ichekrygin) [inline pkg/controller/admissionchecks/multikueue/workload.go]: Maybe a bit out of scope, but worth asking:

`MultiKueueConfig` (config) and `MultiKueueCluster` (cluster) are separate. It’s possible for `config` to reference a new cluster **before** the cluster object is created/updated. Since we’re not watching for `cluster` changes, this could still require workload/job re-creation.

A simple repro: remove the `cluster` object (without touching config), submit a job, then add the cluster object back.

Should we be concerned about this in the context of this PR?

Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go]: I considered this scenario, and my reasoning was that in such cases, MultiKueue should error out rather than attempt to schedule workloads when referenced clusters are missing since MultiKueueConfig should be source of truth. That’s why I didn’t address these cases in this PR and instead planned to handle error scenarios in a follow-up.

However, I’m open to changing this behavior if others feel strongly that we should handle these cases within this PR.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 7 above)
Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go:568]: Nope.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 1 above)
Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go:612]: I see your point about the inconsistency. The first call is a prerequisite - if we can't get the admission checks list, there's nothing to process. The second call is in a loop where we want to process as many items as possible even if some fail. I don't have a strong preference either way though - happy to make them consistent if you think that's cleaner.

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 21 above)
Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go]: I'm ambivalent here too: I gave my reasoning here: https://github.com/kubernetes-sigs/kueue/pull/6732#discussion_r2342603373

File: test/integration/multikueue/dispatcher_test.go (hunk 17 above)
Comment (ravisantoshgudimetla) [reply test/integration/multikueue/dispatcher_test.go]: Can you elaborate? This step is prerequisite, are you suggesting that this shouldn't be a top level ginkgo.It(..)?

File: pkg/controller/admissionchecks/multikueue/workload.go (hunk 23 above)
Comment (ichekrygin) [reply pkg/controller/admissionchecks/multikueue/workload.go]: >  MultiKueue should error out rather than attempt to schedule workloads

To clarify, if MultiKueue cannot initialize a remote client for a newly referenced cluster, it continues processing workloads but effectively treats that cluster as absent, so no placements are attempted there. This mirrors the behavior when the cluster is missing from the MultiKueue config. Later, when the corresponding MultiKueueCluster is created and the remote client finally initializes, existing workloads are not automatically placed onto that new remote cluster. They will remain as is until a requeue or rescheduling event occurs.

Comment (ravisantoshgudimetla) [reply pkg/controller/admissionchecks/multikueue/workload.go]: > This mirrors the behavior when the cluster is missing from the MultiKueue config.

You're absolutely right about this scenario. However, this is a different problem than config changes not being propagated - one is about missing cluster handling, the other is about config watching. I kept them separate to avoid scope creep, but I'm happy to include cluster lifecycle handling in this PR if you think they should be addressed together

Comment (ichekrygin) [reply pkg/controller/admissionchecks/multikueue/workload.go]: Keeping them separate makes sense to me.

**Comment by mimowo** [comment]
@ravisantoshgudimetla could you please address (respond to) all comments, so that it is clear to other reviewers if the comment is addressed or not without reverse engineering, eg. https://github.com/kubernetes-sigs/kueue/pull/6732#discussion_r2383940701

**Comment by ravisantoshgudimetla** [comment]
>@ravisantoshgudimetla could you please address (respond to) all comments, so that it is clear to other reviewers if the comment is addressed or not without reverse engineering, eg. https://github.com/kubernetes-sigs/kueue/pull/6732#discussion_r2383940701

This seems to be outdated comment. I'm still waiting on understanding what @mbobrovskyi exactly wants. I think I gave reasoning on approaches mentioned for example - https://github.com/kubernetes-sigs/kueue/pull/6732#discussion_r2342603373 but did not get response.

**Comment by mimowo** [comment]
Oh I see, it might be outdated indeed, but the intention of the comments seems to be "please update the ginkgo.By description to make it clear what is the scenario we are testing'. If it is too long to describe inside the step name, then it is fair to have a brief step name, but add a comment to the ginkgo By.

IIRC Mike is on vacation by the end of the week.

**Comment by ravisantoshgudimetla** [comment]
>Oh I see, it might be outdated indeed, but the intention of the comments seems to be "please update the ginkgo.By description to make it clear what is the scenario we are testing'. If it is too long to describe inside the step name, then it is fair to have a brief step name, but add a comment to the ginkgo By.

>IIRC Mike is on vacation by the end of the week.

No worries. I addressed them as well using Ginkgo.It and Ginkgo.Context. The output looks something like below:

```
make test-multikueue-integration GINKGO_ARGS="--focus 'MultiKueueConfig Re-evaluation' -v" TEST_LOG_LEVEL=2

MultiKueueConfig Re-evaluation should create workload and nominate only worker1 when config contains single cluster
MultiKueueConfig Re-evaluation when MultiKueueConfig changes should re-evaluate existing workload when worker2 is added to config
MultiKueueConfig Re-evaluation when worker clusters have different resource capacities should assign workload to cluster with sufficient resources
```

Happy to change if they are not descriptive enough.

File: test/integration/multikueue/dispatcher_test.go [hunk 24]
```diff
@@ -721,3 +718,359 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+				util.SetQuotaReservation(worker2TestCluster.ctx, worker2TestCluster.client, workloadLookupKey, admission)
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+			// Verify workload is not created on worker1 (insufficient resources)
+			gomega.Eventually(func(g gomega.Gomega) {
+				remoteWorkload := &kueue.Workload{}
+				g.Expect(worker1TestCluster.client.Get(worker1TestCluster.ctx, workloadLookupKey, remoteWorkload)).To(utiltesting.BeNotFoundError())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+			// Verify workload is assigned to worker2 with sufficient resources
```
Comment (mimowo) [inline test/integration/multikueue/dispatcher_test.go]: Turn the comments like here and in other places as ginkgo.By steps. This makes debugging much easier when issue happens as we then see which step failed.

File: test/integration/multikueue/dispatcher_test.go [hunk 25]
```diff
@@ -721,3 +718,359 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+		gomega.Expect(managerTestCluster.client.Create(managerTestCluster.ctx, multiKueueAC)).To(gomega.Succeed())
+
+		ginkgo.By("wait for check active", func() {
+			updatedAc := kueue.AdmissionCheck{}
+			acKey := client.ObjectKeyFromObject(multiKueueAC)
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(managerTestCluster.client.Get(managerTestCluster.ctx, acKey, &updatedAc)).To(gomega.Succeed())
+				g.Expect(updatedAc.Status.Conditions).To(utiltesting.HaveConditionStatusTrue(kueue.AdmissionCheckActive))
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+		})
```
Comment (mimowo) [inline test/integration/multikueue/dispatcher_test.go]: nit, we should introduce a helper like ExpectAdmissionChecksToBeActive by analogy to [ExpectClusterQueuesToBeActive](https://github.com/kubernetes-sigs/kueue/blob/af0d80ee04210a537fc25dda7a8e23445dbb2763/test/util/util.go#L1025)

I'm ok with a follow up, but it could also be this PR to introduce the function, wdyt?

File: test/integration/multikueue/dispatcher_test.go [hunk 26]
```diff
@@ -721,3 +718,359 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+		}
+
+		// Set quota reservation to trigger MultiKueue processing
+		createdWorkload := &kueue.Workload{}
+		admission := utiltesting.MakeAdmission(managerCq.Name).Obj()
+		gomega.Eventually(func(g gomega.Gomega) error {
+			if err := managerTestCluster.client.Get(managerTestCluster.ctx, workloadLookupKey, createdWorkload); err != nil {
+				return err
+			}
+			util.SetQuotaReservation(managerTestCluster.ctx, managerTestCluster.client, workloadLookupKey, admission)
```
Comment (mimowo) [inline test/integration/multikueue/dispatcher_test.go]: This function already does Eventually, do we still need another Eventually as a wrapper? https://github.com/kubernetes-sigs/kueue/blob/af0d80ee04210a537fc25dda7a8e23445dbb2763/test/util/util.go#L785

File: test/integration/multikueue/dispatcher_test.go [hunk 27]
```diff
@@ -721,3 +718,359 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+		util.ExpectObjectToBeDeleted(worker2TestCluster.ctx, worker2TestCluster.client, worker2Cq, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, multiKueueAC, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, managerMultiKueueConfig, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, workerCluster1, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, workerCluster2, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, managerMultiKueueSecret1, true)
+		util.ExpectObjectToBeDeleted(managerTestCluster.ctx, managerTestCluster.client, managerMultiKueueSecret2, true)
+	})
+
+	ginkgo.It("should create workload and nominate only worker1 when config contains single cluster", func() {
```
Comment (mimowo) [inline test/integration/multikueue/dispatcher_test.go]: Would this test fail or pass on the main branch?

File: test/integration/multikueue/dispatcher_test.go [hunk 28]
```diff
@@ -721,3 +718,359 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+				managerMultiKueueConfig.Spec.Clusters = []string{workerCluster1.Name, workerCluster2.Name}
+				return managerTestCluster.client.Update(managerTestCluster.ctx, managerMultiKueueConfig)
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+			// Wait for admission check to remain active with both clusters
+			gomega.Eventually(func(g gomega.Gomega) {
+				updatedAdmissionCheck := kueue.AdmissionCheck{}
+				g.Expect(managerTestCluster.client.Get(managerTestCluster.ctx, client.ObjectKeyFromObject(multiKueueAC), &updatedAdmissionCheck)).To(gomega.Succeed())
+				g.Expect(updatedAdmissionCheck.Status.Conditions).To(utiltesting.HaveConditionStatusTrue(kueue.AdmissionCheckActive))
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
```
Comment (mimowo) [inline test/integration/multikueue/dispatcher_test.go]: Here we could use the helper I mentioned in a comment above

File: test/integration/multikueue/dispatcher_test.go [hunk 29]
```diff
@@ -721,3 +718,359 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+
+			// Wait for workload to be propagated to worker2 and set reservation there
+			gomega.Eventually(func(g gomega.Gomega) {
+				remoteWorkload := &kueue.Workload{}
+				g.Expect(worker2TestCluster.client.Get(worker2TestCluster.ctx, workloadLookupKey, remoteWorkload)).To(gomega.Succeed())
+				util.SetQuotaReservation(worker2TestCluster.ctx, worker2TestCluster.client, workloadLookupKey, admission)
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+			// Verify workload is not created on worker1 (insufficient resources)
```
Comment (mimowo) [inline test/integration/multikueue/dispatcher_test.go]: Is this accurate? I think the workloads are created on all workers regardless of the amount of resources. I think what happens here is that the workload gets deleted, because the copy on worker2 gets admitted.

File: test/integration/multikueue/dispatcher_test.go [hunk 30]
```diff
@@ -721,3 +718,359 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+			gomega.Eventually(func(g gomega.Gomega) error {
+				if err := managerTestCluster.client.Get(managerTestCluster.ctx, workloadLookupKey, createdWorkload); err != nil {
+					return err
+				}
+				util.SetQuotaReservation(managerTestCluster.ctx, managerTestCluster.client, workloadLookupKey, admission)
+				return nil
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+		})
+
+		ginkgo.It("should re-evaluate existing workload when worker2 is added to config", func() {
```
Comment (mimowo) [inline test/integration/multikueue/dispatcher_test.go:843]: IIUC this is the main new "test", the one above would pass on main, and the one below is testing downstream workload processing which isn't really affected by the new code. 

If my understanding is correct then I propose to only keep this test: "should re-evaluate existing workload when worker2 is added to config", and drop the others.

File: test/integration/multikueue/dispatcher_test.go [hunk 31]
```diff
@@ -721,3 +718,359 @@ var _ = ginkgo.Describe("MultiKueueDispatcherAllAtOnce", ginkgo.Ordered, ginkgo.
...
+			}
+
+			// Set quota reservation to trigger MultiKueue processing
+			createdWorkload = &kueue.Workload{}
+			admission = utiltesting.MakeAdmission(managerCq.Name).Obj()
+			gomega.Eventually(func(g gomega.Gomega) error {
+				if err := managerTestCluster.client.Get(managerTestCluster.ctx, workloadLookupKey, createdWorkload); err != nil {
+					return err
+				}
+				util.SetQuotaReservation(managerTestCluster.ctx, managerTestCluster.client, workloadLookupKey, admission)
```
Comment (mimowo) [inline test/integration/multikueue/dispatcher_test.go]: SetQuotaReservation already encapsulates Eventually

**Comment by mimowo** [comment]
LGTM overall, thank you, but the integration test scenarios seem to go much beyond the new code. I asked a comment to verify my understanding, and if confirmed we can simplify the testing scenarios.

File: test/integration/multikueue/dispatcher_test.go (hunk 30 above)
Comment (ravisantoshgudimetla) [reply test/integration/multikueue/dispatcher_test.go:843]: Fair enough, I just kept this test and dropped the others.

**Comment by ravisantoshgudimetla** [comment]
> I asked a comment to verify my understanding, and if confirmed we can simplify the testing scenarios.

Some of existing tests were not covering the actual workload creation scenario. However, I removed the test which checks the existing functionality and fixed the compilation errors. PTAL

**Comment by mimowo** [comment]
@ravisantoshgudimetla I completely missed the PR might already be ready. Could you please answer all addressed comments so that it is obvious if they are addressed or not? It makes reviewing much easier rather than reverse engineering the state of the comments.

File: test/integration/multikueue/dispatcher_test.go (hunk 25 above)
Comment (ravisantoshgudimetla) [reply test/integration/multikueue/dispatcher_test.go]: Done

File: test/integration/multikueue/dispatcher_test.go (hunk 28 above)
Comment (ravisantoshgudimetla) [reply test/integration/multikueue/dispatcher_test.go]: Done

File: test/integration/multikueue/dispatcher_test.go (hunk 31 above)
Comment (ravisantoshgudimetla) [reply test/integration/multikueue/dispatcher_test.go]: Removed it.

**Comment by ravisantoshgudimetla** [comment]
>I completely missed the PR might already be ready. Could you please answer all addressed 

I have resolved all the comments that are outdated. Please take a look now.

**Review by mimowo — COMMENTED** [review]
Thanks
/lgtm
/approve
/cherrypick release-0.14
/cherrypick release-0.13

**Comment by mimowo** [comment]
/test pull-kueue-test-e2e-main-1-33
This is a known flake https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6732/pull-kueue-test-e2e-main-1-33/1981240333270257664

**Comment by mimowo** [comment]
I took ownership of backporting the fix as we are planning to release today
