### PR TITLE
Fix concurrent admission in cohort when borrowing

### LINKED ISSUE #804: Concurrent preemption within cohort can lead to over-admission.
**What happened**:
In a scenario in which we have three cluster  queues `cqA`, `cqB` and `cqC` with the same quotas, within the same cohort, and having two workloads admitted in `cqA`  which evenly us the entire cohort resources.

Creating two workloads in `cqB` and `cqC` using the full nominal quotas, will only preempt one workload in `cqA` and admit both.
 
**What you expected to happen**:

Both workload in `cqA` should be preempted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kueue version (use `git describe --tags --dirty --always`): v0.4.0-devel-130-g9d3ecbc

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Giving a situation with a cohort composed of more than two queues, in which at least one queue is borrowing resources , when two new workloads are evaluated for admission within the same scheduling cycle, since the two workloads are not aware of each other,   they both can be evaluated as fit leading to over-admitting workloads within the cohort.

A simple solution could be to make sure that only one workload within a cohort is evaluated for admission within a single scheduling cycle, however since this can be a b drastic, we are limiting this limit to cohorts in which any of  its queues is borrowing.

#### Which issue(s) this PR fixes:

Fixes #804

#### Does this PR introduce a user-facing change?

```release-note
Fix: Potential over-admission within cohort when borrowing.
```

### CODE REVIEW

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -140,14 +140,15 @@ func (s *Scheduler) schedule(ctx context.Context) {
...
 		cq := snapshot.ClusterQueues[e.ClusterQueue]
-		if e.assignment.Borrows() && cq.Cohort != nil && usedCohorts.Has(cq.Cohort.Name) {
-			e.status = skipped
-			e.inadmissibleMsg = "workloads in the cohort that don't require borrowing were prioritized and admitted first"
-			continue
-		}
-		// Even if there was a failure, we shouldn't admit other workloads to this
-		// cohort.
 		if cq.Cohort != nil {
+			e.assignment.Borrows()
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:144]: it looks like you forgot to remove this line

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -140,14 +140,15 @@ func (s *Scheduler) schedule(ctx context.Context) {
...
+			if usedCohorts.Has(cq.Cohort.Name) && (e.assignment.Borrows() || cq.Cohort.HasBorrowingQueues()) {
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:145]: can you explain why this new check solves the bug in the PR description and what other alternatives you considered and why they didn't work?

I'm wondering whether this check is excessive.

IIUC, the over-admission would happen in the second scheduling cycle:
- one workload was already preempted
- two workloads try to use the space, the first one fits.
- The second one is not aware that the first one was just scheduled. Could we just call `snapshot.AddWorkload` when we call `AssumeWorkload`?

And this also makes me think that there is a bug even without preemption, in an scenario very similar to the integration test you have below. Disable preemption and just mark one of the beta workloads as finished after you have already created the workloads for alpha and gamma.

File: test/integration/scheduler/preemption_test.go [hunk 3]
```diff
@@ -289,6 +302,60 @@ var _ = ginkgo.Describe("Preemption", func() {
...
+			betaHighWl := testing.MakeWorkload("beta-high", ns.Name).
+				Queue(betaQ.Name).
+				Priority(highPriority).
+				Request(corev1.ResourceCPU, "3").
+				Obj()
+			gomega.Expect(k8sClient.Create(ctx, betaHighWl)).To(gomega.Succeed())
+
+			util.ExpectWorkloadsToBeAdmitted(ctx, k8sClient, betaCQ.Name, betaMidWl, betaHighWl)
+
+			ginkgo.By("Creating workload in alpha-cq and game-cq that need to preempt")
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption_test.go:324]:
```suggestion
			ginkgo.By("Creating workload in alpha-cq and gamma-cq that need to preempt")
```

File: test/integration/scheduler/preemption_test.go [hunk 4]
```diff
@@ -185,8 +185,8 @@ var _ = ginkgo.Describe("Preemption", func() {
 
 	ginkgo.Context("In a ClusterQueue that is part of a cohort", func() {
 		var (
-			alphaCQ, betaCQ *kueue.ClusterQueue
-			alphaQ, betaQ   *kueue.LocalQueue
+			alphaCQ, betaCQ, gamaCQ *kueue.ClusterQueue
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption_test.go:188]:
```suggestion
			alphaCQ, betaCQ, gammaCQ *kueue.ClusterQueue
```

File: test/integration/scheduler/preemption_test.go [hunk 5]
```diff
@@ -289,6 +302,60 @@ var _ = ginkgo.Describe("Preemption", func() {
...
+			util.FinishEvictionForWorkloads(ctx, k8sClient, betaMidWl)
+
+			// one of alpha-mid and gama-mid should be admitted
+			var firstAdmitted []*kueue.Workload
+			gomega.Eventually(func() []*kueue.Workload {
+				firstAdmitted = util.FilterAdmittedWorkloads(ctx, k8sClient, alphaMidWl, gamaMidWl)
+				return firstAdmitted
+			}, util.Timeout, util.Interval).Should(gomega.HaveLen(1))
+			// and stay that way
+			gomega.Consistently(util.FilterAdmittedWorkloads(ctx, k8sClient, alphaMidWl, gamaMidWl), util.ConsistentDuration, util.Interval).Should(gomega.Equal(firstAdmitted))
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption_test.go:351]: we shouldn't need this check. We should avoid calling `Consistently` as it's pretty much a busy wait.

We can instead confirm that both workloads are admitted at the end, and verify that the preempted workloads are not admitted anymore.

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/scheduler/scheduler.go:144]: Please add a comment to this check to summarize why we are doing it.

File: test/integration/scheduler/preemption_test.go [hunk 6]
```diff
@@ -185,8 +185,8 @@ var _ = ginkgo.Describe("Preemption", func() {
 
 	ginkgo.Context("In a ClusterQueue that is part of a cohort", func() {
```
[the remark this answers is not in the document]
Comment (trasc) [reply test/integration/scheduler/preemption_test.go:186]: We besides using the preemption,  I don't think we have a way to ensure the workloads will be evaluated in the same scheduling cycle, I've added a unit test for it.

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/scheduler/scheduler.go:144]: Please add the comment

File: pkg/scheduler/scheduler_test.go [hunk 7]
```diff
@@ -605,6 +609,110 @@ func TestSchedule(t *testing.T) {
...
+							Flavors: map[corev1.ResourceName]kueue.ResourceFlavorReference{
+								corev1.ResourceCPU: "spot",
+							},
+							ResourceUsage: corev1.ResourceList{
+								corev1.ResourceCPU: resource.MustParse("100000m"),
+							},
+							Count: 100,
+						},
+					).Obj(),
+				"eng-beta/new": *utiltesting.MakeAdmission("eng-beta", "one").Assignment(corev1.ResourceCPU, "on-demand", "50000m").AssignmentPodCount(50).Obj(),
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler_test.go:709]: it looks like `eng-beta/new` and `eng-beta/new-gamma` could have the same chance of being scheduled?

Could this unit test flake depending on the randomness of sort?

File: pkg/scheduler/scheduler_test.go [hunk 8]
```diff
@@ -605,6 +609,110 @@ func TestSchedule(t *testing.T) {
...
+					).
+					Admit(utiltesting.MakeAdmission("eng-alpha").
+						PodSets(
+							kueue.PodSetAssignment{
+								Name: "borrow-on-demand",
+								Flavors: map[corev1.ResourceName]kueue.ResourceFlavorReference{
+									corev1.ResourceCPU: "on-demand",
+								},
+								ResourceUsage: corev1.ResourceList{
+									corev1.ResourceCPU: resource.MustParse("51000m"),
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler_test.go:643]:
```suggestion
									corev1.ResourceCPU: resource.MustParse("51"),
```

**Review by alculquicondor — COMMENTED** [review]
just some nits

/approve

**Review by alculquicondor — COMMENTED** [review]
just some nits

/approve

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (trasc) [reply pkg/scheduler/scheduler.go:150]: done

File: pkg/scheduler/scheduler_test.go (hunk 8 above)
Comment (trasc) [reply pkg/scheduler/scheduler_test.go]: done

File: pkg/scheduler/scheduler_test.go (hunk 7 above)
Comment (trasc) [reply pkg/scheduler/scheduler_test.go]: at this point no, `new` will always have a timestamp <= to the one in of `new-gamma` .. but let'm make sure is always smaller.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/label tide/merge-method-squash

**Comment by alculquicondor** [comment]
tests failing due to https://github.com/kubernetes/test-infra/issues/29622

**Comment by alculquicondor** [comment]
@trasc can you create a manual cherry-pick for the release-0.3 branch?

**Comment by trasc** [comment]
will do
