### PR TITLE
Fix the availability check after rolling restart

### LINKED ISSUE #7919: [flaky test] ManageJobsWithoutQueueName when manageJobsWithoutQueueName=true and LocalQueueDefaulting=false should suspend a job
/kind flake 

**What happened**:
failure https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7899/pull-kueue-test-e2e-customconfigs-main/1993718563780694016
**What you expected to happen**:
no fail
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:
```
End To End Custom Configs handling Suite: kindest/node:v1.34.0: [It] ManageJobsWithoutQueueName when manageJobsWithoutQueueName=true and LocalQueueDefaulting=false should suspend a job expand_less	51s
{Expected success, but got an error:
    <*errors.StatusError | 0xc000bfa1e0>: 
    conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post "https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s": EOF
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post \"https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s\": EOF",
            Reason: "",
            Details: nil,
            Code: 500,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc000bfa1e0>: 
    conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post "https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s": EOF
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post \"https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s\": EOF",
            Reason: "",
            Details: nil,
            Code: 500,
        },
    }
In [AfterEach] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/customconfigs/managejobswithoutqueuename_test.go:86 @ 11/26/25 16:41:21.303
}
```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind failing-test
/kind flake

#### Which issue(s) this PR fixes:

Fixes #7919

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go [hunk 1]
```diff
@@ -212,11 +212,6 @@ var _ = ginkgo.Describe("ManageJobsWithoutQueueName", ginkgo.Ordered, func() {
 					g.Expect(createdJob.Labels).ShouldNot(gomega.HaveKeyWithValue(controllerconstants.QueueLabel, "default"))
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
 			})
-			ginkgo.By("setting feature gates back to its original state", func() {
```
Comment (mimowo) [inline test/e2e/customconfigs/managejobswithoutqueuename_test.go:215]: Also dropping this call because it is already in the afterEach: https://github.com/kubernetes-sigs/kueue/pull/7925/files#diff-7fb50105d6ea57d298c2788bec48c38c69a071f60834733bec81814c93e8bf4cR108-R112

**Comment by mimowo** [comment]
cc @sohankunkerkar @mbobrovskyi

File: test/e2e/customconfigs/managejobswithoutqueuename_test.go (hunk 1 above)
Comment (mimowo) [reply test/e2e/customconfigs/managejobswithoutqueuename_test.go:215]: I take it back after seeing: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7925/pull-kueue-test-e2e-customconfigs-main/1993751471627177984
I got confused by afterEach from another When

**Review by sohankunkerkar — APPROVED** [review]
/lgtm
