### PR TITLE
Fix integration test on release-0.10

### LINKED ISSUE #4344: Failing Test: MXJob controller when TopologyAwareScheduling enabled should admit workload which fits in a required topology domain
**What happened**:
Flaky integration tests: `MXJob Controller Suite: [It] MXJob controller when TopologyAwareScheduling enabled should admit workload which fits in a required topology domain [Redundant]`

```
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:313 with:
Not enough workloads are admitted
Expected
    <int>: 0
to equal
    <int>: 1 failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:313 with:
Not enough workloads are admitted
Expected
    <int>: 0
to equal
    <int>: 1
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/controller/jobs/mxjob/mxjob_controller_test.go:446 @ 02/21/25 01:44:58.745
}
```

**What you expected to happen**:
Non errros.

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-release-0-10/1892750118059249664

Image

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by nasedil**
In cb91c2464a7750532e1b24350285f2a41a838a17 the test was not updated.

#### What type of PR is this?
/king bug
/kind flake

#### What this PR does / why we need it:
Integration test fails in release-0.10
#### Which issue(s) this PR fixes:

Fixes #4344

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/controller/jobs/mxjob/mxjob_controller_test.go [hunk 1]
```diff
@@ -359,6 +359,7 @@ var _ = ginkgo.Describe("MXJob controller when TopologyAwareScheduling enabled",
 				StatusAllocatable(corev1.ResourceList{
 					corev1.ResourceCPU:    resource.MustParse("1"),
 					corev1.ResourceMemory: resource.MustParse("1Gi"),
+					corev1.ResourcePods:   resource.MustParse("10"),
```
Comment (tenzen-y) [inline test/integration/controller/jobs/mxjob/mxjob_controller_test.go:362]: Ah, I guess this happened by my change...
Thank you!
