### PR TITLE
Respect configured webhook.certDir in cert-manager rotator

### LINKED ISSUE #5430: Inconsistent `certDir` handling between Kueue configuration and cert-manager rotator.
Currently, Kueue allows configuring an alternative `webhook.certDir` via the manager configuration.
However, the internal cert-manager rotator still uses the default constant value:
`/tmp/k8s-webhook-server/serving-certs`.

As a result, if `webhook.certDir` is set to a custom value in the configuration, the Kueue manager fails to start successfully. This issue is particularly impactful when running the Kueue manager with webhook support in local mode, where custom certificate paths are often required.

Expected behavior:
When a custom webhook.certDir is configured, the cert-manager rotator should respect and use that same directory, ensuring compatibility and successful startup.

**What happened**:
The Kueue manager failed to start when a custom (non-default) `certDir` was specified.

**What you expected to happen**:
The Kueue manager should start successfully with the provided custom `certDir`.

**How to reproduce it (as minimally and precisely as possible)**:
Start the Kueue manager with a configuration that sets webhook.certDir to a custom path (different from the default `/tmp/k8s-webhook-server/serving-certs`).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ichekrygin**
The cert-manager rotator previously used a hardcoded default certificate directory (/tmp/k8s-webhook-server/serving-certs), ignoring the configured webhook.certDir value. This commit updates the logic to use the configured value if provided, falling back to the default only when necessary.

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #5430

#### Does this PR introduce a user-facing change?
No

```release-note
Fix the bug that the webhook certificate setting under `controllerManager.webhook.certDir` was ignored by the internal cert manager, effectively always defaulting to /tmp/k8s-webhook-server/serving-certs.
```

### CODE REVIEW

**Comment by mimowo** [comment]
Thanks 👍 
/release-note-edit
```release-note
Fix the bug that the webhook certificate setting under `controllerManager.webhook.certDir` was ignored by the internal cert manager, effectively always defaulting to /tmp/k8s-webhook-server/serving-certs.
```
cc @PBundyra @tenzen-y 
/lgtm

**Comment by mimowo** [comment]
I'm leaving approve to Yuki

File: pkg/util/cert/cert.go [hunk 1]
```diff
@@ -44,6 +44,12 @@ func ManageCerts(mgr ctrl.Manager, cfg config.Configuration, setupFinished chan
 	// DNSName is <service name>.<namespace>.svc
 	var dnsName = fmt.Sprintf("%s.%s.svc", *cfg.InternalCertManagement.WebhookServiceName, *cfg.Namespace)
 
+	// Use the CertDir provided by the webhook configuration, defaulting to "/tmp/k8s-webhook-server/serving-certs".
+	certDir := cfg.Webhook.CertDir
+	if certDir == "" {
+		certDir = defaultCertDir
+	}
+
```
Comment (tenzen-y) [inline pkg/util/cert/cert.go]: Could you move this defaulitng to https://github.com/kubernetes-sigs/kueue/blob/main/apis/config/v1beta1/defaults.go so that we can avoid splitting defaulting places?

Comment (mimowo) [reply pkg/util/cert/cert.go]: +1

Comment (ichekrygin) [reply pkg/util/cert/cert.go]: Yeah, I’m definitely in favor of consolidating defaulting logic in defaults.go — makes things cleaner and easier to maintain.

That said, I wanted to bring up one concern. This particular default is tied to Kueue’s internal cert management, which is gated behind a condition in main.go. Since users can disable that feature entirely, I’m wondering if setting the default globally (regardless of whether the feature is enabled) could have any unintended side effects.

This PR follows the pattern from controller-runtime where the default is set closer to the webhook setup, which kind of makes sense given it’s only relevant if cert management is turned on.

I’m not super deep in all areas of the Kueue codebase, so just raising this in case it might cause confusion or issues when cert management is disabled. Curious what others (@tenzen-y) think.

Comment (mimowo) [reply pkg/util/cert/cert.go]: I will leave Yuki to answer more but you could do the defaulting only when internal certs management is enabled. Note that the config defaulting is applied on bootup, so it will apply depending on the user enablement of the internal certs management feature.

Comment (tenzen-y) [reply pkg/util/cert/cert.go]: Yes, we should default this value only when internal certmanagement is enabled in https://github.com/kubernetes-sigs/kueue/blob/e3bbc66fa7c95df49668a33934e9ae9c97d9b65a/apis/config/v1beta1/configuration_types.go#L68-L69

**Comment by mimowo** [comment]
@ichekrygin  the unit tests need adjustments, otherwise LGTM, thanks 👍

File: apis/config/v1beta1/defaults.go [hunk 2]
```diff
@@ -74,6 +75,9 @@ func SetDefaults_Configuration(cfg *Configuration) {
 	if cfg.Webhook.Port == nil {
 		cfg.Webhook.Port = ptr.To(DefaultWebhookPort)
 	}
+	if cfg.Webhook.CertDir == "" {
```
Comment (tenzen-y) [inline apis/config/v1beta1/defaults.go:78]: Could you check if internalCertManagement is enabled as we discussed?

Comment (ichekrygin) [reply apis/config/v1beta1/defaults.go:78]: Hi @tenzen-y  yes — I can add this check.

That said, while I don’t have a strong preference either way, I wanted to share a quick thought: tying the default value of `cfg.Webhook.CertDir` to the state (nil or enabled/disabled) of a separate component — in this case, `internalCertManagement` — feels a bit suboptimal. The two are related, but `internalCertManagement` is more of a downstream concern.

Instead, I opted to set a default for `cfg.Webhook.CertDir` if it’s not provided, regardless of whether `internalCertManagement` is enabled. This feels more in line with how `cfg.Webhook.Port` is handled just a few lines above.

Curious to hear what you think about this approach.

Comment (mimowo) [reply apis/config/v1beta1/defaults.go:78]: From my PoV: I'm ok either way, but indeed I see value in consistency. So I'm leaning to leave as is, just adjust the unit tests.

Comment (tenzen-y) [reply apis/config/v1beta1/defaults.go:78]: I'm ok with keeping the current condition. Once we want to add InternalCermanagement enabling guard, we can add it later.

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve

**Comment by tenzen-y** [comment]
/test pull-kueue-test-integration-baseline-main

due to https://github.com/kubernetes-sigs/kueue/issues/5395
