### PR TITLE
Make sure worker nodes are ready before reporting cluster created

### LINKED ISSUE #8911: [Flaky MultiKueue E2E] MultiKueue when Connection via ClusterProfile with plugins Should be able to use ClusterProfile as way to connect worker cluster
/kind flake

**What happened**:

End To End MultiKueue Suite: kindest/node:v1.34.3: [It] MultiKueue when Connection via ClusterProfile with plugins Should be able to use ClusterProfile as way to connect worker cluster 

```
{Timed out after 300.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/e2e.go:250 with:
Expected
    <string>: ReplicaSetUpdated
to equal
    <string>: NewReplicaSetAvailable failed [FAILED] Timed out after 300.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/e2e.go:250 with:
Expected
    <string>: ReplicaSetUpdated
to equal
    <string>: NewReplicaSetAvailable
In [BeforeAll] at: /home/prow/go/src/kubernetes-sigs/kueue/test/util/e2e.go:626 @ 01/30/26 11:33:40.885
}
```

**What you expected to happen**:

No errors

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-multikueue-main/2017192467891228672

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Make sure worker nodes are ready before we continue to setup test on the cluster.

#### Which issue(s) this PR fixes:

Fixes #8911

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm

Thank you!

File: hack/e2e-common.sh [hunk 1]
```diff
@@ -308,6 +255,8 @@ function cluster_create {
     ||  { echo "unable to start the $1 cluster "; cat "$ARTIFACTS/$1-create.log" ; }
 
     kubectl config --kubeconfig="$3" use-context "kind-$1"
+    # wait for worker nodes to be ready before loading images or deploying components
+    kubectl wait --kubeconfig="$3" --for=condition=Ready node --selector='!node-role.kubernetes.io/control-plane' --timeout=300s
```
Comment (mimowo) [inline hack/e2e-common.sh]: why do you exclude the `node-role.kubernetes.io/control-plane'` from the check? I think it is also expected to get ready?

Comment (mszadkow) [reply hack/e2e-common.sh]: a worker node cannot become "Ready" unless a control-plane node is "Ready" and functioning
 so we wait for worker

Comment (mimowo) [reply hack/e2e-common.sh]: I don't get it. So if you remove the check it will not work?

Comment (mimowo) [reply hack/e2e-common.sh]: I mean the selector `--selector='!node-role.kubernetes.io/control-plane'`

Comment (vladikkuzn) [reply hack/e2e-common.sh]: @mszadkow maybe we can remove this check and wait for both CP and workers?

Comment (mimowo) [reply hack/e2e-common.sh]: +1, let's see - if this does not work, then we revert to as is, basically I would say ` kubectl wait --kubeconfig="$3" --for=condition=Ready node  --timeout=300s`

because I still couldn't understand why the selector is needed, so maybe the logs will be helpful to explain the problem when it happens on CI.

**Comment by mimowo** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9081/pull-kueue-test-e2e-kueueviz-main/2021860470830403584
@mszadkow ptal it does not seem related, but i don't know

**Comment by mimowo** [comment]
let me retest

**Comment by mszadkow** [comment]
> https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9081/pull-kueue-test-e2e-kueueviz-main/2021860470830403584 @mszadkow ptal it does not seem related, but i don't know

I found it was related, hopefully fixed now

**Comment by mbobrovskyi** [comment]
@mszadkow could you please prepare cherry-picks?
