### PR TITLE
Differentiate error message for cohort and cluster queue

### LINKED ISSUE #4392: Misleading error message when cohort has no parent and have borrowingLimit
**What happened**:
When defining a cohort that has no parent cohort and has `borrowingLimit` the following error message is shown:
```
admission webhook "vcohort.kb.io" denied the request: spec.resourceGroups[0].flavors[0].resources[0].borrowingLimit: Invalid value: "0": must be nil when cohort is empty
```
The message is misleading because clusterQueue object has `cohort` field for its parent cohort while cohort object has `parent` field for it's parent cohort.  And the error message is same for both cases.
**What you expected to happen**:
The message could end with `must be nil when parent is empty` or`must be nil when parent cohort is empty`.
**How to reproduce it (as minimally and precisely as possible)**:
Applying the following YAML file:
```
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: pod-performance-resource-flavor
---
apiVersion: kueue.x-k8s.io/v1alpha1
kind: Cohort
metadata:
  name: test-cohort
spec:
  # there is no parent cohort
  # parent: ~
  resourceGroups:
    - coveredResources: ["pods"]
      flavors:
        - name: "pod-performance-resource-flavor"
          resources:
            - name: "pods"
              nominalQuota: 1
              borrowingLimit: 0
...
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.31.5
- Kueue version (use `git describe --tags --dirty --always`):  v0.11.0-devel-244-gfd6a5206
- Cloud provider or hardware configuration: GCP GKE
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by nasedil**
When parent cohort is empty it uses "parent" for cohort and "cohort" for cluster queue.

#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
It fixes misleading error message in case of empty parent for hierarchical cohort and non-zero borrowing/lending limit.
#### Which issue(s) this PR fixes:

Fixes #4392 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/webhooks/clusterqueue_webhook_test.go [hunk 1]
```diff
@@ -156,7 +157,7 @@ func TestValidateClusterQueue(t *testing.T) {
 					*testingutil.MakeFlavorQuotas("x86").Resource("cpu", "1", "", "1").Obj()).
 				Obj(),
 			wantErr: field.ErrorList{
-				field.Invalid(resourceGroupsPath.Index(0).Child("flavors").Index(0).Child("resources").Index(0).Child("lendingLimit"), "1", limitIsEmptyErrorMsg),
+				field.Invalid(resourceGroupsPath.Index(0).Child("flavors").Index(0).Child("resources").Index(0).Child("lendingLimit"), "1", fmt.Sprintf(limitIsEmptyErrorMsgTemplate, "cohort")),
```
Comment (gabesaba) [inline pkg/webhooks/clusterqueue_webhook_test.go:160]: please write literal string in test

File: pkg/webhooks/cohort_webhook.go [hunk 2]
```diff
@@ -75,6 +75,6 @@ func validateCohort(cohort *kueuealpha.Cohort) field.ErrorList {
 	var allErrs field.ErrorList
 
 	allErrs = append(allErrs, validateFairSharing(cohort.Spec.FairSharing, path.Child("fairSharing"))...)
-	allErrs = append(allErrs, validateResourceGroups(cohort.Spec.ResourceGroups, config, path.Child("resourceGroups"))...)
+	allErrs = append(allErrs, validateResourceGroups(cohort.Spec.ResourceGroups, config, path.Child("resourceGroups"), true)...)
```
Comment (gabesaba) [inline pkg/webhooks/cohort_webhook.go:78]: can we cover this message with a test case?

File: pkg/webhooks/clusterqueue_webhook_test.go (hunk 1 above)
Comment (nasedil) [reply pkg/webhooks/clusterqueue_webhook_test.go:160]: wrote the literal string, but it's is ignored when running tests:
https://github.com/kubernetes-sigs/kueue/blob/2b92883a0ec779ef0cd38b369b316fa0828bfcb4/pkg/webhooks/clusterqueue_webhook_test.go#L335-L336

I can try to modify the logic so that error strings are actually compared.

Comment (nasedil) [reply pkg/webhooks/clusterqueue_webhook_test.go:160]: However, it's ignored in other tests as well, and it makes sense to not compare error detail messages in most of the cases.  Maybe we can make an exception just for this particular subtest.

File: pkg/webhooks/cohort_webhook.go (hunk 2 above)
Comment (nasedil) [reply pkg/webhooks/cohort_webhook.go:78]: I've added a test for cohort where error detail message is not ignored and compared to the expected message

File: pkg/webhooks/clusterqueue_webhook.go [hunk 3]
```diff
@@ -200,10 +201,16 @@ func validateResourceQuantity(value resource.Quantity, fldPath *field.Path) fiel
...
 
-// validateLimit enforces that BorrowingLimit or LendingLimit must be nil when cohort is empty
-func validateLimit(limit resource.Quantity, config validationConfig, fldPath *field.Path) field.ErrorList {
+// validateLimit enforces that BorrowingLimit or LendingLimit must be nil when cohort (or parent cohort) is empty
+func validateLimit(limit resource.Quantity, config validationConfig, fldPath *field.Path, isCohort bool) field.ErrorList {
 	var allErrs field.ErrorList
 	if !config.hasParent {
+		var limitIsEmptyErrorMsg string
+		if isCohort {
+			limitIsEmptyErrorMsg = fmt.Sprintf(limitIsEmptyErrorMsgTemplate, "parent")
```
Comment (mwielgus) [inline pkg/webhooks/clusterqueue_webhook.go:210]: Why returning parent when isCohort?

**Comment by mimowo** [comment]
/approve
Thanks!
