### PR TITLE
Apply admission checks covering all CQ resources to workloads before flavor assigned

### LINKED ISSUE #7254: Combination of MultiKueue and a non-MultiKueue AdmissionChecks may return an empty list
One of the MultiKueue constraints is that it always applies to all RFs in a CQ. In theory a Workload submitted to such a CQ doesn't need admission (flavor assignment) because regardless of the flavor it would always use the MultiKueue AdmissionCheck - this is what happens [here](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/workload/workload.go#L1180-L1191) - before we check for admission, if all AdmissionChecks applies to all RFs in a CQ it returns a list of the AdmissionChecks. It works correctly if MultiKueue is the only AdmissionCheck in a CQ, but we suspect it would break if there was combination of MultiKueue and an AdmissionCheck that should be run only on part of the flavors. Then the code would return an empty list of AdmissionChecks, even there should be the MultiKueue one (according to its assumption).

In particular, deleting [the code which should merely be a microoptimization](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/workload/workload.go#L1180-L1191) breaks the integration test case `MultiKueue when not all integrations are enabled [It] Should not create a MPIJob workload, when MPIJob adapter is not enabled` ([test run](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6785/pull-kueue-test-integration-multikueue-main/1975539260094156800)).

What's happening is that the admissionCheck [here](https://github.com/kubernetes-sigs/kueue/blob/dc263e01760ce118ee580a4a6816dae6fbba962b/test/integration/multikueue/jobs_test.go#L1442) is `Pending` just as the test expects - but then it changes to `nil` because [this code](https://github.com/kubernetes-sigs/kueue/blob/dc263e01760ce118ee580a4a6816dae6fbba962b/pkg/workload/workload.go#L1196-L1199) is now executed (previously the microoptimization was returning the function a few lines above). The test is failing, because its check happens already after `Pending` has changed into `nil`.

What's worse, even if I comment out [this expectation](https://github.com/kubernetes-sigs/kueue/blob/dc263e01760ce118ee580a4a6816dae6fbba962b/test/integration/multikueue/jobs_test.go#L1441-L1450), the test is failing a [couple lines below](https://github.com/kubernetes-sigs/kueue/blob/dc263e01760ce118ee580a4a6816dae6fbba962b/test/integration/multikueue/jobs_test.go#L1478), as `worker2 wl` is never removed.

When investigating the test run with a debugger, [workload.go:456](https://github.com/kubernetes-sigs/kueue/blob/5a6b10a710386852e5b57ce91896dd47c583cfcf/pkg/controller/admissionchecks/multikueue/workload.go#L456) and then [workload_controller.go:543](https://github.com/kubernetes-sigs/kueue/blob/5a6b10a710386852e5b57ce91896dd47c583cfcf/pkg/controller/core/workload_controller.go#L543) are triggered. Then [`UnsetQuotaReservationWithCondition`](https://github.com/kubernetes-sigs/kueue/blob/dc263e01760ce118ee580a4a6816dae6fbba962b/pkg/controller/jobframework/reconciler.go#L540) happens, and inside it `Status.Admission` is set to `nil`.

The PR should consist of:
1. Create an integration test similar to the one that currently fails (with deletion of the linked part of the code) and add AdmissionCheckStrategy to it, with an AdmissionCheck defined only for a one out of two flavors in the CQ - this should prove that there's indeed a bug. No need to change anything in the production code, let's just add another integration test.
1. When we prove that there's indeed a bug, fix the linked part of the code so that whenever there's a MultiKueue AdmissionCheck it should always be returned, regardless of different AdmissionChecks

### PR DESCRIPTION
**Pull request by Singularity23x0**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Bug:
Currently, the MultiKueue admission check (which is required to span all resources of a Cluster Queue)
is applied to workloads inside the Workload Controller when it does not have an admission (quota reservation) ONLY when the CQ's admission checks all cover every resource flavor defined for the CQ (i.e. defined in its Resource Groups).

This leads to an issue described in #7254:

1. We define a CQ on the Manager. It support flavor1 and flavor2. On the CQ we define the MK AC and an additional, custom AC spanning only flavor1.
1. A workload is admitted to the CQ on the Manager and has a Remote Workload Admitted on a Worker Cluster.
1. We loose connection to the Worker, but the Worker is still running. In this case, after enough time the Manager will Backoff the workload and, in the current implementation, remove both ACs, since the custom one does not support all flavors on the CQ.
1. Now if the worker gets reconnected, but the manager workload no longer has the MK AC, we will not process it in the MK Reconciler, meaning the remote workload admitted on the now reconnected Worker will continue running until the AC check is re-added to the WL on the Manager (aka when it gets an admission). All the while the underlying job will continue executing on the Worker. This means it will reserve resources there while manager workload may have proceeded to dispatch to and admit on a different worker in the meantime, causing a double reservation of resources invisible to the Manager.

Fix:
The PR updates the logic assigning/removing admission checks to/from the workload in Workload Controller.
Now, all checks that apply to all resource flavors of a Cluster Queue will be applied to the Workload even before an admission with a flavor is populated, EVEN if other ACs that span only some resources of the CQ are defined.
For the MK AC - this means the check should be applied to all workloads targeting the CQ anointed with one.

#### Which issue(s) this PR fixes:

Fixes #7254

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
AdmissionChecks: fix the bug that on backoff admission checks which are spanning all ResourceFlavors, such as MultiKueue, may be missing in the Workload’s status. 

For MultiKueue that manifested with a bug, when aside from the MultiKueue admission check there was another non-MultiKueue admission check. In the scenario when eviction on the management cluster happened the manager that had temporarily lost connection to a worker, the remote workload would keep running on the reconnected worker, despite the workload staying without reservation on the manager cluster.
```

### CODE REVIEW

File: pkg/workload/workload.go [hunk 1]
```diff
@@ -1305,42 +1305,50 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+	if assignedFlavors := admissionFlavors(wl.Status.Admission); len(assignedFlavors) > 0 {
+		return checksForFlavors(allChecks, assignedFlavors)
+	}
+
+	// If unable to determine flavors assigned to a workload we can only list
+	// the checks which apply to all flavors supported by the ClusterQueue.
+	allFlavors := queue.AllFlavors(cq.Spec.ResourceGroups)
+	checksForAllFlavors := sets.New[kueue.AdmissionCheckReference]()
+	for acName, acFlavors := range allChecks {
+		if allFlavors.Difference(acFlavors).Len() == 0 {
```
Comment (kshalot) [inline pkg/workload/workload.go]: `Equal` is a better fit here https://pkg.go.dev/github.com/R167/go-sets#Set.Equal

**Comment by Singularity23x0** [comment]
> Out of curiosity, what is the real world scenario in which MultiKueue is combined with other AdmissionChecks?

Basing it on https://github.com/kubernetes-sigs/kueue/issues/7254.

1. We define a CQ on the Manager. It support flavor1 and flavor2. On the CQ we define the MK AC and an additional, custom AC spanning only flavor1.
2. A workload is admitted to the CQ on the Manager and has a Remote Workload Admitted on a Worker Cluster.
3. We loose connection to the Worker, but the Worker is still running. In this case, after enough time the Manager will Backoff the workload and, in the current implementation, remove both ACs, since the custom one does not support all flavors on the CQ.
4. Now if the worker gets reconnected, but the manager workload no longer has the MK AC, we will not process it in the MK Reconciler, meaning the remote workload admitted on the now reconnected Worker will continue running until the AC check is re-added to the WL on the Manager (aka when it gets an admission). All the while the underlying job will continue executing on the Worker.


This PR remedies that by ensuring that in the Workload Controller specifically the logic adds/keeps all admission checks that span all resources on the workload, meaning the MK admission check will remain on the WL in this case and the MK Reconciler will ensure the Remote Workload is deleted form the worker since the Manager WL has no quota reservation atm.

File: pkg/workload/workload.go (hunk 1 above)
Comment (Singularity23x0) [reply pkg/workload/workload.go]: The diff is used here as the user can define an ac to cover more flavors than defined in the Resource Groups. In this case if feel more intuitive to add this checks right away since it has to cover any flavor the wl may be assigned. This is supported by the fact that once we get an admission such an AC would in fact be added to the wl no matter the flavor CQ assigned to it.

**Comment by Singularity23x0** [comment]
> I'll do another review pass later, but posting one minor thing already.
> 
> Also - I'd consider rewording the release note a little bit. Maybe try to focus on the impact or some specific scenario that was fixed? Just so it's clear to the user what exactly was shipped. Right now it's pretty cryptic. Especially this part - `This was already possible under specific circumstances, which this PR loosens by expanding the amount of cases such checks can be added in advance.`. I feel that it's very vague.

Updated the desc, PTAL.

**Comment by mwielgus** [comment]
> > Out of curiosity, what is the real world scenario in which MultiKueue is combined with other AdmissionChecks?
> 
> Basing it on #7254.
> 
> 1. We define a CQ on the Manager. It support flavor1 and flavor2. On the CQ we define the MK AC and an additional, custom AC spanning only flavor1.
> 2. A workload is admitted to the CQ on the Manager and has a Remote Workload Admitted on a Worker Cluster.
> 3. We loose connection to the Worker, but the Worker is still running. In this case, after enough time the Manager will Backoff the workload and, in the current implementation, remove both ACs, since the custom one does not support all flavors on the CQ.
> 4. Now if the worker gets reconnected, but the manager workload no longer has the MK AC, we will not process it in the MK Reconciler, meaning the remote workload admitted on the now reconnected Worker will continue running until the AC check is re-added to the WL on the Manager (aka when it gets an admission). All the while the underlying job will continue executing on the Worker.
> 
> This PR remedies that by ensuring that in the Workload Controller specifically the logic adds/keeps all admission checks that span all resources on the workload, meaning the MK admission check will remain on the WL in this case and the MK Reconciler will ensure the Remote Workload is deleted form the worker since the Manager WL has no quota reservation atm.

This I understand. The question was more about what other AdmissionChecks make sense together with MK.

**Comment by Singularity23x0** [comment]
> This I understand. The question was more about what other AdmissionChecks make sense together with MK.

I don't have any concrete examples as of right now. I can only speak in general terms.

Given that a user can define custom admission checks with dedicated controllers we can't guarantee no one will ever decide to implement such an AC to further customize how MK behaves for specific resource flavors.

Whether that should be allowed to happen (and if yes - should its current handling remain or be updated) is another matter with its own caveats. Currently:
* Such a check would not affect the dispatch of a workload itself unless it enters the Rejected or Retry state. In fact, the check could remain in the Pending state, keeping the workload on the manager from being admitted (condition admitted), but the quota would be reserved and remotes would be created as usual. This could even lead to the workload finishing without being officially admitted at all. This behavior is not ideal and inconsistent with what an AC is meant to be doing: instead of keeping the workload from admission until Ready, it keeps it from admission only after it is Rejected (or Retrying after rejection).
* Even though the workload can end up finished despite such a check never leaving the Pending state, the check could enter the Rejected or Retry state, leading to the workloads eviction and removal of all of the remote workloads.


If we do not want to handle additional checks on an MK CQ, then a separate PR should be created to adjust the restrictions on Manager Cluster Queues. I added the summary provided here to the bug report: #7254. PTAL and lets discuss there.

File: pkg/workload/workload.go [hunk 2]
```diff
@@ -1341,42 +1305,50 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+			checksForAllFlavors.Insert(acName)
 		}
 	}
-	if hasAllFlavors {
-		return sets.New(slices.Collect(maps.Keys(admissionChecks))...)
-	}
+	return checksForAllFlavors
```
Comment (mimowo) [inline pkg/workload/workload.go:1530]: IIUC this is the rare scenario, so it seems beneficial to log. It would also let us keep the logger. I don't like to remove logger because it makes diff bigger and later we will likely need to re-add it anyway.

File: test/integration/singlecluster/controller/core/clusterqueue_controller_test.go [hunk 3]
```diff
@@ -966,23 +966,40 @@ var _ = ginkgo.Describe("ClusterQueue controller", ginkgo.Label("controller:clus
...
+			).AdmissionChecks(kueue.AdmissionCheckReference(check.Name)).Obj()
 			lq = utiltestingapi.MakeLocalQueue("queue", ns.Name).ClusterQueue(cq.Name).Obj()
 			util.MustCreate(ctx, k8sClient, lq)
 			util.MustCreate(ctx, k8sClient, cq)
+
+			podSetAssignment := utiltestingapi.MakePodSetAssignment(kueue.DefaultPodSetName).Flavor(
+				resourceGPU,
+				kueue.ResourceFlavorReference(flavor.Name),
+			).Obj()
+			cqAdmission = utiltestingapi.MakeAdmission(cq.Name).PodSets(podSetAssignment).Obj()
```
Comment (mimowo) [inline test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]: TBH I don't like moving that. Sure it avoids duplication, but it makes diff bigger as requires checking the pre-existing code, and also conceptually doesn't fit here. Because the shape of the admission depends on the Workload, and the Workload is created in the body of the test, not in Before section

Comment (Singularity23x0) [reply test/integration/singlecluster/controller/core/clusterqueue_controller_test.go]: Moved back into the body.

File: pkg/workload/workload.go (hunk 2 above)
Comment (Singularity23x0) [reply pkg/workload/workload.go:1530]: Reintroduced loger.

**Comment by mimowo** [comment]
> This I understand. The question was more about what other AdmissionChecks make sense together with MK.

I think so, but even if we wouldn't see a use-case yet, someone may discover since the AdmissionChecks allow for any external mechanism. So, we should basically conform to the API we allow with validation.

One example we discussed in the context of external ACs is "budgeting". I can imagine someone wants to check the budget at the Manager cluster level, for two reasons:
1. to make the budget check accurate - otherwise it would require the external AC to have some synchronization database reachable from the different clusters
2. to avoid throttling at the worker clusters later in the pipeline

File: pkg/util/testing/v1beta2/wrappers.go [hunk 4]
```diff
@@ -946,6 +946,16 @@ func (c *ClusterQueueWrapper) AdmissionChecks(checks ...kueue.AdmissionCheckRefe
...
 
+// Adds an additional admission check.
+func (c *ClusterQueueWrapper) WithAdmissionCheck(check kueue.AdmissionCheckReference, flavors ...kueue.ResourceFlavorReference) *ClusterQueueWrapper {
+	newRule := kueue.AdmissionCheckStrategyRule{
+		Name:      check,
+		OnFlavors: flavors,
+	}
+	c.Spec.AdmissionChecksStrategy.AdmissionChecks = append(c.Spec.AdmissionChecksStrategy.AdmissionChecks, newRule)
+	return c
+}
```
Comment (kshalot) [inline pkg/util/testing/v1beta2/wrappers.go]: There's already an `AdmissionCheckStrategy` function where you can pass `AdmissionCheckStrategyRule`s for the `ClusterQueueWrapper`.

I'd consider re-using that. Right now you are writing sth like this in the tests:
```
...
AdmissionChecks("check1", "check2").
WithAdmissionCheck("check3", kueue.ResourceFlavorReference(flavor2.Name)).
...
```

Which is not very clear IMO.

File: pkg/scheduler/scheduler.go [hunk 5]
```diff
@@ -678,17 +678,17 @@ func (s *Scheduler) admit(ctx context.Context, e *entry, cq *schdcache.ClusterQu
 	return nil
 }
 
-func (s *Scheduler) prepareWorkload(log logr.Logger, wl *kueue.Workload, cq *schdcache.ClusterQueueSnapshot, admission *kueue.Admission) {
+func (s *Scheduler) prepareWorkload(wl *kueue.Workload, cq *schdcache.ClusterQueueSnapshot, admission *kueue.Admission) {
 	workload.SetQuotaReservation(wl, admission, s.clock)
-	if workload.HasAllChecks(wl, workload.AdmissionChecksForWorkload(log, wl, cq.AdmissionChecks, schdcache.AllFlavors(cq.ResourceGroups))) {
```
Comment (kshalot) [inline pkg/scheduler/scheduler.go:736]: Is the `schdcache.AllFlavors` function relevant anymore? From what I can see, https://github.com/kubernetes-sigs/kueue/pull/6785 introduced the same function to calculate all flavors 3 times.

[Here](https://github.com/kubernetes-sigs/kueue/blob/9feb05e01205ceed50876a9c4e3c03246ade51e1/pkg/util/admissioncheck/admissioncheck.go#L175) it also calculates `allFlavors` in a loop, which is redundant.

Not strictly related to this PR, but we might want a follow-up with a cleanup.

File: pkg/workload/workload.go [hunk 6]
```diff
@@ -1305,42 +1306,69 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+	for acName, acFlavors := range allChecks {
+		if allFlavors.Difference(acFlavors).Len() == 0 {
+			checksForAllFlavors.Insert(acName)
 		}
 	}
-	if hasAllFlavors {
-		return sets.New(slices.Collect(maps.Keys(admissionChecks))...)
+
+	if checksForAllFlavors.Len() == 0 {
+		log.V(3).Info("Unable to determine required admission checks.")
```
Comment (kshalot) [inline pkg/workload/workload.go]: This message sounds very ominous without additional context - I'd mention it's because of the flavors not being assigned yet.

File: pkg/workload/workload.go [hunk 7]
```diff
@@ -1305,42 +1306,69 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+	} else {
+		log.V(3).Info(
+			"Found admission checks required for all workloads in ClusterQueue regrardless of assigned flavors.",
```
Comment (kshalot) [inline pkg/workload/workload.go]:
```suggestion
			"Found admission checks required for all workloads in ClusterQueue regardless of assigned flavors.",
```

File: pkg/workload/workload.go [hunk 8]
```diff
@@ -1305,42 +1306,69 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+		klog.KObj(cq),
+	)
+	allChecks := admissioncheck.NewAdmissionChecks(cq)
+
+	// If we have an admission with flavors assigned we can provide all relevant checks right away.
+	if assignedFlavors := admissionFlavors(wl.Status.Admission); len(assignedFlavors) > 0 {
+		return checksForFlavors(allChecks, assignedFlavors)
+	}
+
+	log.V(2).Info("Workload has no Admission.")
```
Comment (kshalot) [inline pkg/workload/workload.go]: Wouldn't we want a bit more context in this log? Right now it would say sth like "reconciler : workload : clusterqueue : Workload has no Admission.". I'd mention that we are determining admission checks etc.

File: pkg/scheduler/scheduler.go (hunk 5 above)
Comment (Singularity23x0) [reply pkg/scheduler/scheduler.go:736]: The allFlavors vs AllFlavors issue is one of dependencies - when trying to clean this code up I encountered a warning abt circular dependencies but was unable to pinpoint which imports were exactly the problem.

In terms of there being two AllFlavors functions - they use different types of "ResourceGroup" - one uses the definition from v1beta2, one a local definition.

File: pkg/workload/workload.go (hunk 8 above)
Comment (Singularity23x0) [reply pkg/workload/workload.go]: Updated.

File: pkg/workload/workload.go [hunk 9]
```diff
@@ -1346,42 +1347,61 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+	return checksForAllFlavors
+}
 
-	// Kueue sets AdmissionChecks first based on ClusterQueue configuration and at this point Workload has no
-	// ResourceFlavors assigned, so we cannot match AdmissionChecks to ResourceFlavor.
-	// After Quota is reserved, another reconciliation happens and we can match AdmissionChecks to ResourceFlavors
-	if wl.Status.Admission == nil {
-		log.V(2).Info("Workload has no Admission", "Workload", klog.KObj(wl))
+// ChecksRequiredForAdmission returns all admission checks that apply to the specified admission based on assigned flavors.
+func ChecksRequiredForAdmission(allChecks map[kueue.AdmissionCheckReference]sets.Set[kueue.ResourceFlavorReference], admission *kueue.Admission) sets.Set[kueue.AdmissionCheckReference] {
```
Comment (pajakd) [inline pkg/workload/workload.go]: Perhaps `ChecksRequiredForAdmission` can be removed completely since its just calling `checksForFlavors` anyway and it is only used within the `workload` package. WDYT?

File: pkg/workload/workload.go [hunk 10]
```diff
@@ -1346,42 +1347,61 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+	for _, podSet := range admission.PodSetAssignments {
 		for _, flavor := range podSet.Flavors {
-			assignedFlavors = append(assignedFlavors, flavor)
+			assignedFlavors.Insert(flavor)
 		}
 	}
+	return assignedFlavors
+}
 
+func checksForFlavors(admissionChecks map[kueue.AdmissionCheckReference]sets.Set[kueue.ResourceFlavorReference], flavors sets.Set[kueue.ResourceFlavorReference]) sets.Set[kueue.AdmissionCheckReference] {
```
Comment (pajakd) [inline pkg/workload/workload.go]: perhaps change it to a more general `filterChecks` function that also receives a predicate as an argument. You would be able to use it to compute the `checksForAllFlavors` above and remove some duplicated logic.

File: test/integration/multikueue/jobs_test.go [hunk 11]
```diff
@@ -1970,6 +1971,221 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
...
+			util.SetAdmissionCheckActive(managerTestCluster.ctx, managerTestCluster.client, additionalAc, metav1.ConditionTrue)
+
+			flavor1Quotas := *utiltestingapi.MakeFlavorQuotas(additionalFlavor1.Name).Resource(corev1.ResourceCPU, "10").Obj()
+			flavor2Quotas := *utiltestingapi.MakeFlavorQuotas(additionalFlavor2.Name).Resource(corev1.ResourceMemory, "100Gi").Obj()
+			resourceGroups := []kueue.ResourceGroup{
+				utiltestingapi.ResourceGroup(flavor1Quotas),
+				utiltestingapi.ResourceGroup(flavor2Quotas),
+			}
+
+			flavor1Rule := *utiltestingapi.MakeAdmissionCheckStrategyRule(
```
Comment (pajakd) [inline test/integration/multikueue/jobs_test.go]: I'm a bit confused -- this rule is for both flavors but its called `flavor1Rule`?

File: test/integration/multikueue/jobs_test.go [hunk 12]
```diff
@@ -1970,6 +1971,221 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
...
+					ResourceUsage: corev1.ResourceList{
+						corev1.ResourceCPU: resource.MustParse("1"),
+					},
+				},
+			)
+
+			admitWorkloadAndCheckWorkerCopies(multiKueueAC.Name, wlLookupKey, admission)
+
+			var disconnectedTime time.Time
+			ginkgo.By("breaking the connection to worker2", func() {
```
Comment (pajakd) [inline test/integration/multikueue/jobs_test.go]: It is described in the test that we are breaking the connection, but if this is going to be used in other multikueue tests in the future then perhaps encapsulate it in a helper function.

File: test/integration/multikueue/jobs_test.go [hunk 13]
```diff
@@ -1970,6 +1971,221 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
...
+					acs := admissioncheck.FindAdmissionCheck(createdWorkload.Status.AdmissionChecks, kueue.AdmissionCheckReference(multiKueueAC.Name))
+					g.Expect(acs).To(gomega.BeComparableTo(&kueue.AdmissionCheckState{
+						Name:       kueue.AdmissionCheckReference(multiKueueAC.Name),
+						State:      kueue.CheckStatePending,
+						RetryCount: ptr.To(int32(1)),
+					}, cmpopts.IgnoreFields(kueue.AdmissionCheckState{}, "LastTransitionTime", "Message")))
+				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
+			})
+
+			ginkgo.By("restoring the connection to worker2", func() {
```
Comment (pajakd) [inline test/integration/multikueue/jobs_test.go]: not sure if possible, but it would be nice to have a function that breaks the connection to return a callable to restore it that we would just call here.

File: test/integration/multikueue/jobs_test.go [hunk 14]
```diff
@@ -1970,6 +1971,221 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
 			}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
 		})
 	})
+
+	ginkgo.When("an additional admission check covering only some flavors supported by the cluster queue is present", func() {
```
Comment (pajakd) [inline test/integration/multikueue/jobs_test.go:1860]: have you checked:
1. that the test is not flaky (by running it in a loop for a while)?
2. that the test is failing without the code change?

Comment (Singularity23x0) [reply test/integration/multikueue/jobs_test.go:1860]: 1. Yes.
1. Yes.

**Comment by Singularity23x0** [comment]
> To the description:
> 
> > All the while the underlying job will continue executing on the Worker.
> 
> Not sure if it is obvious what the correct behavior should be but could you perhaps write why this is wrong?
> 
> +there is a typo "olny"

Updated.

File: test/integration/multikueue/jobs_test.go (hunk 11 above)
Comment (Singularity23x0) [reply test/integration/multikueue/jobs_test.go]: An artifact of a previous test version. Cleaning up.

File: pkg/workload/admissionchecks.go [hunk 15]
```diff
@@ -158,9 +158,13 @@ func HasAllChecksReady(wl *kueue.Workload) bool {
...
 
-// HasAllChecks returns true if all the mustHaveChecks are present in the workload.
+// HasAllRequiredChecks returns true if all the relevant checks are present in the workload.
 // (They don't have to be in the Ready state; for that, see HasAllChecksReady).
-func HasAllChecks(wl *kueue.Workload, mustHaveChecks sets.Set[kueue.AdmissionCheckReference]) bool {
+func HasAllRequiredChecks(wl *kueue.Workload, allChecks map[kueue.AdmissionCheckReference]sets.Set[kueue.ResourceFlavorReference]) bool {
+	admissionFlavors := admissionFlavors(wl.Status.Admission)
+	mustHaveChecks := filterChecks(allChecks, func(acFlavors flavorSet) bool {
+		return admissionFlavors.Intersection(acFlavors).Len() > 0
+	})
```
Comment (olekzabl) [inline pkg/workload/admissionchecks.go]: Why not call `AdmissionChecksForWorkload` here?

File: pkg/workload/workload.go [hunk 16]
```diff
@@ -1403,48 +1404,64 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
-	// Kueue sets AdmissionChecks first based on ClusterQueue configuration and at this point Workload has no
-	// ResourceFlavors assigned, so we cannot match AdmissionChecks to ResourceFlavor.
-	// After Quota is reserved, another reconciliation happens and we can match AdmissionChecks to ResourceFlavors
-	if wl.Status.Admission == nil {
-		log.V(2).Info("Workload has no Admission", "Workload", klog.KObj(wl))
-		return nil
+	// If we have an admission with flavors assigned we can provide all relevant checks right away.
+	if assignedFlavors := admissionFlavors(wl.Status.Admission); len(assignedFlavors) > 0 {
+		return filterChecks(allChecks, func(acFlavors flavorSet) bool {
+			return assignedFlavors.Intersection(acFlavors).Len() > 0
```
Comment (olekzabl) [inline pkg/workload/workload.go]: This confused me - I had to go & check that cq.AdmissionChecks specifies all flavors for ACs like the MK one. (I mean, that user-facing API of "no flavors" is internally translated to "all flavors").
As you rely on it, I'd consider adding an explicit comment on the ClusterQueue.AdmissionChecks field that it behaves like this. Then it'll be easier to deduce that the code here is correct.
WDYT?

File: pkg/workload/workload.go [hunk 17]
```diff
@@ -1403,48 +1404,64 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
-		for _, flavor := range podSet.Flavors {
-			assignedFlavors = append(assignedFlavors, flavor)
-		}
-	}
+	// If unable to determine flavors assigned to a workload we can only list
+	// the checks which apply to all flavors supported by the ClusterQueue.
+	allFlavors := queue.AllFlavors(cq.Spec.ResourceGroups)
+	checksForAllFlavors := filterChecks(allChecks, func(acFlavors flavorSet) bool {
+		return allFlavors.Difference(acFlavors).Len() == 0
+	})
```
Comment (olekzabl) [inline pkg/workload/workload.go:1524]: I'm thinking if it wouldn't be better to "cache" it inside the `cq` object, rather than compute anew every time.

For precedence, `cq` already has fields like e.g. `perFlavorMultiKueueAdmissionChecks` - which feels a similar case. And in that case someone has decided to precompute & store.

WDYT?

File: pkg/workload/workload.go [hunk 18]
```diff
@@ -1403,48 +1404,64 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+	log.V(3).Info(
+		"Workload has no Admission: assigning only checks that apply to all workloads in the Cluster Queue regardless of flavor",
+		"Assigned AdmissionChecks",
+		checksForAllFlavors,
+	)
+	return checksForAllFlavors
+}
 
+// filterChecks rerurns the names of all admission checks with a flavor set fulfilling the predicate.
```
Comment (olekzabl) [inline pkg/workload/workload.go]:
```suggestion
// filterChecks returns the names of all admission checks with a flavor set fulfilling the predicate.
```

File: pkg/workload/admissionchecks.go (hunk 15 above)
Comment (Singularity23x0) [reply pkg/workload/admissionchecks.go]: The method differs in that it allows for the wl not to have an admission check. Here - we expect the ac to exist. Due to that difference I decided to keep the two methods separate. On the other hand I saw no point in encapsualting the "filterChecks" call in a separate function (i.e. `checksForAdmission`) as it is only a wrapper that would define the predicate and that seemed like overcomplicating it.

File: pkg/workload/workload.go (hunk 16 above)
Comment (Singularity23x0) [reply pkg/workload/workload.go]: On it.

File: pkg/workload/workload.go (hunk 17 above)
Comment (Singularity23x0) [reply pkg/workload/workload.go:1524]: Yes but that is a differenc cluster queue.
You are talking about the scheduler cache implementation of the cq.
This here is the cq object we load from the client. We would have to choose the best place to store it in kueue memory (queue or scheduler cache) and ensure the data is always there and synchronized when performing this in case of the workload controller. I am hesitant to say it is in the scope of this PR as the previous logic also performed the calculation every time.

I can create a followup clean-up-issue if you wish.

Comment (olekzabl) [reply pkg/workload/workload.go:1524]: Ah I see. Good point. Then I wouldn't even request a follow-up.

File: pkg/workload/admissionchecks.go (hunk 15 above)
Comment (olekzabl) [reply pkg/workload/admissionchecks.go]: Following [another thread](https://github.com/kubernetes-sigs/kueue/pull/9359#discussion_r2911918108), I'm now realizing calling it here would be cumbersome as we don't have the proper `cq` at this point :)

So, anyway, ignore.

File: pkg/workload/workload_test.go [hunk 19]
```diff
@@ -1180,6 +1157,97 @@ func TestAdmissionCheckStrategy(t *testing.T) {
 	}
 }
 
+func TestFlavorResourceUsage(t *testing.T) {
```
Comment (olekzabl) [inline pkg/workload/workload_test.go]: AFAICS this test func is completely unchanged; you just moved it.
(Leading to a large diff as reported by GitHub. At least for me).

Can you help other reviewers by moving this back?

File: pkg/workload/workload_test.go [hunk 20]
```diff
@@ -1156,22 +1064,91 @@ func TestAdmissionCheckStrategy(t *testing.T) {
...
-			wantAdmissionChecks: nil,
+			wantAdmissionChecks: sets.New[kueue.AdmissionCheckReference]("ac1", "ac2"),
+		},
+	}
+	for name, tc := range cases {
+		t.Run(name, func(t *testing.T) {
+			admissionFlavors := admissionFlavors(tc.wl.Status.Admission)
+			gotAdmissionChecks := filterChecks(admissioncheck.NewAdmissionChecks(tc.cq), func(acFlavors flavorSet) bool {
+				return admissionFlavors.Intersection(acFlavors).Len() > 0
+			})
```
Comment (olekzabl) [inline pkg/workload/workload_test.go]: Hmm, what is being tested here?

This essentially duplicates the logic which you've added to `HasAllRequiredAdmissionChecks`.
I consider this problematic: e.g. when that logic there gets updated, this test will continue to test the _old_ behavior (hardcoded here).

I propose extracting that logic to a common helper method. I mean: `HasAllRequiredAdmissionChecks` should call that helper and then this will become the proper unit test of that helper.

File: pkg/workload/workload_test.go [hunk 21]
```diff
@@ -1156,22 +1064,91 @@ func TestAdmissionCheckStrategy(t *testing.T) {
...
+
+			if diff := cmp.Diff(tc.wantAdmissionChecks, gotAdmissionChecks); diff != "" {
+				t.Errorf("Unexpected AdmissionChecks, (want-/got+):\n%s", diff)
+			}
+		})
+	}
+}
+
+func TestAdmissionCheckListingForWorkload(t *testing.T) {
```
Comment (olekzabl) [inline pkg/workload/workload_test.go]: [optional]

This is a unit test for `AdmissionChecksForWorkload`, moreover, the only unit test for that method, so I'd call it `Test<exactly-method-name>`.
I guess it's not mandatory (in particular, the existing code already broke that convention) - but I don't see a reason to invent special names.
Do you?

(BTW this will also apply to the the func above, if you follow [my other comment](https://github.com/kubernetes-sigs/kueue/pull/9359/changes#r2914822119) there)

File: pkg/workload/workload_test.go [hunk 22]
```diff
@@ -1156,22 +1064,91 @@ func TestAdmissionCheckStrategy(t *testing.T) {
...
+	now := time.Now().Truncate(time.Second)
+	cases := map[string]struct {
+		wl                  *kueue.Workload
+		wantAdmissionChecks sets.Set[kueue.AdmissionCheckReference]
+	}{
+		"Only relevant checks returend for an admitted workload": {
```
Comment (olekzabl) [inline pkg/workload/workload_test.go]:
```suggestion
		"Only relevant checks returned for an admitted workload": {
```

File: pkg/workload/workload_test.go [hunk 23]
```diff
@@ -1156,22 +1064,91 @@ func TestAdmissionCheckStrategy(t *testing.T) {
...
+				ReserveQuotaAt(utiltestingapi.MakeAdmission("cq").
+					PodSets(utiltestingapi.MakePodSetAssignment(kueue.DefaultPodSetName).
+						Assignment("cpu", "flavor1", "1").
+						Assignment("memory", "flavor2", "1").
+						Obj()).
+					Obj(), now).
+				Obj(),
+			wantAdmissionChecks: sets.New[kueue.AdmissionCheckReference]("ac1", "ac2", "ac3", "ac4", "ac6"),
+		},
+		"Only correct checks covering all relevant flavors returned for Wrokload without Quota Reserved ": {
```
Comment (olekzabl) [inline pkg/workload/workload_test.go]:
```suggestion
		"Only correct checks covering all relevant flavors returned for Workload without Quota Reserved ": {
```

File: test/util/util.go [hunk 24]
```diff
@@ -1201,6 +1201,64 @@ func IsLoggedEntryAConcurrentModification(le observer.LoggedEntry) bool {
 	return strings.Contains(errorDetals, expectedConcurrentModiciationDetails)
 }
 
+// BreakConnection breaks connection to the cluster, then returns:
+// a callback to restore the connection AND
+// the timestamp of becoming disconnected
+func BreakConnection(ctx context.Context, cli client.Client, cluster *kueue.MultiKueueCluster) (func(), time.Time) {
+	var disconnectedTime time.Time
```
Comment (olekzabl) [inline test/util/util.go]: Most of such test helpers (calling `ginkgo`, `gomega` etc.) start with `ginkgo.GinkgoHelper()`.
Please consider.

File: test/util/util.go [hunk 25]
```diff
@@ -1201,6 +1201,64 @@ func IsLoggedEntryAConcurrentModification(le observer.LoggedEntry) bool {
...
+				Reason: "BadKubeConfig",
+			}, IgnoreConditionMessage, IgnoreConditionTimestampsAndObservedGeneration))
+			disconnectedTime = activeCondition.LastTransitionTime.Time
+		}, Timeout, Interval).Should(gomega.Succeed())
+	})
+
+	return createConnectionRestoringCallback(ctx, cli, cluster, trueLocation), disconnectedTime
+}
+
+func createConnectionRestoringCallback(ctx context.Context, cli client.Client, cluster *kueue.MultiKueueCluster, location string) func() {
```
Comment (olekzabl) [inline test/util/util.go:1389]: Nit: instead of `cluster`, you could pass just `clusterKey`; you seem to need only this.

File: test/integration/multikueue/jobs_test.go [hunk 26]
```diff
@@ -1214,25 +1215,7 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
...
-				g.Expect(managerTestCluster.client.Get(managerTestCluster.ctx, client.ObjectKeyFromObject(workerCluster2), createdCluster)).To(gomega.Succeed())
-				activeCondition := apimeta.FindStatusCondition(createdCluster.Status.Conditions, kueue.MultiKueueClusterActive)
-				g.Expect(activeCondition).To(gomega.BeComparableTo(&metav1.Condition{
-					Type:   kueue.MultiKueueClusterActive,
-					Status: metav1.ConditionFalse,
-					Reason: "BadKubeConfig",
-				}, util.IgnoreConditionMessage, util.IgnoreConditionTimestampsAndObservedGeneration))
-			}, util.Timeout, util.Interval).Should(gomega.Succeed())
-		})
+		restoreConnectionToWorker2, _ := util.BreakConnection(managerTestCluster.ctx, managerTestCluster.client, workerCluster2)
```
Comment (olekzabl) [inline test/integration/multikueue/jobs_test.go]: Niiice :)

File: test/integration/singlecluster/controller/core/workload_controller_test.go [hunk 27]
```diff
@@ -271,10 +284,11 @@ var _ = ginkgo.Describe("Workload controller", ginkgo.Label("controller:workload
 			util.ExpectObjectToBeDeleted(ctx, k8sClient, clusterQueue, true)
 			util.ExpectObjectToBeDeleted(ctx, k8sClient, check2, true)
 			util.ExpectObjectToBeDeleted(ctx, k8sClient, check1, true)
-			util.ExpectObjectToBeDeleted(ctx, k8sClient, flavor, true)
+			util.ExpectObjectToBeDeleted(ctx, k8sClient, flavor2, true)
+			util.ExpectObjectToBeDeleted(ctx, k8sClient, flavor1, true)
 		})
 
-		ginkgo.It("the workload should get the AdditionalChecks added", func() {
+		ginkgo.It("the workload should get the AdditionalChecks that cover all flavors added", func() {
```
Comment (olekzabl) [inline test/integration/singlecluster/controller/core/workload_controller_test.go]: I think this sentence parses ambiguously:

* A: ... should get the (ACs that cover all flavors) added
* B: ... should get the (ACs that cover all (flavors added))

Maybe not a big deal, but this differs subtly, and may be confusing. Please try clarifying.

BTW, I know it pre-existed, but what are "AdditionalChecks"? Kueue seems not to have SuchAThing.
(Did someone mean "AdmissionChecks"? Or should we de-capitalize this?)

File: test/integration/multikueue/jobs_test.go [hunk 28]
```diff
@@ -1970,6 +1860,182 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
...
 	})
+
+	ginkgo.When("an additional admission check covering only some flavors supported by the cluster queue is present", func() {
+		var (
+			additionalAc      *kueue.AdmissionCheck
+			additionalFlavor1 *kueue.ResourceFlavor
+			additionalFlavor2 *kueue.ResourceFlavor
+		)
+		ginkgo.BeforeEach(func() {
+			additionalFlavor1 = utiltestingapi.MakeResourceFlavor("flavor1").Obj()
```
Comment (olekzabl) [inline test/integration/multikueue/jobs_test.go]: In what sense is this flavor "additional"? Are there any "non-additional" flavors around?

File: test/util/util.go (hunk 25 above)
Comment (Singularity23x0) [reply test/util/util.go:1389]: Id prefer to keep it inside to avoid calling the client.ObjectKeyFromObject(cluster) bit multiple times.

File: test/integration/singlecluster/controller/core/workload_controller_test.go (hunk 27 above)
Comment (Singularity23x0) [reply test/integration/singlecluster/controller/core/workload_controller_test.go]: Additional meaning checks added later on top of the ones already set. I will reword to make it sound better.

File: test/integration/multikueue/jobs_test.go (hunk 28 above)
Comment (Singularity23x0) [reply test/integration/multikueue/jobs_test.go]: Renamed.

File: pkg/workload/workload_test.go (hunk 20 above)
Comment (Singularity23x0) [reply pkg/workload/workload_test.go]: Done.

File: pkg/controller/core/workload_controller_test.go [hunk 29]
```diff
@@ -2937,3 +2937,171 @@ func TestWorkloadDeletion(t *testing.T) {
...
+					Name:  "ac1",
+					State: kueue.CheckStatePending,
+				},
+				{
+					Name:  "ac2",
+					State: kueue.CheckStatePending,
+				},
+			},
+		},
+		"add only checks covering all flavors to unadmitterd wl from cq with strategy": {
```
Comment (olekzabl) [inline pkg/controller/core/workload_controller_test.go]:
```suggestion
		"add only checks covering all flavors to unadmitted wl from cq with strategy": {
```

File: pkg/workload/workload.go [hunk 30]
```diff
@@ -1403,48 +1404,79 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
-	// Kueue sets AdmissionChecks first based on ClusterQueue configuration and at this point Workload has no
-	// ResourceFlavors assigned, so we cannot match AdmissionChecks to ResourceFlavor.
-	// After Quota is reserved, another reconciliation happens and we can match AdmissionChecks to ResourceFlavors
-	if wl.Status.Admission == nil {
-		log.V(2).Info("Workload has no Admission", "Workload", klog.KObj(wl))
-		return nil
-	}
+	if wl.Status.Admission != nil {
+		// If we have an admission we can provide all relevant checks right away.
+		// Checks that are defined with an empty list of flavors are coinsidered
```
Comment (olekzabl) [inline pkg/workload/workload.go]:
```suggestion
		// Checks that are defined with an empty list of flavors are considered
```

File: pkg/controller/core/workload_controller_test.go [hunk 31]
```diff
@@ -3167,3 +3167,171 @@ func TestWorkloadDeletion(t *testing.T) {
...
+					Name:  "ac2",
+					State: kueue.CheckStatePending,
+				},
+			},
+		},
+		"add all cq checks to wl with empty assignment": {
+			wl: *utiltestingapi.MakeWorkload("wl", "ns").Admission(&kueue.Admission{
+				ClusterQueue:      "cq",
+				PodSetAssignments: []kueue.PodSetAssignment{},
+			}).Obj(), // todo admitted.Obj(),
```
Comment (gabesaba) [inline pkg/controller/core/workload_controller_test.go]: nit: cleanup todo

File: pkg/controller/core/workload_controller_test.go [hunk 32]
```diff
@@ -3167,3 +3167,171 @@ func TestWorkloadDeletion(t *testing.T) {
...
+					ClusterQueue: "cq",
+					PodSetAssignments: []kueue.PodSetAssignment{
+						{
+							Name: "p1",
+							Flavors: map[corev1.ResourceName]kueue.ResourceFlavorReference{
+								corev1.ResourceCPU: "flavor1",
+							},
+						},
+					},
+				}).Obj(), // todo admitted
```
Comment (gabesaba) [inline pkg/controller/core/workload_controller_test.go]: nit: cleanup

File: pkg/workload/admissionchecks.go [hunk 33]
```diff
@@ -158,9 +159,11 @@ func HasAllChecksReady(wl *kueue.Workload) bool {
 	return true
 }
 
-// HasAllChecks returns true if all the mustHaveChecks are present in the workload.
+// HasAllRequiredChecks returns true if all the relevant checks are present in the workload.
 // (They don't have to be in the Ready state; for that, see HasAllChecksReady).
-func HasAllChecks(wl *kueue.Workload, mustHaveChecks sets.Set[kueue.AdmissionCheckReference]) bool {
+func HasAllRequiredChecks(log logr.Logger, wl *kueue.Workload, allChecks map[kueue.AdmissionCheckReference]sets.Set[kueue.ResourceFlavorReference]) bool {
```
Comment (gabesaba) [inline pkg/workload/admissionchecks.go:165]: nit: consider defining an alias for map[kueue.AdmissionCheckReference]sets.Set[kueue.ResourceFlavorReference], as it is quite long and used several times (13 times in total in codebase). This can also be a follow-up PR to avoid drive-by cleanup

Comment (gabesaba) [inline pkg/workload/admissionchecks.go:165]: nit: do we want to check (or at least comment that) admission must be non-nil?

Comment (Singularity23x0) [reply pkg/workload/admissionchecks.go:165]: Will do in a follow up: https://github.com/Singularity23x0/kueue/tree/admission-check-map-alias

Comment (Singularity23x0) [reply pkg/workload/admissionchecks.go:165]: We can, though this should never happen - if it does it is not a legitimate kueue error, but rather a critical error with the code. If it happens, the error of denoting a null pointer should pop up either way, which is more appropriate in this scenario as the issue would be with the implementation.

File: pkg/workload/workload.go [hunk 34]
```diff
@@ -1498,48 +1499,79 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+	return checksForAllFlavors
+}
 
-	var assignedFlavors []kueue.ResourceFlavorReference
-	for _, podSet := range wl.Status.Admission.PodSetAssignments {
-		for _, flavor := range podSet.Flavors {
-			assignedFlavors = append(assignedFlavors, flavor)
-		}
+func admissionChecksForAdmission(log logr.Logger, acs map[kueue.AdmissionCheckReference]sets.Set[kueue.ResourceFlavorReference], admission kueue.Admission) sets.Set[kueue.AdmissionCheckReference] {
+	admissionFlavors := admissionFlavors(admission)
```
Comment (mwielgus) [inline pkg/workload/workload.go]: The local variable admissionFlavors shadows the package-level function name admissionFlavors. While valid in Go, it can be confusing for readers. Consider renaming.

File: pkg/workload/workload.go [hunk 35]
```diff
@@ -1498,48 +1499,79 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+		// because checks with empty OnFlavor lists have their lists populated
+		// with all flavors in the CQ when initially processed by Kueue.
+		return admissionChecksForAdmission(log, allChecks, *wl.Status.Admission)
+	}
+
+	// If no admission is present yet we can only list
+	// the checks which apply to all flavors supported by the ClusterQueue
+	allFlavors := queue.AllFlavors(cq.Spec.ResourceGroups)
+	checksForAllFlavors := filterChecks(allChecks, func(acFlavors flavorSet) bool {
+		return allFlavors.Difference(acFlavors).Len() == 0
```
Comment (mwielgus) [inline pkg/workload/workload.go]: Using acFlavors.IsSuperset(allFlavors) would be more readable and directly express the intent.

File: pkg/workload/admissionchecks.go [hunk 36]
```diff
@@ -158,9 +159,11 @@ func HasAllChecksReady(wl *kueue.Workload) bool {
...
+	mustHaveChecks := admissionChecksForAdmission(log, allChecks, *wl.Status.Admission)
```
Comment (mwielgus) [inline pkg/workload/admissionchecks.go:166]: Can wl.Status.Admission be nil?

Comment (Singularity23x0) [reply pkg/workload/admissionchecks.go:166]: No. This func is used only once, afer SetQuotaReservation. A nil in a workload passed here should be considered a programmer's error.

Comment (Singularity23x0) [reply pkg/workload/admissionchecks.go:166]: To make it more visible I added a mention of this to the doc.

File: pkg/workload/workload.go [hunk 37]
```diff
@@ -1498,48 +1499,79 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
+			return admissionFlavors.Intersection(acFlavors).Len() > 0
+		})
 	}
 
+	log.V(3).Info(
+		"Admission has no Flavors; assigning all checks",
+		"AdmissionChecks",
+		acs,
+	)
+	return sets.KeySet(acs)
```
Comment (kshalot) [inline pkg/workload/workload.go:1549]: In the release note you stated that this "(only affects tests)". Maybe this should be mentioned in the code as well, since it's not clear what this edge-case means.

Also - why does it only affect tests? Why do we need a branch that is test-specific in the core logic?

Comment (Singularity23x0) [reply pkg/workload/workload.go:1549]: Since outside of checks an admission should always have a request, which means a flavor will be assigned.
In a lot of tests workloads are created with empty requests however.

Comment (kshalot) [reply pkg/workload/workload.go:1549]: Is this logic change necessary? Looking at the OG code, if there are no assigned flavors the assigned ACs would be empty. This is slightly more intuitive to me.

Comment (Singularity23x0) [reply pkg/workload/workload.go:1549]: OG code logic would assign either:
1. All checks if all covered all flavors in the CQ.
2. No flavors otherwise.

I opted to make it "Assign all flavors always" for 2 reasons:
1. Existing tests that don't bother assigning flavors all expect all defined ACs (if any defined that is) to be applied.
2. It seems a safer default - we expect a flavor to be there - if it isn't it seems safer to force all checks onto it instead of letting it pass without issue. This way if a test defines checks and expects only some to apply, but the test author forgets to assign flavors, they will see their workload not admitted as unexpected checks block it, instead of being admitted due to no checks blocking, potentially producing a false positive.

Comment (kshalot) [reply pkg/workload/workload.go:1549]: If the OG code logic did not assign any checks in case 2 (I assume you meant "checks" not "flavors"), then how do existing tests expect all defined ACs to be applied?
> Existing tests that don't bother assigning flavors all expect all defined ACs (if any defined that is) to be applied.

Wouldn't those tests fail?

Since this is an "impossible" scenario, it feels unintuitive to me to handle it this way and having tests rely on this behavior instead of making them perform the correct setup. When I read this logic now, I think "ok, so there is a scenario where an admission has no flavors". I think some explanation is missing in the code at the very least.

Comment (Singularity23x0) [reply pkg/workload/workload.go:1549]: Beacause all existing tests that define checks but don't define flavors (or rather don't define resource requests for test workloads) create the checks with default flavors, meaning all checks cover all flavors and, in the past, had fallen into that category. There was only one exception to the rule which I have amended.

If we want to remove this logic and ensure the test setups are correct - i would say it is a good idea but it should be left to a followup that sweeps across all tests and corrects them. The change could be potentially significant and deserves its own issue for it. I can create the follow up issue describing the problem - lmk if that is to your satisfaction.

TL;DR - i agree with your point that it would be better to fix test setups, but that is too big a change to be a drive-by cleanup, and should be addressed in a followup cleanup-issue.

Comment (kshalot) [reply pkg/workload/workload.go:1549]: Just to make sure I understand - previously, we returned no admission checks in the case where admission has no flavors, now we are returning all of them. If the tests rely on having all of them returned, why didn't they fail on the main branch? Which tests rely on this behavior?

File: test/integration/multikueue/jobs_test.go [hunk 38]
```diff
@@ -1969,6 +1859,182 @@ var _ = ginkgo.Describe("MultiKueue", ginkgo.Label("area:multikueue", "feature:m
...
+
+			restoreConnectionToWorker2, disconnectedTime := util.BreakConnection(managerTestCluster.ctx, managerTestCluster.client, workerCluster2)
+
+			ginkgo.By("waiting for quotaReservation to be removed", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					createdWorkload := &kueue.Workload{}
+					g.Expect(managerTestCluster.client.Get(managerTestCluster.ctx, wlLookupKey, createdWorkload)).To(gomega.Succeed())
+					acs := admissioncheck.FindAdmissionCheck(createdWorkload.Status.AdmissionChecks, kueue.AdmissionCheckReference(multiKueueAC.Name))
+					// The transition interval should be close to testingKeepReadyTimeout (taking into account the resolution of the LastTransitionTime field)
+					g.Expect(acs.LastTransitionTime.Time).To(gomega.BeComparableTo(disconnectedTime.Add(testingWorkerLostTimeout), cmpopts.EquateApproxTime(2*time.Second)))
```
Comment (mimowo) [inline test/integration/multikueue/jobs_test.go]: Is checking the LastTransitionTime anyhow relevant here? It does not feel like responsibility of the PR really.

File: test/util/util.go [hunk 39]
```diff
@@ -1352,6 +1352,68 @@ func IsLoggedEntryAConcurrentModification(le observer.LoggedEntry) bool {
 	return strings.Contains(errorDetals, expectedConcurrentModiciationDetails)
 }
 
+// BreakConnection breaks connection to the cluster, then returns:
+// a callback to restore the connection AND
+// the timestamp of becoming disconnected
+func BreakConnection(ctx context.Context, cli client.Client, cluster *kueue.MultiKueueCluster) (restoreConnection func(), disconnectedTime time.Time) {
```
Comment (mimowo) [inline test/util/util.go]: This looks like a reasonable helper, but I'm not convinced the disconnectedTime is needed or useful here (also in another comment).

File: test/e2e/multikueue/e2e_test.go [hunk 40]
```diff
@@ -2417,22 +2417,38 @@ func ensurePodWorkloadsRunning(deployment *appsv1.Deployment, managerNs corev1.N
...
+			var admissionCheck *kueue.AdmissionCheckState
+			wlLookupKey := types.NamespacedName{Name: workloadpod.GetWorkloadNameForPod(pod.Name, pod.UID), Namespace: managerNs.Name}
+			ginkgo.By("Checking pod is admitted on manager", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					createdLeaderWorkload = &kueue.Workload{}
+					gomega.Expect(k8sManagerClient.Get(ctx, wlLookupKey, createdLeaderWorkload)).To(gomega.Succeed())
+					admissionCheck = admissioncheck.FindAdmissionCheck(createdLeaderWorkload.Status.AdmissionChecks, kueue.AdmissionCheckReference(multiKueueAc.Name))
+					gomega.Expect(admissionCheck.State).To(gomega.Equal(kueue.CheckStateReady))
+				}, util.VeryLongTimeout, util.Interval).Should(gomega.Succeed())
+			})
```
Comment (mimowo) [inline test/e2e/multikueue/e2e_test.go:2565]: This seems like a useful change, but again I'm not understanding how related to the PR. it seems it would also pass on the main branch, wouldn't it? If it works the same on the manager branch then I suggest to decouple the refactoring to a separate PR.

Comment (Singularity23x0) [reply test/e2e/multikueue/e2e_test.go:2565]: The thing is the test faces a race condition without this refactor - the effect should be the same but the way the test is written it may not be fast enough to catch the window when the workload is evicted. The tests then fails because the assertion was not fast enough. Now the tests verifies the stable state after the eviction is processed: once the MG workload backs off, the remotes are cleaned up and the MW is re-scheduled, gets the reservation back and is pending on the remotes.

File: pkg/workload/workload.go [hunk 41]
```diff
@@ -1498,48 +1499,79 @@ func RemoveFinalizer(ctx context.Context, c client.Client, wl *kueue.Workload) e
...
-		return sets.New(slices.Collect(maps.Keys(admissionChecks))...)
-	}
+// ClusterQueue configuration
+func AdmissionChecksForWorkload(log logr.Logger, wl *kueue.Workload, cq *kueue.ClusterQueue) sets.Set[kueue.AdmissionCheckReference] {
+	log = log.WithValues(
+		"Workload",
+		klog.KObj(wl),
+		"ClusterQueue",
+		klog.KObj(cq),
+	)
```
Comment (mimowo) [inline pkg/workload/workload.go]: Do we need to put the Workload and ClusterQueue into the context? I would assume these are already part of the logging for the WorkloadReconciler, if not I would rather put them outside this function, as the external code is already aware of that stuff.

File: test/integration/multikueue/jobs_test.go (hunk 38 above)
Comment (Singularity23x0) [reply test/integration/multikueue/jobs_test.go]: It can be removed here.

File: test/util/util.go (hunk 39 above)
Comment (Singularity23x0) [reply test/util/util.go]: There is a test case which checks the disconnectedTime (one that already exists and is not new to this test).

Comment (Singularity23x0) [reply test/util/util.go]: "Should requeue the workload with a delay when the connection to the admitting worker is lost"

File: pkg/workload/workload.go (hunk 37 above)
Comment (mimowo) [inline pkg/workload/workload.go:1549]: Why don't we just return `findAdmissionFlavors` here? Are there any integration or e2e tests fail if we do that? I'm wondering maybe there is some weird unit tests only which led you to set the code like that.

Comment (mimowo) [reply pkg/workload/workload.go:1549]: Ups, I think this is already discussed here: https://github.com/kubernetes-sigs/kueue/pull/9359/changes#r3008761371. Let me move the discussion there,

Comment (Singularity23x0) [reply pkg/workload/workload.go:1549]: When the admission had no flavors, we returned:
* no admission checks when any admission check didn't cover any of the flavors defined for the CQ,
* all admission checks when all of them covered all flavors of the CQ.

Most tests I encountered that did not bother to assign flavors to the admission, rely on the latter behavior.

After my change, an admission with no flavors is expected to fulfill all ACs. 
This seemed like the better option as it allows the existing tests to keep working according to their assumptions, without exposing us to always allowing workloads with no flavors to be admitted immediately (instead they have to comply with a superset of admission checks any legal flavor would be assigned).

While less dangerous, I don't like this being allowed to happen. As such I propose creating a follow up to ensure all tests set up flavors properly. This is too big a task for a drive-by cleanup. If necessary, the task can be separately implemented before to make sure we don't have to verify this test-specific behavior.

Comment (mimowo) [reply pkg/workload/workload.go:1549]: > TL;DR - i agree with your point that it would be better to fix test setups, but that is too big a change to be a drive-by cleanup, and should be addressed in a followup cleanup-issue.

I would still like to know if this is just about unit tests or integration / e2e too, and how many. Sure, adjusting tests is a toil but changing behavior as a drive-by is also tricky. 

As this PR is fixing a bug I would like to consider for cherrypicked. As such, any drive by changes, even to seemingly unimportant scenarios requires more care when reviewing.

File: pkg/workload/workload.go (hunk 41 above)
Comment (Singularity23x0) [reply pkg/workload/workload.go]: Moved up.

File: pkg/workload/workload.go (hunk 37 above)
Comment (Singularity23x0) [reply pkg/workload/workload.go:1549]: Number of tests that fail without this special clause:
* 4 Unit Tests.
* 3 Integration Tests.

File: test/util/util.go (hunk 39 above)
Comment (mimowo) [reply test/util/util.go]: Got it, ok, I'm not sure we need that assert at all, but if we already had it , then it is fine to keep.

File: pkg/controller/core/workload_controller.go [hunk 42]
```diff
@@ -739,8 +738,13 @@ func (r *WorkloadReconciler) reconcileCheckBasedEviction(ctx context.Context, wl
 }
 
 func (r *WorkloadReconciler) reconcileSyncAdmissionChecks(ctx context.Context, wl *kueue.Workload, cq *kueue.ClusterQueue) (bool, error) {
-	log := ctrl.LoggerFrom(ctx)
-	admissionChecks := workload.AdmissionChecksForWorkload(log, wl, admissioncheck.NewAdmissionChecks(cq), qutil.AllFlavors(cq.Spec.ResourceGroups))
+	log := ctrl.LoggerFrom(ctx).WithValues(
+		"Workload",
+		klog.KObj(wl),
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go]: PLease check if this is needed - I'm pretty sure this should be already in the context added by the controller-runtime.

I looked at some e2e logs from the workload_controller using https://storage.googleapis.com/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-main-1-35/2041380761398939648/artifacts/run-test-e2e-singlecluster-1.35.0/kind-worker2/pods/kueue-system_kueue-controller-manager-7cc486454b-r2zm8_613324b6-af5c-454f-b135-f73e2438d4e9/manager/0.log

And I see `2026-04-07T05:35:49.001606198Z stderr F 2026-04-07T05:35:49.001297813Z	LEVEL(-2)	workload-reconciler	core/workload_controller.go:193	Reconcile Workload	{"replica-role": "leader", "namespace": "sts-e2e-sfz9b", "name": "statefulset-sts-1dc8e", "reconcileID": "600a6400-acce-45a9-ab1f-1c829fd76172"}`
so the workload name & namespace are already there. just under "name" & "namespace"

File: pkg/workload/workload.go (hunk 37 above)
Comment (mimowo) [reply pkg/workload/workload.go:1549]: Ok, thanks for explaining that difference in https://github.com/kubernetes-sigs/kueue/pull/9359/changes#r3045285324

I think the previous behavior was very spooky anyway, not not something we would like to maintain:
```
* no admission checks when any admission check didn't cover any of the flavors defined for the CQ,
* all admission checks when all of them covered all flavors of the CQ.
```
So, I think I'm ok with the new "all admission checks" for this case.

Comment (kshalot) [reply pkg/workload/workload.go:1549]: > So, I think I'm ok with the new "all admission checks" for this case.

I also got why the tests were failing now I'm okay with this as well, but I still feel like some explanation in a comment could be useful:
> I think some explanation is missing in the code at the very least.

Because what sparked this conversation was me looking at this code branch, seeing explicit handling for an admission **without** flavors and thinking: "An admission can have no flavors here?".

File: test/util/util.go (hunk 39 above)
Comment (mimowo) [reply test/util/util.go]: Actually, no I prefer to drop returning `disconnectedTime` from here.  I'm ok to drop the assert actually. I'm not certain what the intention of the test, but it seems weird, looks like it just escaped reviewer's attention rather than useful check.

File: pkg/workload/workload.go (hunk 37 above)
Comment (Singularity23x0) [reply pkg/workload/workload.go:1549]: Added a commend referencing a GH Issue: https://github.com/kubernetes-sigs/kueue/issues/10316

File: test/e2e/multikueue/e2e_test.go (hunk 40 above)
Comment (mimowo) [reply test/e2e/multikueue/e2e_test.go:2565]: Ack, that change looks ok.

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
AdmissionChecks: Workloads will be assigned Admission Checks, which cover all of a Cluster Queue's Resource Flavors, regardless of if/what flavors were assigned yet. Workloads with empty requests (no flavors assigned in admission) will be treated as requiring all Admission Checks (only affects tests).

In MultiKueue context:
1. Every workload admitted to an MK queue will always be annotated with the MultiKueue admission check.
2. Bug fix: # 7254 (summarized in # 9359) - remote workloads will always be removed from workers when the manager workload looses quota reservation.
```

**Comment by gabesaba** [comment]
/release-note-edit

```release-note
MultiKueue: Fixed an issue where the MultiKueue admission check could be removed from a workload that had no quota reservation (e.g. during backoff) if the ClusterQueue also had admission checks 
  covering only some of its resource flavors. When this happened on a manager that had temporarily lost connection to a worker, the remote workload would keep running on the reconnected worker —   
  invisible to the manager — risking double resource reservation.                                                                                                                                    
                                                                                                                                                                                                     
  Admission checks that cover all of a ClusterQueue's resource flavors are now applied to workloads regardless of whether flavors have been assigned, ensuring the MultiKueue check stays attached   
  and remote workloads are reliably reconciled. (#7254)
```

**Comment by gabesaba** [comment]
/release-note-edit

```release-note
MultiKueue: Fixed an issue where the MultiKueue admission check could be removed from a workload that had no quota reservation (e.g. during backoff) if the ClusterQueue also had admission checks 
  covering only some of its resource flavors. When this happened on a manager that had temporarily lost connection to a worker, the remote workload would keep running on the reconnected worker —   
  invisible to the manager — risking double resource reservation.                                                                                                                                    
                                                                                                                                                                                                     
  Now, admission checks that cover all of a ClusterQueue's resource flavors are now applied to workloads regardless of whether flavors have been assigned, ensuring the MultiKueue check stays attached   
  and remote workloads are reliably reconciled. (#7254)
```

**Comment by mimowo** [comment]
/release-note-edit
```release-note
AdmissionChecks: fix the bug that on backoff admission checks which are spanning all ResourceFlavors, such as MultiKueue, may be missing in the Workload’s status. 

For MultiKueue that manifested with a bug, when aside from the MK admission check there was another non-MultiKueue admission check. In the scenario when eviction on the management cluster happened the manager that had temporarily lost connection to a worker, the remote workload would keep running on the reconnected worker, despite the workload staying without reservation on the manager cluster.
```

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
AdmissionChecks: fix the bug that on backoff admission checks which are spanning all ResourceFlavors, such as MultiKueue, may be missing in the Workload’s status. 

For MultiKueue that manifested with a bug, when aside from the MultiKueue admission check there was another non-MultiKueue admission check. In the scenario when eviction on the management cluster happened the manager that had temporarily lost connection to a worker, the remote workload would keep running on the reconnected worker, despite the workload staying without reservation on the manager cluster.
```
