### PR TITLE
fix(scheduler): relax strict admission attempt expectations in flaky tests

### LINKED ISSUE #9526: [flaky test] Scheduler when Handling clusterQueue events Should re-enqueue by the update event of ClusterQueue
**Which test is flaking?**:
Scheduler when Handling clusterQueue events Should re-enqueue by the update event of ClusterQueue 
and
Scheduler Suite: [It] Scheduler when Requeueing Inadmissible Workloads Should collapse requeue requests to ClusterQueue

**Link to failed CI job or steps to reproduce locally**:

**Failure message or logs**:
```
Scheduler Suite: [It] Scheduler when Handling clusterQueue events Should re-enqueue by the update event of ClusterQueue expand_less	11s
{Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:577 with:
pending_workloads with status=inadmissible
Expected
    <int>: 3
to be <=
    <int>: 2 failed [FAILED] Timed out after 10.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:577 with:
pending_workloads with status=inadmissible
Expected
    <int>: 3
to be <=
    <int>: 2
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/scheduler/scheduler_test.go:901 @ 02/26/26 14:02:14.99
}
[open stderropen_in_new](https://prow.k8s.io/spyglass/lens/junit/iframe?req=%7B%22artifacts%22%3A%5B%22artifacts%2Fjunit.xml%22%5D%2C%22index%22%3A2%2C%22src%22%3A%22gs%2Fkubernetes-ci-logs%2Flogs%2Fperiodic-kueue-test-integration-release-0-15%2F2027016273371598848%22%7D&topURL=https%3A//prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-release-0-15/2027016273371598848&lensIndex=2#)
Scheduler Suite: [It] Scheduler when Requeueing Inadmissible Workloads Should collapse requeue requests to ClusterQueue expand_less	13s
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:577 with:
pending_workloads with status=inadmissible
Expected
    <int>: 10
to be <=
    <int>: 5 failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:577 with:
pending_workloads with status=inadmissible
Expected
    <int>: 10
to be <=
    <int>: 5
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/scheduler/scheduler_test.go:3065 @ 02/26/26 14:02:39.634
}
[open stderropen_in_new](https://prow.k8s.io/spyglass/lens/junit/iframe?req=%7B%22artifacts%22%3A%5B%22artifacts%2Fjunit.xml%22%5D%2C%22index%22%3A2%2C%22src%22%3A%22gs%2Fkubernetes-ci-logs%2Flogs%2Fperiodic-kueue-test-integration-release-0-15%2F2027016273371598848%22%7D&topURL=https%3A//prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-release-0-15/2027016273371598848&lensIndex=2#)
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by Sebastianhayashi**
## Summary
- relax strict upper bounds on `PendingAdmissionAttempts` in flaky scheduler tests
- update assertions in:
  - `test/integration/singlecluster/scheduler/scheduler_test.go`
  - `test/integration/singlecluster/scheduler/inadmissible/requeueing_test.go`
- keep lower-bound and successful-admission checks unchanged

Fixes #9526.

## Rationale
The tests currently assume a tight upper bound for admission attempts. In slower or noisier environments, extra requeue/scheduling cycles can happen before settling, which causes flakes without indicating a real behavior regression.

## Validation
Historical reproduction/verification evidence (attached in task artifacts) ran the focused scenarios repeatedly and showed stabilization after this change.

Note: I could not re-run Go integration tests in this specific local workspace because the environment is missing required toolchain utilities (`go` and GNU `sed`) expected by this repo's test Makefile; CI should validate end-to-end on maintainers' infra.

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/scheduler/inadmissible/requeueing_test.go [hunk 1]
```diff
@@ -95,11 +95,11 @@ var _ = ginkgo.Describe("Scheduler", func() {
 			}
 
 			// schedule attempt is proxy for requeue
-			ginkgo.By("between 1-5 schedule attempts occur")
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/inadmissible/requeueing_test.go:98]: Do we have any evidence the test requires an update? As mentioned by @sohankunkerkar https://github.com/kubernetes-sigs/kueue/issues/9526#issuecomment-3971047128 this test should be good after the previous PR: https://github.com/kubernetes-sigs/kueue/pull/9531

So following the discussions we only need the adjustment in the scheduler_test.go.

Comment (Sebastianhayashi) [reply test/integration/singlecluster/scheduler/inadmissible/requeueing_test.go:98]: Thanks for the pointer. I updated this PR to keep the scope aligned with the discussion in #9526: the changes in `test/integration/singlecluster/scheduler/inadmissible/requeueing_test.go` were reverted, and only the adjustment in `scheduler_test.go` remains.
