### PR TITLE
WaitForPodsReady.recoveryTimeout implementation

### LINKED ISSUE #2732: Extend waitForPodsReady to evict a workload if a replacement pod cannot schedule
**What would you like to be added**:

Extend the waitForPodsReady mechanism to allow workload eviction if there is a replacement pod which cannot be scheduled within a specified timeout.

**Why is this needed**:

Currently the mechanism only evicts workloads if they cannot start, but a pod can fail while the  workload is running.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
It introduces a new logic to WaitForPodsReady feature, to support new `.recoveryTimeout` API, according to [this KEP](https://github.com/kubernetes-sigs/kueue/pull/2737)

#### Which issue(s) this PR fixes:

Fixes #2732

#### Special notes for your reviewer:
This is one of two PRs for this feature. The [first one](https://github.com/kubernetes-sigs/kueue/pull/4302) introduces API only, and this one adds logic.
Please wait until the PR with API is merged

The integration test in this PR should be enough for the Kueue part, but I'd like to have an additional e2e test in the follow up, which covers full journey with the batchv1.Job controller 

#### Does this PR introduce a user-facing change?

```release-note
Kueue exposes a new recovery mechanism as part of the WaitForPodsReady API. This evicts jobs which surpasses configured threshold for pod's recovery during runtime
```

### CODE REVIEW

**Comment by PBundyra** [comment]
@mimowo @tenzen-y 
Can you PTAL? The API PR has been merged, I rebased this one and it's ready for review

**Comment by tenzen-y** [comment]
> @mimowo @tenzen-y Can you PTAL? The API PR has been merged, I rebased this one and it's ready for review

ACK
/assign

File: pkg/controller/jobframework/reconciler.go [hunk 1]
```diff
@@ -460,15 +460,17 @@ func (r *JobReconciler) ReconcileGenericJob(ctx context.Context, req ctrl.Reques
 	// handle a job when waitForPodsReady is enabled, and it is the main job
 	if r.waitForPodsReady {
 		log.V(3).Info("Handling a job when waitForPodsReady is enabled")
-		condition := generatePodsReadyCondition(job, wl)
-		// optimization to avoid sending the update request if the status didn't change
-		if !apimeta.IsStatusConditionPresentAndEqual(wl.Status.Conditions, condition.Type, condition.Status) {
-			log.V(3).Info(fmt.Sprintf("Updating the PodsReady condition with status: %v", condition.Status))
+		condition := generatePodsReadyCondition(log, job, wl)
+		if !workload.HasCondition(wl, &condition) {
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:464]: I think the semantics of the HasCondition is quite unclear just by looking at its name. In particular, should we check timestamps, message, reason etc. are the obvious questions. 

I think it would be better to have HasConditionWithTypeAndReason (I believe we should already have something like this). 

I did a quick check and the HasCondition function checks the message, I think we should avoid building any logic on the messages. They are only for humans.

File: pkg/controller/jobframework/reconciler.go [hunk 2]
```diff
@@ -1148,22 +1150,72 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+			Status:  status,
+			Reason:  reason,
+			Message: message,
+			// ObservedGeneration is added via workload.UpdateStatus
+		}
+	}
+
+	podsReadyStartCond := workload.IsPodsReadyStartCond(wl)
+	podsReadyRecoveryCond := workload.IsPodsReadyRecoveryCond(wl)
+	log.V(2).Info("PATRYK before switch",
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1171]: Revisit the log. Surely remove PATRYK, but also probably this is V(3). I also think the ":" aren't necessary. Isn't the log folded as json?

File: pkg/controller/jobframework/reconciler.go [hunk 3]
```diff
@@ -1148,22 +1150,72 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+		message = "One of pods has failed and is waiting for recovery"
+
+	// 4a. A failed pod has recovered during workload's runtime
+	// 4b. Pods continue to be ready after recovery
+	case job.PodsReady() && podsReadyRecoveryCond != nil:
+		reason = kueue.WorkloadWaitForPodsRecovery
+		status = metav1.ConditionTrue
+		message = "All pods reached readiness and the job is running"
+	default:
+		log.V(2).Info("Unexpected PodsReady condition",
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1207]: Here probably v(2) is justified, but clear the ":". Also, maybe add "WARNING" if this is unexpected.

**Review by mimowo — COMMENTED** [review]
ack, initiall pass, I will continue next week

File: pkg/controller/jobframework/reconciler.go [hunk 4]
```diff
@@ -1148,22 +1150,72 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+	podsReadyRecoveryCond := workload.IsPodsReadyRecoveryCond(wl)
+	log.V(2).Info("PATRYK before switch",
+		"WaitForPodsReady with WorkloadWaitForPodsStart reason:", podsReadyStartCond,
+		"WaitForPodsReady with WorkloadWaitForPodsRecovery reason:", podsReadyRecoveryCond,
+		"Workload admitted:", workload.IsAdmitted(wl),
+		"Pods are ready:", job.PodsReady())
+	switch {
+	// 1a. The workload has just been admitted and doesn't have PodsReady cond yet
+	// 1b. The workload has just been admitted, and not all pods are ready
+	case !job.PodsReady() && (apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadPodsReady) == nil ||
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1179]: Make sure PodsReady is computed only once in this function. While it is fast for batch/Job it is slower for JobSet (where it depends on the number of PodSets), but in general it depends on the integration code, so could be non-constant.

File: pkg/controller/jobframework/reconciler.go [hunk 5]
```diff
@@ -1148,22 +1150,72 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+		status = metav1.ConditionTrue
+		message = "All pods reached readiness and the job is running"
+
+	// 3a. The workload was running and a pod has failed
+	// 3b. A pod has failed and the Workload has already recovered once before
+	case !job.PodsReady() && (podsReadyStartCond != nil && podsReadyStartCond.Status == metav1.ConditionTrue ||
+		podsReadyRecoveryCond != nil):
+		reason = kueue.WorkloadWaitForPodsRecovery
+		status = metav1.ConditionFalse
+		message = "One of pods has failed and is waiting for recovery"
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1198]:
```suggestion
		message = "At least one pod has failed, waiting for recovery"
```
proposal, because the previous message suggested it is the pod that is waiting for recovery, whilst the pod will never recover :). What can recover is the workload.  We could maybe say "At least one pod has failed, workload waiting for recovery", but up to you. I'm also open to other proposals.

File: pkg/controller/jobframework/reconciler.go [hunk 6]
```diff
@@ -1148,22 +1150,72 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+		reason = kueue.WorkloadWaitForPodsStart
+		status = metav1.ConditionFalse
+		message = "Not all pods are ready or succeeded"
+
+	// 2a. Pods have reached readiness; before job runtime
+	// 2b. Pods continue to be ready
+	case job.PodsReady() && podsReadyStartCond != nil:
+		reason = kueue.WorkloadWaitForPodsStart
+		status = metav1.ConditionTrue
+		message = "All pods reached readiness and the job is running"
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1190]: Maybe it is safer not to say "job", but rather workload? The reason is that Kueue already supports serving workloads such as Deployments, StatefulSet or LWS. For them "Job" might be misleading. I'm aware we use "job" in many places like that for historical reasons, but I want to migrate from it over time. PTAL https://github.com/kubernetes-sigs/kueue/issues/4286

File: pkg/controller/jobframework/reconciler.go [hunk 7]
```diff
@@ -1148,22 +1150,72 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+	if !workload.IsAdmitted(wl) {
+		// The workload has not been admitted yet
+		// or it was admitted in the past but it's evicted/requeued
+		return metav1.Condition{
+			Type:    kueue.WorkloadPodsReady,
+			Status:  status,
+			Reason:  reason,
+			Message: message,
+			// ObservedGeneration is added via workload.UpdateStatus
+		}
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1166]: This is duplicated with the last return. Can we maybe create a function such as `createPodsReadyCondition` and call it from here, but also from the switch cases, instead of the final return.

File: pkg/controller/jobs/job/job_controller_test.go [hunk 8]
```diff
@@ -491,6 +494,143 @@ func TestReconciler(t *testing.T) {
 		wantEvents        []utiltesting.EventRecord
 		wantErr           error
 	}{
+		"PodsReady is set to False before Workload is Admitted": {
```
Comment (mimowo) [inline pkg/controller/jobs/job/job_controller_test.go:497]: Do the test cases cover 100% of the code in `generatePodsReadyCondition`? You can generate the coverage data by adding `-coverprofile=` while running unit tests, then report with `go tool cover -html`.

**Review by mimowo — COMMENTED** [review]
Completed the first pass. I will revisit when the remarks are addressed.

File: pkg/controller/jobframework/reconciler.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go:464]: > There are two cases in which the message is the only differentiator between conditions:

Thanks for explaining, I see the motivation.

> Are you suggesting merging those two and setting more generic message?

Possibly, but not necessarily. I can see at least two options:
1. make the message generic IIUC this is how it was done before 
2. discriminate against the two states by the reason field, e.g. `WaitForPodsStart` and `NotAdmitted`

Basically, we should not build any logic based on messages being equal or different, because messages are free to change at any point. We have the analogous policy in the code k8s.

My preference is for (2.), but since it was done like in (1.) I'm ok to leave it for follow up.

File: pkg/controller/jobs/job/job_controller_test.go (hunk 8 above)
Comment (PBundyra) [reply pkg/controller/jobs/job/job_controller_test.go:497]: It covers 95.8% of the code, the remaining ~4% is because we don't test the `default` code of block when the conditions are invalid

Comment (mimowo) [reply pkg/controller/jobs/job/job_controller_test.go:497]: Thanks for checking. 

> we don't test the default code of block when the conditions are invalid

What does it mean the conditions are invalid? Does it mean the "reason" field is unrecognized? Is this the scenario which will happen to every workload on upgrade? If so then I believe it is worth covering. 

Actually, I believe we should have some form of a test demonstrating the behavior on upgrade. We have two options: keep the old reason, but make sure it is handled as WaitForPodsStart, or convert it to "WaitForPodsStart" on the first iteration. I would be leaning to convert it actually.

File: pkg/controller/jobframework/reconciler.go (hunk 7 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: PTAL if it aligns with your suggestion

File: pkg/controller/jobframework/reconciler.go (hunk 4 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: Good point, done

File: pkg/controller/jobframework/reconciler.go (hunk 6 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: Thanks, done

File: pkg/controller/jobframework/reconciler.go (hunk 5 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: I agree it was misleading, done

File: pkg/controller/jobframework/reconciler.go (hunk 3 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: Done

File: pkg/controller/core/workload_controller.go [hunk 9]
```diff
@@ -826,8 +826,21 @@ func (r *WorkloadReconciler) admittedNotReadyWorkload(wl *kueue.Workload) (bool,
 	if podsReadyCond != nil && podsReadyCond.Status == metav1.ConditionTrue {
 		return false, 0
 	}
-	admittedCond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadAdmitted)
-	elapsedTime := r.clock.Since(admittedCond.LastTransitionTime.Time)
+
+	var elapsedTime time.Duration
```
[the remark this answers is not in the document]
Comment (PBundyra) [reply pkg/controller/core/workload_controller.go:830]: PTAL if this is what you had in mind

File: pkg/controller/jobs/job/job_controller_test.go (hunk 8 above)
Comment (PBundyra) [reply pkg/controller/jobs/job/job_controller_test.go:497]: We do convert it on the first iteration, I'll cover that in tests

Comment (PBundyra) [reply pkg/controller/jobs/job/job_controller_test.go:497]: Added the test, covering 100% now

File: pkg/controller/core/workload_controller.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/core/workload_controller.go:830]: Pretty much, and not you don't need to declare elapsed time outside of the switch, right?

File: pkg/controller/jobframework/reconciler.go (hunk 1 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: I also like the second approach better. I've added `NotAdmitted` reason and removed message comparison from the `HasConditionWithTypeAndReason` function

File: pkg/workload/workload.go [hunk 10]
```diff
@@ -771,6 +771,22 @@ func IsActive(w *kueue.Workload) bool {
 	return ptr.Deref(w.Spec.Active, true)
 }
 
+func IsPodsReadyStartCond(w *kueue.Workload) *metav1.Condition {
```
Comment (mimowo) [inline pkg/workload/workload.go:774]: A function with a name starting with `Is` should return bool, so something is off here. 

Maybe we can introduce a helper function `FindConditionWithReason`? It could already replace places like this in a follow up: https://github.com/kubernetes-sigs/kueue/blob/a70fd62ad7649877147a150afa92725e366a01f5/pkg/workload/workload.go#L725-L727

File: pkg/workload/workload.go [hunk 11]
```diff
@@ -771,6 +771,22 @@ func IsActive(w *kueue.Workload) bool {
...
+	cond := apimeta.FindStatusCondition(w.Status.Conditions, kueue.WorkloadPodsReady)
+	if cond == nil || cond.Reason != kueue.WorkloadWaitForPodsStart {
+		return nil
+	}
+	return cond
+}
```
Comment (mimowo) [inline pkg/workload/workload.go:780]:
```suggestion
	if cond := apimeta.FindStatusCondition(w.Status.Conditions, kueue.WorkloadPodsReady); 
	   cond != nil && cond.Reason == kueue.WorkloadWaitForPodsStart {
		return cond
	}
	return nil
}
```
nit, to avoid negating the reason equality which makes it harder to imo.

File: apis/kueue/v1beta1/workload_types.go [hunk 12]
```diff
@@ -587,6 +587,9 @@ const (
 	// when the Pods were ready since the workload admission, but some pod has failed,
 	// and workload waits for recovering.
 	WorkloadWaitForPodsRecovery = "WaitForPodsRecovery"
+
+	// WorkloadNotAdmitted is a reason that indicates the Workload has not been admitted
```
Comment (mimowo) [inline apis/kueue/v1beta1/workload_types.go:591]: Is this reason used for workload which get evicted and are waiting to be re-admitted?
If no, then maybe say "the Workload has never been admitted yet" to make it more explicit, wdyt?

Comment (PBundyra) [reply apis/kueue/v1beta1/workload_types.go:591]: It is used for both cases - first admission and readmission

File: pkg/workload/workload.go (hunk 10 above)
Comment (PBundyra) [reply pkg/workload/workload.go]: Added the function

File: pkg/workload/workload.go (hunk 11 above)
Comment (PBundyra) [reply pkg/workload/workload.go]: Done

File: pkg/controller/core/workload_controller.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (PBundyra) [reply pkg/controller/core/workload_controller.go]: Right, I've cleaned this up

File: apis/kueue/v1beta1/workload_types.go (hunk 12 above)
Comment (mimowo) [reply apis/kueue/v1beta1/workload_types.go:591]: So, then maybe say "... the Workload is not admitted". I'm not an English expert, but " has not been admitted" sounds ambiguous to me, and I actually assumed you mean "has never been admitted yet".

File: pkg/controller/jobframework/reconciler.go [hunk 13]
```diff
@@ -1148,24 +1150,62 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
-		Message: message,
-		// ObservedGeneration is added via workload.UpdateStatus
+func generatePodsReadyCondition(log logr.Logger, job GenericJob, wl *kueue.Workload) metav1.Condition {
+	if !workload.IsAdmitted(wl) {
+		// The workload has not been admitted yet
+		// or it was admitted in the past but it's evicted/requeued
+		return workload.CreatePodsReadyCondition(metav1.ConditionFalse,
+			kueue.WorkloadNotAdmitted,
+			"Workload isn't admitted")
+	}
```
Comment (tenzen-y) [inline pkg/controller/jobframework/reconciler.go:1160]: I do not think that this is needed since we will do as following, IIUC:

- `it was admitted in the past but it's evicted/requeued`: kueue turns the QuotaReserved condition to False and removes Admitted condition from Workload.
- `The workload has not been admitted yet`: We tell by the `Admitted` and `QuotaReserved` conditions whether or not the Workload is admitted. What is the value of an additional admitted state rather than `Admitted` and `QuotaReserved`.

File: pkg/controller/jobframework/reconciler.go [hunk 14]
```diff
@@ -1148,24 +1150,62 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+			"At least one pod has failed, waiting for recovery")
+
+	// 4a. A failed pod has recovered during workload's runtime
+	// 4b. Pods continue to be ready after recovery
+	case podsReady && podsReadyRecoveryCond != nil:
+		return workload.CreatePodsReadyCondition(metav1.ConditionTrue,
+			kueue.WorkloadWaitForPodsRecovery,
+			"All pods reached readiness and the workload is running")
+	default:
+		log.V(2).Info("WARNING Unexpected PodsReady condition",
```
Comment (tenzen-y) [inline pkg/controller/jobframework/reconciler.go:1201]: What is the assumed situations where we face here in this flow?
https://github.com/PBundyra/kueue/blob/daad59ea89bc520b9af7d3ed58c4117bf03ec337/keps/349-all-or-nothing/README.md

File: pkg/controller/jobframework/reconciler.go [hunk 15]
```diff
@@ -1148,24 +1150,62 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+	if !workload.IsAdmitted(wl) {
+		// The workload has not been admitted yet
+		// or it was admitted in the past but it's evicted/requeued
+		return workload.CreatePodsReadyCondition(metav1.ConditionFalse,
+			kueue.WorkloadNotAdmitted,
+			"Workload isn't admitted")
+	}
+
+	podsReadyStartCond := workload.FindStatusConditionWithReason(wl, kueue.WorkloadPodsReady, kueue.WorkloadWaitForPodsStart)
+	podsReadyRecoveryCond := workload.FindStatusConditionWithReason(wl, kueue.WorkloadPodsReady, kueue.WorkloadWaitForPodsRecovery)
```
[the remark this answers is not in the document]
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1163]: Do you mean something along the lines:

```golang
var podsReadyStartCond, podsReadyRecoveryCond *metav1.Condition
podsReadyCond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadPodsReady)
if podsReadyCond != nil && podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart {
	podsReadyStartCond = podsReadyCond
} else if podsReadyCond != nil && podsReadyCond.Reason == kueue.WorkloadWaitForPodsRecovery {
	podsReadyRecoveryCond = podsReadyCond
}
```

File: apis/kueue/v1beta1/workload_types.go (hunk 12 above)
Comment (PBundyra) [reply apis/kueue/v1beta1/workload_types.go]: Oh yes, done

File: pkg/controller/jobframework/reconciler.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go:1163]: no, I mean not to have the `podsReadyStartCond, podsReadyRecoveryCond ` variables at all.

File: pkg/controller/core/workload_controller.go [hunk 16]
```diff
@@ -826,9 +826,20 @@ func (r *WorkloadReconciler) admittedNotReadyWorkload(wl *kueue.Workload) (bool,
...
 	}
-	admittedCond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadAdmitted)
-	elapsedTime := r.clock.Since(admittedCond.LastTransitionTime.Time)
-	return true, max(r.waitForPodsReady.timeout-elapsedTime, 0)
+
+	if podsReadyCond == nil || podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart {
+		admittedCond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadAdmitted)
+		elapsedTime := r.clock.Since(admittedCond.LastTransitionTime.Time)
+		return true, max(r.waitForPodsReady.timeout-elapsedTime, 0)
+	} else {
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller.go:834]:
```suggestion
	}
```

This `else` is redundant.

File: pkg/controller/jobframework/reconciler.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go:1163]: In order words to have something like:

```golang
podsReadyCond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadPodsReady)
if podsReadyCond == nil {
 // handle case without the condition
}
reason := podsReadyCond.Reason
status := podsReadyCond.Status
switch {
  case reason == XYZ && status == ABC {
     ...
  }
  ...
```

File: pkg/controller/core/workload_controller.go [hunk 17]
```diff
@@ -826,9 +826,20 @@ func (r *WorkloadReconciler) admittedNotReadyWorkload(wl *kueue.Workload) (bool,
...
+		// podsReadyCond.Reason == kueue.WorkloadWaitForPodsRecovery
+		// A pod has failed and the workload is waiting for recovery
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller.go:836]: What if `podReadyCond` has `reason: PodsReady` and `status: False`?

File: pkg/controller/core/workload_controller.go [hunk 18]
```diff
@@ -826,9 +826,20 @@ func (r *WorkloadReconciler) admittedNotReadyWorkload(wl *kueue.Workload) (bool,
 	if podsReadyCond != nil && podsReadyCond.Status == metav1.ConditionTrue {
 		return false, 0
 	}
-	admittedCond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadAdmitted)
-	elapsedTime := r.clock.Since(admittedCond.LastTransitionTime.Time)
-	return true, max(r.waitForPodsReady.timeout-elapsedTime, 0)
+
+	if podsReadyCond == nil || podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart {
```
Comment (tenzen-y) [inline pkg/controller/core/workload_controller.go:830]:
```suggestion
	if podsReadyCond == nil || podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart || podsReadyCond.Reason == "PodsReady" {
```

IIUC, the `WaitForPodsStart` is compatible with the old `PodsReady` reason.

> We introduce new WorkloadWaitForPodsStart and WorkloadWaitForPodsRecovery reasons to distinguish the reasons of setting the PodsReady=false condition.

File: pkg/workload/workload.go [hunk 19]
```diff
@@ -798,6 +807,28 @@ func IsEvicted(w *kueue.Workload) bool {
...
+// HasConditionWithTypeAndReason checks if there is a condition in Workload's status
+// with exactly the same Type, Status and Reason
+func HasConditionWithTypeAndReason(w *kueue.Workload, cond *metav1.Condition) bool {
+	for _, statusCond := range w.Status.Conditions {
+		if statusCond.Type == cond.Type && statusCond.Reason == cond.Reason &&
+			statusCond.Status == cond.Status {
+			return true
+		}
+	}
+	return false
```
Comment (tenzen-y) [inline pkg/workload/workload.go:819]:
```suggestion
	condition := FindStatusConditionWithReason(w, cond.Type, cond.reason)
	return condition != nil && condition.Status == cond.Status
```

I think this could leverage `FindStatusConditionWithReason`.

**Review by tenzen-y — COMMENTED** [review]
Could we leave test cases to verify compatibility for older `PodsReady` reason?

> We introduce new WorkloadWaitForPodsStart and WorkloadWaitForPodsRecovery reasons to distinguish the reasons of setting the PodsReady=false condition.

https://github.com/PBundyra/kueue/blob/daad59ea89bc520b9af7d3ed58c4117bf03ec337/keps/349-all-or-nothing/README.md#timeout-on-reaching-the-podsready-condition

File: pkg/controller/jobframework/reconciler.go (hunk 13 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1160]: My primary motivation was that after creating a Workload we set the PodsReady condition to False, even tho it hasn't been admitted yet, and is not counting down. I thought it can be misleading so I wanted to differentiate the case when the workload is not admitted yet, and when it's admitted and counting down

File: pkg/controller/core/workload_controller.go (hunk 18 above)
Comment (PBundyra) [reply pkg/controller/core/workload_controller.go:830]: We don't necessarily need to cover that case as we convert the old reason into a new one in the `generatePodsReadyCondition` function. However if you think it would be safer to take into account the old reason in both places I'm happy to update that

File: pkg/controller/core/workload_controller.go (hunk 17 above)
Comment (PBundyra) [reply pkg/controller/core/workload_controller.go]: With the current flow `podsReadyCond` with `PodsReady` reason will be converted into `WaitForPodsStart` here:
https://github.com/kubernetes-sigs/kueue/pull/4301/files#diff-552ab657667de70900b502e2617bcb405fbf4203ff08b2a35d7c87f2d637a75bR1196-R1202

File: pkg/controller/jobframework/reconciler.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go]: Yeah, almost, this looks better. 

However, I still have a hard time to see if the switch cases are complementary or not, as each of them has a couple of entry checks. 

Maybe it could be helpful to at least check podsReadyCond == nil as a preliminary check so that it does not need to be checked in every case down the line?

File: pkg/controller/jobframework/reconciler.go [hunk 20]
```diff
@@ -1148,24 +1150,56 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+
+	podsReadyCond := apimeta.FindStatusCondition(wl.Status.Conditions, kueue.WorkloadPodsReady)
+	podsReady := job.PodsReady()
+	log.V(3).Info("Generating PodsReady condition",
+		"Current PodsReady condition", podsReadyCond,
+		"Pods are ready", podsReady)
+	switch {
+	// 1a. The workload has just been admitted and doesn't have PodsReady cond yet
+	// 1b. The workload has just been admitted, and not all pods are ready
+	case !podsReady && (podsReadyCond == nil || podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart && podsReadyCond.Status == metav1.ConditionFalse):
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1170]: Actually, is this even correct, what happens if `podsReady=true`, but podsReadyCond == nil. IIUC the code will enter the default, which will set the condition to False. This does not seem accurate since `podsReady=True`.

**Comment by PBundyra** [comment]
> Could we leave test cases to verify compatibility for older `PodsReady` reason?
> 
> > We introduce new WorkloadWaitForPodsStart and WorkloadWaitForPodsRecovery reasons to distinguish the reasons of setting the PodsReady=false condition.
> 
> https://github.com/PBundyra/kueue/blob/daad59ea89bc520b9af7d3ed58c4117bf03ec337/keps/349-all-or-nothing/README.md#timeout-on-reaching-the-podsready-condition

Do you mean something different than this one?

https://github.com/kubernetes-sigs/kueue/pull/4301/files#diff-4691f767e133e2011fb5255af68af22a19112c49cad441049aa4a0ef65ba5ebdR634-R660

File: pkg/controller/jobframework/reconciler.go (hunk 20 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1170]: Fixed, added a test scenario covering that

File: pkg/controller/jobframework/reconciler.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: I see, ptal

File: pkg/controller/jobframework/reconciler.go (hunk 13 above)
Comment (tenzen-y) [reply pkg/controller/jobframework/reconciler.go:1160]: In that case could we clear the `PodsReady` condition if the Workload has it since `{Admitted: nil, QuotaReserved: false, PodsReady: false}` is weird.

The `{QuotaReserved: False}` covers all cases for `WorkloadNotAdmitted`. I mean we represent non admitted workloads by `{QuotaRerserved: False}` and `WorkloadNonAdmitted` reason. I think we should represent the state by only one semantics.

Do you have any logic to verify something by this `WorkloadNonAdmitted` reason?

File: pkg/controller/jobframework/reconciler.go (hunk 14 above)
Comment (tenzen-y) [reply pkg/controller/jobframework/reconciler.go]: Sorry for your confusion. This is just a question to clarify when we face this path (`default`).

**Comment by mimowo** [comment]
LGTM overall, what I'm missing yet is an integration test for the baseline scenario.

I think it would be valuable to ensure the mechanism works well spanning multiple reconciles. I'm ok to leave it for a follow up, especially if you tested this locally on a running cluster.

File: pkg/controller/core/workload_controller.go (hunk 18 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:830]: It would be better to confirm both places (JobFramework and WorkloadController (here)) since they usually deploy kueue-external-manager to support non-upstream Jobs. In that case, the kueue-external-manager might be older than kueue-manger, which means kueue-external-manager JobFramework reconciler keeps repling on PodsReady reason.

It might be better to do following steps:

v0.11 (upcoming latest release): Check if podsReady reason is PodsReady in the workload-controller as well, which means verifying PodsReady with PodsReady reason case both in JobFramwork and WrokloadController. And add `[ACTION REQUIRED]` release note to upgrade JobFramwrork version in kueue-external-manager.
v0.12: Remove the redundant verification from WorkloadController, and then keep it only in JobFramework.

@mimowo Any thoughts?

File: test/integration/singlecluster/scheduler/podsready/scheduler_test.go
Comment (tenzen-y) [inline test/integration/singlecluster/scheduler/podsready/scheduler_test.go:1]: I think that we want to add integration test cases, at least.

**Comment by mimowo** [comment]
/hold
for the https://github.com/kubernetes-sigs/kueue/pull/4301#discussion_r1967483299 comment which I consider blocking.
The integration tests are block-ish, but to me could be added in a quick follow up if it was tested manually end-to-end on a local cluster.

File: pkg/controller/core/workload_controller.go (hunk 18 above)
Comment (tenzen-y) [reply pkg/controller/core/workload_controller.go:830]: > This problem is more visible in case of external controllers, but is also present within build-in Kueue controllers, which is also why I'm thinking some integration test would be great.

SGTM, in that case, let's do 2 things in this PR:

1. Keep previous cases for PodsReady with `PodsReady` reason
2. Add Integration testings.

File: pkg/controller/jobframework/reconciler.go (hunk 13 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1160]: > In that case could we clear the `PodsReady` condition if the Workload has it since `{Admitted: nil, QuotaReserved: false, PodsReady: false}` is weird.

Just so you know, this is the current Kueue's behavior. 

Could you elaborate on what you mean by "clearing" the condition? Do you mean to set empty strings in Condition's Status, Reason and Message?

**Comment by PBundyra** [comment]
> I meant could we keep holding cases where input Workload has PodsReady condition with PodsReady reason? For example, this PR replaces those cases like [this](https://github.com/kubernetes-sigs/kueue/pull/4301/files#diff-fbea57b850eb71f650b095afe623b9ed3e9ce3eb5cc35ab965e3498a010a17e0R1114). But, It would be better to keep holding original case as long as the behavior is supported.

Would you like to leave all the old test cases and duplicate all of them with the only difference being the new reason? Or maybe just leave them as they were without duplicating?

**Comment by PBundyra** [comment]
@mimowo @tenzen-y 
Here's an integration test that checks the baseline scenario with a failing pod: https://github.com/kubernetes-sigs/kueue/pull/4301/files#diff-f1db0eb3182b0e49163aaa7fc1fcc2ee21f01eda279797cc07d01fd16da41ce6R2182-R2239

Would you like to have another one that tests anything particular that is not covered by this one?
I've chosen to put the test into batchv1.Job tests as it's easy to controller the `PodsReady()` method from the framework interface

File: pkg/controller/core/workload_controller_test.go [hunk 21]
```diff
@@ -1081,7 +1151,7 @@ func TestReconcile(t *testing.T) {
 				Condition(metav1.Condition{
 					Type:    kueue.WorkloadPodsReady,
 					Status:  metav1.ConditionFalse,
-					Reason:  "PodsReady",
+					Reason:  kueue.WorkloadWaitForPodsStart,
```
[the remark this answers is not in the document]
Comment (PBundyra) [reply pkg/controller/core/workload_controller_test.go:1154]: Done

File: pkg/controller/jobframework/reconciler.go (hunk 13 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1160]: > After this PR, `Admitted: True` or `PodsReady: False, Reason: NonAdmitted` can represent admission status.

I see, that's a good catch.

> In conclusion, basically, I think we should represent Admission state only by Admitted and QuotaReserved.

@mimowo are you fine with getting rid of the `NotAdmitted` reason and sticking with the 1st approach discussed [here](https://github.com/kubernetes-sigs/kueue/pull/4301#discussion_r1967304906)?

File: pkg/controller/jobframework/reconciler.go (hunk 14 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1202]: Now the `default` path is only for unexpected circumstances. Also, we need to return something if non of the above `cases` are true

File: pkg/controller/jobframework/reconciler.go (hunk 13 above)
Comment (mimowo) [reply pkg/controller/jobframework/reconciler.go:1160]: The NotAdmitted reason is not a new way to represent not admitted workload. This remains solely dependent on the Admitted condition type.

The reason is only used within the context of the PodsReady condition to indicate why PodsReady is False.

That being said I'm ok to not introduce the reason as part of this PR because it is a bit orthogonal and it wasn't there ok. I still think it makes sense as a follow up

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 22]
```diff
@@ -2068,24 +2069,29 @@ var _ = ginkgo.Describe("Interacting with scheduler", ginkgo.Ordered, ginkgo.Con
...
 			Enable:         true,
 			BlockAdmission: ptr.To(true),
-			Timeout:        &metav1.Duration{Duration: util.TinyTimeout},
+			Timeout:        waitForPodsReadyTimeout,
 			RequeuingStrategy: &configapi.RequeuingStrategy{
 				Timestamp:          ptr.To(configapi.EvictionTimestamp),
 				BackoffBaseSeconds: ptr.To(backoffBaseSeconds),
 				BackoffLimitCount:  backoffLimitCount,
 			},
+			RecoveryTimeout: &metav1.Duration{Duration: util.TinyTimeout},
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2094]: I would suggest a separate config (probably Describe?) for that. Yes, this is more code, but:
- testing without `RecoveryTimeout` makes sense as this remains a valid configuration
- it is hard for reviewers to decouple which changes in the files are due to logic changes and which due to the introduction of the timeout.

Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2094]: cc @tenzen-y

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 23]
```diff
@@ -2115,34 +2121,122 @@ var _ = ginkgo.Describe("Job controller interacting with Workload controller whe
 		fwk.StopManager(ctx)
 	})
 
-	ginkgo.When("long backoffBaseSeconds", func() {
+	ginkgo.When("long backoffBaseSeconds and tiny waitForPodsReady.timeout", func() {
 		ginkgo.BeforeEach(func() {
 			backoffBaseSeconds = 10
+			waitForPodsReadyTimeout = &metav1.Duration{Duration: util.TinyTimeout}
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2127]: What is the purpose of this change? It is completely non-obvious to me how this is related to the recovery timeout. Please revert if possible. As posted in the other comment, I think it is better to have a bit more of extra code but have a dedicated configuraiton.

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 24]
```diff
@@ -2177,40 +2271,40 @@ var _ = ginkgo.Describe("Job controller interacting with Workload controller whe
 		ginkgo.BeforeEach(func() {
 			backoffBaseSeconds = 1
 			backoffLimitCount = ptr.To[int32](1)
+			waitForPodsReadyTimeout = &metav1.Duration{Duration: util.TinyTimeout}
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2274]: Simiarly here, please revert if not needed.

**Comment by mimowo** [comment]
> Sorry, it should point to `test/integration/singlecluster/controller/jobs/job/job_controller_test.go` L2182

Yeah, this looks like the scenario I was looking for, but somehow missed it in the amount of changes for integration tests. I posted comments to de-couple the integration tests, and have a new dedicated config. Then, use the old config to confirm that a failed pod does not trigger eviction (as before).

File: pkg/controller/jobframework/reconciler.go (hunk 13 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1160]: SGTM, I'll revert the changes related to NotAdmitted, and will create a new issue once this PR is merged

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 23 above)
Comment (PBundyra) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2127]: Those changes were actually needed, as previously for every `When` scenario the waitForPodsReadyTimeout was hardcoded to tiny, as those test check if the Workload is evicted. Given that I wanted to test eviction because of `.recoveryTimeout` and not `.timeout` I had to prolong it, and this is where this change is coming from

Comment (PBundyra) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2127]: > Plus, if you don't modify configuration for the existing ones you can test what happens if the pod fails, but there is no recovertyTimeoutSet, which actually is quite important to check.

If we want to test this then the changes need to stay

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 25]
```diff
@@ -2115,34 +2121,122 @@ var _ = ginkgo.Describe("Job controller interacting with Workload controller whe
...
+						Status:  metav1.ConditionFalse,
+						Reason:  "NoReservation",
+						Message: "The workload has no reservation",
+					}, util.IgnoreConditionTimestampsAndObservedGeneration),
+					gomega.BeComparableTo(metav1.Condition{
+						Type:    kueue.WorkloadRequeued,
+						Status:  metav1.ConditionFalse,
+						Reason:  kueue.WorkloadEvictedByPodsReadyTimeout,
+						Message: fmt.Sprintf("Exceeded the PodsReady timeout %s", wlKey.String()),
+					}, util.IgnoreConditionTimestampsAndObservedGeneration),
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2176]: Please revert to assert only these which were asserted. I think we use ContainElements for the reason - there used to be flakes as some of the other conditions might be transitioning.

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 23 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2127]: Ah, I got it, so you are not changing the configuration. Just setting it to tiny as it was hardcoded before, fine.

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 26]
```diff
@@ -2115,34 +2121,122 @@ var _ = ginkgo.Describe("Job controller interacting with Workload controller whe
...
 		})
 
-		ginkgo.It("should evict workload due pods ready timeout", func() {
+		ginkgo.It("should evict workload due waitForPodsReady.timeout", func() {
 			ginkgo.By("creating job")
 			job := testingjob.MakeJob("job", ns.Name).Queue(lq.Name).Request(corev1.ResourceCPU, "2").Obj()
 			gomega.Expect(k8sClient.Create(ctx, job)).Should(gomega.Succeed())
 
-			wl := &kueue.Workload{}
-			wlKey := types.NamespacedName{Name: workloadjob.GetWorkloadNameForJob(job.Name, job.UID), Namespace: job.Namespace}
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2129]: Can you revert? Sorry, I know the cleanup looks ok, but the PR is already large and so the drive-by cleanups add distractions IMO.

Comment (PBundyra) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Done, sorry for polluting the PR

**Comment by PBundyra** [comment]
I believe I addressed all the comments, to sum up the changes since yesterday:
- Removed the `NotAdmitted` reason;
- Added two more integration tests:

Besides unit tests, currently we have 3 integration tests:
1. Checks that if there's no `.recoveryTimeout` a workload doesn't get evicted if a Pod fails (as it was before)
2. Checks that if there's `.recoveryTimeout` and the timeout is surpassed a workload gets evicted if a Pod fails
3. Checks that if there's `.recoveryTimeout` and a workload recovers before the timeout is surpassed, it doesn't get evicted

@mimowo @tenzen-y

File: pkg/controller/jobframework/reconciler.go [hunk 27]
```diff
@@ -1148,24 +1150,61 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+	// b) A pod has failed and the Workload has already recovered once before
+	case !podsReady && ((podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart || podsReadyCond.Reason == "PodsReady") && podsReadyCond.Status == metav1.ConditionTrue ||
+		podsReadyCond.Reason == kueue.WorkloadWaitForPodsRecovery):
+		return workload.CreatePodsReadyCondition(metav1.ConditionFalse,
+			kueue.WorkloadWaitForPodsRecovery,
+			"At least one pod has failed, waiting for recovery")
+
+	case podsReady && podsReadyCond.Reason == kueue.WorkloadWaitForPodsRecovery:
+		return workload.CreatePodsReadyCondition(metav1.ConditionTrue,
+			kueue.WorkloadWaitForPodsRecovery,
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1198]: @PBundyra @tenzen-y I find these reasons `WaitForPodsRecovery` and `WaitForPodsStart` suboptimal for the positive scenarios (when pods are ready). Shouldn't we have dedicated "PodsRecovered" and "PodsStarted" reasons?

File: pkg/controller/jobframework/reconciler.go [hunk 28]
```diff
@@ -1148,24 +1150,61 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+
+	case podsReady && (podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart || podsReadyCond.Reason == "PodsReady"):
+		return workload.CreatePodsReadyCondition(metav1.ConditionTrue,
+			kueue.WorkloadWaitForPodsStart,
+			"All pods reached readiness and the workload is running")
+
+	// a) The workload was running and a pod has failed
+	// b) A pod has failed and the Workload has already recovered once before
+	case !podsReady && ((podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart || podsReadyCond.Reason == "PodsReady") && podsReadyCond.Status == metav1.ConditionTrue ||
+		podsReadyCond.Reason == kueue.WorkloadWaitForPodsRecovery):
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1191]: TBH, I'm still sceptical about the spagetti entry condtitions, and still wasn't able to verify they are complementary, shouldn't it be just simply:

```
case !podsReady && podsReadyCond.Status == metav1.ConditionTrue:
```
meaning we wait for recovery because it was running before and is no longer running?

File: pkg/controller/jobframework/reconciler.go [hunk 29]
```diff
@@ -1148,24 +1150,61 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+		return workload.CreatePodsReadyCondition(metav1.ConditionFalse,
+			kueue.WorkloadWaitForPodsStart,
+			"Not all pods are ready or succeeded")
+
+	case podsReady && podsReadyCond == nil:
+		return workload.CreatePodsReadyCondition(metav1.ConditionTrue,
+			kueue.WorkloadWaitForPodsStart,
+			"All pods reached readiness and the workload is running")
+
+	case !podsReady && (podsReadyCond.Reason == kueue.WorkloadWaitForPodsStart || podsReadyCond.Reason == "PodsReady") && podsReadyCond.Status == metav1.ConditionFalse:
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1178]:
```suggestion
	case !podsReady && podsReadyCond.Status == metav1.ConditionFalse:
```
why not just like this?

File: pkg/controller/jobframework/reconciler.go [hunk 30]
```diff
@@ -1148,24 +1150,60 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
+		switch {
+		case podsReadyCond == nil:
+			reason = kueue.WorkloadStarted
+
+		case podsReadyCond.Reason == kueue.WorkloadWaitForPodsRecovery:
+			reason = kueue.WorkloadRecovered
+
+		default:
+			reason = kueue.WorkloadStarted
+		}
```
Comment (mimowo) [inline pkg/controller/jobframework/reconciler.go:1179]:
```suggestion
                reason := kueue.WorkloadStarted
		if podsReadyCond != nil && podsReadyCond.Reason == kueue.WorkloadWaitForPodsRecovery {
			reason = kueue.WorkloadRecovered
                }
```
Seems equivalent and much shorter

File: pkg/controller/jobframework/reconciler.go (hunk 29 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: Simplified

File: pkg/controller/jobframework/reconciler.go (hunk 28 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: Simplified

File: pkg/controller/jobframework/reconciler.go (hunk 27 above)
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1199]: I see, added

File: apis/kueue/v1beta1/workload_types.go [hunk 31]
```diff
@@ -587,6 +587,12 @@ const (
 	// when the Pods were ready since the workload admission, but some pod has failed,
 	// and workload waits for recovering.
 	WorkloadWaitForPodsRecovery = "WaitForPodsRecovery"
```
[the remark this answers is not in the document]
Comment (PBundyra) [reply apis/kueue/v1beta1/workload_types.go]: I like this, added

**Comment by mimowo** [comment]
LGTM seeing the most recent updates. I will return here when the tests complete.

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 32]
```diff
@@ -1028,8 +1029,16 @@ var _ = ginkgo.Describe("When waitForPodsReady enabled", ginkgo.Ordered, ginkgo.
...
+					g.Expect(createdWorkload.Status.Conditions).To(gomega.ContainElements(
+						gomega.BeComparableTo(metav1.Condition{
+							Type:    kueue.WorkloadAdmitted,
+							Status:  metav1.ConditionFalse,
+							Reason:  "NoReservation",
+							Message: "The workload has no reservation",
+						}, util.IgnoreConditionTimestampsAndObservedGeneration),
+					))
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
-				util.SyncAdmittedConditionForWorkloads(ctx, k8sClient, createdWorkload)
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:1032]: @PBundyra why is this line removed?

Comment (PBundyra) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:1032]: I added the check above which ensures the condition is synced

Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:1032]: Is it effectively doing the same?

Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:1032]: Maybe separate is better, not because the change is bad, but because the role of the change is non-obvious in the PR with so many other changes, so it may distract future readers.

Comment (PBundyra) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:1032]: I added this because one of the integration test was flaky because the Workload sometimes was still admitted when generating a new PodsReady condition. So this change is directly related to the whole PR

**Comment by mimowo** [comment]
/lgtm
/approve
/hold
Leaving final pass to @tenzen-y since there are some changes compared to the KEP

**Comment by tenzen-y** [comment]
> /lgtm /approve /hold Leaving final pass to @tenzen-y since there are some changes compared to the KEP

ACK, I will take a look after patch release

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go
Comment (tenzen-y) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:1]: I'm ok with the removal of the old `PodsReady` reason tests from other types of Job integration tests like RayJob.
However, It would be worth keeping one test case for the old `PodsReady` reason in this Job integration test since Job integration tests are responsible for verifying JobFramework availability.

**Review by tenzen-y — COMMENTED** [review]
Basically, lgtm
Additionally, could you open KEP update PR as a follow-up?

**Comment by PBundyra** [comment]
> Additionally, could you open KEP update PR as a follow-up?

Absolutely, will do

File: apis/kueue/v1beta1/workload_types.go [hunk 33]
```diff
@@ -579,14 +579,20 @@ const (
...
 	// when the Pods were ready since the workload admission, but some pod has failed,
 	// and workload waits for recovering.
-	WorkloadWaitForPodsRecovery = "WaitForPodsRecovery"
+	WorkloadWaitForRecovery = "WaitForRecovery"
+
+	// WorkloadStarted indicates that all Pods are ready and the Workload has successfully started
+	WorkloadStarted = "Started"
+
+	// WorkloadRecovered indicates that after at least one Pod has failed, the Workload has recovered and is running
+	WorkloadRecovered = "Recovered"
```
[the remark this answers is not in the document]
Comment (PBundyra) [reply apis/kueue/v1beta1/workload_types.go:595]: I happy to improve the documentation in general so this could be another thing to consider. However, please note that the additional two new reasons ("Started"/"Recovered") were introduce to actually ease the debugging progress

File: pkg/controller/jobframework/reconciler.go [hunk 34]
```diff
@@ -1148,24 +1150,52 @@ func (r *JobReconciler) ignoreUnretryableError(log logr.Logger, err error) error
...
-		message = "All pods were ready or succeeded since the workload admission"
-	}
-	return metav1.Condition{
-		Type:    kueue.WorkloadPodsReady,
-		Status:  conditionStatus,
-		Reason:  "PodsReady",
-		Message: message,
-		// ObservedGeneration is added via workload.UpdateStatus
+func generatePodsReadyCondition(log logr.Logger, job GenericJob, wl *kueue.Workload) metav1.Condition {
+	if !workload.IsAdmitted(wl) {
```
[the remark this answers is not in the document]
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go:1159]: Done

File: pkg/controller/jobframework/reconciler.go [hunk 35]
```diff
@@ -460,15 +460,17 @@ func (r *JobReconciler) ReconcileGenericJob(ctx context.Context, req ctrl.Reques
 	// handle a job when waitForPodsReady is enabled, and it is the main job
 	if r.waitForPodsReady {
 		log.V(3).Info("Handling a job when waitForPodsReady is enabled")
-		condition := generatePodsReadyCondition(job, wl)
-		// optimization to avoid sending the update request if the status didn't change
-		if !apimeta.IsStatusConditionPresentAndEqual(wl.Status.Conditions, condition.Type, condition.Status) {
-			log.V(3).Info(fmt.Sprintf("Updating the PodsReady condition with status: %v", condition.Status))
+		condition := generatePodsReadyCondition(log, job, wl)
+		if !workload.HasConditionWithTypeAndReason(wl, &condition) {
+			log.V(3).Info(fmt.Sprintf("Updating the PodsReady condition with reason: %v and status: %v", condition.Reason, condition.Status))
```
[the remark this answers is not in the document]
Comment (PBundyra) [reply pkg/controller/jobframework/reconciler.go]: Done

File: apis/kueue/v1beta1/workload_types.go (hunk 33 above)
[the remark this answers is not in the document]
Comment (tenzen-y) [reply apis/kueue/v1beta1/workload_types.go:595]: Yeah, here I do not have a strong offering. Just nice to have :)

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go
Comment (tenzen-y) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:1]: That makes sense. I'm ok without those tests for JobController, thanks.

**Comment by PBundyra** [comment]
> > Additionally, could you open KEP update PR as a follow-up?
> 
> Absolutely, will do

Follow up with KEP update:
https://github.com/kubernetes-sigs/kueue/pull/4419

**Comment by PBundyra** [comment]
/hold cancel
As I got two approvals
