### PR TITLE
[Flake] Use agnhost `test-webserver` instead of `pause`

### LINKED ISSUE #4733: Flaky Test: End To End Suite: Pod groups when Single CQ should allow to preempt the lower priority group
**What happened**:

Flaky E2E Test Case, `End To End Suite: kindest/node:v1.32.3: [It] Pod groups when Single CQ should allow to preempt the lower priority group` in unrelated branch.

```shell
{Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:484 with:
v1.PodStatus{Phase:"Succeeded", Conditions:[]v1.PodCondition{v1.PodCondition{Type:"TerminationTarget", Status:"True", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 13, 0, time.Local), Reason:"WorkloadEvictedDueToPreempted", Message:"Preempted to accommodate a workload (UID: 9788b1f0-9a2c-4166-b205-926beddaacdd, JobUID: UNKNOWN) due to prioritization in the ClusterQueue"}, v1.PodCondition{Type:"PodReadyToStartContainers", Status:"False", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 14, 0, time.Local), Reason:"", Message:""}, v1.PodCondition{Type:"Initialized", Status:"True", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 12, 0, time.Local), Reason:"PodCompleted", Message:""}, v1.PodCondition{Type:"Ready", Status:"False", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 14, 0, time.Local), Reason:"PodCompleted", Message:""}, v1.PodCondition{Type:"ContainersReady", Status:"False", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 14, 0, time.Local), Reason:"PodCompleted", Message:""}, v1.PodCondition{Type:"PodScheduled", Status:"True", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 12, 0, time.Local), Reason:"", Message:""}}, Message:"", Reason:"", NominatedNodeName:"", HostIP:"172.18.0.2", HostIPs:[]v1.HostIP{v1.HostIP{IP:"172.18.0.2"}}, PodIP:"10.244.1.142", PodIPs:[]v1.PodIP{v1.PodIP{IP:"10.244.1.142"}}, StartTime:time.Date(2025, time.March, 21, 5, 54, 12, 0, time.Local), InitContainerStatuses:[]v1.ContainerStatus(nil), ContainerStatuses:[]v1.ContainerStatus{v1.ContainerStatus{Name:"c", State:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(0xc00025f650)}, LastTerminationState:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(nil)}, Ready:false, RestartCount:0, Image:"registry.k8s.io/e2e-test-images/agnhost:2.53", ImageID:"registry.k8s.io/e2e-test-images/agnhost@sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85", ContainerID:"containerd://6270b0109a689462d230824991c0ef73f7aed792429144b12b2b4a1d6c70a421", Started:(*bool)(0xc000c0afd9), AllocatedResources:v1.ResourceList(nil), Resources:(*v1.ResourceRequirements)(nil), VolumeMounts:[]v1.VolumeMountStatus{v1.VolumeMountStatus{Name:"kube-api-access-8rmqj", MountPath:"/var/run/secrets/kubernetes.io/serviceaccount", ReadOnly:true, RecursiveReadOnly:(*v1.RecursiveReadOnlyMode)(0xc000c06860)}}, User:(*v1.ContainerUser)(nil), AllocatedResourcesStatus:[]v1.ResourceStatus(nil)}}, QOSClass:"Burstable", EphemeralContainerStatuses:[]v1.ContainerStatus(nil), Resize:"", ResourceClaimStatuses:[]v1.PodResourceClaimStatus(nil)}
Expected
    <v1.PodPhase>: Succeeded
to equal
    <v1.PodPhase>: Failed failed [FAILED] Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:484 with:
v1.PodStatus{Phase:"Succeeded", Conditions:[]v1.PodCondition{v1.PodCondition{Type:"TerminationTarget", Status:"True", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 13, 0, time.Local), Reason:"WorkloadEvictedDueToPreempted", Message:"Preempted to accommodate a workload (UID: 9788b1f0-9a2c-4166-b205-926beddaacdd, JobUID: UNKNOWN) due to prioritization in the ClusterQueue"}, v1.PodCondition{Type:"PodReadyToStartContainers", Status:"False", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 14, 0, time.Local), Reason:"", Message:""}, v1.PodCondition{Type:"Initialized", Status:"True", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 12, 0, time.Local), Reason:"PodCompleted", Message:""}, v1.PodCondition{Type:"Ready", Status:"False", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 14, 0, time.Local), Reason:"PodCompleted", Message:""}, v1.PodCondition{Type:"ContainersReady", Status:"False", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 14, 0, time.Local), Reason:"PodCompleted", Message:""}, v1.PodCondition{Type:"PodScheduled", Status:"True", LastProbeTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), LastTransitionTime:time.Date(2025, time.March, 21, 5, 54, 12, 0, time.Local), Reason:"", Message:""}}, Message:"", Reason:"", NominatedNodeName:"", HostIP:"172.18.0.2", HostIPs:[]v1.HostIP{v1.HostIP{IP:"172.18.0.2"}}, PodIP:"10.244.1.142", PodIPs:[]v1.PodIP{v1.PodIP{IP:"10.244.1.142"}}, StartTime:time.Date(2025, time.March, 21, 5, 54, 12, 0, time.Local), InitContainerStatuses:[]v1.ContainerStatus(nil), ContainerStatuses:[]v1.ContainerStatus{v1.ContainerStatus{Name:"c", State:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(0xc00025f650)}, LastTerminationState:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(nil)}, Ready:false, RestartCount:0, Image:"registry.k8s.io/e2e-test-images/agnhost:2.53", ImageID:"registry.k8s.io/e2e-test-images/agnhost@sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85", ContainerID:"containerd://6270b0109a689462d230824991c0ef73f7aed792429144b12b2b4a1d6c70a421", Started:(*bool)(0xc000c0afd9), AllocatedResources:v1.ResourceList(nil), Resources:(*v1.ResourceRequirements)(nil), VolumeMounts:[]v1.VolumeMountStatus{v1.VolumeMountStatus{Name:"kube-api-access-8rmqj", MountPath:"/var/run/secrets/kubernetes.io/serviceaccount", ReadOnly:true, RecursiveReadOnly:(*v1.RecursiveReadOnlyMode)(0xc000c06860)}}, User:(*v1.ContainerUser)(nil), AllocatedResourcesStatus:[]v1.ResourceStatus(nil)}}, QOSClass:"Burstable", EphemeralContainerStatuses:[]v1.ContainerStatus(nil), Resize:"", ResourceClaimStatuses:[]v1.PodResourceClaimStatus(nil)}
Expected
    <v1.PodPhase>: Succeeded
to equal
    <v1.PodPhase>: Failed
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:486 @ 03/21/25 05:54:58.464
}
```

**What you expected to happen**:

no errors

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/4730/pull-kueue-test-e2e-release-0-11-1-32/1902957672265682944

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Use `agnhost test-web server` instead of `agnhost pause` for e2e tests.
To avoid flakiness observed and summarised in https://github.com/kubernetes/kubernetes/issues/131021

#### Which issue(s) this PR fixes:

Fixes #4733

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
It is probably not going to help, ptal: https://github.com/kubernetes-sigs/kueue/issues/4733#issuecomment-2747018044

File: test/util/constants.go [hunk 1]
```diff
@@ -75,4 +75,8 @@ var (
 
 	// The agnhost container will print args passed and `exit 0`
 	BehaviorExitFast = []string{"entrypoint-tester"}
+
+	// Starts a container runs simple webserver, but does not register any signal handler.
+	// Useful for preemption tests, when SIGTERM signal can come before signal handlers are registered.
+	BehaviorWaitForDeletionRunning = []string{"test-webserver"}
```
Comment (mimowo) [inline test/util/constants.go:81]: Can we just use it to replace the pause? Searched for other uses of `BehaviorWaitForDeletionFailOnExit` and found this: https://github.com/kubernetes-sigs/kueue/blob/848b8ee9c21a437ce829b04ebeeec28663858857/test/e2e/singlecluster/e2e_test.go#L147

I think this test could also flake if we continue to use the pause as it expects the workload to be failed: https://github.com/kubernetes-sigs/kueue/blob/848b8ee9c21a437ce829b04ebeeec28663858857/test/e2e/singlecluster/e2e_test.go#L207.


So, I would suggest to just have 

```
// Starts a container which always ends in failure on deletion.
// To achieve this runs simple webserver, but does not register any signal handler.
BehaviorWaitForDeletionFailOnExit = []string{"test-webserver"}
```

Comment (mszadkow) [reply test/util/constants.go]: you are right
