### PR TITLE
[Flaky] Fix "should preempt a workload from LQ with higher recent usage"

### LINKED ISSUE #6227: [Flaky] Scheduler when Using AdmissionFairSharing at Cohort level should preempt a workload from LQ with higher recent usage
**What happened**:
Scheduler Fair Sharing Suite: [It] Scheduler when Using AdmissionFairSharing at Cohort level should preempt a workload from LQ with higher recent usage

```
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:431 with:
Not enough workloads are preempted
Expected
    <int>: 0
to equal
    <int>: 1 failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/util.go:431 with:
Not enough workloads are preempted
Expected
    <int>: 0
to equal
    <int>: 1
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:508 @ 07/28/25 09:04:04.895
}
```

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5174/pull-kueue-test-integration-baseline-main/1949754497840451584

**Anything else we need to know?**:

/kind flake

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

Fix flaky test "Scheduler when Using AdmissionFairSharing at Cohort level should preempt a workload from LQ with higher recent usage"

#### Which issue(s) this PR fixes:

Fixes #6227 

#### Special notes for your reviewer:

Giving some extra time to allow localqueue usage to be updated correctly, seem to fix the flakiness.

After applying the fix, the test was run for ~1 hour with 475 attempts, and no flakes occurred.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go [hunk 1]
```diff
@@ -499,6 +499,14 @@ var _ = ginkgo.Describe("Scheduler", func() {
 					usage := lqB.Status.FairSharing.AdmissionFairSharingStatus.ConsumedResources[corev1.ResourceCPU]
 					g.Expect(usage.MilliValue()).To(gomega.BeNumerically(">", 0))
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
+				gomega.Eventually(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(lqA), lqA)).Should(gomega.Succeed())
+					g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(lqB), lqB)).Should(gomega.Succeed())
+					usageA := lqA.Status.FairSharing.AdmissionFairSharingStatus.ConsumedResources[corev1.ResourceCPU]
+					usageB := lqB.Status.FairSharing.AdmissionFairSharingStatus.ConsumedResources[corev1.ResourceCPU]
+					g.Expect(usageA.MilliValue()).To(gomega.BeNumerically(">", usageB.MilliValue()))
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: Is usage(LQa) > usage(LQb) expected because the workload in LQa is of size 20, while the workload in B is size 12? 

This would be sensible, but then in the previous steps we check that usage(LQa) > 0 and usage(LQb) > 0.

So, does it mean that we may observe usage(LQa)> 0, usage(LQb)>0, yet usage(LQa) < usage(LQb) for a while? If so, do you know how this is possible?

Comment (mimowo) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: cc @PBundyra

Comment (PBundyra) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:508]: > So, does it mean that we may observe usage(LQa)> 0, usage(LQb)>0, yet usage(LQa) < usage(LQb) for a while? If so, do you know how this is possible?

Yes, this could be the reason. This could be possible because entry penalty for a workload A is higher than for a workload B

Comment (IrvingMg) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: Yeah... I need to check. My assumption was that by adding a new assertion, we could give a bit of extra time for the LocalQueue usages to fully update. But you're right,  with the > 0 assertions, we should already have it fully covered as we create only one workload per localqueue.

Still, it seems to be a sync issue, because with this extra assertion, the tests have been running without flakes so far. I’ll confirm the root cause.

Comment (mimowo) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: I looked at this a bit with @PBundyra who may add something, but generally we lack good logs in AFS to confirm different hypotheses. 

So, before we plumb the tests I would like to enrich the logs with logging LQ usage when scheduler is making the preemption decision (ordering of LQs), potentially other places too.  

These can be locally injected logs first. Then repeat the test in a loop and when it flakes analyze what went unexpectedly. Once the logs are proven useful in debugging we can promote them in a PR. 

Once we understand the underlying issue we will decide if we want to plumb the test or prefer to fix. 

We don't need to rush plumbing the tests as the flake is not very common yet.

**Comment by PBundyra** [comment]
Thanks for coming up with this @IrvingMg ! This indeed should solve the test flake. Even the flake is more because of the test itself rather than prod scenario, in which we would have multiple workloads and the increase in usage probably wouldn't be so rapid, we'd still like to understand where the difference in usages comes from. My hypothesis is that because of some error LQ-A status was not updated, and in the meantime LQ-B status was, resulting in LQ-B usage being temporary higher. This would match the exact time Kueue picks candidate for preemption.

In order to have better understanding please add logs that would show what's the LQ's usage of candidates for preemption e.g. in `pkg/scheduler/preemption/preemption.go:559`. Then please try to once again reproduce the issue and paste the logs so we can analyze the root cause.

After we do the analysis I'll happy to merge this fix 

cc @mimowo

**Comment by IrvingMg** [comment]
I've reproduced the error with some additional logs, specifically "Calculated LocalQueueFSUsage for workload". You can see that in scheduling cycle 3, lq-a's usage is lower than lq-b's. Then, in subsequent cycles, usageA is updated and remains higher.

Below are the logs for cycles 3 and 4:

```none
STEP: Checking that the workload from lq-A is preempted despite having bigger priority @ 07/31/25 15:31:47.022
  2025-07-31T15:31:47.02217+02:00	LEVEL(-2)	core/workload_controller.go:157	Reconcile Workload	{"controller": "workload_controller", "namespace": "core-6ntpz", "name": "workload-6gpj9", "reconcileID": "7d959af3-23a8-4bf8-b89a-9147f14b9a56"}
  2025-07-31T15:31:47.022389+02:00	LEVEL(-5)	controller/controller.go:355	Reconcile done, requeueing after 1s	{"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-b", "reconcileID": "8040489b-5308-4c97-9f1d-69de887096ed"}
  2025-07-31T15:31:47.02246+02:00	LEVEL(-2)	localqueue-reconciler	core/localqueue_controller.go:228	Queue update event	{"localQueue": {"name":"lq-b","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.022485+02:00	LEVEL(-5)	controller/controller.go:339	Reconciling	{"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-c", "reconcileID": "ed132de4-03b2-4fe2-b374-af30dceb1dc3"}
  2025-07-31T15:31:47.022523+02:00	LEVEL(-2)	core/localqueue_controller.go:152	Reconcile LocalQueue	{"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-c", "reconcileID": "ed132de4-03b2-4fe2-b374-af30dceb1dc3"}
  2025-07-31T15:31:47.022444+02:00	LEVEL(-5)	controller/controller.go:368	Reconcile successful	{"controller": "workload_controller", "namespace": "core-6ntpz", "name": "workload-6gpj9", "reconcileID": "7d959af3-23a8-4bf8-b89a-9147f14b9a56"}
  2025-07-31T15:31:47.022462+02:00	LEVEL(-5)	core/workload_controller.go:1012	Workload cluster queue update event	{"localQueue": {"name":"lq-b","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.022222+02:00	LEVEL(-5)	scheduler	cache/snapshot.go:220	Calculated LocalQueueFSUsage for workload	{"schedulingCycle": 3, "workload": {"name":"workload-67g2h","namespace":"core-6ntpz"}, "queue": "lq-a", "usage": 1.339}
  2025-07-31T15:31:47.023296+02:00	LEVEL(-5)	scheduler	cache/snapshot.go:220	Calculated LocalQueueFSUsage for workload	{"schedulingCycle": 3, "workload": {"name":"workload-hbgcc","namespace":"core-6ntpz"}, "queue": "lq-b", "usage": 1.566}
  2025-07-31T15:31:47.023392+02:00	LEVEL(-5)	scheduler	preemption/preemption.go:560	Comparing workloads by LocalQueue fair sharing usage	{"schedulingCycle": 3, "workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "clusterQueue": {"name":"cq2"}, "workloadA": {"name":"workload-hbgcc","namespace":"core-6ntpz"}, "queueA": "lq-b", "usageA": 1.566, "workloadB": {"name":"workload-67g2h","namespace":"core-6ntpz"}, "queueB": "lq-a", "usageB": 1.339}
  2025-07-31T15:31:47.023427+02:00	LEVEL(-5)	scheduler	preemption/preemption.go:387	Simulating fair preemption	{"schedulingCycle": 3, "workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "clusterQueue": {"name":"cq2"}, "candidates": [{"name":"workload-hbgcc","namespace":"core-6ntpz"},{"name":"workload-67g2h","namespace":"core-6ntpz"}], "resourcesRequiringPreemption": [{"Flavor":"default","Resource":"cpu"}], "preemptingWorkload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.023543+02:00	LEVEL(-5)	scheduler	preemption/preemption.go:560	Comparing workloads by LocalQueue fair sharing usage	{"schedulingCycle": 3, "workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "clusterQueue": {"name":"cq2"}, "workloadA": {"name":"workload-hbgcc","namespace":"core-6ntpz"}, "queueA": "lq-b", "usageA": 1.566, "workloadB": {"name":"workload-67g2h","namespace":"core-6ntpz"}, "queueB": "lq-a", "usageB": 1.339}
  2025-07-31T15:31:47.023573+02:00	LEVEL(-5)	scheduler	preemption/preemption.go:387	Simulating fair preemption	{"schedulingCycle": 3, "workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "clusterQueue": {"name":"cq2"}, "candidates": [{"name":"workload-hbgcc","namespace":"core-6ntpz"},{"name":"workload-67g2h","namespace":"core-6ntpz"}], "resourcesRequiringPreemption": [{"Flavor":"default","Resource":"cpu"}], "preemptingWorkload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.023614+02:00	LEVEL(-5)	scheduler	scheduler/fair_sharing_iterator.go:81	Computing DominantResourceShare for tournament	{"schedulingCycle": 3, "rootCohort": {"name":"all"}}
  2025-07-31T15:31:47.023642+02:00	LEVEL(-3)	scheduler	scheduler/fair_sharing_iterator.go:84	Running tournament to decide next workload to consider in scheduling cycle	{"schedulingCycle": 3, "rootCohort": {"name":"all"}}
  2025-07-31T15:31:47.023667+02:00	LEVEL(-3)	scheduler	scheduler/fair_sharing_iterator.go:92	Determined tournament winner	{"schedulingCycle": 3, "rootCohort": {"name":"all"}, "cohort": {"name":"all"}, "clusterQueue": {"name":"cq2"}, "winningWorkload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.023692+02:00	LEVEL(-5)	scheduler	scheduler/fair_sharing_iterator.go:226	DominantResourceShare values used during tournament	{"schedulingCycle": 3, "rootCohort": {"name":"all"}, "cohort": {"name":"all"}, "clusterQueue": {"name":"cq2"}, "winningWorkload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "drsValues": ["{parentCohort: all, workload core-6ntpz/workload-6gpj9, drs: 0}"]}
  2025-07-31T15:31:47.023721+02:00	LEVEL(-2)	scheduler	scheduler/scheduler.go:259	Attempting to schedule workload	{"schedulingCycle": 3, "workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "clusterQueue": {"name":"cq2"}, "parentCohort": {"name":"all"}, "rootCohort": {"name":"all"}}
  2025-07-31T15:31:47.025968+02:00	LEVEL(-5)	localqueue-reconciler	core/localqueue_controller.go:310	Updated LocalQueue fair sharing status	{"namespace": "core-6ntpz", "name": "lq-c", "consumedResources": {}}
  2025-07-31T15:31:47.028441+02:00	LEVEL(-5)	admission	admission/http.go:117	received request	{"webhookGroup": "kueue.x-k8s.io", "webhookKind": "Workload", "Workload": {"name":"workload-hbgcc","namespace":"core-6ntpz"}, "namespace": "core-6ntpz", "name": "workload-hbgcc", "resource": {"group":"kueue.x-k8s.io","version":"v1beta1","resource":"workloads"}, "user": "admin", "requestID": "d02473ab-130f-425a-aef4-7a1d17c641b9"}
  2025-07-31T15:31:47.028723+02:00	LEVEL(-5)	admission.workload-webhook	webhooks/workload_webhook.go:96	Validating update	{"webhookGroup": "kueue.x-k8s.io", "webhookKind": "Workload", "Workload": {"name":"workload-hbgcc","namespace":"core-6ntpz"}, "namespace": "core-6ntpz", "name": "workload-hbgcc", "resource": {"group":"kueue.x-k8s.io","version":"v1beta1","resource":"workloads"}, "user": "admin", "requestID": "d02473ab-130f-425a-aef4-7a1d17c641b9"}
  2025-07-31T15:31:47.028829+02:00	LEVEL(-5)	admission	admission/http.go:163	wrote response	{"webhookGroup": "kueue.x-k8s.io", "webhookKind": "Workload", "code": 200, "reason": "", "message": "", "requestID": "d02473ab-130f-425a-aef4-7a1d17c641b9", "allowed": true}
  2025-07-31T15:31:47.029021+02:00	LEVEL(-5)	controller/controller.go:355	Reconcile done, requeueing after 1s	{"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-c", "reconcileID": "ed132de4-03b2-4fe2-b374-af30dceb1dc3"}
  2025-07-31T15:31:47.029065+02:00	LEVEL(-5)	core/workload_controller.go:1012	Workload cluster queue update event	{"localQueue": {"name":"lq-c","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.029068+02:00	LEVEL(-5)	controller/controller.go:339	Reconciling	{"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-a", "reconcileID": "3c9d97fe-6577-408f-8ba1-fc6e01022795"}
  2025-07-31T15:31:47.029134+02:00	LEVEL(-2)	core/localqueue_controller.go:152	Reconcile LocalQueue	{"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-a", "reconcileID": "3c9d97fe-6577-408f-8ba1-fc6e01022795"}
  2025-07-31T15:31:47.029082+02:00	LEVEL(-2)	localqueue-reconciler	core/localqueue_controller.go:228	Queue update event	{"localQueue": {"name":"lq-c","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.030411+02:00	LEVEL(-3)	scheduler	preemption/preemption.go:175	Preempted	{"schedulingCycle": 3, "workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "clusterQueue": {"name":"cq2"}, "parentCohort": {"name":"all"}, "rootCohort": {"name":"all"}, "targetWorkload": {"name":"workload-hbgcc","namespace":"core-6ntpz"}, "preemptingWorkload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "reason": "InCohortFairSharing", "message": "Preempted to accommodate a workload (UID: e4981306-1eff-4712-8412-4edbf7dddf7e, JobUID: UNKNOWN) due to Fair Sharing within the cohort", "targetClusterQueue": {"name":"cq1"}}
  2025-07-31T15:31:47.030494+02:00	DEBUG	events	recorder/recorder.go:104	Preempted to accommodate a workload (UID: e4981306-1eff-4712-8412-4edbf7dddf7e, JobUID: UNKNOWN) due to Fair Sharing within the cohort	{"type": "Normal", "object": {"kind":"Workload","namespace":"core-6ntpz","name":"workload-hbgcc","uid":"ecd6c158-b0cd-4952-a51e-b21937b2971f","apiVersion":"kueue.x-k8s.io/v1beta1","resourceVersion":"257"}, "reason": "Preempted"}
  2025-07-31T15:31:47.030488+02:00	LEVEL(-3)	scheduler	scheduler/logging.go:43	Workload evaluated for admission	{"schedulingCycle": 3, "workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "clusterQueue": {"name":"cq2"}, "status": "", "reason": "couldn't assign flavors to pod set main: insufficient unused quota for cpu in flavor default, 10 more needed. Pending the preemption of 1 workload(s)", "nominatedAssignment": {"PodSets":[{"Name":"main","Flavors":{"cpu":{"Name":"default","Mode":1,"TriedFlavorIdx":-1}},"Status":{},"Requests":{"cpu":"10"},"Count":1,"TopologyAssignment":null,"DelayedTopologyRequest":null}],"Borrowing":0,"LastState":{"LastTriedFlavorIdx":[{"cpu":-1}],"ClusterQueueGeneration":1},"Usage":{"Quota":{"{\"Flavor\":\"default\",\"Resource\":\"cpu\"}":10000},"TAS":null}}, "preempted": [{"name":"workload-hbgcc","namespace":"core-6ntpz"}]}
  2025-07-31T15:31:47.030562+02:00	LEVEL(-2)	scheduler	scheduler/scheduler.go:768	Workload re-queued	{"schedulingCycle": 3, "workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "clusterQueue": {"name":"cq2"}, "queue": {"name":"cq2","namespace":"core-6ntpz"}, "requeueReason": "PendingPreemption", "added": true, "status": ""}
  2025-07-31T15:31:47.030589+02:00	LEVEL(-2)	workload-reconciler	core/workload_controller.go:737	Workload update event	{"workload": {"name":"workload-hbgcc","namespace":"core-6ntpz"}, "queue": "lq-b", "status": "admitted", "clusterQueue": "cq1"}
  2025-07-31T15:31:47.03069+02:00	LEVEL(-5)	controller/controller.go:339	Reconciling	{"controller": "workload_controller", "namespace": "core-6ntpz", "name": "workload-hbgcc", "reconcileID": "77f775aa-db28-46fa-a88f-9b5ef0b1f17c"}
  2025-07-31T15:31:47.030722+02:00	LEVEL(-2)	core/workload_controller.go:157	Reconcile Workload	{"controller": "workload_controller", "namespace": "core-6ntpz", "name": "workload-hbgcc", "reconcileID": "77f775aa-db28-46fa-a88f-9b5ef0b1f17c"}
  2025-07-31T15:31:47.030763+02:00	LEVEL(-5)	controller/controller.go:368	Reconcile successful	{"controller": "workload_controller", "namespace": "core-6ntpz", "name": "workload-hbgcc", "reconcileID": "77f775aa-db28-46fa-a88f-9b5ef0b1f17c"}
  2025-07-31T15:31:47.032276+02:00	LEVEL(-5)	localqueue-reconciler	core/localqueue_controller.go:310	Updated LocalQueue fair sharing status	{"namespace": "core-6ntpz", "name": "lq-a", "consumedResources": {"cpu":"2627m"}}
  2025-07-31T15:31:47.033388+02:00	LEVEL(-5)	admission	admission/http.go:117	received request	{"webhookGroup": "kueue.x-k8s.io", "webhookKind": "Workload", "Workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "namespace": "core-6ntpz", "name": "workload-6gpj9", "resource": {"group":"kueue.x-k8s.io","version":"v1beta1","resource":"workloads"}, "user": "admin", "requestID": "82f7787d-e0c7-447f-9f5f-41a6bd34660f"}
  2025-07-31T15:31:47.033568+02:00	LEVEL(-5)	admission.workload-webhook	webhooks/workload_webhook.go:96	Validating update	{"webhookGroup": "kueue.x-k8s.io", "webhookKind": "Workload", "Workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "namespace": "core-6ntpz", "name": "workload-6gpj9", "resource": {"group":"kueue.x-k8s.io","version":"v1beta1","resource":"workloads"}, "user": "admin", "requestID": "82f7787d-e0c7-447f-9f5f-41a6bd34660f"}
  2025-07-31T15:31:47.033608+02:00	LEVEL(-5)	admission	admission/http.go:163	wrote response	{"webhookGroup": "kueue.x-k8s.io", "webhookKind": "Workload", "code": 200, "reason": "", "message": "", "requestID": "82f7787d-e0c7-447f-9f5f-41a6bd34660f", "allowed": true}
  2025-07-31T15:31:47.034943+02:00	DEBUG	events	recorder/recorder.go:104	couldn't assign flavors to pod set main: insufficient unused quota for cpu in flavor default, 10 more needed. Pending the preemption of 1 workload(s)	{"type": "Warning", "object": {"kind":"Workload","namespace":"core-6ntpz","name":"workload-6gpj9","uid":"e4981306-1eff-4712-8412-4edbf7dddf7e","apiVersion":"kueue.x-k8s.io/v1beta1","resourceVersion":"266"}, "reason": "Pending"}
  2025-07-31T15:31:47.034986+02:00	LEVEL(-2)	workload-reconciler	core/workload_controller.go:737	Workload update event	{"workload": {"name":"workload-6gpj9","namespace":"core-6ntpz"}, "queue": "cq2", "status": "pending"}
  2025-07-31T15:31:47.035157+02:00	LEVEL(-3)	scheduler	queue/manager.go:631	Obtained ClusterQueue heads	{"schedulingCycle": 4, "count": 1}
  2025-07-31T15:31:47.035177+02:00	LEVEL(-2)	localqueue-reconciler	core/localqueue_controller.go:228	Queue update event	{"localQueue": {"name":"lq-a","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.035178+02:00	LEVEL(-5)	core/workload_controller.go:1012	Workload cluster queue update event	{"localQueue": {"name":"lq-a","namespace":"core-6ntpz"}}
  2025-07-31T15:31:47.035203+02:00	LEVEL(-5)	scheduler	cache/snapshot.go:220	Calculated LocalQueueFSUsage for workload	{"schedulingCycle": 4, "workload": {"name":"workload-67g2h","namespace":"core-6ntpz"}, "queue": "lq-a", "usage": 2.6270000000000002}
  2025-07-31T15:31:47.03522+02:00	LEVEL(-5)	controller/controller.go:355	Reconcile done, requeueing after 1s	{"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-a", "reconcileID": "3c9d97fe-6577-408f-8ba1-fc6e01022795"}
  2025-07-31T15:31:47.035235+02:00	LEVEL(-5)	controller/controller.go:339	Reconciling	{"controller": "workload_controller", "namespace": "core-6ntpz", "name": "workload-6gpj9", "reconcileID": "3887e90d-841f-47c5-bcf9-28ff44b827c8"}
  2025-07-31T15:31:47.035327+02:00	LEVEL(-2)	core/workload_controller.go:157	Reconcile Workload	{"controller": "workload_controller", "namespace": "core-6ntpz", "name": "workload-6gpj9", "reconcileID": "3887e90d-841f-47c5-bcf9-28ff44b827c8"}
  2025-07-31T15:31:47.035264+02:00	LEVEL(-5)	scheduler	cache/snapshot.go:220	Calculated LocalQueueFSUsage for workload	{"schedulingCycle": 4, "workload": {"name":"workload-hbgcc","namespace":"core-6ntpz"}, "queue": "lq-b", "usage": 1.566}
```

I'm also attaching the full logs.
[out.log](https://github.com/user-attachments/files/21531755/out.log)

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go (hunk 1 above)
Comment (IrvingMg) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: I've opened a PR with increased logging #6328

Comment (mimowo) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go]: Actually, thinking about the intention of this specific test - we should choose to preempt the workload which has a higher usage, it is perfectly reasonable to await for the usage to stabilize.

I would even go further, and instead of awaiting for >0, wait until >12 (for workload A). This would simplify the overall conditions in the test (I don't think we even need to test >0 for workload B, but we could.

@IrvingMg @PBundyra wdyt?

**Comment by PBundyra** [comment]
Thanks for the repro @IrvingMg ! I'd like to have some time to go over the logs
/hold

**Comment by PBundyra** [comment]
I've analyzed the logs and came to the interesting findings. There was a race in processing reconcile requests between `lq-a` and `lq-b`. At some point because of difference of 1 microsecond, lq-b was processed before lq-a.

Here are the logs:

```2025-07-31T15:31:46.783528+02:00  LEVEL(-5) controller/controller.go:355  Reconcile done, requeueing after 216.476ms  {"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-a", "reconcileID": "ac6e58bc-1bec-44c9-adf5-56cc595c52e4"}```

The request will be ready at `2025-07-31T15:31:47.000004+02:00`

```2025-07-31T15:31:46.786479+02:00  LEVEL(-5) controller/controller.go:355  Reconcile done, requeueing after 213.524ms  {"controller": "localqueue_controller", "namespace": "core-6ntpz", "name": "lq-b", "reconcileID": "754ed359-a24f-488f-9764-f9a24599f500"}```

The request will be ready at `2025-07-31T15:31:47.000003+02:00`

That's why the test sometimes flaked. Because in the first round lq-b sometimes won the race. After that the difference in requested CPU would be too much.

To conclude how we should proceed now:

Following @mimowo 's advice: https://github.com/kubernetes-sigs/kueue/pull/6304#discussion_r2247051775 let's change the assert in the tests so it checks if the lq-a usage is > 12

At the same time let's shorten the half-life time to 1s so it doesn't take dozens of second for the usage to grow above 12

Thanks @IrvingMg for providing logs

**Comment by mimowo** [comment]
> At the same time let's shorten the half-life time to 1s so it doesn't take dozens of second for the usage to grow above 12

Ok, but preferably only for the test in question so that we don't risk flakes in other tests now :)

**Comment by IrvingMg** [comment]
I've updated the test case to use a config with a shortened half-life. I also made some additional changes to the test suite to allow passing this shortened config value for the specific case.

The shortened values apply only to two test cases — the ones under the node "Using AdmissionFairSharing at Cohort level".
I could separate these two tests to apply the shortened config only to the flaky one, but that would require duplicating some code. WDYT?

I ran both tests with approximately 250 repetitions, and no flakes were observed.

File: test/integration/singlecluster/scheduler/fairsharing/suite_test.go [hunk 2]
```diff
@@ -63,48 +73,55 @@ var _ = ginkgo.BeforeSuite(func() {
...
-	gomega.Expect(err).NotTo(gomega.HaveOccurred())
+		sched := scheduler.New(queues, cCache, mgr.GetClient(), mgr.GetEventRecorderFor(constants.AdmissionName),
+			scheduler.WithFairSharing(fairSharing), scheduler.WithAdmissionFairSharing(admissionFairSharing))
+		err = sched.Start(ctx)
+		gomega.Expect(err).NotTo(gomega.HaveOccurred())
+	}
+}
+
+func restartManagerWithConfig(admissionFairSharing *config.AdmissionFairSharing) {
+	if fwk != nil {
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: Why this one? If fwk was nil it would panic on `fwk.StartManager`, no?

File: test/integration/singlecluster/scheduler/fairsharing/suite_test.go [hunk 3]
```diff
@@ -63,48 +73,55 @@ var _ = ginkgo.BeforeSuite(func() {
...
+		fwk.StopManager(ctx)
+	}
+	fwk.StartManager(ctx, cfg, managerAndSchedulerSetup(admissionFairSharing))
+}
 
-	sched := scheduler.New(queues, cCache, mgr.GetClient(), mgr.GetEventRecorderFor(constants.AdmissionName),
-		scheduler.WithFairSharing(fairSharing), scheduler.WithAdmissionFairSharing(admissionFairSharing))
-	err = sched.Start(ctx)
-	gomega.Expect(err).NotTo(gomega.HaveOccurred())
+func restartManagerWithDefaultConfig() {
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: This function is used only once, let's inline

File: test/integration/singlecluster/scheduler/fairsharing/suite_test.go [hunk 4]
```diff
@@ -63,48 +73,55 @@ var _ = ginkgo.BeforeSuite(func() {
...
-	err = workloadjob.SetupIndexes(ctx, mgr.GetFieldIndexer())
-	gomega.Expect(err).NotTo(gomega.HaveOccurred())
+		sched := scheduler.New(queues, cCache, mgr.GetClient(), mgr.GetEventRecorderFor(constants.AdmissionName),
+			scheduler.WithFairSharing(fairSharing), scheduler.WithAdmissionFairSharing(admissionFairSharing))
+		err = sched.Start(ctx)
+		gomega.Expect(err).NotTo(gomega.HaveOccurred())
+	}
+}
+
+func restartManagerWithConfig(admissionFairSharing *config.AdmissionFairSharing) {
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: Actually, I don't like the approach of restarting manager, this could introduce more unrelated flakes. 

It also makes tests take llonger for no reason.

Can we instead start the manger with the desired config?

Comment (IrvingMg) [reply test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: Currently, all the tests in the suite use the same config values, since the AFS config is loaded in the manager. I'm not sure if it's possible to update the config without restarting the manager.

I think the easiest way to start the manager with the desired config would be to create a separate test suite, but that would require duplicating more code.

File: test/integration/singlecluster/scheduler/fairsharing/suite_test.go (hunk 2 above)
Comment (IrvingMg) [reply test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: Right, I've removed it.

File: test/integration/singlecluster/scheduler/fairsharing/suite_test.go (hunk 3 above)
Comment (IrvingMg) [reply test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: Done.

File: test/integration/singlecluster/scheduler/fairsharing/suite_test.go (hunk 4 above)
Comment (mimowo) [reply test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: > I think the easiest way to start the manager with the desired config would be to create a separate test suite, but that would require duplicating more code.

Duplicating beforeEach and AfterEach is fine. These are very repeatable

Comment (mimowo) [reply test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: We can have a new When("Half Lifetime is short") or somehing like this. 

It is better to duplicate and avoid restarting manager, for sure.

Comment (IrvingMg) [reply test/integration/singlecluster/scheduler/fairsharing/suite_test.go]: Done. I've created a new Describe block where I can start the manager with the desired config using BeforeAll.

I'm running repetitions, and so far, after ~330 runs, no flakes observed.

**Comment by mimowo** [comment]
Awesome work!
/lgtm
/approve
/cherry-pick release-0.13
/cherry-pick release-0.12

**Comment by mimowo** [comment]
@IrvingMg the cherrypicks will likely need to be manual due to conflicts. Please proceed. I think it is worth it to align the structure of the tests as we will need to maintain 0.12 for another 2 months. So it will make future cherrypicks much easier.

**Comment by IrvingMg** [comment]
/hold

It seems my latest changes broke the test "should promote a workload from LQ with lower recent usage"

**Comment by mimowo** [comment]
Thank you for looking into that.It is a signal the tests were already too convoluted at it is good to restructure

**Comment by IrvingMg** [comment]
> Thank you for looking into that.It is a signal the tests were already too convoluted at it is good to restructure

Yeah... The issue was that the test "should promote a workload from LQ with lower recent usage" was implicitly relying on cq2 to be present in order to borrow resources, even though it doesn't explicitly reference cq2. When I separated it from the test "should preempt a workload from LQ with higher recent usage", I removed cq2, which caused the first test to fail.

A simple fix would be to create a second CohortQueue, but since both tests were originally under When("Using AdmissionFairSharing at Cohort level"), I think it's better to keep them together. So I moved them to the new Describe block with the shortened half-life time.

Maybe to better structure the tests, I should move the ones using AdmissionFairSharing into the second Describe block? WDYT?

**Comment by mimowo** [comment]
/unhold
/lgtm
Thank you 👍 Merging as this will already fix a common flake

**Comment by mimowo** [comment]
> Maybe to better structure the tests, I should move the ones using AdmissionFairSharing into the second Describe block? WDYT?

Thank you for describing the issue. I think this is conceptually a single Describe, but 2 different When sections. I think it makes sense for when to correspond to configuration sections, so we could have When(Using short halflife) and When(Uinsg long halflife). You could also potentially nest When inside When. Say When using cohorts inside, but this is a detail.
