### PR TITLE
[pods] Finalize the replaced pods

### LINKED ISSUE #1762: Cleanup Failed pods once replacement Pods are present
**What would you like to be added**:

Cleanup Failed pods once there is a level of confidence that replacement Pods exist and the Workload object wouldn't be garbage collected.

We need to be mindful of possible race conditions that could end up finalizing all Pods too early. Integration and E2E tests are a must. 

**Why is this needed**:

Keeping the terminated pods was a conscious design decision for pod groups for a first implementation https://github.com/kubernetes-sigs/kueue/tree/main/keps/976-plain-pods

However, in a busy system where lots of preemptions could happen, the unfinalized pods could cause unnecessary load in the etcd+apiserver.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc: Update KEP with the proposed design
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Finalize the Failed pods in a pod-group once a replacement pods are created.
#### Which issue(s) this PR fixes:

Fixes #1762 

#### Does this PR introduce a user-facing change?

```release-note
The Failed pods in a pod-group are finalized once a replacement pods are created.
```

### CODE REVIEW

File: pkg/util/slices/slices.go [hunk 1]
```diff
@@ -82,3 +82,17 @@ func CmpNoOrder[E comparable, S ~[]E](a, b S) bool {
 	}
 	return true
 }
+
+// Pick creates a new slice containing only the elements for which keep return true.
+func Pick[E any, S ~[]E](s S, keep func(*E) bool) S {
+	if s == nil {
+		return nil
+	}
+	ret := S{}
```
Comment (alculquicondor) [inline pkg/util/slices/slices.go:91]: nit:
```suggestion
	var ret S
```
To save one conditional and an allocation if no elements pass `keep`

File: pkg/util/slices/slices_test.go [hunk 2]
```diff
@@ -102,3 +102,36 @@ func TestToCmpNoOrder(t *testing.T) {
...
+			testSlice: nil,
+			want:      nil,
+		},
+		"empty input": {
+			testSlice: []int{},
+			want:      []int{},
+		},
+		"no match": {
+			testSlice: []int{1, 3, 5, 7, 9},
+			want:      []int{},
```
Comment (alculquicondor) [inline pkg/util/slices/slices_test.go:121]:
```suggestion
			want:      nil,
```

File: test/integration/controller/jobs/pod/pod_controller_test.go
Comment (alculquicondor) [inline test/integration/controller/jobs/pod/pod_controller_test.go:1]: Please also update the following E2E tests:
- `Failed Pod can be replaced in group`
- `should allow to preempt the lower priority group`

in https://github.com/kubernetes-sigs/kueue/blob/main/test/e2e/singlecluster/pod_test.go

File: pkg/controller/jobs/pod/pod_controller.go [hunk 3]
```diff
@@ -704,14 +704,12 @@ func (p *Pod) validatePodGroupMetadata(r record.EventRecorder, activePods []core
...
-		if isPodRunnableOrSucceeded(&pod) {
-			activePods = append(activePods, pod)
-		}
-	}
+	return utilslices.Pick(p.list.Items, isPodRunnableOrSucceeded)
+}
 
-	return activePods
+// notRunnableandAndNotSucceededPods returns a slice of inactive pods in the group
+func (p *Pod) notRunnableAndNotSucceededPods() []corev1.Pod {
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:711]:
```suggestion
func (p *Pod) notRunnableNorSucceededPods() []corev1.Pod {
```

File: pkg/controller/jobs/pod/pod_controller.go [hunk 4]
```diff
@@ -971,25 +1035,31 @@ func (p *Pod) FindMatchingWorkloads(ctx context.Context, c client.Client, r reco
...
 		}
-
 		// Cleanup excess pods of the role
-		err := p.cleanupExcessPods(ctx, c, r, int(ps.Count), roleActivePods)
+		err := p.cleanupExcessPods(ctx, c, r, int(ps.Count), roleActivePods, roleInactivePods)
 		if err != nil {
 			return nil, nil, err
 		}
+
+		// Cleanup replaced inactive pods
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:1062]: Is this a leftover from a previous approach?

File: keps/976-plain-pods/README.md [hunk 5]
```diff
@@ -565,25 +565,23 @@ in-memory Workload, then it is considered unmatching and the Workload is evicted
...
-managing finalizers, but it might lead to too many Pods lingering in etcd for a long time after
-terminated.
-
 ### Retrying Failed Pods
 
 The Pod group will generally only be considered finished if all the Pods finish with a Succeeded
 phase.
 This allows the user to send replacement Pods when a Pod in the group fails or if the group is
 preempted. The replacement Pods can have any name, but they must point to the same pod group.
+Once the replacement Pod is created the old one will be completely removed.
```
Comment (alculquicondor) [inline keps/976-plain-pods/README.md:584]: Without reading the implementation, I think this might be less code and easier to maintain (because we don't exactly know which pod is being replaced):

```suggestion
Once a replacement Pod is created, and Kueue has added it as an owner of the Workload,
 any Failed pods will be deleted.
```

Comment (alculquicondor) [inline keps/976-plain-pods/README.md:584]: Without reading the implementation, I think this might be less code and easier to maintain (because we don't exactly know which pod is being replaced):

```suggestion
Once a replacement Pod is created, and Kueue has added it as an owner of the Workload,
 any Failed pods will be deleted.
```

File: pkg/controller/jobs/pod/pod_controller.go [hunk 6]
```diff
@@ -723,11 +721,77 @@ func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
...
+}
+
 // cleanupExcessPods will delete and finalize pods created last if the number of
 // activePods is greater than the totalCount value.
-func (p *Pod) cleanupExcessPods(ctx context.Context, c client.Client, r record.EventRecorder, totalCount int, activePods []corev1.Pod) error {
+func (p *Pod) cleanupExcessPods(ctx context.Context, c client.Client, r record.EventRecorder, totalCount int, activePods []corev1.Pod, inactivePods []corev1.Pod) error {
 	log := ctrl.LoggerFrom(ctx)
 
+	// Remove inactive pods that have a replacement
+	if len(inactivePods) > 0 && (len(inactivePods)+len(activePods)) > totalCount {
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:750]: I suppose here you are trying to identify which pod was replaced. I prefer we avoid having to maintain this code.

File: test/integration/controller/jobs/pod/pod_controller_test.go
Comment (alculquicondor) [inline test/integration/controller/jobs/pod/pod_controller_test.go:1]: I think we need a stronger test:

A scenario where a Pod fails, gets replaced and the replacement immediately fails.
We need to safeguard against the case where we prematurely delete pods in a way that could lead to the deletion of the Workload.
It might be the case that your implementation already is good against this case. But we need to be extra sure, as this might affect production workloads.

Comment (trasc) [reply test/integration/controller/jobs/pod/pod_controller_test.go:1]: done

Comment (trasc) [reply test/integration/controller/jobs/pod/pod_controller_test.go:1]: `"Should keep the existing workload for pod replacement"` updated to fail the replacement after it's created.

File: pkg/controller/jobs/pod/pod_controller.go (hunk 6 above)
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go]: Also refactored to reuse the deletion loop.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 7]
```diff
@@ -971,22 +1020,26 @@ func (p *Pod) FindMatchingWorkloads(ctx context.Context, c client.Client, r reco
 
 	// Cleanup excess pods for each workload pod set (role)
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go:1021]: We could drop the `EnsureWorkloadOwnedByAllMembers` method and make it part of the `FindMatchingWorkloads` before any excess pods cleanup is done.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller.go:1021]: I'm ok with that. I suppose you mean to only make owners the Pods in the active list.

[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go:1021]: Sure, but before deleting the excess.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller.go:1021]: Sounds good.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 8]
```diff
@@ -723,47 +721,98 @@ func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
...
+			jLastActive := lastActiveTime(pj)
 
-	// Finalize and delete the active pods created last
+			if iLastActive.Equal(jLastActive) {
+				return pi.CreationTimestamp.Before(&pj.CreationTimestamp)
+			}
+			return iLastActive.Before(jLastActive)
+		})
+
+		extraPods = inactivePods[:extraInactivePodsCount]
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:785]: Can you explore the option of not deleting these pods? Just removing the finalizer.

Then it would be up to the k8s garbage collector to take them.

This behavior would preserve the lifecycle of a Pod that users are accustomed to, avoiding potential surprises, or even allowing for some debugging of the Pod yaml before it's fully deleted.

File: pkg/util/slices/slices.go [hunk 9]
```diff
@@ -82,3 +82,14 @@ func CmpNoOrder[E comparable, S ~[]E](a, b S) bool {
 	}
 	return true
 }
+
+// Pick creates a new slice containing only the elements for which keep return true.
+func Pick[E any, S ~[]E](s S, keep func(*E) bool) S {
```
Comment (alexandear) [inline pkg/util/slices/slices.go:87]: Maybe we should rename this function to `Filter` because it's more common for this kind of operation.

From the https://github.com/kubernetes/utils/blob/e7106e64919e62d73c0926352134656a22dc2e38/strings/slices/slices.go#L39C1-L52C1

Comment (trasc) [reply pkg/util/slices/slices.go:87]: In my opinion filter sold have an effect on the input, it's not the case here.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 10]
```diff
@@ -723,47 +721,98 @@ func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
...
+// - the deletion time
+func lastActiveTime(p *corev1.Pod) time.Time {
+	lastTransition := metav1.Now()
+	for _, c := range p.Status.Conditions {
+		if c.Type == corev1.ContainersReady {
+			if c.Status == corev1.ConditionFalse && c.Reason == string(corev1.PodFailed) {
+				lastTransition = c.LastTransitionTime
+			}
+			break
+		}
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go:739]: It's not the same, we should stop on `c.Type == corev1.ContainersReady` regardless of the state.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 11]
```diff
@@ -723,47 +721,98 @@ func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
 	return p.Status.Phase != corev1.PodFailed
 }
 
+// Get the last timestamp on which the pod was observed active:
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go]: can you point me to the part from where it results that `lastActiveTime returns ` should be used instead of `Get` in this context.
done anyway.

File: pkg/controller/jobs/pod/pod_controller_test.go [hunk 12]
```diff
@@ -1359,7 +1358,7 @@ func TestReconciler(t *testing.T) {
 					KueueFinalizer().
 					Group("test-group").
 					GroupTotalCount("2").
-					StatusPhase(corev1.PodFailed).
+					StatusPhase(corev1.PodSucceeded).
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller_test.go:1361]: why change the status of these 2 pods? If not absolutely necessary, please revert.

File: pkg/controller/jobs/pod/pod_controller_test.go [hunk 13]
```diff
@@ -2920,6 +2919,178 @@ func TestReconciler(t *testing.T) {
 				},
 			},
 		},
+		"the failed pods are finalized in order": {
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller_test.go:2922]: Add a unit test for not finalizing pods when waiting for expectations.

Another one where there are 2 Pods, 1 Pod already has a finalizer removed and there is 1 replacement Pod. No new pod should get a finalizer removed.

File: test/integration/controller/jobs/pod/pod_controller_test.go [hunk 14]
```diff
@@ -748,6 +748,9 @@ var _ = ginkgo.Describe("Pod controller", ginkgo.Ordered, ginkgo.ContinueOnFailu
 				podLookupKey := types.NamespacedName{Name: pod.Name, Namespace: pod.Namespace}
 				util.ExpectPodUnsuspendedWithNodeSelectors(ctx, k8sClient, podLookupKey, map[string]string{"kubernetes.io/arch": "arm64"})
 
+				// cache the uid of the workload it should be the same until the execution ends otherwise the workload was recreated
```
Comment (alculquicondor) [inline test/integration/controller/jobs/pod/pod_controller_test.go:751]: nice :)

File: test/integration/controller/jobs/pod/pod_controller_test.go [hunk 15]
```diff
@@ -770,15 +773,30 @@ var _ = ginkgo.Describe("Pod controller", ginkgo.Ordered, ginkgo.ContinueOnFailu
...
+					util.SetPodsPhase(ctx, k8sClient, corev1.PodFailed, replacementPod)
+				})
+
 				// Workload shouldn't be deleted after replacement pod has been created
-				gomega.Consistently(func() error {
-					return k8sClient.Get(ctx, wlLookupKey, createdWorkload)
+				gomega.Consistently(func(g gomega.Gomega) {
+					g.Expect(k8sClient.Get(ctx, wlLookupKey, createdWorkload)).To(gomega.Succeed())
+					g.Expect(createdWorkload.UID).To(gomega.Equal(wlUid))
 				}, util.ConsistentDuration, util.Interval).Should(gomega.Succeed())
```
Comment (alculquicondor) [inline test/integration/controller/jobs/pod/pod_controller_test.go:786]: I think we can remove this "consistently" at this point and just check at the very end of the test that the UID didn't change.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 16]
```diff
@@ -754,16 +790,22 @@ func (p *Pod) cleanupExcessPods(ctx context.Context, c client.Client, r record.E
...
+	log := ctrl.LoggerFrom(ctx)
+
+	if len(extraPods) == 0 {
+		return nil
+	}
 
 	// Extract all the latest created extra pods
-	extraPods := activePods[len(activePods)-extraPodsCount:]
 	extraPodsUIDs := utilslices.Map(extraPods, func(p *corev1.Pod) types.UID { return p.UID })
 	p.excessPodExpectations.ExpectUIDs(log, p.key, extraPodsUIDs)
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go:806]: >  We need to do the same for finalizePods. We don't necessarily need to add a new "expectations" field for finalizers....

done

> Please also add an integration test that exercise

The new UT  `no unnecessary additional failed pods are finalized` should cover this, as is not considering `finished-with-error`  to be finalized even if it failed before `finished-with-error-no-finalizer` which has no finalizer (was the chosen one to be finalized in a previous reconciliation).

File: pkg/controller/jobs/pod/pod_controller.go [hunk 17]
```diff
@@ -893,9 +946,13 @@ func (p *Pod) ConstructComposableWorkload(ctx context.Context, c client.Client,
 	}
 
 	// Cleanup extra pods if there's any
-	err = p.cleanupExcessPods(ctx, c, r, groupTotalCount, activePods)
-	if err != nil {
-		return nil, err
+	if excesPodsCount := len(activePods) - groupTotalCount; excesPodsCount > 0 {
```
Comment (alexandear) [inline pkg/controller/jobs/pod/pod_controller.go:949]: Please fix a typo:
```suggestion
	if excessPodsCount := len(activePods) - groupTotalCount; excessPodsCount > 0 {
```

File: pkg/controller/jobs/pod/pod_controller.go [hunk 18]
```diff
@@ -971,37 +1028,73 @@ func (p *Pod) FindMatchingWorkloads(ctx context.Context, c client.Client, r reco
...
-		var roleActivePods []corev1.Pod
-		for _, activePod := range activePods {
-			roleHash, err := getRoleHash(activePod)
+		// Find all the active and inactive pods of the role
+		var roleHashErrors []error
+		hasRoleFunc := func(p *corev1.Pod) bool {
+			hash, err := getRoleHash(*p)
 			if err != nil {
-				return nil, nil, fmt.Errorf("failed to calculate pod role hash: %w", err)
+				roleHashErrors = append(roleHashErrors, err)
```
[the remark this answers is not in the document]
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go:1043]: please check the implementation of `errors.Join`

File: pkg/controller/jobs/pod/pod_controller.go (hunk 17 above)
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go]: done

File: pkg/controller/jobs/pod/pod_controller.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (alexandear) [reply pkg/controller/jobs/pod/pod_controller.go:1043]: In fact, there won't be any additional logic required because we have a minimal number of errors. 

Let's investigate when we encounter `roleHashError`. The `getRoleHash` function only returns an error if `json.Marshal` fails. In our scenario, `json.Marshal` will seldom fail. Therefore, we can use `[]error` or `errors.Join` interchangeably. However, `errors.Join` has advantages - it provides cleaner code and its use will be consistent with the rest of the code.

However, the decision to use `errors.Join` is ultimately up to you.

File: pkg/controller/jobs/pod/pod_controller.go [hunk 19]
```diff
@@ -723,21 +725,55 @@ func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
...
-	if !p.satisfiedExcessPods {
-		return errPendingOps
+	deletionTime := ptr.Deref(p.DeletionTimestamp, metav1.Now())
+	if lastTransition.Before(&deletionTime) {
+		return lastTransition.Time
 	}
+	return deletionTime.Time
+}
 
+// sortInactivePods - sorts the provided pods slice base on:
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:748]:
```suggestion
// sortInactivePods sorts the provided pods slice base on:
```

File: pkg/controller/jobs/pod/pod_controller.go [hunk 20]
```diff
@@ -723,21 +725,55 @@ func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
...
+// - finalizer state (pods with finalizers are first)
+// - lastActiveTime (pods that ware active last are first)
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:750]:
```suggestion
// - lastActiveTime (pods that were active last are first)
```

File: pkg/controller/jobs/pod/pod_controller.go [hunk 21]
```diff
@@ -723,21 +725,55 @@ func isPodRunnableOrSucceeded(p *corev1.Pod) bool {
...
+		jLastActive := lastActiveTime(pj)
+
+		if iLastActive.Equal(jLastActive) {
+			return pi.CreationTimestamp.Before(&pj.CreationTimestamp)
+		}
+		return jLastActive.Before(iLastActive)
+	})
+}
+
+// sortActivePods - sorts the provided pods slice base on:
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:772]:
```suggestion
// sortActivePods sorts the provided pods slice based on:
```

File: pkg/controller/jobs/pod/pod_controller.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobs/pod/pod_controller.go:1043]: It would be nicer if `errors.Join` appended to the existing `joinError` array instead of creating a new one each time you call it. So for now it seems better to use an array (not just here, but in any case were we need to concatenate errors).

File: pkg/controller/jobs/pod/pod_controller.go [hunk 22]
```diff
@@ -971,37 +1028,73 @@ func (p *Pod) FindMatchingWorkloads(ctx context.Context, c client.Client, r reco
...
+			keptPods = append(keptPods, roleActivePods[:len(roleActivePods)-excessCount]...)
+		} else {
+			keptPods = append(keptPods, roleActivePods...)
 		}
 
-		// Cleanup excess pods of the role
-		err := p.cleanupExcessPods(ctx, c, r, int(ps.Count), roleActivePods)
-		if err != nil {
-			return nil, nil, err
+		if finalzeblePodsCount := min(len(roleInactivePods), len(roleInactivePods)+len(roleActivePods)-int(ps.Count)); finalzeblePodsCount > 0 {
```
Comment (alculquicondor) [inline pkg/controller/jobs/pod/pod_controller.go:1062]: nit: `finalizeablePodsCount`

**Review by alculquicondor — COMMENTED** [review]
nits just for future reference.

/lgtm
/approve
/cherry-pick release-0.6

File: pkg/controller/jobs/pod/pod_controller.go (hunk 19 above)
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go]: done

File: pkg/controller/jobs/pod/pod_controller.go (hunk 20 above)
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go]: done

File: pkg/controller/jobs/pod/pod_controller.go (hunk 21 above)
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go]: done

File: pkg/controller/jobs/pod/pod_controller.go (hunk 22 above)
Comment (trasc) [reply pkg/controller/jobs/pod/pod_controller.go]: done

**Comment by alculquicondor** [comment]
@trasc please create a cherry-pick and highlight in the description any significant changes compared to this PR.
