### PR TITLE
Make test "should print workloads list with paging" less likely to fail

### LINKED ISSUE #2353: Flaky integration test: Should print workloads list with paging
/kind flake

**What happened**:

Integration test failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2314/pull-kueue-test-integration-main/1798039851593895936

**What you expected to happen**:

No flake

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the build.

**Anything else we need to know?**:

```
  [FAILED] Expected
      <string>: "...     1s
      "
  to equal               |
      <string>: "...     0s
      "
  In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/kueuectl/list_test.go:206 @ 06/04/24 17:19:10.001
```

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Make test "should print workloads list with paging" less likely to fail

#### Which issue(s) this PR fixes:

Part of  #2353

#### Special notes for your reviewer:
Sometime it's not enough one second to create resources and execute command. And it's printing Age with 1s instead 0s.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
@mbobrovskyi Could you clear the reason why this test is flaky?

File: test/integration/kueuectl/list_test.go [hunk 1]
```diff
@@ -72,14 +74,17 @@ var _ = ginkgo.Describe("Kueuectl List", ginkgo.Ordered, ginkgo.ContinueOnFailur
...
+			executeTime := time.Now()
 			err := kueuectl.Execute()
 
 			gomega.Expect(err).NotTo(gomega.HaveOccurred(), "%s: %s", err, output)
 			gomega.Expect(errOutput.String()).Should(gomega.BeEmpty())
 
-			gomega.Expect(output.String()).Should(gomega.Equal(`NAME   CLUSTERQUEUE   PENDING WORKLOADS   ADMITTED WORKLOADS   AGE
-lq1    cq1            0                   0                    0s
-`))
+			gomega.Expect(output.String()).Should(gomega.Equal(fmt.Sprintf(`NAME   CLUSTERQUEUE   PENDING WORKLOADS   ADMITTED WORKLOADS   AGE
```
Comment (mimowo) [inline test/integration/kueuectl/list_test.go:83]: IIUC the issue is that `output.String()` may return 1s rather than 0s as typically. However, I think it could still flake if `time.Now()` uses a different time than `output.String()` . I guess they would need to return different second, which is unlikely, but possible. 

I think it is better to use `gomega.Eventually` to re-try if the times differ. And call `time.Now` and `output.String()` within the lambda.

Alternatively, we could maybe use a fake clock, but I'm not sure how much refactoring this would be.

**Comment by mbobrovskyi** [comment]
It's because sometime not enough one second to create resources and execute command. And it's printing Age with `1s` instead `0s`.

File: test/integration/kueuectl/list_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/integration/kueuectl/list_test.go:83]: Yes, you right, now this issue in progress #2287. So in follow-up I think we can make it.

Comment (mimowo) [reply test/integration/kueuectl/list_test.go:83]: Ok, so please don't just close the issue https://github.com/kubernetes-sigs/kueue/issues/2353. We will close it when the follow up is ready. In the PR description say "Part of #2353"

Comment (mimowo) [reply test/integration/kueuectl/list_test.go:83]: And maybe let's say in title "Make the "should print workloads list with paging" test less likely to fail"

**Comment by mimowo** [comment]
/approve
/lgtm
Thanks!
