### PR TITLE
Deflake ProvReq integration test by adding 100ms sleep to avoid data race

### LINKED ISSUE #4948: Flaky Test: Provisioning when A workload is using a provision admission check Should ignore the change if Workload is Admitted and the ProvisioningRequest's condition is set to BookingExpired
**What happened**:

Failed `Provisioning admission check suite: [It] Provisioning when A workload is using a provision admission check Should ignore the change if Workload is Admitted and the ProvisioningRequest's condition is set to BookingExpired [slow]` on the periodic release-0.10 CI Job.

```shell
{Failed after 0.387s.
The function passed to Consistently failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/controller/admissionchecks/provisioning/provisioning_test.go:690 with:
Expected
    <[]v1beta1.AdmissionCheckState | len:1, cap:4>: [
        {
            Name: "ac-prov",
            State: "Rejected",
            LastTransitionTime: {
                Time: 2025-04-14T01:44:32Z,
            },
            Message: "",
            PodSetUpdates: [
                {
                    Name: "ps1",
                    Labels: nil,
                    Annotations: {
                        "autoscaling.x-k8s.io/consume-provisioning-request": "wl-ac-prov-1",
                        "autoscaling.x-k8s.io/provisioning-class-name": "provisioning-class",
                        "cluster-autoscaler.kubernetes.io/consume-provisioning-request": "wl-ac-prov-1",
                        "cluster-autoscaler.kubernetes.io/provisioning-class-name": "provisioning-class",
                    },
                    NodeSelector: nil,
                    Tolerations: nil,
                },
                {
                    Name: "ps2",
                    Labels: nil,
                    Annotations: {
                        "autoscaling.x-k8s.io/consume-provisioning-request": "wl-ac-prov-1",
                        "autoscaling.x-k8s.io/provisioning-class-name": "provisioning-class",
                        "cluster-autoscaler.kubernetes.io/consume-provisioning-request": "wl-ac-prov-1",
                        "cluster-autoscaler.kubernetes.io/provisioning-class-name": "provisioning-class",
                    },
                    NodeSelector: nil,
                    Tolerations: nil,
                },
            ],
        },
    ]
to contain element matching
    <*matchers.BeComparableToMatcher | 0xc000b6af60>: {
        Expected: <v1beta1.AdmissionCheckState>{
            Name: "ac-prov",
            State: "Ready",
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            Message: "",
            PodSetUpdates: nil,
        },
        Options: [
            <*cmp.pathFilter | 0xc0005963d8>{
                core: {},
                fnc: 0x79dbc0,
                opt: <cmp.ignore>{core: {}},
            },
        ],
    } failed [FAILED] Failed after 0.387s.
The function passed to Consistently failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/controller/admissionchecks/provisioning/provisioning_test.go:690 with:
Expected
    <[]v1beta1.AdmissionCheckState | len:1, cap:4>: [
        {
            Name: "ac-prov",
            State: "Rejected",
            LastTransitionTime: {
                Time: 2025-04-14T01:44:32Z,
            },
            Message: "",
            PodSetUpdates: [
                {
                    Name: "ps1",
                    Labels: nil,
                    Annotations: {
                        "autoscaling.x-k8s.io/consume-provisioning-request": "wl-ac-prov-1",
                        "autoscaling.x-k8s.io/provisioning-class-name": "provisioning-class",
                        "cluster-autoscaler.kubernetes.io/consume-provisioning-request": "wl-ac-prov-1",
                        "cluster-autoscaler.kubernetes.io/provisioning-class-name": "provisioning-class",
                    },
                    NodeSelector: nil,
                    Tolerations: nil,
                },
                {
                    Name: "ps2",
                    Labels: nil,
                    Annotations: {
                        "autoscaling.x-k8s.io/consume-provisioning-request": "wl-ac-prov-1",
                        "autoscaling.x-k8s.io/provisioning-class-name": "provisioning-class",
                        "cluster-autoscaler.kubernetes.io/consume-provisioning-request": "wl-ac-prov-1",
                        "cluster-autoscaler.kubernetes.io/provisioning-class-name": "provisioning-class",
                    },
                    NodeSelector: nil,
                    Tolerations: nil,
                },
            ],
        },
    ]
to contain element matching
    <*matchers.BeComparableToMatcher | 0xc000b6af60>: {
        Expected: <v1beta1.AdmissionCheckState>{
            Name: "ac-prov",
            State: "Ready",
            LastTransitionTime: {
                Time: 0001-01-01T00:00:00Z,
            },
            Message: "",
            PodSetUpdates: nil,
        },
        Options: [
            <*cmp.pathFilter | 0xc0005963d8>{
                core: {},
                fnc: 0x79dbc0,
                opt: <cmp.ignore>{core: {}},
            },
        ],
    }
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/controller/admissionchecks/provisioning/provisioning_test.go:697 @ 04/14/25 01:44:34.401
}
```

**What you expected to happen**:
No errors.

**How to reproduce it (as minimally and precisely as possible)**:

- https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-release-0-10/1910870358446051328
- https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-release-0-10/1911595141114630144

Image

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind feature
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #4948

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go [hunk 1]
```diff
@@ -666,6 +667,7 @@ var _ = ginkgo.Describe("Provisioning", ginkgo.Ordered, ginkgo.ContinueOnFailure
 			})
 
 			ginkgo.By("Setting the provisioning request as BookingExpired", func() {
+				time.Sleep(100 * time.Millisecond)
```
Comment (mimowo) [inline test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:670]: Maybe let's add a comment
// wait a bit to make it almost certain that the provisioning controller already sees the workload as admitted.

Comment (tenzen-y) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:670]: Why not just using `LongTimeout`?

Comment (mimowo) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:670]: This is not a timeout, we just want to give the provisioning controller a bit more time.

Comment (tenzen-y) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:670]: Uhm, that makes sense. Let's just add sleep since this is integration tests.
We want to avoid the checking internal cache as much as possible.

Comment (PBundyra) [reply test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go:670]: Done
