### PR TITLE
[Flake] Change image behavior of high-priority-group pod

### LINKED ISSUE #4434: Flaky Test: Pod groups when Single CQ should allow to preempt the lower priority group
**What happened**:
The below E2E test failed.

```
End To End Suite: kindest/node:v1.30.0: [It] Pod groups when Single CQ should allow to preempt the lower priority group
```

```shell
{Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/pod_test.go:483 with:
Expected
    <v1.PodPhase>: Succeeded
to equal
    <v1.PodPhase>: Failed failed [FAILED] Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/pod_test.go:483 with:
Expected
    <v1.PodPhase>: Succeeded
to equal
    <v1.PodPhase>: Failed
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/singlecluster/pod_test.go:485 @ 02/27/25 01:48:44.842
}
```

**What you expected to happen**:
No errors.

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-release-0-10-1-30/1894925220897099776

Image

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Prevent the situation that high-group-priority finish too fast.
Add control over when the pod group should finish.

#### Which issue(s) this PR fixes:

Fixes #4434 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/singlecluster/pod_test.go [hunk 1]
```diff
@@ -517,6 +517,10 @@ var _ = ginkgo.Describe("Pod groups", func() {
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
 			})
 
+			ginkgo.By("Call high priority group pods to complete", func() {
+				util.WaitForActivePodsAndTerminate(ctx, k8sClient, restClient, cfg, ns.Name, 2, 0)
```
Comment (mimowo) [inline test/e2e/singlecluster/pod_test.go:521]: Actually, I don't think we should be terminating them by the /exit, because the Pod is already being deleted due to preemptions. So, we just need to wait for SIGKILL by kubelet. To make it faster we can specify spec.graceTerminationPeriodSeconds. See https://github.com/kubernetes-sigs/kueue/issues/4434#issuecomment-2688669626

Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go:521]: Ah, sorry, this is already terminating the high-priority group. makes sense

**Comment by mimowo** [comment]
@mszadkow were you able to repro the issue locally before fix and confirm the code fixes it?

File: test/e2e/singlecluster/pod_test.go (hunk 1 above)
Comment (mszadkow) [reply test/e2e/singlecluster/pod_test.go:521]: If we do not terminate them they will never finish and replacement pods can't be ungated

**Comment by mszadkow** [comment]
> @mszadkow were you able to repro the issue locally before fix and confirm the code fixes it?

100 times repeated, but I did not catch it

**Comment by mimowo** [comment]
Ok, but as you use "BehaviorWaitForDeletion" command, isn't the "Check that the preempted pods are deleted" step now taking long becuase we need to wait 30s for SIGKILL? If this is the case we may just limit the graceful termination period to 1s.

File: test/e2e/singlecluster/pod_test.go (hunk 1 above)
Comment (mimowo) [reply test/e2e/singlecluster/pod_test.go:521]: yeah, got it.

**Comment by mszadkow** [comment]
> Ok, but as you use "BehaviorWaitForDeletion" command, isn't the "Check that the preempted pods are deleted" step now taking long becuase we need to wait 30s for SIGKILL? If this is the case we may just limit the graceful termination period to 1s.

It's a different group (default) that I didn't touch.
But as you said it, I think we can decrease the time.
Instead of deleting pods we could use different behaviour and send exit code 1 then we have the same effect but faster

**Comment by mszadkow** [comment]
@mimowo wdyt?
@mbobrovskyi can you make the review too?

**Comment by mbobrovskyi** [comment]
> Ok, but as you use "BehaviorWaitForDeletion" command, isn't the "Check that the preempted pods are deleted" step now taking long becuase we need to wait 30s for SIGKILL? If this is the case we may just limit the graceful termination period to 1s.

We already have the graceful termination period for the default priority group.

https://github.com/kubernetes-sigs/kueue/blob/fdd8fc79eb61486cbe3d41966e320db930efc4ac/test/e2e/singlecluster/pod_test.go#L420-L425

And we are waiting for this group:

https://github.com/kubernetes-sigs/kueue/blob/fdd8fc79eb61486cbe3d41966e320db930efc4ac/test/e2e/singlecluster/pod_test.go#L500-L508

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Comment by mimowo** [comment]
> We already have the graceful termination period for the default priority group.

Ah, got it , thanks, this is what I was looking for.

**Comment by mbobrovskyi** [comment]
/retest

Due to

```
fatal: unable to access 'https://github.com/kubernetes-sigs/kueue.git/': Failed to connect to github.com port 443 after 132387 ms: Couldn't connect to server
fatal: could not fetch 3e4e48b0b5fe6b46[84](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/4438/pull-kueue-test-integration-main/1896470330256396288#1:build-log.txt%3A84)34d6767749b399319f2da2 from promisor remote
```
