### PR TITLE
Record an event when provisioning request fails

### LINKED ISSUE #3025: Surface errors when a PodTemplate or a ProvReq is invalid
**What would you like to be added**:

When a ProvReq or PodTemplate is rejected by a webhook, Kueue just logs the error and continues retrying. These errors will not be visible to end-users and they might just interpret them as "kueue is stuck". We should communicate these errors in the Workload object, maybe even produce an event?

**Why is this needed**:

A cloud provider could have a webhook to validate PodTemplates created for ProvisioningRequests.

These errors need to be surfaced to users so they can fix any problem about them.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
It produces an event when an error during provisioning request creation occurs.

#### Which issue(s) this PR fixes:

Fixes #3025

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/admissionchecks/provisioning/controller.go [hunk 1]
```diff
@@ -302,6 +302,7 @@ func (c *Controller) syncOwnedProvisionRequest(ctx context.Context, wl *kueue.Wo
 			}
 
 			if err := c.client.Create(ctx, req); err != nil {
+				c.record.Eventf(wl, corev1.EventTypeWarning, "ProvisioningRequestError", "Error creating ProvisioningRequest: %q", req.Name)
```
Comment (kannon92) [inline pkg/controller/admissionchecks/provisioning/controller.go:305]: It is a bit weird seeing that you title the constant as ProvisioningRequestError and the type of event is a warning.

I would also declare this as a constant and move it to the constants package.

Comment (mimowo) [inline pkg/controller/admissionchecks/provisioning/controller.go:305]:
```suggestion
				c.record.Eventf(wl, corev1.EventTypeWarning, "FailedCreate", "Error creating ProvisioningRequest: %q", req.Name)
```
Or `FailedToCreate`. I assume the event is attached to the ProvisiningRequest, so we don't need to repeat the type in the event reason. Inspired by https://github.com/kubernetes/kubernetes/blob/21f54c3ca1ac87611e101f46d8b05682f51efbee/pkg/controller/cronjob/cronjob_controllerv2.go#L635

Comment (IrvingMg) [reply pkg/controller/admissionchecks/provisioning/controller.go]: Done. Thanks

File: pkg/controller/admissionchecks/provisioning/controller.go [hunk 2]
```diff
@@ -302,6 +303,10 @@ func (c *Controller) syncOwnedProvisionRequest(ctx context.Context, wl *kueue.Wo
 			}
 
 			if err := c.client.Create(ctx, req); err != nil {
+				ac.Message = fmt.Sprintf("Error creating ProvisioningRequest: %q", requestName)
```
Comment (mwielgus) [inline pkg/controller/admissionchecks/provisioning/controller.go:306]: Can you include some information about what is the problem in the message?

File: pkg/controller/admissionchecks/provisioning/controller_test.go [hunk 3]
```diff
@@ -40,6 +42,25 @@ import (
...
+	c.err = err
+}
+
+func (c *fakeControllerRuntimeClient) Create(ctx context.Context, obj client.Object, opts ...client.CreateOption) error {
+	if c.err != nil {
+		return c.err
+	}
+
+	return c.Client.Create(ctx, obj, opts...)
+}
```
Comment (mbobrovskyi) [inline pkg/controller/admissionchecks/provisioning/controller_test.go:60]: Can we use `builder.WithInterceptorFuncs(...)` instead?

File: pkg/controller/admissionchecks/provisioning/controller.go (hunk 2 above)
Comment (IrvingMg) [reply pkg/controller/admissionchecks/provisioning/controller.go]: Done.

File: pkg/controller/admissionchecks/provisioning/controller_test.go (hunk 3 above)
Comment (IrvingMg) [reply pkg/controller/admissionchecks/provisioning/controller_test.go]: Done.

**Review by trasc — COMMENTED** [review]
/lgtm

File: pkg/controller/admissionchecks/provisioning/controller.go [hunk 4]
```diff
@@ -302,6 +303,10 @@ func (c *Controller) syncOwnedProvisionRequest(ctx context.Context, wl *kueue.Wo
 			}
 
 			if err := c.client.Create(ctx, req); err != nil {
+				ac.Message = fmt.Sprintf("Error creating ProvisioningRequest %q: %v", requestName, err)
+				workload.SetAdmissionCheckState(&wl.Status.AdmissionChecks, *ac)
+
+				c.record.Eventf(wl, corev1.EventTypeWarning, "FailedCreate", "Error creating ProvisioningRequest %q: %v", req.Name, err)
```
Comment (mimowo) [inline pkg/controller/admissionchecks/provisioning/controller.go:309]:
```suggestion
				c.record.Eventf(wl, corev1.EventTypeWarning, "FailedCreate", ac.Message)
```
nit: to avoid code duplication to compute the message.

**Review by mimowo — COMMENTED** [review]
LGTM, just a nit

File: pkg/controller/admissionchecks/provisioning/controller.go (hunk 4 above)
Comment (IrvingMg) [reply pkg/controller/admissionchecks/provisioning/controller.go]: Done.

**Comment by mbobrovskyi** [comment]
/lgtm

Thanks!

**Comment by mimowo** [comment]
/lgtm
/approve
Thanks!

File: pkg/controller/admissionchecks/provisioning/controller.go [hunk 5]
```diff
@@ -302,6 +303,10 @@ func (c *Controller) syncOwnedProvisionRequest(ctx context.Context, wl *kueue.Wo
 			}
 
 			if err := c.client.Create(ctx, req); err != nil {
+				ac.Message = fmt.Sprintf("Error creating ProvisioningRequest %q: %v", requestName, err)
```
Comment (mimowo) [inline pkg/controller/admissionchecks/provisioning/controller.go:306]: @IrvingMg it just occurred to me - could you please follow up to use the TruncateConditionMessage, and TruncateConditionMessage helpers to make sure the message is not too long? 

It shouldn't be a problem in most cases, but since the message may come from custom webhooks it may be arbitrarily long.

Comment (mimowo) [reply pkg/controller/admissionchecks/provisioning/controller.go:306]: cc @mbobrovskyi

**Review by tenzen-y — COMMENTED** [review]
It seems that this is user-facing new feature. Hense, the release note would be helpful.

/release-note-edit
```release-note
MultiKueue: Record the ProvisioningRequest creation errors to event and ProvisioningRequest status.
```

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
MultiKueue: Record the ProvisioningRequest creation errors to event and ProvisioningRequest status.
```

**Comment by mimowo** [comment]
I think we should drop the "MultiKueue: " - this is not used in MultiKueue. In fact, currently ProvisioningRequests and MultiKueue aren't working together.

**Comment by tenzen-y** [comment]
> I think we should drop the "MultiKueue: " - this is not used in MultiKueue. In fact, currently ProvisioningRequests and MultiKueue aren't working together.

Oh, you're right. Let me revise the release-note.

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
ProvisioningRequest: Record the ProvisioningRequest creation errors to event and ProvisioningRequest status.
```

**Comment by mimowo** [comment]
/retitle Record an event and set status message when creation of provisioning request fails
