### PR TITLE
Fix accounting for running TAS workloads when Topology is re-created

### LINKED ISSUE #8748: TAS: re-creating topology instance leads to cache corruption
**What happened**:

When an instance of a topology is deleted and re-created it leads to cache corruption, and in consequence incorrect admissions:
1. it can lead to unexpected placement on two Pods on the same node which does not have enough capacity
2. it can lead to scheduling another workload on an occupied node

**What you expected to happen**:

Kueue should gracefully handle re-creating of Topology. The usage coming from pre-existing workloads should be correctly taken into account.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a workload binding a specific node with 1GPU, the workload using 1GPU
2. Re-create the topology
3. Delete the workload
4. Create a new workload 2x size (2 pods with 1 GPU each). 
5. 
Issue: both pods will be placed on the same node by Kueue.

**Anything else we need to know?**:

It is really hard to update a Topology currently, as Topology is immutable. Also, RF using Topology is immutable. 

The only workaround we found for the issue:
1. put all CQs on hold, setting spec.stopPolicy=HOLD
2. update the Topology by re-creating
3. restart Kueue <- essential step to rebuild the cache
4. resume all CQs, by setting spec.stopPolicy=NONE

This works fine, but this is not documented, and tricky to follow.

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #8748

#### Special notes for your reviewer:

To make sure there are no flakes I run all the TAS integration tests in a loop:
```
GINKGO_ARGS="--until-it-fails"  INTEGRATION_TARGET=./test/integration/singlecluster/tas make test-integration | tee out.txt
```
I have 20 fully successful attempts (before https://github.com/kubernetes-sigs/kueue/pull/8755/changes/8011a1c534dd8e9f32ec93a14fc2632c88e52a29)
already 7 fully successful attempts after that commit.

#### Does this PR introduce a user-facing change?

```release-note
TAS: Fixed handling of the scenario where a Topology instance is re-created (for example, to add a new Topology level).
Previously, this would cause cache corruption, leading to issues such as:
1. Scheduling a workload on nodes that are fully occupied by already running workloads.
2. Scheduling two or more pods of the same workload on the same node (even when the node cannot host both).
```

### CODE REVIEW

**Comment by mimowo** [comment]
I think it would be good to include in 0.16.0, as well as backport. 

cc @gabesaba @PBundyra ptal

**Comment by gabesaba** [comment]
```
Summarizing 1 Failure:
  [FAIL] LeaderWorkerSet integration when LeaderWorkerSet created should allow to scale up, scale down fast [It] LeaderCreatedStartupPolicy [area:singlecluster, feature:leaderworkerset]
  /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/leaderworkerset_test.go:495
Ran 82 of 82 Specs in 521.792 seconds
FAIL! -- 81 Passed | 1 Failed | 0 Pending | 0 Skipped
```

Failure looks unrelated.

/retest

**Comment by mimowo** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/8755/pull-kueue-test-e2e-main-1-35/2014610903948857344

> Failure looks unrelated.

Indeed this is a known flake https://github.com/kubernetes-sigs/kueue/issues/8752

File: pkg/cache/scheduler/clusterqueue.go [hunk 1]
```diff
@@ -237,7 +230,39 @@ func (c *clusterQueue) updateQueueStatus(log logr.Logger) {
...
+func (c *clusterQueue) ensureTASIsSynced(log logr.Logger) {
+	if !features.Enabled(features.TopologyAwareScheduling) || len(c.tasFlavors) == 0 {
+		return
+	}
+	if !c.isTASInitialized() {
+		c.isTASSynced = false
+		return
+	}
+	if !c.isTASSynced {
+		log.V(2).Info("Syncing TAS usage initilized TAS cache", "workloads", len(c.Workloads))
```
Comment (gabesaba) [inline pkg/cache/scheduler/clusterqueue.go]:
```suggestion
		log.V(2).Info("Syncing TAS usage to initialized TAS cache", "workloads", len(c.Workloads))
```

File: pkg/cache/scheduler/clusterqueue.go [hunk 2]
```diff
@@ -237,7 +230,39 @@ func (c *clusterQueue) updateQueueStatus(log logr.Logger) {
...
+		// There are some workloads which are not accounted yet for TAS.
+		// We re-add them as now the tasCache is initialized.
+		for k, w := range c.Workloads {
+			if c.workloadsNotAccountedForTAS.Has(k) {
+				c.addOrUpdateWorkload(log, w.Obj)
+				c.workloadsNotAccountedForTAS.Delete(k)
+			}
+		}
+	}
+	c.isTASSynced = true
```
Comment (gabesaba) [inline pkg/cache/scheduler/clusterqueue.go]: I'm wondering if we could simplify further, and delete `workloadsNotAccountedForTAS` altogether, with the end state of `ensureTASIsSynced` looking close to this:

```go
if !c.isTASInitialized() {
		c.isTASSynced = false
		return
	}
	if c.isTASSynced {
		return
	}
	log.V(2).Info("Syncing TAS usage initilized TAS cache", "workloads", len(c.Workloads))
	for _, w := range c.Workloads {
		c.addOrUpdateWorkload(log, w.Obj)
	}
	c.isTASSynced = true
```

To make this work, I think we could add idempotent deletes into TASFlavorCache, so that if a delete is processed when the cache is not initialized/synced, it won't do anything:

```go
type TASFlavorCache struct {
...
  map[wlKey]TopologyRequests
}

// updates usage, and stores the added usage to the map
func (c *TASFlavorCache) addUsage(wlKey KEY, TopologyRequests)

// removes usage if it exists in the map, and deletes key from map. idempotent
func (c *TASFlavorCache) removeUsage(wlKey KEY)
```

File: pkg/cache/scheduler/clusterqueue.go (hunk 1 above)
Comment (mimowo) [reply pkg/cache/scheduler/clusterqueue.go]: done

File: pkg/cache/scheduler/clusterqueue.go (hunk 2 above)
Comment (mimowo) [reply pkg/cache/scheduler/clusterqueue.go]: Yes, I think this can work. let me cherrypick that [commit](https://github.com/kubernetes-sigs/kueue/commit/0bf31ec44201591fc4d0c15d157a38d6cd7db299) which lgtm

Comment (mimowo) [reply pkg/cache/scheduler/clusterqueue.go]: Done, ptal , I only:
- tweaked this function https://github.com/kubernetes-sigs/kueue/pull/8755/changes#diff-aa793cfc2528f289b2b59725f714db6e6f6b2c6e9edf4c75925e656e0cc055b7R167-R173
- added comment: https://github.com/kubernetes-sigs/kueue/pull/8755/changes#diff-aa793cfc2528f289b2b59725f714db6e6f6b2c6e9edf4c75925e656e0cc055b7R89-R90
- added Clone here: https://github.com/kubernetes-sigs/kueue/pull/8755/changes#diff-aa793cfc2528f289b2b59725f714db6e6f6b2c6e9edf4c75925e656e0cc055b7R163

File: pkg/cache/scheduler/tas_flavor.go [hunk 3]
```diff
@@ -154,12 +159,18 @@ func (c *TASFlavorCache) snapshotForNodes(log logr.Logger, nodes []corev1.Node)
 	return snapshot
 }
 
-func (c *TASFlavorCache) addUsage(topologyRequests []workload.TopologyDomainRequests) {
+func (c *TASFlavorCache) addUsage(key workload.Reference, topologyRequests []workload.TopologyDomainRequests) {
+	c.wlUsage[key] = slices.Clone(topologyRequests)
```
Comment (gabesaba) [inline pkg/cache/scheduler/tas_flavor.go:163]: should we do a defensive deep copy, or do you think shallow is enough?

Comment (mimowo) [reply pkg/cache/scheduler/tas_flavor.go:163]: I don't think we have code which mutates instances of TopologyDomainRequests in place, so I think just shallow is enough.

**Comment by gabesaba** [comment]
/lgtm

thanks!

**Comment by mimowo** [comment]
I will make them manually

File: pkg/cache/scheduler/tas_flavor.go [hunk 4]
```diff
@@ -154,12 +159,18 @@ func (c *TASFlavorCache) snapshotForNodes(log logr.Logger, nodes []corev1.Node)
 	return snapshot
 }
 
-func (c *TASFlavorCache) addUsage(topologyRequests []workload.TopologyDomainRequests) {
+func (c *TASFlavorCache) addUsage(key workload.Reference, topologyRequests []workload.TopologyDomainRequests) {
```
Comment (PBundyra) [inline pkg/cache/scheduler/tas_flavor.go:162]: Shouldn't we also make it indempotent and check if the Workload has already been added?

Comment (mimowo) [reply pkg/cache/scheduler/tas_flavor.go:162]: I'm not sure what "should" means here. If it means 
1. "is it required to fix the bug?" - then I don't think so, because idempotence for adds is already taken care at the [addOrUpdateWorkload](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/scheduler/clusterqueue.go#L454-L466) level. 
2. "would it be more readable if we moved the idempotence down to the same layer" - likely yes, but I think one would need to prototype the PR. I'm open to this consideration, symmetry is nice.
