### PR TITLE
[kueuectl] Fix "should print workloads list with paging" test

### LINKED ISSUE #2353: Flaky integration test: Should print workloads list with paging
/kind flake

**What happened**:

Integration test failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2314/pull-kueue-test-integration-main/1798039851593895936

**What you expected to happen**:

No flake

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the build.

**Anything else we need to know?**:

```
  [FAILED] Expected
      <string>: "...     1s
      "
  to equal               |
      <string>: "...     0s
      "
  In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/kueuectl/list_test.go:206 @ 06/04/24 17:19:10.001
```

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
To fix "Should print workloads list with paging" test.

#### Which issue(s) this PR fixes:

Fixes #2353

#### Special notes for your reviewer:
The order of workloads in the table is wl3, wl1, wl2, which is different that the order of workloads in the expectations. Since the creation timestamps are generated by API server they may differ, so we need to use the same order.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
Integration passed 1/5

/test pull-kueue-test-integration-main

**Comment by mbobrovskyi** [comment]
Integration passed 2/5

/test pull-kueue-test-integration-main

**Comment by mbobrovskyi** [comment]
Integration passed 3/5

/test pull-kueue-test-integration-main

**Comment by mbobrovskyi** [comment]
Integration passed 4/5

/test pull-kueue-test-integration-main

**Comment by mbobrovskyi** [comment]
Integration passed 5/5

/test pull-kueue-test-integration-main

File: test/integration/kueuectl/list_test.go [hunk 1]
```diff
@@ -69,48 +69,50 @@ var _ = ginkgo.Describe("Kueuectl List", ginkgo.Ordered, ginkgo.ContinueOnFailur
...
 		// Simple client set that are using on unit tests not allow to filter by field selector.
 		ginkgo.It("Should print local queues list filtered by field selector", func() {
-			streams, _, output, errOutput := genericiooptions.NewTestIOStreams()
-			configFlags := CreateConfigFlagsWithRestConfig(cfg, streams)
-			executeTime := time.Now()
-			kueuectl := app.NewKueuectlCmd(app.KueuectlOptions{ConfigFlags: configFlags, IOStreams: streams, Clock: testingclock.NewFakeClock(executeTime)})
-
-			kueuectl.SetArgs([]string{"list", "localqueue", "--field-selector",
-				fmt.Sprintf("metadata.name=%s", lq1.Name), "--namespace", ns.Name})
+			gomega.Eventually(func(g gomega.Gomega) {
```
Comment (mimowo) [inline test/integration/kueuectl/list_test.go:72]: Why is Eventually needed since we use a fake clock? Is it that some places in the code still use real clock?

File: test/integration/kueuectl/list_test.go [hunk 2]
```diff
@@ -194,45 +200,49 @@ very-long-cluster-queue-name            0                   0
...
-				kueuectl := app.NewKueuectlCmd(app.KueuectlOptions{ConfigFlags: configFlags, IOStreams: streams, Clock: testingclock.NewFakeClock(executeTime)})
-
-				os.Setenv(list.KueuectlListRequestLimitEnvName, "1")
-				kueuectl.SetArgs([]string{"list", "workload", "--namespace", ns.Name})
-				err := kueuectl.Execute()
-
-				gomega.Expect(err).NotTo(gomega.HaveOccurred(), "%s: %s", err, output)
-				gomega.Expect(errOutput.String()).Should(gomega.BeEmpty())
-				gomega.Expect(output.String()).Should(gomega.Equal(fmt.Sprintf(`NAME                      JOB TYPE   JOB NAME   LOCALQUEUE                   CLUSTERQUEUE   STATUS    POSITION IN QUEUE   AGE
+				gomega.Eventually(func(g gomega.Gomega) {
```
Comment (mimowo) [inline test/integration/kueuectl/list_test.go:224]: This test failed here: https://github.com/kubernetes-sigs/kueue/issues/2353#issuecomment-2158668997 due to time shift, which suggests still some parts of the code use real clock. Could you explain why the test failed, then we can think if wrapping with Eventually is the solution we want. Maybe we could make sure all parts of the code use the same fake clock consistently instead.

File: test/integration/kueuectl/list_test.go (hunk 1 above)
Comment (mbobrovskyi) [reply test/integration/kueuectl/list_test.go]: Added eventually to fix [this](https://github.com/kubernetes-sigs/kueue/issues/2353#issuecomment-2159897688) one. In another cases you right it's not need. So reverted this changes.

Comment (mbobrovskyi) [reply test/integration/kueuectl/list_test.go]: Moved this fix to separate PR #2399

File: test/integration/kueuectl/list_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/integration/kueuectl/list_test.go]: Looks like it just mixed workload creation times.

**Review by trasc — COMMENTED** [review]
/lgtm

File: test/integration/kueuectl/list_test.go [hunk 3]
```diff
@@ -229,9 +229,9 @@ very-long-workload-name                         lq1
 wl1                                             lq1                                         PENDING                       %s
 wl2                                             very-long-local-queue-name                  PENDING                       %s
 `,
+					duration.HumanDuration(executeTime.Sub(wl3.CreationTimestamp.Time)),
```
Comment (tenzen-y) [inline test/integration/kueuectl/list_test.go:232]: I don't think that this should be resolved the root cause since the metav1 sore the only second level time, right?
So, could you add a sleep for every workload creation?

```shell
 lq1 = testing.MakeLocalQueue("lq1", ns.Name).ClusterQueue("cq1").Obj() 
 gomega.Expect(k8sClient.Create(ctx, lq1)).To(gomega.Succeed()) 
 time.Sleep(time.Second)
...
```

https://github.com/kubernetes-sigs/kueue/blob/ccfadf0a87dbb2043afb0dc6db4c862b8fe77cec/test/integration/kueuectl/list_test.go#L60-L67

**Comment by mimowo** [comment]
@mbobrovskyi could you please explain why the change fixes the issue, and what is the problem?

**Comment by mimowo** [comment]
/lgtm
/approve
Thanks

File: test/integration/kueuectl/list_test.go (hunk 3 above)
Comment (tenzen-y) [reply test/integration/kueuectl/list_test.go:232]: Ah got it. Thanks.
