### PR TITLE
Deduplicate cohort hierarchy processing in QueueInadmissibleWorkloads

### LINKED ISSUE #8339: [TAS] Kueue tries to move inadmissible workloads to heap too many times upon a node change
**What happened**:
There's a mechanism in TAS that moves inadmissible workloads back to heap if there's some change to a node.
Once triggered, workloads in a whole CQ/Cohort hierarchy are put back at the front of the queue: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/queue/manager.go#L625

However in lines: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/tas/resource_flavor.go#L183-L190 we trigger this moving for every active CQ.

 **As a result we put back the workloads in a whole hierarchy N times, where N=number of CQ in a hierarchy.** 

**What you expected to happen**:
I expect that putting back workloads happens only once per change of node

**How to reproduce it (as minimally and precisely as possible)**:
Kueue: latest
Kind cluster manifest: `tas-kind-cluster.yaml` from the `hack/` folder
Manifests of the whole hierarchy:

```
apiVersion: kueue.x-k8s.io/v1beta2
kind: Topology
metadata:
  name: "default"
spec:
  levels:
  - nodeLabel: "cloud.provider.com/topology-block"
  - nodeLabel: "kubernetes.io/hostname"
---
kind: ResourceFlavor
apiVersion: kueue.x-k8s.io/v1beta2
metadata:
  name: "tas-flavor"
spec:
  nodeLabels:
    cloud.provider.com/node-group: "tas-group"
  topologyName: "default"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: "cq"
spec:
  namespaceSelector: {} # match all.
  cohortName: "root"
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "tas-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue"
spec:
  clusterQueue: "cq"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: "cq-2"
spec:
  cohortName: "root"
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "tas-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: Cohort
metadata:
  name: "root"
```

Try to change anything about a node e.g. value of some label and observe that for each `Reconcile TAS Resource Flavor` log there are two `Attempting to move workloads` logs

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sohankunkerkar**
The change tracks which cohort roots have already been processed within a single `QueueInadmissibleWorkloads` call and skip CQs whose root was already handled. This ensures each hierarchy is processed exactly once regardless of how many CQs from that hierarchy are in the input.

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #8339 

#### Does this PR introduce a user-facing change?

```release-note
HC: Avoid redundant requeuing of inadmissible workloads when multiple ClusterQueues in the same cohort hierarchy are processed.
```

### CODE REVIEW

**Comment by mimowo** [comment]
@sohankunkerkar let us know if the PR is ready for review, then remove the WIP tag.

File: pkg/cache/queue/manager.go [hunk 1]
```diff
@@ -608,12 +608,22 @@ func (m *Manager) QueueInadmissibleWorkloads(ctx context.Context, cqNames sets.S
...
 			continue
 		}
+		if cq.HasParent() {
+			rootName := cq.Parent().getRootUnsafe().GetName()
+			if processedRoots.Has(rootName) {
+				continue
+			}
+			processedRoots.Insert(rootName)
+		}
 		if m.requeueWorkloadsCQ(ctx, cq) {
```
Comment (tenzen-y) [inline pkg/cache/queue/manager.go]: This is just a comment. I confirmed that `requeueWorkloadsCQ` requeues workloads belonging to all subtrees nodes: https://github.com/kubernetes-sigs/kueue/blob/2f51c88c72a81080475eaf27df19cb4ffeb2825e/pkg/cache/queue/manager.go#L627-L677

File: pkg/cache/queue/manager_test.go [hunk 2]
```diff
@@ -263,6 +263,62 @@ func TestRequeueWorkloadsCohortCycle(t *testing.T) {
...
 }
 
+func TestQueueInadmissibleWorkloadsDeduplication(t *testing.T) {
+	ctx, _ := utiltesting.ContextWithLog(t)
+
+	cohort := utiltestingapi.MakeCohort("alpha").Obj()
+	clusterQueues := []*kueue.ClusterQueue{
+		utiltestingapi.MakeClusterQueue("cq1").Cohort("alpha").Obj(),
+		utiltestingapi.MakeClusterQueue("cq2").Cohort("alpha").Obj(),
+	}
```
Comment (tenzen-y) [inline pkg/cache/queue/manager_test.go]: Could you use Tree structure for carefully verifications?

**Review by tenzen-y — COMMENTED** [review]
Basically, LGTM. Thank you 👍 

@sohankunkerkar If you can, could you show that kueue-controller-manager logs do not output `Attempting to move workloads` twice by using exampled described in https://github.com/kubernetes-sigs/kueue/issues/8339?

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
HC: Avoid redundant requeuing of inadmissible workloads when multiple ClusterQueues in the same cohort hierarchy are processed.
```

**Comment by tenzen-y** [comment]
I think that this is not only for TAS and this issue affects all HC environments. So, I added the "HC" prefix to the release note.

File: pkg/cache/queue/manager_test.go (hunk 2 above)
Comment (sohankunkerkar) [reply pkg/cache/queue/manager_test.go]: Sure, I think this was used in the existing file in some test, so I thought of using the same convention but let me change that.

**Comment by sohankunkerkar** [comment]
> @sohankunkerkar If you can, could you show that kueue-controller-manager logs do not output `Attempting to move workloads` twice by using exampled described in #8339?

Sure, I have done some testing around this. I'm not sure the expectation here but I can just paste the piece of logs before v/s after:
```sh
  ---
  {"level":"Level(-2)","ts":"2026-01-07T19:06:10.395518591Z","logger":"tas-resource-flavor-controller","caller":"tas/resource_flavor.go:154","msg":"Reconcile TAS Resource Flavor","replica-role":"leader","name":"tas-flavor","reconcileID":"ddf8db42-d339-4d2d-9fab-754c03b84121"}
  {"level":"Level(-2)","ts":"2026-01-07T19:06:10.39560449Z","logger":"tas-resource-flavor-controller","caller":"queue/manager.go:664","msg":"Attempting to move workloads","replica-role":"leader","name":"tas-flavor","reconcileID":"ddf8db42-d339-4d2d-9fab-754c03b84121","cohort":"root","root":"root"}
  {"level":"Level(-2)","ts":"2026-01-07T19:06:10.395620411Z","logger":"tas-resource-flavor-controller","caller":"queue/manager.go:664","msg":"Attempting to move workloads","replica-role":"leader","name":"tas-flavor","reconcileID":"ddf8db42-d339-4d2d-9fab-754c03b84121","cohort":"root","root":"root"}

  After the fix:
  {"level":"Level(-2)","ts":"2026-01-07T19:11:30.097847942Z","logger":"tas-resource-flavor-controller","caller":"tas/resource_flavor.go:189","msg":"Reconcile TAS Resource Flavor","replica-role":"leader","name":"tas-flavor","reconcileID":"92586f92-03a3-4ba8-8096-aa98c82eb850"}
  {"level":"Level(-2)","ts":"2026-01-07T19:11:30.097942339Z","logger":"tas-resource-flavor-controller","caller":"queue/manager.go:674","msg":"Attempting to move workloads","replica-role":"leader","name":"tas-flavor","reconcileID":"92586f92-03a3-4ba8-8096-aa98c82eb850","cohort":"root","root":"root"}


```

File: pkg/cache/queue/manager_test.go [hunk 3]
```diff
@@ -263,6 +263,74 @@ func TestRequeueWorkloadsCohortCycle(t *testing.T) {
 	}
 }
 
+func TestQueueInadmissibleWorkloadsDeduplication(t *testing.T) {
```
Comment (gabesaba) [inline pkg/cache/queue/manager_test.go]: Is this testing anything new? Does it still pass before the src code change?

File: pkg/cache/queue/manager.go [hunk 4]
```diff
@@ -608,12 +608,22 @@ func (m *Manager) QueueInadmissibleWorkloads(ctx context.Context, cqNames sets.S
...
 		if cq == nil {
 			continue
 		}
+		if cq.HasParent() {
+			rootName := cq.Parent().getRootUnsafe().GetName()
+			if processedRoots.Has(rootName) {
+				continue
+			}
+			processedRoots.Insert(rootName)
+		}
```
Comment (gabesaba) [inline pkg/cache/queue/manager.go]: nit: extract this to a well-named function please

File: pkg/cache/queue/manager_test.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/cache/queue/manager_test.go]: Yes, that's right. But almost all those tests were added before HC was introduced.
Additionally, I think verifications with Tree test data are important in this case since we rely on the mechanism to get the root cohort.

**Comment by tenzen-y** [comment]
> > @sohankunkerkar If you can, could you show that kueue-controller-manager logs do not output `Attempting to move workloads` twice by using exampled described in #8339?
> 
> Sure, I have done some testing around this. I'm not sure the expectation here but I can just paste the piece of logs before v/s after:
> 
> ```shell
>   ---
>   {"level":"Level(-2)","ts":"2026-01-07T19:06:10.395518591Z","logger":"tas-resource-flavor-controller","caller":"tas/resource_flavor.go:154","msg":"Reconcile TAS Resource Flavor","replica-role":"leader","name":"tas-flavor","reconcileID":"ddf8db42-d339-4d2d-9fab-754c03b84121"}
>   {"level":"Level(-2)","ts":"2026-01-07T19:06:10.39560449Z","logger":"tas-resource-flavor-controller","caller":"queue/manager.go:664","msg":"Attempting to move workloads","replica-role":"leader","name":"tas-flavor","reconcileID":"ddf8db42-d339-4d2d-9fab-754c03b84121","cohort":"root","root":"root"}
>   {"level":"Level(-2)","ts":"2026-01-07T19:06:10.395620411Z","logger":"tas-resource-flavor-controller","caller":"queue/manager.go:664","msg":"Attempting to move workloads","replica-role":"leader","name":"tas-flavor","reconcileID":"ddf8db42-d339-4d2d-9fab-754c03b84121","cohort":"root","root":"root"}
> 
>   After the fix:
>   {"level":"Level(-2)","ts":"2026-01-07T19:11:30.097847942Z","logger":"tas-resource-flavor-controller","caller":"tas/resource_flavor.go:189","msg":"Reconcile TAS Resource Flavor","replica-role":"leader","name":"tas-flavor","reconcileID":"92586f92-03a3-4ba8-8096-aa98c82eb850"}
>   {"level":"Level(-2)","ts":"2026-01-07T19:11:30.097942339Z","logger":"tas-resource-flavor-controller","caller":"queue/manager.go:674","msg":"Attempting to move workloads","replica-role":"leader","name":"tas-flavor","reconcileID":"92586f92-03a3-4ba8-8096-aa98c82eb850","cohort":"root","root":"root"}
> ```

Thank you for checking that! That looks great 👍

**Review by tenzen-y — COMMENTED** [review]
My PoV, LGTM,
@sohankunkerkar Please address @gabesaba 's comments.

File: pkg/cache/queue/manager.go (hunk 4 above)
Comment (sohankunkerkar) [reply pkg/cache/queue/manager.go]: I believe this code is self-contained and doesn’t need to be factored into a separate function, since it isn’t reused elsewhere.

File: pkg/cache/queue/manager_test.go (hunk 3 above)
Comment (sohankunkerkar) [reply pkg/cache/queue/manager_test.go]: Yeah, good call! I have added a custom logger to check the log calls explicitly.

**Comment by PBundyra** [comment]
LGTM as well, leaving final tagging to @gabesaba

**Comment by mimowo** [comment]
LGTM, let's cherrypick once merged
/cherrypick release-0.15
/cherrypick release-0.14

File: pkg/cache/queue/manager.go (hunk 4 above)
Comment (tenzen-y) [reply pkg/cache/queue/manager.go]: Personally, +1 on @sohankunkerkar 
@gabesaba Could we revisit making this as another function aftewards? Do you still think that we should decouple this mechanism into a separate function?

Comment (mimowo) [reply pkg/cache/queue/manager.go]: no big preference, but also leaning towards keeping this inside. We can extract if there is a potential to reuse, but I'm not clear where.

Comment (gabesaba) [reply pkg/cache/queue/manager.go]: The point of my suggestion wasn't reuse, but readability. The following reads a lot easier:

```go
if alreadyProcessedRoot(cq, processedRoots) {
  continue
}
```

Comment (gabesaba) [reply pkg/cache/queue/manager.go]: > @gabesaba Could we revisit making this as another function aftewards? Do you still think that we should decouple this mechanism into a separate function?

yes, we can revisit later.

**Comment by gabesaba** [comment]
thank you!

/lgtm
/approve

File: pkg/cache/queue/manager.go [hunk 5]
```diff
@@ -608,12 +608,22 @@ func (m *Manager) QueueInadmissibleWorkloads(ctx context.Context, cqNames sets.S
...
+	// multiple times when multiple CQs in cqNames share a root.
+	processedRoots := sets.New[kueue.CohortReference]()
 	var queued bool
 	for name := range cqNames {
 		cq := m.hm.ClusterQueue(name)
 		if cq == nil {
 			continue
 		}
+		if cq.HasParent() {
+			rootName := cq.Parent().getRootUnsafe().GetName()
```
Comment (gabesaba) [inline pkg/cache/queue/manager.go:621]: Sorry, I missed this - we need to do a cycle check before calling this unsafe root:

```
hierarchy.HasCycle(cohort)
```

You can try testing with a cohort cycle - I think this would cause a panic (which I'm surprised an existing test didn't pick up)

e.g. cq -> cohort2 -> cohort1 -> cohort2

Comment (tenzen-y) [reply pkg/cache/queue/manager.go:621]: Good point, thank you for calling it out.
We should do that. We can verify cycle similar as https://github.com/kubernetes-sigs/kueue/blob/2f51c88c72a81080475eaf27df19cb4ffeb2825e/pkg/cache/queue/manager.go#L659-L662

Comment (sohankunkerkar) [reply pkg/cache/queue/manager.go:621]: Can we invert the logic instead?
```go
if cq.HasParent() {
			if !hierarchy.HasCycle(cq.Parent()) {
				rootName := cq.Parent().getRootUnsafe().GetName()
				if processedRoots.Has(rootName) {
					continue
				}
				processedRoots.Insert(rootName)
			}
		}
```

Comment (sohankunkerkar) [reply pkg/cache/queue/manager.go:621]: >You can try testing with a cohort cycle - I think this would cause a panic (which I'm surprised an existing test didn't pick up)

I added a test for this. Let me know your thoughts.

File: pkg/cache/queue/manager.go [hunk 6]
```diff
@@ -629,12 +608,24 @@ func (m *Manager) QueueInadmissibleWorkloads(ctx context.Context, cqNames sets.S
...
+	// multiple times when multiple CQs in cqNames share a root.
+	processedRoots := sets.New[kueue.CohortReference]()
 	var queued bool
 	for name := range cqNames {
 		cq := m.hm.ClusterQueue(name)
 		if cq == nil {
 			continue
 		}
+		if cq.HasParent() {
+			if !hierarchy.HasCycle(cq.Parent()) {
```
Comment (mimowo) [inline pkg/cache/queue/manager.go]: non-blocking nit, but I would inline the checks to save on avoid indentation

File: pkg/cache/queue/manager_test.go (hunk 2 above)
Comment (mimowo) [reply pkg/cache/queue/manager_test.go]: This seems already addressed, so can we resolve to avoid distractions?

File: pkg/cache/queue/manager_test.go [hunk 7]
```diff
@@ -265,11 +259,138 @@ func TestRequeueWorkloadsCohortCycle(t *testing.T) {
...
+			t.Errorf("Unexpected active workloads after requeue (-want +got):\n%s", diff)
+		}
+		// Verify deduplication: although cq1 and cq2 share the same root, the
+		// "Attempting to move workloads" log should appear only once.
+		if moveWorkloadsLogCount != 1 {
+			t.Errorf("Expected 1 'Attempting to move workloads' log call (deduplication), got %d", moveWorkloadsLogCount)
+		}
+	})
+
+	t.Run("cohort cycle", func(t *testing.T) {
```
Comment (mimowo) [inline pkg/cache/queue/manager_test.go]: It could be a follow up, but I prefer using table tests with static initialization. 

This way we avoid duplication with the imperative code to set up the tests, and thus we make adding new test cases less error prone. Finally, it is easier to read - you read the setup set once and then can read all test cases.

**Comment by sohankunkerkar** [comment]
@mimowo @gabesaba PTAL

File: pkg/cache/queue/manager_test.go [hunk 8]
```diff
@@ -265,11 +259,140 @@ func TestRequeueWorkloadsCohortCycle(t *testing.T) {
...
+			wantActive: nil,
+		},
+	}
+
+	for name, tc := range cases {
+		t.Run(name, func(t *testing.T) {
+			var ctx context.Context
+			var moveWorkloadsLogCount int
+
+			if tc.wantMoveWorkloadsLogCount > 0 {
```
Comment (mimowo) [inline pkg/cache/queue/manager_test.go]: Do we need this "if"? It seems it adds unnecessary complexity

Comment (sohankunkerkar) [reply pkg/cache/queue/manager_test.go]: Good point, simplified it. Now using the counting logger for all cases.

**Comment by mimowo** [comment]
Thank you 👍 
/lgtm
/unhold
