### PR TITLE
Fix using PrioritySortingWithinCohort=false and borrowWithinCohort

### LINKED ISSUE #2821: Infinite preemption loop is possible when PrioritySortingWithingCohort=false is used with borrowWithinCohort
**What happened**:

An infinite preemption loop is possible when `PrioritySortingWithingCohort=false` is used together with 
borrowWithinCohort. This is possible when a high-priority workload from CQ running above quota needs
to borrow and preempts a lower priority workload. Then, the lower priority workload may take spot
in front of the high-priority workload (because PrioritySortingWithingCohort=false) and get re-admitted.
The cycle (preempt - admit - preempt) will repeat for the lower-priority workload.

The high-priority workload is never admitted (as long as its CQ is running above it nominal quota), because the lower-priority workload gets in front of it repeatedly.

**What you expected to happen**:

No infinite cycles of preempt - admit - preempt.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up the cluster as follows:
```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue-a"
spec:
  cohort: "all"
  preemption:
    withinClusterQueue: LowerPriority
    reclaimWithinCohort: Any
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 0
        borrowingLimit: 10
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue-b"
spec:
  cohort: "all"
  preemption:
    withinClusterQueue: LowerPriority
    reclaimWithinCohort: Any
    borrowWithinCohort:
      maxPriorityThreshold: 80000
      policy: LowerPriority
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 5
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue-c"
spec:
  cohort: "all"
  preemption:
    withinClusterQueue: LowerPriority
    reclaimWithinCohort: Any
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 5
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue-a"
spec:
  clusterQueue: "cluster-queue-a"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue-b"
spec:
  clusterQueue: "cluster-queue-b"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue-c"
spec:
  clusterQueue: "cluster-queue-c"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: mid-priority
value: 2
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 3
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
```
2. create the lower-priority workload in CQa:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-a-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue-a
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      priorityClassName: mid-priority
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["300s"]
        resources:
          requests:
            cpu: "4"
      restartPolicy: Never
```
3. Create 2 workloads in CQb:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-b-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue-b
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      priorityClassName: high-priority
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["300s"]
        resources:
          requests:
            cpu: "4"
      restartPolicy: Never
```
**Issue:** workload-a will go through infinite cycle of preemptions and admissions.

### PR DESCRIPTION
**Pull request by mimowo**
#### What this PR does / why we need it:

To prevent infinite preemption loop when borrowWithinCohort is used with `PrioritySortingWithingCohort=false`

#### Which issue(s) this PR fixes:

Fixes #2821

#### Special notes for your reviewer:

In the scenario described in #2821 when `PrioritySortingWithingCohort=false` we re-admit repeatedly workload-A (lower priority) which blocks the admission of the Workload-B2 (higher priority). 

Ideally, we would like workload-B to be scheduled, which would break the cycle. Workload-B2 would not get preempted  by Workload-A.

The code that is important for relative prioritization of the two workloads is [here](https://github.com/kubernetes-sigs/kueue/blob/21e9ac330cb6624f555668ccaca347a61c1f81ac/pkg/scheduler/scheduler.go#L625-L654):
1. [L630-634] both `Workload-A` and `Workload-B2` need to borrow to get admitted
2. [L637-639] fair sharing is not configured here, so this block is not relevant
3. [L641-648]  `PrioritySortingWithingCohort=false`  so this block is not relevant
4. [L651-653] `Workload-A` currently "wins" here because it is older

The idea for the fix in to modify the formula for `GetQueueOrderTimestamp` at the last step and use the timestamp to discriminate in favor of `Workload-B2`. In this order we use the `EvictionTimestamp` rather than creation timestamp. This idea is not entirely new as we do something similar to penalize workload evicted due to PodsReady timeout already.

#### Does this PR introduce a user-facing change?

```release-note
Prevent infinite preemption loop when PrioritySortingWithingCohort=false
is used together with borrowWithinCohort.
```

### CODE REVIEW

File: pkg/workload/workload.go [hunk 1]
```diff
@@ -540,6 +540,15 @@ func (o Ordering) GetQueueOrderTimestamp(w *kueue.Workload) *metav1.Time {
 			return &evictedCond.LastTransitionTime
 		}
 	}
+	if !features.Enabled(features.PrioritySortingWithinCohort) {
+		if preemptedCond := apimeta.FindStatusCondition(w.Status.Conditions, kueue.WorkloadPreempted); preemptedCond != nil &&
+			preemptedCond.Status == metav1.ConditionTrue &&
+			preemptedCond.Reason == kueue.InCohortReclaimWhileBorrowingReason {
```
Comment (mimowo) [inline pkg/workload/workload.go:546]: We would need to do `strings.HasPrefix(preemptedCond.Reason, "InCohort")` if we want to cherry-pick down to 0.7. 
cc @gabesaba

Comment (mimowo) [reply pkg/workload/workload.go:546]: As far as I can tell we don't need to cherry-pick to 0.7. Closing the comment.

**Comment by PBundyra** [comment]
Could you please describe the mechanism in description behind preventing the infinite loop?

**Comment by PBundyra** [comment]
How do we estimate that 1ms will be enough to put the preemptor in front of the workload being preemtepted?
Other than that, LGTM

**Comment by mimowo** [comment]
> Could you please describe the mechanism in description behind preventing the infinite loop? Especially which workload does Kueue should admit after the changes

Good idea, I have updated the "Special notes for your reviewer:" section. PTAL.

**Comment by mimowo** [comment]
> How do we estimate that 1ms will be enough to put the preemptor in front of the workload being preemtepted?
> Other than that, LGTM

Yes, any epsilon would be enough. This is just to discriminate them in scenario when the creation timestamp of the preemptor equals eviction timestamp of the preempted workload. This is a practical possibility which was discovered by the integration test when I was running it in a loop.

**Comment by PBundyra** [comment]
Thank you, LGTM

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Prevent infinite preemption loop when PrioritySortingWithinCohort=false
is used together with borrowWithinCohort.
```
