### PR TITLE
[Fix] Make sure Kueue deployment works after restart

### LINKED ISSUE #8668: [flaky multikueue test] MultiKueue when Connection via ClusterProfile no plugins uses ClusterProfile as way to connect worker cluster
**Which test is flaking?**:
MultiKueue when Connection via ClusterProfile no plugins uses ClusterProfile as way to connect worker cluster
**First observed in** (PR or commit, if known):
don't know
**Link to failed CI job or steps to reproduce locally**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-multikueue-release-0-15/2013243602003562496
**Failure message or logs**:
```
End To End MultiKueue Suite: kindest/node:v1.34.0: [It] MultiKueue when Connection via ClusterProfile no plugins uses ClusterProfile as way to connect worker cluster expand_less	55s
{Expected success, but got an error:
    <*errors.StatusError | 0xc00099bea0>: 
    conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post "https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s": EOF
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post \"https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s\": EOF",
            Reason: "",
            Details: nil,
            Code: 500,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc00099bea0>: 
    conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post "https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s": EOF
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post \"https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s\": EOF",
            Reason: "",
            Details: nil,
            Code: 500,
        },
    }
In [AfterEach] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/multikueue/e2e_test.go:207 @ 01/19/26 13:57:31.823
}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
As investigated by @mimowo [here](https://github.com/kubernetes-sigs/kueue/issues/8668#issuecomment-3798196469).
Check `.spec.Replicas` additionally to checking `.status.Replicas` to not check transitioning pods.

#### Which issue(s) this PR fixes:

Fixes #8668

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/util/e2e.go [hunk 1]
```diff
@@ -450,6 +451,7 @@ func waitForDeploymentWithOnlyAvailableReplicas(ctx context.Context, k8sClient c
 	gomega.EventuallyWithOffset(2, func(g gomega.Gomega) {
 		g.Expect(k8sClient.Get(ctx, key, deployment)).To(gomega.Succeed())
 		g.Expect(deployment.Status.Replicas).To(gomega.Equal(deployment.Status.AvailableReplicas))
```
Comment (mbobrovskyi) [inline test/util/e2e.go:453]: I'm wondering do we we need this?

Comment (mimowo) [reply test/util/e2e.go:453]: it might no longer be needed. The initial idea was to make sure we only have AvailableReplicas. However, this wasn't enough for the case when we have more AvailbaleReplicas than desired.

We may consider simplifying in a follow up if we test it does not flake.
