### PR TITLE
Order candidates for FS preemption using less function used to sort workloads

### LINKED ISSUE #6763: [FairSharing] Preemption algorithm is non-deterministic leading to excessive preemption
**What happened**:
When there are two CQ that have equal DRS, FairSharing preemption algorithm picks one randomly ([based on the hash function in a set](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/cache/hierarchy/cohort.go#L45)). Since the algorithm is run over and over for the same preemptor until preemption actually executes this leads to excessive preemption, where a preemptor Workload preempts more Workloads than needed if they come from drawing ClusterQueues

**What you expected to happen**:
Make the preemption algorithm deterministic, ideally Workloads should be ordered by the same less function as across the codebase

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
- Moves `CandidatesOrdering` function to different package to avoid cyclic dependency 
- Uses `CandidatesOrdering` function in FS preemption algorithm in case of two ClusterQueues draw
- Adds logger to `TargetClusterQueueOrdering` so it can call `CandidatesOrdering`
- Adds integration test that tests the scenario described in the issue. Before the change the test failed

#### Which issue(s) this PR fixes:

Fixes #6763 

#### Special notes for your reviewer:
I decided to keep moving the function and calling it in the same PR to be able to cherrypick it smoothly

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug in FairSharing algorithm for identifying preemption candidates, as it could return a different
set of preemption target workloads (pseudo random) in consecutive attempts in tie-break scenarios,
resulting in excessive preemptions.
```

### CODE REVIEW

**Comment by PBundyra** [comment]
cc @gabesaba @mimowo

**Comment by mimowo** [comment]
Please update the release note so that it allows users to correlate they behavior with the bug, focusing on user-observable behavior rather than internal details.

Proposal, but feel free to update:

/release-note-edit
```release-note
Fix the bug in FairSharing algorithm for identifying preemption candidates, as it could return a different
set of preemption target workloads (pseudo random) in consecutive attempts in tie-break scenarios,
resulting in excessive preemptions.
```

**Comment by mimowo** [comment]
@PBundyra general question before reading this in full - what is the general appraoch for fixing the problem? 

Seems like a needle in haystack due to the amount of changes. Is there a way to de-couple refactoring and actual fix?

**Comment by PBundyra** [comment]
> Please update the release note so that it allows users to correlate they behavior with the bug, focusing on user-observable behavior rather than internal details.

The fix is to use `CandidatesOrdering` when it comes to tie between two CQ with the same DRS: https://github.com/kubernetes-sigs/kueue/pull/6764/files#diff-c791c7f8f43735ff11274e29bfe6eb9320dfc913d4a5a0f14b3ba03038b076b4R154-R163

The refactor only consists of moving the `CandidatesOrdering` and related function to different package, I could divide into two PRs but I would also like to cherrypick this one

**Comment by mimowo** [comment]
> The fix is to use CandidatesOrdering when it comes to tie between two CQ with the same DRS:

Makes sense! Thanks for the link, I just missed it after an initial browse.

I'm fine with reusing the entire function, but not sure about the consequences of various checks  - like AFS or priority - we probably don't test them all?

Did you consider exposing a smaller function which would be tie-breaking just by Timestamp and UID?

> The refactor only consists of moving the CandidatesOrdering and related function to different package, I could divide into two PRs but I would also like to cherrypick this one

I see, indeed in this approach it is probably better to keep in one PR. Maybe just write the approach in "Special notes for your reviewer:" so that reviewers have the big picture of "why".

**Comment by PBundyra** [comment]
> I'm fine with reusing the entire function, but not sure about the consequences of various checks - like AFS or priority - we probably don't test them all?
> 
> Did you consider exposing a smaller function which would be tie-breaking just by Timestamp and UID?

We don't check the AFS there as I call this function with `afsEnabled:false` argument. I think it makes sense to boils down to priority/timestamp/uid which I think makes sense

**Comment by mimowo** [comment]
> We don't check the AFS there as I call this function with `afsEnabled:false` argument. I think it makes sense to boils down to priority/timestamp/uid which I think makes sense

I see, I'm good using the function then. The remaining question if it belongs conceptually to "fairsharing" package. Is this function used for classical preemption? If so, then maybe it belongs to `common` package, wdyt?

File: pkg/scheduler/preemption/preemption.go [hunk 1]
```diff
@@ -221,7 +219,7 @@ func (p *Preemptor) classicalPreemptions(preemptionCtx *preemptionCtx) []*Target
 		Requests:          preemptionCtx.workloadUsage.Quota,
 		WorkloadOrdering:  p.workloadOrdering,
 	}
-	candidatesGenerator := classical.NewCandidateIterator(hierarchicalReclaimCtx, p.enabledAfs, preemptionCtx.frsNeedPreemption, preemptionCtx.snapshot, p.clock, CandidatesOrdering)
+	candidatesGenerator := classical.NewCandidateIterator(hierarchicalReclaimCtx, p.enabledAfs, preemptionCtx.frsNeedPreemption, preemptionCtx.snapshot, p.clock, fairsharing.CandidatesOrdering)
```
Comment (gabesaba) [inline pkg/scheduler/preemption/preemption.go]: Can we move CandidatesOrdering to preemptioncommon? classical should not be using fairsharing package. Consider doing this in a prepatory PR (I'll leave this up to you).

Comment (gabesaba) [reply pkg/scheduler/preemption/preemption.go]: oops, @mimowo already said this :) https://github.com/kubernetes-sigs/kueue/pull/6764#issuecomment-3269858218

File: test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go [hunk 2]
```diff
@@ -614,6 +614,56 @@ var _ = ginkgo.Describe("Scheduler", ginkgo.Ordered, ginkgo.ContinueOnFailure, f
...
+				ResourceGroup(
+					*testing.MakeFlavorQuotas("default").Resource(corev1.ResourceCPU, "8").Obj(),
+				).Preemption(kueue.ClusterQueuePreemption{
+				ReclaimWithinCohort: kueue.PreemptionPolicyAny}).
+				Obj())
+
+			features.SetFeatureGateDuringTest(ginkgo.GinkgoTB(), features.AdmissionFairSharing, false)
+		})
+
+		ginkgo.It("Guaranteed workloads cause preemption of a single best effort workload", func() {
```
Comment (mimowo) [inline test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:647]: Does this test flake (how often) on the main branch?

 Sanity check if it is really testing the changes.

Comment (PBundyra) [reply test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go:647]: It fails almost constantly

File: pkg/scheduler/preemption/preemption.go (hunk 1 above)
Comment (PBundyra) [reply pkg/scheduler/preemption/preemption.go]: Yes, I will do that

**Comment by PBundyra** [comment]
> > We don't check the AFS there as I call this function with `afsEnabled:false` argument. I think it makes sense to boils down to priority/timestamp/uid which I think makes sense
> 
> I see, I'm good using the function then. The remaining question if it belongs conceptually to "fairsharing" package. Is this function used for classical preemption? If so, then maybe it belongs to `common` package, wdyt?

Will do!

File: pkg/scheduler/preemption/preemption.go (hunk 1 above)
Comment (PBundyra) [reply pkg/scheduler/preemption/preemption.go]: Done

**Comment by PBundyra** [comment]
> > I see, I'm good using the function then. The remaining question if it belongs conceptually to "fairsharing" package. Is this function used for classical preemption? If so, then maybe it belongs to `common` package, wdyt?
> 
> Will do!

Done

**Review by mimowo — COMMENTED** [review]
Thanks 👍 

/lgtm
/approve
/cherrypick release-0.13
/cherrypick release-0.12

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
FS: Fix the algorithm bug for identifying preemption candidates, as it could return a different
set of preemption target workloads (pseudo random) in consecutive attempts in tie-break scenarios,
resulting in excessive preemptions.
```
