### PR TITLE
Report entire objects in ginkgo reports when asserts fail

### LINKED ISSUE #9360: Report entire objects in ginkgo reports when asserts fail
**What would you like to be added**:

I would like to report the entire objects in the failure report when an assert fails.

For example, an assert on the suspend field fails, I would like to see the entire Job state in the failure report.

https://github.com/kubernetes-sigs/kueue/blob/cf49633305c8df2cd7b1a2d944f488962497e304/test/util/util.go#L844

There might be not "silver bullet" solution, so we could just start by improving the "helper" utility functions for asserting. in test/util/*.

Some ideas at technical level:
- use ginkgo.HasField, to assert field, eg"spec.suspend", but it will report the entire workload
- attach the entire object as description to each assert (needs better formatter probably)

**Why is this needed**:

This will be very useful for debugging. Some historical cases which could be easier by this:
- when finalizers keep workload deletion we just see that there is no NotFoundError, but seeing finalizers would make it easier
- some race conditions caused Workload state internally invalid, eg for admissionChecks and evictions. Seeing entire workload rather than just the field would help to resolve just issues much faster

### PR DESCRIPTION
**Pull request by laxmi-333**
Include full object state in failure descriptions for test helper functions in test/util/util.go. This uses gomega.HaveField for clear field-level assertions combined with json.MarshalIndent to attach the entire object to the failure report.

Starting with finalizer helpers (ExpectPodsJustFinalized, ExpectPodsFinalizedOrGone, ExpectWorkloadsFinalizedOrGone) to align on the approach before expanding to more helpers.

Ref #9360

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Improves test failure debugging by including the full object state (as JSON) in Ginkgo failure reports when assertions fail in test helper functions.

Currently, when an assertion fails (e.g., a finalizer is still present on a Pod or Workload), the failure report only shows the field value that didn't match. This makes it difficult to understand why the object is in that state. With this change, the entire object is attached to the failure report as JSON, showing all metadata, labels, annotations, finalizers, conditions, status, etc.

The approach uses:
- `gomega.HaveField` for clear field-level assertions
- `json.MarshalIndent` to attach the full object state as a failure description

Starting with finalizer helpers to align on the approach before expanding to more helpers.

#### Which issue(s) this PR fixes:

Fixes  #9360

#### Special notes for your reviewer:

This PR covers 3 helper functions to start with as per @mimowo's suggestion to align on the approach first:
- `ExpectPodsJustFinalized`
- `ExpectPodsFinalizedOrGone`
- `ExpectWorkloadsFinalizedOrGone`

I considered `format.Object` (Gomega's built-in formatter) but chose `json.MarshalIndent` because it produces cleaner output -- nil/empty fields are omitted via `omitempty` tags, and the format is familiar from `kubectl get -o json`.

I also tried using `gomega.HaveField` alone, but it only reports the extracted field value in its failure message, not the entire object. The combined approach (HaveField + JSON description) provides both the field-level clarity and the full object dump.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/util/util.go [hunk 1]
```diff
@@ -124,7 +127,7 @@ func expectObjectToBeDeletedWithTimeout[PtrT objAsPtr[T], T any](ctx context.Con
 	}
 	gomega.EventuallyWithOffset(2, func(g gomega.Gomega) {
 		newObj := PtrT(new(T))
-		g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(o), newObj)).Should(utiltesting.BeNotFoundError())
+		g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(o), newObj)).Should(utiltesting.BeNotFoundError(), "Object still exists\n%s", toJSON(newObj))
```
Comment (mimowo) [inline test/util/util.go:130]: Have you had a chance to test locally if this works well if there is a custom finalizer injected which would prevent the deletion? Would you mind maybe posting the output in that case.

Comment (laxmi-333) [reply test/util/util.go:130]: Hi @mimowo, 

Yes, I tested it locally. 

**Scenario 1:**

I forced a failure by commenting out the delete call in `expectObjectToBeDeletedWithTimeout`, so the object would never be deleted. When the timeout occurred, the failure output showed the full object state, clearly indicating why the deletion was blocked.

For example, the reason why the deletion is blocked can be seen here
```
Finalizers: [
    "kueue.x-k8s.io/resource-in-use",
]
```



 Output:

```
[FAILED] Timed out after 45.001s.
  The function passed to Eventually failed at /Users/laxmiadavalli/OSS-Kubernetes/kueue/test/util/util.go:130 with:
  Object still exists
      <*v1beta2.ClusterQueue | 0xc000ec2b40>: {
          TypeMeta: {Kind: "", APIVersion: ""},
          ObjectMeta: {
              Name: "cq",
              GenerateName: "",
              Namespace: "",
              SelfLink: "",
              UID: "b606bbbd-92c8-41d6-9f7e-0263c349a2f5",
              ResourceVersion: "246",
              Generation: 1,
              CreationTimestamp: {
                  Time: 2026-03-11T13:24:49+05:30,
              },
              DeletionTimestamp: nil,
              DeletionGracePeriodSeconds: nil,
              Labels: nil,
              Annotations: nil,
              OwnerReferences: nil,
              Finalizers: [
                  "kueue.x-k8s.io/resource-in-use",
              ],
              ManagedFields: [
                  {
                      Manager: "pod.test",
                      Operation: "Update",
                      APIVersion: "kueue.x-k8s.io/v1beta2",
                      Time: {
                          Time: 2026-03-11T13:24:49+05:30,
                      },
                      FieldsType: "FieldsV1",
                      FieldsV1: {
                          Raw: "{\"f:spec\":{\".\":{},\"f:flavorFungibility\":{\".\":{},\"f:whenCanBorrow\":{},\"f:whenCanPreempt\":{}},\"f:namespaceSelector\":{},\"f:preemption\":{\".\":{},\"f:borrowWithinCohort\":{\".\":{},\"f:policy\":{}},\"f:reclaimWithinCohort\":{},\"f:withinClusterQueue\":{}},\"f:queueingStrategy\":{},\"f:resourceGroups\":{},\"f:stopPolicy\":{}}}",
                      },
                      Subresource: "",
                  },
                  {
                      Manager: "pod.test",
                      Operation: "Update",
                      APIVersion: "kueue.x-k8s.io/v1beta2",
                      Time: {
                          Time: 2026-03-11T13:24:49+05:30,
                      },
                      FieldsType: "FieldsV1",
                      FieldsV1: {
                          Raw: "{\"f:status\":{\".\":{},\"f:admittedWorkloads\":{},\"f:conditions\":{\".\":{},\"k:{\\\"type\\\":\\\"Active\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:message\":{},\"f:observedGeneration\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}},\"f:flavorsReservation\":{\".\":{},\"k:{\\\"name\\\":\\\"fl\\\"}\":{\".\":{},\"f:name\":{},\"f:resources\":{\".\":{},\"k:{\\\"name\\\":\\\"cpu\\\"}\":{\".\":{},\"f:borrowed\":{},\"f:name\":{},\"f:total\":{}},\"k:{\\\"name\\\":\\\"memory\\\"}\":{\".\":{},\"f:borrowed\":{},\"f:name\":{},\"f:total\":{}}}}},\"f:flavorsUsage\":{\".\":{},\"k:{\\\"name\\\":\\\"fl\\\"}\":{\".\":{},\"f:name\":{},\"f:resources\":{\".\":{},\"k:{\\\"name\\\":\\\"cpu\\\"}\":{\".\":{},\"f:borrowed\":{},\"f:name\":{},\"f:total\":{}},\"k:{\\\"name\\\":\\\"memory\\\"}\":{\".\":{},\"f:borrowed\":{},\"f:name\":{},\"f:total\":{}}}}},\"f:pendingWorkloads\":{},\"f:reservingWorkloads\":{}}}",
                      },
                      Subresource: "status",
                  },
              ],
          },
          Spec: {
              ResourceGroups: [
                  {
                      CoveredResources: ["cpu", "memory"],
                      Flavors: [
                          {
                              Name: "fl",
                              Resources: [
                                  {
                                      Name: "cpu",
                                      NominalQuota: {
                                          i: {value: ..., scale: ...},
                                          d: {Dec: ...},
                                          s: "9",
                                          Format: "DecimalSI",
                                      },
                                      BorrowingLimit: nil,
                                      LendingLimit: nil,
                                  },
                                  {
                                      Name: "memory",
                                      NominalQuota: {
                                          i: {value: ..., scale: ...},
                                          d: {Dec: ...},
                                          s: "36",
                                          Format: "DecimalSI",
                                      },
                                      BorrowingLimit: nil,
                                      LendingLimit: nil,
                                  },
                              ],
                          },
                      ],
                  },
              ],
              CohortName: "",
              QueueingStrategy: "BestEffortFIFO",
              NamespaceSelector: {
                  MatchLabels: nil,
                  MatchExpressions: nil,
              },
              FlavorFungibility: {
                  WhenCanBorrow: "MayStopSearch",
                  WhenCanPreempt: "TryNextFlavor",
                  Preference: nil,
              },
              Preemption: {
                  ReclaimWithinCohort: "Never",
                  BorrowWithinCohort: {
                      Policy: "Never",
                      MaxPriorityThreshold: nil,
                  },
                  WithinClusterQueue: "Never",
              },
              AdmissionChecksStrategy: nil,
              StopPolicy: "None",
              FairSharing: nil,
              AdmissionScope: nil,
          },
          Status: {
              Conditions: [
                  {
                      Type: "Active",
                      Status: "True",
                      ObservedGeneration: 1,
                      LastTransitionTime: {
                          Time: 2026-03-11T13:24:49+05:30,
                      },
                      Reason: "Ready",
                      Message: "Can admit new workloads",
                  },
              ],
              FlavorsReservation: [
                  {
                      Name: "fl",
                      Resources: [
                          {
                              Name: "cpu",
                              Total: {
                                  i: {value: 0, scale: 0},
                                  d: {Dec: nil},
                                  s: "0",
                                  Format: "DecimalSI",
                              },
                              Borrowed: {
                                  i: {value: 0, scale: 0},
                                  d: {Dec: nil},
                                  s: "0",
                                  Format: "DecimalSI",
                              },
                          },
                          {
                              Name: "memory",
                              Total: {
                                  i: {value: 0, scale: 0},
                                  d: {Dec: nil},
                                  s: "0",
                                  Format: "DecimalSI",
                              },
                              Borrowed: {
                                  i: {value: 0, scale: 0},
                                  d: {Dec: nil},
                                  s: "0",
                                  Format: "DecimalSI",
                              },
                          },
                      ],
                  },
              ],
              FlavorsUsage: [
                  {
                      Name: "fl",
                      Resources: [
                          {
                              Name: "cpu",
                              Total: {
                                  i: {value: 0, scale: 0},
                                  d: {Dec: nil},
                                  s: "0",
                                  Format: "DecimalSI",
                              },
                              Borrowed: {
                                  i: {value: 0, scale: 0},
                                  d: {Dec: nil},
                                  s: "0",
                                  Format: "DecimalSI",
                              },
                          },
                          {
                              Name: "memory",
                              Total: {
                                  i: {value: 0, scale: 0},
                                  d: {Dec: nil},
                                  s: "0",
                                  Format: "DecimalSI",
                              },
                              Borrowed: {
                                  i: {value: 0, scale: 0},
                                  d: {Dec: nil},
                                  s: "0",
                                  Format: "DecimalSI",
                              },
                          },
                      ],
                  },
              ],
              PendingWorkloads: 0,
              ReservingWorkloads: 0,
              AdmittedWorkloads: 0,
              FairSharing: nil,
          },
      }
  Error matcher expects an error.  Got:
      <nil>: nil
  In [AfterEach] at: /Users/laxmiadavalli/OSS-Kubernetes/kueue/test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go:132
```

**Scenario 2:**

Injected a custom finalizer (test/block-deletion) before the delete call to simulate a stuck deletion. 

```
  Finalizers: [
                  "test/block-deletion",
              ],
```

 Output:

```
[FAILED] Timed out after 45.001s.
  The function passed to Eventually failed at /Users/laxmiadavalli/OSS-Kubernetes/kueue/test/util/util.go:134 with:
  Object still exists
      <*v1beta2.ResourceFlavor | 0xc0018809a0>: {
          TypeMeta: {Kind: "", APIVersion: ""},
          ObjectMeta: {
              Name: "fl",
              GenerateName: "",
              Namespace: "",
              SelfLink: "",
              UID: "896bf857-2318-4758-a8cc-29335417951d",
              ResourceVersion: "274",
              Generation: 2,
              CreationTimestamp: {
                  Time: 2026-03-11T16:44:19+05:30,
              },
              DeletionTimestamp: {
                  Time: 2026-03-11T16:44:20+05:30,
              },
              DeletionGracePeriodSeconds: 0,
              Labels: nil,
              Annotations: nil,
              OwnerReferences: nil,
              Finalizers: [
                  "test/block-deletion",
              ],
              ManagedFields: [
                  {
                      Manager: "pod.test",
                      Operation: "Update",
                      APIVersion: "kueue.x-k8s.io/v1beta2",
                      Time: {
                          Time: 2026-03-11T16:44:20+05:30,
                      },
                      FieldsType: "FieldsV1",
                      FieldsV1: {
                          Raw: "{\"f:metadata\":{\"f:finalizers\":{\"v:\\\"test/block-deletion\\\"\":{}}},\"f:spec\":{}}",
                      },
                      Subresource: "",
                  },
              ],
          },
          Spec: {NodeLabels: nil, NodeTaints: nil, Tolerations: nil, TopologyName: nil},
      }
  Error matcher expects an error.  Got:
      <nil>: nil
  In [AfterEach] at: /Users/laxmiadavalli/OSS-Kubernetes/kueue/test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go:133
```
