### PR TITLE
[PartialAdmission] Fix preemption while partially admitting.

### LINKED ISSUE #2799: Partial Admission Preemption Panic
**What happened**:
While refactoring `Preemptor.GetTargets`, I encountered a panic. Furthermore, I discovered that we are not exercising the PartialAdmission preemption logic in any of our tests, and it may be broken and panicking generally.

[This test](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/scheduler_test.go#L1194) exits [here](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/scheduler.go#L467-L469), as we find a preemption target above. The PartialAdmission preemption path is not tested.

[In this test](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/scheduler_test.go#L1234), we exit [here](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/preemption/preemption.go#L111). We panic when calling `assignment.TotalRequestsFor`, as [this map](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/flavorassigner/flavorassigner.go#L166) is empty

**How to reproduce it (as minimally and precisely as possible)**:

Move this line to the top of `Preemptor.GetTargets` and observe a panic during [this test](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/scheduler_test.go#L1234)
https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/preemption/preemption.go#L116

Delete these lines and observe that unit and integration tests still pass
https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/scheduler.go#L477-L481

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
- Fix the flow that allows a workload to be partially admitted while preempting lower priority workloads. 
- Add an unit test for preemption while partially admitting.

#### Which issue(s) this PR fixes:

Fixes #2799 

#### Does this PR introduce a user-facing change?

```release-note
Fix some scenarios for partial admission which are affected by wrong calculation of resources
used by the incoming workload which is partially admitted and preempting.
```

### CODE REVIEW

**Comment by trasc** [comment]
> Please add a release note describing what's changed from the user's perspective.

done

File: pkg/scheduler/flavorassigner/flavorassigner.go [hunk 1]
```diff
@@ -110,7 +110,12 @@ func (a *Assignment) TotalRequestsFor(wl *workload.Info) resources.FlavorResourc
 	usage := make(resources.FlavorResourceQuantities)
 	for i, ps := range wl.TotalRequests {
 		for res, q := range ps.Requests {
-			flv := a.PodSets[i].Flavors[res].Name
+			aps := a.PodSets[i]
+			flv := aps.Flavors[res].Name
+			// in case of partial admission scale down the quantity
+			if aps.Count != ps.Count {
+				q = q * int64(aps.Count) / int64(ps.Count)
```
Comment (mimowo) [inline pkg/scheduler/flavorassigner/flavorassigner.go:117]: IIRC we support `ps.Count=0` (https://github.com/kubernetes-sigs/kueue/issues/2227). Could it break in a scenario like this?

Comment (trasc) [reply pkg/scheduler/flavorassigner/flavorassigner.go]: I guess it is possible, reworked.

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -471,9 +471,12 @@ func (s *Scheduler) getAssignments(log logr.Logger, wl *workload.Info, snap *cac
...
 		reducer := flavorassigner.NewPodSetReducer(wl.Obj.Spec.PodSets, func(nextCounts []int32) (*partialAssignment, bool) {
 			assignment := flvAssigner.Assign(log, nextCounts)
-			if assignment.RepresentativeMode() == flavorassigner.Fit {
+			mode := assignment.RepresentativeMode()
+			if mode == flavorassigner.Fit {
 				return &partialAssignment{assignment: assignment}, true
-			} else if assignment.RepresentativeMode() == flavorassigner.Preempt {
+			}
+
+			if mode == flavorassigner.Preempt {
```
Comment (gabesaba) [inline pkg/scheduler/scheduler.go:479]: > [This test](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/scheduler_test.go#L1194) exits [here](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/scheduler.go#L467-L469), as we find a preemption target above. The PartialAdmission preemption path is not tested.

after deletion of this preemption block, the tests noted in #2799 still passes:
```
go test ./pkg/scheduler -run "TestSchedule/partial_admission_single_variable_pod_set,_preempt_first"
```

Comment (trasc) [reply pkg/scheduler/scheduler.go:479]: That test checks that preemption is done and wl admitted in full (without checking if it fits partially and decreasing the count) if that preemption is an option.

File: pkg/scheduler/flavorassigner/flavorassigner.go [hunk 3]
```diff
@@ -109,8 +109,13 @@ func (a *Assignment) ToAPI() []kueue.PodSetAssignment {
 func (a *Assignment) TotalRequestsFor(wl *workload.Info) resources.FlavorResourceQuantities {
 	usage := make(resources.FlavorResourceQuantities)
 	for i, ps := range wl.TotalRequests {
+		// in case of partial admission scale down the quantity
+		aps := a.PodSets[i]
+		if aps.Count != ps.Count {
+			ps = *ps.ScaledTo(aps.Count)
+		}
 		for res, q := range ps.Requests {
```
Comment (gabesaba) [inline pkg/scheduler/flavorassigner/flavorassigner.go:117]:
```suggestion
		aps := a.PodSets[i]
		for res, q := range ps.ScaledTo(aps.Count).Requests {
```

nit: check whether there is a change of `pod count` in `ScaledTo`, and call ScaledTo in the `range` line

File: pkg/workload/workload.go [hunk 4]
```diff
@@ -170,9 +170,11 @@ func (psr *PodSetResources) ScaledTo(newCount int32) *PodSetResources {
 		Flavors:  maps.Clone(psr.Flavors),
 	}
 
-	scaleDown(ret.Requests, int64(ret.Count))
-	scaleUp(ret.Requests, int64(newCount))
-	ret.Count = newCount
+	if psr.Count != 0 {
```
Comment (gabesaba) [inline pkg/workload/workload.go:173]:
```suggestion
	if psr.Count == 0 || psr.Count == newCount {
	  return psr
	}
```
is it safe to do this guard clause (which would be placed at the top of the function, before the copy)? i.e. do any callers modify this object, outside of ScaledTo?

File: pkg/scheduler/flavorassigner/flavorassigner.go [hunk 5]
```diff
@@ -109,8 +109,13 @@ func (a *Assignment) ToAPI() []kueue.PodSetAssignment {
 func (a *Assignment) TotalRequestsFor(wl *workload.Info) resources.FlavorResourceQuantities {
```
Comment (gabesaba) [inline pkg/scheduler/flavorassigner/flavorassigner.go:109]: Please add a comment indicating that in the case of `PartialAdmission`, we scale the returned `Requests`.

**Comment by trasc** [comment]
@gabesaba @mimowo is there anything else we should do on this?

File: pkg/scheduler/flavorassigner/flavorassigner.go (hunk 3 above)
Comment (mimowo) [reply pkg/scheduler/flavorassigner/flavorassigner.go:119]: I agree that moving the check into `ScaledTo` is preferred. It matches my expectations on how the function should behave (safe and performant).

**Comment by mimowo** [comment]
I support the ask in [comment](https://github.com/kubernetes-sigs/kueue/pull/2826#discussion_r1719937771).

File: pkg/scheduler/scheduler.go [hunk 6]
```diff
@@ -489,9 +489,12 @@ func (s *Scheduler) getAssignments(log logr.Logger, wl *workload.Info, snap *cac
 	if wl.CanBePartiallyAdmitted() {
 		reducer := flavorassigner.NewPodSetReducer(wl.Obj.Spec.PodSets, func(nextCounts []int32) (*partialAssignment, bool) {
 			assignment := flvAssigner.Assign(log, nextCounts)
-			if assignment.RepresentativeMode() == flavorassigner.Fit {
```
Comment (mimowo) [inline pkg/scheduler/scheduler.go:492]: Please reverted formatting changes if not needed (to miminize distractions).

**Comment by mimowo** [comment]
Could you describe what the scenario is fixed here, and what is the consequence from the user perspective when it happens? 

Please update the release note with a short description of the problematic scenario. 

It will also help us to guide the decision about cherry-picking.

**Comment by mimowo** [comment]
@gabesaba is it fair to close the original issue https://github.com/kubernetes-sigs/kueue/issues/2799 when this PR is merged?

File: pkg/scheduler/scheduler.go (hunk 6 above)
Comment (trasc) [reply pkg/scheduler/scheduler.go:492]: there is no reason the call `RepresentativeMode` twice

File: pkg/scheduler/flavorassigner/flavorassigner.go (hunk 3 above)
Comment (trasc) [reply pkg/scheduler/flavorassigner/flavorassigner.go:119]: `ScaleTo` is now checking if the count is different but for it's own purpose (to skip the actual scaling), having it also skip the cloning it's odd for me.  As well as cloning when it's not needed.

**Comment by trasc** [comment]
> @trasc Could you describe what the scenario is fixed here, and what is the consequence from the user perspective when it happens?
> 
> Please update the release note with a short description of the problematic scenario.
> 
> It will also help us to guide the decision about cherry-picking.

The scenario is `preemption during partial admission`.

**Comment by mimowo** [comment]
> The scenario is `preemption during partial admission`.

Can you provide a little bit more details? In particular: is the preemption not working at all / erroring / panicing / or working sub-optimally.

**Comment by mimowo** [comment]
/reopen
misclicked by mistake

File: pkg/scheduler/scheduler.go (hunk 6 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go:492]: I would suggest opening a dedicated cleanup PR, doesn't see to have anything to do with the fix.

Comment (trasc) [reply pkg/scheduler/scheduler.go]: done #3078

File: pkg/scheduler/flavorassigner/flavorassigner.go [hunk 7]
```diff
@@ -106,11 +106,18 @@ func (a *Assignment) ToAPI() []kueue.PodSetAssignment {
...
 }
 
+// TotalRequestsFor - returns the total quota needs of the wl, taking into account the potential
+// scaling needed in case of partial admission.
 func (a *Assignment) TotalRequestsFor(wl *workload.Info) resources.FlavorResourceQuantities {
 	usage := make(resources.FlavorResourceQuantities)
 	for i, ps := range wl.TotalRequests {
+		// in case of partial admission scale down the quantity
+		aps := a.PodSets[i]
+		if aps.Count != ps.Count {
```
Comment (mimowo) [inline pkg/scheduler/flavorassigner/flavorassigner.go:116]: Please drop this check, as suggested in the [comment](https://github.com/kubernetes-sigs/kueue/pull/2826/files#r1719937771) it is not necessary as `ScaledTo` already takes care of it.

Comment (trasc) [reply pkg/scheduler/flavorassigner/flavorassigner.go:116]: `ScaledTo` need to do that after cloning the input , otherwise it will need to return a clone or the original depending on some opaque logic. 

At least for now `aps.Count != ps.Count` it's very unlikely to happen , the feature is supported by batch/Job only, additionally potential new frameworks supporting this will only allow one podSet to have a variable count, therefore by keeping this we avoid unnecessary allocations.

Comment (mimowo) [reply pkg/scheduler/flavorassigner/flavorassigner.go:116]: I think it is a premature optimization. Clean code is more important in this case that the allocation.

Comment (trasc) [reply pkg/scheduler/flavorassigner/flavorassigner.go:116]: Unfortunately we need a clone every time we are scaling, otherwise we end up mutating the `Info.TotalRequests` that is used to re-queue the workload.

- We could ignore this aspect but we it could have surprising and very hard to debug side effects in the future.
- We could attempt to restore the scaling before re-queuing.

But any of this options are more complex or harder to follow the the current approach.

**Comment by mimowo** [comment]
> The scenario is preemption during partial admission.

I'm testing locally the impact of the bug and it seems to go beyond preemption. 

For example:
1. I have a CQ allowing for 9 pods
2. I created 2 small jobs, each consuming 3 pods, so 6 pods total. 
3. a big Job comes in requesting 9 pods, but using partial admission to say min 3 pods
4. 3 pods are created (correctly), but the CQ misreports usage as 15 units (6 + 9).
5. When, the small jobs are deleted (or finished), the big Job continues to use 3 pods, but reports consuming 9 resources
6. I create new small jobs requesting 3 units which should fit in, but they are suspended

I'm yet going to understand the scope of the problem, but it seems serious enough to justify cherry-picking.

**Comment by trasc** [comment]
> > The scenario is preemption during partial admission.
> 
> I'm testing locally the impact of the bug and it seems to go beyond preemption.
> 
> For example:
> 
> 1. I have a CQ allowing for 9 pods (preemption disabled completely)
> 2. I created 2 small jobs, each consuming 3 pods, so 6 pods total.
> 3. a big Job comes in requesting 9 pods, but using partial admission to say min 3 pods
> 4. 3 pods are created (correctly), but the CQ misreports usage as 15 units (6 + 9).
> 5. When, the small jobs are deleted (or finished), the big Job continues to use 3 pods, but reports consuming 9 resources
> 6. I create new small jobs requesting 3 units which should fit in, but they are suspended
> 
> I'm yet going to determine the scope of the problem and fix, but it seems serious enough to justify cherry-picking.

I think this is be a different issue. Just open the issue in GH and feel free to assign it to me.

**Comment by mimowo** [comment]
Regarding the fix here I played a bit more, and observed, that the feature generally worked before (no panics, no errors), but there are differences in some scenarios, and they are really hard for me to briefly (also the other issue is interfering to test properly, because the other issue is also present with preemption enabled). 

Still, IIUC the culprit for the issue is wrong calculation of resources requested by the incoming workload. I would like to capture this in the release note as below.
```
/release-note-edit
```release-note
Fix some scenarios for partial admission which are affected by wrong calculation of resources
used by the incoming workload which is partially admitted and preempting.
```

Going forward it would be super helpful to have an integration test(s) for this feature, otherwise it is hard to judge how the unit tests translate into the e2e behavior, imo.

Regarding the cherry-pick, no strong view here, but I think we don't need to, given that we don't have customers / users affected by the issue, or demanding the fix. Additionally, the other issue opened above still interferes to fully evaluate the fix. We can re-evaluate cherry-picking them together, or when we have users demanding the fix.

**Comment by mimowo** [comment]
LGTM, except for the point raised [here](https://github.com/kubernetes-sigs/kueue/pull/2826#discussion_r1766411786), but I can accept as is, just waiting a bit for @alculquicondor in case he has something to add or other ideas to improve.

File: pkg/scheduler/flavorassigner/flavorassigner.go (hunk 7 above)
Comment (alculquicondor) [reply pkg/scheduler/flavorassigner/flavorassigner.go:116]: Right.
I'm ok with keeping the optimization.
