### PR TITLE
[Flake] Add TerminationGracePeriod when applicable for tests

### LINKED ISSUE #4626: Flaky Test: LeaderWorkerSet integration when LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy
**What happened**:

`End To End Suite: kindest/node:v1.32.0: [It] LeaderWorkerSet integration when LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy` accidentally failed in CI

```shell
{Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/leaderworkerset_test.go:409 with:
Expected
    <int32>: 2
to equal
    <int32>: 1 failed [FAILED] Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/leaderworkerset_test.go:409 with:
Expected
    <int32>: 2
to equal
    <int32>: 1
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/leaderworkerset_test.go:418 @ 03/16/25 04:32:08.556

There were additional failures detected after the initial failure. These are visible in the timeline
}
```

**What you expected to happen**:

no errors

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/4625/pull-kueue-test-e2e-main-1-32/1901125782999142400

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
We have faced a lot of flakiness lately, possibly due to high load on test infra, thus increased timeouts.
Add TerminationGracePeriod when applicable for tests to decrease pod deletion waiting time and possible timeouts.

#### Which issue(s) this PR fixes:

Fixes #4626

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/singlecluster/leaderworkerset_test.go [hunk 1]
```diff
@@ -455,6 +460,7 @@ var _ = ginkgo.Describe("LeaderWorkerSet integration", func() {
 					Size(3).
 					Replicas(2).
 					RequestAndLimit(corev1.ResourceCPU, "200m").
+					TerminationGracePeriod(1).
```
Comment (mbobrovskyi) [inline test/e2e/singlecluster/leaderworkerset_test.go:463]: Please add also to LeaderTemplate.

Comment (mbobrovskyi) [reply test/e2e/singlecluster/leaderworkerset_test.go:463]: Ah, I see we have it twice. I think this is not needed.

File: test/e2e/multikueue/e2e_test.go [hunk 2]
```diff
@@ -587,6 +588,7 @@ var _ = ginkgo.Describe("MultiKueue", func() {
 					Image(util.E2eTestAgnHostImage, util.BehaviorWaitForDeletion). // Give it the time to be observed Active in the live status update step.
 					Parallelism(2).
 					RequestAndLimit(corev1.ResourceCPU, "1").
+					TerminationGracePeriod(1).
```
Comment (mimowo) [inline test/e2e/multikueue/e2e_test.go:591]: I think we cannot do this here, as we later expect the Workload to be successful: https://github.com/kubernetes-sigs/kueue/pull/4660/files#diff-5dcb842cd0d9d77809e502564dd2fa3e151d3ad48945f7075dc6aeeed483852bR624

This would risk flaking again.

Comment (mimowo) [reply test/e2e/multikueue/e2e_test.go:591]: Ah, maybe we can, because we call `WaitForActivePodsAndTerminate`, and so we terminate the pods without deleting actually.

**Comment by mimowo** [comment]
/lgtm
/approve
Ok, I think all the places look safe. Let's see how it works in practice.

**Comment by mimowo** [comment]
/cherry-pick release-0.10 release-0.9
There are probably some conflicts, so please prepare manually if this fails.
