### PR TITLE
Fix the flake issue for Ray integration tests

### LINKED ISSUE #10170: RayCluster with elastic jobs via workload-slices support Should support scheduling pending workload after freeing capacity on scale-down
**Which test is flaking?**:

RayCluster Controller Suite: [It] RayCluster with elastic jobs via workload-slices support Should support scheduling pending workload after freeing capacity on scale-down [slow] 

**Link to failed CI job or steps to reproduce locally**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-integration-release-0-15/2038253294379339776

**Failure message or logs**:
```
{ failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go:932 with:
Expected success, but got an error:
    <*errors.StatusError | 0xc000c6fcc0>: 
    Operation cannot be fulfilled on rayclusters.ray.io "raycluster-a": the object has been modified; please apply your changes to the latest version and try again
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Operation cannot be fulfilled on rayclusters.ray.io \"raycluster-a\": the object has been modified; please apply your changes to the latest version and try again",
            Reason: "Conflict",
            Details: {Name: "raycluster-a", Group: "ray.io", Kind: "rayclusters", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 409,
        },
    }
In [It] at: /home/prow/go/src/kubernetes-sigs/kueue/test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go:933 @ 03/29/26 14:13:11.51
}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?
/kind bug
/kind flake

#### Which issue(s) this PR fixes:

Fixes #10170

#### Special notes for your reviewer:

We need to fetch the new version of the RayCluster when retrying on conflict. Otherwise the request fails on each retry attempts because it still has the old ResourceVersion.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go [hunk 1]
```diff
@@ -928,6 +928,7 @@ var _ = ginkgo.Describe("RayCluster with elastic jobs via workload-slices suppor
 
 		ginkgo.By("scale-down raycluster-a to make room for raycluster-b")
 		gomega.Eventually(func(g gomega.Gomega) {
+			g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(testRayClusterA), testRayClusterA)).Should(gomega.Succeed())
```
Comment (mbobrovskyi) [inline test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go:931]: I think we can loose key in one of failed iterations.

Comment (mszadkow) [reply test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go:931]: which key?
getting latest version of the object is correct approach anyway

Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go:931]: > I think we can loose key in one of failed iterations.

I'm don't know how losing the key could happen - doesn't see possible in this test really.

Also this is what we do in other places in the test: L916: `g.Expect(k8sClient.Get(ctx, client.ObjectKeyFromObject(testRayClusterB), testRayClusterB)).Should(gomega.Succeed())` or L940.
Also in other tests, for example: https://github.com/kubernetes-sigs/kueue/blob/e39ca08fcdc7ed74cd8adce589b631cc6b650877/test/e2e/certmanager/visibility_test.go#L87

I agree we mix the strategies - sometimes precompute the key and sometimes re-compute inside Eventually. 

Both approaches have trade-offs: 
- pre-computing saves a tiny bit of execution time 
- pre-computing requires more lines of code.

Functionally, I don't see any difference.

Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go:931]: Ah, I see we have the same strategy in this test case. Than I'm ok with it.
