### PR TITLE
Fix: StatefulSet integration when StatefulSet created should allow to scale up after scale down to zero

### LINKED ISSUE #7390: [flaky test]  StatefulSet integration when StatefulSet created should allow to scale up after scale down to zer
/kind flake

**What happened**:
failures 

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7389/pull-kueue-test-e2e-main-1-32/1981745144096886784
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7205/pull-kueue-test-e2e-main-1-34/1975862374690721792

**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:

```
End To End Suite: kindest/node:v1.32.8: [It] StatefulSet integration when StatefulSet created should allow to scale up after scale down to zero expand_less	58s
{Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/statefulset_test.go:339 with:
Expected
    <int32>: 0
to equal
    <int32>: 3 failed [FAILED] Timed out after 45.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/statefulset_test.go:339 with:
Expected
    <int32>: 0
to equal
    <int32>: 3
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/statefulset_test.go:340 @ 10/24/25 15:46:46.084
}
```

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

The loose ReadyReplicas < 3 check allowed scaling up before workload deletion completed, causing a race condition. This fix ensures the scale-down is completely finished before attempting scale-up.

#### Which issue(s) this PR fixes:

Fixes #7390 

#### Special notes for your reviewer:

I ran the test over 500 times successfully with the fix.

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug for the StatefulSet integration that the scale up could get stuck if
triggered immediately after scale down to zero.
```

### CODE REVIEW

File: test/e2e/singlecluster/statefulset_test.go [hunk 1]
```diff
@@ -314,16 +314,19 @@ var _ = ginkgo.Describe("StatefulSet integration", func() {
 				}, util.Timeout, util.Interval).Should(gomega.Succeed())
 			})
 
-			ginkgo.By("Wait for ReadyReplicas < 3", func() {
+			ginkgo.By("Wait for ReadyReplicas to be zero", func() {
```
Comment (mimowo) [inline test/e2e/singlecluster/statefulset_test.go]: I think this change is not essential, what is essential that we wait until the Workload is deleted (below). However, the user may not check that, we don't have any validation for that.

So, I think this flaky test is showing us that we have a production issue.

I'm ok with the "fix" as a pragmatic change to make the test not flaky, but we need to fix the underlying bug in the integration. I think we may need to use "prebuiltworkloads" for that as we do for LWS. 

cc @mbobrovskyi

Comment (mimowo) [reply test/e2e/singlecluster/statefulset_test.go]: So I think what heppens is:
1. we trigger scale down of StatefulSet from 3 to 0
2. StatefulSet has no longer any pods, but the Workload still exists (unlikely by possible)
3. before the workload is deleted we scale up the StatefulSet, and it creates the first pod
4. the pod is attached to the old Workload
5. the old Workload is deleted, thus and thus the Pod, no new Workload is created (somehow)

And essentially the scale up is stuck. This condition is very unlikely because in (2.) the workload would usually be already deleted.

Comment (mimowo) [reply test/e2e/singlecluster/statefulset_test.go]: I think an alternative fix is to check in the webhook not only if status.ReadyReplicas is 0, but if also the Workload is deleted. We could detect that for example using the indexer from the webhook. Not the cleanest approach, but should work.

Another alternative would be to somehow prevent (4.) - attaching the new pod to the old workload, and wait for the deletion of the old workload first, but it might be harder (not sure).

EDIT: even if (1.) is not cleanest it should work, and I think it is good to try, rather than swiping the problem under the rug by tweaking the test.

Comment (mbobrovskyi) [reply test/e2e/singlecluster/statefulset_test.go]: I think we should keep this test. We intentionally created it to ensure that this case works correctly.

Comment (mimowo) [reply test/e2e/singlecluster/statefulset_test.go]: exactly

Comment (IrvingMg) [reply test/e2e/singlecluster/statefulset_test.go]: Got it. I'll investigate the error further to fix the issue while leaving the test as it is

Comment (IrvingMg) [reply test/e2e/singlecluster/statefulset_test.go]: I've applied the fix in the webhook to check whether the workload is deleted. I ran over 250 successful repetitions of the test.

File: pkg/controller/jobs/statefulset/statefulset_webhook.go
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go:1]: Could you please add unit test?

File: pkg/controller/jobs/statefulset/statefulset_webhook.go [hunk 2]
```diff
@@ -174,8 +174,23 @@ func (wh *Webhook) ValidateUpdate(ctx context.Context, oldObj, newObj runtime.Ob
...
+			workloadName := GetWorkloadName(oldStatefulSet.GetName())
+			wlKey := client.ObjectKey{Namespace: oldStatefulSet.GetNamespace(), Name: workloadName}
+			var wl kueue.Workload
+			err := wh.client.Get(ctx, wlKey, &wl)
+			if client.IgnoreNotFound(err) != nil {
+				return nil, err
+			}
+			if err == nil {
+				allErrs = append(allErrs, field.Forbidden(replicasPath, "workload from previous scale-down is still being deleted"))
+			}
```
Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go]: I don't think so we should return both errors. Probably it should be else case, right?

Comment (mbobrovskyi) [inline pkg/controller/jobs/statefulset/statefulset_webhook.go]:
```suggestion
			if err := wh.client.Get(ctx, wlKey, &wl); client.IgnoreNotFound(err) != nil {
				return nil, err
			} else if err == nil {
				allErrs = append(allErrs, field.Forbidden(replicasPath, "workload from previous scale-down is still being deleted"))
			}
```
nit

Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go]: Sorry, not sure what you mean. Do you mean the change you mentioned below?

Comment (mbobrovskyi) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go]: We should find the workload only if `newStatefulSet.Status.Replicas == 0`, so this selected lines should be placed in the else clause.

File: pkg/controller/jobs/statefulset/statefulset_webhook.go
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go:1]: Done.

File: pkg/controller/jobs/statefulset/statefulset_webhook.go (hunk 2 above)
Comment (IrvingMg) [reply pkg/controller/jobs/statefulset/statefulset_webhook.go]: Done.

**Review by mbobrovskyi — APPROVED** [review]
/lgtm
Thank you!

**Comment by mimowo** [comment]
We need a release note for this one, ptal
/release-note-edit
```release-note
Fix the bug for the StatefulSet integration that the scale up could get stuck if
triggered immediately after scale down to zero.
```

**Review by mimowo — COMMENTED** [review]
Looks great, thank you 👍 
/approve
/cherrypick release-0.14
/cherrypick release-0.13
