### PR TITLE
Set DefaultRequeuingBackoffBaseSeconds to 60s.

### LINKED ISSUE #2215: Make backoffBaseSeconds default consistent with timeout in waitForPodsReady
**What would you like to be cleaned**:

Increase the default for waitForPodsReady to 5-10 minutes. 

**Why is this needed**:

Currently Kueue retries to run a workload almost immediately after it failed to start it for 5 minutes. If the situation was not favorable for the workload for 5 minutes (there was no space in the cluster, cluster autoscaler failed to deliver nodes, the workload is crashing immediately after start etc) it is unlikely to improve just after 10 or 20 seconds. 

cc: @tenzen-y @mimowo

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Set DefaultRequeuingBackoffBaseSeconds to 60s.

#### Which issue(s) this PR fixes:

Fixes #2215

#### Does this PR introduce a user-facing change?

```release-note
Increased the default value in the `.waitForPodsReady.requeuingStrategy.backoffBaseSeconds` to 60

ACTION REQUIRED: You can configure `.waitForPodsReady.requeuingStrategy.backoffBaseSeconds` as needed.
```

### CODE REVIEW

**Review by trasc — COMMENTED** [review]
/lgtm

File: apis/config/v1beta1/configuration_types.go [hunk 1]
```diff
@@ -256,7 +256,7 @@ type RequeuingStrategy struct {
 	// BackoffBaseSeconds defines the base for the exponential backoff for
 	// re-queuing an evicted workload.
 	//
-	// Defaults to 10.
+	// Defaults to 60s.
```
Comment (mimowo) [inline apis/config/v1beta1/configuration_types.go:259]:
```suggestion
	// Defaults to 60.
```
:)

**Review by mimowo — COMMENTED** [review]
LGTM

File: apis/config/v1beta1/configuration_types.go (hunk 1 above)
Comment (mbobrovskyi) [reply apis/config/v1beta1/configuration_types.go]: Fixed

**Review by tenzen-y — COMMENTED** [review]
Could you update document as well?

- https://github.com/kubernetes-sigs/kueue/blob/0db23a7d8431b25ea77281fc6b7504db247c34dc/pkg/controller/core/workload_controller.go#L458
- https://github.com/kubernetes-sigs/kueue/tree/main/keps/1282-pods-ready-requeue-strategy#design-details

**Review by tenzen-y — COMMENTED** [review]
Could you also update there: https://github.com/kubernetes-sigs/kueue/blob/3e2ef02e4c000a88bd46c0aec34ad3782c341d64/keps/1282-pods-ready-requeue-strategy/README.md?plain=1#L240-L244?

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Increased the default value in the ".waitForPodsReady.requeuingStrategy.backoffBaseSeconds" to 60
```

**Comment by alculquicondor** [comment]
/release-note-edit

```release-note
Increased the default value in the `.waitForPodsReady.requeuingStrategy.backoffBaseSeconds` to 60

ACTION REQUIRED: You can configure `.waitForPodsReady.requeuingStrategy.backoffBaseSeconds` as needed.
```

**Comment by mbobrovskyi** [comment]
@tenzen-y fixed. Thanks

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve
