### PR TITLE
Increase the timeout for waiting for the Deployment update to start and check if ObservedGeneration changed.

### LINKED ISSUE #9313: [flaky test] MultiKueue when The connection to a worker cluster is unreliable Should update the cluster status to reflect the connection state
**Which test is flaking?**:
MultiKueue when The connection to a worker cluster is unreliable Should update the cluster status to reflect the connection state
**Link to failed CI job or steps to reproduce locally**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/9309/pull-kueue-test-e2e-multikueue-release-0-15/2023697194514649088
**Failure message or logs**:
```
End To End MultiKueue Suite: kindest/node:v1.35.0: [It] MultiKueue when The connection to a worker cluster is unreliable Should update the cluster status to reflect the connection state expand_less	1m39s
{Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/e2e.go:258 with:
Expected
    <v1.Time>: {
        Time: 2026-02-17T10:03:26Z,
    }
not to equal
    <v1.Time>: {
        Time: 2026-02-17T10:03:26Z,
    } failed [FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/util/e2e.go:258 with:
Expected
    <v1.Time>: {
        Time: 2026-02-17T10:03:26Z,
    }
not to equal
    <v1.Time>: {
        Time: 2026-02-17T10:03:26Z,
    }
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:1407 @ 02/17/26 10:11:06.447

There were additional failures detected after the initial failure. These are visible in the timeline
}
```

**Anything else we need to know?**:

I think this is likely a new problem related to https://github.com/kubernetes-sigs/kueue/pull/9275. 

Maybe we should just give it more time than 10s?

Or maybe the rollout started to progress in exactly the same second? In that case maybe instead of checking time we should check the `ObservedGeneration` for status

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:
Increase the timeout for waiting for the Deployment update to start and check if ObservedGeneration changed.

#### Which issue(s) this PR fixes:

Fixes #9313

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/util/e2e.go [hunk 1]
```diff
@@ -240,6 +240,7 @@ func UpdateDeploymentAndWaitForProgressing(ctx context.Context, k8sClient client
 		ginkgo.GinkgoLogr.Info("Deployment status condition before the restart", "type", deploymentCondition.Type, "status", deploymentCondition.Status, "reason", deploymentCondition.Reason)
 	}, Timeout, Interval).Should(gomega.Succeed())
 
+	beforeObservedGeneration := deployment.Status.ObservedGeneration
 	beforeUpdateTime := deploymentCondition.LastUpdateTime
```
Comment (mimowo) [inline test/util/e2e.go]: Should we also add waiting to cross the full second bundary here, ptal https://github.com/kubernetes-sigs/kueue/issues/9313#issuecomment-3914335676?

Comment (mbobrovskyi) [reply test/util/e2e.go]: Done.

File: test/util/e2e.go [hunk 2]
```diff
@@ -249,13 +250,18 @@ func UpdateDeploymentAndWaitForProgressing(ctx context.Context, k8sClient client
 		g.Expect(k8sClient.Update(ctx, deployment)).To(gomega.Succeed())
 	}, Timeout, Interval).Should(gomega.Succeed())
 
+	// Wait for the next second to ensure the Progressing process has started.
+	// Otherwise, the update may happen too quickly and cause a flake.
+	WaitForNextSecond(beforeUpdateTime)
```
Comment (mimowo) [inline test/util/e2e.go]: I think we should wait before triggering the update. Otherwise it is possible the `deploymentCondition.LastUpdateTime` will still be in the previous second, we will just check it in the new second.

**Comment by mimowo** [comment]
I think this is also likely to fix https://github.com/kubernetes-sigs/kueue/issues/9301, so we may consider "Fixes #9301"

File: test/util/e2e.go (hunk 2 above)
Comment (mimowo) [reply test/util/e2e.go]: if `deploymentCondition.LastUpdateTime == beforeUpdateTime, then it does not matter how long you want afterwards

Comment (mimowo) [reply test/util/e2e.go]: /hold

Comment (mimowo) [reply test/util/e2e.go]: Ok, I spent some time thinking about it, this looks correct, wdyt? 

```golang
// Wait for the next second to ensure the Progressing process is started on the next full second
var beforeUpdateTime time.Time
var beforeObservedGeneration time.Time

// Apply changes and update Deployment.
gomega.Eventually(func(g gomega.Gomega) {
  g.Expect(k8sClient.Get(ctx, key, deployment)).To(gomega.Succeed())
  deploymentCondition := FindDeploymentCondition(deployment, appsv1.DeploymentProgressing)
  g.Expect(deploymentCondition).NotTo(gomega.BeNil())
  beforeUpdateTime := deploymentCondition.LastUpdateTime
  beforeObservedGeneration = deploymentt.Status.ObservedGeneration
  
  // wait up to full second to ensure the update has a new (different) timestamp
  WaitForNextSecond(beforeUpdateTime)
  applyChanges(deployment)
   g.Expect(k8sClient.Update(ctx, deployment)).To(gomega.Succeed())
}, Timeout, Interval).Should(gomega.Succeed())

// Wait for the Deployment update to be in progress.
gomega.Eventually(func(g gomega.Gomega) {
  g.Expect(k8sClient.Get(ctx, key, deployment)).To(gomega.Succeed())
  g.Expect(deployment.Status.ObservedGeneration).NotTo(gomega.Equal(beforeObservedGeneration))
  deploymentCondition := FindDeploymentCondition(deployment, appsv1.DeploymentProgressing)
  g.Expect(deploymentCondition).NotTo(gomega.BeNil())
  g.Expect(deploymentCondition.LastUpdateTime).NotTo(gomega.Equal(beforeUpdateTime))
}, LongTimeout, Interval).Should(gomega.Succeed())
```

Comment (mimowo) [reply test/util/e2e.go]: but I think we could also just replace checking `LastUpdateTime` with relying on `ObservedGeneration`. 

This would simplify the check a lot, and avoid the custom WaitForNextSecond.

The only drawback might be is another process / controller updates the deployment spec in the meanwhile, but that should not happen in our tests ( at least I don't know about the case). The tests which update configuration are always sequential

Comment (mimowo) [reply test/util/e2e.go]: If there are concurrent modifications of Kueue deployment in e2e tests then we have a bigger problem, so honestly I would just simplify the check to something like
```golang
var beforeObservedGeneration time.Time

// Apply changes and update Deployment.
gomega.Eventually(func(g gomega.Gomega) {
  g.Expect(k8sClient.Get(ctx, key, deployment)).To(gomega.Succeed())
  deploymentCondition := FindDeploymentCondition(deployment, appsv1.DeploymentProgressing)
  g.Expect(deploymentCondition).NotTo(gomega.BeNil())
  beforeObservedGeneration = deploymentt.Status.ObservedGeneration
  
  applyChanges(deployment)
   g.Expect(k8sClient.Update(ctx, deployment)).To(gomega.Succeed())
}, Timeout, Interval).Should(gomega.Succeed())

// Wait for the Deployment update to be in progress.
gomega.Eventually(func(g gomega.Gomega) {
  g.Expect(k8sClient.Get(ctx, key, deployment)).To(gomega.Succeed())
  g.Expect(deployment.Status.ObservedGeneration).NotTo(gomega.Equal(beforeObservedGeneration))
  deploymentCondition := FindDeploymentCondition(deployment, appsv1.DeploymentProgressing)
  g.Expect(deploymentCondition).NotTo(gomega.BeNil())
}, LongTimeout, Interval).Should(gomega.Succeed())
```

Comment (mimowo) [reply test/util/e2e.go]: Actually, I synced with @mbobrovskyi on priv. We may have in this code an unlikely scenario when there is a pending deployment status update, which will bump the generation before our update is respected. To make sure there are no pending status we may check that `generation = status.observedGeneration` before the code above.

Comment (mbobrovskyi) [reply test/util/e2e.go]: Done

**Comment by mimowo** [comment]
Thank you 👍 
/unhold
/lgtm
/approve
/cherrypick release-0.16
/cherrypick release-0.15
