### PR TITLE
Count inflight workload as pending 

### LINKED ISSUE #1937: In some scenarios the ClusterQueue status shows wrong count for PendingWorkloads
**What happened**:

The count for the number of pending workloads in ClusterQueue is down-counted by one.
This stays like that for a long time.

**What you expected to happen**:

The number of pending workloads correspond to reality. 

**How to reproduce it (as minimally and precisely as possible)**:

Create the following setup:

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  queueingStrategy: StrictFIFO
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue"
spec:
  clusterQueue: "cluster-queue"
```

Create the "blocker" job that gets admitted:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: blocker-job-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 9
  completions: 9
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["3600s"]
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Never
```

Then create the sample job:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["1800s"]
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Never
```

Now, the sample job is "blocked", and it is pending, `kubectl describe workload` returns:
```
Status:
  Conditions:
    Last Transition Time:  2024-04-02T12:46:27Z
    Message:               couldn't assign flavors to pod set main: insufficient unused quota for cpu in flavor default-flavor, 3 more needed
    Reason:                Pending
    Status:                False
    Type:                  QuotaReserved
Events:
  Type    Reason   Age                   From             Message
  ----    ------   ----                  ----             -------
  Normal  Pending  116s (x25 over 116s)  kueue-admission  couldn't assign flavors to pod set main: insufficient unused quota for cpu in flavor default-flavor, 3 more needed
```
However, the workload is not shown in the status of the ClusterQueue, `clusterQueue.status.pendingWorkloads=0`.

**Anything else we need to know?**:

I suspect this is because the number of pending workloads is taken from the cache, which decrements by 1 on Pop (from the heap). Then, at the end of each cycle it returns to the cache by RequeueIfNotPresent. So, it might flake.

I suppose this is not so much of an issue for BestEffortFIFO, because in that case the workload is moved to inadmissibleWorkloads queue, so it is not continuously popped.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #1937

#### Does this PR introduce a user-facing change?

```release-note
Properly count the number of pending workloads in StrictFIFO queue, when the first workload cannot be admitted.
```

### CODE REVIEW

**Comment by mimowo** [comment]
/hold 
Experimentation for now

**Comment by mimowo** [comment]
/hold cancel
Ready for review

File: pkg/queue/cluster_queue_impl.go [hunk 1]
```diff
@@ -153,6 +157,7 @@ func (c *clusterQueueBase) Delete(w *kueue.Workload) {
 	key := workload.Key(w)
```
Comment (alculquicondor) [inline pkg/queue/cluster_queue_impl.go:157]: 🤔 did we forget to lock the mutex? Or is it locked by all callers?

File: pkg/queue/cluster_queue_impl.go [hunk 2]
```diff
@@ -235,7 +247,11 @@ func (c *clusterQueueBase) Pending() int {
 }
 
 func (c *clusterQueueBase) PendingActive() int {
```
Comment (alculquicondor) [inline pkg/queue/cluster_queue_impl.go:249]: Is this ever called without locking?

Comment (mimowo) [reply pkg/queue/cluster_queue_impl.go:249]: No, it is called from two places:
- `cq.Pending()` - this is using read lock scoped to the cq
- `manager.reportPendingWorkloads()`, but all invocations of this function take manager lock, which is broader range than cq

File: pkg/queue/cluster_queue_impl.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/queue/cluster_queue_impl.go:157]: can we rename it to `delete` instead?

Comment (alculquicondor) [reply pkg/queue/cluster_queue_impl.go:157]: Actually, it's also called from the queue Manager, via the ClusterQueue interface.

But we already access the manager through a mutex. Now I'm wondering why we added a dedicated mutex to the ClusterQueue.

Comment (alculquicondor) [reply pkg/queue/cluster_queue_impl.go:157]: Oh it was for the status snapshoter https://github.com/kubernetes-sigs/kueue/pull/1069

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

File: pkg/queue/cluster_queue_impl.go (hunk 1 above)
Comment (mimowo) [reply pkg/queue/cluster_queue_impl.go:157]: That's right, sorry for confusion, somehow I missed it in vs-code when using the "all references" option.

IIRC we added the mutex to ClusterQueue so that the `Snapshot` operation (needed for visibility) only requires cq-scoped mutex, and this operation could be expensive.

**Comment by tenzen-y** [comment]
@alculquicondor @mimowo Isn't this a bug?

File: pkg/queue/cluster_queue_impl.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/queue/cluster_queue_impl.go:157]: I suppose there might still be problematic scenarios, for example, the event handlers triggering a Workload deletion while the snapshoter is running.

So we should always be locking the mutex. However, maybe we can get rid of the snapshotter in the near future in favor of the visibility API.

Comment (mimowo) [reply pkg/queue/cluster_queue_impl.go:157]: > I suppose there might still be problematic scenarios, for example, the event handlers triggering a Workload deletion while the snapshoter is running.

The main purpose of the cs-scoped mutex is to make sure the heap structure can be iterated and copied so that we don't miss any element due to concurrent modifications.  

> So we should always be locking the mutex. 

yes

> However, maybe we can get rid of the snapshotter in the near future in favor of the visibility API.

I think we can get rid of the snapshotter that persists data in etcd, but the `Snapshot()` function itself is used by the visibility API to get consistent view of the workloads, so I don't see a way of dropping the cq-scoped mutex, unless:
- we use the manager-scoped mutex, but this would impact performance
- don't use mutex for `Snapshot()` at all, but this would impact consistency of results during updates

**Comment by mimowo** [comment]
> @alculquicondor @mimowo Isn't this a bug?

yes, it is, let me update the labels:

/kind-remove cleanup
/kind bug

**Comment by mimowo** [comment]
> Also, should we do cherry-pick to v0.6.

I would vote in favor of cherry-picking, the risk seems small. On the other hand it wasn't reported by users, but me when I was working on the feature: https://github.com/kubernetes-sigs/kueue/issues/1873, so may not be critical.

I checked that there is a small conflict with https://github.com/kubernetes-sigs/kueue/pull/1815, if we include #1815, then it cherry-picks without conflict.

**Comment by alculquicondor** [comment]
This doesn't seem urgent enough for a cherry-pick IMO

**Comment by tenzen-y** [comment]
Considering conflicts, I'm ok without cherry-pick.
