### PR TITLE
Start JobFramework controller and webhook on new CRDs availability

### LINKED ISSUE #2414: Add a watch for Ray and Training Operator CRDs
**What happened**:
When the Kueue component is installed before the Ray OR Training Operator, Kueue doesn't monitor RayCluster or PyTorchJob resources + any other [CRDs from the Training Operator.](https://github.com/kubeflow/training-operator/tree/master/manifests/base/crds)

When the user creates a RayCluster or PyTorchJob resources, Kueue doesn't control admission of those resources.

Logs:
>{"level":"info","ts":"2024-05-30T11:07:08.761740832Z","logger":"setup","caller":"jobframework/setup.go:69","msg":"No matching API in the server for job framework, skipped setup of controller and webhook","jobFrameworkName":"kubeflow.org/pytorchjob"}

**What you expected to happen**:
JobFramework Controller and Webhook should start/restart once required CRDs from Ray OR Training-Operator are available.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Kueue without the Ray or Training-Operator CRDs.
2. Check Kueue logs.

**Anything else we need to know?**:
Proposed Solution:
Add a watcher to controller and webhook, to start/restart in the event of availability of Ray OR Training-Operator CRDs.

I have a draft PR ready - still needs some work.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ChristianZaccaria**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add function to wait for API availability using the RESTMapper in controller manager.

This PR checks for availability of JobFramework integrations in the Kubernetes cluster before executing the action().

The function utilises the RESTMapper from the controller-runtime manager to verify the existence of the CRD by its GroupVersionKind (GVK). If one of the CRDs become available, the respective controller and webhook will start.

The user/dev will no longer be required to restart the Kueue pod to allow for integration on new CRDs available.

No restarts on the Kueue pod is performed.

#### Which issue(s) this PR fixes:

Fixes #2414 

#### Does this PR introduce a user-facing change?

```release-note
Detect and enable support for job CRDs installed after Kueue starts.
```

### CODE REVIEW

**Comment by ChristianZaccaria** [comment]
cc: @trasc thank you for your previous input on this.

File: pkg/controller/jobframework/setup.go [hunk 1]
```diff
@@ -94,6 +89,43 @@ func SetupControllers(mgr ctrl.Manager, log logr.Logger, opts ...Option) error {
...
+	}
+	var err error
+	for {
+		_, err = getRestMapping()
+		if err != nil {
+			select {
+			case <-ctx.Done():
+				log.Info(fmt.Sprint("Context cancelled!", "gvk", gvk))
+				return
+			case <-time.After(time.Second * 5):
```
Comment (trasc) [inline pkg/controller/jobframework/setup.go:120]: let's make this a package constant. When you do that add a comment describing how it is used. 

For me the value looks small, so maybe let't bring it up to 20s at least.

File: pkg/controller/jobframework/setup.go [hunk 2]
```diff
@@ -94,6 +89,43 @@ func SetupControllers(mgr ctrl.Manager, log logr.Logger, opts ...Option) error {
...
+        return fmt.Errorf("%s: unable to create webhook: %w", fwkNamePrefix, err)
+    }
+
+    return nil
+}
+
+func waitForAPI(ctx context.Context, mgr ctrl.Manager, log logr.Logger, gvk schema.GroupVersionKind, action func()) {
+	getRestMapping := func() (*meta.RESTMapping, error) {
+		return mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version)
+	}
```
Comment (trasc) [inline pkg/controller/jobframework/setup.go:111]: I don't think we need this , It's a one line function used once.

File: pkg/controller/jobframework/setup.go [hunk 3]
```diff
@@ -94,6 +89,43 @@ func SetupControllers(mgr ctrl.Manager, log logr.Logger, opts ...Option) error {
...
+	var err error
+	for {
+		_, err = getRestMapping()
```
Comment (trasc) [inline pkg/controller/jobframework/setup.go:114]:
```suggestion
	for {
		_, err := ......
```

File: pkg/controller/jobframework/setup.go [hunk 4]
```diff
@@ -94,6 +89,43 @@ func SetupControllers(mgr ctrl.Manager, log logr.Logger, opts ...Option) error {
 	})
 }
 
+func setupControllerAndWebhook(mgr ctrl.Manager, gvk schema.GroupVersionKind, fwkNamePrefix string, cb IntegrationCallbacks, opts ...Option) error {
+    if err := cb.NewReconciler(
+        mgr.GetClient(),
+        mgr.GetEventRecorderFor(fmt.Sprintf("%s-%s-controller", gvk.Kind, "managerName")), // Ensure managerName is defined or fetched
```
Comment (KPostOffice) [inline pkg/controller/jobframework/setup.go:95]: I think "managerName" should still come from options
```suggestion
        options := ProcessOptions(opts...)
        mgr.GetEventRecorderFor(fmt.Sprintf("%s-%s-controller", gvk.Kind, options.ManagerName)), // Ensure managerName is defined or fetched
```

File: pkg/controller/jobframework/setup.go [hunk 5]
```diff
@@ -67,24 +69,17 @@ func SetupControllers(mgr ctrl.Manager, log logr.Logger, opts ...Option) error {
...
 			}
-			if _, err = mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version); err != nil {
+			if _, err := mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version); err != nil {
 				if !meta.IsNoMatchError(err) {
 					return fmt.Errorf("%s: %w", fwkNamePrefix, err)
 				}
 				logger.Info("No matching API in the server for job framework, skipped setup of controller and webhook")
+				go waitForAPI(context.Background(), mgr, logger, gvk, func() {
+					log.Info(fmt.Sprintf("API now available, starting controller and webhook for %v", gvk))
+					setupControllerAndWebhook(mgr, gvk, fwkNamePrefix, cb, opts...)
```
Comment (KPostOffice) [inline pkg/controller/jobframework/setup.go:79]: One question here is what happens if a controller/webhook errors on startup? Should kueue kueue restart or should it log the error and continue on?

File: pkg/controller/jobframework/setup.go [hunk 6]
```diff
@@ -67,24 +69,17 @@ func SetupControllers(mgr ctrl.Manager, log logr.Logger, opts ...Option) error {
...
-					opts...,
-				).SetupWithManager(mgr); err != nil {
-					return fmt.Errorf("%s: %w", fwkNamePrefix, err)
-				}
-				if err = cb.SetupWebhook(mgr, opts...); err != nil {
-					return fmt.Errorf("%s: unable to create webhook: %w", fwkNamePrefix, err)
-				}
-				logger.Info("Set up controller and webhook for job framework")
-				return nil
+				setupControllerAndWebhook(mgr, gvk, fwkNamePrefix, cb, opts...)
```
Comment (KPostOffice) [inline pkg/controller/jobframework/setup.go:82]: Here as well, the previous behavior was to return an error

**Review by KPostOffice — COMMENTED** [review]
Nice, I tested this out on a cluster and it worked as expected for me

File: pkg/controller/jobframework/setup.go (hunk 5 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:79]: Originally, the error would be logged and we would continue on. - I wouldn't like to restart Kueue based on controller/webhook startup errors as in the event of consistent/repetitive errors on one framework would cause Kueue to never start. With that said, the waitForAPI() takes care of ensuring the API exists before starting the controller/webhook.

File: pkg/controller/jobframework/setup.go (hunk 6 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:82]: Correct me if I'm wrong, the current implementation will still return an error if encountered on startup of the controller/webhook.

File: pkg/controller/jobframework/setup.go (hunk 1 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:120]: You're right, the `5s` is too short, it was mainly for testing rapidly. Great idea on the package constant, will do, thank you!

**Comment by ChristianZaccaria** [comment]
Rebased

**Review by Ygnas — APPROVED** [review]
Works as expected.

File: pkg/controller/jobframework/setup.go [hunk 7]
```diff
@@ -35,6 +37,9 @@ var (
 	errFailedMappingResource = errors.New("restMapper failed mapping resource")
 )
 
+// APIRetryInterval is the duration to wait before retrying the API request.
```
[the remark this answers is not in the document]
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:40]: Hi Kevin, good question. I might be wrong, but I don't see great benefit on allowing this value to be configurable through Kueue config options.

Dev/Users will want the controller and webhook to start in a "reasonable" amount of time after the respective CRD becomes available.  - I'm not saying 20s is the right amount, it's something we could discuss, but I think making this value configurable for the dev/user to update to 1s or 5min could lead to inconsistent behaviour and harder to troubleshoot.

[the remark this answers is not in the document]
Comment (kannon92) [reply pkg/controller/jobframework/setup.go:40]: I’m not sure either. I just usually see constants and wonder if someone would want to tune this..

@tenzen-y wdyt?

[the remark this answers is not in the document]
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:40]: I'm actually going to change this to a `var` as I wish to add a test case for this. - Will have a new commit promptly.

**Comment by ChristianZaccaria** [comment]
Hi @alculquicondor, thanks for your previous input on issue https://github.com/kubernetes-sigs/kueue/issues/2414. This PR resolves the issue and includes a test case. Manual tests have been made and work as expected. Let me know if there's anything else I could do for this PR to be successfully merged. Thank you

**Comment by alculquicondor** [comment]
I'm unfortunately overwhelmed with reviews. I'll let @trasc take a pass, but note that he's currently on vacation.

**Comment by mbobrovskyi** [comment]
This PR also fix #2612.

**Comment by mbobrovskyi** [comment]
/release-not-edit

```release-not
Added logic to wait until the job framework API is available.
```

**Comment by mbobrovskyi** [comment]
/release-note-edit

```release-note
Added logic to wait until the job framework API is available.
```

File: pkg/controller/jobframework/setup.go [hunk 8]
```diff
@@ -99,6 +105,40 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+
+func (m *integrationManager) waitForAPI(ctx context.Context, mgr ctrl.Manager, log logr.Logger, gvk schema.GroupVersionKind, action func()) {
+	for {
+		m.mu.Lock()
+		_, err := mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version)
+		m.mu.Unlock()
+		if err != nil {
+			select {
+			case <-ctx.Done():
+				log.Info(fmt.Sprint("Context cancelled!", "gvk", gvk))
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/setup.go:131]: I don't think so this log will be useful.

File: pkg/controller/jobframework/setup.go [hunk 9]
```diff
@@ -99,6 +105,40 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+	m.enableIntegration(name)
+	return nil
+}
+
+func (m *integrationManager) waitForAPI(ctx context.Context, mgr ctrl.Manager, log logr.Logger, gvk schema.GroupVersionKind, action func()) {
+	for {
+		m.mu.Lock()
+		_, err := mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version)
+		m.mu.Unlock()
+		if err != nil {
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:128]: Make sure the error is logged. Can you paste here an example log line?

File: pkg/controller/jobframework/setup.go [hunk 10]
```diff
@@ -35,6 +38,13 @@ var (
 	errFailedMappingResource = errors.New("restMapper failed mapping resource")
 )
 
+var (
+	// APIRetryInterval is the duration to wait before retrying the API request.
+	APIRetryInterval = 20 * time.Second
+	// APIRetryMutex is the mutex used to safely access the APIRetryInterval.
+	APIRetryMutex sync.Mutex
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:45]: This mutex does not seem needed as the interval cannot be changed at runtime, just in tests.

File: pkg/controller/jobframework/setup.go [hunk 11]
```diff
@@ -35,6 +38,13 @@ var (
 	errFailedMappingResource = errors.New("restMapper failed mapping resource")
 )
 
+var (
+	// APIRetryInterval is the duration to wait before retrying the API request.
+	APIRetryInterval = 20 * time.Second
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:43]: Not need to export

**Comment by alculquicondor** [comment]
/release-note-edit
```
Detect and enable support for job CRDs installed after Kueue starts.
```

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Detect and enable support for job CRDs installed after Kueue starts.
```

File: pkg/controller/jobframework/setup.go [hunk 12]
```diff
@@ -35,6 +38,13 @@ var (
...
+	// APIRetryMutex is the mutex used to safely access the APIRetryInterval.
+	APIRetryMutex sync.Mutex
+)
```
[the remark this answers is not in the document]
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: That is excellent! - You're right, thanks.

File: pkg/controller/jobframework/setup.go [hunk 13]
```diff
@@ -99,6 +105,40 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+	if err := cb.SetupWebhook(mgr, opts...); err != nil {
+		return fmt.Errorf("%s: unable to create webhook: %w", fwkNamePrefix, err)
+	}
+	m.enableIntegration(name)
+	return nil
+}
+
+func (m *integrationManager) waitForAPI(ctx context.Context, mgr ctrl.Manager, log logr.Logger, gvk schema.GroupVersionKind, action func()) {
+	for {
+		m.mu.Lock()
```
[the remark this answers is not in the document]
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: I've been finding this lock hard to avoid as a `write` is performed in the tests [[here] ](https://github.com/kubernetes-sigs/kueue/pull/2574/files#diff-0e0e2357162d6c7d6172e1f1e2f0fed3d27946005ee221718652d972f6a61879R167)

However, I enhanced this by using `RLock()` instead which can be held by an arbitrary number of readers.

File: pkg/controller/jobframework/integrationmanager.go [hunk 14]
```diff
@@ -76,6 +77,7 @@ type integrationManager struct {
 	integrations         map[string]IntegrationCallbacks
 	enabledIntegrations  set.Set[string]
 	externalIntegrations map[string]runtime.Object
+	mu                   sync.Mutex
```
[the remark this answers is not in the document]
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/integrationmanager.go]: I just had an interesting read on RWMutex vs Mutex. - That is a really nice change, thanks!

File: pkg/controller/jobframework/setup.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (mbobrovskyi) [reply pkg/controller/jobframework/setup.go]: Actually, I don't like that we are using the same mutex for `mgr.GetRESTMapper()` and `integrationManager`. It's not related for integrationManager and need just for test. But we will unnecessary lock this code on update `integrationManager`. In my opinion it's better to create another one just for test.

File: pkg/controller/jobframework/setup_test.go [hunk 15]
```diff
@@ -135,18 +156,42 @@ func TestSetupControllers(t *testing.T) {
...
 			}
 
-			if diff := cmp.Diff(tc.wantEnabledIntegrations, manager.enabledIntegrations.SortedList()); len(diff) != 0 {
+			if slices.Contains(tc.wantEnabledIntegrations, "ray.io/raycluster") {
+				testDelayedIntegration(mgr, manager)
+			}
+
+			manager.mu.RLock()
+			diff := cmp.Diff(tc.wantEnabledIntegrations, manager.enabledIntegrations.SortedList())
+			manager.mu.RUnlock()
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/setup_test.go:170]: I think it's better to create a method `getEnabledIntegrations()` that will lock `enabledIntegrations` and return copy of value. You can use it where it's need.

File: pkg/controller/jobframework/integrationmanager.go
Comment (mbobrovskyi) [inline pkg/controller/jobframework/integrationmanager.go:1]: I think you missed to lock `enabledIntegrations` on `getJobTypeForOwner(ownerRef *metav1.OwnerReference)` and EnableIntegrationsForTest(tb testing.TB, names ...string).

File: pkg/controller/jobframework/setup.go (hunk 9 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: I hesitated on adding a log here as it would log for each API that is not yet available, and will retry after the specified interval. - This could cause log flooding. The error serves here as an indication to retry.

I've refactored the `waitForAPI()` to reflect explicitly the expected behaviour. - Let me know what you think, thank you.

Comment (mbobrovskyi) [reply pkg/controller/jobframework/setup.go]: Can we log only unexpected errors?

File: pkg/controller/jobframework/setup_test.go [hunk 16]
```diff
@@ -135,18 +156,42 @@ func TestSetupControllers(t *testing.T) {
...
-			gotError := manager.setupControllers(mgr, logger, tc.opts...)
+			gotError := manager.setupControllers(context.Background(), mgr, logger, time.Millisecond*20, tc.opts...)
 			if diff := cmp.Diff(tc.wantError, gotError, cmpopts.EquateErrors()); len(diff) != 0 {
 				t.Errorf("Unexpected error from SetupControllers (-want,+got):\n%s", diff)
 			}
 
-			if diff := cmp.Diff(tc.wantEnabledIntegrations, manager.enabledIntegrations.SortedList()); len(diff) != 0 {
+			if slices.Contains(tc.wantEnabledIntegrations, "ray.io/raycluster") {
+				testDelayedIntegration(mgr, manager)
+			}
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/setup_test.go:166]:
```suggestion
			if tc.afterSetup != nil {
				tc.afterSetup(mgr, manager)
			}
```

Maybe like this? And just move `testDelayedIntegration` to test case struct. It will allow to create another test cases if we will need and be independent of "ray.io/raycluster".

File: pkg/controller/jobframework/integrationmanager.go
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/integrationmanager.go:1]: I didn't lock any direct calls to `enabledIntegrations` as if I'm not mistaken the function is already locking/unlocking from within the function. I ensured though to add a lock to the `Clone` action being made on `EnableIntegrationsForTest(b testing.TB, names ...string) func()`:

`old := manager.enabledIntegrations.Clone()`

Let me know what you think and if I should lock the other `enableIntegrations` calls too, thanks.

File: pkg/controller/jobframework/setup_test.go (hunk 16 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup_test.go:166]: That's a great idea! - Thanks

File: pkg/controller/jobframework/integrationmanager.go
Comment (mbobrovskyi) [reply pkg/controller/jobframework/integrationmanager.go:1]: Yes, we need to lock all writes and reads of `enabledIntegrations` because it is potential race condition.

File: pkg/controller/jobframework/setup_test.go [hunk 17]
```diff
@@ -135,18 +158,44 @@ func TestSetupControllers(t *testing.T) {
...
+	for {
+		_, ok := getEnabledIntegrations(manager)["ray.io/raycluster"]
+		if ok {
+			break // Exit loop if RayCluster is enabled
+		}
+		time.Sleep(10 * time.Millisecond)
+	}
+}
+
+func getEnabledIntegrations(manager *integrationManager) set.Set[string] {
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/setup_test.go:193]: No, I meant a method of `integrationManager`. You can use it inside `integrationManager` to do not duplicate every time lock/unlock.

File: pkg/controller/jobframework/integrationmanager.go [hunk 18]
```diff
@@ -207,12 +211,16 @@ func EnableIntegration(name string) {
 // Mark the frameworks identified by names and return a revert function.
 func EnableIntegrationsForTest(tb testing.TB, names ...string) func() {
 	tb.Helper()
+	manager.mu.Lock()
 	old := manager.enabledIntegrations.Clone()
+	manager.mu.Unlock()
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/integrationmanager.go:216]:
```suggestion
	old := manager.getEnabledIntegrations()
```

File: pkg/controller/jobframework/setup.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: That makes sense, I've added a new mutex for use with the RESTMapper. Let me know what you think, thank you.

File: pkg/controller/jobframework/setup.go (hunk 9 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: Absolutely, I've added an error log for unexpected errors, such as any error that is not a `IsNoMatchError`

File: pkg/controller/jobframework/setup_test.go (hunk 17 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup_test.go]: Ohh I understand now, please see latest changes if it meets with expectations. Thanks for the help

File: pkg/controller/jobframework/setup.go [hunk 19]
```diff
@@ -33,6 +36,7 @@ import (
 
 var (
 	errFailedMappingResource = errors.New("restMapper failed mapping resource")
+	restMapperMutex          sync.RWMutex
```
Comment (mbobrovskyi) [inline pkg/controller/jobframework/setup.go:39]: To avoid confusion other members, please, add a comment why we add this mutex (that it is using only for unit test and we need to lock RESTMapper on update).

**Review by mbobrovskyi — COMMENTED** [review]
Overall LGTM

File: pkg/controller/jobframework/setup.go [hunk 20]
```diff
@@ -99,6 +100,50 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+			action()
+			return
+		}
+		if !meta.IsNoMatchError(err) {
+			log.Error(err, "Failed to get REST mapping for gvk", "gvk", gvk)
+		}
+		select {
+		case <-ctx.Done():
+			return
+		case <-time.After(retryInterval):
```
Comment (varshaprasad96) [inline pkg/controller/jobframework/setup.go:131]: Nit in terms of optimisation (can be done in follow up, not a blocker at all) - Given we are re-trying fetching the rest mapper in every cycle, better to use golang's [ticker](https://gobyexample.com/tickers):

```
ticker := time.NewTicker(retryInterval)
defer ticker.Stop()
```

Reason for this being - in this case a new timer is created every iteration, and it remains till the garbage collector does its job.

**Review by varshaprasad96 — COMMENTED** [review]
Nice work @ChristianZaccaria! The current changes look good, and my suggestions are completely nits (not a blocker at all)!

/lgtm

File: pkg/controller/jobframework/setup.go (hunk 20 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: That's an excellent idea, thanks!

File: cmd/kueue/main.go [hunk 21]
```diff
@@ -72,6 +73,8 @@ import (
 	// +kubebuilder:scaffold:imports
 )
 
+const retryInterval = time.Second * 20
```
Comment (trasc) [inline cmd/kueue/main.go:76]: let's make the variable name specific CRD detection.

In the context of kueue's main `retryInterval` can be confusing.

However, making the retry an option with a default defined in the jobframework might be better.

File: pkg/controller/jobframework/setup_test.go [hunk 22]
```diff
@@ -38,7 +39,7 @@ import (
 	jobset "sigs.k8s.io/jobset/api/jobset/v1alpha2"
 
 	kueue "sigs.k8s.io/kueue/apis/kueue/v1beta1"
-	"sigs.k8s.io/kueue/pkg/util/slices"
+	kslices "sigs.k8s.io/kueue/pkg/util/slices"
```
Comment (trasc) [inline pkg/controller/jobframework/setup_test.go:42]: I don'y think this change is necessary.

File: pkg/controller/jobframework/setup.go [hunk 23]
```diff
@@ -44,11 +49,11 @@ var (
 // this function needs to be called after the certs get ready because the controllers won't work
 // until the webhooks are operating, and the webhook won't work until the
 // certs are all in place.
-func SetupControllers(mgr ctrl.Manager, log logr.Logger, opts ...Option) error {
-	return manager.setupControllers(mgr, log, opts...)
+func SetupControllers(ctx context.Context, mgr ctrl.Manager, log logr.Logger, retryInterval time.Duration, opts ...Option) error {
```
Comment (trasc) [inline pkg/controller/jobframework/setup.go:52]: How about making `retryInterval` an option, then we can setup a default in https://github.com/kubernetes-sigs/kueue/blob/86691f1265974b9b58634773c928804952787bdb/pkg/controller/jobframework/reconciler.go#L187 , and avoid doing any changes to main until necessary (we have a config key for it).

File: pkg/controller/jobframework/setup.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: @kannon92 I have added `IntegrationRetryInterval` as a config option for Kueue. This option can now be tuned through the configmap. Thanks for the great suggestion.

[the remark this answers is not in the document]
Comment (kannon92) [reply pkg/controller/jobframework/setup.go]: Looks good!

File: apis/config/v1beta1/configuration_types.go [hunk 24]
```diff
@@ -319,6 +319,10 @@ type Integrations struct {
 	//  - "kubeflow.org/xgboostjob"
 	//  - "pod"
 	Frameworks []string `json:"frameworks,omitempty"`
+	// IntegrationRetryInterval refers to the duration to wait before retrying the API request.
```
Comment (trasc) [inline apis/config/v1beta1/configuration_types.go:322]: This needs to be more specific

File: pkg/controller/jobframework/setup.go (hunk 23 above)
Comment (trasc) [reply pkg/controller/jobframework/setup.go]: Please set up a default value as well.

File: apis/config/v1beta1/configuration_types.go [hunk 25]
```diff
@@ -319,6 +319,10 @@ type Integrations struct {
...
+	// Defaults to 20 seconds if not set.
+	// +optional
+	IntegrationRetryInterval *metav1.Duration `json:"integrationRetryInterval,omitempty"`
```
Comment (mimowo) [inline apis/config/v1beta1/configuration_types.go:325]: Actually, I'm not sure we want to expose this configuration at the surface of the API. @ChristianZaccaria do you have a use case for changing the value, or we could come up with a satisfying default which we set as a const? I would prefer not to expose it if we don't have a clear need, and we do research about other approaches.

The reason is - I'm not sure this is the optimal approach (see another comment about a CRDs watch), and exposing this at the API level would sort of commit us to it (deprecation of API is hard).

File: pkg/controller/jobframework/integrationmanager.go [hunk 26]
```diff
@@ -147,7 +149,15 @@ func (m *integrationManager) getExternal(kindArg string) (runtime.Object, bool)
 	return jt, f
 }
 
+func (m *integrationManager) getEnabledIntegrations() set.Set[string] {
```
Comment (mimowo) [inline pkg/controller/jobframework/integrationmanager.go:152]:
```suggestion
func (m *integrationManager) enabledIntegrations() set.Set[string] {
```

File: pkg/controller/jobframework/setup.go [hunk 27]
```diff
@@ -33,6 +36,8 @@ import (
 
 var (
 	errFailedMappingResource = errors.New("restMapper failed mapping resource")
+	// restMapperMutex is required for unit tests to lock the RESTMapper on update.
+	restMapperMutex sync.RWMutex
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:40]: I would prefer not to introduce code just for test. See related comment.

File: pkg/controller/jobframework/setup.go [hunk 28]
```diff
@@ -99,6 +100,52 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+		case <-ctx.Done():
+			return
+		case <-ticker.C:
+			continue
+		}
+	}
+}
+
+func getRESTMapping(mgr ctrl.Manager, gvk schema.GroupVersionKind) (*meta.RESTMapping, error) {
+	restMapperMutex.RLock()
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:140]: Would the `get` fail occasionally if there is no lock? Note that there is no such locking in production code, so such errors (race conditions) could happen in prod code. Seeing the errors which may be throws is desired, we can retry them in the test code, as the prod code would retry.

File: pkg/controller/jobframework/setup.go [hunk 29]
```diff
@@ -71,25 +76,21 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
 			if err != nil {
 				return fmt.Errorf("%s: %w: %w", fwkNamePrefix, errFailedMappingResource, err)
 			}
-			if _, err = mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version); err != nil {
+			if _, err := getRESTMapping(mgr, gvk); err != nil {
 				if !meta.IsNoMatchError(err) {
 					return fmt.Errorf("%s: %w", fwkNamePrefix, err)
 				}
 				logger.Info("No matching API in the server for job framework, skipped setup of controller and webhook")
+				go waitForAPI(ctx, mgr, log, gvk, options.IntegrationRetryInterval.Duration, func() {
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:84]: I'm ok with this as a quick fix, but I'm wondering if it would be better / feasible to have a watch on the CRDs (an analog of `kubectl get crd -w --output-watch-events`), and install the Controller and webhook when we see the ADDED event for the CRD in question. Unless I'm missing something, this could work without any user-facing API.

**Review by mimowo — COMMENTED** [review]
Generally lgtm, but I have an ask about extending the API surface for this approach, which may not be optimal in the long-run. Maybe we could consider / follow up with a CRD watch.

File: pkg/controller/jobframework/setup.go (hunk 23 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: The default value has been set [here](https://github.com/kubernetes-sigs/kueue/pull/2574/files#diff-dec60c4ac9a26c19509573fd87068ecb6bb784c0af528d38b48f5dc526eb4241R52). Let me know if this is okay.

File: pkg/controller/jobframework/setup.go (hunk 29 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:84]: Previously, that was the original idea. I was going to use [`apiextensions`](https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions) to watch CRDs directly, however I was suggested to use the restmapper. I suppose it is more straightforward and it's also how we've been checking for their availability. This is from [a draft PR](https://github.com/opendatahub-io/kueue/pull/33/commits/5bec43389f43dc7a71d644d4efa9d6f456f77fc4#diff-9b0c3819f5a2c007ac714ec151937ce08cc2b768527cc28d20580a57f47ca5a7R155) from some time ago (might need more work). A follow-up can be made on this.

File: apis/config/v1beta1/configuration_types.go (hunk 25 above)
Comment (ChristianZaccaria) [reply apis/config/v1beta1/configuration_types.go:325]: I agree, please see the other comment for details. Should I remove the latest commit and remove this as a config option, and just have minimal changes to include the default value?

File: pkg/controller/jobframework/integrationmanager.go (hunk 26 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/integrationmanager.go:152]: This might not be possible, as that already exists [here](https://github.com/kubernetes-sigs/kueue/pull/2574/files#diff-fde4763cb4c71b0994c0012fc717450c2c2d90a182e3fa30f3d5a21417b42686L150-L152). WDYT?

File: pkg/controller/jobframework/setup.go (hunk 29 above)
Comment (mimowo) [reply pkg/controller/jobframework/setup.go:84]: > I was going to use [apiextensions](https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions) to watch CRDs directly, however I was suggested to use the restmapper.

Thank you for the context. I still think the current approach is suboptimal, whatever is the interval, because it means periodic polling, which takes goroutines and results in spammy logging. 

So, I think we would like to use a watch for CRDs  to guide the RestMapper check. So only once we discover the new CRD, then we start waiting for the rest mapper to be filled. Then, the waiting intervals could be much smaller (and don't need to be configurable).

One way to the watcher would be to have a controller-runtime reconciler for the CRD type, similar to the one for [ResourceFlavor](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/core/resourceflavor_controller.go). I imagine we would use `WithEventFilter` to only listen for the ADD events. Then trigger reconciler. The Reconcile function would actually call the rest mapper. If succeeds, then done, if fails, then it will retry with exponential backoff, but this is already handled by controller-runtime.

File: pkg/controller/jobframework/setup.go (hunk 28 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:140]: The `get` never failed without the lock. In fact, all tests passed without the `-race` flag. 

This lock is added for the tests to pass with the `-race` flag. In the tests, a [`write` is performed](https://github.com/kubernetes-sigs/kueue/pull/2574/files#diff-0e0e2357162d6c7d6172e1f1e2f0fed3d27946005ee221718652d972f6a61879R185), causing a race condition here.

File: apis/config/v1beta1/configuration_types.go (hunk 25 above)
Comment (mimowo) [reply apis/config/v1beta1/configuration_types.go:325]: Please remove it from API (which is largely the last commit). I'm ok to keep it as an iinput option to some function that is used for test purposes to make the tests run fast.

File: pkg/controller/jobframework/setup.go (hunk 29 above)
Comment (mimowo) [reply pkg/controller/jobframework/setup.go:84]: Then we could also investigate if we can do the symmetric operation - when the CRD is removed (DELETE event), can we unregister the controller and the webhook.

File: pkg/controller/jobframework/setup.go (hunk 28 above)
Comment (mimowo) [reply pkg/controller/jobframework/setup.go:140]: I see, in that case we could retry the write, but then there is a question if the write would be retried by the production code. I think, ideally we would have an integration test for that. At the unit test level I prefer to retry the write.

File: pkg/controller/jobframework/setup.go (hunk 23 above)
Comment (trasc) [reply pkg/controller/jobframework/setup.go]: It may not be sufficient, if at some point we and up calling `SetupControllers` without the option set , we'll end up running loops `0s` sleep.

File: pkg/controller/jobframework/setup.go (hunk 29 above)
Comment (varshaprasad96) [reply pkg/controller/jobframework/setup.go:84]: @mimowo having a separate controller watch for a CRD, and then send in the event through a channel to trigger the start of the main controller does follow the event driven principle and reduces the delay that comes by polling at the specified interval. But the reason for having it this way, was to introduce as minimum complexity as possible upstream, as this would be an occurrence only once before the start of the main controller. 

> One way to the watcher would be to have a controller-runtime reconciler for the CRD type, similar to the one for [ResourceFlavor](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/core/resourceflavor_controller.go).

Looking at the code (pl correct me if I'm wrong), each of the watchers specified in the ResourceFlavour, receive events through channels created in their respective reconcilers (AdmissionCheck, LocalClusterQueue, ClusterQueue) - https://github.com/kubernetes-sigs/kueue/blob/58ef31e6ef674db0aa04cb587d41862570ad1d12/pkg/controller/core/clusterqueue_controller.go#L89. But in this case, the list of CRDs is configurable, so having a reconciler for each type would not be scalable. One option here, would be to have a single reconciler, and have a dynamic restMapper (with a dynamic Client) to watch for all the expected CRD types and send in a signal to start the core controller. This is going to be very similar (without the creation of separate reconciler) to @ChristianZaccaria option (1) as mentioned in the issue.

>  when the CRD is removed (DELETE event), can we unregister the controller and the webhook.

This touches the part of dynamically starting/stopping the reconcilers, which unfortunately is not natively supported by controller-runtime yet (https://github.com/kubernetes-sigs/controller-runtime/pull/2159). There are ways to do workarounds on this - like cancelling the context, stopping the informers (which may not be trivial), registering a stopChn with `manager` to signal a shutdown. That being said - is this the behaviour we would expect? Since the option to provide integrations is provided by the user through config API at the start of the Kueue controller, and iiuc there is no way to signal that the integration is no longer required - I would expect the Kueue controller to fail and error if the CRD is removed, rather than us unregistering the respective controller?

Comment (mimowo) [reply pkg/controller/jobframework/setup.go:84]: > But the reason for having it this way, was to introduce as minimum complexity as possible upstream, as this would be an occurrence only once before the start of the main controller.

I agree with reducing the complexity, but being uncertain about the long-term solution does not make me comfortable extending the API surface, because likely we will need to deprecate it one day. Having hard-coded 20s for the current solution is fine for me.

> But in this case, the list of CRDs is configurable, so having a reconciler for each type would not be scalable.

I was thinking we could have the just a single reconciler with a single watch for the `CustomResourceDefinition` kind. Then, based on the object, we could read the details of the new CRD installed: https://github.com/kubernetes/kubernetes/blob/ceb58a4dbc671b9d0a2de6d73a1616bc0c299863/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go#L36-L44, and lookup the RESTMapper.

>  I would expect the Kueue controller to fail and error if the CRD is removed, rather than us unregistering the respective controller?

I'm not sure, maybe it should be configurable. Anyway, I think we can park this particular decision for now. 

In summary, I would suggest to research a little more the reconciler based approach, if there are obstacles, we can go with the current one, but I wouldn't extend the API surface for it.

Comment (varshaprasad96) [reply pkg/controller/jobframework/setup.go:84]: > I agree with reducing the complexity, but being uncertain about the long-term solution does not make me comfortable extending the API surface, because likely we will need to deprecate it one day. Having hard-coded 20s for the current solution is fine for me.

Agreed, seems fair enough to not extend an API surface especially given that it's not going to impact the Kueue functionality largely and is used only during setup. 

> I was thinking we could have the just a single reconciler with a single watch for the CustomResourceDefinition kind. 

I'm a bit skeptical with controller approach because - Controllers are useful when there is a need to manage the state of the resource through continuous reconciliation, in addition to being able to integrate with other controllers (which is the use-case here). The design mentioned above complies perfectly with the current Watcher approach, wherein say the `ClusterQueueReconciler` is managing the state of `ClusterQueue` resource apart from being able to send a signal to another controller. In this case, we are not intending to manage the lifecycle of any of the CRDs (there are respective operators for each one of them), nor are going to manage the CRs created for them throughout the existence of Kueue's core controller. 

Having a separate controller, apart from its benefits - is also going to give us the overhead of caching these CRDs, spinning up informers for them (which currently cannot be stopped as of c-r design) consuming memory and CPU resources, while we are going to use it only during setup. Imo having a controller for this seems to be an overkill. Given we are not going to deal with managing the state of any of the resources - a simple Watch makes more sense, given its going to be lightweight,  where we can just close the channel once we have received the event we want and have started the core controller and also follows the event driven approach rather than polling.

Comment (varshaprasad96) [reply pkg/controller/jobframework/setup.go:84]: @mimowo would you be comfortable with making the `retryInterval` constant in the current design, and following up further on the watch based approach as suggested by @ChristianZaccaria in [here](https://github.com/opendatahub-io/kueue/pull/33/commits/5bec43389f43dc7a71d644d4efa9d6f456f77fc4#diff-9b0c3819f5a2c007ac714ec151937ce08cc2b768527cc28d20580a57f47ca5a7R155).

Comment (mimowo) [reply pkg/controller/jobframework/setup.go:84]: Yes, I would also like you folks to consider adding an integration test for it on the way.

Comment (mimowo) [reply pkg/controller/jobframework/setup.go:84]: One more thing worth considering also is an exponential backoff instead of fixed intervals for for calling RESTmapper (say from 1s to 1min). I believe generally the RESTMapper would be updated very fast, but maybe for an overloaded system it makes sense to throttle the attempts. WDYT?

Comment (varshaprasad96) [reply pkg/controller/jobframework/setup.go:84]: > I believe generally the RESTMapper would be updated very fast, but maybe for an overloaded system it makes sense to throttle the attempts.

Yeah, polling it quickly might indeed overload the apiserver. My only concern here would be the responsiveness of the overall system with us trying exponential backoff. If we can have a reasonable limit on the maximum backoff time, then it should be good.

Comment (mimowo) [reply pkg/controller/jobframework/setup.go:84]: Reconcilers use exponential rate limiters: https://github.com/kubernetes/client-go/blob/fe54892e0cc44385de5b5300985bd27218dd2c23/util/workqueue/default_rate_limiters.go#L112C6-L115, so from 1ms to 1000s by default. We can try that and see how it works in practice, I'm ok for adjust the lower end to say 100ms (or 1s) if it turns out there are too many failed attempts.

**Comment by tenzen-y** [comment]
It seems that this PR is working in progress based on https://github.com/kubernetes-sigs/kueue/pull/2574#discussion_r1687575212 and https://github.com/kubernetes-sigs/kueue/pull/2574#discussion_r1687586765. Once these discussion results are applied to the code, I will come back here.

File: pkg/controller/jobframework/setup.go (hunk 29 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:84]: Exponential rate limiters sound like a great idea, will be implemented in this PR. Thanks! We could re-discuss to agree on a lower and upper end values.

**Comment by ChristianZaccaria** [comment]
Hi @mimowo , I just got back to this recently. I've created 2 PRs in my fork repository with some alternatives. Each PR has a description with additional details:
- [Using Mutex on enabledIntegrations as there is a real case of race conditions](https://github.com/ChristianZaccaria/kueue/pull/6) - I've added the different use cases in which a race could happen.
- [Alternative without using Mutex: cancelling the context to restart the Kueue pod on newly available Frameworks.](https://github.com/ChristianZaccaria/kueue/pull/8)

Please let me know which alternative would be best, and your thoughts. Thank you !

**Comment by mimowo** [comment]
Hi @ChristianZaccaria, very nice to see you are back on this. 

Thanks for the investigation. IIUC the non-mutex solution requires Kueue pod restart, I think this is a significant con. So, I'm leaning towards the mutex-based solution. 

I don't expect the mutex to have any significant performance impact, but we may consider R/W locks to allow multiple readers for the `getJobTypeForOwner` function.

**Comment by ChristianZaccaria** [comment]
@mimowo thanks! :) . I understand, the 'restarting Kueue pod' would interfere with any running processes.
> we may consider R/W locks to allow multiple readers for the getJobTypeForOwner function.

Completely agree on this, will make changes now, thanks.

**Comment by ChristianZaccaria** [comment]
Correct me if I'm wrong, [`getEnabledIntegrations()`](https://github.com/kubernetes-sigs/kueue/pull/2574/files#diff-fde4763cb4c71b0994c0012fc717450c2c2d90a182e3fa30f3d5a21417b42686R152-R154) currently uses R Locks allowing for multiple reads for the `getJobTypeForOwner()`.

File: pkg/controller/jobframework/integrationmanager.go (hunk 26 above)
Comment (mimowo) [reply pkg/controller/jobframework/integrationmanager.go:152]: The name `enableIntegration` is slightly different so will not conflict with `enabledIntegrations`.

**Comment by mimowo** [comment]
Yes, it is ok. I somehow missed that, maybe I confused it with the other function.

**Comment by ChristianZaccaria** [comment]
Perfect, please let me know on the next steps for this PR to be successfully merged. I'll create a follow-up issue for further discussion on [this thread](https://github.com/kubernetes-sigs/kueue/pull/2574#discussion_r1687586765).

File: pkg/controller/jobframework/setup_test.go [hunk 30]
```diff
@@ -135,18 +165,33 @@ func TestSetupControllers(t *testing.T) {
 				t.Fatalf("Failed to setup manager: %v", err)
 			}
 
-			gotError := manager.setupControllers(mgr, logger, tc.opts...)
+			gotError := manager.setupControllers(context.Background(), mgr, logger, tc.opts...)
```
Comment (mimowo) [inline pkg/controller/jobframework/setup_test.go:168]: nit, can we use context from `utiltesting.ContextWithLog(t)`?

File: pkg/controller/jobframework/setup_test.go [hunk 31]
```diff
@@ -135,18 +165,33 @@ func TestSetupControllers(t *testing.T) {
...
+			if len(diff) != 0 {
 				t.Errorf("Unexpected enabled integrations (-want,+got):\n%s", diff)
 			}
 		})
 	}
 }
 
+func testDelayedIntegration(mgr ctrlmgr.Manager, manager *integrationManager) {
+	for {
+		_, ok := manager.getEnabledIntegrations()["ray.io/raycluster"]
```
Comment (mimowo) [inline pkg/controller/jobframework/setup_test.go:187]: nit, make the CRD name as a param to this function

File: pkg/controller/jobframework/setup.go [hunk 32]
```diff
@@ -99,6 +100,60 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+	}
+	if err := cb.SetupWebhook(mgr, opts...); err != nil {
+		return fmt.Errorf("%s: unable to create webhook: %w", fwkNamePrefix, err)
+	}
+	m.enableIntegration(name)
+	return nil
+}
+
+func waitForAPI(ctx context.Context, mgr ctrl.Manager, checkAPIAvailable fetchRestMapperFunc, log logr.Logger, gvk schema.GroupVersionKind, action func()) {
+	rateLimiter := workqueue.NewItemExponentialFailureRateLimiter(100*time.Millisecond, 100*time.Second)
```
Comment (mimowo) [inline pkg/controller/jobframework/setup.go:119]: nit, move to constants, and until we can await for the CRD being installed, I would suggest:
`minBackoffWaitForIntegration =1s`, `maxBackoffWaitForIntegration=2min`.

**Review by mimowo — COMMENTED** [review]
Just some nits. Ideally, we would have these covered before release:
- integration or e2e test
- only start `waitForAPI` with exponential backoff once the CRD is registered (wait either by controller or watcher on CRD type)

**Comment by mimowo** [comment]
> Perfect, please let me know on the next steps for this PR to be successfully merged.

Sgtm, we can track both things mentioned in my previous comment in follow up issues. 
/cc @tenzen-y 
Would you also like to give it a pass?

**Comment by ChristianZaccaria** [comment]
> Just some nits. Ideally, we would have these covered before release:
> 
> * integration or e2e test
> * only start `waitForAPI` with exponential backoff once the CRD is registered (wait either by controller or watcher on CRD type)

Thank you, I'll track these items in the follow-up issue.

**Comment by mimowo** [comment]
> Thank you, I'll track these items in the follow-up issue.

Please also address this nit: https://github.com/kubernetes-sigs/kueue/pull/2574/files#r1687576889.

**Comment by mimowo** [comment]
I would like to consider this PR for cherry-picking as a fix. WDYT @tenzen-y @alculquicondor ? It does not entail API changes and I've seen users hitting this.

File: pkg/controller/jobframework/integrationmanager.go (hunk 26 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/integrationmanager.go:159]: Sorry, I meant `enabledIntegrations` would conflict with this[ `enabledIntegrations`](https://github.com/kubernetes-sigs/kueue/pull/2574/files#diff-fde4763cb4c71b0994c0012fc717450c2c2d90a182e3fa30f3d5a21417b42686R85)

**Comment by tenzen-y** [comment]
> > Perfect, please let me know on the next steps for this PR to be successfully merged.
> 
> Sgtm, we can track both things mentioned in my previous comment in follow up issues. /cc @tenzen-y Would you also like to give it a pass?

I came back here.

File: pkg/controller/jobframework/integrationmanager.go [hunk 33]
```diff
@@ -231,12 +241,14 @@ func EnableIntegration(name string) {
 // Mark the frameworks identified by names and return a revert function.
 func EnableIntegrationsForTest(tb testing.TB, names ...string) func() {
 	tb.Helper()
-	old := manager.enabledIntegrations.Clone()
+	old := manager.getEnabledIntegrations()
 	for _, name := range names {
 		manager.enableIntegration(name)
 	}
```
Comment (alculquicondor) [inline pkg/controller/jobframework/integrationmanager.go:247]: It would be more accurate to obtain the lock once for this entire operation. But because this is just for tests, it's fine.

File: pkg/controller/jobframework/setup.go [hunk 34]
```diff
@@ -21,16 +21,26 @@ import (
...
+	"k8s.io/apimachinery/pkg/runtime/schema"
+	"k8s.io/client-go/util/workqueue"
 	ctrl "sigs.k8s.io/controller-runtime"
 	"sigs.k8s.io/controller-runtime/pkg/client"
 	"sigs.k8s.io/controller-runtime/pkg/client/apiutil"
 
 	"sigs.k8s.io/kueue/pkg/controller/jobs/noop"
 )
 
+type fetchRestMapperFunc func(mgr ctrl.Manager, gvk schema.GroupVersionKind) (bool, error)
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup.go:37]:
```suggestion
type fetchRestMapperFunc func(mgr ctrl.Manager, gvk schema.GroupVersionKind) error
```

It doesn't look like the boolean will be true when there is an error, so no need for 2 outputs.

File: pkg/controller/jobframework/setup.go [hunk 35]
```diff
@@ -103,6 +109,60 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+	}
+	if err := cb.SetupWebhook(mgr, opts...); err != nil {
+		return fmt.Errorf("%s: unable to create webhook: %w", fwkNamePrefix, err)
+	}
+	m.enableIntegration(name)
+	return nil
+}
+
+func waitForAPI(ctx context.Context, mgr ctrl.Manager, checkAPIAvailable fetchRestMapperFunc, log logr.Logger, gvk schema.GroupVersionKind, action func()) {
+	rateLimiter := workqueue.NewItemExponentialFailureRateLimiter(baseBackoffWaitForIntegration, maxBackoffWaitForIntegration)
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup.go:128]: what's the rationale for using an exponential backoff instead of just checking every minute?

File: pkg/controller/jobframework/setup.go [hunk 36]
```diff
@@ -103,6 +109,60 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+		select {
+		case <-ctx.Done():
+			return
+		case <-time.After(rateLimiter.When(item)):
+			continue
+		}
+	}
+}
+
+func getRESTMapping(mgr ctrl.Manager, gvk schema.GroupVersionKind) (*meta.RESTMapping, error) {
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup.go:150]: are we ever using the `*meta.RESTMapping`?

If not, please simplify.

File: pkg/controller/jobframework/setup.go [hunk 37]
```diff
@@ -103,6 +109,60 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+	restMapping, err := mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version)
+	if err != nil {
+		return nil, fmt.Errorf("failed to get REST mapping for %v: %w", gvk, err)
+	}
+	return restMapping, nil
+}
+
+var defaultCheckAPIAvailable fetchRestMapperFunc = func(mgr ctrl.Manager, gvk schema.GroupVersionKind) (bool, error) {
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup.go:158]: global variables for the purpose of testing are cumbersome (as you should be restoring them after the test). Prefer passing the function to `SetupControllers` as an `Option`.
Even better, make use of `MapperProvider`

File: pkg/controller/jobframework/setup_test.go [hunk 38]
```diff
@@ -99,6 +117,18 @@ func TestSetupControllers(t *testing.T) {
...
 			wantEnabledIntegrations: []string{"batch/job"},
 		},
+		"mapper doesn't have ray.io/raycluster when Controllers have been setup, but eventually does": {
+			opts: []Option{
+				WithEnabledFrameworks([]string{"batch/job", "kubeflow.org/mpijob", "ray.io/raycluster"}),
+			},
+			mapperGVKs: []schema.GroupVersionKind{
+				batchv1.SchemeGroupVersion.WithKind("Job"),
+				kubeflow.SchemeGroupVersionKind,
+				// Not including RayCluster
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup_test.go:127]: what adds it?

File: pkg/controller/jobframework/setup_test.go [hunk 39]
```diff
@@ -134,18 +164,33 @@ func TestSetupControllers(t *testing.T) {
...
 
-			gotError := manager.setupControllers(mgr, logger, tc.opts...)
+			gotError := manager.setupControllers(ctx, mgr, logger, tc.opts...)
 			if diff := cmp.Diff(tc.wantError, gotError, cmpopts.EquateErrors()); len(diff) != 0 {
 				t.Errorf("Unexpected error from SetupControllers (-want,+got):\n%s", diff)
 			}
 
-			if diff := cmp.Diff(tc.wantEnabledIntegrations, manager.enabledIntegrations.SortedList()); len(diff) != 0 {
+			if tc.afterSetup != nil {
+				tc.afterSetup(mgr, &manager, "ray.io/raycluster")
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup_test.go:173]: `afterSetup` sounds too generic and we are only implementing it once. Try to be more explicit with the naming.

File: pkg/controller/jobframework/setup.go (hunk 34 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:37]: This is true, but there is a scenario where it can return false with no errors i.e., if it is an `IsNoMatchError`, it is fine and expected to have missing job frameworks. It could also return false with errors if it's a different error such as issues with fetching the RESTMapper itself. I've modified the function variable to reflect this explicitly.
```
	var defaultCheckAPIAvailable = func(mgr ctrl.Manager, gvk schema.GroupVersionKind) (bool, error) {
		err := restMappingExists(mgr, gvk)
		if meta.IsNoMatchError(err) {
			return false, nil
		}
		if err != nil {
			return false, err
		}
		return true, nil
	}

File: pkg/controller/jobframework/setup.go (hunk 35 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:128]: Good question, there could be a scenario where we deploy 2 or more components at the same time, where Kueue was the first one to be deployed. The low base backoff helps in integrating with the new job frameworks quickly, while allowing for a higher-end backoff for any newly added frameworks at any later stage. I'm open to changing it to check on every minute if desired.

File: pkg/controller/jobframework/setup_test.go (hunk 38 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup_test.go:120]: I've updated the test to add the job framework to the mapper directly. 

However, previously, with the `defaultCheckAPIAvailable` function variable we simulate the RayCluster framework becoming available. For context, first we check if the restMapping exists for any given framework, if not, we start the go routine on `waitForAPI()` with the function variable which will return if the restMapping was found. In the test, we overwrite the function variable to eventually return true, saying that the restMapping for the RayCluster framework was found.

File: pkg/controller/jobframework/setup.go [hunk 40]
```diff
@@ -103,6 +110,64 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+		case <-ctx.Done():
+			return
+		case <-time.After(rateLimiter.When(item)):
+			continue
+		}
+	}
+}
+
+func restMappingExists(mgr ctrl.Manager, gvk schema.GroupVersionKind) error {
+	mu.RLock()
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup.go:162]: It looks like this is just for tests, so create the lock somewhere in the `MapperProvider` function, probably wrapping the Wrapper into another struct that has the lock.

File: pkg/controller/jobframework/setup.go [hunk 41]
```diff
@@ -103,6 +110,64 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
+	}
+
+	for {
+		isAvailable, err := defaultCheckAPIAvailable(mgr, gvk)
+		if isAvailable {
+			rateLimiter.Forget(item)
+			action()
+			return
+		}
+		if err != nil && !meta.IsNoMatchError(err) {
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup.go:149]:
```suggestion
		err := restMappingExists(mgr, gvk)
		if err != nil {
			rateLimiter.Forget(item)
			action()
			return
		} else if !meta.IsNoMatchError(err) {
```

File: pkg/controller/jobframework/setup_test.go [hunk 42]
```diff
@@ -134,18 +160,46 @@ func TestSetupControllers(t *testing.T) {
...
 			}
 
-			gotError := manager.setupControllers(mgr, logger, tc.opts...)
+			gotError := manager.setupControllers(ctx, mgr, logger, tc.opts...)
 			if diff := cmp.Diff(tc.wantError, gotError, cmpopts.EquateErrors()); len(diff) != 0 {
 				t.Errorf("Unexpected error from SetupControllers (-want,+got):\n%s", diff)
 			}
 
-			if diff := cmp.Diff(tc.wantEnabledIntegrations, manager.enabledIntegrations.SortedList()); len(diff) != 0 {
+			if tc.delayedIntegrationTest {
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup_test.go:168]:
```suggestion
			if len(tc.delayedGVKs) > 0 {
```

File: pkg/controller/jobframework/setup_test.go [hunk 43]
```diff
@@ -134,18 +160,46 @@ func TestSetupControllers(t *testing.T) {
...
+				// Simulate the delayed addition of RayCluster
+				simulateDelayedIntegration(mgr, tc.delayedGVKs)
+				testDelayedIntegration(&manager, "ray.io/raycluster")
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup_test.go:171]: use a for loop on `tc.delayedGVKs` or something along those lines, instead of the hardcoded string.

**Review by tenzen-y — COMMENTED** [review]
Overall not bad.
IIUC, we decided to introduce this mechanism if the mechanism is not complex.
However, this PR tries to implement a lightweight mechanism similar to reconciler by hand.

Although I know there were discussions about whether we should watch CRD by reconcilers, and then we put the decision to introduce the reconciler for CRD on hold.

But, I'm wondering if we should use the dedicated reconciler instead of hand made watcher so that we can avoid implementing the similar to mechanism as reconciler by hand.

@alculquicondor @mimowo Please let me know what you think.

Even if we decided to switch to reconciler mechanism, I think we can work on the switching at the follow-up PRs.

**Comment by alculquicondor** [comment]
That's a good point.

I don't recall at which point we switched from looking at CRDs to querying the RESTMapper. But certainly using a reconciler has the potential of reducing the registration time to zero. And we could even remove integrations as CRDs are removed.

I don't want to hold this PR for much longer, since it's not extremely complex, but you are right, a reconciler would have similar complexity with a few extra benefits.

**Comment by tenzen-y** [comment]
> I don't want to hold this PR for much longer, since it's not extremely complex, but you are right, a reconciler would have similar complexity with a few extra benefits.

I agree with you. So I recommended this one: 

> Even if we decided to switch to reconciler mechanism, I think we can work on the switching at the follow-up PRs.

So, let's track and investigate the possibility of the reconciler pattern for this mechanism by another issue.

File: pkg/controller/jobframework/setup.go [hunk 44]
```diff
@@ -75,25 +86,21 @@ func (m *integrationManager) setupControllers(mgr ctrl.Manager, log logr.Logger,
...
 				return fmt.Errorf("%s: %w: %w", fwkNamePrefix, errFailedMappingResource, err)
 			}
-			if _, err = mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version); err != nil {
+			if err := restMappingExists(mgr, gvk); err != nil {
 				if !meta.IsNoMatchError(err) {
 					return fmt.Errorf("%s: %w", fwkNamePrefix, err)
 				}
 				logger.Info("No matching API in the server for job framework, skipped setup of controller and webhook")
+				go waitForAPI(ctx, mgr, log, gvk, func() {
+					log.Info(fmt.Sprintf("API now available, starting controller and webhook for %v", gvk))
```
[the remark this answers is not in the document]
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go]: Thanks!!

File: pkg/controller/jobframework/setup.go (hunk 40 above)
Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:150]: I've attempted to create a wrapper into another struct with the mapper and the lock, but the result is very similar.

The issue is this: In the application code, the go routine will continuously read the RESTMapping while in the test it will add to the mapper to simulate the availability of the newly added framework. It's a race condition, but of eventual consistency as the go routine reads again from the mapper and verifies the framework's availability.

I tried to lock the mapper in the test on its own, but the application code will continue to read from the mapper, causing this race condition.

Comment (alculquicondor) [reply pkg/controller/jobframework/setup.go:150]: But in the application code, the mapper is updated without taking this lock (because it's defined somewhere else).

So the race condition will still exist.

Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:150]: I think I understand your point, correct me please. If we were to add a new `CRD`, this would update the RESTMapper, we then at the same time will be requesting it to check/read for specific Mappings. If the RESTMapper has not yet been updated with the new CRD at the time we read from it, the mechanism is to re-read of which, is a race condition but of eventual synchronization. How do you think we could proceed?

Comment (alculquicondor) [reply pkg/controller/jobframework/setup.go:150]: I don't know if the application RESTMapper itself has some internal lock already, it might be worth checking.

My point is that adding a lock here doesn't prevent a race condition in the application code, but maybe that's fine, eventually it will succeed.

Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup.go:150]: > My point is that adding a lock here doesn't prevent a race condition in the application code, but maybe that's fine, eventually it will succeed.

That's correct. You're right, the lock here is for the test to pass, given it's ran with the `-race` flag. Ideally, it's best to not introduce code here for the tests, but the `setup_test.go` (test file) essentially runs the `setup_controllers()` function which executes almost the entirety of the `setup.go` file, meaning it basically runs as a hybrid test or closely as it would run in production, hence requiring this lock here.

File: pkg/controller/jobframework/setup_test.go [hunk 45]
```diff
@@ -134,18 +159,48 @@ func TestSetupControllers(t *testing.T) {
...
+				}
+			}
+
+			diff := cmp.Diff(tc.wantEnabledIntegrations, manager.getEnabledIntegrations().SortedList())
+			if len(diff) != 0 {
 				t.Errorf("Unexpected enabled integrations (-want,+got):\n%s", diff)
 			}
 		})
 	}
 }
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup_test.go:181]: You can do something like this:

```golang
func TestRESTMapper struct {
  *DefaultRESTMapper
  lock sync.RWMutex
}

func (m *TestRESTMapper) RESTMapping(...) {
  m.lock.Lock()
  return m.DefaultRESTMapper.RESTMapping(...)
}
```

Comment (ChristianZaccaria) [reply pkg/controller/jobframework/setup_test.go:185]: That is genius, please see latest changes if it meets with expectations. Thanks for the help and guidance Aldo.

**Comment by ChristianZaccaria** [comment]
Rebased

File: pkg/controller/jobframework/setup_test.go [hunk 46]
```diff
@@ -123,29 +149,73 @@ func TestSetupControllers(t *testing.T) {
 						return gvk.GroupVersion()
 					})
 					mapper := apimeta.NewDefaultRESTMapper(gvs)
+					testMapper := &TestRESTMapper{
+						DefaultRESTMapper: mapper,
+						lock:              sync.RWMutex{},
```
Comment (alculquicondor) [inline pkg/controller/jobframework/setup_test.go:154]: nit: this line is not needed

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by mimowo** [comment]
@tenzen-y @alculquicondor as we are about to prepare the 0.8.1 release - how do you find cherry-picking this PR?

I feel this issue is on a boundary between a feature and a bug. It could be considered a feature, because we didn't plan for it up front. OTOH, I participated in some debugging sessions for users, and I think the users' perception was always that this is a bug.

Finally, the change does not introduce any API changes, so I would suggest considering it for cherry-picking.

**Comment by tenzen-y** [comment]
> OTOH, I participated in some debugging sessions for users, and I think the users' perception was always that this is a bug.

Thank you for this experience. In that case, I agree with cherry-picking.

**Comment by mimowo** [comment]
There is a conflict in `integrationmanager`. @ChristianZaccaria would you like to prepare the cherry-pick manually? You can use the https://github.com/kubernetes-sigs/kueue/blob/main/hack/cherry_pick_pull.sh script

**Comment by ChristianZaccaria** [comment]
Thank you, on it now.

**Comment by ChristianZaccaria** [comment]
For reference, here is the generated PR: https://github.com/kubernetes-sigs/kueue/pull/2991 Thanks!

**Comment by mimowo** [comment]
To x-reference the follow up issues:
- https://github.com/kubernetes-sigs/kueue/issues/2837
- https://github.com/kubernetes-sigs/kueue/issues/3015
