### PR TITLE
MultiKueue testing: allow running tests after: The connection to a worker cluster is unreliable

### LINKED ISSUE #6399: [MultiKueue test] The connection to a worker cluster is unreliable makes cluster not working properly
**What happened**:

This test leaves the cluster not working properly, if there are any tests executing after it they flake.

**What you expected to happen**:

The test should leave the cluster in usable state.

**How to reproduce it (as minimally and precisely as possible)**:

see https://github.com/kubernetes-sigs/kueue/issues/6386

**Anything else we need to know?**:

Maybe we could call AwaitForAvailablity on both workers and manager clusters.

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
In the test when we disconnect and re-connect worker cluster, we wait for Kueue deployment readiness.
However what sometimes is not ready are the kube-system pods, e.g. kindnet, kube-scheduler.
By checking their readiness after the reconnection we make sure the test does not fail.

Steps to eliminate flakines:
* Bind API Server address instead of docker connect/disconnect
* Wait for Kueue availability
* Wait for Kind cluster related components availability
* Add timeout for objects deletion after each test 

#### Which issue(s) this PR fixes:

Fixes #6399 

#### Special notes for your reviewer:
This has been tested in repeated fashion, but locally.
I want to run couple retries on [pull-kueue-test-e2e-multikueue-main](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6466/pull-kueue-test-e2e-multikueue-main/1952708791380217856) jobs.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/util/e2e.go [hunk 1]
```diff
@@ -317,6 +317,19 @@ func WaitForKubeRayOperatorAvailability(ctx context.Context, k8sClient client.Cl
...
+func WaitForKubeSystemControllersAvailability(ctx context.Context, k8sClient client.Client, restClient *rest.RESTClient, cfg *rest.Config, timeout time.Duration) {
+	const ns = "kube-system"
+	for _, controller := range []string{
+		"kindnet",
+		"kube-controller-manager",
+		"kube-scheduler",
+	} {
+		controllerOpts := GetListOptsFromLabel(fmt.Sprintf("app=%s", controller))
+		ginkgo.By(fmt.Sprintf("Waiting for %s to be available", controller))
+		WaitForPodIsReady(ctx, k8sClient, restClient, cfg, ns, timeout, controllerOpts)
```
Comment (mimowo) [inline test/util/e2e.go]: Looking at individual Pods seems very tricky. I suppose some of them might be Failed, and just get recreated during the downtime, there is nothing wrong about. I think it would be better to make sure or Deployments  (and potentially DaemonSets) are availbable.

File: test/e2e/multikueue/e2e_test.go [hunk 2]
```diff
@@ -1022,6 +1009,28 @@ var _ = ginkgo.Describe("MultiKueue", func() {
 						util.IgnoreConditionTimestampsAndObservedGeneration)))
 				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
 			})
+
+			ginkgo.By("Waiting for the kube-system components to become active", func() {
+				util.WaitForKubeSystemControllersAvailability(ctx, k8sWorker1Client, worker1RestClient, worker1Cfg, util.StartUpTimeout)
```
Comment (mimowo) [inline test/e2e/multikueue/e2e_test.go]: Let's also wait for Kueue to be available.

Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: Hmmm, yes, but at least locally it was always kube-system pods that was the last to stabilise.

File: test/util/e2e.go (hunk 1 above)
Comment (mszadkow) [reply test/util/e2e.go]: Good point, yes but only kindnet.
Kube-scheduler and Kube-controller manager are only pods.

File: test/e2e/multikueue/e2e_test.go (hunk 2 above)
Comment (mimowo) [reply test/e2e/multikueue/e2e_test.go]: Maybe, but it seems reasonable to also check Kueue itself

Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: Done.

File: test/util/e2e.go (hunk 1 above)
Comment (mimowo) [reply test/util/e2e.go]: there are more like etcd, etc: 
image


I see, for pods which are managed by higher level abstractions (Deployments, DaemonSets) don't check pods but rely on reporting on higher level abstractions. A failed deployment pod may be not bad as long as replaces.

For other Pods just enlist them like 
```golang
for _, podName := range []string"kube-scheduler", "kube-controller-manager"} {
  WaitForReadyPod(ctx, client, podName, "kube-system")
}
```

It sets the expectations more explicitly.

File: test/util/e2e.go [hunk 3]
```diff
@@ -383,6 +402,27 @@ func WaitForActivePodsAndTerminate(ctx context.Context, k8sClient client.Client,
 	}
 }
 
+func WaitForPodIsReady(ctx context.Context, k8sClient client.Client, restClient *rest.RESTClient, cfg *rest.Config, namespace string, timeout time.Duration, opts ...client.ListOption) {
```
Comment (mbobrovskyi) [inline test/util/e2e.go]:
```suggestion
func WaitForPodsInNamespaceAreReady(ctx context.Context, k8sClient client.Client, namespace string, timeout time.Duration, opts ...client.ListOption) {
```

File: test/util/e2e.go [hunk 4]
```diff
@@ -281,40 +281,59 @@ func waitForOperatorAvailability(ctx context.Context, k8sClient client.Client, k
...
 func WaitForKubeRayOperatorAvailability(ctx context.Context, k8sClient client.Client) {
 	// TODO: use ray-system namespace instead.
 	// See discussions https://github.com/kubernetes-sigs/kueue/pull/4568#discussion_r2001045775 and
 	// https://github.com/ray-project/kuberay/pull/2624/files#r2001143254 for context.
 	kroKey := types.NamespacedName{Namespace: "default", Name: "kuberay-operator"}
-	waitForOperatorAvailability(ctx, k8sClient, kroKey)
+	waitForOperatorAvailability(ctx, k8sClient, kroKey, true)
+}
+
+func WaitForKubeSystemControllersAvailability(ctx context.Context, k8sClient client.Client, restClient *rest.RESTClient, cfg *rest.Config, timeout time.Duration) {
```
Comment (mbobrovskyi) [inline test/util/e2e.go]:
```suggestion
func WaitForKubeSystemControllersAvailability(ctx context.Context, k8sClient client.Client, timeout time.Duration) {
```

File: test/e2e/multikueue/e2e_test.go [hunk 5]
```diff
@@ -1022,6 +1009,29 @@ var _ = ginkgo.Describe("MultiKueue", func() {
 						util.IgnoreConditionTimestampsAndObservedGeneration)))
 				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
 			})
+
+			ginkgo.By("Waiting for Kueue and kube-system pods to become active again", func() {
+				util.WaitForKueueAvailabilityNoRestartCountCheck(ctx, k8sWorker1Client)
+				util.WaitForKubeSystemControllersAvailability(ctx, k8sWorker1Client, worker1RestClient, worker1Cfg, util.StartUpTimeout)
```
Comment (mbobrovskyi) [inline test/e2e/multikueue/e2e_test.go]:
```suggestion
				util.WaitForKubeSystemControllersAvailability(ctx, k8sWorker1Client, worker1RestClient, worker1Cfg)
```
Do we need to propagate `timeout`? Can we use StartupTimeout inside function like we have in `waitForOperatorAvailability()`?

Comment (mbobrovskyi) [inline test/e2e/multikueue/e2e_test.go]:
```suggestion
				util.WaitForKubeSystemControllersAvailability(ctx, k8sWorker1Client, worker1RestClient, worker1Cfg, util.StartUpTimeout)
				util.WaitForKueueAvailabilityNoRestartCountCheck(ctx, k8sWorker1Client)
```
I think we should check kube-system first.

File: test/e2e/multikueue/e2e_test.go [hunk 6]
```diff
@@ -1022,6 +1009,29 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+			})
+
+			ginkgo.By("Checking if it is possible to use the cluster again", func() {
+				// After reconnecting the container to the network, when we try to get pods,
+				// we get it with the previous values (as before disconnect). Therefore, it
+				// takes some time for the cluster to restore them, and we got actually values.
+				// To be sure that the leader of kueue-control-manager successfully recovered
+				// we can check it by removing already created Cluster Queue.
+				util.ExpectObjectToBeDeletedWithTimeout(ctx, k8sWorker1Client, worker1Cq2, true, util.LongTimeout)
```
Comment (mbobrovskyi) [inline test/e2e/multikueue/e2e_test.go]: I think this is no longer needed, right?

File: test/e2e/multikueue/e2e_test.go [hunk 7]
```diff
@@ -1022,6 +1009,29 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+
+				// Extra check by creating and removing object with use of reconnected kueue.
+				rf := utiltesting.MakeResourceFlavor("other-default").Obj()
+				util.MustCreate(ctx, k8sWorker1Client, rf)
+				gomega.Eventually(func(g gomega.Gomega) {
+					createdRf := &kueue.ResourceFlavor{}
+					g.Expect(k8sWorker1Client.Get(ctx, client.ObjectKeyFromObject(rf), createdRf)).Should(gomega.Succeed())
+				}, util.Timeout, util.Interval).Should(gomega.Succeed())
+				util.ExpectObjectToBeDeleted(ctx, k8sWorker1Client, rf, true)
```
Comment (mbobrovskyi) [inline test/e2e/multikueue/e2e_test.go]: Is it enough just check for availability?

File: test/util/e2e.go [hunk 8]
```diff
@@ -281,40 +281,59 @@ func waitForOperatorAvailability(ctx context.Context, k8sClient client.Client, k
...
+	const ns = "kube-system"
+	for _, controller := range []string{
+		"kindnet",
+		"kube-controller-manager",
+		"kube-scheduler",
+	} {
```
Comment (mbobrovskyi) [inline test/util/e2e.go]: Maybe just find all Pods in the `kube-system` namespace instead of checking each controller individually?

File: test/util/e2e.go (hunk 3 above)
Comment (mimowo) [reply test/util/e2e.go]: Instead of checking all pods in namespace we should only check the "static" pods directly. Other pods can and should be checked by the availablity status of the orchestrating controller (Deployment or DaemonSet).

File: test/e2e/multikueue/e2e_test.go (hunk 7 above)
Comment (mimowo) [reply test/e2e/multikueue/e2e_test.go]: Yes, I think the checks are unnecessary.

Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: I don't agree, it's not enough.
From my observations test usually flakes at this extra check

File: test/util/e2e.go (hunk 8 above)
Comment (mszadkow) [reply test/util/e2e.go]: Like @mimowo said, some have higher level abstractions and I have to checks daemonsets and deployments.
I can check others but still I have to have the list.

File: test/e2e/multikueue/e2e_test.go (hunk 6 above)
Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: Actually I think this is very much needed.
IMHO we want to show operational state from the client's perspective and that's proven only when it can manipulate objects.

File: test/e2e/multikueue/e2e_test.go (hunk 5 above)
Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: sgtm

Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: We can

File: test/util/e2e.go (hunk 8 above)
Comment (mbobrovskyi) [reply test/util/e2e.go]: OK

File: test/e2e/multikueue/e2e_test.go (hunk 6 above)
Comment (mbobrovskyi) [reply test/e2e/multikueue/e2e_test.go]: But if all pods are available, shouldn't it work as expected?

File: test/e2e/multikueue/e2e_test.go (hunk 7 above)
Comment (mimowo) [reply test/e2e/multikueue/e2e_test.go]: Right, but in that case we should understand why it is flaking, because if all controllers are available I would the cluster is working ok. 

If the cluster is left by the test in such a weird state that all core controllers are avaialble , but we cannot create resources, then I would call the entire test wrong, and look for alternatives to `docker network disconnect`, maybe:
- block the traffic between clusters (represented as docker containers) temporarily using iptables, or
- just delete the api-server pod on the worker cluster to simulate a transient downtime of the worker - it should be recreated by kind in a couple of seconds.

File: test/e2e/multikueue/e2e_test.go (hunk 6 above)
Comment (mimowo) [reply test/e2e/multikueue/e2e_test.go]: +1, we should only rely on availability checks, if the cluster after docker network disconnect is left in corrupted state I would look for alternatives, see also https://github.com/kubernetes-sigs/kueue/pull/6466#discussion_r2256357333

File: test/e2e/multikueue/e2e_test.go (hunk 7 above)
Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: Agree, I will check what is causing the flake even if everything is in place.
I am just saying, how do we know it's working if we don't check it with this create/delete step...

Comment (mbobrovskyi) [reply test/e2e/multikueue/e2e_test.go]: > block the traffic between clusters (represented as docker containers) temporarily using iptables

We’ve already tried this solution, but it doesn’t work on macOS (see [#1971](https://github.com/kubernetes-sigs/kueue/pull/1971)).

File: test/util/e2e.go (hunk 1 above)
Comment (mszadkow) [reply test/util/e2e.go]: Done.

File: test/e2e/multikueue/e2e_test.go (hunk 6 above)
Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: I would keep those checks for now, let it proves to us it work as expected, we can remove it after a flawless week, wdyt?

Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: Ok, nvm, let it be availability checks only.

**Comment by mszadkow** [comment]
@mbobrovskyi @mimowo I think it's ready for final round.

File: test/util/e2e.go [hunk 9]
```diff
@@ -281,40 +281,73 @@ func waitForOperatorAvailability(ctx context.Context, k8sClient client.Client, k
...
+	ginkgo.By(fmt.Sprintf("Waiting for deployment %q to be available", deployKey.Name))
+	waitForDeploymentAvailability(ctx, k8sClient, deployKey, true)
+
+	for _, ds := range []string{
+		"kindnet",
+		"kube-proxy",
+	} {
+		dsKey := types.NamespacedName{Namespace: ns, Name: ds}
+		ginkgo.By(fmt.Sprintf("Waiting for daemonset %q to be available", ds))
+		waitForDamonSetAvailability(ctx, k8sClient, dsKey)
```
Comment (mimowo) [inline test/util/e2e.go]:
```suggestion
		waitForDaemonSetAvailability(ctx, k8sClient, dsKey)
```

File: test/util/e2e.go [hunk 10]
```diff
@@ -383,6 +416,44 @@ func WaitForActivePodsAndTerminate(ctx context.Context, k8sClient client.Client,
...
+		g.Expect(pods.Items).ToNot(gomega.BeEmpty(), "No pods found in namespace %q with options %v", namespace, podListOpts)
+		for _, p := range pods.Items {
+			g.Expect(p.Status.Conditions).To(gomega.ContainElement(gomega.BeComparableTo(corev1.PodCondition{
+				Type:   corev1.PodReady,
+				Status: corev1.ConditionTrue,
+			}, podCondIgnoreFields)))
+			g.Expect(p.Status.Conditions).To(gomega.ContainElement(gomega.BeComparableTo(corev1.PodCondition{
+				Type:   corev1.ContainersReady,
+				Status: corev1.ConditionTrue,
+			}, podCondIgnoreFields)))
```
Comment (mimowo) [inline test/util/e2e.go]: I don't think this is necessary when ContainersReady != False then kubelet will always set Ready=False, so when PodReady=True, then we know that ContainersReady=True. 

See: https://github.com/kubernetes/kubernetes/blob/8e6d788887034b799f6c2a86991a68a080bb0576/pkg/kubelet/status/generate.go#L123-L133

File: test/util/e2e.go [hunk 11]
```diff
@@ -383,6 +416,44 @@ func WaitForActivePodsAndTerminate(ctx context.Context, k8sClient client.Client,
...
+
+func waitForDamonSetAvailability(ctx context.Context, k8sClient client.Client, key types.NamespacedName) {
+	daemonset := &appsv1.DaemonSet{}
+	waitForAvailableStart := time.Now()
+	ginkgo.By(fmt.Sprintf("Waiting for availability of deployment: %q", key))
+	gomega.EventuallyWithOffset(2, func(g gomega.Gomega) error {
+		g.Expect(k8sClient.Get(ctx, key, daemonset)).To(gomega.Succeed())
+		g.Expect(daemonset.Status.DesiredNumberScheduled).To(gomega.Equal(daemonset.Status.CurrentNumberScheduled))
+		g.Expect(daemonset.Status.DesiredNumberScheduled).To(gomega.Equal(daemonset.Status.NumberAvailable))
+		g.Expect(daemonset.Status.DesiredNumberScheduled).To(gomega.Equal(daemonset.Status.NumberReady))
```
Comment (mimowo) [inline test/util/e2e.go]:
```suggestion
g.Expect(daemonset.Status.DesiredNumberScheduled).To(gomega.Equal(daemonset.Status.NumberAvailable))
```
I don't think there is a need to look for Ready or Scheduled since Available is the strongest condition.

File: test/util/e2e.go [hunk 12]
```diff
@@ -383,6 +416,44 @@ func WaitForActivePodsAndTerminate(ctx context.Context, k8sClient client.Client,
...
+		}
+	}, StartUpTimeout, Interval).Should(gomega.Succeed())
+	ginkgo.GinkgoLogr.Info("Pod is available in the cluster", "pod[0]", pods.Items[0].Name, "waitingTime", time.Since(waitForAvailableStart))
+}
+
+func waitForDamonSetAvailability(ctx context.Context, k8sClient client.Client, key types.NamespacedName) {
+	daemonset := &appsv1.DaemonSet{}
+	waitForAvailableStart := time.Now()
+	ginkgo.By(fmt.Sprintf("Waiting for availability of deployment: %q", key))
+	gomega.EventuallyWithOffset(2, func(g gomega.Gomega) error {
```
Comment (mimowo) [inline test/util/e2e.go]:
```suggestion
	gomega.EventuallyWithOffset(2, func(g gomega.Gomega) {
```
why returning error?

File: test/util/e2e.go [hunk 13]
```diff
@@ -383,6 +416,44 @@ func WaitForActivePodsAndTerminate(ctx context.Context, k8sClient client.Client,
 	}
 }
 
+func waitForPodAvailability(ctx context.Context, k8sClient client.Client, namespace string, opts ...client.ListOption) {
```
Comment (mimowo) [inline test/util/e2e.go]: I think this is much more compliacted than needed using the list of options, and also inconsistent with the logging in the line https://github.com/kubernetes-sigs/kueue/pull/6466/files#diff-2e6108aa98030ed90991bf0aedca66477b40aa916513427588352404443fd685R440 which always reports first Pod. 

Can we just `Get` the Pod by namespace and name?

File: test/util/e2e.go [hunk 14]
```diff
@@ -263,7 +263,7 @@ func waitForOperatorAvailability(ctx context.Context, k8sClient client.Client, k
 				// To make sure that we don't have restarts of controller-manager.
 				// If we have that's mean that something went wrong, and there is
 				// no needs to continue trying check availability.
-				if cs.RestartCount > 0 {
+				if checkRestartCount && cs.RestartCount > 0 {
```
Comment (mimowo) [inline test/util/e2e.go]: This check isn't really testing "Availability".

 It should be done by another function "VerifyNoControllerRestarts` in the first place, but since it is tangled like that already then fine for this PR, but we should consider refactoring at some point.

File: test/util/e2e.go (hunk 13 above)
Comment (mszadkow) [reply test/util/e2e.go]: We know the namespace, but we don't know the name, we need label to identify the pod.
There is indeed no need for the whole list, I can pass single label, that's all and also name of the component for logging.

Comment (mimowo) [reply test/util/e2e.go]: I don't understand why we don't know pod name, aren't the static pods having predetermined names like kube-apiserver?

Comment (mszadkow) [reply test/util/e2e.go]: nvm, yes, we know the name

Comment (mszadkow) [reply test/util/e2e.go]: Done.

File: test/util/e2e.go (hunk 14 above)
Comment (mszadkow) [reply test/util/e2e.go]: Good point, can be a small follow up.

**Review by mimowo — COMMENTED** [review]
LGTM

@mszadkow were you able to check if we this eliminates the flakes? 

THen we could follow up with splitting the tests into two files again.

**Comment by mszadkow** [comment]
> LGTM
> 
> @mszadkow were you able to check if we this eliminates the flakes?
> 
> THen we could follow up with splitting the tests into two files again.


> LGTM
> 
> @mszadkow were you able to check if we this eliminates the flakes?
> 
> THen we could follow up with splitting the tests into two files again.

I am doing local test with repetitions, I will do them once more before I can confirm.
Also at least 5 times retest in CI, when it's ready.

**Comment by mszadkow** [comment]
I have enhanced the tests with endpoint check and resetting of the cluster client instance.
The test still flakes in one of two ways:
Either failed request (webhook) or object that should have been deleted is still present.

I am out of ideas, I can try what you suggested @mimowo 

> just delete the api-server pod on the worker cluster to simulate a transient downtime of the worker - it should be recreated by kind in a couple of seconds.

File: test/e2e/multikueue/e2e_test.go [hunk 15]
```diff
@@ -1022,6 +1009,22 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
+
+			ginkgo.By("Check kueue-webhook-service endpoints ready", func() {
+				gomega.Eventually(func(g gomega.Gomega) {
+					esl := &discoveryv1.EndpointSliceList{}
+					g.Expect(k8sWorker1Client.List(ctx, esl, client.MatchingLabels{"kubernetes.io/service-name": "kueue-webhook-service"})).To(gomega.Succeed())
+					g.Expect(esl.Items).ToNot(gomega.BeEmpty(), "kueue-webhook-service should have endpoints")
+					for _, e := range esl.Items {
+						g.Expect(e.Endpoints).ToNot(gomega.BeEmpty(), "kueue-webhook-service should have endpoints")
+					}
+				}, util.StartUpTimeout, util.Interval).Should(gomega.Succeed())
```
Comment (mimowo) [inline test/e2e/multikueue/e2e_test.go]: This should be not necessary as testing the webhook availability is already part of Kueue availability via the probes.

**Comment by mimowo** [comment]
> I have enhanced the tests with endpoint check and resetting of the cluster client instance. The test still flakes in one of two ways: Either failed request (webhook) or object that should have been deleted is still present.
> 
> I am out of ideas, I can try what you suggested @mimowo

Yeah, all of this is getting too complex. I think the test is too disruptive and is missing the point.

I think what we really want to test is just network disconnect. 

I'm not an expert on networking, but I'm pretty sure we could use NetworkPolicy to block the Ingress (incoming traffic) from the manager cluster if we knew its IP, can you check the Gemini recommentation :)
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-specific-cluster-ip
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0 # Allow traffic from ANY source IP...
        except:
          - 198.51.100.10/32 # ...EXCEPT for this one.
```
then `kubectl apply -f block-ip-policy.yaml`

File: test/e2e/multikueue/e2e_test.go (hunk 15 above)
Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go]: Removed.

**Comment by mszadkow** [comment]
Steps to eliminate flakines:
* Bind API Server address instead of docker connect/disconnect
* Wait for Kueue availability
* Wait for Kind cluster related components availability
* Add timeout for objects deletion after each test

File: test/e2e/multikueue/e2e_test.go [hunk 16]
```diff
@@ -171,11 +171,11 @@ var _ = ginkgo.Describe("MultiKueue", func() {
...
 
-		util.ExpectObjectToBeDeleted(ctx, k8sWorker1Client, worker1Cq, true)
-		util.ExpectObjectToBeDeleted(ctx, k8sWorker1Client, worker1Flavor, true)
+		util.ExpectObjectToBeDeletedWithTimeout(ctx, k8sWorker1Client, worker1Cq, true, util.LongTimeout)
+		util.ExpectObjectToBeDeletedWithTimeout(ctx, k8sWorker1Client, worker1Flavor, true, util.LongTimeout)
 
-		util.ExpectObjectToBeDeleted(ctx, k8sWorker2Client, worker2Cq, true)
-		util.ExpectObjectToBeDeleted(ctx, k8sWorker2Client, worker2Flavor, true)
+		util.ExpectObjectToBeDeletedWithTimeout(ctx, k8sWorker2Client, worker2Cq, true, util.LongTimeout)
+		util.ExpectObjectToBeDeletedWithTimeout(ctx, k8sWorker2Client, worker2Flavor, true, util.LongTimeout)
```
Comment (mimowo) [inline test/e2e/multikueue/e2e_test.go]: Can you extract to a preparatory PR , I would like to cherrypick this to 0.12 too

File: test/e2e/multikueue/e2e_test.go [hunk 17]
```diff
@@ -1022,6 +1000,11 @@ var _ = ginkgo.Describe("MultiKueue", func() {
 						util.IgnoreConditionTimestampsAndObservedGeneration)))
 				}, util.LongTimeout, util.Interval).Should(gomega.Succeed())
 			})
+
+			ginkgo.By("Waiting for Kueue and kube-system pods to become active again", func() {
+				util.WaitForKubeSystemControllersAvailability(ctx, k8sWorker1Client, worker1Container)
```
Comment (mimowo) [inline test/e2e/multikueue/e2e_test.go:1007]: Do we actually need to wait for the kube components? I would assume that with the bind-address to 127.0.01,they don't get disrupted. Maybe they get disrupted while kube-apiserver is  restarting though?

Comment (mszadkow) [reply test/e2e/multikueue/e2e_test.go:1007]: Yes, they do get disrupted and they are restart.

**Comment by mimowo** [comment]
> Steps to eliminate flakines:
> * Bind API Server address instead of docker connect/disconnect
> * Wait for Kueue availability
> * Wait for Kind cluster related components availability
> * Add timeout for objects deletion after each test 

Does it eliminate the flakes allowing to reliably run tests after the suite?

File: test/e2e/multikueue/e2e_test.go [hunk 18]
```diff
@@ -171,11 +171,11 @@ var _ = ginkgo.Describe("MultiKueue", func() {
 		gomega.Expect(util.DeleteNamespace(ctx, k8sWorker1Client, worker1Ns)).To(gomega.Succeed())
 		gomega.Expect(util.DeleteNamespace(ctx, k8sWorker2Client, worker2Ns)).To(gomega.Succeed())
 
-		util.ExpectObjectToBeDeleted(ctx, k8sWorker1Client, worker1Cq, true)
-		util.ExpectObjectToBeDeleted(ctx, k8sWorker1Client, worker1Flavor, true)
+		util.ExpectObjectToBeDeletedWithTimeout(ctx, k8sWorker1Client, worker1Cq, true, util.LongTimeout)
```
Comment (mimowo) [inline test/e2e/multikueue/e2e_test.go]: Please rebase

File: test/util/e2e.go [hunk 19]
```diff
@@ -250,23 +250,28 @@ func exportKindLogs(ctx context.Context, kindClusterName string) {
...
 		g.Expect(k8sClient.Get(ctx, key, deployment)).To(gomega.Succeed())
 		g.Expect(k8sClient.List(ctx, pods, client.InNamespace(key.Namespace), client.MatchingLabels(deployment.Spec.Selector.MatchLabels))).To(gomega.Succeed())
+		g.Expect(pods.Items).To(gomega.HaveLen(int(deployment.Status.AvailableReplicas)))
 		for _, pod := range pods.Items {
 			for _, cs := range pod.Status.ContainerStatuses {
 				// To make sure that we don't have restarts of controller-manager.
 				// If we have that's mean that something went wrong, and there is
 				// no needs to continue trying check availability.
-				if cs.RestartCount > 0 {
+				if checkRestartCount && cs.RestartCount > 0 {
```
Comment (mimowo) [inline test/util/e2e.go]: Do we actually see Kueue containers getting restarted? This is a bit weird, I would assume the entire Pod gets replaced. Maybe this was needed before when we used network disconnect, but is no longer needed?

File: test/util/e2e.go [hunk 20]
```diff
@@ -250,23 +250,28 @@ func exportKindLogs(ctx context.Context, kindClusterName string) {
...
-func waitForOperatorAvailability(ctx context.Context, k8sClient client.Client, key types.NamespacedName) {
+func waitForDeploymentAvailability(ctx context.Context, k8sClient client.Client, key types.NamespacedName, checkRestartCount bool) {
 	deployment := &appsv1.Deployment{}
 	pods := &corev1.PodList{}
 	waitForAvailableStart := time.Now()
 	ginkgo.By(fmt.Sprintf("Waiting for availability of deployment: %q", key))
 	gomega.EventuallyWithOffset(2, func(g gomega.Gomega) error {
 		g.Expect(k8sClient.Get(ctx, key, deployment)).To(gomega.Succeed())
 		g.Expect(k8sClient.List(ctx, pods, client.InNamespace(key.Namespace), client.MatchingLabels(deployment.Spec.Selector.MatchLabels))).To(gomega.Succeed())
+		g.Expect(pods.Items).To(gomega.HaveLen(int(deployment.Status.AvailableReplicas)))
```
Comment (mimowo) [inline test/util/e2e.go]: Why this check? I think this should be done via the Deployment itself.

File: test/util/e2e.go [hunk 21]
```diff
@@ -250,23 +250,28 @@ func exportKindLogs(ctx context.Context, kindClusterName string) {
...
 			for _, cs := range pod.Status.ContainerStatuses {
 				// To make sure that we don't have restarts of controller-manager.
 				// If we have that's mean that something went wrong, and there is
 				// no needs to continue trying check availability.
-				if cs.RestartCount > 0 {
+				if checkRestartCount && cs.RestartCount > 0 {
 					return gomega.StopTrying(fmt.Sprintf("%q in %q has restarted %d times", cs.Name, pod.Name, cs.RestartCount))
 				}
 			}
+			g.Expect(pod.Status.Conditions).To(gomega.ContainElement(gomega.BeComparableTo(
```
Comment (mimowo) [inline test/util/e2e.go]: Why do we check on individual Pods directly? I would like to eliminate such checks if possible, or understand why we do them, because the orchestrator for Pods is Deployment in this case.

File: test/util/e2e.go (hunk 14 above)
Comment (mimowo) [reply test/util/e2e.go]: I'm still wondering why this is needed. I would expect the newly recreated pods have RestartCount=0. Let me know if I'm missing something. Maybe the root problem is that you are scanning statuses of already Failed pods `g.Expect(k8sClient.List(ctx, pods, client.InNamespace(key.Namespace), client.MatchingLabels(deployment.Spec.Selector.MatchLabels))).To(gomega.Succeed())` would also returned Failed IIUC.

**Comment by mimowo** [comment]
/retitle MultiKueue testing: allow running tests after: The connection to a worker cluster is unreliable

File: test/util/e2e.go (hunk 14 above)
Comment (mszadkow) [reply test/util/e2e.go]: In fact pods are not recreated, rather their containers are restarted.
But if we move Deployment status condition check above before iterating over pods this should give the same level of certainty.

File: test/util/e2e.go (hunk 19 above)
Comment (mszadkow) [reply test/util/e2e.go]: Yes, all operator pods (not only Kueue, but also JobSet, Kubeflow, etc.) got restarted due to:
```
ERROR	setup	kueue/main.go:235	Unable to setup indexes	{"error": "setting index on queue for Workload: failed to get server groups: Get \"[https://10.96.0.1:443/api](https://10.96.0.1/api)\": dial tcp 10.96.0.1:443: connect: connection refused"}
```

File: test/util/e2e.go (hunk 21 above)
Comment (mszadkow) [reply test/util/e2e.go]: So you say, individual pods does not matter because the whole Eventually fails if the Deployment condition is not `DeploymentAvailable` ?

File: test/util/e2e.go (hunk 19 above)
Comment (mimowo) [reply test/util/e2e.go]: ack, please keep the comment open for posterity, or update the PR description then resolve

File: test/e2e/multikueue/e2e_test.go (hunk 17 above)
Comment (mimowo) [reply test/e2e/multikueue/e2e_test.go:1007]: Please update the PR description with more details then

File: test/util/e2e.go (hunk 21 above)
Comment (mimowo) [reply test/util/e2e.go]: I would expect so, I'm still puzzled why this is not enough (or if not enough)

File: test/util/e2e.go (hunk 14 above)
Comment (mimowo) [reply test/util/e2e.go]: I see, yeah I see they restart "in place" because there is no rollout, just temporary api-server "downtime". ack

File: test/util/e2e.go (hunk 20 above)
Comment (mszadkow) [reply test/util/e2e.go]: This one I removed, as it is not always correct.

**Comment by mimowo** [comment]
/lgtm
/approve
/cherrypick release-0.13
Thanks 👍 Let's give it a try! It is anyway better than before!
