### PR TITLE
Fix race condition that prevents Workload from reflecting Inadmissible status.

### LINKED ISSUE #6789: Race Condition Prevents Workload from Reflecting Inadmissible Status
**What happened**

The `Workload` status is not always updated to reflect the `Inadmissible` condition, even when the workload is clearly unschedulable under current cluster conditions. This leads to confusion for users and limits the usefulness of status-based observability for automation or debugging.

Note: A `Warning` event is correctly recorded, and the scheduler logs the following message:

```
"couldn't assign flavors to pod set main: insufficient unused quota for cpu in flavor default-flavor, 100m more needed"
```

**What you expected to happen**

When a workload cannot be admitted due to unmet scheduling constraints (e.g., resource quota, flavor mismatch, node selector, etc.), its `.status.conditions` should reflect the `Inadmissible` condition with an appropriate `reason` and `message`.

**Anything else we need to know?**

I believe this issue is caused by a race condition between the scheduler and the workload controller. The scheduler logs the following error:

```
{"level":"error","ts":"2025-09-10T20:56:50.879693-07:00","logger":"scheduler","caller":"scheduler/scheduler.go:776","msg":"Could not update Workload status","schedulingCycle":2,"error":"Operation cannot be fulfilled on workloads.kueue.x-k8s.io \"job-demo-2-56c73\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"..."}
```

When the scheduler fails to patch the admission status, it merely [logs the error](https://github.com/kubernetes-sigs/kueue/blob/a3887653ef8e71ef892afd327e9c0b35fc2471f9/pkg/scheduler/scheduler.go#L776) and relies on a future scheduling cycle to reattempt scheduling and update the workload status. However, unlike a controller-runtime reconciler, the scheduler does **not** immediately retry this workload scheduling, leading to status drift.

This results in workloads appearing pending without any `Inadmissible` condition, even though their scheduling failure is known and logged.

### **How to reproduce it (as minimally and precisely as possible)**

I encountered this issue in a MultiKueue setup, though I do not believe it is exclusive to MultiKueue.

**MultiKueue setup:**

* `worker1`: 2 CPUs
* `worker2`: 2 CPUs
* `manager`: 4 CPUs (aggregated)

**Steps:**

1. Submit a job requesting 3 CPUs — this will be placed and block quota in the manager cluster but won't fit in any worker cluster.
2. Submit a second job requesting `1100m` CPU.
3. Observe the second workload — in many cases, it will remain in `Pending` without an `Inadmissible` condition, even though it cannot be scheduled due to quota blockage.

In this setup, I can reproduce the issue with a frequency > 50%.

### **Environment**

* **Kubernetes version** (use `kubectl version`):
* **Kueue version** (use `git describe --tags --dirty --always`):
* **Cloud provider or hardware configuration**:
* **OS** (e.g., `cat /etc/os-release`):
* **Kernel** (e.g., `uname -a`):
* **Install tools**:
* **Others**:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix race condition that prevents Workload from reflecting Inadmissible status.

#### Which issue(s) this PR fixes:

Fixes #6789

#### Does this PR introduce a user-facing change?

```release-note
Fix the race condition which could result that the Kueue scheduler occasionally does not record the reason
for admission failure of a workload if the workload was modified in the meanwhile by another controller.
```

### CODE REVIEW

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Fix the race condition which could result that the Kueue scheduler occasionally does not record the reason
for admission failure of a workload if the workload was modified in the meanwhile by another controller.
```

**Comment by mimowo** [comment]
@mbobrovskyi the change is rather easy so I'm ok to merge, but I'm considering if we could write a test for the change? 

Maybe it could be unit test, or integration we also recently following this example: https://github.com/kubernetes-sigs/kueue/pull/7665

We could then reuse the test for the retry when we implement the patch. wdyt?

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -798,7 +798,7 @@ func (s *Scheduler) requeueAndUpdate(ctx context.Context, e entry) {
 				updated = true
 			}
 			return updated, nil
-		}); err != nil {
+		}, workload.WithLooseOnApply()); err != nil {
```
Comment (tenzen-y) [inline pkg/scheduler/scheduler.go:801]: Isn't this the cause that the old resource version will be patched?
I suspect that we will lose the atomic Admission.

Comment (mimowo) [reply pkg/scheduler/scheduler.go:801]: Yes it might mean that we will patch older version. However this is also what we do during admission from within scheduler. Since scheduler is the only entity which assigns admission I don't see it being problematic. Do you see some scenario Yuki?

Comment (tenzen-y) [reply pkg/scheduler/scheduler.go:801]: IIRC, the admission used SSA previously. So, the resource versions could be ignored.
But, now, we use the Patch operation for that (correct me if my understanding is incorrect).

So, I am worried about introducing a non-strict operation for that. 
The current resource version error -> requeue sounds reasonable for the atomic policy.

AFAIK, you don't observe performance regressions for the requeueing due to conflict errors, right?

Comment (mimowo) [reply pkg/scheduler/scheduler.go:801]: You are partly correct. We are not yet using Patch. The LooseOnApply is used specifically to use Loose semantics for SSA. The semantics for Patch (still alpha) remains strict. For Patch Mike is working on the retry

Comment (mimowo) [reply pkg/scheduler/scheduler.go:801]: > AFAIK, you don't observe performance regressions for the requeueing due to conflict errors, right?

We don't observe performance regression for using Patch, yes. However, I think this change to use patch might be for 0.16 as we already have many changes in this release.

**Comment by mbobrovskyi** [comment]
> @mbobrovskyi the change is rather easy so I'm ok to merge, but I'm considering if we could write a test for the change?
> 
> Maybe it could be unit test, or integration we also recently following this example: #7665
> 
> We could then reuse the test for the retry when we implement the patch. wdyt?

Added unit test.

File: pkg/scheduler/scheduler_test.go [hunk 2]
```diff
@@ -9109,3 +9110,189 @@ func TestResourcesToReserve(t *testing.T) {
 		})
 	}
 }
+
+func TestSchedulerWithRaceCondition(t *testing.T) {
```
Comment (mimowo) [inline pkg/scheduler/scheduler_test.go]:
```suggestion
func TestSchedulerWhenWorkloadModifiedConcurrently(t *testing.T) {
```
nit the previous name suggests the race condition is inside scheduler

File: pkg/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -9109,3 +9110,189 @@ func TestResourcesToReserve(t *testing.T) {
...
+				features.SetFeatureGateDuringTest(t, feature, enabled)
+			}
+			ctx, log := utiltesting.ContextWithLog(t)
+			clientBuilder := utiltesting.NewClientBuilder().
+				WithObjects(ns.DeepCopy(), rf.DeepCopy(), cq.DeepCopy(), lq.DeepCopy(), tc.workload).
+				WithStatusSubresource(&kueue.Workload{}).
+				WithInterceptorFuncs(interceptor.Funcs{
+					SubResourcePatch: func(ctx context.Context, c client.Client, subResourceName string, obj client.Object, patch client.Patch, opts ...client.SubResourcePatchOption) error {
+						if _, ok := obj.(*kueue.Workload); ok && subResourceName == "status" {
+							// Simulate race condition.
```
Comment (mimowo) [inline pkg/scheduler/scheduler_test.go]:
```suggestion
							// Simulate concurrent modification by another controller
```

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/scheduler/scheduler.go:801]: > You are partly correct. We are not yet suing Patch. The LooseOnApply is used specifically to use Loose semantics for SSA. The semantics for Patch (still alpha) remains strict. For Patch Mike is working on the retry

I think that PATCH with non-strict mode does not look safe since the Workload objects are accessed by multiple components like Kueue, external-manager (implement JobFramework), Dispatchers, and AdmissionChecks.

So, I think that we should avoid this mode when we enable the PATCH operation.

**Comment by mimowo** [comment]
I triggered tentatively cherrypicks to 0.13 and 0.14, but I'm aware there has been many changes to the SSA / patch mechanics recently, so if hard to cherrypick, then we can skip, and just recommend users updating to 0.15. Please check and let us know how tricky this is @mbobrovskyi

**Comment by tenzen-y** [comment]
As I mentioned in https://github.com/kubernetes-sigs/kueue/pull/7845#discussion_r2558821167, it would be better to use strict mode when performing a PATCH operation.

Actually, we don't observe performance regression. So, I think we should respect atomic behavior in strict mode.

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (mimowo) [reply pkg/scheduler/scheduler.go:801]: This is why we have two separate options: LooseOnApply, and LooseOnPatch. We only change LooseOnApply in this PR.

**Comment by mimowo** [comment]
Correct, when we enable PATCH we will need to use strict. We don't observe performance regression so we could just do it. However, for this specific issue, if we use strict PATCH without retry, then the condition will not be recorded. So, the task by @mbobrovskyi to retry when using PATCH is important for this case.

**Comment by tenzen-y** [comment]
> This is why we have two separate options: LooseOnApply, and LooseOnPatch. We only change LooseOnApply in this PR.

> Correct, when we enable PATCH we will need to use strict. We don't observe performance regression so we could just do it. However, for this specific issue, if we use strict PATCH without retry, then the condition will not be recorded. So, the task by @mbobrovskyi to retry when using PATCH is important for this case.

That makes sense. For the Apply operation, that sounds reasonable to me.
For the Patch operation, let' revisit how to handle that in PATCH retry mechanism PR or PATCH graduation PR 👍
