### PR TITLE
[Fix] Synchronise access to RuntimeInfo to avoid data race

### LINKED ISSUE #7078: [flaky test] MultiKueue Should run a TrainJob on worker if admitted
/kind flake

**What happened**:

example: 
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7077/pull-kueue-test-integration-multikueue-main/1973001871303905280

**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:

I think this started after re-enabling the test in https://github.com/kubernetes-sigs/kueue/pull/7068

unfortunately no more details:

```
/home/prow/go/src/sigs.k8s.io/kueue/test/integration/framework/framework.go:145
------------------------------
[DeferCleanup (Suite)] PASSED [0.001 seconds]
[DeferCleanup (Suite)] 
/home/prow/go/src/sigs.k8s.io/kueue/test/integration/framework/framework.go:145
------------------------------
[ReportAfterSuite] PASSED [2.849 seconds]
[ReportAfterSuite] Autogenerated ReportAfterSuite for --json-report --junit-report
autogenerated by Ginkgo
------------------------------
Ran 31 of 31 Specs in 169.067 seconds
SUCCESS! -- 31 Passed | 0 Failed | 0 Pending | 0 Skipped
Ginkgo ran 1 suite in 4m40.050654998s
Test Suite Failed
make: *** [Makefile-test.mk:90: test-multikueue-integration] Error 1

```

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Synchronise to avoid data race related to accessing kubeflow trainer `RuntimeInfo`.
#### Which issue(s) this PR fixes:

Fixes #7078 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/jobs/trainjob/trainjob_controller.go [hunk 1]
```diff
@@ -162,6 +165,9 @@ func (t *TrainJob) PodLabelSelector() string {
 }
 
 func getChildJobSet(t *TrainJob) (*jobsetapi.JobSet, error) {
+	getChildJobSetMutex.Lock()
+	defer getChildJobSetMutex.Unlock()
```
Comment (mimowo) [inline pkg/controller/jobs/trainjob/trainjob_controller.go]: Can you instead wrap just calling `runtime.RuntimeInfo`? For simplity you can move that invocation to another helper function

```golang
func runtimeInfo(t *TrainJob) (*info, error) {
   runtimeInfoMutex.Lock()
	defer runtimeInfoMutex.Unlock()
   return runtime.RuntimeInfo(trainJob, trSpec.Template, trSpec.MLPolicy, trSpec.PodGroupPolicy)
}
```

**Review by mimowo — COMMENTED** [review]
Have you had a chance to test locally that it fixes the flake?

File: pkg/controller/jobs/trainjob/trainjob_controller.go (hunk 1 above)
Comment (mbobrovskyi) [reply pkg/controller/jobs/trainjob/trainjob_controller.go]: Also move mtx to trainJobReconciler.

**Comment by mszadkow** [comment]
> Have you had a chance to test locally that it fixes the flake?

This is just a matter of repetitions, it's running for 20 runs so far, I will increase it locally to 100 to make sure.
Without the lock it usually fails in 10-20 runs.

File: pkg/controller/jobs/trainjob/trainjob_controller.go (hunk 1 above)
Comment (mszadkow) [reply pkg/controller/jobs/trainjob/trainjob_controller.go]: Ok, will do

File: pkg/controller/jobs/trainjob/trainjob_controller.go [hunk 2]
```diff
@@ -190,6 +192,13 @@ func getChildJobSet(t *TrainJob) (*jobsetapi.JobSet, error) {
 	return jobsetApplyToJobset(jobsetApply)
 }
 
+func (r *trainJobReconciler) runtimeInfo(runtime kftrainerruntime.Runtime, trainJob *kftrainer.TrainJob, trSpec *kftrainer.TrainingRuntimeSpec) (*kftrainerruntime.Info, error) {
```
Comment (mimowo) [inline pkg/controller/jobs/trainjob/trainjob_controller.go:196]: please also add TODO to remove the mutex once the RuntimeInfo is thread safe and open issue for tracking in the kubełet Trainer.

Comment (mszadkow) [reply pkg/controller/jobs/trainjob/trainjob_controller.go:196]: Done.
