### PR TITLE
Fix overadmission after deleting resource from borrowing CQ.

### LINKED ISSUE #2678: Overadmission after deleting resource from borrowing CQ
Consider the following scenario. We have two CQs in the same Cohort:
```
CQ1:
  1 CPU, 1 Memory
CQ2:
  2 CPU, 1 Memory
```

First, create WL1 in CQ1 which uses (2 CPU, 2 Memory)
Next, create WL2 in CQ2 which uses (1 CPU, 1 Memory). WL2 is initially suspended, as there is no available Memory.

Update the CQ definitions so that CQ1 no longer provides Memory
```
CQ1:
  1 CPU
CQ2:
  2 CPU, 1 Memory
```
WL2 admits, while WL1 is still running. We have admitted (3 CPU, 3 Memory), while the Cohort has total of (3 CPU, 1 Memory).

We filter out usage of no longer existing `FlavorResources` [here](https://github.com/kubernetes-sigs/kueue/blob/d6cbd8c77e9a37fd172452960bd7a87f89b3be47/pkg/cache/clusterqueue.go#L170-L171)

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix overadmission after deleting resource from borrowing CQ.

#### Which issue(s) this PR fixes:

Fixes #2678

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
/test all

Let me check if the prow job will be started here.

https://github.com/kubernetes-sigs/kueue/pull/2849#issuecomment-2303328536

**Comment by tenzen-y** [comment]
As we can see here, no prow jobs were triggered.

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kueue-build-image-main

**Comment by tenzen-y** [comment]
> As we can see here, no prow jobs were triggered.
> 
> https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kueue-build-image-main

I guess that this problem happend by "Aug 21, 2024: Prow is being migrated on Wednesday, August 21! Expect CI disruption and avoid releases that week. ([details](https://groups.google.com/a/kubernetes.io/g/dev/c/qzNYpcN5la4))".

File: pkg/cache/clusterqueue.go [hunk 1]
```diff
@@ -225,14 +225,24 @@ func (c *clusterQueue) update(in *kueue.ClusterQueue, resourceFlavors map[kueue.
...
 func filterFlavorQuantities(orig resources.FlavorResourceQuantities, resourceGroups []kueue.ResourceGroup) resources.FlavorResourceQuantities {
 	ret := make(resources.FlavorResourceQuantities, len(orig))
+
+	for key, value := range orig {
+		if value > 0 {
+			ret[key] = value
+		}
+	}
+
 	for _, rg := range resourceGroups {
```
Comment (gabesaba) [inline pkg/cache/clusterqueue.go:235]: We shouldn't need to differentiate between zero value and absent value for `usage`. Can we delete this logic, and rename the function to something like "filterZeros"? The only annoying part is this requires test updates...

Furthermore, I'm tempted to delete this function altogether [1] - and be okay leaking memory for a few int64s

[1] and also update newClusterQueue to allocate these maps, as we rely on this function for allocating the maps

Comment (mbobrovskyi) [reply pkg/cache/clusterqueue.go:235]: > Furthermore, I'm tempted to delete this function altogether [1] - and be okay leaking memory for a few int64s. 

I thought about it too. Just don't know is it using keys somewhere. Will check.

Comment (mbobrovskyi) [reply pkg/cache/clusterqueue.go]: I removed `filterLocalQueueUsage` and fixed tests. Looks like working find. Thanks.

**Comment by gabesaba** [comment]
/lgtm

thanks for the fix :)

File: pkg/cache/cache_test.go [hunk 2]
```diff
@@ -111,30 +111,22 @@ func TestCacheClusterQueueOperations(t *testing.T) {
...
-					Usage: resources.FlavorResourceQuantities{
-						{Flavor: "default", Resource: corev1.ResourceCPU}: 0,
-					},
-					AdmittedUsage: resources.FlavorResourceQuantities{
-						{Flavor: "default", Resource: corev1.ResourceCPU}: 0,
-					},
-					Status:     active,
-					Preemption: defaultPreemption,
-					FairWeight: oneQuantity,
+					Usage:                         resources.FlavorResourceQuantities{},
```
Comment (alculquicondor) [inline pkg/cache/cache_test.go:114]: you can use `cmpopts.EquateEmpty` to avoid having to define these empty maps.

File: pkg/cache/clusterqueue.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/cache/clusterqueue.go]: Looking great without the `filterLocalQueueUsage` approach.
Thanks.

File: pkg/cache/cache_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply pkg/cache/cache_test.go]: Done.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

File: test/integration/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -2207,4 +2209,137 @@ var _ = ginkgo.Describe("Scheduler", func() {
...
+				cq1.Spec.ResourceGroups = nil
+				cq1Wrapper := &testing.ClusterQueueWrapper{ClusterQueue: *cq1}
+				cq1Wrapper.ResourceGroup(*testing.MakeFlavorQuotas(onDemandFlavor.Name).
+					Resource(corev1.ResourceCPU, "1").
+					Obj(),
+				)
+				cq1 = cq1Wrapper.Obj()
+				g.Expect(k8sClient.Update(ctx, cq1)).Should(gomega.Succeed())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+
```
Comment (tenzen-y) [inline test/integration/scheduler/scheduler_test.go:2314]: My question is what happens if the kueue-manager is restarted after the CQ resources are reduced?

I guess that the overadmission will happen because the kueue-manager doesn't know the previous CQ resourceGroup parameters, right?

Comment (tenzen-y) [reply test/integration/scheduler/scheduler_test.go:2314]: Oh, that makes sense. Thank you for the clarifications!

Comment (mbobrovskyi) [reply test/integration/scheduler/scheduler_test.go:2314]: I manually tested this case again to make sure it works fine. After restarting, the controller manager is still not admit the workload.

```
couldn''t assign flavors to pod set main: insufficient unused quota
        in cohort for memory in flavor fl, 2Gi more needed
```

Comment (tenzen-y) [reply test/integration/scheduler/scheduler_test.go:2314]: That sounds great!
Thank you!

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix over-admission after deleting resources from borrowing ClusterQueue. 
```

**Comment by tenzen-y** [comment]
@mbobrovskyi, Could you take a look at the cherry-pick?
