### PR TITLE
Drop remove operations from webhook patches

### LINKED ISSUE #2878: Kueue mutating webhooks drops fields in KubeRay resources
**What happened**:

When using Kueue with KubeRay, new fields in KubeRay that are not recognized by Kueue are dropped during defaulting. Here's an example using Kind and RayJob:

Create cluster:
```
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋
```

Install Kueue:
```
$ kubectl apply --server-side -f https://github.com/kubernetes-sigs/kueue/releases/download/v0.8.0/manifests.yaml
namespace/kueue-system serverside-applied
...
...
```

Install latest release candidate of KubeRay:
```
$ helm install kuberay-operator kuberay/kuberay-operator --version 1.2.0-rc.0
NAME: kuberay-operator
LAST DEPLOYED: Thu Aug 22 16:03:11 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

Deploy Kueue resources:
```
$ kubectl apply -f kueue-resources.yaml
resourceflavor.kueue.x-k8s.io/default-flavor created
clusterqueue.kueue.x-k8s.io/cluster-queue created
localqueue.kueue.x-k8s.io/local-queue created
```

Create a RayJob with a reference to the local queue:
```
$ cat rayjob.yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: image-resize
  labels:
    kueue.x-k8s.io/queue-name: local-queue
spec:
  backoffLimit: 2
  shutdownAfterJobFinishes: true
  entrypoint: python ray-operator/config/samples/ray-data-image-resize/ray_data_image_resize.py
  runtimeEnvYAML: |
    pip:
      - torch
      - torchvision
      - numpy
      - google-cloud-storage
    working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
    env_vars:
      BUCKET_NAME: ray-images
      BUCKET_PREFIX: images
  # rayClusterSpec specifies the RayCluster instance to be created by the RayJob controller.
  rayClusterSpec:
    rayVersion: '2.34.0'
    headGroupSpec:
      rayStartParams: {}
      # Pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.34.0
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "2"
                  memory: "4Gi"
                requests:
                  cpu: "2"
                  memory: "4Gi"
    workerGroupSpecs:
      - replicas: 4
        minReplicas: 1
        maxReplicas: 5
        groupName: small-group
        rayStartParams: {}
        # Pod template
        template:
          spec:
            containers:
              - name: ray-worker
                image: rayproject/ray:2.34.0
                resources:
                  limits:
                    cpu: "2"
                    memory: "4Gi"
                  requests:
                    cpu: "2"
                    memory: "4Gi"
$ kubectl apply -f rayjob.yaml
rayjob.ray.io/image-resize created
```

Note the RayJob sets a new field introduced in v1.2.0 `spec.backoffLimit`. In this example it is set to 2. However, Kueue is defaulting the field to 0:
```
$ kubectl get rayjob image-resize -o yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  ...
  labels:
    kueue.x-k8s.io/queue-name: local-queue
  name: image-resize
  ...
spec:
  backoffLimit: 0
  entrypoint: python ray-operator/config/samples/ray-data-image-resize/ray_data_image_resize.py
  rayClusterSpec:
  ...
```

**What you expected to happen**:

I believe we saw similar behavior while transition KubeRay v0.6.0 to v1.0.0, but I thought it was specific to the  v1apha1 -> v1 upgrade when we deleted fields in v1alpha1. 

I would not expect Kueue to drop new fields introduced in v1 APIs of KubeRay.

**How to reproduce it (as minimally and precisely as possible)**:

See steps above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): v0.8.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Prevent job webhooks from dropping fields for newer API fields when Kueue libraries are behind the latest released CRDs.

This was possible by reusing controller-runtime's handler for CustomDefaulter, by dropping the "remove" operations from the jsondiffs.

I had to duplicate controller-runtime's webhook builder, because there is no way to introduce a custom handler in it. I have an open PR to upstream this ability https://github.com/kubernetes-sigs/controller-runtime/pull/2932

#### Which issue(s) this PR fixes:

Fixes #2878

#### Special notes for your reviewer:

Just to expand on why I decided to go with this approach of dropping the remove operations:
Another option I considered was for every job to return jsonpatches in the Suspend operation. But then it becomes quite hard to explain how to do your own, if you aren't already familiar with jsonpatches. It's much simpler to say "just edit the object". Then I was thinking how can we produce safe patches generically, starting from an edited object. One option would have been to do something similar to https://github.com/kubernetes-sigs/controller-runtime/pull/2931, but that approach might introduce other bugs, as explained in https://github.com/kubernetes-sigs/controller-runtime/pull/2931#discussion_r1728367254

So ultimately I decided to exploit the fact that our webhooks simply don't drop fields.

#### Does this PR introduce a user-facing change?

```release-note
Prevent job webhooks from dropping fields for newer API fields when Kueue libraries are behind the latest released CRDs.
```

### CODE REVIEW

File: pkg/controller/jobframework/webhook/builder.go
Comment (tenzen-y) [inline pkg/controller/jobframework/webhook/builder.go:1]: Could we mention that we will remove this original webhook builders once https://github.com/kubernetes-sigs/controller-runtime/pull/2932 is released in the controller-runtime repository?

The comment would be helpful for developers who implement custom Jobs queuing controllers.
Additionally, the comment can encourage not too much depending on these custom builders.

Thoughts?

**Review by tenzen-y — COMMENTED** [review]
This is just confirmation. Have you ever seen any dropping schemes in the reconcilers/controllers?

For sure, I have seen your comment mentioning the investigations: https://github.com/kubernetes-sigs/kueue/issues/2878#issuecomment-2305438068

File: pkg/controller/jobframework/webhook/builder.go [hunk 1]
```diff
@@ -0,0 +1,246 @@
...
+	"k8s.io/client-go/rest"
+	"k8s.io/klog/v2"
+
+	"sigs.k8s.io/controller-runtime/pkg/client/apiutil"
+	"sigs.k8s.io/controller-runtime/pkg/manager"
+	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
+	"sigs.k8s.io/controller-runtime/pkg/webhook/conversion"
+)
+
+// This code is copied from https://github.com/kubernetes-sigs/controller-runtime
```
Comment (mimowo) [inline pkg/controller/jobframework/webhook/builder.go:37]: I would suggest to minimize the changes which aren't required, so that in the future we don't diverge too much. 
Some changes that look extra: rename of WebhookBuilder -> Builder, making recoverPanic as bool from *bool.

File: pkg/controller/jobframework/webhook/defaulter.go [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+type defaulterForType struct {
+	admission.Handler
+}
+
+// Handle handles admission requests, dropping remove operations from patches produced by controller-runtime.
+// The controller-runtime handler works by creating a jsondiff from the raw object and the marshalled
+// version of the object modified by the defaulter. This generates "remove" operations for fields
+// that are not present in the go types, which can occur when Kueue libraries are behind the latest
+// released CRDs.
+// Dropping the "remove" operations is safe because Kueue's job mutators never remove fields.
```
Comment (mimowo) [inline pkg/controller/jobframework/webhook/defaulter.go:44]: I'm slightly worried that this assumption may change and we may not notice. Maybe some warning to draw attention?
I'm also wondering if this is safe in case of webhooks delivered by users for external Jobs?

File: pkg/controller/jobframework/webhook/builder.go [hunk 3]
```diff
@@ -0,0 +1,246 @@
...
+
+	// Register webhook(s) for type
+	blder.registerDefaultingWebhook()
+	blder.registerValidatingWebhook()
+
+	err = blder.registerConversionWebhook()
+	if err != nil {
+		return err
+	}
+	return nil
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/builder.go:144]: I think the code changed since the last time I copied it. I'll resync.

File: pkg/controller/jobframework/webhook/builder.go [hunk 4]
```diff
@@ -0,0 +1,246 @@
...
+	"sigs.k8s.io/controller-runtime/pkg/webhook/conversion"
+)
+
+// This code is copied from https://github.com/kubernetes-sigs/controller-runtime
+// with some modifications to get full control of the construction of patches.
+
+// Builder builds a Webhook.
+type Builder struct {
+	apiType         runtime.Object
+	mutationHandler admission.Handler
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/builder.go:45]: Yes

File: pkg/controller/jobframework/webhook/builder.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/builder.go]: The file just changed since I copied the code. Except the rename, which I reverted now. And I synced with the latest version.

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:44]: I highlighted the word "dropping" now.

> I'm also wondering if this is safe in case of webhooks delivered by users for external Jobs?

In most cases, custom integrations would use the baseWebhook, which doesn't remove fields.
But implementors can choose not to use this handler or builder.
And they should write integration tests, in which they would notice if a field is not removed.

File: pkg/controller/jobframework/webhook/builder.go
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/builder.go:1]: Added to the comment below

File: pkg/controller/jobframework/webhook/builder.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/builder.go]: Yes, added filename and hash.

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:44]: > In most cases, custom integrations would use the baseWebhook, which doesn't remove fields.

Yeah, but this may not be feasible for more some complex webhooks like [appwrapper](https://github.com/project-codeflare/appwrapper/blob/main/internal/webhook/appwrapper_webhook.go).

> And they should write integration tests, in which they would notice if a field is not removed.

I guess we need to resort to that. One potential preemptive action would be to note about this in the [docs](https://kueue.sigs.k8s.io/docs/tasks/dev/integrate_a_custom_job/#building-a-built-in-integration).

I assume users still can register webhooks without this property if they really need to, right?

File: pkg/controller/jobframework/webhook/builder.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/jobframework/webhook/builder.go]: I checked the diff: https://www.diffchecker.com/iSfsfBol/. Looks clean to me now.

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:44]: > Yeah, but this may not be feasible for more some complex webhooks like [appwrapper](https://github.com/project-codeflare/appwrapper/blob/main/internal/webhook/appwrapper_webhook.go).

Actually, for external integrations, they are more likely to happen in the same repo as to where the CRDs live, so they shouldn't be affected by version skew. As a result, they probably will be ok with the CustomDefaulter way of controller-runtime.

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:44]: > I assume users still can register webhooks without this property if they really need to, right?

Yes, in https://github.com/kubernetes-sigs/controller-runtime/pull/2932 I'm leaving the two options for building webhooks.

Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter.go:44]: TBH, I'm hoping to be fixed this regression in the controller-runtime side by the next Kueue minor release (v0.10). 
So, if this regression will not be fixed before we cut a v0.10, it might be better to add notes to the documents.

Otherwise, we can keep the current documentation. WDYT?

File: pkg/controller/jobframework/webhook/builder.go
Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/builder.go:1]: Thanks. Looks good to me.

File: pkg/controller/jobframework/webhook/builder.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/builder.go]: Ah, I see. Thanks!

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:45]: In controller-runtime I'm only adding the option to provide a full handler. I'm not adding this handler, as this is somewhat specific to Kueue. So we will still need this handler code.

To make things more clear, I renamed the Defaulter to LosslessDefaulter, so bring more attention to its effects.

Just to expand on why I decided to go with this approach of dropping the remove operations:
Another option I considered was for every job to return jsonpatches in the `Suspend` operation. But then it becomes quite hard to explain how to do your own, if you aren't already familiar with jsonpatches. It's much simpler to say "just edit the object". Then I was thinking how can we produce safe patches generically, starting from an edited object. One option would have been to do something similar to https://github.com/kubernetes-sigs/controller-runtime/pull/2931, but that approach might introduce other bugs, as explained in https://github.com/kubernetes-sigs/controller-runtime/pull/2931#discussion_r1728367254

So ultimately I decided to exploit the fact that our webhooks simply don't drop fields.

Comment (dgrove-oss) [reply pkg/controller/jobframework/webhook/defaulter.go:45]: > > Yeah, but this may not be feasible for more some complex webhooks like [appwrapper](https://github.com/project-codeflare/appwrapper/blob/main/internal/webhook/appwrapper_webhook.go).
> 
> Actually, for external integrations, they are more likely to happen in the same repo as to where the CRDs live, so they shouldn't be affected by version skew. As a result, they probably will be ok with the CustomDefaulter way of controller-runtime.

I believe this is correct in general (and is definitely correct for appwrapper). We build/release the CRDs and the controller/webhook together so aren't subject to the same version skew problems.

File: pkg/controller/jobframework/webhook/defaulter_test.go [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+	resp := handler.Handle(context.Background(), req)
+	if !resp.Allowed {
+		t.Errorf("Response not allowed")
+	}
+	wantPatches := []jsonpatch.Operation{
+		{
+			Operation: "add",
+			Path:      "/foo",
+			Value:     "bar",
+		},
```
Comment (tenzen-y) [inline pkg/controller/jobframework/webhook/defaulter_test.go:92]: Could we add a remove operation so that we can verify if the remove operation is ignored?

**Review by tenzen-y — COMMENTED** [review]
Otherwise lgtm.

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter.go:45]: > I believe this is correct in general (and is definitely correct for appwrapper). We build/release the CRDs and the controller/webhook together so aren't subject to the same version skew problems.

I guess that there are some situations where they develop the external Kueue controller to enqueue non upstream supported Job, internally.

For example, I can imagine the VolcanoJob, TeckTon Pipeline, or something.

File: pkg/controller/jobframework/webhook/defaulter_test.go (hunk 5 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter_test.go:94]: Let me add a comment:

The raw object has a field `"baz": "qux"`, which is not in the go type, and there is no remove operation for it.
If I replace the LossLessDefaulter with controller-runtime's custom defaulter, then it generates a remove operation.

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:45]: I'll submit a separate PR for the documentation, but I don't think I'll cherry-pick this change, so it can go with the next release.

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:45]: We don't need to cherry-pick because we are already in the latest versions of kube-ray and kubernetes, which were the known libraries to have new fields.

File: pkg/controller/jobframework/webhook/defaulter.go [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+	admission.Handler
+}
+
+// Handle handles admission requests, **dropping** remove operations from patches produced by controller-runtime.
+// The controller-runtime handler works by creating a jsondiff from the raw object and the marshalled
+// version of the object modified by the defaulter. This generates "remove" operations for fields
+// that are not present in the go types, which can occur when Kueue libraries are behind the latest
+// released CRDs.
+// Dropping the "remove" operations is safe because Kueue's job mutators never remove fields.
+func (h *losslessDefaulter) Handle(ctx context.Context, req admission.Request) admission.Response {
```
Comment (alculquicondor) [inline pkg/controller/jobframework/webhook/defaulter.go:46]: I was chatting with @jpbetz to get his opinion on my former approach, doing a round-trip of the raw object, which was rejected by the maintainers of controller-runtime because it might break backwards compatibility when a go type removes an omitempty clause that was set for a field before https://github.com/kubernetes-sigs/controller-runtime/pull/2931#discussion_r1728367254

He agreed that both approaches (current behavior of controller-runtime and my PR) have pros and cons. However, getting new fields dropped is worse than dealing with CRDs that did backward-incompatible changes related to omitempty.
And, in the case of Kueue, we are only dealing with production ready CRDs and we only modify a few fields that the likelihood of a problem is low.
So, we could move in that direction instead of the approach in the current PR to drop "remove" operations, which can be less future proof.
WDYT?

Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: I support moving forward with https://github.com/kubernetes-sigs/controller-runtime/pull/2932 to at least enable us in Kueue to register the lossLesshandler. 

However, for the long term solution LossLessHandler isn't ideal. Even if we don't the problem yet, it might happen with increased adoption, for example an adopter of Kueue wants to write an in-house webhook to drop a problematic field from Volcano CRD (for example to work-around some issue). 

I see the concern in https://github.com/kubernetes-sigs/controller-runtime/pull/2931, but some solution like this could be handy, maybe it just needs additional care for the problematic cases mentioned?

I'm also wondering if this problem is related to https://github.com/kubernetes/kubernetes/issues/126175 (might be red herring, but PTAL)

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: > but some solution like this could be handy, maybe it just needs additional care for the problematic cases mentioned?

We wouldn't be able to know generically. It depends on the CRD. But again, the likelihood is very low.

So, up to you. Would you prefer the implementation of LosslessHandler as suggested in https://github.com/kubernetes-sigs/controller-runtime/pull/2931 or are you ok with proceeding with the current PR?

Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: I will need to learn more about the pros & cons of thttps://github.com/kubernetes-sigs/controller-runtime/pull/2931. 
Would the change in omitempty be problematic then only for build-in types, or CRDs also? Also is it problematic removing "omitempty", or adding as well?

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter.go:45]: > We don't need to cherry-pick because we are already in the latest versions of kube-ray and kubernetes, which were the known libraries to have new fields.

That makes sense. Indeed, we do not observe the new field on our other supporting Jobs (Kubeflow, JobSet...).

File: pkg/controller/jobframework/webhook/defaulter_test.go (hunk 5 above)
Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter_test.go:94]: Oh, I got it. Thank you for the clarifications.

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 6 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: The problematic scenario is when the go library in Kueue doesn't have omitempty, but the object stored in apiserver doesn't have the field. In this case, roundtripping in Kueue would add the fields, leading to possibly invalid patches. This can happen in two scenarios:
- The go type author removes the omitempty from a field, and this is the library that Kueue uses. A user created the object when omitempty was in place.
- Kueue is using an older library that doesn't have omitempty. The go type author adds omitempty to a field, and a user creates an object using this version.
So yes, it can happen in either scenario. @jpbetz, please correct me if my interpretation is wrong.

Another diminishing factor is that this only matters if we are modifying a field that is having these omitempty transitions. If the transition happens in an object that Kueue doesn't touch, then this wouldn't show up in the jsondiff. But the omitempty status of all the parents of the field could be relevant.

I think https://github.com/kubernetes/kubernetes/issues/126175 is also related, but it rather happens with the current CustomDefaulter of controller-runtime, and it wouldn't happen with my version because it wouldn't show in the jsondiff.

So the question comes down to:
Do we want to prioritize supporting newly added fields that Kueue libraries don't know about? Or do we prioritize supporting buggy types (which, as we can see, could also be a problem in the current version)? I think it's only fair to prioritize the former and be in the watch to report issues as necessary in other libraries and upgrade when appropriate.

OTOH, the LosslessDefaulter as currently implemented (just dropping every remove operation), doesn't have any problems, as long as we know that we are not removing any fields in the webhook.

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: I think there is a risk in kubeflow because some of the `RunPolicy` fields don't have omitempty. Maybe we can make sure they get omitempty before we implement the RoundtripDefaulter in Kueue? cc @andreyvelich (sorry, it's a long thread to read, but you can only understand it if you follow all of it).

Comment (jpbetz) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: I'm strongly in favor of biasing toward approaches that work for well-behaved CRD authors.

Adding fields to CRDs is very common, and it's essential to being able to safely and backward compatibly evolving a CRD over time.  If we have a webhook mechanism that removes fields that it doesn't recognize or need to care about purely because the webhook was developed before the field was introduced, that's a risk to all well behaved CRD authors. I personally wouldn't ever use a webhook that might start removing perfectly valid fields in the future.  That seems broken to me, and the failure mode is pretty bad.. it seems to work when you develop it, then later it mutates resources in a dangerous way, maybe in production.

Am I mis-representing the problem?

> Would the change in omitempty be problematic then only for build-in types, or CRDs also? Also is it problematic removing "omitempty", or adding as well?

I don't think we could ever make this change to a built-in type. And even if you do make this change, it's it only problem if the server cares about the difference between absent and zero-valued? (which is backward incompatible and dangerous for the interpretation of any resources written to storage before the change?)

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: > Am I mis-representing the problem?

No, you are on point :)

> I don't think we could ever make this change to a built-in type. And even if you do make this change, isn't it only problem if the server differentiates between absent and zero-valued? (

Right, in a built-in type, we would never remove an "omitempty" for an optional field, but we could still add one, just because we forgot before, like in https://github.com/kubernetes/kubernetes/pull/126046

I think, in that case, if Kueue keeps the library with the buggy go type (without omitempty), then using the RoundTripperDefaulter is at risk of producing invalid jsonpatches.

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: But in that case, it would be silly not to upgrade Kueue to the latest patch version.

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: My overall suggestion is the following:
1. Merge LosslessDefaulter (this PR)
2. Do an audit of all in-tree integrations and make sure they are using omitempty appropriately, at least for the fields we modify.
3. Fix each external CRD as necessary and wait for their releases.
4. Upgrade Kueue libraries and change the LosslessDefaulter for a RoundTripDefaulter.

Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: Aldo, big thanks for explaining the issue in detail, and to all folks sharing their perspectives.

I fully agree with the need to fix the issue, a webhook which removes fields is very bad. This is important to the extent that I would consider cherry-picking this fix to 0.8.2. Even if the current master webhook doesn’t drop fields, because it is compiled against the latest CRD (say Ray), it may start dropping fields in a couple on months just because the next version of Ray is released (outside of Kueue’s control). WDY @tenzen-y ?

Regarding the fix of choice. 

Re 1. I really like the LossLessDefaulter approach, and I don’t see it buggy at all. IIUC it ensures correctness (current and future) for all CRDs managed by Kueue, as long as our the webhooks don’t remove fields, but our webhooks are part of Kueue codebase for built-in integrations, so we are in control. The approach is opt-in, so external developers may or may not want to use LossLessDefaulter (we should warn about the potential risk in documentation). Finally, if a user developing external or internal integration using LossLessDefaulter has a need to remove a field, they could do so using a second webhook registered using regular Defaulter, and just drop the field (set to nil). It will be safe, because the dedicated webhook will be compiled against the CRD version new enough to contain the field.

Re 2-4: I’m sceptical here. First, IIUC the mechanism as prototyped in https://github.com/kubernetes-sigs/controller-runtime/pull/2931 is not opt-in, and so if there is a field that changes omitempty, the correctness is out of Kueue - we basically need to accept the fact that Kueue’s webhooks misbehave from the end-user perspective.  

I just did a quick heuristic check: searched in kubernetes by “omitempty” : https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+omitempty+label%3Akind%2Fapi-change+is%3Aclosed , and clicked through a couple of top results, finding:
- https://github.com/kubernetes/kubernetes/pull/126046 added omitempty
- https://github.com/kubernetes/kubernetes/pull/124859 removed omitempty
- https://github.com/kubernetes/kubernetes/pull/124553 removed omitempty
- https://github.com/kubernetes/kubernetes/pull/121078 added omitempty
- https://github.com/kubernetes/kubernetes/pull/121000 added omitempty

I also remember OnCalling an issue where the culprit was that a user changed omitempty for an in-house CRD.

Given that such changes happen in the core k8s (often to fix bugs), and we cannot control in-house integrations, I think it isn't feasible to audit all CRDs (as suggested in 2-3 points), so I think any fix we choose needs to handle that scenario gracefully. 

I would like to move forward with (1.), and maybe (4) provided that the approach can be adjusted to handle changes in omitempty gracefully. 

I’m happy to re-evaluate if I missed something.

Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: One more thing to clarify: when I say I don't see (1.) buggy I mean it solves the problem for Kueue and as long as we are careful - the correctness is in hands of Kueue developers (or developers of integrations). **as long as we are careful** is still an important caveat here, so the solution is far from ideal. Another reason it is not ideal, is that other projects, like JobSet would also need to introduce something like LossLessDefaulter, and this approach will not scale.  It is just my preference out of the options on the table.

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: > First, IIUC the mechanism as prototyped in https://github.com/kubernetes-sigs/controller-runtime/pull/2931 is not opt-in

Right, that original PR is not opt-in. However, the proposal would be to add a `RoundTripDefaulter` as an alternative to c-r's `CustomDefaulter`, not as a replacement. Then it is opt-in.

But, in any case, if you are accepting `LosslessDefaulter` as is, then the only reason to change to `RoundTripDefaulter` would be because we suddenly have a need to remove fields in our webhooks or we just want to be future-proof or provide the alternative to external developers.

A good thing about making it opt-in, is that we don't have to migrate all webhooks at once. We can do the audit for a specific type and then do the migration for just that webhook.

> I just did a quick heuristic check: searched in kubernetes by “omitempty” 

That's scary. We need to be more diligent about https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required when doing API reviews. I'll send an email to api-reviewers :)

> Another reason it is not ideal, is that other projects, like JobSet would also need to introduce something like LossLessDefaulter

I don't think this is a problem for Jobset, at least not in the same way. Jobset's webhook would always be released alongside the new CRD version. Sure, jobset uses job specs underneath, which in theory could add fields, but unless they are in the latest version, the fields would be dropped even if there wasn't a webhook, because they wouldn't be part of the jobset CRD.
So, this is more of a problem of components like Kueue that deal with libraries that it doesn't control.

Anyways, it sounds like we should be proceeding with this PR for now. Any additional implementation comments?

**Comment by mimowo** [comment]
/lgtm
/approve
/hold
In case @tenzen-y has more comments. @alculquicondor please follow up with a note about the recommendation for registering webhooks for integrations.

Also, @tenzen-y  @alculquicondor  WDYT about cherry-picking to 0.8?

**Comment by alculquicondor** [comment]
re cherry-picking:
This PR depends on https://github.com/kubernetes-sigs/kueue/pull/3132, so maybe a bit too much for a clean merge?

I think we are relatively safe given that we are using the latest libraries in 0.8 already. And people who might be thinking of upgrading k8s or kuberay are more likely to also stay up to date with Kueue.

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 6 above)
Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: > the proposal would be to add a RoundTripDefaulter as an alternative to c-r's CustomDefaulter, not as a replacement. Then it is opt-in.

Probably worth adding to controller-runtime as an option. However, even then I would be a bit cautious for using in Kueue (but open). The reason gets correctness, from the end-user perspective, out of Kueue. So, a user of Kueue may see there was an edit of CRD by Kueue's webhook, and attribute this as a bug of the Kueue webhook, which would be understandable, even though the actual change was in CRD.

> I don't think this is a problem for Jobset, at least not in the same way. Jobset's webhook would always be released alongside the new CRD version.

Ah, right. Though, to some extent it may still happen if omitempty is changed for the Pod API in Kube, because JobSet has [pod webook](https://github.com/kubernetes-sigs/jobset/blob/main/pkg/webhooks/pod_mutating_webhook.go) also.

> Anyways, it sounds like we should be proceeding with this PR for now. Any additional implementation comments?

Good to go from me, but let's see if @tenzen-y has some final comments.

**Comment by tenzen-y** [comment]
> re cherry-picking: This PR depends on #3132, so maybe a bit too much for a clean merge?
> 
> I think we are relatively safe given that we are using the latest libraries in 0.8 already. And people who might be thinking of upgrading k8s or kuberay are more likely to also stay up to date with Kueue.

Indeed, I had some discussions about cherry-picking there: https://github.com/kubernetes-sigs/kueue/pull/3132#discussion_r1775672986

So, I'm ok without cherry-picking.

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 6 above)
Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: > I think there is a risk in kubeflow because some of the RunPolicy fields don't have omitempty. Maybe we can make sure they get omitempty before we implement the RoundtripDefaulter in Kueue?

On behalf of Kubeflow Training TL, I believe this request is reasonable and acceptable. But, I want to open an issue in the kubeflow side before we start implementations.

Another concern is the older Kubeflow TrainingOperator users. IIUC, after the RoundTripDefaulter is implemented in the Kueue side, if the users use the older TrainingOperator (without omitempty RunPolicy), some field could be accidentally dropped during webhook, right?

So, I want to keep using this LossLessDefaulter for a while. But, we can discuss it in another issue.

**Review by tenzen-y — COMMENTED** [review]
Thanks @alculquicondor @mimowo @jpbetz!
/lgtm
/approve
/hold cancel

@alculquicondor  Please open a PR to update docs and an issue to discuss about the RoudtripDefaulter as we discussed.

**Comment by tenzen-y** [comment]
> go: github.com/mikefarah/yq/v4@v4.44.3: Get "https://proxy.golang.org/github.com/mikefarah/yq/v4/@v/v4.44.3.info": dial tcp 142.250.191.113:443: i/o timeout

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/3132/pull-kueue-test-multikueue-e2e-main/1839710600670744576

This seems to be a networking connectivity error.

/test pull-kueue-test-multikueue-e2e-main

**Comment by mimowo** [comment]
I think https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/3132/pull-kueue-test-integration-main/1839710600372948992 is a flake

**Comment by tenzen-y** [comment]
Due to https://github.com/kubernetes-sigs/kueue/issues/3144

File: pkg/controller/jobframework/webhook/defaulter.go (hunk 6 above)
Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: >  if the users use the older TrainingOperator (without omitempty RunPolicy), some field could be accidentally dropped during webhook, right?

I don't think so. If Kueue libraries have omitempty when necessary, then the patches will be correct even if the objects were created with a different version.

Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: > > if the users use the older TrainingOperator (without omitempty RunPolicy), some field could be accidentally dropped during webhook, right?
> 
> I don't think so. If Kueue libraries have omitempty when necessary, then the patches will be correct even if the objects were created with a different version.

I see. I was misunderstaindin your point a little bit. Now, all clear. So, we want to add the `omitempty` to RunPolicy as soon as possible. Let's open an issue and add omitempty to the TrainigOperator and MPIOperator.

Thanks for the clarifications and for sharing your investigations.

Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: I think understanding all nuances of setting "omitempty" properly has proved to be hard, and so it is hard for me to imagine we could maintain bug-free CRDs. Even if we put effort into auditing the CRDs for version X, I think with new fields added such bugs are likely to slip review in X+2, and will require changes (bugfixes). 

I'm also a bit concerned that with widespread use of RoundTripDefauler we will have an incentive not to fix omitempty bugs, so that we don't run into issues on upgrades.

Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: > I'm also a bit concerned that with widespread use of RoundTripDefauler we will have an incentive not to fix omitempty bugs, so that we don't run into issues on upgrades.

I'm sure your concerns. But, I guess that we need to take a little bit longer time to fix the root cause in the contoller-runtime and core kube API. So, I would recommend to treat the RoutTripDefaulter as a temporary solution and put the function in the internal package so that the function is not widespread used.

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: Again, the omitempty issue only affects Kueue webhooks if they are missing in the fields that Kueue modifies. If Kueue doesn't modify them, then they would simply not form part of the jsondiff. So, to ensure Kueue correctness, we only need to audit the fields that we touch.

Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: I guess that Michal's concern is for the third-party Kueue controllers. Isn't it?

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: Yeah, but unfortunately we cannot do much better than document the problem.

Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:46]: My comment was more speculative, touching two potential concerns. Let me explain below in more detail.

> So, to ensure Kueue correctness, we only need to audit the fields that we touch. 

Yes, but even if we audit all fields modified by Kueue for TFJob at a given release of Kueue and TFJob, Kueue may want to use new fields in its future releases (for new features, like managedBy). Then, we need to audit the new field, and if we find an "omitempty" bug in TFJob operator in the field, then what do we do? Wait with the new feature of Kueue until the TFJob is fixed and released, or build the new feature based on the buggy field? None of the choices is ideal.

> I guess that Michal's concern is for the third-party Kueue controllers. Isn't it?

Yeah, this is another consideration, if RoundTrip defaulter is widespread in customer, and third-party webhooks, it would create an incentive not to fix the omitempty bugs (whatever small, but still).

File: pkg/controller/jobframework/webhook/defaulter.go [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+	response := h.Handler.Handle(ctx, req)
+	if response.Allowed {
+		var patches []jsonpatch.Operation
+		for _, p := range response.Patches {
+			if p.Operation != "remove" {
```
Comment (mimowo) [inline pkg/controller/jobframework/webhook/defaulter.go:51]: @alculquicondor would it be feasible to make the LossLessDefaulter more selective - only drop remove operations which correspond to fields outside of schema? If possible, then we could allow webhooks to remove known fields, while still preventing dropping of unknown fields. I suppose the answer may not be straightforward - depending how easily we can check if a remove operation corresponds to a known field, also performance may play a role. 

If possible, maybe it would increase chances for promoting LossLessDefaulter as part of opt-in defaulter inside controller-runtime?

Comment (alculquicondor) [reply pkg/controller/jobframework/webhook/defaulter.go:51]: I suppose there is a way using the `reflect` package. But I don't think I'll have time to explore it.

Comment (tenzen-y) [reply pkg/controller/jobframework/webhook/defaulter.go:51]: @mimowo That sounds more safety. Could we open an issue on the Kueue side?
If anyone is interested in this enhancement, they can take it.

Comment (mimowo) [reply pkg/controller/jobframework/webhook/defaulter.go:51]: It would be wonderful, opened: https://github.com/kubernetes-sigs/kueue/issues/3174
