### PR TITLE
Fix the MultiKueue flake issue

### LINKED ISSUE #6573: Flaky E2E: MultiKueue when The connection to a worker cluster is unreliable Should update the cluster status to reflect the connection state
**What happened**:

Unexpected `End To End MultiKueue Suite: kindest/node:v1.33.1: [It] MultiKueue when The connection to a worker cluster is unreliable Should update the cluster status to reflect the connection state` failure on periodic Job

```
{Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:115 with:
Error matcher expects an error.  Got:
    <nil>: nil failed [FAILED] Timed out after 45.000s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:115 with:
Error matcher expects an error.  Got:
    <nil>: nil
In [AfterEach] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/multikueue/e2e_test.go:175 @ 08/13/25 05:31:21.359
}
```

**What you expected to happen**:

No errors

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-e2e-multikueue-release-0-13/1955496724898254848

Image

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #7457: [flaky test] The connection to a worker cluster is unreliable Should update the cluster status to reflect the connection state
/kind flake

**What happened**:

failure https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7448/pull-kueue-test-e2e-multikueue-main/1983905265296084992

**What you expected to happen**:
no failure
**How to reproduce it (as minimally and precisely as possible)**:
ci
**Anything else we need to know?**:

```
MultiKueue when The connection to a worker cluster is unreliable [It] Should update the cluster status to reflect the connection state
/home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:978
  [FAILED] Expected success, but got an error:
      <*errors.StatusError | 0xc000bb8820>: 
      conversion webhook for kueue.x-k8s.io/v1beta1, Kind=ClusterQueue failed: Post "[https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s](https://kueue-webhook-service.kueue-system.svc/convert?timeout=30s)": dial tcp 10.244.1.9:9443: connect: connection refused
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "conversion webhook for kueue.x-k8s.io/v1beta1, Kind=ClusterQueue failed: Post \"[https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s](https://kueue-webhook-service.kueue-system.svc/convert?timeout=30s)\": dial tcp 10.244.1.9:9443: connect: connection refused",
              Reason: "",
              Details: nil,
              Code: 500,
          },
      }
  In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/multikueue/e2e_test.go:1040 @ 10/30/25 14:50:02.347
  There were additional failures detected.  To view them in detail run ginkgo -vv
------------------------------
```

### LINKED ISSUE #7637: [Flaky] End To End Custom Configs: conversion webhook for kueue.x-k8s.io/v1beta1 failed
**What happened**:

```
{Expected success, but got an error:
    <*errors.StatusError | 0xc0001770e0>: 
    conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post "https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s": EOF
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post \"https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s\": EOF",
            Reason: "",
            Details: nil,
            Code: 500,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc0001770e0>: 
    conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post "https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s": EOF
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "conversion webhook for kueue.x-k8s.io/v1beta1, Kind=LocalQueue failed: Post \"https://kueue-webhook-service.kueue-system.svc:443/convert?timeout=30s\": EOF",
            Reason: "",
            Details: nil,
            Code: 500,
        },
    }
In [AfterEach] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/customconfigs/managejobswithoutqueuename_test.go:85 @ 11/13/25 11:45:43.614
}
```

**What you expected to happen**:
No issue

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/7636/pull-kueue-test-e2e-customconfigs-main/1988932518660804608

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mimowo**
/kind flake

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #7457
Fixes #7637
Fixes #6573

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @IrvingMg @mbobrovskyi wdyt? 
I tested on https://github.com/kubernetes-sigs/kueue/pull/7662 and it seems to pass consistently

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-e2e-multikueue-main

1 of 5 atempts

**Comment by mbobrovskyi** [comment]
Could you please delete this one https://github.com/mimowo/kueue/blob/2f1fa40505bddb77c6e16b6593ca61b468f1cb59/test/e2e/multikueue/e2e_test.go#L979-L987?

UPDTE: Ah, it still uses.

**Comment by mbobrovskyi** [comment]
/lgtm
Thank you!

/hold for 5 attempts.

**Comment by mbobrovskyi** [comment]
Please fix `Fixes ##7457` on PR description.

**Comment by mimowo** [comment]
✅

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-e2e-multikueue-main

2 of 5 atempts

**Comment by mimowo** [comment]
/hold
the experiment failed on ReplicaSetUpdated as reason for deployment. I think we need to add it to accepted reasons

**Comment by mbobrovskyi** [comment]
> the experiment failed on ReplicaSetUpdated as reason for deployment. I think we need to add it to accepted reasons

I didn't got why it could be possible 2 reasons?

**Comment by mimowo** [comment]
> I didn't got why it could be possible 2 statuses?

I think it depends on if the Deployment was still available before the restart is happening or not, but I'm not totally sure

File: test/util/e2e.go [hunk 1]
```diff
@@ -212,16 +212,17 @@ func rolloutOperatorDeployment(ctx context.Context, k8sClient client.Client, key
...
-		Status: corev1.ConditionTrue,
-		Reason: "NewReplicaSetAvailable",
+	acceptedDeploymentReasons := []string{
+		"NewReplicaSetAvailable",
+		"ReplicaSetUpdated",
 	}
 
 	gomega.EventuallyWithOffset(2, func(g gomega.Gomega) {
 		g.Expect(k8sClient.Get(ctx, key, deployment)).To(gomega.Succeed())
 		deploymentCondition = FindDeploymentCondition(deployment, appsv1.DeploymentProgressing)
```
Comment (mbobrovskyi) [inline test/util/e2e.go:218]: Shouldn't we check for DeploymentAvailable?

Comment (mbobrovskyi) [reply test/util/e2e.go:218]: I think thats why we have this bug https://github.com/kubernetes-sigs/kueue/issues/7637. We are not waiting for availability.

Comment (mimowo) [reply test/util/e2e.go:218]: Let me see

Comment (mimowo) [reply test/util/e2e.go:218]: I added the check for DeploymentAvailable here: https://github.com/kubernetes-sigs/kueue/compare/a2568949682f2a400f7af363b3676111a0536727..3415f121071dbcda324d8a99aefcaf2e289df4f9#diff-2e6108aa98030ed90991bf0aedca66477b40aa916513427588352404443fd685R239-R240

File: test/util/e2e.go [hunk 2]
```diff
@@ -414,24 +415,28 @@ func WaitForKubeSystemControllersAvailability(ctx context.Context, k8sClient cli
...
 
-	for _, ds := range []string{
-		"kindnet",
-		"kube-proxy",
-	} {
-		dsKey := types.NamespacedName{Namespace: ns, Name: ds}
-		ginkgo.By(fmt.Sprintf("Waiting for daemonset %q to be available", ds))
-		waitForDaemonSetAvailability(ctx, k8sClient, dsKey)
-	}
+	for pass := range 2 {
```
Comment (mimowo) [inline test/util/e2e.go]: I have also added another pass over availability of kube-system Pods, because I think it is possible that we see some pod say kube-controller-manager as Ready, but it becomes NotReady becasue api-server is down, and only later we confirm api-server to be Ready.

**Comment by mimowo** [comment]
> I didn't got why it could be possible 2 reasons?

The expected condition reason at the end should be just NewReplicaSetAvailable which denotes success - fixed.

However, for the state before in MultiKueue tests we occasionally see ReplicaSetUpdated, which was the reason for one of the failures I saw. I think this is because at the moment we start restart the replicas may not necessarily be available.

File: test/util/e2e.go [hunk 3]
```diff
@@ -414,49 +414,35 @@ func WaitForKubeSystemControllersAvailability(ctx context.Context, k8sClient cli
...
 	gomega.EventuallyWithOffset(1, func(g gomega.Gomega) {
-		g.Expect(k8sClient.Get(ctx, key, pod)).To(gomega.Succeed())
-		g.Expect(pod.Status.Conditions).To(gomega.ContainElement(gomega.BeComparableTo(corev1.PodCondition{
-			Type:   corev1.PodReady,
-			Status: corev1.ConditionTrue,
-		}, cmpopts.IgnoreFields(corev1.PodCondition{}, "Reason", "LastTransitionTime", "LastProbeTime"))))
-	}, StartUpTimeout, Interval).Should(gomega.Succeed())
-	ginkgo.GinkgoLogr.Info("Pod available in the cluster", "pod", key, "waitingTime", time.Since(waitForAvailableStart))
-}
+		// we wait for all the DeamonSets and Pods in kube-system to be available at the same time
```
Comment (mbobrovskyi) [inline test/util/e2e.go]:
```suggestion
		// we wait for all the DaemonSets and Pods in kube-system to be available at the same time
```

Comment (mimowo) [reply test/util/e2e.go]: done

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-e2e-multikueue-main

3 of 5 atempts

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Comment by mimowo** [comment]
FYI, I also mark this PR is fixing https://github.com/kubernetes-sigs/kueue/issues/7637 and https://github.com/kubernetes-sigs/kueue/issues/6573, because #7637 is likely fixed by the extra availability check at the end of restart, and #6573 is likely another manifestation of Kueue not running after restart.

**Comment by mimowo** [comment]
/test pull-kueue-test-e2e-multikueue-main

4 of 5 attempts

**Comment by mimowo** [comment]
We already have 30 attempts as I opened the experiment PRs running the same code in loop 15 times each: https://github.com/kubernetes-sigs/kueue/pull/7670 and https://github.com/kubernetes-sigs/kueue/pull/7662

**Comment by mimowo** [comment]
60 successful attempts counting the other two PRs

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-e2e-multikueue-main

5 of 5 attempts

/unhold
