### PR TITLE
[workload] Allow specifying PodSetUpdates for a subset of PodSets

### LINKED ISSUE #2260: MPIJobs can't run with ProvisioningRequest with DWS
**What happened**:

For DWS, we use the following configuration:

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ProvisioningRequestConfig
metadata:
  name: dws-config
spec:
  provisioningClassName: queued-provisioning.gke.io
  managedResources:
  - nvidia.com/gpu
```

This allows to create a ProvReq only for the workers of an MPIJob, but not the launcher.

However, when the ProvisioningRequest is satisfied, the Kueue provisioning controller only sets a `podSetUpdate` for the podset used in the provisioningRequest. This fails validation for the Workload status.

**What you expected to happen**:

Validation should pass for cases where `podSetUpdates` has less elements than `.spec.podSets` and the logic that handles the updates should not expect the slices to match.

**How to reproduce it (as minimally and precisely as possible)**:

- Configure a cluster using https://cloud.google.com/kubernetes-engine/docs/how-to/provisioningrequest#for_jobs_with_kueue
- Create an MPIJob where the workers requests GPUs, but the launcher doesn't.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Allow an admission check controller to provide podSetUpdates for a podSet subset when needed.

#### Which issue(s) this PR fixes:

Fixes #2260

#### Does this PR introduce a user-facing change?

```release-note
Fix support for MPIJobs when using a ProvisioningRequest engine that applies updates only to worker templates.
```

### CODE REVIEW

File: pkg/webhooks/workload_webhook_test.go [hunk 1]
```diff
@@ -120,17 +120,6 @@ func TestValidateWorkload(t *testing.T) {
 			workload: testingutil.MakeWorkload(testWorkloadName, testWorkloadNamespace).AdmissionChecks(kueue.AdmissionCheckState{}).Obj(),
 			wantErr:  nil,
 		},
-		"should podSetUpdates have the same number of podSets": {
```
Comment (alculquicondor) [inline pkg/webhooks/workload_webhook_test.go:123]: Let's keep the test with `wantErr: nil`

Comment (trasc) [reply pkg/webhooks/workload_webhook_test.go:123]: done

**Comment by mimowo** [comment]
/lgtm
/hold cancel
I believe all comments are addressed. If there are some remaining improvements we can follow up.

**Comment by tenzen-y** [comment]
@trasc Could you create a cherry-pick PR?
