### PR TITLE
Don’t add the Workload to the Queues Manager if it is deactivated.

### LINKED ISSUE #5623: Workloads deactivated by Kueue are not deleted after Kueue restart (ObjectRetentionPolicies)
**What happened**:

Jobs which were deactivated before Kueue upgrade to 0.12.2, are not garbage-collected (deleted) even when ObjectRetentionPolicies are enabled, as described here: https://kueue.sigs.k8s.io/docs/tasks/manage/setup_object_retention_policy/

Same would happen if Kueue is rebooted in the meanhwile.

**What you expected to happen**:

Kueue deletes deactivated workloads even if they were deactivated before upgrade or restart.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Kueue 0.12.2 and disable ObjectRetentionPolicies by setting false, and configure waitForPodsReady and object retention policies as described in https://kueue.sigs.k8s.io/docs/tasks/manage/setup_object_retention_policy/
2. Create a Job which has node selector which does not allow to run it, it will get deactivated after 2min
3. Enable ObjectRetentionPolicies by setting true, and restart kueue
*Issue*: the workload is not deleted

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Don’t add the Workload to the Queues Manager if it is deactivated.

#### Which issue(s) this PR fixes:

Fixes #5623

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug that Kueue, upon startup, would incorrectly admit and then immediately deactivate
already deactivated Workloads.

This bug also prevented the ObjectRetentionPolicies feature from deleting Workloads
that were deactivated by Kueue before the feature was enabled.
```

### CODE REVIEW

File: test/e2e/customconfigs/objectretentionpolicies_test.go [hunk 1]
```diff
@@ -35,6 +35,100 @@ import (
 	"sigs.k8s.io/kueue/test/util"
 )
 
+var _ = ginkgo.Describe("ObjectRetentionPolicies", ginkgo.Ordered, ginkgo.ContinueOnFailure, func() {
```
Comment (mimowo) [inline test/e2e/customconfigs/objectretentionpolicies_test.go:38]: Thank you for adding the test. I find it quite valuable, it is one of the bugs which is very hard to identify when looking at each component in isolation.

However, I think this bug also exists outside of "object retention policies". So, I'm wondering if we could also cover this in a more lightweight test. Maybe an integration test which checks the "AdmittedWorkloadsTotal" metric and confirms it was not incremented after reboot (regardless of the object retention policies).

wdyt?

Comment (mbobrovskyi) [reply test/e2e/customconfigs/objectretentionpolicies_test.go:38]: Done

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 2]
```diff
@@ -2088,6 +2102,64 @@ var _ = ginkgo.Describe("Interacting with scheduler", ginkgo.Ordered, ginkgo.Con
...
+		})
+
+		restartManager()
+
+		ginkgo.By("Checking that the Workload is not admitted after restart manager", func() {
+			gomega.Consistently(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, wlKey, wl)).To(gomega.Succeed())
+				g.Expect(workload.IsAdmitted(wl)).To(gomega.BeFalse())
+				g.Expect(workload.IsEvicted(wl)).To(gomega.BeTrue())
+			}, util.ConsistentDuration, util.Interval).Should(gomega.Succeed())
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Instead of using consistently, could we check that the metric stays 0? Seems much shorter to check.

EDIT: oh, I see, if we check the metric didn't bump then it could be racy, because maybe it didin't bump becuase the test checked too early...

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 3]
```diff
@@ -2088,6 +2102,64 @@ var _ = ginkgo.Describe("Interacting with scheduler", ginkgo.Ordered, ginkgo.Con
...
+
+		ginkgo.By("Checking that the Workload is deactivated and evicted", func() {
+			gomega.Eventually(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, wlKey, wl)).To(gomega.Succeed())
+				g.Expect(workload.IsActive(wl)).To(gomega.BeFalse())
+				g.Expect(workload.IsEvicted(wl)).To(gomega.BeTrue())
+			}, util.Timeout, util.Interval).Should(gomega.Succeed())
+		})
+
+		restartManager()
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: wrap in ginkgo.by

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go [hunk 4]
```diff
@@ -2088,6 +2102,64 @@ var _ = ginkgo.Describe("Interacting with scheduler", ginkgo.Ordered, ginkgo.Con
...
+
+		ginkgo.By("Checking that the Workload is not admitted after restart manager", func() {
+			gomega.Consistently(func(g gomega.Gomega) {
+				g.Expect(k8sClient.Get(ctx, wlKey, wl)).To(gomega.Succeed())
+				g.Expect(workload.IsAdmitted(wl)).To(gomega.BeFalse())
+				g.Expect(workload.IsEvicted(wl)).To(gomega.BeTrue())
+			}, util.ConsistentDuration, util.Interval).Should(gomega.Succeed())
+			util.ExpectAdmittedWorkloadsTotalMetric(prodClusterQ, 1)
```
Comment (mimowo) [inline test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2163]: Actually, I'm surprised the metric isn't 0. I would expect the manager restart clears the metric down to 0, doesn't it?

File: pkg/controller/core/workload_controller.go [hunk 5]
```diff
@@ -665,7 +665,8 @@ func (r *WorkloadReconciler) triggerDeactivationOrBackoffRequeue(ctx context.Con
 func (r *WorkloadReconciler) Create(e event.TypedCreateEvent[*kueue.Workload]) bool {
 	defer r.notifyWatchers(nil, e.Object)
 	status := workload.Status(e.Object)
-	log := r.log.WithValues("workload", klog.KObj(e.Object), "queue", e.Object.Spec.QueueName, "status", status)
+	active := workload.IsActive(e.Object)
+	log := r.log.WithValues("workload", klog.KObj(e.Object), "queue", e.Object.Spec.QueueName, "status", status, "active", active)
```
Comment (mimowo) [inline pkg/controller/core/workload_controller.go]: Maybe don't add it here. It feels confusing to have "status: finished", "active: true". I would probably think Deactivated is one of the possible states of status. However, we can leave it for later.

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 4 above)
Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2163]: No, we’re only restarting the manager. The metrics are stored globally in memory.

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Can you try the following: check if EvictedWorkloadsTotal=1 (this way we know we started to account for metrics), and AdmittedWorkloadsTotal=0. Then, I believe it should be enough to catch the bug (repro) without consistently.

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 3 above)
Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Done

File: pkg/controller/core/workload_controller.go (hunk 5 above)
Comment (mbobrovskyi) [reply pkg/controller/core/workload_controller.go]: Done

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 4 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2163]: Ah, ok, probably the test env for controller-runtime keeps it separate. 

In that case, I would suggest:
- add a comment, something like: `// NOTE: controller restart in integration tests does not reset the metrics`
- verify the metric also before restart (so that it is clear delta=0)
- verify also before and after the restart the metric for EvictedWorkloadsTotal (expected delta is 1)

Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2163]: > verify the metric also before restart (so that it is clear delta=0)
> verify also before and after the restart the metric for EvictedWorkloadsTotal (expected delta is 1)

Yes, we have it before

https://github.com/kubernetes-sigs/kueue/blob/e94b055b992dcc75be46b2e81afd9d5e85afea2d/test/integration/singlecluster/controller/jobs/job/job_controller_test.go#L2133

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 2 above)
Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Done

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 4 above)
Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go:2163]: > add a comment, something like: // NOTE: controller restart in integration tests does not reset the metrics

Done

File: test/integration/singlecluster/controller/jobs/job/job_controller_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: I re-visited and played with this assert locally to understand various nuances. After thinking about it, I prefer to check exactly that the conditions don't flip. plus, the metric, maybe:

```golang
ginkgo.By("Checking that the Workload is not admitted after restart the manager", func() {
	gomega.Consistently(func(g gomega.Gomega) {
		g.Expect(k8sClient.Get(ctx, wlKey, wl)).To(gomega.Succeed())
		g.Expect(workload.IsAdmitted(wl)).To(gomega.BeFalse())
		g.Expect(workload.IsEvicted(wl)).To(gomega.BeTrue())
		// Using short intervals to make it likely to fail if the conditions flip
	}, util.ConsistentDuration, 10*time.Millisecond).Should(gomega.Succeed())
	// NOTE: controller restart in integration tests does not reset the metrics
	util.ExpectAdmittedWorkloadsTotalMetric(prodClusterQ, 1)
})
```
BTW: I think we should use the interval of 10ms in other tests too. 250ms is really a lot of time to make the condition flip back and forth in the meanwhile (out of scope for the PR).

Comment (mbobrovskyi) [reply test/integration/singlecluster/controller/jobs/job/job_controller_test.go]: Done

File: test/util/constants.go [hunk 6]
```diff
@@ -43,6 +43,7 @@ const (
 	StartUpTimeout     = 5 * time.Minute
 	ConsistentDuration = time.Second
 	Interval           = time.Millisecond * 250
+	ConsistentInterval = 10 * time.Millisecond
```
Comment (mimowo) [inline test/util/constants.go]: Thanks for defining it here.
```suggestion
	ShortInterval = 10 * time.Millisecond
```
nit, to align with the naming convention for `Timeout`

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Fix the bug that Kueue, upon startup, would incorrectly admit and then immediately deactivate
already deactivated Workloads.

This bug also prevented the ObjectRetentionPolicies feature from deleting Workloads
that were deactivated by Kueue before the feature was enabled.
```

File: test/util/constants.go (hunk 6 above)
Comment (mbobrovskyi) [reply test/util/constants.go]: Done

**Comment by mbobrovskyi** [comment]
/retest

Due to 

```
Get "https://us-central1-docker.pkg.dev/v2/k8s-artifacts-prod/images/e2e-test-images/agnhost/manifests/sha256:1c5d47ecd9c4fca235ec0eeb9af0c39d8dd981ae703805a1f23676a9bf47c3bb": EOF
```

**Comment by mimowo** [comment]
@mbobrovskyi please prepare CP for 0.11

**Comment by mbobrovskyi** [comment]
> @mbobrovskyi please prepare CP for 0.11

#5630.
